### ISSUE TITLE
Consider providing a Flatpak package

### ISSUE THREAD

**Issue by Alexander-Wilms** [texstudio-org/texstudio#10]
I created a manifest for building a cross-distro [Flatpak](https://flatpak.org/) package :
https://github.com/Alexander-Wilms/flathub/tree/texstudio

You can test this by installing flatpak and flatpak-builder, downloading the json file and then running:

flatpak remote-add kde --from https://distribute.kde.org/kderuntime.flatpakrepo
flatpak install kde org.kde.Platform
flatpak install kde org.kde.Sdk
flatpak-builder --repo=texstudio-repo texstudio-build org.texstudio.TeXstudio.json
flatpak remote-add --no-gpg-verify texstudio-repo
flatpak install texstudio-repo org.texstudio.TeXstudio
flatpak run org.texstudio.TeXstudio

Flatpak provides a way to execute commands on the host, mentioned here: https://blogs.gnome.org/chergert/2016/09/16/builder-nightly-flatpak/

I think [this](https://github.com/flatpak/flatpak/blob/master/data/org.freedesktop.Flatpak.xml#L43) method would need to be called [here](https://github.com/texstudio-org/texstudio/blob/master/src/buildmanager.cpp#L1619) using Qt D-Bus.

LanguageTool has yet to be added as well.

---

This was the original feature request: https://sourceforge.net/p/texstudio/feature-requests/1247/

**Comment by Alexander-Wilms** [comment]
`Tools > Open Terminal` doesn't work either: `Unable to detect a terminal application`

```
flatpak run --devel --command=sh org.texstudio.TeXstudio                  
sh-4.3$ which konsole                                                                           
which: no konsole in (/app/bin:/usr/bin)
```

**Comment by dsboger** [comment]
The current manifest uses `--allow=devel` to permit issuing the document compilation commands. Unfortunately, that breaks the sandbox, so it should be avoided for non-development tools. Would it be possible to include TeXlive as a module of TeXstudio, or maybe as a flatpak runtime/extension? This way the flatpak would not need that option. It would certainly inflate the size of the package considerably, but TeXlive would not be needed on the host, in most cases.

**Comment by Alexander-Wilms** [comment]
In the original issue on Sourceforge, this was discussed. The main reason for using the distro's Tex Live packages was that it's updated almost daily.

I guess bundling TeXlive wouldn't cause too much bloat since people probably won't use several LaTeX editors at the same time.

Back when I tried adding it as a module, I encountered an error with mktexfmt, so I'd appreciate some help with that.

**Comment by Alexander-Wilms** [comment]
I tried to use [these](http://www.linuxfromscratch.org/blfs/view/svn/pst/texlive.html) build instructions, 
but it currently fails with

```
Can't locate mktexlsr.pl in @INC (@INC contains: //tlpkg //texmf-dist/scripts/texlive /etc/perl /usr/lib/perl/site_perl/5.22.1/ /usr/lib/perl/site_perl/5.22.1 /usr/lib/perl/vendor_perl/5.22.1/ /usr/lib/perl/vendor_perl/5.22.1 /usr/lib/perl/5.22.1/ /usr/lib/perl/5.22.1 /usr/local/lib/site_perl /usr/lib/perl/5.22.1 .) at /app/bin/fmtutil line 23.
BEGIN failed--compilation aborted at /app/bin/fmtutil line 25
```

<details>
  <summary>Click to expand</summary>
{
	"app-id": "org.texstudio.TeXstudio",
	"runtime": "org.kde.Sdk",
	"runtime-version": "5.9",
	"sdk": "org.kde.Sdk",
	"command": "texstudio",
	"rename-icon": "texstudio",
	"rename-appdata-file": "texstudio.appdata.xml",
	"rename-desktop-file": "texstudio.desktop",
	"finish-args":[
		"--socket=x11",
		"--share=ipc",
		"--device=dri",
		"--socket=wayland",
		"--share=network",
		"--filesystem=home"
	],
	"build-options" : {
		"cflags": "-O2",
		"cxxflags": "-O2",
		"env": {
			"LD_LIBRARY_PATH": "/app/lib:/app/lib64"
		}
	},
	"modules": [
			{
			"name": "texlive-texmf",
			"buildsystem": "simple",
			"sources": [
				{
					"type": "archive",
					"path": "texlive-20170524-texmf.tar.xz",
					"sha256": "3f63708b77f8615ec6f2f7c93259c5f584d1b89dd335a28f2362aef9e6f0c9ec"
				}
			],
			"build-commands": [
				"cp -R . /app"
			]
		},
		{
			"name": "libxmu",
			"buildsystem": "autotools",
			"sources": [
				{
					"type": "archive",
					"url": "http://xorg.freedesktop.org/releases/individual/lib/libXmu-1.1.2.tar.bz2",
					"sha256": "756edc7c383254eef8b4e1b733c3bf1dc061b523c9f9833ac7058378b8349d0b"
				}
			]
		},
		{
			"name": "libxaw",
			"buildsystem": "autotools",
			"sources": [
				{
					"type": "archive",
					"url": "http://xorg.freedesktop.org/releases/individual/lib/libXaw-1.0.13.tar.bz2",
					"sha256": "8ef8067312571292ccc2bbe94c41109dcf022ea5a4ec71656a83d8cce9edb0cd"
				}
			]
		},
		{
			"name": "openjpeg",
			"buildsystem": "cmake",
			"sources": [
				{
					"type": "archive",
					"url": "https://github.com/uclouvain/openjpeg/archive/v2.3.0.tar.gz",
					"sha256": "3dc787c1bb6023ba846c2a0d9b1f6e179f1cd255172bde9eb75b01f1e6c7d71a"
				}
			]
		},
		{
			"name": "poppler",
			"buildsystem": "cmake",
			"config-opts": [
				"-DCMAKE_BUILD_TYPE=release",
				"-DENABLE_QT5:BOOL=true",
				"-DCMAKE_INSTALL_LIBDIR:PATH=/app/lib"
			],
			"sources": [
				{
					"type": "archive",
					"url": "https://poppler.freedesktop.org/poppler-0.62.0.tar.xz",
					"sha256": "5b9a73dfd4d6f61d165ada1e4f0abd2d420494bf9d0b1c15d0db3f7b83a729c6"
				}
			]
		},
		{
			"name": "texlive-source",
			"buildsystem": "simple",
			"sources": [
				{
					"type": "archive",
					"path": "texlive-20170524-source.tar.xz",
					"sha256": "0161695304e941334dc0b3b5dabcf8edf46c09b7bc33eea8229b5ead7ccfb2aa"
				}
			],
			"build-commands": [
				"mkdir build && \
				cd build && \
				../configure --disable-native-texlive-build --with-system-fontconfig --with-system-libgs --with-system-zlib --disable-static --enable-shared --prefix=/app && \
				make && \
				make install-strip && \
				ldconfig && \
				make texlinks && \
				make install && \
				mktexlsr && \
				fmtutil-sys --all && \
				mtxrun --generate"
			]
		},
		{
			"name" : "konsole",
			"buildsystem" : "cmake-ninja",
			"sources" : [
				{
					"url" : "git://anongit.kde.org/konsole.git",
					"commit" : "595f9fdc1d31e8ce7fa39c6c3175bdda1a6c9821",
					"type" : "git"
				}
			]
		},
		{
			"name": "texstudio",
			"buildsystem": "qmake",
			"cleanup-platform": ["/bin", "/mkspecs"],
			"sources": [
				{
					"type":"archive",
					"url": "https://github.com/texstudio-org/texstudio/archive/2.12.8.tar.gz",
					"sha256": "3dec30ded3f36bb0591f8ed1b78b86fa23f276f5744925bc91075715c3f58062"
				}
			]
		}
	]
}
</details>

**Comment by Alexander-Wilms** [comment]
Using the install-tl script, I was able to bundle TeX Live and compile a PDF with pdflatex, but only without `-interaction=nonstopmode`. Otherwise I get these errors:

```
sh-4.3$ "pdftex" -synctex=1 -interaction=nonstopmode "test".tex
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017) (preloaded format=pdftex)
 restricted \write18 enabled.
entering extended mode
(./test.tex
! Undefined control sequence.
l.1 \documentclass
                  []{article}
! Undefined control sequence.
l.4 \title
          {}
! Undefined control sequence.
l.5 \author
           {}
! Undefined control sequence.
l.7 \begin
          {document}
! Undefined control sequence.
l.9 \maketitle
              
! Undefined control sequence.
l.11 \begin
           {abstract}
[1{/app/texmf-var/fonts/map/pdftex/updmap/pdftex.map}] )
(see the transcript file for additional information)</app/texmf-dist/fonts/type
1/public/amsfonts/cm/cmr10.pfb>
```

lualatex throws this error, though: https://github.com/sharelatex/sharelatex/issues/450

**Comment by Alexander-Wilms** [comment]
The lualatex error can be fixed like [this](https://bugzilla.novell.com/show_bug.cgi?id=847102#c17): 

```
mkdir ~/.tex
export TEXMFCACHE=/home/username/.tex
```

![screenshot](https://user-images.githubusercontent.com/3226457/36630878-f7a490b2-196d-11e8-8bc4-8e2520cb8f1c.png)

I encountered [this](https://tex.stackexchange.com/questions/301739/package-xparse-continues-to-throw-support-package-l3kernel-too-old/301773) problem with the l3kernel package, but that appears to be unrelated to packaging TeX Live as a Flatpak.

**Comment by dsboger** [comment]
Is your WIP manifest available somewhere? I would like to test and maybe get some insight to be able to help.

**Comment by Alexander-Wilms** [comment]
It's here: https://github.com/Alexander-Wilms/flathub/blob/texstudio/org.texstudio.TeXstudio.json

However, flatpak-builder has no network access during the build stage, so I had to rsync the TeX Live repo and put it in an archive. AN alternative might be downloading the iso and extracting that.

**Comment by Murmele** [comment]
Is it possible to add it to the flathub repository?

**Comment by Alexander-Wilms** [comment]
Once the errors are resolved, yes.

**Comment by Alexander-Wilms** [comment]
I've now installed TeXlive from the .iso and it works flawlessly so far. I'll probably submit TeXstudio to Flathub later today. @sunderme and @timhoffm , would you be interested in having push access to the Flathub repo?

**Comment by timhoffm** [comment]
@Alexander-Wilms thanks for working on this. I'm currently quite tight and won't have time to look into this. I may come back to you later.

**Comment by Alexander-Wilms** [comment]
I tried building TeXstudio with the Kde Sdk 5.10, but got a whole lot of these errors, for all of QStringView's member functions:

```
In file included from /usr/include/QtCore/qstring.h:54:0,
                 from /usr/include/QtCore/qobject.h:47,
                 from /usr/include/QtCore/QObject:1,
                 from src/modifiedQObject.h:39,
                 from src/mostQtHeaders.h:12,
                 from src/aboutdialog.h:15,
                 from src/aboutdialog.cpp:12:
/usr/include/QtCore/qstringview.h: In member function ‘constexpr QStringView QStringView::chopped(qsizetype) const’:
/usr/include/QtCore/qstringview.h:244:87: error: expression ‘((n < 0ll) ? txs_assert(((const char*)"n >= 0"), ((const char*)"/usr/include/QtCore/qstringview.h"), 244) : qt_noop())’ is not a constant-expression
     { return Q_ASSERT(n >= 0), Q_ASSERT(n <= size()), QStringView(m_data, m_size - n); }
                                                                                       ^
```

This seems to be a similar issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=896457

**Comment by benibela** [comment]
That is an kde/qt internal issue, only they can fix it.

We do not even use [QStringView](https://github.com/texstudio-org/texstudio/search?utf8=%E2%9C%93&q=qstringview&type=)

**Comment by Alexander-Wilms** [comment]
Alright, I'm using the KDE 5.9 Sdk for now. Maybe it won't occur with 5.11.

**Comment by Alexander-Wilms** [comment]
Closing, since it's now available here: https://flathub.org/apps/details/org.texstudio.TeXstudio

**Comment by Alexander-Wilms** [comment]
@timhoffm There's now an easier way to spawn processes on the host by running 'flatpak-spawn --host'. This way, TeX Live doesn't have to be bundled and only openjpeg, poppler, konsole and TeXstudio need to be built. Do you have time to look into this now?

**Comment by timhoffm** [comment]
> Do you have time to look into this now?

Unfortunately not.

**Comment by AlbertoFabbri93** [comment]
I found a version of TeXstudio on FlatHub but it is 1 year old... is FlatHub an officially supported way of installing TeXstudio or not?

**Comment by sunderme** [comment]
it is not.

**Comment by AlbertoFabbri93** [comment]
Ok thanks, do you plan on supporting it in the foreseeable future?

**Comment by sunderme** [comment]
no. "official" builds are done via github actions and a ppa for ubuntu.
If someone wants to step up, that is fine with me, but I am not extending build targets.

**Comment by sunderme** [comment]
by the way, the above mentioned manifest seems to be current, flathub is behind though.

**Comment by Alexander-Wilms** [comment]
The version on Flathub is 4.5.2:
https://github.com/flathub/org.texstudio.TeXstudio/blob/master/org.texstudio.TeXstudio.yaml#L100

It's just that the metainfo file is not up to date:
https://github.com/texstudio-org/texstudio/blob/master/utilities/texstudio.metainfo.xml#L49

I had created a script in texstudio-meta that updates the file, but for some reason, it doesn't get run anymore:
https://github.com/texstudio-org/texstudio-meta/blob/master/changelog2metainfo.sh

**Comment by sunderme** [comment]
the release script is not used anymore.

I don't know the flow on flathub, but as it is basically only a conversion of CHANGELOG.md, you can't run the script prior to upload on your side/ in the build script ?
