### ISSUE TITLE
Newly added "config_terminal.svg" may contain error

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#1000]
The newly added [`config_terminal.svg`](https://github.com/texstudio-org/texstudio/blob/master/images-ng/config_terminal.svg) cannot be previewed on GitHub, while other svg files can. For example, [`annotation_text.svg`](https://github.com/texstudio-org/texstudio/blob/master/images-ng/annotation_text.svg).

When opened locally by Chrome 80.0.3987.149, it shows 

> This page contains the following errors:
error on line 5 at column 40: `xmlns:ns: '&#38;#38;#38;ns_vars;'` is not a valid URI
error on line 6 at column 37: `xmlns:i: '&#38;#38;#38;ns_ai;'` is not a valid URI
Below is a rendering of the page up to the first error.

**Comment by axkibe** [comment]
Issue 1000 extremely important :) pull request #1002

In core either an inkscape or a github issue, I just fixed the symptom not the cause.
