### ISSUE TITLE
Missing shortcuts

### ISSUE THREAD

**Issue by melsophos** [texstudio-org/texstudio#1005]
I have the impression that it is not possible to update the shortcuts associated to the "Go to previous/next error". From the configuration file, I found that they are associated to `main/edit2/goto/errorprev~0` and `main/edit2/goto/errornext~0`, but there is no such shortcut in the menu (see attached image).

### Environment

- TeXstudio: 2.12.22
- Qt: 5.13.2
- OS: Fedora 31

![missing_goto_error_shortcut](https://user-images.githubusercontent.com/168402/77636498-80f99e00-6f54-11ea-9bc3-a263887acbcc.png)

**Comment by muzimuzhi** [comment]
Find them under `Menus -> Idefix -> Goto`
![image](https://user-images.githubusercontent.com/6376638/77689881-691a2c80-6fdd-11ea-89ea-a3978a05f462.png)

**Comment by melsophos** [comment]
Thanks, I overlooked it despite having searched for some time.
