### ISSUE TITLE
How to type LaTeX documents very fast

### ISSUE THREAD

**Issue by maikol-solis** [texstudio-org/texstudio#1007]
### Environment
- TeXstudio: 2.12.22
- Qt:  5.9.7
- OS: Linux (OpenSUSE 15.1)
- TeX distribution: texlive

### Question

Is it possible to type similar to this guy (https://castel.dev/post/lecture-notes-1/) with TXS? 

Does anyone have tried this with macros?

**Comment by axkibe** [comment]
Nothing will beat vim :p

**Comment by sunderme** [comment]
but the snippets are about what you can do with macros.
apart from that command completion works pretty well , so the special \begin{document}... snippet is not necessary, you can use env completion instead.
So, I don't see a point to change anything

**Comment by maikol-solis** [comment]
Thanks for your answer.

 I know how to use at a very basic level the macros in TXS, but how to do with complex instructions like this "smart fractions"

// | → | \frac{}{}
-- | -- | --
3/ | → | \frac{3}{}
4\pi^2/ | → | \frac{4\pi^2}{}
(1 + 2 + 3)/ | → | \frac{1 + 2 + 3}{}
(1+(2+3)/) | → | (1 + \frac{2+3}{})
(1 + (2+3))/ | → | \frac{1 + (2+3)}{}

![](https://castel.dev/3f83f1bdc3078aa16382e80a276f199f/frac.gif)

Or that ones 

phat → \hat{p} and zbar → \overline{z}

Thanks.

**Comment by sunderme** [comment]
you can try to find something close here: https://github.com/texstudio-org/texstudio/wiki/Scripts

**Comment by maikol-solis** [comment]
Excellent! I tried my first complex macros. 

The only thing that I need to know is how to trigger them only in a math context. I guess that this is a very though question. 

In any case, I will continue creating more and see if I could type very fast with TXS. 

```
{
    "abbrev": "",
    "description": [
        ""
    ],
    "formatVersion": 1,
    "menu": "fast latex",
    "name": "fraction",
    "shortcut": "",
    "tag": [
        "%SCRIPT",
        "env = triggerMatches[1]",
        "txt = \"\\\\frac{\"+env+\"}{}\"",
        "cursor.insertText(txt)",
        "cursor.movePosition(1, cursorEnums.PreviousCharacter)"
    ],
    "trigger": "((\\d+)|(\\d*)(\\\\)?([A-Za-z]+)((\\^|_)(\\{\\d+\\}|\\d))*)/"
}
```


```
{
    "abbrev": "",
    "description": [
        ""
    ],
    "formatVersion": 1,
    "menu": "fast latex",
    "name": "bar",
    "shortcut": "",
    "tag": [
        "%SCRIPT",
        "env = triggerMatches[1]",
        "txt = \"\\\\overline{\"+env+\"}\"",
        "cursor.insertText(txt)"
    ],
    "trigger": "([a-zA-Z])bar"
}

``
