### ISSUE TITLE
TERMINAL does not build on travis

### ISSUE THREAD

**Issue by sunderme** [texstudio-org/texstudio#1008]
Terminal support does not build on travis-ci, see https://travis-ci.org/github/texstudio-org/texstudio/jobs/667383301?utm_medium=notification&utm_source=github_status

### Environment
- TeXstudio: HEAD
- Qt: 
- OS: ubuntu 16.04
- TeX distribution: N/A

**Comment by axkibe** [comment]
Probably a tool old version of the qtermwidget library not supporting setTerminalSizeHint.
Which is absolutely not essential, the size hints are IMO just undesirable in the case of TexStudio
Unfortunately I don't a way to #ifdef for the library versions or even the existence of this member function.

**Comment by sunderme** [comment]
there are ways to detect version with pkg-config (see has_poppler32).
However that seems not to work properly with qtermwidget ...

**Comment by MeanSquaredError** [comment]
`qtermwidget` does not provide the corresponding `.pc` file, so `pkg-config` does not work with it indeed.

I think that the easiest workaround would be to drop the autodetection of `qtermwidget` and just expect the user to specify the `TERMINAL` build option if he needs the terminal in TXS.

Another more complex workaround would be to use `qtCompileTest()` as described here
https://stackoverflow.com/a/44011108

**Comment by sunderme** [comment]
hmmm, on ubuntu: '/usr/lib/x86_64-linux-gnu/pkgconfig/qtermwidget5.pc'

**Comment by MeanSquaredError** [comment]
on Fedora 31 it does not have the `.pc` file:
```
root@localhost:~# rpm -ql qtermwidget | grep -Ei '\.pc'
root@localhost:~# 
```
Do you mean that `pkg-config --print-provides qtermwidget5` does not work on the Travis-CI server but works on your development machine?

In the latter case maybe the Travis-CI server has a qtermwidget package without the `.pc` file?

**Comment by sunderme** [comment]
Pkg-config -print-provides works fine (here and on travis)
--atleast-version seems not to work and qmakes existPackage (or similar) does not detect libqtermwidget...

**Comment by MeanSquaredError** [comment]
The Qt documentation says that `packagesExist` uses `pkg-config`, so I cannot test it on my machine because on Fedora the `.pc` file is missing.

Can you check the `Name:` tag inside `/usr/lib/x86_64-linux-gnu/pkgconfig/qtermwidget5.pc` ?
Is the package `Name:` defined as `libqtermwidget` or `qtermwidget5` ?

The `packagesExist` method should check for the same name as in the `Name:` tag.

Actually if you upload the .pc file from your computer, I think I can test it on my computer and see how it will behave here.

**Comment by yan12125** [comment]
Seems Fedora 31 does provide `qtermwidget5.pc` in qtermwidget-devel package [1]. Maybe you didn't install that devel package?

[1] https://src.fedoraproject.org/rpms/qtermwidget/blob/f31/f/qtermwidget.spec#_70

**Comment by MeanSquaredError** [comment]
@yan12125 
You are right. The `qtermwidget-devel` package provides `qtermwidget5.pc`
I will check tomorrow if qmake/packagesExist works on Fedora 31.
