### ISSUE TITLE
[Feature Request] Set resolution of embedded images, autocrop

### ISSUE THREAD

**Issue by mxa** [texstudio-org/texstudio#1009]
LaTeX (and TeXstudio) produce huge PDF files when the source images are in high resolution. They will be embedded in full resolution and blow up the PDF size. My printer gave up on printing some of the resulting files.
It would be desirable to let the user decide on a maximum resolution for PDF compilation, and all images with a higher resolution will automagically resized to the maximum to keep the PDF size small.
Likewise (and more complex to implement) it would be desirable to save output size by cropping the source images for inclusion in the PDF according to the trim of `\includegraphics`.

Workaround for now is to either manually change the resolution of the source images by estimation (not recommended, because you later might want to change the layout to images with a bigger size), or using [ghostscript](https://tex.stackexchange.com/questions/14429/pdftex-reduce-pdf-size-reduce-image-quality)

**Comment by sunderme** [comment]
texstudio is a text editor which simplifies editing latex source files. The compilation is done by latex and this is managed by a completely different set of people. 
For questions concerning latex, please ask tex.stackexchange.com.

**Comment by mxa** [comment]
I'm aware this functionality isn't part of what latex is doing. However, since TeXstudio is a frontend for a whole toolbox of different programs doing specific things, amongst them ghostscript and possibly imagemagick too, this could be somehow scripted into the toolchain of latex compilation just like indexing for the glossary or compiling the references to the bibliography isn't done by latex either.

**Comment by muzimuzhi** [comment]
PS: Inside latex, you can try `\DeclareGraphicsRule` from `graphicx` package and `\epstopdfDeclareGraphicsRule` from `epstopdf` package.
