### ISSUE TITLE
backspace not working in TERMINAL

### ISSUE THREAD

**Issue by sunderme** [texstudio-org/texstudio#1010]
Backspace in qtermwidget seems not to work.
### Environment
- TeXstudio: HEAD
- Qt: 
- OS: Ubuntu 19.10
- TeX distribution: N/A

**Comment by axkibe** [comment]
hmmm...works for me...

Did you assign a shortcut to it?

**Comment by axkibe** [comment]
Just to find out what the issue is, try this patch. This will disable any shortcuts when the terminal has the focus (it may be too much for some people, but just for testing)
```
--- a/src/toolwidgets.cpp
+++ b/src/toolwidgets.cpp
@@ -165,16 +165,8 @@ bool TerminalWidget::eventFilter(QObject *watched, QEvent *event)
 {
        if (event->type() == QEvent::ShortcutOverride) {
                QKeyEvent *keyEvent = static_cast<QKeyEvent*>(event);
-               if (keyEvent->modifiers().testFlag(Qt::ControlModifier)
-                       && ( (keyEvent->key() == 'C')
-                       || (keyEvent->key() == 'D')
-                       || (keyEvent->key() == 'L')
-                       || (keyEvent->key() == 'X')
-                       || (keyEvent->key() == 'Y')
-                       || (keyEvent->key() == 'V') ) ) {
-                       event->accept();
-                       return true;
-               }
+               event->accept();^M
+               return true;^M
        }
        return QWidget::eventFilter(watched, event);
 }
```

**Comment by sunderme** [comment]
no change
furthermore cursor keys are not working either, so for now the terminal is unusable... (ubuntu 19.10)

**Comment by axkibe** [comment]
cursor keys are also working for me... no idea what's going on?

**Comment by axkibe** [comment]
maybe try installing "qterminal" and see if it's working there (this is a standalone demo app basically just of this widget)

**Comment by axkibe** [comment]
Also another approach is to see if disabling the filter code altogether changes things.

**Comment by sunderme** [comment]
as I am using lxqt, qterminal is my standard which is working fine...

a minimal example with termwidget only show the same issue ... strange

**Comment by sunderme** [comment]
okay, the issue comes up when I start txs from qtcreator.
Everything is fine when started directly from cli.
So, not directly related to the code.
