### ISSUE TITLE
Inline preview is centered

### ISSUE THREAD

**Issue by ElieGouzien** [texstudio-org/texstudio#1012]
### Environment
- TeXstudio: 2.12.22
- Qt: 5.12.5
- OS: linux/debian
- TeX distribution: texlive

### Actual behavior
Inline preview is always centered.

### Problem with it
When not wrapping lines, if there is one long line, preview is in the middle of it, most of the time not visible.

### Expected behavior
Maybe adding an option to choose preview position would be enought (left/center/right).

### How to reproduce
1. Deactivate line wrapping in options;
2. type one long line;
3. somewhere else type an equation;
4. preview it.

**Comment by sunderme** [comment]
fixed

**Comment by ElieGouzien** [comment]
Thanks ! You where fast.
