### ISSUE TITLE
Typo: "Spechern" instead of "Speichern" (german)

### ISSUE THREAD

**Issue by N-Olbert** [texstudio-org/texstudio#1016]
### Environment
- TeXstudio: TeXstudio 2.12.16 (git 2.12.16)

![image](https://user-images.githubusercontent.com/45466413/77850301-d5f61800-71d1-11ea-97e6-eb0c1dfcfb61.png)

Note: I think a dot is also missing, because the other options end with a dot.
Also the the text of the buttons is in englisch, i don't know if this is intended.

**Comment by sunderme** [comment]
seems no to be present in current dev. build.
