### ISSUE TITLE
No suggestions of TikZ libraries

### ISSUE THREAD

**Issue by tmelorc** [texstudio-org/texstudio#1018]
### Environment
- TeXstudio: TeXstudio 3.00.00 
- Qt: Using Qt Version 5.11.1, compiled with Qt 5.11.1 R
- OS: Linux Mint 18
- TeX distribution: pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019)

### Expected behavior
With `tikz` package loaded, a list of all TikZ libraries should  be suggested.

Below, the image from my previous txs. Since the `shapes.geometry` should be changed to `shapes.geometric`, I decided to download from Git the last version of txs and compile it again. 

After that, there is no suggestions anymore. 

![Seleção_204](https://user-images.githubusercontent.com/15181573/77953841-1b831580-72a4-11ea-9345-d71903e68c05.png)

### Actual behavior
The list is empty when trying to insert a TikZ library.

Should I delete something in my system or local folder?

**Comment by sunderme** [comment]
fixed

**Comment by tmelorc** [comment]
> fixed

Ow, really? Can I download the source and compile it again just now?

**Comment by tmelorc** [comment]
> fixed

Oh, thanks a lot. I saw the fixed code, so simple. It works now. Regards.
