### ISSUE TITLE
texstudio crash after using option filter

### ISSUE THREAD

**Issue by fg-dev** [texstudio-org/texstudio#1019]
When I  try to filter option in the configure TeXstudio window, the app crashes.

### Environment
- TeXstudio: 3.00.00 (git 3.0.0alpha2-34-gad302ef)
- Qt: 5.12.1, compiled with Qt 5.12.1 R
- OS: Windows 10 64bit
- TeX distribution: miktex

### Expected behavior

Filter the option according to the typed letters.
### Actual behavior

crash and the app window close.

### How to reproduce
open configure TeXstudio and type a letter in option filter.

**Comment by sunderme** [comment]
works fine on linux and windows here...
Have you tried reinstall ? removing texstudio.ini ?

**Comment by fg-dev** [comment]
I deleted the texstudio.ini file however the problem still persists
for the installation, I am using the portable file.

**Comment by MeanSquaredError** [comment]
I tested it on Windows 7 and it did crash indeed. I will try to prepare a fix shortly.

**Comment by fg-dev** [comment]
> I tested it on Windows 7 and it did crash indeed. I will try to prepare a fix shortly.

thank you.
