### ISSUE TITLE
wrong symbols in the left panel

### ISSUE THREAD

**Issue by guanghwang** [texstudio-org/texstudio#102]
The left panel does not display symbols correctly. 

### Environment
- TeXstudio: 
TeXstudio 2.12.8
- Qt: 
5.6.1
- OS: 
Linux Deepin
- TeX distribution: 
 texlive

### Expected behavior
display correct symobls

### Actual behavior
some random symbols.

### How to reproduce
Open texstudio, click the symbols bottom on the left panel

![image](https://user-images.githubusercontent.com/12839553/38458416-1f95c324-3a6c-11e8-9305-efe379915129.png)

PS: The QT4 version display correct symbols.

**Comment by sunderme** [comment]
what install file did you use ?
Please state the version number in the about dialog.

**Comment by guanghwang** [comment]
Here is from the about dialog

TeXstudio 2.12.8 (hg n/a)
Using Qt Version 5.6.1, compiled with Qt 5.3.2 R

**Comment by timhoffm** [comment]
This appears not to be an official release. Did you compile TeXstudio yourself? If not, where did you get it from?

**Comment by guanghwang** [comment]
I downloaded it from the official website. I use Debian 8.0 amd 64 qt5 version. Here is the download link.

http://download.opensuse.org/repositories/home:/jsundermeyer/Debian_8.0/amd64/texstudio_2.12.8-1+18.1_amd64.deb

**Comment by timhoffm** [comment]
@sunderme do the linux files not access the git revision?

**Comment by sunderme** [comment]
the linux builds can‘t use git

**Comment by sunderme** [comment]
no possibility to debug, use qt4 version
