### ISSUE TITLE
Question: Can TeXstudio be installed on Windows 10 without administrative privilege?

### ISSUE THREAD

**Issue by Jwolter0** [texstudio-org/texstudio#1024]
I have not downloaded the software yet, and before I do the IT folks in my organization want to know whether I will need administrator privilege to install it. If there are other privileges needed, have they been compiled into a list?

### Environment
- TeXstudio: 2.12.22
- OS: Windows 10

**Comment by timhoffm** [comment]
I don't think the installer needs priviledges. Anyway, you can also use the portable version, which does not need installation at all. It can be unpacked to any directory and be used from there. It will not do any modifcations to the system outside that directory.
