### ISSUE TITLE
Ransomware behavior detected

### ISSUE THREAD

**Issue by foreachthing** [texstudio-org/texstudio#1029]
### Environment
- TeXstudio: 3.0 alpha 3
- Qt: 5
- OS: Windows 10
- TeX distribution: miktex

### Behavior
Just wanted go give 3a3 a try and Bitdefender did this:

> Ransomware behavior detected
> now
> 
> Feature:
> Ransomware Remediation
> 
> The process C:\Users\USERNAME\Desktop\txs_3a3\texstudio.exe manifests ransomware behavior and was blocked. Several files were encrypted by it and we couldn't automatically restore all of them. You can find the files to be restored below.

![image](https://user-images.githubusercontent.com/10420187/78509545-f05e6180-778e-11ea-856c-3c55924be345.png)

and also this:
![image](https://user-images.githubusercontent.com/10420187/78509577-3ca9a180-778f-11ea-9a6f-fab652b9dbbe.png)

**Comment by timhoffm** [comment]
Where did you download TeXstudio from?

**Comment by sunderme** [comment]
I have deleted the windows build, just in case.

**Comment by timhoffm** [comment]
@sunderme do you still have a copy of that file so that we could check it?

**Comment by sunderme** [comment]
yes, I do. Do you want it ?

**Comment by sunderme** [comment]
I have removed all builds.
I have uploaded texstudio.exe to virustotal amd also the installer.
There were no warning on the installer and one on the exe.
Probably best to check in more details tomorrow...

**Comment by timhoffm** [comment]
@sunderme No, I don't need the exe right now. I would also just have uploaded it to virustotal for a quick check. Thanks for the quick action!

**Comment by sunderme** [comment]
@foreachthing can you generate a hash of your texstudio.exe ? MD5 or sha256 ?

**Comment by foreachthing** [comment]
I got it from here (its gone now):
https://github.com/texstudio-org/texstudio/releases/tag/3.0.0alpha3

Here are the checksums (made with TotalCommder 9.51):
MD5: `ede8df8b400b47e1c1f854c48496893f *texstudio.exe`
SHA256: `53fec1c3dc5dde2337a963a9a6d649335e8d32f0a96f89f61a04856a02fc7e3a *texstudio.exe`
SHA3_512: `c53dc1b6b22dca861ab948283853c9c6af05110a80b5831956c94e5f393a0e0d1cd8b4b9647342ad74974ed983f04ee381363c507ef1458109d09fcda35dfb2d *texstudio.exe`

Maybe it's just a false-positive...

**Comment by MeanSquaredError** [comment]
I downloaded and installed the latest Windows installer (non-portable) on the 1st of April. Seems OK to me so far. In case anyone wants to double-check it, I have uploaded a .zip of the installed program in `c:\Program Files (x86)\texstudio\`

https://gofile.io/?c=aCkagF

**Comment by sunderme** [comment]
I can't say that the binaries act suspicious in any way.
They start fine, installation works. No excessive writing (though in a virtual machine)...

**Comment by sunderme** [comment]
virustotal also does not find anything (portable version) ...
I will add a sha256sum check to all binaries in the build chain, to be able to see if the installer were changed between build and upload...

**Comment by MeanSquaredError** [comment]
@foreachthing 
From your screenshot it seems that Bitdefender is triggered by access to `nvdrssel.bin`.
It seems that it is a file where NVidia drivers keep the user profile settings. While I don't know why TXS tries to access that file, I am not surprised that it actually happens. Probably TXS calls some Windows API function which, updates the video driver settings and also updates the NVidia user profile.

Googling a bit for `"nvdrssel.bin" bitdefender` shows that there are other programs that trigger Bitdefender when they try to work with this file, so I guess it is a false alarm indeed.

**Comment by foreachthing** [comment]
> ... it is a false alarm indeed.

And closing.
