### ISSUE TITLE
Add Babel package to new document assistant

### ISSUE THREAD

**Issue by skbormann** [texstudio-org/texstudio#103]
It would be nice if an option/checkbox could be added for the babel package to the new document assistant like it already exists for the beamer presentation assistant.
Or maybe a list of commonly used packages could be added that can be selected for a new document.
Currently, you can select only the AMS, makeidx and graphicx package.

I use the assistant quite often to generate new simple documents. While I could create a template for simple documents or type the necessary commands myself, having more options for the new document assistant would be still more comfortable.

**Comment by sunderme** [comment]
done
