### ISSUE TITLE
Right click in \cite autoselect current word.

### ISSUE THREAD

**Issue by axkibe** [texstudio-org/texstudio#1034]
### Environment
- TeXstudio: TeXstudio 3.00.00 (git 3.0.0alpha1-99-gce659544)
- Qt: 5.11.3, compiled with Qt 5.11.3 D
- OS: Debian Linux, buster 
- TeX distribution: texlive

### Actual behavior

When having following text in a line:
```
bla bla \cite{Paper1, Paper2
```
and you put the mouse cursor at the end, and right click to select "Paste" to add another, it will autoselect "Paper2" and thus overwrite it.

This is circumventable by disabling "Inline Checking -> Citations" in the settings. However, I think it should work with it enabled.

### Expected behavior

Just keep the last selection as it was, or keep none selected as it was, when right clicking into a \cite Also when inline checking citations is enabled.

### How to reproduce

See Actual behavior

**Comment by sunderme** [comment]
Paper2 is marked as incorrect/unknown bibitem ?

**Comment by axkibe** [comment]
It is auto-selected on right click...  something you really don't want, if you want to use the right context menu to select "paste" from it.

Yes I know there i Ctrl+V... some people like to use it the other way tough.

**Comment by sunderme** [comment]
in my case, it is only auto-selected if it is not a valid citation id.

apart from that, what do you do to put the comma in, to separate the new entry from the last ?

**Comment by axkibe** [comment]
Well it's not me personally (I'm personally using Ctrl+C/Ctrl+V anyway), I'm forwarding this issue, some users are just used to do things in a different way.. Anyway, the point is, it should never auto select anything just on right click, no matter if valid, invalid, or comma is there or isn't, because that autoselection it interferes with the context menu that has copy/paste items in it.

Only left clicks should change selections.

**Comment by axkibe** [comment]
Thanks!
