### ISSUE TITLE
Texstudio unresponsive when opening and clicking on OK in the  Configure

### ISSUE THREAD

**Issue by ScyllaHide** [texstudio-org/texstudio#1035]
### Environment
- TeXstudio: texstudio-2.12.22 **Portable**
- Qt: Using Qt Version 5.12.1, compiled with Qt 5.12.1 R
- OS: Windows Pro 10 build 1903 or so!
- TeX distribution: Miktex uptodate! 

### Expected behavior
Well it should open and save settings (Configure Window) quickly and should be responsive (i dont know how to write this down, but i should go into the unresponsive condition)

### Actual behavior
When i open and save settings, texstudio goes for ~20 seconds into not responding. It is like the Gui freezes and windows also displays that "not resonding" state in the window title.
What you click:
Opening: Options --> Configure Texstudio --> (~20s) --> fully usuable.
Saving changes to Configuration: Click Ok --> (~20s) - not repsonsive for me --> after that it works again.

### How to reproduce
Well just do it, it always occurs for me on my system? I dont have an AV installed, but check weekly with online NOD, so the system is clean.

### Compare with TeXstudio 2.12.6 (hg 6632:7777b2b8a906), using Qt Version 5.6.2
The behavior does not occur here.

Thanks in advance
ScyllaHide

**Comment by sunderme** [comment]
not reproducible, neither on linux nor windows

you can try o remove %appdata\textsudio\texstudio.ini
what does %appdata\textsudio\completion\... look like ?

**Comment by ScyllaHide** [comment]
> you can try o remove %appdata\textsudio\texstudio.ini

ok i renamed my ini file and opened texstudio, same behavior.

> what does %appdata\textsudio\completion... look like ?
I am using the portable version of texstudio, but my completion folder has a few user generated cwl files and some newer auto generated, recently created ()like two days ago).
i deleted the autogenerated cwl files, but it is still the same behavior.

Anything else, what i could try?

**Comment by sunderme** [comment]
my only idea was, that the number of cwl files is large and read in may be slow.
Apart from that I am not sure what could slow down the behaviour.

**Comment by ScyllaHide** [comment]
ok i can try to go back one previous version and report back.

Thanks for your help.

**Comment by sunderme** [comment]
not reproducible
