### ISSUE TITLE
macOS 10.15 users cannot open Terminal.app through menu item

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#1037]
### Environment
- TeXstudio: 2.12.22
- Qt: not relevant
- OS: macOS 10.15.4
- TeX distribution: not relevant

### Expected behavior

Click menu `Tools -> Open Terminal`, then `Terminal.app` opens with working directory at path of current opened file.

### Actual behavior

`Terminal.app` is not opened. Nothing happens. This is originally reported in https://github.com/texstudio-org/texstudio/issues/613#issuecomment-612942717 by @rwg3328 .

### Some analysis

Currently, in macOS the menu `Tools -> Open Terminal` calls
https://github.com/texstudio-org/texstudio/blob/9659067de6cea7377a5d53e081a1bfb7bfbd34b5/src/utilssystem_unix.cpp#L8-L10

But since macOS 10.15, `Terminal.app` has moved to `/System/Applications/Utilities/Terminal.app`, see [this answer](https://apple.stackexchange.com/a/376828/367154). I have checked this new path.

 - Is a full path to `Terminal.app` necessary? Since `open -a Terminal` seems sufficient to open the terminal. Otherwise, texstudio need to determine the version of macOS. 
 - It seems `open -b com.apple.terminal` can be used for a path-irrelevant solution.

**Comment by MeanSquaredError** [comment]
If `open -a Terminal` or `open -b com.apple.terminal`, works then I guess we should fix it. So if one of these commands works for you from the command line, then maybe you can just send a PR with the fix ?

**Comment by muzimuzhi** [comment]
Yes both commands works for me. Using `open -a Terminal`, the complied app works as expected. I will send a PR with `open -a Terminal`.
