### ISSUE TITLE
TexStudio Editor Spontaneously Switches from Left to Right Typing to Right to Left

### ISSUE THREAD

**Issue by ZaydH** [texstudio-org/texstudio#104]
**Migrated from the as requested in the forums**

I recently upgraded from TexStudio 2.12.6 to 2.12.8. Immediately after the upgrade, I started getting weird behavior in the editor where sometimes after entering a "\\", the editor would begin writing text "backwards" (i.e., instead of left to right, text would fill in right to left similar to a language like Arabic.)

### Environment
- TeXstudio: TeXstudio 2.12.8 (hg 2.12.8)
- Qt: Using Qt Version 5.10.0, compiled with Qt 5.10.0 R
- OS: OSX 10.13.3 (17D102)
- TeX distribution: texlive 2017

### Expected behavior

Example: I type "\cite" to enter a citation.

### Actual behavior

Example: If I type "\cite" sometimes the editor displays it as "\" -> "\c" -> "\ic" -> "\tic" -> "\etic". I do not know yet what causes it, but moving the cursor via an arrow key and the mouse clears the issue.  I also just observed that when TexStudio enters this erroneous mode, it also starts deleting from right to left.  Hence, if I have entered "\etic" and press "backspace", it will update the text to "\tic" with the cursor between the "\\" and the "t".

### How to reproduce

I do not have a reproducible test case yes.  It seems to spontaneous enter this mode sometimes after entering a backslash "\\".

**Comment by sunderme** [comment]
Duplicate #87
