### ISSUE TITLE
PDF rendered profoundly ugly by internal viewer when Qt scaling is enabled

### ISSUE THREAD

**Issue by skoehler** [texstudio-org/texstudio#1042]
I am using Arch Linux with a 4K screen. In KDE Plasma I configure the screen to have a scaling of 150%. Accordingly, the environment variables are set like this:

````
QT_SCREEN_SCALE_FACTORS=eDP-1=1.5;DP-1=1.5;HDMI-1=1.5;DP-2=1.5;HDMI-2=1.5;
QT_AUTO_SCREEN_SCALE_FACTOR=0
````

However, the integrated PDF viewer renders at the unscaled resolution and then scales the picture up by a factor of 1.5 before it is displayed. Note that a factor of 1.5 is particularly ugly as far as image scaling is concerned. Even though I'm watching a latex generated PDF, it looks like one of those old research papers that had to be scanned because the source material is no longer available.

I am utterly disappointed that this is _still_ an issue.

### Environment
- TeXstudio: 2.12.22-1 as provided by Arch Linux
- Qt: using Qt 5.14.2, compiled with Qt 5.14.0 R
- OS: Arch Linux
- TeX distribution: texlive as provided by Arch

### Expected behavior
Render the PDF at the actual pixel resolution, disable any scaling that Qt performs.

### Actual behavior
The PDF is rendered and then scaled up by a factor of 1.5

### How to reproduce
You can probably reproduce this just by setting the Qt environment variables as above for your system. Need that `QT_SCREEN_SCALE_FACTORS` contains the names of the screen connectors as listed by the `xrandr` command.

**Comment by sunderme** [comment]
I am not sure that your approach is productive.
It tells qt to scale all content by 1.5 after it has been produced by the program. Documentation even warns that non-integer scaling factors lead to ugly results (https://doc.qt.io/qt-5/highdpi.html).
txs is dpi aware. I am not sure why there seems to be a movement to reinvent the wheel on display managers as they have been dpi aware for years.

Using .Xresources/.Xdefaults with 
'
!! Xft settings help the problem with small font in google chromium tabs! 
!! Xft.dpi: 96  is the setting that makes the tab font larger 
Xft.dpi: 144
Xft.antialias: true 
Xft.rgba: rgb 
Xft.hinting: true 
Xft.hintstyle: hintslight 
'
works well. (lxqt)

**Comment by skoehler** [comment]
That's not "my" approach, that's the approach of KDE Plasma. I am not manually setting the scaling via some tweaks of environment variables. I am setting the 150% scaling through the KDE Plasma system settings which warns about certain ratios - but 150% is fine with KDE Plasma and a pretty standard ratio, even on other platforms like Windows. Your link (https://doc.qt.io/qt-5/highdpi.html) even mentions this case.

Other PDF viewers (like okular, which is also Qt based, I presume) do not have issues.

Also, do you want me to try a scaling of 200%? Because, I would assume that the result is still somewhat ugly - even if it is less ugly - because I will basically see a pixel image scaled by a factor of 2.

I have not looked into the source of texstudio, but from my experience I would conclude that you currently do not take any measures to render at the proper resolution if QT Scaling is enabled. However, that is standard for KDE Plasma user with a highspi screen.

I would claim that the KDE developers know best (or at least better than me) how to configure Qt for proper scaling. I believe that DPI based tweaks scale fonts but not icons or toolbars and whatnot. That would be unacceptable for people using laptops that run at 200% scaling or above, for example.

**Comment by sunderme** [comment]
should be fine with dev version
