### ISSUE TITLE
[3.0.0alpha3] Color scheme not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by lwbaqueros** [texstudio-org/texstudio#1043]
I install compile `3.0.0alpha3` on Ubuntu 20.04 with `TeX 3.14159265 (TeX Live 2019/Debian)`.

When I selected `Color scheme` `Modern - dark,` or `Modern `I have the result of the picture. I have the Ubuntu window color set as Dark (as it shows in the pdf viewr area in teh pic).

Am I doing something wrong? I want to have a full dark Texstudio. 

PD: Thanks for this wonderful rocket. 

![Screenshot from 2020-04-19 01-28-58](https://user-images.githubusercontent.com/46763074/79673931-8d34ec00-81de-11ea-9147-509a3db34695.png)

**Comment by sunderme** [comment]
It is not clear what color scheme you have chosen in Settings/Appearance
Modern-dark on its own relies that the window color are set by the display manager accordingly (restart may be required), it basically changes some icons and the syntax highlighting.
It the display manager does not provide correct color information, you should check option/use own color scheme which basically ignores display manager settings and uses txs colors.

**Comment by lwbaqueros** [comment]
I noticed as you mention to mark the option `Ignore Most System Colors` and it works fine.

![solution1](https://user-images.githubusercontent.com/46763074/79684639-56d58c00-8233-11ea-9499-8721926dd05f.png)

Then I got this:

![solution2](https://user-images.githubusercontent.com/46763074/79684757-23473180-8234-11ea-9c9b-880722a9af35.png)

![Uploading solution2.png…]()
