### ISSUE TITLE
Specify separate syntax themes for light/dark mode on macOS

### ISSUE THREAD

**Issue by crstnbr** [texstudio-org/texstudio#1048]
By adjusting the `[formats]` section in my `texstudio.ini` I can nicely customise my editors syntax highlighting theme. Is it possible to specify a **separate** theme for dark mode?

Depending on my macOS light/dark mode I want TeXstudio to look like this, respectively:

![Screenshot 2020-04-21 at 11 06 53](https://user-images.githubusercontent.com/187980/79847716-646c4c80-83c0-11ea-952f-ddd519c724b6.png)
![Screenshot 2020-04-21 at 11 07 50](https://user-images.githubusercontent.com/187980/79847730-6a622d80-83c0-11ea-8ae5-8733ec66d96f.png)

Based on [this commit](https://github.com/texstudio-org/texstudio/commit/91a6bed0d835db415b86b360b16dee5921829bda) I thought that perhaps specifying an additional `[formatsDark]` group in the `texstudio.ini` might do the job, but unfortunately that was not the case.

If it's not possible yet: I would love to see this feature!

Best,
Carsten

**Comment by sunderme** [comment]
with the latest development version, formatsDark is used for dark theme and the other for the light theme.
There is no build on github, but you can use the builds from https://bintray.com/sunderme/texstudio

**Comment by crstnbr** [comment]
Oh, great, so my interpretation of the commit was correct. Thanks for the pointer!

**Comment by crstnbr** [comment]
Hm, that doesn't seem to work for me - I now have the latest dev version and two groups `[formats]` and `[formatsDark]` in my texstudio.ini. Any ideas why it's not working?

**Comment by sunderme** [comment]
what exactly does not work ? switching between the two modes requires a restart of the program...

**Comment by crstnbr** [comment]
Well, it just doesn't switch the theme.

![texstudio](https://user-images.githubusercontent.com/187980/79954822-2fbeca80-847e-11ea-9d2e-bfcfbe470da3.gif)

**Comment by sunderme** [comment]
txs does not automatically switch light/darkmode (though it may seem differently)
you need to change options/color scheme to manhattan dark

**Comment by crstnbr** [comment]
So, 1) I can not use the `[formatsDark]` theme with the classic theme and 2) it doesn't automatically switch based on the macOS light/dark mode?

That's very unfortunate. While I can imagine that 2) is not straightforward to implement - I have no clue how hard it is to query the macOS mode - shouldn't it be easy to lift 1)? Are there any plans if/when this will be possible? Of course, I'd love to see both :)

**Comment by sunderme** [comment]
1) is not going to happen as many classic GUI elements don't handle dark color schemes well
2) probably will come if the detection mechanism works.

**Comment by crstnbr** [comment]
Fair enough. However, I'm not sure why the GUI would matter. I only care about the editor's syntax highlighting theme, nothing else. In my video above, the GUI elements already look just fine.

**Comment by sunderme** [comment]
auto detection at start-up is implemented in the latest dev
classic mode can also use dark mode though only when system colors are used.

**Comment by crstnbr** [comment]
Awesome, works great. Thank you for adding this (so fast)!
