### ISSUE TITLE
Multi-file search/replace does not automatically write changes to disk.

### ISSUE THREAD

**Issue by jamesrobb** [texstudio-org/texstudio#1049]
When I do a search and replace for text in the entire project, the text replace in the various files is not saved. What I have to do after a search/replace in multiple files is open and manually save each "modified" file. This is cumbersome when there are many tex files I'd like to modify via search/replace.

### Environment
- TeXstudio: 2.12.22
- Qt: 5.14.2
- OS: Manjaro Linux
- TeX distribution: texlive

### Expected behavior
- Search for text in multiple files.
- Enter text to be replaced and click "replace all".
- The appropriate text is replaced in all the corresponding files, and the changes are written to disk.

### Actual behavior
- Search for text in multiple files.
- Enter text to be replaced and click "replace all".
- The appropriate changes are not written to disk. I have to open each file manually, and then save the file (there is an icon next to the file name to denote there are changes to be saved).

### How to reproduce
- Follow the above steps for actual behavior.

**Comment by sunderme** [comment]
fixed
3 options are available:
1) saveAll from file menu
2) compile automatically calls save all
3) exit asks for unsaved hidden documents

**Comment by jamesrobb** [comment]
Thanks for the options, but I'm not sure what you mean by "fixed"? Was some patch applied?

This problem exhibits rather counter-intuitive behavior; someone needs to be explicitly aware that they must use one of these options. Similar functionality in other software doesn't place such a burden on the user.

**Comment by sunderme** [comment]
fixed means that the change is done in the development repository.
option 2&3 make sure that the multi file replace is written on disk unless you deliberately tell txs not to (3).

**Comment by jamesrobb** [comment]
If I understand correctly, a future release will automatically save the files that have had text replaced in them, and the above options are how to deal with it in the mean time?

**Comment by sunderme** [comment]
no, 2.12.22 does not save hidden files (which are the non-visible files with the replacements)
in 2.12.22 you can open a hidden file (e.g. via the structure pane by opening the included files) , and save it manually.
in 3.0.0 (i.e. txs next), the changed hidden hidden files are saved with one of the three options
manually triggered (1)  or automatically when you compile (2) or when you close txs (3). At lastest with closing, the files get saved.
