### ISSUE TITLE
latest windows installer (texstudio-2.12.8-win-qt5.exe) does not install silently

### ISSUE THREAD

**Issue by chanlists** [texstudio-org/texstudio#105]
Even if run with /sp- /verysilent /SUPPRESSMSGBOXES /norestart, a dialog box pops up asking for where to install TeXstudio....

**Comment by Swarheley** [comment]
Installer changed to NSIS. Silent switch is now /S. However, in the uninstaller this does not work for me so far: See: https://github.com/texstudio-org/texstudio/issues/92

**Comment by RoyiAvital** [comment]
Are there release notes for 2.12.8?
