### ISSUE TITLE
Problems with using TeXstudio on iPad via RDP

### ISSUE THREAD

**Issue by DanielFNG** [texstudio-org/texstudio#1054]
Environment
- TeXstudio: TeXstudio 2.12.22 (git 2.12.22)
Using Qt Version 5.12.1, compiled with Qt 5.12.1 R
Windows 10*
TeXLive

*I am using RDP on an iPad to remote in to a Windows 10 PC running TeXMaker. 

### Expected behavior

Can input keys normally. 

### Actual behavior

After making TeXstudio the active window, the first key press is registered correctly. All other keystrokes are registered as that same key. Example: 'abcd' when entered shows as 'aaaa'. Keystrokes are registered normally on other text editors and elsewhere e.g chrome windows.

### How to reproduce

Remote in to a Windows 10 machine with TeXstudio and try to use it as normal. I have only tried from my iPad so not sure if the issue lies with that or just rdp in general.

**Comment by DanielFNG** [comment]
This doesn't happen when using Microsoft's RDP app but does happen on Jump Desktop. Maybe it's a problem on their end.

**Comment by sunderme** [comment]
so, we can close this ?

**Comment by DanielFNG** [comment]
Yes I think so, sorry!
