### ISSUE TITLE
Problem with Polish characters

### ISSUE THREAD

**Issue by thebadan** [texstudio-org/texstudio#1057]
### Environment
- TeXstudio: 2.12.22 (git 2.12.22) Polish version, encoding UTF-8
- Qt: used version Qt 5.12.1, compiled with Qt 5.12.1 R
- OS: Windows 10
- TeX distribution: Miktex 2.9.7200

### Expected behavior
1. Posibility of witing Polish ź when Preview panel (F7) is opened
2. Possiblity to write Polish Ś character using RightAlt+Shift+s (only possible with CapsLock RightAlt+s)
### Actual behavior
1. When Preview panel is open RightAlt+x (ź on Polish keyboard) opens external Acrobat Reader window
2. Npthing happens.
### How to reproduce
1. Change keyboard layout to Polish (programmer).
2. Try to write in texstudio ź (RightAlt+x) character when Preview panel (F7) is opened. The shortcut will  trigger opening external Adobe Acrobat window.
3. Try to write in texstudio Ś (Shift+RightAlt+S) character. Next try with CapsLock RightAlt+s and the character will be shown as should be.

**Comment by sunderme** [comment]
the short cut for external viewer is set to ctrl+alt+x. Windows actually sends ctrl+alt when pressing the right alt-key. You can get rid of the problem by changing the shortcut for "external viewer" to something else (options/shortcuts/pdfviewer/view/external viewer).
As there are many different keyboard layouts, it is impossible to avoid all shortcut collisions ...

**Comment by thebadan** [comment]
"As there are many different keyboard layouts, it is impossible to avoid all shortcut collisions ..."
I am not an expert and I believe you, but this "changes" were probably introduced in the latest version of the texstudio (I use texstudio for about one year and I haven't noticed them before). Please only consider if they were really necessary. Maybe such potentially conflicting shortcuts should not be introduced arbitrary, especially if affecting typing of international symbols in the internationalized version of the software.
Yes, I know that I can change shortcuts, but please don't go this "modern programming way" writing software which gives users possibilty to fly to cosmos, but to write a symbol they have to start from changing configuration. 
I don't want to complain, I really like texstudio and teach students how to use it, but please consider my my point of view on this seemingly trivial problem:
"Dear students, for writing and editing latex files I recommend textstudio. It is very functional, stable and frequently updated program with Polish version. But in order to write Polish ź and Ś in Polish version of the program you need first to delete/change the following shortcuts.... (probably after each program update) and maybe some newly introduced shortcuts in the future versions."

**Comment by sunderme** [comment]
i have removed some shortcuts

**Comment by thebadan** [comment]
Thank you!

**Comment by dbitouze** [comment]
@sunderme 

> i have removed some shortcuts

Which ones?

**Comment by sunderme** [comment]
ctrl+alt+x -> removed , for external viewer
ctrl+shift+alt+s -> ctrl+shift+s , for save all
ctrl+alt+a -> removed , for about dialog (whyever there was a shortcut in the first place)
ctrl+alt+r could be filtered if it collides with a keyboard layout, unfiltered for now

**Comment by muzimuzhi** [comment]
(Related commit: https://github.com/texstudio-org/texstudio/commit/fa2af1310a2f6914169e9bead3afc2c3420b7b0a)
