### ISSUE TITLE
Listing environments are not detected correctly 

### ISSUE THREAD

**Issue by johanneskind** [texstudio-org/texstudio#1059]
### Environment
- TeXstudio: 2.12.22 
- Qt: 5.14.2
- OS: Arch Linux 
- TeX distribution: TeX Live

### Expected behavior
TeXstudio should recognize and accept any `listings` environment at any place in the document. 

### Actual behavior
The package `listings`is imported with `\usepackage{listings}`. After the first `begin{lstlisting} ... \end{lstlisting}` the next environments are not detected correctly and the next `\end{lstlisting}` gets marked as "closing environment which is not opened". 
![Lstlisting](https://user-images.githubusercontent.com/17383992/80477142-bc203000-894b-11ea-849b-797afad5b934.png)

### How to reproduce
Use two `begin{lstlisting} ... \end{lstlisting}` in your document (does not neccessarily need to be directly behind each other).

**Comment by sunderme** [comment]
this is already fixed in the development version

**Comment by johanneskind** [comment]
Thanks for the information! Any idea how I could have known this beforehand?
