### ISSUE TITLE
lstlisting environment disables all autocorrect/autocomplete after usage  

### ISSUE THREAD

**Issue by iisharankov** [texstudio-org/texstudio#1060]
### Environment
- TeXstudio: 2.12.22.1
- Qt: 5.14.2, compiled with Qt 5.14.0 R
- OS: Manjaro KDE
- TeX distribution: texlive

### Expected behavior
autocorrect working before and after lstlisting environment

### Actual behavior
using a lstlisting environment disables any future autocorrect, as well as TexStudio suggestions, including autocomplete on \ref{fig:.....}. I tried reloading the file, editing the preamble, etc., but I can't wrap my head at what's happening here. Issue is on multiple different files tested on.

### How to reproduce
simply create an lstlisting environment (even empty!) and notice how future autocorrect and autocomplete fails to register.

Stackexchange question on issue with photos for guidance/explanation: https://tex.stackexchange.com/questions/539018/lstlisting-diables-autocorrect-after-usage

**Comment by muzimuzhi** [comment]
More specific, in texstudio 2.12.22, a `\label{key-x}` after `lstlisting` environment is not correctly recognized, hence the autocompletion of `\ref` (either before or after `lstlisting` environment) will not contain `key-x`.
 * `verbatim` environment is fine
 * a `\label` before `lstlistings` environment is fine

Tests show that **texstudio 3.0.0 alpha4 is fine.** So this problem might be fixed in the latest development code.

Minimum example:
```tex
\documentclass{article}
\usepackage{listings}

\begin{document}
\begin{lstlisting}
  content
\end{lstlisting}
\label{key}

\end{document}
```

**Comment by sunderme** [comment]
i assume fixed

**Comment by iisharankov** [comment]
Is it? 

I started writing a new documentation manual, and there's been no update. I'm currently using the most updated version, 2.12.22, which is also what my package manager provides (and it's the latest on texstudio.org). 

This bug still exists, and I currently have to comment out all lstlisting environments while writing my documentation in order to have spell checking and auto completion. 

Is there a (more or less) stable alpha that I can use? Or a environment like lstlisting that isn't buggy?

**Comment by sunderme** [comment]
fixes can only appear in builds generated after being reported.
So, try 3.0.0...
