### ISSUE TITLE
Clicking tags/labels in structure leads to program crashing

### ISSUE THREAD

**Issue by BOZHENG001** [texstudio-org/texstudio#1063]
## Environment
- TeXstudio:  2.12.22
- Qt:  5.12.1
- OS:  Windows10
- TeX distribution:  miktex

### Expected behavior
After clicking the tag/label in the structure on the left, it should jump me to that part inside my paper.

### Actual behavior
After clicking the tag/label in the structure on the left, the whole program stops/crashes. I will have to use task manager from Windows10 to shut it down. It happens every time I do this. I have already tried to uninstall and re-install texstudio, but it does not help.

**Comment by sunderme** [comment]
please provide a sample document which shows this behavior

**Comment by BOZHENG001** [comment]
[MDPI_template.zip](https://github.com/texstudio-org/texstudio/files/4557663/MDPI_template.zip)

Thanks for your reply. When I use the template from MDPI, it happens.

**Comment by sunderme** [comment]
what exactly do you mean by "clicking on tag/label in the structure" ? There are no labels in your example ?

**Comment by BOZHENG001** [comment]
![image](https://user-images.githubusercontent.com/50182201/80742417-a2354780-8b1b-11ea-9a32-cb33b0948f94.png)

One the left side of texstudio, usually we have this "structure" window to show sections and subsections of the whole paper. The tag/label I meant is those sections or subsections. When I click them, my texstudio just crashes. But if I dont touch that part, I can work normally with texstudio.

**Comment by sunderme** [comment]
hmmm, works fine here.
clicking on any structure entry ?

**Comment by sunderme** [comment]
crashing ? or freezing ?

**Comment by BOZHENG001** [comment]
Yes, clicking on any structure entry. It freezes first, and after some time, there is no reaction from program, then it crashes. If it works fine there on ur PC, will it be a problem from my laptop or OS?

**Comment by sunderme** [comment]
freezing is difficult to analyze.
txs generates a crash report in case of crash (somewhere in a tmp directory), you could send us these ,if they exist
apart from that, does it happen with an ‚article‘ on a clean texstudio (%appdata%\texstudio removed) ?

**Comment by BOZHENG001** [comment]
I did not find the crash report, but the second suggestion works, now it does not crash anymore. Thanks for your help!

**Comment by Biorix** [comment]
What's exactly was the fix @BOZHENG001? I have the same issue exactly, but I don't see the 'second suggestion'

**Comment by octaeder** [comment]
I think it's this: *%appdata%\texstudio removed*. You may rename the folder for testing if it helps.

**Comment by Biorix** [comment]
OK that's what I thought. I have the issue even though this isn't in the path name
It doesn't always freeze and not with all documents.

**Comment by octaeder** [comment]
I suggest opening a new issue. There you can give details of your environment as asked in the issue.
