### ISSUE TITLE
Packages not found: XCharter // enumitem // flowfram

### ISSUE THREAD

**Issue by Nietzschikus** [texstudio-org/texstudio#1064]
Downloaded a template from http://www.LaTeXTemplates.com (Link: https://www.latextemplates.com/template/wenneker-resume-cv). Texstudio didn´t recoqnize certain commands and as I viewed into the "structure.tex" of the template, certain packages were not found (\usepackage{XCharter} // \usepackage{enumitem} // \usepackage{flowfram}. Hence it could not compile my document. Cannot provide much more infos as I am not expert enough.

### Environment
- TeXstudio: VERSION 2.12.22
- Qt: 5.12.1
- OS: Windows(10)
- TeX distribution: MikTex 2.9

**Comment by sunderme** [comment]
compilation is sole responsibility of miktex. if packages are missing, so need to install them there.

**Comment by Nietzschikus** [comment]
That comment helped, thx. Here is what I did. 

1) went into "C:\Program Files\MiKTeX 2.9\miktex\bin\x64"
2) executed miktex-console as Admin
3) updated MikTex
4) updated Database @ "Packages"
5) search for the packages and installed them manually
