### ISSUE TITLE
How to set whole theme into dark mode

### ISSUE THREAD

**Issue by qiuzhu** [texstudio-org/texstudio#1067]
Texstudio: 2.12
I just set the editor area into dark mode, but it is very contrast with other area:
![image](https://user-images.githubusercontent.com/13781719/80811527-a7b48f80-8bf8-11ea-8bce-dfe424fb63d2.png)

Want to set the final effect like the VScode (one dark mode):
![image](https://user-images.githubusercontent.com/13781719/80811631-dd597880-8bf8-11ea-8706-46d8062b5eb9.png)

is it possible in texstudio has the API to set the whole theme?

**Comment by sunderme** [comment]
you could try txs 3.0.0alpha 4 ...

**Comment by fg-dev** [comment]
> you could try txs 3.0.0alpha 4 ...

is it different from the daily build

**Comment by sunderme** [comment]
Not much, a bit behind

**Comment by qiuzhu** [comment]
> you could try txs 3.0.0alpha 4 ...

I try txs 3.0.0, there is a dark theme mode. but it seems there is no so much enhancement to set the whole app to dark mode like VScode

**Comment by sunderme** [comment]
you have to activate "use own color scheme" plus "manhattan style - dark"
