### ISSUE TITLE
Wrong horizontal scroll direction

### ISSUE THREAD

**Issue by shuxl03** [texstudio-org/texstudio#1068]
### Environment
- TeXstudio: 3.0.0alpha4 
- Qt: 5.14.1 
- OS: macOS 10.15.4 
- TeX distribution: texlive 2020 

### Expected behavior
Using a trackpad and previewing with the internal PDF viewer.
Fingers go up = page down; fingers go right = page left. Consistent with other applications.

### Actual behavior
Fingers go up = page down; fingers go right = page **right**. (and vice versa)
Same results in embedded/windowed mode.

### How to reproduce
Just compile a document, zoom in, and scroll.

**Comment by sunderme** [comment]
if someone with a mac can try to tackle this ?

**Comment by muzimuzhi** [comment]
With macOS 10.15.4, I can confirm that this problem exists for 3.0.0 alpha 2 and 4. Alpha 1 and 2.12.22 work as expected. (3.0.0 alpha 3 did not provide a `.dmg`, so it is not covered.)

**Comment by nik312123** [comment]
If you need to connect with someone with macOS to resolve this issue, feel free to say so below. I would be willing to help in whatever way I can.

**Comment by sunderme** [comment]
just provide a pull-request if you can resolve the issue

**Comment by nik312123** [comment]
This should be closed as per #1178.
