### ISSUE TITLE
Shortcut jumps to next placeholder unexpectedly

### ISSUE THREAD

**Issue by thatlittleboy** [texstudio-org/texstudio#107]
### Environment
- TeXstudio: TeXstudio 2.12.9 (hg 2.12.8-48-g60b98db) 
- Qt: 5.8.0
- OS: Windows 10 
- TeX distribution: Miktex 

### Expected behavior
The cursor to remain on the current placeholder.

### Actual behavior
The cursor jumps to the next placeholder.

![mwe](https://user-images.githubusercontent.com/30731072/38510151-05537144-3c1c-11e8-8996-a1c0c737d4fe.gif)

### How to reproduce
In a new file, perform the key combinations:

1. <kbd>Ctrl</kbd>+<kbd>E</kbd>, type `equation` to get:
```
\begin{equation}
	content
\end{equation}
```

2. <kbd>Ctrl</kbd>+<kbd>Right Arrow</kbd> to jump placeholder to `content`.

3. Type `\sum`, then <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>D</kbd> to invoke subscript shortcut. You should get:
```
\begin{equation}
	\sum_{content}
\end{equation}
```
but the cursor is now on the `\end{equation}` line. I expect the cursor to remain on the `content` line.

This behaviour seems to persist even after clearing placeholders <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>K</kbd>, in the 3rd step after typing `\sum`, but before invoking the subscript shortcut.

**Comment by sunderme** [comment]
fixed in repository
