### ISSUE TITLE
Autogenerated cwl is missing environments created with \specialcomment from comment package

### ISSUE THREAD

**Issue by AbcAeffchen** [texstudio-org/texstudio#1072]
### Environment
- TeXstudio: 2.12.22+debian-1build1
- Qt: 5.12.8
- OS: Ubuntu 20.04
- TeX distribution: texlive

### Expected Behavior
I use `\specialcomment{solution}...` from the comment package to create an environment that I can exclude for certain builds (e.g. solutions in an assignment sheet) using `\excludecomment`.  As for every other regular environment defined in my cls file (works fine), I expect that I get completion for `\begin{solution}`.

I noticed that there is a folder with auto generated cwl files. the cwl for my cls file is missing the solution environment. Probably because it does not take into account that `\specialcomment` also creates such an environment.

### Current Workaround
At the moment I fix this by adding the missing parts to a custom cwl file. So its not a huge problem.

### Side note
The command  `\excludecomment` from the comment package is also not recognized. But all other commands from that package are, as far as I can see.

**Comment by sunderme** [comment]
not sure what the issue at hand is.
Auto generated cwl just provides a list of commands which are not listed as unknown, no functionality of the commands is deduced.
If that is desired, the cwl needs to be adapted manually, see manual.

**Comment by muzimuzhi** [comment]
In texstudio v2.12.22, after `\specialcomment{solution} ...`, I **can** get the autocompletion for `solution` environment.
![image](https://user-images.githubusercontent.com/6376638/81009821-ea3fcb80-8e87-11ea-8808-6cd39a43fc1d.png)

**Comment by AbcAeffchen** [comment]
Wow. Its the same for me when I define `\specialcomment` in the .tex file. But for some reason it seems not to work when defined in the `documentclass`. We use a custom class for our assignments.

Actually I don't get completion for the other environments defined in the custom class, but they are also not marked as unknown/undefined.

**Comment by MeanSquaredError** [comment]
TXS does not load automatically .cwl definitions for the packages included in custom class files.
If you want to load the .cwl definitions for these packages you need to define a custom `.cwl` with the same name as your custom class and then use `#include` statements to include the `.cwl` definitions for these packages.

E.g. assuming that your custom class is called `mycustomclass`, then you need `mycustomclass.cwl` with content like:
```
#include:amssymb
#include:amsthm
#include:hyperref
#include:makecell
#include:mathtools
```
Then you need to place `mycustomclass.cwl` in the cwl directory where TXS will find it. On Fedora it is `$HOME/.config/texstudio/completion/user/`

**Comment by muzimuzhi** [comment]
@MeanSquaredError 
The autogeneration is ok. But there is a typo in `comment.sty`, where the `m` in `\specialcomment` is not doubled. I have opened a pr to fix this (and another minor cwl problem).
