### ISSUE TITLE
Bug: texstudio breaks whenever I use the "LABELS" to find a label.

### ISSUE THREAD

**Issue by xuxy09** [texstudio-org/texstudio#1076]
It seems a quite bad bug with the newest version Texstudio 2.12.22. Whenever I use the "LABELS" in the structure region to find a label, the whole program breaks down. I switched to an older version 2.12.6, and the bug disappears.

**Comment by muzimuzhi** [comment]
That function works as expected in 2.12.22 on my side. Which operation system are you using? Does the problem persist after restoring default settings (by menu item `Options -> Restore default Settings ...`) ? (You can save the setting before restore.)

![image](https://user-images.githubusercontent.com/6376638/81209210-cead0000-9002-11ea-8cc1-6a1e26da7f3b.png)

**Comment by sunderme** [comment]
which OS ? test case ?
There is reason, why there is a template when presenting a new issue ...

**Comment by MeanSquaredError** [comment]
This could be related or a duplicate of https://github.com/texstudio-org/texstudio/issues/1063
Given that the previous issue was resolved by deleting the settings, maybe it is a good idea to get the user's `texstudio.ini` file before he resets his settings.

**Comment by sunderme** [comment]
I guess that rather  a cw is the culprit...

**Comment by sunderme** [comment]
no user feedback
