### ISSUE TITLE
Parse user texmf tree

### ISSUE THREAD

**Issue by jrmoserbaltimore** [texstudio-org/texstudio#1078]
TeXstudio does not provide autocompletion for files located in user texmf tree.  It ignores .cls and .bst files, so its syntax highlighting tells the user all commands defined by additional classes in the ~/texmf user tree are invalid.

Other editors, such as LyX, parse ~/texmf on Windows and Linux.  LyX uses its own format, and I'd rather convert back to TeX.  latex itself uses the ~/texmf tree.  To be compliant as a latex editor, txs needs to recognize and parse `$TEXMFVAR` and `$TEXMFHOME`.

See also #336

**Comment by muzimuzhi** [comment]
`~/texmf` is the default value of texlive's predefined texmf tree `TEXMFHOME`. Running `kpsewhich -var-value=TEXMFHOME` returns the current value of `TEXMFHOME`. 

After some test, I find that texstudio **do generates cwl files for `.cls/.sty` files located in `TEXMFHOME`**. By default, the autogenerated cwl files contain lines ending with `#S`, which means the cwl info is used for syntax checking but not autocompletion. For example, a line `\newcommand\testCmd{}` in file `myclass.cls` corresponds to the line `\testCmd#S` in `myclass.cwl`. 

I use texstudio 2.12.22 in macOS 10.15.4.

------
Here is what I did as a test:
1. Create a `myclass.cls` which defines dummy command and environment, then put it under path `TEXMFHOME/tex/latex`.
2. Create a tex file which loads `myclass`.

```tex
% myclass.cls
\ProvidesClass{myclass}[2020/05/07]
\LoadClass{article}

\RequirePackage{comment}
\newcommand\testCmd{|test|}
\newenvironment{testEnv}{begin code}{end code}
```

```tex
% test-myclass.tex
\documentclass{myclass}
\begin{document}
\testCmd

\begin{testEnv}
  content
\end{testEnv}
\end{document}
```

3. Then in `~/.config/texstudio/completion/autogenerated` I find the autogenerated `myclass.cwl`.
```
% myclass.cwl
# autogenerated by txs
#include:comment
#include:latex-document
#include:tex
\begin{testEnv}#S
\end{testEnv}#S
\testCmd#S
```

4. And here is how texstudio highlights `test-myclass.tex` (I don't know why but you may need to reopen texstudio to have the syntax highlighting taking effect)
![image](https://user-images.githubusercontent.com/6376638/81312042-b7304e80-90b8-11ea-8e08-f6ffa37d8a03.png)

**Comment by sunderme** [comment]
so, the only remaining issue is that automatically generated cwls are only used for syntax check and not for completion ?

**Comment by muzimuzhi** [comment]
> so, the only remaining issue is that automatically generated cwls are only used for syntax check and not for completion ?

If my test is right, yes.

**Comment by sunderme** [comment]
as automatically scanned command name do not contain any context information, I don't see an argument to change current behavior
