### ISSUE TITLE
OSX: Runtime error at commit bf35644: Error: Could not start the command

### ISSUE THREAD

**Issue by KarlMagnusLarsson** [texstudio-org/texstudio#1084]
### Environment
- TeXstudio: commit bf356445ba88fb1ac2d7c7bf7c74fe83d9380167
- Qt: Using Qt Version 5.14.2, compiled with Qt 5.14.2 R
- OSX: 10.13.6
- TeX distribution: Texlive2020

### Expected behavior
The command tools->build&view should build and show the pdf.

### Actual behavior
Error: Could not start the command: ... in messages window, for all configured commands.

### How to reproduce
```
1: git clone https://github.com/texstudio-org/texstudio.git
2: cd texstudio
3: git checkout bf356445ba88fb1
4: qmake texstudio.pro
5: make -j4
6: start texstudio app
7: open any tex source file (thesis.tex in this case)
8: tools->build&view
9: Error: Could not start the command: latexmk -pdf -silent -latexoption="-synctex=1 --shell-escape" "thesis".tex. 
```

I use latexmk, but that is not the issue. At commit bf356445ba88f and newer Texstudio can not find any of the the configured commands. Code before this commit work fine.

Workaround:
The code up to and including commit b7ed544c7f57bbb works fine.

The System report is attached.
[System-Report.txt](https://github.com/texstudio-org/texstudio/files/4617839/System-Report.txt)

**Comment by KarlMagnusLarsson** [comment]
The part of commit bf35644 which cause the runtime error seems to be the changes to  src/execprogram.cpp. If I add the patch below to b7ed544 then it beeaks and I get the runtime error.

```
@@ -56,10 +56,7 @@ void ExecProgram::execAndNoWait(QProcess &proc) const
	qputenv("PATH", pathExtended.toLocal8Bit());
	// If there are no arguments specified separately assume that the program name
	// also contains all the arguments (if any)
	-if (m_arguments.isEmpty()) {
	-       proc.start(m_program);
	-} else {
	-       proc.start(m_program, m_arguments);
	-}
	+  proc.start(m_program, m_arguments);
	qputenv("PATH", pathOrig.toLocal8Bit());
}
```

**Comment by KarlMagnusLarsson** [comment]
Thank you for the commit.

Now, at commit a11fb4d I get another, but similar error in messages :
```
tools->build&view
Process started: latexmk -pdf -silent -latexoption="-synctex=1 --shell-escape" "thesis".tex
env: perl: No such file or directory
Process exited with error(s)
```
I scratched everything rebuilt up to and including b7ed544c, again, and that works for me, so that is a useful fact.

If I take working b7ed544c and patch as below (proper diff command this time and no handwriting...):
```
git diff
diff --git a/src/execprogram.cpp b/src/execprogram.cpp
index 86628894..fb498196 100644
--- a/src/execprogram.cpp
+++ b/src/execprogram.cpp
@@ -56,10 +56,6 @@ void ExecProgram::execAndNoWait(QProcess &proc) const
        qputenv("PATH", pathExtended.toLocal8Bit());
        // If there are no arguments specified separately assume that the program name
        // also contains all the arguments (if any)
-       if (m_arguments.isEmpty()) {
-               proc.start(m_program);
-       } else {
-               proc.start(m_program, m_arguments);
-       }
+       proc.start(m_program, m_arguments);
        qputenv("PATH", pathOrig.toLocal8Bit());
 }
```
Then I recreate the error in the original report at the top of this thread.

**Comment by sunderme** [comment]
probably fixed with last commit

**Comment by KarlMagnusLarsson** [comment]
Yes, 6ab30c7e4ea0ba7e3a9fee6cf52da5596a81d346 works for me.

Thank you.
