### ISSUE TITLE
[3.0.0 alpha4] In align env, align-ampersand (&) is highlighted as math-keyword

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#1085]
### Environment
- TeXstudio: 3.0.0 alpha4
- Qt: Using Qt Version 5.14.1, compiled with Qt 5.14.1 R
- OS: macOS 10.15.4
- TeX distribution: irrelevant

### Expected behavior
In multiline display math environments like `align`, the `&` should be highlighted blue (the color for identifier align-ampersand).

In 2.12.22
![image](https://user-images.githubusercontent.com/6376638/81747957-9c584280-94db-11ea-9b61-e2b506a98707.png)

### Actual behavior
The `&` is highlighted bold and olive (the color for identifier math-keyword).
In 3.0.0 alpha4
![image](https://user-images.githubusercontent.com/6376638/81747912-877baf00-94db-11ea-9991-0afbe2889674.png)

### How to reproduce
Example input:
```tex
\documentclass{article}
\usepackage{amsmath}

\begin{document}
$abc \alpha \text{}$

\begin{align}
	content & b \\
	c       & \begin{aligned}
              content
            \end{aligned}
\end{align}

\begin{tabular}{ll}
  a & b \\
  c & d
\end{tabular}
\end{document}
```

**Comment by MeanSquaredError** [comment]
IIRC there were some changes in 3.0.0 to speed up the syntax highlighting, so maybe the different behavior is related to these changes. From your screenshots it seems that tabular environments are not affected, though.

**Comment by sunderme** [comment]
apart that it is changed behavior, is it bad ?

**Comment by muzimuzhi** [comment]
So long as `&` acts as align character, highlighting `&` consistently in text and math mode tabular like environments is the desired behavior. These environments including `tabular`, `array` and `align`, etc.

**Comment by muzimuzhi** [comment]
Compiled with Qt 5.14.2, this is confirmed to be solved. Thanks.
![image](https://user-images.githubusercontent.com/6376638/82131965-67b2f680-980d-11ea-8f3e-bee33ac4f524.png)
