### ISSUE TITLE
Known Command Does Not Show Up in Completion

### ISSUE THREAD

**Issue by CakeUser321** [texstudio-org/texstudio#1088]
When using the package ``xfrac``, the command ``\sfrac``does not show up in the auto completion list. However it is not marked red, so the command must be known. 

### Environment
- TeXstudio: TeXstudio 2.12.6 (hg 6631:16db084dae24)
- Qt: 5.9.5, compiled with Qt 5.9.3 R
- OS: Linux <computer name> 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- TeX distribution: TexLive 2020

### Expected behavior
`\sfrac` is available in the auto completion.

### Actual behavior
`\sfrac` is *not* available in the auto completion.

### How to reproduce
```
\documentclass[english]{book}
\usepackage{xfrac}

\begin{document}
	\sfrac{1}{2}
\end{document}
```

**Comment by muzimuzhi** [comment]
Currently texstudio does not contain the cwl file for `xfrac` package. And autogenerated cwl files are used for syntax highlighting (not marked red) only, not for autocompletion. See https://github.com/texstudio-org/texstudio/issues/336#issuecomment-425545477.

**Comment by CakeUser321** [comment]
Hello muzimuzhi, thank you for your prompt response! According to https://github.com/texstudio-org/texstudio/issues/336#issuecomment-425545477 the auto completion only works for a package if the corresponding cwl file is stored in `~/.config/texstudio/completion/user`. However on my machine, this directory is empty. Nontheless, auto completion works quite well for most packages (e.g. `FloatBarrier` from `placeins`, although `~/.config/texstudio/completion/user/placeins.cwl` does not exist).

**Comment by muzimuzhi** [comment]
I have opened #1089 to add `xfrac.cwl` to texstudio. As a quick solution, you can save the contents of file `xfrac.cwl` in `~/.config/texstudio/completion/user/xfrac.cwl`.

**Comment by CakeUser321** [comment]
> I have opened #1089 to add `xfrac.cwl` to texstudio. As a quick solution, you can save the contents of file `xfrac.cwl` in `~/.config/texstudio/completion/user/xfrac.cwl`.

This fix does unfortunately not work for me.

**Comment by muzimuzhi** [comment]
> According to [#336 (comment)](https://github.com/texstudio-org/texstudio/issues/336#issuecomment-425545477) the auto completion only works for a package if the corresponding cwl file is stored in `~/.config/texstudio/completion/user`.

The autocompletion works if there is a corresponding cwl file
 - installed with texstudio (this is the case for `placeins.cwl`), or
 - in path `~/.config/texstudio/completion/user`.

**Comment by muzimuzhi** [comment]
> > I have opened #1089 to add `xfrac.cwl` to texstudio. As a quick solution, you can save the contents of file `xfrac.cwl` in `~/.config/texstudio/completion/user/xfrac.cwl`.
> 
> This fix does unfortunately not work for me.

You need to reopen texstudio.

**Comment by CakeUser321** [comment]
> You need to reopen texstudio.

I already tried that. Furthermore, I tried to enable xfrac.cwl manually in the options. 
Neither
1) xfrac.cwl not manually imported + restart
nor 
2) xfrac.cwl manually imported + restart
did work...

**Comment by CakeUser321** [comment]
> The autocompletion works if there is a corresponding cwl file
> 
>     * installed with texstudio (this is the case for `placeins.cwl`), or
> 
>     * in path `~/.config/texstudio/completion/user`.

That makes sense, thank you. So what you are saying is, basically I have to wait until a `.cwl` file for the xfrac package has been manually created?

**Comment by muzimuzhi** [comment]
This is strange. On my side, after copying the `xfrac.cwl` to `~/.config/texstudio/user`, I get command `\sfrac` shown in autocompletion.
![image](https://user-images.githubusercontent.com/6376638/81836343-e857c580-9575-11ea-804d-126ba82d98ce.png)

Notice that you use a somewhat old release of texstudio (2.12.6), would you test the latest stable release (2.12.22)?

**Comment by CakeUser321** [comment]
> Notice that you use a somewhat old release of texstudio (2.12.6), would you test the latest stable release (2.12.22)?

Sure, I can do that. Did you copy the `xfrac.cwl` file from the autogenerated directory or did you get this file from somewhere else?

**Comment by muzimuzhi** [comment]
You can get the contents of `xfrac.cwl` here: https://github.com/texstudio-org/texstudio/pull/1089/files#diff-419ebdee302edda6b9a6de72fd25c326.

**Comment by CakeUser321** [comment]
Thanks, with the new `xfrac.xwl` is does work! Even with the old version. The problem was, that I copied the autogenerated file and not your new file.

**Comment by CakeUser321** [comment]
Maybe it would make sense to update the section `Why does a command not show up in the completion?` in the FAQ https://sourceforge.net/p/texstudio/wiki/Frequently%20Asked%20Questions/#why-does-a-command-not-show-up-in-the-completion. Your point is not included in it

**Comment by muzimuzhi** [comment]
> The problem was, that I copied the autogenerated file and not your new file.

> I have opened #1089 to add `xfrac.cwl` to texstudio. As a quick solution, you can save the contents of file `xfrac.cwl` in `~/.config/texstudio/completion/user/xfrac.cwl`.
> quoted from https://github.com/texstudio-org/texstudio/issues/1088#issuecomment-628081206

Ok, that might be my fault to not explicitly mention "save the contents of file `xfrac.cwl` _provided in my pr_."
