### ISSUE TITLE
Highlight from the autocomplete bleeds into the next line by ~2 characters

### ISSUE THREAD

**Issue by thatlittleboy** [texstudio-org/texstudio#109]
### Environment
- TeXstudio: TeXstudio 2.12.9 (hg 2.12.8-48-g60b98db) 
- Qt: 5.8.0
- OS: Windows 10 
- TeX distribution: Miktex 

### How to reproduce
In a new file, perform the key combinations:

1. <kbd>Ctrl</kbd>+<kbd>E</kbd>, type `equation` to get:
```
\begin{equation}
	content
\end{equation}
```
then <kbd>Ctrl</kbd>+<kbd>Right Arrow</kbd> to jump placeholder to `content`.

2. Type some text, like `This is a test`, highlight the words you just typed (e.g., `test`), then replace it with `\sum`. Then <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>D</kbd> (subscript shortcut).

### Actual behavior
This happens:
![mwe](https://user-images.githubusercontent.com/30731072/38516478-2bceaa4c-3c2f-11e8-8d8b-15f6203f1da3.gif)

I should note that this often happens when I'm trying to overwrite certain parts, for example, what I really wanted to type was `This is a \sum_{x}` and I am trying to overwrite the `test` that I mistakenly typed.
So if I continue typing after the wrong "highlight" occurs, I will get something like:

![texstudio_2018-04-09_19-48-22](https://user-images.githubusercontent.com/30731072/38516405-fae760f4-3c2e-11e8-8651-09dd7fcfac29.png)

and I would have to fill in the missing `\e` myself again.

### Expected behavior
It should only "highlight" and replace up till the `}`.
I'm not quite sure how to generalize this behaviour, but I've experienced this quite often in a variety of cases.

**Comment by sunderme** [comment]
fixed in repository
