### ISSUE TITLE
Redirect wiki on sourceforge to GitHub?

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#1090]
There are two copies of wiki pages of texstudio,
 - one on sourceforge https://sourceforge.net/p/texstudio/wiki/Home/, and
 - one on GitHub https://github.com/texstudio-org/texstudio/wiki.

It seems the GitHub one is under maintenance, but the sourceforge one is not. For example, [this change](https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions/_compare/57a20ce6cc103c8ed433b2c645c548f89989acdb) to FAQ wiki page taken place on GitHub in 2018 is not shown in [corresponding wiki page on sourceforge](https://sourceforge.net/p/texstudio/wiki/Frequently%20Asked%20Questions/).

Since users may still come to sourceforge, I suggest to redirect wiki on sourceforge to GitHub (or something similar).

**Comment by sunderme** [comment]
sounds. good

**Comment by sunderme** [comment]
there is info now on that wiki, but I am hesitant to remove content

**Comment by timhoffm** [comment]
Some of the information on the sf wiki is outdated and AFAIR we migrated all the content to github. So there is no particular need to keep the old content. But OTOH I'm not too worried if you want to keep it.

**Comment by muzimuzhi** [comment]
Thanks.

**Comment by muzimuzhi** [comment]
A follow-up minor problem: Now https://sourceforge.net/p/texstudio/wiki/Home/ contains
```html
<strong>Developments has moved to <a class="" href="http://github.com/textstudio-org/texstudio" rel="nofollow">github</a><br>
These pages are not maintained.</strong>
```
But GitHub responses with 404 for `http://github.com/textstudio-org/texstudio`. So it should be `https://...`.
