### ISSUE TITLE
open external terminal does not work

### ISSUE THREAD

**Issue by fg-dev** [texstudio-org/texstudio#1094]
### Environment
- TeXstudio: TeXstudio 3.00.00 (git 3.0.0alpha4-32-g577b520)
- Qt: Version 5.12.1, compiled with Qt 5.12.1 R
- OS: Windows 10 64bit 
- TeX distribution: miktex

### Expected behavior

an open window of cmd

### Actual behavior
I can see in the message windows this message "Process started: C:\WINDOWS\system32\cmd.exe"
but no window appears.

I checked in the process monitor, and I found the process is started, but no window appears.

### How to reproduce
go to Tools menu, then click on the open external terminal.

**Comment by MeanSquaredError** [comment]
I can confirm the problem. I think it is due to the new code that changes the way the external terminal executable is run. I will provide a PR with the fix shortly.
