### ISSUE TITLE
dollar in \url argument interpreted as math mode shift

### ISSUE THREAD

**Issue by jendrikw** [texstudio-org/texstudio#1095]
### Environment
- TeXstudio: 2.12.22
- Qt: 5.14.2
- OS: Arch Linux (5.6.12-arch1-1)
- TeX distribution: Texlive 2019

### Expected behavior
Using the dollar sign in a url should be fine (like it works for `\verb`). Also useful for `\mintinline`.

### Actual behavior
There is wrong syntax highlighting, but the document compiles.

### How to reproduce
```tex
\documentclass{article}
\usepackage{hyperref}
\begin{document}
	\url{http://example.com/abc$abc}
\end{document}
```

![image](https://user-images.githubusercontent.com/12938023/82073129-17d31300-96d9-11ea-8ce2-a90dc729cf53.png)

**Comment by foreachthing** [comment]
Don't you have to backslash-escape $ as well?

**Comment by jendrikw** [comment]
![image](https://user-images.githubusercontent.com/12938023/82082797-e8c49d80-96e8-11ea-9a42-b99a5364f813.png)

 
It works for me.

**Comment by sunderme** [comment]
this is not (easily) fixable.
As a work around, you can place '%$' behind the url command

**Comment by sunderme** [comment]
fixed
