### ISSUE TITLE
[doc] Document fold range marker %BEGIN_FOLD and %END_FOLD

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#1104]
From [Collapse '\usepackage's in preambule](https://tex.stackexchange.com/q/545438) on tex.stackexchange.com, I knew for the first time, that the `%BEGIN_FOLD` and `%END_FOLD` can be used to mark a foldable range.

And I find it is implemented (for years) in `tex.qnfa` file with full syntax `%[\ \t]*BEGIN_FOLD` and `%[\ \t]*END_FOLD`
https://github.com/texstudio-org/texstudio/blob/8f595a1aee76f23dc550d0c4e2018ae08a7d5840/utilities/qxs/tex.qnfa#L28-L29

This utility is useful but not documented. Currently in the `usermanual.html`, there is no separate section for folding. Maybe we can add a new subsection under _4. Other features_, for example named _Miscellaneous_, to document this utility?

**Comment by muzimuzhi** [comment]
A draft: https://github.com/texstudio-org/texstudio/compare/master...muzimuzhi:doc-begin-fold

**Comment by sunderme** [comment]
just make a PR
