### ISSUE TITLE
Bug: support Chinese character in the directory name of tex file 

### ISSUE THREAD

**Issue by zhangliye** [texstudio-org/texstudio#1107]
### Environment
- TeXstudio: 2.12.22 
- Qt: 5.14.0, compiled with Qt 5.14.0 R
- OS: Windows10 / Mac
- TeX distribution: miktex / texlive

### Expected behavior
Cursor following scrolling and scrossing following cursor does not work

### Actual behavior
Cursor following scrolling and scrossing following cursor does not work.
This is caused by using Chinese characters in the directory name. 

### How to reproduce
Need supporting Chinese character in the directory name.

**Comment by sunderme** [comment]
see #983

**Comment by sunderme** [comment]
unless synctex can handle unicode, there is nothing we can do.

**Comment by muzimuzhi** [comment]
Both synctex and cursor following scrolling/scrolling following cursor work under macOS 10.15.4 with texlive 2020. I test with both directory name and tex file name containing Chinese characters.
