### ISSUE TITLE
Blue rhombus overlay in internal pdf viewer using the beamer multimedia package

### ISSUE THREAD

**Issue by krrk** [texstudio-org/texstudio#111]
### Description of Issue
When using the multimedia package in a beamer presentation the internal pdf viewer is overlaying giant blue rhombi whenever a `\movie[options]{poster text}{file}` is inserted and the movie is not empty. An "empty" movie (as in `\movie{}{}` will not produce the problem), but as soon as any poster text is specified `\movie{poster text}{}` or a size is given `\movie[width=1cm,height=1cm]{}{}` a blue rhombus will overlaying most of or all of the frame. These rhombi do not appear in external viewers such as Okular, Evince, Preview (macOS), Adobe Reader DC (macOS, Windows). Of course if you include an actual movie there is the same issue, but interestingly if you declare the movie with the `externalviewer` option (as in `\movie[externalviewer]{poster text}{file}`) there is no issue. If you have compiled texstudio with phonon backend then you can click on the movies and they will play and also will come out in front of the rhombus, but the rhombus is still there.

### Environment
TeXstudio 2.12.9 (hg 2.12.8-48-g60b98db)
This is a development version.
Using Qt Version 5.10.0, compiled with Qt 5.10.0 R
Ubuntu 16.04
Note that I have compiled TeXstudio with the phonon backend, however the issue exists with the 2.12.8 QT5 xUbuntu16.04 from texstudio.org and it exists on macOS 2.12.8 dmg from texstudio.org
```
$ pdflatex --version
pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian)
kpathsea version 6.2.1
Copyright 2015 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Compiled with libpng 1.6.17; using libpng 1.6.17
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with poppler version 0.41.0
```

### Expected behavior
Internal pdf viewer does not overlay rhombi and renders the pdf as the external viewers do.

### Actual behavior
Giant blue rhombi overlay each page of the resulting pdf which do not allow you to see the content.

### How to reproduce
```latex
\documentclass{beamer}

\usepackage{default}
\usepackage{multimedia}
% I've included lmodern because of latex complaining about a missing font size, the issue persists with or without lmodern
\usepackage{lmodern}

\begin{document}
	\begin{frame}
	\centering
	No problem here with an empty movie
	\movie{}{}
	\end{frame}

	\begin{frame}
	\centering
	Now adding poster text makes the movie take up some space and it appears to show a blue rhombus in the internal PDF vider, but not in the external viewer. \\
	\movie{Poster Text, No Movie}{}
	\end{frame}

	\begin{frame}
	\centering
	A small size bounding box reveals almost the whole rhombus \\
	\movie[width=0.1mm,height=0.1mm]{}{}
	\end{frame}

	\begin{frame}
	\centering
	The same issue happens with a movie \\
	\movie[width=10.66cm,height=6cm,poster]{}{big_buck_bunny_720p_stereo.ogg}
	\end{frame}

	\begin{frame}
	\centering
	The same also happens with a movie of a smaller size \\
	\movie[width=5.33cm,height=3cm,poster]{}{big_buck_bunny_720p_stereo.ogg}
	\end{frame}

	\begin{frame}
	\movie[options]{poster text}{file}
	\centering
	There is no issue when specifying the externalviewer option \\
	\movie[externalviewer]{\beamerbutton{External Viewer}}{big_buck_bunny_720p_stereo.ogg}
	\end{frame}
\end{document}
```
Latex output pdf: [movie.pdf](https://github.com/texstudio-org/texstudio/files/1895269/movie.pdf)
What I see in TexStudio (zoomed out of all pages to illustrate all pages): 
![screenshot_20180410_114527](https://user-images.githubusercontent.com/4636304/38567721-e2239462-3cb4-11e8-99d4-88ebc6596e9d.png)

After clicking on the movie to play it, here is a screenshot during playback:
![screenshot_20180410_115403](https://user-images.githubusercontent.com/4636304/38568170-f7cde082-3cb5-11e8-8588-58af8b671344.png)

For linked movie [big_buck_bunny_720p_stereo.ogg](http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_720p_stereo.ogg)

**Comment by sunderme** [comment]
works fine with texworks/evince, so no poppler bug, but texstudio

**Comment by sunderme** [comment]
fixed in repository

**Comment by krrk** [comment]
Thanks, its working for me now.
