### ISSUE TITLE
Feature Request: unattended installer

### ISSUE THREAD

**Issue by TimmKroe** [texstudio-org/texstudio#1110]
### Environment
- TeXstudio: 2.12.22
- Qt: 5.12.1
- OS: Windows 10 1909
- TeX distribution: miktex

### Expected behavior
Is it possible or it should be possible to run the installer unattended (silent) so you can install the software with a package manager like winget

**Comment by timhoffm** [comment]
TeXstudio uses the Nullsoft Install System (NSIS). Do the standard options not work for you?

http://www.silentinstall.org/nsis

**Comment by TimmKroe** [comment]
Well I didn't know that it uses the Nullsoft Install. I'll try if it works for me and then reply. But thanks a lot :)

**Comment by TimmKroe** [comment]
Seems to have worked. 

https://github.com/microsoft/winget-pkgs/pull/1049
