### ISSUE TITLE
shortcuts not restored properly

### ISSUE THREAD

**Issue by TaZi-loh** [texstudio-org/texstudio#1111]
### Environment
- TeXstudio: 2.12.6
- Qt: Qt-Version 5.9.1, compiled with Qt 5.9.1 R
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
when I load stored settings, I expect all shortcuts to be in place again.

### Actual behavior
Ctrl+Q was set as shortcut for "Quit" 

### How to reproduce
- go to settings and set Ctrl+Q as shortcut for "toggle comment" (click ok, when asked it Ctrl+Q should be removed as shortcut for quitting.
- go to options "save profile" to save your settings
- [optional] check the file you stored to see that "quit" has a blank shortcut while "toggle comment" has "Ctrl+Q" as shortcut.
- reset settings to default.
- load the previously saved profile
- check in the settings, that Ctrl+Q is now again the shortcut for "quit" rather than "toggle comment"

remark: shortcuts that did not collide, were restored nicely.

**Comment by sunderme** [comment]
we are only talking about "load profile" ?

**Comment by TaZi-loh** [comment]
yes
