### ISSUE TITLE
(3.0.0alpha6) GUI: Configure Window - Bad alignment of gui objects

### ISSUE THREAD

**Issue by jonasstein** [texstudio-org/texstudio#1118]
### Environment
```
TeXstudio 3.00.00 (git 3.0.0alpha6-1-g80b1f228)
Using Qt Version 5.15.0, compiled with Qt 5.15.0 R
```
Minor bug, but trivial to fix.

bad alignment of gui objects. The objects should need no scrollbar by default.
![image](https://user-images.githubusercontent.com/298682/83576352-d7c1bc00-a531-11ea-8321-17b4bf397615.png)

**Comment by sunderme** [comment]
the actual layout is very dependent on circumstances (font size, resolution, etc)
We don't control it on pixel level. It is okay on linux on lxqt. But no guarantees if something changes, so "don't fix"
