### ISSUE TITLE
Caching(?) issues with long documents

### ISSUE THREAD

**Issue by thatlittleboy** [texstudio-org/texstudio#112]
### Environment
- TeXstudio: TeXstudio 2.12.9 (git 2.12.8-52-ged7d4ab)
- Qt: Qt Version 5.8.0, compiled with Qt 5.8.0 R 
- OS: Windows 10 
- TeX distribution: MikTeX

### How to reproduce
1. Open a `.tex` document that spans more than 1 page (TXS window height) long. Or just create one: here's some sample text to copy and paste:

>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel sem maximus, sagittis tortor nec, pharetra nisi. Duis dignissim at nulla eu fermentum. Ut sit amet tortor sapien. Vestibulum volutpat justo tincidunt porttitor laoreet. Curabitur viverra felis volutpat facilisis fermentum. Donec in mattis tortor, ac mollis magna. Quisque vel neque dictum, tincidunt turpis eu, rhoncus lacus. Nullam ipsum urna, tincidunt id lorem posuere, pretium molestie lorem. Aenean et vulputate magna. Cras eget efficitur odio. Nam et ligula imperdiet, tincidunt lectus ac, convallis ante. Nullam quam turpis, facilisis ut magna in, molestie venenatis purus. Phasellus enim risus, tristique a neque a, eleifend placerat erat.

2. and scroll down.

### Expected behavior
The document to appear as normal.

Works fine in the previous version: `TeXstudio 2.12.9 (git 2.12.8-51-gd7b4986)`

### Actual behavior
Document missing.

![mwe](https://user-images.githubusercontent.com/30731072/38583016-8c3d736a-3d09-11e8-96ba-55f656ee2002.gif)

**Comment by sunderme** [comment]
fixed
