### ISSUE TITLE
Saving sessions (and therefore restoring) does not work

### ISSUE THREAD

**Issue by paulinsmaier** [texstudio-org/texstudio#1126]
TeXstudio 3.00.00 (git 3.0.0alpha6-13-gc67e0de)
Nutze Qt-Version 5.12.1, kompiliert mit Qt 5.12.1 R

### Expected behavior
Restoring or saving sessions by hand.

### Actual behavior
Actual sessions are not saved. If I save a session by hand it just says: "Das Speicher der Sitzung ist fehlgeschlangen" - something like: Saving of the session failed. (the txss file)

**Comment by sunderme** [comment]
which OS ?
Is the place you want to put the file is writeable ?

**Comment by paulinsmaier** [comment]
Windows 10. Latest build.

Yes of course, it s writeable. I tried the same folder as the Tex file e.g.

sunderme <notifications@github.com> schrieb am Fr., 12. Juni 2020, 10:39:

**Comment by paulinsmaier** [comment]
@sunderme  I tried on a second computer also Windows 2004, 19041.329. Same behavior. It does not allow me to save the session in any folder I tried. I also run texstudio as administrator. Same. Can I generate a log or something?

**Comment by paulinsmaier** [comment]
Seems to work. Thanks!
