### ISSUE TITLE
Dark Mode in Mac OS X with "dark mode" enabled unusable

### ISSUE THREAD

**Issue by sgoendoer** [texstudio-org/texstudio#1131]
Issue with TexStudio 2.12.22, where the OS is set to "dark mode" and TexStudio apparently (?) automatically switches to dark mode too. 

Certain things are not visible anymore. E.g.: 
- Black text for section names on dark gray background.
- White normal text in a highlighted line on white (jikes!) background!

Apparently, no switch is implemented that would run TexStudio in light mode even though the OS is set to dark mode

### Environment
- TeXstudio: 2.12.22
- Qt: 5.14.0 R
- OS: Mac OS X 10.15.5
- TeX distribution: texlive

### Expected behavior

- TexStudio having a dark mode where colors are not making text completely unreadable
- TexStudio having an option to easily switch between a dark and a light mode - independently from the OS's setting

### Actual behavior

OS X in dark mode automatically switches TexStudio to dark mode too
Dark mode unreadable

### How to reproduce

Switch MacOS X to dark mode and reopen TexStudio

**Comment by sgoendoer** [comment]
<img width="382" alt="Screen Shot 2020-06-15 at 16 05 55" src="https://user-images.githubusercontent.com/1579152/84667976-4ab03700-af23-11ea-8564-03a5828b24ed.png">

**Comment by sunderme** [comment]
work around is Options/ignore most system colors
3.0.0 will have support for dark mode (available as alpha build)
