### ISSUE TITLE
In TXS3 the spelling doesn't work if syntax is not enabled

### ISSUE THREAD

**Issue by hair-splitter** [texstudio-org/texstudio#1132]
### Environment
- TeXstudio: 3.00.00 (git 3.0.0alpha6-24-g1e3755f)
- Qt: 5.12.1, compiled with Qt 5.12.1 R
- OS: Windows 10
- TeX distribution: TeX Live 2020

### Expected behavior
If 'Spelling' is enabled and 'Syntax' is not enabled, then the spelling works, and the LaTeX syntax mistakes are not highlighted.

### Actual behavior
If 'Spelling' is enabled and 'Syntax' is not enabled, then the spelling doesn't work.
This bug is not in TeXstudio 2.12.22.

### How to reproduce
Options / Configure TeXstudio / Editor
'Spelling' is enabled
'Syntax' is not enabled

**Comment by sunderme** [comment]
confirmed
spellchecking has moved into the syntax checker for performance reasons
Not sure yet, how to go on about it.

**Comment by hair-splitter** [comment]
Okay, thanks.

**Comment by sunderme** [comment]
fixed
