### ISSUE TITLE
Broken download link for ubuntu 20.04

### ISSUE THREAD

**Issue by mhtb32** [texstudio-org/texstudio#1134]
The [download link](http://download.opensuse.org/repositories/home:/jsundermeyer/xUbuntu_20.04/amd64/texstudio_2.12.22-1+2.1_amd64.deb) for Ubuntu 20.04 LTS doesn't work. Here's what I get:

![Imgur](https://imgur.com/wJlYdgx.png)

**Comment by sunderme** [comment]
fixed
