### ISSUE TITLE
.cwl file: argument serves as a label iff no optional argument is given (suggestion)

### ISSUE THREAD

**Issue by user929292** [texstudio-org/texstudio#1135]
### Environment
- TeXstudio: 2.12.22
- Qt Version 5.12.1, compiled with Qt 5.12.1 R
- OS: Windows 10
- TeX distribution: miktex

My .cwl file contains the following lines:
\xlabel[label]{nonlabel}#l
\xlabel{label}#l

### Expected behavior
When no optional argument is given, the only argument is added to the list of labels.

### Actual behavior
The second \xlabel line has no effect. Therefore, the only argument is not added to the list of labels.

### How to reproduce
This way you can define a latex command whose optional argument is the label, if given, else its second argument is the label.

\usepackage{xifthen} 
\newcommand{\xref}{\nameref} %21.6.20
\makeatletter
\newcommand{\xlabel}[2][]{\phantomsection\def\@currentlabelname{\ifthenelse{\equal{#1}{}}{#2}{#1}}\label{#2}} %\usepackage{xifthen} to allow omitting the optional argument
\makeatother %More on this: https://tex.stackexchange.com/a/550382/

**Comment by sunderme** [comment]
no
The current syntax recognition is based on argument position which is fine for most packages.
Why don't you reverse the order of the \xlabel definition ,i.e. \xlabel[nonlabel]{label} ? Way more consistent with other packages... and does not require massive reqrite of txs code.

**Comment by user929292** [comment]
Sounds reasonable. Actually, I accidentally did copy above such version of \xlabel, and I'm fine with changing also the other commands according to that.
