### ISSUE TITLE
TeXstudio crashes on El Capitan

### ISSUE THREAD

**Issue by titizaki** [texstudio-org/texstudio#114]
### Environment
- TeXstudio: 2.12.8
- Qt: 5.10.0
- OS: 10.11.6 (crash), 10.13.4 (no crash)
- TeX distribution: TeX Live 2017 (fully updated)

### Expected behavior
TeXstudio can function without crashing on macOS 10.11 (since your website indicated that 10.8+ is supported).

### Actual behavior
TeXstudio 2.12.8 crashes systematically after launch on macOS 10.11.

### How to reproduce
I manage a number of Macs running 10.11 or 10.13 and started testing TeXstudio 2.12.8. This version crashes almost immediately after launch on every El Capitan (10.11) machine.

I tried deleting the preferences file or running TeXstudio from a newly-created user account, but it doesn't change anything. Even if TeXstudio's window appears correctly, simply displaying the PDF viewer is enough to make it crash reliably.

Here is a crash report from my test machine:
[texstudio2128crash.txt](https://github.com/texstudio-org/texstudio/files/1919044/texstudio2128crash.txt)

On the other hand, version 2.12.6 works without problem on El Capitan, and 2.12.8 is also fine on High Sierra (10.13). Only the combination 2.12.8 on 10.11 seems to be buggy.

**Comment by sunderme** [comment]
duplicate #96 
I have no idea why it works on some macs and not on others, it works here
