### ISSUE TITLE
Commands incorrectly marked as errors after find&replace.

### ISSUE THREAD

**Issue by marmistrz** [texstudio-org/texstudio#1140]
### Environment
- TeXstudio: ae3e0b83ceddcb7a0a219a39ac47ca93b74ecbb7
- Qt: 5.15.0-3
- OS: Arch Linux
- TeX distribution: texlive

### How to reproduce
I have the following formula in my .tex file:
```
\[
\omega([X, Y]) \overset{?}{=} X(\omega(Y)) - L_X\omega(Y) \\
\]
```
I find & replace: `X(\omega` -> `\mu(\omega`. Then `\mu(\omega` is highlighted as an error. However, after touching this part of the equation (e.g. adding and removing a space), the error highlight is gone.

![Screenshot from 2020-06-23 12-10-54](https://user-images.githubusercontent.com/2914938/85391557-9e85d600-b54a-11ea-8d73-0097bc60bf27.png)

**Comment by sunderme** [comment]
here, it looks like the replacement marker (red) inside a math env looks similar to a error marker.
Nothing is shown when hovering over the marker, esc closes the sear panel and removes the marker  ...

**Comment by sunderme** [comment]
no feedback

**Comment by marmistrz** [comment]
Oh, I didn't know feedback was expected. This is likely to be what you've mentioned. The color is probably a little unfortunate, I guess.
