### ISSUE TITLE
Only partial window redraw

### ISSUE THREAD

**Issue by clecap** [texstudio-org/texstudio#1141]
### Environment
- TeXstudio: 2.12.22
- Qt: 5.14.0 R
- OS: MacOS 10.15.3
- TeX distribution: Texlive 2015

### Expected behavior
F5 saves, compiles and displays result

### Actual behavior
F5 saves, compiles, but then only displays the editor pane, the rest remains white, see attached screenshot.
<img width="2786" alt="Screenshot 2020-06-23 at 21 37 31" src="https://user-images.githubusercontent.com/7084049/85452125-dae12280-b59a-11ea-81bf-bd1bed1fe0f3.png">

### How to reproduce
Updated from TeXstudio 2.?.? to 2.12.22 and got an installation where randomly on 1 out of approximately 8 save-recompiles with F5 I get an incomplete repaint (see attachment).

Some 15-20 seconds later or when clicking into the window, the window repaints or starts to repaint.

**Update:** This also happens outside of the F5 command just at random moments when editing.

**Update 2:** This happens so frequently as to render this version unusable on Catalina. Going back to Texstudio 2.2.16 is a *temporary* soluion.

**Comment by sunderme** [comment]
you can try a dev. build to see whether the problem persists.
Apart from that I don‘t see an approach to see what is wrong. 
Mind you, you are the first to report such behavior half a year after publishing that version.

**Comment by clecap** [comment]
**Dev build** is working for 2 days now without any problem.

**Case closed.**

And: Dev build shows nice cool new features. **THANX.**
