### ISSUE TITLE
Greenish appendix background at the dark theme

### ISSUE THREAD

**Issue by buran21** [texstudio-org/texstudio#1144]
Hello.
Many thanks for the dark theme, it works well for TeXstudio v2.12.22 win10. There is a small but annoying detail. I have a paper with a few appendix sections. They are marked on the left tree view by a "greenish background" (#c8e6c8) and together comprise a bright spot with poorly readable text. It seems that appendix tree color is hard coded as it doesn't present in stylesheet.qss. Is there a way to change that color?

![appendix](https://user-images.githubusercontent.com/32599462/85434965-79678680-b58f-11ea-89a6-a6686b9e24af.jpg)

_Originally posted by @buran21 in https://github.com/texstudio-org/texstudio/issues/45#issuecomment-648300758_

**Comment by sunderme** [comment]
support for dark mode will start with 3.0.0
you can try a dev build.

**Comment by vsht** [comment]
I'm using version 3.0.4 on Fedora 32 (Gnome) and I see the same greenish background
in the side panel. How can I get rid of it?

**Comment by rademacher-p** [comment]
I didn't care for this either, found the setting to disable it! Try Options -> Configure TexStudio -> Show Advanced Options (bottom left tickbox) -> Adv. Editor -> Structure Panel -> Uncheck "Mark structure elements in appendix"

**Comment by vsht** [comment]
@rademacher-p Many thanks, this fixes the issue for me!
