### ISSUE TITLE
Copy Paste Indentation

### ISSUE THREAD

**Issue by flashoux** [texstudio-org/texstudio#1146]
### Environment
- TeXstudio: 12.22.2
- Qt: 5
- OS: Linux Mint/Ubuntu 20.04
- TeX distribution: TexLive

### Expected behavior
I would like to paste (a script Python for example ) in TexStudio editor with respect of the indentation there is in the script

### Actual behavior
def foo(a):
     return a**2  <-indentation here (Tab) it is not appeared here due to this editor too !!!
copy this an paste in the TexStudio editor will give :

def foo(a):
return a**2  <-no identation

### How to reproduce

def foo(a):
     return a**2

copy this an paste in the TexStudio editor will give :

def foo(a):
return a**2

**Comment by muzimuzhi** [comment]
Not sure if I fully understand your problem:

Copy
```
def foo(a):
<tab char>return a**2
```
then paste in texstudio, only get
```
def foo(a):
return a**2
```
the `<tab char>` before `return` is missing.

If that _is_ your problem, then set

> Configuration ----- Editor --- Indentation mode -- Keep indentation.
> 
> from https://github.com/texstudio-org/texstudio/issues/445#issuecomment-484076936

**Comment by flashoux** [comment]
Great ! Thank you very much !
