### ISSUE TITLE
Suggestion to let user choose the file extension upon saving

### ISSUE THREAD

**Issue by ptoche** [texstudio-org/texstudio#1147]
Minor annoyance: TeXStudio won't let me save a document with a file extension of my choice, e.g. `note.txt`.

As I use TeXStudio to typeset TeX documents I will often save short notes that may or may not be TeX related and that I wish to save with a `txt` extension (or even `py` or something else). But the best I can get right now is `note.txt.tex`, and I need to manually remove the `.tex` extension afterwards. 

<img width="518" alt="tmp" src="https://user-images.githubusercontent.com/6339274/85918489-091f6600-b818-11ea-98d1-f6b580a88401.png">

**Comment by sunderme** [comment]
which OS ?
You can change the file type in save dialog (from tex to txt ).

**Comment by sunderme** [comment]
which version

**Comment by ptoche** [comment]
Oh sorry! I'm on MacOS. TeXstudio 2.12.22 (git 2.12.22) Using Qt Version 5.14.0, compiled with Qt 5.14.0 R.

**Comment by ptoche** [comment]
Oh I see what you mean. I totally missed that, sorry. Thanks a lot for your help.
