### ISSUE TITLE
Autocompletion not working when using a .sty file

### ISSUE THREAD

**Issue by Saavestro** [texstudio-org/texstudio#115]
I use a preamble file called mymacros.sty, I use `\usepackage{mymacros.sty}` in my main.tex file. TeXstudio automatically creates a file called mymacros.cwl, which I activate in configuration -> completion. Also I have activated the automatically load include files option.

Still my main file doesn't recognize my macros autocompletion, these are recognized only in the same mymacros.sty file.

### Environment
- TeXstudio: 2.12.8
- Qt: 5.9.1
- OS: Ubuntu 17.10

### Expected behavior
For example I expect to write \pd to be autocompleted as `\pd{arg1}{arg2}`, instead it suggests me `\pdfbookmark[option]{text}{name}` and `\pd{arg}{arg}` is not even listed as an option.

Any help with this?

**Comment by sunderme** [comment]
see wiki how txs handles commands:https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions

**Comment by Saavestro** [comment]
That didn't help

**Comment by sunderme** [comment]
see #46 , read the manual, look at the discussions/issues in https://sourceforge.net/projects/texstudio/

**Comment by Saavestro** [comment]
As I said, I already activated the `Automatically load included files` and didn't work. I have only two files `main.tex`:

```
\documentclass[letterpaper]{article}
\usepackage{testmacros}

\begin{document}
\begin{equation}
\pd{f}{x}
\end{equation}
\end{document}

```
It compiles well. All testmacros.sty has is

`\newcommand{\pd}[2]{\frac{\partial #1}{\partial #2}}`

**Comment by Saavestro** [comment]
![2](https://user-images.githubusercontent.com/38469598/38906340-c134fda0-427b-11e8-98e1-0e5182715723.png)
![1](https://user-images.githubusercontent.com/38469598/38906341-c14809ae-427b-11e8-9005-83a9aa913a04.png)

**Comment by sunderme** [comment]
txs does not scan .sty file 
write a cwl file yourself or change it to \input{mymacros.tex}

**Comment by Saavestro** [comment]
`\input{mymacros.tex}` did the trick, thank you.

Still, when I use a format for the .sty file as the following:
```
\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{mymacros}[2018/04/15 v1.0 My own macros]
...content...
\endinput
```
I don't get the command autocompletion. So I don't know which is the correct format for .sty files.
