### ISSUE TITLE
TeXstudio Hangs When Dealing with Large Files and \input

### ISSUE THREAD

**Issue by ultimatecheese** [texstudio-org/texstudio#1150]
### Environment

- TeXstudio 2.12.14 (git 2.12.14)
- Qt: Version 5.8.0, compiled with Qt 5.8.0 R
- OS: Windows 10
- TeX distribution: miktex

### Computer

- Processor Core i7-8650U @ 1.90GHz
- RAM: 16.0 GB (I forget what)
- Storage: 512 GB SSD

### Expected behaviour

Run normally (without hanging)

### Actual behaviour

Short version: hangs upon saving changes to files which have been included via `\input`.

I am writing my thesis using TeXstudio. In general, I love it, but I have noticed that it really does not seem to like large files. I have a master file and then 6 other main files, which I include using `\input{filename#.tex}` in the appropriate place; these six files are a little over 700 KBs. So not _enormous_, but not small either.

If I open one of these, henceforth referred to as, 'subfiles' and make some changes then press save, texstudio hangs for a long time -- sometimes minutes. Even if I edit them in a different editor, such as` Notepad++`, upon saving in the other editor texstudio clearly realises that changes have been made and hangs. I guess it's maybe trying to parse it all line by line?

In a highly related post (https://github.com/texstudio-org/texstudio/issues/249), which the author did not follow up, there is a suggestion to disable automatic loading of included files. I disabled this, but it still happens.

### How to reproduce

I can provide a zip/similar of my files, but I'd rather not post them publicly. I am happy to send them privately.

**Comment by sunderme** [comment]
you should try the latest dev release: https://github.com/texstudio-org/texstudio/releases/tag/3.0.0beta1
If the problem persists, you can send the problematic document to me: sunderme@gmx.de

**Comment by ultimatecheese** [comment]
Thanks for your response. Is it possible to have the development release installed without uninstalling my current set-up? Only I'm right at the point of submitting my thesis, and I don't want to update and lose some compatibility or something!

Incidentally, quite a while ago I had a similar issue with another document. I had a main file plus a preamble file. When updating the preamble file it would hang. I only updated the preamble occasionally so it didn't really bother me and once I finished the project I forgot about it. I mention this because this was around 2yrs ago. So it seems that this issue has been around for a while.

**Comment by sunderme** [comment]
use can use the portable version. Unzip it and start the exe.

**Comment by ultimatecheese** [comment]
There is still some hanging sometimes, but for around 10secs. Previously it was 1min+.

I also tried the most recent non-beta version (`2.12.22` portable). I did the same type of edit and hit save. It hung for nearly one minute. Tried a similar small change again and hung for just over one minute.

---


The new version is having some issues when I make changes and don't save them before pressing `build+view`. Namely, it ignores the changes. It almost seems like it does the compiling first _then_ saves. If I then press `b+v` again it says that the file has been changed outside of TeXstudio and asks if I want to reload from disk. If I press "yes" then it reverts the changes. If I press "no" then click on "conflict" and "overwrite", then I can get the changes saved.

Perhaps this is something to do with the portable version not having the appropriate privileges?

**Comment by sunderme** [comment]
are you saving into a drop box like directory ?

**Comment by ultimatecheese** [comment]
Thanks for your super-quick response.

Sort of. I'm saving straight to my usual Documents folder. However, I use `Boxifier` to link a Documents folder to Dropbox. So any changes get automatically synchronised.

**Comment by ultimatecheese** [comment]
This was causing too much hassle, so while it is being sorted I moved back to my original set up, with the idea that I'd just save infrequently (safe!). I've been doing that for around 10mins. Not had a single hang (ie `(Not Responding)`) and compiling much faster than the beta version was...

It's not just today that I'd been having this issue. Rather it had been happening all last week.

**Comment by sunderme** [comment]
you could try to disable advanced editor/safe writing of files

**Comment by ultimatecheese** [comment]
At the moment I am having no problems with my original configuration (crazy, I know!). If the problems start up again, then I shall try what you suggest. I'll also try the non-portable version
