### ISSUE TITLE
Installing TexStudio installed texlive packages that are conflicting

### ISSUE THREAD

**Issue by kkittykait** [texstudio-org/texstudio#1151]
Installing TexStudio installed texlive packages that are conflicting and out of date, and not requested

Installing from the repository I ended up with it installing TexLive base and other packages that are not wanted

I had to remove them after

I install TexLive from the ISO to avoid the distro that is notouriously out of date and a terrible way to manage TexLive.

It would be nice if TexStudio installed JUST TEXSTUDIO and no TexLive packages at all, I ended having to remove them

I installed from the PPA and Distro, I do not want TexLive deployed in this way partial or otherwise.
It is just a waste of bandwidth, storage space, risks conflicts and waste of time.

TexStudio ONLY nothing else

**Comment by sunderme** [comment]
the package on ubuntu ppa is set up to recommend texlive.
`Depends: libc6 (>= 2.29), libgcc-s1 (>= 3.0), libpoppler-qt5-1 (>= 0.34.0), libqt5concurrent5 (>= 5.6.0~rc), libqt5core5a (>= 5.12.2), libqt5gui5 (>= 5.11.0~rc1) | libqt5gui5-gles (>= 5.11.0~rc1), libqt5network5 (>= 5.0.2), libqt5printsupport5 (>= 5.0.2), libqt5script5 (>= 5.6.0~beta), libqt5svg5 (>= 5.6.0~beta), libqt5widgets5 (>= 5.12.2), libqt5xml5 (>= 5.0.2), libqtermwidget5-0 (>= 0.9.0~), libstdc++6 (>= 5.2), libx11-6, zlib1g (>= 1:1.1.4)

Recommends: texlive-latex-base, texlive-latex-extra, texlive-latex-recommended, texlive-base, latex-beamer, dvipng
`
So, the package is fine, just avoid installing recommended packages.

**Comment by kkittykait** [comment]
I did an apt-get install on texstudio and it dumped down texlive, then I had to remove it after

how do I avoid installing recommended?

**Comment by sunderme** [comment]
the answer my be here: https://unix.stackexchange.com/questions/122289/why-install-recommends-default-is-true
