### ISSUE TITLE
LanguageTool flag errors inside maths

### ISSUE THREAD

**Issue by ElieGouzien** [texstudio-org/texstudio#1154]
### Environment
- TeXstudio: `master` (problem don't exist with last stable release)
- OS: GNU/Linux
- LanguageTool: 4.8

### Expected behaviour
No spell/grammar check for maths (except when text inside maths). 

### Actual behaviour
Maths get checked by LanguageTool, and part are flags as errors.

For instance, all signs for subscript or superscript (`_` and `^`) are marked as errors when language set to French.
Minus signs (`-`) are marked as errors in English.
Grammar errors also appear (for instance, start a sentence with some inline maths and it will indicate that we should start it with capital letter).

### How to reproduce
Writing maths with LanguageTool activated.

Affects both inline and display mathematical environments.

**Comment by sunderme** [comment]
there seems to be no easy solution, so that may take a while

**Comment by ElieGouzien** [comment]
One remark, there is also LangugageTool checks for tikz node names, and path separations (`--`).

**Comment by SouKot** [comment]
Would you please have a look at [textidote](https://github.com/sylvainhalle/textidote)? As far as I understood, it tries to solve a similar problem.

**Comment by DanieLoche** [comment]
Similarly I just notice another similar error with Latex formulas with apostrophes.
Here's an example... should be way simpler to explain : 
![image](https://user-images.githubusercontent.com/11614445/152684152-baa6cfc2-9206-457f-aac2-e9a17be5f117.png)

I don't know why but Language Tool says the ```'``` is missing. Using the suggested correction it simply deleted ```\textbf{```.

**Comment by sunderme** [comment]
finally fixed for math envs
