### ISSUE TITLE
Texstudio truncates files read by \input if computer is low on disk space

### ISSUE THREAD

**Issue by bjtho08** [texstudio-org/texstudio#1156]
This bug is difficult to replicate, but it seems to be similar to a bug found in texmaker, which would truncate input files, essentially wiping it completely without the possibility of undoing it. In my case I had less than 3 GB space left and it would truncate the last of two input files, consistently. When I freed some disk space, the behavior went away. I am unclear about why texstudio would even read files in a potentially destructive manner, like this.

### Environment
- TeXstudio: TeXstudio 3.00.00 (git 3.0.0alpha6)
- Qt: Qt Version 5.12.1, compiled with Qt 5.12.1 R
- OS: Windows 10
- TeX distribution: texlive

### Expected behavior
`\input{}`'ed files should be read, but not truncated. Even if disk space is low.

### Actual behavior
Low disk space causes file contents to be wiped.

### How to reproduce
1. Create a tex document with at least two files read using `\input{}` (haven't tried with only one, since it was always the second one).
2. Make sure the computer is low on disk space.
3. Run Build & View
4. Observe how the last read file is truncated to size 0.

**Comment by sunderme** [comment]
unless the files was changed inside txs, it will not be saved.
are you sure that pdflatex is the culprit. try to compile from command line ...

**Comment by bjtho08** [comment]
I have no idea if pdflatex is the culprit. I assumed it was somehow texstudio itself. But the file was never opened inside texstudio.

This is an example:

```latex
%%% filename: mytable.tab %%%

\begin{tabular}{| r | r | l | l |}
    \hline
    col1 & col2 & col3 & col4 \\ \thickhline
    1 & 2 & 3 & 4 \\ \hline
    5 & 6 & 7 & 8 \\ hline
\end{tabular}
```

```latex
%%% filename: main.tex %%%

\documentclass{article}
\title{Test}
\author{Me}

\begin{document}
\maketitle

\section{Intro}
some text
\begin{table}
    \caption{First table. The table is similar to the one found in "mytable.tab"}
    \input{sometablefile.tab}
\end{table}

More text ...

\begin{table}
    \caption{Second table}
    \input{mytable.tab}
\end{table}

\end{document}
```
The table files are generated with a python script and copied into the same directory as `main.tex`. I have verified the contents using `notepad++` both before and after copying. The table files are not opened at any other point. Not in texstudio or otherwise. When I hit F5, I will sometimes get a compile error and sometimes I will just get a document, where the second table figure is missing the tabular material. In either case, I can go back to the file explorrer and see that now the second table file has a size of 0 and is completely wiped of its contents.

**Comment by aubreyz** [comment]
Are the source files by any slight chance in any sort of synchronised folder? Dropbox in particular.

**Comment by bjtho08** [comment]
@aubreyz yes, they are in a OneDrive folder. I did however make sure that all files were fully synced before compiling. I have tried a couple of times now and freeing up disk space seems to have completely eliminated the issue. Does that point towards OneDrive being the culprit rather than pdflatex of texstudio?

**Comment by aubreyz** [comment]
Well Dropbox is well known to cause this exact problem (wiping file contents of locked files under some circumstances) which is why I gave up my subscription (that and their habit of making bug reports and problems reported on their forum non-visible). I bet you Onedrive is doing it. 

Being fully synched is not the issue (or at least was not on Dropbox) - when files were locked it was (instead of delaying any attempt at reconciling) doing exactly this - replacing them with nul files under some circumstances.

**Comment by sunderme** [comment]
one remark, pdflatex is part of miktex. texstudio just calls it for compiling the tex into pdf. you can do the same from powershell/cmd.exe, just to narrow down the cause...

**Comment by bjtho08** [comment]
If that is actually the case, @aubreyz, then I don't understand how disk space can affect the behavior that much. I had a Dropbox-related issue a while back but that was Dropbox locking the pdf while pdflatex was doing a second/third/nth pass and thus causing the process to fail. The behavior in this case is completely new to me.
@sunderme I will try to reproduce the behavior tonight, if possible, using powershell.

**Comment by bjtho08** [comment]
Okay, so now I've done some testing and made some discoveries. First and most important is perhaps that I cannot recreate the precise behavior with data loss. However, if I execute `Build & View` in texstudio, the modification timestamp changes on the two `.tab` files, but executing pdflatex with identical parameters from windows powershell does not.

To me, that is a clear sign that texstudio does something ahead of starting pdflatex even though the files have never been opened inside texstudio. I suppose it is related to texstudio scanning the files to see if they contain any document structure-related markup? Whatever the reason, texstudio apparently does this in a potentially destructive manner.

**Comment by sunderme** [comment]
Maybe as a cross check: can you put the file in anormal directory and check whether the issue is still present ?

You could also disable safe file saving option.

**Comment by muzimuzhi** [comment]
> ### Environment
> * TeXstudio: TeXstudio 3.00.00 (git 3.0.0alpha6)
> * Qt: Qt Version 5.12.1, compiled with Qt 5.12.1 R
> * OS: Windows 10
> * TeX distribution: texlive

> one remark, pdflatex is part of miktex. texstudio just calls it for compiling the tex into pdf. you can do the same from powershell/cmd.exe, just to narrow down the cause...

@sunderme  (whisper) It seems @bjtho08 installs texlive, not miktex.

**Comment by sunderme** [comment]
True

**Comment by bjtho08** [comment]
@sunderme as soon as I can reliably recreate the issue again, I will run that test. I tried creating a large file to take up disk space using fsutil.exe, but the behavior did not reappear, so I will probably have to wait until I accidentally fill up my drive with several large files, which would more closely mimic the state of my computer when I first noticed the issue.
