### ISSUE TITLE
Wrong Cursor Positioning in Monospace Font (Highlighting Verbatim) 

### ISSUE THREAD

**Issue by foto-andreas** [texstudio-org/texstudio#1157]
If I set a Monospace-Font for verbatim-highlighting and do not use the same font as default, the positioning of cursor differs from vision in editor. This leads to changing/deleting chars at wrong position.
### Environment
- TeXstudio: 2.12.22
- Qt: 5.14.0 R
- OS: MacOS 10.15.5
- TeX distribution: MacTex from TeXlive

Should position and show cursor corresponding to current font

Sets cursor to wrong position

Select "Courier New" for Highlighting verbatim, Leave the default font alone or set to another varying font face. The create a document with verbatim environment and try to edit in it.

**Comment by sunderme** [comment]
please try to disable: advanced editor/disable cache of character width

**Comment by foto-andreas** [comment]
None of the checkboxes helps, but when I change to Qt-Mode instead of QCE it works.
