### ISSUE TITLE
macOS: wrong range of line is selected 

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#1159]
### Environment
- TeXstudio: 3.0.0alpha4 to 3.0.0beta1
- Qt: Using Qt Version 5.14.1, compiled with Qt 5.14.1 R
- OS: macOS
- TeX distribution: texlive 2020, though not related

### Expected behavior
When selecting text lines from tail to head and when the cursor moves left out of the edit area, the beginning of selected line is kept selected.

### Actual behavior
The beginning several characters of first selected line is un-selected. The total width of un-selected characters seems corresponding to the horizontal distance between cursor position and left border of edit area.

![Screen-Recording-2020-07-03-at-16 11 57](https://user-images.githubusercontent.com/6376638/86447620-33a57d80-bd48-11ea-8e24-55641dfde374.gif)

### How to reproduce

See the attached gif above.

### More info
 - This happens in TeXstudio 3.0.0alpha4 to 3.0.0beta1. 3.0.0alpha2 cannot reproduce the problem.
 - "Restore default settings" does not solve the problem.

**Comment by sunderme** [comment]
also happens on linux

**Comment by sunderme** [comment]
anybody interested in biscecting ?

**Comment by sunderme** [comment]
a86fecc3619646b6651cc3d029e5a3f368a68d22 is the culprit.
@axkibe  ?

**Comment by axkibe** [comment]
Ok, found it. For the abstract scrollarea the events cursor position are rebased by QT to the viewport, which I did not when I grabbed the cursor position for the timer handler (because I have no event info there)

**Comment by sunderme** [comment]
I can confirm that it is fixed
thanks again

**Comment by muzimuzhi** [comment]
@sunderme @axkibe Thanks for so quick response and fixing. I should have reported this earlier.
