### ISSUE TITLE
DARK Theme icons missing

### ISSUE THREAD

**Issue by oliversheridanmethven** [texstudio-org/texstudio#116]
After a recent install update to the latest version, and adding a dark style, I cannot see any of the drop down boxes: 

What I would like:

[![enter image description here][1]][1]

What I have:

[![enter image description here][2]][2]

Notice the missing box:

[![enter image description here][3]][3]

Also shows up in the main IDE:

[![enter image description here][4]][4]

[![enter image description here][5]][5]

**DARK theme**

I really want to keep the dark theme (but will settle for a slightly different dark theme). (Currently using the Qt style sheet given at [https://github.com/texstudio-org/texstudio/issues/45](https://github.com/texstudio-org/texstudio/issues/45).)

  [1]: https://i.stack.imgur.com/5Ak7f.png
  [2]: https://i.stack.imgur.com/d7AUH.png
  [3]: https://i.stack.imgur.com/ctx8n.png
  [4]: https://i.stack.imgur.com/adJKt.png
  [5]: https://i.stack.imgur.com/CT01S.gif

**Comment by timhoffm** [comment]
This is some issue within the theme. We do not maintain or officially support any Qt style sheet.

We welcome, if someone is maintaining and improving a dark theme via stylesheets. However, the core developers do not have the capacity to do so.

**Comment by thatlittleboy** [comment]
@oliversheridanmethven Feel free to try [this](https://github.com/thatlittleboy/TeXstudio-QSS-Stylesheet.git): I modified the QSS in https://github.com/texstudio-org/texstudio/issues/45 slightly. There are still some issues as detailed in the README.md, but the icons are fixed, at least.
