### ISSUE TITLE
Mouse cursor does not change to I-beam cursor after clicking editor.

### ISSUE THREAD

**Issue by ho94949** [texstudio-org/texstudio#1160]
### Environment
- TeXstudio: 2.12.22
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution: TexLive

### Expected behavior

I-beam cursor should be shown as mouse cursor while cursor is on editor.

### Actual behavior

Default mouse cursor is shown as mouse cursor while cursor is on editor.

### How to reproduce

Open any file, click on editor, I-beam cursor changes into default mouse cursor.

**Comment by sunderme** [comment]
works as expected on linux and on windows ...

**Comment by ho94949** [comment]
I think It occurs at first installation/execution, and before reboot. (I tried in another PC)

If this is not reproducible, please close this issue.
