### ISSUE TITLE
3.0.0beta1 exits unexpectedly on macOS

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#1162]
### Environment
- TeXstudio: 3.0.0beta1
- Qt: Using Qt Version 5.15.0, compiled with Qt 5.15.0 R
- OS: macOS 10.15.5
- TeX distribution: texlive 2020

### How to reproduce

I was using TeXstudio for a long time (< 12h) and there were five to seven tex files opened. When I pressed shortcut to close TeXstudio, it exited unexpectedly after a while (< 1 min).

[full-crash-report.txt](https://github.com/texstudio-org/texstudio/files/4874956/crash-report.txt)

(Not sure if this excerption is informative and/or helpful.)
```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000018
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [51472]
```

**Comment by sunderme** [comment]
I think a test case is needed to fix this ...

**Comment by muzimuzhi** [comment]
I will provide more info if it reproduces.

**Comment by muzimuzhi** [comment]
After another long time of use, TeXstudio 3.0.0beta2 exits unexpectedly on macOS again.

```
Time Awake Since Boot: 580000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000098
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [52922]

VM Regions Near 0x98:
--> 
    __TEXT                 00000001045ce000-0000000105207000 [ 12.2M] r-x/r-x SM=COW  /Applications/texstudio.app/Contents/MacOS/texstudio
```
[texstudio-3.0.0beta2-macos-crash-report.txt](https://github.com/texstudio-org/texstudio/files/4915544/texstudio-3.0.0beta2-macos-crash-report.txt)

I will provide more info if it reproduces stably.

**Comment by sunderme** [comment]
Seems to be a different issue. some more context would be helpfull...

**Comment by muzimuzhi** [comment]
This time, 3.0.0beta3 quit unexpectedly on macOS 10.15.6 when I click menu item "View" after a long time usage.

```
Time Awake Since Boot: 200000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000028
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [57048]

VM Regions Near 0x28:
--> 
    __TEXT                 0000000107f6a000-0000000108ba4000 [ 12.2M] r-x/r-x SM=COW  /Applications/texstudio.app/Contents/MacOS/texstudio
```
[200802-3.0.0beta3-macos-crash-report.txt](https://github.com/texstudio-org/texstudio/files/5011114/200802-3.0.0beta3-macos-crash-report.txt)

I know nothing about desktop app development, which type of context info would be helpful?

**Comment by sunderme** [comment]
hmm, crash in the event loop
not sure that it helps ...

**Comment by sunderme** [comment]
close as it is affecting old version and no route forward to solve it
