### ISSUE TITLE
Structure view with input/include files

### ISSUE THREAD

**Issue by jeanbertg** [texstudio-org/texstudio#1164]
### Environment
- TeXstudio: 2.12.22

### Expected behavior
Well indented structure view for both the normal tex code and outside files

### Actual behavior
Everything is Left indent

### How to reproduce
\section{Test}
\subsection{Subtest}
\input{input.tex}
\include{input.tex}
\subsection{Subtest2}
\subsection{Subtest3}

Comment input/include line for appropriate structure view

**Comment by sunderme** [comment]
options/adv. editor/keep indentation of includes in structure tree ...

**Comment by jeanbertg** [comment]
I would prefer to have file at same level without having to expand the section.
Assuming one likes this presentation, I do not see why someone would expect 'Subtest2' to appear in a different indent than 'Subtest' just because an input appear in between.
If anything, I would even prefer to have input files left indent if standard sectioning did not break.

**Comment by sunderme** [comment]
you may want to sketch what you mean
e.g.
-Test
--subtest
...

**Comment by jeanbertg** [comment]
<img width="316" alt="subtest" src="https://user-images.githubusercontent.com/45230003/86621068-d286df80-bfbd-11ea-90ad-0a38940ae1c7.png">

See image here.

the input.tex is left indent, i can live with that.
What I don't find okay is the indent of 'subtest2' which I expect to have same indent in the structure as 'subtest' because they are both subsections.
The option you mentioned makes it nested in the subsection so we have to expand by clicking the arrow, also okay with that.

**Comment by sunderme** [comment]
you have only the two options
indenting a tree item without a direct parent is not possible.
