### ISSUE TITLE
Typing errors in TeXStudio editor (missing characters)

### ISSUE THREAD

**Issue by jonathan-g** [texstudio-org/texstudio#1166]
### Environment
- TeXstudio: 2.12.22
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution: MikTeX

### Expected behavior

The characters I type appear in the editor, even if I type quickly.

### Actual behavior

When I type quickly, many characters are missing. If I type this:
```
This is an example paragraph that I am typing quickly in TeXStudio
```
this is what appears in the editor
```
Thiss n example aragraph tha I amtypig quckly in TeXStuio.
```

If I type very slowly (around 2 characters per second), then the typing is mostly accurate. But when every I type quickly, many characters go missing. This is not my typing, since this behavior only appears in TeXStudio and not in any other application.

### How to reproduce

Type quickly in the TeXStudio editor.

**Comment by sunderme** [comment]
simulating keystrokes on linux (about > 100 per second) does not show any issue.
Anybody interested to check on win ?

**Comment by MeanSquaredError** [comment]
I just did a fresh install of 2.12.22 on Windows 7 and it seems to work correctly when I type with about 10 symbols per second which is relatively fast.

@jonathan-g 
1. Does the same problem show up with the TeXstudio 3.0.0 beta ?
2. Can you try starting Windows in safe mode, start TexStudio while in safe mode and see if the problem still persists?

**Comment by foreachthing** [comment]
I've recorded a short macro on my keyboard and played it twice.
150 chars (24 words) takes about 5 seconds. All is fine, on Windows 10 and TeXstudio 2.12.22.

**Comment by jonathan-g** [comment]
I uninstalled TeXStudio and did a fresh install of beta 3.0.0 and I have no problems with the beta. I will close this issue.

Thanks for looking into it.
