### ISSUE TITLE
User command for knitr does not send filename correctly

### ISSUE THREAD

**Issue by vam103** [texstudio-org/texstudio#1169]
### Environment
- TeXstudio: 3.00.00 git
- Qt: 5.9.5
- OS: Windows 10 and Linux Mint 19.3
- TeX distribution: texlive
- R distribution: 4.0.2
- knitr version: 1.29/1.3 

### Expected behavior
Setting user command for knitr send file of %.Rnw to RScript and first "knits" document before running through LaTeX build process with a pdf with embedded R code produced.

### Actual behavior
When executing the user command R throws an error of unknown object as the filename has had the quotes removed.

### How to reproduce
Using the latest git version of TeXStudio and R with the knitr package installed
Create a file as
```
\documentclass{article}

\begin{document}
\maketitle
\end{document}
```
Save as testing.Rnw

Set up user command
```
Rscript.exe -e "library(knitr);knit('%.Rnw')" | txs:///quick
```
and run the user command.

Interestingly it does work on TeXStudio 2.12.22

**Comment by sunderme** [comment]
might be a problem with escaping quotation marks inside quotation marks

**Comment by sunderme** [comment]
probably, you need to replace % by ?am or ?m (to avoid the enclosing double quotes)

**Comment by sunderme** [comment]
no feedback

**Comment by sbtseiji** [comment]
I tested the suggestions given above and no success.
To narrow down the cause of the problem, I also tested with the simplest user command:

> Rscript -e 'print("hello")'

and again, I got an error.

> Error in print(hello) : object 'hello' not found Execution halted

The command below runs successfully

> Rscript -e 'print("hello")'

**Comment by sunderme** [comment]
@MeanSquaredError the setProgramAndArguments swallows characters.
example: sed -e 's/ab/"gh"/' text.txt  -> ' and " are removed ...

**Comment by MeanSquaredError** [comment]
OK, let me check that...

**Comment by sunderme** [comment]
qprocess apparently sets quotes around arguments which goes south if there are quotes within
Also ' collides at times ...

**Comment by MeanSquaredError** [comment]
I checked the code and indeed `ExecProgram::setProgramAndArguments()` intentionally removes single and double quotes even when they are enclosed in other quotes. I guess at the time I did not take into account that someone might run external programs like sed that need single and double quotes as parts of their arguments.

I will prepare a fix shortly.

**Comment by sunderme** [comment]
QProcess also manipuilates quotes, so please check that QProcess actually works as intended.
I have played around with the aforementioned sed command and I was not able to get it running via arglists.
Apparently qprocess sets quotes and a quote in the middle messes things up ...

**Comment by MeanSquaredError** [comment]
@sunderme 
I provided a PR with a proposed fix here https://github.com/texstudio-org/texstudio/pull/1231. The `knitr` command seems to work correctly with this PR, just like the example with `sed`. 
Any comments or suggestions for the PR are welcome.
