### ISSUE TITLE
release notes? changelog?

### ISSUE THREAD

**Issue by moldt** [texstudio-org/texstudio#117]
Hi,

This may seem like a stupid question but where do I find the release notes for version 2.12.8? I'm just wondering if it would be worth it for me to upgrade to this latest version, right now I still use 2.12.6.

Searching for "release notes" or "changelog" or the like on google or here in this github repository didn't bring up anything (which could very well just be my lack of understanding of how searching in github repositories works). Google found the page https://www.texstudio.org/#news, but this site only has the changelogs of version 2.12.6 and older.

Thanks for helping me out!

PS: I'm a fan. On MS Windows, TeXstudio is so much better than the alternatives I know.

**Comment by sunderme** [comment]
we have not bothered to write release notes.
Mainly only bug fixes and minor improvements.

**Comment by dbitouze** [comment]
>Mainly only bug fixes and minor improvements.

Well, the way math symbols are handled in the sidebar could have been notified.
