### ISSUE TITLE
File, Edit, Idefix ... bar is missing.  

### ISSUE THREAD

**Issue by Kaveh01** [texstudio-org/texstudio#1170]
File, Edit, Idefix ...  bar is missing.  
### Environment
- TeXstudio: 2.12.22+debian-1build1
- Qt: 5 I guess 
- OS:  Ubuntu 20.04 
### Expected behavior
File, Edit, Idefix ... should be in place.

### Actual behavior
File, Edit, Idefix ...  bar is missing. 

### How to reproduce
Install a fresh ubuntu 20.04 and texstudio from the official package manager or via .deb on the www.texstudio.org

**Comment by sunderme** [comment]
so where is the deb coming from ? texstudio.org offers for sure a different version than ubuntu or ppa ...

**Comment by sunderme** [comment]
and to be honest, I don't think it is a txs issue. Rather a issue with qt5 and the window manager ... which is not mentioned in the post ?

**Comment by Kaveh01** [comment]
> so where is the deb coming from? texstudio.org offers for sure a different version than ubuntu or ppa ...

I tried both texstudio.org deb files and ubuntu repo and nothing changed.

**Comment by Kaveh01** [comment]
> and to be honest, I don't think it is a txs issue. Rather a issue with qt5 and the window manager ... which is not mentioned in the post ?

I agree. I had this problem and a qt4 build solved the problem.

**Comment by Kaveh01** [comment]
Update: It is the problem with gnome-flashback. It works fine with other desktops.
