### ISSUE TITLE
Conjunct letters in TeXstudio

### ISSUE THREAD

**Issue by Al-Imran-Abir** [texstudio-org/texstudio#1171]
### Environment
- TeXstudio: 2.12.22
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
I use TeXstudio as the LaTeX editor. When I write Bengali (which has many conjunct letters) using TeXstudio, the conjunct letters are not properly shown. An example of how a script containing conjunct letters should be, is given here:

```
	\tableofcontents
	
	\section{রাসায়নিক বিক্রিয়ার শ্রেণীবিভাগ}
	
	রাসায়নিক বিক্রিয়াগুলোকে নিম্নলিখিত বিষয়গুলোর উপর ভিত্তি করে শ্রেণিবিভাগ করা যায়ঃ
	
	\subsection{রাসায়নিক বিক্রিয়ার দিক}
	বিক্রিয়ার দিকের উপর ভিত্তি করে রাসায়নিক বিক্রিয়াকে দুই ভাগে ভাগ করা যায়। একমুখী বিক্রিয়া ও উভমুখী বিক্রিয়া। 
	\\
	\paragraph{একমুখী বিক্রিয়া}
	যে রাসায়নিক বিক্রিয়ায় বিক্রিয়ক পদার্থগুলো উৎপাদে পরিণত হয়, কিন্তু উৎপাদ পদার্থগুলো পুনরায় বিক্রিয়কে পরিণত হয় না তাকে একমুখী বিক্রিয়া বলা হয়। 
	
	\selectlanguage{english}
	\[ CaCO_{3} (s) \longrightarrow CaO (s) + CO_2 \]
```

### Actual behavior
However, when I write this in TeXstudio, it looks like this:
![image](https://user-images.githubusercontent.com/68059604/87034570-d1e28900-c209-11ea-86d5-f48c4ebbe370.png)

For example, just look at the conjunct letters of the words 'বিক্রিয়া', & 'শ্রেণীবিভাগ' in the <\section> command. They are awkward.

Although the output pdf file has no problem with conjunct letters, it will be great if the editor shows the conjunct letters correctly. I have tried changing font at `Options -> Configure` TeXstudio but that didn't work for me. Can you suggest a way for this?

(This is my first activity in GitHub. Don't know that much about it. If you suggest any edit for more clarity of the issue, I will try to do that.)

**Comment by sunderme** [comment]
you can try to play with options/advanced editor/hacks/workarounds -> display settings (at the bottom of that config page)
Apart from that I don't think that I can help as I can't teel what it is supposed to look like.

**Comment by Al-Imran-Abir** [comment]
Thanks, sunderme. I have been able to solve the problem. I just needed to change the font family to a Bengali font (like Nirmala UI, Shonar Bangla, Kalpurush, etc) at `options-> Configure TeX -> Editor`.
