### ISSUE TITLE
Line Number Missing 

### ISSUE THREAD

**Issue by SanjuSoni** [texstudio-org/texstudio#1172]
Dear All,
I am unable to get the line number in the editor due to which I am not able to get the error mentioned at particular line.

Kindly, help me to fix it

Here, is the attached file for reference in which the line number is not showing.

Thanks.

![line number missing](https://user-images.githubusercontent.com/61820415/87239882-b4900380-c431-11ea-9a0f-daf96a088142.JPG)

**Comment by timhoffm** [comment]
Check your settings under `Editor / Line Numbers`.

Note also that you can click an error in the error list to move to the respective line in the editor.

**Comment by SanjuSoni** [comment]
Thanks Texstudio-Org/Texstudio,
Now I am getting the proper line numbers

**Comment by wanjiac** [comment]
Thanks, I seek the Line Number in Adv. Editor for vvvvvvery long time !!!!

**Comment by muzimuzhi** [comment]
@wanjiac 
PS: You can make use of the "option filter" at the lower left corner of configure window. For example, filter by "line/number/line number"
![image](https://user-images.githubusercontent.com/6376638/88027433-d132e680-cb69-11ea-82bb-af76ff2d5b7a.png)
