### ISSUE TITLE
Is it possible to have TeXstudio list available labels for a custom command which is based on \ref?

### ISSUE THREAD

**Issue by henrikgit** [texstudio-org/texstudio#1173]
I defined a custom command:

    \newcommand{\fullref}[1]{\autoref{#1}, \autopageref{#1}}

Is it possible to have TeXstudio list available labels from my document, so that I can use that custom command like I am using `\ref` or `\autoref` and similar commands?

Note: the option to load included files is checked/activated (in the options in the **Editor** tab).

### Environment
- TeXstudio: TeXstudio 2.12.22 (git n/a)
- Qt: Nutze Qt-Version 5.15.0, kompiliert mit Qt 5.14.0
- OS: Linux (Arch)
- TeX distribution: Tex Live

### Expected behavior
I'd like TeXstudio to show available labels when I enter the brackets for `\fullref{#1}`.

### Actual behavior
* TeXstudio does not show the labels when the cursor is within the brackets 

### How to reproduce
Create a custom command, e. g. `\newcommand{\fullref}[1]{\autoref{#1}, \autopageref{#1}}` and start typing it.

**Comment by muzimuzhi** [comment]
You need to record `\fullref` in cwl file.

For example,
 - In directory `~/.config/texstudio/completion/user`, create a file `my-macros.cwl` containing line `\fullref{label}#r`.
 - Reopen texstudio, in "Configure TeXstudio -> Completion -> Permanently active completion files", check `my-macros.cwl`.
 - Done.

Related documentation:
 - [FAQ - Where are cwl files stored?](https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions#where-are-cwl-files-stored)
 - [User manual - 4.14 Description of the cwl format](https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html#CWLDESCRIPTION)

**Comment by sunderme** [comment]
this is answered

**Comment by henrikgit** [comment]
Thank you. It was super easy. I just had to put `\fullref{key}#r` in my custom completion file. :)
