### ISSUE TITLE
Associate LaTeX files with TeXstudio on install

### ISSUE THREAD

**Issue by TBemrose** [texstudio-org/texstudio#118]
### Environment
- TeXstudio: 2.12.8
- Qt: 5.8.0 (compiled with 5.8.0 R)
- OS: Win 10.0.16299.371
- TeX distribution: MiKTeX

### Expected behavior
Associate with LaTeX files upon installation.  Even if another program is later installed that takes over the file association, Windows 10 will know that TeXstudio is set up to handle LaTeX files and can quickly be set to change the Open/Edit/etc commands and icon back to TeXstudio.

### Actual behavior
*.tex files type associated with TeXworks.  Windows 10 doesn't know that TeXstudio can handle any file types which makes associating file types with it a manual process.

### How to reproduce
I recently reformatted my system and started with a fresh install of everything.  Instead of installing proTeXt as I had in the past, I just went to download MiKTeX and TeXstudio directly.  I don't recall which order I installed them (though I should have installed them in that order).  Today I noticed *.tex files were associated with TeXworks.  I went to

- Settings >> Apps >> Set defaults by app

and TeXstudio is not listed.  This tells me that when its installed, it doesn't give Windows a list of file types to associate with TeXstudio.  If TeXstudio were on that list, I could click on it, click the Manage button, and then tell it to take back the association with every file type it can handle.

This also means I couldn't go to 

- Settings >> Apps >> Choose default apps by file type

and scroll down to *.tex to try to change it there, since Windows only offered TeXworks and "Look for an app in the Store".

Instead I had to:
- Right click a *.tex file >> Properties >> General >> Change... (button) >> "Look for another app on this PC" >> browse to texstudio.exe

This method is rather crude, only creating an Open action for that file type, and worst, it gives all *.tex files the *same* icon as the executable for TeXstudio, making file.tex and texstudio.exe visually identical.

I then went and downloaded some 3rd party software to edit the file type icon, because Win 10 doesn't provide that capability anymore.  I figured I'd be able to point it to texstudio.exe and find a second icon contained in the executable file for associating with document files (usually the icon will display a sheet of paper with a small copy of the app icon in the corner), but didn't find any such icon.  This is further evidence to me that TeXstudio is making no effort to associate itself with LaTeX files.

**Comment by sunderme** [comment]
.tex is automatically associated in future releases (commit fa99136d6b48ba76884bcdefabdad878de53eba3)
