### ISSUE TITLE
lstlisting environment disables spell checking for the remainder of the document

### ISSUE THREAD

**Issue by laikoni** [texstudio-org/texstudio#1184]
### Environment
- TeXstudio:  2.12.22 (git 2.12.22)
- Qt: Using Qt Version 5.12.1, compiled with Qt 5.12.1 R
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
Spell checking should work both before and after an `lstlisting` environment. (Maybe it should be disabled inside the environment, I don't really know).

### Actual behavior
After `\end{lstlisting}`, spell checking is disabled for the rest of the document.

![image](https://user-images.githubusercontent.com/23499430/87979250-0ab81300-cad2-11ea-8983-bcbd84b338bc.png)

### How to reproduce
Start e.g. the system report (Help > Check LaTeX installation) and have online spell checking enabled.

![image](https://user-images.githubusercontent.com/23499430/87979622-a21d6600-cad2-11ea-9990-a1fa2c45a452.png)

Notice all the red squiggly lines.

Copy the following somewhere in there:
```
\begin{lstlisting}
content...
\end{lstlisting}
```
![image](https://user-images.githubusercontent.com/23499430/87979786-e1e44d80-cad2-11ea-809c-3e32edd5d032.png)

Notice how all squiggly lines below the environment are gone. Tested with languages `en_US`, `en_GB` and `de_DE`, same behaviour.

**Comment by muzimuzhi** [comment]
Works ok in [texstudio 3.0.0beta2](https://github.com/texstudio-org/texstudio/releases/tag/3.0.0beta2), using the following example.
```tex
\documentclass{article}
\usepackage{listings}

\begin{document}
content conten conte
\begin{lstlisting}
content...
\end{lstlisting}

content conten conte
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/87993739-dcf8bb80-cb1d-11ea-8211-6be1ca9f96aa.png)




> Start e.g. the system report (Help > Check LaTeX installation) and have online spell checking enabled.

Besides, you mentioned "online spell checking", which online service do you use and how do you configured to use it?

**Comment by laikoni** [comment]
I do not use any online service, I just read in a comment by [sunderme](https://github.com/sunderme) on a different issue that it is called like that, likely in opposition to _Tools > Check Spelling..._

> "online" checking is spell checking as you type, the red wiggle line shows misspelled words.
> Unless you have deactivated it, it should be active by default.
https://github.com/texstudio-org/texstudio/issues/479#issuecomment-455681418

**Comment by laikoni** [comment]
> 
> Works ok in [texstudio 3.0.0beta2](https://github.com/texstudio-org/texstudio/releases/tag/3.0.0beta2), using the following example.
> 

Works for me as well again after installing 3.0.0beta2. Thanks!
