### ISSUE TITLE
Shortcut for Hide inline preview

### ISSUE THREAD

**Issue by desk7** [texstudio-org/texstudio#1185]
### Environment
- TeXstudio: 2.12.22
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution: texlive

I know that you can use the shortcut <kbd>Alt</kbd>+<kbd>p</kbd> to view the inline preview. I cannot find a shortcut to hide the inline preview. Does it exist? If not so, could you add it?

**Comment by sunderme** [comment]
you can set a shortcut to idefix/clear inline preview yourself.

**Comment by desk7** [comment]
I just discovered a strange behaviour, I don't know it it expected: after enabling preview of a math formula,

- if I right-click on the math preview and click on hide, the preview diseappears as expected
- if I go to Idefix and click on hide, the preview disappear **but** a blank rectangle remains where the preview was.

Is the last behaviour expected? I'd like the preview to disappear completely

**Comment by sunderme** [comment]
not reproducible
it is the same function.

**Comment by muzimuzhi** [comment]
> I just discovered a strange behaviour, I don't know it it expected: after enabling preview of a math formula,
> 
> * if I right-click on the math preview and click on hide, the preview diseappears as expected
> * if I go to Idefix and click on hide, the preview disappear **but** a blank rectangle remains where the preview was.
> 
> Is the last behaviour expected? I'd like the preview to disappear completely.

@desk7 
1. Which display mode are you using? You can see it in "Configure TeXstudio -> Preview".
2. Does it reproduce with latest pre-release [texstudio 3.0.0beta3](https://github.com/texstudio-org/texstudio/releases/tag/3.0.0beta3)?

**Comment by desk7** [comment]
@muzimuzhi 
I use "Inline" preview mode.

To be clearer, these are some screen recording.

***
- TeXstudio: 2.12.22
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution: texlive

Working as expected when I right-click on the math preview
![texstudio-12 2 22-working](https://user-images.githubusercontent.com/46022640/88283123-5c32ee80-ccda-11ea-9908-05fd68f8dbb9.gif)

Bug when I use the menu on the selected latex text
![texstudio-12 2 22-not-working](https://user-images.githubusercontent.com/46022640/88283206-7ec50780-ccda-11ea-90dd-a77eed1156b4.gif)
***
I've tested the beta portable version you linked to and not only the bug is not fixed but I found another bug: to preview a math equation I need to manually select the equation environment while in the current version I have only to right-click on any point on the equation environment and click preview.

Example with the 2 bugs:
![texstudio-beta-not-workinh](https://user-images.githubusercontent.com/46022640/88283430-e0857180-ccda-11ea-813d-055af6e3c3b4.gif)

**Comment by muzimuzhi** [comment]
@desk7 


First problem:

> * if I go to Idefix and click on hide, the (inline) preview disappear **but** a blank rectangle remains where the preview was.

Second problem:

> to preview a math equation I need to manually select the equation environment while in the current version (2.12.22) I have only to right-click on any point on the equation environment and click preview.

Test results: Yes means can reproduce, no means cannot.

|                | 2.12.22 | 3.0.0beta3 |
| -------------- | ------- | ---------- |
| First problem  |         |            |
| desk7          | yes     | yes        |
| Muzimuzhi      | yes     | no         |
| Second problem |         |            |
| desk7          | no      | yes        |
| muzimuzhi      | no      | Yes        |

I tested on macOS 10.15.6.
