### ISSUE TITLE
TeXstudio 2.12.22 crashes every time I operate the internal previewer

### ISSUE THREAD

**Issue by ONLYA** [texstudio-org/texstudio#1186]
### Environment
- TeXstudio: 2.12.16 - 2.12.22
- Qt: 5.12.1
- OS: Windows 10

### Expected behavior
If I operate the internal viewer(e.g. close it, windowed viewer, etc), it will do the action without crashing. If the document is "Compile & View"ed, the compiled pdf will appear in Internal viewer without crashing the program.

### Actual behavior
Any action related to the internal viewer will cause the crash of the program all the time. If I *only* build the document, the environment will **_not_** crash.

### How to reproduce
For me, just open texstudio, and try to "Build & View" any document or operate the already opened pdf displayed in the internal viewer. Then it will crash.
(P.S. I have updated the Texstudio to the latest version, but this annoying problem still occurs.)

**Comment by sunderme** [comment]
Can you try the portable version ?

**Comment by ONLYA** [comment]
Yes, portable version works like a charm. Probably I just need to uninstall and install it...

**Comment by ONLYA** [comment]
Oh no... I have uninstalled and installed TexStudio 3 times. However, nothing changes including the opened files last time when I close it. It still crashes when I operate Internal PDF viewer. I doubt there may be a global config stuff lying somewhere in my disk.

**Comment by sunderme** [comment]
look for texstudio.ini in appdata...

**Comment by ONLYA** [comment]
Thank you! I just delete the whole folder containing texstudio.ini then reinstall it again, and it works fine now.
I have a suggestion for uninstallation program to have an option to delete all related data from the disk. 
I will close this issue as my problem has been solved. Thanks for your help again.
