### ISSUE TITLE
Math-keyword highlighted as number

### ISSUE THREAD

**Issue by sergiokapone** [texstudio-org/texstudio#1188]
### Environment
- TeXstudio: TeXstudio 3.00.00 (git 3.0.0beta3-4-gbafd7ce)
- Qt: Using Qt Version 5.12.1, compiled with Qt 5.12.1 R
- OS: Win 10
- TeX distribution: texlive2020

### Actual behavior
Math-keyword highlighted as number, and the color of math-wor not does not affect

Last working build is TeXstudio 3.00.00 (git 3.0.0beta1-15-g38f416e)

**Comment by sunderme** [comment]
please present a screen shot
looks okay here ...

**Comment by sergiokapone** [comment]
An old version [https://i.imgur.com/geFaI9c.jpg](url)

A new one

**Comment by sunderme** [comment]
checked again with beta3 on windows, no issue.

so, please start by checking a tcs without your texstudio.ini ...

**Comment by sergiokapone** [comment]
Without my .ini it's work/ Yes, some troble in my ini. 
Whhen I copy paste [Formats] and [FormatsDark] from my .ini into a new one, the proplem appear again.

**Comment by sunderme** [comment]
you would have to narrow it down further ...

**Comment by sergiokapone** [comment]
TXS think math-keyword is a keyword

**Comment by sunderme** [comment]
maybe you post your formats setting ?

**Comment by sergiokapone** [comment]
My [ini](https://drive.google.com/file/d/1nWe8sP0G8EEQ9m3fRv9NN8FNK-6-L2xH/view?usp=sharing)

**Comment by sunderme** [comment]
well, you have assigned priorities to the different highlight elements (all -1 by default)
Until recently, that was mostly ignored but not any more.
keyword has a higher priority than math-keyword, hence ...
