### ISSUE TITLE
Cursor moving from a view to another

### ISSUE THREAD

**Issue by McAlyster** [texstudio-org/texstudio#1193]
### Environment
- TeXstudio: 2.12.22 
- Qt: 5.14.0
- OS: OSX 10.14.6
- TeX distribution: 

### Actual behavior
Hi, 
did someone already had the problem that the cursor in Texstudio would move from a view to another without any particular reason when 2 docs open, one in each view ? 
I'm working with a macbook pro and priorly thought it was due to a too sensitive trackpad and unwanted movements but the problem persists even after I've turned off the "tap to click" mode ... 

Thank you for your help : ) 

### How to reproduce
No particular action except typing on keyboard.

**Comment by muzimuzhi** [comment]
Does the word "view" here mean 
![image](https://user-images.githubusercontent.com/6376638/89108871-ce3fcc00-d46e-11ea-8bff-6313d3a32a6b.png)

**Comment by McAlyster** [comment]
Yes, precisely. 
But I'm doubting about my keyboard. It was changed (Apple replacement program) and I can't exclude that it is because of unsolicited shortcuts ...

**Comment by McAlyster** [comment]
Hmmmm ... I think this is the keyboard, you should delete the issue, it does not seem to be related to the software.

**Comment by muzimuzhi** [comment]
No need to delete, but you can close the issue yourself.
