### ISSUE TITLE
Bug: Problem with custom windows color sheme in options

### ISSUE THREAD

**Issue by Parlazo** [texstudio-org/texstudio#1195]
My windows is dark and i also use dark colors in the syntax settings.
i did click on use a custom sheme in the options
i did click ok
then all was bright and not dark any more
then i did uncheck this custom theme stuff in the options and glick ok again
every thing did return to dark but the file tabs on top and the line numbers at the left side did remain bright until a restart
after TexStudio restart it was fine again

**Comment by sunderme** [comment]
there is a reason why some default info should be given.
Please state OS, version etc and please follow the suggested flow of stating the issue.

**Comment by sunderme** [comment]
insufficient info
