### ISSUE TITLE
enhancement: line number and colon number in statusbar field

### ISSUE THREAD

**Issue by Parlazo** [texstudio-org/texstudio#1196]
If possible please add two little fields to the status bar below the editor with the active Line Number and the active Colon Number of the cursor position.
Most text editors have this function and it can be very handy and i guess many people are used to it

thanks for every thing :)

**Comment by muzimuzhi** [comment]
I think they're already there.
![image](https://user-images.githubusercontent.com/6376638/89126746-c0478500-d51a-11ea-8086-db244e6cf5e1.png)
