### ISSUE TITLE
Remove autocomplete window when it's empty

### ISSUE THREAD

**Issue by mike352** [texstudio-org/texstudio#120]
### Environment
- TeXstudio: 2.12.8
- Qt: 5.8.0
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
I expect that when there are no options left for autocomplete that the autocomplete window will disappear and stop taking up so much space.

### Actual behavior
The autocomplete window stays around once activated and will not clear unless ESC is pressed.

**Comment by sunderme** [comment]
I don't think that is the way to go, as you could want to change the last letter or change to a different tab,e.g. all tab.

**Comment by timhoffm** [comment]
The window should also disappear when your command is complete, i.e. when typing { or space.
