### ISSUE TITLE
TeXstudio does not immediately recognize all commands, inconsistent behaviour after toggling Inline Checking

### ISSUE THREAD

**Issue by shredEngineer** [texstudio-org/texstudio#1202]
### Environment
- TeXstudio: TeXstudio 3.00.00 (git 3.0.0beta2), but I've got the erroneous behaviour in 2.12.22 aswell.
- Qt: Qt-Version 5.12.1
- OS: Windows 10
- TeX distribution: MiKTeX

### Expected behavior
When I use `\documentclass{scrreprt}`, TeXstudio should recognize commands like `\KOMAoptions` and not highlight these as unknown.
Also, after disabling and reenabling _Inline Checking_, the commands TeXstudio does or doesn't recognize about should not change (because, why should it.)

### Actual behavior
When I open TeXstudio, all `\KOMAoptions` keywords (e.g.) are marked as unknown.
After toggling Inline Checking, however, TeXstudio suddenly _does_ recognize the `\KOMAoptions` keywords and doesn't highlight them as unrecognized.

### How to reproduce
Disable Inline Checking. Enable Inline Checking. Now more commands are recognized than before.
This is inconsistent behaviour in itself, but it does show that TeXstudio does somehow know these commands after all.

There just seems to be some initialization / caching issue?

**Comment by muzimuzhi** [comment]
Similar to #952. In short, the highlighting and/or auto-completion info for KOMA bundle recorded in [`class-scrartcl,scrreprt,scrbook.cwl`](https://github.com/texstudio-org/texstudio/blob/master/completion/class-scrartcl,scrreprt,scrbook.cwl) is far from comprehensive. `cwl` files contain semantic info rather than just the command name, so it takes human efforts to update and maintain them. 

I've done several cwl contributions but since I seldom use KOMA bundle, I am not familiar with it... Welcome to contribute to texstudio!

**Comment by shredEngineer** [comment]
Thank you very much for the quick reaction! I would very much like to contribute the .cwl repository.
But first, let me understand how this works:

1. Ok, `class-scrartcl,scrreprt,scrbook.cwl` sounds good for starters. But it's not on my drive. Does the standard installation NOT contain all these files, and why? Should I manually insert it into the `completion/user` folder?

2. I just did another file search, and despite having compiled many times using the scrreprt class, there is NO scrreprt.cwl file to be found on my drive. However, the docs (on Sourceforge, I might add) claim that TeXstudio tries to auto-generate .cwl files for new packages.
How (well) does this process work, and how can I monitor or influence this?

Best regards!

**Comment by muzimuzhi** [comment]
> 1. [...] so is it actually hardcoded into the binaries?

See the related [wiki / FAQ / Where are cwl files stored?](https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions#where-are-cwl-files-stored):

> TXS ships with a number of built-in cwl files. You cannot see them because they are compiled into the executable, however you may have a look at the [source code of the built-in cwls](https://github.com/texstudio-org/texstudio/tree/master/completion).

------

> Does this mean TeXstudio will never try to auto-generate anything for scrreprt?

Yes, I think so. Also see related section in [user manual](https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html), sec. 14.14.5:

> cwl files can be provided from three locations. If present, the user provided cwl is taken, if not built-in versions are taken. As a last resort, txs automatically generates cwls from latex styles, though these only serve to provide syntax information. Context information for arguments are not available and no completion hints are given.

**Comment by shredEngineer** [comment]
Thank you for further clarifying the matter. However, when I look at the built-in file `class-scrartcl,scrreprt,scrbook.cwl`, there clearly exists a command `\addtokomafont`, e.g. But this command is also NOT immediately recognized by TeXstudio.

I **have** to toggle Inline Checking, then it **does** get recognized! Take a look at the attached screenshots; one directly after TeXstudio started, and the other one after toggling Inline Checking (during the same session).

So, despite the .cwl files being incomplete (which I can understand), there clearly is some synchronization error (which I cannot understand)!
Like, TeXstudio "forgets" to read the built-in .cwl files at application start, but does so after toggling Inline Checking.

Before toggling:
![Anmerkung 2020-08-10 020026](https://user-images.githubusercontent.com/39415391/89744471-8263d700-daad-11ea-9ae4-46817d6755bd.png)

After toggling, TeXstudio somehow gets smarter (or cares less? I don't know).
![Anmerkung 2020-08-10 020126](https://user-images.githubusercontent.com/39415391/89744472-82fc6d80-daad-11ea-8e58-f65f97fd4ce5.png)

**Comment by muzimuzhi** [comment]
> ### How to reproduce
> Disable Inline Checking. Enable Inline Checking. Now more commands are recognized than before.
> This is inconsistent behaviour in itself, but it does show that TeXstudio does somehow know these commands after all.
> 
> There just seems to be some initialization / caching issue?

Sorry I misunderstood your problem before. Using texstudio 3.0.0rc1 on macOS, the problem is not reproducible on my side. Would you please try [3.0.0rc1](https://github.com/texstudio-org/texstudio/releases/tag/3.0.0rc1)?

**Comment by sunderme** [comment]
you should use the latest dev build, see texstudio.org.
if the issue persists, please prove a document which shows the issue.

**Comment by shredEngineer** [comment]
@muzimuzhi: No problem! -- I just tried with 3.0.0rc1, but unfortunately I've got the same behaviour.
@sunderme: You are right, I should've provided an MWE right from the beginning. I attached a .zip to this comment.

The contents are simple and very short
[Issue.zip](https://github.com/texstudio-org/texstudio/files/5050726/Issue.zip)
:
- /Issue/Foo/Bar.sty
- /Issue/Project/Main.sty

**Comment by sunderme** [comment]
I am not sure what the MWE is good for. 

local sty files are not analyzed. You need to provide a cwl file.
\input{...tex} is read and analyzed by txs.
There is no intention to change that behavior.

Apart from that the MWE is completely unrelated to the stated issue ?

**Comment by shredEngineer** [comment]
> I am not sure what the MWE is good for.
> [...]
> Apart from that the MWE is completely unrelated to the stated issue ?
It does show a reasonable use case where TeXstudio fails to perform as intended -- at least in my opinion.
Because the issue is about not recognizing some keywords, I provided a very minimal example which results in TeXstudio highlighting 

> local sty files are not analyzed. You need to provide a cwl file.
> There is no intention to change that behavior.
This issue is not about introducing new keywords, even though I learnt about this possibly only in the discussion above, yes.
It is, however, about parsing the ones it DOES know about, and in the best case doing so consistently. I.e., after application start and not after the user toggled some seemingly unrelated option.
It is about TeXstudio going into the included files -- either through `\usepackage` or `\input` -- and recognizing the depenencies / loaded packages to provide consistent syntax highlighting.

> \input{...tex} is read and analyzed by txs.
Yes. But NOT if the .tex is in a "lower" folder relative to the main .tex file. I just checked by turning my .sty into a regular .tex file and placing it in the main directory!
The same goes for the "package" version! If I place the .sty in the main directory, everything WORKS as intended!
So the inconsistency which this issue addresses has ALSO to do with a "relative path" problem.

All in all, I totally agree that this is another issue, and I will open another issue right now, accordingly!
I apologize for not having made this distinction earlier. I'm just now getting the mechanisms by which TeXstudio actually works in the background.

Thank you very much to this point! :)

**Comment by sunderme** [comment]
the point is that packages are usually organized differently (provided by the tex distribution and static) and it makes sense to provide more syntax information for that (hence the cwl). 
Included files are just analyzed for defined commands and used packages, no deeper syntax context can be determined.
Whatever is happening in your real example, it looks rather like a unintended side effect than a intended use case ...

**Comment by muzimuzhi** [comment]
Maybe there is something texstudio can do to load the newly autogenerated cwl file immediately.

With following directory structure and files ([test-autogenerated-cwl.zip](https://github.com/texstudio-org/texstudio/files/5053166/test-autogenerated-cwl.zip)),
```
$ tree
.
├── Bar.sty
└── Main.tex

0 directories, 2 files

$ cat Bar.sty
\usepackage{amsmath}
\newcommand{\cmd}{def}

$ cat Main.tex
\documentclass{article}
\usepackage{Bar}
\begin{document}
content
\end{document}
```
 - Remove possibly existing `Bar.cwl` in directory of autogenerated cwls.
 - Open `Main.tex`, then `Bar.cwl` containing single non-comment line `\cmd#S` is autogenerated.
   - There is no `#include:amsmath` in `Bar.cwl`. This is the expected one.
   - But `\cmd` in `Main.tex` is marked unrecognized. The output of "Help -> Check Active Completion Files" contains `Bar.cwl`, but nothing is added. It seems this one can be improved.
```
/path/to/Main.tex: #latex-document.cwl, latex-dev.cwl, #tex.cwl, textcomp.cwl, #Bar.cwl
[....]
------------------- Package #Bar.cwl: ---------------------
	possible commands
	special def commands
	special treatment commands
	option Commands: 
	kinds
	all commands: 
[...]
```
 - Reopen texstudio, then open `Main.tex`, now `\cmd` is recognized.
