### ISSUE TITLE
TXS 3.0 saves unchanged subfile before compiling

### ISSUE THREAD

**Issue by hair-splitter** [texstudio-org/texstudio#1206]
### Environment
- TeXstudio: TeXstudio 3.0.0 (git 3.0.0rc1-9-g9c80e10)
- Qt: Qt 5.12.1 R
- OS: Windows 10
- TeX distribution: texlive

### Expected behavior
TXS saves a project subfile before compiling, if there are some change in it.

### Actual behavior
TXS saves a project subfile before compiling, although there wasn't any change in it.

### How to reproduce
There are two tex files.

main.tex content:
    \documentclass{article}
    \begin{document}
    \input{sub}
    \end{document}

sub.tex content:
    text

1. Open TXS
1. Open main.tex
1. Open sub.tex
1. Close sub.tex
1. Compile main.tex

The bug: TXS saves sub.tex file, although there wasn't any change in it.

**Comment by sunderme** [comment]
how do you determine that the included file is saved ?
