### ISSUE TITLE
3.0.0rc2: no .dmg asset for macOS

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#1209]
See https://github.com/texstudio-org/texstudio/releases/tag/3.0.0rc2.

Is this on purpose or by mistake?

**Comment by sunderme** [comment]
never on purpose, travis always builds all variants (or at least tries to ...)

**Comment by sunderme** [comment]
glitch in travis which was not marked as error ...
tagged a new rc ...

**Comment by sunderme** [comment]
this time it worked.

**Comment by muzimuzhi** [comment]
Thanks.
