### ISSUE TITLE
Can texstudio automatically complete filenames?

### ISSUE THREAD

**Issue by thu1911** [texstudio-org/texstudio#1210]
### Environment
- TeXstudio: TeXstudio 2.12.16 (git 2.12.16)
- Qt: Using Qt Version 5.12.3, compiled with Qt 5.12.3 R
- OS: OS 10.25.6
- TeX distribution: mactex

### Expected behavior
I want to automatically complete figure names in `\includegraphics` command

### Actual behavior
No methods to do that.

**Comment by muzimuzhi** [comment]
I guess this is from TeX-SX question [How to auto-complete filenames in texstudio](https://tex.stackexchange.com/q/559075/). But the description shown in current issue is a bit different from the TeX-SX one.

 - If you don't use `\graphicspath{{./figures/}}`, then `\includegraphics{<cursor here>}` will trigger auto-completion of the file list under working directory.
 - If `\graphicspath{{./figures/}}` is used, I'm not sure whether TeXstudio will provide a file list under both working directory and `./figures/` sub-directory.

**Comment by thu1911** [comment]
@muzimuzhi Thank you. How to trigger auto-completion, you mean `ctrl+space`? For the second case, i.e., using `\graphicspath{{./figures/}}` , I can not get images under `./figures/` with ctrl+space

**Comment by muzimuzhi** [comment]
> For the second case, i.e., using `\graphicspath{{./figures/}}` , I can not get images under `./figures/` with ctrl+space

Yes, that's the case I commented under TeX-SX question with

> TeXstudio doesn't have this utility. ([link to this comment](https://tex.stackexchange.com/questions/559075/how-to-auto-complete-filenames-in-texstudio#comment1409959_559075))

Because currently TeXstudio don't (specially) parse the argument of `\graphicspath`. (I'm not 100% sure if there is any workarounds.)
