### ISSUE TITLE
Macros are added twice

### ISSUE THREAD

**Issue by clecap** [texstudio-org/texstudio#1213]
### Environment
- TeXstudio: TeXstudio 3.00.00 (git 3.0.0alpha6-30-g7c53058)
- Qt: Using Qt Version 5.15.0, compiled with Qt 5.15.0 R
- OS: MacOS 10.15.3 Catalina
- TeX distribution: TeX Live 2020

### Expected behavior
Newly added macro only entered once upon use.

### Actual behavior
Newly added macro entered twice upon use under certain conditions.

### How to reproduce
0) Open existing LaTeX document
1) Menu: Edit Macros...
2) Button:  + Add
3) Enter Name: TESTING
4) Enter LaTeX Content: TESTCONTENT
5) Button: Ok
6) Click into Latex editor into a free text area (not on an existing environment name)
7) Click on name "TESTING" of newly added Macro in the Macros sidebar
8) Observe that "TESTCONTENTTESTCONTENT" is added in the editor (twice instead of once).

Note 1: If you doubleclick the name of a Latex environment, then "TESTCONTENT" is added only once, as it should. The bug depends on the context of the editor.

Note 2: Now quit Texstudio and reopen it. Click on name "TESTING" in the Macros sidebar. Now "TESTCONTENT" is added only once, as it should, independently of the cursor position in the editor.

Note 3: The double entry effect shows up not only for the specific macro just added but also for macros which had been added earlier. Again, the "solution" is to quit Texstudio and restart - then no macro is added twice, until you again add a fresh macro and the mystery starts again.

Observation: It looks like s o m e status handling of the macro editor is done incorrectly.

Disclaimer: I am not familiar with Qt and the source of texstudio. Reporting here on the development version only to help the devs.

**Comment by sunderme** [comment]
works here (linux)

**Comment by clecap** [comment]
@sunderme: Which version did you use?

I also did not have the bug in linux on one of the dev versions but cannot recall the exact version number since I then moved to Mac. Now I have it reproducibly on two Mac machines.

**Comment by sunderme** [comment]
latest (git head)

**Comment by sunderme** [comment]
okay, found and fixed
