### ISSUE TITLE
CI on github

### ISSUE THREAD

**Issue by sunderme** [texstudio-org/texstudio#1216]
Since github offers actions to implement CI/CD, it may be an option to use this instead of travis.
Any help is welcome to extend the current actions.
Current set-up for travis can be seen in ./travis-ci/...

Wanted ci flows are:

- [ ] build OSX with homebrew with packaging
- [ ] build windows with installer (texworks seems to use msys, we have been using cross-compiling with mxe so far)
- [ ] build linux release with appimage packaging
- [ ] deployment on release
- [ ] deployment to bintray on every push

**Comment by Piraty** [comment]
why not stick with travis?

**Comment by sunderme** [comment]
There was a glitch on travis that hid that it was working. So, I am fine with the current set-up but some more support on CD is welcome. GitHub may be simpler for that.

**Comment by sunderme** [comment]
Done
