### ISSUE TITLE
macOS background colore

### ISSUE THREAD

**Issue by Tealk** [texstudio-org/texstudio#1217]
### Environment
- TeXstudio 2.12.22 (git 2.12.22)
- Nutze Qt-Version 5.14.0, kompiliert mit Qt 5.14.0 R
- OS: macOS 11

when macos switches to the dark theme, the marked line can no longer be read.
![image](https://user-images.githubusercontent.com/12276250/90990888-3af94280-e5a5-11ea-9144-de47f14e412a.png)

**Comment by sunderme** [comment]
please try txs 3.0.0 (available from github , releases)

**Comment by Tealk** [comment]
Works great, thanks.
