### ISSUE TITLE
Resize Built-In Viewer

### ISSUE THREAD

**Issue by JohnWestlund** [texstudio-org/texstudio#1219]
### Environment
- TeXstudio: 3.0
- Qt: 
- OS: MacOS 10.14.6
- TeX distribution: 

### Expected behavior
When the internal viewer is integrated into the main TexStudio window, it should be possible to drag the left edge of the internal viewer pane to resize the width of the internal viewer.

### Actual behavior
The internal viewer always takes up 50% of the main TexStudio window when open.

Workaround: Pop the internal viewer out ("Windowed Viewer") and resize the window.

### How to reproduce
Build and View.

**Comment by sunderme** [comment]
you are talking about the resizing not being persistent?

**Comment by JohnWestlund** [comment]
I must have tried 100 times and couldn't get it to resize. Just tried again managed to get it to work. It's a little counterintuitive that you have to grab to the left of the internal viewer panel (where the scroll bar for the editor panel appears)

I was kind of expecting the mouse cursor to change to indicate I could resize the panels.

**Comment by sunderme** [comment]
so, all good ?
