### ISSUE TITLE
Auto-detection of preferred language for spellchecker

### ISSUE THREAD

**Issue by zoelx** [texstudio-org/texstudio#122]
### Environment
- TeXstudio: 2.12.6
- Qt: 5.7.1 R
- OS: Mac
- TeX distribution: mactex

### Request
Changing from one language to another for spellchecking is quite tedious as you have to go into the settings to choose the language from a list.

It would be a nice feature of TeXstudio to use the information from the included packages on language (or some other form of auto-detection found in other text editors) to change the spellchecking accordingly. Making the language setting available to single files would also be a sufficient solution.

**Comment by sunderme** [comment]
You can change to spell checker language in the status panel  (right at the bottom of the txs window)
Furthermore you can set the language as % !Tex language ... in the document itsels, see manual or option in the status panel.
