### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by zalois** [texstudio-org/texstudio#1220]
![Screenshot_2020-08-25_12-29-30](https://user-images.githubusercontent.com/9462454/91123358-3fba1580-e6cf-11ea-9697-8b4858746bd9.png)

### Environment
- TeXstudio:   3.0.0
- Qt:   qt5
- OS:  slackware 64 current
- TeX distribution:  TeX Live 2020

**Comment by sunderme** [comment]
your compiler crashes, not really an txs issue.
txs builds fine on quite a range on linuxes, so I don't see how txs causes it.

Have you tried make clean.

**Comment by zalois** [comment]
> your compiler crashes, not really an txs issue.
> txs builds fine on quite a range on linuxes, so I don't see how txs causes it.
> 
> Have you tried make clean ?

i made clean and it can work now, thank you!
