### ISSUE TITLE
macOS High Sierra: 3.0 crash PDFRenderEngine

### ISSUE THREAD

**Issue by KenjutsuGH** [texstudio-org/texstudio#1221]
### Environment
- TeXstudio: 3.0.0 (installed via Homebrew)
- Qt: Unknown, txs now crash on startup
- OS: macOS High Sierra 10.13.6
- TeX distribution: MacTeX 2020

### Expected behavior
Preview PDF using the internal PDF viewer

### Actual behavior
```
Crashed Thread:        23  PDFRenderEngine

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/texstudio.app/Contents/MacOS/../Frameworks/libpoppler.94.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by sunderme** [comment]
since we don't provide the homebrew cask, no idea why it crashes ... looks like a poppler issue.
@muzimuzhi ?

**Comment by muzimuzhi** [comment]
@KenjutsuGH 
Works well on macOS 10.15.6 here. It seems it is your macOS version 10.13 that causes the problem. Perhaps you can try to compile by yourself, see the related [wiki](https://github.com/texstudio-org/texstudio/wiki/Compiling#mac).

Noted the `(which was built for Mac OS X 10.15)` part in error message.

> Dyld Error Message:
>   Symbol not found: ____chkstk_darwin
>   Referenced from: /Applications/texstudio.app/Contents/MacOS/../Frameworks/libpoppler.94.dylib (which was built for Mac OS X 10.15)
>   Expected in: /usr/lib/libSystem.B.dylib

@sunderme Homebrew [cask for `texstudio`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/texstudio.rb) simply downloads `.dmg` from official release assets, hence I think homebrew is not the source of error.

**Comment by muzimuzhi** [comment]
Concerning the error message `Symbol not found: ____chkstk_darwin`, issue https://github.com/nodegui/nodegui/issues/391 is related.

> Looks like prebuilt binary support added on the latest version of nodegui (0.13 and up) has backfired in this case.
>
> The binaries are built on Github actions ci server and that uses mac os v10.15. And It seems its not compatible with macos 10.13
> from https://github.com/nodegui/nodegui/issues/391#issuecomment-582328912

> Need to add CMAKE_OSX_DEPLOYMENT_TARGET to an older version of mac than the latest to make the binary compatible.
> https://github.com/nodegui/nodegui/issues/391#issuecomment-582788859

**Comment by KenjutsuGH** [comment]
> @KenjutsuGH
> Works well on macOS 10.15.6 here. It seems it is your macOS version 10.13 that causes the problem. Perhaps you can try to compile by yourself, see the related [wiki](https://github.com/texstudio-org/texstudio/wiki/Compiling#mac).
> 
I was able to recompile from source and it is working :-)

TeXstudio 3.0.0 (git n/a)
Using Qt Version 5.15.0, compiled with Qt 5.15.0 R

**Comment by muzimuzhi** [comment]
With the following change, I locally built a `.dmg` (see [this release](https://github.com/muzimuzhi/texstudio/releases/tag/3.0.1-macOS)). Welcome to test whether it works on macOS 10.13. Note that it is compiled on macOS 10.15.6, with qt 5.15.0.

```diff
diff --git a/texstudio.pro b/texstudio.pro
index 82e8229e4..0a702d03b 100644
--- a/texstudio.pro
+++ b/texstudio.pro
@@ -153,7 +153,7 @@ macx {
         x86_64

     # QMAKE_MAC_SDK = /Developer/SDKs/MacOSX10.4u.sdk
-    # QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.4
+    QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.13
     target.path = /Applications
     manual.path = Contents/Resources/
     utilities.path = Contents/Resources/
```

**Comment by KenjutsuGH** [comment]
> ... Welcome to test whether it works on macOS 10.13. Note that it is compiled on macOS 10.15.6, with qt 5.15.0.
>

Unfortunately it does not work:

```
Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/Cellar/poppler/0.90.1/lib/libpoppler.101.dylib
  Referenced from: /private/var/folders/bp/6gs20d4n1c33z8cmrvz92p2h0000gn/T/AppTranslocation/D45B18F7-CE33-4692-A411-CDA2C7C175F2/d/texstudio.app/Contents/Frameworks/libpoppler-qt5.1.dylib
  Reason: image not found
```

**Comment by muzimuzhi** [comment]
@KenjutsuGH  It's a known problem, see https://github.com/texstudio-org/texstudio/issues/1257#issuecomment-688110081.

**Comment by lemerleau** [comment]
I had the same problem.
You can simply solve it by downloading the appropriate version for you Mac. 
I used the Textstudio 2.12 and it works perfectly. https://www.heise.de/download/product/texstudio-62955/download
