### ISSUE TITLE
Version 3.0.0 for Windows not available

### ISSUE THREAD

**Issue by BeerStud** [texstudio-org/texstudio#1222]
# Environment
- TeXstudio: 2.12.12
- Qt: 5.12.1
- OS: Windows 10 PRO Version 20H2
- TeX distribution: miktex

# Actual behavior

When starting TeXstudio, I am greeted with a screen informing me that version 3.0.0 is available and displaying a URL to download the newer version from. However, no newer version 3.0.0 is available on that site.

**Comment by bahaxid** [comment]
It also happened to me.
But, the version 3.0.0 actually can we access from [here](https://github.com/texstudio-org/texstudio/releases/tag/3.0.0).

**Comment by sunderme** [comment]
webpage has been update
