### ISSUE TITLE
Input fields in settings dialog unreadable with dark mode

### ISSUE THREAD

**Issue by schtandard** [texstudio-org/texstudio#1223]
### Environment
- TeXstudio: 3.0.0
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution: TeX Live 2020

### The Issue
When dark mode is selected and "Ignore Most System Colors" is enabled (which is necessary for the dark mode to really take effect), input fields and drop-down menus as well as buttons in the settings dialog are (close to) unreadable. They have a white (or very light) background with white text.

![colorproblem](https://user-images.githubusercontent.com/23075534/91166686-0a172b80-e6d3-11ea-8f57-fae2d60d9455.png)

### How to Reproduce
- In the settings panel (under "General"), select the color scheme "Modern - dark" and check "Ignore Most System Colors".
- Click "OK" and restart TeXstudio.
- Open the settings panel again.

**Comment by sunderme** [comment]
I would recommend to use *style* Adwaita dark and classic color scheme.
Ignore system colors can be off.
