### ISSUE TITLE
Background color makes (suspected) syntax errors hard to read in dark mode

### ISSUE THREAD

**Issue by schtandard** [texstudio-org/texstudio#1224]
### Environment
- TeXstudio: 3.0.0
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution: TeX Live 2020

### The Issue
In dark mode, the light background color of suspected syntax errors in combination with their also light font color makes them very hard to read. A dark red background color would be better.

![colorproblem](https://user-images.githubusercontent.com/23075534/91167497-59aa2700-e6d4-11ea-82ed-cdf5597b3ad7.png)

### How to reproduce
- In the settings panel (under "General"), select the color scheme "Modern - dark" and check "Ignore Most System Colors".
- Click "OK" and restart TeXstudio.
- Create a `.tex` file that makes TeXstudio suspect a syntax error. For example:
  ```latex
  \documentclass{article}
  
  \begin{document}
  
  Hello World\dots
  
  \end{document}
  ```

**Comment by sunderme** [comment]
You can change the color in options/syntax highlighting (latexSyntaxMistake)
If you have found a good color, we may put it in as default

**Comment by schtandard** [comment]
Dark red (`#aa0000`) works well.
