### ISSUE TITLE
user scripts with quotes don't work properly

### ISSUE THREAD

**Issue by sbtseiji** [texstudio-org/texstudio#1225]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

TeXstudio 3.0.0 (git 3.0.0)
Qt: 5.15.0 compiled with Qt5.15.0 R
OS: Mac OS 10.15.6
TeX: MacTeX 2020

Thank you for your great work. I've been experiencing problem in executing the user command that containing quotes in TexStudio 3.0.0. When I execute the command: 

> Rscript -e "library(knitr); knit( '%.Rnw' )"

TexStudio gives me an error saying:

> Error: unexpected input in " knit( 10_" Execution halted 

"10_" is the part of the file name I'm working on.

The scripts just works fine in 2.12.22. Is there any work around for this?

**Comment by sunderme** [comment]
see #1169

**Comment by MeanSquaredError** [comment]
This PR https://github.com/texstudio-org/texstudio/pull/1231 will probably fix it.

**Comment by sunderme** [comment]
@sbtseiji please confirm that it fixes your problem (build, see bintray.com/sunderme/texstudio...)

**Comment by sbtseiji** [comment]
I downloaded and tried the latest TeXstudio 3.0.1 (git 3.0.0-3-g5841d8f), still no change.

> Process started: Rscript -e 'print("hello")'
> Error in print(hello) : object 'hello' not found Execution halted

> Process started: Rscript -e "print('hello')"
> Error in print(hello) : object 'hello' not found Execution halted

**Comment by sunderme** [comment]
you might have been a tad too fast.
You are looking for version e9031ac5

**Comment by sbtseiji** [comment]
Thank you! TeXstudio 3.0.1 (git 3.0.0-11-gf594431) worked fine.

> Process started: Rscript -e "print('hello')"
> [1] "hello"
> Process exited normally
