### ISSUE TITLE
Extra closing curly brace on auto complete

### ISSUE THREAD

**Issue by gkvallis** [texstudio-org/texstudio#123]
### Environment
- TeXstudio: <2.12.6>
- Qt: <5.71>
- OS: <Mac>

### Expected behavior
I type \begin{it
in order insert an 'itemize' environment. Then #P to complete it. I expect to get
\begin{itemize}
 \item
\end{itemize}

### Actual behavior
Instead I get
\begin{itemize}
 \item
\end{itemize}}
That is, there is an extra curly bracket after \end{itemize} that I have to remove manually. If I do the auto complete after \begin  (and before I have inserted the opening curly brace) then the extra one is not there, but then I have to select the environment and then do an extra  autocomplete, and the process is quite clunky. 

It would be _much_ more convenient if this extra brace were not there in my first case usage.

**Comment by sunderme** [comment]
works fine here.
try 2.12.8

**Comment by gkvallis** [comment]
I tried 2.12.8.  Same behaviour. 

Note that I'm doing the auto-complete (cmd-P) at the stage after I've opened the first curly brace, so at:
  \begin{it   

and it completes with 
\begin{itemize}
  \item
\end{itemize}}

Maybe I am trying to auto-complete in an incorrect way.

**Comment by sunderme** [comment]
cmd+p is not the default shortcut, what do execute with it.
Anyway, acceptance of completer is return/enter.

**Comment by gkvallis** [comment]
I see the issue now. If I have auto-complete parentheses turned on (which I did) then typing
 \begin{     
produces
\begin{ }
with the cursor between the curly brackets. Then typing 'ite' and cmd-space (or equivalently cmd-P) to autocomplete gives
\begin{itemize}
\item
\end{itemize}}
where the extra curly bracket at the end comes from the curly bracket at the end of \begin{ }.

The work-around is to turn auto-complete parenthesis off, and then it works as desired. However,  think it would be nice (IMHO)  if it could detect the extra parenthesis, and work as one might desire, even when auto-complete paranetheses is turned on.

**Comment by sunderme** [comment]
fixed
