### ISSUE TITLE
Selected dark theme does not change the interface

### ISSUE THREAD

**Issue by update-freak** [texstudio-org/texstudio#1230]
After installing the latest version v3.0.0 it is possible to set up a dark theme.
The settings "Modern" and "Modern - dunkel" have the same appearance, although in one case it should be dark.

![interface](https://user-images.githubusercontent.com/40196995/91421797-a9b0f700-e856-11ea-91b8-208d4ee7a036.png)

### Environment
- TeXstudio: 3.0.0
- Qt: 5.12.1
- OS: Windows 10 Edu (Version 2004)
- TeX distribution: TeX Live 2020

### Expected behavior
With "Modern - dunkel" it is dark.

### Actual behavior
With "Modern - dunkel" it is not dark.

**Comment by sunderme** [comment]
the modern style-dark is intended for usage in a system where the system determines the dark color scheme.
To get a dark mode on win without a general dark color scheme, change *style* to adwaita dark, color schem classic, use system colors.

**Comment by update-freak** [comment]
Thanks! It works.
