### ISSUE TITLE
Feature Request:  Project Spaces

### ISSUE THREAD

**Issue by jrmoserbaltimore** [texstudio-org/texstudio#1237]
For the next version of TeXStudio, can we have some form of project spaces?

It's difficult to keep track with so many files open when operating multiple projects.  With a fixed root document, F5 rebuilds the current project; but with multiple projects this is no good.

Two things would enhance the workflow:

- Allow a higher level of organization on the Structure pane which groups together documents in the current project; and
- Hide (but remember) tabs for projects which are collapsed in the Structure pane

This way, when working on one project or another simultaneously, it's possible to switch between them (like having multiple TeXStudio windows open).  Hitting F5 would rebuild the root document of the current project for the file selected.

This is a non-trivial feature, involving:

1. Adding the level of organization to the Structure pane (easy enough)
2. Differentiating certain TeXStudio environment state (notably root document) based on the current project (likely refactoring)
3. Detecting the environment based on the tab selected (relies on (2))
4. UI modifications and state tracking based on whether a project is expanded or collapsed in the Structure pane (probably not easy)

As such I don't imagine it will be the highest priority thing on the books.

**Comment by sunderme** [comment]
you are aware that if you do not set an explicit root, txs can determine itself what the root is and act accordingly ?
Only requisite is that the root/top file is opened in txs and that "automatically load included files" is active.

**Comment by jrmoserbaltimore** [comment]
Yes, sometimes I simply have multiple documents that can appear as root for a given file, so I set an explicit root.

It's more a matter of files from different projects being mixed together in a disorganized way in the left pane that prevents working on two different projects at once.

**Comment by jrmoserbaltimore** [comment]
Not sure it finds explicit roots properly either.

![image](https://user-images.githubusercontent.com/3127473/92333325-8a824880-f052-11ea-9bad-71a7ad867fc4.png)

**Comment by jrmoserbaltimore** [comment]
After thinking about this, I think it makes more sense to do this per root document, e.g.

- main.tex
  - BIBLIOGRAPHY
    - bibtex/references
      - Foo2009
        - Annotation
  - title.tex
  - chapters/chapter1.tex
    - Section 1
    - Section 2
  - chapters/chapter2.tex
    - Section 1
      - figures/figure1.tex
    - Section 2
- annotated_bibliography.tex
  - BIBLIOGRAPHY
    - bibtex/references
      - Foo2009
        - Annotation

Does this seem more reasonable?

**Comment by sunderme** [comment]
global toc has been introduced with 3.1.0
