### ISSUE TITLE
Feature Request:  Newclude support \include*{}

### ISSUE THREAD

**Issue by jrmoserbaltimore** [texstudio-org/texstudio#1238]
### Environment
- TeXstudio: 3.0.0

### Expected behavior

`\include*` should show the foo.tex file in the Structure pane.

### Actual behavior

Shows an entry with no file name

### How to reproduce

```
\usepackage{newclude}
\include*{foo}
```

**Comment by sunderme** [comment]
you can do your own definition.
see https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html#CWLDESCRIPTION
and https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions#how-does-the-custom-highlighting-work
Once you have create a working cwl, come back and we can integrate it into the binary.

**Comment by jrmoserbaltimore** [comment]
It looks like there's [already a newclude cwl](https://github.com/texstudio-org/texstudio/blob/master/completion/newclude.cwl), and it's working now.  Weird.  I used it for a document yesterday and had three files that just showed up blank in the pane, and so removed it and went back to `\input`.  Dunno why that happened.

I guess this is moot.
