### ISSUE TITLE
Textbox too white to be readable when dark mode is enabled

### ISSUE THREAD

**Issue by surprized** [texstudio-org/texstudio#1239]
### Environment
TeXstudio 2.12.22 (git n/a)
Using Qt Version 5.14.2, compiled with Qt 5.13.2 R
Usint texlive-scheme-mediun provided by Fedora, and in openSUSE texlive (both distros are updated as of right now).

### Expected behavior
Readable text.

### Actual behavior
I can't see anything.

### How to reproduce
Enable dark mode for GNOME 3 using gnome-tweaks (I assume the theme is adawaita-dark?) or use breeze-dark on KDE.

Maybe it's a bug? The text appears readable when opening a window inside TXS.

![Screenshot from 2020-08-30 22-10-43](https://user-images.githubusercontent.com/20981514/91682424-0c4d1000-eb41-11ea-9551-eaaef8ced8fb.png)

![Screenshot from 2020-08-30 22-17-25](https://user-images.githubusercontent.com/20981514/91682426-0d7e3d00-eb41-11ea-9fa3-ccfc83b7bd2f.png)

This happens with "Ignore system colors" either enabled or disabled.

**Comment by sunderme** [comment]
update to 3.0.0

**Comment by surprized** [comment]
Yes! It's working fine now. 
I guess repos are still catching up on the update. Meanwhile, where can I see the changelog?

**Comment by muzimuzhi** [comment]
> Meanwhile, where can I see the changelog?

A brief changelog can be seen in https://github.com/texstudio-org/texstudio/blob/master/utilities/manual/CHANGELOG.txt.

**Comment by surprized** [comment]
It literally got updated for Fedora 32 2 hours after my post, thanks!
