### ISSUE TITLE
TS becomes unresponsive for 30+ seconds when editing a root file containing many \input’s

### ISSUE THREAD

**Issue by Fifis** [texstudio-org/texstudio#1243]
I do not know in which version this behaviour was introduced, but it completely halted my editorial activity after I installed version 3.0.0 and not having upgraded it for over a year. I am using a gaming machine with an 8th-gen i7 processor, 16 GB RAM and an SSD, and the slowdown is terrible.

### Environment
- TeXstudio: TeXstudio 3.0.0
- Qt: Using Qt Version 5.12.8, compiled with Qt 5.12.8 R
- OS: Linux Mint 20
- TeX distribution: TeXLive 2020

### Expected behaviour
A user should be able to edit the names of \input and \include’d files in the root document regardless of their number.

### Actual behaviour
When the master (root) document is open and there are hundreds of \input’s, as soon as I start editing the name of just one file, TeXstudio completely freezed for 30–40 seconds. One CPU core is at maximum load, the programme won’t respond. After I change just one (!) character of a file name, it freezes for half a minute again, reflects that change, and again, a change of one symbol followed by a long waiting period.

### How to reproduce
See the video below. Set-up: have a master document, have 10 or so subfolders in the same folder, each containing roughly 40 TeX files (say, each one containing one verse environment—I was typesetting poetry, one file per poem). The master document is nothing but a list of inputs between \begin{document} and \end{document}. Then, start modifying the name of any \input’ed file (e. g. erase one character in a name). Have TeXStudio halted for 30 seconds or more. LanguageTool is disabled.

### Video example
I sped it up by a factor of 5 (!), so... imagine this unresponsiveness being 5 times worse. What I am trying to do is type in the path to a file ‘2019/mywretched.tex’ on a keyboard, but fail to do so because it freezes so badly.

![texstudio](https://user-images.githubusercontent.com/5990916/91921875-db014b00-eccc-11ea-88f7-7ddbd1b373b3.gif)

**Comment by sunderme** [comment]
it would be helpful to have the test case i.e. the complete document to check what is going on.
You can send it directly to me sunderme@gmx.de

**Comment by jeanbertg** [comment]
This is not limited to Linux and is present since at least 2.10.8.
I am on Catalina with a fast M.2 drive so it also baffles me.
My main file has about 30 input files each with some 2000 lines.
Working in the separate files has no issue but the main file is unresponsive on small changes (input{} but also on \usepackage{} modifications).

**Comment by sunderme** [comment]
in principle changing usepackage in a large document (including subfiles) is expensive as *all* subfiles have to parsed a again as known commands and its interpretation is/may be changed
whether there is something especially suboptimal in your document, I can't say without a concrete example.
If no example is provided, there is nothing we can do.
