### ISSUE TITLE
Compute mathematical expressions

### ISSUE THREAD

**Issue by Kosay** [texstudio-org/texstudio#1245]
Hi
I have an idea to calculate the mathematical expressions and make it easier to write. We can use a tag for a variable **(\var{ID,\x^{2}})** and after compilation we get  <a href="https://www.codecogs.com/eqnedit.php?latex=x^{2}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?x^{2}" title="x^{2}" /></a>.
While when we calculate the expression we get the value
It will help specially for writing regular reports and instead of re-compute, the LaTeX will compute it directly.

### Example1
We have a table 
\begin{table}[]
\begin{tabular}{lll}
Items N. & Item Price & Price \\
\var        & 2          & 10    \\
1        & 2          & 2     \\
Total    &            & 12   
\end{tabular}
\end{table}

If we find a mistake in the price we must calculate it from the beginning, so like the excel, we can use an expression.

\begin{table}[]
\begin{tabular}{lll}
Items N. & Item Price & \var{**Price**,Price} \\
**(\var{ID1,5})**        & **(\var{ID2,2})**          & **(\var{ID1,ID1*ID2})**    \\
**(\var{ID3,1})**        & **(\var{ID4,2})**          & **(\var{ID1,ID3*ID4})**    \\
Total    &            & \var{total,sum(**Price**)}  
\end{tabular}
\end{table}

For a big table, it will be very beneficial. 

### Example2
If we have an equation like $y=5x$
and we want to find values for y, we write it as $y=5*\var{ID1,x}$ and for any place in the text-only we use $y=5*\var{ID1,6}$ and the result y=30

**Comment by foreachthing** [comment]
Like the calculator package does? 
https://ctan.org/pkg/calculator?lang=en
IMHO,  TS should not do any math like that - if I want someone else to work on my tex file, they would need TS to get it to work...

**Comment by sunderme** [comment]
from the syntax, it looks like a suggestion for a latex package.
What is the point for txs here ?

**Comment by Kosay** [comment]
> Like the calculator package does?
> https://ctan.org/pkg/calculator?lang=en
> IMHO, TS should not do any math like that - if I want someone else to work on my tex file, they would need TS to get it to work...
Thank you very much and I think this package is what I need,
