### ISSUE TITLE
Broken \left-\right autocompletion

### ISSUE THREAD

**Issue by lashkevi** [texstudio-org/texstudio#1246]
In the version 3.0.0 and 3.0.1 the parentheses autocompletion for the \left-\right construction is broken. When i type e.g. "\left(" it completes to "\left()" rather than "\left(\right)" as in earlier version.

### Environment
- TeXstudio: 3.0.0, 3.0.1 
- Qt: 5.9.7 
- OS: Linux OpenSUSE 13.1 
- TeX distribution: texlive 

### Expected behavior

"\left(" is expanded to "\left(\right)" (with the cursor between  "(" and "\")

### Actual behavior

"\left(" is expanded to "\left()" (with the cursor between "(" and ")")

### How to reproduce

Launch the TXS, set parentheses autocompletion, open any document, type "\left(".

**Comment by foreachthing** [comment]
It does what it should under Windows.
 
### Environment
* TeXstudio: 3.0.1
* Qt: 5.12.1
* OS: Windows 10 x64 (v2004)
* TeX distribution: MikTex

> ### Expected behavior
> "\left(" is expanded to "\left(\right)" (with the cursor between "(" and "")

### Actual behavior
`\left(\right)` with the cursor before `\right)`.
