### ISSUE TITLE
Macro Inserts Unwanted Spaces

### ISSUE THREAD

**Issue by Ackbach** [texstudio-org/texstudio#1247]
### Environment
- TeXstudio: 2.12.22
- Qt: 5.12.8
- OS: Windows(7,8,10), Mac, Linux (Distribution)
- TeX distribution: miktex, texlive, ...

### Expected behavior

I have written the following macro, because I use certain enum environments a lot:

```
%SCRIPT
editor.write("\\begin{enumerate}[{\\bf a}]");
cursor.insertLine();
editor.write("\\item ");
cursor.insertLine();
editor.write("\\item ");
cursor.insertLine();
editor.write("\\end{enumerate} ");
cursor.moveTo(cursor.anchorLineNumber()-2,cursor.anchorColumnNumber());
```
The idea is to create the begin and end commands, with two items, and then put the cursor right on the first item so I can begin typing immediately.

### Actual behavior

This macro does everything exactly the way I want, except that as soon as I start typing, TeXStudio inserts 10 spaces. This is
an annoyance more than anything. I do, in fact, have a temporary work-around which might give you a clue as to why this is happening: if I hit the left arrow, and then the right arrow, I'm right back to where the cursor put me, and TeXStudio will not insert the 10 spaces.

### How to reproduce

Write up the above macro and try using it in a document. This occurs on all three major OS's, as far as I know.

### A thought

The string length difference between '\item ' and '\end{enumerate} ' may be accounting for this difference. In the script, if I write 6 instead of cursor.anchorColumnNumber() for the column number, the problem disappears.

**Comment by Ackbach** [comment]
After figuring out the '6' versus 'cursor.anchorColumnNumber()' approach, this doesn't seem like a bug anymore. Closing.

**Comment by dbitouze** [comment]
> editor.write("\\begin{enumerate}[{\\bf a}]");

Aside remarks:

1. In LaTeX documents, `\bf` is now deprecated in favour of `\bfseries` (see http://mirrors.ctan.org/info/l2tabu/english/l2tabuen.pdf).
1. Instead of repeating `\begin{enumerate}[{\bfseries a}]`, you could use the `enumitem` package:

```latex
\documentclass{article}
\usepackage{enumitem}
%
\setlist[enumerate,1]{label=\textbf{\alph*}, ref=\alph*}
%
\begin{document}
\begin{enumerate}
\item Foo.
\item Bar.
\end{enumerate}
\end{document}
```
![test](https://user-images.githubusercontent.com/1032633/92026304-19484a00-ed61-11ea-8059-2d708c6984d6.png)

**Comment by sunderme** [comment]
and for completeness sake
The macro
```
\begin{enumerate}
\item %|
\item
\end{enumerate}
```
does the same thing without javascript.
