### ISSUE TITLE
Autocomplete filenames when including images

### ISSUE THREAD

**Issue by Kevinpgalligan** [texstudio-org/texstudio#1248]
It would be wonderful to autocomplete filenames in the \includegraphics command. It's the only thing I really miss from using Overleaf.

I'm willing to work on it myself if you give me a few pointers on where to start. It might be possible to extend the feature to work for other commands that take filenames as arguments.

**Comment by sunderme** [comment]
have you pressed ctrl+space ?

**Comment by Kevinpgalligan** [comment]
Oh wow, I have not.
