### ISSUE TITLE
"\cite" dropdown empty and bibliographic entries not found by TeXstudio

### ISSUE THREAD

**Issue by atifraza** [texstudio-org/texstudio#1249]
### Environment
- TeXstudio: 3.0.1 (previously tested on 2.12.x as well)
- Qt: 5.9.5
- OS: Linux (Ubuntu 18.04 LTS)
- TeX distribution: TeXlive 2019

Using the [cleanthesis](https://github.com/derric/cleanthesis) style, there are multiple TeX files which are placed in a `content` directory and each file is `\input` in a main TeX file.
The document compiles correctly in TeXstudio or Overleaf.

### Expected behavior
Using the `cite` command should populate a dropdown list with the documents from the bibliographic list.
This is the observed behavior on Overleaf and expected in TeXstudio.

### Actual behavior
When trying to cite a document from the bibliography (using BibLaTeX with biber), the `cite` popup does not show any documents.
Also, the cited documents are correctly added to the bibliography but TeXstudio has a squiggly line under the cited documents. When pointing the mouse over the citation, the message is *Citation missing:*

### How to reproduce
The [cleanthesis template](https://github.com/derric/cleanthesis/releases/download/v0.4.1/cleanthesis-incl-example_v0.4.1.zip) contains an example document which can reproduce the issue.

**Comment by sunderme** [comment]
I have no idea how overleaf parses tex but txs can't understand PassOptionsToPackage for an unknown package.
local .sty are not scanned, passOption... is not supported.
Just set the bibliography in a standard way and it works.

**Comment by atifraza** [comment]
Thanks for the quick comment.
CleanThesis also allows for setting up the biblatex yourself and I was aple to get the problem rectified as per yor comment and by importing and setting up biblatex myself.
