### ISSUE TITLE
Incorrect word in Text Analysis: phrases --> words

### ISSUE THREAD

**Issue by divenex** [texstudio-org/texstudio#125]
In TeXstudio 2.12.8 (Windows 10), there is a misleading incorrect word in the "tools/Analyse Text..." menu.

The Text Analysis dialog box writes "Total shown phrases", "Different phrases" and "Characters in phrases" but the word "phrases" here is used instead of "words". 

This, of course, changes the meaning of the result, as the two words have a very different meaning, with phrases being groups of words within punctuations.

**Fix:** One should write "words" instead of "phrases" in all three outputs above.

**Comment by thatlittleboy** [comment]
The Analyse Text tool allows counting of more than 1 word per 'phrase' under "Maximum words per phrase", so using 'words' wouldn't be appropriate, I'm guessing.

<img src=https://user-images.githubusercontent.com/30731072/39143115-c3293416-4724-11e8-9107-e92926155237.png width=500px>

**Comment by divenex** [comment]
Ah, I see. Thank you. This is technically correct then. I had missed it. 

This is still quite confusing, however. It's hard to define as "phrase" a single word...

Perhaps a solution would be to also print "Total words", which will be equal to "Total phrases" when "Maximum words per phrase"=1.

The number of words is a common quantity people may want to extract, as it is a common requirement e.g. for journals submission. So it would be good for people to find that quantity without ambiguity.
