### ISSUE TITLE
Add \setmathfont and \setromanfont commands support

### ISSUE THREAD

**Issue by rend3r** [texstudio-org/texstudio#1250]
TeXstudio 3.0.1 (git 3.0.1)
Using Qt Version 5.12.1, compiled with Qt 5.12.1 R
Miktex, Windows 10

\setmathfont from unicode-math package.
\setromanfont (derpecated but still alive) from fontspec.

Currently, TXS draw "unrecognized command" tooltip.

**Comment by sunderme** [comment]
you can remedy it yourself.
https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions#why-does-texstudio-mark-a-command-as-unrecognized
If you have a cwl file, please hand it in

**Comment by rend3r** [comment]
\setromanfont is synonym for \setmainfont according to fontspec-xetex.sty (622 line). I believe, you can safely add
```
\setromanfont{font}
\setromanfont[font features%keyvals]{font}
\setromanfont{font}[font features%keyvals]
\setromanfont[font features%keyvals]{font}[font features%keyvals]#*
#keyvals:\addfontfeature,\addfontfeatures,\defaultfontfeatures,\fontspec,\newfontface,\newfontfamily,\providefontface,\providefontfamily,\renewfontface,\renewfontfamily,\setboldmathrm,\setfontface,\setfontfamily,\setmainfont,\setmathrm,\setmathsf,\setmathtt,\setmonofont,\setsansfont,\setromanfont
```
to built-in https://github.com/texstudio-org/texstudio/blob/master/completion/fontspec.cwl

**Comment by rend3r** [comment]
As for unicode-math, here is quick draft:
[unicode-math.cwl.txt](https://github.com/texstudio-org/texstudio/files/5178787/unicode-math.cwl.txt)

**Comment by sunderme** [comment]
looks good so far

**Comment by sunderme** [comment]
@muzimuzhi do you want to review it and generate a PR ?

**Comment by muzimuzhi** [comment]
I suggest to NOT add `\setromanfont` to `fontspec.cwl` because it was deprecated since 2010, see the related comments in source file [`fontspec-code-interfaces.dtx`](https://github.com/wspr/fontspec/blob/d0e0e342e36e3f55d7fb61adc0c70bc46aefbb4a/fontspec-code-interfaces.dtx#L76-L85).

I will generate a PR that adds `unicode-math.cwl` and thank you @rend3r, though I originally wanted to add it after #902 is implemented.
