### ISSUE TITLE
Crash when deleting a file that is under the project tree

### ISSUE THREAD

**Issue by oldninja** [texstudio-org/texstudio#1253]
### Environment
- TeXstudio: 3.0.1 (git 3.0.1)
- Qt: Using Qt Version 5.12.1, compiled with Qt 5.12.1 R 
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
A crash occurs if I delete a *.tex file that is in the tree of a current project. This happened when I merged two files into one and simply remove the "extra" .tex file thru "delete" in my explorer window - it happened twice.

### Actual behavior
This is not a big issue, I can just close TexStudio prior to deleting any files.

### How to reproduce
Open a project and import a file, let's say ''\input{./tex/something.tex}'', then remove that file and TexStudio should crash as you simply remove the file.

**Comment by sunderme** [comment]
no crash under linux ...

**Comment by sunderme** [comment]
no crash on windows either 

does the crash occur every time you delete an included file  ?

**Comment by oldninja** [comment]
Hi @sunderme , yes. It happened twice with different deleted files. If it doesn't happened on your end, let's close the issue and I will review my installation.
