### ISSUE TITLE
Weird autocomplete after text selection

### ISSUE THREAD

**Issue by rend3r** [texstudio-org/texstudio#1255]
TeXstudio 3.0.1 (git 3.0.1)
Using Qt Version 5.12.1, compiled with Qt 5.12.1 R
Miktex, Windows 10

Steps to reproduce:
1) Text selection of any piece of script.
2) Press \ backslash (dont erase text with Del or BackSpace).
3) Print \setmain and press Tab to autocomplete the command to \setmainfont{font} in my case.
4) "font" placeholder is replaced with selected text from 1st step.

Is it intend?

**Comment by sunderme** [comment]
yes
