### ISSUE TITLE
No \cite popup anymore, bibliography not recognized by texstudio any more

### ISSUE THREAD

**Issue by WDGroll** [texstudio-org/texstudio#1256]
### Environment
- TeXstudio: 2.12.14 , 3.0.1
- Qt:  5.11.3
- OS: Linux (Debian 10)
- TeX distribution: texlive 
- Bibliography: BibTex

### Expected behavior
A popup window showing the citation information from the bibliography file when hovering on a citation, or a drop down list to choose the citation from when entering a \cite{.
The behavior like it was up to Debian 9 (TeXstudio 2.11.2)

### Actual behavior
There is no dropdown menu to choose an entry from when entering a citation, hovering over a \cite leads to "citation missing":
![Bildschirmfoto_2020-09-06_11-06-10](https://user-images.githubusercontent.com/23437854/92322807-bd691400-f033-11ea-874f-1e9e05ebe017.png)

When trying to add a citation, you cannot chose the bib-file, the only choice is a new, unnamed file:
![Bildschirmfoto_2020-09-06_11-08-05](https://user-images.githubusercontent.com/23437854/92322808-be01aa80-f033-11ea-84fe-75a6c1e751d6.png)

Nevertheless, the document compiles without error and all citations are correct. So the LaTeX-flow seems to be OK, only TeXstudio doesn't know where to look for the bibliograpy.

### How to reproduce
The problem came up when upgrading from Debian 9 to Debian 10, thus moving from TeXstudio 2.11.2 to 2.12.14.
To check whether this has been fixed in the meantime, I compiled the TeXstudio from the git repository. But it's still the same with the freshly compiled version 3.0.1. 
(Screenshots taken from 3.0.1).

Seems TeXstudio lost the connection to the bibliography file(s), but I could not find a way to add any *.bib file to the project.

Maybe it is a configuration problem, but there is a strong advice not to change anything within the institute templates.

There is an old  thread dealing with an alike issue on [stackexchange](https://tex.stackexchange.com/questions/106607/cite-pop-up-in-texstudio-doesnt-show-up-anymore
)
But none of the suggestions worked for me, and some of them seemed to be related to the Biber rather than BibTex flow.

**Comment by sunderme** [comment]
txs reads \addbibresource or \bibliography
The filename needs to be directly accessible (i.e. not over an extra defined search path, though options aloow setting searchpathes)
subfiles are loaded and parsed by txs (automatically if load included files option is active as it should be)
If the bibliography is defined in a sty file, tcs does not read it nor interpret it.

**Comment by WDGroll** [comment]
The files are all in one directory, including the *.bib, with the exception of the images, which are located in the subfolder "Bilder"

```
3P_Layoutwahl.aux  bibstyle.bst       Hauptdokument.log         Hauptdokument.tex
3P_Layoutwahl.tex  Bilder             Hauptdokument.out         Hauptdokument.toc
Bibi-JR.bib        Hauptdokument.aux  Hauptdokument.pdf         Hauptdokument.tps
Bibo.bib           Hauptdokument.bbl  Hauptdokument.synctex.gz
Bibo.bib.orig      Hauptdokument.blg  Hauptdokument.tcp

```
The bibliography is inserted within the template 3P_Layoutwahl.tex:
![Bildschirmfoto_2020-09-06_12-48-10](https://user-images.githubusercontent.com/23437854/92324166-55202f80-f03f-11ea-8968-6f688633206f.png)
The 'load included files' option is checked in the extended preferences.

But maybe the problem is that the '\bibliography' is contained in a conditional, depending on the type of export? 
"Erstabgabe" or "Endabgabe" in '3P_Layoutwahl.tex'?
[3P_Layoutwahl.pdf](https://github.com/texstudio-org/texstudio/files/5179516/3P_Layoutwahl.pdf)
If txs doesn't know which style to parse, it might be unable to find the bibliography.

But it worked at least up to version 2.11.2...

**Comment by sunderme** [comment]
txs does not interpret self-defined commands
older versions of txs did less accurate parsing, thus a line with \bibliography... was just interpreted without context. Now command definitions are ignored, even if they continue over several lines, hence txs does not see the bibliography command.

**Comment by WDGroll** [comment]
Thank you very much, that's it.
So I have to reconfigure the template, despite the tutor's strong advice...

Many thanks!

**Comment by JJM-JFX** [comment]
Pop-ups for citations were not working, except for an empty box. 
It was caused by an extra space after the comma in the \bibliography{} command arguments:

Compiles and gives pop-up menu:
`\bibliography{IEEEabrv.bib,references_v39.bib}
`
Compiles and gives pop-up menu:
`\bibliography{IEEEabrv,references_v39}`

Compiles but gives NO pop-up menu:
`\bibliography{IEEEabrv, references_v39}`
