### ISSUE TITLE
Profile not uploading - Solarized Dark and Light 

### ISSUE THREAD

**Issue by SeemaSangari** [texstudio-org/texstudio#1259]
### Environment
- TeXstudio:  3.0.1
- Qt:  Using Qt Version 5.15.0, compiled with Qt 5.15.0 R
- OS:  MAC
- TeX distribution:  TexStudio

### Expected behavior
Load the profile and change the color scheme

### Actual behavior
No change after loading the profile

### How to reproduce
Options -> Load Profile and select the attached files in the zip folder
[Archive.zip](https://github.com/texstudio-org/texstudio/files/5180864/Archive.zip)

**Comment by sunderme** [comment]
3.0.x has two syntax color schemes: light and dark-mode
Old profiles can only set the light mode. If txs uses dark-mode, the profiles will not be effective

**Comment by SeemaSangari** [comment]
Thanks, I was wondering if there is any way that I can change the light and dark mode as per the files attached in the earlier posts.
