### ISSUE TITLE
words after `\code` interpreted as verbatim

### ISSUE THREAD

**Issue by jendrikw** [texstudio-org/texstudio#1261]
### Environment
- TeXstudio: 3.0.1
- Qt: Using Qt Version 5.15.0, compiled with Qt 5.15.0 R
- OS: Arch Linux
- TeX distribution: Texlive 2020

### Expected behavior
When `\code` is not defined, or defined as a normal command, there should be no verbatim highlighting after it

### Actual behavior
`\code` seems like a special thing for texstudio so it enters verbatim mode

### How to reproduce

```tex
\documentclass{article}
\newcommand{\code}[1]{\texttt{#1}}
\begin{document}
\code{x} the highlighting here is wrong
\end{document}
```

![image](https://user-images.githubusercontent.com/12938023/92360709-8f480a80-f0ed-11ea-8292-57910f65a4a3.png)

At the closing curly bracket, I get verbatim highlighting (orange).

It doesn't happen with other commands:

![image](https://user-images.githubusercontent.com/12938023/92360872-cdddc500-f0ed-11ea-9434-d60cca2e8a95.png)

I found `\code` in a few cwl files, but none of those should be loaded.

It seems to be the case that texstudio expects to see some kind of paired delimiter:

![image](https://user-images.githubusercontent.com/12938023/92361066-21e8a980-f0ee-11ea-81b8-b7cc1afca9b4.png)

**Comment by sunderme** [comment]
works fine here
please show the result of help/check active completion...

**Comment by jendrikw** [comment]
Sorry, I just realized this is because of a custom cwl file I have:

```
\code{verbatimSymbol}#S
```

I didn't understand `verbatimSymbol` and expected it to work with `{}`.

**Comment by muzimuzhi** [comment]
@jendrikw 
`verbatimSymbol` is one of the special argument names, see the [user manual](https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html), sec. 4.14.2:

> `verbatimSymbol`: verbatim argument, e.g. `\verb|%<text%>|` and `\verb{verbatimSymbol}#S` from `latex-document.cwl` in source code.

(It seems its documentation can be improved.)
