### ISSUE TITLE
Can't write in file after saving - no .aux file created

### ISSUE THREAD

**Issue by Izanuela** [texstudio-org/texstudio#1264]
Hello there, 

I am currently writing my bachelor's thesis in TeXStudio and eversince the update to version 3.0.1. I can't preview the files anymore. When opening a blank file, typing in it and pressing the Build&View button, the file is actually compiled and gives me a preview. but as soon as i then save that file, make a minor change to the coument (adding a comma to a sentence or adding a number in a date) the file won't build and view anymore giving off th error "I can't write on file ..." appears. 

i tried using different Editors like TeXMaker but they also didn'T complile the files. I tried uninstalling both TeXStudio and Miktex and reinstallin. I even tried an older texstudio build. 

i am so close to crying right now 
- TeXstudio:  3.0.1
- Qt: <!-- SEE THE ABOUT SCREEN IN TXS -
- OS: Windows 10 Build 18363.1016
- TeX distribution: MikTex

### Expected behavior
TeXstudio builds and views the file

### Actual behavior
Gives off Error "I can'T save in file"

### How to reproduce
Open new file, text anything, build and view. Then save. Try to build and view again.

**Comment by sunderme** [comment]
where do you save your files on ?
If texmaker is afflicted as well, it seems to be rather a general problem.
Sounds a bit like missing writing permissions.

**Comment by sunderme** [comment]
No feedback
