### ISSUE TITLE
Plans on translating the user manual in other languages?

### ISSUE THREAD

**Issue by IngegnerLor** [texstudio-org/texstudio#1267]
I would like to ask if there are any current plans on translating the TeXstudio [user manual](https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html). If not, maybe I can contribute in translating it in my mother tongue (Italian).

**Comment by sunderme** [comment]
so far, nobody has come up with a translated manual. It would be welcome.

**Comment by IngegnerLor** [comment]
Thank you for your reply! I may work on it in my spare time.
