### ISSUE TITLE
LaTeX equation preview process: Adding some commands at begining/end of the equations

### ISSUE THREAD

**Issue by nsaxena1234** [texstudio-org/texstudio#1269]
Dear All,

I have some queries regarding the LaTeX equation preview process (Showing the output of LaTeX equations) of TeXStudio. I want to add some of my commands at the beginning and end of the equations. How I can do that...?

Please provide your suggestions…

Regards,
NS

**Comment by sunderme** [comment]
you can't with the hover preview but you can select any text and generate a preview from the selection (alt+p)

**Comment by sunderme** [comment]
No feedback
