### ISSUE TITLE
minted's `\newmintinline` should be recognized as defining new commands

### ISSUE THREAD

**Issue by jendrikw** [texstudio-org/texstudio#1270]
### Environment
- TeXstudio: 3.0.1
- Qt: Using Qt Version 5.15.0, compiled with Qt 5.15.0 R
- OS: Arch Linux (Linux 5.8.5)
- TeX distribution: Texlive 2020

### Expected behavior
`\newmintinline` should be recognized as defining new commands. Quoting the minted manual v2.5:

> `\newmintinline` This creates custom versions `\mintinline`. The syntax is the same as that for newmint: `\newmintinline[〈macro name〉]{〈language〉}{〈options〉}`.  If a〈macro name〉is not specified, then the created macro is called `\〈language〉inline`.

### Actual behavior
Texstudio shows highlighting errors

### How to reproduce

```tex
\documentclass{article}
\usepackage{minted}
\newmintinline{perl}{} % defines \perlinline
\newmintinline[mycode]{perl}{} % defined \mycode
\begin{document}
\perlinline{abc}

\mycode{abc}
\end{document}
```

![image](https://user-images.githubusercontent.com/12938023/92720612-22d74080-f365-11ea-8f69-5f9970aa65ee.png)

**Comment by sunderme** [comment]
you can add the commands yourself, see https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions#how-does-the-custom-highlighting-work
We are happy to accept a corrected cwl.

**Comment by muzimuzhi** [comment]
> ```tex
> \newmintinline{perl}{} % defines \perlinline
> \newmintinline[mycode]{perl}{} % defined \mycode
> ```

Unfortunately, the syntax of texstudio's cwl file doesn't support this. That is, texstudio could not add `\<macro name>` to the list of recognized commands after `<macro name>` (or part of it) is given as an argument of a user command.
