### ISSUE TITLE
Weird figure placement behavior over text

### ISSUE THREAD

**Issue by highpotentialunicorn** [texstudio-org/texstudio#1271]
### Environment
- TeXstudio:  TeXstudio 3.0.1 (git 3.0.1)
- Qt: Using Qt Version 5.12.1, compiled with Qt 5.12.1 R 
- OS: Windows 10 
- TeX distribution: Miktex 

### Expected behavior

Print image below text or start new page if it doesn't fit. (worked until somewhen today)

### Actual behavior

Placement of the image in the center of the page, ignoring any text and moving the text. 

### How to reproduce

Just standard figure:
                    `\begin{figure}[htb]%
    				\centering%
    				%
    				\includegraphics[width=0.6\linewidth]{Images/somepic.jpg}%
    				%
    				\hspace*{5mm}%
    				%
    				\captionCaption.}%
    				\label{fig:image}%
    			\end{figure}`
![Screenshot 2020-09-11 190217](https://user-images.githubusercontent.com/54549714/92953062-54cdcd00-f461-11ea-951f-6655013dba9b.png)

**Comment by sunderme** [comment]
that is a pure latex question.
Please use a dedicated site for this like tex.stackexchange.com
