### ISSUE TITLE
Can't find main.bcf in subfolder

### ISSUE THREAD

**Issue by MalakanC** [texstudio-org/texstudio#1273]
### Environment
- TeXstudio: 3.0.1
- Qt: 5.15.0
- OS: MacOS 10.15.6
- TeX distribution: MacTex 2019

### Expected behavior

Need build files to be in subfolder `build_folder`. This is done with a PdfLaTex command. Should work as normal but with build files in the subfolder.

I assume my command is just wrong but unsure.

### Actual behavior

I get an error message popup:

```
Could not start Build & View:PdfLaTeX:
pdflatex -synctex=1 -interaction=nonstopmode -output-directory=build_folder "main".tex.
```

And the process exits with errors with no descriptive messages beyond that.

After cleaning the auxilary files I get a different message popup:

```
Could not start Recompile Bibliography:PdfLaTeX:
pdflatex -synctex=1 -interaction=nonstopmode -output-directory=build_folder "main".tex.
```

followed by the following message:

```
Process started: pdflatex -synctex=1 -interaction=nonstopmode -output-directory=build_folder "main".tex

Process exited with error(s)



Process started: biber "main"

INFO - This is Biber 2.12
INFO - Logfile is 'main.blg'

ERROR - Cannot find control file 'main.bcf'! - Did latex run successfully on your .tex file before you ran biber?
INFO - ERRORS: 1

Process exited with error(s)



Process started: pdflatex -synctex=1 -interaction=nonstopmode -output-directory=build_folder "main".tex

Process exited with error(s)



Process started: pdflatex -synctex=1 -interaction=nonstopmode -output-directory=build_folder "main".tex

Process exited with error(s)

```

The file is present in the subfolder, so I'm guessing it's not looking inside the folder.

### How to reproduce

Set PdfLaTex command to: `pdflatex -synctex=1 -interaction=nonstopmode -output-directory=build_folder %.tex` with a folder called `build_folder` alongside the root document. Build.

**Comment by muzimuzhi** [comment]
Add option `--output-directory=build_folder` to Biber command, see [`texdoc biber`](http://mirrors.ctan.org/biblio/biber/documentation/biber.pdf), sec.3.3.1. 

The option `-output-directory=build_folder` added to PdfLaTeX command made `main.bnf` be written to `build_folder/main.bnf`, so you need to config Biber to input `main.bnf` from that sub-directory as well.

**Comment by sunderme** [comment]
@muzimuzhi are interested in writing a short faq answer about this in the wiki ?

**Comment by muzimuzhi** [comment]
@sunderme I find it is already recorded in wiki: https://github.com/texstudio-org/texstudio/wiki/Tips-And-Tricks#using-a-separate-directory-for-auxiliary-files. I've added the option `-output-directory`, see this [revision comparison](https://github.com/texstudio-org/texstudio/wiki/Tips-And-Tricks/_compare/35a10ea4f6c1397206651a7edd10dd0f3fa7f44c...bd037a338821c1a2c0ca2a613b8f5d0ed5951754).

**Comment by sunderme** [comment]
thanks for looking at it

**Comment by MalakanC** [comment]
@muzimuzhi I've added the option `--output-directory=build_folder` to the Biber command, am now getting a new error message popup and message log:


Could not start Recompile Bibliography:PdfLaTeX:
pdflatex -synctex=1 -interaction=nonstopmode -output-directory=build_folder "main".tex.





Process started: pdflatex -synctex=1 -interaction=nonstopmode -output-directory=build_folder "main".tex

Process exited with error(s)



Process started: biber "main" --output-directory=build_folder

INFO - This is Biber 2.12
INFO - Logfile is 'build_folder/main.blg'
ERROR - build_folder/main.bcf is malformed, last biblatex run probably failed. Deleted build_folder/main.bbl
INFO - ERRORS: 1

Process exited with error(s)



Process started: pdflatex -synctex=1 -interaction=nonstopmode -output-directory=build_folder "main".tex

Process exited with error(s)



Process started: pdflatex -synctex=1 -interaction=nonstopmode -output-directory=build_folder "main".tex

Process exited with error(s)

**Comment by muzimuzhi** [comment]
> ```
> Process started: pdflatex -synctex=1 -interaction=nonstopmode -output-directory=build_folder "main".tex
> 
> Process exited with error(s)
> ```

Either `main.tex` or `.bib` is problematic. Delete all the aux files, then try again? It's better to provide a complete example (`.tex` + `.bib`).

**Comment by MalakanC** [comment]
@muzimuzhi  I got the above error and messages after cleaning aux. If i didn't clean aux I would get an error with no error message.

I've just been trying to create a MWE in a zip to send over and I seem I may have found something, unsure how to proceed. After a bit of testing, it seems the error is related to having other `.tex` files within a different subfolder called `chapters`. If they are in the root directory there is no error.

Now that the build files are going to a subfolder I can put my child tex files into the root folder. Should solve the immediate issue for me.

[Here](http://www.mediafire.com/file/yaj5a7rtljf8usv/Archive.zip/file) is a zip of my MWE if it can help find the issue.

For some reason I'm not getting the PDF preview anymore, the PDF is appearing within `build_folder`.

**Comment by muzimuzhi** [comment]
> I got the above error and messages after cleaning aux. If i didn't clean aux I would get an error with no error message.

The error message came from `library.bib`. Either comment out the first three text lines using `%`, or just delete them. 

> For some reason I'm not getting the PDF preview anymore, the PDF is appearing within `build_folder`.

Open configure window, check "Show Advanced Options", find "Build -> Additional Search Paths", add `build_folder` to both fields "Log File" and "PDF File".
![image](https://user-images.githubusercontent.com/6376638/93039890-478c2a80-f67b-11ea-8f18-330b89eadd29.png). If you need to specify multiple paths, use `;` as separator in Windows, otherwise use `:`.

I'll update related wiki.

**Comment by muzimuzhi** [comment]
Related wiki entry is updated, see [wiki/Tips-And-Tricks#using-a-separate-directory-for-auxiliary-files](https://github.com/texstudio-org/texstudio/wiki/Tips-And-Tricks#using-a-separate-directory-for-auxiliary-files).

**Comment by MalakanC** [comment]
Quick question, does -output-directory=DIR have to point to a relative location within the root folder or can I specify a full path, including outside of the root folder?

OneDrive syncs the files within the build_folder even when not told to. Need to dump them somewhere outside of OneDrive, unless there is another solution?

**Comment by muzimuzhi** [comment]
> Quick question, does -output-directory=DIR have to point to a relative location within the root folder or can I specify a full path, including outside of the root folder?

No, you can use either relative or absolute path.

**Comment by MalakanC** [comment]
I set to not sync build_folder, I run the `Build` and it uploads them all the same.

I'll opt for an absolute path thats outside of onedrive, easy solution

**Comment by BeerStud** [comment]
On Mon, 14 Sep 2020 04:52:34 -0700
MalakanC <notifications@github.com> wrote:

> Quick question, does -output-directory=DIR have to point to a
> relative location within the root folder or can I specify a full
> path, including outside of the root folder?
> 
> OneDrive syncs the files within the build_folder even when not told
> to. Need to dump them somewhere outside of OneDrive, unless there is
> another solution?

Any file can be excluded from being synced by OneDrive. You are doing
something wrong or just failing to correctly configure OneDrive.

Can you supply the settings your are using and a log file extract to
show the actual syncing?

-- 
Gerard

**Comment by MalakanC** [comment]
@BeerStud , on a Mac: OneDrive> Help & Settings > PreferencesAccount > Choose Folders

[This](https://imgur.com/a/fdEIEgX) is the image of how it currently looks. I've removed files from the build_folder.

Whenever I built TexStudio would dump the files in there and OneDrive would just start up all the same.

Wehre do I get a log extract?
