### ISSUE TITLE
Not possible to save file to a network drive

### ISSUE THREAD

**Issue by PatrickN88** [texstudio-org/texstudio#1274]
Hello all, 

We have some issues with overwriting existing files on a network drive. The first time it seems fine (if you use save-as), but the second time it says it "Could not get write permissions in file". 

I have tried it with multiple versions of texstudio.
It does work in version 2.11.0 and 2.11.2. 
In the newer versions we have this issue

### Environment
- TeXstudio: 2.12.16 (git 2.12.16)
- Qt: 5.12.1
- OS: Microsoft Windows Server 2012 R2 Standard
- TeX distribution: texlive2019

### Expected behavior
Edit a file and be able to save it to a network drive

### Actual behavior
We get a message: Could not get write permissions in file h:\document.tex
Perhaps it is read-only or opened in another program?

### How to reproduce
1) Create a new file
2) save-as to a network drive. 
3) edit the file 
4) save the file

**Comment by sunderme** [comment]
added note on webpage

**Comment by sunderme** [comment]
can you recheck with current version of txs ?

**Comment by PatrickN88** [comment]
Thnx for your reply, It seems to work now for our version (2.12.16). 
Any idea what the problem was?

**Comment by sunderme** [comment]
possibly qt/win issue

**Comment by PatrickN88** [comment]
Unfortunately the problem has returned
Any suggestions? 

(there was no update on our side)

**Comment by chiastic-security** [comment]
I am having this exact problem too: I can save local files, but can't save to a network drive. I'm on Linux. Please could this be reopened?

**Comment by sunderme** [comment]
open a new issue. and be more precise what your network drive under linux is.
