### ISSUE TITLE
Crashing/closing when opening 'Tools --> Check Spelling' window

### ISSUE THREAD

**Issue by FimomilI** [texstudio-org/texstudio#1276]
### Environment
- TeXstudio: 3.0.1 
- Qt: version 5.12.1, compiled with 5.12.1 R 
- OS: Windows 10 
- TeX distribution: miktex

### Expected behavior
Not crashing/closing when opening the 'Tools --> Check Spelling' window.

### Actual behavior
TeXstudio closes and all progress not saved is lost. Also, on reopening, the open projects are all gone and TeXstudio seems to go back to a previously saved configuration where (in my case) 2 projects from a week or 2 ago are now back in the editor. Hence I think it is a little more than just a closing of the program and more like a crashing.

### How to reproduce
I think it happens when I add a new word to the dictionary and go to 'Tools --> Check Spelling' and have the dropdown box 'Show User Words' still unfolded from the previous time I went to 'Tools --> Check Spelling'.
So it will never happen the first time when the list of user words is still hidden but if I unfold the 'Show Words' box, and then close the window, the next time I go to 'Tools --> Check Spelling', TeXstudio crashes.
The reasons I went to 'Tools --> Check Spelling' is because I realize I added a wrong word and within a minute I would go to 'Tools --> Check Spelling' only for it to crash. I'm not sure if adding a word right before or in general is required for the crash to occur but I thought I would mention it.
It has happened multiple times now and at first I didn't think much of it but now it seems like a consistent crash/closing yet I cannot seem to reproduce it myself. I have tried running the compiler before adding the wrongly spelled word to see if that might be important but alas, unfortunately I am not able to give the full instructions required to reproduce the crashing/closing behavior I experience.

**Comment by sunderme** [comment]
I don't see a crash
do you have a backtrace in tmp ?

**Comment by FimomilI** [comment]
My apologies, but I'm afraid I don't know exactly what (I presume to be a file) you want me to send regarding the crash?

**Comment by sunderme** [comment]
there is a file texstudio_backtrace...txt somewhere in a tmp directory on your computer...

**Comment by FimomilI** [comment]
Unfortunately it does not seem like the texstudio_backtrace...txt file was created or has since been deleted as I cannot find it anywhere on my computer, temp directory or not.

**Comment by sunderme** [comment]
unfortunately without having the ability to reproduce the issue, there is nothing I can do ...
