### ISSUE TITLE
Structure view: Beamer \mode<...> prevents the following \input{...} info to be parsed correctly

### ISSUE THREAD

**Issue by jprk** [texstudio-org/texstudio#1277]
### Environment
- TeXstudio: 3.0.1
- Qt: 5.12.1
- OS: Windows10 version 2004 build 19041.508
- TeX distribution: miktex

### Expected behavior
I woud expect the Structure view to correctly display all references to files that are used as `\input{...}` command arguments in the active `.tex` file.

### Actual behavior
The reference is there, but in case the the `\input` is preceeded by `\mode<...>`, it is empty, in fact referring to the directory where all files reside. In case I put another TeX command between the `\mode<...>` and `\input`, things start to work again.

### How to reproduce
See the screenshot below. Having
```
\mode<presentation>
\input{presentation_header.tex}
\mode*
```
does not work, but in the moment I have
```[tex]
\mode<presentation>
\relax\input{presentation_header.tex}
\mode*
```
the reference to `presentation_header.tex` is parsed correctly. 

![texstudio-mode-bug](https://user-images.githubusercontent.com/5995093/93706286-f2da2b00-fb24-11ea-9853-aff1326c5c42.png)

**Comment by dbitouze** [comment]
Does it work if you leave a blank line after `\mode<...>` :
```latex
\mode<presentation>

\input{presentation_header.tex}

\mode*
```
as in the examples of the `beamer`'s documentation?

**Comment by jprk** [comment]
@dbitouze No, it does not ... but I guess the current fix will fix both cases.
