### ISSUE TITLE
How to improve cwl line for "minted" env

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#1278]
### Environment
- TeXstudio: 3.0.1
- Qt: Using Qt Version 5.15.0, compiled with Qt 5.15.0 R
- OS: macOS 10.15.6
- TeX distribution: irrelevant

### Expected behavior

`minted` environment provided by `minted` package has full syntax `\begin{minted}[<keyvals>]{<language>}`.

1. In `\begin{minted}[<cursor here>]{tex}`, "Idefix -> Complete -> Normal" should trigger key-val completer.
1. In
   ```tex
   \begin{minted}[]{text}
     \begin{minted}[]
   \end{minted}
   ```
   The second `\begin{minted}` should be highlighted as verbatim contents.

### Actual behavior
Currently, `minted` env is recorded in cwl as
https://github.com/texstudio-org/texstudio/blob/41034f29dd1a2041f3337b6917b6bfe4f71ed78f/completion/minted.cwl#L23-L26
by my PR #981. In that way, first requirement is met, but the second one is broken.
![image](https://user-images.githubusercontent.com/6376638/93814687-757afb80-fc87-11ea-9f83-f51d8d4c2b06.png)

I tried some variants in cwl, none of them works for both requirements.

### How to reproduce

Use 
```tex
\documentclass{article}
\usepackage{minted}

\begin{document}
\begin{minted}{language}
  content...
\end{minted}

\begin{minted}{text}
  \begin{minted}
\end{minted}

\begin{minted}[]{text}
  \begin{minted}
\end{minted}
\end{document}
```

**Comment by sunderme** [comment]
do I miss something ?

![grafik](https://user-images.githubusercontent.com/14033169/93916583-0e525b00-fd0a-11ea-9082-634071684438.png)

(git HEAD)

**Comment by sunderme** [comment]
can you try dev build ?

**Comment by sunderme** [comment]
so, only completion is no working as expected, from my current set-up ?

**Comment by muzimuzhi** [comment]
I tried 98a5b9a, it meets both requirements, but after typing `\begin{minted`, the completer shows an extra item `\begin{minted}[options]`, which is wrong because `minted` need a mandatory argument.
