### ISSUE TITLE
texstudio output working correctly

### ISSUE THREAD

**Issue by HenryLande** [texstudio-org/texstudio#1280]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution:

**Comment by HenryLande** [comment]
I have texstudio. Unfortunately, the output no loner appears on the right of the screen. Instead, it fills the screen. It can also happen that the screen becomes grey - both on the right and on the entire screen  Also, it seems to be not compiling correctly

**Comment by muzimuzhi** [comment]
Please provide relevant info as suggested in issue template.
