### ISSUE TITLE
Can you please add a binary build for Raspberry PI (ARM)?

### ISSUE THREAD

**Issue by dca00** [texstudio-org/texstudio#1281]
Having to go back to TexMaker would be painful. It has an ARM binary. TexStudio could to. Thanks!

**Comment by sunderme** [comment]
you. an find arm builds here: https://build.opensuse.org/package/show/home:jsundermeyer/texstudio-3.0.1

**Comment by sunderme** [comment]
note added on webpage

**Comment by dca00** [comment]
For god's sake, do not close issues right away!
Raspbian build is incomplete, still building.

**Comment by sunderme** [comment]
it is done now
