### ISSUE TITLE
Macros won't import in version 3.0.1

### ISSUE THREAD

**Issue by JarlSamseth** [texstudio-org/texstudio#1283]
I installed the newest version TeXstudio 3.0.1. When importing some macros (see example attached in [subfigures.zip](https://github.com/texstudio-org/texstudio/files/5278041/subfigures.zip)), the macros were not visible, as presented in the following image:
![image](https://user-images.githubusercontent.com/38281025/94178518-7d12ee00-fe9b-11ea-9985-d394e514bc7a.png)
The macro was recognised by the user interface, because a new white line appeared. The blue marking line (as in the image) shifted one down when the macro was imported.
The macro-files had not been added to the %APPDATA%/texstudio/macro.
Nor does Texstudio notice when I add files directly into that folder.

### Environment
- TeXstudio: 3.0.1
Using Qt Version 5.12.1, compiled with Qt 5.12.1 R
- OS:  Windows 10 
- TeX distribution:  miktex 2.9

### Expected behavior
Imported macros are entered and appear in the GUI.

### Actual behavior
Empty macros. See image above.

### How to reproduce
Import macro.

**Comment by sunderme** [comment]
don't know which txs version was used to create the macros but txs parser has become more picky and it needs to be correct json now.

Basically a line ```"formatVersion": 1,``` needs to be added and all backslash need to be changed to two backslashes.
The percent sign in the first line also confuses txs and should be avoided.
```
{
"name" : "subfigures" ,
"tag" : [
 "%%\\usepackage{subcaption}",
 "\\begin{figure}",
 "\\begin{subfigure}[t]{0.5\\textwidth}",
 "\\centering",
 "\\includegraphics{}",
 "\\caption{}",
 "\\label{fig:sub1}",
 "\\end{subfigure}",
 "~ %~~~~~~ more space if 0.45\\textwidth is used",
 "\\begin{subfigure}[t]{0.5\\textwidth}",
 "\\centering",
 "\\includegraphics{}",
 "\\caption{}",
 "\\label{fig:sub2}",
 "\\end{subfigure}",
 "\\caption{Main caption}",
 "\\end{figure}"
 ],
"description" : [
 "A figure with two subfigures side by side"
 ],
"formatVersion": 1,
"abbrev" : "subfigures" ,
"trigger" : "" ,
"menu" : "" ,
"shortcut" : ""
}
```
