### ISSUE TITLE
Parenthesis color matching not working

### ISSUE THREAD

**Issue by fdifonzo** [texstudio-org/texstudio#1284]
### Environment
- TeXstudio: 3.0.1
- Qt: Using Qt Version 5.12.1, compiled with Qt 5.12.1 R
- OS: Windows 10
- TeX distribution:  texlive

### Expected behavior
My color setting is as in the attachment: 
![image](https://user-images.githubusercontent.com/19834568/94246903-a031b200-ff1c-11ea-82ff-d199d02294f5.png)

### Actual behavior
This is what I see in the editor, though: 
![image](https://user-images.githubusercontent.com/19834568/94246964-bc355380-ff1c-11ea-97a6-b1780ac696b3.png)

Nevertheless, as soon as I move the cursor, the match is as expected:
![image](https://user-images.githubusercontent.com/19834568/94247033-d7a05e80-ff1c-11ea-98f3-951a94db721f.png)

### How to reproduce
Just try the color combination above

**Comment by sunderme** [comment]
works as expected on linux
what exactly is "as soon as I moce the cursor" ?

**Comment by fdifonzo** [comment]
But OS is Windows, and that is the behavior
I mean when you do back and forth with the cursor

**Comment by sunderme** [comment]
os should not be the issue.
Can you generate a screencast to illustrate your issue ?

**Comment by fdifonzo** [comment]
Sure, here it is-
[texstudioIssue.zip](https://github.com/texstudio-org/texstudio/files/5327471/texstudioIssue.zip)

**Comment by fdifonzo** [comment]
May this depend on custom color setting in Windows?

**Comment by fdifonzo** [comment]
Is there any news about this?

**Comment by sunderme** [comment]
not looked further yet

**Comment by fdifonzo** [comment]
May this depend on Windows custom color setting? I did change it, actually

**Comment by sunderme** [comment]
possibly

**Comment by fdifonzo** [comment]
Nothing, I tried the default setting but the bug is still there...
