### ISSUE TITLE
When suppressing words on a line, words from the below line do not move up to close the gap

### ISSUE THREAD

**Issue by eidalex** [texstudio-org/texstudio#1285]
### Environment
- TeXstudio: 3.0.1 (also not working in TeXstudio 2.8)
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
I would like lines to auto format themselves when you modify them.

### Actual behavior
The bug is a little tedious to explain... I am writing a paragraph and then when I suppress words inside a line a blank space is left at the end of the line. But no sign of "white space" or "tabulation" symbols. It is just GUI white.

### How to reproduce
Write a pragraph and delete words inside the lines. 

`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ex orci, pretium sit amet bibendum et, tempor in sem. Aliquam vitae arcu maximus, tristique sem ut, facilisis est. Nulla consequat pharetra sapien, quis aliquet diam scelerisque et.`

And when you suppress words you get :
![bug](https://user-images.githubusercontent.com/46104119/94285872-9461e200-ff54-11ea-8348-1ab11a1d2bf1.PNG)

Thanks for the amazing work with TeXStudio. I would be grateful for your help.
Regards, 
Alexandre

**Comment by sunderme** [comment]
what is the setting for wrapping ? options/advanced editor/line wrapping

**Comment by sunderme** [comment]
I assume that you are talking about wrapping.
If not, a screencast with more explication may be necessary

**Comment by eidalex** [comment]
Sorry I am in french but I think the option is set to limit word count to 160. I have tried with fictictional limit but it does not solve the problem... Would I have to deactivate it ?
![bug_texmaker](https://user-images.githubusercontent.com/46104119/94337640-6203c380-ffec-11ea-8a30-3af620f296f0.PNG)

**Comment by sunderme** [comment]
my apologies if I misunderstand 
issue: if you delete character in a line, you expect it to filled up again from the next line

This is true for something called "soft-wrap". The line is wrapped after n character/window width and words from the wrapped line are taken up again if you delete characters. If you press enter, the lines are separated and stay that way.
You have activated "hard-wrap" which means that a "LF" character is inserted when words are moved to the next line (in txs when the document is saved) and thus the lines are effectively split and removing characters does not draw words from the next line.
In my opinion, that option is never a good choice, but some seem to like it.
Whether that effect is clear from the French description, I can't say.

**Comment by eidalex** [comment]
Ok thanks a lot for your explanation. I now understand why saving file (every 5 minutes for me) would change the end of line character (seen in the margin). I have changed my options to english language and checked the soft wrap one. It works as intended ! Thanks for your help :) And thanks for TeXStudio ... I have tried many...
