### ISSUE TITLE
How to avoid switching the profile or customize the light and dark profile?

### ISSUE THREAD

**Issue by SeemaSangari** [texstudio-org/texstudio#1288]
### Environment
- TeXstudio: TeXstudio 3.0.1 (git 3.0.1)

- Qt: Using Qt Version 5.15.0, compiled with Qt 5.15.0 R
- OS:  macOS Catalina Version 10.15.6
- TeX distribution:  MikTex Console 4.0

### Expected behavior
I would like to know how I can customize the light and dark profile. Also, it would be great if you can tell me how I can just keep one profile and avoid switching over the profiles.

**Comment by sunderme** [comment]
you can select "ignore most system colors" to override OSX influence on the presentation

**Comment by SeemaSangari** [comment]
Thanks that helps to keep one profile. I would appreciate if you could comment on how to customize light and dark profiles.

**Comment by sunderme** [comment]
you can influencethe syntax colours, but not the gui.
Stylesheets can be employed but that is rather complicated. (you need to look up qt5 stylesheets)
