### ISSUE TITLE
.sty files not found

### ISSUE THREAD

**Issue by SeemaSangari** [texstudio-org/texstudio#1289]
TexStudio not able to find nomencl.sty, srcltx.sty, relsize.sty, appendix.sty, algorithm.sty, glossaries.sty, 

### Environment
- TeXstudio: TeXstudio 3.0.1 (git 3.0.1)

- Qt: Using Qt Version 5.15.0, compiled with Qt 5.15.0 R
- OS:  MacOS Catalina Version 10.15.7
- TeX distribution:  miktex

**Comment by muzimuzhi** [comment]
If this problem is reproducible when you compile the tex from command line, then this is a miktex problem, not texstudio. MiKTeX can install missing packages from internet (aka, on-the-fly), if working as expect.

**Comment by dbitouze** [comment]
Another solution would be to install, as a TeX distribution, [MacTeX](http://www.tug.org/mactex/) instead of MiKTeX.
