### ISSUE TITLE
Getting "Failed to load file [...]/main.pdf due to a bad alloc;" - Adobe opens the file without issue

### ISSUE THREAD

**Issue by bjtho08** [texstudio-org/texstudio#1291]
### Environment
- TeXstudio: 3.0.1
- Qt: 5.12.1
- OS: Windows10
- TeX distribution: texlive 2018

### Expected behavior
The embedded viewer should display the pdf

### Actual behavior
I get the error "Failed to load file [...]/main.pdf due to a bad alloc; Perhaps it is not a valid PDF document." 

### How to reproduce
I have no idea. I am finishing my doctoral dissertation and the project consists of several .tex files, .png's, .pdf's and .jpg's spread out across several folders within the main project folder. I use a multitude of packages and a custom document class (classic-thesis). It has worked without issue for years, but after changing a few lines of a tabular env, I suddenly get this error. I changed nothing else than this one particular table. Adobe reader can open the document and it does not appear to have any errors.

I have no idea how to troubleshoot this one on my own. I tried deleting a few of the auxiliary files, but it didn't seem to make a difference. Any help is greatly appreciated! My deadline is in 10 days so I really need the rest to go smoothly.

**Comment by sunderme** [comment]
you can try latest dev build which support 64bit in case it is memory issue. (https://bintray.com/sunderme/texstudio/texstudio-win#files , take the latest)
Otherwise we need a test case.

**Comment by bjtho08** [comment]
> you can try latest dev build which support 64bit in case it is memory issue. (https://bintray.com/sunderme/texstudio/texstudio-win#files , take the latest)
> Otherwise we need a test case.

Thank you! That did the trick! My pdf has grown beyond 40 MB, because a lot of my figures are high-res uncompressed. Maybe that's the issue, I don't know. The entire project directory is less than 400 MB, so I never would have thought memory could be the issue, but now it works.
