### ISSUE TITLE
Texstudio not installing on Linux Mint 20

### ISSUE THREAD

**Issue by SergioCamiz** [texstudio-org/texstudio#1292]
Impossible to upgrade my TeXstudio 
TeXstudio 2.12.22 (Build: 2.12.22+debian-1build1)
Using Qt Version 5.12.8, compiled with Qt 5.12.5 R

to the new 3.0.1 version.

### Environment
- TeXstudio:texstudio 3.0.1-1+2.1  xUbuntu 20.04 	amd64 	3.0.1, QT 5
- Qt: Qt5
- OS: Linux Mint 20 Ulyana
- TeX distribution: TeXlive 2019-20200218-1

### Expected behavior
Normal installation by using the package downloaded correctly from the site via the usual installation program that starts by clicking on the ,deb archive.
### Actual behavior
Package operation failed
The installation or removal of a software package failed.
(Reading database ... 
(Reading database ... 5%%
(Reading database ... 10%%
(Reading database ... 15%%
(Reading database ... 20%%
(Reading database ... 25%%
(Reading database ... 30%%
(Reading database ... 35%%
(Reading database ... 40%%
(Reading database ... 45%%
(Reading database ... 50%%
(Reading database ... 55%%
(Reading database ... 60%%
(Reading database ... 65%%
(Reading database ... 70%%
(Reading database ... 75%%
(Reading database ... 80%%
(Reading database ... 85%%
(Reading database ... 90%%
(Reading database ... 95%%
(Reading database ... 100%%
(Reading database ... 609767 files and directories currently installed.)
Preparing to unpack .../texstudio_3.0.1-1+2.1_amd64.deb ...
Unpacking texstudio (3.0.1-1+2.1) over (2.12.22+debian-1build1) ...
dpkg: error processing archive /home/sergio/Downloads/texstudio_3.0.1-1+2.1_amd64.deb (--install):
 trying to overwrite '/usr/share/texstudio/tabletemplate_fullyframed_firstBold.js', which is also in package texstudio-doc 2.12.22+debian-1build1
dpkg-deb (subprocess): decompressing archive member: lzma write error: Broken pipe
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg-deb (subprocess): cannot copy archive member from '/home/sergio/Downloads/texstudio_3.0.1-1+2.1_amd64.deb' to decompressor pipe: failed to write (Broken pipe)
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24+linuxmint1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 /home/sergio/Downloads/texstudio_3.0.1-1+2.1_amd64.deb
### How to reproduce
I simply clicked on the downloaded package as usual and received the log above

**Comment by sunderme** [comment]
works fine on ubuntu 20.04 for which it was build.
I can't give support on Linux mint.

**Comment by ElieGouzien** [comment]
@SergioCamiz : try to uninstall `texstudio-doc` (`sudo apt remove texstudio-doc`) before installing last version.
Here are the relevant lines of the installation output:
> dpkg: error processing archive /home/sergio/Downloads/texstudio_3.0.1-1+2.1_amd64.deb (--install):
> trying to overwrite '/usr/share/texstudio/tabletemplate_fullyframed_firstBold.js', which is also in package texstudio-doc 

I guess you have installed texstudio from mint repository that split it into two packages (`texstudio` and `texstudio-doc`) and now try to update it from the texstudio package that brings everything.

Also, I don't think this is the right place to ask for help since your problem concern more mint that texstudio.
If what I suggest doesn't work, you might want to try to find help on [mint forum](https://forums.linuxmint.com/) or [mint troubleshooting guide](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/).
