### ISSUE TITLE
citation bug in editor

### ISSUE THREAD

**Issue by rezayhaghdoost** [texstudio-org/texstudio#1294]
### Environment
- TeXstudio: 3.0.1
- OS: Mac OSx 10.15.6
- TeX distribution:  texlive
<img width="593" alt="Screenshot 2020-10-05 at 10 46 53" src="https://user-images.githubusercontent.com/49158090/95098740-5a03fc00-072f-11eb-905b-99eebde07b4b.png">

### Actual behavior
Citations are displayed incorrectly within the editor. The keyword appears bigger than the rest of the text, although the corresponidng size is set to 100%. The bigger issue here is that the actual position of the cursor does not match with the position shown in the editor (see the screenshot), as the end of the line appears within the citation keyword.

### Expected behavior
The end of the line should NOT appear within the citation keyword. 

### How to reproduce
Use \cite{xxx}

**Comment by sunderme** [comment]
please upload your texstudio.ini

**Comment by rezayhaghdoost** [comment]
[texstudio.ini.zip](https://github.com/texstudio-org/texstudio/files/5329041/texstudio.ini.zip)

**Comment by muzimuzhi** [comment]
> [texstudio.ini.zip](https://github.com/texstudio-org/texstudio/files/5329041/texstudio.ini.zip)

With macOS 10.15.7, texstudio 3.0.1 and `~/.config/texstudio/texstudio.ini` replaced with your `texstudio.ini` file, I cannot reproduce the problem. Also note that I get normal background white, only current line has background black.

**Comment by rezayhaghdoost** [comment]
Thx for the quick reply. After changing my txsprofile from custom to the defualt the "bug" was gone. So it must be something in my txsprofile.

Is there any collection of different dark themes (txprofiles) available one could choose from?

[custom-dark1.txsprofile.zip](https://github.com/texstudio-org/texstudio/files/5329478/custom-dark1.txsprofile.zip)

**Comment by sunderme** [comment]
3.0.1 has a default theme for dark mode...
