### ISSUE TITLE
SIGSEV Error when opening File on Manjaro

### ISSUE THREAD

**Issue by trrristan** [texstudio-org/texstudio#1295]
Hello,

Since a Manjaro update, I'm experiencing crashes from TeXstudio, specifically when I try to open a file.

### Environment
- TeXstudio: version 3.0.1
- Qt: 5.15.1
- OS: Linux Manjaro 20.1.1 Mikah
- TeX distribution: TexLive

### Expected behavior

Open a file

### Actual behavior

When opening texstudio from a terminal, and pressing Ctrl-O, I get the following in the terminal
`tristan@tristan-ordi Linux 5.8.11-1-MANJARO x86_64 20.1.1 Mikah
~ >>> texstudio &                                                              
[1] 4319
~ >>> crashed with signal SIGSEGV                                              
SIGSEGV (TXS-Version  R )
SIGSEGV (TXS-Version  R )
SIGSEGV (TXS-Version  R )
SIGSEGV (TXS-Version  R )

[bt] texstudio(_ZN12SimulatedCPU13set_from_realEv+0) [0x559b2eac6590]
[bt] texstudio(_ZN12SimulatedCPU13set_from_realEv+0) [0x559b2eac6590]

"/tmp/texstudio_backtrace1.txt"
"Current: 0/0"`

and I get the following /tmp/backtrace : 
`SIGSEGV (TXS-Version  R )
[bt] texstudio(_ZN12SimulatedCPU13set_from_realEv+0) [0x559b2eac6590]`

### How to reproduce
Every way of opening (Ctrl-O, button on the top bar, navigating in menus) bring the same error.
However, double-clicking on a .tex file opens it correctly with texstudio.

Thanks for the help !
Tristan

**Comment by sunderme** [comment]
As manjaro is based on arch and arch infamously produced buggy behaviour with txs, there will be no support whatsoever with problems of txs on arch or manjaro.

**Comment by blechschmidt** [comment]
I experienced the same issue. Deleting the user configuration (`mv ~/.config/texstudio/ ~/.config/texstudio.bak`) fixed it for me on Manjaro.
