### ISSUE TITLE
[Question] - Update PPA with version 3.0.1

### ISSUE THREAD

**Issue by kalimerre** [texstudio-org/texstudio#1296]
### Environment
- TeXstudio: 3.0.0

### Question
Do you know then the PPA version (3.0.0) will be updated to 3.0.1 ? 
PPA : https://code.launchpad.net/~sunderme/+archive/ubuntu/texstudio

Thanks a lot!

**Comment by sunderme** [comment]
recipe was set-up correctly, build had to be triggered manually,though
Build complete but probably still needs to propagate through the mirror servers
