### ISSUE TITLE
MikTex install dialog doesn't get called on "Compile & View" for "new" packages

### ISSUE THREAD

**Issue by ViToni** [texstudio-org/texstudio#1297]
### Environment
- TeXstudio:  3.0.1 (git 3.0.1)
- Qt: 5.12.1, compiled with Qt 5.12.1 R
- OS: Windows10
- TeX distribution: miktex

### Expected behavior
"Compile & View" should behave similar to "Build" in leading to MikTex bringing up the install dialog for packages not yet avilable locally.

### Actual behavior
"Compile & View" blocks and hangs when using not installed yet packages.
It can be stopped though. Using "Build" brings up the install dialog.
After installation "Compile & View" can be used in a regular fashion.

### How to reproduce

1. MikTex is configured to ask before installing new packages.
2. try to use a new package (not installed yet package)
3. call "Compile & View"

**Comment by sunderme** [comment]
works as intended here. What do you use behind "compile&view" ?

**Comment by ViToni** [comment]
@sunderme I'm using the regular commands, just have an outout directory configured
`pdflatex.exe -synctex=1 -interaction=nonstopmode --output-directory=build %.tex`

However be behavior seems to have vanished after a recent update of MikTex.
So I cannot reproduce it anymore and this change in behavior seems to indicate that was more an MikTex issue.
