### ISSUE TITLE
Documentation advises to set labels on issues although GitHub does not support this for non-contributors

### ISSUE THREAD

**Issue by ViToni** [texstudio-org/texstudio#1298]
The README.md (https://github.com/texstudio-org/texstudio/blob/af2de2d36433660a2d94cad10dfe6536001e5003/README.md) advises to use labels on issues:

> Please set a label whether this is a feature request/enhancement, a question or a bug report. In case of a bug report, please state version and operation system and a description which allows to reproduce the issue on another computer.

Unfortunately this is only possible for contributors. See:
- https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/applying-labels-to-issues-and-pull-requests
-  https://github.com/isaacs/github/issues/148

**Comment by sunderme** [comment]
fixed

**Comment by muzimuzhi** [comment]
(resolved by https://github.com/texstudio-org/texstudio/commit/9b0ac94777204b50cc1882ac8a82a27f9eed79e2)
