### ISSUE TITLE
Problem with the pre-filled entry in the search panel

### ISSUE THREAD

**Issue by samcarter8** [texstudio-org/texstudio#130]
Texstudio is a fantastic editor, however there is a small detail I am constantly fighting against - probably because I simply don't understand the logic behind the behaviour. Maybe someone can point out how the current behaviour works or what I could do differently.

My problem is the pre-filled search word when I open the "Find" panel 

![screen shot 2018-04-27 at 11 31 40](https://user-images.githubusercontent.com/8226363/39357495-58a0de40-4a13-11e8-93f2-5a3ceabab002.png)

Assume I searched for "foo" in a previous session of texstudio. Then I close the editor. 

Sometime later I open it again, maybe even with another file. If I now open the search panel again, the previous search is pre-filled. OK - I think I can understand this: the previously searched string is pre-filled.

Next step: I either type or copy/paste the string I want to search for, let's say I search for "bar". Works fine.

Now I either change to a document open in another tab or open a new document. If I now open the search panel again, sometimes "foo" is pre-filled, sometimes "bar". Does anybody understand the logic behind whether "bar" or "foo" is chosen? 

If the search word is independent for each document, why is "foo" inserted in the first place if I searched for it in another document in the previous session? Why is search panel not empty for a new document?

Personally I find myself currently surprised and often have to retype the same word over and over again, as I naively would expect the last used search word (bar) to be used. I hope if I understand the logic behind this I can somehow adapt my workflow.

--------

Remark: I am aware of the extended search capabilities, which lets you search the whole project or all documents at once. While this a very helpful feature, it does not help my wildernesses upon the pre-filled search words.

(In case it is relevant: I have the option "use single line selection as search word" disabled, this lead to even more entropy. Furthermore "restore last session at startup" is enabled. My texstudio version is 2.12.6 on mac OSX 10.9 )

**Comment by sunderme** [comment]
if option/advanced editor/use single line selection as search word (default) is activated, the word under the cursor is taken as search word.

**Comment by samcarter8** [comment]
@sunderme Yes, however this only works in the current document where the word is selected. After switching tabs, it is again a surprise.

**Comment by samcarter8** [comment]
@benibela This would be the perfect behaviour! However this does not happen.

**Comment by benibela** [comment]
Are you sure? You probably did not press enter. It searches without enter, but only enter/click sets it in the other tabs

**Comment by samcarter8** [comment]
@benibela Unfortunately yes. I just tried again and paid extra attention to press enter. This is a step by step account of what I am doing. Do I do something wrong?

My preferences:
![screen shot 2018-04-27 at 21 44 50](https://user-images.githubusercontent.com/8226363/39382070-a661eaec-4a64-11e8-999d-9a75e8042a4e.png)

I have two open files:
![screen shot 2018-04-27 at 21 45 17](https://user-images.githubusercontent.com/8226363/39382216-0a475434-4a65-11e8-9fe1-90e21eef6631.png)

Then I open the search panel in one file and search for something. While typing the hits in the document are highlighted in yellow, then I hit enter and the first hit after the courser position is highlighted in blue. By hitting enter again, I can jump from one hit to the next.

![screen shot 2018-04-27 at 21 45 35](https://user-images.githubusercontent.com/8226363/39382351-77cd1912-4a65-11e8-8be1-84fe94655b4d.png)

Then I change to the other file, open the search panel and a search word from a previous session in pre-filled
 
![screen shot 2018-04-27 at 21 45 51](https://user-images.githubusercontent.com/8226363/39382408-a4462ac4-4a65-11e8-8fba-c96fb28ba2a9.png)

**Comment by benibela** [comment]
Then there is another rule.

It is only set on the other tabs, if you search something new that you have never searched before.

**Comment by samcarter8** [comment]
I see! This could indeed be my problem, as I often search for the same things.

**Comment by benibela** [comment]
In texstudio.ini `Search\Find%20History`

**Comment by samcarter8** [comment]
@benibela Thank you very much for your help! The previously saved search words where indeed the problem. 

So I just will write a script that will remove this part of the .ini file before each start of texstudio - this should circumvent the problem!
