### ISSUE TITLE
How to go to next args? Missing in documentation?

### ISSUE THREAD

**Issue by bernhard-kleine** [texstudio-org/texstudio#1301]
### Environment
- TeXstudio: 3.0.1
- Qt: 5.12.1
- OS: win10
- TeX distribution: texlive

I cannot find the command to go to the next args. I looked through the docu, but did not find any. Maybe you could add the texstudio manual to the help menu. It is not very convenient to look into the internet for instructions of the usage of the editor itself. This issue is not mention in "Autocompletion".

**Comment by bernhard-kleine** [comment]
I have seen that the manual is already present, but the issue is not mentioned.

**Comment by dbitouze** [comment]
> I cannot find the command to go to the next args.

Are you looking for <kbd>Ctrl</kbd>+<kbd>→</kbd> and <kbd>Ctrl</kbd>+<kbd>←</kbd>?

**Comment by bernhard-kleine** [comment]
That is what I have been looking for! Thanks a lot. Are these shortcuts in the docu?

**Comment by dbitouze** [comment]
> Are these shortcuts in the docu?

Yes, section 1.5 "Configuring the autocompletion":
>Use Placeholders: if the completed commands have options which need to be filled out, placeholders are put at these positions and they can be jumped to by using Ctrl+Right/Ctrl+Left.

**Comment by bernhard-kleine** [comment]
Ok, I missed that! Thankx again!
