### ISSUE TITLE
overleaf vs texstudio

### ISSUE THREAD

**Issue by kadirseker00** [texstudio-org/texstudio#1302]
I use the app to write my thesis. The template does not work properly. 
we use [this](http://www.fbe.yildiz.edu.tr/media/files/YTU%20Thesis%20Latex-21_07_2020.zip) template to write thesis  
Adding citations is not work. I upload this template to overleaf, it works. 
What is the possible problem? 

### Environment
- TeXstudio: TeXstudio 2.12.16 (git 2.12.16)
- Qt: Using Qt Version 5.12.3, compiled with Qt 5.12.3 R 
- OS: Macos Catalina 
- TeX distribution: 

### Expected behavior
`lorem ipsum \cite{test} `---> lorem ipsum [1] 

### Actual behavior
`lorem ipsum \cite{test} `---> lorem ipsum [test]

**Comment by dbitouze** [comment]
You have to configure TeXstudio (TXS) in order it uses `biber` (and not `bibtex`) as a default bibliography tool: menu Options → Configure TeXstudio → Build → Default Bibliography Tool → Biber.

Then, depending on the context, TXS will run `biber` by itself or not. If not, run:

1. pdflatex (F5)
1. biber (F8)
1. pdflatex (F5)

**Comment by kadirseker00** [comment]
It works when I changed bibtex to biber. Citation in the text is okay but, It is not added to references automatically.

**Comment by kadirseker00** [comment]
Sorry, I have changed the parameter in the default compiler. I fixed it. It works totally.
