### ISSUE TITLE
texdoc not found

### ISSUE THREAD

**Issue by qx87** [texstudio-org/texstudio#1303]
I use portable TeXstudio and portable TeX Live 2019 on USB flash stick. Compilation works fine for LaTeX, but texdoc has been never worked. 
Actually, there is no texdoc command in Configure -> Commands, and I don't know a way to make it work using relative paths.

The bug is very old:
https://sourceforge.net/p/texstudio/bugs/2253/
https://sourceforge.net/p/texstudio/bugs/1280/
https://sourceforge.net/p/texstudio/bugs/1258/
https://sourceforge.net/p/texstudio/bugs/1193/
https://sourceforge.net/p/texstudio/bugs/2296/
https://sourceforge.net/p/texstudio/bugs/2378/

### Environment
- TeXstudio: 3.0.1
- Qt: Qt 5.12.1
- OS: Windows 7
- TeX distribution: texlive

### Expected behavior

TeX documentation should pop up.

### Actual behavior

Error 'texdoc not found'.

### How to reproduce

Create directory structure with both portable programs:

Programs\\
|-  TeXstudio\\
|-  texlive\

Open TeXstudio -> Configuration -> General, set 'Store relative paths' checkbox.

Open TeXstudio -> Configuration -> Commands, set text for LaTeX command like this:
[txs-app-dir]\..\texlive\2019\bin\win32\latex.exe -src -interaction=nonstopmode %.tex

Open TeXstudio -> Configuration -> Build -> Commands ($PATH), set text like this (because texdoc is in that dir):
[txs-app-dir]\..\texlive\2019\bin\win32\

TeXstudio -> Help -> Packages help... -> type any TeX package name, see 'texdoc not found' error.

### Possible solution

I see two ways:
whether in Configuration -> Commands there should be command for texdoc 
or
Configuration -> Build -> Commands ($PATH) should correctly accept relative paths with [txs-app-dir] macro.

**Comment by qx87** [comment]
And yes, using absolute path like d:\Programs\texlive\2019\bin\win32\ in Configuration -> Build -> Commands ($PATH) DOES work.

**Comment by sunderme** [comment]
should be fixed in the latest build (9dd7774)
texdoc command added in config/commands
