### ISSUE TITLE
running latexmk I encounter the following:  SyncTeX: Can't rename FalterInLenzkirch.synctex(busy) to FalterInLenzkirch.synctex.gz

### ISSUE THREAD

**Issue by bernhard-kleine** [texstudio-org/texstudio#1304]
### Environment
- TeXstudio: 3.0.1
- Qt: 5.12.1
- OS: win10 automatic updates
- TeX distribution: texlive

I cannot remove the file ....  .syntec(busy) and I cannot see any owner. This happens when I interfere with the compilation process.

**Comment by muzimuzhi** [comment]
Dose deleting file `FalterInLenzkirch.synctex(busy)` work?

If this problem reproduces when you compile `FalterInLenzkirch.tex` directly from command line (e.g., by running `latexmk FalterInLenzkirch.tex`) and without using texstudio, then this is a latex or latexmk problem, not relevant to texstudio, which is just an editor.

**Comment by bernhard-kleine** [comment]
I have already been told that this arrives most probably due the fact that texlive uses wrapper "around common tools (e.g. latexmk, 
arara etc.) based on the runscript.exe program" [https://tug.org/pipermail/tex-live/2020-September/046111.html](url). I should use the taskmanager in windows to shop the process. Obviously not the problem of texstudio. Not having stopped the process, I am unable to delete FalterInLenzkirch.synctex(busy) even with admin rights.
