### ISSUE TITLE
Highlighting problem after \lstinline

### ISSUE THREAD

**Issue by kiara-ottogalli** [texstudio-org/texstudio#1305]
In the editor, while writing the latex document, after typing the command \lstinline, for instance, \lstinline[language={[Sharp]C}]{void CollectObservations()}, after the first word inside the curly brackets, every character is colored turquoise. Then on the first line of every paragraph, the first word is colored normally, but the rest is colored turquoise. I installed the previous version of texstudio (2.12.6), and it works fine.

### Environment
- TeXstudio: 3.0.1
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior

Normal highlighting after command \lstinline.

### Actual behavior

After the first word inside the curly brackets, all characters are colored turquoise.
The same pattern repeats for all paragraphs thereafter.

### How to reproduce

Include the package:
\usepackage{listings}

Use the command:
\lstinline[language={[Sharp]C}]{void CollectObservations()}

**Comment by muzimuzhi** [comment]
Currently, texstudio only supports syntax`\lstinline[<options>]<char><verbatim text><same char>`. The change toke place in https://github.com/texstudio-org/texstudio/commit/f89f1d7dc99bcf8b3925975d1f2001751fc156c9.

**Comment by sunderme** [comment]
since `\lstinline[language={[Sharp]C}]!void CollectObservations()!` works fine and the other syntax is declared experimental, I don't see a necessity to tweak txs here.
