### ISSUE TITLE
Should save macros after edit not after application close

### ISSUE THREAD

**Issue by clecap** [texstudio-org/texstudio#1307]
### Environment
- TeXstudio: 3.0.1
- Qt: 5.15.0
- OS: Mac 10.15.6
- TeX distribution: N/A

### Expected behavior
After editing a macro and closing the editing dialogue the macro should be made persistent immediately in ~user/.config/texstudio/macro

### Actual behavior
The macro is made persistent only when completely closing the application.

### How to reproduce
Open Texstudio and write on a long document. While doing so, design and edit numerous macros. Do not close Texstudio for several weeks. Face an unexpected crash of the application. Realize that the 20+ macros you have carefully crafted and debugged over the last 2 weeks have not been stored in .config and thus also are not in your backup but...gone. :-)

You can also edit a macro and watch that after closing the macro editor pane the macro files in .config are not updated, only when closing the application - but this is just half the fun.

BTW it looks like the macros also are saved to the macro directory when saving a profile. While this is fine, the astonishing part is that the macros seem not to be stored as part of the profile file. This behavior also is unexpected. It would be a great feature, if you could, optionally, also store the macros as part of a profile. Certainly, the macros should be made persistent when leaving the editor pane.

**Comment by sunderme** [comment]
implemented
