### ISSUE TITLE
Search panel in Internal PDF Viewer not iterating through all results; (zoom-level dependent)

### ISSUE THREAD

**Issue by thatlittleboy** [texstudio-org/texstudio#131]
### Environment
- TeXstudio: 2.12.8 (Git eddac84)
- Qt: 5.8.0
- OS: Windows 10, 64 Bit
- TeX distribution: MikTeX

### Actual behavior
The search panel in the internal PDF viewer iterates through only _some_ search results.

### Expected behavior
The search panel to iterate through _all_ search results.

### How to reproduce

```
\documentclass{article}
\usepackage[paperheight=3in,paperwidth=3in]{geometry}
\usepackage{lipsum}
\newcommand\sampletext{Lorem ipsum dolor sit\par}
\begin{document}
	\lipsum[1]
	\sampletext
	\sampletext
	\sampletext
	\sampletext
	\sampletext
	\sampletext
	\sampletext
	\sampletext
\end{document}
```
Compile this, and from the internal PDF viewer, search for "Lorem". Click <kbd>Enter</kbd> several times, and notice that the search jumps back to the first instance of "Lorem" after the second instance of "Lorem" instead of iterating through all the other Lorem's.

I found this bug to happen sporadically, but it seems to depend on the zoom level of the internal PDF viewer?

![mwe](https://user-images.githubusercontent.com/30731072/39386513-e149f412-4a6c-11e8-8a92-8eade1c00e1d.gif)

----------------------------
(On a separate note: this particular version crashes very often for me on Windows 10. It happens often after (or during?) compilation. Just FYI.)

**Comment by sunderme** [comment]
fixed in repository
