### ISSUE TITLE
Color Scheme overrides customized editor settings in txsprofile

### ISSUE THREAD

**Issue by dkz-phys** [texstudio-org/texstudio#1311]
### Environment
- TeXstudio: 3.0.1
- OS: MacOS 10.15

### Expected behavior

Prior upgrading to version 3+, I can simply change say the editor background color by loading a customized .txsprofile, regardless of the color scheme setting under "Preferences"->"General"->"Appearance".

I really liked the "solarized light" theme in this post: https://tex.stackexchange.com/questions/108315/how-can-i-set-a-dark-theme-in-texstudio. My mac is in dark mode and the light background color works great with the dark frames (plus darkscroll bars, dark side panels etc).

### Actual behavior

Now the editor background color appears to be solely controlled by the color scheme option.  Configurations like

data\background\background=#ede2c2

in either .ini or .txsprofile have no effect on editor appearances.

The customized settings only makes a difference if  the option "ignore Most System Colors" is checked. But then the frame colors are no longer consistent with MacOS dark mode.

I can still change all the colors through the "preference" UI panel, but picking every syntax color manually is very unrealistic...

### How to reproduce
load a txsprofile with an arbitrary background color and observe

Options->Load Profile

**Comment by nik312123** [comment]
I, too, am experiencing this issue. I was on 2.12.22 and tried upgrading to 3.0.1 but decided against it for now due to this issue.

I am on macOS 10.14.6.

**Comment by nik312123** [comment]
Here is mine from my current version: [test.txsprofile.zip](https://github.com/texstudio-org/texstudio/files/5412552/test.txsprofile.zip)

**Comment by sunderme** [comment]
the point is , as stated, that you need to adapt the profile to set colors for darkMode as well.
If they are meant to be the same as for light mode, duplicate the [formats] section to [formatsDark]

**Comment by nik312123** [comment]
Hi, sunderme. I tried doing so, but the color settings still did not work. I have attached my modified profile here: [test.txsprofile.zip](https://github.com/texstudio-org/texstudio/files/5427618/test.txsprofile.zip)

**Comment by sunderme** [comment]
works as intended ... black background in light and dark mode (after restart of txs)
by the way, when using it as profile, probably best to remove eveyrthing which is not supposed to change, i.e. all categories beside formats/formatsDark

**Comment by nik312123** [comment]
Okay. It did actually load. I had to restart 3.0.1 after loading the profile.
