### ISSUE TITLE
Customize Idefix to recognize $ $ as parenthesis

### ISSUE THREAD

**Issue by deltakam** [texstudio-org/texstudio#1312]
### Environment
- TeXstudio: 3.0.1
- Qt: 5.15.0
- OS: mac
- TeX distribution: texlive

### Expected behavior
I want Idefix - Parenthesis menus to work for $ $, the symbol to enclose equations

### Actual behavior
It does not do that. I googled it and was not able to find any option to change what is qualified as parenthesis for Idefix.

### How to reproduce
Try to use any menus of Idefix - Parenthesis on $ $.

**Comment by sunderme** [comment]
That ability was lost in the transition from <3.0 to 3.0
I will take a look whether it is feasible to set up again

**Comment by sunderme** [comment]
fixed
