### ISSUE TITLE
How to contribute with a cwl file?

### ISSUE THREAD

**Issue by kitanokuma** [texstudio-org/texstudio#1315]
I've written a cwl file for the tdsfrmath package of which I'm the author. 
How could I make it available to everybody?

**Comment by sunderme** [comment]
the easiest for us would be a pull request (there should be tutorials on how to do it somewhere)
but you can also just attach it here 
A pull request may be easier in the long run, as cwl are usually reviewed to make the best of txs features.

**Comment by kitanokuma** [comment]
I've tried to do that but the result seems odd.
I hope I've not broken anything

**Comment by sunderme** [comment]
yes, as commented in the PR, the base needs to be master branch, up to date.

**Comment by sunderme** [comment]
I have added the cwl by downloading the attachment as the PR was not suitable
