### ISSUE TITLE
Profile change no longer possible

### ISSUE THREAD

**Issue by bakchos** [texstudio-org/texstudio#1317]
### Environment
- TeXstudio: 3.0.1
- Qt: change profile
- OS: macOS Catalina 10.15.7
- TeX distribution: texlive

### Expected behavior
use load profile to change the appearance after a restart of texstudio

### Actual behavior
load profile has no effect; it worked fine before the upgrade; some behavior on second mac

### How to reproduce
upgrade and load different profile; it will have no effect

**Comment by muzimuzhi** [comment]
Can you provide some specific profiles? And perhaps you can give more info above "some behavior on second mac".

**Comment by bakchos** [comment]
I copied these two profiles from in web. They worked fine before the upgrade:



I have a MacBook Pro and an iMac. Both show the same behaviour. As soon as the upgrade was done, it was impossible to change profiles.

**Comment by muzimuzhi** [comment]
The attachments are missing. To attach files to an issue comment, you have to open the webpage on github.com.

**Comment by bakchos** [comment]
[Archiv.zip](https://github.com/texstudio-org/texstudio/files/5445730/Archiv.zip)

**Comment by sunderme** [comment]
same as #1311
