### ISSUE TITLE
No file found for Debian 10 amd64 3.0.1, QT 5

### ISSUE THREAD

**Issue by tignous** [texstudio-org/texstudio#1318]
When I tried to update my texstudio version on the download part of the website (https://www.texstudio.org/), I couldn't get the latest version for Debian 10, amd64 : [this link](http://download.opensuse.org/repositories/home:/jsundermeyer/Debian_10/amd64/texstudio_3.0.1-1+2.1_amd64.deb) (the i386 version didn't work too).

Again today, I just get a 404 error page... It's quite strange because I didn't see any complaint about that and the others versions function well.
(I'm working with an updated Debian 10 and Firefox.)

**Comment by sunderme** [comment]
fixed
no idea why OBS triggers a new build (and changes the binary name)
