### ISSUE TITLE
texdoc not responding to querys (takes to long?)

### ISSUE THREAD

**Issue by Stimmenhotel** [texstudio-org/texstudio#1319]
I have just uninstalled both, TexStudio nad Miktex to be sure.
Also I have used the "Restore default settings..." of TS.

I believe it worked on 2.12.22, but I rarely used it in the last year.

I checked if this error occurs on any simple template. My test case is:

```
\documentclass[]{scrreprt}

\usepackage{color} %extra added

% Title Page
\title{}
\author{}


\begin{document}
\maketitle

\begin{abstract}
\end{abstract}

\end{document}     
``` 

**Another procedure**
Also trying to use "Package Help..." is not working.
If you type "color" in the text field: 1. It tells me nothing found, then a few seconds later I can `Open` the documentation.
Now I receive a error popup: "texdoc took too long to open the documentation for the package: color".
But a few seconds after the documentation is opened anyway.

If I run "texdoc color" in my cmd it will take quite a few seconds but opens the documentation anyway.

Don't know if related to https://github.com/texstudio-org/texstudio/issues/1303 since there the texdoc binary is not even found.

### Environment
- TeXstudio: TeXstudio 3.0.1 (git 3.0.1)
- Qt: Using Qt Version 5.12.1, compiled with Qt 5.12.1 R
- OS: Windows 10
- TeX distribution: MikTex 20.10

### Expected behavior
Open the package documentation inside internal PDF viewer

### Actual behavior
Shows popup: "texdoc did not respond to query on package: color"

### How to reproduce
Create new scrreprt document from template.
Add \usepackage{color}
Right click the "color" and press "open package documentation (color)"

**Comment by muzimuzhi** [comment]
> It tells me nothing found, then a few seconds later I can `Open` the documentation.

> If I run "texdoc color" in my cmd it will take quite a few seconds but opens the documentation anyway.

Did the lengths of these two "a few seconds" similar? Or did texstudio take obviously longer time to open the documentation?

**Comment by sunderme** [comment]
on cmd.exe/powershell, does texdoc color give a meaningful result ?

**Comment by Stimmenhotel** [comment]
> Did the lengths of these two "a few seconds" similar? Or did texstudio take obviously longer time to open the documentation?

Using right click won't open anything.
The time between click open and the error message in both cases could be nearly identical. (roughly estimated, since it don't take long, 1-2 seconds maybe)

> on cmd.exe/powershell, does texdoc color give a meaningful result ?

This is on my laptop which is not working.
```
2020-10-28 21:57:43,969+0100 INFO  texdoc - this process (13760) started by 'texstudio' with command line: "C:\Program Files\MiKTeX\miktex\bin\x64\texdoc.exe" --list-only color
2020-10-28 21:57:46,176+0100 INFO  texdoc - this process (13760) finishes with exit code 0
```
```
C:\>texdoc --version
MiKTeX Help Utility 4.0 (MiKTeX 20.10)
```

Well, before opening this issue I tested the same procedure on the laptop of a friend of mine. We both are working with the same versions (TexStudio, Miktex and on Windows 10).
Only difference are the custom configurations within TS, which are mostly design/colors. (as far i remember)

Now for this answer I tried to reproduce the error with the steps from the issue on my desktop pc ... and it is working.
Again, same versions are used here too...
Same log output of texdoc... 

> Did the lengths of these two "a few seconds" similar? Or did texstudio take obviously longer time to open the documentation?
Now I tried to open both documentations the same time (Package help...) and the laptop is visibly slower.
Where the PC already opened the PDF (in sumatrapdf), the laptop haven't opened the error message yet.
The error popup on my laptop opened a moment after the pdf on PC.
A short moment later the pdf on the laptop was opened too.
Laptop until PDF: ~4s
PC until PDF: ~2s

**Comment by sunderme** [comment]
txs uses a time-out of 2s.
That has been changed in the current dev version while fixing the different command handling

**Comment by Stimmenhotel** [comment]
Using the "Help->Package help..." tool works now.

But the right click option does not work and won't notify anymore (timeout deactivated completely?).
According to the log the new commands won't be recognized:

```
2020-10-30 10:34:38,402+0100 INFO  texdoc - this process (18108) started by 'texstudio' with command line: texdoc.exe --list --machine color
2020-10-30 10:34:38,418+0100 FATAL texdoc - --list: unknown option
2020-10-30 10:34:38,418+0100 FATAL texdoc - --list: unknown option
2020-10-30 10:34:38,418+0100 FATAL texdoc - Info: 
2020-10-30 10:34:38,418+0100 FATAL texdoc - Source: 
2020-10-30 10:34:38,418+0100 FATAL texdoc - Line: 0
```  

Same output if i try `texdoc --list color` or `texdoc --machine color` directly in cmd.
Both options are not known to texdoc.

Just found this:
> Texdoc is part of the TeX Live distribution. (A command named texdoc is also available in MiKTeX, but it is merely a shortcut for an independent program, mthelp.) 
https://www.tug.org/texdoc/

mthelp documentation: https://docs.miktex.org/manual/mthelp.html

This now also answers me why the --version shows "MiKTeX Help Utility 4.0 (MiKTeX 20.10)" and why i wasn't bale to use -V instead --version...

**Comment by sunderme** [comment]
fixed in latest dev version
