### ISSUE TITLE
[Feature request] Autocomplete cite key by full text search

### ISSUE THREAD

**Issue by tranhungnghiep** [texstudio-org/texstudio#132]
### Environment
- TeXstudio: 2.12.6
- Qt: 5.7.1
- OS: Mac 10.11.6
- TeX distribution: TeXLive-2016

When typing `\cite{somewords`, autocomplete shows a list of cite keys that start with 'somewords'. But I want it to show cite keys that contain 'somewords' inside, that is doing a full text search on cite keys.

For example if cite key is `[author][title][year]`, then 'somewords' could be author's name (at the beginning) or paper's title (inside).

**Comment by tranhungnghiep** [comment]
I looked into the code, it seems not very difficult, the current implementation is simple C++ string operation, no index involved.

We just need to change `beginsWith()` to `contains()`, and maybe add the logic to rank result list showing most related citations on the top. I think `contains()` will not affecting the UX, except on very large bib file, but in that case `beginsWith()`  will also suffer.

I'll do this soon on a free weekend when I find it. Do some of you familiar with the codebase have any warning/gotcha for me?

**Comment by sunderme** [comment]
the completer works with sorted list for performance reasons. contains() might produce unsorted lists and may lead to a performance drop. Some users works with thousands of bibids ...

**Comment by tranhungnghiep** [comment]
Sorted list may be made by post-processing, I would like to keep the beginsWith() list at the top, then append the contains() to it.

Performance will be sure to drop, but is it bad enough? I think there are some citation managers/plugins supporting full-text search of even the title. For example the Zotero plugin for Word/Libre.

**Comment by sunderme** [comment]
there is a reason why the code path has been optimized for speed ...

**Comment by tranhungnghiep** [comment]
@sunderme As you are more familiar with it, can you elaborate on this design choice? Maybe current hardware and software is fast enough to make a change? Like an average laptop nowadays is faster than a workstation in the past.

If UX speed is critical, one workaround is to do multiprocessing, let a process do the longer search while fetching the usual beginsWith() list to user. However this will make the code more complicated to write and maintain.

I personally think there are rooms for improvements here, like full-text search, case insensitive search... it will make writing easier.

**Comment by sunderme** [comment]
the point is that users don‘t accept delays when typing. So one has to be careful... anyway, try it and we will see

**Comment by timhoffm** [comment]
@tranhungnghiep If you intend to dive into this, I suggest that you check what's common practive for more advanced [string searching](https://en.wikipedia.org/wiki/String-searching_algorithm). You'll most likely need some preprocessed data structure for fast lookup to ensure that we'll get millisecond response time of the completer.

**Comment by tranhungnghiep** [comment]
@timhoffm Thanks for the link. Currently I intend to use the standard C++ function. C++ use the naive string search algorithm (O(nm)), however the developers of C++ base their choice on the average case complexity, which is roughly O(n), with a smaller constant factor than advance algorithms like KMP.

May we reference the implementations of other tools? This is not a new problem, at least I know of Zotero plugin for Word supports it.

**Comment by timhoffm** [comment]
In the end, it all comes down to benchmarking the actual code. As a rough estimate, I would require an algorithm to find matches in 1000 entries within 10ms (on an average 2-core machine). @sunderme Do you agree this is a reasonable performance requirement?

We also should have the option to fall back to the beginsWith variant, either by manual config option, or automatically if the bib file is too large.

**Comment by tranhungnghiep** [comment]
I think that performance requirement is OK. I did a quick benchmark on string search here, on a single core, core i5 1.8GHz: https://gist.github.com/tranhungnghiep/25ad3a2969136cdb284e8e8867432657
It's in Python, because actually I'm not working with C++ currently (thus I would appreciate experts in C++ help). 

Some observations: 
- Python's implementation of Boyer–Moore–Horspool is actually faster than the naive search.
- C++ should be faster.

**Comment by alexeiZamyatin** [comment]
This is a feature available in overleaf/sharelatex - would be great to have this in Texstudio.

**Comment by thatlittleboy** [comment]
This feature has been implemented in 2.12.12 called "fuzzy autocomplete". It works not just with cite keys but with cross-ref labels, commands and even normal text autocompletion.

**Comment by thatlittleboy** [comment]
@tranhungnghiep Can you give a concrete example? That's not my experience, for example, if `gingras2011` is a cite key, typing `ras` still suggests that key in the fuzzy autocomplete.

**Comment by tranhungnghiep** [comment]
@thatlittleboy I'm on TeXstudio 2.12.12, updated yesterday. Now I look again, the problem is different. Fuzzy can skip first character, but the problem is it does not work at all for cite key. Typing `\cite{` shows nothing. Not sure if this is a bug or not.

**Comment by tranhungnghiep** [comment]
@thatlittleboy It works! I can press Enter with `\cite{bibid}` and use fuzzy. Do you know how to search case insensitive, if that is implemented?

**Comment by thatlittleboy** [comment]
@tranhungnghiep 

> Do you know how to search case insensitive, if that is implemented?

That's not implemented yet I believe. Again, if you want that as an option, it warrants a new issue in my opinion. But do as you so wish.

> I think the discussed information here will be useful for future searchers when they try to use the feature.

If you open a new issue and reference this one, a note saying "so-and-so issue referenced this issue..." will appear here, so there's no worry about future searchers missing any discussed information.

**Comment by tranhungnghiep** [comment]
@thatlittleboy Sure, in that case, "case insensitive search" should be in a new issue.

Thanks @sunderme for implementing fuzzy autocomplete, it mostly solved this feature request. So I will close this issue now.
