### ISSUE TITLE
newabbreviation label not appearing

### ISSUE THREAD

**Issue by judober** [texstudio-org/texstudio#1322]
### Expected behavior
When using `\newabbreviation` of the `glossaries-extra` package to define an abbreveation and then citing with `\gls{}`, the labels should appear in Texstudio.

### Actual behavior
The labels do not appear.

### Fix
I allready opend a pullrequest which adds a `glossaries-extra.cwl` that fixes the problem.

**Comment by muzimuzhi** [comment]
What you need is to dynamically add items, arguments of some macros, to a completion list triggered by `\gls{<cursor position>}`, which, I'm not sure supported by texstudio or not. The most similar utility introduced in [`user manual`](https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html#CWLDESCRIPTION) is `#s#%color`.

**Comment by judober** [comment]
I think `#l`works fine (as in case of `newacronym` of `glossaries.cwl`)
