### ISSUE TITLE
Newabbreviation label does not appear

### ISSUE THREAD

**Issue by judober** [texstudio-org/texstudio#1323]
### Expected behavior
When using `\newabbreviation` of the `glossaries-extra` package to define an abbreveation and then citing with `\gls{}`, the labels should appear in Texstudio.

### Actual behavior
The labels do not appear.

### Fix
I allready opend a pullrequest which adds a `glossaries-extra.cwl` that fixes the problem. #1321

**Comment by muzimuzhi** [comment]
If current issue is an exact duplicate of #1322, then this one can be closed.

**Comment by judober** [comment]
Yes, sorry for the double post

**Comment by muzimuzhi** [comment]
(_whisper:_ As the one who opened this issue, you can close it by yourself.)
