### ISSUE TITLE
Feauture request

### ISSUE THREAD

**Issue by pizdjuk** [texstudio-org/texstudio#1324]
It would be nice to have some git-plugin with a possibility to update TODO-list, binded to lines.

Something like comments to the tex-file

Now it is possible, for example in overleaf, but it implies to work online. Which is a pain. Manytimes no collaboration work is needed, but a comments of colleges, and editing of it.

**Comment by sunderme** [comment]
you should find a better title

**Comment by pizdjuk** [comment]
Already there
