### ISSUE TITLE
How to install without admin rights

### ISSUE THREAD

**Issue by erxa90** [texstudio-org/texstudio#1325]
### Environment
- TeXstudio: 3.0.1
- OS: Windows 10 (UAC enabled)
- TeX distribution: miktex (all?)

### Expected behavior
It should be possible to install texstudio for a normal / regular windows user

### Actual behavior
It is not possible to install without providing the admin password / pin. 
Also there is no option to install for one user.

### How to reproduce
Download the installer and try to install as regular user.

**Comment by sunderme** [comment]
you can unpack the portable version wherever you want and start it there.
