### ISSUE TITLE
Structure Pane: files with underscores/dots/hypens "not found"

### ISSUE THREAD

**Issue by kucharsky** [texstudio-org/texstudio#1326]
When tex file consists:
\input filename_with_underscores.tex
or
\input filename.with.dots.tex
or
\input filename-with-hypens.tex
(which are valid names of existing files, "inputed" by TeX without problems)
Structure Pane shows only "filename" in red with info "File not found" (for all 3 files).

### Environment
- TeXstudio: 3.0.1
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution: texlive 2019

### Expected behavior
Actual filenames displayed in Structure Pane. Clicking a name opens a file.

### Actual behavior
Truncated name displayed in red. Clicking that displays modal "warning" window with info "File does not exist. Do you want to create it?"

### How to reproduce
Create files with names:
filename_with_underscores.tex
filename.with.dots.tex
filename-with-hypens.tex
In the main.tex put
\input filename_with_underscores.tex
\input filename.with.dots.tex
\input filename-with-hypens.tex

**Comment by sunderme** [comment]
txs works fine if you put braces around the filename

**Comment by kucharsky** [comment]
True, that works. I suggest this info should be added to user manual, eg. section 2.4.
