### ISSUE TITLE
Unable to get LuaText to work properly

### ISSUE THREAD

**Issue by BeerStud** [texstudio-org/texstudio#1327]
I have a 'tex' file that works fine using TexStudio on one of my PC's. On the other one, it fails to compile. I cannot figure out why. This error message appears in the "Check Latex Installation" output. "where pdflatex: ERROR: Invalid pattern is specified in "path:pattern"." I have included the entire file "TexStudio.txt"

### Environment
- TeXstudio: <3.0.1>
- Qt: Version 5.12.1, compiled with Qt 5.12.1 R
- OS: Win 10 PRO
- TeX distribution: MikTeX
[TexStudio.txt](https://github.com/texstudio-org/texstudio/files/5470987/TexStudio.txt)
[TexStudio-Log.txt](https://github.com/texstudio-org/texstudio/files/5470988/TexStudio-Log.txt)

### Expected behavior
I would expect the file to compile like it does on my other PC

### Actual behavior
It doesn't compile. I have included the entire build log file "TexStudio-Log.txt"

**Comment by sunderme** [comment]
lualatex is run, so the problem seems not to lie on txs side ...
You could recheck using texworks or powershell. 
If the lualatex output is unexpected (error, etc.) , the document is most likely not correct ...

**Comment by sunderme** [comment]
no feedback
