### ISSUE TITLE
Installer adds .... stuff...

### ISSUE THREAD

**Issue by foreachthing** [texstudio-org/texstudio#133]
### Environment
- TeXstudio: 2.12.8
- OS: Windows 8.1
- TeX distribution: texlive

### Expected behavior
Same as 2.12.6

### Actual behavior
![image](https://user-images.githubusercontent.com/10420187/39488740-734388f6-4d83-11e8-9745-5de61af8a232.png)

### How to reproduce
See _Programs and Features_ after installation of 2.12.8.

**Comment by benibela** [comment]
fixed in 4e3e3d4
