### ISSUE TITLE
%n reproduced verbatim both in the bottom and in the "Messages" tab

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#1330]
### Environment
- TeXstudio 3.0.2 (git 3.0.1-92-gf2a43c21)
- Qt: 5.12.6, compiled with Qt 5.12.6 D
- OS: Linux Mageia 7
- TeX distribution: TeX Live 2020

### Actual behavior
Some `info` in `uiconfig.xml` (e.g. the `maketitle` one) contain `%n` which are strangely reproduced verbatim both in the bottom and in the "Messages" tab.

### How to reproduce
Open a new document, go to "LaTeX" menu and select e.g. `\maketitle{}`.

**Comment by sunderme** [comment]
%n is not interpreted as line break.
As the info is displayed in status line, it should not use line break anyway...

**Comment by muzimuzhi** [comment]
So the `%n`s in `info="..."` should be removed? For example, `info="... title page%n- except ..."` in
https://github.com/texstudio-org/texstudio/blob/3e07a68592c66c7a0b202f2f2ecbd3f81e11d999/uiconfig.xml#L10
![image](https://user-images.githubusercontent.com/6376638/100267737-e348e980-2f8e-11eb-99fa-a47e49492841.png)

**Comment by sunderme** [comment]
That would be my take away.
