### ISSUE TITLE
textstudio 3.0.1 repeated crashes on Win10

### ISSUE THREAD

**Issue by ap0305-thunder** [texstudio-org/texstudio#1332]
### Environment
TeXstudio 3.0.1 (git 3.0.1)
Using Qt Version 5.12.1, compiled with Qt 5.12.1 R
Win 10
MikTeX 2.9
### Actual behavior
Very frequent random crashes: 
1) not responding on the window title
2) all window becomes whiteish
3) texstudio has stopped working....
### How to reproduce
random but frequent, such as about every one hour.
possibly correlated with actions on the viewer.

**Comment by 1900011604** [comment]
I am using Win10 and Manjaro Linux 20.2.

Texstudio works faster and smoother on Linux, obviously. The Settings on Texstudio response very slow on Win10, it will crash for several seconds then apply.

**FOR WIN10 PLEASE USE VS CODE**

**Comment by sunderme** [comment]
you can try the latest dev build as it uses 64 bit (in case the problem is memory).
Apart from that without test case ...

**Comment by BeerStud** [comment]
I have been using TexStudio on a Win 10 PRO / 64-bit machine for years without any problems. It sounds like you have a problem with your system, perhaps insufficient memory or a disk that might be going bad. Have you run a full set of diagnostics on the machine to rule out a problem?

**Comment by 1900011604** [comment]
> you can try the latest dev build as it uses 64 bit (in case the problem is memory).
> Apart from that without test case ...

where to find the dev builds? I use Surface Pro 6 with 8 GB RAM

**Comment by sunderme** [comment]
https://bintray.com/sunderme/texstudio

**Comment by ap0305-thunder** [comment]
> 
> 
> you can try the latest dev build as it uses 64 bit (in case the problem is memory).
> Apart from that without test case ...

Thanks, I am trying. So far so good... fingers crossed.

**Comment by ap0305-thunder** [comment]
> 
> 
> I have been using TexStudio on a Win 10 PRO / 64-bit machine for years without any problems. It sounds like you have a problem with your system, perhaps insufficient memory or a disk that might be going bad. Have you run a full set of diagnostics on the machine to rule out a problem?

Hi. I am sorry to say that "It works for me" is not, usually, a particularly useful analysis.
Yes, it is possible that my pc has hw problems, and I will double check. But I doubt I have lack of resoures with my portable workstation, Xeon quad-core e500 with 32 Gb RAM. By the way, I use it very often for computational tasks much heavier and longer. So I think it is very well capable to run lualatex even if I run on a 135k lines /5MB latex file. 
Thanks for your comments.

**Comment by 1900011604** [comment]
It says:
**No direct downloads selected for this package.**
???

**Comment by ap0305-thunder** [comment]
> 
> 
> It says:
> **No direct downloads selected for this package.**
> ???

https://bintray.com/sunderme/texstudio/texstudio-win#files

**Comment by sunderme** [comment]
no furthermcomments, imasumme it is fixed

**Comment by ap0305-thunder** [comment]
> 
> 
> no further comments, i assume that it is fixed

In fact I was waiting for some more test; so far so good (it crashed only once instead of 1 per hour)....
THANKS
