### ISSUE TITLE
jumps by the internal viewer

### ISSUE THREAD

**Issue by ap0305-thunder** [texstudio-org/texstudio#1333]
Environment
TeXstudio 3.0.1 (git 3.0.1)
Using Qt Version 5.12.1, compiled with Qt 5.12.1 R
Win 10
MikTeX 2.9

After carefully fitting size and position of the text in the viewer window,
as soon as I click on the latex source, the viewer moves at the correct position, but it also displaces horizontally going out of center/view.

**Comment by sunderme** [comment]
what have set for the viewer ? If there is a horizontal scrollbar, there is nothing you can do.

**Comment by ap0305-thunder** [comment]
Hi, thanks.
I feel I was not able to explain my issue.
Please have a look at the video:
https://drive.google.com/file/d/1fDU3QJfqTV1H4UXJ3359RZrO7Mq3iJF5/view?usp=sharing
At t=6s, I click on the structure tab on the left, and the viewer, while moving to about the correct line, also jumps horizontally, going out of center; this is of course annoying because I have to recenter it very often.
I am not sure this is what expected.
Thanks

**Comment by sunderme** [comment]
I could not open the video ...

**Comment by ap0305-thunder** [comment]
> 
> 
> I could not open the video ...

oops sorry... I tried to set correclty the sharing now; you are welcome tro try again, if you like. Otherwise I can send you privately.
Thanks

**Comment by sunderme** [comment]
from the looks of it, txs jumps to a wrong page as well ?

**Comment by ap0305-thunder** [comment]
> 
> 
> from the looks of it, txs jumps to a wrong page as well ?

Well, not really.... it usually does not jump very precisely (let's say +/- one page), but it think I remember someone mentioning in some thread that this depends on synctex, not on texstudio. So I consider it acceptable. You see in the video it jumping to a table of contents, but I have one at every chapter, so this should be ok.

**Comment by sunderme** [comment]
indeed synctex is responsible for the matching of text to pdf position.
An easy cross-check whether txs or synctex is to blame, is using texworks in order try to see if the same issue appears there.

**Comment by ap0305-thunder** [comment]
> indeed synctex is responsible for the matching of text to pdf position.
> An easy cross-check whether txs or synctex is to blame, is using texworks in order to try to see if the same issue appears there.

.... the same jump with texworks.... even if the vertical positioning seems to be more precise. On the other hand, it is overall very much slower than texstudio

**Comment by sunderme** [comment]
so we can close this as there is nothing we can do ?

synctex is developed on github as well, but there is not much activity ... maybe you want to report there ?

**Comment by sunderme** [comment]
synctex issue

**Comment by ap0305-thunder** [comment]
Sorry to come-back on this, but I realized that the problem only happens with source projects using multiple files: is there any chance that this is due to texstudio gui?
