### ISSUE TITLE
Options/keyvals don't work for some macro in custom CWL

### ISSUE THREAD

**Issue by tweh** [texstudio-org/texstudio#1334]
### Environment
- TeXstudio: 3.0.1 (git 3.0.1)
- Qt: 5.15.0
- OS: macOS 10.15.7
- TeX distribution: texlive

### Expected behavior
I wrote the following custom CWL code for some macros. The keyvals work as expected for \elementsettings, but they don't for `\element`
```txt
\element{element}{xpos}{node ID}{ID}
\element{element}{xpos}{node ID}{ID}[options%keyvals]
\element*{element}{xpos}{node ID}{ID}
\element*{element}{xpos}{node ID}{ID}[options%keyvals]
\elementsettings{options%keyvals}
#keyvals:\element#c,\element*#c,\elementsettings#c
align=#left,right
type=#pattress,outlet
height=#outlet,switch,controller,sensor,movementsensor,lamp,%<height%>
ductwork=#none,up,down
components=%<components%>
function=%<function%>
name=%<name%>
component-alignment=#above,below,left,right
id-alignment=#above,below,left,right
info-alignment=#above,below,left,right
check-id=#true,false
#endkeyvals
```

### Actual behavior
The keyvals should also work for `\elements`. However I fear this is more a problem of my definition rather than an actual bug …

### How to reproduce
add code to cwl, restart TeXstudio, test

Thanks!

**Comment by sunderme** [comment]
my guess would be that [options%keyval] can't be behind the mandatory arguments for it to work in txs

**Comment by tweh** [comment]
Possible. But in that case I’d consider it to be a bug.

**Comment by sunderme** [comment]
as stated earlier, the issue is the optional command after obligatory commands.
txs does not handle that situation and it is unlikely to change

**Comment by tweh** [comment]
Thanks again. I know my macro syntax is a bit off the standard, but perfectly valid TeX code, so maybe one could take into consideration to make option list work her as well. As far as I can see it should’t be a great difference for TeXstudio to autocomplete such a list in braces instead of brackets at any point in the syntax definition (of course it must be marked with `%keyval` in the CWL file.

**Comment by sunderme** [comment]
won't change
