### ISSUE TITLE
Automatic saving, where to trigger it?

### ISSUE THREAD

**Issue by bernhard-kleine** [texstudio-org/texstudio#1335]
### Environment
- TeXstudio 3.0.1 (git 3.0.1)
Using Qt Version 5.12.1
- OS: win10
- texlive

I do not see it in Option->Adv.Editor. According to Tim Hoffmann ( https://sourceforge.net/p/texstudio/discussion/907840/thread/66d14c22/ ) it should be there.
Can someone point to the correct line?

**Comment by sunderme** [comment]
marked in the image
<img width="1181" alt="Screenshot_20201103_175858" src="https://user-images.githubusercontent.com/14033169/98017110-14eeea80-1dff-11eb-9cf9-d2458158e77b.png">

**Comment by bernhard-kleine** [comment]
Thanks. I'm sorry. I did not see the wood for the trees.

Bernhard
