### ISSUE TITLE
laggy input for "Help"->"Package help..."

### ISSUE THREAD

**Issue by Stimmenhotel** [texstudio-org/texstudio#1337]
I have checked this behavior on two notebooks.
Mine is running a i5-3320M and a friend of mine is running a i7-10710U.
Although his runs faster he is noticing significant lags too.
But while mine really halts for a few seconds, his just lags a little while typing.
The initial opening and initial search is not as interrupting for him as it is for me, but also noticeable.

It seems the text input directly searches for the input string without waiting a little bit (time between keystrokes).
And the search seems to interrupt the UI until a response is received.

### Environment
- TeXstudio: 3.02-6892dfc
- Qt: 5.12.3
- OS: Windows 10
- TeX distribution: Miktex 20.10

### Expected behavior
Fluent input and search after i wrote the whole package name or waited for a short duration

### Actual behavior
Long opening time (package text field already contains input = 1. search)
Once initial input is deleted, 2. search on first character of new input (halts the ui until search is complete)
3. search after 2. search, if I wrote the package name while ui was halted, else:
search for every short break i took while typing.

### How to reproduce
1. Open TexStudio 3.0.2-6892dfc
2. Go to Help -> "Package help ..."
3. do your search after the first halt of ui

**Comment by sunderme** [comment]
confirmed. I have to take a closer look ...

**Comment by sunderme** [comment]
have you tried the latest dev build ?

**Comment by Stimmenhotel** [comment]
Just did it.
It is now working better, but introduced a new bug.
If you delete the input field using backspace or delete, the "open" button will be locked in greyed out state.
It keeps working if you just replace the text by highlighting the previous text (default behaviour).

**Comment by sunderme** [comment]
that is a feature. you can only open valid packages

**Comment by Stimmenhotel** [comment]
Yeah, but even if you enter a valid package name (color, amsbsy, colorx) you wont get the "Open" activ again.
![grafik](https://user-images.githubusercontent.com/15821524/98678339-ae1d8400-235e-11eb-9422-c88ad1489447.png)

**Comment by Stimmenhotel** [comment]
Okay, today I checked this with my notebook again.
Here it is working. (Using latest dev build from yesterday 12.Nov)...

I will try it in a few hours on my desktop again (with same version as on laptop).

Also I noticed colorx doesn't exist... But it is only one of the packages I am testing with.
Instead I should have used xcolor everytime ...

Also I will check the logs on my desktop again (on my notebook there is no error logged, since it is working)

**Comment by sunderme** [comment]
I have checked, it works
mthelp is really slow though compared to texdoc

**Comment by Stimmenhotel** [comment]
Okay, tested it today again.
It seems it I haven't head the same version installed.
Updated to the latest version (4 days ago) of the dev build and it is working.

Is it wanted each search is printed into the log?
![grafik](https://user-images.githubusercontent.com/15821524/99288582-1c20ea00-283c-11eb-8934-68ce415fddfb.png)

Else everything is fine now and this issue can be closed.

**Comment by sunderme** [comment]
yes, a by-product of using buildmanager ...
