### ISSUE TITLE
Support for Qt6 port wanted

### ISSUE THREAD

**Issue by sunderme** [texstudio-org/texstudio#1338]
I have started Qt6 support. Compilation in branch Qt6 works but start-up crashes before main.cpp.
Any hints on how to resolve this are welcome.
Furthermore Qt6 port needs adaptation concerning scripting and also how to handle QTextCodec which is not supported that way in Qt6.

### Environment
- TeXstudio: 3.0.2 (branch Qt6)
- Qt: 6.0.0 beta
- OS: Linux
- TeX distribution: N/A

**Comment by sunderme** [comment]
@MeanSquaredError  any interest ?

**Comment by sunderme** [comment]
on a general note, branch Qt6 compiles and works with Qt5 (apart from scripting and textcodec)

**Comment by MeanSquaredError** [comment]
Sure, please assign the issue to me. It may take me a few days before I can look into this, but I will try to get down to it this week.

I guess we want to keep Qt5 support after adding support for Qt6 ?

**Comment by sunderme** [comment]
yes, since linux will take some time to deliver Qt6.
We may raise the minimum version though.

**Comment by MeanSquaredError** [comment]
OK, great. I will try to get down to it this Friday and get it working on Linux and after that add the adjustments for Windows (in case it needs any).

The Linux distros are indeed slow to adopt the new major Qt versions.

**Comment by sunderme** [comment]
sounds good

**Comment by sunderme** [comment]
okay , I got it running
1) use the internal quazip (tweaked to compile with Qt6)
2) don't use libqterminal (texstudio.pro needs to be tweaked)
Obviously Qt5 libs should not appear in the build ...

**Comment by sunderme** [comment]
@MeanSquaredError still interested in helping with the port ?
