### ISSUE TITLE
Show even pages as left pages and odd as right ones

### ISSUE THREAD

**Issue by tsfg** [texstudio-org/texstudio#1339]
### Environment
- TeXstudio: 3.0.2-202010081711-git_9b0ac94
- Qt: 5.12.3
- OS: Windows(7,10), 
- TeX distribution: miktex

### Expected behavior
in Integrated pdf-viewer : A double-sided document (option twoside) is shown like the even page on a left side and the odd pages on the right, if two pages are displayed side by side. 
The first left page position has to be left free.
How about an option to set this as a fixed behavior.

### Actual behavior
The even page is displayed on the left and the odd page follows on the right. 
~~It looks like it depends on the window fitting option. But I don't get the systematic right now. ~~

### How to reproduce

Open a twoside formatted document after compiling in Integrated pdf-viewer.

**Comment by sunderme** [comment]
turn off view/grid/single page step

**Comment by tsfg** [comment]
It looks like the option View/continuous is influencing the behavior.

**Comment by tsfg** [comment]
> turn off view/grid/single page step

That set the wanted behavior. 
Thanks for the quick solution.

**Comment by tsfg** [comment]
Any source to read more on the viewers options and functions? 
Especially, what is the single page step and continuous used for?

**Comment by sunderme** [comment]
not sure if that behaviour is documented with more detail in the manual ... but since nobody is reading the manual anyway ...
