### ISSUE TITLE
[feature request] Custom command for including files in structure view?

### ISSUE THREAD

**Issue by andyboeh** [texstudio-org/texstudio#1340]
### Environment
- TeXstudio: 3.0.1
- Qt: 5.15.1
- OS: Arch Linux
- TeX distribution: texlive

For some compatibility reason, I had to wrap calls to `\input` and `\include` into a custom macro. Now the structure view is broken, i.e. TexStudio does not detect my subfiles any more. Is there any chance I can tell the structure view to parse my custom command (`\includeCond`) the same way as `\include` is parsed?

**Comment by sunderme** [comment]
you need to provide a cwl file, see manual and wiki

**Comment by andyboeh** [comment]
Sorry for the noise, I really should have searched better. This worked out nicely!

For reference, I created the file ~/.config/texstudio/usercommands.cwl with the following content:
```
\includeCond{%<file>%}#i
```
After enabling `usercommands.cwl` in Options -> Configure TeXStudio -> Completion, everything was fine.

Thanks for the quick reply!
