### ISSUE TITLE
Change behaviour when you select some text and press Ctrl+E

### ISSUE THREAD

**Issue by desk7** [texstudio-org/texstudio#1342]
### Environment
- TeXstudio: 3.0.1
- Qt: 5.12.1 R
- OS: Windows 10 64 bit
- TeX distribution: TeX Live 2020

### Expected behavior
When I select some text and then I press Ctrl+E to create an environment, I expect to have a new environment which has the selected text as _content_ and to have the cursor set to write the name of environment.

```
\begin{environment-name}
	The cat is on the table
\end{environment-name}
```

### Actual behavior
When I select some text and then I press Ctrl+E to create an environment, alla the selected text is used as name of environment
```
\begin{The cat is on the table}
	content
\end{The cat is on the table}
```

### How to reproduce
Select some text and presse Ctrl+E to create a new environment.

### Notes
I think it is much more likely to have to select text to put it in an environment than to write the environment name, select it and create the environment.

**Comment by sunderme** [comment]
select text, type "table", ctrl+shift+space (complete env) ->
```
\begin{table}
The cat is on the table
\end{table}
```

**Comment by dbitouze** [comment]
@sunderme Nevertheless, I second this feature request. It makes sense for many environments.

**Comment by sunderme** [comment]
done
