### ISSUE TITLE
Improve / Repair Folding and Fold Magic Comment

### ISSUE THREAD

**Issue by clecap** [texstudio-org/texstudio#1345]
There have been numerous requests https://sourceforge.net/p/texstudio/feature-requests/584/ (at least 6) for side-by-side simultaneous split editing. It has been explained that the current architecture is not suitable for this. However, there could be a work-around. Depending on the perspective you want to take you can consider this issue a suggestion for expanding a feature or an issue on a bug for an existing feature. Demand for this feature seems to be high.

Obviously, it would be possible to emulate split editing by a fold approach. It does work nicely, however with one serious restriction: It looks like the magic comment BEGIN_FOLD / END_FOLD has to be entirely part of a Latex folding group.

My minimal example is as follows:

```
\documentclass{article}
%BEGIN_FOLD
% PART-A
\begin{document}
% PART-B
%END_FOLD
% PART-C
\end{document}
```

Expected behavior: When folding at the magic comment, PART-C still is visible.

Actual behavior: When folding at the magic-comment, PART-C also gets folded away.

Similar examples can be produced with section, subsection etc.

Of course, with a bit of coding fantasy, it becomes obvious why this is implemented that way. However, it might be much easier to adapt the behavior of the folding comment than to implement a synchronized multiple split editor UI.

That said: as an additional bonus it would be great if one had a similar folding behavior not only via magic comments or user-macros but also using context menu on the sidebar showing lines.

**Comment by sunderme** [comment]
this seems to be technically impossible
txs uses a tree approach for folding text. You can't have a part which is inside a "parent" stop outside of it.

**Comment by sunderme** [comment]
So, the basic suggestion is that if you want two text parts next to each other, you "simply" fold everything in between ?

**Comment by clecap** [comment]
Not knowing details of the current fold implementation I was thinking of two possible strategies. (1) Being able to switch between two different tree concepts. One would be the current syntax tree. The other would be the suggested folding. There is no need to have both folding modes at the same time, so it could be feasible. (2) Have a folding concept which goes from "folding from X to Y" and not "folding child node X". I do not know if (2) can be implemented.

Yes, the suggestion is to simulate a spilt editor by folding stuff between. Seeing one part while editing the other part of a file without requiring a more complicated setup.

**Comment by sunderme** [comment]
your suggestion is way more complicated than anything else
Furthermore, users would need to move the folding marks around ... that means it is very impractical

not being implemented
