### ISSUE TITLE
xltabular: unrecognized environment

### ISSUE THREAD

**Issue by homocomputeris** [texstudio-org/texstudio#1346]
### Environment
- TeXstudio 3.0.1 (git 3.0.1)
- Using Qt Version 5.15.0, compiled with Qt 5.15.0 R
- OS: macos
- TeX distribution: mactex from homebrew

### Expected behavior
Recognize https://ctan.org/pkg/xltabular

### Actual behavior
`xltabular` is highlighted in orange, the tooltip reads `unrecognized environment`

### How to reproduce
```latex
\usepackage{xltabular}
...
\begin{xltabular}{\linewidth}{@{} X X @{}}
& \\
\end{xltabular}
```

**Comment by sunderme** [comment]
see https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions#what-are-cwl-files-good-for-and-how-do-they-work

You can hand in a cwl for that package is you like.

**Comment by homocomputeris** [comment]
Basically, `xltabular` is a wrapper for `longtable`, and here's a working cwl:

```
# mode: xltabular.sty
#
\begin{xltabular}[alignment]{width}{preamble}#\tabular
\begin{xltabular}{width}{preamble}#\tabular
\caption*{text}
\endfirstfoot#/xltabular
\endlastfoot#/xltabular
\endfirsthead#/xltabular
\endfoot#/xltabular
\endhead#/xltabular
\end{xltabular}
\tabularnewline
```
However, when I write
```latex
\begin{xltabular}{\linewidth}{XX}
text & text \\
\hline
\end{xltabular}
```
TS says that `\hline` is 'tabular command outside tabular env'. How do I fix it?

**Comment by sunderme** [comment]
works here as expected.
Where did you place the cwl ?
Mind you, there is proably an autogenerated cwl in ~/.config/texstudio/completion/autogenerated

**Comment by homocomputeris** [comment]
> Where did you place the cwl ?

`completion/user`

**Comment by sunderme** [comment]
well, it works here
