### ISSUE TITLE
Problem with package babel and option spanish

### ISSUE THREAD

**Issue by savinspm** [texstudio-org/texstudio#1349]
### Environment
- TeXstudio: 3.0.1
- Qt: 5.15.0, compiled with Qt 5.15.0 R
- OS: MacOS Mojave 10.14.6
- TeX distribution: miktex-20.11-darwin-x86_64.dmg

### Expected behavior
Successful compilation.

### Actual behavior
it can not compile a .tex file when the option spanish is used.
Package babel Error: Unknown option `spanish'. Either you misspelled itd. \ProcessOptions*

### Other software 
There are other software where there are not problem but I would like to use TexStudio.

**Comment by muzimuzhi** [comment]
This is a LaTeX problem and TeXstudio is just an editor, hence LaTeX Q&A sites like [tex.stackexchange.com](https://tex.stackexchange.com/) is the right place to post it.

BTW, you may need install the package [`babel-spanish`](https://ctan.org/pkg/babel-spanish).
