### ISSUE TITLE
Installation on openSUSE Leap 15.2

### ISSUE THREAD

**Issue by doctorrerumnaturalium** [texstudio-org/texstudio#1350]
### Description
I want to install TeXstudio 3.0.1 on openSUSE Leap 15.2. With YaST2 after import the package, an error occurs:

`Error loading package list`

If I install TeXstudio via command line with `yast2 -i ./texstudio-3.0.1-lp152.2.1.x86_64.rpm` as root, the following output were shown:

`yast2 -i ./texstudio-3.0.1-lp152.2.1.x86_64.rpmDEPRECATED. Use zypper directly: zypper --non-interactive install ./texstudio-3.0.1-lp152.2.1.x86_64.rpm`
`Loading repository data...`
`Reading installed packages...`
`Resolving package dependencies...`

`The following package is going to be upgraded:`
`  texstudio`

`1 package to upgrade.`
`Overall download size: 18.4 MiB. Already cached: 0 B. After the operation, additional
411.5 KiB will be used.`
`Continue? [y/n/v/...? shows all options] (y): y`
`Retrieving package texstudio-3.0.1-lp152.2.1.x86_64
                                                   (1/1),  18.4 MiB ( 97.1 MiB unpacked)`
`texstudio-3.0.1-lp152.2.1.x86_64.rpm:`
`    Header V3 DSA/SHA1 Signature, key ID ea279317: NOKEY`
`    V3 DSA/SHA1 Signature, key ID ea279317: NOKEY`

`Looking for gpg key ID EA279317 in cache /var/cache/zypp/pubkeys.`
`Repository Plain RPM files cache does not define additional 'gpgkey=' URLs.`
`texstudio-3.0.1-lp152.2.1.x86_64 (Plain RPM files cache): Signature verification failed [4-Signatures public key is not available]`
`Abort, retry, ignore? [a/r/i] (a): a`
`Problem occurred during or after installation or removal of packages:`
`Installation has been aborted as directed.`
`Please see the above error message for a hint.` 

### Environment
- TeXstudio: 3.0.1
- Qt: 5.12.7
- OS: openSUSE Leap 15.2
- TeX distribution: TeX Live 2017/TeX Live for SUSE Linux

Thank you for your support ...

**Comment by sunderme** [comment]
If I read your log correctly, you aborted the installation because the rpm is not signed ? You may get a public key from OBS (open suse build service), but nobody else signed that package.
In my opinion, you should ignore the key issue.

**Comment by doctorrerumnaturalium** [comment]
Okay, I guess I used the wrong parameters with the command `rpm`. If I use the command

`rpm -U ./texstudio-3.0.1-lp152.2.1.x86_64.rpm`

the installation respectively the update works fine. Now I have the version 3.0.1 installed.

![image](https://user-images.githubusercontent.com/59892214/98861727-0c815a00-2466-11eb-85fa-468b02c11a90.png)
