### ISSUE TITLE
TexStudio crashes when saving new files

### ISSUE THREAD

**Issue by cavemanr** [texstudio-org/texstudio#1351]
### Environment
- TeXstudio: TeXstudio 3.0.1 (git n/a)
- Qt: 5.15.1, kompiliert mit Qt 5.15.1 R
- OS: Manjaro Linux
- TeX distribution: texlive

### Expected behavior
When saving an new .tex file TeXstudio shall not crash und save file.

### Actual behavior
TeXstudio crashes and is not saving the new .tex file

![texstudio-sigsegv-crash](https://user-images.githubusercontent.com/19832356/99060145-e4961180-259f-11eb-9eb1-2545f2d50514.png)

/tmp/texstudio_backtrace1.txt:

`SIGSEGV (TXS-Version  R )
[bt] texstudio(_ZN12SimulatedCPU13set_from_realEv+0) [0x559486d15590`

### How to reproduce

1. Start Texstudio
2. Create an new file
3. Click on save
4. TeXstudio crashes

Edit 2020-11-13 14:46:
The problem also occurs when I want to "save as" an existing .tex file.

**Comment by sunderme** [comment]
manjaro again ...

**Comment by cavemanr** [comment]
> manjaro again ...

Thanks for your helpful comment.

**Comment by sunderme** [comment]
okay, the longer answer. 
Arch and hence Manjaro have cost me hours to debug issues which were only present on that system and sometimes disappear on its own.
The only suggestion I can give is, remove texstudio.ini
If it still fails, compile txs yourself.
We don't provide arch packages for a reason.

**Comment by cavemanr** [comment]
> okay, the longer answer. 
> 
> Arch and hence Manjaro have cost me hours to debug issues which were only present on that system and sometimes disappear on its own.
> 
> The only suggestion I can give is, remove texstudio.ini
> 
> If it still fails, compile txs yourself.
> 
> We don't provide arch packages for a reason.

Thanks you for the answer. I will compile TeXstudio by myself and try to reproduce the issue.

**Comment by cavemanr** [comment]
Installing TeXstudio (git) via yay resolved the problem. @sunderme thanks for your hint

**Comment by albsch** [comment]
> The only suggestion I can give is, remove texstudio.ini

Thank you for this hint, this was enough in my case (crashed when opening the file browser).
