### ISSUE TITLE
Folding may break proper scrolling

### ISSUE THREAD

**Issue by clecap** [texstudio-org/texstudio#1353]
### Environment
- TeXstudio: 3.0.1
- Qt: 5.15.0 R
- OS: 10.15.6
- TeX distribution: N/A (TeXLive)

### Expected behavior
1. Fold code portion as in enclosed screenshot
2. Scroll down
3. Be able to see last line completely

### Actual behavior
1. Fold code portion as in enclosed screenshot
2. Scroll down
3. See a partially covered last line even though you have scrolled down completely

### How to reproduce
1. Generate a document with sections
2. Fold all
3. Unfold begin document

<img width="1764" alt="Screenshot 2020-11-14 at 11 58 47" src="https://user-images.githubusercontent.com/7084049/99145769-acf79a00-2671-11eb-94a9-bf5e900735a0.png">

**Comment by sunderme** [comment]
please provide a document which demonstrates the behaviour

**Comment by clecap** [comment]
Hm. Looks like it was some form of transient error. It did happen reliably and reproducibly with the document I was working on (which I since have changed a number of times). Now I can't reproduce it any more. I even tried three variants from time machine backup - everything is fine. It could have been the restart of Texstudio in between.

Anyway. Thanx for the follow up. I'll close this and reopen if it reappears.
