### ISSUE TITLE
Random crashing of 3.0.1

### ISSUE THREAD

**Issue by Linguista** [texstudio-org/texstudio#1356]
In the last four days of heavy TexStudio use, the program has crashed on me three times. The scant details I can provide are below. I know it's not much to go on, but this may be useful to others with similar problems. I'll also note that I never had a single crash with any of the 2.12 versions I used.

### Environment
- TeXstudio: 3.0.1 (git n/a)
- Qt: 5.12.18
- OS: Kubuntu 20.04
- TeX distribution: TexLive 2018

### Expected behavior
No crashes.

### Actual behavior
Crashes. In two instances I received no error message. In one, a segfault was mentioned. In the latter case, editing became extremely slow at first (10-15 seconds before keyboard input was recognized) and then it became impossible, before I eventually got the error message.

In one instance, TexStudio returned to something akin to the default state -- it used a different theme, did not retain my 30+ macros, lost customized shortcuts, etc.

In another, it lost only my custom shortcuts as far as I can tell.

### How to reproduce
Use TexLive for an extended period.

**Comment by sunderme** [comment]
not really helpful
please compile txs with debug info and without Crash_HANDLER (see wiki) and run in gdb.
That may give some backtraces.(there should be backtraces in /tmp/ as well)

**Comment by sunderme** [comment]
insufficient info, no feedback
