### ISSUE TITLE
"Remove trailing whitespace on save" option has no effect

### ISSUE THREAD

**Issue by Linguista** [texstudio-org/texstudio#1357]
### Environment
- TeXstudio: 3.0.1 (git n/a)
- Qt: 5.12.18
- OS: Kubuntu 20.04
- TeX distribution: TexLive 2018

### Expected behavior
Trailing whitespace should be removed on save.

### Actual behavior
Trailing whitespace is not removed on save.

### How to reproduce
- Select "Remove trailing whitespace on save" option.
- Save file.
- Observe that the trailing whitespace is untouched.

**Comment by sunderme** [comment]
the white spaces are only removed in the file, not in the current editor
If you close txs and open the file again, the trailing spaces are gone

**Comment by sunderme** [comment]
no feedback

**Comment by vauhochzett** [comment]
Thank you for the clarification! I was just confused by this behavior as well. Would it be technically possible (and reasonably simple) to also reload the file in the editor to make the changes visible to the user?

**Comment by octaeder** [comment]
@sunderme Sorry for the delay. I would expect seeing the changes when opening the file again. But closing the editor is not sufficient. Is the file cached or what's the reason? This is not intuitive to me. Maybe we need a tooltip for that option.
