### ISSUE TITLE
Fail to show containing folder

### ISSUE THREAD

**Issue by qimingyudaowenti** [texstudio-org/texstudio#1358]
"Show Containing Folder" gives:

![image](https://user-images.githubusercontent.com/17612199/99607608-164b2480-2a47-11eb-9bfd-2e94ebae4dd1.png)
![image](https://user-images.githubusercontent.com/17612199/99607767-6b873600-2a47-11eb-8fd1-d81e9d6aab34.png)

By the way, `! SyncTeX Error : No file?` appears when I start texstudio, why?

### Environment
- TeXstudio: 3.0.1
- Qt: 5.12.8
- OS: Ubuntu 20.04
- TeX distribution: texlive

Thanks for your reply!

**Comment by qimingyudaowenti** [comment]
TeXstudio 3.0.3 still has the problem:
```
(base) gy@gy-PC:~$ texstudio
QIODevice::read (QProcess): device not open
xdg-open: unexpected argument 'files/MathematicalModel"'
Try 'xdg-open --help' for more information.
```
@sunderme

**Comment by sunderme** [comment]
works here
