### ISSUE TITLE
[Feature Request] Built-in version control system

### ISSUE THREAD

**Issue by TRPrasanna** [texstudio-org/texstudio#1360]
It would be great to have a built-in version control system to revert to previous drafts and jump between drafts.

**Comment by flhofer** [comment]
TexStudio already "includes" `svn` as a version control system, see File->SVN. I for my part, changed the preferences to use it with git. However, that only works for commit but I do the rest on `zsh` anyway.

Did you try it? Or do you want to be more specific about the feature wish?

**Comment by flhofer** [comment]
Duplicate of #911

**Comment by TRPrasanna** [comment]
My bad for not looking into this first. I haven't used this before, so I'll comment here once I check it out.

**Comment by sunderme** [comment]
support for svn/git has to suffice
