### ISSUE TITLE
Listings package spills color coding to regular text

### ISSUE THREAD

**Issue by dca00** [texstudio-org/texstudio#1361]
### Environment
- TeXstudio: 3.0.1
- Qt: 5.12
- OS: Windows 7
- TeX distribution: miktex

### Expected behavior

Color coding should be correct

### Actual behavior

Listings package seems to confuse TexStudio 3.0.1. When listings are present, light-magenta seems to randomly spill out of the listings both before and after them.

### How to reproduce

I am not really sure because I was never able to reproduce this in a small MWE. Only my large books with many listings spill somewhere around page 20+. I do not know when it started because this is the first time in many years that I tried the latest version. Some time since 2.16 it broke.

**Comment by sunderme** [comment]
without any concrete hints, what is wrong, there is nothing we can do.
You can send me the book with the issue directly (sunderme@gmx.de).

**Comment by dca00** [comment]
Well, it is totally up to you whether you want to test your code or not. Clearly, none of your users has resources to build MWE out of documents that consist of hundreds of pages and take years to create. I can only suggest that you tinker with the Listings package a bit, but this is it.

**Comment by sunderme** [comment]
well , I offered to take a look at a complete document,
None of the developers has the time (resources) to go on a mysterious bug hunt which may involve a certain package.
