### ISSUE TITLE
Improve readability of output log

### ISSUE THREAD

**Issue by antodc** [texstudio-org/texstudio#1363]
- TeXstudio: 3.0.1
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution: TeXLive 2020

The output log in the Messages panel looks weird. It seems that final parentheses break lines. Moreover, blank lines are added here and there.

The log obtained from the command line looks much better (in my opinion).

Please notice that I made a similar comment in issue #772 a few days ago, but maybe you do not look at older issues very frequently. Really sorry if this "double posting" may cause any trouble.

### Expected behavior

See attached file terminal-output.txt.

### Actual behavior

See attached file TeXstudio-output.txt.

### How to reproduce

Compile the following short text with pdflatex from command prompt and from TeXStudio.

\documentclass{article}
\begin{document}
This is a test.
\end{document}

[terminal-output.txt](https://github.com/texstudio-org/texstudio/files/5592270/terminal-output.txt)
[TeXstudio-output.txt](https://github.com/texstudio-org/texstudio/files/5592272/TeXstudio-output.txt)

**Comment by sunderme** [comment]
a detail, which you failed to mention, is that you are using a non-default mode: build/(build options) show stdout -> always
I have change its behaviour taht it does not add \n log entries are placed, so it does not split so often.
The actual log is shown in the log, so no further changes here.
