### ISSUE TITLE
How can I increase the number of bookmarks shown on the botton bar?

### ISSUE THREAD

**Issue by skanskan** [texstudio-org/texstudio#1368]
Hello.

I'm using TexStudio 3.0.2 on Windows 10.
I like to click on the bookmark buttons on the bottom right side to quickly jump to a predefined section in my document.
https://i.imgur.com/TmjMisw.png

But it seems it can only have up to 3 bookmarks.
If I define more bookmarks on the document they don't appear on this bar and I can't use them.

How can I do it?

**Comment by sunderme** [comment]
it is fixed to 3
But there is a bookmark pane on the left.
And you can press ctrl+1...9 to jump to the bookmarks

**Comment by muzimuzhi** [comment]
Some indirect workarounds:

Firstly, from menu "Edit -> Goto Bookmark", you can see the shortcuts of "Goto Bookmark \<n\>" for \<n\> ranging from 1 to 9, and 0. For example, on macOS, the corresponding default shortcut is `cmd + <n>`. These shortcuts are configurable in "Configure TeXstudio (the configure window) -> Shortcuts".

Second, in "Configure TeXstudio -> Toolbars", you can add those "Goto Bookmark \<n\>" menu items to the toolbar.

PS: To see the mentioned configuration fields, you may need to check the lower-left checkbox "Show Advanced Options" in the configure window.

**Comment by skanskan** [comment]
> Some indirect workarounds:
> 
> Second, in "Configure TeXstudio -> Toolbars", you can add those "Goto Bookmark <n>" menu items to the toolbar.

Thanks.
I did it, but how can I choose to place that links on the bottom right bar?

**Comment by muzimuzhi** [comment]
> I did it, but how can I choose to place that links on the bottom right bar?

You can't. As Sunderme said above, the bottom right is not configurable. Currently all you can do is using one of i) shortcuts, ii) menu items, iii) left pane, and iv) toolbar icons.

**Comment by skanskan** [comment]
OK, thank you.
