### ISSUE TITLE
TexStudio doesn't see MikTex

### ISSUE THREAD

**Issue by ViToni** [texstudio-org/texstudio#1369]
### Environment
- TeXstudio: 3.0.1
- Qt: 5.15
- OS: MacOs 10.15.7
- TeX distribution: miktex

### Expected behavior
TexStudio finds the installed MikTex installation and uses it 

### Actual behavior
When TexStudio start it nags about no TeX distribution being available

### How to reproduce

- Install minimal MikTex distribution from download.
- Update it to full.
- Add `export PATH=~/bin:$PATH`to  `.zshenv`
- `pdflatex` is executable from the teminal
- Install TexStudio from Dock or Spotlight

**Comment by sunderme** [comment]
obviously txs does not see the PATH
You can check path with help/check latex installation
Probably the PATH needs to be set somewhere else.

**Comment by ViToni** [comment]
@sunderme You are right. When starting txs from the terminal it seems to work.
After some further investigation it seems that it's not easy to make the Dock/Spotlight aware of changes to the path.
I followed this approach: https://stackoverflow.com/a/32405815/1268685

Interestingly  "help/check latex installation" showed the correct path when calling getenv BEFORE that change but somehow couldn't make use of it.
