### ISSUE TITLE
Adwaita (txs)-Tooltips sometimes are way to big

### ISSUE THREAD

**Issue by Stimmenhotel** [texstudio-org/texstudio#1370]
### Environment
- TeXstudio:  3.0.2-1f2e869
- Qt: 5.12.3 R
- OS: Windows 10
- TeX distribution: Miktex 20.10

Settings which ~~may~~ impact (~~untested right now~~):
- Adwaita Dark (txs)
Edit: Reverting to "Windows"-Style fixes the problem.

Okay, I have this quite long and don't know why it wasn't reported already.
I tested this on three devices (my laptop, my desktop and a laptop of a friend).

Every time I open a tool tip for any item I receive the way to big one.
Once this big was displayed I mostly receive the small ones if I don't leave "area".
![10-43-20](https://user-images.githubusercontent.com/15821524/100435809-c00d5f80-309e-11eb-9670-5d75248b43d1.gif)

### Expected behavior
Hovering the mouse above a screen item which features a tooltip:
Open the tooltip in a reasonable size
![grafik](https://user-images.githubusercontent.com/15821524/100433641-a4ed2080-309b-11eb-8eb7-bb1ca307d82d.png)

### Actual behavior
Sometimes the tooltip is way to big for its content.
![grafik](https://user-images.githubusercontent.com/15821524/100433660-acacc500-309b-11eb-8df0-e9848692229f.png)

### How to reproduce
1. Open Texstudio
2. Hover the Icon for new project "new"
(For me the first try is most of the time the issue)

**Comment by AnomalRoil** [comment]
This is not the case on my Windows device, even when using the German language.
Tested on TeXstudio 3.0.1 (git 3.0.1)

**Comment by Stimmenhotel** [comment]
Strange, this happens to me on three devices. Two are mine and one by a friend. But as hannes101 in the issue 1412 mentioned, it started with using Adwianta (txs) (dark for me).
Just reverted back to "Windows" Style and the problem instantly disappeared.

**Comment by sunderme** [comment]
it is a problem with the adwaita style, not present on linux ... so debugging it may take a while

**Comment by sergiokapone** [comment]
Yes, confirm. Now the toolpi are small. But the big  Adwiata's style buttons depress me anyway.

**Comment by sunderme** [comment]
this is probably fixed
