### ISSUE TITLE
Control A/E don't move cursor to beginning/end of current line.

### ISSUE THREAD

**Issue by jondeaton** [texstudio-org/texstudio#1371]
### Environment
- TeXstudio: 3.0.1
- OS: macOS Big Sur (though this is true on any macOS version)

### Expected behavior
The keyboard shortcut crtl-a and ctrl-e should move the cursor to the beginning and end of the current line, respectively. This is a very standard keyboard shortcut across terminal emulators, text editors, browsers, web apps, etc.

### Actual behavior
Pressing ctrl-a/e doesn't do anything and there is no way to configure these shortcuts to have this behavior.

### How to reproduce
Press ctrl-a or ctrl-e.

**Comment by sunderme** [comment]
see image
<img width="954" alt="Screenshot_20201128_150009" src="https://user-images.githubusercontent.com/14033169/100517440-d0026d80-318a-11eb-9029-bf7ced6a4314.png">

**Comment by jondeaton** [comment]
Thank you.
