### ISSUE TITLE
Adding a cwl file for a custom math environment \eq with linebreaks

### ISSUE THREAD

**Issue by vsht** [texstudio-org/texstudio#1372]
### Environment
- TeXstudio: 3.0.1
- Qt: 5.14.2
- OS: Fedora 32
- TeX distribution: TeX Live 2020

I have a question regarding the inclusion of custom math environments
via cwl files. I've switched to TeXstudio from Texmaker  only very recently,
so I apologize if the question is too trivial.

What I have is a custom math environment called `eq` defined as follows

```
\newcommand{\eq}[1]{\begin{align}#1\end{align}}
```

I've been using it for many years in numerous LaTeX-files, so that obviously
I'd like to stick with it also when using TeXstudio.

To that end I've created a custom user-defined cwl file with the following content
```
\eq{formula}#S
```

When I input math equations as in
```
\eq{x^2 + y^2 = r}
```
everything works as expected. However, in real life my equations require more than one
line, so that my input usually looks like
```
\eq{
x^2 + y^2 = r, \\
a^2 + b^2 = c^2
}
```
For such input my cwl-file apparently doesn't work: TeXstudio complains about "math command outside math envirioment".
So could anyone kindly point out, how 
```
\eq{formula}#S
```
should be modified to account for linebreaks in the input?

Notice that one could of course employ
```
\begin{eq}#\math 
\end{eq}#S
```
but this is not a good solution for me. I don't want to change my existing tex files and I prefer to use `\eq{}` instead of `\begin{eq}` and `\end{eq}`

**Comment by sunderme** [comment]
txs does not really support math as command argument.
The "formula" argument silences math warnings and is a work-around for chemical formulas. It seems not to work over multi-line arguments.
The alternative is 
```\eq{definition}```
which avoids syntax checking in the argument altogether

**Comment by vsht** [comment]
Many thanks! This nicely solves my problem and fixes the spurious "math command outside math envirioment" warnings.
