### ISSUE TITLE
User additions to Special commands of Table autoformatting are ignored

### ISSUE THREAD

**Issue by homocomputeris** [texstudio-org/texstudio#1373]
### Environment
- TeXstudio 3.0.1 (git n/a)
- Using Qt Version 5.15.2, compiled with Qt 5.15.1 R
- OS: Arch Linux version 5.9.12-1-clear
- TeX distribution: TeX Live 2020.55416-1

### Expected behavior
Format table according to the config
```latex
\begin{tabular}{cc}
    \hline
    A &
    B
    \tabularnewline
    \hline
    C &
    D
    \\
    \hline
\end{tabular}
```

### Actual behavior
Config is partially ignored
```latex
\begin{tabular}{cc}
	\hline
	A &
	B \tabularnewline \hline C &
	D \\
	\hline
\end{tabular}
```

### How to reproduce

1. Append `,\tabularnewline,\\` to Adv. Editor > Table autoformatting > Special commands
2. Choose Separate line (indented to first column)
3. Format the table:
```latex
\begin{tabular}{cc}
    \hline A & B \tabularnewline \hline C & D \\ \hline
\end{tabular}
```

**Comment by sunderme** [comment]
I don't think that what you expect is covered by the program logic
1) special commands are thinks like \hline etc, so they are put directly after row break
2)\tabularnewline is unknown and not recognized as line break. Putting it into "special commands" does not change that.
Hence ```B \tabularnewline \hline C``` are interpreted as one cell ... nothing wrong there.

we may discuss that ```\tabularnewline``` is interpreted like ```\\```, but that is adifferent story and has nothing to do with "special commands"

**Comment by homocomputeris** [comment]
Isn't the program logic just put whatever is listed in 'Special commands' where 'Specials commands' position specifies?
Will `\hfill` be put on a new line? Will `FooBar`?

`\\` is a legit command, why is it not put on a separate line?

**Comment by sunderme** [comment]
```\tabularnewline``` is now handled like ```\\```

**Comment by homocomputeris** [comment]
`\tabularnewline` was handled like this in `longtable` but not `xltabular`, so it was a CWL issue in some sense.

**Comment by homocomputeris** [comment]
Another issue seems to be that
```latex
\begin{longtable}{ll}
	\hline	a &	a \hline\hline    a &	a \\	\hline\hline
\end{longtable}
```
becomes
```latex
\begin{longtable}{ll}
	\hline
	a &
	a \hline\hline    a &
	a \\
	\hline\hline
\end{longtable}
```
but the config name suggests that is should become
```
...
\hline
\hline
```
