### ISSUE TITLE
Viewer (Embedded Mode) toolbars grow after Configure TeXstudio is closed

### ISSUE THREAD

**Issue by homocomputeris** [texstudio-org/texstudio#1376]
### Environment
- TeXstudio 3.0.1 (git n/a)
- Using Qt Version 5.15.2, compiled with Qt 5.15.1 R
- OS: Arch Linux
- TeX distribution: TeX Live

Envvar is set to `QT_AUTO_SCREEN_SCALE_FACTOR=1`, Gnome 3 is set to autoscale for 4K screens, 200% effectively.

### Expected behavior
Preserve toolbar size

### Actual behavior
Embedded viewer toolbar becomes twice larger
![txs](https://user-images.githubusercontent.com/7422433/101147008-b2faee00-3613-11eb-9136-032941e6d640.png)

### How to reproduce

1. Open a document in an embedded viewer, leave it open
2. Open Options > Configure TeXstudio
3. Press OK to close the config window (_neither_ Cancel _nor_ ×)

**Comment by SFH1984** [comment]
Same here. Maybe my additional information is useful to solve the issue: 

TeXstudio 3.0.1 (git 3.0.1)
Nutze Qt-Version 5.12.1, kompiliert mit Qt 5.12.1 R
Win 10
MikTeX
