### ISSUE TITLE
[Feature Request] Add Math Render preview while edit document.

### ISSUE THREAD

**Issue by Atreyu-94** [texstudio-org/texstudio#1377]
Hey, I have used LyX and TeXstudio interchangeably. My problem with LyX is that I don't have full control of the document. That is why I love TeXstudio.
Would it be possible to add a function so that the formulas, in math mode, can be rendered on the fly? 
This would be very efficient, as sometimes the formulas are big enough to get lost in understanding them. Cheers!

**Comment by muzimuzhi** [comment]
Select the math equation, click "Preview Selection/Parentheses" in the right-click menu. See some config options in the "Preview" tab of configuration window.

**Comment by sunderme** [comment]
as described above, txs already has a preview (tooltip, inline, extra pane)

**Comment by Atreyu-94** [comment]
Thank you for your answers. But that's not exactly what I meant. I was referring to that for mathematical environments, rendering when writing, putting the code and editing the equation and seeing the result. How in LyX. For equations it is very convenient. Greetings. If you know how it could be done at least 🤔.

**Comment by sunderme** [comment]
"Preview Selection/Parentheses" as inline is continous. If you change the selected text, the preview is updated.

**Comment by Atreyu-94** [comment]
Thanks a lot! The truth was not exactly what I wanted. But it's a cool feature and I didn't know about it. Now I'm going to use it for my work. Later I will explain myself better and maybe I can contribute if you are interested. Greetings.
