### ISSUE TITLE
Commands declared with \DeclareTextFontCommand{} are not detected by the syntax highlighter

### ISSUE THREAD

**Issue by Linguista** [texstudio-org/texstudio#1378]
### Environment
- TeXstudio: 3.0.1
- Qt: 5.12.8
- OS: Kubuntu 20.04
- TeX distribution: TexLive 2020

### Expected behavior
When you declare a new command with \DeclareTextFontCommand{} it should be recognized by the syntax highlighter and NOT be marked as an invalid command.

### Actual behavior
Commands declared with \DeclareTextFontCommand{} are highlighted as invalid commands by TexStudio.

### How to reproduce
In preamble:
```
\newfontfamily\myfont{Charis SIL}[StylisticSet=5, Scale=MatchLowercase]
\DeclareTextFontCommand{\mine}{\myfont}

```

In document:
```
\mine{My special font is applied here}
```

Every instance of **\mine** in the document is shown as red on orange-pink, indicating TexStudio believes it does not exist as a command.

**Comment by sunderme** [comment]
you need to activate options/completion/latex-dev.cwl

**Comment by Linguista** [comment]
@sunderme That option is already activated in my TexStudio setup.

**Comment by sunderme** [comment]
fixed with latest dev build
