### ISSUE TITLE
Future plan to support arm processors?

### ISSUE THREAD

**Issue by cilia** [texstudio-org/texstudio#1381]
### Environment
- TeXstudio: 3.0.1
- Qt: 5.15.0
- OS: macOS 10.14.6
- TeX distribution: MacTeX

Is there any future plan to natively support M1 arm processors from Apple? If so, what would be the rough timeline? Thanks.

**Comment by sunderme** [comment]
txs supports arm processors on linux.
The issue with arm/OSX is
1) the build providers (CI travis,github) need to offer a mac with arm
2) QT needs to be provided for that (though that is probably not an issue with homebrew being ported for arm)

**Comment by sunderme** [comment]
if you need txs now, either use homebrew variant or compile on your own (see wiki)
