### ISSUE TITLE
Glossaries labels suggestions are not shown if the \glsxtrnewsymbol command is used

### ISSUE THREAD

**Issue by chiavez** [texstudio-org/texstudio#1382]
If the command \glsxtrnewsymbol is used TeXstudio does not understand a glossary entry has been defined. Every label referenced with \gls() is said to be missing. The suggestions do not work. 

This does not happen if the standard command  \newglossaryentry{} is used.

### Environment
- TeXstudio: 3 .0.1 (git 3.0.1) 
- Qt:  Version 5.12.1, compiled with Qt 5.12.1 R  
- OS:  Windows 10 
- TeX distribution:  miktex  

### Expected behaviour
TeXstudio recognizes that a glossary entry is being defined when \glsxtrnewsymbol is used. label suggestions are given

### Actual behaviour
TeXstudio does not recognize that a glossary entry is being defined when \glsxtrnewsymbol is used. label suggestions are not given

### How to reproduce
Define a glossary entry using \glsxtrnewsymbol  eg:

\glsxtrnewsymbol
[description={Stiffness matrix of an element}]
{m:k:e}
{\ensuremath{[K^e]}}

try reference it using
\gls{m:k:e}

the referenced entry will be underlined and said to be missing.

**Comment by sunderme** [comment]
glossary cwl is incomplete
you may want to overhaul the bit that you need (https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions#what-are-cwl-files-good-for-and-how-do-they-work)
