### ISSUE TITLE
About texstudio should show whether 32bit or 64bit

### ISSUE THREAD

**Issue by bernhard-kleine** [texstudio-org/texstudio#1384]
### Environment
TeXstudio 3.0.2 (git 3.0.2beta1)
Using Qt Version 5.12.3, compiled with Qt 5.12.3 R

- OS: win10-64
- TeX distribution: texlive

Since 64bit is now supported should make it clear whether the verion being used is 32 or 64 Bit.
The actual display does not mention anything about 32 or 64 Bit:

TeXstudio 3.0.2 (git 3.0.2beta1)
Using Qt Version 5.12.3, compiled with Qt 5.12.3 R

**Comment by sunderme** [comment]
all builds will be 64 bit.
the compilers don't support a cross platform variable to detect this, so I will not bother.
