### ISSUE TITLE
Column width in Options->Configure TeXstudio doesn't fit text and is not remembered

### ISSUE THREAD

**Issue by SFH1984** [texstudio-org/texstudio#1385]
### Environment
- TeXstudio: 3.0.1 (git 3.0.1)
- Qt: 5.12.1, compiled with Qt 5.12.1 R
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
Preserve column width in Options -> Configure TeXstudio -> Menus, Shortcuts, Syntax highlighting

### Actual behavior
Column width in the config window is set to a (too narrow) standard value each time "Configure TeXstudio" is opened

![screenshot_texstudio_1](https://user-images.githubusercontent.com/75536587/101496734-680e0d00-396a-11eb-8014-0419ac08f500.PNG)

### How to reproduce
1) Open Options -> Configure TeXstudio -> Menus or Shortcuts or Syntax Highlighting -> change column width
2) Press OK to close the config window
3) Open Options -> Configure TeXstudio again

**Comment by sunderme** [comment]
first column width will be remembered
