### ISSUE TITLE
[suggestion] [3.0.1] Add keyboard shortcuts to context menu

### ISSUE THREAD

**Issue by chsk-uk** [texstudio-org/texstudio#1387]
Good morning, 

I'd like to make a small suggestion for TeXstudio: it would be nice to have keyboard shortcuts in the default context menu for documents so that when you open the context menu using Shift-F10, you can quickly choose the desired action without having to either reach for the mouse or use the cursor keys to scroll through the menu.

As usual, thank you very much for this excellent tool!

**Comment by sunderme** [comment]
it is default behaviour.
As it is in menus, the underscore in the menu entries is the key you need to press to select that entry.
<img width="289" alt="grafik" src="https://user-images.githubusercontent.com/14033169/101823106-963a4b00-3b2a-11eb-89d2-2ccf4cb19f2c.png">
(t in case of Paste as latex)

**Comment by chsk-uk** [comment]
Hi, thanks a lot for your reply! Yes, this is exactly what I had in mind --- and what I'm not actually seeing:

![image](https://user-images.githubusercontent.com/45624888/101824624-c4b92580-3b2c-11eb-9470-b86f31efd343.png)

Do these shortcuts need to be enabled somewhere, or is there a configuration option that I might accidentally have disabled? Thanks a lot and all the best!

**Comment by sunderme** [comment]
which OS ?
maybe pressing "alt" key ? Should be part of the OS...

**Comment by chsk-uk** [comment]
Windows 10, and pressing Alt just closes the context menu again (just tried). I do agree it's somewhat weird behavior (but that's Windows for you).
