### ISSUE TITLE
TexStudio is rercognising $ math delimiter is R-code of Sweave block

### ISSUE THREAD

**Issue by petermott** [texstudio-org/texstudio#1388]
### Environment
- TeXstudio:  VERSION 	TeXstudio 3.0.1 (git 3.0.1) Using Qt Version 5.12.1, compiled with Qt 5.12.1 R 
- Qt:  Qt 5.12.1 
- OS: Windows10 
- TeX distribution: miktex

### Expected behavior
The $ symbol within an R-code block is the normal chunk code colour.

### Actual behavior
The $ is recognised as a math delimiter and the text chnages colour until a blank line or another $ is encounters.

### How to reproduce
The attached text file (with the extension changed to .Rnw) will reproduce the behaviour:
[document.txt](https://github.com/texstudio-org/texstudio/files/5667060/document.txt)

The following image shows the effect.
![document](https://user-images.githubusercontent.com/7861523/101653443-3f077e00-3a37-11eb-8e8d-ff7e2b5c9069.png)

**Comment by muzimuzhi** [comment]
Looks like the contents of `sweave-block` should be highlighted either as verbatim or R language. The latter need an extra `R.qnfa`.
https://github.com/texstudio-org/texstudio/blob/5986bd983b596917ce6cb1ac3eab95f2cd9e8b29/utilities/qxs/sweave.qnfa#L14-L17

**Comment by petermott** [comment]
In fact the issue is one of documentation. The configure >> syntax highlighting dialog allows an option at the far right to set the priority of any give highlighting. Initially these are all -1. By increasing the priority of Sweave highlighting to some number > -1 the highlighting of $ xx $ is overidden and expected behaivour occurs,
