### ISSUE TITLE
'Cursor follows scrolling' does not work

### ISSUE THREAD

**Issue by limasierra** [texstudio-org/texstudio#139]
Hi!

The 'Cursor follows scrolling' feature has no effect. Tested

- with continuous and single page scrolling mode, 
- with and without enabling the 'scrolling follows cursor' mode (which works fine by the way!), and
- with the embedded viewer in splitted as well as windowed mode.

On a side note, embedded viewer → right click → 'Go to source' works as expected. Thus, (missing) SyncTex is probably not the root cause of the issue.

### Environment
TeXstudio 2.12.8 (hg n/a)
Using Qt Version 5.10.1, compiled with Qt 5.10.1 R
OS: Arch Linux, up to date version :)
Compiled with: LuaTeX, Version 1.0.4 (TeX Live 2017/Arch Linux)

### Expected behavior
The cursor should move in the source code as I scroll through the PDF in the embedded viewer.

### Actual behavior
Cursor does not move :)

### How to reproduce
Enable 'cursor follows scrolling' in the embedded viewer and start scrolling in the viewer.

### Related bugs
Found the following bug reports when googling the issue. They describe the same problem.

- 2012: **#506 Strange scroll behavior in main window** 
https://sourceforge.net/p/texstudio/bugs/506/

- 2017: **#2059 Bug for scrolling follows cursor**
https://sourceforge.net/p/texstudio/bugs/2059/

Kind regards,
Laurent

**Comment by sunderme** [comment]
I can reproduce the behaviour

**Comment by andrewufrank** [comment]
I see the same. it is working on a different computer (but i cannot see what version of TXS is running). The function is definitely not working on 2.11.2
