### ISSUE TITLE
Right click package name to view documentation not working.

### ISSUE THREAD

**Issue by BeerStud** [texstudio-org/texstudio#1392]
### Environment
- TeXstudio: 3.0.1
- Qt: 5.12.2
- OS: Windows 10 Pro Insider Preview  --  Version: 2004 -- OS Build: 21277.1000
- TeX distribution: miktex

### Expected behavior
When I right-click on a package name I expect to see the package documentation

### Actual behavior
When I right-click on a package name, I am greeted with an error message. "Texdoc did not respond to query on package: PACKAGE NAME

### How to reproduce
Just try it.

This used to work. I have no idea why it suddenly stopped working.
[System Report.txt](https://github.com/texstudio-org/texstudio/files/5683847/System.Report.txt)

**Comment by muzimuzhi** [comment]
In your `System Report.txt`, part `Command configuration in TeXstudio:`, there is no `texdoc` item, which looks like
```
Command configuration in TeXstudio:
    [...]
    texdoc (texdoc): texdoc 
    [...]
```
here in texstudio 3.0.2beta2 on macOS, with mactex/texlive 2020 installed.

Could you check what's there in "Configuration TeXstudio -> Commands -> texdoc"?
![image](https://user-images.githubusercontent.com/6376638/102004112-bd6e6380-3d48-11eb-8508-1baf26d977c6.png)

Also, what do you get in the lower "Message" panel, after right-clicking on a package name? For example, I get
```
Process started: texdoc  --view tikz

Process exited normally
```

**Comment by BeerStud** [comment]
I don't have anything pertaining to "texdoc" in my commands listing. This is a screenshot of the entire list.

![image](https://user-images.githubusercontent.com/17906160/102010802-5764ea80-3d0e-11eb-9b98-7ffd79c3631c.png)

**Comment by foreachthing** [comment]
Exactly the same thing here!
Win10 Pro (20H2, 19042.685), TXS 3.0.1.

**Comment by sunderme** [comment]
please update to 3.0.2beta2
