### ISSUE TITLE
Placeholder frame drawn incorrectly when wrapped

### ISSUE THREAD

**Issue by homocomputeris** [texstudio-org/texstudio#1395]
### Environment
- TeXstudio 3.0.1 (git n/a)
- Using Qt Version 5.15.2, compiled with Qt 5.15.1 R
- Arch Linux

### Expected behavior
Rectangles

### Actual behavior
Weird polygons
![txs1](https://user-images.githubusercontent.com/7422433/102087116-fa9e2880-3e10-11eb-98da-832e30bf1aa6.png)
![txs2](https://user-images.githubusercontent.com/7422433/102087120-fb36bf00-3e10-11eb-805c-4e950e87f057.png)

### How to reproduce

1. Enable soft wrap and Center Document in Editor
2. Type some text
3. Start and autocomplete a command like `\textbf{}`
4. Start typing to replace the selected placeholder text
5. Type until the text is wrapped

**Comment by muzimuzhi** [comment]
With "Configure TeXstudio -> Adv. Editor -> Special options -> Center Document in Editor" checked, your problem is reproducible here. I have texstudio 3.0.2beta2 installed on macOS 10.15.7.
