### ISSUE TITLE
Improve readability of output log

### ISSUE THREAD

**Issue by antodc** [texstudio-org/texstudio#1396]
Sorry to return to the issue described in #1363 that you considered as closed, but the output log shown in the Messages window by TeXstudio (3.0.2 beta 2) is still different from the one obtained from the command line.

Blank lines now are gone, but parentheses like ‘)’, ‘]’, ‘{‘ and ‘}’ still break the lines.

**Comment by sunderme** [comment]
I was not kidding about "The actual log is shown in the log, so no further changes here."
The log is here:
<img width="631" alt="grafik" src="https://user-images.githubusercontent.com/14033169/102118380-e7ef1800-3e3f-11eb-9378-d9ebcf200276.png">
