### ISSUE TITLE
TexStudio crashes due to a SIGSEGV whenever I try to open a document or try to "save as"

### ISSUE THREAD

**Issue by saulonio** [texstudio-org/texstudio#1397]
### Environment
- TeXstudio: Version 3.0.1
- Qt: 5.12.2
- OS: Manjaro Linux (fully updated from the stable repositories)
- TeX distribution: texlive

### Expected behavior
Ctrl+O or File>Open should launch a dialog to open a file. Likewise for "Save As". Other functions, such as "Save", work normally as long as the document already exists. (Saving a new document also makes TexStudio crash).

### Actual behavior
TexStudio crashes 'due to a SIGSEGV'. The backtrace contains only two lines: 

````
SIGSEGV (TXS-Version  R )

[bt] texstudio(_ZN12SimulatedCPU13set_from_realEv+0) [0x55c9d1a93590]
````

Launching it on the terminal gives me the following:
```` 
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1872, resource id: 0, major code: 18 (ChangeProperty), minor code: 0
crashed with signal SIGSEGV
SIGSEGV (TXS-Version  R )
SIGSEGV (TXS-Version  R )
SIGSEGV (TXS-Version  R )
SIGSEGV (TXS-Version  R )

[bt] texstudio(_ZN12SimulatedCPU13set_from_realEv+0) [0x563e17ee9590]
[bt] texstudio(_ZN12SimulatedCPU13set_from_realEv+0) [0x563e17ee9590]

"/tmp/texstudio_backtrace1.txt"
````

### How to reproduce
By selecting File>Open or File>Save As or doing Ctrl+O

**Comment by sunderme** [comment]
as the binary is not provided by us, I suggest you try to compile txs on your computer, see wiki

**Comment by saulonio** [comment]
I managed to fix this issue, albeit not ideally. Seems like the problem has to do to with launching gnome's native file dialog and it can be fixed by changing the following line in texstudio.ini:   
`Files\Use%20Native%20File%20Dialog=true`    
to `false`.

I don't know exactly what is going wrong. It seems that other Qt5 applications do not present this error and display the Gnome file dialog normally.

**Comment by sunderme** [comment]
txs uses qfiledialog. I would still recommend compiling on your own.

**Comment by sunderme** [comment]
as this is a system issue, we can't do anything.
