### ISSUE TITLE
Escape-Key closes searchbar and stops compiling

### ISSUE THREAD

**Issue by bastianleirpo** [texstudio-org/texstudio#1398]
### Environment
- TeXstudio: 3.0.1

### Expected behavior
Just search bar is closed

### Actual behavior
Search bar is closed and compiling is stopped

### How to reproduce
Compile a large document and work further on the document ("run compiling in background"). While working on the document search for word occurrences (CTRL + F). Close search bar after found search string with ESC-Button.

**Comment by muzimuzhi** [comment]
Reproducible in 3.0.2bete2 on macOS 10.15.7.

**Comment by sunderme** [comment]
can you post a screen cast of the issue ?

**Comment by bastianleirpo** [comment]
After the first search I needed to press 3 times ESC, until the search bar closed. Unfortunately with the first two times compiling crashed (as usual beahaviour described by this report)
The second time without compiling, it closes immediately.
https://drive.google.com/file/d/1L9hnU1ktPPP6z6XECLhrL7JIGYpfr1ui/view?usp=sharing

**Comment by sunderme** [comment]
fixed, now a search panel is closed and onyl with a closed panel the compilation is killed

**Comment by bastianleirpo** [comment]
You are awesome! Thanks
