### ISSUE TITLE
Handling of external changes

### ISSUE THREAD

**Issue by projekter** [texstudio-org/texstudio#1400]
Assume TeXStudio is configured to watch for changes in external files, but not to silently load external files.
Now I open a file and do some change, whatever it is. Perhaps I even save the file.
- If I now externally modify the file, TeXStudio prompts whether I want to reload, which is fine.
- However, if I never changed anything in the file from the beginning, it will just silently reload (and, see #665, not allow to undo this).
- If I agree to reload, don't change anything and yet another external change happens, this is again silently loaded.

My expectation - that will now cost me some hours in re-writing lost content - is that _any_ external change should always trigger the prompt, as it will change the current content of the editor.

Additionally, assume I did some changes and saved the file, so now the "Save" button is disabled. External changes are performed and I disagree to reload. The "Save" button is still disabled, even though now the editor content differs from the file content. I would suggest to enable this button and that clicking/shortcut triggers a dialog similar to the "Conflict" dialog, just with the buttons "Save" and "Cancel".

### Environment
- TeXstudio: 3.0.1
- Qt: 5.12.1 R
- OS: Windows 10
- TeX distribution: miktex

**Comment by sunderme** [comment]
short answer: no
long answer: you seem to treat texstudio as ram backup of the document which is not a healthy workflow and will not be supported.

**Comment by projekter** [comment]
This is ridiculous. Of course, it is your decision how TeXStudio behaves, but the current behavior is inconsistent. This has nothing to do with my bad luck experience this time. The current setting (don't know exactly the English caption) is called "Silent reload of files if they are changed externally". If this setting is disabled, then the editor should _not_ silently reload files, of whether the loaded files were touched at some point or not. If it does, then either this is intended behavior and the setting is labelled wrongly or it is a bug.
