### ISSUE TITLE
Trackpad is unusable in windowed pdf viewer (overly sensitive)

### ISSUE THREAD

**Issue by Noma1556** [texstudio-org/texstudio#1401]
### Environment
- TeXstudio: 2.12.6
- Qt: Using Qt Version 5.9.5, compiled with Qt 5.9.3 R
- OS: Linux Ubuntu 18.04.5 LTS
- TeX distribution: not relevant

### Expected behaviour

Scrolling should be smooth and predictable for both mouse scroll, two-finger trackpad scroll and should be the same for windowed and embedded internal pdf viewer.

### Actual behaviour

Scrolling is unusable when using simultaneously the two-finger scroll from the trackpad and the windowed internal pdf viewer of TexStudio.
It only occurs for this combination: everything works as expected when using the mouse scroll or the embedded viewer.

A gentle scroll down of about ~2lines results in a jump to the previous page, while a scroll up of the same amount results in a jump to the next page.

As a result, just touching the trackpad results in an unpredictable jump somewhere in the document.
See the attached video where I scroll across the same 5-page document:
* in embedded view, smooth as butter;
* in windowed view, it's chaotic and skips pages in the direction opposite to the scroll every ~2 lines of scroll

I don't see this behaviour in any other app on this machine.

### How to reproduce

Just compile a multipage tex document, F7 with the windowed internal pdf viewer and try to scroll with the trackpad.

https://user-images.githubusercontent.com/76486017/102905196-0c1bac00-4473-11eb-80a3-f71a4d4ca8d8.mp4

**Comment by Noma1556** [comment]
Hmm, first time ever I try to upload a video on github.
The embedded video viewer does not show the video in my browser, but the video can be downloaded [https://user-images.githubusercontent.com/76486017/102905196-0c1bac00-4473-11eb-80a3-f71a4d4ca8d8.mp4](link to video) and works fine if opened locally with vlc.

**Comment by sunderme** [comment]
you need to set the windowed pdf viewer to "continuous mode"
<img width="640" alt="grafik" src="https://user-images.githubusercontent.com/14033169/102985061-d75d3280-450e-11eb-96a4-a46d5a3344f8.png">

**Comment by Noma1556** [comment]
> you need to set the windowed pdf viewer to "continuous mode"

Indeed, that works!
But I'm a bit confused:
* why is this settings only affecting the pdf viewer when it is windowed and not embedded?
* the default behaviour (continuous mode left unticked) is unusable with a trackpad, why isn't the continuous mode default?
* why is there such dramatic difference between trackpad scrolling (unusable) and mouse scrolling (perfectly fine) when not using the continuous mode?
* along the same line, why is there such difference in behaviour between the embedded and windowed pdf viewer modes?

Cheers and thanks for the pointer.

**Comment by sunderme** [comment]
1) embedded / windowed mode are somewhat independent
2) nobody has had an issue so far
