### ISSUE TITLE
Strange behavior of <Ctrl>+<Right> and <Ctrl>+<Left> in editor

### ISSUE THREAD

**Issue by sancho-s** [texstudio-org/texstudio#1402]
### Environment
- TeXstudio: 3.0.1
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution:  ??

Assume I have a tex file with schematic contents like this

...
text text text
\begin{equation}
	\label{eqn:1}
	\left( x \right) = 2 \left[ u^{-1} \log{u} \right]^{2/3}      % <--- point 1
        \quad ,
\end{equation}
%
text \cite{art1} text text \ref{eqn:1} text text $\sin(x)$ text
...

### Actual behavior
If the cursor is at point 1 or before, hitting \<Ctrl\>+\<Right\> moves word-by-word.
If the cursor is anywhere between the following character (i.e., the first blank in the line of \quad)
and before the opening curly brace in \ref{eqn:1}, hitting \<Ctrl\>+\<Right\> moves before the closing curly brace, and "eqn:1" is selected, jumping over whatever text is in between.
Something similar happens when navigating a document with \<Ctrl\>+\<Left\> from after \ref{eqn:1}.

Note: I couldn't get the systematic of what commands or else act as hurdles for these long jumps, but it is irrelevant.

### Expected behavior
\<Ctrl\>+\<Right\> and \<Ctrl\>+\<Left\> should always navigate word-by-word.

**Comment by sunderme** [comment]
works fine here.
Screencast to make sure I understand the description ?

**Comment by homocomputeris** [comment]
> <Ctrl>+<Right> and <Ctrl>+<Left>

These are the default TXS shortcuts for "Next/Previous placeholder or one word right/left".
You can change this behaviour in Configure... > Shortcuts > Editor

**Comment by sunderme** [comment]
no feedback

**Comment by Photon89** [comment]
@homocomputeris @sunderme 

Hi, I am struggling with the same problem. If I set the "Next/Previous placeholder or one word right/left" to "none" to prevent jumping to the next or previous placeholder, I end up not being able to jump to the next or previous word. I couldn't find a shortcut for "Next/Previous one word right/left" unfortunately.

**Comment by sunderme** [comment]
see image. remove shortcut at yellow marker, set shortcut at selected line
<img width="1032" alt="grafik" src="https://github.com/texstudio-org/texstudio/assets/14033169/e6d4bc2e-e8d7-466f-ae4d-e45fc0369a4d">

**Comment by Photon89** [comment]
Great, thanks! I didn't think of searching somewhere else, outsied of the "Next ..." and "Previous ..." groups.
