### ISSUE TITLE
Zoom & Font resizing Not Working For RTL languages in Editor Screen(Hebrew,Arabic,etc)

### ISSUE THREAD

**Issue by ToCodeOrNotTo** [texstudio-org/texstudio#1404]
Edit: Video Added. Zooming doesn't affect RTL languages.

https://user-images.githubusercontent.com/76603694/103161167-acdbd580-47ab-11eb-9670-e0a301cdfb68.mp4

Edit: Video Added for Similar Problem. Changing font size doesn't change font size of RTL languages UNLESS you restart TexLive.
PS: Apparently my video recording didnt capture the GUI of the font change but you can notice the font changed by looking at English text.

https://user-images.githubusercontent.com/76603694/103255438-48f61000-4957-11eb-9231-36da9c5aa777.mp4

### Environment
- TeXstudio:  3.0.0/.1 
- Qt:  
- OS:  Windows 10/Linux Ubuntu 20.04
- TeX distribution:  Texlive

### Expected behavior
When using the mouse wheel to zoom on the text the RTL text should zoom.

### Actual behavior
The RTL text doesn't zoom although surrounding text does zoom.

### How to reproduce
Just zoom in Arabic or Hebrew(Tested Languages)

Test Files:

[testdocument.zip](https://github.com/texstudio-org/texstudio/files/5748510/testdocument.zip)

**Comment by sunderme** [comment]
can you provide a sample document ?

**Comment by ToCodeOrNotTo** [comment]
@sunderme Did that. But you can do that with any document.

**Comment by ToCodeOrNotTo** [comment]
@sunderme Added a similar problem with the font sizing.

**Comment by ToCodeOrNotTo** [comment]
@sunderme Its solved in the next update ?

**Comment by sunderme** [comment]
yes, or you can use a dev build from bintray.com/sunderme

**Comment by ToCodeOrNotTo** [comment]
@sunderme Thnx, props to your hard and fast work. Zooming works fine now.
