### ISSUE TITLE
Letter "e" appears randomly

### ISSUE THREAD

**Issue by erelsgl** [texstudio-org/texstudio#1406]
### Environment
- TeXstudio: 3.0.1
- Qt: 5.12.8
- OS: Ubuntu 20.04
- TeX distribution: texlive

### How to reproduce
Open a file, type "abc", select it and click Ctrl+Shift+E.

### Expected behavior
The outcome should be "\emph{abc}".

### Actual behavior
The "abc" disappears, and instead, a yellow "e" appears.
It cannot be undone (Ctrl+Z does not help),
and it duplicates itself to following lines. See screencast

![Peek 2020-12-27 11-58](https://user-images.githubusercontent.com/1462215/103168395-967d5a80-483b-11eb-9938-2cfbc6311d22.gif)

**Comment by sunderme** [comment]
1) try to use the menu for selecting the command (latex/font style/emphasis)

**Comment by erelsgl** [comment]
From the menu it works. But from the keyboard shortcut it does not work.

**Comment by sunderme** [comment]
have you changed the shortcut ? does ubuntu mess with the shortcut or have defined macros ?

**Comment by benibela** [comment]
That Isn't the yellow color the "preedit" format?

**Comment by erelsgl** [comment]
Here is my shortcuts menu:

![Screenshot from 2020-12-28 08-17-31](https://user-images.githubusercontent.com/1462215/103193474-3642f300-48e5-11eb-8faa-50159fe63148.png)

**Comment by erelsgl** [comment]
I have defined two macros, but they use diffferent shortcuts: Alt+A, Alt+Q (and they work fine).

**Comment by sunderme** [comment]
then it is probably a global short cut from your desktop environment
quick test may be changing the txs shortcut to something else ...

**Comment by erelsgl** [comment]
I did not find this shortcut in my desktop environment (Unity on Ubuntu 20.04)

![image](https://user-images.githubusercontent.com/1462215/103435957-475e6d80-4c1f-11eb-8098-753a3f73b6ca.png)

**Comment by sunderme** [comment]
it is a ubuntu/unity (X11) bug. It happens as well with qtcreator.
It does not occur on ubuntu on wayland.
So, nothing we can do.
