### ISSUE TITLE
TeXstudio crashes whenever attempting to use "open file" dialog

### ISSUE THREAD

**Issue by mefuller** [texstudio-org/texstudio#1408]
### Environment
- TeXstudio: TeXstudio 3.0.1 (git n/a)
- Qt: Qt-Version 5.15.2, compiled with Qt 5.14.2 R
- OS: Linux: Fedora Rawhide, GNOME desktop under Wayland (on or before 24 DEC 2020 to present (29 DEC 2020))
- TeX distribution: TeXlive (package texlive-2020-36-fc34.src.rpm; epoch 9, version 2020, release 36.fc34)

### Expected behavior
TeXstudio is opened from a graphical launcher on desktop. From there, the "open" button (top left) of "ctrl+o" is utilized to activate a file browser to select a file for editing.

### Actual behavior
On pressing the "open" button or using "ctrl+o" TeXstudio immediately crashes

### How to reproduce
Open TeXstudio. Press "open" button or "ctrl+o". Observe crash.

### Additional notes
It is possible to open a file in TeXstudio using the system file browser to locate the desired file and using the "open with TeXstudio" option there. This causes TeXstudio to launch normally with the desired file open.

**Comment by mefuller** [comment]
A little hunting found a [solution](https://github.com/NixOS/nixpkgs/issues/79034#issuecomment-748264633):

Force TexStudio to not use the Gnome file dialog.
Go to `.config/texstudio/texstudio.ini` and change
`Files\Use%20Native%20File%20Dialog=true`
to
`Files\Use%20Native%20File%20Dialog=false`

**Comment by sunderme** [comment]
This is rather a qt issue

**Comment by sunderme** [comment]
works fine on ubuntu gnome/wayland.
I would suggest to compile txs on your own as QT versions during comipaltion and use differ.
