### ISSUE TITLE
Custom TeX file syntax Highlightning

### ISSUE THREAD

**Issue by sergiokapone** [texstudio-org/texstudio#141]
### Environment
- TeXstudio: VERSION 	TeXstudio 2.12.8 (hg 2.12.8) portable
- Qt:  5.8.0 
- OS: Windows(8.1) 
- TeX distribution: texlive 

### Actual behavior

I had download all *.qnfa files from utilities\qxs\ to config\languages folder and redefined styles(color, font,...)  in defaultFormats.qxf. I expected the changing of format (color, font,...) after restart TS But it leaved the same as built-in

Also, I put in config\languages\python.qnfa and python.qxf from TS help, and again, no reaction on .py files too.

I see some strange colors even without python.qnfa in languages\ .  Where dit it get it?

[Screenshot](https://ibb.co/jCuOFd)

Do I need to recompile TS from sources?

May be it is better to create checkbox in Syntax Highlightning configuration dialog for choosing internal/external Highlightning ?

**Comment by sunderme** [comment]
I would expect that color/font/etc are changed in the options and hence stored in texstudio.ini. So, I don't expect txs to honor defaultFormats.qxf, whereever it is placed, if texstudio.ini exists ...

**Comment by sunderme** [comment]
but I will take a close look ...

**Comment by sunderme** [comment]
seems to work fine.
the 'languages' directory needs to be where texstudio.ini is present ...

**Comment by sergiokapone** [comment]
Yes, my languages\ is in config\ folder, but, unfortunantly, I do not know why this is not work for my case.

**Comment by sunderme** [comment]
your answer is not that complete that I can really determine that you are looking at the correct folder. Please give the complete path.

**Comment by sergiokapone** [comment]
\TeXStudio\config\languages\

**Comment by sunderme** [comment]
You are using an irregular path. How is that path set for texstudio ?

**Comment by sergiokapone** [comment]
Why this path is irregular? I do not understand.  Folder **languages\** located in TXS's **config\** folder, any  other features (user templates, user completion, etc from **config\** folder  are well recognized by TXS). Why **languages\** do not recognized?

**Comment by sunderme** [comment]
usually the config is located in appdata\texstudio and not programs\latex\texstudio\config ...

**Comment by sergiokapone** [comment]
Yes, but it is for installed version of TXS, but I use **portable** one (texstudio-2.12.8-win-portable-qt5.zip). Portable version seek files in config\ folder.  Hmm... may be the bug is here for portable version only?

**Comment by thatlittleboy** [comment]
@sergiokapone I just tried with the portable version, 2.12.12. It works as expected (the highlighting is as claimed in the user manual). Did you remember to switch the language highlighting? `View -> Highlighting -> Python` should be present and should be selected. With the QNFA and qxf files in `./config/languages`.
