### ISSUE TITLE
Improve parsing of multiline LaTeX3 warnings/errors

### ISSUE THREAD

**Issue by tweh** [texstudio-org/texstudio#1410]
This issue might be linked to issue #318 could be tagged “enhancement”.

### Environment
- TeXstudio: 3.0.1
- Qt: 5.15.0
- OS: macOS 10.15.7
- TeX distribution: texlive 2020

### Actual behavior
For longer warnings issued by LaTeX2e using `\MessageBreak` or by LaTeX3 package in general in the LOG file for every line except the first one the message is indented and the line starts with `(<pkg>)` (marked red). The latter text is then parsed by TeXstudio to be part of the message in the table view. For warnings without `\MessageBreak` the parsing is fine, since the format of the message in the LOG is different.
![txswarning tex - TeXstudio 2020-12-31 11-34-54](https://user-images.githubusercontent.com/3011538/103406916-b45cff00-4b5c-11eb-9146-4a7cd28987f0.png)

### Expected behavior
It would be nice if TeXstudio could filter these texts (marked red) and show only the real message text without interruption.

### How to reproduce
Example to test

```latex
\documentclass{article}

\newcommand{\warningIIeA}{%
   \PackageWarning{demo}{This is a quite long warning message broken in multiple lines, but the parser incorporatdes the line prefix conatining the package name.}
}
\newcommand{\warningIIeB}{%
   \PackageWarning{demo}{This is a quite long warning message broken in multiple\MessageBreak lines, but the parser incorporatdes the line prefix\MessageBreak conatining the package name.}
}

\usepackage{xparse}

\ExplSyntaxOn
\msg_new:nnnn { demo } { message } { This~is~a~quite~long~warning~message~broken~in~multiple~lines,~but~the~parser~incorporatdes~the~line~prefix~conatining~the~package~name. } { no~futher~help~... }
\NewDocumentCommand{ \warningIII } { } {
   \msg_warning:nn { demo } { message }
}
\ExplSyntaxOff

\begin{document}
\LaTeXe\ warning message \warningIIeA

\LaTeXe\ warning message with message break \warningIIeB

\LaTeX3 warning message \warningIII
\end{document}
```

**Comment by muzimuzhi** [comment]
Reproducible when using `\MessageBreak` in latex2e style `\PackageWarning`.

**Comment by tweh** [comment]
Thanks. I updated/generalised the title and comment.

**Comment by tobiasBora** [comment]
Note also that if the error message contains a long line like `robustExternalize/robExt-ABC41082ADB6EF46AFE4D61D09630D7A.pdf` here:
```
! Package robExt Error: On line 16: the pdf file
(robExt)               
robustExternalize/robExt-ABC41082ADB6EF46AFE4D61D09630D7A.pdf
(robExt)                is not present. The compilation command "cd
(robExt)                robustExternalize/ && gnuplot -c
(robExt)                "robExt-ABC41082ADB6EF46AFE4D61D09630D7A.tex" &&
(robExt)                echo "ok" >
(robExt)                "robExt-ABC41082ADB6EF46AFE4D61D09630D7A.pdf"" used
(robExt)                to compile the environment on line 16 certainly
(robExt)                failed with errors:
(robExt)                vvvvvv
(robExt)                some random message error from gnuplot
(robExt)                ^^^^^^
(robExt)                See full logs below or in
(robExt)               
robustExternalize/robExt-ABC41082ADB6EF46AFE4D61D09630D7A-compilation.log.
```
the error message is even worse as it will not even print anything past "On line 16: the pdf file".
