### ISSUE TITLE
GUI Scaling - Embedded PDF Toolbar

### ISSUE THREAD

**Issue by jcardenast** [texstudio-org/texstudio#1413]
### Environment
- TeXstudio:  3.0.3
- Qt: 5
- OS: Windows 8.1
- TeX distribution: Not necessary for that 

### Expected behavior
I change the size of the Embedded PDF Toolbar less than default value ( the first mark ), 
### Actual behavior
The Icon's size change as expected, but when I restart TextStudio and enter again to configuration window and click ok, The icons size change to the minimum and the slider appears in the begin. Therefore, the icon's size result less than I configured before. See the images below

### How to reproduce

![image](https://user-images.githubusercontent.com/12958198/103447831-64fef780-4c5e-11eb-8294-7d6a0e2a9346.png)
Pressing reset value to restart Embedded PDF Toolbar

![image](https://user-images.githubusercontent.com/12958198/103447845-94adff80-4c5e-11eb-8ffe-0a9130db7b8a.png)
Adjusting to the desire size and save the change ( next, I restart TextStudio and enter to configure and click on save again without doing something)

![image](https://user-images.githubusercontent.com/12958198/103447896-7eed0a00-4c5f-11eb-9a54-b2d46e3327a8.png)
I open again and the icons change to smallest size possible.

**Comment by sunderme** [comment]
fixed with 3.0.4 (to be published soon)

**Comment by nmadani** [comment]
Interesting that my installation of TexStudio 3.0.3 on Windows 10 under Options -> Configure TexStudio... -> GUI Scaling shows the first three sliders but not the "Embedded PDF Toolbar" option! On my macOS installation it is there. BTW, I could never express enough gratitude to the developers of TexStudio! Absolutely awesome!

**Comment by nmadani** [comment]
P.S. uninstalled and reinstalled 3.0.4, problem fixed. Thanks again.
