### ISSUE TITLE
How to change the key-binding for Multi-Cursors?

### ISSUE THREAD

**Issue by 1900011604** [texstudio-org/texstudio#1414]
How to change the key-binding for Multi-Cursors?

I want to set the default `Ctrl+Cursor` to `Alt+Cursor`, which is the same as VS code.

**Comment by sunderme** [comment]
not sure what you exactly want to do 
Have you looked at option/bindkeys/basic editing ?

**Comment by 1900011604** [comment]
Yes, there is none. Even I change the Ctrl+Alt+Up/Down` to `Alt+Up/Down`.

**Comment by sunderme** [comment]
please be more verbatim about what you are doing, which OS, possibly screenshots.

**Comment by muzimuzhi** [comment]
I didn't know that texstudio supports multi-cursor too until just now.

In macOS, a mirror cursor can be inserted by `Option + Command + Click`. Guess in @1900011604's system the corresponding shortcut is `Ctrl + Click`, and he wanted to change the `Ctrl` to `Alt`. 

link: [vscode doc for multi-cursor](https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor)

**Comment by sunderme** [comment]
it is ctrl+alt+click on other systems and , no, you can't change that.

**Comment by sunderme** [comment]
I assume that this is solved
