### ISSUE TITLE
input breaks structure in navigation panel

### ISSUE THREAD

**Issue by bastianleirpo** [texstudio-org/texstudio#1416]
### Environment
- TeXstudio: 3.0.4 (and at least 3.0.1)
- 
### Expected behavior
Sections, chapters etc. shall be aligned correctly.
![image](https://user-images.githubusercontent.com/22075788/103611085-cf938a00-4f21-11eb-9e80-80d13b96358a.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/22075788/103610913-73c90100-4f21-11eb-8148-e52444143b64.png)

**Comment by muzimuzhi** [comment]
Guess that is considered as a feature ...

**Comment by sunderme** [comment]
yes, it is a feature.
However you can change the behavior in option/advanced editor/keep indentation of includes in structure tree

**Comment by bastianleirpo** [comment]
Oh sorry, and thanks! I would highly suggest to activate this option as default setting.

**Comment by sjtuwx** [comment]
@sunderme    Thanks a l....................ot!  I also have this problem, and I solved it today by your help!
My god!  I am so happy!  Yes!  Yes!  Yes!  Yes!
