### ISSUE TITLE
[Feature Request] Bring ''Go to source'' option back please

### ISSUE THREAD

**Issue by PhilScience** [texstudio-org/texstudio#1418]
Hi, I 'm using the TeXstudio 3.0.1 (git 3.0.1) / Using Qt Version 5.12.1, compiled with Qt 5.12.1 R , which I believe is the last version to write my papers. I noticed that after the last update the ''Go to source'' option when right-clicking on the pdf viewer has been removed. I find this feature very helpful since when spotting errors/typos on the pdf one can just right click and go to the relevant source code instead of trying to find it. 

Is there any particular reason this feature has been removed? Could you please bring it back?

Thanks!

**Comment by dbitouze** [comment]
I don't see this trouble with the development version of TXS:

- TeXstudio 3.0.5 (git 3.0.1-159-g476bf102)
- Qt version 5.12.6

**Comment by PhilScience** [comment]
How can I get this version? I have just updated to the latest available version for windows from the texstudio.org website which is 3.0.4 and the feature is still missing when I right-click on the pdf viewer.

**Comment by dbitouze** [comment]
>How can I get this version?

By cloning the current Git repository.

**Comment by muzimuzhi** [comment]
> How can I get this version?

https://bintray.com/sunderme/texstudio

**Comment by muzimuzhi** [comment]
> I noticed that after the last update the ''Go to source'' option when right-clicking on the pdf viewer has been removed.

I tested on macOS and found that when the corresponding`*.synctex.gz` file is not found, the "Go to source" option is hidden.

**Comment by sunderme** [comment]
first step would be to check that the pdflatex actual produces the sync information (....synctex.gz), for this pdflatex needs to run with option `-synctex=1` ... so , do you have the ...syntex.gz file next to your tex source ?

**Comment by PhilScience** [comment]
@sunderme and @muzimuzhi thanks for the info. Yes, the syntex.gz file is in the same folder as the tex source file. But I also noticed that when I click the corresponding ''go to pdf'' option it doesn't work either and I get a message at the bottom of the pdf viewer saying ''No Syncdata available''

**Comment by sunderme** [comment]
remove the synctex file and regenerate it ?
In principle pdf syncing in the program code has not been touched for some time ...

**Comment by sunderme** [comment]
no feedback
