### ISSUE TITLE
Insert text at cursor, not append at the end

### ISSUE THREAD

**Issue by bonej079** [texstudio-org/texstudio#1419]
### Environment
- TeXstudio: 3.0.4
- Qt: 5.5.1
- OS: Linux (Pop!_OS)
- TeX distribution: texlive

### Expected behavior

When inserting text, the text should be inserted at the cursor, not appended at the end.

### Actual behavior

Adding sub to \section to get \subsection, instead the text is always appended at the end of the word so the result is \sectionsub

### How to reproduce

Put cursor after \ in \section, type sub, cursor moves automatically to the end. 

Example video attached.

https://user-images.githubusercontent.com/11914535/103757062-84a47000-5010-11eb-8621-5020c3dc0161.mp4

**Comment by muzimuzhi** [comment]
It works ok on macOS. Does other commands have the same problem?

**Comment by bonej079** [comment]
It happens with all text, not just LaTeX commands. See the attached video.


https://user-images.githubusercontent.com/11914535/103757298-db11ae80-5010-11eb-957e-20832a2ecec5.mp4

**Comment by sunderme** [comment]
you are using the appimage ?

**Comment by sunderme** [comment]
i would suggest that you compile txs locally, see wiki

**Comment by bonej079** [comment]
I am using the AppImage. I installed from the .deb version and the issue is gone. Thanks for the advice.

**Comment by bonej079** [comment]
Bug still present. I am using the .deb installed version now, and the problem persists.


https://user-images.githubusercontent.com/11914535/103769568-d0611480-5024-11eb-95e8-253a928edfb7.mp4

**Comment by sunderme** [comment]
maybe remove .config/texstudio/texstudio.ini , maybe compile it on your own.

**Comment by sunderme** [comment]
nothing we can do
