### ISSUE TITLE
Recognize and autofill biblatex-chicago

### ISSUE THREAD

**Issue by richardohrvall** [texstudio-org/texstudio#142]
Hi!

When I use the biblatex package I can write \parencite{ or other cite commands and get suggestions of different cite keys. But if I instead use the biblatex-chicago package \parencite and other cite commands are highlighted as unrecognized and I don't get any suggestion of different cite keys. Would it be possible to get the same features for biblatex-chicago as for biblatex? I use bibalatex-chicago because it can handle orginal dates for publications.

All the best,
Richard

**Comment by sunderme** [comment]
txs uses the package name toload a cwl (see manual/wiki) which contains akk the information about commands. Unknown packages are scanned, but the automatic scna can only detect correct commands, not its usage (i.e. tha it handles citations). You colud either edit the bibalatex-chicago or activate the biblatex.cwl in the options.
