### ISSUE TITLE
Keyboard shortcut to swap two lines of LaTeX code

### ISSUE THREAD

**Issue by sh-cau** [texstudio-org/texstudio#1420]
I would enjoy having a keyboard shortcut that lets me swap two lines of LaTeX code.

### Environment
- TeXstudio: 2.12.6
- Qt: 5.9.5
- OS: Ubuntu 18.04.5 LTS (Bionic)
- TeX distribution: pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian)

### Expected behavior
E.g. I assigned `Ctrl+Shift+↑` to swap the line where the curser currently is with the line above it.

Before (curser is in the "Ipsum" line):
\item Lorem
\item Ipsum

After:
\item Ipsum
\item Lorem

**Comment by muzimuzhi** [comment]
See Configure -> Shortcuts -> Menus -> Editor -> Line Operations -> Move Line Up/Down
![image](https://user-images.githubusercontent.com/6376638/103913198-45c30700-5143-11eb-963e-2dd9f9675832.png)

**Comment by sh-cau** [comment]
I'm so sorry. I tried to avoid this, but obviously I was not able to find this option :D Thank you.
