### ISSUE TITLE
Incompatibility between LanguageTool and TexStudio dictionary names

### ISSUE THREAD

**Issue by jmollera** [texstudio-org/texstudio#1425]
### Environment
- TeXstudio: 3.0.4 (git 3.0.4)
- Qt: 5.12.3, compiled with Qt 5.12.3 R
- OS: Windows 10 (20H2)
- TeX: miktex
- LanguageTool: 5.2 (released 2020-12-29)
 
### What I have found
I'm writing a text in Catalan, and until recently I was only using the dictionaries includes in the TeXstudio distribution. Then I learned about LanguageTool and installed it, but it wasn't working because it complained that the language selected (in Options/Configure TeXstudio.../Language Checking) was not supported. After some time I realized that the problem was in the names of the files given to the dictionary Catalan files in the "dictionaries" folder of the TeXstudio distribution: **ca_CA-Catalan.aff** and **ca_CA-Catalan.dic**; the same problem applies to the Catalan Valencian files: **ca_CAVA-CatalanValencian.aff** and **ca_CAVA-CatalanValencian.dic**.

### How I solved the problem
After some time I realized that the problem could be solved by changing the names of the above files to: **ca_ES-Catalan.aff** and **ca_ES-Catalan.dic** (for Catalan), and **ca_ES-valencia-CatalanValencian.aff** and **ca_ES-valencia-CatalanValencian.dic** (for Catalan Valencian).

### What I'm proposing
Perhaps future distributions of TeXstudio could rename those four files to the names I've found to be working correctly with LanguageTool.

**Comment by sunderme** [comment]
I would guess that language tool uses a wrong language code ?

**Comment by jmollera** [comment]
I think the standard name is ca_ES.

Some links:
[https://www.localeplanet.com/icu/](url)
[https://lh.2xlibre.net/locale/ca_ES/](url)
[http://manpages.ubuntu.com/manpages/bionic/man3/DateTime::Locale::ca_ES.3pm.html](url)
[https://docs.oracle.com/cd/E23824_01/html/E26033/glset.html](url)

**Comment by sunderme** [comment]
ca-Catalan.dic works as well ?

**Comment by jmollera** [comment]
No, ca-Catalan doesn't work.

Here you can see the message error that appears when I point the mouse to the LT icon in the bottom toolbar:

![ca](https://user-images.githubusercontent.com/77206640/104125488-52b84400-5357-11eb-9317-5d3a8f4b2531.png)

**Comment by sunderme** [comment]
should be fixed
