### ISSUE TITLE
Strange behavior of search and replace using many spaces

### ISSUE THREAD

**Issue by Stimmenhotel** [texstudio-org/texstudio#1426]
### Environment
- TeXstudio: 3.0.4
- Qt: 5.12.3
- OS: Win 10
- TeX distribution: miktex 20.1x

### Expected behavior
If I search for repeated spaces "                             " everything still seem to work.
If I use the "+" to search in more documents it shows me the expected result.

If I now want to replace the "string" of spaces with only, I expect to have the "big space parts" replaced with only one.
### Actual behavior
Especially very big tables are getting screwed up. See the video.

### How to reproduce
Open the attached file,
Click on the icon shown below
![grafik](https://user-images.githubusercontent.com/15821524/104107351-b8ef8900-52bb-11eb-95bd-d4640e7d5e8c.png)
The table is getting badly resized, you saved, you want to undo it.
Search for a few spaces "    ", click on + and try to replace them with only one space " "

Testfile: (rename to tex, git wont upload tex. Also dont mind the content, just needed some content ;-) )
[test.tex.txt](https://github.com/texstudio-org/texstudio/files/5791726/test.tex.txt)

Video:
![20-54-26](https://user-images.githubusercontent.com/15821524/104107555-526b6a80-52bd-11eb-8160-b41b517f85a4.gif)

**Comment by sunderme** [comment]
fixed with 75bced3
