### ISSUE TITLE
The speed of downloading 'TeXStudio for Windows' is very slow.

### ISSUE THREAD

**Issue by NigelBoxing** [texstudio-org/texstudio#1427]
### Environment
- TeXstudio: 3.0.4
- Qt: 5
- OS: Windows 10
- TeX distribution: texlive

### Expected behavior

Provide a mirror site for downloading.
### How to reproduce
downloading freom "https://github.com/texstudio-org/texstudio/releases/download/3.0.4/texstudio-3.0.4-win-qt5.exe"

**Comment by sunderme** [comment]
since txs is provided for free, there is not much we can do.
In theory, releases are copied to https://sourceforge.net/projects/texstudio/ but that does not work well.

**Comment by foreachthing** [comment]
@NigelBoxing,  how slow? Where do you downloas from? 
I downloaded it in like 5 seconds,  from github and Switzerland.
