### ISSUE TITLE
Feature request: adding an accurate word count tool

### ISSUE THREAD

**Issue by ycwang427** [texstudio-org/texstudio#1430]
I think adding a tool to accurately count words might be helpful. 

Though there is a "Text Analysis" tool, its result is not accurate enough. For example, it seems to count everything that looks like a word, e.g. "document" in `\begin{document}`, "amsmath" in `\usepackage{amsmath}`.

Also, it does not work for languages like Chinese and Japanese, where there is no spaces between words or characters. The "Text Analysis" tool simply regard a sentence or even a whole paragraph as a word/phrase. (As far as I know, for Chinese documents we just count the number of characters.)

I was wondering if some scripts, e.g. [TeXcount](https://app.uio.no/ifi/texcount/) (it seems to work fine for me), can be added to TeXstudio.

**Comment by clsgg** [comment]
You can add a user commands to add TeXcount to TeXstudio in “Options”-“Configure TeXstudio”-“Build”.
eg:
texcount -brief -sum=1 -ch YourDir/*.tex

**Comment by sunderme** [comment]
executing that tool from txs should suffice.
