### ISSUE TITLE
Unable to install on MacOSx

### ISSUE THREAD

**Issue by santoshchiniwar** [texstudio-org/texstudio#1431]
MacOSx security says,  "unable to identify the software is free from malware". So I can't install it on MacOS 11.1

Thank you

**Comment by muzimuzhi** [comment]
1. Open `Applications` folder
2. Open `.dmg` file, drag the `texstudio.app` into `Applications`. This will copy `texstudio.app` into `Applications`.
3. Right click the copied `texstudio.app`, then choose `Open`

If you have homebrew installed, then executing `brew install texstudio` is equivalent to the first two steps.

**Comment by sunderme** [comment]
see also comment on webpage (texstudio.org)
<img width="519" alt="grafik" src="https://user-images.githubusercontent.com/14033169/104838189-9233e280-58b9-11eb-84e8-3b1c4ec4caaa.png">
