### ISSUE TITLE
Embedded pdf viewer not showing eps generated figures properly 

### ISSUE THREAD

**Issue by JoeHRIsaac** [texstudio-org/texstudio#1439]
### Environment
- TeXstudio: TeXstudio 3.0.4 (git 3.0.4)
- Qt: Using Qt Version 5.15.1, compiled with Qt 5.15.1 R
- OS: Mac OS Big sur 11.1 (20C69)
- TeX distribution: MacTex - pdfTeX 3.14159265-2.6-1.40.17 (TeX Live 2016)

### Expected behavior
When compiling eps files, the legends, title and axis labels should appear in the embedded pdf viewer

### Actual behavior
The figure appears with the lines of the graph, but no text is rendered in the embedded PDF viewer. However when opening the file externally using preview of Mac, the labels and axes are rendered properly. The embedded pdf viewer alone is not working.

### How to reproduce
Compile any tex file with an eps file

**Comment by sunderme** [comment]
please,provide,a sample document.

**Comment by JoeHRIsaac** [comment]
Thank you. Following your instruction kind of fixed the issue.
So here's what happened: when I copied the eps file to another folder to prepare a sample document with the same figure, the text of the graphs rendered properly. On closer inspection, it seems that after I delete the converted files from eps (for example file xyz.eps will create a file called xyz-converted-to.pdf) and recompile the full code after clearing the cached files works. 

Thanks for making me to find the issue. It works now.
