### ISSUE TITLE
Crash when pressing Shift+z in a \cite{} command due to large .bib file

### ISSUE THREAD

**Issue by SabinSnorlax** [texstudio-org/texstudio#144]
### Environment
- TeXstudio:  2.12.8 (hg 2.12.8-1-g68cd350)
- Qt:  5.8.0, compiled with Qt 5.8.0 R
- OS:  Windows 10
- TeX distribution:  MiKTeX-pdfTeX 2.9.6642

### Expected behaviour
Normal citation of a reference starting with "Z"

### Actual behaviour
Program crash

### How to reproduce
I have added a simple .tex file and my literature .bib file in [test.zip](https://github.com/texstudio-org/texstudio/files/2014935/test.zip)

As soon as you type Shift+z inside the \cite{} command, the program should crash.
Any other letter will work fine.

The issue is clearly related to the size of the .bib file.
If I have only one reference with Z in the .bib file, TeXstudio works fine.
But if I use my - admittedly very large .bib file - it crashes.
Nonetheless, I am surprised this only occurs for Z but not for Y for example (if this would have something to do with references with Z being located at the end of the .bib file).

Many thanks in advance!

**Comment by sunderme** [comment]
fixed
