### ISSUE TITLE
Invalid build dependency

### ISSUE THREAD

**Issue by OgreTransporter** [texstudio-org/texstudio#1444]
https://github.com/texstudio-org/texstudio/blob/a3f1fc52f220e854588eff8a106b84d6de72c072/src/pdfviewer/pdfviewer.pri#L71

https://github.com/texstudio-org/texstudio/blob/a3f1fc52f220e854588eff8a106b84d6de72c072/src/quazip/quazip/quazip.pri#L6

The library z exists on Windows only in the MinGW Linux environment. It does not exist under Windows otherwise. If you use e.g. Visual Studio for compiling, you get the following error message:
```
LINK : fatal error LNK1104: cannot open file "z.lib"
```
```
LINK : fatal error LNK1104: cannot open file "zlib.lib"
```

**Comment by sunderme** [comment]
both packages need z-lib, they don't compile without.

**Comment by OgreTransporter** [comment]
Yes, but only under Linux/MacOS and Windows with MinGW (GCC). z does not exist under Windows otherwise, instead you have to link zlib.

This mess with hardcoded dependencies is one reason why I still prefer CMake. CMake looks for the dependencies and if they are not in the default directories, the user can specify the location without having to change a file.

**Comment by sunderme** [comment]
not sure what there should happen. The code blocks need z.lib. That has to be provided in some way... 
This has nothing to do qmake or cmake.

**Comment by OgreTransporter** [comment]
> This has nothing to do qmake or cmake.

True, it has something to do with TXS project configuration. For example, Z is not required for quazip but zlib.

https://github.com/texstudio-org/texstudio/blob/b0ce7dd556983c517132df564120a207e4532d6b/src/quazip/CMakeLists.txt#L42
```
# Use system zlib on unix and Qt ZLIB on Windows
if(UNIX OR MINGW)
    find_package(ZLIB REQUIRED)
else(UNIX OR MINGW)
    set(ZLIB_INCLUDE_DIRS "${QT_ROOT}/src/3rdparty/zlib" CACHE STRING "Path to ZLIB headers of Qt")
    set(ZLIB_LIBRARIES "")
    if(NOT EXISTS "${ZLIB_INCLUDE_DIRS}/zlib.h")
        message("Please specify a valid zlib include dir")
    endif(NOT EXISTS "${ZLIB_INCLUDE_DIRS}/zlib.h")
endif(UNIX OR MINGW)
```

Meanwhile even only
https://github.com/stachenov/quazip/blob/7d7661de38843fbe47af2132d800bcf52d645a55/CMakeLists.txt#L62
```
find_package(ZLIB REQUIRED)
```

Poppler also uses zlib and not z: https://gitlab.freedesktop.org/poppler/poppler/-/blob/master/CMakeLists.txt

**Comment by sunderme** [comment]
You are building txs with cmake, so the issue does not concern you ?

**Comment by OgreTransporter** [comment]
Yes and no.

Yes, I build with CMake because as mentioned several times Visual Studio and Qt Creator don't get along so well.

No, this has nothing to do with CMake. The CMake scripts mentioned are the original build files of the dependencies and have nothing to do with my build. They are not in my CMake branch but in external projects.

**Comment by sunderme** [comment]
the cmake files are not used at all. 
It is completely unclear what you want to be changed.
