### ISSUE TITLE
"Open External Terminal" does not work

### ISSUE THREAD

**Issue by SadraBA** [texstudio-org/texstudio#1449]
### Environment
- TeXstudio: 3.0.4
- Qt: 
- OS:  Windows 7 
- TeX distribution:  texlive 
- TeXstudio installed from:  windows installer in texstudio.org 
- Compiler version (if compiling from source):

**Comment by SadraBA** [comment]
"Open External Terminal" in Tools Menu does not work correctly. After clicking on this command in Tools menu a cmd window is opened and immediately closed.

**Comment by sunderme** [comment]
works fine on win 10.
Win 7 is EOL !
