### ISSUE TITLE
Keyval options marked as unrecognized despite being in autocompleter

### ISSUE THREAD

**Issue by thatlittleboy** [texstudio-org/texstudio#145]
### Environment
- TeXstudio: 2.12.9 (git 15179a9)
- Qt: 5.8.0 
- OS: Windows 10 
- TeX distribution: MikTeX

### Actual behavior
It seems the parser only "recognizes" key-val options word-by-word, instead as treating it as a whole phrase. For example: `reciprocal-positive-first` is a valid value for the `per-mode` key in `siunitx` (as the autocompleter prompts it), but the words `-positive-first` still end up as unrecognized.

<img src=https://user-images.githubusercontent.com/30731072/40229821-51e729a8-5a8d-11e8-8a22-289d2d7e3769.png width=500px>

<img src=https://user-images.githubusercontent.com/30731072/40229823-54378ec8-5a8d-11e8-95de-af3bf06faab7.png width=500px>

-------------------------

There seems to be a disconnect between what is recognized by TXS and what is being autocompleted. This is surprising since I took for granted that whatever is in the `cwl` should be recognized, as evidenced by several TeX stackexchange answers, [for example](https://tex.stackexchange.com/q/47493).

**Another example:**

<img src=https://user-images.githubusercontent.com/30731072/40230030-1358a6f2-5a8e-11e8-8afe-c749afd392b3.png width=500px>
<img src=https://user-images.githubusercontent.com/30731072/40230032-143e7222-5a8e-11e8-8179-c8064966ef53.png width=500px>

----------------
This then seems to further confirm that the parser does not compare against the entire phrase in key-val lists declared in the `cwl` file -- only up to the first word?? -- (Since `symbol` is also a valid value of the `per-mode` key, but `repeated`, by itself, is not.)

### Expected behavior

The key-val suggestions that appear in the autocompleter should be recognized by TXS after they have been entered. (or perhaps I should say, the values should be treated as a whole phrase if they are composed by words separated by hyphens, as in the `siunitx` case).

### How to reproduce
Open up the autocompleter for the below example, and look at the results for all the key-val options: paying attention to the ones that are phrases instead of words.

```
\documentclass{article}
\usepackage{siunitx}

\begin{document}
	\si[per-mode=]{}
\end{document}
```

**Comment by sunderme** [comment]
fixed
