### ISSUE TITLE
Internal PDF viewer: cannot scroll horizontally with touchpad (Windows 10)

### ISSUE THREAD

**Issue by ycwang427** [texstudio-org/texstudio#1450]
### Environment
- TeXstudio: 3.0.4
- Qt: 5
- OS: Windows 10 
- TeX distribution: texlive
- TeXstudio installed from: binary

### Expected behavior
In Windows 10, I should be able to scroll the document in the "Internal PDF Viewer" by placing two fingers on the touchpad and sliding horizontally or vertically.

### Actual behavior
When I slide two fingers **horizontally**, the PDF Viewer won't scroll horizontally. (There is no problem with vertical scrolling; The problem with horizontal scrolling does not exist in TeXstudio 2.x versions.)

### How to reproduce
- View a PDF with the "Internal PDF Viewer";
- Zoom in so that the document can be scrolled horizontally;
- Slide two fingers horizontally on the touchpad.

**Comment by sunderme** [comment]
should be fixed with latest commit.
Please test https://bintray.com/sunderme/texstudio/texstudio-win#files (latest !)

**Comment by ycwang427** [comment]
> should be fixed with latest commit.
> Please test https://bintray.com/sunderme/texstudio/texstudio-win#files (latest !)

It works, thank you.
