### ISSUE TITLE
Dark theme not working

### ISSUE THREAD

**Issue by jdramirez08** [texstudio-org/texstudio#1451]
### Environment
- TeXstudio:  3.0.4
- Qt:  5.14.2
- OS:  Ubuntu 20.10
- TeX distribution:  Texlive
- TeXstudio installed from:  binary (PPA)

### Expected behavior
I tried to change the theme of Texstudio as I did in Windows, applying the theme "Adwaita Dark (txs)" but this is not on the list.
I would like to know whether this can be applied in Ubuntu.
![image](https://user-images.githubusercontent.com/70728656/105562258-86945180-5ce7-11eb-806d-ba1673692ab2.png)

Thank you very much

**Comment by sunderme** [comment]
ubuntu offers adwaita-qt as extra package.

**Comment by jdramirez08** [comment]
I just need to install it and the option will appear?

**Comment by jdramirez08** [comment]
Thank you
