### ISSUE TITLE
Modefrn-dark for style Fusion does not work anymore!

### ISSUE THREAD

**Issue by sergiokapone** [texstudio-org/texstudio#1457]
TeXstudio 3.0.5 (git )
Using Qt Version 5.15.2, compiled with Qt 5.15.2 R
Windows 10

Modefrn-dark for style Fusion does not work anymore!

**Comment by sunderme** [comment]
there were too many issues with modern dark, so for windows adwaita dark is suggested for dark mode.

**Comment by sergiokapone** [comment]
Sad, but how then can you fix this [#1370](https://github.com/texstudio-org/texstudio/issues/1370)?

**Comment by sunderme** [comment]
you can try a recent dev. build if it still persists.
Apart I have no idea what could go wrong ...

**Comment by sergiokapone** [comment]
Yes, confirm. Now the toolpi are small. But the big  Adwiata's style buttons depress me anyway.

**Comment by sunderme** [comment]
if you find a different stylesheet which gives better result, we can integrate it into txs. But I am done tweaking styles.

**Comment by sergiokapone** [comment]
> But I am done tweaking styles.
It looks like you left no choice for a dark scheme for Windows users. Or Adwaita or nothing.

>  which gives better result
Style Fusion with dark scheme was a good scheme.

I hope you can fix the problems sometime in the future.
