### ISSUE TITLE
Crash when opening and building other file

### ISSUE THREAD

**Issue by stefanbschneider** [texstudio-org/texstudio#1459]
### Environment
- TeXstudio: 3.0.1 (same for 3.0.4)
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution: miktex
- TeXstudio installed from: Binary from website

### Expected behavior

* Double click on my `main.tex` file starts TeXstudio and opens the file
* TeXstudio also shows previously open files
* Changing the root document to `main.tex` and clicking build (pressing F5) should build the PDF for the new root document

### Actual behavior

* Starting, showing `main.tex` and setting it as root works fine
* But when clicking build, TeXstudio crashes

### How to reproduce

* This behavior is reproducible and requires that TeXstudio initially is not yet open, but opened by double clicking the new `main.tex`. There are other open files, one of them was the previous root document before switching to `main.tex`. I also always close the other files other than `main.tex` before trying to build.
* The crash can be avoided by starting TeXstudio first and then opening the new file `main.tex` (rather than both at once through double click).

**Comment by sunderme** [comment]
quick test does not crash. Please provide the files.
In general it is not necessary to explicitly set a root file.

**Comment by stefanbschneider** [comment]
Hm, strange. I can't reproduce it anymore. Sorry about that
