### ISSUE TITLE
TeXstudio misinterprets the key combination "RightAlt + s"

### ISSUE THREAD

**Issue by concastinator** [texstudio-org/texstudio#1460]
### Environment

- TeXstudio: 3.0.4
- Qt: 5.12.3
- OS: Windows 10 x64
- TeX distribution: MiKTeX 21.1 x64
- TeXstudio installed from: binary

The bug also affects TXS 2.12.*, with Qt4, running on Windows 7 x32.

### Expected behavior

I am using the "Romanian (Programmers)" keyboard layout. With it, the combination "RightAlt + s" should produce the character "ș".

### Actual behavior

The combination "RightAlt + s" opens the "Save As" window, instead of outputting the character "ș".

### How to reproduce

Install the "Romanian (Programmers)" keyboard layout and switch to it.
Open a .tex document.
Press "RightAlt + s".

### Other software

TeXmaker does not exhibit this bug. TeXworks suffers from the same issue ("RightAlt + s" opens the "Save File" window instead of outputting a "ș").

**Comment by muzimuzhi** [comment]
Does the "LeftAlt + s" work as expected? As a last solution, you can change the shortcut for "RightAlt + s" in Configure TeXstudio -> Shortcuts.

**Comment by concastinator** [comment]
> 
> 
> Does the "LeftAlt + s" work as expected? As a last solution, you can change the shortcut for "RightAlt + s" in Configure TeXstudio -> Shortcuts.

Yes, it does, and by this I mean that it doesn't do anything special - as it should. By default, only the RightAlt behaves as a modifier, producing letters with diacritics.

**Comment by sunderme** [comment]
in windows altgr is actually ctrl+alt , hence altgr+s is recognized as save as. Change themshortcut for save as to something else, and it should work.

**Comment by concastinator** [comment]
> 
> 
> in windows altgr is actually ctrl+alt , hence altgr+s is recognized as save as. Change themshortcut for save as to something else, and it should work.

Indeed, this solves my issue and, in retrospect, it was not bug.
