### ISSUE TITLE
umlauts are not recogniced anymore by spell checker

### ISSUE THREAD

**Issue by Stimmenhotel** [texstudio-org/texstudio#1461]
### Environment
- TeXstudio: 3.0.5 eac6f7d
- Qt: 5.15.2
- OS: Windows 10
- TeX distribution: Miktex 20.1x
- TeXstudio installed from: Bintray (sunderme)

### Expected behavior
Before updating from commit b75a03f version everything worked fine.
Words containing umlauts are spelled correctly and the spell checker doesn't mark them as wrong.
![grafik](https://user-images.githubusercontent.com/15821524/106272927-1e3af800-6232-11eb-9c42-212d9ecba184.png)
(mind the words beschränkt and Überwachung in the middle of the picture)

### Actual behavior
Updating to eac6f7d the spell checker shows many words as wrong, even they are spelled correctly.
![grafik](https://user-images.githubusercontent.com/15821524/106272716-c7352300-6231-11eb-8333-41c9a4cca149.png)

Also, the right click won't recognize the umlaut as it and in some cases the suggestion containing a missing character(?) icon.
![grafik](https://user-images.githubusercontent.com/15821524/106272457-6279c880-6231-11eb-9590-9b55b988a364.png)

I am not sure if this is because something is wrong with my windows installation, I remember having this problem on my desktop PC a while ago, but my laptop I am using here never had similar problems.

### How to reproduce
I will try to create a reproduction scheme in a few days, once I am finished writing my thesis.
Maybe it is enough to use a few words containing umlauts in a "de_DE" document.

**Comment by sunderme** [comment]
fixed
new binary is being built
