### ISSUE TITLE
"bbding" package not working with lualatex

### ISSUE THREAD

**Issue by BeerStud** [texstudio-org/texstudio#1464]
### Environment
- TeXstudio: 3.0.4
- Qt: 5.12.3
- OS: Win 10 PRO
- TeX distribution: MikTex
- TeXstudio installed from: binary

### Description
I am using lualatex.exe with Texstudio. I am attempting to use the "bbding" package to create different objects. This is a simple code example I have tried.

`\documentclass[10pt,letterpaper,final]{article}
\usepackage{bbding}
\usepackage[T1]{fontenc}
\usepackage{ucs}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{graphicx}
\usepackage[width=8.50in, height=11.00in, left=0.50in, right=0.50in, top=1.00in, bottom=1.00in]{geometry}
\begin{document}
	
	\Square
	
	\Phone
	
\end{document}`

This is the log output specific to the \Square and \Phone entries:

`LaTeX Font Info:    Trying to load font information for U+ding on input line 12
.
("C:/Program Files/MiKTeX/tex/latex/bbding/uding.fd"
File: Uding.fd 1996/02/01 v1.0 BBding font definitions
)
luaotfload | cache : Lookup cache loaded from C:/Users/gerar/AppData/Local/MiKTeX/luatex-cache/generic/names/luaotfload-lookup-cache.luc.
luaotfload | db : Reload initiated (formats: otf,ttf,ttc); reason: Font "bbding10" not found.
luaotfload | resolve : sequence of 3 lookups yielded nothing appropriate.
luaotfload | resolve : sequence of 3 lookups yielded nothing appropriate. [1

Missing character: There is no f (U+0066) in font bbding10!
Missing character: There is no  (U+0008) in font bbding10!
{C:/Users/gerar/AppData/Local/MiKTeX/pdftex/config/pdftex.map}] (./texstudio_OYcHxd.aux))`

Nothing is printed on the screen. I have reinstalled the package; however, it doesn't help. Is this a problem with lualatex.exe or something else?

Thanks!

**Comment by sunderme** [comment]
this is a latex question ... not a texstudio issue

**Comment by muzimuzhi** [comment]
@BeerStud I could not reproduce your problem, running lualatex on texlive 2020 with all packages updated.  Perhaps the font `bdding` is not properly installed.  And when you post this to latex Q&A places such as tex.stackexchange.com, providing a version list generated by inserting `\listfiles` in preamble and found in `.log` would be helpful.

**Comment by BeerStud** [comment]
> @BeerStud I could not reproduce your problem, running lualatex on texlive 2020 with all packages updated. Perhaps the font `bdding` is not properly installed. And when you post this to latex Q&A places such as tex.stackexchange.com, providing a version list generated by inserting `\listfiles` in preamble and found in `.log` would be helpful.

Thanks for the tip. I had not thought of that.

I did just that now, and all of the files appear to be available. I think this is a MiKTeX problem.

 *File List*
 article.cls    2020/04/10 v1.4m Standard LaTeX document class
  size10.clo    2020/04/10 v1.4m Standard LaTeX file (size option)
 amsmath.sty    2020/09/23 v2.17i AMS math features
 amstext.sty    2000/06/29 v2.01 AMS text
  amsgen.sty    1999/11/30 v2.0 generic functions
  amsbsy.sty    1999/11/29 v1.2d Bold Symbols
  amsopn.sty    2016/03/08 v2.02 operator names
  bbding.sty    1999/04/15 v1.01 Dingbats symbols
fontspec.sty    2020/02/21 v2.7i Font selection for XeLaTeX and LuaLaTeX
  xparse.sty    2020-10-27 L3 Experimental document command parser
   expl3.sty    2021-01-09 L3 programming layer (loader) 
l3backend-luatex.def    2020-01-29 L3 backend support: PDF output (LuaTeX)
fontspec-luatex.sty    2020/02/21 v2.7i Font selection for XeLaTeX and LuaLaTeX

 fontenc.sty
fontspec.cfg
graphicx.sty    2020/09/09 v1.2b Enhanced LaTeX Graphics (DPC,SPQR)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
graphics.sty    2020/08/30 v1.4c Standard LaTeX Graphics (DPC,SPQR)
    trig.sty    2016/01/03 v1.10 sin cos tan (DPC)
graphics.cfg    2016/06/04 v1.11 sample graphics configuration
  luatex.def    2020/10/05 v1.2a Graphics/color driver for luatex
geometry.sty    2020/01/02 v5.9 Page Geometry
  ifvtex.sty    2019/10/25 v1.7 ifvtex legacy package. Use iftex instead.
   iftex.sty    2020/03/06 v1.0d TeX engine tests
geometry.cfg
  ts1cmr.fd    2019/12/16 v2.5j Standard LaTeX font definitions
supp-pdf.mkii
epstopdf-base.sty    2020-01-24 v2.11 Base part for package epstopdf
   uding.fd
 ***********
