### ISSUE TITLE
GUI scaling / Symbol Grid does not work in TXS3.0.5

### ISSUE THREAD

**Issue by hair-splitter** [texstudio-org/texstudio#1467]
### Environment
- TeXstudio: TeXstudio 3.0.5 (git 3.0.5beta3)
- Qt: Qt 5.15.2 R
- OS: Windows10
- TeX distribution: TeX Live 2020

The symbols on the side panel are too small and the "Options / Configure TeXstudio / GUI scaling / Symbol Grid" does not work.

**Comment by sunderme** [comment]
interestingly it works in adwaita dark and if txs is locally build...

**Comment by sunderme** [comment]
fixed with work-around
