### ISSUE TITLE
Add fontawesome(5) to "Symbols" in side panel

### ISSUE THREAD

**Issue by ppaspp** [texstudio-org/texstudio#1468]
### Describe the feature and the current behavior/state
An overview of symbols provided by the packages fontawesome/fontawesome5 could be provided within the side panel under the category of "Symbols".

Although code completion can be used to find the desired fontawesome symbol, no visual search is possible. One has to check the documentation to find an visual overview. An additional category in the side panel would make the search much faster and accessible.

### Who will benefit with this feature?
Anyone how would like to add a symbol from the fontawesome package

**Comment by sunderme** [comment]
we would need a list of the symbols, preferable in txs xml format, see https://github.com/texstudio-org/texstudio/tree/master/symbols-ng , the xml files.

**Comment by JonathanLevine657** [comment]
@sunderme ,

The attached [fa5.zip](https://github.com/texstudio-org/texstudio/files/6167057/fa5.zip) contains three files:
- symbols-ng format xml file
- txt file with list of all icons in package
- txt file with subset of icons which are trademarked (in case you're careful about IP issues)

I used the scripts in `symbols-ng/` and added a category in `SymbolWidget::setupData`, and it all works as expected.

**Comment by sunderme** [comment]
integrated

**Comment by sunderme** [comment]
thanks, integration is easier if pull-requests are used ...
