### ISSUE TITLE
After update texstudio stops working.

### ISSUE THREAD

**Issue by achimfrase** [texstudio-org/texstudio#1469]
### Environment
- TeXstudio: 3.0.4
- OS: Linux (Fedora Silverblue 33)
- TeX distribution: ? Flatpak?

### Expected behavior
When I Press the green compile button in UI of TeXstudio, the document should be translated into an pdf-file.

### Actual behavior
I get the following error:
Portal call failed: Failed to start command: Kindprozess »pdflatex« konnte nicht ausgeführt werden (Datei oder Verzeichnis nicht gefunden)
Prozess endete mit Fehler(n)

### How to reproduce
Just update to version 3.0.4 and start to compile a document.

I don't know why an update is able to break my TeXstudio.
I am very sad because I need TeXstudio on a Daily basis. What can I do now?

Thanks for your support!
Regards, Achim

**Comment by sunderme** [comment]
that sounds rather like a set-up problem.
steps for debugging:
1) does pdflatex work from command line
2) check "Help/check latex"
3) are the commands set correctly in txs ...

**Comment by achimfrase** [comment]
I don't think this is a setup problem.
We are talking about flatpak here. It is supposed to bring everything that is needed to run properly.

In the mean time I switched back to this commit that still works.
sudo flatpak update --commit=2cfe2168587c13b1d237188a1c9332b5f6250e92342a07f6ecc79ec321ba619d org.texstudio.TeXstudio

There is no pdflatex installed on my system. This should be (and was) part of the flatpak.
Or should be available as extension at least.

I hope that helps to clarify the situation.

Best Regards, Achim

**Comment by sunderme** [comment]
the flatpack is not provided by us. Please report at the packager.

**Comment by achimfrase** [comment]
Hey sunderme,

Oh sorry didn't know that this is not the correct place.

Sorry for taking your time.

Regards, Achim

**Comment by sunderme** [comment]
no problem

**Comment by rugk** [comment]
ref correct project: https://github.com/flathub/org.texstudio.TeXstudio/issues/55
