### ISSUE TITLE
Mac update issues

### ISSUE THREAD

**Issue by AditiM420** [texstudio-org/texstudio#1470]
Hi all,

Apologies if this has been already asked, but I have texstudio for Mac. It runs well and fine, but I just have one weird issue that I wonder if anyone else has. Whenever I open texstudio, and I am asked to update, I do so fine. However, this has happened a few times where I have updated the software, but when there is a new update available, it states that my current version of texstudio is very old, as in like v 2.12.8. I have definitely updated to at least version 3.0, but whenever I check the version, its 2.X.X. 

Does anyone else have this issue?  

Thanks for reading! 

Edit -  I do not know how github works sorry! So apologies if it is not in the right format. 
My mac is the latest version 11.2.1 if that helps.

**Comment by sunderme** [comment]
You are talking about OSX 11.2.1 ? 
Where do you check the version ? How do you update ?

**Comment by AditiM420** [comment]
Yes, OSX 11.2.1. 

I can check the tex studio version by clicking the "texstudio" on the far left of the notification bar (next to the apple). I do not know how to update as such, sometimes when I open texstudio, i will get a message that pops up saying a new update has been released. Then the link will take me to the texstudio page where i download the update/package. 

hope this explains more!

**Comment by sunderme** [comment]
Where do you get your copy of texstudio ? Homebrew ?
Basically OSX 11.2.1 is not supported with newer builds as they rely on newer version of Qt which does not support OSX11.2.1.
You could compile txs on wour own with an older Qt version.

**Comment by sunderme** [comment]
no further feedback
