### ISSUE TITLE
Cannot switch to Chinese interface

### ISSUE THREAD

**Issue by workhardyzh** [texstudio-org/texstudio#1473]
Texstudio 3.0.5 was released today.But I cannot switch to Chinese interface through options-configure texstudio,
language:default cannot be changed into zh_CN

**Comment by sunderme** [comment]
will be fixed soon.
Meanwhile you can change in texstudio.ini  the line `Interface\Language=zh_CN`

**Comment by sunderme** [comment]
you can also use a dev build (https://github.com/texstudio-org/texstudio/actions/runs/569087627)
