### ISSUE TITLE
How to make a command \mychapter recognized for folding and highlightning?

### ISSUE THREAD

**Issue by bernhard-kleine** [texstudio-org/texstudio#1474]
### Environment
TeXstudio 3.0.4 (git 3.0.4)
Using Qt Version 5.12.3, compiled with Qt 5.12.3 R

- OS: win10 64
- TeX distribution: texlive

### Description
I have within the preamble of the document the command 
`

    \DeclareDocumentCommand\mychapter{sO{#3}m}{%

	\IfBooleanTF{#1}%
	
		{\chapter*{#3}\renewcommand*{\chapterthumbformat}{#3}}%
		
		{\chapter[{#2}]{#3}\renewcommand*{\chapterthumbformat}
		
		{\thechapter\enskip#2}}%
		
		}
`
Now I would like to see mychapter working in the same way as chapter. How can one achieve this?

Regards Bernhard

**Comment by sunderme** [comment]
make a cwl file (see wiki/manual)
e.g.: \mychapter{titre%title}#L1
(excerpt from yathesis.cwl, %title notes the argument  which is used as title, #L1 means it is a chaper , #L2 for section , etc)

**Comment by sunderme** [comment]
was the brief info sufficient ?

**Comment by sunderme** [comment]
Assume solved
