### ISSUE TITLE
Path to TXS on Windows

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#1475]
### Environment
- TeXstudio: 3.0.5
- Qt: 5.15.2
- OS: Windows 10 (on VM from Linux Mageia 7)

### Description
[AFAICS](https://github.com/retorquere/zotero-better-bibtex/issues/1743), on Windows, the path to TXS isn't in the system path and has changed from `C:\Program Files (x86)\texstudio` to `C:\Program Files\texstudio`.

Can we rely on it?

**Comment by sunderme** [comment]
I guess so
