### ISSUE TITLE
Changing the name of a math environment

### ISSUE THREAD

**Issue by hair-splitter** [texstudio-org/texstudio#1480]
### Environment
- TeXstudio: 3.1.0 (git 3.1.0)
- Qt: Qt 5.15.2 R
- OS: Windows 10
- TeX distribution: TeX Live 2020

When I change the name of a math environment (for example, from "align" to "align*"), the highlighting of the text after the environment changes from black to green. 
If I reload the file in the TXS, then the highlighting is okay.
This bug isn't in TXS 3.0.4.

**Comment by sunderme** [comment]
can you show a screenshot ?

**Comment by hair-splitter** [comment]
Before
![before](https://user-images.githubusercontent.com/31892631/108394323-e3b2f280-7214-11eb-9820-b12412b46aa7.png)

After
![after](https://user-images.githubusercontent.com/31892631/108394382-f3323b80-7214-11eb-9eca-f9f0476b9d79.png)

**Comment by sunderme** [comment]
okay, I see it.

**Comment by sunderme** [comment]
you can try a fixed version from here: https://github.com/texstudio-org/texstudio/actions/runs/579080108
