### ISSUE TITLE
BUG: Syntax highlighting is disabled after saving .txt file as .tex

### ISSUE THREAD

**Issue by JonathanLevine657** [texstudio-org/texstudio#1481]
### Environment
- TeXstudio: 3.0.2
- Qt: 5.15.2
- OS: Linux 

### How to reproduce
1. FIle/new
2. Enter a short latex document
3. save as file.txt
4. save again under a new name as file.tex

### Expected behavior
Saving a file with .tex extention should always enable TeX syntax-highlighting

### Actual behavior
Saving an existing .txt file with a .tex extension does not enable syntax-highlighting.

**Comment by muzimuzhi** [comment]
A manual workaround without reopening the tex file: choose View -> Highlighting -> (La)TeX.

**Comment by JonathanLevine657** [comment]
I think it's ok for mode detection to fire once, and then have the user manage it. I was not previously aware that you could manually change the syntax mode.
