### ISSUE TITLE
Feature Request: Please Add Edit/Wrap Paragraph Command

### ISSUE THREAD

**Issue by JonathanLevine657** [texstudio-org/texstudio#1483]
### Describe the feature and the current behavior/state
This is a command commonly found in text editors, including vim/emacs/sublime:
![fill](https://user-images.githubusercontent.com/79280183/108413841-6b076280-7223-11eb-8f32-602b9daee120.gif)

Sometimes called "Wrap Paragraph", or sometimes "Fill Paragraph".
It takes a selection and breaks the text into lines at word boundaries, so
that lines do not exceed N characters (often N=80 for historical reasons
predating wide screens).

### Who will benefit with this feature?

Those of us used to it from using other editors. :)

**Comment by dbitouze** [comment]
[Already asked](https://github.com/texstudio-org/texstudio/issues/815#issuecomment-559567426), but not as an issue per se. I strongly support this feature!

**Comment by sunderme** [comment]
this begs to be solved by script ... so if someone wants to step forward ...

**Comment by JonathanLevine657** [comment]
> this begs to be solved by script ... so if someone wants to step forward ...

Challenge Accepted.

```js
%SCRIPT

var MAX_LINE_WIDTH = 80;

function wrap_paragraph(s, line_width) {
    // split into words
    var words=s.split(/\s+/); 
    var lines = [];

    // form words into lines as strings
    var length = 0;
    var i = 0;
    for (; i < words.length; i++) {
        if( length + (i) + words[i].length >= line_width ) { 
            lines.push(words.slice(0,i).join(" "));
            words = words.slice(i);
            i = -1;
            length = 0;
            continue;
        }
        length += words[i].length;
    }
    // ... and don't forget any partial last line
    if ( length > 0) {
        lines.push(words.slice(0,i).join(" "));
    }
 
    // form the resulting wrapped string
    var result=lines.join("\n");

	// To maintain whitespace to next block, restore any trailing newlines.
	var match_crlf_suffix = /[\r\n]+$/.exec(s);
	if (match_crlf_suffix !== null) {
		result += match_crlf_suffix[0];
	}

	return result;
}

// if no selection is active, select the current text block
if (!cursor.hasSelection()) {
	cursor.movePosition(0,cursorEnums.StartOfBlock);
	cursor.movePosition(0,cursorEnums.EndOfBlock,cursorEnums.KeepAnchor);	
} 

// Do it
var wrapped = wrap_paragraph(cursor.selectedText(), MAX_LINE_WIDTH);
editor.replaceSelectedText(wrapped);

```

**Comment by foreachthing** [comment]
Please add the opposite (un-paragraph) as well ;-) 
I don't like those 80-char-width-pars. 
Thanks!

**Comment by sunderme** [comment]
you can put a pull-request to texstudio-macro which allows "easy" download for all users

**Comment by benibela** [comment]
Isn't that just Idefix / Hard Line Break?

**Comment by sunderme** [comment]
indeed.
What exactly does "smart scoping" do ?

**Comment by benibela** [comment]
It chooses the paragraph or something. Without smart scoping, it only wraps the selected text or, if nothing is selected, the entire document

**Comment by dbitouze** [comment]
> you can put a pull-request to texstudio-macro which allows "easy" download for all users

BTW, isn't the purpose of the TXS-macro "Format TeX source" that may be found in Macros→Edit Macros...→Browse→automatedTextmanipulation→formatTeXsource.txsMacro? Its description is: Formats TeX source code by applying proper indentation, compressing multiple whitespace characters into one, etc.

**Comment by dbitouze** [comment]
> you can put a pull-request to texstudio-macro which allows "easy" download for all users

IMO, it is a really useful feature and should be directly available in TXS, not as macro.

**Comment by sunderme** [comment]
the wrapping is already in txs, only nobody is aware of it. That is a reason why I am hesitant simply to add more and more specialized functions, especially if the result is a matter of personal taste, here "proper indentation"

**Comment by JonathanLevine657** [comment]
> Isn't that just Idefix / Hard Line Break?

It totally is. I didn't know that command existed and apparently I'm not the only one. It's a shame about the mandatory click-through dialog, but it does do exactly this.

**Comment by JonathanLevine657** [comment]
@foreachthing, I updated the [script](https://github.com/texstudio-org/texstudio/wiki/Scripts#toggle-wrapfill-paragraph-to-maximum-line-length) to toggle between wrap/unwrap.

**Comment by benibela** [comment]
> It's a shame about the mandatory click-through dialog, but it does do exactly this.

That is what Repeat Hard Line Break is for

**Comment by JonathanLevine657** [comment]
> > It's a shame about the mandatory click-through dialog, but it does do exactly this.
> 
> That is what Repeat Hard Line Break is for

Thanks, good to know. 

Personally, everything about how this was implemented is confusing. But it's available out of the box, no question.

**Comment by foreachthing** [comment]
>I updated the [script](https://github.com/texstudio-org/texstudio/wiki/Scripts#toggle-wrapfill-paragraph-to-maximum-line-length) to toggle between wrap/unwrap.

@JonathanBrockhausen, this is AWESOME! 😀 Thank you so much!!
