### ISSUE TITLE
BUG: Configure lets you insert new menu items, but not remove them afterwards

### ISSUE THREAD

**Issue by JonathanLevine657** [texstudio-org/texstudio#1484]
### Environment
- TeXstudio: 3.0.2
- Qt: 5.12.2
- OS: Linux

### Expected behavior
If the program let's you add items via the GUI, you should be able to remove them again through the GUI as well.

### Actual behavior
Changed items are saved in a binary blob in texstudio.ini under the `changedLatexMenus` key, which effectively means once you add an entry, you can't delete it.

### How to reproduce
1. Click Menu Item Options/Configure
2. Toggle "Advanced options" to On state.
3. Navigate to "Menus", and Right click on any menu item on the list, for example any item under "&Math".
4. The context menu provides the action "Insert new Menu Item". But there is no way to delete an existing item if, for example, you change your mind later.

**Comment by sunderme** [comment]
fixed in 69491e6e4d42eed5a3a057129a5da27d5dcd45c0

**Comment by JonathanLevine657** [comment]
Thank you.
