### ISSUE TITLE
Feature Request: Please Add File/Revert To Saved

### ISSUE THREAD

**Issue by JonathanLevine657** [texstudio-org/texstudio#1486]
### Describe the feature and the current behavior/state
TexStudio has configuration options to monitor external changes to files, and auto-reload the
file when changes are detected. This is highly useful in some contexts, but in other contexts
I've had to disable it. If I then want to reload the file manually, there is no way to do it except
to manually close and reopen. It'd be useful to simply have a File/Revert action available.

It's also occasionally a problem, especially when developing external scripts that process the file (example:auto-renumber default equation labels, while preserving existing labels and references to them), that the auto-reload option does not create an undo entry but instead resets the edit history altogether.

**Comment by benibela** [comment]
It is File/Fifix/Revert To Saved

**Comment by JonathanLevine657** [comment]
Thanks. 

No one knows about these buried commands (including contributors, it seems). "FiFix" (like "Idefix") isn't a familiar term from any other software I've ever used. I'm not the only user who instinctively  ignores over it. The same thing happened with "Hard line fix". Users can't easily find these commands because they don't follow familiar UI patterns.
