### ISSUE TITLE
Icons in version 3.10 look especially blurry

### ISSUE THREAD

**Issue by alanrunner** [texstudio-org/texstudio#1487]
The icons on the toolbars in version 3.10 on Windows 10 look especially blurry.  The x's on the tabs for different document also look very blurry.  The popup image when TeXStudio starts up looks very pixelated.  Apparently, all of these icons and image files need to be replaced with higher resolution images.

**Comment by sunderme** [comment]
please try dev version: https://github.com/texstudio-org/texstudio/actions/runs/580963157

**Comment by sunderme** [comment]
duplicate #1491
