### ISSUE TITLE
BUG: Math Menu Macros Behave Strangely When Edited To Include Newline with %\\

### ISSUE THREAD

**Issue by JonathanLevine657** [texstudio-org/texstudio#1488]
### Environment
- TeXstudio: 3.0.2
- Qt: 5.12.5
- OS: Linux

### Expected behavior
Editable Math Menu Macros should function correctly when they include new lines.

### Actual behavior
After changing an entry to include a "%\\" macro, and involking it, the macro is expanded properly, but the cursor position doesn't behave as expected, so that a subsequent "Paste" or text entry, inserts the text in the wrong location.

### How to reproduce
I changed the definition of the "&Math/Display Math"  Entry to include a new line
where the contents go:
![Math](https://user-images.githubusercontent.com/79280183/108415636-b6227500-7225-11eb-8c2d-5478f9e2e649.png)
Because I prefer the following form in documents I create:
```tex
This is the equation \[
(1+x)(1-x)=1-x^2
\]
```

But, after changing the definition, invoking them item puts texstudio into an indeterminate
state, so that entered text is not inserted where indicated by the escape sequence "%|", but somewhere else.

### Additional Information

The bug is possibly related to the fact that `CursorPosition::setColumnNumber` is sometimes
called with with a negative number, here:
https://github.com/texstudio-org/texstudio/blob/64279dd604902b4a56382f5333d96f053e7f37f6/src/codesnippet.cpp#L557

Here's the implementation
https://github.com/texstudio-org/texstudio/blob/64279dd604902b4a56382f5333d96f053e7f37f6/src/cursorposition.h#L32

This negative number is stored, but later ends up in a call to Qt with an invalid value, which puts things into a weird state and results in the strange cursor behavior described. Checking and Ignoring negative value in calls to `setColumnNumber` cured the problem, but the proper fix would be the figure out where the offset calculations go wrong in the first place.

**Comment by sunderme** [comment]
what exactly did you put into the command. You can run the command as macro to test it first.

**Comment by JonathanLevine657** [comment]
```
\[%\%|%\\]%\
```
As shown in the screenshot above.

I do tend to use macros instead of editing the menus now, and have had no problems there. 

In the macro editor there's no problem directly creating a multi-line snippet, but in the Menu editor you're forced to use `%\\`, which turns out not to work properly in combination with `%|` from what I've seen. Something about the cursor position calculation is off.

**Comment by sunderme** [comment]
works as intended
which linux ?

**Comment by JonathanLevine657** [comment]
My account was flagged for no reason and it took 5 days to get Github to review, that's why my issues disappeared - Sorry, but it was out my control. 

I can't reproduce it with the latest git either. Either it was fixed since 3.0.2, or I'm missing something about what triggered it. 

If it recurs I'll reopen.
