### ISSUE TITLE
Issues with cursor placement after confirming autocompletion suggestion and undo-ing

### ISSUE THREAD

**Issue by thatlittleboy** [texstudio-org/texstudio#149]
### Environment
- TeXstudio: 2.12.9 (git 15179a9) 
- Qt: 5.8.0
- OS: Win 10 (64bit)
- TeX distribution: MikTeX

### Actual behavior
The Undo function (<kbd>Ctrl</kbd>+<kbd>Z</kbd>) after confirming an autocompletion suggestion jumps the cursor back to the start of the command instead of undoing the selection.

I show two examples here. Note that I am accepting the autocompletion suggestions (using <kbd>Enter</kbd>) after typing `\alpha` and `\be` respectively, then invoking Undo (which is when the cursor jumps) in the examples below.

<img src=https://user-images.githubusercontent.com/30731072/40267770-9f7e8c2e-5b5a-11e8-8307-483f78e4795f.gif width=500px>

I believe both example bugs have the same origins.

As an aside, I still experience a similar issue as #109 _sporadically_, in the sense that after pressing <kbd>Enter</kbd> after autocompletion suggestion, the next two or three characters are gobbled up (resulting in something similar to 2nd image in #109).
I haven't found a way to reproduce it consistently, nor capture it in a gif, but I suspect this autocompletion + undo/redo bug described in this post might have something to do with it.

### Expected behavior

For the cursor to stay on the front of the command, as is the case when I *don't* accept the autocompletion suggestion. See below for examples, where I use <kbd>Esc</kbd> to get rid of the autocompletion menu instead of accepting the suggestion.

<img src=https://user-images.githubusercontent.com/30731072/40267864-1144b738-5b5c-11e8-9176-720815eaed97.gif width=500px>

Hence, this issue only appears when autocompletion suggestion is selected.

### How to reproduce

```
\documentclass{article}

\begin{document}
	$  $
\end{document}
```

1. To reproduce the first case, type `\alpha`, <kbd>Enter</kbd>, then <kbd>Ctrl</kbd>+<kbd>Z</kbd>.

2. The second case: type `\be`, <kbd>Enter</kbd> to accept the first suggestion, then <kbd>Ctrl</kbd>+<kbd>Z</kbd>. (I had `\becquerel` because I had `siunitx.cwl` selected in the autocompletion settings from a previous test, but you should be able to reproduce with other similar commands.)

**Comment by thatlittleboy** [comment]
Any updates here? Is this reproducible on the dev's end, or not?

**Comment by timhoffm** [comment]
This is a bug. Likely somewhere in `CompleterInputBinding::insertCompleteWord`.

**Comment by thatlittleboy** [comment]
Ok, thanks @timhoffm for confirming.

**Comment by thatlittleboy** [comment]
@sunderme Thanks a lot for working on this!
