### ISSUE TITLE
BUG: Unexpected behavior in multicursor selection 

### ISSUE THREAD

**Issue by JonathanLevine657** [texstudio-org/texstudio#1490]
### Environment
- TeXstudio: 3.0.2
- Qt: 5.12.5
- OS: Linux

### Expected behavior
![multicursor3](https://user-images.githubusercontent.com/79280183/108431349-a95c4c00-723a-11eb-985d-7c676da9a3a5.gif)

When holding down CTRL and dragging the cursor, it should not be possible to have the selection begin at different columns on different rows, or to have a range selected only in
the first row.

One may think this is benign behavior, since if the user has steady hands and/or is sufficiently
careful this isn't an issue. In practice, I often have to try to nail the selection more than once before I succeed.

### Actual behavior

![multicursor](https://user-images.githubusercontent.com/79280183/108430632-8f6e3980-7239-11eb-90bd-f9a65135e6db.gif)

### Additional Info
<strike>Other editors commonly allow the manual addition of cursors at specific locations...</strike>

**Update**: as pointed out below: you can select individual locations with Ctrl+Alt.

**Comment by sunderme** [comment]
in txs, the intention is to set mirror cursors which allow entering text on several lines simultaneously. It is not for selecting different stuff.

**Comment by JonathanLevine657** [comment]
Editing multiple lines simultaneously is the primary use of multicursors, for me.

The fact that you can hit "Ctrl+Shift+Left/Right" to select the word at the cursor even if they are of differing lengths is what makes this such a powerful feature. I hope you'll reconsider that decision. 

For reference, all implementation of multicursors I know of support this, which includes at least sublime and vim.  

Regardless, the difficulty of activating the multicursors exactly vertically  without selecting some text on the initial line b y mistake because my hand shifted just a little half an inch in the wrong dimension is still valid usability bug IMO.

**Comment by benibela** [comment]
The keys are Ctrl+Shift for selecting and and Ctrl+Alt to place them anywhere

**Comment by JonathanLevine657** [comment]
Thanks!

In that case what is Ctrl by itself?

**Comment by JonathanLevine657** [comment]
I'm pretty sure Ctrl activating multi-cursors is unintentional:

This  (mouseMoveEvent) if:
https://github.com/texstudio-org/texstudio/blob/c3bdfcbb9369e23062a2439e1a7d1f82a21a9cd8/src/qcodeedit/lib/qeditor.cpp#L3698-L3702

should have the same logic check as this (mousePressEvent):
https://github.com/texstudio-org/texstudio/blob/a670d4636f2c1575fa480824377ef28a05064239/src/qcodeedit/lib/qeditor.cpp#L3772-L3780

**Comment by JonathanLevine657** [comment]
Aside from the <kbd>ctrl</kbd> issue, I figured out why this behavior is so strange to me.
In sublime, when you activate drag-select and click, the selection starts where you click.
But in TXS it starts where the cursor was, and the selection extens to where you clicked instead. and it's the same in VSCode.

I prefer the former but that's just a personal preference, not a bug.

**Comment by sunderme** [comment]
I have no intention to change the behavior

**Comment by JonathanLevine657** [comment]
@sunderme , what's the intended difference between using `ctrl` vs. `ctrl+shift`? if none, why have both?
