### ISSUE TITLE
Icons are very blurry, scaling of everything is completely off

### ISSUE THREAD

**Issue by SebsterTeX** [texstudio-org/texstudio#1491]
- TeXstudio: 3.1.0
- OS: Windows 10
- TeX distribution: TeXlive

Wanted to install new TeXstudio Version 3.0.1. deinstalled the pervious version and then installed the newest stable version. Installation was issue free. However now everything is scaled completely wrong. The option menues are huge and are completely out of sync with the rest. The icons are very blurry and are hardly legible. I have tried GUI scaling and changing the font.I have never had this problem in the past. 
![icons](https://user-images.githubusercontent.com/79304919/108477276-4b0f8780-7293-11eb-8feb-5f6762c45a04.JPG)
![menu](https://user-images.githubusercontent.com/79304919/108477741-e99be880-7293-11eb-8cfa-b0be3dc02ce2.JPG)

**Comment by sunderme** [comment]
you can try dev build: https://github.com/texstudio-org/texstudio/actions/runs/580963157
