### ISSUE TITLE
BUG In showing a pdf image

### ISSUE THREAD

**Issue by majidyazdani-py** [texstudio-org/texstudio#1492]
### Environment
- TeXstudio:  3.1.0
- Qt:  When textstudio builds a preview can not correctly load the pdf images, the formula on inserted pdf on the main file will not be loaded in the software preview screen; although when you open the created pdf with other softwares you see no problem and textstudio has already build the whole pdf correctly!
- OS:  Mac big sur

**Comment by sunderme** [comment]
provide a test case (i.e. a reduced tex file and the pdf)

**Comment by sunderme** [comment]
and please provide a screen shot to illustrate the issue.

**Comment by sunderme** [comment]
Insufficient info, no feedback
