### ISSUE TITLE
Since updating to 3.1.0, TeXstudio intermittantly crashes upon saving

### ISSUE THREAD

**Issue by aetb** [texstudio-org/texstudio#1493]
### Environment
- TeXstudio: 3.1.0
- Qt: 5.15.2
- OS: Windows 10
- TeX distribution: miktek

### Expected behavior
I should be able to save changes or build while the program remains open.

### Actual behavior
I save and the program immediately closes. Thankfully, the save persists. However, if I have changes on multiple files, only one file will maintain its changes. This also occurs when trying to build with changes present. This behavior occurs on almost every save (if changes are present). I have reproduced this issue on two computers now.

### How to reproduce
Load a large, multi-file project, edit a page, and save.

**Comment by sunderme** [comment]
I have just fixed a crash, not directly affecting saving.
Can you check, whether it helps in your case as well ?
https://github.com/texstudio-org/texstudio/actions/runs/581933953

**Comment by sunderme** [comment]
assume fixed

**Comment by aetb** [comment]
Yes, this hasn't occurred since the latest update.
