### ISSUE TITLE
Crash to many input-files

### ISSUE THREAD

**Issue by relaxony** [texstudio-org/texstudio#1497]
### Environment
- TeXstudio: 3.10
- Qt: nA
- OS: Win 10 x64
- TeX distribution: miktex

### Expected behavior
Stability throughout, when opening \input{file}- files

### Actual behavior
If the programme runs too long (5min) and input files are opened by clicking in the navigation bar, the programme crashes. Unfortunately, no security backup is created, so that unsaved contents are deleted.

### How to reproduce
Create TeX-File with many \input{file}-files and try to open it, after a several time of running this program.

**Comment by sunderme** [comment]
can you try the latest dev build: https://github.com/texstudio-org/texstudio/actions/runs/586725149

**Comment by riccardo-degasperi** [comment]
I was having a similar issue. My editor (3.1.0 Win 10 x64, Miktex) crashed when my coauthors were modifying some of the input files. The latest dev build seems to solve this. Thanks!

**Comment by relaxony** [comment]
It seems to be fixed with the suggested version. Thank you so much!

**Comment by sunderme** [comment]
do you see crashes again ? if yes, i need a test case .

**Comment by relaxony** [comment]
Crashes no, but a bug in the dev build. I think it's easier to reopen the thread than to open a new thread because of the dev version. But if you want me to create another thread for the dev build, I'll be happy to do that.

In the mathematical environment, if I want to superscript something, i.e. work with the "^" sign, in the previous versions you could enter the number or symbol directly, but now you have to type in a space, otherwise the programme jumps one character forward.

For example, if I want to enter 4^2, I type 4 and if I use the circumflex character, I have to type a space before I type the 2. If I don't do that, it just says '4^' and the input location is between the 4 and the circumflex character.

**Comment by sunderme** [comment]
please open new  thread with corresponding title. Otherwise it is hard to find issues later

**Comment by relaxony** [comment]
np 👍
