### ISSUE TITLE
Question: Cannot Build & View or Compile

### ISSUE THREAD

**Issue by TechnoDino** [texstudio-org/texstudio#15]
This is a newbie question. I cannot compile or build & view with any of the default pdf programs.  The message is: "Cannot start....".  Using version 2.12.6 on Fedora 27 with Texlive  (a complete install).  Typing "latex" on the terminal shows that pdflatex is installed. 

Can you help?  I am reasonably proficient in using the terminal but need "TexStudio for Dummies" level instructions.
Thanks so much.
John

**Comment by timhoffm** [comment]
Check `Help -> Check Latex Installation`:

- does `which pdflatex` show a result?
- is the latex bin folder on the PATH?

Note: Linux can have different PATH settings for consoles and for GUI applications started via menu.

**Comment by TechnoDino** [comment]
Tim: sorry to be so slow to respond. One hardware or other goofy Fedora error evedyday. Finally figured out how to add to PATH & now working.

Thanks for getting back to me.
John
