### ISSUE TITLE
MathTime Pro 2 commands not recognized

### ISSUE THREAD

**Issue by madsmh** [texstudio-org/texstudio#150]
### Expected behavior
That commands such as \PARENS{} and and \upPhi from the MathTime Pro2 package is recognized by the TexStudio auto-complete feature.

### Actual behavior
Any commands specific to MathTime Pro 2 are not recognized.

### How to reproduce
In a math encironment start to write any MathTime Pro 2 specific command, and the auto-completion fails to suggest a completion.

**Comment by thatlittleboy** [comment]
Auto-completion is handled by cwl files in TeXstudio. If there are commands from MathTime Pro 2 that are not recognized, just write your own. See [the wiki](https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions#why-does-a-command-not-show-up-in-the-completion) or questions on TeX stackexchange ([this](https://tex.stackexchange.com/a/364581/117534) or [this](https://tex.stackexchange.com/a/85220/117534)) for more information.

**Comment by madsmh** [comment]
There actually is a cwl file included with TeXStudio for MathTime Pro 2 (mtpro2.cwl), and activating it does not seem to have any effect.

**Comment by thatlittleboy** [comment]
It's in the ./completion/autogenerated folder right? Those are usually classified as `#S` so they don't show up in the autocompleter.

**Comment by madsmh** [comment]
Thanks, I have made a cwl file, that may be of use for others.

[mtpro2.cwl.txt](https://github.com/texstudio-org/texstudio/files/2024122/mtpro2.cwl.txt)

**Comment by sunderme** [comment]
for the cwl to be included, it should be a little refined.
E.g. \mathscr{arg1} is enough, no need for an entry without argument.
Furthermore commands which never come up in texts should be left out, e.g \LMP1+mtt etc.

**Comment by sunderme** [comment]
and siomething like 
`\Gamma
\Gamma#m`
does not make sense either. the '#m' is a flag to show that the command is only valid in math-env. If you add it a second time to be valid everywhere is not helpful ...

**Comment by sunderme** [comment]
cwl is not sufficiently refined.
Since not many can use it anyway, I don‘t see it necessary to invest time here.
