### ISSUE TITLE
Texstudio causing maximum CPU usage

### ISSUE THREAD

**Issue by galaxyhaxz** [texstudio-org/texstudio#1500]
### Environment
- TeXstudio: 3.1.1 
- Qt: 5.15.2
- OS: Windows 7
- TeX distribution: miktex

### Expected behavior
Program should run with idle CPU usage when not doing any tasks.

### Actual behavior
Program is constantly starting and stopping `mpm.exe` (Mikitex package manager) which is always using 100% CPU.

### How to reproduce
Start Texstudio, open task manager and watch CPU usage fly.

**Comment by galaxyhaxz** [comment]
Just want to leave a shout out to the Texstudio developers. I'm new and just learning LaTeX and among all the editors I've tried so far this one is by far the best.

Not sure why it's constantly pinging the Mikitex package manager which is causing a massive CPU spike. Perhaps it is trying to check for updates or perform a task which could be disabled in options?

Cheers, Andi

**Comment by sunderme** [comment]
txs checks for the packages installed to provide an accurate list when completing \usepackage. The information is cached, so it should stop after a while.

**Comment by galaxyhaxz** [comment]
Yes it seems you are correct. I let the program idle for a few minutes and eventually it stopped. Now it's using 0-1% CPU :)
