### ISSUE TITLE
Mathematical environment, shift input point when superscripting

### ISSUE THREAD

**Issue by relaxony** [texstudio-org/texstudio#1502]
### Environment
- TeXstudio: 3.1.1 (git )
- Qt: 5.15.2, compiled 5.15.2 R
- OS: Win 10
- TeX distribution: miktex

### Expected behavior
In the mathematical environment, if you want to superscript something, you type character^character and it is transferred directly in the editor like that.

### Actual behavior
If you want to enter character1^character2, character2 is not written, the input field moves back one place between character1 and ^. To get around this problem, you have to press the space bar once before typing the "^" character.

### How to reproduce
Try to insert a subscripted character in the mathematical environment.

**Comment by sunderme** [comment]
works as expected.
Be aware that ^ is an accent in some language and windows combines it with the following character if possible, e.g. ^+a -> â
Hence ^ does not appear when typed but after the next character can't be combined.

**Comment by relaxony** [comment]
I know that in some languages it is an accent. But not in German and so far it has worked as described: If I wanted to put 4^2, I could put it like that without any problems. With the dev-build, I have to press the space bar after the accent character, which I never had to do with the previous versions. If I don't do this, the input field jumps between 4 and the accent character back and that was definitely never the case in the previous versions. Especially because I haven't seen 2 with an accent mark above it in any language.

**Comment by sunderme** [comment]
it works fine here on linux and windows
please update to release 3.1.1

**Comment by relaxony** [comment]
Check! Right now, with the release version it works! Thanks!
