### ISSUE TITLE
Unable to notice different files that have the same name

### ISSUE THREAD

**Issue by unalfaruk** [texstudio-org/texstudio#1504]
### Environment
- TeXstudio: 3.1.1
- Qt: 5.15.2
- OS: Windows 10
- TeX distribution: XeLatex

### Expected behavior
TeXstudio should open the file that I select from the side panel, not another file with the same name of the file I want to open.

### Actual behavior
I have duplicated an existing project(document) contains "./TeX_files/chapter01..05". Now both are listed on the side panel (Structure). I am editing the new one, as root document.

When I try to open "./TeX_files/chapterX" from the old document, TeXstduio opens "./TeX_files/chapterX" from the new one which set as root.

![texstudio_problem](https://user-images.githubusercontent.com/17685751/109045356-84f1eb00-76e4-11eb-957e-35fa28e0b2d7.png)

### How to reproduce
Duplicate a multi-files project, try to open sub files from both.

**Comment by sunderme** [comment]
if you set the first "main.tex" as explicit root, txs takes its base directory as starting point to find the included file.
You can use "detect automatically root document" which works fine. That would txs to check what the root file actually is and open the intended file.
