### ISSUE TITLE
Incoherent root document detection with symbolic links

### ISSUE THREAD

**Issue by melsophos** [texstudio-org/texstudio#1505]
In some cases, Texstudio is not handling properly the root document and included files when the path of the current project contains a symbolic link. I think that the reason is the following: the path to the root document is not converted to the real path, however, the included files opened through the editor use the real path. As a consequence, Texstudio does not understand that both files are part of the same project and thus fails to compile and autocomplete references and citations.

### Environment

- TeXstudio: 3.1.1 (but happened in previous versions)
- Qt: 5.15.2
- OS: Linux (Fedora 33, Ubuntu 20.10)
- TeX distribution: texlive

### Expected behavior

Texstudio should be able to compile and autocomplete even if the path to the Latex file contains a symbolic link and included files are opened through Texstudio.

### Actual behavior

Root document is not recognized. This leads to the following problems:
- compilation fails
- unable to autocomplete references and citations (`\cite{}`, `\ref{}`, etc).

Setting the root explicitly with a magic command and relative path allows compiling, but not to autocomplete.

### How to reproduce

What is strange is that I could not reproduce the behavior with a minimal working example in my home, so I am detailing my exact setup for one example (note that I have problems with most of my papers, so it's not an isolated problem).

Consider the following path to a root document (I am shortening the names with respect to the screenshot for simplicity):
`/mnt/data/Projets/#Majorana fermions and 2d quantum gravity/notes-harold/notes_2d_gravity_majorana_fermion.tex`

I have created a symbolic link:
`~/Projets/ → /mnt/data/Projets/`
such that I can open the root document through:
`~/Projets/#Majorana fermions and 2d quantum gravity/notes-harold/notes_2d_gravity_majorana_fermion.tex`
This root document contains a biblatex file added with `\addbibresource`.

If I do this, then Texstudio sees correctly that `notes_2d_gravity_majorana_fermion.tex` is located in `~/Projets/#Majorana fermions and 2d quantum gravity/notes-harold/`. Compilation and completion of bibtex cite and label references work well.

See the path at the top of the window:
<img src="https://user-images.githubusercontent.com/168402/109083575-73b9d600-7706-11eb-8d78-84143503c1b6.png" width="500">

However, if I open the included file `sections/introduction.tex` through Texstudio, it displays the path: `/mnt/data/Projets/#Majorana fermions and 2d quantum gravity/notes-harold/notes_2d_gravity_majorana_fermion.tex`. In that case, compilation fails when I have the focus on `intoduction.tex`. Similarly, completion of bibtex cite and label references fail.

See the path at the top of the window and empty completion window:
<img src="https://user-images.githubusercontent.com/168402/109083662-9e0b9380-7706-11eb-8654-7e8bc93e0133.png" width="500">

If I add the following magic command at the top of `introduction.tex`
```
% !TeX root = ../notes_2d_gravity_majorana_fermion.tex
```
then compilation works but still not autocompletion.

Adding this magic command through the menu inserts:
```
% !TeX root = ../../../../../../../../../../Projets/Recherche/Papiers/2d gravity/#Majorana fermions and 2d quantum gravity/notes-harold/notes_2d_gravity_majorana_fermion.tex
```
in which case compilation and completion work.

Both compilation and completion work if:
- the included file is manually opened from the file explorer from the path _with_ symbolic link
- the root document is opened from the path without symbolic link (in that case, the included files have the same path when opened through Texstudio)
- using the option `Set current document as explicit root`

**Comment by sunderme** [comment]
please provide a test case (as tar)

**Comment by melsophos** [comment]
I finally manage to find how to reproduce the bug with a MWE. The problem appears when there are two nested symbolic links.

### How to reproduce

1. Create the following folders and links:
    ```bash
    mkdir -p ~/Folder1/Folder2/paper
    ln -s ~/Folder1 ~/Link1
    ln -s ~/Link1/Folder2 ~/Link2
    ```
2. In `paper/`, create a document `document.tex` which includes another tex file `sections/section.tex`. For example : [paper.tar.gz](https://github.com/texstudio-org/texstudio/files/6051213/paper.tar.gz)
3. Open `~/Link2/paper/document.tex` from the file explorer, then open `section.tex` from Texstudio.
4. Compilation and completion fail.

At point 3, the paths to the files displayed in the top bar are:
```
~/Link2/paper/document.tex
~/Link1/Folder2/paper/sections/section.tex
```
If instead you open `~/Link1/Folder2/paper/document.tex` from the file explorer and then `section.tex` from Texstudio, compilation and completion work and the paths in the top bar are:
```
~/Link1/Folder2/paper/document.tex
~/Link1/Folder2/paper/sections/section.tex
```
Obviously, it also works if you open `~/Folder1/Folder2/paper/document.tex`.

**Comment by melsophos** [comment]
In case someone else gets the same problem, here is a temporary fix:
```bash
cp /usr/share/applications/texstudio.desktop ~/.local/share/applications/
sed "s/Exec=texstudio %F/Exec=bash -c 'texstudio \"\$(realpath \"\$1\")\"' \$F/" ~/.local/share/applications/texstudio.desktop -i
```
