### ISSUE TITLE
Logfile not showing

### ISSUE THREAD

**Issue by adlag** [texstudio-org/texstudio#1506]
I am using Windows 10 fully patched. In Texstudio 3.1.1 the following bug is present:
When typesetting with or without errors the Log tab shows an empty logfile, whereas checking the file system shows that the logfile is present.

![textstudio](https://user-images.githubusercontent.com/58976146/109138957-3df30c80-775b-11eb-9cd3-7d745295a08e.png)

**Comment by muzimuzhi** [comment]
From the screenshot, you were on "Issues" tab. Try the "Log File" tab at the left of the "Issues"?

**Comment by adlag** [comment]
Dear Muzimuzhi,
 �
see another screenshot, attached.
 �
Ad
 �

**Comment by sunderme** [comment]
@adlag there are no screenshots in the last comment

**Comment by sunderme** [comment]
and I don't see an issue with log here (win & linux)

**Comment by adlag** [comment]
I sent an email and did not reply here. That is what I am doing now.
So I will drop the new screenshot here.
I also did not have any problems until I installed 3.1.0
Restarting Windows did not help. 

![textstudio2](https://user-images.githubusercontent.com/58976146/109194611-e45e0280-7799-11eb-802c-eeddebe258ff.png)

**Comment by adlag** [comment]
I solved it. Uninstalled TexStudio. Removed all the entries of TexStudio in \AppData\Roaming\ 
Reinstalled TexStudio.. See screenshot.
Thanks a lot.

![textstudio3](https://user-images.githubusercontent.com/58976146/109203838-eda09c80-77a4-11eb-9e77-baa916f609f8.png)
