### ISSUE TITLE
Assigning shortcut to "next placeholder" does nothing

### ISSUE THREAD

**Issue by zhou31415** [texstudio-org/texstudio#1507]
### Environment
- TeXstudio: 3.1.1
- Qt: 5.15.2
- OS: macOS Big Sur 11.2.1
- TeX distribution: pdfTex 3.14159265-2.6-1.40.16 (TeX Live 2015)

### Expected behavior
Under Preferences>Shorctcut>Editor>Basic Key Mapping, I changed Current Shortcut for the command "next placeholder" to Option+Cmd+right arrow, and disabled that shortcut for View>Focus viewer. 

When I type \frac{}{} and the cursor is in the first placeholder, and I press the shortcut I assigned, I expect to move to the second placeholder. 

### Actual behavior
Nothing happens

### How to reproduce
Assign the shortcut for "next placeholder" to Option+Cmd+Rightarrow, disable that same shortcut for View>Focus viewer, then type \frac{}{} in the document and use the shortcut.

**Comment by sunderme** [comment]
removal of menu shortcuts and setting of editor shortcuts needs to be done in two steps (for now).
1) remove the shortcut View->Focus..
2) restart txs
3) set editor short cut

**Comment by zhou31415** [comment]
Ok, I tried restarting, and even assigning a complicated shortcut to the previous/next placeholder that is unlikely to be already used (shift+command+option+left/right), but these shortcuts don't do anything. Here is a picture of how I assigned the shortcuts. 

<img width="1113" alt="Screen Shot 2021-02-26 at 11 50 44 AM" src="https://user-images.githubusercontent.com/79667814/109348538-81b44780-7829-11eb-9ba2-54d485fdda5e.png">

If I assign these same shortcuts to "next placeholder or one word right" and "previous placeholder or one word left" respectively, these shortcuts always cause the cursor to move one word right/left (i.e. they ignore the placeholders entirely). So the key combinations work on my computer, it's just TeXstudio cannot detect existence of placeholders? I'm using \frac{}{} to test.

**Comment by sunderme** [comment]
hmmm, what exactly do you do to generate the placeholder. They are only placed when you use completion/menu commands and it should look like this.
<img width="109" alt="Bildschirmfoto vom 2021-02-27 08-47-07" src="https://user-images.githubusercontent.com/14033169/109381104-8edc3f80-78d8-11eb-9bc1-9365ac97a249.png">

**Comment by zhou31415** [comment]
Ok, I fixed it, in the Configurations, under Completion, I had to check "Insert Arguments" and "Arguments as Placeholders," which I didn't check before. Thank you for your help.
