### ISSUE TITLE
Shortcut to move to next paragraph

### ISSUE THREAD

**Issue by zhou31415** [texstudio-org/texstudio#1508]
### Describe the feature and the current behavior/state
Currently there doesn't seem to be a shortcut in texstudio that allows you to move the text cursor down 1 paragraph at a time. I'm looking for an available shortcut to allow one to do this. When I mean paragraph, I mean one line number of math/text. 

### Who will benefit with this feature?
Anyone that wants to edit long documents efficiently using a keyboard

### Any Other info
On a Mac, Option+up/down arrow is supposed to accomplish this. In TeXstudio, these commands are first assigned to moving cursor to end/begining of line. Once I remove those shortcuts, then the Option+up/down arrows just scroll the document (i.e. move the slider bar, not the cursor) even though they don't seem to be assigned to any command.

**Comment by foreachthing** [comment]
Maybe you can adapt something like this to fit your needs: https://github.com/texstudio-org/texstudio/wiki/Scripts#select-the-current-section

**Comment by DvP17** [comment]
In the meantime you might want to accomplish this with the two macros. And assign them to the desired shortcut.

`%SCRIPT
cursor.movePosition(1, cursorEnums.NextBlock);	

%SCRIPT
cursor.movePosition(1, cursorEnums.PreviousBlock);`	

(A little bit slow, though.)

**Comment by LaifsV1** [comment]
> In the meantime you might want to accomplish this with the two macros. And assign them to the desired shortcut.
> 
> ```
> %SCRIPT
> cursor.movePosition(1, cursorEnums.NextBlock);	
> 
> %SCRIPT
> cursor.movePosition(1, cursorEnums.PreviousBlock);
> ```
> 
> (A little bit slow, though.)

Tried this, "a little bit" is an understatement. It takes over a second. Is this shortcut still not in? Are there any alternatives?

**Comment by sunderme** [comment]
implemented, no short cut preassigned. The shortcuts needs to be set in `config/shortcuts/editor/basic key mapping`

The operations are `Move Cursor to Next Block`and `Cursor to Previous Block`

**Comment by LaifsV1** [comment]
I'm trying the 4.8.1 app image. I do not see the `Move Cursor to Next Block` option under `basic key mapping`. Was this supposed to be added on 4.8.1?

**Comment by foreachthing** [comment]
Grab the dev-build: https://github.com/texstudio-org/texstudio/actions/runs/9429711394
Or, the latest from here: https://github.com/texstudio-org/texstudio/actions/workflows/cd.yml

**Comment by LaifsV1** [comment]
On Ubuntu 24.04 Desktop, the shortcut no longer appears to be working when mapped to CTRL+DOWN and CTRL+UP. I can map it to, say, ALT+UP and ALT+DOWN, but not CTRL. Has this been observed before or is it just my installation?

I tested the following AppImage: `texstudio-linux-4.8.2-202406081520-git_5698236fe-x86_64.AppImage`
version: `TeXstudio 4.8.2 (git 4.8.1-4-g5698236fe)`

**Comment by sunderme** [comment]
works here, but shortcuts edit/go to/next mark .../previous mark are not automatically replaced. You have to remove those shortcuts.

**Comment by LaifsV1** [comment]
thanks! the next mark and previous mark shortcuts were indeed the issue!
