### ISSUE TITLE
Extended Search ignores never-opened files

### ISSUE THREAD

**Issue by i3v** [texstudio-org/texstudio#151]
### Environment
- TeXstudio: 2.12.8
- Qt: 5.8.0 
- OS: Windows 10
- TeX distribution: texlive2018

### How to reproduce
1. Create 2 files (in the same folder):

   - root.tex:
   ```
   \documentclass{memoir}
   \input{another.tex}
   \begin{document}
   	% xyz
   \end{document}
   ```
   - another.tex
   ```
   % xyz
   ```

2. Open the "root.tex", close other files.
3. Restart TexStudio
4. Make sure only "root.tex" is open.
5. Make sure you see "another.tex" in "Structure" window
6. Perform "Extended Search" (Project-type) for "xyz"

### Expected behavior
Both results should be visible (one from "root.tex" and one from "another.tex")

### Actual behavior
Only result from "root.tex" is visible

7. Open "another.tex"
8. Close it
9. Repeat the search - now both results are visible.

**Comment by thatlittleboy** [comment]
Is `Configure TeXstudio -> Editor -> Automatically load included files` option checked? (need to enable `Show advanced options` on the bottom left corner)

**Comment by i3v** [comment]
@thatlittleboy , thanks! After I've checked it, it now works as expected.
