### ISSUE TITLE
BUG: Entering and Exiting macro editor erases shortcut for "Edit Macros".

### ISSUE THREAD

**Issue by JonathanLevine657** [texstudio-org/texstudio#1511]
### Environment
- TeXstudio: 3.1.1
- Qt: 5.12.5
  
### How to reproduce
1. Assign a shortcut to Macros/Edit Macros from options/configure
2. Activate the macro editor. Immediately exit by clicking "OK" 
3. The shortcut previously assigned to edit macros is now gone.

**Comment by JonathanLevine657** [comment]
```diff
diff --git a/src/configmanager.cpp b/src/configmanager.cpp
index 6b2b039e..a33b99a2 100644
--- a/src/configmanager.cpp
+++ b/src/configmanager.cpp
@@ -1277,7 +1277,8 @@ QSettings *ConfigManager::saveSettings(const QString &saveName)
        config->beginWriteArray("keysetting");
        for (int i = 0; i < managedMenuNewShortcuts.size(); ++i) {
                config->setArrayIndex(i);
-        if(managedMenuNewShortcuts[i].first.startsWith("main/macros/")){
+        if(managedMenuNewShortcuts[i].first.startsWith("main/macros/")
+            && managedMenuNewShortcuts[i].first != "main/macros/manage~0"){
             continue;
         }
                config->setValue("id", managedMenuNewShortcuts[i].first);
@@ -2051,7 +2052,14 @@ void ConfigManager::updateUserMacroMenu()
         }
     }
     recreatedMenu->addSeparator();
-    newOrLostOldManagedAction(recreatedMenu, "manage", QCoreApplication::translate("Texstudio", "Edit &Macros..."), SLOT(editMacros()));
+
+    QAction *old = menuParent->findChild<QAction *>(recreatedMenu->objectName() + "/" + "manage");
+    QList<QKeySequence> shortcuts;
+    if(old) {
+        shortcuts = old->shortcuts();
+    }
+    newOrLostOldManagedAction(recreatedMenu, "manage", QCoreApplication::translate("Texstudio", "Edit &Macros..."), SLOT(editMacros()), shortcuts);
+
     // update quote replacement
        const int autoQuoteCount = 10;
        if (replaceQuotes >= 1 && replaceQuotes < autoQuoteCount) {
diff --git a/src/texstudio.cpp b/src/texstudio.cpp
index 41f371db..7085131f 100644
--- a/src/texstudio.cpp
+++ b/src/texstudio.cpp
@@ -1210,7 +1210,8 @@ void Texstudio::setupMenus()
        act->trigger(); // initialize menu for specified type
 
        //  User
-        newManagedMenu("main/macros", tr("Ma&cros"));
+        menu = newManagedMenu("main/macros", tr("Ma&cros"));
+        newManagedAction(menu, "manage", QCoreApplication::translate("Texstudio", "Edit &Macros..."), SLOT(editMacros()));
        updateUserMacros();
        scriptengine::macros = &configManager.completerConfig->userMacros;
 

```

**Comment by sunderme** [comment]
you care to comment what I am looking at ?

**Comment by JonathanLevine657** [comment]
Sure. 

**Problem 1**: When a shortcut is assigned to "Edit macros" it isn't persisted as part of the settings, so a restart of TXS forgets the shortcut.

**Solution**: Convert the "Edit Macros" action into a `managedAction` in order for the persistence code to pick it up. Also, added an exception to the code in `saveSettings` which by ignores everything in the macro menu, because it expects these items to be recreated (with their shortcuts) from the macro JSON files. But the "Edit Macros" menu item is not a macro and so _should_ be persisted by `saveSettings`.

**Problem 2**: Assigning a shortcut to "Edit macros", then opening the macro editor, and finally clicking OK, causes the shortcut to be lost.

**Solution**: The root cause is that when the dialog returns with `accept()`, the entire menu is rebuilt. Specifically, the "Edit Macros" action/menu item is recreated via a call to `newOrLostOldManagedAction`. This call does take an optional shortcut, but the code which currently calls it for "Edit macros" doesn't pass in the existing shortcut to the function, so the recreated item always has its shortcut reset to an empty key sequence. To fix this, we stimply retrieve and pass in any existing shortcut for "Edit Macros".
