### ISSUE TITLE
TXS3.1.1 crash (bug in global TOC)

### ISSUE THREAD

**Issue by hair-splitter** [texstudio-org/texstudio#1512]
### Environment
- TeXstudio: TeXstudio 3.1.1 (git 3.1.1)
- Qt: 5.15.2 R
- OS: Windows 10
- TeX distribution: TeX Live 2020

### How to reproduce
Push the right mouse button on the Side Panel / TOC (on the white area) and the TXS crash without saving the document.

**Comment by sunderme** [comment]
more context.
I don't see a crash just by changing to globalTOC.

**Comment by hair-splitter** [comment]
https://user-images.githubusercontent.com/31892631/109420576-96344380-79d3-11eb-8497-05bf93e0d9b6.mp4

... and TXS crash.

**Comment by sunderme** [comment]
got it, fixed, thanks

**Comment by sunderme** [comment]
by the way, what program did you use to generate the screen cast ?

**Comment by hair-splitter** [comment]
[FlashBack Express Recorder](https://www.flashbackrecorder.com/)
