### ISSUE TITLE
The central bar should be narrow

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#1514]
### Environment
- TeXstudio: 3.1.1 (git n/a)
- Qt: 5.15.2
- OS: Linux Mageia 8
-
### Expected behavior
A narrow central bar.

### Actual behavior
The central bar is wide:
![image](https://user-images.githubusercontent.com/1032633/109426347-93dee300-79ed-11eb-9d36-0b73ccfdbf7c.png)

**Comment by sunderme** [comment]
very strange
did you change something in options/toolbar/central ?
Looks like the icons are not used and the text is used as fallback.
Works fine here. 
So, make clean ???

**Comment by dbitouze** [comment]
> So, make clean ???

Indeed: no problem after `make clean`. Thanks!
