### ISSUE TITLE
pdflatex command runs fine, biber and user commands do not run - why?

### ISSUE THREAD

**Issue by brixxx** [texstudio-org/texstudio#1520]
### Environment
- TeXstudio: 3.1.1.
- Qt: 5.15.2
- OS: KDE neon 5.21.1
- TeX distribution: texlive 2020

### Expected behavior
The build command for Biber "**biber %.bcf**" should work.
The user command "**R --version**" should return the version of R which is in /usr/bin. (Command for testing)

### Actual behavior
Executing "**biber %.bcf**" using the bibliography command leads to: "Error: Could not start the command: biber "test".bcf"
The user command "**R --version**" leads to: "Error: Could not start the command: R --version"
However, the command configured as "**pdflatex -synctex=1 -src -interaction=nonstopmode %.tex**" works fine!
The user command "**echo $PATH**" returns: 
```
Process started: echo /usr/bin:/app/bin:/app/texlive/bin:/app/texlive/bin/x86_64-linux
/usr/bin:/app/bin:/app/texlive/bin:/app/texlive/bin/x86_64-linux
Process exited normally
```
TexStudio does only see a part of programs when executing "**ls /usr/bin/**" from within TexStudio. R is not visible. But when opening the folder from a terminal it is. Also, biber is in the same directory as pdflatex, which runs fine.

Every not working command runs fine using it from a terminal.

The file rights / details for R are:
-rwxr-xr-x 1 root root 8812 Mär 25  2020 R

### How to reproduce
Install texlive 2020
Add: 
```
PATH=/usr/local/texlive/2020/bin/x86_64-linux:$PATH
export PATH
```
to "/etc/profile.d/texlive.sh".
Install R to /usr/bin
Set bibliography command to biber and try to run e.g. the bibliography command and or "R --version" as user command.

Note: I installed the same configuration onto a Kubuntu system which uses TexStudio 2.12.22 with Qt 5.12.8 and there everything works. On both systems the latest available version of TexStudio found with Discover was installed.
Executing TexStudio from the command line makes no difference.

Executing the bibliography compilation and other commands from a terminal by hand is not that convenient ;-)
It would be really great if you could help me to solve this.
Thanks!

**Comment by sunderme** [comment]
a bit out of scope. Probably related to your linux distribution.
Points to look to *remedy* the issue:
1) you can set additional search path
2) set R with absolute path

**Comment by sunderme** [comment]
you are not using flatpack or similar ?

**Comment by brixxx** [comment]
Thanks for the help!
The strange thing is that pdflatex runs, but not biber.
Using the absolute path or changing the search path did not change anything.

I installed Texstudio via flatpack.

I found a solution for me. I uninstalled it and downloaded the latest version from texstudio.org.
This version works as expected.
