### ISSUE TITLE
Command line option --texpath overwrite default compiler

### ISSUE THREAD

**Issue by dervomsee** [texstudio-org/texstudio#1525]
When using the command line option --texpath the default compiler gets overwritten.

### Environment
- TeXstudio: 3.1.1 (git 3.1.1), portable Windows version
- Qt: 5.15.2
- OS: Windows 10
- TeX distribution: miktex portable

### Expected behavior
The command line option --texpath sets just the binary paths and not overwrites/resets other settings.

### Actual behavior
The command line option --texpath sets the default compiler to PdfLaTeX (default/first option).

### How to reproduce
* Unzip portable Windows version and start with default settings. PdfLaTeX (default/first option) is selected as the default compiler.
* Change the default compiler to LuaLaTeX and close TeXstudio
* Restart TeXstudio and check, if setting was saved ;-)
* Start with command line option --texpath. The default compiler is again PdfLaTeX instead of LuaLaTeX

**Comment by sunderme** [comment]
that is intentional behaviour
if the compilers are set correctly, there is no need to use this option

**Comment by dervomsee** [comment]
Without setting the --texpath option, Texstudio does not find the Miktex installation.
My Miktex installation is not added to the PATH or anything else. It is a prepared, zipped, portable installation, unzipped to a local directory.

**Comment by sunderme** [comment]
Are the commands set with absolute paths when you use --texpath ?

**Comment by dervomsee** [comment]
I tried the "additional search path" with a relative path to the Tex installation, but it did not work.

The --texpath option is used with a relative path in a .bat file, which starts Texstudio.
Commit dbb1930 solves the issue. Thanks!
