### ISSUE TITLE
Bug in Proof enviroment

### ISSUE THREAD

**Issue by Algardiagon** [texstudio-org/texstudio#1528]
### Environment
- TeXstudio: 3.1.1
- Qt: Undefined control sequence. \end{proof}
- OS: Windows 10
- TeX distribution: Texlive

### Expected behavior
Run document showing no errors and the compiled version on the right hand side.

### Actual behavior
It shows errors for each \end{proof} command, do not show the compiled version on the right hand side but going to the pdf file it is all fine.

### How to reproduce
 \documentclass[11pt]{article}
\usepackage{amsfonts}
\usepackage{amsmath,amssymb}
\usepackage{amscd}
\usepackage{amsthm}
\usepackage{color}
\usepackage{hyperref}
\usepackage{tikz-cd}
\begin{document}

\begin{proof}
\end{proof}

\end{document}

**Comment by sunderme** [comment]
looks like a latex error. Different texlive installations ?
Take a look at help/check latex installation.

**Comment by muzimuzhi** [comment]
@Algardiagon This is a LaTeX usage question. 

`proof` environment _is_ provided in `amsthm` package. "Undefined control sequence.  \end{proof}" is the excerpted message and that doesn't necessarily mean `\end{proof}` is undefined. You should click the "Log File" tab at the left of "Issues" tab, and see exactly which one is the undefined control sequence from full error message.
![image](https://user-images.githubusercontent.com/6376638/110728251-acee5c00-8257-11eb-8397-8a668597ed4c.png)


Online docs that might help:
 - https://www.overleaf.com/learn/latex/Errors/Undefined%20control%20sequence
 - https://www.dickimaw-books.com/latex/minexample/html/errormessages.html

**Comment by Algardiagon** [comment]
It worked adding 
\usepackage{txfonts}

Not sure why it ran before (and when the problem started it ran well in TeXworks and Overleaf).
