### ISSUE TITLE
In version 3.1.1. font settings get reset after each exit and relaunch.

### ISSUE THREAD

**Issue by AtaZadehgol** [texstudio-org/texstudio#1529]
### Environment
- TeXstudio:  3.1.1
- Qt: 
- OS:  Windows 10
- TeX distribution:  miktex

### Expected behavior
In versions prior to 3.1.1, after leaving the program and returning to it, the editor's view settings did not change. 

### Actual behavior
In version 3.1.1: I set the text magnification to a certain level. After I exit TeXStudio and return to it, all view settings get reset and I have to set it again.

### How to reproduce
1. Launch TeXStudio.
2. Set text font size to anything new.
3. Type some stuff.
4. Save
5. Close TeXStudio.
6. Launch TeXStudio, and now the font size has been reset to defaults again!

**Comment by sunderme** [comment]
how/where do you change "text font size" ?

**Comment by AtaZadehgol** [comment]
I press on the Control key and simultaneously roll up the middle button of
my mouse; this increases the font size. If I roll down the middle button,
it decreases the font size.

**Comment by AtaZadehgol** [comment]
Ok, but it used to be persistent in versions prior to 3.1.1.

Sincerely,
Ata

+++++++++++++++++++++++++++
Dr. Zadehgol, Ata
Mobile: +1-217-419-3884
Website: https://sites.google.com/view/atazadehgol/home
+++++++++++++++++++++++++++
GM
"Your best and wisest refuge from all troubles is in your science" -- Ada
Lovelace

**Comment by sunderme** [comment]
not with 2.12.22

**Comment by AtaZadehgol** [comment]
So you're not able to replicate my issue?

**Comment by AtaZadehgol** [comment]
This issue was not present as recently as version 3.1.0.

**Comment by sunderme** [comment]
2.12.22 on linux does not have persistent zoom.
I don't consider that as faulty behavior, so from my point of view, there is nothing to fix.

**Comment by AtaZadehgol** [comment]
Ok, but I was reporting this issue on Windows 10, not linux. Thanks for the
great product, and your prompt attention!

Sincerely,
Ata

+++++++++++++++++++++++++++
Dr. Zadehgol, Ata
Mobile: +1-217-419-3884
Website: https://sites.google.com/view/atazadehgol/home
+++++++++++++++++++++++++++
GM
"Your best and wisest refuge from all troubles is in your science" -- Ada
Lovelace

**Comment by sunderme** [comment]
it is the same with 2.12.22 under win.
