### ISSUE TITLE
Custom templates missing

### ISSUE THREAD

**Issue by foreachthing** [texstudio-org/texstudio#153]
### Environment
- TeXstudio: 2.12.8
- OS: Windows 7 64bits
- TeX distribution: texlive

### Expected behavior
Be able to choose from my templates.

### Actual behavior
Does only list one (tex) file.

### How to reproduce

- Correctly edited the file `template_resources.xml` (I know, because it used to work).
`    <Resource>
        <Name>ACME</Name>
        <Path>q:/abt_Simulation/Daten/Vorlagen</Path>
        <Description>ACME Vorlagen</Description>
        <Editable>False</Editable>
        <Icon>ft.png</Icon>
    </Resource>`
- List of templates: 
![image](https://user-images.githubusercontent.com/10420187/40406179-f966f91c-5e5f-11e8-984d-f3be28dfb959.png)

- New from Template: 
![image](https://user-images.githubusercontent.com/10420187/40406283-64e0b0f2-5e60-11e8-878d-60dd4c7ac863.png)

Only the .tex file is listed now. There used to be all the templates available and `LatexColors.incl.tex` was _not_ listed.

**Comment by sunderme** [comment]
we are not guessing and typing a test case. Please upload the files.

**Comment by dbitouze** [comment]
BTW, could be nice to be able to load templates from a remote repository, for example provided by the TXS community or from e.g. [Overleaf templates](https://www.overleaf.com/latex/templates).

**Comment by foreachthing** [comment]
Please find `template_resources.xml` and some dummy-template files attached.
Note: you'll need to edit the path in `template_resources.xml`, but you know that already.

[support_texstudio.zip](https://github.com/texstudio-org/texstudio/files/2030874/support_texstudio.zip)

**Comment by sunderme** [comment]
fixed in repository (5a36022e4f4b329ed703f00e692df2a044a40b18)

**Comment by foreachthing** [comment]
Thanks for fixing this.
How can I download Windows exe? Can't build ..... :-\
