### ISSUE TITLE
Cursor will ghostly move to other places even if I didn't move my mouse and sometimes leads plasmashell crash

### ISSUE THREAD

**Issue by 1900011604** [texstudio-org/texstudio#1532]
在用texstudio编辑的时候时常发现敲击过快时光标跳到了别的地方使得输入位置错误/覆盖原来的内容（出现速度快来不及捕捉也难以复现）。有时候在这上面打字的时候会系统假死，鼠标能动但是不能点击，只能切换到别的tty然后重启。

**有极少时候**首先切换到命令行界面

输入

`killall plasmashell`

再回到图形化界面，打开终端，执行

`plasmashell &`

可以解决

When I type fast on texstudio, cursor will ghostly move to other places even if I didn't move my mouse, sometimes it leads to deleting lines I inserted. It happens so fast that I cannot reproduce it.

sometimes plasmashell will crash when I type in texstudio, only the mouse can move but it cannot click anywhere. The only keys work are `Ctrl+Alt+F2~6` which allows me to change to tty2 and reboot.

It does not relate to touch-screen as my Linux-kernel does not support touch-screen

Kate Vim VSCode does not have these issues

```
Version: Texstudio >3.0.0
OS: Manjaro 21.0 Ornara
Kernel: x86_64 Linux 5.12 Manjaro
Resolution: 2736x1824
DE: KDE 5.79.0 / Plasma 5.21.1
WM: KWin
GTK Theme: Breath [GTK2/3]
Icon Theme: breath2
Disk: 75G / 241G (32%)
CPU: Intel Core i5-8250U @ 8x 3.4GHz
GPU: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
```

**Comment by sunderme** [comment]
no chance to reproduce, no chance to resolve
crashes in plasma shell are likely problems of said program
and lastly, it is manjaro (rolling release, arch based) which causes at times weird bugs.

Without a step-by-step instruction for a bug, there is really no way forward, hence closed.
