### ISSUE TITLE
Do not need "num" and "den" in \frac{}{}

### ISSUE THREAD

**Issue by 1900011604** [texstudio-org/texstudio#1533]
Thus we do not need to delete the "num" and "den" to input numbers.

Also in other languages like \frac{分子}{分母}

**Comment by sunderme** [comment]
that are placeholders, they are automatically selected when changing via "move to next word or placeholder" (ctrl+right) and can be overwritten without pressing anything additional.

**Comment by sunderme** [comment]
you can turn the arguments off: options/completion/ disable "insert arguments"

**Comment by 1900011604** [comment]
I turned "Insert Arguments" and "Arguments as Placeholders" off, and found that it does turn off when I type \frac but it does not turn off when I click "Shift+Alt+F" to insert it.

**Comment by muzimuzhi** [comment]
> [...] and found that it does turn off when I type \frac but it does not turn off when I click "Shift+Alt+F" to insert it.

@1900011604 This is configurable in Configure TeXstudio -> Menus
![image](https://user-images.githubusercontent.com/6376638/110936362-be288d00-836b-11eb-9a44-a777899143c5.png)

**Comment by 1900011604** [comment]
Thanks! @muzimuzhi

**Comment by 1900011604** [comment]
> > [...] and found that it does turn off when I type \frac but it does not turn off when I click "Shift+Alt+F" to insert it.
> 
> @1900011604 This is configurable in Configure TeXstudio -> Menus
> ![image](https://user-images.githubusercontent.com/6376638/110936362-be288d00-836b-11eb-9a44-a777899143c5.png)

After I changed it, sometimes it will automatically change back, why?

**Comment by 1900011604** [comment]
> you can turn the arguments off: options/completion/ disable "insert arguments"

this will break the placeholders of `$\left[\right]$` (which will put the cursor on the right of `]` not in the middle of `[` and `\`)

**Comment by muzimuzhi** [comment]
> After I changed it to `\frac{%|}{}`, sometimes it will automatically change back, why?

Which version of texstudio do you use now? Any pattern to reproduce the problem? Possibly similar to #1522, which occurred in v3.1.1 and had been fixed since v3.1.2beta1.

**Comment by 1900011604** [comment]
I am using v3.1.1 and as I use package-manager so I am not going to use v3.1.2beta1, waiting for v3.1.2 release. Possibly similar to #1522, I think.

**Comment by 1900011604** [comment]
How about changing the `Arguments as Placeholders`(like `num`, `den`, `width`, `position`) to `%|` when turning it off?
