### ISSUE TITLE
Custom language or tex.qnfa problem

### ISSUE THREAD

**Issue by quinlon** [texstudio-org/texstudio#1537]
Dear Developers, I am not a coder and unsure if this is the right place, however it seems to me that there has to be a bug relating tex.qnfa or the way the file is used by the system. Thank you for your great work.

### Environment
- TeXstudio: TeXstudio 3.1.1 
- Qt: Qt Version 5.15.2
- OS: Win10
- TeX distribution: texlive

### Expected behavior:
Still being able to use the structure tree in the window to the left when using a custom language based on tex.qnfa.

### Actual behavior
The structure tree is gone (only the file name is displayed in the window), no parts, chapters, or labels are displayed.

### How to reproduce
Download tex.qnfa, put it in the settings/languages folder, edit it so that the entry QNFA language="(La)TeX" refers to anything else, so it can be picked in the highlights menu, start texstudio and choose it in the highlight menu. You will notice, the structure tree will have collapsed and will reappear once you switch back to regular (La)TeX in the highlights menu. 

The problem does not seem to have anything to do with the file itself, if you leave QNFA language="(La)TeX"  unchanged in the file but make other edits to the file, these do work as the custom settings are overwritten and the structure tree is still displayed.

**Comment by sunderme** [comment]
txs analyses latex very specifically. Why do you not want to call it latex in the tex.qnfa ?

**Comment by quinlon** [comment]
Because I use it to highlight specific parts of latex code, specifically footnotes, and I it seems like a good idea to be able to switch between my custom view and the standard latex highlighting

**Comment by sunderme** [comment]
you could use the following language names for syntax hightlighting: "(La)TeX" , "Pweave" , "Sweave" , "TeX dtx file"

**Comment by sunderme** [comment]
Is this answered ?
