### ISSUE TITLE
Some UI Bugs in Adwaita Style

### ISSUE THREAD

**Issue by shatzman** [texstudio-org/texstudio#1538]
![image](https://user-images.githubusercontent.com/48896370/111081657-a0daf680-8504-11eb-8246-001d8c8437a4.png)
1. The Buttons/icons are too big and you cannot configure them in settings.
2. In darkmode the font /background are bad set, you cant see the entries properly. Unfortuanately i couldnt find where i can modify this section. I could only modify the colors in the editor itself
![image](https://user-images.githubusercontent.com/48896370/111081722-029b6080-8505-11eb-9521-76d3eb376da9.png)

**Comment by sunderme** [comment]
which os, which version of txs.

**Comment by shatzman** [comment]
OS: Windows 10
Texstudio: 
TeXstudio 3.1.1 (git 3.1.1)
Qt-Version 5.15.2

I dont know which version of txs. I ahve installed the new texstudio version couple days ago. 
![image](https://user-images.githubusercontent.com/48896370/111082509-fe714200-8508-11eb-9cee-e118ff0dd1ed.png)
![image](https://user-images.githubusercontent.com/48896370/111082541-219bf180-8509-11eb-828a-271a98a140b2.png)

**Comment by sunderme** [comment]
you need to set Adwaita - dark and classic style. Other combinations will not work properly.

**Comment by shatzman** [comment]
Still the same issues.  The Font color of the Search results and the document structure is very exhausting for the eyes because if the contrast.

**Comment by shatzman** [comment]
Here aswell the font color is too dark.
![image](https://user-images.githubusercontent.com/48896370/111082995-98d28500-850b-11eb-9323-b86ea47e5513.png)

**Comment by sunderme** [comment]
restart of txs ?

**Comment by shatzman** [comment]
Thank you... that solves my problem.
