### ISSUE TITLE
Search&Replace Functionality

### ISSUE THREAD

**Issue by shatzman** [texstudio-org/texstudio#1539]
When i want to search for soemthing and replace the section where i can replace doesnt refresh.
### Environment
- TeXstudio: 3.1.1
- Qt: 5.12.2
- OS: Windows 10
- TeX distribution: , texlive

### Expected behavior
I search for a word and open the section "Search results" i do replace sucessfully.
 Now i want to search for another word. I type my new word and press enter. The search results should get refreshed and i cam replace.  

### Actual behavior
The searchresults section doesnt refresh and even i click on refresh, the new search word doesnt  refresh and so i dont get the search results for my new search word and cannot replace them

![image](https://user-images.githubusercontent.com/48896370/111082143-09c36e00-8507-11eb-80cd-21c75f4b9691.png)

**Comment by sunderme** [comment]
you need to press "+" again
