### ISSUE TITLE
New from template issues

### ISSUE THREAD

**Issue by morpheusbeing** [texstudio-org/texstudio#154]
### Environment
TeXstudio 2.12.8 (hg n/a)
Using Qt Version 5.10.1, compiled with Qt 5.10.1 R
running on Debian testing.
TeX distribution:  texlive, 

### Expected behavior
When choosing new from template - user defined, expect it to open multiple .tex files as defined in .json and stored in zip file. It does not, only works if only 1 file specified in the .json and stored in the .zip file.

And the date is not shown

**Comment by sunderme** [comment]
please provide files/ a test case

**Comment by sunderme** [comment]
no feedback
