### ISSUE TITLE
Greek ALphabets feature

### ISSUE THREAD

**Issue by Abel-Github** [texstudio-org/texstudio#1540]
I recently Used Maple and came across a nice shortcut that makes it a lot easy to type Greek characters.  Pressing **Ctlr+G** will activate all the characters to become greek alphabets. so whatever character you press next on the keyboard will just display in Greek. As an example  **Ctlr+G** followed by w = omega, y = gamma, t = tau, r = rho, k = kappa,  o = omicron and os on and so forth. It works for both small and capital letter Greek alphabets

I will like the same features to be ported to Texstudio.  An example will be like  **Alt+Shift + G** followed by any character will display the corresponding Greek alphabet in Latex format.  e.g  **Alt+Shift + G** followed by w = \omega, y = \gamma, t = \tau, r = \rho, k = \kappa, F = \Phi, f = \phi, s = \psi etc.

**Comment by sunderme** [comment]
this is also functionality which can be solved by macros and/or scripting
You can define macros with \alpha etc and set it to whatever shortcut you like, i.e ctrl+g,ctrl+a etc.
