### ISSUE TITLE
Selection of bibliography-type (biber / bibtex) des not work.

### ISSUE THREAD

**Issue by chr-wag** [texstudio-org/texstudio#1543]
### Environment
- TeXstudio: 3.1.1 (and earlier)
- Qt: Nutze Qt-Version 5.15.2, kompiliert mit Qt 5.15.2 R
- OS: Win10
- TeX distribution: texlive, but bug is independent of the latex installation

### Expected behavior

The selection "bibliography -> kind -> bibtex / biblatex" should specify, whether bibtex or biber are executed.

### Actual behavior

The selection "bibliography -> kind -> bibtex / biblatex" does not work - no matter what I select, texstudio wants to run biber.exe. But it should use "bibtex.exe"

After alternating the commands (Options -> Configure) and change biber to "bibtex.exe %", it runs bibtex. But the specification of the bibtex-command remians ignored.

### How to reproduce

Trivial ;)

**Comment by sunderme** [comment]
apparently you need to change options/build/default bibliography tool

**Comment by chr-wag** [comment]
Ok, thank you very much!  But you may agree that this option "bibliography -> kind -> bibtex / biblatex" appears confusing, right? What is is used for?

**Comment by sunderme** [comment]
I have no idea, I will take a look at the code.

**Comment by sunderme** [comment]
the type changes the offered menu entries in the Bibliography menu.

**Comment by chr-wag** [comment]
Thanks a lot for the clarification and your quick answers!
