### ISSUE TITLE
Missing windowsvista style in newer versions of TeXstudio

### ISSUE THREAD

**Issue by khung** [texstudio-org/texstudio#1544]
### Environment
- TeXstudio: 3.1.1
- Qt: 5.15.2
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
The appearance (style) of the UI under Windows should default to the windowsvista QT style.

### Actual behavior
The appearance (style) of the UI under Windows defaults to the Windows QT style. There is no windowsvista style available under  Options > Configure TeXstudio... > General > Style.

### How to reproduce
Install TeXstudio 3.1.1 for Windows and launch it.

It looks like this started with version 3.0.5. 3.0.4 has the style and defaults to it, while all publicly released versions afterwards don't have the style.

**Comment by sunderme** [comment]
fixed
