### ISSUE TITLE
New Menu items are not saved in the ini file

### ISSUE THREAD

**Issue by cipman** [texstudio-org/texstudio#1546]
### Environment
- TeXstudio: 3.1.1
- Qt:  5.12.8
- OS: Linux Mint 20.1
- TeX distribution: texlive

### How to reproduce
Options > Configure TeXstudio > Menus > Insert New Menu Item (before) > [create a new menu item of your choice, say under Math] > OK
Close TeXStudio
Open  TeXStudio

### Expected behavior
One would expect the newly created menu item to be saved and found when checking menu items

### Actual behavior
The new menu item info is not saved. Although the ini file is saved upon closing TS, the info about the new menu item is not there.

Reproduced:
- using the current install on my production box
- removing ~/.config/texstudio  (like a clean install) as above
- on a fresh Linux Mint 20.1 virtual box

**Comment by muzimuzhi** [comment]
Perhaps this is a duplicate of #1522. Does the new builds [here](https://github.com/texstudio-org/texstudio/actions/runs/629620816) (under title "Artifacts") fix your problem?

**Comment by cipman** [comment]
Yes, it does. Thank you!
I'm closing this issue.
