### ISSUE TITLE
No spinning wheel when compiling

### ISSUE THREAD

**Issue by cipman** [texstudio-org/texstudio#1547]
### Environment
- TeXstudio: 3.1.1
- Qt:  5.12.8
- OS: Linux Mint 20.1
- TeX distribution: texlive

### Expected behavior
When compiling a bigger project there used to be a qt spinning wheel replacing the magnifier glass indicating there's something going on.

### Actual behavior
Since qt5 versions (I think), no spinning anything. 
The only indication is the deactivation of the Build&View and Compile buttons and the activation of the Stop Compile button.

### How to reproduce
Build&View any [ more complex] project.

**Comment by sunderme** [comment]
The spinning wheel probably resulted from a blocked event queue. 
That was not intentional and it will not be implemented deliberately.
Just look at the Messages pane, to see if a command is finished.
