### ISSUE TITLE
Language Tool results are not shown

### ISSUE THREAD

**Issue by nehkaa** [texstudio-org/texstudio#1548]
### Environment
- TeXstudio: 3.1.1
- Qt: 5.15.2, kompiliert mit Qt 5.15.2 R
- OS: Windows 10
- TeX distribution: MikTeX 2.9
- LanguageTool: 3.3

### Starting Situation
My languagetool config says:
- Server-URL: http://localhost:8081/
- Java: java
- LT-Path: C:\Users\<username>\Downloads\languagetool-3.3\languagetool-server.jar
- LT arguments: org.languagetool.server.HTTPServer -p 8081

My LT Report says:
```
where java: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
C:\ProgramData\Oracle\Java\javapath\java.exe

JAVA: java
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) Client VM (build 25.251-b08, mixed mode, sharing)

Echzeitprüfungen sind aktiviert.
Grammatikprüfungen sind aktiviert.

Versucht es automatisch zu starten.

Aktueller Status von LT:arbeitet

LT-URL: http://localhost:8081/v2/check
```

When I call LT manually via (via Windows Subsystem Linux):
`curl --data "language=en-US&text=Write or paste your text here too have it checked continuously." http://localhost:8081/v2/check`
I recieve:
```
<?xml version="1.0" encoding="UTF-8"?>
<matches software="LanguageTool" version="3.3" buildDate="2016-03-28 09:17">
<language shortname="en-US" name="English (US)"/>
<error fromy="0" fromx="30" toy="0" tox="38" ruleId="TOO_TO" subId="1"  msg="Did you mean &apos;to have&apos;?" shortmsg="Possible typo" replacements="to have" context="Write or paste your text here too have it checked continuously." contextoffset="30" offset="30" errorlength="8" category="Commonly Confused Words" categoryid="CONFUSED_WORDS" locqualityissuetype="misspelling"/>
</matches>
```

I've placed the sentance "Write or paste your text here too have it checked continuously." in my LaTeX document.

### Expected behavior
I would have expected the "too" to be marked / underlined in the tex file in the TeXstudio editor.

### Actual behavior
no markings are present in the sentance mentioned above.

### How to reproduce
This happens every time I try it.

**Comment by sunderme** [comment]
works as expected (linux though)
Any particular reason why you use such an old version of LT (current is 5.2.3 ) ?

**Comment by sunderme** [comment]
Newer version delivers json as result.That is probably the issue.

**Comment by nehkaa** [comment]
Okay, this was clearly my fault. After updating to Version 5.2 it also works for me. Whyever I found a trustable website showing me 3.3 as the latest verion... 🙈 
sorry for that.

However. That would result in a feature Request. I'd like to suggest a specific message with the hint to update language tool in the "check languagetool config" dialog if the result from languagetool is XML rather than json.
