### ISSUE TITLE
Error: Could not start the command: xelatex -synctex=1 -interaction=nonstopmode "xxx".tex

### ISSUE THREAD

**Issue by 1900011604** [texstudio-org/texstudio#1549]
Manjaro Linux 20.1 TeXstudio 3.1.1

If I start txs from desktop, it will say: 
```
Error: Could not start the command: xelatex -synctex=1 -interaction=nonstopmode "xxx".tex

which pdflatex: /usr/bin/which: no pdflatex in (/home/firestar/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
```
But start it from command line is fine

I add
```
PATH=/usr/local/texlive/2020/bin/x86_64-linux:$PATH; export PATH
MANPATH=/usr/local/texlive/2020/texmf-dist/doc/man:$MANPATH; export MANPATH
INFOPATH=/usr/local/texlive/2020/texmf-dist/doc/info:$INFOPATH; export INFOPATH
```
in my `.profile` but not working

Before today there was no this issue and I haven't move my TeX Live installation path.

**Comment by sunderme** [comment]
does it work if you start txs from command line ?
Desktop/start menu start does not necessarily use the same settings as command line.

**Comment by 1900011604** [comment]
Yes, if I start txs from command line, the command `xelatex -synctex=1 -interaction=nonstopmode "xxx".tex` works

**Comment by sunderme** [comment]
do you have enough info that you can debug on your side ?

**Comment by 1900011604** [comment]
I am waiting for the TeX Live 2021 next week.

**Comment by 1900011604** [comment]
![Screenshot_20210403_224051](https://user-images.githubusercontent.com/65082432/113481832-6a264980-94ce-11eb-9b96-63983fcbc9c4.png)

It seems that `which pdflatex` in TeXstudio cannot find the right location.
