### ISSUE TITLE
Feature Request: Load autogenerated cwl files upon creation without requiring restart

### ISSUE THREAD

**Issue by JonathanLevine657** [texstudio-org/texstudio#1550]
TXS autogenerates cwl files for unknown packages which is very useful, but the generated files are not activated until TXS is restarted.

**Comment by sunderme** [comment]
fixed

**Comment by JonathanLevine657** [comment]
If I'm iterating on a WIP cwl file to support a new package, how do I refresh to reflect the changes I just made without restarting TXS?

**Comment by sunderme** [comment]
Probably you can't as txs caches the files.
