### ISSUE TITLE
cwl syntax "#keyvals:\documentclass/thesis" doesn't work

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#1553]
### Environment
- TeXstudio: TeXstudio 3.1.2 (git 3.1.1-117-gc5b19893)
- Qt: Qt Version 5.15.2, compiled with Qt 5.15.2 D
- OS: Linux (Mageia 8)

### Expected behavior
```
#keyvals:\documentclass/thesis
my-option1
my-option2
#endkeyvals
```
or
```
\documentclass[%<options%>]{thesis}
#
#keyvals:\documentclass/thesis
my-option1
my-option2
#endkeyvals
```
(BTW, which one is appropriate?) should provide completion in `\documentclass[options]{thesis}` when "options" is replaced by "my".

### Actual behavior
Nothing happens

**Comment by sunderme** [comment]
works as expected
Is cwl loaded at all ? txs uses the class name or usepackage to determine which cwls to load.

**Comment by dbitouze** [comment]
> works as expected

At least and AFAICS, not with `yathesis.cwl`.

> Is cwl loaded at all ?

It is. It fails even if `yathesis.cwl` is checked in Options → Configure TXS → Completion.

> txs uses the class name or usepackage to determine which cwls to load.

Indeed: for instance, the commands defined in `yathesis.cwl` are marked as known and take advantage of the completion.

**Comment by dbitouze** [comment]
> works as expected

Is the line `\documentclass[%<options%>]{thesis}` needed or on the contrary is it to be avoided?

**Comment by sunderme** [comment]
you don't need that line.
Starting the completer for keyval of yathesis is somewhat janky, I will take a closer look.

**Comment by dbitouze** [comment]
> you don't need that line.

OK.

> Starting the completer for keyval of yathesis is somewhat janky, I will take a closer look.

Thanks but please wait a few minutes: I'm in the process to pull request another version of `yathesis.cwl`.

**Comment by sunderme** [comment]
Should work reliable with latest commits

**Comment by dbitouze** [comment]
> Should work reliable with latest commits

With TeXstudio 3.1.2 (git 3.1.2beta1-45-g165955b6), it still doesn't work for me.

**Steps:**

1. File → New
2. LaTeX → \documentclass
3. <kbd>Ctrl</kbd>+<kbd>→</kbd> and overwrite `class` by `yathesis`
4. <kbd>Ctrl</kbd>+<kbd>←</kbd> and start to write one of the class options of `yathesis` stipulated in the `yathesis.cwl` file (reminded below), e.g. `mainlanguage`
5. No completion.

**Checked:** the `yathesis.cwl` checkbox is checked in in Options → Configure TXS → Completion.

**Extract of the `yathesis.cwl` file:**
```
#keyvals:\documentclass/yathesis
mainlanguage=#french,english
secnumdepth=#part,chapter,section,subsection,subsubsection,paragraph,subparagraph
space=#single,onehalf,double
chap-style=#Sonny,Lenny,Glenn,Conny,Rejne,Bjarne,PetersLenny,Bjornstrup,none
fncychap=#Sonny,Lenny,Glenn,Conny,Rejne,Bjarne,PetersLenny,Bjornstrup,none
nofrontcover#true,false
sepcorpaffilfrench=
sepcorpaffilenglish=
version=#inprogress,inprogress*,submitted,submitted*,final,draft
output=#screen,paper,paper*
colophon-location=#verso-frontcover,recto-backcover,nowhere
hdr
numlaboratories=%<⟨nombre de laboratoires affichés⟩%>
localtocs
localtocs/depth=#section,subsection,subsubsection,paragraph,subparagraph
localbibs
localbibs*
10pt
11pt
12pt
leqno
fleqn
oneside
noerror
noauthor
notitle
noacademicfield
nodate
noinstitute
nodoctoralschool
nolaboratory
nolaboratoryaddress
nosupervisor
nomaketitle
nokeywords
noabstract
nomakeabstract
notableofcontents
noprintbibliography
graphicx={%<⟨options du package graphicx⟩%>}
adjustbox={%<⟨options du package adjustbox⟩%>}
setspace={%<⟨options du package setspace⟩%>}
xcolor={%<⟨options du package xcolor⟩%>}
datatool={%<⟨options du package datatool⟩%>}
titlesec={%<⟨options du package titlesec⟩%>}
draftwatermark={%<⟨options du package draftwatermark⟩%>}
babel={%<⟨options du package babel⟩%>}
datetime2={%<⟨options du package datetime2⟩%>}
corps=%<⟨corporation⟩%>
role=%<⟨role⟩%>
#endkeyvals
```

**Comment by sunderme** [comment]
looks like you need to update to upstream

**Comment by dbitouze** [comment]
> looks like you need to update to upstream

Indeed, it works smoothly now: many thanks and sorry for the noise.

**Comment by sunderme** [comment]
No problem
