### ISSUE TITLE
Question: How do I disable syntax highlighting inside specified environments?

### ISSUE THREAD

**Issue by JonathanLevine657** [texstudio-org/texstudio#1558]
For example, `pygmentex` provides code syntax-highlighting. That means I might have python code inside a latex document, and I don't want the TXS latex highlighter to try and color it.

**Comment by sunderme** [comment]
Declare it as verbatim environment

**Comment by JonathanLevine657** [comment]
Thanks, that was enough to figure it out.

For future reference: 

1. syntax-highlighting is controlled by cwl files. 
2.  cwl files are organized by package, and they define attributes for various commands defined/supported by that package.
3.  If no cwl file for a given package is shipped with TXS. cwl files are autogenerated the first time a package is used (though they are usually less precise/complete than handcrafted ones) 
4. to disable syntax highlighting inside an environment provided by a 3rd part package, find its cwl file, and annotate the `\begin{fooenv}` token with the attribute `V` which marks it as "verbatim".

For example, the `pygmentex` package which provides the environment `pygmented`. To disable syntax-highlighting inside it, open `~/.config/texstudio/completion/autogenerated/pygmentex.cwl` in an editor and replace
```
\begin{pygmented}#S
```
with
```
\begin{pygmented}#SV
```

**Comment by sunderme** [comment]
Maybe you want to remove the 'S' in#SV.
With S the line is not used for completion, see manual.
