### ISSUE TITLE
Feature Request: Support project templates (.zip/tarball project templates)

### ISSUE THREAD

**Issue by JonathanLevine657** [texstudio-org/texstudio#1559]
### Describe the feature and the current behavior/state

TXS provides document templates, a great convenience. However, when working on larger documents, you often have a base template which may include a style file, stock graphics, external diagram source code etc'.

How about supporting a template zip/tarball file which can be extracted into a new directory,
with a designated "main document" file, to be opened after creation?

**Comment by foreachthing** [comment]
You can already do that. Since many years...
Read more here: https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html#SECTION12b

> 2.2.2.1 The Template Format
> In its simplest form, a template is only a .tex file. Multi-file templates can be created by packaging all .tex files in a zip archive. Optionally, meta data can be stored in JSON format in a separate file with the same name, but extension ".json" instead of ".tex" or ".zip". Currently the following entries are supported in the meta data ...

**Comment by JonathanLevine657** [comment]
Thanks, I obviously wasn't  aware.

I'll see if I can improved the docs a bit after playing with this.
