### ISSUE TITLE
Settings for math-mode shortcuts are not persistent

### ISSUE THREAD

**Issue by LimeHunter7** [texstudio-org/texstudio#1560]
### Environment
- TeXstudio: 3.1.1
- Qt: 5.15.2
- OS: Windows 10
- TeX distribution: MiKTeX 2.9

### Expected behavior
Changing the behavior of the math-mode shortcut to remove excess spaces should be saved in settings.

### Actual behavior
The setting is not persistent between TeXStudio sessions and is not saved and restored in settings or profiles.

### How to reproduce
Editing the setting is done as follows: "Options" > "Configure TeXStudio" > "Menus" > "&Math" > Double-click on the value in the "Command" column and edit it, *e.g.* for "Inline math mode" from `$ %| $` to `$%|$`.

Editing the setting and clicking "OK", then closing and reopening TeXStudio *twice* reverts to the default setting.

Editing the setting and clicking "OK", then explicitly saving settings ("Options" > "Save Current Settings"), then closing and reopening TeXStudio *twice* reverts to the default setting.

Editing the setting and clicking "OK", then saving a profile ("Options" > "Save Profile..."), then closing and reopening TeXStudio *twice* and loading that profile ("Options" > "Load Profile...") reverts to the default setting.

Editing the setting and clicking "OK", then opening the "Configure TeXStudio" dialog again *once*, then then closing and reopening TeXStudio *once* reverts to the default setting.

As a side note, editing the setting and clicking "OK", then opening the "Configure TeXStudio" dialog again *twice* causes the column value to become *non-bold* as opposed to the bolding that the non-default values display.

**Comment by sunderme** [comment]
Try 3.1.2beta1

**Comment by LimeHunter7** [comment]
That seems to have fixed it, thanks.
