### ISSUE TITLE
BUG: inline preview does not clean up temporary files

### ISSUE THREAD

**Issue by JonathanLevine657** [texstudio-org/texstudio#1561]
### Environment
- TeXstudio: 3.1.1
- OS: Linux

### Expected behavior
Whenever a preview is updated/cleared *all* temporary files created during the preview compilation should be deleted.

### Actual behavior
only the temporary .tex file is deleted. The compilation however produces (at least) a .pdf, .aux, .log and synctex files, yet these are never cleaned up by TXS.

If the user uses the preview feature extensively and does many edits while a preview is active, the temp files can accumulate to the point of affecting the system (for example, if the temp directory lives in memory as is the case on some linux systems).

I think it's fair to call this a resource leak.

### How to reproduce
1. create a document with a math environment
2. activate preview for the environment
3. make some edits
4. observe files created in temp directory
5. make some edits
6. note that .tex files are removed, but the other files remain

### Further info

One possible solution would be to use a unique temporary directory for each preview run in order to isolate the related files, then clean up the whole directory instead of just the .tex file.

**Comment by sunderme** [comment]
works fine on ubuntu.
All files disappear after closing the program.

**Comment by JonathanLevine657** [comment]
I double-checked yesterday, but I don't see it either today.
I've been experiencing some crashes, and using multiple instances at the same time, maybe it's an intermittent thing. I'll reopen if/when I can reliably reproduce.

Since users may have TXS be long-running, it would have been better to clear out old files as soon as possible, instead of waiting for the user to close the program. Currently, there's no limit on the use of temporary storage, when all you need is just the most recent preview.
