### ISSUE TITLE
viewer as tab /or merging windows was better

### ISSUE THREAD

**Issue by DrDids** [texstudio-org/texstudio#1563]
Since the last version of TexStudio the viewer appears on the side. It is used to be as tab (like any other opened file) and was much more practical. Just saying!

**Comment by sunderme** [comment]
if by viewer, you mean pdf viewer, that was never a tab.
No idea what program is referred to here.

**Comment by JonathanLevine657** [comment]
@DrDids, are you aware that you can switch the built in viewer between embedded mode (pane on the right), windowed mode (seperate window), or external mode (use your favorite window)?

**Comment by sunderme** [comment]
no feedback
