### ISSUE TITLE
TXS 3.1.2beta crash

### ISSUE THREAD

**Issue by JonathanLevine657** [texstudio-org/texstudio#1564]
### Environment
- TeXstudio: 3.1.2beta bdf8ce86
- Qt: 5.12.1
- OS: linux
 
### description

Intermittent crashes, haven't been able to pin down what triggers it, but save triggered
on at least some of the occasions.

It has occurred several times in the last couple of weeks, prehaps related to a recent change, since I haven't encountered previously, but I've also been using more features lately.

That's not much information, but I compiled a debug version and managed to grab a backtrace:
```
[bt] ./texstudio(Texstudio::recoverFromCrash()+0x583) [0x984309]
[bt] ./texstudio(recover()+0x9) [0x983d82]
[bt] ./texstudio(QString::size() const+0xf) [0x68cda9]
[bt] ./texstudio(QString::toLocal8Bit() const &+0x1d) [0x6f35ab]
[bt] ./texstudio(StructureEntry::debugPrint(char const*) const+0x173) [0x84ec9d]
[bt] ./texstudio(LatexDocumentsModel::parent(QModelIndex const&) const+0x13f) [0x85159d]
```

**Comment by sunderme** [comment]
please try the latest dev build

**Comment by JonathanLevine657** [comment]
I've switched to it, I'll update if I hit another crash.

**Comment by sunderme** [comment]
open a new report if there is another crash

**Comment by JonathanLevine657** [comment]
so far so good.
