### ISSUE TITLE
Add Chinese dash and quotemarks in editor

### ISSUE THREAD

**Issue by 1900011604** [texstudio-org/texstudio#1566]
![图片](https://user-images.githubusercontent.com/65082432/113323515-a0d25780-9348-11eb-898d-9834b131632b.png)

The dash line and quotemarks are still in Latin mode. The correct display is:

![图片](https://user-images.githubusercontent.com/65082432/113324229-759c3800-9349-11eb-92c8-0638f958ed45.png)

maybe we should use `U+2E3A` to display Chinese Dash.

See https://www.thetype.com/2019/03/14918/

**Comment by sunderme** [comment]
no idea what is asked here.

**Comment by 1900011604** [comment]
Maybe its hard for non-Chinese to understand this, when I edit files in texstudio, the Chinese characters and comma/dot/?/! are in Chinese font but the dash(破折号) and quotation mark are still in Latin font.

**Comment by 1900011604** [comment]
As developer @muzimuzhi is Chinese, I rewrite it in Chinese which is more fluent:

现在字体选择只有一种，无法分别选择中文、英文字体或者像VS Code里面一样选择多个fallback字体，现在问题是：当选择编辑器字体为西文等宽字体时，没有中文的破折号和中文的引号，这两个符号依然用的是英文的字体（斜的引号，半角），中英文区别不明显。

**Comment by muzimuzhi** [comment]
Have no idea whether Qt supports this.

**Comment by sunderme** [comment]
and this does not happen if the editor font is changed ?

**Comment by 1900011604** [comment]
Only Chinese **non-monospaced** fonts supports Chinese Dash and quotemarks, such as Noto Sans, even Noto Mono does not support.

**Comment by sunderme** [comment]
so, the solution is to use a font which contains the characters. Most fonts don't contain them. So, what is txs supposed to do ?

**Comment by sunderme** [comment]
not really anything txs can do, as far as I understand it.
