### ISSUE TITLE
TeXStudio does not reliably detect changed user packages

### ISSUE THREAD

**Issue by chaosflaws** [texstudio-org/texstudio#1569]
### Environment
- TeXstudio: 3.1.1
- Qt: 5.15.2
- OS: Windows 10
- TeX distribution: texlive

### Expected behavior
When a user-defined package or class (located in `TEXMFHOME`) is changed, TeXLive should detect those changes at reasonable times (e. g. at startup) and recreate its autogenerated cwl files.

### Actual behavior
TeXLive does not seem to refresh the autogenerated files at all. They will only be regenerated if the cwl file is deleted.

### How to reproduce

1. Create `my-test-package.sty` in `TEXMFHOME` with the following content:
```latex
\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{my-test-package}

\newcommand{\testCommand}{}
```

2. Create a test latex file, open it with texstudio and add the following MWE:
```latex
\documentclass{article}

\usepackage{my-test-package}

\begin{document}

\testCommand

\end{document}
```

3. Restart texstudio. It should now recognize `\testCommand`.

4. Add this line to `my-test-package.sty`:
```latex
\newcommand{\newTestCommand}{}
```

5. Add `\newTestCommand` to your latex test file. The document compiles, but the new command is not recognized.

6. Delete `my-test-package.cwl` in your autogenerated cwl files, restart texstudio twice. On the first restart, texstudio recreates the cwl file. After a second restart, the new command is recognized.

**Comment by sunderme** [comment]
txs autogenerates cwl as a  last resort.
If you want to make use of cwls in a meaningful way, make an edited cwl file.
The assumption is that packages are system packages, which don't change that often, hence generated once.
Any more mutable are includes/inputs.

**Comment by JonathanLevine657** [comment]
https://github.com/texstudio-org/texstudio/issues/1550#issuecomment-809793366

me too.

**Comment by sunderme** [comment]
> me too. regenerating when the file size/last_modified changes would be useful.

That would not be sufficient as sub-files may be changed.

**Comment by JonathanLevine657** [comment]
> That would not be sufficient as sub-files may be changed.

why not? you reload the parent. that gives you a list of dependencies which are either new (so load as usual) or cached, in which case we check the stored size/date on the cached package against the file on disk.

**Comment by JonathanLevine657** [comment]
I see what you mean now. If only the subfile is changed, you can't detect the cwl is stale without checking the sub-files, which isn't currently stored anywhere, so you'd have to reparse to do it. Chicken and egg. 

But, in practice, most  user styles are single-file. And packages which have many subfiles have their main file's date changed when they're update with the package manager. So, doing this would still cover most cases in practice. And if users need to remember to resave the toplevel style file to trigger a refresh, that's not that bad either. It's probably open in their editor anyway.

**Comment by sunderme** [comment]
manual maintained cwls when the author can do it should give the best results for cwls.
So, no changed behavior planned.
