### ISSUE TITLE
Font problem in embedded previewer

### ISSUE THREAD

**Issue by sjx95** [texstudio-org/texstudio#157]
### Environment
- TeXstudio: 2.12.8
- Qt: N/A
- OS: Mac
- TeX distribution: MacTeX Basic

### Expected behavior
After necessary component, such as "Fandol", and "xeCJK" included, compile with XeTeX successful.
But the Chinese Character not display in Preview window. But if I open it external, these display normal.

So I think this is caused by font, I searched "Fandol" in Font Book but got nothing.

**Comment by sjx95** [comment]
![screen shot 2018-05-26 at 20 55 38](https://user-images.githubusercontent.com/18415916/40576346-30182e3a-6127-11e8-842f-ec65a787778d.png)

**Comment by sunderme** [comment]
please provide the files (tex&pdf)
You might want to try a development build, see https://bintray.com/sunderme/texstudio/texstudio-osx#files

**Comment by sjx95** [comment]
```TeX
\documentclass[a4paper]{article}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{graphicx}
\usepackage{xeCJK}
\title{\LaTeX 中文测试}
\author{FukoMaster}
\begin{document}
	\maketitle
\end{document}
```
[texstudio_UvuuSC.pdf](https://github.com/texstudio-org/texstudio/files/2042202/texstudio_UvuuSC.pdf)

**Comment by sunderme** [comment]
could you try https://github.com/texstudio-org/texstudio/releases/download/2.12.8/texstudio-2.12.8-osx-forOldCPUs.dmg

**Comment by sjx95** [comment]
This doesn't work.

**Comment by ken-nakanishi** [comment]
I also encountered the same problem in my environment, and I think the cause of this problem is in `/Applications/texstudio.app/Contents/Frameworks/libpoppler.68.dylib` .

```
$ strings -a /Applications/texstudio.app/Contents/Frameworks/libpoppler.68.dylib | grep poppler
/usr/local/Cellar/poppler/0.57.0-texworks/share/poppler/ColorProfiles/
/usr/local/Cellar/poppler/0.57.0-texworks/share/poppler
%Produced by poppler pdftops version: {0:s} (http://poppler.freedesktop.org)
```
, but my poppler path is `/usr/local/Cellar/poppler/0.65.0` .

I do not think it is the best way, but I solved this problem as follows.
```
brew install --upgrade poppler
mkdir -p /usr/local/Cellar/poppler/0.57.0-texworks/share
ln -s /usr/local/Cellar/poppler/0.65.0/share/poppler /usr/local/Cellar/poppler/0.57.0-texworks/share/poppler
```

My environment is as follows.
```
MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
macOS High Sierra 10.13.4
poppler: stable 0.65.0, at /usr/local/Cellar/poppler/0.65.0
```
I hope this will help!

**Comment by manfeel** [comment]
> I also encountered the same problem in my environment, and I think the cause of this problem may be in `/Applications/texstudio.app/Contents/Frameworks/libpoppler.68.dylib` .
> 
> ```
> $ strings -a /Applications/texstudio.app/Contents/Frameworks/libpoppler.68.dylib | grep poppler
> /usr/local/Cellar/poppler/0.57.0-texworks/share/poppler/ColorProfiles/
> /usr/local/Cellar/poppler/0.57.0-texworks/share/poppler
> %Produced by poppler pdftops version: {0:s} (http://poppler.freedesktop.org)
> ```
> , but my poppler path is `/usr/local/Cellar/poppler/0.65.0` .
> 
> I do not think it is the best way, but I solved this problem as follows.
> 
> ```
> brew install --upgrade poppler
> mkdir -p /usr/local/Cellar/poppler/0.57.0-texworks/share
> ln -s /usr/local/Cellar/poppler/0.65.0/share/poppler /usr/local/Cellar/poppler/0.57.0-texworks/share/poppler
> ```
> My environment is as follows.
> 
> ```
> MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
> macOS High Sierra 10.13.4
> ```
> I hope this will help!

It works !!!
