### ISSUE TITLE
Editor does not link to pdf from "input" file anymore.

### ISSUE THREAD

**Issue by MR2387** [texstudio-org/texstudio#1572]
### Environment
- TeXstudio:  3.1.1
- Qt: 
- OS:  Windows(10) 
- TeX distribution:  miktex 

### Expected behavior

When I'm into an input file in the editor, I expect to go to the pdf location.
This does not happen anymore in the new version. I can't compile from the input file anymore.
This is the main file,
\input{content}
 when I'm inside content.tex I can't go to the pdf location or compile anymore.

**Comment by muzimuzhi** [comment]
Menu items under Options -> Root Document may provide some manual workarounds.

**Comment by sunderme** [comment]
insufficient information ("how to reproduce ...")
txs should work fine.
