### ISSUE TITLE
TeXstudio Emergency (Keeps Crashing)

### ISSUE THREAD

**Issue by vladimir-grbic** [texstudio-org/texstudio#1573]
Every time I click to open a document or save a file that has never been saved before (a file I just created) TeXstudio crashes and I get this message.

```
TeXstudio has CRASHED due to a SIGSEGV

A backtrace was written to
/tmp/texstudio_backtrace1.txt
Please provide this file if you send a bug report.

Do you want to keep TeXstudio running? This may cause
data corruption.
```

However, if I open a tex file from the folder, everything works fine and I can save it, build it and compile it. Also, TeXworks and gummi work normally, but I want to use TeXstudio. I tried removing it and installing it again and it did not work.

I am using Manjaro Linux with Gnome desktop as my OS. Please help.

**Comment by marijnschraagen** [comment]
Possibly related (also Manjaro), with a workaround: https://github.com/texstudio-org/texstudio/issues/1397

**Comment by sunderme** [comment]
the comment above should do it.
Otherwise, it is arch based and we don't provide packages for that.
