### ISSUE TITLE
Installation without texlive from distribution

### ISSUE THREAD

**Issue by elijahbailey** [texstudio-org/texstudio#1574]
### Environment
- TeXstudio: 3.1.1
- Qt: 5.12.8
- OS: Linux (Ubuntu 20.04 LTS)
- TeX distribution: texlive200 from CD/iso

### Description
When I install TeXStudio either from ubuntu repository or from download .deb file the installer ALWAYS tries to install texlive from the distribution.

I have TeXLive installed from the CD before and do NOT want the repository's distribution (Yes there are some reasons for this).
May be I missed something?
How can I achieve this?

Best regards
lpk

**Comment by sunderme** [comment]
The debian package recommends texlive but it is not a hard requirement.

**Comment by sunderme** [comment]
no feedback
