### ISSUE TITLE
Missing windowsvista style 

### ISSUE THREAD

**Issue by SainoNamkho** [texstudio-org/texstudio#1575]
@sunderme said it's fixed in https://github.com/texstudio-org/texstudio/issues/1544#issuecomment-800549761_, but the style is still missing in the latest release [3.1.2beta2](https://github.com/texstudio-org/texstudio/releases/tag/3.1.2beta2), how can I get the style?

**Comment by sunderme** [comment]
I assume that you are using the portable version ?

**Comment by SainoNamkho** [comment]
> 
> 
> I assume that you are using the portable version ?

Yes, so must I install the program to get that style? Is there anyway to pick a standalone style file to load a particular style?

**Comment by sunderme** [comment]
the package issue has been fixed. It was already fine with the installer version.
