### ISSUE TITLE
Misalignment of Find/Replace Arrows

### ISSUE THREAD

**Issue by Sam-OT** [texstudio-org/texstudio#1580]
### Describe the feature and the current behaviour/state

The forward/backward arrows for find/replace are misaligned. I frequently am doing a Find+Replace, but do not want to replace _all_ instances. I thus tap the blue "Find Next" arrow until I get to an entry which I wish to replace and tap the red "Replace Next" arrow. This was always quick and easy as the arrows were in line with each other. I just recently noticed---I think new in v3 to which I have recently upgraded, but I'm not 100% sure---that the Replace text box is larger than the Find. This misaligns the two arrows. I keep accidentally hitting "Find Previous" rather than "Find Next". See image below.

![image](https://user-images.githubusercontent.com/81111289/114556663-d5a3b000-9c60-11eb-98f5-4e79fe0a7c89.png)

### Who will benefit with this feature?

Everyone using Find+Replace

### Any Other info

I am guessing that this is a pretty easy fix: simply make the Replace text box the same size as the Find

---

I wanted to add the `enhancement` label, but I can't see how to do this...

**Comment by Sam-OT** [comment]
@sunderme may I ask why you closed this? Has it been fixed in a new version?

**Comment by sunderme** [comment]
![grafik](https://user-images.githubusercontent.com/14033169/115276936-f29a2080-a143-11eb-8904-a56a6e9fff75.png)
means it has been fixed with a commit which will be present starting from the next dev build.

**Comment by Sam-OT** [comment]
Ah, cool, thanks! :-)
