### ISSUE TITLE
Crash when File->Open

### ISSUE THREAD

**Issue by Yiannis128** [texstudio-org/texstudio#1586]
### Environment
- TeXstudio: 3.1.1
- Qt: Using Qt Version 5.15.2, compiled with Qt 5.15.2 R
- OS: Linux Manjaro Kernel 5.11
- TeX distribution: texlive

### Expected behavior
Dialog to open file opens.

### Actual behavior
Program crashes (Output shown below) when trying to open the file dialog to open a file.

### How to reproduce
File->Open

### Console Output
Here are the content of console from opening the file until the crash:
```
QApplication: invalid style override 'kvantum' passed, ignoring it.
	Available styles: Adwaita-Dark, Adwaita, Windows, Fusion
"/proc/28509/root"
QAbstractItemModel::endInsertRows:  Invalid index ( 1 , 0 ) in model LatexDocumentsModel(0x5562f501db30)
crashed with signal SIGSEGV
SIGSEGV (TXS-Version  R )
SIGSEGV (TXS-Version  R )
SIGSEGV (TXS-Version  R )
SIGSEGV (TXS-Version  R )

[bt] texstudio(_ZN12SimulatedCPU13set_from_realEv+0) [0x5562f37a10f0]
[bt] texstudio(_ZN12SimulatedCPU13set_from_realEv+0) [0x5562f37a10f0]

"/tmp/texstudio_backtrace1.txt"
"Current: 0/0"
"Current: 0/0"
"Current: 0/0"
Killed on user request after error: SIGSEGV

zsh: abort (core dumped)  texstudio report.tex
```
### Backtrace
Here are the content of the backtrace:
```
$ cat /tmp/texstudio_backtrace1.txt
SIGSEGV (TXS-Version  R )
[bt] texstudio(_ZN12SimulatedCPU13set_from_realEv+0) [0x5562f37a10f0]
```
### Note
You can still open files from the terminal: ```texstudio filename.tex```

**Comment by sunderme** [comment]
Same as #1573 ?

**Comment by JonathanLevine657** [comment]
@Yiannis128, Can you compile texstudio as a debug build and provide a proper stack trace? the one generated by release builds isn't helpful.

This bug has been reported several times, but none have provides sufficient information for a fix.

**Comment by Yiannis128** [comment]
> @Yiannis128, Can you compile texstudio as a debug build and provide a proper stack trace? the one generated by release builds isn't helpful.
> 
> This bug has been reported several times, but none have provides sufficient information for a fix.

I was using the build from my package manager, I will try and compile it from source and give the feedback you require.

**Comment by sunderme** [comment]
maybe you can try the work-around from #1397

**Comment by JonathanLevine657** [comment]
or, maybe provide a stacktrace to help see if txs can incorporate a fix after three separate manjaro users have complained about this. Perhaps it'll help clarify the problem enough to open a bug report for manjaro.

**Comment by sunderme** [comment]
the work-around sets Qt to use a different file dialog. It is a qt/gnome issue.

**Comment by JonathanLevine657** [comment]
qt/gnome is used by many distros, but only manjaro users have complained. 

a backtrace may help pinpoint the issue to qt or gnome or manjaro. Just using the workaround doesn't help solve the problem upstream.

as a last resort, txs could detect manjaro and activate the workaround automatically.

**Comment by JonathanLevine657** [comment]
@sunderme, getting a somewhat meaningful stacktrace for release builds might be as simple as compiling with `-fno-omit-frame-pointer`, which shouldn't have a noticeable impact on performance. 

It'd be especially useful if official binaries releases would have working backtrace capabilities - since that's what most users install.

**Comment by sunderme** [comment]
reporter does not reply

**Comment by sunderme** [comment]
compile flag has been activated, thanks
