### ISSUE TITLE
It is possible to avoid the buildin PDF viewer hanging when compiling

### ISSUE THREAD

**Issue by asmwarrior** [texstudio-org/texstudio#159]
TeXstudio 2.12.6 (hg 6632:7777b2b8a906)
Using Qt Version 5.9.1, compiled with Qt 5.9.1 R
I'm under Windows 7, and using TextLive 2015.

It takes several seconds to build my tex source file to pdf. When building, I still need to view the old PDF file under the build-in pdf viewer. But it becomes really slow(the buildin pdf viewer just hangs!) if I would like to drag the pdf or zoom the pdf, I believe the most CPU time is eat by the building process.

Is it possible to still view and navigate the old pdf when building?

I believe it is a multiply process issue, if the build-in pdf viewer is in a separate process instead of the main GUI process, then this issue could be solved. If they are in the same process, the CPU time is mainly doing some pipe text handling (which the text is from the compiling pdflatex.exe process)

Any ideas?

**Comment by asmwarrior** [comment]
OK, I found one issue which cause the hanging, because Texstudio automatically run the compiling several times. For me, I get 6 repeats, like below:

```
Process started: "xelatex.exe" -shell-escape -synctex=1 -interaction=nonstopmode "exam-a".tex

Process exited normally



Process started: "xelatex.exe" -shell-escape -synctex=1 -interaction=nonstopmode "exam-a".tex

Process exited normally



Process started: "xelatex.exe" -shell-escape -synctex=1 -interaction=nonstopmode "exam-a".tex

Process exited normally



Process started: "xelatex.exe" -shell-escape -synctex=1 -interaction=nonstopmode "exam-a".tex

Process exited normally



Process started: "xelatex.exe" -shell-escape -synctex=1 -interaction=nonstopmode "exam-a".tex

Process exited normally



Process started: "xelatex.exe" -shell-escape -synctex=1 -interaction=nonstopmode "exam-a".tex

Process exited normally
```

I just looked at the setting, and I see that the "repeat contained compilation commands" option is ON for the Xelatex command.

If I disable the option, then I get only one process start and exit log message, and it is really fast, so I don't see the hangs in the build-in PDF viewer.

I just want to know why I get 6 times of compiling when I click the "compile and view" toolbar button?
This really waste a lot of time!

**Comment by timhoffm** [comment]
Latex may need multiple compilation runs to get cross-references, glossaries, figure numbers etc. right.

The compiler will tell at the end of the log file if an additional run is needed. We parse this information and rerun if the compiler says so. The number of reruns depends on the packages and tex commands you are using.

You don't have to fully compile everytime, but then some elements of your PDF will not be right. It's up to you to trade compilation time for output correctness. You may setup am additional custom build change with just one "compile | view" for quick updates.

**Comment by asmwarrior** [comment]
Hi, @timhoffm thanks for explanation. Your statement is quite important for the user to understand why there is such an option. I would suggest putting them in the maunal/doc of Texstudio.

But to my original question, when TexStudio running several compilations, I still can't use the buildin PDF viewer, it just hangs or with no response. Is it possible to solve this issue. I think the most task is parsing the log files from the running xelatex process.

**Comment by asmwarrior** [comment]
I found that using the toolbar button "Latexmk" saves a lot of time. I just did some test. I change a word in my tex file, and when using the "Build and View" button, I get 6 times of running the Xelatex, like the logs I posted before. When I click the "Latexmk" command, I only get 2 times. See the log below:

```
Process started: latexmk -pdf -silent -pdflatex="xelatex -synctex=1 %O %S" "exam-a"

Latexmk: Run number 1 of rule 'pdflatex'

Latexmk: Summary of warnings: Latex found 25 multiply defined reference(s)

Latexmk: Run number 2 of rule 'pdflatex'

Latexmk: Summary of warnings: Latex found 25 multiply defined reference(s)

Process exited normally
```
My another question is: is the "Build and View" button just blindly did a full rebuild?

**Comment by sunderme** [comment]
I would assume that if txs starts xelatex 6 times, it reloads the pdf as many times.
I would suggest that you use latexmk (it might be possible to use `latxmk -xelatex`)

**Comment by asmwarrior** [comment]
Hi, @sunderme  thanks for the help, I agree with you.

> I would assume that if txs starts xelatex 6 times, it reloads the pdf as many times.
So, we need a method that the pdf should only be reload after the 6th's build, right?

> I would suggest that you use latexmk
Yes, I'm using this now, it is far better than the old way(using the "Build and View" button)

**Comment by sunderme** [comment]
but there is not much we are gooing to do about it, especially since there is a good solution
