### ISSUE TITLE
FR: make macros menu scrollable instead of multi-column

### ISSUE THREAD

**Issue by JonathanLevine657** [texstudio-org/texstudio#1591]
### Describe the feature and the current behavior/state
If the user has lots of macros (I have several dozens), the macro menu becomes unmanagable. It would be nice if the user could scroll, or even better filter the menu 
instead of the menu taking up most of the screen.

### Who will benefit with this feature?
Heavy users of the macro menu

**Comment by sunderme** [comment]
pretty unspecific

**Comment by sunderme** [comment]
I don't think that there is much influence on how the menu is set up
But there is already a macro panel ...

**Comment by JonathanLevine657** [comment]
What's unspecific about it?

**Comment by sunderme** [comment]
qt does not allow to change the behaviour of the menu in that way.
Use,the macro pane instead.
