### ISSUE TITLE
Better support for `subfiles` package

### ISSUE THREAD

**Issue by JonathanLevine657** [texstudio-org/texstudio#1593]
### Describe the feature and the current behavior/state
The `subfiles` package provides the ability to decompose a document into multiple files,
while keeping individual files compilable. Most importantly, the child documents reuse the
preamble from the parent. 

Currently, if you call compile on a child document, the master document is compiled instead, and the viewer simply jumps to the child document's location. This defeats the purpose of using `subfiles`, which is shorter compilation times. On the other hand, this suggests that `subfiles` *is* actually treated especially by TXS already. So, perhaps this is really a bug.

Example for experimentation:

`theMainDocument.tex`:
```tex
\documentclass{article}
\usepackage{subfiles}

% shared preamble here

\begin{document}
\subfile{child1}
\subfile{child2}
\end{document}
```

`child1.tex`:
```tex
\documentclass[theMainDocument]{subfiles}
 
% preamble from parent will be automatically inserted

\begin{document} 
content
\end{document}
```

### Who will benefit with this feature?
Users of the `subfiles`.  I know not every package in the TeX-sphere merits special support, but TXS already seems to support `subfiles`, and it [seems](https://tex.stackexchange.com/questions/tagged/subfiles) like its fairly popular.

**Comment by JonathanLevine657** [comment]
Another point - the packages imported in the master file aren't activated  in the editor for the child file, so completion/syntax highlighting isn't helpful.

**Comment by sunderme** [comment]
to compile local file (not master), use user tool/command: ```pdflatex -synctex=1 -interaction=nonstopmode ?c:me```
to view local file, use user tool/command: ```txs:///view-pdf-internal ?c:m.pdf --embedded```
Using user commands instead of cahnging the main command allows easier switching.
I don't see that subfiles are treated differently from normal includes.

**Comment by JonathanLevine657** [comment]
not differently, but they are recognized as includes. A good thing.

Thanks for the suggestion. It solves the subfile-only compilation problem.  Do you have any recommendation about the missing syntax highlighting?

**Comment by sunderme** [comment]
as stated, i don‘t see an issue with syntax higlighting.
you have all files opened ?

**Comment by homocomputeris** [comment]
@JonathanLevine657 
It seems to have highlighting and autocompletion working in the subfile, you need to compile the main file with all the subfiles included. After the compilation of the main file, the subfile immediately recognizes commands.

https://user-images.githubusercontent.com/7422433/124734273-a1692400-df1d-11eb-8c8a-4a208117aa6d.mov
