### ISSUE TITLE
FR: windowed viewer toolbar doesn't expose "scrolling follows cursor"

### ISSUE THREAD

**Issue by JonathanLevine657** [texstudio-org/texstudio#1599]
### Describe the feature and the current behavior/state
The windowed viewer has these toggles as part of its menus, and the internal viewer honors
them when they are  active, but there's no way to activate them without switching to the windowed viewer, toggling them, then returning to the internal viewer.

**Comment by sunderme** [comment]
<img width="476" alt="grafik" src="https://user-images.githubusercontent.com/14033169/115277407-8a980a00-a144-11eb-93c2-aa72bb4dde1d.png">
 ???

**Comment by JonathanLevine657** [comment]
Thanks.
