### ISSUE TITLE
Add new and/or own environments to Align Columns

### ISSUE THREAD

**Issue by fernandozucatelli** [texstudio-org/texstudio#1600]
### Describe the feature and the current behavior/state

Let's say I created my own array:
`\newenvironment{myArray}{\begin{pmatrix}}{\end{pmatrix}}`

And the I inserted some non-aligned numbers
```
\begin{equation}
  \begin{myArray}
    1 & 2    &  3        & 7 \\
    4 & 5        &   6 & 8 
  \end{myArray}
\end{equation}
```

The same way,  I might add
`\usepackage{nicematrix}`

and use
```
\begin{equation}
  \begin{pNiceMatrix}
    1 & 2    &  3        & 7 \\
    4 & 5        &   6 & 8
  \end{pNiceMatrix}
\end{equation}
```
This environment can't have the &s aligned through the command "Align Columns".
To have it so, I must replace its name from "myArray" to "array", **then** apply "Align Columns" and **then** rename it back to "myArray".

It would be nice to **add** my own environment "myArray" to the set of environments the command "Align Columns" can be applied to.

### Who will benefit with this feature?

Every user.

**Comment by sunderme** [comment]
implemented
However your env needs to be declared in a cwl file, so that txs knows what to do (i.e. a line ```\begin{myArray}#\array```

**Comment by fernandozucatelli** [comment]
I downloaded TeXstudio version 3.1.2 and the feature works like a charm. Thanks.
