### ISSUE TITLE
Adwaita Dark (txs) for TeXstudio in Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by bahman-mirzakhani** [texstudio-org/texstudio#1603]
### Describe the feature and the current behavior/state
There is TeXstudio ```Adwaita Dark (txs)``` style in Windows but not in Ubuntu. Is it possible to use that style in Ubuntu?

**Comment by sunderme** [comment]
adwaita-qt is provided as a package in the ubuntu package repository

**Comment by bahman-mirzakhani** [comment]
Thanks so much.
