### ISSUE TITLE
I can no longer discern which tex document I'm in by the tab's appearence

### ISSUE THREAD

**Issue by brnbne** [texstudio-org/texstudio#1604]
### Environment
- TeXstudio: 3.1.1
- Qt: 5.15.2, compiled with Qt 5.15.2 R
- OS: Windows 10
- TeX distribution:  miktex
__
### Description

~~The new style for the tabs of open tex documents makes it very difficult to tell which document I'm in, much more difficult than its previous appearance.~~ 

![image](https://user-images.githubusercontent.com/42383478/115657736-05a42080-a2fd-11eb-9fc5-377444e3f787.png)
~~How long will it take you to determine which of these TWO tabs I'm in? And usually I have 6 or 7 tabs open, so this has become a real inconvenience. I'd appreciate a button in the Configure menu to use the old style instead.~~

Never been accused of being bright.

**Comment by sunderme** [comment]
Options/General/Style ?
