### ISSUE TITLE
Issue in include graphics

### ISSUE THREAD

**Issue by saisidd1963** [texstudio-org/texstudio#1606]
Whatever file i put in the include it shows image not found...although was in same directory...please review this issue..note that i have included all packages i am aware i am in right directory

**Comment by sunderme** [comment]
sounds like tex issue. please go to tex.stackexchange.com
On a general note, a working example ,i.e. the actual document plus the image is necessary for someone to actualy debug the issue.
As said, above includegraphics has nothing to do with txs (the text editor).
