### ISSUE TITLE
Disable auto Compilation

### ISSUE THREAD

**Issue by Manjoy** [texstudio-org/texstudio#1608]
### Environment
- TeXstudio: 3.1.1
- Qt: 
- OS:  Windows 7, 64 bit
- TeX distribution:  MiKTeX 2.9

### Description

How do I stop auto compilation in TexStudio? Every time I stop typing, it starts compiling.

https://user-images.githubusercontent.com/83311841/116410061-0a635a00-a852-11eb-935b-26b78d26b946.mp4

**Comment by sunderme** [comment]
Some contextbis missing.
In principle txs does not auto-compile.
It does so however for inline previews and maybe other previews.
So, a screencastbwhich shows the issue would be helpful.

**Comment by Manjoy** [comment]
The compiler takes very short time to compile. By this time, capturing
screenshot is not possible.

At first there was some problem regarding the updation of MiKTeX console
and the package updation. Some error was occuring while updating and a
pop-up was coming up on the screen. So I changed the server setting and
connected with a China server. After this incident, the auto compilation
has started. Is there any connection between these server changing and auto
compilation?

**Comment by sunderme** [comment]
txs does not auto compile
if txs executes compiles, there are messages in the message pane.
Screen cast is recording a movie of your activities...

**Comment by Manjoy** [comment]
I have added a screencast.

**Comment by sunderme** [comment]
What macros do you have set up ?

**Comment by Manjoy** [comment]
In the video, I was working inside `\begin{circuitikz}...\end{circuitikz}`

**Comment by sunderme** [comment]
macro here means, menu "Macros"

**Comment by Manjoy** [comment]
Honestly speaking, I don't know. I have no idea about it. I search in
goohle how to find it. But I got no clue.

**Comment by sunderme** [comment]
just open the macros-menu and open the macro editor.

**Comment by sunderme** [comment]
other point maybe. Does it occur with an new document, no other documents open.
(please restart with no open document)

**Comment by Manjoy** [comment]
Actually it was happening due to ticking a checkbox in Internal pdf viewer
-> auto-recompile document on changes.

But after unchecking that box, now I am facing a big problem. The compiler
is not stopping compilation and seems that the file is corrupted. A big
worry for me!!!

**Comment by sunderme** [comment]
escape ?
Stop compile ? restart ?

**Comment by Manjoy** [comment]
Restarted many times. Deleted .aux file and started compiling. No positive
result.

Compiling continues but getting new errors in log pane. E.g
1. File ended while scanning use of ***@***.*** \begin{document}

2. Now I am getting 'package tikz error:(..)'

**Comment by sunderme** [comment]
you can compile from command line if txs compilation is messed.
But it sounds like a regular tex problem.

**Comment by Manjoy** [comment]
What do I do now? It's getting over my head. It's very important document
and I have gone so far till now. I can't leave it behind now.

**Comment by Manjoy** [comment]
I cut all the document and compiled just commands together with
\begin{document}...\end{document}.. now it stops compiling. But in the
right side where I see the pdf, there is a note:* '....pdf does not look
like a valid pdf document. Either the file is corrupt or it is in the
process of creation. Retrying every two seconds.'*

**Comment by sunderme** [comment]
easiest way would be to ask someone who knows latex and can directly interact with the document and your computer. It is impossible to debug with just hints on error messages when the options are changed, the document is unknown and what else is non-standard.

**Comment by Manjoy** [comment]
Ok, thanks.
