### ISSUE TITLE
Can't start the program normally

### ISSUE THREAD

**Issue by zongxian** [texstudio-org/texstudio#1609]
The program cannot be started when I try **version 3.1.1.0 and version 3.1.2.0**.

There is no problem with **version 3.0.4.0**, so I can only reinstall the old version. 

By checking the system information (Win10 20h2), there may be some problems with the **ntdll.dll** module, and give **Exception code: 0xc00000fd**. 

I hope this information can help you. 

错误应用程序名称: texstudio.exe，版本: 3.1.2.0，时间戳: 0x607acae1
错误模块名称: ntdll.dll，版本: 10.0.19041.928，时间戳: 0x9bed63d6
异常代码: 0xc00000fd
错误偏移量: 0x000000000002b866
错误进程 ID: 0xcb4
错误应用程序启动时间: 0x01d73716ab146917
错误应用程序路径: C:\Program Files\texstudio\texstudio.exe
错误模块路径: C:\WINDOWS\SYSTEM32\ntdll.dll

**Comment by sunderme** [comment]
are you using an old indows version ?

**Comment by zongxian** [comment]
> are you using an old indows version ?

Are you mean the Windows version? It is Win10 20h2, latest version.

**Comment by sunderme** [comment]
works fine here 
reinstall ?

**Comment by zongxian** [comment]
> works fine here
> reinstall ?
I tried many times, but it still doesn't work, and I also ran the Portable version, but it didn't work either.

**Comment by sunderme** [comment]
not really anything I can do

**Comment by sunderme** [comment]
wait, are you using 32bit windows ?

**Comment by zongxian** [comment]
> wait, are you using 32bit windows ?

not 32bit, it is 64bit windows 10.

**Comment by sunderme** [comment]
nothing I can do
