### ISSUE TITLE
TikZ auto-completing to deprecated "left/right/above/below of=" syntax

### ISSUE THREAD

**Issue by bogger33** [texstudio-org/texstudio#1610]
### Environment
- TeXstudio: TeXstudio 2.12.14 (Build: 2.12.14+debian-1)
- Qt: Qt Version 5.11.3, compiled with Qt 5.11.2 R
- OS: LMDE
- TeX distribution: pdflatex

### Expected behavior

I create/edit a \node and want to specify its location in the square bracket. If i type "b", it's automatically expanded to "below of="

but this is deprecated syntax. it should be "below=of ".

See here e.g.: https://tex.stackexchange.com/questions/9386/difference-between-right-of-and-right-of-in-pgf-tikz

**Comment by sunderme** [comment]
txs 2.12.14 is obsolete, update to current version 
And current version suggests below=of ...

**Comment by muzimuzhi** [comment]
More precisely, those cwl lines were removed by https://github.com/texstudio-org/texstudio/commit/063323710d276e7324adb431352a2b55a7ca09b5, and the change took effect since v2.12.18beta1.
