### ISSUE TITLE
auto complete triggers without waiting for user confirmation in some situations

### ISSUE THREAD

**Issue by bogger33** [texstudio-org/texstudio#1611]
### Environment
- TeXstudio: TeXstudio 2.12.14 (Build: 2.12.14+debian-1)
- Qt: Qt Version 5.11.3, compiled with Qt 5.11.2 R
- OS: LMDE
- TeX distribution: pdflatex

### Expected behavior
normally I'd have to hit enter for auto complete to actually insert its suggestion, but in some circumstances this is not the case.

This is a little strange, so I start in the tikzpicture environment, creating a new node:
```
\begin{tikzpicture}
\node[]

\end{tikzpicture}
```

if i now move my cursor between the brackets and type "b", it automatically expands that to "below of=" without having to press anything except the b key. I would expect it to suggest "below of=" (or rather "below=of ", see #1610), but not to actually fill it in until I press enter.

This is particularly annoying as it also happens when you have text selected. Quite often I come back to something, e.g. I already have a node that looks out like this:
`\node[state, right=of q1] (q2) {$q_2$};`

and then I figure out that the node should actually be below q1, not right of it, so I highlight the text segment "right" and start typing "b", and the whole thing is automatically replaced with 
`\node[state, below of=of q1] (q2) {$q_2$};`
which is not valid syntax at all, and I'll usually type out a few more characters of the word "below" before i catch on to it

**Comment by sunderme** [comment]
please provide a full example, including the packages you use.
I don't see the described behaviour.

**Comment by sunderme** [comment]
again, old version. please update

**Comment by sunderme** [comment]
no feedback

**Comment by bogger33** [comment]
just to confirm, this problem was fixed in the new version, sorry for the erroneous reports. I didn't realize the version in the debian repositories was so out of date, thanks for the responses
