### ISSUE TITLE
Disable spell checking through magic comments

### ISSUE THREAD

**Issue by henrikgit** [texstudio-org/texstudio#1613]
Searching for this issue on google, I found an old thread on TeX.sx: https://tex.stackexchange.com/questions/338291/disable-spell-checking-through-magic-comments

I hereby would like to ask for a new feature (enhancement), i.e. to make it possible to disable spell-checking (which could already be activated in TeXstudio's options) for the `.tex`-file which has the "magic comment" `% !TeX spellcheck = disable` or something similar in it. :)

**Comment by sunderme** [comment]
why ?

**Comment by henrikgit** [comment]
Oh. Thank you for the quick reply. :) 

Well, sometimes the one language that can be set with the magic command, isn't necessarily the one that is the (only) relevant one for that file.

This is true for `.tex`-files, where there is content in different languages put in these files. If one sets the language to `en_US`, obviously all, say, French, Spanish and German parts would get the red wave under them. Yes, it is truly awesome the simple way the magic comment works and one could use it to check the relevant parts for the case-based enabled languages when you switch the settings.

But then, after that, all you can do is either set one language or disable spell-checking altogether.

=> So I would prefer to have the spell-checking disabled for that specific file with the help of a magic comment. I would prefer that over a) to continuously see the red waves for all the parts which do not fit the one language defined via the "magic comment" or b) turn off spell-checking overall.

To be fair:  It is just a wish for of a better quality-of-life aspect, I suppose.

**Comment by sunderme** [comment]
it turns out, this is already implemented.
The language to ```none```
