### ISSUE TITLE
Comment-environments blocks/prevents inverse search from working (cursor does not to jump to its target)

### ISSUE THREAD

**Issue by henrikgit** [texstudio-org/texstudio#1614]
### Environment
- TeXstudio: TeXstudio 3.1.1 (git n/a)
- Qt: Qt-Version 5.15.2, kompiliert mit Qt 5.15.2 R
- OS:  Linux (Arch)
- TeX distribution: texlive-bin 2020.54586-14 (output of running `pacman -Q texlive-bin`)

### Expected behavior

Inverse search behavior works as intended and the cursor goes/jumps to the relevant source code part.

### Actual behavior

The cursor does not jump to the relevant source code part.

### How to reproduce

C & p the following `.tex` code into a document and compile it. Try to go to source.

If you comment out the lines with `\begin{len}` and `\end{len}` for one environment in the document, inverse search works again.

	\documentclass[parskip=full]{scrartcl}

	\usepackage{
	lmodern,
	}

	\usepackage{comment}
	\usepackage[T1]{fontenc}

	\newenvironment{len}{%
	\selectlanguage{english}}
	{}

	\newenvironment{lde}{%
	\selectlanguage{german}}
	{}

	\includecomment{len}
	\excludecomment{lde}

	\begin{len}
	\usepackage[english]{babel}
	\end{len}

	\listfiles

	\begin{document}
	\begin{len}
	Abc.
	Def.

	123.
	456.

	EGJSDFGJ.
	DDDDDDDDD.
	EEEEEEEEE.

	FFFFFFF.
	GGGGGG.
	\end{len}
	\clearpage
	\begin{len}
	Page 2: some words to form a sentence.
	\end{len}
	\end{document}

**Comment by sunderme** [comment]
so, we are talking about synctex and pdf/text synchronozation.

**Comment by sunderme** [comment]
same with texworks.
It is a synctex issue, nothing we can do.

**Comment by henrikgit** [comment]
Ok. Hm. :(

Thank you for getting back to me so quickly!

**Comment by henrikgit** [comment]
It seems to be a rather [old issue](https://tex.stackexchange.com/questions/163951/synctex-go-to-source-from-pdf-and-comment-package). 

Seeing this has been addressed by users already in 2013 and still is a real obstacle in 2021, imho I think it is fair to close this issue. (Unless you want to keep it open for *any* reason.) Since I do not know the rules & guidelines about this software's closing etiquette, I gladly leave it up to you.
