### ISSUE TITLE
The style of appearance "windowsvista" disappeared since TeXstudio version 3.0.5

### ISSUE THREAD

**Issue by suc1997** [texstudio-org/texstudio#1616]
Hi TeXstudio developers,
Recently I updated my TeXstudio to the latest version (3.1.1) and then found that the appearance changed. After checking configurations, I noticed that there should have been a style of appearance called "windowsvista" while it disappeared, which also changed the "default" style on Windows. After testing some versions of TeXstudio, I found that I can see that style in version 3.0.4, but not in 3.0.5. I know that it's of low priority, but I'm sure there must be someone else who like this style. I hope it could be added in a future release. I really appreciate all of your contributions.
Sincerely.

![Snipaste_2021-05-06_00-36-04](https://user-images.githubusercontent.com/25244664/117176985-17a8b780-ae03-11eb-92ba-8eebb46ed09c.png)

### Environment
- TeXstudio: 3.0.5 and newer
- Qt: 5.15.2 (in TeXstudio 3.0.5)
- OS: Windows 10 (1709)
- TeX distribution: texlive

**Comment by sunderme** [comment]
try the 3.1.2beta

**Comment by suc1997** [comment]
> 
> 
> try the 3.1.2beta

I find it, thank you! I'm looking forward to the stable release now.
