### ISSUE TITLE
Some icons are too small under 4K display

### ISSUE THREAD

**Issue by LetianHub** [texstudio-org/texstudio#1617]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior
I expected the new version of texstudio will have a better scaling for 4K display.

### Actual behavior
Some icons are too small, such as the closed button, the magnify button and the enlarge-viewer button. Their sizes cannot be changed in the configuration.
 
![Screenshot 2021-05-06 094823](https://user-images.githubusercontent.com/55523866/117230773-587aed80-ae50-11eb-9b7f-a5c7ed9ecffc.png)

**Comment by sunderme** [comment]
looks like a qt/window issue

**Comment by sunderme** [comment]
looks fine on 4.0.4 (qt6)
