### ISSUE TITLE
Placeholder for parentheses with multiple characters in autocompletion

### ISSUE THREAD

**Issue by dzhy444** [texstudio-org/texstudio#1619]
### Environment

- TeXstudio: 3.1.1
- Qt: Qt 5.15.2
- OS: Windows 10

### Describe the feature and the current behavior/state

For parentheses with multiple characters like \\[...\\] and \\{...\\}, the right parentheses \\] and \\} are not placeholders. If one types the \\] or \\} one would get duplicate parentheses. 

I would like to have the feature to make \\], \\} etc. placeholders, so that they "eat" characters when one types the right parentheses.

**Comment by sunderme** [comment]
using placeholders was disabled intentionally 
```
// don't set placeholder for commands e.g. \} or \left as it pretty much inhibits enterring normal commands
```
I'll stick with that evaluation by Tim (?)
