### ISSUE TITLE
Global TOC - selection won't work

### ISSUE THREAD

**Issue by leomayer** [texstudio-org/texstudio#1621]
### Environment
- TeXstudio: 3.1.1
- Qt: 5.15.2
- OS: Linux, OpenSusue

### Behavior

In the sidebar I can see the TOC of a document - which is great. I have a document which structures into different directories, e.g. `images` or `definitions` (e.g. `macros`). The files are displayed. Some files are marked with a blue marker (see below).
I guess this means that they don't have additional sub-structures. 

When I click on them the files won't open. When I click on the main item it just collapses or opens. (When I click on the one with `S` the file is opened)

I would expect that in both scenarios 

- either the file is already open than switch to it (to the last cursor position)
- or just open it an place the cursor at the first position

This would be especially helpful when working with complex tex-structure.

![blue marker ](https://user-images.githubusercontent.com/2641128/118020963-06a7fb00-b35b-11eb-873b-4065793f3db5.png)

**Comment by sunderme** [comment]
please provide a complete working example (zip with all the files)

**Comment by leomayer** [comment]
Find attached a simplified sample. That's a reduction of my current working set. Selections in the TOCs are not done - as described already.

[test-1621.zip](https://github.com/texstudio-org/texstudio/files/6471636/test-1621.zip)

**Comment by sunderme** [comment]
is already fixed in the dev code.
