### ISSUE TITLE
Crash when doing right click in TOC view

### ISSUE THREAD

**Issue by the-voidl** [texstudio-org/texstudio#1623]
### Environment
- TeXstudio: 3.1.1 (installed via pacman)
- Qt: 5.12.2 R
- OS: Linux Manjaro 5.12.1-2
- TeX distribution: texlive

### Expected behavior
Texstudio doing nothing.

### Actual behavior
Texstudio crashes (with dialog that is able to restore the editor).

### How to reproduce
Open "TOC" view in the left navigation panel.
Do a right click in an empty space below the displayed sections.

This isn't reproducible in "Structure" or any other navigation view.

#### Backtrace
```
SIGSEGV (TXS-Version  R )                                       
[bt] texstudio(_ZN12SimulatedCPU13set_from_realEv+0) [0x55bcc15c40f0] 
```

**Comment by sunderme** [comment]
please upgrade to 3.1.2
should be fixed there
