### ISSUE TITLE
Pagenumberfield too small in OrionDark

### ISSUE THREAD

**Issue by TheRisenPhoenix** [texstudio-org/texstudio#1624]
When using OrionDark theme, the page number field in the internal PDF viewer only shows one digit of the current page number. When navigating inside, you can move the cursor to explore the whole number of the current page, but in the other themes, the number is completely visible.

### Environment
- TeXstudio: 3.1.2
- Qt: 5.15.2
- OS: Windows 10
- Resolution is 2560x1440

### Expected behavior
As in all the other themes, the whole number of the current page should be visible.

### Actual behavior
The field is too small and only shows one digit at a time

### How to reproduce
Switch to OrionDark and have a PDF with 10+ pages.

![Truncated](https://user-images.githubusercontent.com/43245438/118226845-cdb97480-b487-11eb-9425-2d6ea74855bd.png)
(this is the truncated version, actually I'm on page 28 here)

**Comment by sunderme** [comment]
I don't see the issue here.
What did you set as style/color scheme. 2 monitors ? scaling ?

**Comment by TheRisenPhoenix** [comment]
It happens for me with all three color schemes (classic/modern/modern dark), but only when style is set OrionDark. All other styles work fine.
I indeed use two monitors. The one I saw the issue first with is 2560x1440, 100% scaling. I just tried with the second monitor, 4k with 250% , and it has the same issue, even stronger (which is okay I guess, but at least the 100% version should work). 
The workaround suggested by pagenum solves the issue.

**Comment by pagenum** [comment]
I only have 1 monitor. The resolution is 1920x1080. 100% scaling.
Also the language of my operation system is not English.

**Comment by pagenum** [comment]
> A workaround:
> create a new file: "stylesheet.qss" in %APPDATA%\texstudio
> 
> the content of "stylesheet.qss":
> 
> ```
> QLineEdit {
> 	border-left-width: -5px;
> 	border-right-width: -5px;
> }
> ```
This looks better:
`QLineEdit {
	padding: 0px -2px 0px 0px;
}`
