### ISSUE TITLE
Tooltips show after end-of-line when last word on line is a LaTeX command

### ISSUE THREAD

**Issue by Markus74a** [texstudio-org/texstudio#1625]
### Environment
- TeXstudio: 3.1.2
- Qt: 5.15.2
- OS: Windows 10 20H2
- TeX distribution: TeXlive 2021

### Expected behavior
TeXstudio shows tooltips **only** when doing a mouse-over on LaTeX commands in the edit window.

### Actual behavior
The region of the mouse-over area is extended to the right side of the screen if a LaTeX blackslash-command without parameters is used at the end of the line.

It is very annoying in tables, where a `\\` command is at the end of every line, but `\par`, `\item` and other commands without parameters will also cause this effect if no normal text follows.

### How to reproduce
Mouse-over any of the regions marked with RED color.
[screenshot](https://user-images.githubusercontent.com/74558820/118247194-319d6680-b4a3-11eb-83e2-e1f1ef10983b.jpg)
TeXstudio will show the tooltip of the command at the end of the line everywhere.

**Comment by Markus74a** [comment]
This bugfix introduced a different problem.

If text needs to be shown on several lines because it is too long for one line, keyboard navigation will not work correctly any more in that paragraph.

Lets say the text is `abcd efgh ijkl mno pqr stu vwx yz` and assume it needs to be placed on 3 lines because it doesn't fit into 1 line. It might look like this:
```
abcd efgh ijkl
mno pqr stu
vwx yz
```
If the edit cursor is after the `j`, `k`or `l`and you press the `<down>` key, it will **not** go to the `u`, but jump to the `a`.
If the edit cursor is after the `r`, `s`, `t`or `u`and you press the `<down>` key, it will **not** go to the `z`, but jump to the `a`.

You end up in an endless loop, you won't be able to navigate this text block by keyboard any more and have to use the mouse.

**Comment by sunderme** [comment]
should be fixed now
