### ISSUE TITLE
Page number in the pdf viewer toolbar cannot display

### ISSUE THREAD

**Issue by pagenum** [texstudio-org/texstudio#1628]
### Environment
- TeXstudio: 3.1.2
- Qt: 5.15.2
- OS: Win 10 20H2
- TeX distribution: texlive

### Expected behavior
There should be a page number. If I don't use dark theme (adwaita or orion) it can display

### Actual behavior
The page number is missing. I think the space is too small so it cannot display. Could you make it bigger? 
![未命名](https://user-images.githubusercontent.com/84386759/118645520-9cd39980-b811-11eb-9332-9017ee90dc8e.png)

### How to reproduce
Switch to dark theme

**Comment by sunderme** [comment]
What did you set as style/color scheme. 2 monitors ? scaling ?
