### ISSUE TITLE
Open file dialog always start at $HOME directory

### ISSUE THREAD

**Issue by russell-lai** [texstudio-org/texstudio#1629]
On Manjaro running Gnome 3.38.4, if the "Use system file dialogs" option is not ticked, then the open file dialog expectedly starts at the directory where the currently opened file is located. However if the "Use system file dialogs" option is ticked, then the GTK open file dialog always starts at either "Recent" if "org.gtk.Settings.FileChooser startup-mode" is set to 'recent' and "Home" if it is set to "cwd". 

I think this is a bug on Texstudio's side since setting "org.gtk.Settings.FileChooser startup-mode" to "cwd" causes other applications, e.g. Sublime Text, to start the GTK open file dialog at the current working directory, as expected, but not for TexStudio.

### Environment
- TeXstudio: 3.1.1
- Qt: 5.15.2
- OS: Manjaro Linux x86_64 
- TeX distribution: TeX Live 2021

### Expected behavior

If "org.gtk.Settings.FileChooser startup-mode" is set to "cwk", and the "Use system file dialogs" option in TexStudio is ticked, the open file dialog should start at the current working directory.

### Actual behavior

The open file dialog always starts at the home directory.

### How to reproduce

1. Execute 
gsettings set org.gtk.Settings.FileChooser startup-mode cwd
at the terminal.
2. Make sure the "Use system file dialogs" option in TexStudio is ticked.
3. Ctrl+O in TexStudio

**Comment by sunderme** [comment]
not sure txs is culpable. 
Qt has an option to use native/non-native file dialog and that is it. I doubt that QT reads gtk settings.

**Comment by russell-lai** [comment]
> not sure txs is culpable.
> Qt has an option to use native/non-native file dialog and that is it. I doubt that QT reads gtk settings.

From my experiment, changing the "org.gtk.Settings.FileChooser startup-mode" setting indeed affects TexStudio -- setting it to "recent" makes the file dialog always open at "Recent", while setting it to "cwd" makes the file dialog always open at "Home". 

My understanding is that, with the "org.gtk.Settings.FileChooser startup-mode" set to "cwd", unless the application (TexStudio) tells gtk where to look at, it defaults to home. So I suspect that either TexStudio doesn't tell gtk to look at the correct directory, or it does but gtk doesn't understand.

**Comment by sunderme** [comment]
txs does not influence the dialog apart from telling Qt to use the native dialog.
If that does not work, Qt is probably to blame.
Nothing we can do.
