### ISSUE TITLE
Forward search works improperly for the second paragraph of a page

### ISSUE THREAD

**Issue by dzhy444** [texstudio-org/texstudio#1631]
### Environment
- TeXstudio: 3.1.2
- Qt: 5.15.2
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
When using forwards search, the current paragraph in the pdf preview should be highlighted.

### Actual behavior
Instead of the current paragraph, the title of the previous page is highlighted. This usually happens in the second paragraph of a page, if the first paragraph has overlap with previous page.

### How to reproduce
[ForwardSearch.zip](https://github.com/texstudio-org/texstudio/files/6525701/ForwardSearch.zip)
Try forward search in the paragraph
"Forward search of this paragraph does not work."
on line 3 of page 3.

**Comment by sunderme** [comment]
It is the same with texworks.
Synctex is the library which is used for this. Please report at https://github.com/jlaurens/synctex (though develoment weems not to be very active).

**Comment by sunderme** [comment]
synctex issue, nothing txs can do directly
