### ISSUE TITLE
Bug on Menu (Chinese Version)

### ISSUE THREAD

**Issue by 1900011604** [texstudio-org/texstudio#1632]
![1](https://user-images.githubusercontent.com/65082432/119247039-263fee80-bbb9-11eb-9c43-611646ec5289.jpg)

无衬线f --> 无衬线字体 @muzimuzhi

**Comment by sunderme** [comment]
translation is done via https://www.transifex.com/texstudio/texstudio/languages/

**Comment by muzimuzhi** [comment]
Corrected on transifex.com, see https://www.transifex.com/texstudio/texstudio/translate/#zh_CN/texstudio_ents/85523398 .

**Comment by 1900011604** [comment]
![Screenshot_20210524_222504](https://user-images.githubusercontent.com/65082432/119364368-67cbb900-bce1-11eb-8b40-be1130b61e5d.png)

you can see that "对其方式" should also be changed to "对齐方式", I did it on https://www.transifex.com/texstudio/texstudio/translate/#zh_CN/texstudio_ents/60321133?q=text%3Aalign

PS: I think the Chinese Translation can be reviewed.
