### ISSUE TITLE
Chinese parentheses left part overlap with the next english character when typing more than two english characters

### ISSUE THREAD

**Issue by erusyd** [texstudio-org/texstudio#1634]
### Environment
- TeXstudio: 3.1.2
- Qt: 5.15.2
- OS: Windows 10
- TeX distribution: miktex

### Actual behavior
Chinese parentheses left part overlap with next the english character when typing **more than two** english characters.

### How to reproduce
open a xxx.tex file, type this:
 （abc
you should see the overlap.
<img width="106" alt="mx_screencap_20210525_111509" src="https://user-images.githubusercontent.com/1529102/119434356-9b8ef900-bd4a-11eb-927f-c200343ab07a.png">

**Comment by muzimuzhi** [comment]
Does the setting shown in https://github.com/texstudio-org/texstudio/issues/1099#issuecomment-632485580 help?

**Comment by erusyd** [comment]
> 
> 
> 高级编辑器 --> 破解/变通 --> 取消勾选“自动选择最佳显示选项”，并勾选“禁用字符宽度缓存”和“关闭固定位置模式”

**Comment by erusyd** [comment]
Thanks all, it works.
