### ISSUE TITLE
Wrong Behaviour in `\left[(cursor)\right]`

### ISSUE THREAD

**Issue by 1900011604** [texstudio-org/texstudio#1636]
### Environment
- TeXstudio: 3.1.2
- OS: Linux (Manjaro)
- TeX distribution: texlive 2021

### Expected behavior

Disable "Insert arguments", Enable "Arguments as placeholders": `\left[(cursor)\right]`

Enable "Insert arguments", Enable "Arguments as placeholders": `\left[(cursor)\right]`

### Actual behavior

Disable "Insert arguments", Enable "Arguments as placeholders": `\left[\right](cursor)`

Enable "Insert arguments", Enable "Arguments as placeholders": `\left[(cursor)\right]`

### How to reproduce

Configure them in "Configure TeXstudio"

**Comment by sunderme** [comment]
I don't concur with the first expectation: 
```Disable "Insert arguments", Enable "Arguments as placeholders": \left[(cursor)\right]```
The cursor is placed at the first argument (or where specified in the arguments). If there is no argument, it is placed after the inserted text.

**Comment by 1900011604** [comment]
What about putting a `%|` in it? like `\left[%|\right]`

**Comment by sunderme** [comment]
I don't see any benefit.

**Comment by sunderme** [comment]
I don‘t see described behavior as erroneneous -> closed

**Comment by 1900011604** [comment]
Maybe this should be a feature request, I consider num, den, width, position etc. are arguments and `%|` are placeholders.

One settings is to control that if there is a placeholder `%|` (is as default)

Another settings is to control that if the `%|` is replaced as `<arguments|%|>`

Not all people want to delete the arguments before inserting, but prefer a clean one

**Comment by dbitouze** [comment]
> Not all people want to delete the arguments before inserting, but prefer a clean one

It is worth mentioning that it isn't necessary to _delete_: you can just start to write what you want.

**Comment by 1900011604** [comment]
> > Not all people want to delete the arguments before inserting, but prefer a clean one
> 
> It is worth mentioning that it isn't necessary to _delete_: you can just start to write what you want.

Not all, for example, in `\tfrac{num}{den}`, I can start with `num` but I should delete the `den`

**Comment by dbitouze** [comment]
> Not all, for example, in `\tfrac{num}{den}`, I can start with `num` but I should delete the `den`

Yes, it is possible here as well: on Linux and Windows, once you have replaced `num`, just hit <kbd>Ctrl</kbd>+<kbd>➝</kbd> and then replace `den`.

**Comment by 1900011604** [comment]
Thanks for your advice, although I still think this would be better.

> Maybe this should be a feature request, I consider num, den, width, position etc. are arguments and `%|` are placeholders.
> 
> One settings is to control that if there **is** a placeholder `%|` (**is** as default)
> 
> Another settings is to control that if the `%|` is replaced as `<arguments|%|>`

**Comment by 1900011604** [comment]
What I said in this issue is same as what is done by [LaTeX Workshop](https://github.com/James-Yu/LaTeX-Workshop), you can see there.

https://github.com/James-Yu/LaTeX-Workshop
