### ISSUE TITLE
Text not shown on embedded PDF figures in internal PDF viewer

### ISSUE THREAD

**Issue by jnrobinson** [texstudio-org/texstudio#1637]
### Environment
- TeXstudio: 3.1.2
- Qt: 5.15.2
- OS: 11.3.1
- TeX distribution: MacTeX

### Expected behavior
Text in embedded PDF files should be visible in internal PDF viewer.

### Actual behavior
Text is not visible in PDF figures produced using MATLAB's exportgraphics function, and also on some, but not all, third-party PDF files. If the project document is opened in an external PDF viewer, the text appears appropriately.

I was not experiencing this bug on previous versions of TeXstudio on other computers, but it has been present on my new laptop since I first downloaded TeXstudio 3.1.2. The issue may be related to M1 processors.

Demonstration (Preview.app on the left, TeXstudio internal viewer on the right):
![Screen Shot 2021-05-25 at 11 13 30 AM](https://user-images.githubusercontent.com/25557902/119522775-3dfaac80-bd4a-11eb-8179-40786adbf8cc.png)

**Comment by sunderme** [comment]
my guess is that the font of the included pdf is not embedded into the file. 
Font searching of poppler on mac is a bit of a mess. texworks patches poppler before using it but I have abandoned that as it makes things complicated with using homebrew. Unless a mac user steps up, that is how it is.

**Comment by jnrobinson** [comment]
> my guess is that the font of the included pdf is not embedded into the file.
> Font searching of poppler on mac is a bit of a mess. texworks patches poppler before using it but I have abandoned that as it makes things complicated with using homebrew. Unless a mac user steps up, that is how it is.

If the font isn't embedded, why would it show up fine in Preview but not in TeXstudio? Also, wouldn't TeXstudio try to replace the font with a different one rather than omitting the text entirely?

Failing any possible bugfixes, would my best option be to convert PDFs to high resolution PNGs before embedding them?

**Comment by sunderme** [comment]
preview uses some mac fonts, poppler looks for X server fonts. If X server is not installed, poppler does not find the font in question.
You can install txs via homebrew (which installs poppler and probably fonts for it)
Conversion to pdf might offer the embedding of fonts, maybe you can look at matlab docs.

**Comment by jnrobinson** [comment]
> preview uses some mac fonts, poppler looks for X server fonts. If X server is not installed, poppler does not find the font in question.
> You can install txs via homebrew (which installs poppler and probably fonts for it)
> Conversion to pdf might offer the embedding of fonts, maybe you can look at matlab docs.

I just tried installing with homebrew, but that didn't fix the issue. I also tried deleting the texstudio folder in ~/.config before installing so it would be more clean, but that didn't have any effect.

I previously installed XQuartz, so I believe I already have X server installed.

I guess I'll try switching to texmaker, which doesn't seem to have the same issue.

**Comment by sunderme** [comment]
as said, the font embedding is a guess.
No further steps are taken, so I close the issue.

**Comment by muzimuzhi** [comment]
> Text is not visible in PDF figures produced using MATLAB's exportgraphics function, and also on some, but not all, third-party PDF files. If the project document is opened in an external PDF viewer, the text appears appropriately.

@jnrobinson I don't use MATLAB. Can you please share a sample PDF figure so I can test with it on Intel Mac?

**Comment by jnrobinson** [comment]
> > Text is not visible in PDF figures produced using MATLAB's exportgraphics function, and also on some, but not all, third-party PDF files. If the project document is opened in an external PDF viewer, the text appears appropriately.
> 
> @jnrobinson I don't use MATLAB. Can you please share a sample PDF figure so I can test with it on Intel Mac?

Yes, here is the figure from the example:

[cifp_airports.pdf](https://github.com/texstudio-org/texstudio/files/6542737/cifp_airports.pdf)

**Comment by muzimuzhi** [comment]
It works OK on Intel Mac, with macOS 11.1 + texstudio 3.1.2. 

> my guess is that the font of the included pdf is not embedded into the file.

And @sunderme's guess is right, see

```
# get pdffonts from poppler, e.g. `brew info poppler`

$ pdffonts cifp_airports.pdf
Fontconfig warning: ignoring UTF-8: not a valid region tag
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
Helvetica                            Type 1            WinAnsi          no  no  no      14  0
Times-Roman                          Type 1            WinAnsi          no  no  no      15  0
```

Maybe you could try letting MATLAB embed the used fonts into PDF.
