### ISSUE TITLE
Placeholder shortcuts changing semi-randomly when pressing Ok-Button of Configure TeXstudio

### ISSUE THREAD

**Issue by chrisitanw** [texstudio-org/texstudio#1639]
After configuring TeXstudio, the editor doesn't handle circumflexes properly. E.g. after typing circumflexes it jumps to the previous placeholder. 
MWE:
Typing $\frac{}{}$ and then typing in the first bracket e.g. "x^2" (exactly these three buttons) yields $\frac{x^}{}$, i.e. with the 2 missing and the cursor blinking between "{x".

[Here](https://sourceforge.net/p/texstudio/bugs/539/) the problem is described already, however, since it's from 2012 I had hoped it would be fixed?

### Environment
- TeXstudio 3.1.2 (git 3.1.2)
Using Qt Version 5.15.2, compiled with Qt 5.15.2 R

### Expected behavior
Typing e.g. $\frac{}{}$ and then typing in the first bracket "x^2" should give $\frac{x^2}{}$ and the cursor residing between "2}".

### Actual behavior
Typing e.g. $\frac{}{}$ and then typing in the first bracket e.g. "x^2" gives $\frac{x^}{}$ and the cursor residing between "{x".

### How to reproduce
I figured out it has to do with the configuration of TeXstudio. 
When starting a new version of TeXstudio, the bug is not present. However, after going to Options -> Configure TeXstudio -> Pressing Ok button (without changing the configuration in any way!) the behavior described above occurs. One can reset it by resetting TeXstudio to its default configuration. 
You can also see that after pressing the Ok-button of the configuration once, the Basic Keymappings of some Previous Placerholder changes from "< n o n e >" to <    > (empty), even though you haven't touched it.

**Comment by sunderme** [comment]
which OS ?
Can you upload a screencast of what you are doing?

**Comment by chrisitanw** [comment]
Windows 10.

Unfortunately my laptop doesn't have the hardware for a screencap, so here's a poor man's version recorded with a phone: https://www.youtube.com/watch?v=zAsoesSRpw8

**Comment by sunderme** [comment]
what keyboard layout are using ?

by the way, there are many programs to record screencasts, including win10 in game mode ( or whatever they call it)

**Comment by chrisitanw** [comment]
German keyboard layout, and I indeed tried the Win10 screencast, but got the error message that my hardware doesn't suffice.

**Comment by sunderme** [comment]
looks like txs/win10 bug
