### ISSUE TITLE
Native support of Apple Silicon for TexStudio

### ISSUE THREAD

**Issue by Hanna-S-1995** [texstudio-org/texstudio#1642]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Description

Sorry, in the other post there was a mistake. I mean:
when will TexStudio (!) run natively on Apple Silicon? Are there any timelines/roadmaps? (for nebies, who cannot build their own version.)

**Comment by sunderme** [comment]
the answer is still the same.
txs is build by github build chains. When they offer M1 support, that will be activated.
Using homebrew is simple, they seem to offer M1 support. (see brew.sh)
Building txs on its own also involves homebrew.
So, no time line as it depends on external circumstances.
txs should build fine on M1 without a problem, so the whole issue is just a question of infrastructure.

**Comment by BrushXue** [comment]
> Using homebrew is simple, they seem to offer M1 support. (see brew.sh)

https://github.com/Homebrew/homebrew-cask/blob/1884cd8058c6f9868fd27cfc6de316c93112c844/Casks/texstudio.rb
It's just downloading the official .dmg and extract.

I tried to build 3.1.2 using Qt 5.15.2. Seems good for now. The only problem is `Could not find qmake spec 'macx-clang'`. The new spec is `macx-clang-arm64` so `BUILD.sh` needs to be changed accordingly(maybe add something like `case $(uname -m) in`).
