### ISSUE TITLE
Update siunitx.cwl for siunitx version 3

### ISSUE THREAD

**Issue by kiriya-aoi** [texstudio-org/texstudio#1643]
### Environment
- TeXstudio: TeXstudio 3.1.2 (git 3.1.2)
- Qt: Using Qt Version 5.15.2, compiled with Qt 5.15.2 R
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
Autocompletion recognizes the quantity `\qty{num}{unit}` or `\unit{unit}` macros introduced in siunitx v3 and does not recognize units deprecated from v3 such as `\elementarycharge`. It should recognize but mark as unusual or S old `\SI...` macros, as they remain functional but are not recommended for new use.

### Actual behavior
As v3 of siunitx is very new (2021-05-17 for v3.0.0 -- newer than the latest TeXstudio release), the cwl has not yet been updated and so is missing new additions and removals.

**Comment by sunderme** [comment]
That sounds like a good opportunity for you to provide an updated siunitx.cwl.
Please be aware that not all are already using v3.

**Comment by kiriya-aoi** [comment]
I'm under the assumption that it wouldn't affect that many people until TeX Live 2022, at any rate. I'll keep this on my to-do list, but don't know when I'll get to it.
