### ISSUE TITLE
Install on debian from ppa?

### ISSUE THREAD

**Issue by martynwheeler** [texstudio-org/texstudio#1644]
### Environment
- TeXstudio: 3.1.2
- Qt: 
- OS: Linux (Pop-OS), 
- TeX distribution: texlive
### Description

How to install latest version of texstudio from ppa?  I have run apt update and apt upgrade but it is not finding the latest version of texstudio.  What do I have to do in order for apt to find the latest version?  Any help appreciated.  Thank you

**Comment by sunderme** [comment]
https://code.launchpad.net/~sunderme/+archive/ubuntu/texstudio
