### ISSUE TITLE
4.0.0alpha1 on macOS: extra separation/spacing between GUI components

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#1649]
### Environment
- TeXstudio: 4.0.0alpha1
- Qt: 5.15.2, compiled with Qt 5.15.2 R
- OS: macOS 11.1 with Intel chip
- TeX distribution: mactex (irrelevant)

### Expected behavior
![image](https://user-images.githubusercontent.com/6376638/121474572-d786b700-c9f6-11eb-9685-1c7dcf95ddf3.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/6376638/121473326-16b40880-c9f5-11eb-9103-ca586cb5b1bf.png)

### How to reproduce
Install 4.0.0alpha1 on macOS.

**Comment by muzimuzhi** [comment]
It works, thanks.

BTW, homebrew now provides qt6 through formula qt. I've tried building with qt6 on macOS in https://github.com/muzimuzhi/texstudio/commit/a28d440656650e0710b51213552316904b61230a, and the build succeeded.

**Comment by sunderme** [comment]
the missing piece in the puzzle is poppler-qt6
