### ISSUE TITLE
Tex file's content appears white and won't compile because PDF is corrupted

### ISSUE THREAD

**Issue by AlbFab** [texstudio-org/texstudio#165]
### Environment
- TeXstudio: 2.12.8
- Qt: Version 5.8.0, compiled with Qt 5.8.0 R
- OS: Windows 10

### Expected behavior
 I had just copied some (normal) text from a website and pasted it into texstudio when I hit "compile and view" and then something went wrong. The pc froze and I had to forcedly restart it. After that, I tried to open it again and run it. I expected it to show me the code, regularly compile and show me the result.

### Actual behavior
The code is no longer shown. Something can be selected (it's like the code's written in white or it's made up only by spaces, you can select it but you can't either read it nor copy and paste it anywhere), but when compiling it returns an error for invalid code. The output panel shows a message saying "[FILEPATH].pdf does not look like a valid PDF document". I also noticed a new file has appeared with the extension ".tex~txs0".

### How to reproduce
It does it anytime I launch the .tex file. The message about the PDF file not looking like a valid one has only appeared the first time I tried to open the file after the computer had frozen.

**Comment by sunderme** [comment]
well, edit the file with another editor (or start-over) and remove the invalid characters from the document ...

and there is no way that we can debug a corrupted text without even the slightest information what that looks like, i.e. having that file ...

**Comment by sunderme** [comment]
no feedback
