### ISSUE TITLE
Feature Request: Pasting common math Unicode symbols in math mode automatically converts them

### ISSUE THREAD

**Issue by bogger33** [texstudio-org/texstudio#1650]
### Describe the feature and the current behavior/state
Paste some unicode symbols like e.g. "⋃︀ ⨄︀ ∈ ∃ ∄ ∀ ∩∪ ⊎ ⇔⇒⇐ ⊂⊆≻⊃⊇", 

it just pastes the unicode characters into your latex code

but it could instead automatically convert e.g. the above string of symbols into  "\bigcup \biguplus \in  \exists \nexists \forall \cap \cup \uplus  \Leftrightarrow \Rightarrow \Leftarrow \subset \subseteq \succ \supset \supseteq", you get the idea

### Who will benefit with this feature?

anyone who is copying and pasting math equations or other symbols into math mode in latex (e.g. when solving a problem to copy the question from a pdf). also people who have a unicode character and don't know the equivalent latex symbol. 

Obviously doing this for all unicode characters might be a little difficult, but even just maintaining a table of common ones would probably be quite useful. I would also be willing to try to help with implementing this if you point me into the right direction, although admittedly I may be a little out of my depth

**Comment by bogger33** [comment]
In my case I would usually get the characters from copying out of a website, worksheet or an ebook, in the case of the latter two, often also generated by latex, but without the source code available. I can only speak for myself, but I'm in the situation of pasting a formula and then manually replacing the symbols one by one quite frequently. Greek letters and symbols like e.g. ≤, ≥, √, ∞, ² are especially common. 

I don't think the table would necessarily have to strive to be complete and cover every possible unicode symbol, every symbol one doesn't have to manually replace with the code is an improvement in user experience and there's really no downside to it, in my opinion. And neither unicode nor the equivalent latex codes are the kind of thing that really changes over time, so it seems that this wouldn't be very fragile.

I could write myself a macro, but then I'd be the only one benefitting from it. Like I said, I would be willing to give it a shot to try and implement this.

**Comment by sunderme** [comment]
there is texstudio-macro to post macros or you can put in in the wiki.
So distributing the macro is feasible.

**Comment by bogger33** [comment]
I personally don't think people really look at those kind of resources very often. So if I submitted this as a pull request, you would not accept it?

**Comment by sunderme** [comment]
correct, I accept it to texstudio-macro, you can add it to the wiki but I don't think it is suited for txs core.
We have already a completer and a symbol panel for the same functionality and I don't see too many people going for unicode symbols from the internet.
Maybe the exposure of texstudio-macro is smaller than txs itself, macros can be added directly to txs installation from txs itself, so it is available to all users at a mouse click. And if people like it, we will see.

**Comment by bogger33** [comment]
Alright, thanks for the feedback
