### ISSUE TITLE
Git SHA missing in "About TeXstudio"

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#1651]
### Environment
- TeXstudio: [artifact](https://github.com/texstudio-org/texstudio/actions/runs/925781164) for commit https://github.com/texstudio-org/texstudio/commit/451ac852cbdc3085ac4114b60660e761bc20864c
- Qt: Using Qt Version 5.15.2, compiled with Qt 5.15.2 R
- OS: macOS 10.11
- TeX distribution: irrelevant

### Expected behavior
The first line in "About TeXstudio" reads 
> TeXstudio 4.0.0 (git \<sth containing commit sha\>)

### Actual behavior
For normal CD builds, the git commit SHA is missing.
![image](https://user-images.githubusercontent.com/6376638/121580703-a0002500-ca5f-11eb-8753-8e3e57cd4d0f.png)

### How to reproduce
Open a CD build for macOS.

**Comment by sunderme** [comment]
the github actions do not check out the tags and hence git describe does not work properly ...
