### ISSUE TITLE
Italian Translation Typo

### ISSUE THREAD

**Issue by NetBender** [texstudio-org/texstudio#1653]
### Environment
- TeXstudio: 3.1.2
- Qt: 5.15.2
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
The text "È dispo**nib**ile una nuova versione di TeXstudio."

### Actual behavior
![typo](https://user-images.githubusercontent.com/3443323/121683710-0c117600-cabe-11eb-8646-16ea3cbfc6f6.png)

### How to reproduce
Wait for TeXstudio to have an upgrade available (or install an older version) and wait for the popup to appear

**Comment by muzimuzhi** [comment]
You can fix it yourself on https://www.transifex.com/texstudio/texstudio/languages/. Sorry I don't speak Italian.

**Comment by NetBender** [comment]
I wrote the exact string that should replace the current one in order to avoid any hassle. The transifex page already contains the proper translation but it has not been upvoted enough times to be used.

**Comment by sunderme** [comment]
should be fixed now
