### ISSUE TITLE
hasPersistent function not working in TeXstudio 4.0.0alpha1-14

### ISSUE THREAD

**Issue by mmaunier** [texstudio-org/texstudio#1656]
hello,
I use in one of my macros (%SCRIPT version) the `bool hasPersistent (&name)` function.
I just updated texstudio to 4.0.0 (from 3.1.2) and I get the following error message:
`"Exception manquée à la ligne 1 : ReferenceError: haspersistent is not defined"`
I also tested hasGlobal, which give the same error message. See attached picture.

### Environment
- TeXstudio: 4.0.0 (git 4.0.0alpha1-14-g57bd6eb2)
- Qt: version 5.9.5, compilé avec Qt 5.9.5 R
- OS: Linux Manjaro, kernel 5.12.8-1
- TeX distribution: TeXLive 2021 (texlive-bin 2021.58686-3) 

### Expected behavior
Normally, the function should detect if there is a persistent variable and return true or false.

### Actual behavior
function hasPersistent() is not defined (and hasGlobal() too), showing error message.

### How to reproduce
just use this macro : 
```
%SCRIPT
if (hasPersistent("test")) 
	alert("test variable exist");	
```

Do you have any idea where this might come from  ?
I have been looking at the sources (scriptobject.cpp and scriptobject.h) and the functions seem to be still there.
![Screenshot_20210615_115615](https://user-images.githubusercontent.com/2765724/122033589-f4453500-cdd0-11eb-8009-47d7934dc5e5.jpg)

**Comment by mmaunier** [comment]
Thank you !!

**Comment by bryango** [comment]
I believe `hasGlobal`, `getGlobal` and `setGlobal` are not yet implemented as of `4.0.0`. They could be useful, as is demonstrated in this wiki snippet: https://github.com/texstudio-org/texstudio/wiki/Scripts#macro-virus

Also I think either `registerAsBackgroundScript` or `setTimeout` is not working as of `4.0.0`. Example:

```js
registerAsBackgroundScript("my-script")
setTimeout(function() {
	alert("ha")
}, 10)
```

This shows no alert, while a simple `alert("ha")` works perfectly.

**Comment by sunderme** [comment]
registerAsBackground and setTimeout work. Please follow the example in the wiki to see how that works.
...global is not implemented. Unless I see a real life necessity, I will not bother.

**Comment by bryango** [comment]
> registerAsBackground and setTimeout work. Please follow the example in the wiki to see how that works. ...global is not implemented. Unless I see a real life necessity, I will not bother.

Thank you for the hint! I've found the solution: it seems that **anonymous functions no longer work**, while named functions (such as the example given in [wiki](https://github.com/texstudio-org/texstudio/wiki/Scripts#periodic-auto-save-all-documents-under-a-new-name)) still works. _Note that anonymous functions did work in `3.1.2`._

Namely,

```js
registerAsBackgroundScript("my-script")

// NOT working:
setTimeout(function() {
	alert("ha")
}, 10)

// working:
function alertFunction() {
	alert("ha")
}
setTimeout(alertFunction, 10)
```

I guess it would be helpful for other users if I share the solution here. Sorry for the inconvenience.
