### ISSUE TITLE
Unable to uninstall TeXstudio (flatpak)

### ISSUE THREAD

**Issue by NewUser36** [texstudio-org/texstudio#1659]
### Environment
- TeXstudio: 3.1.2
- Qt: Using Qt Version 5.15.3, compiled with Qt 5.15.3 R
- OS: Linux (Pop!_Os 20.10)
- TeX distribution: texlive

### Description
Sorry if this is not the place to post my issue, I'm new to GitHub and I wasn't sure where I should ask for help.

I am using Pop_Os and I recently installed the flatpak version of TeXstudio using the pop shop. However, I decided to remove it from my computer (since it can't find where I installed texlive even though I specified the path, but the .deb version works, I decided to use the deb version of TeXstudio even though it is older).

Running `$ flatpak uninstall org.texstudio.TeXstudio` I get
`
**
flatpak:ERROR:common/flatpak-transaction.c:2615:mark_op_resolved: assertion failed: (commit != NULL)
Bail out! flatpak:ERROR:common/flatpak-transaction.c:2615:mark_op_resolved: assertion failed: (commit != NULL)
Aborted (core dumped)
`
I have been searching for a while online on how to solve this issue, but I found nothing. I also tried to remove TeXstudio from the pop shop, but it just crashes.

Thanks in advance.

**Comment by sunderme** [comment]
we don't offer flatpack.
Please ask wherever you got the file from.

**Comment by NewUser36** [comment]
Will do. Thanks!
