### ISSUE TITLE
Autocomplete window should reappear if a single invalid character is pressed and then erased again

### ISSUE THREAD

**Issue by bogger33** [texstudio-org/texstudio#1660]
### Describe the feature and the current behavior/state

Basically, when you make a typo and the autocomplete window disappears because there are no more suggestions, it should reappear if you then immediately hit backspace to erase that character again.

So to be a bit more specific, I type with a german keyboard so all the time I typo \begin{ to \begin[ because the curly braces are unfortunately incredibly awkward to type on a german keyboard. this causes all suggestions to disappear, and when I then backspace, they don't reappear again.

So my suggestion is, that for exactly one character, if you backspace it again it should remember that the autocomplete window was previously open, and reopen it. 

### Who will benefit with this feature?

bad typists who typo stuff all the time

**Comment by muzimuzhi** [comment]
> So to be a bit more specific, I type with a german keyboard so all the time I typo \begin{ to \begin[ because the curly braces are unfortunately incredibly awkward to type on a german keyboard. this causes all suggestions to disappear, and when I then backspace, they don't reappear again.

A bit off-topic, but you can use shortcut `Ctrl-E / Cmd-E` to easily type 
```tex
\begin{<environment-name>}
<content>
\end{<environment-name>}
```
in which the characters surrounded by `<...>` are placeholders.

**Comment by sunderme** [comment]
I would also suggest a different approach for entering the command. 
1) you can press tab when in completer mode to complete common (visible) prefixes.
in case of entering ```\beg``` it gets completed to ```\begin{``` and the completer stays open.
2) you can directly complete for environments by entering ,e.g., ```de``` and pressing ctrl+alt+space. The completer offers all ```\begin{de...}``` environments

Going to start the completer when deleting is probably complicated to do right.

**Comment by sunderme** [comment]
not going to change
