### ISSUE TITLE
`\par` is wrongly highlighted when followed by decimals

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#1665]
### Environment
- TeXstudio: 4.0.0alpha2
- Qt: Using Qt Version 5.15.2, compiled with Qt 5.15.2 R
- OS: macOS 11.1
- TeX distribution: irrelevant

### Expected behavior
The two `\par`s in `\par \par123` are both highlighted as `extra-keyword`.

### Actual behavior
The second `\par` is highlighted as `keyword`.
```tex
\par \par123
\section \section123
```
![image](https://user-images.githubusercontent.com/6376638/122505120-4a62e400-d02e-11eb-805a-933925446aed.png)

**Comment by sunderme** [comment]
I don't really understand.
Why do you place ```\par123``` in the first place ?

**Comment by muzimuzhi** [comment]
I know it's weird and can/should be avoided, but since `\par123` is valid (La)TeX input under default catcode settings ... I found it by accident while preparing a test example.

Running
```tex
\documentclass{article}
\ExplSyntaxOn
\def\xshow{\tl_analysis_show:n}
\ExplSyntaxOff

\begin{document}
\xshow{\par123}
\end{document}
```
you can see
```
The token list contains the tokens:
>  \par (control sequence=\protected\long macro:->\mode_if_horizontal:TF\ETC.)
>  1 (the character 1)
>  2 (the character 2)
>  3 (the character 3).
<recently read> }
```
in stdout and log.

I searched for `extra-keyword` in the codebase, but didn't found where its tokenize rule is defined. Not a big problem and feel free to close it if the required effort is much more than the gain.

**Comment by sunderme** [comment]
it seems that this is a "limitation" of the QCE (our underlying editor component) highlighter.
The keywords are defined in a list "keywords/structure" (with format extra-keyword) dynamically. The highlighter looks for word and it does not distinguish between letters and numbers.
Since this looks like a rabbit hole for a minor inconvenience, I will not follow up.
