### ISSUE TITLE
Installation: Duplicate texstudio.exe (in different folders) after update to 3.1.2 on Windows 10

### ISSUE THREAD

**Issue by cottmann** [texstudio-org/texstudio#1666]
### Environment
- TeXstudio: 3.1.2
- Qt: 5.15.2, compiled with Qt 5.15.2 R
- OS: Windows 10
- TeX distribution: miktex 2.9

### Description
1. After installing texstudio 3.1.2 with the standard installer from the homepage: https://github.com/texstudio-org/texstudio/releases/download/3.1.2/texstudio-3.1.2-win-qt5.exe 

2. I now have two installations: 
3.1.2 is at C:\Program Files\texstudio
3.0.0 is at C:\Program Files (x86)\texstudio

3. Annoyingly, windows opens the 3.0.0 version when I search for texstudio on the start menu

### Question
Can I just delete C:\Program Files (x86)\texstudio or should I use the uninstall.exe in that folder?

**Comment by sunderme** [comment]
it was caused by transitioning to 64 bit binary.
You can remove the folder. (Maybe better to check win/apps configuration, as that can get a bit messed up if programs are deleted outside its context)

**Comment by cottmann** [comment]
Uninstalling texstudio v3.0.0 via control panel > uninstall a program and then manually putting v3.1.2 on the start menu worked. 

Thank you, sunderne, for the help and all of the developers for this great piece of software!
