### ISSUE TITLE
Script error (registerAsBackgroundScript is not defined)

### ISSUE THREAD

**Issue by hair-splitter** [texstudio-org/texstudio#1668]
### Environment
- TeXstudio: 4.0.0 (git 4.0.0alpha2)
- Qt: 5.15.2
- OS: Windows 10
- TeX distribution: TeX Live 2021

I use this script:
[https://github.com/texstudio-org/texstudio/wiki/Scripts#periodic-auto-save-all-documents-under-a-new-name](url)
But I get the following message:
![script-error](https://user-images.githubusercontent.com/31892631/122636293-c6b9fd80-d0e8-11eb-8813-0a954b8b8d68.png)

**Comment by sunderme** [comment]
fixed
