### ISSUE TITLE
Location of the log file

### ISSUE THREAD

**Issue by li-po** [texstudio-org/texstudio#167]
### Environment
- TeXstudio: 2.12.8
- Qt Version 5.10.1, compiled with Qt 5.10.1 R
- OS: Linux Fedora 28
- TeX distribution: texlive

### Expected behaviour
I would like an additional option to define the path of the log file. This is the only way to (1) work with cross-referenced tex documents and (2) keep the tex directory clean.

A possible place for the option could be in 'Adv. Editor' before or after the 'Log Encoding'. Relative path should be possible, e.g. '../build'

### Actual behaviour
I work on some tex documents referencing to each other. Thus all output files are saved in an external common directory, inclusive the log file. Every thing work perfectly (only makeindex needed a workaround, because it is incapable of working in a different directory than cwd), only the log file is not found and I did not found a place where I can define a non-standard location for the log file.

**Comment by benibela** [comment]
Have you seen the  log file path option on the build page?

**Comment by li-po** [comment]
No. I'm sorry. I cannot understand how I missed it. This is exactly what I was looking for.
