### ISSUE TITLE
opens and closes immediately

### ISSUE THREAD

**Issue by parpamgr** [texstudio-org/texstudio#1672]
Assume the project consists of three files
a.tex (preamble), b.tex (main file) c.tex (bibliography)
contained in a folder A with the necessary pics etc.
You compile it and everything is ok.

If accidentally you move b.tex out of folder A, and then
you go and open another project contained in the folder B(a'.tex, b'.tex, c'.tex)
then texstudio opens and closes immediately !! (panic!!!)

**Comment by sunderme** [comment]
please provide a zip with files and directory set-up.

**Comment by sunderme** [comment]
no feedback
