### ISSUE TITLE
Add a command for epstopdf

### ISSUE THREAD

**Issue by phollox-arch** [texstudio-org/texstudio#1675]
Hello,

I was wondering if it would be possible to add a command to run epstopdf from within texstudio

Sometimes in MATLAB, generating output in eps is great because it ignores frame specification, and there is no white margin around the output. The pdf output always has some white frame and is a pain to remove from within MATLAB. I think Octave have similar behaviour. THe PDF output has a margin, and is not great for latex.

So having epstopdf to run and convert those eps images into pdf so pdflatex can process them is really helpful. It takes a second to go to a terminal and type
`$ find . -regex ".*\.eps[c]*" -exec epstopdf {} \;`
and convert all my eps and epsc into pdf images.

If texstudio finds a file from  includegraphics that match the name but not the .pdf extension , and runs the epstopdf automatically, that would be cool

Thanks

**Comment by muzimuzhi** [comment]
> So having epstopdf to run and convert those eps images into pdf so pdflatex can process them is really helpful.

`graphicx` package can automatically do this, so normally there is no need to manually convert eps to pdf.

If you have
```
$ tree .
├── main.tex
└── test.eps
$ cat main.tex
\documentclass{article}
\usepackage{graphicx}

\begin{document}
\includegraphics{test} % NO file extension
\end{document}
```
then after executing `pdflatex main.tex`, you will have
```
$ tree .
├── main.tex
├── test-eps-converted-to.pdf
└── test.eps
```
and the newly created `test-eps-converted-to.pdf` will be included by `\includegraphics{test}`.

**Comment by muzimuzhi** [comment]
Also, one can define [user commands](https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html#SECTION02a) in TeXstudio.

**Comment by sunderme** [comment]
I think, this is answered.

**Comment by phollox-arch** [comment]
Thanks,

I checked and the `graphicx` package is not the solution. It need the `epstopdf` package. But it works as mentioned.

Thanks again
