### ISSUE TITLE
editor.search method leads to some endless loop

### ISSUE THREAD

**Issue by tro100** [texstudio-org/texstudio#1676]
In the macro environment the editor.search method is called with an regular expression that exactly covers the selected text in the specified cursor and a call back function is specified then the function does not return (endless loop). 
Example:
- document does only contains the character a
- macro: 
      function cursor.CallBack(c){};
      editor.search(/a/,"gi",editor.document().cursor(0,0,0,1),cursor.CallBack) 
  where cursor.CallBack is some callback function (even an empty one will do).
The following macros work fine:
      editor.search(/a/,"i",editor.document().cursor(0,0,0,1),cursor.CallBack) 
      editor.search(/a/,"gi",editor.document().cursor(0,0,0,2),cursor.CallBack) 
      editor.search(/a/,"gi",editor.document().cursor(0,0,0,1)) 

### Environment
- TeXstudio: 3.1.1
- Qt: 5.15.2
- OS: Windows 10 
- TeX distribution: TeXlive 2020

**Comment by sunderme** [comment]
please,state the environment
and provide a complete example, ready to copy and run

**Comment by tro100** [comment]
example completed

**Comment by sunderme** [comment]
seems to work with 4.0.0alpha
