### ISSUE TITLE
In the macro environment "look ahead" regular expressions do not work

### ISSUE THREAD

**Issue by tro100** [texstudio-org/texstudio#1677]
Regular expressions containing look ahead terms like (?<=...) do not work within the macro environment. They do work in the manual search .
Example:
var re = new RegExp("(?<=a)b");

### Environment
- TeXstudio: 3.1.1
- Qt: 5.15.2
- OS: Windows 10 
- TeX distribution: TeXlive 2020

### Expected behavior
define a regular expression

### Actual behavior
syntax error

**Comment by sunderme** [comment]
again, which os etc

provide a complete example ready to run

**Comment by tro100** [comment]
the example is complete

**Comment by sunderme** [comment]
Qt uses a javascript version which apparently does not support "look ahead"
Nothing we can do, as we rely on Qt.
