### ISSUE TITLE
bug in keyval highlighting of \tcbset

### ISSUE THREAD

**Issue by mbertucci47** [texstudio-org/texstudio#1678]
The highlighting for keyvals of the `\tcbset` command of `tcolorbox` works as expected for the keyvals defined in lines 547-589 of the [cwl file](https://github.com/texstudio-org/texstudio/blob/master/completion/tcolorbox.cwl), but does not recognize the keyvals defined in lines 525-545 and 594-1513. The obvious difference is that in the latter, the "completion only" classifier `#c` is used, but I don't know what the expected behavior is for commands with multiple specified keyval lists using different classifiers.

### Environment
- TeXstudio: 3.1.2
- Qt: 5.15.2
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
Recognize the keyvals in lines 525-545 and 594-1513 of the cwl.

### Actual behavior
The key `notitle` is in one of the `#c` keyval lists, while `doc keypath` is in one of the keyval lists without `#c`.
![Screenshot 2021-06-24 091242](https://user-images.githubusercontent.com/61854785/123289540-c9906600-d4cd-11eb-9f7c-e41db1fb66e2.png)

**Comment by sunderme** [comment]
I am a bit confused.
'#c' tells txs that it should take the specified commands **not** for syntax checking.
Hence it does not recognize 'notitle'. 
So, why is '#c' set in the first place ?

**Comment by mbertucci47** [comment]
It's my understanding that if `#c` is present, then keyval syntax is not checked at all, i.e. nothing is marked invalid in the keyval location (usually used to not restrict the scope of possible keys, like in packages that interface with tikz). If this is correct, then it seems if there are multiple instances of keyval lists both with and without `#c`, it defaults to the "without `#c`" behavior. I will open a pull request to just get rid of the `#c` classifiers.

**Comment by muzimuzhi** [comment]
The keyvals list for `\tcbset` is incomplete, hence the `#c` I guess.
