### ISSUE TITLE
File `styles/thesis.sty' not found. \usepackage

### ISSUE THREAD

**Issue by TinasheErasmus** [texstudio-org/texstudio#1681]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution:

**Comment by TinasheErasmus** [comment]
Hi guys, I cant seem to solve this error on my latex, when I compile my template it gives me this error: File `styles/somiaethesis.sty' not found. \usepackage. I am using the tex -live distribution on Ubuntu 20.04.

**Comment by sunderme** [comment]
latex problem, please use tex.stackexchange.com
