### ISSUE TITLE
Spellchecking in commands with text argument inside math-mode

### ISSUE THREAD

**Issue by meneken17** [texstudio-org/texstudio#1682]
### Environment
- TeXstudio: 3.1.12
- Qt: 5.15
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
When the autocomplete template (cwl-file) has an argument with the name `text` it should enable spellchecking. 

### Actual behavior
This works fine outside of math-mode, but fails to do so within.

### How to reproduce
create ```.cwl```-file and enable it:
```
\foo{text}#m
\baar{text}
```

```
$\foo{spelllling}$ %not spellechecked
\baar{spelllling} %spellchecked and underlined
```

and when this is fixed, can you please change https://github.com/texstudio-org/texstudio/blob/14df7a40b4279e8d06bf340704e8618f50951f6e/completion/amsmath.cwl#L99 into `\intertext{word or phrase%text}#m`
That would save me a lot of typos in my descriptions.

**Comment by sunderme** [comment]
implemented
