### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by JonathanLevine657** [texstudio-org/texstudio#1683]
### Environment
- TeXstudio: 4.0.0alpha2
- OS: Linux

I can't say what triggered it, except that it was during editing of a  file
```
[bt] texstudio(SimulatedCPU::set_from_real()+0) [0x8515b0]
[bt] texstudio(Texstudio::recoverFromCrash()+0x3e6) [0x7b0a66]
[bt] texstudio(LatexDocumentsModel::parent(QModelIndex const&) const+0xbc) [0x6ee51c]
```

That's all I got.

**Comment by sunderme** [comment]
Unfortunately that is too little to investigate ...

**Comment by sunderme** [comment]
Have you tried globalTOC ?

**Comment by JonathanLevine657** [comment]
I don't know what that is. The side panel was not open at the time, if that's what you mean.

**Comment by sunderme** [comment]
I have ditched the model based structure view (which in the end causes the crash)
So, please try alpha4.
