### ISSUE TITLE
creation of EPS/PDF figures with LaTeX

### ISSUE THREAD

**Issue by istanaro1971** [texstudio-org/texstudio#1685]
Dear Colleagues,
I have the following problem. While earlier I succeeded to create EPS/PDF figures with LaTeX command (a specific file feynman. sty), and each picture was of a normal size, now something changed in LaTeX in a new version of TexStudio, and the EPS/PDF figure occupies an entire page.
[fourpoint.pdf](https://github.com/texstudio-org/texstudio/files/6758499/fourpoint.pdf)
Using Linux-like style of LaTeX through terminal (which earlier helped to solve this problem on Mac computers) now also does not help.
Thus, the question is -- how to obtain a small-size image in LaTeX?

**Comment by sunderme** [comment]
This is a latex question, not about the text editor texstudio.
Please ask on tex.stackexchange.com
