### ISSUE TITLE
IntelliSense a la Visual Studio

### ISSUE THREAD

**Issue by ramayasket** [texstudio-org/texstudio#1688]
I am using TeXstudio to type a manuscript in the field of mathematics/abstract systems. Here is the word statistics from TeXstudio:

![image](https://user-images.githubusercontent.com/31845918/124419574-6c66a100-dd66-11eb-8607-4ffc607252e4.png)

The words I marked are of especial interest of me. The current behavior is that I need to press the Ctrl+Space keys to invoke a word list, which then occupies a huge space in my editor and requires me to take care of tabs typical/most used/fuzzy/all. That's hell of an inconvenience (!):

![image](https://user-images.githubusercontent.com/31845918/124420070-6f15c600-dd67-11eb-8be0-f9e2988b1193.png)

In the meantime, in the Visual Studio and Visual Studio Code, there's a feature called Intelligent code completion, or IntelliSense. It looks like, as you type, for example, "this.", the feature gives you a tiny neat updating word list, which becomes LESS AND LESS and even disappears without a trace as you type further:

![image](https://user-images.githubusercontent.com/31845918/124420779-bc466780-dd68-11eb-9aa2-337b13e83f7b.png)

In TeXstudio, word list joyfully remains in place even when I type something for what there isn't a match:

![image](https://user-images.githubusercontent.com/31845918/124423220-62946c00-dd6d-11eb-98a1-cefa52390593.png)

What's suggested is a similar feature in TeXstudio. Each typist typically has a list of VERY popular words which are VERY good at his/her fingertips.

Comparing to the Visual Studio picture, we don't need the following information:

![image](https://user-images.githubusercontent.com/31845918/124421817-e8fb7e80-dd6a-11eb-8168-ceffde0bac89.png)

Here is how is it suggested to transform the TeXstudio's interface:

![image](https://user-images.githubusercontent.com/31845918/124422837-a6d33c80-dd6c-11eb-8dee-9b4c87f13578.png)

For the too common words, such as "as, the, and, of, it, etc" we don't even need to bother. For the others, we can auto open a word list after we type a first three letters.

The feature has a potential to become really tiny. In overall, this seems a good time investment to save lots of time. Thank you.

**Comment by sunderme** [comment]
I don't follow.
For 'system', you type 'sys' and then you hit ctrl+space, showing three possibilities, from which you can select the one you want.
No need to change tabs.
So, the only issue is, that you need to press ctrl+space ?

**Comment by ramayasket** [comment]
Two issues: a need to press Ctrl+Space, and a huge window with borders which does not disappear when should. The numbers show that I had to press Ctrl+Space hundreds of times, or just abandon the feature altogether. Try Visual Studio Code (it's lightweight) and see for yourself how much more convenient is its IntelliSense.

**Comment by ramayasket** [comment]
Also, the choices are not where I type, so I have to move my eyes a lot. Overall, this consumes time without a true need for that.

**Comment by ramayasket** [comment]
It's not a hard feature to implement, make the list more compact and move it closer to cursor.

**Comment by sunderme** [comment]
code behaves that way only for programming languages. 
For text it is very similar to what we do.
In general it uses more or less the fuzzy mode for word finding. (which you can set as default in the options, if desired)

At least here, pop-up size is similar. (and the screenshot does not give the impression that it is different on your side)
I really don't see what needs changing, especially since ctrl+space is really easy to type.

**Comment by sunderme** [comment]
maybe script: https://github.com/texstudio-org/texstudio/wiki/Scripts#word-completion
