### ISSUE TITLE
Macro triggers should trigger when pasting text

### ISSUE THREAD

**Issue by JonathanLevine657** [texstudio-org/texstudio#1689]
Not sure if this is a bug or a feature-request.

Macro triggers let me define a substitution which applies whenever I type anything in to the editor and it's a big time-saver. However, if I paste in something which contains a trigger, the macro replacement is not applied. I don't see why pasting in and typing in are treated differently since they're both are just  means to write the document.

### Why would this be useful?

I often copy-paste math definitions/theorems from PDF's into my document, and then clean them up. The math expressions tend to get mangled of course, but in a predictable way.
To automate some of the manual cleanup required, I'd like to define triggers which do some of the substitutions for me when I paste.

Common examples: substitute x0 with x_0, x1 with x_1, f-1 with f^{-1}, etc'.

**Comment by sunderme** [comment]
the trigger is tied to key-presses.
For pasting it is simpler, to use the macro to handle the clipboard completely.
-> app.cliboard
https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html#SECTION33

**Comment by JonathanLevine657** [comment]
How does `app.clipboard` help with this? I can read the clipboard and use `curosr.insertText(app.clipboard)`, but that doesn't trigger any macros either, if some content in the clipboard matches the trigger.

**Comment by sunderme** [comment]
you can do the replacements in the script.

**Comment by JonathanLevine657** [comment]
I want the replacement to trigger both when I type and when I paste in text. You're suggesting for each case I both create a macro, and then also edit a custom "paste override" script?

Do you have an objection to texstudio doing this itself, or is it just that the way things are currently, it's not easy to implement?
