### ISSUE TITLE
Structure view does not show entire section title

### ISSUE THREAD

**Issue by hubutui** [texstudio-org/texstudio#169]
### Environment
- TeXstudio:  2.18.2
- Qt:  Using Qt Version 5.11.0, compiled with Qt 5.10.1 R
- OS:  Arch Linux
- TeX distribution:  texlive 2018
- Desktop environment: Gnome 3.28.1
### Expected behavior
![image](https://user-images.githubusercontent.com/2948593/40885816-38b246e0-6760-11e8-8e39-7eb443804733.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/2948593/40885794-da5987c0-675f-11e8-994b-42893ab0c251.png)

I'm sure there is enough place to show the entire section title, but it sometimes does not. I'm not sure what driggers it, but it's quite often.

**Comment by sunderme** [comment]
txs/qt 5.10 bug
this has already been fixed in repository
