### ISSUE TITLE
"varioref" documentation

### ISSUE THREAD

**Issue by BeerStud** [texstudio-org/texstudio#1690]
### Environment
- TeXstudio: 3.1.2 (git 3.1.2)
- Qt: 5.15.2, compiled with Qt 5.15.2 R
- OS: Windows 10 Pro - 64 bit
- TeX distribution: Miktex

### Expected behavior
When I click on "varioref" in "\usepackage[nospace]{varioref}", I expect to see the documentation.

### Actual behavior
I receive this error message:
Process started: texdoc.exe  --list-only varioref
Documentation for varioref could not be found.
Process exited normally

### How to reproduce
See "Expected Behavior"

This may be a "Miktex" error, but I thought I would start here.

**Comment by muzimuzhi** [comment]
What do you get if you manually execute `texdoc -l varioref` in cmd.exe?

**Comment by BeerStud** [comment]
On Mon, 05 Jul 2021 09:42:01 -0700, muzimuzhi stated:
>What do you get if you manually execute `texdoc -l varioref` in
>cmd.exe?
>

texdoc -l varioref
Documentation for varioref could not be found.


-- 
Gerard

**Comment by muzimuzhi** [comment]
So it's just not installed by the distribution, here MiKTeX. You need install MiKTeX package [`latex-tools__doc`](https://miktex.org/packages/latex-tools__doc/files).

Recently (6/7/2021), MiKTeX has adopted a "three-way split", 

> MiKTeX packages are being rearranged: documentation and source files are transferred into separate "companion" packages.
> _from https://miktex.org/announcement/companion-packages_

And the split `xxx__doc` one is not auto installed. See related discussions in https://github.com/MiKTeX/miktex/issues/844 and https://github.com/MiKTeX/miktex/issues/863.

**Comment by BeerStud** [comment]
On Mon, 05 Jul 2021 11:57:01 -0700, muzimuzhi stated:
>So it's just not installed by the distribution, here MiKTeX. You need
>install MiKTeX package
>[`latex-tools__doc`](https://miktex.org/packages/latex-tools__doc/files).
>
>Recently (6/7/2021), MiKTeX has adopted a "three-way split", 
>
>> MiKTeX packages are being rearranged: documentation and source files
>> are transferred into separate "companion" packages. _from
>> https://miktex.org/announcement/companion-packages_
>
>And the split `xxx__doc` one is not auto installed. See related
>discussions in https://github.com/MiKTeX/miktex/issues/844 and
>https://github.com/MiKTeX/miktex/issues/863. 
>

Thanks! It would have taken me a week to figure out what the problem
was. By the way, IMHO, who ever came up with this "new and improved"
idea really needs to rethink it. A new user. i.e., someone with even
less knowledge of LaTeX then me would probably go back to MS Word.

-- 
Gerarde

**Comment by muzimuzhi** [comment]
> By the way, IMHO, who ever came up with this "new and improved" idea really needs to rethink it.

@BeerStud You can subscribe the issue below, which has been labeled "bug" and added to MiKTeX's next milestone
 - https://github.com/MiKTeX/miktex/issues/863
