### ISSUE TITLE
Feature: Syntax for calling javascript functions from a macro

### ISSUE THREAD

**Issue by JonathanLevine657** [texstudio-org/texstudio#1691]
I'd like to to have macros which produce computed text.

Two example:
1. Attach randomly generated label when inserting an equation environment: `\label{eqn:786ad68e0}`.
2. defining a macro which triggers on `x0`, I'd like to be able to insert \$x_0\$ if out of a math environment, or x_0 if inside it.

What I'd like is to be able to separately enter a global script which exports functions available to all macros, then have a syntax to invoke them from within macros:
```
\begin{equation}\label{eqn:<<random_str>>}
\end{equation}
```
or some such.

**Comment by sunderme** [comment]
the pragmatic solution is "copy and paste" ?

**Comment by JonathanLevine657** [comment]
??? how does copy and paste help me generate a random label each time I use `Math/env align`?

**Comment by sunderme** [comment]
all snippets also understand javascript (%SCRIPT ...)
e.g. Latex/List/\item  (see option/menus or directly uiconfig.xml)

**Comment by JonathanLevine657** [comment]
That means I can insert snippets from scripts. What I'd like is to call script functions from a snippet. Basically, templates. like handlebars/jinja2/etc', or even formatted string in recent python. As in `The current date is {{now()}}`.

**Comment by sunderme** [comment]
The snippet is the script. You can generate any text you want in javascript including current date (i assume)

**Comment by JonathanLevine657** [comment]
I'm not sure we're talking about the same thing here.

I want
```
The current date is {{now()}}
```
as a Type:"Normal" macro, to work. With `now` being a function I define somewhere else via the gui.  

Although I can achieve this same result now using
```
%script
ins = 'The current date is " + String(date());
editor.insertSnippet(ins)
```
which is a Type:"script" macro. But gluing together pieces of string and code isn't nearly as convenient. Most of all because it's much harder to see what the result will be, when the output is more complicated. Especially if I include mirrors, cursor here, etc'.

**Comment by sunderme** [comment]
my point is that your objective can be achieved.
Since snippets are internal structures which are not touched regularly, user comfort is not of prime importance.
In the end, you want to push work to someone else, with little general benefit.

**Comment by JonathanLevine657** [comment]
> In the end, you want to push work to someone else, with little general benefit.

That's ugly.

**Comment by JonathanLevine657** [comment]
@sunderme, No one expects you to work on anything you're not interested in. We just expect you not to snap at people for asking for features, or when they're unhappy with the workarounds you suggest. It's be better if you:
1. Just say you're not interested in working on it yourself.
2. Indicate your level of interest in accepting/reviewing a PR for the feature.
 
I don't think you're a bad or evil person. I think you're at or near burnout. Which is why   interacting with you often  feels unpleasent. Since I care about TXS and use it every day, I've dealt with this by trying to set things up as best I could for you to "just do it yourself". For example when I:
1. helped close a bug which had languished for 3 years by figuring out steps to repro in Issue 31.
2. Provided the exact code location of the bug (and screencap)  in issue 1482.
3. Reported a bug and provided an example fix in issue 1511.

I also:
1. Contributed a wrap/unwrap script in issue 1483.
2. Analyzed why the project's git blame was (and still is) broken, and provided a way to mend it in 1562 (and let me tell you, that took **work**).
3. Reported a solution to debug output not showing up on recent linux distros in 1568.

and several others.

I think I've been more helpful then most and I **know** how much time I've put in to think about, describe, explain, screencap, and or debug my issues and feature requests.  Despite all this real work and contributions, you accuse me of being here just to pass off work on you.   **How ugly**.
