### ISSUE TITLE
Percent char (%) sometimes not highlighted as comment

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#1695]
### Environment
- TeXstudio: 4.0.0alpha5
- Qt: Using Qt Version 5.15.2, compiled with Qt 5.15.2 R
- OS: macOS 11.4
- TeX distribution: irrelevant

### Expected behavior
In 
```tex
\newenvironment{env}{%
  abc%def%
}{}
```
The `%` in line 1 and `%def%` in line 2 are both highlighted as comment (in gray).

### Actual behavior
![image](https://user-images.githubusercontent.com/6376638/125185085-240f1d80-e255-11eb-8304-409355dc4c54.png)

### How to reproduce
Either type in or paste the example into editor area. 
 - `\newenvironment` is essential to reproduce the problem.
 - "Idefix - Refresh Structure" doesn't work.

**Comment by sunderme** [comment]
command definition is not checked and also no comment is set,see also #1108.
For command definition I find that acceptable.
