### ISSUE TITLE
Cannot paste text in "Save As" window

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#1696]
### Environment
* TeXstudio: 4.0.0alpha5
* Qt: Using Qt Version 5.15.2, compiled with Qt 5.15.2 R
* OS: macOS 11.4
* TeX distribution: irrelevant

### Expected behavior
One can paste text in "Save As" window.

### Actual behavior
![image](https://user-images.githubusercontent.com/6376638/125189424-99391d80-e26a-11eb-9fb6-f76a376b8cac.png)

### How to reproduce
 - Copy some text
 - Create a new file then save it
 - In the filename field of "Save As" window, paste

This is especially useful when I save an example corresponding to a GitHub issue or TeX-SX question, and want to use the copied issue or question number (now has 6 digits) as part of the file name.

**Comment by sunderme** [comment]
That window is provided by Qt/OS. I don't think we have influence on it.

**Comment by sunderme** [comment]
have you played with options/general/use system file dialog ? (advanced option)

**Comment by muzimuzhi** [comment]
> have you played with options/general/use system file dialog ? (advanced option)

When not checked, the pasting works. Sort of resolved.

**Comment by sunderme** [comment]
As statet above, nothing we can really do about it.

**Comment by muzimuzhi** [comment]
All of a sudden, now I can paste in texstudio v4.5.1.  It's not supported in v4.5.1beta3, if I remembered correctly.

**Comment by octaeder** [comment]
With Win10 and TeXstudio 4.5.2 (git 4.5.1-26-g91f92d5be) it works with native and with Qt dialog.
