### ISSUE TITLE
Please test txs 4.0.0alpha6 on OSX

### ISSUE THREAD

**Issue by sunderme** [texstudio-org/texstudio#1699]
txs 4.0.0 alpha6 on OSX has been compiled against Qt6. 
Please test and check if oddities come up.

**Comment by PasLafon** [comment]
Hello,
I have just test tes 4.0.0 alpha6 on a M1 MacBook (Big Sur 11.3.1) and it produce this error :
Process:               texstudio [70227]
Path:                  /Applications/texstudio.app/Contents/MacOS/texstudio
Identifier:            texstudio
Version:               ???
Code Type:             X86-64 (Translated)
Parent Process:        ??? [1]
Responsible:           texstudio [70227]
User ID:               501

Date/Time:             2021-07-16 12:03:55.170 +0200
OS Version:            macOS 11.3.1 (20E241)
Report Version:        12
Anonymous UUID:        E5AD5FC8-3E4C-DA93-9A5E-6E90F4D4CA89

Sleep/Wake UUID:       300DB37A-E1BE-476E-8B5C-79F2BF41BCFD

Time Awake Since Boot: 230000 seconds
Time Since Wake:       14000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: 984D9B77-5956-3EB3-9EC8-D0AC08D1AAB7
Library not loaded: @rpath/QtDBus.framework/Versions/A/QtDBus
  Referenced from: /Applications/texstudio.app/Contents/Frameworks/QtGui.framework/Versions/A/QtGui
  Reason: image not found

Binary Images:
       0x102760000 -        0x103653fff + (0) <530AA5C8-35BB-3FC4-840E-FED0DC5E4D03> 
       0x10c5b6000 -        0x10c5f5fff +libpoppler-qt6.2.dylib (0) <013D40B7-9D5C-367B-A9BC-C77D75058316> /Applications/texstudio.app/Contents/Frameworks/libpoppler-qt6.2.dylib
       0x10c6bd000 -        0x10c6c8fff +libpoppler-cpp.0.dylib (0) <A3A18C35-A92A-3FEF-8683-9E7F6831FC47> /Applications/texstudio.app/Contents/Frameworks/libpoppler-cpp.0.dylib
       0x10c6fc000 -        0x10c737fff +org.qt-project.QtSvg (6.1 - 6.1.2) <F0B7548F-705C-3F52-BE37-77ACB37B58F9> /Applications/texstudio.app/Contents/Frameworks/QtSvg.framework/Versions/A/QtSvg
       0x10c7cc000 -        0x10c817fff +org.qt-project.QtPrintSupport (6.1 - 6.1.2) <B9EDCE5E-DF5A-360F-A382-B8D5EEC43E98> /Applications/texstudio.app/Contents/Frameworks/QtPrintSupport.framework/Versions/A/QtPrintSupport
       0x10c8c3000 -        0x10c92efff +org.qt-project.QtUiTools (6.1 - 6.1.2) <BF4AD14F-5949-3152-B12B-1334525C4EC5> /Applications/texstudio.app/Contents/Frameworks/QtUiTools.framework/Versions/A/QtUiTools
       0x10ca11000 -        0x10ca18fff +org.qt-project.QtOpenGLWidgets (6.1 - 6.1.2) <1D538F7F-6FD8-3BE2-9EE4-AB09072A7038> /Applications/texstudio.app/Contents/Frameworks/QtOpenGLWidgets.framework/Versions/A/QtOpenGLWidgets
       0x10ca36000 -        0x10ceddfff +org.qt-project.QtWidgets (6.1 - 6.1.2) <96B84818-EDBD-3353-AA2F-8BE354F25E76> /Applications/texstudio.app/Contents/Frameworks/QtWidgets.framework/Versions/A/QtWidgets
       0x10d861000 -        0x10d8c8fff +org.qt-project.QtOpenGL (6.1 - 6.1.2) <C728AF8F-A942-30A6-9A55-459BCAC54CD8> /Applications/texstudio.app/Contents/Frameworks/QtOpenGL.framework/Versions/A/QtOpenGL
       0x10d9b2000 -        0x10df7dfff +org.qt-project.QtGui (6.1 - 6.1.2) <8A784F33-0BFB-31CF-8FE1-E5BDD21E4669> /Applications/texstudio.app/Contents/Frameworks/QtGui.framework/Versions/A/QtGui
       0x10ea17000 -        0x10edd2fff +org.qt-project.QtQml (6.1 - 6.1.2) <5BF37A4C-3485-3733-A2AA-624EBC4EFA3A> /Applications/texstudio.app/Contents/Frameworks/QtQml.framework/Versions/A/QtQml
       0x10f4d2000 -        0x10f61dfff +org.qt-project.QtNetwork (6.1 - 6.1.2) <89F9FC60-49E6-3DC1-9E92-1DD523549CA7> /Applications/texstudio.app/Contents/Frameworks/QtNetwork.framework/Versions/A/QtNetwork
       0x10f882000 -        0x10f89dfff +org.qt-project.QtXml (6.1 - 6.1.2) <366451A9-4BD0-37AE-9997-4EFDE718F9D3> /Applications/texstudio.app/Contents/Frameworks/QtXml.framework/Versions/A/QtXml
       0x10f8e7000 -        0x10f8eafff +org.qt-project.QtConcurrent (6.1 - 6.1.2) <BAB980BC-74CD-3392-B11F-573F277677BA> /Applications/texstudio.app/Contents/Frameworks/QtConcurrent.framework/Versions/A/QtConcurrent
       0x10f900000 -        0x10f947fff +org.qt-project.QtCore5Compat (6.1 - 6.1.2) <7BF8B16F-A98F-3ED3-92FB-A036C14C396E> /Applications/texstudio.app/Contents/Frameworks/QtCore5Compat.framework/Versions/A/QtCore5Compat
       0x10f9d5000 -        0x10fe04fff +org.qt-project.QtCore (6.1 - 6.1.2) <4382AE43-1FF3-3BF3-823C-6036BD0EDBD5> /Applications/texstudio.app/Contents/Frameworks/QtCore.framework/Versions/A/QtCore
       0x11044e000 -        0x1104cdfff +libfreetype.6.dylib (0) <17C2EF02-7F12-3A4E-8B86-C00A63960ED0> /Applications/texstudio.app/Contents/Frameworks/libfreetype.6.dylib
       0x110599000 -        0x110728fff +libpoppler.111.dylib (0) <15D38469-54F8-38AB-85A3-72781D7954EC> /Applications/texstudio.app/Contents/Frameworks/libpoppler.111.dylib
       0x110a65000 -        0x110aa0fff +liblcms2.2.dylib (0) <F8FBE9AB-D543-376C-912B-07F049244490> /Applications/texstudio.app/Contents/Frameworks/liblcms2.2.dylib
       0x110b21000 -        0x110c2cfff +libglib-2.0.0.dylib (0) <4070FABF-36A7-33CB-AE7A-976B84F82168> /Applications/texstudio.app/Contents/Frameworks/libglib-2.0.0.dylib
       0x203aaa000 -        0x203b45fff  dyld (851.27) <7EAA668B-F906-3BAA-A980-139BBE6E8766> /usr/lib/dyld
    0x7ffdffdcc000 -     0x7ffdffe3ffff +runtime (203.42) <A7DF9462-ECE5-3ED4-8C57-BC56BA4793EA> /Library/Apple/*/runtime
    0x7fff20132000 -     0x7fff20133fff  libsystem_blocks.dylib (79) <1C8538C3-F2BE-3F02-89AE-E7052DE66D51> /usr/lib/system/libsystem_blocks.dylib
    0x7fff20134000 -     0x7fff20169fff  libxpc.dylib (2038.100.48) <CFB56DA8-7462-3E8F-9CFB-20926C6A2BB5> /usr/lib/system/libxpc.dylib
    0x7fff2016a000 -     0x7fff20181fff  libsystem_trace.dylib (1277.100.21) <1AAE1F8F-9F9D-3327-8A95-3A6887CED713> /usr/lib/system/libsystem_trace.dylib
    0x7fff20182000 -     0x7fff2021ffff  libcorecrypto.dylib (1000.100.38) <96A88875-7771-394E-A88E-389DCD02A935> /usr/lib/system/libcorecrypto.dylib
    0x7fff20220000 -     0x7fff2024cfff  libsystem_malloc.dylib (317.100.9) <029B5632-62B4-39F6-981C-BCA99C1FBF1D> /usr/lib/system/libsystem_malloc.dylib
    0x7fff2024d000 -     0x7fff20291fff  libdispatch.dylib (1271.100.5) <6B7B23E3-2FD4-3EA2-8A89-CE06244CCA98> /usr/lib/system/libdispatch.dylib
    0x7fff20292000 -     0x7fff202cbfff  libobjc.A.dylib (824) <847490B0-8FE5-32AE-96C8-BF3F3B3E1EB8> /usr/lib/libobjc.A.dylib
    0x7fff202cc000 -     0x7fff202cefff  libsystem_featureflags.dylib (28.60.1) <FEA91919-A5BB-3606-9445-F2077D90BF87> /usr/lib/system/libsystem_featureflags.dylib
    0x7fff202cf000 -     0x7fff20357fff  libsystem_c.dylib (1439.100.3) <DF45CDEC-6B7E-3586-94B4-F3679A762661> /usr/lib/system/libsystem_c.dylib
    0x7fff20358000 -     0x7fff203adfff  libc++.1.dylib (905.6) <B027735F-B398-381C-84A7-606D7BBE4997> /usr/lib/libc++.1.dylib
    0x7fff203ae000 -     0x7fff203c3fff  libc++abi.dylib (905.6) <22AFC7FC-2DB6-3EF0-9CC0-EFFB9B65D5E2> /usr/lib/libc++abi.dylib
    0x7fff203c4000 -     0x7fff203f3fff  libsystem_kernel.dylib (7195.101.2) <62A19DE4-50C5-3866-B5B2-43220E379C3B> /usr/lib/system/libsystem_kernel.dylib
    0x7fff203f4000 -     0x7fff203fffff  libsystem_pthread.dylib (454.100.8) <52F807B1-41A0-3D1E-AE89-115CA570863F> /usr/lib/system/libsystem_pthread.dylib
    0x7fff20400000 -     0x7fff2043bfff  libdyld.dylib (851.27) <9F95C644-D1BD-38D9-9612-6188FE9EA53C> /usr/lib/system/libdyld.dylib
    0x7fff2043c000 -     0x7fff20445fff  libsystem_platform.dylib (254.80.2) <03429519-EBEA-3549-84A6-0FD426CB7373> /usr/lib/system/libsystem_platform.dylib
    0x7fff20446000 -     0x7fff20471fff  libsystem_info.dylib (542.40.3) <C189F0D7-A430-328D-BD7F-7EB0FA023736> /usr/lib/system/libsystem_info.dylib
    0x7fff20472000 -     0x7fff2090ffff  com.apple.CoreFoundation (6.9 - 1775.118.101) <00F47B8F-A02B-37BF-B57F-129CF787F38B> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff21146000 -     0x7fff214a3fff  com.apple.Foundation (6.9 - 1775.118.101) <5B112EDB-35C1-31A7-BFDA-E185D1B49D93> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff21935000 -     0x7fff21b19fff  com.apple.CoreText (677.4.0.4 - 677.4.0.4) <F65330BD-9D48-3DE5-9E6B-1232B5BDB656> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff22500000 -     0x7fff2275ffff  libicucore.A.dylib (66112) <478D57C3-FFF8-35E1-A64F-8490A616AB37> /usr/lib/libicucore.A.dylib
    0x7fff22760000 -     0x7fff22769fff  libsystem_darwin.dylib (1439.100.3) <28AB0CBC-61F6-3A01-BCE2-A53DA1AECB0F> /usr/lib/system/libsystem_darwin.dylib
    0x7fff22ad0000 -     0x7fff22b7efff  com.apple.framework.IOKit (2.0.2 - 1845.100.19) <99034CC2-EC1B-38C0-A8DE-CE37672DF139> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff22b7f000 -     0x7fff22b8afff  libsystem_notify.dylib (279.40.4) <1AA89769-E07F-37CD-BBCF-6DBD345862EB> /usr/lib/system/libsystem_notify.dylib
    0x7fff22bd9000 -     0x7fff23920fff  com.apple.AppKit (6.9 - 2022.44.151) <10AFBC3A-E9A4-3E62-B9F5-97DF579B7A84> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff24b0c000 -     0x7fff24b1afff  libsystem_networkextension.dylib (1295.101.1) <33F45B5A-D346-3E7F-AB34-DFC4387E5A3C> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff24b79000 -     0x7fff24b8ffff  libsystem_asl.dylib (385) <4D4E0D4F-8B40-3ACC-85E1-16375966D6CC> /usr/lib/system/libsystem_asl.dylib
    0x7fff24f0c000 -     0x7fff255bdfff  com.apple.CoreGraphics (2.0 - 1463.14.2) <7EF922E6-1CB8-3214-B939-15776AC72B53> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff26287000 -     0x7fff2628efff  libsystem_symptoms.dylib (1431.100.22) <226C631F-5380-395A-AA20-D686AEA05B9B> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff2652f000 -     0x7fff26535fff  com.apple.DiskArbitration (2.7 - 2.7) <B6CB4430-35B5-3DD1-BA02-666426F87971> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff2858e000 -     0x7fff2859efff  libsystem_containermanager.dylib (318.100.4) <3BAF45DD-75D2-3D8A-845E-83A7058CBA08> /usr/lib/system/libsystem_containermanager.dylib
    0x7fff285bb000 -     0x7fff286defff  com.apple.Metal (244.119 - 244.119) <99A6E326-7BCC-33C5-B0C8-D80C29059592> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
    0x7fff28c82000 -     0x7fff28ec1fff  com.apple.ImageIO (3.3.0 - 2130.4.7) <9587C39A-6794-3EBF-91DA-AF73FB7EF038> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff292a5000 -     0x7fff292a8fff  libsystem_configuration.dylib (1109.101.1) <49050F1E-3143-31B9-8B5C-FCCE4C6F23E5> /usr/lib/system/libsystem_configuration.dylib
    0x7fff292a9000 -     0x7fff292adfff  libsystem_sandbox.dylib (1441.101.1) <24C8DF94-E258-3E24-AC96-2D1FB85F076A> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff29ead000 -     0x7fff29eaffff  libquarantine.dylib (119.40.2) <FABCD375-2FD7-3FF5-9A28-452D8A323D3E> /usr/lib/system/libquarantine.dylib
    0x7fff2a458000 -     0x7fff2a45cfff  libsystem_coreservices.dylib (127) <A1451528-AD1D-3E86-93A9-1340535FAF46> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff2a659000 -     0x7fff2a66bfff  libz.1.dylib (76) <45B3DDDD-FCA5-3387-98B8-38D9BFF68588> /usr/lib/libz.1.dylib
    0x7fff2a66c000 -     0x7fff2a6b7fff  libsystem_m.dylib (3186.100.3) <FA773620-5114-36B6-87CD-55EC4134D0C3> /usr/lib/system/libsystem_m.dylib
    0x7fff2a6b9000 -     0x7fff2a6befff  libmacho.dylib (980) <D503EC4A-6B6A-39C4-8218-9F4B6147A5BF> /usr/lib/system/libmacho.dylib
    0x7fff2a6db000 -     0x7fff2a6e6fff  libcommonCrypto.dylib (60178.100.1) <EA0C1728-C905-3A58-A285-C32ECF903BB4> /usr/lib/system/libcommonCrypto.dylib
    0x7fff2a6e7000 -     0x7fff2a6f1fff  libunwind.dylib (201) <32F74246-BEB8-3249-8C51-CAD863EF158E> /usr/lib/system/libunwind.dylib
    0x7fff2a6f2000 -     0x7fff2a6f9fff  liboah.dylib (203.42) <E3126D8C-F1F5-3E30-B7A2-0EB1AB0AF12D> /usr/lib/liboah.dylib
    0x7fff2a6fa000 -     0x7fff2a704fff  libcopyfile.dylib (173.40.2) <DDE4BE71-76BA-3CDC-B3B0-F5E0BADF8FF2> /usr/lib/system/libcopyfile.dylib
    0x7fff2a705000 -     0x7fff2a70cfff  libcompiler_rt.dylib (102.2) <AD12DBB0-8D0B-3D71-800D-E591A3CBE0D8> /usr/lib/system/libcompiler_rt.dylib
    0x7fff2a70d000 -     0x7fff2a70ffff  libsystem_collections.dylib (1439.100.3) <8B0EA86C-AFA8-3B51-916F-7ED9A42669A4> /usr/lib/system/libsystem_collections.dylib
    0x7fff2a710000 -     0x7fff2a712fff  libsystem_secinit.dylib (87.60.1) <18494A83-796C-33D5-A6D0-BD4E0C2BBFC4> /usr/lib/system/libsystem_secinit.dylib
    0x7fff2a713000 -     0x7fff2a715fff  libremovefile.dylib (49.101.1) <DC4523F8-F5FF-3837-BD58-0AA8763F8FDE> /usr/lib/system/libremovefile.dylib
    0x7fff2a716000 -     0x7fff2a716fff  libkeymgr.dylib (31) <1A66B854-350D-3064-A606-2D9BFE71C400> /usr/lib/system/libkeymgr.dylib
    0x7fff2a717000 -     0x7fff2a71efff  libsystem_dnssd.dylib (1310.100.10) <600B1851-C1D4-3ACF-BE2A-99E7E40E6FC0> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff2a71f000 -     0x7fff2a724fff  libcache.dylib (83) <ED7D7EB4-B248-33A9-9E6A-58F45EAB7602> /usr/lib/system/libcache.dylib
    0x7fff2a725000 -     0x7fff2a726fff  libSystem.B.dylib (1292.100.5) <EADFB1D1-E113-35B4-BD2D-C1E4C38010D4> /usr/lib/libSystem.B.dylib
    0x7fff2a727000 -     0x7fff2a72afff  libfakelink.dylib (3) <3EDDC5DA-6FAD-3031-91C1-E3465C34E643> /usr/lib/libfakelink.dylib
    0x7fff2a72b000 -     0x7fff2a72bfff  com.apple.SoftLinking (1.0 - 1) <82988A53-B066-3D39-A314-CE3C5C3868DE> /System/Library/PrivateFrameworks/SoftLinking.framework/Versions/A/SoftLinking
    0x7fff2d32e000 -     0x7fff2d38dfff  libcups.2.dylib (494.1) <D0767916-ADAF-3D25-BDC4-AB4FF0D48AAD> /usr/lib/libcups.2.dylib
    0x7fff2dc6f000 -     0x7fff2dc6ffff  liblaunch.dylib (2038.100.48) <3C5E58AF-F753-378B-8E0C-F3C9BB82E04D> /usr/lib/system/liblaunch.dylib
    0x7fff300f3000 -     0x7fff300f3fff  libsystem_product_info_filter.dylib (8.40.1) <4CCFBF85-6483-364F-A8D6-A5D2956BEC52> /usr/lib/system/libsystem_product_info_filter.dylib
    0x7fff333a4000 -     0x7fff333a4fff  com.apple.ApplicationServices (48 - 50) <706E69DF-06C7-3C8E-B0A5-BDD96635CAE4> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff3cb51000 -     0x7fff3cb54fff  com.apple.Carbon (160 - 164) <6E0D7D9A-2C50-3FBD-A4CF-1D1285F086F1> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff6bc3b000 -     0x7fff6bc4afff  com.apple.opengl (18.5.8 - 18.5.8) <DFFCB9A8-90D3-3189-B3ED-DBEED6B3695D> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff6e3a4000 -     0x7fff6e3abfff  com.apple.agl (3.3.4 - AGL-3.3.3) <D8CBB8CC-42C0-395A-9EF9-EBB009007838> /System/Library/Frameworks/AGL.framework/Versions/A/AGL

Model: MacBookPro17,1, BootROM 6723.101.4, proc 8:4:4 processors, 16 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: LPDDR4
AirPort: spairport_wireless_card_type_airport_extreme, wl0: Apr  2 2021 00:48:12 version 18.52.1.2.7.8.116 FWID 01-9f7b4413
Bluetooth: Version 8.0.4d18, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by muzimuzhi** [comment]
Similar problem here. TeXstudio just cannot be opened. I'm on macOS 11.4, Intel chip.

> Dyld Error Message:
>   dyld: Using shared cache: 4A889CE9-8D7E-304E-A5F7-84D819B0BF9C
> Library not loaded: @rpath/QtDBus.framework/Versions/A/QtDBus
>   Referenced from: /Applications/texstudio.app/Contents/Frameworks/QtGui.framework/Versions/A/QtGui
>   Reason: image not found

Full problem report: 
[4.0.0alpha6-macos-problem-report.txt](https://github.com/texstudio-org/texstudio/files/6832365/4.0.0alpha6-macos-problem-report.txt)

**Comment by sunderme** [comment]
That is probably fixed soon
