### ISSUE TITLE
Syntax highlighting bug with \url and $

### ISSUE THREAD

**Issue by MrAureliusR** [texstudio-org/texstudio#170]
Today I was trying to render a $ in a \url{}. I noticed that TeXstudio was highlighting it as an error when I had the dollar sign unescaped, so I escaped it, but then the document wouldn't compile. I found numerous posts online showing that dollar signs do not need to be escaped in \url{}. So I removed the backslash, and it compiled fine, but the syntax highlighting from that point onwards was completely messed up:
https://0x0.st/s_N0.png
I am using the hyperref package for \url.

### Environment
- TeXstudio: 2.12.8 (from PPA)
- Qt: 5.9.5
- OS: Ubuntu Budgie 18.04
- TeX distribution: Not sure? New to LaTeX

### Expected behavior
Hopefully the syntax highlighter in TeXstudio would recognise the \url{} and know that there could be unescaped $ inside it.

### Actual behavior
TeXstudio acts as if the $ is the opening $ in a pair of $, and the syntax highlighting is incorrect from that point onward.

### How to reproduce
Simply \usepackage{hyperref} and then insert any \url{} with an unescaped dollar sign.

**Comment by sunderme** [comment]
this is caused by the qeditor-syntax parser. This can't be fixed (easily).
As it can be handled on user side with employing '%$', rarely comes up, this will not be fixed

**Comment by ppoppitz** [comment]
Just wanted to note that this bug also applies to code that includes '$' in a 'minted' environment.
