### ISSUE TITLE
 edit the Download page to not to confuse/bother users

### ISSUE THREAD

**Issue by Gomesz785** [texstudio-org/texstudio#1706]
### Discussed in https://github.com/texstudio-org/texstudio/discussions/1705

<div type='discussions-op-text'>

<sup>Originally posted by **Gomesz785** July 25, 2021</sup>
I tried the latest version, but it is not supported of 32-bit. so what is the newest texstudio version supporting 32-bit?</div>
Please add the newest texstudio version supporting 32-bit  to the texstudio website.

**Comment by Gomesz785** [comment]
Here is the version: https://github.com/texstudio-org/texstudio/discussions/1705#discussioncomment-1047100

**Comment by Gomesz785** [comment]
@sundreme https://github.com/texstudio-org/texstudio-meta/issues/4#issuecomment-888077296

**Comment by sunderme** [comment]
done

**Comment by Gomesz785** [comment]
Thanks. 
![Screenshot_2021-09-27-08-54-32](https://user-images.githubusercontent.com/87658122/134841112-ad0ca224-b5f6-4710-b8f9-be165ca4f974.png)
