### ISSUE TITLE
Compilation du fichier

### ISSUE THREAD

**Issue by Gomesz785** [texstudio-org/texstudio#1707]
### Discussed in https://github.com/texstudio-org/texstudio/discussions/1658 (the french version)

<div type='discussions-op-text'>

<sup>Originally posted by **Wamavis** June 15, 2021</sup>
Bonjour tout le monde! Je suis un débutant en latex et j'utilise TexStudio comme éditeur. Je rencontre un problème au moment de la compilation de mon fichier tex. Voici le message d'erreur que cela m'affiche : "Sorry, but pdflatex.exe did not succeed. The log file hopefully contains the information to get MiKTeX going again: C:\Users\Lepetit\AppData\Local\MiKTeX\miktex\log\pdflatex.log". J'ai vraiment besoin de votre aide </div>

**Below translated version**

Compiling File # 1658

Hello everyone! I am a latex newbie and use TexStudio as my editor. I have a problem while compiling my tex file. Here is the error message it shows me: "Sorry, but pdflatex.exe did not succeed. The log file hopefully contains the information to get MiKTeX going again: C: \ Users \ Lepetit \ AppData \ Local \ MiKTeX \ miktex \ log \ pdflatex.log ". I really need your help

**Comment by sunderme** [comment]
This is basically a latex issue.
tex.stackexchange.com or similar sites help.

**Comment by Gomesz785** [comment]
> This is basically a latex issue.
> tex.stackexchange.com or similar sites help.

I am extremely sorry if I bothered you: Nonetheless I gave an english translation of the issue #1658 to help you and the issue creator. ;)
