### ISSUE TITLE
Symbols not showing correctly

### ISSUE THREAD

**Issue by SpyrosFronimos** [texstudio-org/texstudio#1708]
-  TeXstudio: 3.1.2
-  Qt: 5.15.2
-  OS: Linux Manjaro
-  TeX distribution: texlive 2021

In the Symbols side panel all basic symbols are shown as Chinese characters. 
![Texstudio_Symbols](https://user-images.githubusercontent.com/53839524/126953843-4639be57-7c29-418f-acfc-dbd7cf97a378.png)
 For example the first symbol sould be the "plus-minus" sign.

**Comment by muzimuzhi** [comment]
Looks like an encoding issue. Does it reproduce in any previous version?

**Comment by sunderme** [comment]
The symbols are svg.
Probably best to compile txs locally.

**Comment by sunderme** [comment]
where is the package from ?
(by the way, do the symbols make sense ?)

**Comment by muzimuzhi** [comment]
Taking the svg for first operator ([`img001operators`](https://github.com/texstudio-org/texstudio/blob/master/symbols-ng/operators/img001operators.svg?short_path=30175ef)) as an example, it contains `<glyph d='path data' ... unicode='&#13318;'/>` and 
```xml
<g id='page1'>
<text class='f0' x='39' y='66'>&#13318;</text>
</g>
```
in which `&#13318;` is the decimal form of [U+3406 㐆](https://www.fileformat.info/info/unicode/char/3406/index.htm). Also Chrome shows the same character instead of the `d='path data'` part. interesting

**Comment by sunderme** [comment]
no feedback

**Comment by SpyrosFronimos** [comment]
I apologize for the late response. I didn't have this issue with any previous version. The package is installed from Manjaro package manager.

**Comment by sunderme** [comment]
txs works fine on all other platforms.
So, two points jump to mind:
1) qtsvg needs to be installed
2) and the svg iconengine needs to be present.
As we don't build the manjaro package, that is outside of our scope. Building txs from source may help.(which should be easy enough on linux)

**Comment by SpyrosFronimos** [comment]
Qt5-svg is installed. I just built txs 3.1.2 from source and still get the same icons
![txs3_1_2](https://user-images.githubusercontent.com/53839524/128240451-36d3a206-9a50-4d95-840e-dcc917c96e65.png)

**Comment by sunderme** [comment]
I have checked manjaro/xfce in a VM, works fine...

**Comment by SpyrosFronimos** [comment]
I use Manjaro kde plasma. When I last built txs from source the symbols where shown properly and I think I run version 3.1.2.

**Comment by sunderme** [comment]
as manjaro/arch is a rolling release, all kind of things have changed since the last txs version.
As it occurs only on your system, I would rather search for an issue there.

**Comment by SpyrosFronimos** [comment]
I will try to check for conflicts with other apps and give a feedback.

**Comment by sunderme** [comment]
close for now as it works for me (on all systems)
Please come back if there is anything concrete which points to txs as a culprit rather than manjaro/kde

**Comment by SpyrosFronimos** [comment]
**Feedback**
While I was changing the style of GUI in TexStudio, I realized that only with "Orion Dark" style all the symbols where shown correctly. Below you can see al the available styles as well as the result.
![styles](https://user-images.githubusercontent.com/53839524/134432370-771b4440-9e49-4958-92db-0b58d667d0b1.png)
![OrionDark2](https://user-images.githubusercontent.com/53839524/134432381-e89817d5-eaed-4061-87d9-b0e329e80e86.png)
