### ISSUE TITLE
Quick preview of inline/display equations incorrect when using $ or $$ in TexStudio + other problems.

### ISSUE THREAD

**Issue by l3gi0n0fh3ll** [texstudio-org/texstudio#1709]
### Environment
- TeXstudio: 3.1.2 (git 3.1.2)
- Qt: Using Qt Version 5.15.2, compiled with Qt 5.15.2 R
- OS: Windows 10 64-bit
- TeX distribution: MikTex

**Problem 1:**

When I hover my mouse on a display/inline equation enclosed by $$ or $ , the equation shown is incorrect: 

[![enter image description here][1]][1]

but when it is enclosed by \\[ and \\] , The correct equation is shown:

[![enter image description here][2]][2]

**Problem 2:** 

When I hover my mouse on an inline equation enclosed by \\( and \\) no equation is shown.

**Problem 3:**

When viewing quick previews of equations, temporary files are created at: C:\Users\user-name\AppData\Local\Temp ... Is there a way to change this location to somewhere else  ?

Many Thanks

  [1]: https://i.stack.imgur.com/ivQ6S.jpg
  [2]: https://i.stack.imgur.com/bx2rL.jpg

**Comment by muzimuzhi** [comment]
I saw @sunderme has implemented this in https://github.com/texstudio-org/texstudio/commit/0f526ee7744e1b422d1f18c3bd62df91d3984535, so you can try the latest builds at the bottom of page https://github.com/texstudio-org/texstudio/actions/runs/1068722720.

**Comment by l3gi0n0fh3ll** [comment]
But that's just problem 2 ... what about problem 1 and 3 ?

**Comment by sunderme** [comment]
1&2 are fixed
I don't know if qt temp dir uses a variable. You can investigate yourself (QTemporaryFile)

**Comment by sunderme** [comment]
https://doc.qt.io/qt-5/qdir.html#tempPath
