### ISSUE TITLE
Internal viewer crashes TeXstudio 2.12.8 (Mac OS X)

### ISSUE THREAD

**Issue by DoraPaula** [texstudio-org/texstudio#171]
### Environment
- TeXstudio: 2.12.8-osx (downloaded: texstudio-2.12.8-osx.dmg)
- Qt: 5.10.0, compiled with Qt 5.10.0 R
- OS: Mac OS X El Capitan
- TeX distribution: MacTex 2018

Note: The complete system has been installed yesterday on a previously erased disk.

### Expected behavior
An error message

### Actual behavior
TeXstudio crashes if I use F5 to build and view: The build completes (pdf is there), but opening the embedded viewer leads (always) to a crash.

TeXstudio does not crash if I use F6 (compile only), the crash occurs when I try to open the resulting pdf in the viewer (F7).

### How to reproduce
1. Download texstudio-2.12.8-osx.dmg
2. Install the dmg
3. Open TeXstudio
4a. Reset configuration to default
4b. Reopen TeXstudio
5. Compile the below code (F6) -> produces a pdf
6. Call the viewer (F7) -> CRASH

[Or instead of step 5 and 6, just use F5 ;-)]

\documentclass{article}
\begin{document}
Hello World!
\end{document}

**Comment by sunderme** [comment]
older computer ?
try https://github.com/texstudio-org/texstudio/releases/download/2.12.8/texstudio-2.12.8-osx-forOldCPUs.dmg

**Comment by DoraPaula** [comment]
Old!? Antique: MacBook Late 2008 ;-)

Sorry, I should have mentioned before, that I've already seen the "forOldCPUs"-hint and tried it without luck (TeXstudio still crashes).

**Comment by sunderme** [comment]
Use homebrew to install txs. (see wiki)

**Comment by DoraPaula** [comment]
homebrew worked fine - thx a lot!
