### ISSUE TITLE
[Wayland] Search again (F3) and switch window (Alt+Tab) remove keyboard focus from the document editor

### ISSUE THREAD

**Issue by goduck777** [texstudio-org/texstudio#1711]
### Environment
- TeXstudio: 3.1.1 3.1.2
- Qt: 5.15.2
- OS: KDE Plasma 5.22.3 Wayland

### Expected behavior

The focus should be on the text editor

### Actual behavior

I found that pressing F3 only will not cause focus lost from the editor. However, at this time, if I press Alt+Tab and change to a different window, and Alt+Tab to change back to texstudio, the focus is not on the editor window any more.

More seriously, from this time on, whenever I use Alt+Tab, the focus will never be on the editor window, even if I close the search box. I have to close this file and reopen it again. Surprisingly, the files opened at other tabs are not affected.

### How to reproduce

1. Start a new file
2. Search something with Ctrl+F
3. Press F3 for next item
4. Press Esc to leave the search box
4. Alt+Tab to another window
5. Alt+Tab back to texstudio
6. The focus is on search box

**Comment by sunderme** [comment]
works fine on windows

would be nice to have all the basic questions from the issue form answered, i.e. OS, version of txs

**Comment by sunderme** [comment]
Then it is not an txs issue.
I would close this.

**Comment by goduck777** [comment]
Hi @sunderme, I wonder if txs will support wayland or not. I can test it using Gnome and Sway. If it is a problem in all the wayland platforms, then I think it should be fixed.

**Comment by sunderme** [comment]
it is not like txs does anything special on wayland. QT is the GUI layer which (mostly) determines behaviour.
Basically there is nothing I can do.

**Comment by goduck777** [comment]
I confirm that this is a KDE bug. The bug only appears when the search/replace history drop down menu is shown. Sway does not have this problem.

I will report this bug to KDE. Currently, I hope an option to turn off search/replace history can be added to make it work in KDE wayland.

**Comment by sunderme** [comment]
I don't see that we can implement work-arounds here.
You can do so and compile yourself though. (QSearchPanel)
