### ISSUE TITLE
Latex-light mode

### ISSUE THREAD

**Issue by friedl0373** [texstudio-org/texstudio#1714]
### Describe the feature and the current behavior/state

I am working on a very long project (tex-file with 3000 pages distributed over many tex-files) and I find that texstudio becomes very slow when I type anything since it spends too much time on checking all kinds of issues. For example, I type $  in the middle of the document and it seems like texstudio spends a lot of time figuring out what this means for the rest of the file.
I would find it very useful to have a "light" latex environment which only does "local" highlighting, i.e. which tries the best to present the current page and ignores all other files and everything else. I tried some of the other "highlighting" - which are faster -  but then found that the (un-) comment has a different effect. 

### Who will benefit with this feature?

Anybody dealing with large projects and/or slow computers (for me it's not a hardware issue, I have a brandnew laptop with 32 gb RAM etc)

**Comment by sunderme** [comment]
you can turn off the loading of included files.
You can turn off online checks.
Without details, I can't say what really slows down on your computer, so that is all the advice I can give.

**Comment by sunderme** [comment]
And typing $ is only affecting the local file.
What version of txs ? I assume WIndows ?

**Comment by friedl0373** [comment]
Thanks for your quick response!

I am using the latest version 3.1.2 on Windows 10. Each local file
corresponds to about 200 pages of pdf.
As an example, commenting an input file can take several seconds and
sometimes longer. It seems to me like texstudio is trying too much at such
a point.
When I don't do any highlighting (i.e. highlight plaintext), then this
issue does not arise.

**Comment by sunderme** [comment]
again, without details, not much I can do.
You can try 4.0.0alpha which makes more highlighting asynchronous.

**Comment by sunderme** [comment]
maybe quick tip:
1) avoid automatically loading includes (or opening them) as txs scans them and uses that information for the rest of the document. That may cause the delays commenting/uncommenting include statements as apparently information has changed
2) $ is always costly as it basically inverts math/non-math highlighting. This is basically true for all tex-editors.
\( \) avoids this problem.

**Comment by friedl0373** [comment]
Thanks for your advice!

I just installed version 4.0, unfortunately it is not much better.
If I use the highlight mode for latex I still have the following issues:
If I comment out an input it takes at times a very long time till I can
move on
if I type \begin{claim}    it takes a very long time before it lets me type
anything else.
These issues do not arise when I use "highlight plaintext".

Best,

Stefan

**Comment by sunderme** [comment]
again, without any context ...

**Comment by sunderme** [comment]
you can provide me (sunderme@gmx.de) with an example which behaves badly, so that I can take a look.
But this general, there is nothing worth investigating.

**Comment by sunderme** [comment]
txs has been improved to better handle files with a large number of inputs.
Also handling labels was improved.
