### ISSUE TITLE
Find Next (possible) bug

### ISSUE THREAD

**Issue by joaompereira** [texstudio-org/texstudio#1715]
Hi,

I am having trouble with the Find Next feature, and I am not sure if what I am mentioning here is a bug or not. I have also looked for the answer online and haven't found it, so I am posting it here. 

Whenever I search for an expression, the find next always starts to look at the beginning of the document, instead of starting on the current position of the cursor. One has to scroll down with the find next until it reaches the current position of the cursor. If the description is not enough, I can also add an experiment showing expected behavior / actual behavior.

I remember this was not the behavior in previous versions, so I wonder if this was introduced accidently (bug) or on purpose (feature), but I do not like this behavior.

### Environment
- TeXstudio: 3.1.2
- Qt: 5.15.2
- OS: Windows 10
- TeX distribution: miktex

**Comment by sunderme** [comment]
sounds like you deactivated "search from current cursor position"
<img width="255" alt="grafik" src="https://user-images.githubusercontent.com/14033169/128077602-5f9682ee-fb69-476a-852e-2bf6a3eacee6.png">

**Comment by joaompereira** [comment]
Thank you! I suspected it should be some setting like that but couldn't find it anywhere. I'll go ahead and close the issue.
