### ISSUE TITLE
Spell checking based on \selectlanguage

### ISSUE THREAD

**Issue by Krzmbrzl** [texstudio-org/texstudio#172]
### Environment
- TeXstudio: TeXstudio 2.12.9 (2.12.8-113-g7268741)
- Qt: 5.6.1
- OS: Linux Mint 18.3
- TeX distribution: TeXLive 2017

For people like me who are constantly switching between writing documents in different languages it would be really neat, if the spell-checking in TS would be sensitive to the `\selectlanguage` command provided by `babel`.
More generically the user could specify a custom command which he/she is using to switch the language. In the same way the user could also specify which Language should correspond to which identifier (e.g. `ngerman` -> `de_DE`)

**Comment by thatlittleboy** [comment]
On a per-document level, there is already a functionality for this using magic comments:
e.g.
```
% !TeX spellcheck = de_DE
```

See the [user manual ](http://texstudio.sourceforge.net/manual/current/usermanual_en.html#SECTION_TEXCOM) for more info.

**Comment by Krzmbrzl** [comment]
Okay that's good to know and it's definitely a great starting point.
Thanks for pointing this out!

**Comment by Krzmbrzl** [comment]
Actually - when thinking about it a little more - this is fulfilling all of my needs just fine.

*Closing...*
