### ISSUE TITLE
Scroll /highlight bug when align environment spans more than one page

### ISSUE THREAD

**Issue by ShrirajHegde** [texstudio-org/texstudio#1720]
### Environment
- TeXstudio:TeXstudio 3.1.2 (git n/a) 
- Qt: Using Qt Version 5.15.2, compiled with Qt 5.15.2 R
- OS: Linux (Fedora 34) 
- TeX distribution: texlive

### Expected behavior
PDF Autoscroll on compile scrolls and highlights the line cursor is in (tex file)

### Actual behavior
When `align` environment from `amsmath` spills over to the next page, the scroll jumps to the last page number and highlights the page number, this continues until the environment ends and a fresh environment is used in the current page

### How to reproduce
Tex file:
https://pastebin.com/qu9xhcEz

* paste this in a tex file and open in texstudio.
* compile once, and scroll to second page in PDF
* take the cursor to a line number after displaybreak (say30)
* compile again

Instead of highlighting second page,or equation in second page, the highlight and scrolling is done to the page where align environment starts. Creating a new environment in line 39 say:
```latex
\begin{align*}
	3x + 9y &=  -12 \\	
\end{align*}
```
will restore the scrolling

**Comment by sunderme** [comment]
Same with texworks, so it is a synctex issue. (https://github.com/jlaurens/synctex)
Nothing we can do.

**Comment by ShrirajHegde** [comment]
> Same with texworks, so it is a synctex issue. (https://github.com/jlaurens/synctex)
> Nothing we can do.

that repo seems to be dead, Isn't there any workaround? anything better than this

**Comment by sunderme** [comment]
I am afraid, no.
