### ISSUE TITLE
Provide option to open .tex file with *tikzpicture* elementes collapsed

### ISSUE THREAD

**Issue by elyoas** [texstudio-org/texstudio#1729]
### Describe the feature and the current behavior/state
Currently, when opening a large tex file, it is difficult to navigate. To make navigation easier, the user sometimes collapses some unnecessary section, such as tikzpictures. Why not provide an option to collapse them automatically on opening a .tex file?

### Who will benefit with this feature?
Those who draw images by hand (they take a lot of space) especially `\begin{tikzpicture} \end{tikzpicture}`

**Comment by muzimuzhi** [comment]
Here is a script macro which collapses every line containing `\begin{tikzpicture}` and is automatically triggered (see the trigger `?load-file`) when a file is loaded.
```javascript
%SCRIPT
envname = "tikzpicture";

lines = editor.document().textLines();
for (var i=0; i<lines.length; i++) {
    l = lines[i];
    if (l.includes("\\begin{" + envname + "}")) {
			editor.document().collapse(i);
    }
}
```
![image](https://user-images.githubusercontent.com/6376638/130139323-fd3d686c-7fbb-4ca4-a75b-32a737bb4a81.png)

Doc for and examples of user macros:
 - [sec. 4.6.3 Script Macros](https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html#JAVASCRIPT-MACROS), user manual 
 - [sec. 4.6.4 Triggers](https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html#sectionTriggers), user manual
 - [Collection of user macro scripts](https://github.com/texstudio-org/texstudio/wiki/Scripts), wiki
 - https://github.com/texstudio-org/texstudio-macro, repository for official macro scripts

**Comment by sunderme** [comment]
Is the script sufficient ?

**Comment by elyoas** [comment]
It does not work!

![Screenshot_20210824_20-11-59](https://user-images.githubusercontent.com/64473898/130676014-971cf444-f0ac-4f24-b49f-93d1fbf840a8.png)

**Comment by sunderme** [comment]
the code works with txs4.0.0
```
%SCRIPT
envname = "tikzpicture";

lines = editor.document().textLines();
for (var i=0; i<lines.length; i++) {
    l = lines[i];
    if (l.indexOf("\\begin{" + envname + "}")>-1) {
			editor.document().collapse(i);
    }
}
```
works with all txs versions.

**Comment by sunderme** [comment]
I assume the code works, solves the issue -> closed
