### ISSUE TITLE
Start LanguageTool automatically (4.0.0beta1)

### ISSUE THREAD

**Issue by MikeSmith61x** [texstudio-org/texstudio#1730]
### Environment
- TeXstudio: git 4.0.0beta1
- Qt: 6.1.2
- OS: Windows 10 x64
- TeX distribution: TeX Live 2021
- LanguageTool 5.4

### Expected behavior
Launch LanguageTool when needed.

The following command runs perfectly fine on the command line:
`java -cp languagetool.jar org.languagetool.server.HTTPServer`

### Actual behavior
Does not start LT. 

ERROR log:
----------------------
where java: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exeC:\Program Files\Java\jre1.8.0_301\bin\java.exe

JAVA: java
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)

Real-time checking is enabled.
Grammar checking is enabled.

Tries to start automatically.

LT current status: error
Error: Could not find or load main class org.languagetool.server.HTTPServer

LT-URL: http://localhost:8081/v2/check

### How to reproduce
![LT](https://user-images.githubusercontent.com/89277655/130291303-1c83242e-0ac3-46c5-a0b9-353b40247bab.JPG)

**Comment by sunderme** [comment]
works fine here

**Comment by MikeSmith61x** [comment]
> works fine here

Are you using the same arguments and TS 4.0.0 beta1?

**Comment by sunderme** [comment]
I have an additional argument -p 8081

**Comment by MikeSmith61x** [comment]
It is the default. But are you also using the 4.0.0 beta1 version or the latest stable?

**Comment by sunderme** [comment]
I am using dev which is 4 commits ahead, non of them affecting LT.

**Comment by MikeSmith61x** [comment]
I moved LT to another directory which does not require admin privileges and now it works. This strange, because it was installed in the same directory it was running perfectly fine using 3.1.2.

**Comment by dirkziegenbalg** [comment]
I've the same issue with 4.0.3 on Win 10 and LT 5.5. It runs fine when started from the command line but cannot be started by TeXstudio. The trick with the new folder did also not work for me. It somehow looks as the starting command is not processed correctly.

**Comment by sunderme** [comment]
please don't add reports in closed issues (unless you want them to be ignored)
In principle LT5.5 on win10 with 4.0.3 works.
