### ISSUE TITLE
libpoppler-qt6.3.dylib not loaded by dylib

### ISSUE THREAD

**Issue by maimaris** [texstudio-org/texstudio#1732]
![image](https://user-images.githubusercontent.com/11732627/130430811-3dbc82bc-c609-431a-8f9e-474ea3f0933f.png)
### Environment
- TeXstudio: 
- post beta 1 
- texstudio-osx-4.0.0-202108222003-git_b60bdcab.dmg
- to cater with copy libbrotli common (work-around)
CD #429: Commit b60bdca pushed by sunderme
- Qt: 
- qt6
- OS: 
- mac catalina
- TeX distribution: 
texlive latest
### Expected behavior
Texstudio to run

### Actual behavior

![image](https://user-images.githubusercontent.com/11732627/130430811-3dbc82bc-c609-431a-8f9e-474ea3f0933f.png)

**Comment by sunderme** [comment]
should be fixed
