### ISSUE TITLE
4.0 beta 2: TeX installation from MacPorts not found

### ISSUE THREAD

**Issue by ednl** [texstudio-org/texstudio#1740]
### Environment
- TeXstudio: git 4.0.0beta2
- Qt: 6.1.2
- OS: MacOS 11.5.2 Big Sur on Apple Silicon (M1)
- TeX distribution: texlive from MacPorts: https://ports.macports.org/port/texlive/

### Expected behavior

All the TeX commands are available in the user path under /opt/local/bin (with the actual texbin dir as /opt/local/libexec/texlive/texbin) so I would have expected Texstudio to find them.

### Actual behavior

On first startup of Texstudio, it says that no TeX installation was found. In Settings, the paths to the commands are all empty. I can fix it by manually entering every command as /opt/local/bin/latex etc. but this is very tedious. Is it not possible to indicate where texbin is once, or autodetect the TeX commands in the user path? Should MacPorts link to their own texbin from a predefined location somewhere in /Library perhaps?

### How to reproduce

Remove all old Texstudio configuration files (this was a fresh install, I had never started Texstudio on this computer), download and run Texstudio 4.0.0 beta 2.

**Comment by sunderme** [comment]
when you open a terminal and type "latex --version" , what is the output ?

**Comment by ednl** [comment]
```
pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2021/MacPorts 2021.58693_0)
kpathsea version 6.3.3
Copyright 2021 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.03
```

**Comment by ednl** [comment]
I tested the latest release version 3.1.2 after removing all local config files with `rm -fr ~/.config/texstudio/` and that did work, it picked up all the binaries and populated the Settings with them. Removed the configs and ran 4.0beta2 again, and it gave the same error: no TeX installation found, every command empty.

**Comment by sunderme** [comment]
what is the output of help/check latex installation with 3.1.2 and 4.0.0 ?

**Comment by ednl** [comment]
# 3.1.2:

```
dpi: 72
which pdflatex: /opt/local/bin/pdflatex

PDFLATEX: pdflatex -version
pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2021/MacPorts 2021.58693_0)
kpathsea version 6.3.3
Copyright 2021 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.03

Environment variables:
COMMAND_MODE=unix2003
HOME=/Users/USERNAME
LOGNAME=USERNAME
PATH=/Users/USERNAME/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/usr/local/texlive/2012/bin/x86_64-darwin
SHELL=/opt/local/bin/bash
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.0XONjVqdwx/Listeners
TMPDIR=/var/folders/qh/gz40m32d2qg0stmmsp3y8sdc0000gn/T/
USER=USERNAME
XPC_FLAGS=0x0
XPC_SERVICE_NAME=application.texstudio.6777849.6778020
__CFBundleIdentifier=texstudio
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x5

TeXstudio:
Path        : /Users/USERNAME/Desktop/texstudio.app/Contents/MacOS/texstudio
Program call: /Users/USERNAME/Desktop/texstudio.app/Contents/MacOS/texstudio
Setting file: /Users/USERNAME/.config/texstudio/texstudio.ini

Command configuration in TeXstudio:
    Texindy (texindy): 
    XeLaTeX (xelatex) (r): xelatex -synctex=1 -interaction=nonstopmode %.tex
    Default Viewer (view): txs:///view-pdf
    Asymptote (asy): 
    Ps2Pdf (ps2pdf): ps2pdf %.ps
    DviPs (dvips): dvips -o %.ps %.dvi
    PdfLaTeX (pdflatex) (r): pdflatex -synctex=1 -interaction=nonstopmode %.tex
    DviPng (dvipng): dvipng -T tight -D 120 %.dvi
    Precompile (pre-compile): 
    Build & View (quick): txs:///compile | txs:///view
    GIT (git): git 
    DVI->PDF Chain (dvi-pdf-chain): txs:///latex | txs:///dvipdf | txs:///view-pdf
    DviPdf (dvipdf): dvipdfmx %.dvi
    Ghostscript (gs): gs "?am.ps"
    PS Viewer (view-ps): open %.ps > /dev/null
    Asymptote PDF Chain (asy-pdf-chain): txs:///pdflatex | txs:///asy | txs:///pdflatex | txs:///view-pdf
    Makeglossaries (makeglossaries): makeglossaries %
    External Terminal (terminal-external): open -a Terminal ?c:a"
    External PDF Viewer (view-pdf-external): open %.pdf > /dev/null
    Default Glossary Tool (glossary): txs:///makeglossaries
    DVI Chain (dvi-chain): txs:///latex | txs:///view-dvi
    LuaLaTeX (lualatex) (r): lualatex -synctex=1 -interaction=nonstopmode %.tex
    PDF Chain (pdf-chain): txs:///pdflatex | txs:///view-pdf
    SVNADMIN (svnadmin): 
    BibTeX (bibtex): bibtex %.aux
    SVN (svn): 
    DVI Viewer (view-dvi): open %.dvi > /dev/null
    MetaPost (metapost): mpost -interaction=nonstopmode ?me)
    Latexmk (latexmk): latexmk -pdf -silent -synctex=1 %
    Internal Precompile (internal-pre-compile): txs:///pre-compile | txs:///conditionally-recompile-bibliography
    LaTeX (latex) (r): latex -src -interaction=nonstopmode %.tex
    BibTeX 8-Bit (bibtex8): bibtex8 %.aux
    PDF Viewer (view-pdf): txs:///view-pdf-internal --embedded
    Biber (biber): biber %
    DVI->PS->PDF Chain (dvi-ps-pdf-chain): txs:///latex | txs:///dvips | txs:///ps2pdf | txs:///view-pdf
    PS Chain (ps-chain): txs:///latex | txs:///dvips | txs:///view-ps
    Asymptote DVI Chain (asy-dvi-chain): txs:///latex | txs:///asy | txs:///latex | txs:///view-dvi
    Default Index Tool (index): txs:///makeindex
    Recompile Bibliography (recompile-bibliography): txs:///compile | txs:///bibliography | txs:///compile
    texdoc (texdoc): texdoc 
    Makeindex (makeindex): makeindex %.idx
    Default Bibliography Tool (bibliography): txs:///bibtex
    Default Compiler (compile) (r): txs:///pdflatex

Additional Search Paths:
    Command: /usr/local/texlive/2012/bin/x86_64-darwin
    Log: 
    Pdf: 
```

# 4.0.0.beta2:

```
dpi: 72
which pdflatex: usage: which [-as] program ...

PDFLATEX:  -version


Environment variables:
COMMAND_MODE=unix2003
HOME=/Users/USERNAME
LOGNAME=USERNAME
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/usr/local/texlive/2012/bin/x86_64-darwin
SHELL=/opt/local/bin/bash
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.0XONjVqdwx/Listeners
TMPDIR=/var/folders/qh/gz40m32d2qg0stmmsp3y8sdc0000gn/T/
USER=USERNAME
XPC_FLAGS=0x0
XPC_SERVICE_NAME=application.texstudio.6778682.6778861
__CFBundleIdentifier=texstudio
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x5

TeXstudio:
Path        : /Users/USERNAME/Desktop/texstudio.app/Contents/MacOS/texstudio
Program call: /Users/USERNAME/Desktop/texstudio.app/Contents/MacOS/texstudio
Setting file: /Users/USERNAME/.config/texstudio/texstudio.ini

Command configuration in TeXstudio:
    DviPng (dvipng): 
    Ghostscript (gs): 
    Default Bibliography Tool (bibliography): txs:///bibtex
    DviPs (dvips): 
    Recompile Bibliography (recompile-bibliography): txs:///compile | txs:///bibliography | txs:///compile
    Biber (biber): 
    XeLaTeX (xelatex) (r): 
    PS Viewer (view-ps): open %.ps > /dev/null
    Makeindex (makeindex): 
    Asymptote DVI Chain (asy-dvi-chain): txs:///latex | txs:///asy | txs:///latex | txs:///view-dvi
    GIT (git): git 
    Latexmk (latexmk): 
    Default Compiler (compile) (r): txs:///pdflatex
    DVI->PS->PDF Chain (dvi-ps-pdf-chain): txs:///latex | txs:///dvips | txs:///ps2pdf | txs:///view-pdf
    DVI->PDF Chain (dvi-pdf-chain): txs:///latex | txs:///dvipdf | txs:///view-pdf
    PDF Viewer (view-pdf): txs:///view-pdf-internal --embedded
    SVNADMIN (svnadmin): 
    Internal Precompile (internal-pre-compile): txs:///pre-compile | txs:///conditionally-recompile-bibliography
    LaTeX (latex) (r): 
    BibTeX 8-Bit (bibtex8): 
    PDF Chain (pdf-chain): txs:///pdflatex | txs:///view-pdf
    Default Viewer (view): txs:///view-pdf
    Texindy (texindy): 
    MetaPost (metapost): 
    Asymptote (asy): 
    PS Chain (ps-chain): txs:///latex | txs:///dvips | txs:///view-ps
    Asymptote PDF Chain (asy-pdf-chain): txs:///pdflatex | txs:///asy | txs:///pdflatex | txs:///view-pdf
    BibTeX (bibtex): 
    Ps2Pdf (ps2pdf): 
    DVI Chain (dvi-chain): txs:///latex | txs:///view-dvi
    Default Glossary Tool (glossary): txs:///makeglossaries
    External PDF Viewer (view-pdf-external): open %.pdf > /dev/null
    LuaLaTeX (lualatex) (r): 
    Precompile (pre-compile): 
    DVI Viewer (view-dvi): open %.dvi > /dev/null
    Default Index Tool (index): txs:///makeindex
    PdfLaTeX (pdflatex) (r): 
    Makeglossaries (makeglossaries): 
    texdoc (texdoc): 
    External Terminal (terminal-external): open -a Terminal ?c:a"
    SVN (svn): 
    Build & View (quick): txs:///compile | txs:///view
    DviPdf (dvipdf): 

Additional Search Paths:
    Command: /usr/local/texlive/2012/bin/x86_64-darwin
    Log: 
    Pdf: 
```

**Comment by ednl** [comment]
So yeah, the $PATH variable that is set correctly in bash doesn't get picked up by 4.0 but it does work in 3.1.2. If I `echo $PATH` on the command prompt, I get: `/Users/USERNAME/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin`. I see that both installations add `/usr/local/texlive/2012/bin/x86_64-darwin` to the end of their PATH, which doesn't exist.

Non-standard settings on my machine: I use bash (from MacPorts, at /opt/local/bin/bash which is added to /etc/shells) instead of zsh. Every shell is a login shell on MacOS, so dividing things up between .bashrc, bash_profile and .profile isn't really necessary but still, these are the relevant lines from mine:

```
$ cat .profile 
# MacPorts
[ -d /opt/local/sbin ] && export PATH="/opt/local/sbin:$PATH"
[ -d /opt/local/bin ] && export PATH="/opt/local/bin:$PATH"

# Add user bin to path if it exists
[ -n "$HOME" ] && [ -d "$HOME/bin" ] && export PATH="$HOME/bin:$PATH"
```
```
$ cat .bash_profile 
# Load .profile, containing login, non-bash related initializations.
if [ -f ~/.profile ]; then
	source ~/.profile
fi

# Load .bashrc, containing non-login related bash initializations.
if [ -f ~/.bashrc ]; then
	source ~/.bashrc
fi
```
```
$ cat .bashrc 
[ -r ~/.bash_aliases ] && source ~/.bash_aliases
```

And these are links I saw in /Library to the TeX installation:

```
$ ls -l /Library/TeX/Distributions/MacPorts-TeXLive.texdist/Contents/
total 0
drwxr-xr-x  7 root  admin  224 27 aug 09:13 AllTexmf
drwxr-xr-x  6 root  admin  192 27 aug 09:13 Doc
lrwxr-xr-x  1 root  admin   21 12 aug 02:22 Info -> /opt/local/share/info
lrwxr-xr-x  1 root  admin   20 12 aug 02:22 Man -> /opt/local/share/man
drwxr-xr-x  4 root  admin  128 27 aug 09:13 Programs
drwxr-xr-x  3 root  admin   96 27 aug 09:13 Resources
lrwxr-xr-x  1 root  admin   16 12 aug 02:22 Root -> /opt/local/share
-rw-r--r--  1 root  admin    2 12 aug 02:22 TeXDistVersion
lrwxr-xr-x  1 root  admin   28 12 aug 02:22 TexmfLocal -> /opt/local/share/texmf-local
lrwxr-xr-x  1 root  admin   23 12 aug 02:22 TexmfSysVar -> /opt/local/var/db/texmf
```

**Comment by sunderme** [comment]
hmm.
the change was introduced with 757bb459414b6a61493ee999c527c9c6913f644b because of an issue (#1700)
It now follows apple's guideline in detecting the path.
Using macport/bash is apparently not compatible with that.

**Comment by ednl** [comment]
Thanks for checking. I don't know what the official guidelines are, I can't find them with a few tries on google. I do think that GUI apps should never rely on shell environment variables. On the other hand, the commands it wants to find are probably meant to be executed via a shell/sys call from Texstudio? Does that rely on the PATH again, or are they executed with a complete path spec like /opt/local/bin/latex?

Maybe the best/simplest solution would be to ask the user where their texbin is, or the directory containing the executables? For the texlive installation from MacPorts, that is either /opt/local/bin (symlinks) or /opt/local/libexec/texlive/texbin (symlinks) or /opt/local/libexec/texlive/binaries (executables and symlinks to scripts).

**Comment by ednl** [comment]
Here is the output of `man path_helper`:

```
path_helper(8)            BSD System Manager's Manual           path_helper(8)

NAME
     path_helper -- helper for constructing PATH environment variable

SYNOPSIS
     path_helper [-c | -s]

DESCRIPTION
     The path_helper utility reads the contents of the files in the directo-
     ries /etc/paths.d and /etc/manpaths.d and appends their contents to the
     PATH and MANPATH environment variables respectively.  (The MANPATH envi-
     ronment variable will not be modified unless it is already set in the
     environment.)

     Files in these directories should contain one path element per line.

     Prior to reading these directories, default PATH and MANPATH values are
     obtained from the files /etc/paths and /etc/manpaths respectively.

     Options:

     -c      Generate C-shell commands on stdout.  This is the default if
             SHELL ends with "csh".

     -s      Generate Bourne shell commands on stdout.  This is the default if
             SHELL does not end with "csh".

NOTE
     The path_helper utility should not be invoked directly.  It is intended
     only for use by the shell profile.

Mac OS X                        March 15, 2007                        Mac OS X
(END)
```

**Comment by sunderme** [comment]
if you execute the command in your bash shell, it take $PATH into account. But Qt6 in txs does not use a bash shell.
You can set the path /opt/local/bin in txs as well.
<img width="1160" alt="grafik" src="https://user-images.githubusercontent.com/14033169/131249119-26dbfd41-bf5d-4753-875b-8bf8c69ac753.png">

**Comment by ednl** [comment]
> if you execute the command in your bash shell, it take $PATH into account. But Qt6 in txs does not use a bash shell.

Right. But no GUI app uses any sort of shell. Having looked into this, I am now certain that path_helper is not an official way to get the user PATH environment variable. As stated by its man page which I quoted above, it only reads from the file /etc/paths and from any files in /etc/paths.d. Those are only the standard system directories. Also, the output is clearly meant for inclusion in a shell script. The man page also says: "It is intended only for use by the shell profile." The reason this still works for Homebrew is by accident: it installs itself in one of the system directories (/usr/local/bin) while MacPorts (wisely, I think) doesn't. For MacTeX, [they say](https://www.tug.org/mactex/mactex-download.html): "MacTeX writes a symbolic link /Library/TeX/texbin which indirectly points to the TeX Live binary directory. Configure your GUI programs to use this link." Does Texstudio check for /Library/TeX/texbin? Like I said in my first post, linking that might be an improvement that MacPorts could do to make this work.

> You can set the path /opt/local/bin in txs as well.

Right! I didn't see that because I was stuck on the Commands tab which looked like it might have all the Commands info. That will probably do the trick; I haven't tried it yet. Wouldn't it be more logical to move the "Commands $PATH" setting to the Commands tab..?

**Comment by sunderme** [comment]
txs check /Library/TeX/texbin

**Comment by ednl** [comment]
I added `/opt/local/libexec/texlive/texbin` to the Build options Commands PATH in 4.0.0beta2 but on the Commands options tab they remain empty and Texstudio still complains "No TeX installation found" on start up.

**Comment by sunderme** [comment]
can you try beta3.  (once it is built)
additionalSearchPath should be taken into account for finding the commands

**Comment by sunderme** [comment]
any chance to check 4.0.0beta3

**Comment by ednl** [comment]
Thanks. Same result. On first startup (having removed the settings from `~/.config/texstudio`) it says no LaTeX found. I open Options, enable Advanced Options, remove `/usr/local/texlive/2012/bin/x86_64-darwin` from the $PATH in Build options because it does not exist anyway, replace it with `/opt/local/libexec/texlive/texbin`, close the options and the app and restart it: still "No LaTeX found" and the Commands in options are still all empty.

**Comment by sunderme** [comment]
additional paths should work in 4.0.0rc1.

**Comment by sunderme** [comment]
assume fixed (with additional path)
