### ISSUE TITLE
Add learnlatex.org in the "Help" menu

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#1745]
### Describe the feature and the current behavior/state
Add a new entry in the "Help" menu: https://www.learnlatex.org/
### Who will benefit with this feature?
LaTeX's beginners.

**Comment by sunderme** [comment]
can't say that I fancy that page much.
It demands interaction as it does not show results of the latex commands directly.
Hence it is less suited for skimming over the text and little for looking things up.
I would probably still prefer latex Kochbuch (German), not sure where (or if) the translation is.

**Comment by sunderme** [comment]
latex2e was updated.
That file reference learnlatex.org, that should suffice.
