### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by guarionex2** [texstudio-org/texstudio#1755]
- TeXstudio:  2.10.8 (5802:5ee1d048e556)

- Qt: 
- OS:  ubuntu 16.04
- TeX distribution: Don't know

### Expected behavior
File should compile/make/build. This was a working file last time it was compiled. The only difference is that some time has elapsed before opening the file and recompiling.

### Actual behavior
Software shows a package error when compiling or building (a small red circle at the start of the offending line). The error only shows on "\usepackage" lines of code as if a particular package was missing. The tagging of the error line appears to be random, but it is usually halfway through the \usepackage list.
Solution:
    1. Deleted (cut) the offending line and recompiled successfully.
    2. Pasted the offending line and recompiled successfully.
### How to reproduce
Unknown
Note: this has happened with several files that were compiled (built) successfully previously. It seems that TexStudio gets the hick-ups when first reading a file.

**Comment by sunderme** [comment]
please update to a current version of txs.
If the problem still exists, please report with a complete example, i.e. attaching all files.
