### ISSUE TITLE
"#include" packages with options in cwl files

### ISSUE THREAD

**Issue by mbertucci47** [texstudio-org/texstudio#1756]
### Describe the feature and the current behavior/state
It would be useful if `#include:package` in cwl files allowed one to load the package's cwl file with a list of specified package options (corresponding to the `#ifOption:option ... #endif` blocks). For example, a possible syntax could be `#include:xcolor/html,svgnames` to indicate that the package in question depends on `xcolor` with the options `html` and `svgnames` loaded.

### Who will benefit with this feature?
All users who use TeXstudio completion, as well as making it easier for anyone who writes a cwl file.

**Comment by sunderme** [comment]
I don't like to make things more complicated than necessary.
If there is already a working solution (which is even more general), there is no need to produce a redundant second one.
Typing a bit more in cwls is not a critical concern.
(Looking at the cwls, the current syntax gives also a clear image, what is being loaded. #include:xcolor/opt1,opt2 will be a mess if they are triggered by some options and not by others and several with different conditions are placed on several lines.)
