### ISSUE TITLE
Structureview's width + scrollbar

### ISSUE THREAD

**Issue by Piraty** [texstudio-org/texstudio#176]
### Environment
- TeXstudio 2.12.8 from void linux repository (official tarball + https://github.com/texstudio-org/texstudio/commit/4cf5c2eb2a8a0353335c0ed6d6be4b3f19c950c3) [here](https://github.com/voidlinux/void-packages/tree/95fd13e451c9249d059bfa678ad681a17da7e2bd/srcpkgs/texstudio)
- Using Qt Version 5.10.1, compiled with Qt 5.10.1 R
- OS: Void Linux

### Expected behavior
Compact structureview, that respects the witdth of its entries to define its own width.

### Actual behavior
Structureview's size seems to expand to a fixed width over the actual viewport, regardless of the list entries.
The provided screenshot shows the extreme case of a width-maxed structureview, however his also can be observed with a regular "thin" structureview.
![texstudio_struct-scrollbar bug01](https://user-images.githubusercontent.com/23238955/41155582-e7a15166-6b1e-11e8-95bc-8f4c0bd22088.png)

Not sure if related, but when opening i get
```
QAbstractItemModel::endRemoveRows:  Invalid index ( -1 , 0 ) in model LatexDocumentsModel(0x55725d067c70)
``` 

### how to reproduce
- disable struct view
- restart texstudio
- enable struct view. it looks fine, no excessive scrollbar
- restart texstudio (leaving structview enabled)
- excessive scrollbar appears
- using an empty `~/.config/texstudio` doesn't matter
- a document needs to be loaded, as the issue doesn't appear with a blank texstudio (i.e. `texstudio --config /tmp/texstudio-no-config --no-session`)

**Comment by sunderme** [comment]
works fine here
the patch seems to be incomplete.
In general we don't debug code which is not either released by us or based on master in github.

**Comment by Piraty** [comment]
If you can't repdocude, i understand you cannot debug.
Regarding code: The added patch is actually yours (i placed a reference in the initial comment), and can be found in the history therefore.

Just a follow up:
- 2.12.6 (from void linux repositories) has the same issue.
- current HEAD does too
- i updated the initial commen with a more proper description of how to reproduce (i just found out and edge case)

**Comment by sunderme** [comment]
I will take a look at other qt versions.

**Comment by sunderme** [comment]
I don't see scrollbars with qt5.9 or qt5.11

**Comment by timhoffm** [comment]
Might be connected to the same bug in Qt 5.10 that caused #43

**Comment by sunderme** [comment]
works for me
