### ISSUE TITLE
Advance notification of change to `glossaries` `.glsdefs` file format

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#1760]
I don't know if it is relevant for TXS, but maybe it is worth for you to be aware of the ["advance notification of change to `glossaries` `.glsdefs` file format"](https://groups.google.com/g/comp.text.tex/c/JdGEhfPoA8c).

**Comment by sunderme** [comment]
txs does not read glsdefs, so txs should be fine.
