### ISSUE TITLE
Slow typing in memoir options

### ISSUE THREAD

**Issue by bishopcranmer** [texstudio-org/texstudio#1763]
When adding options to memoir (e.g., 12pt, or article, etc.), typing slows down considerably.

### Environment
- TeXstudio: git 4.0.0rc2
- Qt: 6.1.3 r
- OS: Mac 11.6
- TeX distribution: mactex
- @memoir

### Expected behavior
When adding options to the `memoir` document class within square brackets, one would expect typing to be at normal speed.

### Actual behavior
When using `memoir` as the document class, if I add any options within square brackets, typing slows down considerably, say down to 1 character per second or even slower.

### How to reproduce
- Start a new document
- Add `\documentclass{memoir}`
- Then add the optional square brackets and watch typing slow down.

**Comment by sunderme** [comment]
fixed with 3b696384b80c0bd450951ebba5ad8090c5031493
interestingly kind of Qt6 issue.
