### ISSUE TITLE
Macro fails with TeXstudio not found

### ISSUE THREAD

**Issue by qoheniac** [texstudio-org/texstudio#1765]
I'm on Linux (Fedora 34) and I tried the “Launch Zotero Picker” macro but it returns “TeXstudio” not found. I can execute the curl command in a terminal and it returns the correct LaTeX command and I can run TeXstudio by typing texstudio in a terminal so it should be findable. Any suggestions?

**Comment by sunderme** [comment]
zotero needs to be started with a path-env which contains texstudio.
First test is from zotero/better bibtex -> insert into texstudio

**Comment by qoheniac** [comment]
Ah I see, I installed Zotero via flatpak, I guess that's the problem then.

**Comment by sunderme** [comment]
so, we can close this ?

**Comment by qoheniac** [comment]
> zotero needs to be started with a path-env which contains texstudio.

I just gave it a second try and thanks to your hint I found a solution: https://github.com/flathub/org.zotero.Zotero/issues/89#issuecomment-989979351
