### ISSUE TITLE
%END_FOLD no longer stops code fold when unresolved \begin{envname} is present

### ISSUE THREAD

**Issue by Jetlagger** [texstudio-org/texstudio#1768]
In a file I used in 3.6.1 I was able to add a manual code-fold using %BEGIN_FOLD and %END_FOLD, with an unresolved %\begin{envname} between them.

I suspect that %END_FOLD now conflicts with unresolved \begin{envname}, as when one of those is present, %END_FOLD does not correspond with %BEGIN_FOLD.

### Environment
- TeXstudio: git 4.0.0
- Qt: 6.1.3
- OS: Windows10
- TeX distribution: miktex

### Expected behavior
%BEGIN_FOLD
a
\begin{envname} OR %\begin{envname}
%END_FOLD
b

where folding at %BEGIN_FOLD will fold a, but not b

### Actual behavior
%BEGIN_FOLD
a
\begin{envname} OR %\begin{envname}
%END_FOLD
b

folding at %BEGIN_FOLD will fold a and b; %END_FOLD is highlighted in red

![i_am_doofus](https://user-images.githubusercontent.com/1348631/134803604-ec390589-8024-4a7d-9923-f51f7c156985.PNG)
![big_big_doofus](https://user-images.githubusercontent.com/1348631/134803606-e143bc52-a0ed-4465-962f-79094e33de71.PNG)

**Comment by sunderme** [comment]
works fine here (linux)

**Comment by sunderme** [comment]
works also on windows.
So, please provide screen shot.
Do you work with default configuration.

**Comment by Jetlagger** [comment]
I'm very sorry, I did not test it properly in isolation... 😑 The example I gave is wrong. What actually seems to break it is an unresolved \begin{envname} or %\begin{envname}, of which I had one in my document. I updated the issue.

**Comment by muzimuzhi** [comment]
> What actually seems to break it is an unresolved \begin{envname} or %\begin{envname}, of which I had one in my document.

related to #1758?

**Comment by sunderme** [comment]
as a remark.
```
%BEGIN_FOLD
a
\begin{envname}
%END_FOLD
b
```
breaks the hierarchy and will not give a meaningful result. The folds are organazied as trees. They can be overlapping, only including or completely outside.
