### ISSUE TITLE
Provide an easy access to latexindent

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#177]
Because TXS is not very good at indenting the `.tex` files, it could be helpful for it to provide an easy access to [`latexindent`](https://ctan.org/pkg/latexindent) executable file(s).

**Comment by sunderme** [comment]
easier than user tool: latexident %.   (or whatever the exact syntax should be) ?
the problem with latexident is probably to get it running on a (windows-) system

**Comment by aubreyz** [comment]
I got latexindent running in about 1 second on a windows system. 
Texlive
latexindent.exe - w filename

Can't see a great point in running from within Texstudio though....

**Comment by dbitouze** [comment]
>easier than user tool: latexident %.

That's what I had in mind.

> (or whatever the exact syntax should be) ?

In fact, I'm not sure it would be enough (from the documentation):

>`latexindent.pl myfile.tex` will operate on `myfile.tex`, but will simply output to your terminal; `myfile.tex `will not bechanged by `latexindent.pl `in any way using this command.

Hence I guess at least the `-w` (overwrite) or `-o` (choose another file for output) options would be necessary. Concerning the former, the author warns: "Before you try the script on anything important (like your thesis), test it out on the sample files in the test-case directory".

> the problem with latexident is probably to get it running on a (windows-) system

Hmmm, fortunately not, I guess (from the documentation):

>`latexindent.pl `ships as part of the TeXLive distribution for Linux and Mac users; `latexindent.exe`
ships as part of the TeXLive and MiKTeX distributions for Windows users.

**Comment by dbitouze** [comment]
@aubreyz
>Can't see a great point in running from within Texstudio though....

No need to leave TXS and an instantly much more readable `.tex` file you're working on.

**Comment by aubreyz** [comment]
Just tried it as a user tool and it works just fine

latexindent.exe - w %

**Comment by dbitouze** [comment]
@aubreyz Thanks for the report. What do you mean by user tool? Do you mean Configure TXS → Build →User Commands → Add?

**Comment by aubreyz** [comment]
Yes, where you indicate put something like
user1:latexindent (in box 1 - left hand box)
latexindent.exe -w % (in the right hand box)

You will then have a menu entry at tools>user

**Comment by dbitouze** [comment]
@aubreyz Okay. I'm looking for something more straightforward, especially for average users. IMHO, it could be provided as a "Tools" menu entry. After a deeper look at `latexindent`, I suggest to use it with the `-m` and `-l textwrap1.yaml` options in order to get not too long lines (where it is difficult to locate errors), with a `textwrap1.yaml` (whatever its name, I'm just using the one from the documentation page 56) containing:

```yaml
modifyLineBreaks:
    textWrapOptions:
        columns: 80
```

**Comment by sunderme** [comment]
Since anyone can use the command if he needs to, I close the issue.
