### ISSUE TITLE
typing extended characters (e.g., ü)

### ISSUE THREAD

**Issue by georgeseng** [texstudio-org/texstudio#1770]
### Environment
- TeXstudio: 4.0.0
- Qt: 6.1.3, compiled with Qt 6.1.3 R
- OS: macOS 11.5.1
- TeX distribution: texlive

Hi all,

i cannot type extended characters anymore since the update to 4.0.0.
for example: german umlaut using US intl. keyboard: alt-u + u to type ü.
copy-pasting an ü directly is no problem.
Used to work just fine on texstudio 3.1.2.

regards

**Comment by sunderme** [comment]
Does it also not work for normal txs dialogs. For example the Document wizard ?

**Comment by georgeseng** [comment]
it works in Preferences but not in the editor integrated find/replace fields.
I'm not sure what the Document wizard is? Do you mean the Quick Start wizard? It works in those editfields.

**Comment by sunderme** [comment]
okay.

**Comment by sunderme** [comment]
looks like Qt6 bug.
And a work-around seems not feasible.
I'll try to create a bug report.

**Comment by sunderme** [comment]
bug reported o Qt: https://bugreports.qt.io/browse/QTBUG-96921

**Comment by georgeseng** [comment]
okay, thanks.

**Comment by sunderme** [comment]
I will provide qt5 builds which don't have this issue.
(you could compile on your own or wait probably until tomorrow night)

**Comment by sunderme** [comment]
you can find a qt5 build here: https://github.com/texstudio-org/texstudio/suites/3933103511/artifacts/98507468

**Comment by sunderme** [comment]
the problem seems to be solved with Qt6.2.
I will generate a new release once brew has taken up the new version.
