### ISSUE TITLE
User commands keyboard shortcuts not working on linux

### ISSUE THREAD

**Issue by bgregorys** [texstudio-org/texstudio#1771]
### Environment
- TeXstudio: 4.0.0
- Qt: 5.12.8 R
- OS: Ubuntu 20.04
- TeX distribution: texlive

### Expected behavior
Press  Alt + Shift + F1 to activate User command, e.g., `pdflatex -synctex=1 -interaction=nonstopmode -halt-on-error -jobname=%_Solutions %.tex`

### Actual behavior
Nothing happens. User commands do work when selected though the Tools menu.

### How to reproduce
Issue did not occur on Windows 10 installation.

**Comment by sunderme** [comment]
works on ubuntu/xfce
Are you sure that alt+shift+F1 is not taken and captured by the desktop environment ?

**Comment by bgregorys** [comment]
Sorry, I am a new Ubuntu user. I am not sure to check what you are suggesting. I have tried to use alt+shift+f1 in other settings and nothing appears to happen. According to [this](https://help.ubuntu.com/stable/ubuntu-help/shell-keyboard-shortcuts.html.en), alt+shift+f1 is not listed as a shortcut.

**Comment by bgregorys** [comment]
I can verify that alt+F1 is captured by the desktop environment. Still unsure about alt+shift+F1.

**Comment by sunderme** [comment]
that depends on the actual DE. As it works fine on xfce, I strongly suspect the DE.

**Comment by sunderme** [comment]
by the way, you can set the shortcut to something else.

**Comment by bgregorys** [comment]
I will. Thanks for the help.

**Comment by bgregorys** [comment]
Disabling the alt+F1 shortcut in DE resolved the issue.
