### ISSUE TITLE
On Review menu feature

### ISSUE THREAD

**Issue by tmelorc** [texstudio-org/texstudio#1774]
### Environment
- TeXstudio: VERSION 4

### Description
I observed the new Review menu to insert some commands, like `\alert{<text>}`.

I'd like to know the purpose of that since such command does not work in general (it works in beamer)
In other words: when such menu could be useful?

**Comment by tmelorc** [comment]
I found answer. They are commands for the package `easyReview`. 

Maybe this info should appear somewhere.

**Comment by dbitouze** [comment]
BTW, what's the rationale for the choice of `easyReview`? The [`changes`](https://ctan.org/pkg/changes) might have been a better choice, as more actively maintained.

**Comment by sunderme** [comment]
I discovered easyReview and liked it. There is no more to it.

**Comment by tmelorc** [comment]
> I discovered easyReview and liked it. There is no more to it.

It seems to be an obsolete package. Also it makes use of `todonotes`.

**Comment by sunderme** [comment]
If someone wants to change to another package, I don't mind.

**Comment by nicolai-schwartze** [comment]
> 
> 
> If someone wants to change to another package, I don't mind.

I would have a suggestion for a different package. Why not use some abstractions of [pdfcomment ](https://ctan.org/pkg/pdfcomment?lang=en) to generate the standard pdf markups and annotations?

**Comment by asmwarrior** [comment]
I found some related discussion on tex.stackexchange.com, see here: [texstudio commands \comment \alert and \add](https://tex.stackexchange.com/questions/619426/texstudio-commands-comment-alert-and-add)
