### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by tmelorc** [texstudio-org/texstudio#1777]
### Environment
- TeXstudio: VERSION 4.0.1
- Qt: 5.11.1
- OS: Linux Mint 18
- TeX distribution: texlive 2021

### Description
I found some untranslated text. I check the messages in Transifex and they are translated, but txs does not show properly.

For example, in the **View** menu, the _Side Panel_ text is not translated to pt-br, as screen shot below.
![Menu_184](https://user-images.githubusercontent.com/15181573/135101044-4cf60ea0-a527-43ab-ae79-c76e4d274863.png)

Also, the two tooltips when mouse over the following buttons:
![Seleção_185](https://user-images.githubusercontent.com/15181573/135101389-59ed8fbc-be18-4e19-b403-7474dee70c7f.png)
they are in English.

In addition, the word _Ready_ in the status bar:
![Seleção_187](https://user-images.githubusercontent.com/15181573/135109262-29e9bafc-70c5-4f6e-9668-0c90b9d66fc9.png)

Finally, in **Latex** menu, the _Review_ item is not translated. I didn't find this text on Transifex. 
![Menu_186](https://user-images.githubusercontent.com/15181573/135102286-c4d33ae5-53ee-48be-8581-3d6b8adfe8f1.png)

**Comment by dbitouze** [comment]
In French, no problem, except for LaTeX → Review remarks indeed not translated (string not available on Transifex.

**Comment by sunderme** [comment]
yes, the side panel is simply not translated in pt_BR, you can do so here https://www.transifex.com/texstudio/texstudio/languages/
I create the set-up to translate easyReview.

**Comment by tmelorc** [comment]
> yes, the side panel is simply not translated in pt_BR, you can do so here https://www.transifex.com/texstudio/texstudio/languages/ I am creating the set-up to translate easyReview.

Strange, since I already searched for it there but it seems to be translated.
![Seleção_189](https://user-images.githubusercontent.com/15181573/135132562-754625f0-f07d-40a1-a2d1-c574e7216ce0.png)
 
Is there other such string?

**Comment by sunderme** [comment]
I see it translated in German, but only after a restart. The text is set up rather indirectly.

**Comment by sunderme** [comment]
and here, after restart it also works with pt

**Comment by tmelorc** [comment]
> and here, after restart it also works with pt

Hum... now it works. 
I didn't know that we should restart txs, since some words changes directly when we change the language.
Thanks so much.

**Comment by sunderme** [comment]
> > and here, after restart it also works with pt
> 
> Hum... now it works. I didn't know that we should restart txs, since some words changes directly when we change the language. Thanks so much.

Normally it changes directly. Apparently the program code at this point is a bit odd.

**Comment by sunderme** [comment]
fixed

**Comment by tmelorc** [comment]
> fixed

I got the ts file and I'm using Qt Linguist to edit it.
I observed many yellow marks related to missing trailing spaces in translated strings.
I'm editing and fixing. Soon I'll ask to update the ts file for future releases.

**Comment by tmelorc** [comment]
I'm attaching here the new file (please, rename it to .ts since I did .txt to attach it here)
Also, I added some comments on Transifex in some English strings (related to number of end of lines chars).

[texstudio_pt_BR.txt](https://github.com/texstudio-org/texstudio/files/7246510/texstudio_pt_BR.txt)

**Comment by sunderme** [comment]
You can't do the changes directly on transifex ?

**Comment by tmelorc** [comment]
> You can't do the changes directly on transifex ?

Yes, I could. But using Qt Linguist I was able to check only the strings with punctuation differences, for example, missing space after colon at the end and others. 
Also, in Linguist I can see where the string is used and this gives me a better idea how to translate it.

Do you think is it possible to upload my ts file to Transifex?

**Comment by tmelorc** [comment]
See how good is to work with Linguist. I almost fixed all the yellow check marks. 
![-home-thiago-Downloads-texstudio-master-translation-texstudio_pt_BR ts - Qt Linguist_194](https://user-images.githubusercontent.com/15181573/135146579-b0a70778-3173-4b1f-8301-8ec51ec13147.png)

**Comment by sunderme** [comment]
you can upload the results via transifex.

**Comment by tmelorc** [comment]
> you can upload the results via transifex.

I'll try now.

**Comment by sunderme** [comment]
looks like it is in the repository now

**Comment by tmelorc** [comment]
> looks like it is in the repository now

Very nice! I Didn't know that communication between Transifex and Git is automatic. Good to know.
Thanks for your help.
