### ISSUE TITLE
Matrix assistant inserts blank line after

### ISSUE THREAD

**Issue by tmelorc** [texstudio-org/texstudio#1778]
### Environment
- TeXstudio: VERSION 4.0.1
- Qt: 5.11.1
- OS: Linux Mint 18
- TeX distribution: texlive

### Description
When using matrix assistant I observed that a new line is inserted after it. This could be not good, for example, when inserting it within `\[ \]` with more lines.

To reproduce the problem, use:

```
\[
    %<cursor here when using assistant>
\]
```
and the output will be
```
\[
\begin{array}{cc}
 &  \\
 & 
\end{array}

\]
```
producing an error because the empty line before closing the math environment.

To be clear, see the image below:
![Seleção_195](https://user-images.githubusercontent.com/15181573/135174440-64665aeb-51f7-4ec6-b58b-ec956cc37cad.png)

I didn't test but I suspect that `pmatrix` and others have the same bug.

**Comment by tmelorc** [comment]
I found the line inserting that extra `\n` on `arraydialog.cpp` line 82.
Also, I suggest to add the `Bmatrix` in the item list.

**Comment by sunderme** [comment]
PR is quite simple.
Assuming you have forked txs.
Create a new branch, do the changes in the branch and checkin (to your fork).
Github offersnon the webpage to create PR with branch then.

**Comment by tmelorc** [comment]
> PR is quite simple. Assuming you have forked txs. Create a new branch, do the changes in the branch and checkin (to your fork). Github offersnon the webpage to create PR with branch then.

Thanks. I did PR. Hopefully I did it right.

**Comment by sunderme** [comment]
fixed with PR
