### ISSUE TITLE
Missing "expand all" and "collapse" in context menu of structure tree since version4.0

### ISSUE THREAD

**Issue by stefgers** [texstudio-org/texstudio#1779]
### Describe the feature and the current behavior/state
Previous versions did contain context menu options to "expand all" and collapse in the structure tree view in the left panel.
Version 4.0 misses that feature.

### Who will benefit with this feature?
Complex and long tree views in projects like a doctoral thesis are hard to handle without "expand all" on each headings level.

### Any Other info
What was the reason for deleting the feature? I couldn't find any change in the global options that would explain.

**Comment by sunderme** [comment]
expand/collapse all subitem reintroduced
