### ISSUE TITLE
Enhancement: Built in sorting function

### ISSUE THREAD

**Issue by BeerStud** [texstudio-org/texstudio#178]
### Enhancement
- TeXstudio 2.12.8 (hg 2.12.8-1-g68cd350)
- Qt: 5.8.0, compiled with Qt 5.8.0 R
- OS: MS Windows 10 PRO / amd 64
- TeX distribution: miktex

TexStudio does not have a built-in “sorting” function, or at least I have not been able to locate it. While it is possible to copy things like “lists,” etcetera and sort them in other text editors, it is indeed not as convenient. I realize that it is possible to write a macro to do the job; however, that is neither as easy as nor does it work as well as those built in sorting functions that I have found in other text editors.

I believe it would be a definite enhancement to have a built-in sorting function in Texstudio.

**Comment by sunderme** [comment]
take a look at https://github.com/texstudio-org/texstudio/wiki/Scripts#sorting
Sorting is pretty rare demand in a text editor.
We rather not clutter menus further for single user functions. That is why there is the macro/script functionality in the first place.
It may be interesting to allow simpler access to scripts, but that is as far as we should go.

**Comment by sunderme** [comment]
you can do it via scripts
