### ISSUE TITLE
Opensuse: 4.0.0 doesn't use any longer the system file browser

### ISSUE THREAD

**Issue by leomayer** [texstudio-org/texstudio#1782]
Typing CTRL-O it opens the following the explorer:

![Bildschirmfoto von 2021-09-29 20-02-43](https://user-images.githubusercontent.com/2641128/135324144-22937f98-65e9-4f38-8316-be7ab3ba82d4.png)

up till 3.1.2 the system file browser (GNOME) was used. This is benefical when I have bookmarks in the browser.

Running OpenSuse Tumbleweed

**Comment by muzimuzhi** [comment]
Is "Configure TeXstudio -  General - Files - Use system file dialogs" checked?

**Comment by sunderme** [comment]
I don't think that anything has been changed with this respect.

**Comment by leomayer** [comment]
@muzimuzhi : yes - see screenshot (didn't help to untick and tick again)
![Bildschirmfoto von 2021-09-30 08-37-08](https://user-images.githubusercontent.com/2641128/135400354-42000585-725f-4468-ae4c-a0b1a3281be0.png)

@sunderme : I was forced to install a lot of X11 libs. Anyway the dialog is not the same as before. And the Windows-style in Linux is quite a pain in the a**

**Comment by sunderme** [comment]
Qt provides the interface to the file dialog.

**Comment by sunderme** [comment]
on a rolling release, determing the root cause for this kind of issue is impossible.
txs uses Qt for providing a file dialog and Qt uses its own construct or a "native" one. If the later does not work, there is nothing we can do.
