### ISSUE TITLE
Artifacts while using magnifying glass

### ISSUE THREAD

**Issue by bohdankornienko** [texstudio-org/texstudio#1783]
When using magnifiying glass zoomed version has artifacts.
![image](https://user-images.githubusercontent.com/5053428/135404749-99f3b7ef-3474-4651-90bd-ca934a8e0454.png)

### Environment
- TeXstudio: 4.0.0 (git 4.0.0)
- Qt: 6.1.3, compiled with Qt 6.1.3 R
- OS: Windows 10
- TeX distribution: Not sure how to check it

### Expected behavior
Should see clean magnified version of the image.

### Actual behavior
Image with artifacts

### How to reproduce
1. Render figure (text too, it renders text with artifacts too). 
2. Render/compile preview
3. Use magnifying glass feature by left clicking on the preview

**Comment by muzimuzhi** [comment]
perhaps similar to #1773

**Comment by sunderme** [comment]
workaround: Qt5 version of txs, or screen scaling factor 100% or 150%   or rectangular magnifier
