### ISSUE TITLE
Odd cursor placement after upgrade to texstudio 4.0.0

### ISSUE THREAD

**Issue by pavlogiannis** [texstudio-org/texstudio#1789]
After upgrading texstudio to 4.0.0 on a Mac, I 've noticed that the editor cursor is often oddly placed on top of letters (see the two screenshots). Besides the aesthetics it makes writing a bit confusing as it is not clear whether the cursor is considered to be before or after the letter.

The issue appears on both MacOs 11 and 12.

<img width="106" alt="Screenshot 2021-10-02 at 11 29 19" src="https://user-images.githubusercontent.com/51949124/135711110-3a016253-cf84-453a-b939-258d0707b7c0.png">
<img width="97" alt="Screenshot 2021-10-02 at 11 40 21" src="https://user-images.githubusercontent.com/51949124/135711111-d59b3e1a-9093-401c-ba5f-76ee7e09aa43.png">
.

**Comment by sunderme** [comment]
more info on the display set-up needed.
Resolution, scale, internal/external etc.

**Comment by sunderme** [comment]
and is it always shifted or only sometimes ?

**Comment by sunderme** [comment]
and did you change the font set-up ?

**Comment by pavlogiannis** [comment]
@sunderme It does not happen always. Here is the same text copy-pasted a few lines further down the same document.

I have not modified the font settings after the upgrade, here's a screenshot of them.

<img width="102" alt="Screenshot 2021-10-02 at 12 18 01" src="https://user-images.githubusercontent.com/51949124/135712248-a801f4f4-abcc-4ae9-8a18-c847c39d0386.png">
<img width="948" alt="Screenshot 2021-10-02 at 12 18 49" src="https://user-images.githubusercontent.com/51949124/135712249-9b806452-cc8a-4074-b46c-2d62104285be.png">

**Comment by pavlogiannis** [comment]
> more info on the display set-up needed.
> Resolution, scale, internal/external etc.

I 've noticed the issue on Macbook pros (both 13 and 15 inches) with both built-in and external displays (the latter connected via usb). The screenshots above were produced on a 13-inch 
<img width="361" alt="Screenshot 2021-10-02 at 12 24 30" src="https://user-images.githubusercontent.com/51949124/135712338-89ca41ed-5a8c-40d5-8a70-b43f10ce323e.png">
Macbook pro (2016 model) with the default display settings.

**Comment by sunderme** [comment]
so, when it does not always happen ... when does it happen.
Obviously I need an example which allows me to replicate the issue.

**Comment by pavlogiannis** [comment]
> so, when it does not always happen ... when does it happen.
> Obviously I need an example which allows me to replicate the issue.

This is a full sentence that, when I write down, creates the issue:

`Let $\Time(G)$ be the time required to construct an optimal tree decomposition of $G$ with $\leq n$ bag`

<img width="824" alt="Screenshot 2021-10-02 at 12 30 39" src="https://user-images.githubusercontent.com/51949124/135712567-791b7584-b461-4054-8e04-1e55f2e08022.png">
s.

**Comment by sunderme** [comment]
no issue here.
Have you checked that your example works in isolation (as only text) ?

**Comment by pavlogiannis** [comment]
> no issue here.
> Have you checked that your example works in isolation (as only text) ?

It does indeed.
Oddly enough, the effect is more prominent the further to the right the text is.

<img width="228" alt="Screenshot 2021-10-02 at 12 40 41" src="https://user-images.githubusercontent.com/51949124/135712904-daa6df24-6c7d-4436-afc5-e6f2148a63a8.png">

<img width="817" alt="Screenshot 2021-10-02 at 12 41 16" src="https://user-images.githubusercontent.com/51949124/135712903-2d5e68b0-0998-422a-b9f4-d6573a3f838b.png">

**Comment by sunderme** [comment]
okay, I see it.
