### ISSUE TITLE
Autocompletion should add an empty curly braces pair for new argumentless commands

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#179]
Currently, for a new command with argument(s), such as `\newcommand{\foobar}[1]{foobar#1}`, the autocompletion leads to `\foobar{arg1}`: so far, so good.

But for a new command without argument, such as `\newcommand{\barfoo}{barfoo}`, the autocompletion leads to only `\barfoo`: not so far, not so good since the user has to complete this with either `{}` or `\ `. IMHO, the autocompletion should in this case lead to `\barfoo{}`.

**Comment by timhoffm** [comment]
I don't think that you'll want that for all the commands you define without arguments. If both cases can happen it's better not to add something than to add something that you'd have to delete afterwards. Less disrupting in the flow of typing.

**Comment by sunderme** [comment]
we had a similar discussion some time ago, where you wanted to have all commands followed by {}.
This can lead to problems. Why do you need the {} anyway ?

**Comment by sunderme** [comment]
and you can always provide your own cwl ...

**Comment by dbitouze** [comment]
>we had a similar discussion some time ago, where you wanted to have all commands followed by {}.

I reminded indeed something like that but I couldn't retrieve the discussion.

>Why do you need the {} anyway ?

I guess numerous users will create argumentless personal macros as shortcuts. For example, suppose a student in literature who has to write a (long) dissertation about Dostoïevski: he would have to write "Dostoïevski" numerous times, which is a pain and subject to typos. If he knows about LaTeX new commands, he will create the following one:
```latex
\newcommand{\dst}{Dostoïevski}
```
and will then have to write just `\dst{}`instead of "Dostoïevski". But the empty curly braces pair is necessary: the output of `\dst is born in...` would be "Dostoïevskiis born...".

Hence my request: the `\ds` + TAB autocompletion is nice, but misses the empty curly brace. Okay, a more advanced user could use the Macros  → Edit macros... → Add feature but not everybody is aware of it.

>and you can always provide your own cwl ...

Indeed, but beyond the scope of an average user and, for a simple but rather common case as above, it isn't worth doing such complicated thing (understand the syntax, figure out where to put the `.cwl` file, activating it for the document, etc.).

**Comment by sunderme** [comment]
what about using \xspace ?

`\newcommand{\dst}{Dostoïevski\xspace}`

works very well for me

**Comment by dbitouze** [comment]
>what about using \xspace ?

Indeed but:

1. beyond the scope of an average user,
1. the author of `xspace` himself [doesn't recommend his package](https://tex.stackexchange.com/a/86620/18401).

**Comment by sunderme** [comment]
well, I would not make anyone type {} all the time because xspace might get it wrong in special corner cases. It is less work/annoying to adapt xspace than to change the source of txs and make everyone use an ugly syntax.
So, there is no question, that forcing the user to get {} out of every user command is out of question. (because that is starting a dogmatic flame war of preferences)
If someone is bored, we can accept a patch for an optional behaviour, but I still would recommend xspace. And for sure it is suitable for beginners, since they just need to place it in their definitions and be done. No worry about forgetting braces once again ...

**Comment by dbitouze** [comment]
>well, I would not make anyone type {} all the time because xspace might get it wrong in special corner cases.

No need to make anyone **type** `{}` if his editor make it for him :)

>It is less work/annoying to adapt xspace than to change the source of txs and make everyone use an ugly syntax.

That's not an ugly syntax, but the original one (see e.g. Leslie Lamport [`sample2e.tex`](ftp://www.ctan.org/tex-archive/macros/latex/base/sample2e.tex) file).

> If someone is bored, we can accept a patch for an optional behaviour, but I still would recommend xspace. And for sure it is suitable for beginners, since they just need to place it in their definitions and be done. No worry about forgetting braces once again ...

I know `xspace` and still use it for my own documents. What I have in mind is beginners or average users who never heard about this package.

**Comment by thatlittleboy** [comment]
I also would not prefer the automatic `{}`. It's not always necessary (in math mode, for example), and even though, as @dbitouze said, it's harmless, (i) it's extra clutter in the document (where it's not needed) and (ii) it will be annoying if one wants to *delete* the command (two extra keystrokes *per use* of the command), as @timhoffm pointed out.

Maybe it can be introduced as an optional option, but I, for one, certainly won't be using it. Granted, I am not using a French keyboard, so you could argue my opinion here is not really relevant. :)

**Comment by dbitouze** [comment]
>It's not always necessary (in math mode, for example) [...] (i) it's extra clutter in the document (where it's not needed)

Indeed: maybe could be differentiated between text and math modes. But still harmless in math mode.

>(ii) it will be annoying if one wants to delete the command (two extra keystrokes per use of the command)

Just matter of <kbd>Alt+←</kbd> twice instead of once: much less annoying than having to type `{}`. And it's much less common to have to _delete_ than to _type_ the command.

**Comment by timhoffm** [comment]
Side remark @dbitouze: Your example `\newcommand{\dst}{Dostoïevski}` isn't a very good one. Using latex macros for simple abbreviations makes the text less readable. It may be a solution if you just have a simple editor, nut we can do better. Use a User Macro with a trigger string (e.g. `#dst`) and let the editor do the replacement.

That said, there are for sure reasonable cases for macros that would want `{}`, but there are other cases in which you won't want it. I'm refusing trying to be too smart when there is not just one obvious solution.

**Comment by dbitouze** [comment]
@timhoffm 

>Your example `\newcommand{\dst}{Dostoïevski}` isn't a very good one. Using
>latex macros for simple abbreviations makes the text less readable. It may be
>a solution if you just have a simple editor, but we can do better. Use a User
>Macro with a trigger string (e.g. #dst) and let the editor do the replacement.

I strongly disagree: the `.tex` is admittedly less readable with `\dst` than
with "Dostoïevski" but, following this line, `\textbf{foo}` is less readable
than "foo" in bold face and word processors are better than LaTeX; and, if
`\dst` looks weird, the user could use `\dostoievski` as his command name. 

But that's not the main point: using macros even as simple abbreviations for
the key (I mean main, important, reccurrent) words (or groups of words) of the
document is in the contrary an efficient way of using LaTeX:

1. Suppose the student who's working on Dostoïevski splits his document in
   master and slave files; suppose, when the work is almost completed, his
   supervisor tells him he wants "Dostoïevski", the main purpose of the memoir,
   in small caps. With the `\dst` macro, the student has to change
   `\newcommand{\dst}{Dostoïevski}` into
   `\newcommand{\dst}{\textsc{Dostoïevski}}` just in a single place. Otherwise,
   he has to visit the master and all the slave files.
2. Suppose the student sometimes has to use another editor, e.g. the Overleaf
   one: no trigger.
3. Suppose this work on Dostoïevski is a collaborative work, with people using
   other editors with no trigger feature.
   
About the replacement by a trigger, it's a nice feature for replacing the string
e.g. "dst" (why the sharp mark in your example?) by... `\dst{}` :) But, once
again, such a TXS feature is beyond the scope of an average user.

**Comment by timhoffm** [comment]
Sorry, I would have something to say in response to your points, but I don't have time to go into a lengthy discussion right now. Can we agree to disagree?

**Comment by dbitouze** [comment]
>Can we agree to disagree?

I agree we can agree to disagree :) But an option which lets the choice to the user would be welcome...

BTW, Emacs adds the `{}` ;)

**Comment by sunderme** [comment]
no intention to add this
