### ISSUE TITLE
compilation fails on riscv in debug/debughelper.cpp

### ISSUE THREAD

**Issue by alexfanqi** [texstudio-org/texstudio#1791]
Everything compiles fine and works on riscv except that debughelper is not implemented for riscv.

src/debug/debughelper.cpp: In member function ‘void SimulatedCPU::set_all(void*)’:
src/debug/debughelper.cpp:517:58: error: ‘mcontext_t’ {aka ‘struct mcontext_t’} has no member named ‘gregs’; did you mean ‘__gregs’?
  517 | #define PC_FROM_UCONTEXT(context) (context)->uc_mcontext.gregs[REG_EIP]
      |                                                          ^~~~~
src/debug/debughelper.cpp:1050:28: note: in expansion of macro ‘PC_FROM_UCONTEXT’
 1050 |         this->pc = (char *)PC_FROM_UCONTEXT(context);
      |                            ^~~~~~~~~~~~~~~~
src/debug/debughelper.cpp:517:64: error: ‘REG_EIP’ was not declared in this scope; did you mean ‘REG_TP’?
  517 | #define PC_FROM_UCONTEXT(context) (context)->uc_mcontext.gregs[REG_EIP]
      |                                                                ^~~~~~~
src/debug/debughelper.cpp:1050:28: note: in expansion of macro ‘PC_FROM_UCONTEXT’
 1050 |         this->pc = (char *)PC_FROM_UCONTEXT(context);
      |                            ^~~~~~~~~~~~~~~~
src/debug/debughelper.cpp:519:61: error: ‘mcontext_t’ {aka ‘struct mcontext_t’} has no member named ‘gregs’; did you mean ‘__gregs’?
  519 | #define FRAME_FROM_UCONTEXT(context) (context)->uc_mcontext.gregs[REG_EBP]
...

**Comment by alexfanqi** [comment]
disable backtrace like arm will make it work and likely is the only easy fix.
#if (defined(arm) || defined(__arm__) || defined(__riscv))
#define NO_CRASH_HANDLER
#endif

At first, I tried to implement a backtrace in a similar fashion of arm relying on frame pointer. However, I discovered #https://github.com/riscv-software-src/riscv-tools/issues/136 and [can-i-force-gcc-to-emit-ra-fp-handling-in-a-fixed-sequence](https://stackoverflow.com/questions/69365025/can-i-force-gcc-to-emit-ra-fp-handling-in-a-fixed-sequence). This means the simple frame pointer implementation probably won't work for riscv because 1) gcc for riscv seems to not respect -fno-omit-frame-pointer 2) even if it respects, the order return address and frame pointer get pushed into the stack is not always the same.

**Comment by sunderme** [comment]
you can provide a PR

**Comment by alexfanqi** [comment]
Sure, please refer to #1792

**Comment by sunderme** [comment]
pr integrated
