### ISSUE TITLE
V4.0.0-win-portable-qt6 does not contain config folder

### ISSUE THREAD

**Issue by MortenHannemose** [texstudio-org/texstudio#1796]
When downloading the latest portable release `texstudio-4.0.0-win-portable-qt6.zip` and unzipping it, there is no `config` folder.
Therefore, it defaults to creating a settings file in `%APPDATA%\texstudio\texstudio.ini` instead of in the `config` folder, which results in the program not being portable as downloaded.
### Environment
- TeXstudio: 4.0.0
- Qt: 6
- OS: Windows 10
- TeX distribution: Miktex

### How to reproduce
Download `texstudio-4.0.0-win-portable-qt6.zip`, unzip, open and close texstudio.

### Expected behavior
This should create `./config/texstudio.ini` (i.e. a file in a subfolder from where `texstudio.exe` is located)

### Actual behavior
Creates `%APPDATA%\texstudio\texstudio.ini`

**Comment by tkingpsl** [comment]
I concur with this issue. I have no config folder. I have a textstudio.ini file in my AppData fodler, dated 1 day after I installed 4.0.0. See my post https://github.com/texstudio-org/texstudio/issues/1786

**Comment by sunderme** [comment]
fixed

**Comment by MortenHannemose** [comment]
@sunderme 
thanks for fixing it

@tkingpsl 
In your issue, you say that you "installed" it, which makes me think you are not using the portable version. If that is the case, your issue is not related to this issue.
