### ISSUE TITLE
adding a license file

### ISSUE THREAD

**Issue by jonasstein** [texstudio-org/texstudio#18]
I suggest to add the license information:
https://help.github.com/articles/adding-a-license-to-a-repository/

It could make sense to add several license files like
GPL-3,txt
LGPL.txt
and so on and note in a LICENSE or README file which license applies where. There are external files in this tree and I can not clearly see which files are from texstudio and which are external files. 
At least icons, dictionaries and poppler are bundled.

**Comment by benibela** [comment]
7e83fbafcb7cfb3954c24212acae34bf48803aa6
