### ISSUE TITLE
Convert CSV to LaTeX tables

### ISSUE THREAD

**Issue by daknuett** [texstudio-org/texstudio#180]
### Environment
- TeXstudio: 2.12.9
- Qt: ALL
- OS: ALL
- TeX distribution: ALL

### Expected behavior

- Provide a dialog to open a file (`.csv`, `.tsv`), specify a separator (`,`,`;`,`:`,`\t`,` `) and encoding
- The chosen file is read and split into an array of data according to the separator
- A LaTeX table is generated from the data and inserted in the `.tex` file

### Actual behavior

N/A

### How to reproduce

N/A

### Note

This would be a nice feature requested by some collegues, too. I would be able to write the actual reader (file -> array) and generator (array -> TeX) but I cannot create the interfaces (dialog & stuff).

**Comment by dbitouze** [comment]
Why not, but a more efficient way would be to use the `pgfplotstable` package.

**Comment by daknuett** [comment]
Well the idea was actually to provide a more efficient way to create tables instead of embedding data.

The intended workflow was:

1. Create the table using LibreOffice Calc (For instance a comparison of RTM implementations)
2. Export the table to CSV
3. Generate the LaTeX
4. Forget the CSV
5. Work with the LaTeX table

Also it might be even more useful to use spreadsheets (eliminates step 2) instead of CSV. But I looked up the spreadsheet formats and it would be really an huge amount of work.

**Comment by dbitouze** [comment]
Concerning this use case, the best would probably be a spreadsheet macro. With OpenOffice (and maybe LibreOffice), we could use [Calc2LaTeX](http://calc2latex.sourceforge.net/) which used to work nicely, but that's not the case anymore. With Excel, one can use [Excel2LaTeX](https://ctan.org/pkg/excel2latex) which I was told it is working nicely.

**Comment by sunderme** [comment]
all/most of it could be handled via script ...

**Comment by timhoffm** [comment]
There are many different table packages and types in latex. It's not reasonably possible to support them. Natively in the editor.

Use a script instead and adapt it to your need. See [this example](https://github.com/texstudio-org/texstudio/wiki/Scripts#paste-as-latex-table) for a simple starting point.

*Note:* You don't even need an intermediate .csv file. Just copy the data from your spread sheet application to the clipboard and trigger the macro to generate a table.

**Comment by Fechin** [comment]
You can easy to convert CSV To LaTeX Table at：https://tableconvert.com/

**Comment by foreachthing** [comment]
With this one here http://www.tablesgenerator.com/ you can even import CVS files or tables from clipboard.

**Comment by benibela** [comment]
Using Linux I just call `tr ',;\t' '&'` on the CSV file in the terminal and then use cursor mirrors to add `\\`
