### ISSUE TITLE
Delete key doesn't work in TS 4.0.0

### ISSUE THREAD

**Issue by lashkevi** [texstudio-org/texstudio#1802]
The "delete" key does not work in TS 4.0.0. It simply does nothing.

### Environment
- TeXstudio: 4.0.0 (texstudio-4.0.0-lp153.10.1.x86_64 from, distribution: home:jsundermeyer / openSUSE_Leap_15.3)
- Qt: 5.12.7
- OS: Linux, OpenSUSE 15.3
- TeX distribution: texlive

### Expected behavior
The delete key deletes the letter right to the cursor.

### Actual behavior
The delete key does nothing.

### How to reproduce
Open any text in TS and try.

**Comment by sunderme** [comment]
works fine on Ubuntu.
you can remove ~/.config/texstudio/texstudio.ini to make sure that is not a non-default setting. 
Apart from that I have no idea. (As said, for sure not a general bug)

**Comment by sunderme** [comment]
no problem. I close this issue then.
