### ISSUE TITLE
Doesn't start with Windows 11.

### ISSUE THREAD

**Issue by Bono2007** [texstudio-org/texstudio#1807]
### Environment
- TeXstudio: 4
- Qt:  6 
- OS: Windows11
- TeX distribution: texlive 2021

Texstudio 4 can't start under fresh install on Windows 11
Error 0xc000007b

I've tried to install VC++, .net but no way.
By the way, Qt5 is working.

**Comment by sunderme** [comment]
no other cases have been reported.
VC++ is not used with txs.
