### ISSUE TITLE
Weird behavior with placeholders

### ISSUE THREAD

**Issue by rushi1986** [texstudio-org/texstudio#181]
### Environment
- TeXstudio: 2.12.8
- Qt: 5.8.0
- OS: Windows 10
- TeX distribution: MikTeX 2.9

### How to reproduce
1) ctrl+e (ctrl+e is the shortcut for \begin{\<environment\>})
2) type: thm
3) ctrl+left (shortcut to select the next placeholder)
4) type: D\in R ctrl+up (ctrl+up is my shortcut for Superscript)
5) type:  n

![cc](https://user-images.githubusercontent.com/4869914/41257752-9d4ed21a-6d93-11e8-9539-aa4018f6d28d.gif)

### Expected behavior
\begin{thm}
	D\in R^{n}
\end{thm}

### Actual behavior
\begin{n}
	D\in R^{content}
\end{n}

**Comment by sunderme** [comment]
works fine here-
Make sure that "previous mark" is not still set to ctrl+up

**Comment by rushi1986** [comment]
The same thing happens if I press ctrl+down (subscript) instead of ctrl+up. When I do ctrl+m (inline math), this happens:
![capture](https://user-images.githubusercontent.com/4869914/41257018-fd2b8d8e-6d90-11e8-8b6f-01ad05ff7dad.PNG)
All I did was: ctrl+e, thm, ctrl+left, This , ctrl+m.

Instead of content being selected, content and \end on the next line are selected.

**Comment by thatlittleboy** [comment]
Similar to #109? Try a developmental snapshot https://bintray.com/sunderme/texstudio/texstudio-win.

**Comment by rushi1986** [comment]
I can confirm that this is fixed in the latest developmental snapshot. Sorry about that, I tried searching if this has been reported but didn't know what keywords to search for.
