### ISSUE TITLE
TeXstudio 4.0.0: Missing greek symbols in the preview from some included files

### ISSUE THREAD

**Issue by nutle** [texstudio-org/texstudio#1812]
When including certain PDF files as graphics, some greek symbols are not present during the preview. This was however not the case with the previous build of TexStudio (v.3.5), only noticing this with the latest release.

### Environment
- TeXstudio: 4.0.0
- Qt: 6.1.3
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
All the greek symbols should be present:
![image](https://user-images.githubusercontent.com/15349470/136231822-6594d5dc-ffb2-46f0-add8-f914fbda590c.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/15349470/136231969-88a81555-ad28-4508-91df-12628864e52b.png)

### How to reproduce
Attaching the original file that is causing the issue for me. Other PDF readers in my machine show all the symbols without issues. 
[missing_title.pdf](https://github.com/texstudio-org/texstudio/files/7295160/missing_title.pdf)

The attached file was generated using ``R`` with the following code:

````
require(latex2exp)
require(ggplot2)
p <- ggplot(diamonds, aes(x=carat, y=price, color=cut)) + ggtitle(TeX(r'($\rho = 1, \sigma = 2, \epsilon = 2$)'))
pdf(file='missing_title.pdf')
print(p)
dev.off()
````
And included into latex straightforwardly:
````
\begin{figure}
	\includegraphics[width=1\linewidth]{missing_title.pdf}
\end{figure}
````

**Comment by sunderme** [comment]
fixed with 726ad72f03d2bce5f32b730f24fdc658a5ce3c4b ef7c12ee48d258cb989f7c4d442b2350435a09b0 b74a6c7aa1a9772ea0226097e19a2c22efca667e
