### ISSUE TITLE
Letter É in TexStudio 4.0.0 (macOS Big Sur)

### ISSUE THREAD

**Issue by coulmont** [texstudio-org/texstudio#1819]
### Environment
- TeXstudio: 4.0.0
- Qt version 6.1.3,
- OS: MacOs BigSur

### Expected behavior
French keyboard (AZERTY) :  ALT+SHIT+1 should get ´ and then E to get É (which is a very common French uppercase accentuated letter)

### Actual behavior
Nothing : ALT+SHIFT+1 doesn't write anything
I've tried to see if ALT+SHIFT+1 was assigned to another keyboard shortcut. 

### How to reproduce
Try ALT+SHIFT+1 in TexStudio

**Comment by muzimuzhi** [comment]
looks similar to #1770. In https://github.com/texstudio-org/texstudio/issues/1770#issuecomment-932737174 @sunderme said
> the problem seems to be solved with Qt6.2.
> I will generate a new release once brew has taken up the new version.

So currently it's all waiting for homebrew to upgrade to Qt 6.2.0 (https://github.com/Homebrew/homebrew-core/pull/86836).

**Comment by coulmont** [comment]
Oh thank you !
