### ISSUE TITLE
Scripting - Include not defined

### ISSUE THREAD

**Issue by IHateYourCode** [texstudio-org/texstudio#1824]
[User Manual]: https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html#JAVASCRIPT-MACROS

Just wanted to create a script macro to include another file,
but for some reason it doesn't seem to recognize the global
keyword `include`?

### Environment
- TeXstudio: 4.0.0
- Qt: 5.15.2
- OS: Ubuntu 21.04

### Expected behavior

`Includes another script. Can be a filename or the name of a macro.`
as described in the [User Manual]

--

### Actual behavior

`ReferenceError: include is not defined`

### How to reproduce

Script macro with

```js
%SCRIPT

include('~/Desktop/Build/script.js');
```

And, while not necessary, the corresponding `js` file (empty).

**Comment by sunderme** [comment]
that is correct.
