### ISSUE TITLE
macOS 10.15 is not supported in 4.0.1

### ISSUE THREAD

**Issue by theirix** [texstudio-org/texstudio#1826]
### Environment
- TeXstudio: 4.0.1
- OS: macOS 10.15.7

### Expected behavior

texstudio 4.0.0 is working fine in macOS 10.15 Catalina. So should 4.0.1 (website says "for macOS 10.14 or higher").

### Actual behavior

- 4.0.1 cannot be open due to error "You have macOS 10.15.7. The application requires macOS 11.0 or later."

**Comment by sunderme** [comment]
well, something in the build env disables that it works on 10.15. It will take a bit to figure out what causes this.
