### ISSUE TITLE
TexStudio 4.0.0 4.0.1 Language-Tool ERROR on NON-English Win10 System

### ISSUE THREAD

**Issue by csydzhang** [texstudio-org/texstudio#1833]
All settins are same, TexStudio 4.0.0, 4.0.1 can work with LT in English Win 10, but if using Chinese-Win10, it will show "LT current status: error", "error when communicating with LT"
### Environment
- TeXstudio: <4.0.0 and 4.0.1>
- Qt: <6.0>
- OS: <Windows 10, 64-bit, 21H2, Chinese>

> where java: 
>
>JAVA: C:\Program Files\Java\jre1.8.0_121\bin\java.exe -version
>
>Real-time checking is enabled.
>Grammar checking is enabled.
>
>Tries to start automatically.
>
>LT current status: error
>
>LT-URL: http://localhost:8081/v2/check

NOTE: English Win 10 is OK

**Comment by sunderme** [comment]
difficult to debug from here…
Any takers ?
