### ISSUE TITLE
Visual Bug on the Text Cursor 

### ISSUE THREAD

**Issue by orgekarlo** [texstudio-org/texstudio#1836]
### Environment
- TeXstudio: 4.0.1
- Qt: Version 6.2.0, compiled with Qt 6.2.0 R
- OS: macOS Big Sur 11.6
- TeX distribution: texlive

### Expected behavior

The text cursor on the editor is normally displayed as a blinking vertical line between two characters.

### Actual behavior

This one happens instead:

https://user-images.githubusercontent.com/92455185/137169631-3df7a33b-70f1-411c-a88f-cdf99dd4777d.mov

### How to reproduce

Click on any part of the editor.

**Comment by orgekarlo** [comment]
> screen set-up may play a role. Any details there ?

Well, I usually have a dual screen set-up, but the bug is still there even if the second monitor is not connected.

**Comment by somelinguist** [comment]
I just updated to 4.0.1 and see the same problem on my 16in MacBook Pro with default settings on the built-in display. I'm on macOS 11.6. Let me know if there are any other specific details you need.

It's just the first line of the editor.

**Comment by elicoptetre** [comment]
I'm on macOS 11.6, texstudio version 4.0.1. Same behaviour. But not just the first line of the editor. On the lines where it happens, the slashes fan out from a point on the line (so the inclination of the slash depends on where on the line the cursor is placed).

**Comment by sunderme** [comment]
you could try a different render mode (advanced options)

**Comment by elicoptetre** [comment]
> you could try a different render mode (advanced options)

that does not improve the issue.

**Comment by sunderme** [comment]
can you try to disable option/advanced editor/bold cursor ?

**Comment by sunderme** [comment]
seems not to make a difference

**Comment by sunderme** [comment]
please try latest dev build: https://github.com/texstudio-org/texstudio/suites/4121530521/artifacts/105403715
Also check qt5 version: https://github.com/texstudio-org/texstudio/suites/4121530521/artifacts/105403716
