### ISSUE TITLE
Texstudio 4.0.1 Don't start, broken on OSX 10.15.x

### ISSUE THREAD

**Issue by Jee-Bee** [texstudio-org/texstudio#1843]
### Environment
- TeXstudio: 4.0.1
- Qt: -
- OS: OSX 10.15.7
- TeX distribution:  texlive

### Expected behavior
According to https://www.texstudio.org i should be able to start the new version of Texstudio. See image
<img width="186" alt="Screenshot 2021-10-15 at 11 21 40" src="https://user-images.githubusercontent.com/7187677/137465244-21be055f-553b-4b47-a648-e6fdbed47aea.png">
side note: Homebrew should be changed too since they note it works from 10.12 and up!
<img width="677" alt="Screenshot 2021-10-15 at 12 48 57" src="https://user-images.githubusercontent.com/7187677/137476135-b5c2984b-6b7c-47cb-a1a8-8a0d57fb6b47.png">
### Actual behavior
I'm unable to open the application. The application have a prohibition sign.
<img width="127" alt="Screenshot 2021-10-15 at 11 29 23" src="https://user-images.githubusercontent.com/7187677/137465918-55167b07-8389-4048-b732-2a9cc3f64ce8.png">
and after RMB --> open i got the following error message:
<img width="425" alt="Screenshot 2021-10-15 at 11 22 00" src="https://user-images.githubusercontent.com/7187677/137466028-9bc7dafc-8682-4a61-a4a4-c490a55d9c10.png">
### How to reproduce
just open current version on OSX 10.15.x

**Comment by sunderme** [comment]
updated the webpage.
dev build works with 10.15 again (https://github.com/texstudio-org/texstudio/suites/4063166386/artifacts/103210549)

**Comment by sunderme** [comment]
can you please try: https://github.com/texstudio-org/texstudio/suites/4248241458/artifacts/111246460
It should fix the issue. (as a quick test, press option/general: check updates)
