### ISSUE TITLE
Script document.replace in selected text in 4.0

### ISSUE THREAD

**Issue by andrzej-odyniec** [texstudio-org/texstudio#1845]
### Environment
- TeXstudio: 4.0
- Qt: 
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior

In %SCRIPT command:
editor.replace("a ","gw",editor.document().cursor(cursor.lineNumber(),cursor.columnNumber(),cursor.anchorLineNumber(),cursor.anchorColumnNumber()),"a~")

before 4.0.0 changed "a " with "a~" only in selected text

### Actual behavior

Above command is changing "a " with "a~" in whole document, not only in selected text as command:
editor.replace("a ","gw",editor.document().cursor(0,0,-1),"a~")

### How to reproduce

Inserting command into script and using this Macro on document with one letter words "a "

**Comment by sunderme** [comment]
Assuming that it is just an example (you could use `cursor`directly), the new js engine is a bit picky about how to create cursors.
The new solution is:
```
%SCRIPT
var c=new QDocumentCursor(editor.document(),cursor.lineNumber(),cursor.columnNumber(),cursor.anchorLineNumber(),cursor.anchorColumnNumber());
editor.replace("a","g",c,"a~");
```

**Comment by sunderme** [comment]
manual has been updated
