### ISSUE TITLE
TODO comments are not being highlighted correctly

### ISSUE THREAD

**Issue by ghost** [texstudio-org/texstudio#1867]
### Environment
- TeXstudio 4.0.1 (git n/a)
- Qt: Using Qt Version 5.15.2, compiled with Qt 5.15.2 R
- OS: Arch Linux
- TeX distribution: texlive

### Expected behavior
TODO comments should be highlighted correctly.

### Actual behavior
They are being highlighted like a normal comment, even the "Syntax Highlighting" colours are changed (in settings).

### How to reproduce
Open any .tex file containing a like:
`%TODO: change here`

**Comment by sunderme** [comment]
works fine here.
Have you changed options/adv. editor/Regular expression for TODO comment ? (default is: `%\s*(TODO|todo)`

**Comment by elyoas** [comment]
> works fine here. Have you changed options/adv. editor/Regular expression for TODO comment ? (default is: `%\s*(TODO|todo)`

No I have not changed it. It is still the same..

**Comment by Tux-Code** [comment]
Hi, I have got the same error in all versions from 4.0.
The behaviour does not happen in version 3.12 which was the latest I was using before the latest update.
![image](https://user-images.githubusercontent.com/82405905/144898597-dcdab875-769e-4c4a-aaae-b848714c66d9.png)
I have tested with both Regular expression for TODO comment:
%\s*(TODO|todo)
or
%\s?[A-Z][A-Z_\-]+ (this you recommend in another post somewhere)

**Comment by sunderme** [comment]
what is "crash the font for todo" ?

**Comment by Tux-Code** [comment]
The font is gray as the comment!

**Comment by Tux-Code** [comment]
The color of the TODO is not respected, and the gray from comment overwrites it:
![image](https://user-images.githubusercontent.com/82405905/144900993-4b61da99-73d6-47e1-9242-1174031ed520.png)

**Comment by Tux-Code** [comment]
Changed colour of comment to yellow:
![image](https://user-images.githubusercontent.com/82405905/144901195-8d4afbef-94ff-4697-9f8b-7eb94d5afd8c.png)

**Comment by sunderme** [comment]
probably can be helped by tweaking priority

**Comment by sunderme** [comment]
just check, just change priority for commentTodo to 0 (from -1)

**Comment by Tux-Code** [comment]
Setting the priority to 0 fixed the problem! Thanks!
