### ISSUE TITLE
textstudio pdf viewer does not correctly display embedded pdf graphics

### ISSUE THREAD

**Issue by DavidHankin** [texstudio-org/texstudio#187]
The "viewer" used to display the pdf version of a typeset LaTeX file in texstudio does not allow correct display of all embedded pdf graphics (embedded using \includegraphics in LaTeX). These same graphics display perfectly in the saved .pdf that is created on disk. 

Is there a simple fix to correct this important error

### Environment
- TeXstudio: 
- OS: 

### Expected behavior

Correct display of embedded pdf graphics

### Actual behavior

Imperfect display of embedded pdf graphics. For example, data points missing in scatterplots

### How to reproduce

Result obtains any time a file is typeset and pdf is viewed from within texstudio

**Comment by sunderme** [comment]
please provide a test case/sample file

**Comment by sunderme** [comment]
way to little info
