### ISSUE TITLE
V4.0.1 crashes when undoing action after compilation

### ISSUE THREAD

**Issue by fzenith** [texstudio-org/texstudio#1872]
After launching compilation, trying to undo an action done before compilation will crash the program.
Actions performed after the compilation can still be undone regularly, but crash still occur when reaching actions that were performed before compilation.

This is especially serious as making some changes, compiling, seeing how they play out and eventually undoing them is a common work pattern that is disrupted by this bug.

### Environment
- TeXstudio: 4.0.1
- Qt: 6.2.0
- OS: Windows 10
- TeX distribution: TexLive 2021

### Expected behavior
Modify text; compile; press Ctrl-Z; modifications are undone.

### Actual behavior
Modify text; compile; press Ctrl-Z; dialog titled "TeXStudio Emergency" appears, announcing a crash and allowing to "recover", i.e. keeping the program open; the undo stack is however not recoverable.

### How to reproduce
Modify text; compile; press Ctrl-Z.

### Backtrace
`unknown at 7ff637ab6cc1 (TXS-Version 4.0.1 R )`
`[bt] 00007ff637a1aeb0  ??? error: 487`
`[bt] 000000ddf2de3f60  ??? error: 126`
`[bt] 00000209f5fb1c70  ??? error: 126`

**Comment by fzenith** [comment]
Backtrace:
`unknown at 7ff637ab6cc1 (TXS-Version 4.0.1 R )
[bt] 00007ff637a1aeb0  ??? error: 487
[bt] 000000ddf2de3f60  ??? error: 126
[bt] 00000209f5fb1c70  ??? error: 126`

**Comment by tkingpsl** [comment]
The Ctrl-Z process, as outlined by fzenith, works for me on Win 10 using:
txs: 4.0.2 (git 4.0.1-19-g04ab9bda)  (dev build)
Qt 5.15.2, complied with Qt 5.15.2 R

**Comment by sunderme** [comment]
works win10, txs 4.0.1 qt6

**Comment by tkingpsl** [comment]
Sunderme:

Is TeXstudio software affected by the log4j vulnerability?

Thanks,
Tom King

**Comment by sunderme** [comment]
no
