### ISSUE TITLE
included files in side panel a marked missing (red), although existing

### ISSUE THREAD

**Issue by tweh** [texstudio-org/texstudio#1875]
### Environment
- TeXstudio: 4.0.1 (git 4.0.1)
- Qt: Qt-Version 6.2.0, kompiliert mit Qt 6.2.0 R
- OS: macOS 11.6 (up to date) on MacBookPro13,2
- TeX distribution: MacTeX 2021

### Expected behavior
Files that are on my SSD should be coloured black in the side panel.

### Actual behavior
Actually existing files are marked red, aka missing / non-existent

<img width="898" alt="Bildschirmfoto 2021-10-21 um 00 21 33" src="https://user-images.githubusercontent.com/3011538/138180698-5f57f23d-12b4-464a-a7fe-2d6d916a3209.png">

### How to reproduce

- create a main file and save it
- add `\input{xxx}`
- create `xxx.tex` by clinking it’s name in the side bar
- create `yyy.tex` and save it
- add `\input{yyy}` to main file
- both files are black in the side panel
- quit TeXstudio
- reopen TeXstudio
- open main file
- included files are marked red

### Notes

- I was saving all files in the same folder `~/Desktop/tmp/`
- TeXstudio has full disc access
- I made an update from v3, where my settings where included in v4 (as expected, but maybe the old settings file causes issues)
- There seems to be no difference for `\include`

**Comment by fernandozucatelli** [comment]
> It seems like the issue got better but isn’t solved jet. Pleas see the screen cast:
> 
>  Bildschirmaufnahme.2021-10-26.um.14.30.51.mp4 
> I also attach the demo folder shown in the video.
> 
> [demo.zip](https://github.com/texstudio-org/texstudio/files/7418237/demo.zip)

Is this behavior the supposed correct behavior of all version 4 family? Version 4.2.3 also presents this behavior. Is there a workaround?

**Comment by octaeder** [comment]
Is this the same as #2247? Was fixed 4 days ago, https://github.com/texstudio-org/texstudio/actions/runs/2185248333. At the bottom of that page you see the built dev versions. If you sign in in github you can download it. Maybe you want to try it.

**Comment by fernandozucatelli** [comment]
> Is this the same as #2247? Was fixed 4 days ago, https://github.com/texstudio-org/texstudio/actions/runs/2185248333. At the bottom of that page you see the built dev versions. If you sign in in github you can download it. Maybe you want to try it.

I'm not sure if it is the same as [#2247](https://github.com/texstudio-org/texstudio/issues/2247). #2247 is about some issue 
with wrong naming after saving. I have not seen any issue like that. The issue I see is the **exactly** same behavior in the structure panel of version 4.2.3 as tweh's video presents.

tweh's video behavior as I see it: Inserted files are red, which would imply in not-found files, but they are there, the compilation works. After opening a red marked file, just clicking on it, and returning to the main (root) file, the inserted file on the structure panel becomes black.

**Comment by octaeder** [comment]
I can reproduce with current 4.2.3 Qt6.3.0 on Win10 and dev texstudio-win-qt6-4.2.4-202204181827-git_787704e.exe. As said before, this is a problem of refreshing the structur and TOC as described in #2247 . When you create the file xxx  then structure and TOC musst be refreshed. This happens (as a workaround) when you switch back to tab document.tex.

As a remark the Refresh Structure and update TOC from idefix menu can't resolve the issue.

**Comment by octaeder** [comment]
@sunderme Can you reopen this issue please?
