### ISSUE TITLE
Moving multiple cursors to the end of their lines fails

### ISSUE THREAD

**Issue by FloMiLe** [texstudio-org/texstudio#1879]
### Environment
- TeXstudio: 4.0.1
- Qt: 6.2
- OS: macOS 11.6
- TeX distribution: MacTeX

### Expected behavior
When multiple cursors are placed and the shortcut for "Move cursor to line end" is pressed, all cursors should move the respective ends of the lines.

### Actual behavior
Only the last cursor is moved to the end of its line, all other cursors vanish.

**Comment by FloMiLe** [comment]
I see. If I remember correctly, TXS used to accumulate cursors at the end of the same line. So when there were three cursors on the same line and they were moved to the end of the line, hitting left-delete deleted three characters.

Sublime and Atom solve this by merging cursors at the and of the line. So when there are three cursors on the same line and they are moved to the end of the line, they are merged such that hitting left-delete deletes one character.

I think that would be a nice enhancement.

**Comment by benibela** [comment]
fixed in 7231acaa4023a22850f4e4a0dcfff2c8116e6b99

**Comment by FloMiLe** [comment]
The new implementation of the feature is so great! And it seems super robust. – Thanks so much!

May I just add another little suggestion? It seems the only way to exit multiple-cursor mode at the moment is clicking somewhere with the mouse. Wouldn't it be nice to have a keyboard-only solution for that, e.g. clicking Esc? 

Thanks for considering!

**Comment by sunderme** [comment]
> The new implementation of the feature is so great! And it seems super robust. – Thanks so much!
> 
> May I just add another little suggestion? It seems the only way to exit multiple-cursor mode at the moment is clicking somewhere with the mouse. Wouldn't it be nice to have a keyboard-only solution for that, e.g. clicking Esc?
> 
> Thanks for considering!

implemented
