### ISSUE TITLE
Inconsistent selection/deletion shortcuts on macOS

### ISSUE THREAD

**Issue by FloMiLe** [texstudio-org/texstudio#188]
This is about shortcuts on macOS.

Compared to other macOS apps, TXS seems to behave a little inconsistent when it comes to text selection.

1) Consistent behaviour for Left/Right selection
	cmd+Left/Right moves the cursor to the left/right side of the editor
	cmd+shift+Left/Right highlights the text that the cursor passes for this move

2) Inconsistent behavious for Up/Down selection
	cmd+Up/Down moves the cursor to the beginning/end of the file
	cmd+shift+Up/Down does not do anything

3) Inconsistent behaviour for Left deletion
	cmd+Left moves the cursor to the left side of the editor
	cmd+Del (other apps) deletes text until the left side of the editor
	cmd+Del (TXS) deletes until beginning of entire line if shortcut is set

I just wanted to mention this hoping that you could fix these inconsistencies if they are not wanted but unintentional. Thanks!

### Environment
- TeXstudio: 2.12.8
- Qt: 5.10.0
- OS: Mac

**Comment by sunderme** [comment]
2) is set correctly here
3)txs has no logic to delete until left side of editor in a multi-line text line, so won't fix

**Comment by FloMiLe** [comment]
Sorry, I don't understand the explanation. If TXS can move the cursor from one position to another, then it should also be able to delete everything in between the two positions, shouldn't it?

So for 2), TXS should mark everything until the beginning/end of the file for cmd+shift+Up/Down.

And for 3), since cmd+Left moves the cursor to the left side of the editor, it should be possible to delete content between the current and that cursor positions with cmd+Del.

It is certainly fine to say you think fixing this is unnecessary, but I don't see how logic is missing.
