### ISSUE TITLE
weird search bar behavior

### ISSUE THREAD

**Issue by aliirmak** [texstudio-org/texstudio#1888]
When I try to search for something within a file, the search bar becomes clipped and the text within the search bar is not visible.

### Environment
- TeXstudio: 4.0.2

### Actual behavior
![image](https://user-images.githubusercontent.com/4071128/138948561-cc956a94-9328-4c99-b64a-539b073d13ea.png)

**Comment by efege** [comment]
I confirm this behaviour on Ubuntu 22.04:

- TeXstudio 4.2.1 (Build: 4.2.1+ds-1)
- Using Qt Version 5.15.3, compiled with Qt 5.15.2 R

and also on Windows 10:

- TeXstudio 4.5.2 (git 4.5.2)
- Using Qt Version 6.5.0, compiled with Qt 6.5.0 R

![Untitled](https://github.com/texstudio-org/texstudio/assets/5770894/ca175d30-758b-4043-8c09-f87c25cf1ced)

**Comment by sunderme** [comment]
seems to be fixed
