### ISSUE TITLE
Highlight after code completion extends beyond previously selected text

### ISSUE THREAD

**Issue by FloMiLe** [texstudio-org/texstudio#189]
In the current TXS version, as opposed to earlier versions, the highlighted text after code completion including selected text is too long.

### Environment
- TeXstudio: 2.12.8
- Qt: 5.10.0
- OS: Mac

### Expected behavior
When one highlights some text, then starts writing a macro name like `\emph` and auto-completes it, the previously highlighted text is inserted as argument and selected.

Starting from here
<img width="179" alt="selection before completion" src="https://user-images.githubusercontent.com/13892710/41490235-6daa547c-70f3-11e8-8e0f-245a4885ae57.png">

this is one used to (and should) get
<img width="224" alt="expected selection" src="https://user-images.githubusercontent.com/13892710/41490310-be548e1a-70f3-11e8-931f-11f4e16013f9.png">

### Actual behavior
Instead, the selection after code completion is too long:
<img width="224" alt="selection after completion" src="https://user-images.githubusercontent.com/13892710/41490237-6e5d0b3a-70f3-11e8-86f8-759e35aea425.png">

### How to reproduce
See above.

**Comment by thatlittleboy** [comment]
See #109 and #181. Try a developmental snapshot: https://bintray.com/sunderme/texstudio/texstudio-osx

**Comment by FloMiLe** [comment]
Sorry, I only scanned the open issues for duplicates...

Knowing that this is fixed, I will just wait for the next released version as I do not know how to handle developmental snapshots. Thank you though!
