### ISSUE TITLE
'Go to source' missing from drop menu in pdf builder

### ISSUE THREAD

**Issue by PhilScience** [texstudio-org/texstudio#1891]
### Environment
- TeXstudio: <TeXstudio 4.0.2 (git 4.0.2)>
- Qt: < Using Qt Version 6.2.0, compiled with Qt 6.2.0 R >
- OS: < Windows 10 >
- TeX distribution: < miktex >

### Expected behavior

When building a document, the drop menu when right clicking on the pdf viewer begins with the "Go to source command''. Also, the mouse pointer is typically an arrow, unless 'scroll' is pressed which turns the mouse pointer into a hand.

### Actual behavior

The ''Go to source'' command keeps disappearing from the drop down menu. When I open a new project and compile a new document it reappears on the pdf viewer, but after a couple of ''built & view'''s it disappears again. Also, the mouse pointer has permanently switched into a hand (scroll) and will not return to an arrow, no matter what I do. I 've tried to restore the original settings by removing the .ini file, and I have also completely uninstalled and re-installed TexStudio on my laptop but the behavior remains the same for some reason!

### How to reproduce

I have no idea, sorry.

**Comment by sunderme** [comment]
Without reprocucible test case, there is nothing I can do .

**Comment by PhilScience** [comment]
I can't see how you can reproduce this, sorry. It just looks like texstudio is behaving strangely on my laptop.

**Comment by sunderme** [comment]
Come back, if you have some hints, what goes wrong.
