### ISSUE TITLE
TeXstudio crashes after macOS 11 (Big Sur) wakes from sleep mode

### ISSUE THREAD

**Issue by sbibauw** [texstudio-org/texstudio#1894]
Almost every time macOS returns from sleep mode, I encounter TeXstudio crashed/closed. It does not seem to be specific to 4.x: I had already this issue in the last versions of TeXstudio 3.x.
I'm quite clueless, but it could be linked to an underlying issue, as I have sometimes had this issue with Zotero as well (but never as systematically as with TeXstudio).

### Environment
- TeXstudio: 4.0.2
- Qt: 6.2.0
- OS: macOS 11.6 Big Sur on M1 Mac Mini (ARM)
- TeX distribution: basictex

### Actual behavior
After returning from sleep mode: TeXstudio is crashed (closed with a crash report) and I have to reopen it.

Side note: when it opens, with the setting of reopening the previous environment set, I reopens the PDF in the preview panel, but all files have disappeared from the file list/structure panel and no code appears in the edit panel.

### How to reproduce
Happens almost everytime after macOS returns from sleep mode.

### Excerpt from Crash report (full report on demand)

```
Process:               texstudio [637]
Path:                  /Applications/texstudio.app/Contents/MacOS/texstudio
Identifier:            texstudio
Version:               4.0.2 (0)
Code Type:             X86-64 (Translated)
Parent Process:        ??? [1]
Responsible:           texstudio [637]
User ID:               501

Date/Time:             2021-10-27 17:32:14.014 -0500
OS Version:            macOS 11.6 (20G165)
Report Version:        12
Anonymous UUID:        B9F05D1C-4635-700B-B9C3-A257D88CAA9E

Sleep/Wake UUID:       FAF3A1DB-B937-4DFB-BF42-CB11D1728502

Time Awake Since Boot: 7400 seconds
Time Since Wake:       10 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [637]

Application Specific Information:
*** CFRetain() called with NULL ***

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.CoreFoundation      	0x00007fff205ba3bf CFRetain.cold.1 + 14
1   libqcocoa.dylib               	0x00000001161d0a8a 0x1161c3000 + 55946
2   org.qt-project.QtGui          	0x000000010dc67809 QBackingStore::beginPaint(QRegion const&) + 377
3   org.qt-project.QtWidgets      	0x000000010cc33a45 0x10cbc6000 + 449093
4   org.qt-project.QtWidgets      	0x000000010cc33dff 0x10cbc6000 + 450047
5   org.qt-project.QtWidgets      	0x000000010cc225da QWidget::event(QEvent*) + 1562
6   org.qt-project.QtWidgets      	0x000000010cd63774 QMainWindow::event(QEvent*) + 276
7   org.qt-project.QtWidgets      	0x000000010cbd1167 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 247
8   org.qt-project.QtWidgets      	0x000000010cbd22e5 QApplication::notify(QObject*, QEvent*) + 501
9   org.qt-project.QtCore         	0x000000010fcaece9 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 169
10  org.qt-project.QtCore         	0x000000010fcafe8e QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 814
11  libqcocoa.dylib               	0x00000001161dab05 0x1161c3000 + 97029
12  libqcocoa.dylib               	0x00000001161db27b 0x1161c3000 + 98939
13  com.apple.CoreFoundation      	0x00007fff2048702c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
14  com.apple.CoreFoundation      	0x00007fff20486f94 __CFRunLoopDoSource0 + 180
15  com.apple.CoreFoundation      	0x00007fff20486d6c __CFRunLoopDoSources0 + 340
16  com.apple.CoreFoundation      	0x00007fff20485718 __CFRunLoopRun + 897
17  com.apple.CoreFoundation      	0x00007fff20484cd0 CFRunLoopRunSpecific + 567
18  com.apple.HIToolbox           	0x00007fff2892f1f3 RunCurrentEventLoopInMode + 292
19  com.apple.HIToolbox           	0x00007fff2892ee26 ReceiveNextEventCommon + 284
20  com.apple.HIToolbox           	0x00007fff2892ecf3 _BlockUntilNextEventMatchingListInModeWithFilter + 70
21  com.apple.AppKit              	0x00007fff22bb8172 _DPSNextEvent + 864
22  com.apple.AppKit              	0x00007fff22bb6945 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1364
23  com.apple.AppKit              	0x00007fff22ba8c69 -[NSApplication run] + 586
24  libqcocoa.dylib               	0x00000001161da021 0x1161c3000 + 94241
25  org.qt-project.QtCore         	0x000000010fcb8066 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 470
26  org.qt-project.QtCore         	0x000000010fcaf312 QCoreApplication::exec() + 130
27  texstudio                     	0x00000001027a190f main + 703
28  libdyld.dylib                 	0x00007fff203a9f3d start + 1
```

**Comment by sbibauw** [comment]
> @sbibauw Does this happen with [TeXstudio: 4.0.2 (Qt5) for macOS](https://github.com/texstudio-org/texstudio/releases/download/4.0.2/texstudio-4.0.2-osx-qt5.dmg)?

Hmm. I still have to continue watching out, but I've installed this Qt5 version yesterday and it hasn't crashed until now. So far, all good... Thanks for pointing it out @dbitouze.

**Comment by sbibauw** [comment]
@dbitouze After a few more days, I still had no crash... until TeXstudio got updated by homebrew to 4.0.3 (with Qt 6.2.0), and now I just got a crash again.
So Qt6 indeed seems to be the main culprit here, and using the Qt5 release ([texstudio-4.0.3-osx-qt5](https://github.com/texstudio-org/texstudio/releases/download/4.0.3/texstudio-4.0.3-osx-qt5.dmg)) solves the issue for me.

**Comment by sbibauw** [comment]
Just an update: with Texstudio 4.0.4 with Qt 6.2.1 (and now on macOS 12, Monterey), I don't have had this problem yet. Since it used to be systematic, at every wake, there is a clear improvement. And it might be fixed. I'll let you know if anything comes up.

(Note: [this Qt bug](https://bugreports.qt.io/browse/QTBUG-79944?jql=text%20~%20%22crash%20wake%22) that was "solved" in January 2020 seems closely connected to this, in case anyone needs to investigate further down.)

**Comment by sunderme** [comment]
thanks for the info

**Comment by phzeller** [comment]
I'm observing the same issue on macOS 12.4 and TeXstudio 4.2.3 (git 4.2.3) [Using Qt Version 6.2.3, compiled with Qt 6.2.3 R]. Any ideas?
