### ISSUE TITLE
Autocompletion not working with the `standalone` package

### ISSUE THREAD

**Issue by Zheoni** [texstudio-org/texstudio#1895]
### Environment
- TeXstudio: 4.0.2
- Qt: 6.2.0
- OS: MacOS (both Big Sur and Monterey)
- TeX distribution: MacTeX (TeX Live)

### Expected behavior
When I use the `\includestandalone` macro it should autocomplete and mark it as correct latex syntax.

### Actual behavior
Usage of the `\includestandalone` macro is marked as an unrecognised command. When compiled, all works fine, but it's annoying seeing it marked as if it is wrong. I have tried deleting the autogenerated `standalone.cwl` but the result is the same.

### How to reproduce
2 files:
```tex
% main.tex
\documentclass{article}

\usepackage{standalone}
\usepackage{tikz}

\begin{document}

% this is marked as unrecognised
\includestandalone{fig_test}

\end{document}
```

```tex
% fig_test.tex
\documentclass[tikz]{standalone}

\begin{document}
    \begin{tikzpicture}
        \draw (0,0) rectangle (2,1) node[midway] {Example};
    \end{tikzpicture}
\end{document}
```

**Comment by Zheoni** [comment]
Ok, my bad. I'm sorry, I didn't see the wiki. I managed to create a cwl file for the package myself. Thanks for your answer! I'm really enjoying writing my documents in texstudio, thanks for your work.

**Comment by sunderme** [comment]
you could hand in your cwl if you like.

**Comment by Zheoni** [comment]
I have put together all the commands and options, however I have not tested it as I don't use all of them. Also, I think this package does something unsupported by the cwl description here: https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/blob/master/utilities/manual/usermanual_en.html#CWLDESCRIPTION

The "problem" is that this package behaves differently when used as a document class or with \usepackage. The same command has different keyvalues in these 2 situations. Now it shows all the key values no matter how it is used.

Should I make a pull request o just paste the file here?

**Comment by sunderme** [comment]
If possible, a pull-request is preferable.
