### ISSUE TITLE
Why does the Chinese input box stay fixed in the top left corner of the computer screen?

### ISSUE THREAD

**Issue by YojiroMengyu** [texstudio-org/texstudio#1896]
### Environment
- TeXstudio: 4.0.2
- Qt:  Qt 6.2.0
- OS: MacOS 12.0.1
- TeX distribution: texlive

### Description
After updating my texstudio to 4.0.1, my input box has been kept fixed in the top left corner of the computer screen and recently I updated texstudio to 4.0.2 but the problem still can't be solved.

**Comment by ShujunW** [comment]
I also have the same problem with QT6

**Comment by M1ddlzh** [comment]
same issue on QT6 version, and the DPI of startup logo also different.

**Comment by sunderme** [comment]
my bad
