### ISSUE TITLE
XFAIL test

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#1898]
### Environment
- TeXstudio:  4.0.3 (git 3.1.2beta1-648-g26def17d)
- Qt: 5.15.2
- OS: GNU/Linux Mageia 8
- TeX distribution: TeX Live

### Actual behavior
Don't know whether it is worth to report or not but, anyway, building TXS leads to an "XFAIL test":

`XFAIL  : QEditorTest::autoClosing(insert-match-to-close-mixed-with-same2) currently not properly supported`

**Comment by sunderme** [comment]
xfail means "expected fail"
