### ISSUE TITLE
removing (outdated) bundled libraries

### ISSUE THREAD

**Issue by jonasstein** [texstudio-org/texstudio#19]
I was preparing a new package for Gentoo, when I realized that the tar ball is very large.
So I looked into it and saw that many bundled libraries (some very old) are included.
Do you really need them here? We try to compile all software with fresh libs from the system.

Removing the bundled stuff would clarify also which files belong to texstudio and which are external projects.

Which versions are required? Somewhere I saw a very old qt4 `QAZip`. However texstudio runs with qt5 since a while...

**Comment by sunderme** [comment]
texstudio still builds on qt4 and we are not abandoning that for now (to support older linux distributions).
Since the bundling makes things easier on some platforms which don't provide an easy package system (win,osx), I don't see really the necessity to remove any of it. By setting the configs for qmake, you can use system libraries instead if you want to ...

**Comment by jonasstein** [comment]
Would it be a clean solution to have one pure texstudio.git and one texstudio-budles.git? You would keep the texstudio tree clean and it is clear what is bundled and what is texstudio. Also you could make simple tests with different library versions. For example one branch  texstudio-budles.git/poppler-4x and one texstudio-budles.git/poppler-6x to test, if black magic happens with other libraries... 
For Gentoo we can delete all bundled libs of course and use the system libs. However I have not found out which versions are required. A list like >=poppler-4.1 and so on would be very helpful.

**Comment by sunderme** [comment]
the short answer is no.

The long answer is, we are building txs on 30+ target platforms via OBS/travis/PPA. I am not going to break any of this for cosmetic/dogmatic reasons. You can build txs against system libraries without problem. Unused code in the src does not impede you in any way.

From your point of you, txs builds against all versions of poppler (it still builds on ubuntu 12.04 and poppler there is ancient)
