### ISSUE TITLE
TXS falls into state with dysfunctional shortcuts

### ISSUE THREAD

**Issue by FloMiLe** [texstudio-org/texstudio#190]
Several times a day, TXS falls into a weird state in which shortcuts do not work anymore at all. After bringing an other app into focus (`cmd+tab`) and coming back to TXS, shortcuts do work again.

So far, I have found one way to reliably reproduce this behavior:
1) Open TXS and a new file. Check that a shortcut, say `cmd+e` (to start an environment), works.
2) Open Preferences and press Cancel to close that window again.
3) Find that shortcuts do not work anymore.

### Environment
- TeXstudio: 2.12.8
- Qt: 5.10.0
- OS: Mac

**Comment by sunderme** [comment]
works fine here

**Comment by sunderme** [comment]
which version of osx ?

**Comment by FloMiLe** [comment]
I am using macOS 10.13.5.

**Comment by tweh** [comment]
Same here. But I couldn't figure out, when it happens, i.e. what is causing TXS to ignore the defined shortcuts.

**Comment by sunderme** [comment]
probably obsolete
