### ISSUE TITLE
Cursor behaves erratically

### ISSUE THREAD

**Issue by ThomasKoenigBern** [texstudio-org/texstudio#1908]
On my macOS 12.01, the cursor behaves erratically in TexStudio 4.03. Certain lines cannot be targeted with the mouse pointer or using the vertical arrow keys.

**Comment by sunderme** [comment]
more details. There is a reason that the template offers a certain flow for information.

**Comment by ThomasKoenigBern** [comment]
Hi sunderme, thanks for taking this up.

When I mouse-click on certain lines, the cursor is being put on another line. When I use the up- / down- arrow keys, these lines are also being left out. Sometimes, the only means to put the cursor at the desired position is to use the left and right arrow keys from where the cursor happens to end up when clicking into the text. And I just found out that the behavior depends on the choice of the font size of the editor. When I select size Courier size 12, everything seems fine. Courier 16 is having the described issues.

**Comment by sunderme** [comment]
a test document and maybe a screencast is helpful.
Any other non-default settings ?

**Comment by ThomasKoenigBern** [comment]
Here's a video of what happens when I regularly move the cursor with the vertical arrow keys first, and then using the mouse.

And where do I find the non-default settings that you find relevant? I've attached a screenshot of my editor settings. A test file is in the zip archive, it's happening across documents, though.

https://user-images.githubusercontent.com/84919845/139688415-0cffd081-fde9-4dff-b651-e54e97a53f22.mp4
![2021-11-01 15 29 39](https://user-images.githubusercontent.com/84919845/139688854-baa37218-492f-461e-9707-5e9537a11ca8.jpeg)
[Archive.zip](https://github.com/texstudio-org/texstudio/files/7453994/Archive.zip)

**Comment by sunderme** [comment]
you can check with the latest dev. build, once it is finished.

**Comment by ThomasKoenigBern** [comment]
Seems all fine now, thanks a lot :-)

**Comment by ChesterXXX** [comment]
I am having this exact same issue with TexStudio 4.0.3 on Windows 10. I can reproduce this behavior on the Portable Qt6 version by setting the `Editor > Line Spacing` value to 110%. Note that the Qt5 version doesn't have this issue.
