### ISSUE TITLE
TExstudio 4.0.3 does not start in MacOS Catalina 10.15.7

### ISSUE THREAD

**Issue by posenato** [texstudio-org/texstudio#1911]
### Problem

- Just updated TexStudio 4.0.3 via brew (I tried also the dmg archive provided here in github). 

- It does not start: I see logo, I see the main window but, then, everything disappears suddenly. 

- In the problem report for Apple, there is the following log:

> /usr/lib/libcrypto.dylib
> abort() called
> Invalid dylib load. Clients should not load the unversioned libcrypto dylib as it does not have a stable ABI.

- I think it is sufficient to understand the problem.

### Environment
- TeXstudio: 4.0.3
- Qt: I cannot see it because app does not start
- OS: MacOS Catalina 10.15.7
- TeX distribution: TeXLive

**Comment by sunderme** [comment]
I announce txs as osx 11+.
There seems to be an issue with the update checker on 11.15, see #1843, resolution at the bottom.
You need to deactivate the update check: texstudio.ini -> `Update\AutoCheck=false`

**Comment by posenato** [comment]
And it is necessary also to configure 'brew' to not upgrade.

BTW, just for your info:
1. I have restored version 4.0.0.
2. I run 4.0.0 version and it was ok.
3. then, I run the version 4.0.3 (that I saved as `TexStudio4.0.3`): it works well! :-)

**Comment by sunderme** [comment]
just make sure to turn off "update check".
It runs only once a week and it will probably crash txs 4.0.3.

**Comment by muzimuzhi** [comment]
> I announce txs as osx 11+.

I opened a PR to homebrew-cask.
 - https://github.com/Homebrew/homebrew-cask/pull/113658

**Comment by benibela** [comment]
> > I announce txs as osx 11+.
> 
> I opened a PR to homebrew-cask.
> 

perhaps that is backwards

libcrypto.dylib only worked in old  MacOS versions and is disabled in newer version, is it not?

**Comment by sunderme** [comment]
can you please try: https://github.com/texstudio-org/texstudio/suites/4248241458/artifacts/111246460
It should fix the issue. (as a quick test, press option/general: check updates)

**Comment by posenato** [comment]
> can you please try: https://github.com/texstudio-org/texstudio/suites/4248241458/artifacts/111246460 It should fix the issue. (as a quick test, press option/general: check updates)

I downloaded and run on Mac OS X Catalina (10.15.7).
It works even better than 4.0.3 because it reopens all previously opened files. 
:-)

Thanks.

Roberto

**Comment by muzimuzhi** [comment]
> > I announce txs as osx 11+.
> 
> I opened a PR to homebrew-cask.
> 
> * [Update texstudio `depends_on` to Big Sur Homebrew/homebrew-cask#113658](https://github.com/Homebrew/homebrew-cask/pull/113658)

@sunderme Sorry I'm a bit confusing. Does txs 4.0.4 and the future 4.x releases for osx still depend on osx 11+?

**Comment by sunderme** [comment]
It seems to work with 10.15 again.

**Comment by sunderme** [comment]
@muzimuzhi can you check with brew tomchange it againto 10.15?

**Comment by muzimuzhi** [comment]
> @muzimuzhi can you check with brew tomchange it againto 10.15?

See 
 - https://github.com/Homebrew/homebrew-cask/pull/114015

I was about to open a such PR earlier today, but not get convinced from https://github.com/texstudio-org/texstudio/compare/4.0.3...4.0.4. Perhaps it's the consequence of using Qt 6.2.1 (on macOS)?

And, the behavior @posenato complained is a homebrew issue.

**Comment by muzimuzhi** [comment]
> And, the behavior @posenato complained is a homebrew issue.

A quick search shows 
```
 - This issue was firstly fixed in https://github.com/Homebrew/brew/pull/8572 (Sep 2, 2020).
 - That change was reverted and re-reverted several times (Apr-May, 2021), in solving timeout issue. 
   The last time it is touched was by https://github.com/Homebrew/brew/pull/10924.
(To avoid adding backrefs to homebrew issues, I put these lines/refs in code block on purpose.)
```
