### ISSUE TITLE
Texstudio 4.0.1 and 4.0.2 and 4.0.3 crash on startup

### ISSUE THREAD

**Issue by MarkusBodensee** [texstudio-org/texstudio#1916]
### Environment
- TeXstudio: TeXstudio 4.0.1 and 4.0.2 and 4.0.3 --> installer file name: texstudio-4.0.1-win-qt6.exe and texstudio-4.0.2-win-qt6.exe and texstudio-4.0.3-win-qt6.exe
- Qt: According to [changelog](https://raw.githubusercontent.com/texstudio-org/texstudio/master/utilities/manual/CHANGELOG.txt), it is Qt6 or more likely Qt6.2, but since I cannot start TeXstudio, I am not able to open the about dialogue.
- OS: Windows 7 Professional, Service Pack 1, 64 bit OS
- TeX distribution: MiKTeX with MiKTeX Console 4.4, all packages up to date

### Expected behavior
TeXstudio starts up normally.

### Actual behavior
Error message while starting TeXstudio 4.0.1 or 4.0.2 or 4.0.3, see below. It happens directly after opening the .exe file. After the error message, TeXstudio doesn't show up.

![grafik](https://user-images.githubusercontent.com/82021174/140162438-cd4b174a-28ae-4632-beab-10a02682e3a1.png)

Translated:
Entry point not found

The entry point of the procedure "CreateEventW" was not found in the DLL file "api-ms-win-core-synch-l1-2-0.dll".

### How to reproduce
I had TeXstudio 4.0.0 installed on my machine which works properly. Updated to any of the versions 4.0.1 or 4.0.2 or 4.0.3 on top, afterwards the crash on startup happens.

I don't know if it is the same issue like #1915, so I decided to open another issue. And like mentioned, I had no problem with 4.0.0, it just works fine, installer file name: texstudio-4.0.0-win-qt6.exe.

About dialogue of TeXstudio 4.0.0 which works fine:
TeXstudio 4.0.0 (git 4.0.0)
Nutze Qt-Version 6.1.3, kompiliert mit Qt 6.1.3 R

So obviously it must be a change which was introduced between 4.0.0 and 4.0.1

**Comment by MarkusBodensee** [comment]
Sorry, my initial issue was not accurate enough. I updated my initial posting to what I found out after retesting all of the mentioned versions of TeXstudio.

**Comment by sunderme** [comment]
win 7 is end of life.
Qt6 does not support it. Qt5 does, so use that version.

**Comment by MarkusBodensee** [comment]
@sunderme Thank you for your reply.

TeXstudio 4.0.0 with Qt 6.1.3 obviously works with Windows 7. Is Qt updated to 6.2 with TeXstudio 4.0.1 for Windows? So maybe this is the cause... and Windows 7 is not able to run Qt 6.2?

Would be sad if newer versions of TeXstudio are no more runable on Win 7, because its still a good OS beside Win 10.

**Comment by sunderme** [comment]
any particular reason why you don't use the qt5 version ? txs is identical.
Qt6 is win10+, no guaranties that it runs on older windows systems whatsoever.

**Comment by MarkusBodensee** [comment]
@sunderme
No, there is no reason why not to use the Qt5 version. Just have to remember it while updating to choose the Qt5 version then.

In the meanwhile, I installed TeXstudio 4.0.3 with Qt 5 (installer texstudio-4.0.3-win-qt5.exe) and it works fine.

Thank you very much for the hint and clarification. Much appreciated.

**Comment by mike-a** [comment]
There is every reason why TexStudio download page should specifically state which versions of TexStudio are not backward compatible with older operating systems. Loyal users will move to other products.
