### ISSUE TITLE
Internal PDF viewer creates horizontal light grey lines when using magnifying glass

### ISSUE THREAD

**Issue by RoadTeXer** [texstudio-org/texstudio#1918]
### Environment
- TeXstudio: 4.0.2 and 4.0.3
- Qt: 6.2.0 R
- OS: Windows 10
- TeX distribution: miktex 21.6.28

### Expected behavior
Using the magnifying glass, the text will be magnified; releasing the magnifying glass, the page returns to its normal size

### Actual behavior
When the magnifying glass is activated, all is fine: text is magnified. Upon release, a series of horizontal  grey lines will appear over the text until page is refreshed (for instance, scrolling up or down, changing pages or running pdflatex again).
This screenshot shows how a page looks when using the loupe:
![image](https://user-images.githubusercontent.com/93679521/140185450-84ca298e-98e8-4076-abba-d78642ec7387.png)

The grey lines will continue until page is refreshed (for instance, scrolling up or down, changing pages or running pdflatex again). I used the loupe 3 times on a black page to show the lines more clearly:
![image](https://user-images.githubusercontent.com/93679521/140185744-89388be6-c31b-412c-88bf-e64b9384a478.png)

### How to reproduce

Run pdflatex on this file:
`\documentclass{article}
\usepackage{lipsum}

\begin{document}
\noindent
\lipsum
\end{document}
`
Use the magnifying glass

**Comment by jcardenast** [comment]
Hi, I have the same issue, but is due to Qt: 6 version. IF you want to avoid that bug, you can use the TexStudio with QT5 and it works ok. (You can find it on Downloads section on the main page)

**Comment by sunderme** [comment]
see also #1773

**Comment by Maddahgom** [comment]
I'm not sure but I think it's because 125% Display scale, you can change it in "Scale and layout" part in display settings.

**Comment by andrexleitao** [comment]
> I'm not sure but I think it's because 125% Display scale, you can change it in "Scale and layout" part in display settings.

That is not the reason. I use a scale of 100% and have the same problem.
