### ISSUE TITLE
Pasting '0x0D0A'  in a comment

### ISSUE THREAD

**Issue by MattG-K** [texstudio-org/texstudio#1919]
I came across a weird behavior of the text editor while copying text from a PDF into a LaTeX comment with TeXstudio.
It appears that the text contains the hexadecimal ACSII sequence `0x0D0A` (i.e., carriage return followed by line feed).
TeXstudio correctly breaks the pasted text in two parts: the first is part of the original LaTeX comment (starting with a `%`), and the second is a new line without leading `%`.

The real problem occurs when I want to cancel this line breaking, either by pressing `suppr` at the end of the first part or pressing `del` at the beginning of the first part. Then, TeXstudio shows both parts in the same comment, while preserving the character `0x0D`. Upon compilation, the consequence is that the second part unexpectedly shows up in the output document.

### Environment
- TeXstudio: 3.0.4 (Build: 3.0.4+ds-1)
- Qt: 5.15.2
- OS: GNU/Linux (Ubuntu 21.10)
- TeX distribution: TeX Live 2020 from Ubuntu packages 

### Expected behavior
Both  characters `0x0D` and `0x0A` must be removed by pressing `suppr` or `del` (see above).
When the user sees
```latex
% A B
```
then `B` should not show up in the compiled document.

### Actual behavior
The character `0x0D` survives and the pasted text appears gathered as a comment. If `A` and `B` are the first and second part, respectively, TeXstudio shows:
```latex
% A B
```
But when compiling, `B` shows up in the output document.

### How to reproduce

1. Write a minimal LaTeX document, like
```latex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\begin{document}
% 
\end{document}
```
2. Paste the hexadecimal acsii sequence `0x410D0A42` after the symbol `%`.
3. join `A` and `B` within the same comment line (either `del` or `suppr`)
4. compile your LaTeX document
5. observe that `B` is rendered in the output file

**Comment by sunderme** [comment]
how do you even paste a windows text format on linux ?

**Comment by MattG-K** [comment]
> how do you even paste a windows text format on linux ?

I'm not sure. Is this a joke?
This bug report should be Windows-free. All was done on Linux. I copied text from a PDF opened with Evince. The PDF was generated on Linux using a TeX engine (obviously). If necessary, I could provide a minimal PDF for demonstration purposes.

**Comment by sunderme** [comment]
Please do

**Comment by MattG-K** [comment]
Here is the source.
```latex
\documentclass{standalone}
\usepackage{tikz}
\begin{document}
\tikz{\node[text width=3mm]{A B};}
\end{document}
```
[MWE.pdf](https://github.com/texstudio-org/texstudio/files/7530103/MWE.pdf)
