### ISSUE TITLE
Improve templates of issues/feature requests

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#1921]
### Describe the feature and the current behavior/state
In order to get issues/feature requests better filled, the corresponding templates could be improved. An example is [this one on the JabRef repository](https://github.com/JabRef/jabref/issues/new?assignees=&labels=&template=bug_report.yml) (though it looks too much constraining IMO)
### Who will benefit with this feature?
Developers.

**Comment by sunderme** [comment]
looks a bit confusing.
I find our's not so bad.

**Comment by dbitouze** [comment]
> looks a bit confusing. I find our's not so bad.

They would prevent badly filled issues you're often facing recently. But it is up to you :smile:

**Comment by sunderme** [comment]
That is more an issue with reading and following instructions ;-)

**Comment by muzimuzhi** [comment]
I did some searching and find the mentioned issue template is a new, YAML configured issue form. Seems useful and I maybe recommend it to other repos.
 - [Issues forms beta for public repositories](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) - GitHub Blog
 - [Creating issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) - GitHub Docs

**Comment by muzimuzhi** [comment]
> I did some searching and find the mentioned issue template is a new, YAML configured issue form. The most benefit as I understand is the required fields become mandatory (not skippable). Seems useful and I maybe recommend it to other repos.
> 
> * [Issues forms beta for public repositories](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) - GitHub Blog
> * [Creating issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) - GitHub Docs
