### ISSUE TITLE
TeXstudio crashes upon opening due 

### ISSUE THREAD

**Issue by nik312123** [texstudio-org/texstudio#1922]
### Environment
- TeXstudio: 4.0.3
- Qt: 6.2.0
- OS: macOS Catalina 10.15.7
- TeX distribution: texlive (as installed by MacTeX)

### Expected behavior
TeXstudio opens without issue.

### Actual behavior
TeXstudio crashes with the following error message in the report:
`Invalid dylib load. Clients should not load the unversioned libcrypto dylib as it does not have a stable ABI.`

### How to reproduce
Install TeXstudio on macOS, and open the application.

### Notes
1. I tried reinstalling 4.0.3, but that did not resolve the issue.
2. I then tried installing 4.0.0 over the 4.0.3 app, opening it, running it for a file, and then installing 4.0.3 over the 4.0.0 app, and that seems to have fixed the issue for my machine particularly, but the aforementioned behavior seems like a bug.

**Comment by sunderme** [comment]
can you please try: https://github.com/texstudio-org/texstudio/suites/4248241458/artifacts/111246460
It should fix the issue. (as a quick test, press option/general: check updates)

**Comment by nik312123** [comment]
Ah, as mentioned in the second note, I was able to resolve it by installing 4.0.0 over 4.0.3 and then installing 4.0.3 over 4.0.0. As such, I unfortunately cannot test that the solution fixed the issue.

**Comment by sunderme** [comment]
fixed.
