### ISSUE TITLE
Some unexpected lines in the magnifier. (version4.0.3)

### ISSUE THREAD

**Issue by zhaosh05** [texstudio-org/texstudio#1924]
It was just fine before ver 4.0.0. After update to 4.0.2, there has been such a problem as follows.

![2021-11-06 132711](https://user-images.githubusercontent.com/9410461/140618522-1ae0b7bd-3dce-4aee-bfb3-59d8db1bc9b8.png)

**Comment by sunderme** [comment]
Qt6 bug, see #1773

Qt6 does not work properly for scaling factor like 125% (100% or 150%) is okay. Bug is reported and confirmed.
Change the scaling factor or use Txs qt5 version.
