### ISSUE TITLE
Field completion

### ISSUE THREAD

**Issue by TheBrokenEngineer** [texstudio-org/texstudio#1925]
### Environment
- TeXstudio: 4.0.3
- Qt: 6.2.0
- OS: macOS 11.6.1 (Big Sur)
- TeX distribution: miktex

### Description
The completion for fields does not seem to work correctly when advancing to different fields. Am not sure if this is a bug or a question, the steps to reproduce.

type **\[\frac** then select the fraction from the list. **\[\frac{num}{den}\]** is displayed with the cursor in the num position. Upon typing the **num** disappears and is replaced with the typed text. I then press return which clears the selection box and leaves the edited text in place.  

I would have _expected_ the cursor to move to the **den** and this text disappear when I changed the value. 

Actual result is that once return is pressed the cursor does not advance and instead stays in the exact position. The **den** still has a box around it. The work around is to select the text **den** then type the value, a bit annoying:(

I did have a bit of a poke around in the documentation and then in the code but couldn't see anything obvious.

**Comment by muzimuzhi** [comment]
Texstudio has shortcuts for "Next/Previous Placeholder", but you seem to require "Enter" to play two roles.

**Comment by sunderme** [comment]
you don‘t press enter but the shortcut for the next placeholder.
