### ISSUE TITLE
Cursor to end of line (control+E) not working

### ISSUE THREAD

**Issue by davidgontier** [texstudio-org/texstudio#1928]
### Environment
- TeXstudio:  VERSION 4.04
- Qt: 6.2.1
- OS:  Mac

The shortcuts Control+A or Control+E is no longer working in version 4 (it was working in v3).
The shortcut is present in "Preference -> shortcuts -> Editor", but it is not working.

**Comment by levitabris** [comment]
I don't think it is about the remapped shortcuts. I reset the configuration profile and the default key navigation such as Ctrl + N is not working neither. I'm on the same platform with same version.

**Comment by muzimuzhi** [comment]
Tested with txs Qt5 4.0.4 on macOS, binding `Ctrl + E` to "Move cursor to line end" works.

**Comment by sunderme** [comment]
> Tested with txs Qt5 4.0.4 on macOS, binding `Ctrl + E` to "Move cursor to line end" works.

@muzimuzhi do you see the issue with qt6?

**Comment by muzimuzhi** [comment]
> > Tested with txs Qt5 4.0.4 on macOS, binding `Ctrl + E` to "Move cursor to line end" works.
> 
> @muzimuzhi do you see the issue with qt6?

Just tested. Yes.

**Comment by sunderme** [comment]
This is a qt6 issue (who would have thought)
You can enter "ctrl+e" in the shortcut menu. It does not show as "^E" but as "^ ". That seems to works correctly though.
Apparently qt6 has botched the key codes.

**Comment by sunderme** [comment]
qt6 bug: https://bugreports.qt.io/browse/QTBUG-97713
They claim it its fixed with 6.2.2 (whenever that is published)

**Comment by muzimuzhi** [comment]
Qt 6.2.2 do fixed the bug. I just installed a latest [build](https://github.com/texstudio-org/texstudio/actions/runs/1545947509) compiled with 6.2.2.
