### ISSUE TITLE
Alignment of "fit to text width" with hyperref (integrated PDF viewer)

### ISSUE THREAD

**Issue by NikoKrause** [texstudio-org/texstudio#193]
### Environment
- TeXstudio: 2.12.8
- Qt: 5.9.5
- OS: Linux Mint 19
- TeX distribution: texlive

### Behavior
When I use "fit to text width" in the integrated PDF viewer, the text is centered, as seen here:
![screenshot-area-2018-06-18-145242](https://user-images.githubusercontent.com/8415124/41536957-5c250a4c-7307-11e8-8307-bb2e77c44463.png)

When I press a hyperref link, the viewer jumps to the reference, but the text is no longer centered but left aligned:
![screenshot-area-2018-06-18-145644](https://user-images.githubusercontent.com/8415124/41537142-dab216e8-7307-11e8-85ef-60ebb40b5ffc.png)

The text should stay centered.

**Comment by sunderme** [comment]
please provide a test case/pdf , so that we can test easily

**Comment by NikoKrause** [comment]
Thank you!
