### ISSUE TITLE
Strange gray space in a single page document

### ISSUE THREAD

**Issue by sergiokapone** [texstudio-org/texstudio#1932]
### Environment
- TeXstudio:  4.0.4 (git 4.0.4)
Using Qt Version 6.2.1, compiled with Qt 6.2.1 R
- TeX distribution: texlive

### Actual behavior

In a single document, starange gray field appear. It is looks not so good, especially with standalone package 

### How to reproduce

just compile sigle paged document

[picture ](https://www.upload.ee/download/13626985/71915ceac0e11a140449/Clipboard-1.png)

**Comment by muzimuzhi** [comment]
Seems reproducible with "Style: Orion Dark". The problem is, the internal PDF previewer renders the page in a full-height column, and when the page is shorter than that column, the lower remaining area is always in gray, which should be controlled by the dark style.

**Comment by sunderme** [comment]
The gray area represents no page area. That is similar in other pdf viewers.
Not sure what other color should better represent this.

**Comment by muzimuzhi** [comment]
The point is, 
 - with "Style: default", left = right = below = some gray
![image](https://user-images.githubusercontent.com/6376638/141654040-9cd67695-cd30-46a6-a702-cce2f1af4a3d.png)
 - with "Style: Orion Dark", left = right = some color in dark theme, but below = some gray. Shouldn't below = left = that same color in dark theme?
![image](https://user-images.githubusercontent.com/6376638/141654051-a136d70b-0703-47c4-99af-9ba05ca6faa8.png)

**Comment by sunderme** [comment]
possibly.
Maybe the creator of the stylesheet wants to fix it.
