### ISSUE TITLE
Edit macro: document doesn't have property "editorView"

### ISSUE THREAD

**Issue by MoisesPotato** [texstudio-org/texstudio#1933]
I don't know how to get a macro to open a file and then do something in that file. I would guess my scripts are wrong, but it doesn't work with the macros that are copied from the manual.

The manual and the examples seem to suggest that document.editorView should do it, but that doesn't seem to be a property that exists.

### Environment
- TeXstudio: 4.0.4 (git 4.0.4)
- Qt: Version 6.2.1, compiled with Qt 6.2.1 R
- OS: macOS Catalina 10.15.7
- TeX distribution: Tex Live 2021

### Expected behavior

A new file opens and something is written to it.

### Actual behavior

Get alert "Type error at line 3: cannot read property 'editor' of undefined", because ```documentManager.currentDocument``` doesn't have a property ```editorView```)

### How to reproduce

Try to run this macro (copied from the manual):

```
%SCRIPT
function write_properties(obj) {
    app.fileNew();
    newEditor = documentManager.currentDocument.editorView.editor;   //access the newly created document
    newEditor.setText(Object.getOwnPropertyNames(obj).join("\n"));   //print the properties
}

obj = editor;                                                        //object to show (e.g. the current editor)
write_properties(obj)
```
Click run script to get an angry message:

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/28111500/141362357-f941a2fa-240c-4fa6-88d8-13f8a8ae78c0.png">

<img width="532" alt="image" src="https://user-images.githubusercontent.com/28111500/141362372-0572a9d8-d192-4f4f-a89e-a87754c73c09.png">

**Comment by MoisesPotato** [comment]
The macro works on Linux though.

**Comment by sunderme** [comment]
```document.editorView``` does not work with qt6.
I have changed the dev build to provide: ``` document.getEditorView()```
The code should then look like:
```
doc = documentManager.currentDocument
edView=doc.getEditorView();   //access the newly created document
newEditor=edView.editor
```
(dev build: https://github.com/texstudio-org/texstudio/actions/runs/1453514922 )
