### ISSUE TITLE
ZLIB error when trying to run appimage on Ubuntu 16.04

### ISSUE THREAD

**Issue by he-b** [texstudio-org/texstudio#1934]
### Environment
- TeXstudio: >4.0 appimage executable
- OS: Ubuntu 16.04

### Expected behavior
Launch TeXstudio

### Actual behavior
Error message:
```
texstudio: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/.mount_texstuJnimDu/usr/bin/../lib/libpng16.so.16)
```

### How to reproduce
Try to run TeXstudio appimage on Ubuntu 16.04

TeXstudio version 3.1.2 works fine.

Thanks for your help!

**Comment by sunderme** [comment]
Appimage has moved to 18.04 as oldest supported system. 4.x probably does not run on 16.04 any more. You can try to compile but i doubt it.
