### ISSUE TITLE
input box for the input method is always at the bottom right of the screen

### ISSUE THREAD

**Issue by CuiaCuiSha** [texstudio-org/texstudio#1941]
Version: TeXstudio 4.0.4 

When I use the Microsoft input method, the input box for the input method is always at the bottom right of the screen. Just like this

<img width="675" alt="Snipaste_2021-11-15_19-52-23" src="https://user-images.githubusercontent.com/32769735/141778075-b38006c8-1c88-4634-98f5-64846b0ae706.png">

**Comment by sunderme** [comment]
This is a bug in txs.
It is fixed in the dev version: https://github.com/texstudio-org/texstudio/actions/runs/1458501497
