### ISSUE TITLE
Menu bar is broken

### ISSUE THREAD

**Issue by Altonss** [texstudio-org/texstudio#1942]
### Environment
- TeXstudio: 4.0.4
- Qt: 5.15.2
- OS: Fedora 35, Gnome desktop with wayland, with fractional scaling to 125%
- TeX distribution: texlive (I think)

### Expected behavior
The menu bar should behave normally.

### Actual behavior
When clicking on some entries of the menu bar, the list of items of that menu is displayed at the wrong place.

### How to reproduce
Open TexStudio and hover with the mouse over the menu bar.

**Comment by sunderme** [comment]
sounds rather like a qt/gnome issue.
Have you tried other qt5 programs, like texworks for example ?

**Comment by Altonss** [comment]
Texworks works fine

**Comment by Altonss** [comment]
When lauching with the terminal I get
`QSocketNotifier: Can only be used with threads started with QThread
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
QObject::connect: Cannot queue arguments of type 'std::set<QString>'
(Make sure 'std::set<QString>' is registered using qRegisterMetaType().)`

Then when hovering over the menu bar items I get every time in the terminal this message:
`qt.qpa.wayland: Wayland does not support QWindow::requestActivate()`
Could this be the issue?

**Comment by sunderme** [comment]
do I see it correctly that you have to use an experimental feature to get gnome to offer 125% scaling ?
```
gsettings set org.gnome.mutter experimental-features “[‘scale-monitor-framebuffer’]”
```

**Comment by Altonss** [comment]
Yes I have turned fractional scaling on, but even when I set it on 100% I get the bug.

**Comment by sunderme** [comment]
txs uses qt to manage menus.
It works on all systems I see (linux,window,osx, Fedora35 in a VM), so it is in all likelihood a qt5/gnome/wayland issue, which I can't fix.
Unless proven that there is something off in txs here, no further investigations are preformed.
(you can try another desktop environment)

**Comment by sunderme** [comment]
assume gnome/qt issue

**Comment by Altonss** [comment]
> assume gnome/qt issue

Yes it seems to be a gnome/qt issue sadly as I encounter such issues with other qt apps. However some other qt apps work really well and have no issues at all like VLC for example. So depending on the way the app is made in qt and  then packaged, this could influence the end result. Where do you think is the best place to report this gnome/qt issue?

**Comment by sunderme** [comment]
good question, probably fedora ?

**Comment by Altonss** [comment]
I already started a thread in the Fedora forum here: https://ask.fedoraproject.org/t/bug-with-qt-software-digikam-texstudio/18362
The next step would maybe be to contact the maintainers about this ^^
