### ISSUE TITLE
[FR] Provide a way to use cursor selection in user/custom commands

### ISSUE THREAD

**Issue by fkastner** [texstudio-org/texstudio#1943]
### Describe the feature and the current behavior/state
There is currently no way to use the selected text in commands.
This would be useful to, e.g., implement a custom word count feature that counts the selected words/sentences/etc. or apply spell checking only locally.
Currently `?me)` gives the name and extension of the current file. Similarly `?s)` could give the current selection. Alternatively an extension of the special handling of `@` might be preferable (`@s)`?).

### Who will benefit with this feature?
User who use custom commands and want more control over the input (to these commands).

**Comment by sunderme** [comment]
you can probably do something with a script (macro)

**Comment by sunderme** [comment]
I would not count on it that this will be implemented soon or ever.

**Comment by fkastner** [comment]
Somehow I was completely oblivious to the power of the macro/script system until now.
With a simple macro I could easily achieve what I wanted. Thank you for the pointer!
For reference:
```javascript
%SCRIPT
var text = cursor.hasSelection()?cursor.selectedText():editor.text();
var c = text.split(/\S+/).length - 1
information("Counted "+c+" words.")
```
