### ISSUE TITLE
Sub-Menus Being Deleted

### ISSUE THREAD

**Issue by drfloren** [texstudio-org/texstudio#1944]
### Environment
- TeXstudio: 4.0.4
- Qt: 6.2.1
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
Adding submenus. In this trial, I was trying to add under the LaTeX menu.

### Actual behavior
Submenus (with menu items) are added, but on closing and opening TexStudio, menu items and submenus disappear. In this trial, the submenu and all menu items were deleted (save for one menu item, which was placed at the bottom of the LaTeX menu?).

### How to reproduce
I suppose just try making a sub-menu and making a menu item to put into it. Then close, and reopen.

**Comment by drfloren** [comment]
I've made menu-items that can stay around within the Environments sub-menu, so this seems to be a sub-menu creation thing.

**Comment by sunderme** [comment]
works on linux.
Screenshot to see what exactly you are doing ?

**Comment by sunderme** [comment]
works on windows

**Comment by sunderme** [comment]
no feedback

**Comment by drfloren** [comment]
I've been out of town and in the middle of finals.

Just finished finals, and set up texstudio on a new system (still windows
10): Just had the same issue happen. I made a submenu with my new stuff and
several elements in the submenu yesterday (with keyboard shortcuts for
each). Turning on my machine today, ALL of it is gone...

Is there a way to save my new menu items in a profile or something, so that
when it gets wiped out I can reload quickly the next day?

Thanks,

**Comment by drfloren** [comment]
A screenshot of where my menu was is given below...

[image: image.png]

**Comment by drfloren** [comment]
I just took a video of the process of creating the submenu and menu items,
closing and reopening immediately (where it works), and closing and
reopening (after checking to make sure it fully closed) where all of the
menu items were erased, save for the one of the menu items that dropped to
the bottom of the parent menu for some reason.

Should I create a new ticket, as this one has been closed?

**Comment by drfloren** [comment]
![Try 3](https://user-images.githubusercontent.com/88336500/145480843-8a7b81b3-4168-4b87-b0ac-e46fecbd90aa.gif)

**Comment by sunderme** [comment]
the issue arises when elements are added to the sub-menu a second time.
fixed. (dev build)
