### ISSUE TITLE
No dictionaries available

### ISSUE THREAD

**Issue by zoof** [texstudio-org/texstudio#1946]
No dictionaries configured even though the dictionaries show up in `c:\Program Files\texstudio\dictionaries`.  Dropdown menu for dictionary selection only shows `<none>`.

FYI on my own machines, I run Debian Bullseye and this is not an issue.

### Environment
- TeXstudio: 4.0.1 (I realize this is not the latest version but my employer does not allow me admin rights and upgrading is not straightforward.)
- Qt: 6.2.0
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
Default dictionaries installed and available for selection.

### Actual behavior
See above.

### How to reproduce
Open `texstudio`, select Options -> Configure TeXstudio -> Language Checking

**Comment by sunderme** [comment]
screenshot of the option page ?

**Comment by zoof** [comment]
Here is a screenshot of the configuration window for language checking:

![texstudio-lang-check](https://user-images.githubusercontent.com/1737483/142893039-a1d35991-33f9-4ba4-9d77-ba9697120558.png)

and one for the dictionaries folder:

![texstudio-avail-dicts](https://user-images.githubusercontent.com/1737483/142893035-ca85d031-fdc2-4c7e-b717-90260302d114.png)

**Comment by sunderme** [comment]
from the looks of it, you are not looking at the same directory.
One is `program files (x86)`, the other is `program files`

**Comment by zoof** [comment]
Ah, I see.  I'm fairly certain that `Program Files (x86)` was the default -- I never changed the dictionary folder.  Perhaps in a transition between versions, the install location moved from `Program Files (x86)` to `Program Files` but the old config file remained the same.

**Comment by sunderme** [comment]
Yes, a little while ago, txs moved to 64 bit and that means different program folder.
