### ISSUE TITLE
Configure Window has not maximize button

### ISSUE THREAD

**Issue by tmelorc** [texstudio-org/texstudio#1949]
### Environment
- TeXstudio: 4.1.0
- Qt: 5.12.8
- OS: Linux Mint 20.1
- TeX distribution: texlive 2021

### Expected behavior
Maximize the Configure Window to make all buttons visible on screen.

### Actual behavior
The Configure Window has no maximize button and so we have to move it to see the OK button in the bottom.
![Configurar TeXstudio_002](https://user-images.githubusercontent.com/15181573/142642132-47ba1e3e-80ad-435e-8871-047c99058431.png)

**Comment by sunderme** [comment]
It has on ubuntu xfce, so probably a mint issue ? (desktop env)

**Comment by sunderme** [comment]
probably implemented, but that is probably very dependent on the actual desktop environment

**Comment by tmelorc** [comment]
> 

Nice, now it works perfectly.
