### ISSUE TITLE
keyboard up and down will move the scroll, left and right give no response

### ISSUE THREAD

**Issue by zzz0906** [texstudio-org/texstudio#1952]
### Environment
- TeXstudio: TeXstudio 4.1.0 (git 4.1.0)
- Qt: Using Qt Version 6.2.1, compiled with Qt 6.2.1 R
- OS: Mac OS Monterey 12.0.01
- TeX distribution: pdflatex

### Expected behavior
After checking the keyboard mapping preference, the up, down, left, and right is set as move the cursor and shall move the curse in one space.

### Actual behavior
When I try to use up, down, left, and right to move the cursor, it gives no response. And the up and down will move the scroll.

### How to reproduce
You may install it in the new mac os.

**Comment by sunderme** [comment]
I don't have a machine to do that.
Someone else has to check.

**Comment by Ga-B** [comment]
I can confirm this bug after updating from 4.0.4 using the binaries provided in the website. Deleted the texstudio.ini file to use default settings and the bug persists.

**Comment by sunderme** [comment]
fixed in 4.1.1

**Comment by zzz0906** [comment]
@sunderme thanks! 4.1.1 works.
