### ISSUE TITLE
Resizing the sections of the symbol Panel

### ISSUE THREAD

**Issue by Abel-Github** [texstudio-org/texstudio#1953]
### Describe the feature and the current behavior/state
Please kindly add an option to resize each of the sections of the symbol Panel  for Texstudio.  Also, one should be able to close the most used area, as well as the favorites area independently of the other subsections in the symbol panel. 

This will enable users to just add all their favorite symbols to the favorite panels and  then close/or resize the most used, and the other large area that contains all the symbols depending on the user's preference.

So just as we have a **X** at the top that closes the whole symbol  panel, we should have a smaller **x** for each of the subsection **most used**,  **favorites** and **all symbols** so that the user can either close either of them independently of the other two.

Thanks in anticipation.
![image](https://user-images.githubusercontent.com/69094732/142738009-49c249f6-42bf-4f45-b271-079867ec813b.png)

### Who will benefit with this feature?
If this is not done, one will have to scroll up and down whenever you have added too many symbols/items to your favorite section of the panel region. because you are unable to resize the favorite section as it is, nor are you enabled to close the most used region (which in most cases, is not being used by users as much as the favorite section.

**Comment by sunderme** [comment]
implemented.
"Closing" works by moving the split handle up/down until the section is hidden.
