### ISSUE TITLE
Looking to Implement 

### ISSUE THREAD

**Issue by nadavsuissa** [texstudio-org/texstudio#1960]
### Any Other info

Hello, We are a group of Cs students looking to contribute to an open source project, what he had in mind was to implement an option to write scientific articles in Hebrew, our second thought was to implement a system to check the validity of mathematical functions/equations.
What we would like to know is the following - would you guys have any interest in this, at the end of the day if the implementation is at the required level, will you accept the contribution and secondly we would like to understand if these  tasks are programming focused tasks or to implement these would focus less on programming, thanks in advance

**Comment by sunderme** [comment]
Contributions are always welcome, a source for inspiration are issues marked as enhancement.
Not sure what is needed for "writing articles in Hebrew" as txs supports different input methods.
"validity of equations" may be outside the scope of a latex editor. Just keep in mind that the implemented functions should be of benefit for a larger part of txs users and once stuff is integrated into txs source code, you will lose direct control over it as everything needs to pass through PR. So some functionality might be better off as external tool/script.
