### ISSUE TITLE
Strange horizontal lines appear in the magnifying glass

### ISSUE THREAD

**Issue by WhenMelancholy** [texstudio-org/texstudio#1963]
### Environment
- TeXstudio: TeXstudio 4.1.1 (git 4.1.1)
- Qt: 使用 Qt 6.2.1，由 Qt 6.2.1 R 构建
- OS: Windows 10 21H2 19044.1348
- TeX distribution: texlive

### Expected behavior
no horizontal lines.

### Actual behavior
The background is white but there are black lines in the magnifying glass.
![image](https://user-images.githubusercontent.com/21274779/143388192-8ca2cb30-01e9-42ce-9524-b89f87645cd3.png)

### How to reproduce
Even the simplest document magnifier has problems.
![image](https://user-images.githubusercontent.com/21274779/143388456-6fa8636e-cacf-4623-91a9-7ce93abcd44a.png)

**Comment by muzimuzhi** [comment]
Quoting my https://github.com/texstudio-org/texstudio/issues/1927#issuecomment-964005296:

> duplicate of #1773
> 
> short recap: It's a Qt6 bug and is reported. Try the [Qt5 build](https://github.com/texstudio-org/texstudio/releases/tag/4.0.4) instead.
