### ISSUE TITLE
keyval highlighting not tracking braces across new lines

### ISSUE THREAD

**Issue by mbertucci47** [texstudio-org/texstudio#1965]
### Environment
- TeXstudio: 4.1.1
- Qt: 6.2.1
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
The highlighter marks the arguments of keys as incorrect if they appear on a new line. For example, the following cwl for `mypackage` results in the highlighting shown.
```\foo{keyvals}
#keyvals:\foo
key={%<stuff%>}
anotherkey=%<stuff%>
#endkeyvals
```
<img width="160" alt="keyval highlight" src="https://user-images.githubusercontent.com/61854785/143492049-2708d599-bb50-40fa-a6cb-617c4f5d6b26.png">

**Comment by sunderme** [comment]
implemented
