### ISSUE TITLE
Cannot install TeXstudio 4.1.1 on new MacBookPro

### ISSUE THREAD

**Issue by Decaon** [texstudio-org/texstudio#1971]
### Environment
New MacBookPro 16", using Mac chip, not Intel.

### Expected behavior
Expected to be able to update TexStudio by downloading and installing 4.1.1

### Actual behavior
texstudio-4.1.1-osx.dmg downloads, and app opens, but does not install. the program disappears when closed

it leaves my existing version, 3.0.1 in place

**Comment by sunderme** [comment]
txs does not offer an installer.
You can copy the txs.app to whereever you like.

**Comment by sunderme** [comment]
assume answered

**Comment by Decaon** [comment]
I appreciate the response. 

When I put the TeXstudio.app in in the applications folder, it will open, but it does not appear in Launchpad. My prior version of TexStudio did appear in launchpad.

There are obvious workarounds, but is there a way to get it into launchpad?

Thanks

**Comment by sunderme** [comment]
That is for the mac users to answer (or google)
