### ISSUE TITLE
Weird Cursor moves 

### ISSUE THREAD

**Issue by Henri-Salha** [texstudio-org/texstudio#1973]
When moving the cursor with  Ctrl-Left or Ctrl-Right, sometimes  (not always) the cursor jumps to a {curly-braced} area far removed from it (but in the same paragraphs).
Other weird movements were noticed but rarer.

### Environment
- TeXstudio: 4.1.1
- Qt: Version 6.2.1, compiled with Qt 6.2.1 R
- OS: Win 10
- TeX distribution: miktex

### Expected behavior

Using Ctrl-Left or Ctrl-Right, the cursor should always move from one word to the next before or after.
### Actual behavior
Sometimes (not always) when there is a {curly-braced} area in the paragraph it jumps directly to it, and selects the text inside the curly-braces.

### How to reproduce
Difficult to say. Erratic behavior.
![texstudiobug2](https://user-images.githubusercontent.com/73117230/143787675-a33d8472-931d-4613-8e28-29b73e5b3b95.jpg)

**Comment by Henri-Salha** [comment]
Sorry. I found my problem. If I disable the placeholder option the problem is gone.

**Comment by muzimuzhi** [comment]
> Sometimes (not always) when there is a {curly-braced} area in the paragraph it jumps directly to it, and selects the text inside the curly-braces.

This is the behavior of "Next placeholder or one word right", whose shortcut is configurable in "Configure TeXstudio -> Shortcuts -> Editor -> Basic Key Mapping".
