### ISSUE TITLE
Texstudio unexpectedly restarts Mac OS Monterey

### ISSUE THREAD

**Issue by Pika78** [texstudio-org/texstudio#1976]
### Environment
- TeXstudio: 4.0.4
- Qt: Qt version 6.2.1, complied with Qt 6.2.1 R
- OS: Mac OS Monterey 12.0.1
- TeX distribution: Texlive
### Expected behavior
No random restart of os.

### Actual behavior
Several random restarts of computer, when left unattended.
Only indicated by the message 'your computer has been restarted because of an error ' without specifying the error.
Does not happen when Texstudio not open. 

### How to reproduce
Leave the computer idle for some time (15 to 25 minutes)

Many thanks for your insight into this problem.
Kind regards

**Comment by sunderme** [comment]
txs should not be able to restart the os
Sure that txs is the culprit ?
