### ISSUE TITLE
Small bug in an edge case when restoring a session

### ISSUE THREAD

**Issue by Tehgg** [texstudio-org/texstudio#1978]
Hi,

There is a small edge case where TeXstudio doesn't behave as expected when restoring the previous session.

Suppose we have the following folder structure.

```
.
├── myfolder
│   ├── myfolder
│   │   └── mypdf.pdf
│   └── mypdf.pdf
└── mypdf.tex
```

Suppose we compile with the option `-outdir=myfolder` of `latexmk`. In the option "additional search paths" for pdfs, we thus have "myfolder" (Options > Build, tick the box "advanced options").

Suppose TeXstudio is opened with `mypdf.tex` and `myfolder/mypdf.pdf` in the previewer. If we close it, the next time we open TeXstudio, it will restore the previous session but showing the file `myfolder/myfolder/mypdf.pdf` inside of it, instead of the original `myfolder/mypdf.pdf`. For this, we also need `folder/mypdf.pdf` to be older than `myfolder/myfolder/mypdf.pdf`.

It's a lot of conditions, I don't have such a folder structure of course but I noticed it because TeXStudio was trying to look inside the nonexistent folder `myfolder/myfolder`.

The "problem" is with the following line in the file `src/texstudio.cpp`.
```
if (!s.PDFFile().isEmpty()) {
    runInternalCommand("txs:///view-pdf-internal", QFileInfo(s.PDFFile()), s.PDFEmbedded() ? "--embedded" : "--windowed");
}
```

The second parameter of this function is usually the QFileInfo of the current project (this would be `./mypdf` in our case), not the QFileInfo of the pdf file.

**Comment by sunderme** [comment]
I can't reproduce the behavior.
The files are stored relative to the ```lastSession.txss2```location ?

**Comment by Tehgg** [comment]
Yes, in the file `~/.config/texstudio/lastSession.txss2`, the path of the file is stored correctly relatively to this last file. I compiled the code without modification from github and on my machine it does what I said. It is important that the file `myfolder/mypdf.pdf` is *older* than the file `myfolder/myfolder/mypdf.pdf`, and that there is "myfolder" in the "additional search paths" option for PDFs.

But it is anyway what the code says to do. Here is a summary of what the program does:

1. When it is closed with the pdf `myfolder/mypdf.pdf` opened in the internal viewer, it stores the path of this pdf in the file `lastSession.txss2`.
2. When TeXstudio is reopened, it reads the path of this pdf and calls the function `BuildManager::findCompiledFile` with first parameter the name of the pdf and with second parameter the path to the pdf itself. (When compiling a tex file, the second parameter is the path of the tex file and not the path of the pdf.)
3. The path of the pdf `myfolder/mypdf.pdf` is then taken as the root for searching for the pdf `mypdf.pdf` in the function `FindInDirs::findAbsolute`. But since there is an "additional search path" which is `myfolder`, it then searches inside of `myfolder/myfolder` to see if it finds a more recent version of the pdf... But there shouldn't be a search for the pdf in the first place, since its location is given!

It is something very minor since it works in most cases, but the logic is a bit strange...
