### ISSUE TITLE
Dead Link(s?) to Sourceforge addresses in Github Wiki

### ISSUE THREAD

**Issue by deGravity** [texstudio-org/texstudio#198]
Links to the manual in the wiki are broken.
### Environment
Github Wiki

### Expected behavior
The [link](http://texstudio.sourceforge.net/manual/current/usermanual_en.html#SECTION33c) to the user manual on [this](https://github.com/texstudio-org/texstudio/wiki/Scripts) Wiki
page about scripts links to a Sourceforge address that doesn't exist. The page in question lives in the utilities/manual directory of this repository. If it is hosted somewhere this link should point to it.

**Comment by sunderme** [comment]
sourceforge just updated its server, works now
