### ISSUE TITLE
The blank of preview is too large

### ISSUE THREAD

**Issue by tercelxy** [texstudio-org/texstudio#1980]
### Environment
- TeXstudio: 4.1.1
- Qt: qt6
- OS: win11

The blank of preview is too large, causing the content to exceed the display range. See attached figure

![image](https://user-images.githubusercontent.com/34205978/144044384-cd9d3da1-81a9-4b75-a208-46638cbe3567.png)

**Comment by sunderme** [comment]
can you attach the test document?

**Comment by sunderme** [comment]
what is set in options/preview ?

**Comment by tercelxy** [comment]
@sunderme: My PC is surface pro, which has a high DPI display screen, in the system display setting, the scale is set to 225%, the resolution is 2880×1920. 

For the preview setting, see the attach figure
![image](https://user-images.githubusercontent.com/34205978/144188306-3ae0f092-ba52-4916-b204-cebb541e8498.png)

**Comment by sunderme** [comment]
fixed with latest commit.
pixmap gets scaled to visible width (quality is not perfect, but it is completely visible)
