### ISSUE TITLE
Adwaita Dark language selection problem

### ISSUE THREAD

**Issue by thebodzio** [texstudio-org/texstudio#1988]
### Environment
- TeXstudio: 4.1.1
- Qt: 6
- OS: Windows 10
- TeX distribution: MiKTeX

### Expected behavior
Clicking on language selection button (lower right portion of the editor window) should bring up a list with all available languages.

### Actual behavior
A picture is worth a thousand words:

![Screenshot - 1](https://user-images.githubusercontent.com/1129853/144418222-c3d3ce65-da01-4423-8a69-1021bd2c8c38.jpg)

### How to reproduce
* Choose Adwaita Dark as theme.
* Click on the language selection button.

**Comment by sunderme** [comment]
that is an adwaita bug.
As this code was just taken, it is difficult to debug, so may take a while

**Comment by thebodzio** [comment]
Just reporting the problem, not demanding an immediate action 😊

**Comment by Ledmington** [comment]
I have the same problem on my pc.
TeXstudio: 4.1.1
Qt: 6.2.1
OS: Windows 10
TeX distribution: texlive

**Comment by thebodzio** [comment]
There is a slight work-around for this, that is: reducing the selection of dictionaries to those which are really needed.

One way to do that is visiting the application installation folder and removing unnecessary dictionary files. They are usually stored (in Windows) in “C:\Program Files\texstudio\dictionaries\”. Each dictionary consists of 2 files: *.aff and *.dic and both should be removed. This solution, however, is not the most elegant one, because each reinstallation (update) will repopulate the files and the process will have to be repeated.

Much better option is to copy required dictionaries to an external folder and point TeXstudio to search for dictionaries in that folder. It can be done in application configuration windows in “Language Checking” section. The option is called “Spelling Dictionary Directories”.

Of course it would be better to be able to simply disable unwanted dictionaries (see #1989), but, as of now, it is how it is.
