### ISSUE TITLE
Tilde issue Mac OS (apple m1)

### ISSUE THREAD

**Issue by maxcharlier** [texstudio-org/texstudio#1992]
I use the tilde as an unbreakable space in some of my tex files. 
To write a tilde I use [command]+[n] and got a tilde. Then the tild is in a waiting state (highlight in yellow). To escape this state I press [esc] and i got "~~ " in place of “~".

<img width="67" alt="Capture d’écran 2021-12-03 à 10 27 19" src="https://user-images.githubusercontent.com/9266708/144579520-ac936fb4-581d-418f-bd70-3015ea22304d.png">
<img width="71" alt="Capture d’écran 2021-12-03 à 10 27 33" src="https://user-images.githubusercontent.com/9266708/144579551-12afa018-b252-4f27-8b8b-27b07d52048a.png">

### Environment

Utilise Qt version 6.2.1, compilé avec Qt 6.2.1 R
- TeXstudio: TeXstudio 4.1.1 (git 4.1.1)
- Qt: Qt version 6.2.1, compilé avec Qt 6.2.1 R
- OS: Mac Os Monterey 12.0.1, on apple M1
- TeX distribution: pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2021)
kpathsea version 6.3.3

### Expected behavior
got a tilde : "~"

### Actual behavior
got two tilde and a space : "~~ "

### How to reproduce
Open a new document, type text[tilde][escape]

**Comment by maxcharlier** [comment]
A workaround is to press space in place of escape after the tilde to quit the highlight state, but I think it could be better it this bug was fixed.

**Comment by dbitouze** [comment]
BTW, Windows users also have problems with `~` which, AFAIR, cannot be typed at all (it is necessary to copy it from elsewhere).
