### ISSUE TITLE
Allow more zoom levels in pdf viewer

### ISSUE THREAD

**Issue by samcarter** [texstudio-org/texstudio#1993]
### Describe the feature and the current behavior/state

It would be nice if one could zoom in further than 400% -- increasing the limit to something like 1000% would be really convenient. 

https://github.com/texstudio-org/texstudio/blob/e9cfcec7a8a73045882b6551d71deeb679401989/src/pdfviewer/PDFDocument.cpp#L2833

### Who will benefit with this feature?

For normal text documents that might not be necessary, but if graphics like pgf/tikz are involved, it is sometimes convenient to zoom in further to check if connections look good, if things line up or if there are any gaps. 

Just over the curse of the previous week I found myself a couple of times in situations in which I wished I could zoom in further:

- while debugging https://stackoverflow.com/a/70144790/2777074 to check if all lines connect smoothly
- debugging https://github.com/josephwright/beamer/issues/647#issuecomment-947963336 which depended on adjusting the pgf code to fractions of a bp

I normally work around this by either opening the pdf externally or using a custom version of TXS with a higher zoom level, but I think this might be useful for other users as well.

### Any Other info

I realise that this might cause performance issues, like a longer rendering time of the pdf. If this is indeed a problem, maybe make the extra zoom level optional?

**Comment by sunderme** [comment]
and the magnifier is not sufficient ?

**Comment by samcarter** [comment]
No, because the magnifier is not visible while you compile the document, that means you don't see movement of elements between two compilations. You have to switch focus from the editor to the pdf viewer and then use the mouse. You can't have it open while you tweak the code.

Also the position of the magnifier depends on your mouse and is not constant. This makes it hard to use screen guidline tools and similar to position elements.

**Comment by sunderme** [comment]
you can set screen dpi (option/internal pdf viewer/screen dpi) to higher values.
That will basically redefine what 100% magnification is, larger values means effectively larger magnification at 100% (and so at 400%) and you will run into performance issues (mainly memory).

**Comment by samcarter** [comment]
@sunderme  Oh, that's a brilliant idea! Changing the dpi totally solves my problem! Thanks!

**Comment by Atcold** [comment]
Thanks!
