### ISSUE TITLE
Suggestion of translations' revisions

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#1995]
In the graphic wizard, the following current tooltips look debatable:

1. "Caption for display next to the image" is misleading since, usually, the caption is either below or above of, but not next to, the image. Proposal: "Caption for display below or above of the image".
1. "Caption for display in the list of figures" is misleading, since this has to be used only if it is wanted to be different from the "long" (normal) caption. Proposal: "Caption to be displayed in the list of figures (if wanted different from the long caption)".

**Comment by dbitouze** [comment]
> > ```
> > 1. "Caption for display next to the image" is misleading since, usually, the caption is either below or above of, but not next to, the image. Proposal: "Caption for display below or above of the image".
> > ```
> 
> I would rather say "Caption for the image".

The point is, the "short" caption is also a caption for the image. But I would agree.

**Comment by sunderme** [comment]
do you do a pull-request ?

**Comment by dbitouze** [comment]
Will try right now.
