### ISSUE TITLE
High resolution display problem

### ISSUE THREAD

**Issue by qhx2014** [texstudio-org/texstudio#200]
### Environment
- TeXstudio: 2.12.8 
- Qt: 5.8.0 
- OS: windows 10 （17134.112） 
- TeX distribution: miktex2.9 
- Screen: LG 27UK850 4K with 150% zoom

### Expected behavior
I hope TeXstudio can add support for high resolution screens (3840x2160) to make buttons the right size and editors and PDF previews clear enough.

### Actual behavior
TeXstudio at 3840x2160 resolution, the editor and PDF browsers show a rough, granular look, while toolbar fonts are unaffected.

### How to reproduce
use 4k screen with 150% zoom, and after about 2 to 3 times' use, it will apper like this：
![image](https://user-images.githubusercontent.com/15900875/41848128-05c8d248-78af-11e8-84bc-23e77c11929d.png)
and this：
![image](https://user-images.githubusercontent.com/15900875/41848209-408375fa-78af-11e8-8bad-3c4b05ce1604.png)

**Comment by matthiashh** [comment]
I have the same issue with my 4K display on (K)Ubuntu 18.04. The toolbar, menus, etc. scale well. But both the editor and the PDF preview look pixelated.
**Environment:**
* TeXstudio 2.12.6
* Using Qt Version 5.9.5, compiled with Qt 5.9.3 R
* (K)Ubuntu 18.04

**Comment by 95A31** [comment]
Same problem here.

- TeXstudio 2.12.22
- Using Qt Version 5.15.0, compiled with Qt 5.14.0 R
- KDE 5.19
- Manjaro Linux

**Comment by sunderme** [comment]
probably fixed with newer versions
