### ISSUE TITLE
Problems with shortcut Ctrl + Shift + U (For Supraindices) and \chapter{} recognition in scrbook-style document.s.

### ISSUE THREAD

**Issue by fdiazruiz** [texstudio-org/texstudio#2003]
Hello,
First of all I thank the developers for the hard and excellent work they do to maintain and make texstudio better and better, I am a faithful lover of texstudio!
The current version was able to correct some errors, autocompletes on behalf of the packages, of the past version, however, I have a couple of doubts and for this I detail the information of my system:

### Environment
- TeXstudio: 4.1.3
- Qt: Using Qt Version 5.12.8, compiled with Qt 5.12.8 R
- OS: Linuxmint 20.2 uma
- TeX distribution: (TeX Live 2021) kpathsea version 6.3.3

### Expected behavior
- By default the shortcut for superscripts (Ctrl+Shift+U).
- The name the structure \chapter{} should be recognized in scrbook-style documents as eventually happens, for example, with book and report type documents.

### Actual behavior
- I'm not sure about the functionality that IBus fulfills here, but I have noticed that IBus (has a shortcut of this type assigned) disables the fast access for supra-indexes (Ctrl+Shift+U), it can even be a minor detail and is You can correct it by changing the shortcut, I am questioning the reason why it happens and I would like to know how to solve it, since previous versions have also manifested the same problem and I have not been able to solve it.
- On the other hand, another query arises; When I work on a document type scrbook, the structure \chapter{} is not 
autocomplete, that is, it appears as an unrecognized command, which is seen as a lack of highlighting, in bold, in the name of the chapter, as can be seen in the picture attached below:

![scrbook](https://user-images.githubusercontent.com/95192810/145247106-fb11a50d-e755-4278-b40a-d4603ec335f1.png)

I would highlight that the last flaw was not evident in previous versions.
Being attentive to a prompt response and thanking you in advance for any information that you provide me in this regard, I cordially bid you farewell, not without first wishing you success in the work you do. Kind regards!

 F. Díaz.

<!--### How to reproduce

**Comment by sunderme** [comment]
please, one bug per issue.

**Comment by sunderme** [comment]
You know that you can change shortcuts yourself ? Option/shortcuts ?

**Comment by sunderme** [comment]
missing chapter is added , see dev releases.

**Comment by fdiazruiz** [comment]
Dear Sunderme thank you for being so kind and answering my request in addition to your suggestion.

Regarding the shortcuts I preferred to remove the IBus shortcut, to maintain the originality of texstudio (Problem solved).

Regarding \chapter{} in scrbook, I don't know if I misunderstood, but I proceeded to uninstall the version I had (4.1.3) to check the developer versions (4.1.2), as you indicated above, however, when perform the installation again, I expected the current version (4.1.2) to be installed and the fault would be corrected, despite this, the version (4.1.3) was installed and the problem persists.

Best regards
F. Diaz.
