### ISSUE TITLE
TexStudio 4.1.2 Qt 6 Portable doesn't start on Windows 7

### ISSUE THREAD

**Issue by kompilainenn** [texstudio-org/texstudio#2004]
TexStudio 4.1.2 Qt 6 Portable doesn't start on Windows 7

### Environment

- TeXstudio: 4.1.2
- Qt: 6
- OS: Windows 7
- TeX distribution: texlive 2019

### Expected behavior

TexStudio 4.1.2 Qt 6 Portable starts

### Actual behavior

TexStudio 4.1.2 Qt 6 Portable doesn't start

### How to reproduce

Download TexStudio by link https://github.com/texstudio-org/texstudio/releases/download/4.1.2/texstudio-4.1.2-win-portable-qt6.zip , unzip it and try start it

**Comment by sunderme** [comment]
Win 7 is end-of-life.
Qt6 does not support win7.
You can still use txs with qt5 though.
