### ISSUE TITLE
Create Environment (Ctrl+E) placeholders can't be used simultaneously

### ISSUE THREAD

**Issue by Chaddai** [texstudio-org/texstudio#2005]
### Environment
- TeXstudio: 4.0.4 - 4.1.2
- Qt: 6
- OS: Windows 10

### Expected behavior
When pressing Ctrl+E, the following appears :

    \begin{environment-name}
      content
    \end{environment-name}

with both `environment-name` and `content` showing as placeholders.

You can then edit `environment-name`, press Ctrl+Right and goes on to edit `content`.

### Actual behavior
When you edit `environment-name`, `content` lose its status as a placeholder, you have to select and delete it manually. If you start by pressing Ctrl+Right you're correctly brought to edit the `content` placeholder but `environment-name` lose its status as a placeholder.

### How to reproduce
Press Ctrl+E and try to edit one or the other placeholder, the other should lose its placeholder status immediately.

Similar issue with typing `\begin` and auto-completing into a new environment (though the names of the placeholders are slightly different).

This does not seem to affect other multi-placeholders completions (like `\begin{minipage}`, `\frac`, etc) or macros.

**Comment by muzimuzhi** [comment]
> When you edit `environment-name`, `content` lose its status as a placeholder, you have to select and delete it manually.

Reproducible here with texstudio 4.1.2 Qt6 on macOS 11.5.2.

**Comment by sunderme** [comment]
fixed
