### ISSUE TITLE
Some argument-less macros obtained by completion not followed by a space anymore

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#2010]
### Environment
- TeXstudio: 4.1.3 (git 4.1.2-14-g1815eaec3)
- Qt: 5.15.2 D
- OS: Linux (Mageia),
- TeX distribution: TeX Live 2021

### Expected behavior
Argument-less macros obtained by completion that should be followed by a space, followed by a space.

### Actual behavior
Some argument-less macros obtained by completion not followed by a space anymore.

### How to reproduce
1. Open a document.
2. Start to type `\it` + RET
3. You get `\item` where you would expect `\item `, as it was the case in older versions of TXS.

**Comment by sunderme** [comment]
That behavior is unchanged.
You probably confuse it with ```ctrl+shift+i``` which triggers a script ?

**Comment by dbitouze** [comment]
> That behavior is unchanged.

Ah, sorry.

> You probably confuse it with `ctrl+shift+i` which triggers a script ?

Maybe. But IMHO, `\it `+ RET should be completed into `\item ` since the space after it is:

- either needed if the item content follows on the same line,
- or is harmless if the item content follows on the next line.

**Comment by sunderme** [comment]
Hmmm, actually there is a \item +space completion in the cwl and one without space in tex.cwl
fixed.

**Comment by dbitouze** [comment]
Fixed: thanks!
