### ISSUE TITLE
Add \item before every paragraph I selected when I try to apply \begin{itemize} to its all

### ISSUE THREAD

**Issue by kompilainenn** [texstudio-org/texstudio#2016]
Add \item before every paragraph I selected when I try to apply \begin{itemize} to its all

### Describe the feature and the current behavior/state
For example I have
```
text1
text2
text3
```
I select it all and select LaTeX->Lists->\begin{itemize} menu item and I get

```
\begin{itemize}
    \item text1
text2
text3
\end{itemize}
```

So I would like to see this construction instead

```
\begin{itemize}
    \item text1
    \item text2
    \item text3
\end{itemize}
```
### Who will benefit with this feature?

All TeXstudio users

### Any Other info

It needs to do the same for \begin{enumerate}

**Comment by muzimuzhi** [comment]
If the desired "before every paragraph" can be interpreted as "at every line beginnings", then a texstudio macro might do the trick.

**Comment by kompilainenn** [comment]
> If the desired "before every paragraph" can be interpreted as "at every line beginnings", then a texstudio macro might do the trick.

How?

**Comment by hair-splitter** [comment]
For example see the next macro:
[https://tex.stackexchange.com/questions/620706/quick-itemizing-when-pasting-lists-in-texstudio/620718#620718](https://tex.stackexchange.com/questions/620706/quick-itemizing-when-pasting-lists-in-texstudio/620718#620718)

**Comment by kompilainenn** [comment]
> For example see the next macro: https://tex.stackexchange.com/questions/620706/quick-itemizing-when-pasting-lists-in-texstudio/620718#620718

Excellent! But I still think it should be a default feature
