### ISSUE TITLE
TeXstudio highlights input files as not found

### ISSUE THREAD

**Issue by adcsilva** [texstudio-org/texstudio#2019]
I include some files to the main tex file with `\input{./SettingsExamsMacroPhD02.tex}`.

TeXstudio should list these files in the Structure view in black. However, they are shown in red as if these files were not available (see image).

When I click the file, TeXstudio opens the file and the red indication turns black, as usual. This behavior started to happen in the last update.

<img width="237" alt="screen01" src="https://user-images.githubusercontent.com/59922961/146046297-728fac71-8dab-4382-84e6-0cbb022abb72.png">

### Environment
- TeXstudio: 4.1.2 (git 4.1.2)
- Qt:  Qt Version 6.2.1, compiled with Qt 6.2.1 R
- OS: Windows 10 Pro, Version 20H2
- TeX distribution: miktex

### Expected behavior
input files found and shown in black.

### Actual behavior
input files shown as not found, in red.

### How to reproduce
Include an input file to the main tex file.

**Comment by sunderme** [comment]
works as expected.

**Comment by adcsilva** [comment]
> works as expected.

What is the expected behavior? Do the files have to be shown in red, as if they were not available? It is better if there were shown in black, as black is less distracting

**Comment by sunderme** [comment]
It means that I can't reproduce the issue. The files are presented in black here.

**Comment by adcsilva** [comment]
> It means that I can't reproduce the issue. The files are presented in black here.

Thanks. Is there any setup that I have to change? The files are in the same directory. The same strange behavior appears for me in all TeXstudio files when I have external files linked with `\input{filename}`. They only turn black when I click the file in the Structure view

**Comment by sunderme** [comment]
it should work without changes.

**Comment by adcsilva** [comment]
Is this a bug? The links always show as red in different TEX files.

**Comment by mapfeld** [comment]
I have red and black links in the self-compiled version 4.2.1 from this repo. All files are found though.

**Comment by adcsilva** [comment]
They had to be in black. They appeared in black in previous versions. Red should be for files not found.

**Comment by mapfeld** [comment]
Interestingly, if I reopen an old session all documents are black, while when I open the document containing links anew, they are red. Clicking on the red links opens the documents flawlessly.

**Comment by sunderme** [comment]
probably fixed
