### ISSUE TITLE
Add link to/information about the newest version that still runs on Win7

### ISSUE THREAD

**Issue by xtotdam** [texstudio-org/texstudio#2020]
### Describe the feature and the current behavior/state
Once upon a time I downloaded an up-to-date version of my favorite LaTeX editor and found out, that it cannot ruin on my work notebook. I was very sad.
Please, add any info which version is last for Win7.

### Who will benefit with this feature?
Anyone who for some reason cannot update their OS to Win10

### Any Other info
A beautiful example is Calibre - there is an explicit link to the last version for Win7 (https://calibre-ebook.com/download_windows)

**Comment by xtotdam** [comment]
My bad, there is written 2.12.0
However from my experience 3.0.0 still runs well

**Comment by sunderme** [comment]
the qt5 version should still run on win7. It is 64 bit though.
