### ISSUE TITLE
"Go to source/pdf" not working

### ISSUE THREAD

**Issue by j-chevallier** [texstudio-org/texstudio#2021]
### Environment
- TeXstudio: 4.1.2 (git 4.1.2)
- OS: macOS 11.6.1
- TeX distribution: MacTeX

### Expected behavior
_Go to source:_ By cmd+click/right-click on the pdf document (embedded pdf reader), go to the corresponding place in the LaTeX source code.

_Go to pdf:_ By cmd+click/right click on the source code, go to the corresponding place in the pdf file (embedded pdf reader).

### Actual behavior
_Go to source:_ The pdf reader goes to the next page of the document.

_Go to pdf:_ Works well in a standard document (tested on kaobook) but arrives at the wrong place in presentations (beamer)

**Comment by sunderme** [comment]
these are probably syntex issues, nothing we can do.
