### ISSUE TITLE
Completions of `width=` and `height=`

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#2022]
### Environment
- TeXstudio: 4.1.3 (git 4.1.2-28-ga768859aa)
- Qt: 5.15.2

### Description
The `graphicx.cwl` file contains the following lines:
```
width=##L
height=##L
totalheight=##L
```
Hence, in `\includegraphics[keyvals]{imagefile}`, the completions of both `width=` and `height=` are both `\linewidth` and `\textheight`.

IMO, except maybe in the case of rotated images:

- `\textheight` is a bit odd for `width`,
- `\linewidth` is a bit odd for `height` (and for `totalheight`).

**Comment by sunderme** [comment]
there seem to miss more declared length definitions.

**Comment by dbitouze** [comment]
> there seem to miss more declared length definitions.

And they shouldn't be all blindly proposed for all the lengths.

**Comment by sunderme** [comment]
txs classifies length, it does not distinguish between height and width. Assuming that the user has a basic idea what he/she is doing, they can select the correct one from a list of 4 entries.

added textwidth and made columnwidth more easily accessible. (More lengths are available under "all" tab)

**Comment by dbitouze** [comment]
> txs classifies length, it does not distinguish between height and width. Assuming that the user has a basic idea what he/she is doing, they can select the correct one from a list of 4 entries.

Why not something like:
```
width=#\linewidth,\textwidth,\columnwidth,\paperwidth
height=#\textheight,\paperheight
totalheight=#\textheight,\paperheight
```
instead of the blind:
```
width=##L
height=##L
totalheight=##L
```

**Comment by sunderme** [comment]
inflexible solution. People may want to define their own lengths ...
And there are more places where width can be set, should we go through all of them.
Again, adults can chose from four options, not worth the effort.
