### ISSUE TITLE
Magic comments `% !TeX TS-program = ` and `% !BIB TS-program = ` shouldn't be followed by a line break

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#2027]
### Environment
- TeXstudio: 4.1.3 (git 4.1.2-28-ga768859aa)
- Qt: 5.15.2

### Expected behavior
When are used:

- LaTeX → Add magic comment → Insert program as TeX comment
- LaTeX → Add magic comment → Insert bibliography tool as TeX comment

the corresponding magic comments:

- `% !TeX TS-program = `
- `% !BIB TS-program = `

shouldn't be followed by a line break.

### Actual behavior
When are used:

- LaTeX → Add magic comment → Insert program as TeX comment
- LaTeX → Add magic comment → Insert bibliography tool as TeX comment

the corresponding magic comments:

- `% !TeX TS-program = `
- `% !BIB TS-program = `

are followed by a line break.

### How to reproduce
1. <kbd>Ctrl</kbd>+<kbd>N</kbd>
2. LaTeX → Add magic comment → Insert program as TeX comment
3. LaTeX → Add magic comment → Insert bibliography tool as TeX comment

**Comment by sunderme** [comment]
I don't understand.
```
% !TeX TS-program = 
% !BIB TS-program = 
```
is somehow wrong ?

**Comment by dbitouze** [comment]
Not wrong but, when using e.g. LaTeX → Add magic comment → Insert program as TeX comment, the user ends up with:

```
% !TeX TS-program = 
|
```
where `|` stands for the cursor position. So (s)he has to press the <kbd>Del</kbd> key in order to specify the program on the same line as `% !TeX TS-program = `.

(BTW, "engine" would be more appropriate than "program", though maybe less understandable.)

**Comment by sunderme** [comment]
hence, it should be followed by a linebreak, but the cursor should be placed after `=`

**Comment by dbitouze** [comment]
> hence, it should be followed by a linebreak, but the cursor should be placed after `=`

Indeed, sorry for the confusion.
