### ISSUE TITLE
The hotkey Ctrl+C conflict with the hotkey I set for GoldenDict.

### ISSUE THREAD

**Issue by Stephen2252Ro** [texstudio-org/texstudio#2034]
### Environment
I am using TeXstudio 4.0.2 on Ubuntu 20.

### Problem
The hotkey Ctrl+C conflict with the hotkey I set for GoldenDict.
Specifically, my GoldenDict is using Ctrl+C+C to translate my words. But the key combination of Ctrl+C in TexStudio responses too quickly. It will view Ctrl+C+C as double times of Ctrl+C rather than what I want.

I can find an alternative solution. But the alternative is far from my hobbit. 

So could you provide us an option to set the response time of hotkey in the future version?

**Comment by sunderme** [comment]
I don't think that is possible. You probably need to reaasign the shortcuts.
