### ISSUE TITLE
app crash on startup - bug report

### ISSUE THREAD

**Issue by ap0305-thunder** [texstudio-org/texstudio#2035]
TeXstudio 4.1.1 (git 4.1.1)
Using Qt Version 6.2.1, compiled with Qt 6.2.1 R
win 10
miktex

backtrace file:

c++ exception (TXS-Version 4.1.1 R )
[bt] 00007ff788f0e1b0  ??? error: 487
[bt] 00000018391fd780  ??? error: 126
[bt] 0000016e89c20910  ??? error: 126

**Comment by sunderme** [comment]
see #2031
