### ISSUE TITLE
Accelerators in submenus straight away displayed

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#204]
### Environment
- TeXstudio: 2.12.10
- Qt: 5.9.4
- OS: Linux (Mageia 6)
- Desktop manager: tested with KDE and Xfce

### Expected behavior
The accelerators (characters preceeded by `&` in `linguist`) in submenus are displayed without the need for pressing <kbd>Alt</kbd>.

### Actual behavior
The accelerators (characters preceeded by `&` in `linguist`) in submenus are displayed only if <kbd>Alt</kbd> is pressed (again: the ones of menus also are displayed only if <kbd>Alt</kbd> is pressed, which admittedly is okay).

**Comment by sunderme** [comment]
this is system/qt behaviour. Nothing we want to/can meddle with.
