### ISSUE TITLE
Download button on webpage has incorrect information

### ISSUE THREAD

**Issue by billtubbs** [texstudio-org/texstudio#2040]
I just downloaded and upgraded to version 4 but then found out that:

> You have macOS 10.14.6. The application requires macOS 10.15 or later.

The download button [on the website](https://texstudio.org) is misleading, as it implies the latest version is compatible with Mac OS X 10.11 or higher.

![Screen Shot 2021-12-29 at 11 45 38](https://user-images.githubusercontent.com/7958850/147698252-5f1f3080-0417-4225-97ab-730598e955f3.png)

The information on compatible systems is shown on the website but people may not read this before pressing the download button.

>Platform | Version | Type | Size | How to install
> 10.15+ | 4.1.2 | dmg | 42.7 MB | download, and start it.Please note: Because we do not have an Apple Developer Account, OS X may complain about an unidentified developer and deny opening TXS. In that case, open the context menu on the TXS icon (Ctrl + Click) and select open.
> 10.15+ | 4.1.2 (Qt5) | dmg | 42.7 MB | download. Use this version if QT6 shows issues.
> 10.x |   | There is no release for macOS 10.x, but you can compile it from source or using homebrew. The 11+ release may work on 10.15, but check for newer version seems to lead to crash, so disable that function in the options.

**Comment by sunderme** [comment]
fixed with next release
