### ISSUE TITLE
mouse cursor is displayed abnormally in chinese brackets

### ISSUE THREAD

**Issue by Komari-Koshigaya** [texstudio-org/texstudio#2042]
![image](https://user-images.githubusercontent.com/39209375/147716664-68573443-718a-45f1-aff6-f74341fae1a0.png)

### Expected behavior
It seems mouse cursor is between brackets, but actually outside.
I get "（）你好" rather than "（你好）" when i type “你好”

### Actual behavior
（）你好

### How to reproduce
\documentclass[UTF8,a4paper,10pt]{ctexart}
\begin{document}
	（）
          You get the same error in【】
\end{document}

### Environment
- TeXstudio: 4.1.1
- Qt: qt6
- OS: win10
- TeX distribution: texlive2020

**Comment by muzimuzhi** [comment]
Duplicate of #1634? (I choose this issue, not the earlier similar ones because it had a Chinese comment describing steps.)

**Comment by Komari-Koshigaya** [comment]
It works, thx.
![image](https://user-images.githubusercontent.com/39209375/147719853-94e1b43d-236d-4ea2-b141-103b9fac384f.png)
configuration as above

**Comment by asmwarrior** [comment]
Hi, I have the same issue. When using:

texstudio-4.3.1-win-portable-qt5

I have checked the three options:

~~~~
Disable cache of character width
Disable fixed pitch mode
Disable cache of rendered lines
~~~

But when I open a `tex` file which has some Chinese characters  such as:

~~~~
Chinese braces
（）

English braces
()
~~~~

The application just crashed.

But I have an old version of texstudio-4.2.3-win-portable-qt5, I see that it can open the tex file without crash.
But the Chinese braces does not shown in the correct place, but with the two options checked on, it shows content correctly.

~~~~
Disable cache of character width
Disable fixed pitch mode
~~~

I'm not sure it is a regression. I'm using Win7. So, I can't test a much newer version.
