### ISSUE TITLE
Menu "Help → Bugs Report/Feature Request" doesn't open on the right page

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#2045]
### Environment
- TeXstudio: 4.2.0 (git 4.1.2-68-g0da984e18)
- Qt: 5.15.2
- OS: Linux Mageia 8
- TeX distribution: not relevant

### Expected behavior
Menu "Help → Bugs Report/Feature Request" should open the default browser at the page https://github.com/texstudio-org/texstudio/issues

### Actual behavior

Menu "Help → Bugs Report/Feature Request" opens the default browser at a local strange page (in my case e.g. `file:///home/bitouze/.cache/kioexec/krun/1761199_0/unnamed`).

### Additional remarks

1. A better target might be https://github.com/texstudio-org/texstudio/issues/new/choose
2. The submenu entry "Bugs Report/Feature Request" should be consistent regarding the singular vs plural:
    1. either "Bug Report/Feature Request"
    1. or "Bugs Report/Features Request"

**Comment by sunderme** [comment]
txs tries to open https://github.com/texstudio-org/texstudio/issues/
No idea, why that is not honored on your system. Nothing wrong on txs side.

**Comment by sunderme** [comment]
and I don't want to jump to `new issues` directly. Reporters should at least take a glance at current entries, to see if their issue has already been reported.
