### ISSUE TITLE
Qt6+poppler+Qt creator+texstudio

### ISSUE THREAD

**Issue by zariski63** [texstudio-org/texstudio#2051]
Hello !
I did download "texstudio-4.1.2" in order to compile it.
This time, no more errors EXCEPT this:
"Project ERROR: poppler-qt6 development package not found"
And frankly I don't see what to do; there is nothing on the net to rectify this ....
Please, help me because I don't know what to do
Thank you

**Comment by sunderme** [comment]
I would be helpful to know what OS you are actually using.
And have you followed the wiki instructions (https://github.com/texstudio-org/texstudio/wiki/Compiling)

**Comment by zariski63** [comment]
I am under windows 11. I actually looked at the followed the wiki instructions (https://github.com/texstudio-org/texstudio/wiki/Compiling) but I admit that the implementation of the explanations seems very complicated to me .

**Comment by zariski63** [comment]
OK I followed the MSYS64 instructions but the compilation fails : see below 

**ERIC@DESKTOP-7QEFHNP MINGW64 /home**

$ cd texstudio;qmake6 texstudio.pro

Info: creating stash file C:\msys64\home\texstudio\.qmake.stash

Project MESSAGE: Building with Qt 6.2.1

Project MESSAGE: Static hunspell

Project MESSAGE: Static quazip5

Project MESSAGE: Creating release version

Project MESSAGE: tests are disabled

Project MESSAGE: GIT

**WARNING**: Failure to find: win_res.o

**Comment by sunderme** [comment]
a warning is not an error/failure.
Just continue with the next step: ```make -j 8```
