### ISSUE TITLE
\chapter Not Recognized as Document Partition After Version 4.1.1

### ISSUE THREAD

**Issue by elevenby3** [texstudio-org/texstudio#2058]
### Environment
- TeXstudio: 4.1.2 and above
- Qt: 6
- OS: Windows 10
- TeX distribution: Miktex (updated 2022/01/07)

### Expected behavior
\chapter{} (in report and book classes) should be recognized as a sectioning, and should be boldfaced like the other partitioning, and should also show up in the bookmarks column on the left side of TeXstudio.

### Actual behavior
\chapter{} is treated as regular text. No bookmark shows up on the left side of TeXstudio; \section{} and lower hierarchy partitions still show up appropriately, however.

### How to reproduce
0) Have TeXstudio 4.1.2 or newer installed
1) Start up any valid document class and then begin document (no packages needed)
2) Type \chapter{} (lower hierarchy partitions such as \section{} or \subsection{} are optional)
3) Observe how no bookmark is created in the left column of TeXstudio

Footnote: I reverted to 4.1.1, and \chapter{} still functions as intended over there (checked by loading the exact same test document over there following version rollback, and it was fine). It may have something to do with whatever changes were made after 4.1.1 to resolve the fact that \chapter{} was recognized as valid in an article class in 4.1.1.

**Comment by sunderme** [comment]
Which class have you tested ?

**Comment by sunderme** [comment]
can't confirm.
Any changed settings ?

**Comment by elevenby3** [comment]
I changed to LuaLaTeX and Biber on the backend, but the rest of my changes are just shortcut keys. Not quite sure...

**Comment by muzimuzhi** [comment]
I can partially reproduce with 4.2.0 on macOS 11.5.2. When document class is `report`, `\chapter` is not recognized as sectioning command, but when it's changed to `book` the problem disappears.

**Comment by sunderme** [comment]
works fine here.
Please provide a screenshot and the result of help/check active completion files

**Comment by ap0305-thunder** [comment]
> ### Environment
> 
>     * TeXstudio: 4.1.2 and above
> 
>     * Qt: 6
> 
>     * OS: Windows 10
> 
>     * TeX distribution: Miktex (updated 2022/01/07)
> 
> 
> ### Expected behavior
> 
> \chapter{} (in report and book classes) should be recognized as a sectioning, and should be boldfaced like the other partitioning, and should also show up in the bookmarks column on the left side of TeXstudio.
> ### Actual behavior
> 
> \chapter{} is treated as regular text. No bookmark shows up on the left side of TeXstudio; \section{} and lower hierarchy partitions still show up appropriately, however.
> ### How to reproduce
> 
>     0. Have TeXstudio 4.1.2 or newer installed
> 
>     1. Start up any valid document class and then begin document (no packages needed)
> 
>     2. Type \chapter{} (lower hierarchy partitions such as \section{} or \subsection{} are optional)
> 
>     3. Observe how no bookmark is created in the left column of TeXstudio
> 
> 
> Footnote: I reverted to 4.1.1, and \chapter{} still functions as intended over there (checked by loading the exact same test document over there following version rollback, and it was fine). It may have something to do with whatever changes were made after 4.1.1 to resolve the fact that \chapter{} was recognized as valid in an article class in 4.1.1.

I have exactly the same problem, class memoir.
Patched adding
\chapter{title}#L1
\chapter*{title}#L1
to my cwl

**Comment by mapfeld** [comment]
I just tested it with version 4.2.1 from this repo. My memoir document opens with a \chapter*, the same problem persists, though the cwl contains
\chapter{title}#L1, but
\chapter*{title}#*

Changing the line to end with #L1 solved the problem on first sight, but I had to open the included documents bottom to top, otherwise something weird happened. I will have to look into it and open a separate bug report if necessary.

**Comment by jacob-navia** [comment]
I can confirm this bug with the version downloaded yesterday
TeXstudio 4.2.0 (git 4.2.0)
Utilise Qt version 6.2.2, compilé avec Qt 6.2.2 R
Machine: Mac mini M1 with 16GB RAM

**Comment by mapfeld** [comment]
@sunderme May you be using Windows?

**Comment by sunderme** [comment]
still works here. 
Still need a screenshot and result from help/check active completion files

**Comment by mapfeld** [comment]
**Test file:**
![Bildschirmfoto vom 2022-01-20 14-33-26](https://user-images.githubusercontent.com/67143206/150348934-e365166f-2078-4870-bbf2-26b11b862514.png)

**Version 4.1.2:**
![Bildschirmfoto vom 2022-01-20 14-33-49](https://user-images.githubusercontent.com/67143206/150348980-a3b40110-9fb7-40e1-b717-adc105e04ca1.png)

**GIT version** with modified cwl:
![Bildschirmfoto vom 2022-01-20 14-33-10](https://user-images.githubusercontent.com/67143206/150349008-752d1067-9ae0-40ad-82c9-3f1e1accd7e8.png)

Modification in cwl:
```
\chapter*{title}#L1
...
\chapter{title}#L1
```

**Comment by sunderme** [comment]
the latest git should work with memoir without any changes.

**Comment by mapfeld** [comment]
Can confirm that.

**Comment by mapfeld** [comment]
> still works here. Still need a screenshot and result from help/check active completion files

Excuse my ignorance, I totally misunderstood that.

**Comment by jacob-navia** [comment]
Sorry, I am new here. 
How do you download "the latest git" ? 
Thanks

**Comment by nik312123** [comment]
@jacob-navia Install homebrew here: https://brew.sh/. (The instruction to install it is near the top.)

Then, execute `brew update && brew install git` in the Terminal application (located in `/System/Applications/Utilities/Terminal.app`).

**Comment by ap0305-thunder** [comment]
> works fine here. Please provide a screenshot and the result of help/check active completion files

win10
git 4.2.0

![Image](https://user-images.githubusercontent.com/59927136/150484957-11bfa851-160b-46f5-aea4-0b62757b43dc.jpg)

[cwl.zip](https://github.com/texstudio-org/texstudio/files/7911198/cwl.zip)

**Comment by sunderme** [comment]
> Sorry, I am new here. How do you download "the latest git" ? Thanks

you can also just download the dev builds: https://github.com/texstudio-org/texstudio/actions/workflows/cd.yml

**Comment by sunderme** [comment]
the memoir issue is fixed.
The original reporter claims that there is an issue with the classes report/book which I can not reproduce.
So, for that I need the screenshot and active completion files list.

**Comment by jacob-navia** [comment]
OK, downloaded the software with git, downloaded and installed QT with brew. First pass failed because I didn't have the Poppler libraries, built without the pdf viewer and it worked. Then, downloaded the Poppler libraries and recompiled.
There is "make clean", so I just erased all object files in .obj. (Takes a while to figure out that all .o files are hidden!. What's the point of hiding them?)
Then, compilation crashed with the following error:
.moc/moc_scriptengine.cpp
.moc/moc_scriptengine.cpp:235:22: error: no member named 'crash_assert' in 'scriptengine'
        case 18: _t->crash_assert(); break;
                 ~~  ^
1 error generated.
I resolved that by doing this:
 #if 0
236         case 18: _t->crash_assert(); break;
237         case 19: _t->crash_sigsegv(); break;
238         case 20: _t->crash_sigfpe(); break;
239         case 21: _t->crash_stack(); break;
240         case 22: _t->crash_loop(); break;
241         case 23: _t->crash_throw(); break;
242 #endif
and compilation proceeded, and (wow!) the bug is gone.  Of course I do not think that's a good solution but
the generated executable seems to work OK...

jacob

**Comment by sunderme** [comment]
no feedback for the original issue
memoir issue is fixed.

**Comment by elevenby3** [comment]
I left this issue for a bit by rolling back to 4.1.1. After the 4.2.1 update, checked and saw that it is now interaction between the newer versions of TeXstudio and the extreport/extbook document class. The issue I was previously having with the standard report/book class seem to have been resolved. Attached examples of report vs extreport screenshots and cwls.
[TeXstudio_Extreport-cwl.txt](https://github.com/texstudio-org/texstudio/files/7973190/TeXstudio_Extreport-cwl.txt)
![TeXstudio_Report](https://user-images.githubusercontent.com/97493589/151851125-c3878887-0a40-4281-ac63-590e94458a0b.png)
[TeXstudio_Report-cwl.txt](https://github.com/texstudio-org/texstudio/files/7973192/TeXstudio_Report-cwl.txt)
![TeXstudio_Extreport](https://user-images.githubusercontent.com/97493589/151851128-68d104bc-7acb-42d8-8e80-4ee2cfbccbbb.png)

**Comment by sunderme** [comment]
there is no txs support for extreport, maybe @mbertucci47 wants to add it ?
