### ISSUE TITLE
Zoom in the internal pdf viewer is not working properly

### ISSUE THREAD

**Issue by ShuvroChowdhury** [texstudio-org/texstudio#2059]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution:

**Comment by sunderme** [comment]
hmmm, a bit under-reported
duplicate to this #1773 ?

**Comment by ShuvroChowdhury** [comment]
Yes, I found out that just later.

Thanks!


Sincerely,
*Shuvro Chowdhury*






*Graduate Student Purdue University, USAandAssistant ProfessorDepartment of
Electrical and Electronic EngineeringBangladesh University of Engineering
and TechnologyDhaka-1205, Bangladesh.*
*Cell:* +1-765-775-8599
*Website:* http://teacher.buet.ac.bd/schowdhury
