### ISSUE TITLE
Enhancing grammer checking by using textidote

### ISSUE THREAD

**Issue by SouKot** [texstudio-org/texstudio#206]
Hi,
Is it possible to use  [textidote](https://github.com/sylvainhalle/textidote) for grammar checking? It has the ability to call **Language Tool**  and as far as I can understand, it can also ignore words which are manually added in dictionary ( so no squiggly lines under them) .  
I am sorry if I haven't followed standard procedures( if there is any) for opening issues. This is the first time I have done this. I love TXS and would love to see it incorporating best available tools.

**Comment by sunderme** [comment]
from what I have read, textidote just does the same as txs as it uses LanguageTool as checking engine.
You know, that you can activate grammar checking in txs ? (see manual)
