### ISSUE TITLE
Possible performance regression in 4.2.0 when using autocompletion with environments

### ISSUE THREAD

**Issue by adelon** [texstudio-org/texstudio#2063]
### Environment

- TeXstudio 4.2.0
- Qt Version 6.2.2 (also tested with the Qt Version 5.15.2)
- macOS Catalina 10.15.7
- TeX 3.14159265 (TeX Live 2020) 

### Issue

I recently updated from 3.1.2 to 4.2.0 and I think I'm encountering a small performance regression. When using autocompletion for environments, initially only the first occurrence of the environment name is selected, unless I pause my typing for over 1 second. Previous versions (3.1.2, 4.0.0, 4.1.0, and 4.1.2) do not exhibit the issue.

### Example and additional details

I'd expect the input sequence `\beg<ENTER>theorem` (regardless of typing speed) to result in

```tex
\begin{theorem}
    content...
\end{theorem}
```

but when typed without interruption it results in

```tex
\begin{theorem}
    content...
\end{*environment-name*}
```

instead. Also, if I wait only a bit longer after `<ENTER>`, the second occurrence of `*environment-name*` becomes visually highlighted, but is still not selected properly and continuing to type only results in the first occurrence of `*environment-name*` being replaced.

**Comment by sunderme** [comment]
Please try https://github.com/texstudio-org/texstudio/releases/tag/4.2.1beta1

**Comment by adelon** [comment]
Works great again, thank you so much for the quick fix and the fast beta release!

**Comment by David-Eisenhauer** [comment]
> Please try https://github.com/texstudio-org/texstudio/releases/tag/4.2.1beta1

Can you please create an .deb version for linux user?
