### ISSUE TITLE
Autocompletion with command defined with \NewDocumentCommand

### ISSUE THREAD

**Issue by AntoineLatex** [texstudio-org/texstudio#2066]
Since october 2020, creating new command is possible (and advisable, in replacement of \newcommand) with \NewDocumentCommand, without necessity to load the xparse package.

Using this syntax produce two differents behaviours for the autocompletion, depending on the location of the definition.

For example with the following definition : \NewDocumentCommand{\foo}{m}{def with #1} 

1-If the definition is in a style file mycommands.sty and a correct use of profiles file (texstudio/completion/user) all is ok: the completion propose me "\foo{}"  

2- If the definition of \foo is in the preamble of the current myjob.tex, the autocompletion is not as expected, as described below.

### Environment
- TeXstudio: 4.2.0
- Qt:  6.2.1
- OS: Windows(11)
- TeX distribution:  texlive

### Expected behavior

The completion should propose "\foo{}"
### Actual behavior
the completion give me just "\foo" whithout braces.

### How to reproduce
The behavior is the same with the article, report and book classes. 
Texengine= pdflatex

**Comment by sunderme** [comment]
implemented with 051fc9b34c423748a6080a9dd8566c1b9053e5d4
