### ISSUE TITLE
\end environment name not populating when typing it in \begin in macOS

### ISSUE THREAD

**Issue by nik312123** [texstudio-org/texstudio#2067]
### Environment
- TeXstudio: 4.2.0
- Qt: 6.2.2, compiled with Qt 6.2.2 R
- OS: macOS 12.1
- TeX distribution: texlive (as installed by MacTeX)

### Expected behavior
When I type the name of an environment into the result of `\begin{*environment-name*}` (as autocompleted), the environment name should also be changed to the same value that I am in the process of typing in `\end{*environment-name*}` as well.

### Actual behavior
The text in `\end{...}` still remains as `*environment-name*` without changing.

### How to reproduce
Autocomplete `\begin{...}` to get the following:

```latex
\begin{*environment-name*}
    content...
\end{*environment-name*}
```

Then, immediately begin typing the environment name. `*environment-name*` in `\begin{...}` will be replaced, but `*environment-name*` in `\end{...}` will not change at all.

Notes:
- This issue did not occur in TeXstudio 4.1.2 for me, so I believe it was caused by code changes in between the releases of 4.1.2 and 4.2.0.
- This issue does not occur after the environment name is manually added to `\end{...}`. Then, things work as expected when selecting the environment name in `\begin{...}` and typing. It only fails initially when typing it after the autocompletion occurs.

**Comment by marvlg** [comment]
The same problem occurs with Windows 10 and MikTeX. Therefore it is not an os related issue.

**Comment by sunderme** [comment]
duplicate to #2063
