### ISSUE TITLE
Release Request: Ubuntu 18.04 QT4

### ISSUE THREAD

**Issue by adinriv** [texstudio-org/texstudio#207]
### Environment
- TeXstudio:  2.12.8
- Qt:  4
- OS:  Ubuntu 18.04
- TeX distribution:  TeXLive

### Request

Can you create a release for QT4 for Ubuntu 18.04?

The annoying bug of QT5 regarding shortcuts makes it a daunting task to work with.

**Comment by sunderme** [comment]
apparently poppler-qt4 is not offered any more, so we can't offer txs with qt4.
