### ISSUE TITLE
Cannot import (de_frami) dictionary

### ISSUE THREAD

**Issue by baloe** [texstudio-org/texstudio#2074]
The import of dictionaries is broken:

Options → Configure Texstudio → Language Checking → Import Dictionary ... 

Choose `dict-de-de-frami-2017-01-12.oxt` downloaded from [here](https://extensions.libreoffice.org/en/extensions/show/german-de-de-frami-dictionaries).

### Environment
- TeXstudio: 4.2.0
- OS: Ubuntu 18.04

### Expected behavior

The dictionary is imported.

### Actual behavior

A warning pops up stating that the file did not contain a hunspell dictionary. 
After confirming that I do still want to import the dictionary, it does end up in  
  `~/.config/texstudio/dictionaries/dict-de-de-frami-2017-01-12.oxt/`,
but the language does not show up in the language selector.

The following manual actions are then needed to make the dictionary available:
```
cd ~/.config/texstudio/dictionaries/dict-de-de-frami-2017-01-12.oxt/
mv de_DE_frami/* .
mv thes_de_DE_v2/* .
mv hyph_de_DE/* .
```

**Comment by sunderme** [comment]
any particular reason not to use ubuntu package hunspell-de-de-frami which you can then find in "/usr/share/hunspell/" ?

**Comment by baloe** [comment]
Yes: I did not know any better and simply did what the texstudio configuration window asked me to do.  
I must confess that the conclusion "Spell checking dictionaries: /usr/share/hunspell;[txs-settings-dir]/dictionaries" → `apt install hunspell-de-de-frami` did not occur to me for some reason, although it is rather obvious.
