### ISSUE TITLE
auto-complete of \begin and \end disabled on latest update.

### ISSUE THREAD

**Issue by Stewart-Reid** [texstudio-org/texstudio#2077]
### Environment
- TeXstudio: 4.2.0
- OS: Ubuntu 20.04
- TeX distribution:  texlive

### Expected behavior
When you fill parentheses of a \begin{...} it also copy/completes the \end{...} parentheses

### Actual behavior
only the begin parentheses is filled. I checked configure/completion to find if a setting was un-checked but could not see anything unordinary.

**Comment by sunderme** [comment]
duplicate #2063

**Comment by sunderme** [comment]
Please try https://github.com/texstudio-org/texstudio/releases/tag/4.2.1beta1

**Comment by Stewart-Reid** [comment]
.AppImage works. Thanks.
