### ISSUE TITLE
in ubuntu 18.04, the texstudio can not auto-completion

### ISSUE THREAD

**Issue by yoczhang** [texstudio-org/texstudio#208]
Hello, 
in my ubuntu 18.04, the texstudio can not auto-completion, I have created a new mycwl.cwl to test, the texstudio may detected mycwl.cwl file, but it still can not auto-completion.

- TeXstudio: xUbuntu 18.04 | amd64 | 2.12.8, QT 5
- OS: ubuntu 18.04
- TeX distribution: texlive 2018

**Comment by sunderme** [comment]
how do you know, that the cwl file is detected?
please attach the cwl file.

**Comment by yoczhang** [comment]
@sunderme  Thank you,
I create the mycwl.cwl file, there is just one test command: \alternative{label}#r in this file.
Then I put mycwl.cwl file into ~/.config/texstudio/completion/user, 
and in my texstudio -> Options -> Configure Texstudion -> Completion -> Permanently active completion files: I can find mycwl.cwl. 
However, it doesn't work.

**Comment by sunderme** [comment]
works fine here.
You have looked into the "all" tab in the completer ?

**Comment by yoczhang** [comment]
yeah, all commands do not have an auto-completion prompt, the TAB key does not work, and commands such as \newcommand*{dnorm}[1]{\lVert#1\rVert} also do not have an auto-completion prompt.

**Comment by sunderme** [comment]
well, for starters, the command needs to be: `\newcommand*{dnorm}[1]{\lVert#1\rVert}`

**Comment by yoczhang** [comment]
I've corrected it, but the problem is that in following pictures, the white background is Texstudio 2018 in my laptop ubuntu 18.04, and the black background is Texstudio 2017 in my desktop ubuntu 14.04. You can see that there is NO auto-completion prompt in the Texstudio 2018, I do not know why.
![selection_001](https://user-images.githubusercontent.com/12275879/42224584-0af23264-7f0d-11e8-9b3f-bd022b6eba26.png)
![selection_034](https://user-images.githubusercontent.com/12275879/42224593-14e14fc6-7f0d-11e8-986c-0d1f86aedcc4.png)

**Comment by thatlittleboy** [comment]
You can try manually activating/opening the completion prompt via the Ctrl+Space keyboard shortcut?

**Comment by yoczhang** [comment]
doesn't work.  =_=

**Comment by yoczhang** [comment]
OK, got it! Thank you very much.
But I still wondering that is there any to get the auto-completion prompt? It is a little tedious to manually activate the completion prompt when using every one command.

**Comment by sunderme** [comment]
have you turned off auto-start of completer , probably in options/completer/…
