### ISSUE TITLE
Eliminate TeX Live dependency for those of us using MiKTeX on Linux

### ISSUE THREAD

**Issue by andrewdbate** [texstudio-org/texstudio#2083]
### Describe the feature and the current behavior/state

The TeXstudio deb package currently depends on the `texlive-latex-base`, `texlive-latex-extra`, `texlive-latex-recommended`, and `texlive-base` packages.

I do not wish to install TeX Live on my system because I prefer to use MiKTeX (because it often has more up-to-date packages, at least for the ones I use).

The workaround for me is to use the AppImage instead of the Debian package. This does not require TeX Live to be installed.

However, I would prefer to use the Ubuntu PPA and install TeXstudio with `apt install` as usual so that I can keep my system up-to-date with `apt update && apt upgrade`.

### Who will benefit with this feature?

Users who wish to use MiKTeX instead of TeX Live on Linux.

### Any Other info

TeX Studio currently checks whether LaTeX is on the path at startup. If the required programs are not on the path, then a warning is shown to the user. This happens if you download and run the AppImage on a fresh install of Ubuntu before you have installed MiKTeX or TeX Live.

Does TeXstudio really require these TeX Live packages to be installed? Would it not be sufficient to rely on this existing warning message to prompt the user to install the LaTeX distribution of their choosing?

Perhaps it is not as easy as just removing the dependency in the Debian packaging, but it would be very handy to be able to easily install TeXstudio without the requirement to install TeX Live.

Many thanks!

**Comment by sunderme** [comment]
as far as I see it, texlive is recommended in the deb but does not dependent on it.

**Comment by andrewdbate** [comment]
Perhaps I am doing something wrong... Here's what I did: I first added the Ubuntu PPA by running:
```
$ sudo add-apt-repository ppa:sunderme/texstudio
$ sudo apt update
```
Then when I attempt to `apt install` the `texstudio` package I get the following:
```
$ sudo apt install texstudio         
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  dvipng dvisvgm fonts-hack fonts-lato fonts-lmodern fonts-texgyre libapache-pom-java libcommons-logging-java libcommons-parent-java libfontbox-java libkpathsea6 libpdfbox-java libpoppler-qt5-1 libptexenc1
  libqtermwidget5-0 libruby2.7 libsynctex2 libtcl8.6 libteckit0 libtexlua53 libtexluajit2 libtk8.6 libutf8proc2 lmodern preview-latex-style qtermwidget5-data rake ruby ruby-minitest ruby-net-telnet
  ruby-power-assert ruby-test-unit ruby-xmlrpc ruby2.7 rubygems-integration t1utils tcl tcl8.6 tex-common tex-gyre texlive-base texlive-binaries texlive-fonts-recommended texlive-latex-base
  texlive-latex-extra texlive-latex-recommended texlive-pictures texlive-plain-generic tipa tk tk8.6
Suggested packages:
  libavalon-framework-java libcommons-logging-java-doc libexcalibur-logkit-java liblog4j1.2-java ri ruby-dev bundler tcl-tclreadline debhelper perl-tk xpdf | pdf-viewer xzdec texlive-fonts-recommended-doc
  texlive-latex-base-doc python3-pygments icc-profiles libfile-which-perl libspreadsheet-parseexcel-perl texlive-latex-extra-doc texlive-latex-recommended-doc texlive-luatex texlive-pstricks dot2tex prerex
  ruby-tcltk | libtcltk-ruby texlive-pictures-doc vprerex default-jre-headless
Recommended packages:
  latex-beamer
The following NEW packages will be installed
  dvipng dvisvgm fonts-hack fonts-lato fonts-lmodern fonts-texgyre libapache-pom-java libcommons-logging-java libcommons-parent-java libfontbox-java libkpathsea6 libpdfbox-java libpoppler-qt5-1 libptexenc1
  libqtermwidget5-0 libruby2.7 libsynctex2 libtcl8.6 libteckit0 libtexlua53 libtexluajit2 libtk8.6 libutf8proc2 lmodern preview-latex-style qtermwidget5-data rake ruby ruby-minitest ruby-net-telnet
  ruby-power-assert ruby-test-unit ruby-xmlrpc ruby2.7 rubygems-integration t1utils tcl tcl8.6 tex-common tex-gyre texlive-base texlive-binaries texlive-fonts-recommended texlive-latex-base
  texlive-latex-extra texlive-latex-recommended texlive-pictures texlive-plain-generic texstudio tipa tk tk8.6
0 to upgrade, 52 to newly install, 0 to remove and 3 not to upgrade.
Need to get 163 MB/164 MB of archives.
After this operation, 567 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
```
So it will install the TeX Live packages.

I'm not sure why though because, as you rightly point out, in the Debian control file [here](https://github.com/texstudio-org/texstudio/blob/master/debian/control) it says that the TeX Live packages are recommended not required.

**Comment by sunderme** [comment]
Google says that apt has an option --no-install-recommends ...

**Comment by andrewdbate** [comment]
Ah... I didn't know about that option because I have never had a need to use it before now.

Using the `--no-install-recommends` it works as desired:
```
$ sudo apt --no-install-recommends install texstudio
[sudo] password for andrew:             
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libpoppler-qt5-1 libqtermwidget5-0 libutf8proc2 qtermwidget5-data
Recommended packages:
  fonts-hack texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-base latex-beamer dvipng
The following NEW packages will be installed
  libpoppler-qt5-1 libqtermwidget5-0 libutf8proc2 qtermwidget5-data texstudio
0 to upgrade, 5 to newly install, 0 to remove and 3 not to upgrade.
Need to get 20.7 MB/20.9 MB of archives.
After this operation, 107 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

I just assumed that the default behaviour would be to not install anything more than required.

As a side note, Texmaker does not recommend the TeX Live packages, so running `apt install texmaker` (without the `--no-install-recommends`) is sufficient.

Perhaps a note could be added to the documentation / website to recommend to users of MiKTeX that they should install TeXstudio with `apt install --no-install-recommends texstudio`.

Many thanks.
