### ISSUE TITLE
Keyboard sometimes doesn't work on MacOS

### ISSUE THREAD

**Issue by NXDinh** [texstudio-org/texstudio#2085]
### Environment
- TeXstudio: 4.2
- Qt: 
- OS: MacOS 12.2
- TeX distribution: MikTex

**Comment by sunderme** [comment]
not sure how that is supposed to be solved.

**Comment by sunderme** [comment]
without any detailed information when that happens, there is really nothing I can do.

**Comment by sunderme** [comment]
actually there is and it was working.
#1896 which was fixed.
