### ISSUE TITLE
Automatic highlighting/selection of begin and end arguments does not work anymore.

### ISSUE THREAD

**Issue by jonasallgeier** [texstudio-org/texstudio#2087]
Recently, TeXstudio does not highlight/select both of the begin and end arguments whenever I start a new environment block. Here is a video to explain what I mean: 

https://user-images.githubusercontent.com/38286588/151328211-a5257147-ded1-4977-be4a-f70b2e6c089f.mp4

I searched quite a lot to figure out if this is just a misconfigured setting or a real bug, but I could not find anything. Any help/hint would be appreciated.

I am running "TeXstudio 4.2.0 (git n/a)" on Ubuntu 20.04.

**Comment by sunderme** [comment]
Duplicate #2063
