### ISSUE TITLE
No more picture environment syntax highlighting for other picture-environments

### ISSUE THREAD

**Issue by the-science-guy** [texstudio-org/texstudio#2088]
Ever since updating from TeXstudio verstion 4.1.1 to 4.2.0 and later the picture syntax highlighting of tikzpictures and other similar picture environments has disappeared, except for only "picture".

### Environment
- TeXstudio: 4.2.1
- Qt: Version 5.15.2
- OS: Arch Linux
- TeX distribution: texlive

### Expected behavior

-> orange syntax highlighting of picture environment
![old](https://user-images.githubusercontent.com/98602834/151579815-0035bdff-5eed-4a34-915d-243e50fca143.png)
v. 4.1.1

### Actual behavior

-> **NO** orange syntax highlighting of picture environments except only "picture"

![current](https://user-images.githubusercontent.com/98602834/151579838-d111d1ce-09e1-4326-b6ae-30a8f6bdb05f.png)
v. 4.2.0 & v. 4.2.1

### How to reproduce
-Use Version 4.2.0 or later of TeXstudio (be it on Linux or Windows)
-Use the package tikz
\begin{tikzpicture}
-> no orange syntax highlighting
\end{tikzpicture}

**Comment by sunderme** [comment]
that was changed with bf9ab7a0 
@muzimuzhi any comments ?

**Comment by the-science-guy** [comment]
> that was changed with [bf9ab7a](https://github.com/texstudio-org/texstudio/commit/bf9ab7a0967cc1422f124c2664cb479e88caac7f) @muzimuzhi any comments ?

Is there any way for me to turn it on again and revert this change?

**Comment by sunderme** [comment]
generate a line ```\begin{tikzpicture}[options%keyvals]#\picture``` in a new cwl which need to be loaded.

**Comment by muzimuzhi** [comment]
> that was changed with [bf9ab7a](https://github.com/texstudio-org/texstudio/commit/bf9ab7a0967cc1422f124c2664cb479e88caac7f) @muzimuzhi any comments ?

@sunderme Will adding back `\begin{tikzpicture}[options%keyvals]#\picture` make `tikzpicture` env accept commands that are only valid in `picture` env? If not then just do it. If so then perhaps `tikzpicture` and `pspicture(*)` can be registered like `picture` env in (if I guess right)
https://github.com/texstudio-org/texstudio/blob/15ed5bd1e3bcdbb5807b3257a35c3b8599208597/src/latexdocument.cpp#L3201-L3213

**Comment by sunderme** [comment]
I have defined a pseudo env called "pictureHighlight" which declares an environment to be highlighted like picture env.
