### ISSUE TITLE
Hitting CTRL + Shift + i, with text selected, prepends \item before each selected line

### ISSUE THREAD

**Issue by bogger33** [texstudio-org/texstudio#2091]
### Describe the feature and the current behavior/state
Currently you can hit CTRL + Shift + I as a shortcut for generating the text "\item", useful for quickly making enumrate/itemize lists. I suggest that if this combination is pressed with text currently selected, it will prepend \item before each of the selected lines. That way you can write out your list, select it, and then just hit ctrl + shift + i to bring it into latex-appropriate format. 

### Who will benefit with this feature?

it will allow generating lists more quickly from text pasted from other word processors, or to just skip the latex part of the list while you're editing it

### Any Other info

I'd be willing to take a shot at implementing this, but I wanted to see if there is interest first

**Comment by muzimuzhi** [comment]
Some info: Commit https://github.com/texstudio-org/texstudio/commit/0da984e18f265456ac91fd6067c1e830cb78dda1 implemented what you want for "LaTeX -> List Environments -> \begin{itemize}" and "\begin{enumerate}".

**Comment by sunderme** [comment]
just out of curiosity, are you working on an PR ?

**Comment by bogger33** [comment]
Sorry I had misunderstood the previous message, I thought this was implemented already. I have not started the PR yet, but I'm still interested in doing it.
