### ISSUE TITLE
TeXstudio crashes when typing before \include{a}\include{b}

### ISSUE THREAD

**Issue by Luis-A-Acuna** [texstudio-org/texstudio#2093]
### Environment
- TeXstudio:  4.2.1
- Qt:  6.2.1
- OS:  Windows 10
- TeX distribution:  texlive 2018

### Expected behavior
When typing on a line with text, existing text should just be pushed to the right.

### Actual behavior
The program crashes.

### How to reproduce
Simple!
1. Create a line with the text "\include{a}\include{b}" (without the quotes).
2. Place cursor at beginning of that line and start typing "\whatever" (without the quotes). Actually, just the backlash followed by any letters.
3. After a few letters (two, three, five) the program crashes.

In step 1 it must be exactly that. One single \include doesn't work. Neither do \includ or \includE.
[texstudio_backtrace1.txt](https://github.com/texstudio-org/texstudio/files/7966738/texstudio_backtrace1.txt)

**Comment by muzimuzhi** [comment]
I can reproduce it with 6.2.0 on macOS 11.5.2.

At first time, it triggered when I want to delete the whole line `\whatever\include{regression-test}\include{regression-test}`. Since the second time it behaves just like you described.
[macos_report_txs_gh2093.txt](https://github.com/texstudio-org/texstudio/files/7966768/macos_report_txs_gh2093.txt)

**Comment by foreachthing** [comment]
Almost the same with Windows 11, TeXstudio 4.2.1 (git 4.2.1), Qt 6.2.1 and miktex:
```
unknown at 7ff680f3b971 (TXS-Version 4.2.1 R )
[bt] 00007ff68109f720  ??? error: 487
[bt] 00000042c0dfa540  ??? error: 126
[bt] 000002067def4e90  ??? error: 126
```

**Comment by sunderme** [comment]
strange, I see crash only when typing "\" before the ```\include{a}\include{b}```

Do you see the crash with txs qt5 as well ?

**Comment by foreachthing** [comment]
> Do you see the crash with txs qt5 as well ?

I don't. Works for me with QT5.

**Comment by Luis-A-Acuna** [comment]
> can you try the current dev build (https://github.com/texstudio-org/texstudio/actions/runs/1769621158)

Hello, sunderme. I tried the dev build you linked to, and there was no crash.
It worked fine!
