### ISSUE TITLE
Biber refuses to compile in texstudio but works in terminal

### ISSUE THREAD

**Issue by jjayez** [texstudio-org/texstudio#2096]
### Environment
- TeXstudio: 4.2.1
- Qt: 
- OS:  Linux (Ubuntu)
- TeX distribution:  texlive

### Description
 After an update of Texstudio and texlive (2021) I see the following error description: "Usage: biber [options] file[.bcf] biber [options] --tool <datasource> Creates "file.bbl" using control file "file.bcf" (".bcf" extension is optional). Normally use with biblatex requires no options as they are all set in biblatex and passed via the ".bcf" file In "tool" mode (see B<--tool> option), takes a datasource (defaults to "bibtex" datasource) and outputs a copy of the datasource with any command-line or config file options applied. Please run "biber --help" for option details" This is totally cryptic to me. There is absolutely no problem with xelatex filename;biber filename;biber filename;xelatex filename in a terminal

**Comment by muzimuzhi** [comment]
That info normally means `biber` is called with wrong option or argument. Have you changed the setting for Biber command? Or can you provide an example? I see no problems with one of my local files using biber.
![image](https://user-images.githubusercontent.com/6376638/152091018-22b41a50-f46b-4a81-907d-705c6044d23e.png)

**Comment by jjayez** [comment]
Thank you for answering. I can't detect any particular problem with the call. What I have:
![image](https://user-images.githubusercontent.com/72789305/152135533-aa0121a9-43da-403c-ba38-14c1021520fc.png)


My .bib file is in biblatex format and my declaration is standard:
\usepackage[style=authoryear,sorting=nyt,backend=biber]{biblatex}
\addbibresource{filename.bib}

I also tried with pdflatex instead of xelatex as the default engine. No change (as expected).

**Comment by muzimuzhi** [comment]
Why closed? It seems not resolved yet.

**Comment by jjayez** [comment]
Sorry, a mistake

**Comment by muzimuzhi** [comment]
After clicking "Tools - Commands - Biber", what do you see in the "Messages" panel? For example I get
![image](https://user-images.githubusercontent.com/6376638/152202041-2c05fdc6-ba10-4134-8353-9a6a76f6998a.png)
followed by normal biber stdout.

**Comment by jjayez** [comment]
I see
Process started: biber "Semantics_Crash_Course"
and later on
INFO - Looking for bibtex format file 'Semantics_Crash_Course.bib' for section 0
This line does not make sense to me. My .bib file is bibaltex complying ...

**Comment by jjayez** [comment]
I just tested on another computer (same versions of texstudio and texlive, same Ubunu 20.04, same files) and it works ...

**Comment by muzimuzhi** [comment]
> I see
> Process started: biber "Semantics_Crash_Course"
> and later on
> INFO - Looking for bibtex format file 'Semantics_Crash_Course.bib' for section 0
> This line does not make sense to me. My .bib file is bibaltex complying ...

It seems the `biber` program is working. What do you get in its log `.blg`? Do you still get the initially reported message

> Usage: biber [options] file[.bcf] biber [options] --tool [...]

Other random guesses: Does deleting all the aux files help? Do the output of texstudio's "Help - Check LaTeX Installation" on two computers the same? Since you've find the files works on another computer, providing an example may not help much ...

**Comment by jjayez** [comment]
After some fiddling, it turned out that declaring the full path of biber (/usr/local/texlive/2021/bin/x86_64-linux/biber) creates the problem. I replaced it with txs///biber and the problem disappeared. I probably missed something important in the user manual ...
Thank you for your patience

**Comment by zararash** [comment]
**Solution:**

Another way to solve this issue is to add:

`txs:///compile | txs:///biber | txs:///compile | txs:///view
`
to your "Build and View" section, which you can access it here: Options > Configure TeXstudio > Build
