### ISSUE TITLE
Solid Gray Color on the Internal Viewer When Right-Click to "Go to PDF"

### ISSUE THREAD

**Issue by mhmayyan** [texstudio-org/texstudio#2097]
### Environment
- TeXstudio: 4.2.1
- Qt: Using Qt Version 6.2.1, compiled with Qt 6.2.1 R
- OS: Microsoft Windows [Version 10.0.19044.1466]
- TeX distribution: miktex 4.5

### Expected behavior
On the editor, I have multiple open files all belonging to one project; the main thesis file calling multiple tex files each is dedicated to a chapter. Having the internal PDF viewer open, when I edit on a chapter—say Introduction—and I right-click on "Go to PDF" to see what the current paragraph looks like, the PDF viewer shows me the correct paragraph or even the exact word on which I right-clicked my mouse.

### Actual behavior
Having the internal PDF viewer open, when I edit on a chapter—say Introduction—and I right-click on "Go to PDF" to see what the current paragraph looks like, the PDF viewer turns to a solid gray color, and the status bar says the pdf file might be deleted. I noticed that the status bar is showing the wrong file name. Say the name of my main file is "thesis", and the name of the chapter I right-click on is "introduction". The viewer expects the pdf name ends with "introduction.pdf" while it should look for "thesis.pdf".

**Comment by sunderme** [comment]
something wrong with your document/project set-up.
Without a concrete example, nothing anyone can do.

**Comment by mhmayyan** [comment]
Thank you.
Yes, I figured out the problem. It is on my end. The problem id solved when I set the main file to root document.
