### ISSUE TITLE
Auto completion menu closes on pressing AltGr

### ISSUE THREAD

**Issue by 42ndTowel** [texstudio-org/texstudio#21]
The menu from which to select auto completion choices closes once the AltGr key is being pressed.

My keyboard layout allows to acces arrow keys conveniently when pressing the AltGr key. This would theoretically allow me to chose a completion proposition easily. However, the menu closes for apparently no reason.

**Comment by sunderme** [comment]
which OS ? which version of txs ?

**Comment by 42ndTowel** [comment]
That would be TeXstudio 2.12.6 (hg 6631+:16db084dae24+) Using Qt Version 5.10.0, compiled with Qt 5.9.3 R on Arch Linux

**Comment by sunderme** [comment]
works fine on ubuntu ...
