### ISSUE TITLE
Icon redesign?

### ISSUE THREAD

**Issue by Manueljlin** [texstudio-org/texstudio#2101]
Hello folks,

I created a version of this app's icon for Breeze and [another developer recommended me to try upstream it too](https://invent.kde.org/frameworks/breeze-icons/-/merge_requests/200#note_391004) in case you guys like it. If that's the case, feel free to ask me for extra changes or to iterate on the original file yourself.

![image](https://user-images.githubusercontent.com/11275573/152404175-9127222a-b2f1-4c11-bf12-9a5373511cf5.png)

![image](https://user-images.githubusercontent.com/11275573/152404227-1771d6a4-82cc-4442-8141-89bf3cf4d311.png)

(no issues with licenses for the glyphs since they were made from scratch (you can probably tell it's not exactly the work of a font foundry hahaha, was primarily made to look as sharp as possible but scale to hidpi gracefully)

og one for easy comparison
![image](https://user-images.githubusercontent.com/11275573/152404286-8f6e5d99-e878-4b49-8d1d-87b11e16aafd.png)

---

other earlier versions inspired by some of the proposals in the 2016 sourceforge thread:
![image](https://user-images.githubusercontent.com/11275573/152404716-8c12a790-8b45-43ec-bf26-744eaa8c1498.png)

**Comment by foreachthing** [comment]
I like the last one, it has the most contrast.
![image](https://user-images.githubusercontent.com/10420187/152416205-c93fa208-50ca-4c0b-9119-6465cbe099f2.png)

**Comment by sunderme** [comment]
The icon looks good and probably fits well with breeze theme.
However I don't see a compelling reason to change txs default icon on all other platforms.

**Comment by samcarter** [comment]
@Manueljlin Thanks for sharing your creation! It fits in very nicely with the icon scheme on macOS Big Sur. I love the tuned down colours!

**Comment by yapyanchzhanchzhen** [comment]
> @Manueljlin Thanks for sharing your creation! It fits in very nicely with the icon scheme on macOS Big Sur. I love the tuned down colours and shadows!

I added superellipse it's more prefer for MacOS style :)

https://github.com/yapyanchzhanchzhen/TeXStudioIcon

**Comment by samcarter** [comment]
In case anyone would like to use a splash screen in a similar style, I played around with your icon a bit:

![splash_large](https://github.com/texstudio-org/texstudio/assets/43832342/b3acbe59-7f06-4bdd-b238-775e9f37e3b2)

**Comment by sunderme** [comment]
I think, I prefer the current rectangle design.
