### ISSUE TITLE
Texstudio has CRASHED due to unknown at 7fff5a7062ac

### ISSUE THREAD

**Issue by namakshenas** [texstudio-org/texstudio#2103]
I try to open a tex file:

############
My configuration:
TeXstudio: 4.2.0-win-qt6
Windows: 10 (64 bit)
#############

The following window pops out and the program crashes:

Texstudio has CRASHED due to unknown at 7fff5a7062ac
<img width="323" alt="Untitled" src="https://user-images.githubusercontent.com/51627278/152675180-3f3e01a0-d2e0-4569-8abc-5b0e79a9b383.png">

The content of "texstudio_backtrace1.txt":
###############
unknown at 7fff5a7062ac (TXS-Version 4.2.0 R )
[bt] 00007ff78210f680  ??? error: 487
[bt] 000000f52e5fef40  ??? error: 126
[bt] 0000024c08c0d9b0  ??? error: 126
###############

Any suggestion to resolve this issue?

**Comment by sunderme** [comment]
see #2031

the backtrace on windows is insufficient. You can get a better one when running directly on msys, see https://github.com/texstudio-org/texstudio/wiki/Compiling

However the backtrace provided pointed to a Qt6 issue.

**Comment by namakshenas** [comment]
I don't know how this can be related to this issue. I installed a package including all the following runtimes from this [website](https://err0r.ir/2019/03/23/%d8%af%d8%a7%d9%86%d9%84%d9%88%d8%af-%d9%86%d8%b1%d9%85-%d8%a7%d9%81%d8%b2%d8%a7%d8%b1-all-in-one-runtimes/). Immediately after that, I was unable to open the Texstudio.

########
All NET Frameworks
All Visual C++ runtimes
All DirectX
Adobe Flash Player
Microsoft Silverlight
Shockwave Player
Java Runtime Environment
Visual J-Sharp
##########

**Comment by namakshenas** [comment]
Rolled back and installed "texstudio-3.1.2-win-qt5"
Now, it works perfectly on my machine.
