### ISSUE TITLE
Thesaurus not showing words correctly

### ISSUE THREAD

**Issue by AmiZya** [texstudio-org/texstudio#2106]
<img width="782" alt="Screen Shot 2022-02-10 at 6 08 13 PM" src="https://user-images.githubusercontent.com/407471/153462558-44fc9b4e-5c14-40ef-bfe0-637563b15596.png">

### Environment
- TeXstudio: TeXstudio 4.2.1 (git 4.2.1)
- Qt: Using Qt version 6.2.2, compiled with Qt 6.2.2 R
- OS: Mac
- TeX distribution: miktex

### Expected behavior
Showing accented words correctly.

### Actual behavior
Accented words show with a weird character.

### How to reproduce
Nothing, it's just there when I open Thesaurus while writing in French.

**Comment by sunderme** [comment]
fix in dev. build
