### ISSUE TITLE
Insert Graphics dialogue does not allow specifying order of preference for figure placement.

### ISSUE THREAD

**Issue by ahrendsen** [texstudio-org/texstudio#2108]
### Environment
- TeXstudio: 4.1.1 (git 4.1.1)
- Qt:  6.2.1
- OS: Windows 10
- TeX distribution: miktek

### Expected behavior
I should be able to type into the "Position" box in the Insert Graphics Dialogue the value "htbp", indicating that my first preference is for the image to be placed here, second preference top of the page... etc.

### Actual behavior
The order of the characters is rearranged to correspond to the order in which the check boxes appear in the dialogue. Typing "htbp" results in "tbhp" being displayed in the box.

### How to reproduce
File > New
Wizards > Insert Graphic...
In "Position" dialogue box, type "htbp"

**Comment by hair-splitter** [comment]
The location of h is irrelevant in the order of the options.
In any case, h prevails first.
htbp = thbp = tbhp = tbph

**Comment by ahrendsen** [comment]
Thanks, my mistake. Furthermore, the location of *any* letter is irrelevant.

Apparently it's a common misconception. By searching latex-project.org I found [a document](https://www.latex-project.org/publications/2014-FMi-TUB-tb111mitt-float-placement.pdf) clarifying how figures are placed. From the document:

> The order in which these characters are put in
> the optional argument does not influence how the
> algorithm tries to place the float! The precise order
> is discussed in section 3.2. This is one of the common
> misunderstandings, for instance when people think
> that bt means that the bottom area should be tried
> first.
