### ISSUE TITLE
CTD after changing style

### ISSUE THREAD

**Issue by playful1510** [texstudio-org/texstudio#2109]
### Environment
- TeXstudio: 4.2.1
- Qt: 6.2.1
- OS: Windows 10 21H2

### Expected behavior
Change style to selected style

### Actual behavior
Crash to Desktop

### How to reproduce
Configure TexStudio > Change default style to Orion Dark > click OK

It may or may not be relevant, but I had loaded a different profile prior to attempting to change the style, and attempting to load from a backup profile doesn't change anything.

**Comment by sunderme** [comment]
no crash on windows or linux.
Please try to recreate with clean settings (options/restore default settings)

**Comment by playful1510** [comment]
Restored default settings, still crashed on style change. I'm attaching a video showing the crash happen after doing another default restore.

https://user-images.githubusercontent.com/5361114/153762535-4d94414e-2340-4496-b31a-ff47ca193f99.mp4

**Comment by sunderme** [comment]
can you try without any opened documents ?

**Comment by playful1510** [comment]
Without having any open documents, it seems to work properly on the release build. On the dev build I am able to freely change the style with one document open, but it crashes at three or more open.

**Comment by sunderme** [comment]
Once stylecis changed, can you open the documents?

Can you upload the documents for me to test ?

**Comment by playful1510** [comment]
[Chapter 1.txt](https://github.com/texstudio-org/texstudio/files/8057141/Chapter.1.txt)
[Chapter 2.txt](https://github.com/texstudio-org/texstudio/files/8057142/Chapter.2.txt)
[Fluids1.txt](https://github.com/texstudio-org/texstudio/files/8057156/Fluids1.txt)
[Exam1.txt](https://github.com/texstudio-org/texstudio/files/8057153/Exam1.txt)
