### ISSUE TITLE
TeXstudio ignoring $PATH

### ISSUE THREAD

**Issue by mxa** [texstudio-org/texstudio#2111]
### Environment
- TeXstudio: 4.2.1 (git n/a)
- Qt: Version 5.15.2, compiled with Qt 5.15.2 R
- OS: Kubuntu 21.10
- TeX distribution: TeXlive 2021

### Expected behavior
After the correct installation of TeXlive and added paths to $PATH, TeXstudio should find the binaries of all TeX binaries.

### Actual behavior
TeXstudio seems to be ignoring the $PATH variables

### How to reproduce
Install TeXlive according to the official instructions: https://tug.org/texlive/quickinstall.html
Double check if paths are set up correctly by typing `echo $PATH` in the Terminal.
The output should include the installation directory of TeXlive, here it is: `/usr/local/texlive/2021/bin/x86_64-linux`.
Triple check with `which latex`, it should output:
`/usr/local/texlive/2021/bin/x86_64-linux/latex`
Even though the correct installation is verified, TeXstudio can't find the binaries without adding the path to the settings (That should not be necessary if latex works from the shell!).

**Comment by sunderme** [comment]
txs does not ignore $PATH
Start "texstudio" from commandline/terminal and check if it sees the correct $PATH
The start-menu takes probably a different file to set $PATH -> google

**Comment by mxa** [comment]
Indeed, when launched from the shell the binaries are found, when launched from the panel the binaries are not found. Is this behavior to be expected?

**Comment by sunderme** [comment]
This is your system setting different PATH variables.
Terminal is coming from .bashrc or whatever shell you are using. Panel is desktop env specific. Maybe .profile, maybe something else.

**Comment by mxa** [comment]
Closing the issue then. Further information how to add the PATH to the desktop environment PATH variable might be found here:
https://userbase.kde.org/Session_Environment_Variables
