### ISSUE TITLE
PDF artefacts (both but different in splash vs arthur)

### ISSUE THREAD

**Issue by AJJLagerweij** [texstudio-org/texstudio#2114]
### Environment
- TeXstudio: 4.2.1
- Qt: 5.12.8
- OS: Ubuntu 20.04
- TeX distribution: TexLive

### Expected behaviour
Vector graphics in the pdf should show up as they are intended. That is without ragged edges (aliasing) and no gaps between endpoints). 

### Actual behaviour
I have a integrated a vector graphics in my latex file and in different pdf viewers it looks different. I'm not even sure whether this is a TeXstudio or a dependency issue.

Figure 1 in the attached pdf, exhibits the following behaviour in:

- Internal PDF viewer with Splash renderer: Ragged lines in the fill patterns. This is remains visible in my screenshots.
![image](https://user-images.githubusercontent.com/31255888/154030110-b0169d9a-651b-4333-afcb-d9962c2ca485.png)
- Okular suffers from the same problem 
![image](https://user-images.githubusercontent.com/31255888/154030886-b67152ae-36d1-45c2-96e8-5aefaa4c308b.png)
- Firefox PDF viewer does the anti-aliasing a bit better, but it becomes wavy now especially visible on the right side of the image.
![image](https://user-images.githubusercontent.com/31255888/154033299-c6ffd3fe-9bef-4aa3-ada1-155e14820090.png)
- Internal PDF viewer with Arthur renderer: Small white space is inserted in the pattern.
![image](https://user-images.githubusercontent.com/31255888/154031248-8b0ffa0a-52a0-4c78-a49f-70c9db867468.png)
- Evince PDF Viewer, aka gnome PDF does not show any of this behaviour. The figure looks as is intended.
![image](https://user-images.githubusercontent.com/31255888/154030630-ddbb93d3-6075-4b6d-8e80-3cab241d029a.png)

### How to reproduce
The issues can be verified with the attached [Example.pdf](https://github.com/texstudio-org/texstudio/files/8067611/Article.pdf)
As for the figure itself, it was created as an `.svg` in Inkscape and exported as a 'pdf with tex' [(original and export result)](https://github.com/texstudio-org/texstudio/files/8067710/Composite.zip). To integrate the file in latex I followed [this manual](http://tug.ctan.org/tex-archive/info/svg-inkscape/InkscapePDFLaTeX.pdf). I have used this approach for a while now, and never had any issues. The difference might be the use of the 'Fill Pattern' in the drawing. 

In the end, I have a couple of questions:
- Can we fix this render issue (why don't Envice but also WPS viewer and not show the issue)?
- How does this look in other viewers such as Adobe Acrobat, and why don't all viewers display the same?
- How do I ensure that the image looks good no matter what software is used?

**Comment by sunderme** [comment]
by the looks of it, it seems that the inkscape pdf export is rather rough.
png export with 300 dpi delivers way better results.
I am not an expert to analyse pdfs but I would suspect that the result is rastered already and then everything is relying on anti-aliasing in the viewer.

**Comment by AJJLagerweij** [comment]
Thanks for the quick response, I had the same idea as you did and tried to verify that theory. The following 4 reasons tell me that it is not rasterised:

- Inkscape can rasterise some of its SVG effects, but I have that option disabled.
![afbeelding](https://user-images.githubusercontent.com/31255888/154056612-9ff9bd8a-f2f8-4c96-8988-dd8cdeb36573.png)
- Besides, if it was rasterised then I would either have a much larger file than the 8.1 kB that I have now, or be able to count pixels when zooming in.
- I imported the intermediate pdf, the one that was exported by Inkscape, into Inkscape again through the pdf import function. The lines of the pattern became SVG lines that I could alter. It wouldn't be able to do that to that if they were rasterised.
- I even tried importing the pdf that was created by latex into Inkscape and it still allowed me to edit the lines as if they were lines, not pixels.

As a result, it was not rasterised by Inkscape nor by Latex.

Now I agree that exporting it as a rasterised image (300 dpi as you suggested), is indeed possible and give crisp looking pictures. However, there are also drawbacks, in my real work there will be many complicated equations in my figures, I would like them to be rendered by latex itself. As rendering by an external program such as Inkscape or Illustrator make it difficult to keep the font size and type consistent between the images and the TeX-document.

Less important is that it would also result in much larger PDF files. After all, vector graphics are specifically meant to make this kind of images (graphs and schematics with lots of lines) whereas rasterization is meant for pictures. I'm a bit surprised by how difficult it is to robustly integrate vector graphics in Latex. (which in itself has nothing to do with TeXstudio)

**Comment by sunderme** [comment]
the scope of the question is not directly related to texstudio.
Texstudio uses poppler to render and so do okular and I assume evince. Why evince seems to do a better/different job, I don't know. You can take it to poppler (https://poppler.freedesktop.org/) or just be pragmatic.

**Comment by sunderme** [comment]
if I render the file with mupdf which uses a completely different rendering engine, I see artefacts.
So, I would still assume that the inkscape export is broken/suboptimal.

**Comment by sunderme** [comment]
If quality is the main concern, tikz may be an alternative.
psfrag was used for substituting text in eps but that seems not to work for pdf.

**Comment by AJJLagerweij** [comment]
@sunderme thanks for the feedback, I've created an [issue at Poppler](https://gitlab.freedesktop.org/poppler/poppler/-/issues/1218)  and will also open one at the Inkscape git. Should I also post at the Envice git to ask about the magic they use to remove these artefacts?

It does indeed seem that there is an issue in the way that Inkscape exports patterns to pdf. But it is also surprising that the different render engines show different artefacts for the same pdf. I'm sure that we'll figure out something, and I'll keep you up to date. I'll make another post if there appears to be anything that TeXstudio can do about it.

**Comment by sunderme** [comment]
alright
