### ISSUE TITLE
texStudio runs continously compiles executes without any clicks

### ISSUE THREAD

**Issue by Snowrr** [texstudio-org/texstudio#2116]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior
Should run when clicked the correct menu options 

### Actual behavior
uncontrolled continous execution compilation

**Comment by sunderme** [comment]
well, it usually does not.
No OS given, no txs version.

**Comment by sunderme** [comment]
except if you turn on the option for it.
<img width="521" alt="grafik" src="https://user-images.githubusercontent.com/14033169/154268445-86efaa33-5b4d-49cc-b557-1c9b1c8de843.png">

**Comment by sunderme** [comment]
no feedback

**Comment by octaeder** [comment]
@sunderme Please reopen, it is the previewer. When I had read this new issue it came me clearly to mind that I know this problem. But I coudn't reproduce it. But now I can.

I use this config for previewer:
![grafik](https://user-images.githubusercontent.com/102688820/164817292-cd30a505-2a32-4ab4-baa5-7b0195ed4b61.png)
Now open a new document with the following simple code:
\usepackage{xcolor}
\begin{document}
\color{red}
\end{document}
Open the Messages Tab, then move the mouse pointer over the word red. After a second you will see messages that the previewer started a background compile. In this case it succeeds and txs opens the preview tab. I don't know why it shows this:
![grafik](https://user-images.githubusercontent.com/102688820/164817432-04f0b1fb-8856-446c-8142-5faeae650f71.png)

**Comment by sunderme** [comment]
the new error (black box in color preview)  does not correlate to the reported one (continous compile), so please open a new issue.

And please report complete documents. I assume the document has a class ?

**Comment by octaeder** [comment]
This was indeed the full document. But when I use the follwoing then the preview is slightly different:
\documentclass{article}
\usepackage{xcolor}
\begin{document}
	\color{red}
\end{document}
![grafik](https://user-images.githubusercontent.com/102688820/164888537-d48ef57d-1746-4d5c-8f64-1aa85674866a.png)
Changing color to green chases the box's color to green.

**Comment by yashpalgoyal1304** [comment]
it happens several times for me too - it is automatically recompiles (without any edits)

TXS: 4.3.1 on Win 10 20H2, but I was not able to reproduce it, so, didn't report myself earlier.
