### ISSUE TITLE
automatic fill in with \mint

### ISSUE THREAD

**Issue by damnms** [texstudio-org/texstudio#2117]
### Describe the feature and the current behavior/state
when i type \mint i get some items which i can chose like \mint{language}{code} and \mint{language}|code| etc.
I would like to use only the variants with | | and would really love it to have those listed first, because it saves me 2 clicks. I know that sounds not a lot but i have easily 100 of those sections in my current document and then it sums up
edit: or remove those with {} at all because its not supported (anymore?), see 2113

### Who will benefit with this feature?
all users because {} is not supported at all

### Any Other info
https://github.com/texstudio-org/texstudio/issues/2113

**Comment by sunderme** [comment]
the request is to remove in minted.cwl the lines with ```\mint...{code}```
