### ISSUE TITLE
SHA256 mismatch in texstudio installer

### ISSUE THREAD

**Issue by jsmm** [texstudio-org/texstudio#2121]
I install texstudio via Homebrew. In the last texstudio version upgrade the package cannot be upgraded because of a SHA256 mismatch. 

I let you know in case you handle this directly or want to inform Homebrew on behalf of texstudio. Thanks.

I use macOS 12.2.1, with MacTeX 2021 and Tex Live  1.53.

**Comment by muzimuzhi** [comment]
It seems the release file is updated after I ran `brew bump-cask-pr` locally (which resulted in the PR Homebrew/homebrew-cask#119440) and after the CI there got passed. I'll provide a fix to homebrew.

**Comment by muzimuzhi** [comment]
The [CD for corresponding commit](https://github.com/texstudio-org/texstudio/actions/runs/1869432495) was re-ran 14 hours ago, hence the release files got updated and checksum changed.

**Comment by muzimuzhi** [comment]
A new PR Homebrew/homebrew-cask/#119478 is provided and merged, now the checksum matches. I've also opened #2128 to avoid this kind of mismatch problems in the future.
