### ISSUE TITLE
TXS won't open at all

### ISSUE THREAD

**Issue by Drsch8** [texstudio-org/texstudio#2123]
Installing the latest version of TXS lead to the problem, that the programm simply is not opnening. Only a crash report pops up:
TexStudio crached due to unknown at 7ffe372f6efc.
It would only produce a bugreport in texstudio_backtrace1:

unknown at 7ffe372f6efc (TXS-Version 4.2.2 R )
[bt] 00007ff6f5d1e3d0  ??? error: 487
[bt] 000000dfea9fed30  ??? error: 126
[bt] 000002ac11cf82d0  ??? error: 126

Thanks for your help in advance!

### Environment
- TeXstudio: 4.2.2
- Qt: qt5 and qt6
- OS: Win10
- TeX distribution: miktex

### Expected behavior
Programm starting as regular

### Actual behavior
It's not starting at all

### How to reproduce
Trying to open the program

**Comment by sunderme** [comment]
works fine here.
I would recommend to uninstall txs completely before installing it again.
Also, you can check the portable packages which don't require an installation.

**Comment by Drsch8** [comment]
thanks for the quick answer.
Surely I did the complete reinstallation prior to this _issue_ . Anyways, the portable version runs smoothly, I guess it's some restrictions with the very restricting antivirus software from the institution. So i guess this can be closed, thanks again
