### ISSUE TITLE
TeXstudio not saving file and having corrupt file change history

### ISSUE THREAD

**Issue by gone-insane** [texstudio-org/texstudio#2124]
I am running TeXstudio 4.2.2 on Windows 10 and observe the following error: During writing sessions, I routinely save my file by hitting CTRL + S. However, when doing so after an extended writing session, the file on the disk is not altered. Also File -> Save does not work, the file on the disk remains at an outdated version. Nevertheless, in TeXStudio, the floppy-drive symbol that reminds me to save my data, vanishes also in those cases.

At first, I did not notice this until I pressed CTRL+Z to revert some change. If the above described error happens, also the "undo history" is corrupt and the file is changed at some random location in the text.

I know, these two error descriptions are yet very vague and I cannot reproduce the error on purpose. But it happens daily and is super frustrating if you close TeXStudio and the next day you notice that at least half a day worth of work is lost. Let me know if there is anything I can do to help you find this bug.

This error also ocurred in 4.2.1. The file is stored locally in a git-repository (i.e. it is not stored on a remote server).

**Comment by sunderme** [comment]
what does "the floppy-drive symbol that reminds me to save my data, vanishes also in those cases." mean.
which qt version ?
without some way to reproduce it, it is nearly impossible to solve.

**Comment by gone-insane** [comment]
TeXstudio 4.2.2 (git 4.2.2), Using Qt Version 5.15.2, compiled with Qt 5.15.2 R

by the floppy-drive symbol I mean this little icon here:
![grafik](https://user-images.githubusercontent.com/1622024/154956448-5a42a10d-0903-4022-a8a6-f331f236d74d.png)

**Comment by sunderme** [comment]
there is no logging capability in txs.

**Comment by sunderme** [comment]
if you do a saveAs when you notice the issue works ?
Have you actiavted to use git when saving ?
<img width="1920" alt="grafik" src="https://user-images.githubusercontent.com/14033169/154958768-984504b8-fa1e-4f3f-bce1-8aaacf4de3ae.png">

**Comment by gone-insane** [comment]
Thanks. No, I have not enabled git when saving:
![grafik](https://user-images.githubusercontent.com/1622024/154959178-925ab5d2-ec24-4cf6-b6b4-795dc106ff21.png)

If I recall correctly, "save as" did not work either and the deprecated version was stored. I had to copy everything to another editor, restart texstudio, and "paste back". I will repeat the "save as" procedure once the error occurs again...

**Comment by gone-insane** [comment]
So it just happened again. Observations:

1. Saving the file using "Save As" really saves the current version.
2. However, making changes to the version saved with "Save As" and hitting "Save" once again does not work
3. The "change history" (undo&redo) remains corrupt/messed up, even when using "Save As"
4. Only one "tab" is affected. Tex-files opened in another "tab" can be proprely saved to disk by using "Save"

Closing the tab and opening the file again seems to help.

**Comment by sunderme** [comment]
just to check, txs <4.2.1 did not show the issue ?

**Comment by gone-insane** [comment]
I cannot tell for sure, I started using texstudio extensively (again) after 4.2.1 (beginning of february)...

**Comment by sunderme** [comment]
okay
are you able to build texstudio locally (with debug, see https://github.com/texstudio-org/texstudio/wiki/Compiling). 
There is a debug function which prints the undo stack.

**Comment by sunderme** [comment]
okay
are you able to build texstudio locally (with debug, see https://github.com/texstudio-org/texstudio/wiki/Compiling) ?
There is a debug function which prints the undo stack.

**Comment by sunderme** [comment]
can you try the current dev build: https://github.com/texstudio-org/texstudio/actions/runs/1923435000 (it is building right now)
I have activated edit/debug undo stack
It may give some insights. You could take a look from time to time. My suspicion is that the number of blocks is not incremented at one point in time.

**Comment by gone-insane** [comment]
thanks a lot, I will take a look! In the meantime, I have installed Qt and followed the instructions. I am a bit lost however at the part, where I should set the "qmake setting "NO_POPPLER_PREVIEW=1"". I suppose I have to paste this somewhere in QtCreater - Tools - Options - Kits - CMake. Can you help me, where I should set this flag?
![grafik](https://user-images.githubusercontent.com/1622024/156414510-c6e4f441-ee7b-4ebc-ab0a-473f24e22375.png)

**Comment by gone-insane** [comment]
P.S.: I installed the version you compiled and I am able to access the undo stack via Edit - Debug undo stack. I will post here as soon as it happens again

**Comment by sunderme** [comment]
no it is under "Projects" build and execute (?, sorry I am using German language here)
In the build settings:
<img width="1920" alt="grafik" src="https://user-images.githubusercontent.com/14033169/156417112-52617811-53b7-416c-bcd6-91032d6d0f49.png">
qmake/additional arguments

**Comment by gone-insane** [comment]
alright, thanks!

**Comment by gone-insane** [comment]
So it just happend again after an extended writing session. The undo stack displays (intermediate lines omited)
`Current: 2214/2214
[...}
2213: 
INSERT COMMAND: 115:227
     Inserted text: "\SI{value}{unit}"
     Cursor undoOffset: 0   redoOffset: 0`

When I add now further text to document, the debug stack does not change (no matter if I "try" to save the file or not).

One thing I found interesting, is that the final entry in the debug stack is a `\SI{value}{unit}` command, which I have (most probably) entered via a macro mapped to a shortcut:
![grafik](https://user-images.githubusercontent.com/1622024/156649294-c027c266-4afa-42cb-9535-b2293de65c9d.png)

**Comment by sunderme** [comment]
please store the complete stack (and maybe send it directly to me for further analysis ? sunderme@gmx.de)
I take a look if the piece of information suffices.

**Comment by gone-insane** [comment]
Sorry Jan, I didn't expect such a swift reply and hastily restarted TeXStudio (to save the file properly). I will send you the next complete stack, once it happens again.

**Comment by sunderme** [comment]
how do you enter \\SI. Is the completer not impeding it ?

**Comment by gone-insane** [comment]
Typically, I hit Shift + F1, then CTRL + arrow right to enter the value and unit field.

**Comment by sunderme** [comment]
it may be an idea to remove "abbreviation" and "Trigger" of that macro.

**Comment by sunderme** [comment]
what happens in "line wrapping" ?

**Comment by gone-insane** [comment]
the line wrapping macro is the taken from this one: https://sourceforge.net/p/texstudio/feature-requests/1157/

I use it to quickly toggle between a soft wrap when writing long equations or tables, but I haven't used it yesterday.

**Comment by gone-insane** [comment]
@sunderme I have just sent you a complete stack via mail.

**Comment by sunderme** [comment]
do you remeber what you did after the \SI... in the debug stack ?

**Comment by sunderme** [comment]
I have just initiated a new build which should give a little more info on the issue (if I am guessing right)
Please use https://github.com/texstudio-org/texstudio/actions/runs/1953128125

**Comment by gone-insane** [comment]
Okay, I will use this new build. 
I do not remember what I did after the \SI...

**Comment by sunderme** [comment]
it is probably the step after inserting \SI via macro which causes the issue.

**Comment by gone-insane** [comment]
Happened just again. I noticed, that I used undo and redo soon after inserting a SI-environment by the macro. I tried provoking the error by inserting SI-commands using the macro then using undo and redo, but have not been able to do so...

**Comment by sunderme** [comment]
found it.
it occurred when typing ```$\pm``` and then shift+f1 (inserting the macro) when the completer is still open.

**Comment by sunderme** [comment]
thanks for your patience and support in the debugging.

**Comment by gone-insane** [comment]
Wow. Thank you very much for your great support, really appreciated.
