### ISSUE TITLE
Editor scrolling last time to the top

### ISSUE THREAD

**Issue by Atcold** [texstudio-org/texstudio#2125]
### Describe the feature and the current behavior/state
The editor should let me scroll the document up to having the last line of my document to the top of my screen.
Currently, the last line of the document is always at the bottom of the screen.

### Who will benefit with this feature?
Anyone familiar with fully functional text editors.

**Comment by sunderme** [comment]
a bit condescending. Not every editor behaves that way.

**Comment by Atcold** [comment]
I didn't mean to be rude. Both Vim and Emacs have it. I'm not familiar with other editors.

**Comment by sunderme** [comment]
gedit and kate don't behave that way, so ...

**Comment by Atcold** [comment]
Oh, okay, I've never used them.
I just tried Atom and VSC. Both have the same behaviour too.

I'm so used to it that missing it is somehow painful. :/

**Comment by sunderme** [comment]
Both are based on electron, so no wonder.

**Comment by sunderme** [comment]
Implementing it is costly as it messes up total line numbers with the scrollbar.

**Comment by Atcold** [comment]
Maybe [this](https://www.qtcentre.org/threads/55953-Scroll-QTableView-beyond-last-column-row?s=c83266fd1f2fd614c580fcb0589089fb&p=250584#post250584) could be a solution?

**Comment by Atcold** [comment]
I don't think it messes with the line numbers, or does it?

**Comment by Atcold** [comment]
@benibela, could you please add some more context?
Shall I edit some source files and recompile the IDE myself?

**Comment by foreachthing** [comment]
@Atcold, not much context needed:
<img width="711" alt="image" src="https://user-images.githubusercontent.com/10420187/155931167-d6e98799-8969-4cdd-8350-b0af0b7f348a.png">

**Comment by Atcold** [comment]
Awesome! Thanks, @foreachthing. That was exactly what I was looking for.
I wonder why this is not ON by default. Thanks a bunch!

**Comment by foreachthing** [comment]
@Atcold it was @benibela how pointed that out. 😉

**Comment by Atcold** [comment]
Oops. Well, you provided some context 😅
Thanks for @benibela as well, though.
