### ISSUE TITLE
Make it possible to disable automatic detection of a Master Document

### ISSUE THREAD

**Issue by drtoche** [texstudio-org/texstudio#2127]
I'm working on a project that includes a Master Document. I need to look up some unrelated document and quickly compile it, bam it's linked to the Master file.  

It's nice to have the ability to manually set a Master Document, but automatic detection should be an opt-in option that I would love to be able to opt-out of. 

If I have an ongoing project with a dozen files currently open in TeXStudio and I want to quickly compile an unrelated document I have to manually correct the automatic detection and select ... Automatic Detection ...the naming is unfortunate since Automatic Detection is the way to cancel the previously automatically detected link to the Master Document... but let that not confuse you: **Please consider this feature request: to disable automatic detection and have Master Documents be set manually only.**

See: https://sourceforge.net/p/texstudio/feature-requests/872/

**Comment by sunderme** [comment]
there is rarely the need to define an explicit root. Automatic detection should work sufficiently.
If you want to compile the current document, you can define a command to use/compile the current document,see manual chapter 4.4.

**Comment by drtoche** [comment]
Sorry if I did not make myself clear. This has nothing to do with commands or shortcuts. It has to do with a file being automatically set as a slave to the Master Document. I would like the ability to remove this automation.

If I have a project that depends on a Master Document and if this Master Document is currently opened in the editor, then any document I open will become a slave of that Master Document. Any shebang at the top of the file that is intended to direct TexStudio is ignored. I'd like to be able to disable that feature so that TexStudio can follow instructions in the shebang, as it would if there was no Master Document currently opened in the editor.

I would prefer if the default feature for files opened in the editor while a Master Document was **not** to set it as slave to the Master Document unless I explicitly requested it.

**Comment by sunderme** [comment]
The whole concept of setting explicit root is that all opened documents are its children with all consequences. The automatic detection should work fine to keep track which document belongs to which.

**Comment by drtoche** [comment]
Automatic detection associates **EVERY** file with the currently opened Master Document, unless it is itself a Master Document. In particular, it ignores the shebang, so it's not exactly subtle.

It would be great if it could be disabled, as suggested by Tim Hoffmann on source forge a few years ago.

The way it works currently is that if you're working on a project with multiple files with a Master Document and you want to open another, unrelated file, your choice is: Close the twenty files you're currently working or use another IDE: either way it's more work than ideal. 

I could do away with the Master Document feature, but then if I have a big project with hundreds of file every single one of these files will need a shebang or I will need to tab like a madman to find the Master file among the many that are opened in the IDE.  I currently use TeXStudio for my one big project and another IDE for everything else. I just haven't found a great system yet.

**Comment by jvledesma** [comment]
This "disable" option could be particularly relevant for projects with several .bib files where non of them are associated with the master root document

**Comment by sunderme** [comment]
I assume "shebang at the top" means magic root comment ```% !TeX root=...``` ?

txs does not "associate every file with the currently opened Master Document", it parses the files, particularly the ```\input&\include``` statements and builds a model of the related files.
So, what does actually fail, if a file gets associated with a current open master document ?

**Comment by drtoche** [comment]
> I assume "shebang at the top" means magic root comment % !TeX root=...
Yes. It goes under other names too. See: https://en.wikipedia.org/wiki/Shebang_(Unix)

I have a Master Document for Project A opened in the editor. Let's call it `MasterDocProjectA.tex`. It's the only Master Document currently opened in the editor. Other files may or may not be opened in the editor, it's irrelevant. Now I open a file that has a shebang like `% !TEX root = ProjectB.tex` (neither this file nor `ProjectB.tex` are Master Documents). Now this file has been automatically detected to belong to `MasterDocProjectA.tex`. What actually fails? If I compile the file, the shebang is ignored, `MasterDocProjectA.tex` is invoked and Project A is compiled. Not what I wanted.

So the feature request is some way to disable automatic detection. For instance, a toggle: while it's on TeXStudio detects anything as a slave, but while it's off it doesn't and the shebang will be followed. There may be better ideas.

**Comment by sunderme** [comment]
that works here as expected. Please provide a screencast to illustrate the issue.

**Comment by drtoche** [comment]
I'm not sure we follow.

What do you mean by "it works as expected"? Any document opened in the IDE is associated with the Master Document. Yes it is expected. Yes it works. It's just not convenient. It means you can only have one project opened at any one time.

I would prefer if the shebang had priority. Are you saying that in your case the shebang has priority?

A simple thing that would greatly improve my productivity would be to have a shortcut associated with "Root Document -> Set Automatically." Now perhaps this is the confusing part: By selecting "Set Automatically" I would be able to cancel the automatic detection that I find undesirable. Yes the name "Set Automatically" is basically the opposite of what it does.

**Comment by sunderme** [comment]
There seems to be a misunderstanding.
"Detect Automatically" does exactly what is says.
It looks at all open documents in the editor (loads included documents on its own, unless Options/Editor/automatically load included files is disabled), calculates the relation between the files from the include/input statements and acts accordingly, i.e. collects references,defined commands and chooses the correct root document to compile.

There should be no need to set an explicit root and magic root comment works as expected.

**Comment by drtoche** [comment]
Yes there is a misunderstanding. 

On my computer if I have a Master Document opened and I opened another file that is not itself a Master Document, with or without shebang, it gets associated automatically with the Master Document. As expected. If I want to disassociate it so I can compile it independently of the Master Document, then I select "Detect Automatically". I know it's counterintuitive, but that's the way it works on my end. Selecting "Detect Automatically" is the way to cancel the effect of the automatic detection. The other way would be to make that second document a Master Document, which is not desired. 

I hope this is clearer now. Can you reproduce what I'm describing?

**Comment by sunderme** [comment]
I understand your use model. It is however not the recommended one.
Please take a look into the manual: https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html#SECTION31

**Comment by drtoche** [comment]
I suppose you mean for me to read section 4.1.1. copied below?

What it essentially recommends is not to use a Master Document (named "Root Document" in the manual and in the Options menu, but named Master Document in the File->Open menu): the manual states "As a last resort".

However, what I'm saying is that the Master Document can be useful when you have dozens or hundreds of files in one project and you don't want to have to add a shebang to every single file. But as nice as it may be to have a Master Document, _it would be great to have the shebang take precedence over the automatic detection. Or alternatively, it would be nice to be able to set a key binding to disable automatic detection_  I see none of these points addressed in the portion of the manual below. Did you mean for me to read something else?

To reduce the feature request to its absolute minimum: **Would it be possible to add a key binding to "Options->Root Document-> Detect Automatically" ?**

Can a shortcut be set for that action? Maybe I'm just ignorant and it's already possible.

Thanks!

> 4.1.1 Root Document
> The root document is the top-most file in a multi-file document. For a single-file document this is the file itself. By default, all calls to LaTeX will be performed on the root document.

> TeXstudio automatically detects the root document. If that does not work, you can place a magic comment % !TeX root = root-filename at the top of your included files.

> As a last resort, you may set an explicit root document via Options -> Root Document -> Set Current Document As Explicit Root. This setting takes absolute precedence. All the commands of the "Tools" menu will be called on this document (to be more precise, the build system will expand the placeholder % to the root document), no matter which document is active in the editor. Additionally, labels and usercommands which are defined in any open document, can be used for completion in any open document.

**Comment by sunderme** [comment]
you can set that shortcut yourself: options/shortcuts -> Menus/options/root document/Detect Automatically

My point is that txs detects the root automatically, use the default "Detect [root] automatically" mode, open your root document and whatever other document, do not use magic comments, do not set explicit root. Let txs do its job.

**Comment by drtoche** [comment]
Thanks, I'll see how that goes. I just had my laptop die, so I've had to reset everything and am a bit behind work, but I'll experiment as soon as I have a minute! :-)

**Comment by sunderme** [comment]
I hope that this is resolved.
