### ISSUE TITLE
Clear auxiliary files before compiling to avoid errors

### ISSUE THREAD

**Issue by doej1367** [texstudio-org/texstudio#2134]
### Describe the feature and the current behavior/state
Add clearing the auxiliary files (`.log` `.aux` `.bbl` `.blg`) as the first step when compiling  a document (`F5` and `F6` action) like mentioned in this [stackexchange post](https://tex.stackexchange.com/questions/350907/error-latex-error-somethings-wrong-perhaps-a-missing-item/561933#561933). I think this would prevent a lot of `Something's wrong--perhaps a missing \item` errors.

### Who will benefit with this feature?
Everyone who uses citations

### Any Other info
If this isn't possible for some reason, it slows down the prozess even further or trying it breaks something else, an alternative could be to add a seperate button to clear those files. If not I have to keep searching and deleting all those files by myself evertime the error pops up again...

**Comment by sunderme** [comment]
Short answer: no
Clean files per menu command: Tools/Clean Auxiliary Files ...
You can define arbitrary compile command chains in the options, including user commands for deleting whatever files you like.
The command mentioned above is not part of the tool chains, so you have to define user commands for deletion.
