### ISSUE TITLE
Autocompletion not working

### ISSUE THREAD

**Issue by Atcold** [texstudio-org/texstudio#2135]
### Environment
- TeXstudio: `4.2.2`
- Qt: `6.2.2`
- OS: 
- TeX distribution: `MacOS 11.6.4`

### Expected behavior
I would like to create a `tickzpicture` environment. I type `\begtik`, the suggestion window pops up.
<img width="578" alt="Screenshot 2022-02-27 at 18 18 26" src="https://user-images.githubusercontent.com/2119355/155904229-6559599b-f51b-4828-afe9-96059d0e9f01.png">
The IDE should insert

```tex
\begin{tikzpicture}
  content...
\end{tikzpicture}
```

### Actual behavior
I press return or I double-click the suggestion and the editor completes it as `\begtiktikzpicture`.

<img width="255" alt="Screenshot 2022-02-27 at 18 18 35" src="https://user-images.githubusercontent.com/2119355/155904342-6248869f-00b2-4ed7-bdaa-fbad12c24741.png">

### Update
Rebooting the IDE fixed it.
Still, I'm reporting this in case others may face the same issue.

**Comment by sunderme** [comment]
works as expected as with the reporter
If reproducible test case can be generated, I can try to look into that.
