### ISSUE TITLE
problem with math highlighting in keyvals

### ISSUE THREAD

**Issue by mbertucci47** [texstudio-org/texstudio#2138]
### Environment
- TeXstudio: 4.2.2
- Qt: 6.2.3
- OS: Windows 10
- TeX distribution: miktex
### Description
Math is not always correctly highlighted in keyvals. For example,

<img width="300" alt="Screenshot 2022-02-28 135531" src="https://user-images.githubusercontent.com/61854785/156057721-151a5746-de2c-49a3-85df-d619aea32880.png">

The dollar signs are not highlighted and it doesn't recognize the content as in a math environment. Braces fix the highlighting but the first should still be valid. This behavior occurs wherever you have `key=%<value%>` in a cwl, and regardless of whether the command was specified with a `#c` in the `#keyvals: ... #endkeyvals` structure.

**Comment by sunderme** [comment]
can you add the example. Not keen on copying by hand.

**Comment by mbertucci47** [comment]
```
\documentclass{article}
\usepackage{enumitem}

\begin{document}
\begin{itemize}[label=$\diamond$]
\item text
\end{itemize}
\begin{itemize}[label={$\diamond$}]
\item text
\end{itemize}
\end{document}
```

**Comment by mbertucci47** [comment]
With 4.8.3alpha1 this problem seems to have resurfaced. The example above now displays the same as it did before https://github.com/texstudio-org/texstudio/commit/6274fe778e3d0c2cae1f1e44eced759df2be9ce9
