### ISSUE TITLE
Crash after theme changing 

### ISSUE THREAD

**Issue by fdifonzo** [texstudio-org/texstudio#2139]
### Environment
- TeXstudio: 4.2.2
- Qt: 5.15.2
- OS: Windows 11
- TeX distribution: texlive

### Expected behavior
TeXstudio crashed after theme switching

### How to reproduce
Switch from Adwaita Dark to Fusion
[texstudio_backtrace1.txt](https://github.com/texstudio-org/texstudio/files/8160015/texstudio_backtrace1.txt)
[texstudio_backtrace2.txt](https://github.com/texstudio-org/texstudio/files/8160017/texstudio_backtrace2.txt)

**Comment by sunderme** [comment]
please try txs/qt6.

**Comment by sunderme** [comment]
no feedback

**Comment by fdifonzo** [comment]
Same
