### ISSUE TITLE
TXS 4.2.2-QT6 does not succeed while TXS 4.2.2 QT5 succeeds in compiling with PDFTEX

### ISSUE THREAD

**Issue by zballito** [texstudio-org/texstudio#2140]
Hi,

Firstly i want to thank you for TXS, it is a great app.
Secondly: it is my first report on TXS, so apologize if mydescription is not enought precise

The observation is : when i try this Minimal Working Exemple [MWE] (taken from TXS assistant)
`
\documentclass[10pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{graphicx}
\begin{document}
	hello
\end{document}
`

It compiles with PDFTEX for TeXstudio 4.2.2 (git 4.2.2) Utilise Qt version 5.15.2, compilé avec Qt 5.15.2 R, that means, i get a pdf file with "hello" on its single page

It  does not compile forTeXstudio 4.2.2 (git 4.2.2) Utilise Qt version 6.2.3, compilé avec Qt 6.2.3 R, that means, i get following errors (only the first lines from TXS log tab is given here after)
'
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (MiKTeX 22.1 Portable) (preloaded format=pdftex 2022.3.1)  1 MAR 2022 13:30
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**./main.tex
(main.tex
! Undefined control sequence.
l.1 \documentclass
                  [10pt,a4paper]{article}
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
'

Compilation is done
- on same machine with the same OS, that means,
WIN 10 version 21H1 build 19046.134 (get from winver.exe)
- TXS distros and miktex distro are in adjacent folders that means
\Tools\texstudio-4.2.2-win-portable-qt5\
\Tools\texstudio-4.2.2-win-portable-qt6\
\Tools\miktex-21-12
- TXS configuration for pdftex (taken from menu:Option > submenu:Config Texstudio > Item:Compilations > field:PDFLaTex) is copy/paste between both TXS distro, that means,
"..\MiKTeX-21-12\texmfs\install\miktex\bin\x64\pdflatex.exe" -synctex=1 -interaction=nonstopmode %.tex
- Miktex report (taken from mpm GUI) is
'
ReportDate: 2022-03-01 13:38:32
CurrentVersion: 22.1
SetupDate: 2022-03-01 10:44:00
SetupVersion: 21.12
Configuration: Portable
GitInfo: 6b3d82b / 2022-01-30 11:05:07
OS: Windows 10 Pro, 64-bit, build 19043
SharedSetup: no
LinkTargetDirectory: C:\Users\user.me\Mine\Docs\git\Tools\miktex-21-12\texmfs\install\miktex\bin\x64
PathOkay: no
LastUpdateCheck: 2022-03-01 11:23:02
LastUpdate: 2022-03-01 10:54:40
LastUpdateDb: 2022-03-01 11:23:01
SystemAdmin: no
RootPrivileges: no
AdminMode: no
Root0: C:\Users\user.me\Mine\Docs\git\Tools\miktex-21-12\texmfs\config
Root1: C:\Users\user.me\Mine\Docs\git\Tools\miktex-21-12\texmfs\data
Root2: C:\Users\user.me\Mine\Docs\git\Tools\miktex-21-12\texmfs\install
UserInstall: C:\Users\user.me\Mine\Docs\git\Tools\miktex-21-12\texmfs\install
UserConfig: C:\Users\user.me\Mine\Docs\git\Tools\miktex-21-12\texmfs\config
UserData: C:\Users\user.me\Mine\Docs\git\Tools\miktex-21-12\texmfs\data
'

For information:
- i have anonymized the Miktex report in this issue report (i.e. user.me is not the right string)
- the behavior is the same with a more complexe tex of mine
- error message seems of the same kind of #1268

**Comment by sunderme** [comment]
this looks rather like a set-up issue with miktex.
First of all, you should run pdf*la*tex , your log say "format=pdftex" ...
I can confirm that it works in principle on a newly installed txs(Qt6)/miktex installation.

**Comment by zballito** [comment]
Thank you for the reply and for the remark.

You are correct, i copied the wrong configuration from one TXS distro to another,
  i.e. i copied pdftex configuration from 4.2.2QT5 (and not pdflatex from 4.2.2QT5) to pdflatex configuration for 4.2.2QT6

Now it works has expected.

Very sorry for this noise.

Issue can be closed.
