### ISSUE TITLE
Makefile [.obj/main.o] Error 1

### ISSUE THREAD

**Issue by THEETB** [texstudio-org/texstudio#2141]
### Environment
- TeXstudio:  2.12.14
- Qt:  5
- OS:  centos 8
- TeX distribution:  Texlive

I am trying install texstudio 2.12.14 on centos 8 using BUILD.sh file with following inputs:
TeXstudio compilation :
----------------------------------------
Enter SYSTEM (1: UNIX ; 2: MACOSX) (default is 1) :
1
Enter PREFIX (/usr , /usr/local or /opt) (default is /usr/local) :
/pkpd/texstudio2
Enter path to QT4/5 (e.g. /usr/lib/qt4, you can leave it empty if qmake is in PATH) (default is ) :

Do you want to use the internal pdf viewer (requires the Poppler library)? (yes/no) (default is yes) :
yes
Do you want to use the video player in pdf files (requires the Phonon library)? (yes/no) (default is no) :
no
Do you want to build a debug or release version? (default is debug) :

Do you want to include tests in the debug build? (yes/no) (default is yes) :
no

### Issue
make: *** [Makefile:5683: .obj/main.o] Error 1
Compilation and installation done
Icons and desktop file can be found in the /prefix path directory

**Comment by sunderme** [comment]
there is way more log which you don't show.
In all likelihood dependencies are missing.

**Comment by sunderme** [comment]
personally I don't like the build script.
```qmake texstudio.pro```
```make -j 8``` 
does it as well.

**Comment by THEETB** [comment]
> personally I don't like the build script. `qmake texstudio.pro` `make -j 8` does it as well.

I tried the above command it is not working. I am getting following issues:
make: *** [Makefile:5707: .obj/manhattanstyle.o] Error 1

**Comment by sunderme** [comment]
not sure how this is supposed to work.
You show incomplete error messages.

apart from that, build requirements are:
BuildRequires:  gcc-c++
BuildRequires:  qt5-qtbase-devel
BuildRequires:  qt5-qtsvg-devel
BuildRequires:  qt5-qtdeclarative-devel
BuildRequires:  qt5-qttools-devel
BuildRequires:  qt5-qttools-static
BuildRequires:  poppler-qt5-devel
BuildRequires:  poppler-cpp-devel
