### ISSUE TITLE
Poor performance after editing text with non-ASCII characters

### ISSUE THREAD

**Issue by LimeHunter7** [texstudio-org/texstudio#2143]
### Environment
- TeXstudio: TeXstudio 4.2.2 (git 4.2.2)
- Qt: Using Qt Version 5.15.2, compiled with Qt 5.15.2 R
- OS: Windows 11
- TeX distribution: miktex

As part of my workflow, I paste in text from one pdf into the text editor to mark up as LaTeX. However, pdf files tend to encode mathematical characters poorly, so strange characters get pasted (which have to be edited into proper LaTeX). For example,
```
For grand unification based on SU(5) to work, there must be a potential for the 24
scalar fields Φa such that Φ = Φaτ a has a minimum in the form of Eq. (28.55).
Consider the most general SU(5)-invariant potential for Φ:
V = −m2tr(Φ2) + a tr(Φ4) + b

tr(Φ2)
2
. (28.73)
```
![image](https://user-images.githubusercontent.com/10647359/156497646-f447301b-e03c-4dba-8b87-6c0374a05f29.png)

### Expected behavior
Previously, TeXStudio could handle these characters just fine, and the editor behaved as normal.

### Actual behavior
Now, however, pasting this text in causes TeXStudio to lag very badly to the point of unresponsiveness, even after deleting all of the non-ASCII characters. Restarting TeXStudio while there are still non-ASCII characters still has degraded performance. Restarting TeXStudio after all of the non-ASCII characters have been deleted, however, restores performance. 

### How to reproduce
Paste the above sample text into TeXStudio's text editor, and observe the performance degradation.

**Comment by sunderme** [comment]
the unicode has not survived the pasting ...

**Comment by sunderme** [comment]
please check if txs/qt6 shows the same issue .

**Comment by sunderme** [comment]
can you provide the text snippet as upload, so that I can test here ?
Default is switched back to qt6. There was a glitch in the build queue which impeded building the qt6 version for a few days, so only qt5 was published at first.

**Comment by sunderme** [comment]
no feedback
