### ISSUE TITLE
Search performance in PDF viewer

### ISSUE THREAD

**Issue by wmeyer48** [texstudio-org/texstudio#2146]
### Environment
- TeXstudio:  4.2.2
- Qt:  5.15.2
- OS: Windows 10
- TeX distribution:   miktex

### Expected behavior
The PDF viewer should locate the first occurrence of my target word

### Actual behavior

- poor response as soon as I enter a character
- no movement in the PDF view
- when it is again responsive to my entry, the edit box content updates, but no search appears to commence

### How to reproduce
Search in the PDF for anything. Every attempt I have made fails, as described.
The viewer seems fine as viewer. It appears to be only the search which is broken.

**Comment by sunderme** [comment]
I would need a screencast and the documents (pdf/tex).

**Comment by sunderme** [comment]
no feedback

**Comment by wmeyer48** [comment]
Sorry, I can't release the text of an unpublished book for debugging. The
behavior of the search operation in the PDF viewer is so profoundly broken
that I am comfortable it will manifest on any large document.

**Comment by sunderme** [comment]
well, I don't see no issue whatsoever in medium sized documents (+100 pages), so nothing I can do.
