### ISSUE TITLE
Texstudio memory progressively takes all memory on computer

### ISSUE THREAD

**Issue by cdmckeon** [texstudio-org/texstudio#2147]
Using Texstudio 4.2, the app starts out using about 3.1gb memory on my win7 computer inclusive of outlook 2010, sometimes ms word, adobe acrobat on and off. Within days however the app is up to about 7.9gb of memory, close to my computer's max of 8gb. I noticed it when building an index. My project is a 750-page book inclusive. The index is 26 pages, 2 columns. I don't recall this problem with Texstudio 4.1 but then again I wasn't building an index until upgrading to 4.2. I don't know if it's the index or not because I'm in a project and can't just create practise jobs to figure it out. Either way, this app should NOT be progressively robbing memory up to the max memory installed. This seems like a bug. If it's a compile issue then the app should flush the memory after a compile. Thx.

**Comment by sunderme** [comment]
probably obsolete

**Comment by cdmckeon** [comment]
What's this mean? What's obsolete? TexStudio 4.2?

**Comment by octaeder** [comment]
since today 4.8.3 is latest version, after 1.5 years of development, new versions from Qt and so on, there are chances that the error has been fixed without notice. So you may want to try latest version.
