### ISSUE TITLE
TOC and structure in Side Panel do not support chapter

### ISSUE THREAD

**Issue by j65ej** [texstudio-org/texstudio#2149]
### Environment
- TeXstudio: VERSION 4.2.2 
- OS: Windows 11

### Description

Only book class is supported. The other classes, such as ebook class, do not display chapter links. 
```
\documentclass{ebook}
\begin{document}
\chapter{title}
\section{title1}
\end{document}
```
Only title1 appears. Version 4.0.0  has no problems.

**Comment by sunderme** [comment]
ctan does not know a class ebook.

**Comment by sunderme** [comment]
no feedback

**Comment by yuki** [comment]
I have a similar problem. In a tex file without document class the "\chapter{}" does not appear in the Structure in the side panel.

I have a master file with the "\documentclss{book}" which include other files.

Mater file:
```latex
\documentclass[10pt,a4paper]{book}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\begin{document}
	\include{1.tex}
\end{document}
```

1.tex
```latex
\part{part 1}
\chapter{asd}
\section{asd}
```

If I open only the 1.tex in the structure only appears the Part and the Section. 

Tested on Texstudio 4.2.2 Appimage (texstudio-4.2.2-x86_64.AppImage)

**Comment by sunderme** [comment]
works fine. 
Do you have custom cwls activated ?

**Comment by yuki** [comment]
I have renamed my $HOME/.config/texstudio  in Linux in order to have the default config (only 2 cwls actived: latex-dev.cwl and latex-document.cwl).

I have tested that if I only open 1.tex the chapter does not appear and it's marked with different color:
![only 1](https://user-images.githubusercontent.com/19482/160284247-1d960762-2d36-40e0-9ce4-c59c0a57c6aa.png)

If I open master.tex and then 1.tex, it's ok:
![master and 1](https://user-images.githubusercontent.com/19482/160284265-93305686-f3da-47d2-b52c-4daa921b4c19.png)

My texstudio is in spanish. If you need me to make some other tests, please tell me.

Thanks!

**Comment by sunderme** [comment]
This is expected behaviour. txs scans the files and determines what active cwls are used automatically. 
If master.tex is not open, txs can't know what class is used and what packages, so it falls back to default cwls (latex-document & latex-dev) and this also means ```chapter``` is not recognized.

**Comment by j65ej** [comment]
Is there a way to tell texstudio to recognize chapter?  Version 4.0.0 is work fine. Is there any change about this in version 4.2.2?

**Comment by yuki** [comment]
The change has been made in 4.1.2, because in the texstudio-4.1.1-x86_64.AppImage  the Structure is complete when 1.tex is opened.

Could it be a good idea to have a setting like "ignore documentclass and show full structure" ?

**Comment by j65ej** [comment]
> The change has been made in 4.1.2, because in the texstudio-4.1.1-x86_64.AppImage the Structure is complete when 1.tex is opened.
> 
> Could it be a good idea to have a setting like "ignore documentclass and show full structure" ?

That would be fine！

**Comment by sunderme** [comment]
just also activate `class-book.cwl`

**Comment by yuki** [comment]
I feel so dumb XD It's working. Thanks!

**Comment by octaeder** [comment]
You may use magic comment
% !TeX root = root-filename
telling what the root document (master doc) is, and in the config dialog select option "Automatically load included files". Hence the informations needed would be known to txs.

**Comment by egninge** [comment]
I had the same issue, played around with the rootfile, made sure the class had the option for chapters. All didn't help.

**Updating to TeXstudio 4.2.3 (git 4.2.3) solved the issue for me!**
(I was on TeXstudio 4.1....)

chapters are shown on the part/chapter/section/... tree at the right and also the error/red highlighting is gone.
