### ISSUE TITLE
TOC GUI has bright green background

### ISSUE THREAD

**Issue by Atcold** [texstudio-org/texstudio#2152]
### Environment
- TeXstudio: 4.2.2
- Qt: 6.2.2
- OS: MacOS 12.2.1
- TeX distribution: texlive 2021

### Expected behaviour
Not have a bright green background.

### Actual behavior
![image](https://user-images.githubusercontent.com/2119355/157325033-4bbfa12c-56dd-47eb-9bd7-aaebe5ab35be.png)

**Comment by sunderme** [comment]
<img width="970" alt="grafik" src="https://user-images.githubusercontent.com/14033169/157499094-c5c609cb-2dc0-451a-b8af-2de9e65565dc.png">

**Comment by Atcold** [comment]
Thank you.
Do you have any idea why the TOC had such background at all? Is it supposed to signify anything? I'm confused.

**Comment by sunderme** [comment]
yes, the color describes which file a section belongs to. In your example, two files are involved for the TOC.
