### ISSUE TITLE
TeXstudio wants to save non-existent document

### ISSUE THREAD

**Issue by andrzej-odyniec** [texstudio-org/texstudio#2153]
After creating a new file (Ctrl-N) and then closing and approving Close without saving, each build (F5 etc.) and closing TeXstudio requires Save As again, although no untitled document is among the open ones. Until TeXstudio is restarted or non-existent documents are saved under the chosen name. When saved, the contents of the file are exactly as when the document was closed without saving. If more files have been created and abandoned, each needs to be saved again and again.
### Environment
- TeXstudio: 4.2.2
- Qt: 5.15.2 with 5.15.2R
- OS: Windows 10
- TeX distribution: miktex

**Comment by sunderme** [comment]
can't reproduce

**Comment by sunderme** [comment]
why are there two "explicit root documents" shown in the structure view ?

**Comment by andrzej-odyniec** [comment]
My project consists of several resulting documents. These are two volumes of sheet music, 200+ and 600+ pages. These are ReadMe files for both sheet music and lyrics. There are also some support files for building an index of all the words in the chants. And others. (of course all in Polish)
It is also a text songbook with the chords of the Neocatechumenal Way, in many versions and formats that share a common source, and the TeX code determines the format and its variations (such as chord tones in selected songs) depending on the keywords in the file name.
I normally compile all of this using operating system scripts (under Windows this is CDM and PS1). Then I enter the file name in the luaLaTeXa -j calling parameter. But I test under TeXstudio, and then I use one of the copies of the startup file under desired keyword form as an explicit root document.
Notes compile 1:30. Textbook 1:00. And ReadMe only takes a few seconds. Therefore, to show the effect, on movie I switched the explicit root document to ReadMe. Normally depending on what I change, tweak and test, I toggle explicitly root multiple times. Especially when I'm working on an included file, because such a file is called from many different copies of the startup file and the starting point can be only forced by setting explicit root.
However, only one such file is set up at a time as explicit root.
The project is non-comercial OpenSource. Both the sources and the built files are in the http://spiewnik.andrzej.odyniec.info directory.
