### ISSUE TITLE
Segmentation fault on mouse-over of window close button

### ISSUE THREAD

**Issue by mwlsyn** [texstudio-org/texstudio#2157]
### Environment
- TeXstudio: 4.2.2
- Qt: Version 5.15.2, compiled with Qt 5.15.2 R
- OS: Linux Fedora 34, 64-bit, GNOME 40.8, Wayland
- TeX distribution: texlive

### Actual behavior
Moving mouse pointer over window close button causes segmentation fault

### How to reproduce
Open Texstudio; mouse over window close button

### Backtrace
SIGSEGV (TXS-Version  R )
[bt] texstudio(+0x2f1776) [0x562f40f10776]

**Comment by mwlsyn** [comment]
Probably a Qt Wayland issue; running 

$ XDG_SESSION_TYPE=x11 texstudio &

makes the problem go away.

**Comment by sunderme** [comment]
so, we can close this ?
