### ISSUE TITLE
Useless leading or trailing spaces in strings to be translated?

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#216]
### Environment
TeXstudio: 2.12.10 (git 2.12.4-618-g0394e9a5)

### Issue
Some strings to be translated have leading or trailing spaces that maybe are useless (probably non exhaustive list):

- `src/webpublishdialog.cpp` line 165: `ui.messagetextEdit->append(tr("  Running this command: ") + proc->getCommandLine());` (double leading space)
- `src/pdfviewer/PDFDocks.cpp` line 501: `label->setText(tr(" Find :"));`
- `src/configdialog.ui` line 1030: `<string>Replaces environment variables in commands.The behavior is OS-specific. ...` (extra carriage return at the end)
- `src/configdialog.ui` line 2493: `<string>Regular expression for TODO comment: </string>`
- `src/configdialog.ui` line 2682: `<string>Automatically switch keyboard layout: </string>`
- `src/configdialog.ui` line 3534: `<string>Server URL: </string>`
- `src/configdialog.ui` line 4541: `<string>SVN Directory Search Depth: </string>`

**Comment by sunderme** [comment]
configdialog is auto-genrated from qt designer, so no (!) manual changes there.
And if there are other spaces in gui element texts, then it was a design choice by the author, so no general changes there either.
