### ISSUE TITLE
Problem at the very first launch

### ISSUE THREAD

**Issue by christiancumini** [texstudio-org/texstudio#2162]
### Environment
- TeXstudio: 4.2.2
- Qt: 5 and 6, in both cases the behaviour is the same (actually the error number is different)
- OS: Windows 11
- TeX distribution: miktex

### Expected behaviour
The expected behaviour is the executable to be correctly launched.

### Actual behaviour
The actual behaviuor is that at the very first launch, an error window pops out and it is told me to send a bug report attaching the file I attached. So it basically doesn't open at all.
I attached the file for the 4.2.2 qt6

Thank you in advance.

### How to reproduce
[texstudio_backtrace1.txt](https://github.com/texstudio-org/texstudio/files/8252264/texstudio_backtrace1.txt)

**Comment by sunderme** [comment]
the second launch works ?

**Comment by christiancumini** [comment]
No it doesnt. The second launch present the same problem. In both cases a
message pops out saying that a log file has been generated (the one I
attached), and if I want to continue in opening the executable files
already open in the texstudio interface may be corrupted (but of course it
was the first time on this computer so I didn't have any file open). I
clicked "continue" and i could see TexStudio in task manager but it was
doing nothing (I waited for about 20 minutes). Just for give you some other
infos, my laptop is a Dell Inspiron (Intel core i7 8th gen, 16GB Ram, SSD
as storage memory, nividia GTX 960 as graphic card)

Il mar 15 mar 2022, 17:56 sunderme ***@***.***> ha scritto:

**Comment by sunderme** [comment]
have you tried a portable edition of txs ?

**Comment by christiancumini** [comment]
Good evening!
With the portable edition the problem seems solved.
Thank you for the support!
Christian
