### ISSUE TITLE
I-beam-pointer leaving a black spot over the line

### ISSUE THREAD

**Issue by suetzjoh** [texstudio-org/texstudio#2164]
### Environment
- TeXstudio: TeXstudio 4.2.2
- Qt: 6.2.3
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
The blinking I-beam-pointer should not leave any black pixels.

### Actual behavior
![grafik](https://user-images.githubusercontent.com/80831883/158791921-704d2620-31d4-4b9c-8dec-4ade937c6341.png)
![grafik](https://user-images.githubusercontent.com/80831883/158793922-3674cc8f-ea7d-48ef-b89b-8cb64c1de5db.png)

### How to reproduce
Whenever you move the pointer in a way that changes the highlighting, i.e. mostly going up and down between paragraphs but sometimes also around curly braces, but only if it is the top most line of the currently highlighted area, at the new spot of the cursor a few pixels above the line remain black. These pixels remain black when you move the cursor within the same highlighted area. 

Moving the cursor by clicking with the mouse doesn't always reproduce this behaviour. You can use this to make several of these black pixels appear on screen at the same time, though not in the same line.

Scrolling or touching a LaTeX-command (those that get highlighted yellow) instantly remove all undesirable pixels on screen.

This issue appeared immediately after updating from TeXstudio 3.1.2 to 4.2.2. As I remember I downgraded back to 3.1.2 from 4.0.1 after facing the same issue.

**Comment by sunderme** [comment]
that is a qt 6 issue. Maybe it is fixed with qt 6.3. 
It is not present with txs/qt5

**Comment by sunderme** [comment]
apart from cosmetics, it is harmless.

**Comment by sunderme** [comment]
no feedback, hopefully resolved with next release.

**Comment by octaeder** [comment]
Following animation (26 images, 2s per image) shows how to reproduce this effect easily:

![txs Qt5 Cursor with dot](https://user-images.githubusercontent.com/102688820/163697237-449ef5ff-2019-4091-a820-67d316d6699f.gif)

- open new editor.
- enter a character in the first line (e.g. \%), so first line is not empty. Press return.
- open a pair of curly braces and enter some characters. Overwrite last brace with a brace, so cursor is at the end.
- move the mouse pointer somewhere between two of the characters inside the pair of braces.
- click to set the pointer there. Watch the blinking cursor to see the dot at the top end of it.
- You can move the cursor left with the arrow left key. Dot stays.
- When the cursor arrives directly right from the brace the dot will move there (watch blinking cursor).

To check if Qt6.3.0 now would resolve the issue, one would have to remove following change: https://github.com/texstudio-org/texstudio/commit/b5be8e4909ee59ff5a0dc4aa7047a4095fbcc8e1
