### ISSUE TITLE
Bib2gls & glossaries-extra

### ISSUE THREAD

**Issue by Martin-2019** [texstudio-org/texstudio#2167]
Dear Maintainers!

It seems to me that it is impossible to stay by the wayside without seeing the developments and new possibilities created by new tools for LaTeX.

Therefore, it seems to me necessary to add support - full - for the glossaries-extra package and the bib2gls tool, in future texstudio editions.

I don't think one can wait for someone else to do it, elsewhere.... or time.

I keep my fingers crossed for success

M.

**Comment by sunderme** [comment]
you can edit your tool setup pretty freely with user commands and user tool chains. So , you can setup everything to use your tool of choice. No need to change any defaults.

**Comment by sunderme** [comment]
no feedback
