### ISSUE TITLE
Ctrl+Alt+Space not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by adinriv** [texstudio-org/texstudio#217]
### Environment
- TeXstudio: 2.12.8 
- Qt: 5.9.5 
- OS: Ubuntu 18.04
- TeX distribution: Texlive

### Expected behavior
The key combinations <kbd>CTRL</kbd>+<kbd>Alt</kbd>+<kbd>Space</kbd> should produce a new environment dialog.

### Actual behavior
No environment, nor error message is produced.

### How to reproduce
On a document press <kbd>CTRL</kbd>+<kbd>Alt</kbd>+<kbd>Space</kbd>.

**Comment by sunderme** [comment]
works fine on lubuntu 18.04
probably a issue with ubuntu desktop/global short cut
