### ISSUE TITLE
Add regular expression support for Extended Search/Replace

### ISSUE THREAD

**Issue by apominov** [texstudio-org/texstudio#2176]
### Describe the feature and the current behaviour/state
Currently, the Extended Search across project files doesn't support regular expressions, even when the respective option is activated in the search dialog. Instead, it tries finding the regex as a literal string, which, of course, fails. Similarly, the corresponding replace function doesn't work either.

The feature, if added, will greatly enhance an already capable feature that allows to search and replace in many tex files at once.

### Who will benefit with this feature?

- Power users working with programmatically-generated tex files (e.g. via pandoc) that all suffer from identical small imperfections fixable by regex (e.g. adding a figure float to a picture)
- Users who utilize the \input{} command heavily
- Everyone who needs a small fix across the project (e.g. replacing space with ~ in certain cases that can be located using regex)

**Comment by sunderme** [comment]
Extended search uses regular expression.
Please provide a screencast to show what you are doing.

**Comment by apominov** [comment]
Thank you. Here is a screencast of a minimal example, I should've appended it in the first place, sorry. 


https://user-images.githubusercontent.com/70207191/160259675-5461e780-78e1-49b3-9a0b-e1d1c2a6a392.mp4

**Comment by sunderme** [comment]
it is actually a subtle bug.
basically extended search used a different regexp engine which insists on ```\{.*\}``` instead of ```{.*}```.
Now it is fixed and uses the same engine as the normal search.
