### ISSUE TITLE
package and class highlighting and completion not working

### ISSUE THREAD

**Issue by mbertucci47** [texstudio-org/texstudio#2178]
### Environment
- TeXstudio: 4.2.2
- Qt: 6.2.3
- OS: Windows 10
- TeX distribution: Miktex

### Expected behavior
Previously packages and classes were highlighted (according to packagePresent and packageMissing colors in settings) and a list was shown in the completer. This stopped working when I installed 4.2.2, but I've tried installing back to 4.1.2 with both qt5 and qt6 and it doesn't work with any of them. All other highlighting seems to work as usual.

My only guess for the cause is that Miktex did recently update.

### Actual behavior
Screenshots:
<img width="287" alt="pkgcolor" src="https://user-images.githubusercontent.com/61854785/160255590-379042de-ce15-4fb0-a243-4f8c38019a44.png">
<img width="377" alt="nocompletion" src="https://user-images.githubusercontent.com/61854785/160255588-e7904c15-1cac-4850-8c0b-5c2d0fbc4479.png">
<img width="152" alt="nohighlight" src="https://user-images.githubusercontent.com/61854785/160255589-632f95d8-11a1-4c1e-a447-37cd531449de.png">

**Comment by sunderme** [comment]
fixed
