### ISSUE TITLE
Left pane text shortened

### ISSUE THREAD

**Issue by larsonmars** [texstudio-org/texstudio#218]
### Environment
- TeXstudio: 2.12.8
- Qt: 5.11.1, compiled with QT 5.10.1 R
- OS: Arch Linux, XFCE4 Desktop environment
- TeX distribution: texlive

### Expected behavior
Text on the left pane should be clipped (using ellipsis) at the (movable) border.

### Actual behavior
Text on the left pane is clipped as if the left pane would be sized to a minimum. The empty space is just white.

### How to reproduce
1. Open TexStudio
2. Create new document
3. type a word in the right pane
4. save to some longer name (e.g., "document_with_longer_name.tex")
--> one can now already see that the name is clipped to early
5. Move the border between the left and right pane (change size of left pane)
--> one pixel change is enough, the left pane gets refreshed and the name can be observed fully (see example screenshot 1)
3. click on the right pane again and enter a single character
4. click in the left pane
--> the text in the left pane gets clipped (see screenshot 2)

![texstudio1](https://user-images.githubusercontent.com/33299122/42174310-25f2083c-7e22-11e8-9770-7687310b7e04.png)
![texstudio2](https://user-images.githubusercontent.com/33299122/42174314-2a380aae-7e22-11e8-9ca3-c0789cd3824a.png)

**Comment by sunderme** [comment]
txs/qt5.10 issue, already fixed in repository
