### ISSUE TITLE
`Option->Configure TexStudio` window is not correctly aligned

### ISSUE THREAD

**Issue by yzhang738** [texstudio-org/texstudio#2183]
### Environment
- TeXstudio: 4.2.2
- Qt: 5.15.2
- OS: Windows 10
- TeX distribution: texlive

### Expected behavior
When `Option->Configure TexStudio` is open, the window should aligned correctly with the screen so that the `OK` and `Cancel` buttons are shown.

### Actual behavior
Currently in 4.2.2, the `Option->Configure TexStudio` window does not show the `OK` and `Cancel` buttons when it is initially opened. This is a degrade from the previous version of 4.0.1 in which it is aligned correctly.

### How to reproduce
Select `Option->Configure TexStudio` and it will show. Here is the screenshot.

![TexstudioProblem3](https://user-images.githubusercontent.com/17606316/160308284-52e3698e-da16-4fb4-befa-dee4b5053fe3.jpg)

**Comment by tmelorc** [comment]
(Not a solution) 
Maximize it to see the buttons.

**Comment by yzhang738** [comment]
Yes, I do maximize each time I open it. But it is a bug anyway compared to a previous version of 4.0.1 in which it works fine. Is there a way to set the default to maximized so that each time it is opened, it is maximized.

**Comment by wmeyer48** [comment]
Very strange. On my system, 4.2.2, Windows 10, I get this:
![TexStudioConfig](https://user-images.githubusercontent.com/19627715/160675775-8e0f3c7a-bec9-4afe-a3cc-e3cafb457505.PNG)

**Comment by tmelorc** [comment]
It depends on the screen resolution, I suppose.

**Comment by yzhang738** [comment]
Yes, it is stranged and looks like it depends on the resolution and computer monitor. But it works fine on previous versions like 4.0.1. What is going on for 4.2? 

A good fix is to add an option to make maximized window default. So each time it opens in maximized.

**Comment by tmelorc** [comment]
> Yes, it is stranged and looks like it depends on the resolution and computer monitor. But it works fine on previous versions like 4.0.1. What is going on for 4.2?
> 
> A good fix is to add an option to make maximized window default. So each time it opens in maximized.

If I'm not wrong, I talked about this issue before and it was fixed on Linux version like that: maximized by default.

**Comment by wmeyer48** [comment]
It is not only about the size at which the form opens. My image, also on the General tab, shows substantially more controls than the one in the original post. And clearly, the controls are not missing for lack of space.

**Comment by tmelorc** [comment]
> It is not only about the size at which the form opens. My image, also on the General tab, shows substantially more controls than the one in the original post. And clearly, the controls are not missing for lack of space.

If you observe, there is a check box on left bottom corner of the maximized window. That box is to show the advanced options which you are referencing.

**Comment by wmeyer48** [comment]
Yes, I overlooked that. I was looking above, for any selection which might open secondary content. Sorry.

**Comment by wmeyer48** [comment]
It would be good for the form to open in last used state, but then a question is how far to take that? Position and size, yes. Last selected page? The Advanced Options checkbox?

**Comment by foreachthing** [comment]
@wmeyer48, advanced options is already remembered since ... a very long time.
I'd find it useful, if the last selected "page" was remembered - within a session (not permanently).

**Comment by sunderme** [comment]
I have implemented that maximized/normal state is remembered.
That should suffice.
