### ISSUE TITLE
Problem in finding available label index

### ISSUE THREAD

**Issue by yzhang738** [texstudio-org/texstudio#2184]
### Environment
- TeXstudio: 4.2.2
- Qt: 5.15.2
- OS: Windows 10
- TeX distribution: texlive

### Expected behavior
If `Cancel` in `ref` is clicked, it should set nothing because this means the author knows which key is available and will set it manually. As an alternative, a new feature could be added in `ref` to set a new index directly (currently new index is not allowed to be set).

### Actual behavior
In order to set a key in \label, it needs to find an available label index. This can be done by clicking `ref` in dropdown list. However, after clicking `Cancel`, it always is set to \label{\ref{}}. (It should set nothing because the key has to be manually input in \label{}.)  See the screenshot. 
![TexstudioProblem4](https://user-images.githubusercontent.com/17606316/160458362-3abf9dea-7a6a-4852-bfe8-f02c3b4efeb9.jpg)

### How to reproduce
Clicking `ref` in dropdown list and then clicking `Cancel` will show the problem.

**Comment by sunderme** [comment]
as it is clearly intentional behaviour, I am not going to change it.

**Comment by yzhang738** [comment]
What do you mean by intentional behaviour?

**Comment by sunderme** [comment]
the author of the code decided that `cancel` gives `\ref{}`. It looks intentional.

**Comment by yzhang738** [comment]
Then you should add another dropdown item for checking the available indexes, or an item of a list for all indexes used so far.

**Comment by sunderme** [comment]
the labels are also listed in the TOC (structure view)
as stated above, insert ref is not changed.

**Comment by sunderme** [comment]
I would recommend to use names for label keys. Typical strategy is prefix "fig:" or "eq:",etc. and a describing name which makes recognizing the right key way easier.
