### ISSUE TITLE
Misaligned & Invisible Page Number in Dark Theme

### ISSUE THREAD

**Issue by Sam-OT** [texstudio-org/texstudio#2186]
### Environment
- TeXstudio: 4.2.2
- Qt: 6.2.3
- OS: WIndows 10
- TeX distribution: miktex

### Issue

The page numbering in the "go to" part of the internal PDF viewer has the numbers misaligned.

![image](https://user-images.githubusercontent.com/81111289/160621731-7c3d6557-5279-4922-951e-4f3dcf04019a.png)

This is hardly a big deal in the picture above. It also successfully rescales with more page.

![image](https://user-images.githubusercontent.com/81111289/160622013-ea62bcbd-7670-4343-ba7c-5df923e48bab.png)

However, there is a serious issue when swapping to dark themes. The first two pictures below are for Orion Dark and the other two for Adwatia Dark (txs). The page numbers should be 15 and 298.

![image](https://user-images.githubusercontent.com/81111289/160622500-781c0038-4576-4382-a071-f70a0b0b497b.png)

![image](https://user-images.githubusercontent.com/81111289/160622230-c7b118c5-a731-4a33-a59e-ee44c9370691.png)

![image](https://user-images.githubusercontent.com/81111289/160622410-047d9119-ef2c-4f19-b623-47a900c0dbd1.png)

![image](https://user-images.githubusercontent.com/81111289/160622323-5006c784-91e0-496d-9da4-1de463ea2adf.png)

Orion Dark has a similar issue with the scaling number at the bottom, but AD doesn't.

![image](https://user-images.githubusercontent.com/81111289/160622847-e0bd110e-3f8f-4a2c-808e-8830bded7e2f.png)

![image](https://user-images.githubusercontent.com/81111289/160622930-3cc1cc70-b9be-4b1e-be35-f2495d78b5d0.png)

I do want to use a Dark Mode, but these issues are a bit annoying...

**Comment by Sam-OT** [comment]
There is a similar issue with the Find box:

![image](https://user-images.githubusercontent.com/81111289/161044058-df15f59d-6e8d-4707-8431-3cf82ae04404.png)

![image](https://user-images.githubusercontent.com/81111289/161044086-96948835-28b3-4d46-bfa6-1e05c5d4880f.png)

The latter should have a red background and say `\congr` inside.

It seems like there a quire a lot of issues with the spacing in Orion Dark. I guess I should stick with Adwatia Dark for the time being.

**Comment by octaeder** [comment]
One point of advice from my experiments: Always start txs new after changes affecting the UI like themes, font sizes etc.

I try to reproduce starting with standard theme and 4.2.2 Qt 5.12.2 as well as dev 4.2.3 Qt 6.2.4. Using font MS Shell Dlg 2 in size 8 or Segoe UI 8 respectively (on second system MS Shell... not available):

The internal pdf-viewer shows nearly perfectly (screenshots showing GIMP zooming 8x):

![grafik](https://user-images.githubusercontent.com/102688820/162822924-99d6c28e-01e0-4a49-9ce2-bc32d73421c5.png)
![grafik](https://user-images.githubusercontent.com/102688820/162823022-bca51a00-5ec7-48ea-a63e-c42b9f55aea2.png)

The ruler shows a small offset of 1 pixel (on a Full HD 1920x1080 screen).

What makes me wonder when looking at your screen shot, is the smaller size of the input field when on page 40. My screenshots show a field of constant size. What screen resolution do you use?

Orion dark (tested only with dev 4.2.3):
![grafik](https://user-images.githubusercontent.com/102688820/162826149-0d1142d5-2ced-4462-aab9-d901d879edea.png)
Interesting: Have a look at the adjustor for font size, you can only go down, the up button (not visible in the image) is far on the right. In standard config they are both on the right.

With orion dark I see an offset of 3 pixels and the number field can only show last to digits of the page number (should be 748):
![grafik](https://user-images.githubusercontent.com/102688820/162825603-b6e33ac6-e3fd-42b2-a841-8acc726db88e.png)

After increasing font size to 16 (Segoe UI) is better (all digits visible now, but offset increased to 4):
![grafik](https://user-images.githubusercontent.com/102688820/162829659-3a52551d-9e28-4392-abf6-9da9a4cc7730.png)

A very close look (or a mouse click :-) shows whats going on with the zoom number field:
![grafik](https://user-images.githubusercontent.com/102688820/162830887-f673f5e8-c4d1-4e43-8be6-424b27eb91d6.png)
The dropdown list indicater moved in. It should be this way:
![grafik](https://user-images.githubusercontent.com/102688820/162831098-70188ed9-d5be-4cfb-a678-4780584df343.png)

Conclusion: Issues of Qt, maybe next version is better.

You may test these settings:
![grafik](https://user-images.githubusercontent.com/102688820/162834881-5811e334-f8dd-43bf-9869-9894253ed062.png)

Looks good to me:
![grafik](https://user-images.githubusercontent.com/102688820/162835163-e0498a74-f4b3-4302-88d5-6699e9843e96.png)
![grafik](https://user-images.githubusercontent.com/102688820/162835599-4f143a38-36cb-4d77-81e5-d4ca7c3d9706.png)
The dropdown list indicator is not present, just click on the zoom number.

Hope this helps a bit.

**Comment by Sam-OT** [comment]
Thanks for your comment and investigation. As you say, hopefully it will improve in later.

These are my settings.

![image](https://user-images.githubusercontent.com/81111289/162924377-8db3593f-25ad-485f-9308-bc073c112aad.png)

It's not so bad with Adwatia, but I guess it's not not so well-optimised. It seems to mostly be the sizing which gets messed up.

![image](https://user-images.githubusercontent.com/81111289/162924887-4ca48692-9bb1-457e-b7ea-30c66c8d20e5.png)

Unfortunately, I had to downgrade back to v3, from v4. There were just too many things which were hindering me with the new thing.[*] As such, I'll have to wait to see if these things are reverted in later versions—or maybe post my own ticket requesting their reversion! As it stands, the misalignment from Adwatia Dark is pretty minimal and isn't causing me undue issue :)

---

[*] Off-topic, but I felt I should justify this statement. Mainly, it's the auto-indenting. This is nice sometimes, but other times I like to use my own manual indenting. It just makes some stuff easier to read. In version <=3, if you paste text, it auto-indents it, *unless* the text is commented out. In v4, it does some hybrid where it auto-indents some stuff and not others.

**Comment by octaeder** [comment]
Did you see the options for "Editor":
![grafik](https://user-images.githubusercontent.com/102688820/162933259-9dee9076-773f-4032-bc64-03c145f14929.png)

**Comment by Sam-OT** [comment]
> Did you see the options for "Editor": ![grafik](https://user-images.githubusercontent.com/102688820/162933259-9dee9076-773f-4032-bc64-03c145f14929.png)

Yes, but unfortunately that was even worse for me 🤦 I like the auto-indentation when typing, but I don't want it when pasting. Naturally, if I paste something in with indents I've made, I want those kept. Anyway, don't want to get this off topic!

**Comment by octaeder** [comment]
Issues regarding find and zoom should be fixed (by Qt version?):

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/5b38d9d1-17d7-4a0a-a240-fd85ee8de71c)

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/86ba1af4-d7c8-44c5-8763-513b22d3a03f)

**Comment by octaeder** [comment]
@Sam-OT You may want to check with current dev version. Find artifacts for download [here](https://github.com/texstudio-org/texstudio/actions/runs/9257435473) (scroll down).

**Comment by Sam-OT** [comment]
> @Sam-OT You may want to check with current dev version. Find artifacts for download [here](https://github.com/texstudio-org/texstudio/actions/runs/9257435473) (scroll down).

Thanks, @octaeder, for the fix (and whoever else was involved) and the link! I'll stick with the stable, not dev, version for now. I'm sure this fix will be in the stable version soon enough 🙂
