### ISSUE TITLE
Regression: \command{label}#r in cwl

### ISSUE THREAD

**Issue by LinweiHe** [texstudio-org/texstudio#2187]
### Environment
- TeXstudio:  4.2.2
- Qt: 6.2.3
- OS: Windows 10
- TeX distribution: 

Assume a new command in latex file
`\newcommand{\refeq}[1]{Equation~\ref{#1}}`

and a cwl file for TeXstudio:
`\refeq{label}#r`

Given a dummy equation with label:
```
\begin{equation}
x=y \label{eqn:dummy}
\end{equation}
```

### Expected behavior
Automatically start completer when typing `\refeq{eqn:`, and display all labels starting with `eqn:`
No problem in TeXstudio 3.0.1, see below:

![image](https://user-images.githubusercontent.com/38001235/160715759-7f3f8395-c40c-4df2-8870-8fcdf2c65e36.png)

### Actual behavior

all labels are shown initially; however, they disappear aftewards, see below:

![image](https://user-images.githubusercontent.com/38001235/160715405-90d76947-0c76-419b-a236-94601f830709.png)

### How to reproduce
Include the commands shown above
Ensure `\newcommand...` is used (no bug if the `\refeq `command is not defined in latex file, however it makes no sense to use an undefined command)

**Comment by sunderme** [comment]
Please post the result of help/check active completion files

**Comment by LinweiHe** [comment]
> Please post the result of help/check active completion files

Thanks. However I am not sure what is the "result of help" or "active completion files".
In Completion setting I only enabled: `Editor\Completion%20Files=latex-document.cwl, mycwl.cwl, tex.cwl`; where `mycwl.cwl `is the user cwl with `\refeq{label}#r` mentioned above

**Comment by muzimuzhi** [comment]
@LinweiHe 
![image](https://user-images.githubusercontent.com/6376638/160825062-2980b09d-01ce-47c8-8d63-c8a1b1e0f023.png)

**Comment by LinweiHe** [comment]
Thanks for the instruction. Here is the file [active_completion.txt](https://github.com/texstudio-org/texstudio/files/8380619/active_completion.txt)

**Comment by dbitouze** [comment]
> `\newcommand{\refeq}[1]{Equation~\ref{#1}}`

Off-topic: you may be interested in the [`cleveref`](https://ctan.org/pkg/cleveref) package which implements features like that in a very reliable way.
