### ISSUE TITLE
FileName field is hidden in Save As Dialog

### ISSUE THREAD

**Issue by jpmcdonald** [texstudio-org/texstudio#2188]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior
You should be able to tab into and see what you are typing in this field.  

### Actual behavior

![Screen Shot 2022-03-29 at 11 26 08 PM](https://user-images.githubusercontent.com/24255029/160751853-fd5710b7-9e94-4990-9e79-06478f337427.png)

### How to reproduce
Select File or File Save As from the main menu.

**Comment by muzimuzhi** [comment]
> ### Environment
> * TeXstudio:
> * Qt:
> * OS:
> * TeX distribution:

Which version of texstudio are you using, and on which OS?

**Comment by sunderme** [comment]
The dialog is provided by qt. So, rather a qt bug.
The os/txs version is important here.

**Comment by jpmcdonald** [comment]
TeXstudio 4.2.2 (git 4.2.2)
Using Qt Version 6.2.2, compiled with Qt 6.2.2 R
OS 12.2.1 Monterey
MacTex-2021

**Comment by sunderme** [comment]
you can try to change options/general/use system file dialog

**Comment by jpmcdonald** [comment]
Thank you.  TeXStudio > Preferences > General 
with Show Advanced Options checked, un-checking use system file dialogs works.   With the option checked, however, I still get the buggy behavior.  So I'll leave whether or not to close this up to the developing team.  Thanks for the help.

**Comment by sunderme** [comment]
qt issue.
