### ISSUE TITLE
Autoinsert math delimiters doesn't work if command takes arguments

### ISSUE THREAD

**Issue by mikeymell** [texstudio-org/texstudio#219]
The new feature works for math commands which are completed with no arguments such as
`\sin` and `\int`, but math delimiters are not inserted for commands with arguments such as
`\frac{num}{den}` or `\int_{min}^{max}`

### Environment
- TeXstudio: git 

### Expected behavior
when enabled, all math commands should be inserted with delimiters, whether or not they have arguments.

**Comment by dbitouze** [comment]
In addition, this feature works if (e.g.) `\sin` is manually entered, but doesn't work if it is inserted from the "Math → Math Functions" menu entry.

**Comment by sunderme** [comment]
1) the cwl list are not complete, so txs does not know all math commands as math commands
2) I have no intention to insert $$ for every possible way to enter commands, this is strictly a completer feature only

**Comment by sunderme** [comment]
we can obviously extend the number of commands, but since the cwls are so numerous, it is far too much for me to do it. So pull-request are welcome.

**Comment by mikeymell** [comment]
@sunderme, that's understandable and I'd like to help. Can you give a brief description of what needs to be done? just a few lines to save me having to scour documentation. At the very least `amsmath`
should work out of the box in the first release in which this feature is on by default, I think.

Furthermore, It seems surprising that the completer recognizes $\int$ as a math command, but not $\int_{min}^{max}$, are you completely sure that's simply a problem with the CWL file?

**Comment by sunderme** [comment]
first you need access to the cwl files. The preferred way would be to clone out github repository (see also https://github.com/texstudio-org/texstudio/wiki/Compiling)
It is not necessary to compile txs, you can place the cwl files in %config%/texstudio/completion/user and adapt them there. The important step is that the math commands in the cwl file need to be classified as math-commands by setting '#m', see [manual](http://texstudio.sourceforge.net/manual/current/usermanual_en.html#CWLDESCRIPTION)
When done, you can either generate a pull-request, which is the easiest way for us, or send the changed files here.

**Comment by mikeymell** [comment]
As I said, `\int` inserts with delimiters while `\int_{min}^{max}#m` doesn't. Grep shows:
```
latex-mathsymbols.cwl
119:\int#m
120:\int_{min}^{max}#m
121:\int\limits_{min}^{max}#*m
```

It doesn't seem like this is just a CWL problem.

**Comment by sunderme** [comment]
okay, my bad. I will look into it, but probably in more detail after release of 2.12.10

**Comment by mikeymell** [comment]
Thanks.
