### ISSUE TITLE
windowed pdf viewer opens empty content view

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2199]
### Environment
- TeXstudio: 4.2.2
- Qt: 5.15.2
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior case 1
If the viewer shows a pdf and you open the contents view (menu Window/Show), then the view should show the pdf contents (if there is one) or No TOC (if there is none).

### Actual behavior case 1
If the windowed viewer starts such that the contents view is not open, then the following happens: If you open the contents view, it will stay empty. If you close the viewer (without closing the contents view), then the contents (or No TOC) will show upon the next start of the viewer. Another workaround is to switch to the embedded viewer, then switch back to the windowed viewer.

Addition:
### Expected behavior case 2
When I preview a pdf of a latex document, then switch to a tab of txs editor of another document and click view, then content view dock and all other pdf information docks of the pdf-viewer should show data of the second document.

### Actual behavior case 2
If any of the docks of the pdf-viewer is open, this works as expected. But if all docks had been closed while viewing the first document then data of the first document may be presented in the docks you open now while viewing the second document. It may even happen that de contents dock shows a mixture of the first and the second document:

![grafik](https://user-images.githubusercontent.com/102688820/173177362-fdc15644-7a3c-4562-b0ed-c25bbdb563df.png)
page 3 is from first document, page 4 is the end of the contents of the second document

**Comment by octaeder** [comment]
I prepared a fix, a PR will follow today.

**Comment by sunderme** [comment]
okay
