### ISSUE TITLE
Previews

### ISSUE THREAD

**Issue by FMuro** [texstudio-org/texstudio#22]
I'm having problems with previews inline, in the preview panel, and as tooltips in Fedora. It's likely to be a problem with packaging. For instance, dvipng is not a dependency so the dvipng preview didn't work at all until I installed the texlive-dvipng package. However I can't figure out what I need for pdflatex preview (pdflatex itself is installed). I haven't been able to find the relevant part of the code here. Any ideas?

**Comment by sunderme** [comment]
pdflatex just generates a pdf.
The previews are generated in /tmp

**Comment by FMuro** [comment]
Thanks for the tip, I've checked the logs in /tmp and have found the package that should be installed as a dependency. I'll report to fedora.
