### ISSUE TITLE
windowed pdf viewer (internal one) shows ghost (copies of) pages instead of background colour

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2200]
### Environment
-    TeXstudio: 4.2.2
-    Qt: 5.15.2
-    OS: Windows 10
-    TeX distribution: miktex

In fact this is an old issue for me. I can't exactly remember but it turned up with one of the last versions 2 or one of the erlier versions 3 in 2020. Eversince I was waiting for an update that would fixe this. But until now no fix was shipped. So I opend this issue today.

### Expected behavior
The windowed pdf viewer should not show ghost pages at the beginning or end of the document.

### Actual behavior
You may trust me that all the nine pages shown in the picture look the same, even so the last eight of them are ghost pages (not really in the document). The last page of the document shows in the top left corner of the grid.
![grafik](https://user-images.githubusercontent.com/102688820/161113700-9ce2fd44-28d5-4ce3-9ba0-f99682afac15.png)
It seems that while going through the pages the viewer does not properly clear areas where a page has been shown but now there is no page any longer. This proposition is based on the observation that right after opening the window and jumping to the end of the document you might see a ghost page that disappears within some seconds and by workarounds given below.

### How to reproduce
Easiest way for reproduction is to use grid 2x1, disable option "single page step" and use a document with at least 2 pages.  Open the windowed viewer and you will see the first page on the right. Scroll to the next page and reverse. Then you will see the second page left to the first one on the right.

To reproduce my image choose a document with p pages and a grid c x r such that p > c  \times r and  c \times r does not divide p (text edited). Choose option "single page step" in the grid menu. Now you have more pages than can be shown in the grid but at the end of the document the grid is not totally filled with pages. Jump to the end (with end key). Now use the cursor left key to scroll one ore more pages back (in my case 8 times). Then go back page by page with the cursor right key. Observe how the last page replicates. If you switch to another window and then back to the viewer, then the ghost pages will disappear. Another workaround is to klick on any page (real or ghost page) and then klick in the gray border. Even so, it happens sometimes (depending on the text) that I'm not aware of the ghost page, what is very irritating.

**Comment by sunderme** [comment]
probably fixed, please try dev build

**Comment by octaeder** [comment]
@sunderme I tested different grids, with or without option "single page step" and couldn't find any ghost pages. This is a great fix for me (and I hope for others too). Many thanks.
