### ISSUE TITLE
UI glitches in version 4.2.2 - text area too small in dialogs and label text alignment seems off

### ISSUE THREAD

**Issue by reaktr4n** [texstudio-org/texstudio#2203]
### Environment
- TeXstudio: 4.2.2
- Qt: 5.12.8 
- Ubuntu 20.04.4 LTS
- TeX distribution: TeX Live

### Actual behavior
1. Label text (in labels and buttons) alignment seems off. In the previous version of TeXStrudio, the text alignment on labels and buttons seemed centred. In version 4.2.2, the text alignment looks bottom aligned.
![image](https://user-images.githubusercontent.com/102540007/161313983-68be6bc4-a361-4793-9597-fdb67c41794d.png)
2. Underscores in text areas (input field) are not seen. It feels like the text area cannot accommodate the text height. For instance, when one needs to save a file, the underscores in the filename are not seen.
![image](https://user-images.githubusercontent.com/102540007/161314592-8778427f-383e-4df0-8b67-c4f798a831ac.png)

### Expected behavior
1. The text alignment on labels and buttons must be centred.
2. Text areas in dialogs must be big enough. For instance, when one needs to save a file, the underscores in the filename must be seen.

### How to reproduce
To reproduce (1), simply make changes in your tex source, and close the tab without saving.
To reproduce (2), simply make changes in your tex source, and hit Ctrl+Alt+S to bring up the Save As.. dialog

**Comment by sunderme** [comment]
That is a Qt/DE issue.
You can try to change the setting options/general/USe system file dialogs.
Nothing I can do.
