### ISSUE TITLE
No file found for Debian 11, 4.2.2, QT 5, amd64 and i386

### ISSUE THREAD

**Issue by MaxPeal** [texstudio-org/texstudio#2204]
like #1318 but now its Debian 11 missing

When I tried to download texstudio via the download link on the website (https://www.texstudio.org/),
I couldn't get the version for Debian 11

I get a 404 error page for 
http://download.opensuse.org/repositories/home:/jsundermeyer/Debian_11/amd64/texstudio_4.2.2-1+3.1_amd64.deb
and
http://download.opensuse.org/repositories/home:/jsundermeyer/Debian_11/i386/texstudio_4.2.2-1+3.1_i386.deb

**Comment by sunderme** [comment]
fixed
