### ISSUE TITLE
Transpose Cursor and Anchor Positions of a Selection (Script)

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2205]
### Describe the feature and the current behavior/state
A selection starts at the anchor and ends at the cursor position. This macro interchanges these. Assume you have made a selection to the right (say with function "expand selection to word", see Menus/Edit/Selections). Now cursor is at the right end of the selection. But you want to include some characters/words to the left of the selection, too. After application of this macro the cursor will be on the left of the selection (by creating the same selection from right to left). Thus you are now able to change the selection on the left.

Script attached [Transpose Cursor and Anchor Positions.zip](https://github.com/texstudio-org/texstudio/files/8401242/Transpose.Cursor.and.Anchor.Positions.zip)

If txs team likes it, you can move it to texstudio-macro. The macro comes with ALT+Y predefined as shortcut.

### Any Other info
Curiously functions "expand selection to word" and "Delete right word" (Editor Basic keys) have the same shortcut Ctrl+D).

**Comment by sunderme** [comment]
Can you make a pull-request for texstudio-macro ?
