### ISSUE TITLE
Auto-completion and magnifier issues

### ISSUE THREAD

**Issue by dense-set** [texstudio-org/texstudio#2206]
### Environment
- TeXstudio:  4.2.2
- Qt:  6.2.3
- OS:  Windows 11
- TeX distribution: miktex

### Anomalous behavior:

1.  The auto-completion on my laptop is behaving weirdly like this:  
![image](https://i.stack.imgur.com/ZdLls.gif)
In particular, everything below the suggestion box disappears.

2. The pdf magnifier is also behaving in an absurd fashion:
![image](https://i.stack.imgur.com/oSOHx.gif)
In particular, I face the following problems in this regard:
    - There are weird horizontal lines as the gif shows.
    - When I release the hold, the lines still remain until I click on the editor space, as the give shows.

### How to reproduce

The above is when default settings are selected from Options. 

_These were **not** present in the earlier versions._

**Comment by sunderme** [comment]
This is q qt issue.
Either use txs/qt5 or wait for the next release.

**Comment by sunderme** [comment]
THis is for the second issue.
Only one problem per issue report.

**Comment by sunderme** [comment]
The other looks like qt issue as well.
