### ISSUE TITLE
Strange scroll if grid with 2 columns and more than one row 

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2208]
### Environment
    TeXstudio: 4.2.2
    Qt: 5.15.2
    OS: Windows 10
    TeX distribution: miktex

### Expected behavior
What ever size the grid has, while scrolling down (or up) all rows of the grid should show next (currently not visible) pages (as far as there are enough pages to fill the rows).

### Actual behavior
Open a document with at least for pages in the windowed (internal) pdf viewer. Disable options continuous (View menu) and "single page step" (grid menu). Chose a grid with 2 columns and 2 or more rows. You will see the first page at top right corner of the grid (observe the page counter in the toolbar showing 1). Now scroll down (mouse wheel or cursor down key) one time. Then the page counter shows 2 because the pages moved up only one single row (second page is now top left). So we see to pages we've already seen. To behave correctly the pages should move up 2 rows. In general, having a grid 2 times r scrolling under these conditions should move r rows  of pages up/down.

### Addition for clarification (edit):
So the first scroll moves out one line. If you scroll further and further down you will observe that from now on **always all rows** of the grid are moved out (not one). In other words the first scrolling down moves out the first row, the only one that contains only one page. After that **all** rows are moved out.

This behavior is inconsistent in many ways:
- First moving out one, and afterwards all rows
- This doesn't happen with grids not having 2 columns
- We would have to make a decisions which behavior we want for enhancement request #2190. Depending on the number of columns same behavior as above if there is exactly only one page in the first row. What if the first row is not fully filled with pages? Do we switch behavior if the first row is full of pages to be consistent?

**Comment by sunderme** [comment]
well, that is debatable. It is for sure one philosophy to to step over n rows, but stepping every row is not wrong.
If someone wants to to change that it is fine by me, but I don't really see a necessity. I would anyway rather use "continous" mode.

**Comment by octaeder** [comment]
I added (edited) clarification to my first comment of this issue. This should point out why this behavior should be changed.
