### ISSUE TITLE
Autoinsert math delimiters should let the cursor inside the math environment

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#221]
### Environment
- TeXstudio: 2.12.10 (git 2.12.4-629-g83285512)

### Actual behavior
If (e.g.) `\sin` is manually entered, the result is `$\sin$|` (with `|` standing for the cursor).

### Expected behavior
 If (e.g.) `\sin` is manually entered, the result is `$\sin|$`, or even `$\sin |$`.

**Comment by sunderme** [comment]
the main intention was to insert something like $\sigma$ without too much hassle, not to write formulas.
So for my purpose the cursor position is fine, i am not convinced that I want to change it.

**Comment by dbitouze** [comment]
AFAAICS, the more usual content of inline maths is multiple elements rather than single element.

**Comment by dbitouze** [comment]
Moreover, for all the math functions, it is much more usual to have something following them, e.g.

- `$\sin x$`

- versus `$\sin$`.

**Comment by sunderme** [comment]
well, not in my case ...

**Comment by sunderme** [comment]
the idea is, when you want a multi element inline math, type $ and continue.
If you need to insert a symbol and don't want to bother with the surrounding dollar sign, insert that symbol directly.
