### ISSUE TITLE
What happened to 4.2.3

### ISSUE THREAD

**Issue by BeerStud** [texstudio-org/texstudio#2212]
### Environment
- TeXstudio: 4.2.2
- Qt: 6.2.3
- OS: Windows 10 PRO
- TeX distribution: Miktex

### Description
The download page lists 4.2.2 as the newest Windows version to download. However, the changelog lists Texstudio 4.2.3. So, what happened to 4.2.3?

**Comment by sunderme** [comment]
4.2.3 is not yet released
