### ISSUE TITLE
Viewer Icons Tiny on High-Res Monitors

### ISSUE THREAD

**Issue by ARockhill** [texstudio-org/texstudio#2215]
I'm running TexStudio 3.2.2, Qt 5.15.2 , with Miktex 4.4 on a Microsoft Surfacebook Pro running Windows 11 Pro, build 10.0.22000

I've noticed that the graphics for some of the Icons in the new version of the TexStudio viewer appear tiny with respect to the size of other icons (see screen clipping below, some buttons on the bottom, like zoom are small as well).  This changed from the prior version.

I've had this same issue with GIMP and was told this sometimes happens with high-res monitors.  Just wondering what might have changed between the new version and the last and I might be able to rectify it.  BTW, some of my other settings (such as word wrap in the editor) changed when I updated the version, so could this be a setting that I am unaware of?

![image](https://user-images.githubusercontent.com/93292682/161755559-2a036330-38dc-43a1-959d-5b0f80087807.png)

**Comment by sunderme** [comment]
qt issue, try the txs/qt6 please.

**Comment by ARockhill** [comment]
Thank you for your advice, but I'm afraid I'm a newbie.  How would I find txs/qt6?

**Comment by octaeder** [comment]
You find current version of txs 4.2.2/qt6 here: https://texstudio.org. Qt is third party software used to build/display graphical elements (gui).

**Comment by ARockhill** [comment]
Great! Thanks.  I'll give it a try.

**Comment by ARockhill** [comment]
Perfect.  That did the trick.  Thanks everyone for the help.
