### ISSUE TITLE
Horizontal scroll buttons for tabs should not be transparent

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2219]
### Environment
- TeXstudio: 4.22  (4.2.3 dev)
- Qt: 5.12.2 (6.2.4)
- OS: Windows 10
- TeX distribution: miktex

### Actual behavior
With 4.2.2 it seems that both scroll buttons are transparent:
![grafik](https://user-images.githubusercontent.com/102688820/162288232-2855f237-6ed5-423e-8956-10d989b61f89.png)

With current dev version (texstudio-win-qt6-4.2.3-202204051806-git_8582ee2) it's 50% better, but we can still see the close symbol of a tab through the scroll to right button:
![grafik](https://user-images.githubusercontent.com/102688820/162289234-8e113f9b-5d4e-4db7-9fc6-b36901c9b309.png)

### Expected behavior
I don't no if some code change to txs did the enhancement or if the higher version of qt is the reason. Maybe the last 50% could also be done? Transparency is irritating in this case. We don't know what will happen on clicking on both symbols at the same time.

### How to reproduce
Open as much tabs or shrink window such that the tab line has not enough room. Scroll totaly to the right then some tabs left.

**Comment by sunderme** [comment]
looks like a qt bug

**Comment by octaeder** [comment]
More details after retest with latest dev version texstudio-win-qt6-4.2.3-202204100727-git_07b27ce.exe:

From scratch open say 5new documents, activate the leftmost tab, resize left txs window border (this will left aling the tabs, so the tabs will move the same way as the border) such that the tabs move under the scroll buttons. You will see that the close buttons of the tabs (never the document names) can be seen under the buttons (both left and right, not only the right one as said before). Following shows a sequence of images while moving left border to the right):

![grafik](https://user-images.githubusercontent.com/102688820/162611977-d0afa635-e850-4a15-8ce1-817ccd2558df.png)

Be aware that the name of the tab doesn't show under the buttons.

So I conclude that in 4.2.2 tab name is visible under scroll buttons, but no longer on from tested version texstudio-win-qt6-4.2.3-202204051806-git_8582ee2.exe (s. first comment). But close buttons show under both scroll buttons.

**Comment by octaeder** [comment]
I first tested current version 4.2.2 Qt5, then two dev versions 4.2.3 Qt6. Now I test current 4.2.2 with Qt6 and I find same behavior as with the dev versions. So it seems that with Qt5 names and close button are visible, with Qt6 only close buttons are visible under the scroll buttons.

**Comment by octaeder** [comment]
With the current TeXstudio 4.2.3 Qt 6.3.0 this issue is still present. I hope that qt will fix it some time.

**Comment by octaeder** [comment]
Since nothing can be done, I close the case.

**Comment by octaeder** [comment]
This only occurs when you choose style windowsvista or default here

![grafik](https://user-images.githubusercontent.com/102688820/179401719-cd489f43-b4fd-4cea-a539-883cffe7d791.png)

**Comment by octaeder** [comment]
still present (TeXstudio 4.4.0, Qt Version 6.4.1, compiled with Qt 6.4.1 R) with settings
![grafik](https://user-images.githubusercontent.com/102688820/204140417-0389c7ce-2b20-4385-9172-cf302bed98b1.png)
but not with
![grafik](https://user-images.githubusercontent.com/102688820/204140427-02a101b8-fffd-4fca-b545-6fb7b1789c9a.png)
![grafik](https://user-images.githubusercontent.com/102688820/204140474-d516b2ec-d6dc-4d2f-aedb-1358cf99be02.png)
