### ISSUE TITLE
Enhance creating bookmarks

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2220]
### Describe the feature and the current behavior/state
Left to the linenumbers of the document is an area where a click creates a bookmark. But with documents with thousands of lines it is not quite clear where this area is. Images show the same document. I tried to depict the area with read lines:

![grafik](https://user-images.githubusercontent.com/102688820/162301052-87520a0c-1574-4706-b99d-ed03f2230636.png)
In the case above about 50% of the area between center bar and line numbers can't be clicked for bookmarks. Moving the pointer as close as possible to the center tool may end up in clicking a tool instead of creating a bookmark. So creating the bookmark is more strenuous.

![grafik](https://user-images.githubusercontent.com/102688820/162300826-c29b00ba-b544-4ce4-9d5f-7460397ba593.png)

Maybe you could make this area more visible in some way, for example with the two lines. Or the columns for bookmarks and line numbers could be interchanged (s. notepad++). Thus both columns would always stay a constant distance from the text area away.

### Who will benefit with this feature?
People using line numbers and bookmarks for large documents.

**Comment by tmelorc** [comment]
Maybe a darker background color on it...

**Comment by sunderme** [comment]
i would rather make the line number part change booksmarks as well.
No real need that the cursor jumps to the line instead.

**Comment by octaeder** [comment]
@sunderme I like your idea not to move the cursor when creating a bookmark, this is sometimes not what I want. Using the numbers at first glance might be good, too. But if I want the cursor at the beginning of a specific line for some purpose it would be easier to click on the number (as it is currently). But I would recommend interchanging both columns as said before. Just let me clarify the reason with two images from documents of different size:

Doc w, 20 Lines:
![grafik](https://user-images.githubusercontent.com/102688820/162494159-457ea354-aa05-4709-b3db-ae98fbe4a34b.png)

Doc with 1000 lines:
![grafik](https://user-images.githubusercontent.com/102688820/162494431-0939e1bb-e49f-4eca-8d01-8d9f800def01.png)

The distance between mark and text is depending of the documentsize (increasing with number of digits of largest line number). I think in this way the eye can better correlate text line and both line number and bookmark.

**Comment by octaeder** [comment]
One note: There might be no line numbers at all or only important ones. And following image the area is quite not clear also:
![grafik](https://user-images.githubusercontent.com/102688820/162996608-1d4618e6-3460-4ea8-b806-7377192f28db.png)

**Comment by octaeder** [comment]
Further note: This column shows both bookmarks and Error Log Markers.

**Comment by octaeder** [comment]
Further note: standard behaviour should be that a left mouse key click sets/removes a bookmark and also moves the cursor at the beginning of this line. Since a right mouse key click opens a bookmark menu, I'm looking for another way to set/remove a bookmark without moving the cursor. @sunderme Could a double click with the left mouse key be that way?

**Comment by sunderme** [comment]
solved by changing cursor shape over the linemarkpanel
65203ccd8a7806289c4529c117d578d3d5626033
