### ISSUE TITLE
Question: MS Visual C++Redistributable Packages needed?

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2225]
On first insall of txs 4.2.3dev in a new VM (Win10 sandbox) these days txs missed C++ runtime lib. Is this normal? I couldn't find any requirements about that for txs. After installation of the redistributables txs started.

**Comment by sunderme** [comment]
txs uses msys2 which should not rely on MS redistributables.

**Comment by sunderme** [comment]
hmm, apparently msys2 mingw64 uses msvcrt, though that should already be on the system
```MSVCRT (Microsoft Visual C++ Runtime) is available by default on all Microsoft Windows versions, but due to backwards compatibility issues is stuck in the past, not C99 compatible and is missing some features.```

https://www.msys2.org/docs/environments/

**Comment by sunderme** [comment]
I did not have any issues on a new laptop, so is the VM stripped down ?

**Comment by octaeder** [comment]
I get the following message:
![grafik](https://user-images.githubusercontent.com/102688820/162639311-3752d51d-f5c0-4e43-8e5c-cfeeb703c35b.png)

What I use is the sandbox of Windows. It is only present on Windows 10 Pro and Enterprise but not home:
![grafik](https://user-images.githubusercontent.com/102688820/162639605-44aeaefc-d5e5-4724-8b6f-b92418014de5.png)

The Windows in the SB says:
![grafik](https://user-images.githubusercontent.com/102688820/162639629-45b84830-bdfb-4a5d-aff0-df6c9b69b511.png)

The only thing I do is installing txs and starting it. Maybe you can test it in this way. But it might not be worth it, since normal install on windows is ok. I can't remember how it was when I installed txs years ago.

**Comment by sunderme** [comment]
seems to be a special case

**Comment by octaeder** [comment]
These days I closed my sandbox and set-up a new one (which happens quite frequently due to windows updates, problems with the sandbox ...), but fogott to install the redistributables. Even so txs started. No idea what happend.

**Comment by sunderme** [comment]
usually MS redistributables should not be necessary
