### ISSUE TITLE
opening a document doesn't refresh structure and TOC view while sidebar is hidden

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2228]
This issue is analog to issue #2199 but for the side bar (structure and TOC view) in txs. When I open a document (recent file dialog or klicking dataset) and open the side bar after the document has been loadad then structure view and TOC view should show the content of that document. They should not stay empty and should not show data of other documents until switching to another tab.

As a workaround one can switch between the views. This will refresh data.

I observed this with current version 4.2.2 Qt5, miktex on Win10.

**Comment by sunderme** [comment]
I don't understand
The issue is that, if the document does not have any sections/etc. the structure view shoul not show no content ?
Please illustrate

**Comment by sunderme** [comment]
works fine here.
Screencast ?

**Comment by octaeder** [comment]
Start say with no doc. View is of course empty:
![grafik](https://user-images.githubusercontent.com/102688820/162785197-1b53b4d0-6027-413f-b566-d6079226dfc9.png)

Close side bar:
![grafik](https://user-images.githubusercontent.com/102688820/162785290-f17f958a-bdd5-43d5-9631-893360446ab2.png)

Open/load a document with structure:
![grafik](https://user-images.githubusercontent.com/102688820/162785488-a2a79b8b-a990-4a12-867c-d8b771330ba4.png)

Open side bar:
![grafik](https://user-images.githubusercontent.com/102688820/162785740-590f009a-a0e6-47e6-b95b-7d28798b467e.png)
No structure, even so tab is active.

Switch to TOC (which is now refreshed):
![grafik](https://user-images.githubusercontent.com/102688820/162786105-33f95958-4ff7-4111-8adb-0b44aa3841a8.png)

Switching back to strucure will also refresh it.

**Comment by octaeder** [comment]
In the same manner the structure breaks when you "save as" the loaded doc while the side bar is closed. It will not reflect the new name, shown in the tab. Even more the structure hilites the old name red even so the dataset has not disappeared (renaming creates a new dataset).

**Comment by octaeder** [comment]
Closing a tab while side bar is closed, still datasat (the second one included by the first one) is shown in the structure:
![grafik](https://user-images.githubusercontent.com/102688820/162791449-5af68012-682a-4455-aab5-aae5f25972cc.png)

Idefix resolves the problem

**Comment by octaeder** [comment]
Wrong name after "save as" (should be ...5_test.tex)
![grafik](https://user-images.githubusercontent.com/102688820/162792333-0c22cbe1-990c-4436-b5e3-37444f1b9916.png)

Click on master in structure, old include seems missing:
![grafik](https://user-images.githubusercontent.com/102688820/162792906-e2960051-159d-4e64-a5ac-3a54c9fa1aea.png)
Idefix won't help

**Comment by octaeder** [comment]
Thanks!
