### ISSUE TITLE
Launch TXS with specified settings directory doesn't work

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#223]
### Environment
- TeXstudio: 2.12.10 (git 2.12.4-642-gb7ef662a)
- Qt: version 5.9.4
- OS: Linux Mageia 6

### Issue
I tried to run TXS from the command line with a configuration file different from the default one (located in `~/.config/texstudio/texstudio.ini`), where I only changed `Interface\Language=fr` to `Interface\Language=en`. The other `texstudio.ini` being in my current (sandbox) directory, I run:
```bash
texstudio --config ./ &
```
but TXS is still open with French as language interface. The same happens with an explicit, absolute, path for the settings directory.

**Comment by sunderme** [comment]
the code says that the command option is only used in "portable-mode" which means that the application needs to reside next to a "config" directory.
Hence an installed txs does ignore the option ...

**Comment by dbitouze** [comment]
>could you try `texstudio --ini-file ./ &`

Same result.

>Hence an installed txs does ignore the option ...

Too bad.

Thanks anyway.

**Comment by dbitouze** [comment]
Works nicely, thanks!
