### ISSUE TITLE
Code folding showing headers only

### ISSUE THREAD

**Issue by Atcold** [texstudio-org/texstudio#2236]
### Describe the feature and the current behaviour/state
I would love to be able to fold all text following any heading up to the next one, regardless of the level, collapsing everything down to the TOCs.
Currently, if I close a section, all the following subsections will disappear.

### Who will benefit from this feature?
Who writes lengthy hierarchical chapters.

### Example
In the screenshot below, I would like to be able to see only the purple headings. I don't need to see the text right after the `\section`, since I'm not going to edit it. Meanwhile, I'd possibly want to open a different earlier fold, for context. Having additional text in between adds distraction and takes vertical real estate away.

![image](https://user-images.githubusercontent.com/2119355/163018143-9ae5cd36-a661-47ed-9ff9-afde5f538d05.png)

*Additionally, the `\displaystyle` equation doesn't seem to be willing to be folded on its own.*

**Comment by sunderme** [comment]
that is not possible.
The internal structure is organized as a tree.

**Comment by Atcold** [comment]
I understand that 'pure text' belongs to the lowest tier of the tree, correct?
The hierarchy should be some sort of

 1. part
 2. chapter
 3. section
 4. subsection
 5. subsubsection
 6. paragraph
 7. text

What I'm trying to achieve is collapsing only level 7, regardless of the heading it follows.

**Comment by sunderme** [comment]
"text" is not part of the hierarchy

**Comment by octaeder** [comment]
Isn't this in most cases what the side bar shows in the TOC view? s. images [here](https://github.com/texstudio-org/texstudio/issues/2237#issuecomment-1097202083)

**Comment by octaeder** [comment]
Would it be possible to have a context menu for the root node in the TOC view with entries "Open Document" (this should also be the mouse click action for the node), "Expand Subitems" and "Collapse Subitems"? The latter would help seeing the sections (part, chapter, section etc.) of the document at once (ok, sometimes with included datasets).

**Comment by octaeder** [comment]
> 
> _Additionally, the `\displaystyle` equation doesn't seem to be willing to be folded on its own._
>

I discussed your remark in #2240. Advise: use displaymath env or equation* env. If you find that your formula doesn't fit in one line (or other reasons), then you can easily change the env name, s. #2241).

**Comment by octaeder** [comment]
There is a workaround to do nearly what you like to have. I use special comments \% BEGIN_FOLD and % END_FOLD. Such a block is foldable. If you have something like this in your editor for example:

![grafik](https://user-images.githubusercontent.com/102688820/163579594-9adf5b3a-5a08-4d03-9ca9-efcf48cc0ded.png)

Then calling my script macro opens two new editors (changes needed are not done in the original source):

![grafik](https://user-images.githubusercontent.com/102688820/163579759-137d4c92-8449-4233-b752-c9e081b3c35e.png) ![grafik](https://user-images.githubusercontent.com/102688820/163580719-f5ef6fa7-8f06-48c9-8ada-a9e235f73c33.png)

The left one tells you in which line of the right image which sectioning was found. Accordingly new foldable blocks were created and folded.

The macro is sure far from perfect (it doesn't recognize includes etc.), but it might be usefull to you:

```
%SCRIPT
tl = editor.document().textLines();
sections = "";
documentFound = false
folding = false;
foldlines = [];
for (i = 0; i < tl.length; i++) {
  line = tl[i];
  if ( line.includes("\\begin\{document\}") ) {
    i++;
    sections = sections + i + ": " + line + "\n";
    tl.splice(i,0,"\% BEGIN_FOLD");
    foldlines[foldlines.length] = i;
    folding = true;
  } else {
    if ( line.match(/\\(part|chapter|section|subsection|subsubsection|paragraph)[^a-zA-Z]/) !== null )
    {
      if ( folding ) {
        tl.splice(i,0,"\% END_FOLD");
        i++;
        folding = false;
      }
      i++;
      sections = sections + i + ": " + line + "\n";
      tl.splice(i,0,"\% BEGIN_FOLD");
      foldlines[foldlines.length] = i;
      folding = true;
    } else {
      if ( line.includes("\\end\{document\}") ) {
        tl.splice(i,0,"\% END_FOLD");
        i++;
        sections = sections + (i+1) + ": " + line + "\n";
        folding = false;
      }
    }
  }
}

app.fileNew();
newEditor = documentManager.currentDocument.editorView.editor;
newEditor.setText(sections);

app.fileNew();
newEditor = documentManager.currentDocument.editorView.editor;
newEditor.setText(tl.join("\n"));

for (i = 0; i < foldlines.length; i++) {
  newEditor.document().collapse(foldlines[i]);
}
```

**Comment by sunderme** [comment]
no action planned for this idea, closing
