### ISSUE TITLE
\input'ed documents show up in the TOC

### ISSUE THREAD

**Issue by Atcold** [texstudio-org/texstudio#2237]
### Environment
- TeXstudio: 4.2.2
- Qt: 6.2.2
- OS: MacOS 12.2.1
- TeX distribution: texlive 2021

### Expected behaviour
Document structure and TOC should not be duplicates.

### Actual behaviour
The TOC shows external `\input`ed documents, which clearly don't belong to the table of contents.
These files are already shown in the structure panel.

### TOC
![image](https://user-images.githubusercontent.com/2119355/163014348-8b6c0429-c38f-49bc-913a-1bc6c21fd32a.png)

### GUI's incorrect TOC
![image](https://user-images.githubusercontent.com/2119355/163014123-31d184ee-8594-498c-ae44-ecd16ca33833.png)

### Structure
![image](https://user-images.githubusercontent.com/2119355/163013400-d6dd5e3b-a84b-4dad-9e3c-811b584e00ba.png)

**Comment by sunderme** [comment]
TOC is for fast file navigation. It does not preview the latex toc.

**Comment by sunderme** [comment]
Structure panel shows individual files, TOC is a superset which encompasses all files. Included files are (only) shown if they do not contain sections. Otherwise it would be impossible to navigate to them via TOC. In your case, you may not desire it, but other may put text parts inside those files.

**Comment by octaeder** [comment]
I have some questions please:
![grafik](https://user-images.githubusercontent.com/102688820/163045126-dace393f-613e-43d9-97ec-a2428a8acd5d.png)
Files Titelei and Ende are both included in the root file. Why the far indentation of Ende? Why can't we see the bib-File that is shown in the structure (\addbibresource{xxx.bib} in the root file)? Why isn't the tab with the root file activated when I click on the root file in the TOC (nothing else happens)?

Following pic shows two sets of sections that are included from different files in the parent chapter. Is this the reason why the sections in the first area are green while the others in the second area are gray? Thought it would always be some green (as said in the configuration).
![grafik](https://user-images.githubusercontent.com/102688820/163048136-5b18b2e6-cea4-40ce-8103-3c4d42bb750a.png)

**Comment by sunderme** [comment]
the color indicates that entries belong to the same file. different color, different file,

the indentation of files corresponds where in the toc the contetnt would be placed. here as partnof the section.

**Comment by Atcold** [comment]
> Structure panel shows individual files, TOC is a superset which encompasses all files. Included files are (only) shown if they do not contain sections. Otherwise it would be impossible to navigate to them via TOC. In your case, you may not desire it, but other may put text parts inside those files.

I'm confused.
A LaTeX document is supposed to be split across multiple files that are `\include`ed in the main file.
A selective compilation is controlled by the `\includeonly` macro.
Navigating to `\input`ed files is performed through control / command click on the file name in the main text.
The TOC should let me navigate the document, not the file tree.

Follow up question.
Can we have a checkbox that let us hide external files from the TOC?
If there are tens of headings and tens of `\input`ed files, the TOC is just unusable.

**Comment by sunderme** [comment]
won't change

**Comment by Atcold** [comment]
Oh, I think I understand what's going on.

In issue #2258 it's shown that if an included document starts with a heading, that is used in the TOC.
A file without headings should not be displayed in the TOC.

Currently, all my drawings are shown in the TOC, which makes no sense whatsoever.
Please, correct me if I'm mistaken, but this is a bug.

**Comment by sunderme** [comment]
this is intended behavior, hence by definition not a bug.

**Comment by Atcold** [comment]
Do we agree on the following?

> A file without headings should not be displayed in the TOC.
