### ISSUE TITLE
misalign of check boxes on Build config window

### ISSUE THREAD

**Issue by tmelorc** [texstudio-org/texstudio#2238]
### Environment
- TeXstudio: 4.2.3 (git 4.2.2-88-g8582ee24b)
- Qt: Version 5.12.8, compiled with Qt 5.12.8 R
- OS: Linux Mint 21
- TeX distribution: texlive

### Expected behavior
Open the Configure window and go to Build group.
Check boxes left aligned also on left column.

### Actual behavior
![Seleção_001](https://user-images.githubusercontent.com/15181573/163231334-f2413aaf-b6c6-4dbd-94f2-d4d384255b50.png)

### How to reproduce
Open the Configure window and go to Build group.

**Comment by sunderme** [comment]
works fine on ubuntu
looks like a local glitch

**Comment by tmelorc** [comment]
> works fine on ubuntu looks like a local glitch

Ow, checking the ui from source, it looks ok. 
Strange. Any idea?
Not important but I like aligned boxes.... lol

![Seleção_002](https://user-images.githubusercontent.com/15181573/163234065-4068530e-7283-4b0d-90a6-62eed624c09b.png)

**Comment by sunderme** [comment]
no idea

**Comment by tmelorc** [comment]
Observing the ui, the `spinBoxRerunLatex` belongs to `scrollAreaPaths`, but since it is on the right of the `label_38` _Maximum Compile Repetitions:_, I suspect that it should be outside that `QScrollArea`.

Anyway, please, don't worry with this. If I discover, I'll inform here.

![Seleção_003](https://user-images.githubusercontent.com/15181573/163236306-456875c0-6e7e-4ed8-8807-b0c304437915.png)

**Comment by tmelorc** [comment]
Just to inform, I changed from `plastique` to `cleanlooks` and it works.

![Seleção_004](https://user-images.githubusercontent.com/15181573/163242307-e4864f02-6d7e-42b1-b17a-9bef0c76e654.png)
