### ISSUE TITLE
crash on Windows 10

### ISSUE THREAD

**Issue by jrf1968** [texstudio-org/texstudio#224]
Hi. TexStudio 2.12.8 has suddenly started to hang - it happens sometimes when there is a simple LaTeX error (e.g. missing // in a longtable). Not all LaTeX errors cause trouble. Only solutions is to reboot my computer since shutting down and re-starting does not work (hangs on re-opening). I'm using Windows 10.

**Comment by sunderme** [comment]
we need a reproducible test case ...
(and there is a reason why there is a template when you create an issue...)

**Comment by jrf1968** [comment]
Nice and friendly. I'll use TexPad on my MacBook.

**Comment by sunderme** [comment]
pretty sensitive ... the comment above is in no way abusive, I am just stating what is needed to resolve *your* problem and the reponse time is below an hour.
