### ISSUE TITLE
Q: displaymath env is foldable, should equivalent \[ \] be so, too?

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2240]
This is an open question by Alfredo in #2236. What does the expert say?
This said, the txs LaTeX help recommends using displaymath env.

**Comment by sunderme** [comment]
matter of taste.

**Comment by sunderme** [comment]
but in the example given, you would only see ```\[``` in the folded state which seems pretty useless. Also folding three lines is also not really helpful. So if someone wants to change it, sure but there is no real argument for it.

**Comment by octaeder** [comment]
Number of lines depends on formula. It's more a question of consistency. Manual says "Normally every structure command marks a start of foldable range, and every environment or TeX group constructs a foldable range." So we sum up this case under not normal cases, and I suggest closing the issue. Would you please do so?
