### ISSUE TITLE
no mirror-cursor activated on env name in some case

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2241]
Manual says: If you place the cursor on an environment name _or the corresponding begin- or end-command_, after a moment a mirror-cursor is activated on the environment name...
But when I set the cursor in the middle of \begin, no mirror cursors appear.  What's wrong, code or manual?

txs current 4.2.2 Qt5 for Win10

**Comment by sunderme** [comment]
manual

**Comment by octaeder** [comment]
shall I change it to "If you place the cursor on an environment name after a moment a mirror-cursor is activated on the environment name...", or do you make the change?

**Comment by sunderme** [comment]
you can make it.
Comma is missing before "after"
