### ISSUE TITLE
Check for updates not correct in some case

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2244]
With current txs 4.2.2 Qt5 on win10 I observe following: Open config dialog. It shows Update Level "Stable Releases". I change this to "Dev. Versions" and let immediately check for updates (do not close config dialog). Dialog says "txs is-up-to date". Of course this is not true. Close and reopen config dialog. I see Update Level "Dev. Versions" as expected. Check for updates now shows as expected:

![grafik](https://user-images.githubusercontent.com/102688820/163684031-637ca55a-663e-4bee-9cb0-62207759bc07.png)

If you now change to "Stable Release" without closing config dialog will show prev. image.

### Expected behavior
Check correctly for updates according to (changed) setup without closing config dialog.

**Comment by octaeder** [comment]
I think there are more problems. I do following with 4.2.3-202204170759-git_2587d77 (i.e. current 4.2.3 for Win10). Config is already set to Update Level "Dev. Versions", when I open config. I let check for updates. Dialog says "up-to-date". This can't be true, since dev. version texstudio-win-qt6-4.2.4-202204171341-git_bfa2b8c already exists.

**Comment by muzimuzhi** [comment]
> I think there are more problems. I do following with 4.2.3-202204170759-git_2587d77 (i.e. current 4.2.3 for Win10). Config is already set to Update Level "Dev. Versions", when I open config. I let check for updates. Dialog says "up-to-date". This can't be true, since dev. version texstudio-win-qt6-4.2.4-202204171341-git_bfa2b8c already exists.

In my understanding, Dev. Versions is not per-commit builds, but still have to be [git releases](https://github.com/texstudio-org/texstudio/releases).
 - git release `x.y.z` like 4.2.3 -> stable release, release candidate, dev. version
 - git pre-release `x.y.z`rc`n` like 4.2.3rc1 -> release candidate, dev. version
 - git pre-release `x.y.z`beta`n` like 4.2.2beta1 -> dev. version
 - git pre-realse `x.y.z`alpha`n` like 4.0.0alpha2 -> none of the three update levels

See related source code [`void UpdateChecker::parseData(const QByteArray &data)`](https://github.com/texstudio-org/texstudio/blob/e5098eaa06341503cd31ac494c4a2ccdef081985/src/updatechecker.cpp#L85-L170).

**Comment by octaeder** [comment]
Thanks for your clarification. So it remains the first issue, that the check button uses the value for the update level as it was before opening the config panel.

**Comment by sunderme** [comment]
txs only looks at releases, i.e. beta/rc.
I have to check if it looks for alpha

**Comment by octaeder** [comment]
I work on this. The code from updatechecker doesn't take alpha into account. I will change this. Otherwise if no beta had been released then alpha version would not be offered (even so they are listed on the [website](https://github.com/texstudio-org/texstudio/releases/) given). A current screenshot follows:

![grafik](https://user-images.githubusercontent.com/102688820/173188414-82acbd2b-98f2-4bc7-985c-fda9bb12217d.png)
It might be irritating, that it is version 4.2.4 which never existed. In fact it is 4.2.3 which has been released some days before a fix by sunderme was commited on April 20<sup>th</sup> to fix #2253.

I will remove the useless "(0)" and use the names as listed on the given webpage, i.e. 4.3.0beta1. Or someone changes the website to show f. ex. 4.3.0 beta1 (e.g with blank delimiter). That would be nice, too. But in any case without parenthesis.

I will also add attributes to the message box, such that one can use mouse or cursor to select the text, as you can see it here (test version):

![grafik](https://user-images.githubusercontent.com/102688820/173191435-3fbb1056-9485-473a-b8fd-1da7a1a2a324.png)
In fact, I faked the version here, since 4.3.0 is derived, so no updates would be available. About Dialog shows _TeXstudio 4.3.0 (git )_. Hm, this is a little bit odd. Well, my self compiled version is not on git :-)

Comments are welcome.

**Comment by octaeder** [comment]
### Preliminaries

* Version: We assume that _version number_ is of the form integer<sub>1</sub>.integer<sub>2</sub>.integer<sub>3</sub>. Either nothing more follows then we set _version type_ to stable and _version revision_ to 0. Or a type string (exactly one of "rc", "beta", or "alpha", any case) and a revision number (natural number, not zero) follow immediately the version number (no blanks etc., s. code example below).
* Data: We assume that the data string retrieved from git repo holds versions in increasing order, i.e. older comes before newer (s. code example below).

### Affected code
updatechecker.cpp and utilsVersion.cpp

### Data from git repo and for testing

Data retrieved from github repo (123 versions) is a string of the following form:
```
[{...},{...},...,{...}]
```
Each pair of braces holds a data item for one version. Example (first data item):
```
"ref":"refs/tags/1.8.1","node_id":"MDM6UmVmMTEyMzcwNzY1OnJlZnMvdGFncy8xLjguMQ==","url":"https://api.github.com/repos/texstudio-org/texstudio/git/refs/tags/1.8.1","object":{"sha":"ef685c7e85c6045c35e6c25580030ad6f548f5f0","type":"commit","url":"https://api.github.com/repos/texstudio-org/texstudio/git/commits/ef685c7e85c6045c35e6c25580030ad6f548f5f0"}
```
Test data is a cut down of the original data. This is done by using a subset of the following code as needed:
```
result = QString(" ")
+ "{\"ref\":refs/tags/3.1.2,"
+ "{\"ref\":refs/tags/4.0.0alpha1,"
+ "{\"ref\":refs/tags/4.0.0alpha2,"
+ "{\"ref\":refs/tags/4.0.0alpha3,"
+ "{\"ref\":refs/tags/4.0.0alpha4,"
+ "{\"ref\":refs/tags/4.0.0alpha5,"
+ "{\"ref\":refs/tags/4.0.0alpha6,"
+ "{\"ref\":refs/tags/4.0.0alpha7,"
+ "{\"ref\":refs/tags/4.0.0alpha8,"
+ "{\"ref\":refs/tags/4.0.0beta1,"
+ "{\"ref\":refs/tags/4.0.0beta2,"
+ "{\"ref\":refs/tags/4.0.0beta3,"
+ "{\"ref\":refs/tags/4.0.0rc1,"
+ "{\"ref\":refs/tags/4.0.0rc2"
;
```
So parsing data still runs as usual, but we can control evolving of different cases. Current version is simulated by code similar to:
```
currentVersion.versionNumber = "3.1.2";
currentVersion.type = "stable";
currentVersion.revision = 0;	
```

### Test cases

Update panel is slightly changed to show test information:
- title shows index of update level according to combobox (0=stable, 1= release candidate, 2 = development)
- bottom of the panel shows current simulated data for versions (s. above), so we can figure out whether result is correct

These will be removed later on.

#### Update level 2 and 1 find current dev alpha5 and stable (no rc available)
![grafik](https://user-images.githubusercontent.com/102688820/173253799-f4e08c1a-cbe2-44d3-81e1-56776b7ebc11.png)
![grafik](https://user-images.githubusercontent.com/102688820/173253830-ffb24d43-7592-49a0-872e-5ed3b91225d8.png)

#### Update level 2 and 1 find current dev beta2 and stable (no rc available)
![grafik](https://user-images.githubusercontent.com/102688820/173253916-2d6ce64b-af35-482c-9074-bbe3392a401a.png)
![grafik](https://user-images.githubusercontent.com/102688820/173253918-4807e7a1-acb5-415a-8933-41a35f745729.png)

#### Update level 2 and 0 find current release candidate rc2 and stable
![grafik](https://user-images.githubusercontent.com/102688820/173253978-913e43d5-7b5b-4f25-baca-40b1d9c82e81.png)
![grafik](https://user-images.githubusercontent.com/102688820/173253982-19aa8fa2-d45a-43e4-b9b5-3728b895f6af.png)

#### Update level 2 finds current rc2, and level 0 finds current version to be current stable
![grafik](https://user-images.githubusercontent.com/102688820/173254061-ac5760a1-6173-45c1-855d-ba5a8a9c9d9e.png)
![grafik](https://user-images.githubusercontent.com/102688820/173254164-921bd6e5-fc65-45aa-87cf-17d615537e5f.png)
I've enhanced the message to show the current version.

#### A case that will never more appear (we hope)
![grafik](https://user-images.githubusercontent.com/102688820/173254272-4249feb8-e679-4516-8168-0a361407f0a8.png)
This case shows what would have happend, when TeXstudio project started working and released alpha2 after alpha1 while user app still is alpha1.

#### GUI properties
Text in the panel can be selected and a mouse click on the link opens the website.

### Open tasks
Changing update level has only an effect when reopening config dialog. Am not sure if I can fix this.

**Comment by octaeder** [comment]
update check with my final version _TeXstudio 4.3.0 (git 4.3.0beta1-23-g486d93e46)_ where update level is _development versions_:

![grafik](https://user-images.githubusercontent.com/102688820/173281216-63553e1c-526a-4222-978d-2ff55309113c.png)
Be aware that version 4.2.3 did only show the version number and revision in parentheses (type missing) of the current version. But this is only correct for stable versions.
