### ISSUE TITLE
Dependency on libgcc1 always set to the exact same version as TeXstudio in texstudio.spec

### ISSUE THREAD

**Issue by TomJampen** [texstudio-org/texstudio#2245]
There seems to be an error in your script that is updating the version numbers, e.g. see the last change in [commit "increase version number" for TeXstudio 4.2.3](https://github.com/texstudio-org/texstudio/commit/71017fb1c784e1087c60ed59e3c9d6dfdcaa47db).

The required version of libgcc1 as reported in texstudio.spec is incremented with each TeXstudio version since TeXstudio version 4.1.2. Before, the required libgcc1 version was 4.1.1. Starting with the change from TeXstudio version 4.1.1 to 4.1.2 it was always updated to be set to the exact same version as TeXstudio.

Regards
Tom

**Comment by sunderme** [comment]
libgcc is currently at >10, so that number is pratically irrelevant.
