### ISSUE TITLE
Structure and TOC offer vert. scroll bar to late

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2249]
txs 4.2.3 Qt 6.3.0 (current for Win10, standard theme) offers a horizontal scroll bar, if column is to narrow:

![grafik](https://user-images.githubusercontent.com/102688820/163735063-f8b60652-f795-47c7-8e8c-0b0ea6a39ba9.png)

Image shows the point where a very small increase in width of the column suffices that the scroll bar disappears. This beaviour doesn't take into account the length of the lines in the structure nor in the TOC. In the image above the length is roughly 6x of the visible text length. And be aware that the scroll bar nearly can't be moved to the right.

**Comment by sunderme** [comment]
this is qt behaviour

**Comment by octaeder** [comment]
I hope this is not intended behaviour of qt, cause this scroll bar is useless. Since nothing can be done here, I'll close the case.
