### ISSUE TITLE
user-defined commands not recognized if in "definition" arg

### ISSUE THREAD

**Issue by mbertucci47** [texstudio-org/texstudio#2252]
### Environment
- TeXstudio: 4.2.3
- Qt: 6.3.0
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
Commands defined by the user, even if only locally, should be recognized by the syntax highlighter.

### Actual behavior
If the command definition appears in a "definition"-type argument, like that of `\newcommand` or `\newenvironment`, the completer and syntax highlighter doesn't pick it up. I assume this is because there is no syntax checking in "definition" arguments.

### How to reproduce
<img width="217" alt="screenshot" src="https://user-images.githubusercontent.com/61854785/163841040-897f800d-2e87-4a1b-82c3-f9334ea7b064.png">

Here's the code to reproduce:
```
\documentclass{article}

\newenvironment{myenv}{
	\begin{itemize}
	\def\myitem{\item[$\dagger$]}
	}
{\end{itemize}}

\begin{document}

\begin{myenv}
\item foo
\myitem bar
\end{myenv}

\end{document}
```

**Comment by sunderme** [comment]
correct. And this is not going to be changed.
