### ISSUE TITLE
Unique version number missing in "About texstudio" (help menu)?

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2253]
Help "About texstudio" with texstudio-win-qt6-4.2.4-202204181827-git_787704e.exe (dev. version) shows:

![grafik](https://user-images.githubusercontent.com/102688820/163892140-30ac7c61-c2b1-453a-be76-90ba51df0201.png)

Curios why there is no value (but a space) in parantheses. I would appreciate information that would identify the version (as given in the file name above). Current version 4.2.3 (should be 4.2.3-202204170759-git_2587d77) shows this:

![grafik](https://user-images.githubusercontent.com/102688820/163892540-1a6e56cd-39bd-43f1-87a8-d90114446fe3.png)

**Comment by sunderme** [comment]
the version extraction does not work reliable on the build machines

**Comment by sunderme** [comment]
by the way, the version name is supposed to be 4.2.3-n with n = number of commits after the tag

**Comment by sunderme** [comment]
apparently the version extraction in the source code is generally broken

**Comment by sunderme** [comment]
should be fixed
