### ISSUE TITLE
Portable Version: cannot change UI language

### ISSUE THREAD

**Issue by alfoil** [texstudio-org/texstudio#2254]
### Environment
- TeXstudio: 4.2.3 win portable qt6
- Qt: qt6
- OS: win 11 21H2
- TeX distribution: miktex

![](https://user-images.githubusercontent.com/15233248/163894005-2b5127ea-6649-4c9a-ba53-d796cc52875f.png)

**Comment by alfoil** [comment]
I just compared it to the installed version, and found that the portable version has an extra layer of directory in the translation folder. That's the problem.

**Comment by sunderme** [comment]
fixed in dev builds
you can move content of translation one up to fix the issue.
