### ISSUE TITLE
How to preview with lualatex?

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2255]
I want to preview equation environments with menu Idefix/Preview Selection. The document in UTF-8 has do be build with default compiler txs:///lualatex. But preview is done with pdflatex. The messages are:

Prozess gestartet: pdflatex.exe -synctex=1 -interaction=nonstopmode -shell-escape "hSqMJw".tex
Prozess endete mit Fehler(n)

What can I do?

**Comment by sunderme** [comment]
currently pdflatex is hard-coded.
does lualatex produce the same output as pdflatex with the preview source code (you can try in tmp dir)

**Comment by sunderme** [comment]
you can try to set lualatex as pdflatex-command

**Comment by octaeder** [comment]
Looks not good after replacing pdflatex by lualatex:
![grafik](https://user-images.githubusercontent.com/102688820/164348676-5888915c-4843-4721-820f-8d3e7c014d37.png)


Process started: lualatex.exe -interaction=nonstopmode -ini "&pdflatex hgOpzSn \dump"
Process exited with error(s)

Process started: lualatex.exe -synctex=1 -interaction=nonstopmode "ADvgLR".tex
Error: Command crashed: lualatex.exe -synctex=1 -interaction=nonstopmode "ADvgLR".tex
Process exited with error(s)

**Comment by octaeder** [comment]
> currently pdflatex is hard-coded. does lualatex produce the same output as pdflatex with the preview source code (you can try in tmp dir)

No shure what I should do. The preamble of my doc uses package selnolig, which is not suitable for pdflatex.

**Comment by octaeder** [comment]
Maybe it has to do with the following problem (assume it was introduced with version 4.x.x):

\documentclass[german,11pt,a4paper]{report}
\usepackage[latin1]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[width=210.00cm, height=29.70cm]{geometry}

\begin{document}
gänzlich unmöglich
\end{document}

Enoding is iso-8859-1. The preview of the two words with umlauts gives:

![grafik](https://user-images.githubusercontent.com/102688820/164351273-2a7ddd77-8518-4057-a36e-f69e5a9e4690.png)

Earlier no problem with this. Changing to utf-8 does not help. Gives only other nice double byte characters.

**Comment by sunderme** [comment]
looks like the text is not iso-8859-1 encoded.
txs basically uses utf8 or local code page. 
Anything but utf8 is really obsolete ...

**Comment by octaeder** [comment]
can anyone reproduce or help with the problem?

**Comment by octaeder** [comment]
Example above of course has to be with \usepackage[utf8]{fontenc}. Then it works. Now will try with lualatex.

**Comment by octaeder** [comment]
When using lualatex for building the preview works when changing the PdfLaTeX Command from pdflatex.exe to lualatex.exe in the configuration. Doc encoding is utf8.
