### ISSUE TITLE
TODO comment background color ignored if comments have a background color

### ISSUE THREAD

**Issue by alambicbicephale** [texstudio-org/texstudio#2257]
It's all in the title: in the "syntax highlighting" tab, if I select a background color for standard comments then the background color of TODO comments is ignored. Conversely, if I disable the background color for standard comments, then the background color for TODO comments appears again in the editor.

However, the background color of TODO comments should have priority over that of standard comments, which is not the case.

TexStudio version: 4.2.3
QT 6.3.0
Windows 10.
TeX = TeXLive 2021

**Comment by sunderme** [comment]
works as expected
Just make sure that "priority" of todo comment is higher than priority of comment in the syntax highlighting options

**Comment by alambicbicephale** [comment]
Thank you. Indeed, it works if I set the priority of TODO comments to n+1. 

However (and without wanting to open a debate), one can wonder if the default behavior that overwrites the background color of TODO comments by the one of classic comments is a behavior that can be considered as "expected". Indeed, TODO comments are a special kind of comments and as such, they should be specified with respect to "general" comments. For this reason, they should have priority over standard comments even if the priorities (in the parameters column) are the same. At least that is my opinion. 

Meanwhile, my problem is solved: thanks again!
