### ISSUE TITLE
Description of TOC

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2258]
Since usermanual_en.html is created automatically, I can't add a description by myself. I would like do so because of issues #2152 and #2237. I suggest the following and hope that you can do it for me:

Change the content of _2.4 Browsing your document_ as follows:
- use new subsections _2.4.1 The Structure View_ and _2.4.3 Using Bookmarks_ for already present content.
- Add new subsection _2.4.2 The TOC View_ and insert following content (attached two images needed):

2.4.2 The TOC View
The side panel on the left offers a TOC view (if not, use right mouse button and select it). The TOC shows the structure of your whole document by means of section commands (part, section, subsection, …). A mouse over shows you, in which file the section actually is.
 
![grafik](https://user-images.githubusercontent.com/102688820/164060131-65068a86-3174-45fc-9c80-c79aeb20a6c3.png)

The image shows this: A root file named document.tex that includes the file named file1.tex. The root file contains the section „Main text“, while file1.tex contains the subsection „External“. By placing the mouse pointer over this subsection in the TOC view, you find the file name file1.tex in the mouse over. This works even if the file is not open. In this case a mouse click on the subsection in the TOC will open the file for you. Notice the different shades of color that indicate the sections are in different files. It can happen, that an included file doesn’t contain any sections. Then the file name itself appears in the TOC (without file extension):

![grafik](https://user-images.githubusercontent.com/102688820/164060153-075be154-f8db-456f-bfdb-e7329504b421.png)

The mouse over now would show the name of the file that includes file1.tex (namely document.tex). The indentation shows that the text of file1.tex is part of the section “Main text”. You may like to choose a different color in the configuration dialog (s. Use color in global TOC in advanced editor settings).

Attachements:
![TOC_file](https://user-images.githubusercontent.com/102688820/164062218-0daeeb31-5949-4a59-b1ef-984b02967181.png)
![TOC_standard](https://user-images.githubusercontent.com/102688820/164062220-183d1afd-4b01-4b23-9587-7969efff5146.png)

**Comment by sunderme** [comment]
you can edit the usermanual_en.html , it is not derived from anything else.

**Comment by octaeder** [comment]
sorry, I see how I can edit it in github, but how can I download the file for edit it separatly? I can't see it :-(

**Comment by sunderme** [comment]
it is under utilities/manual in the source code.

**Comment by octaeder** [comment]
i forked your repository, and I know how to download the full repo as a zip (90MB). But I only want to edit this one file in my editor, not in the browser. For that I want do save the file on my desktop. But how? Or is there no such way?

**Comment by octaeder** [comment]
or even better, for a test I would need the whole manual folder.

**Comment by sunderme** [comment]
The easiest way is, install git on your computer. Clone the fork there. Generate a new branch, edit the file, commit the changes, push them to the fork and github offers the PR. Maybe it is possible to clone only parts, but that I have never tried.

**Comment by octaeder** [comment]
I found the way: When I click on the file, github shows its content. There choose raw, which will remove everything of gits web page decoration. Now use save as from the browser menu. After uploading the changed file in my fork I unload the forked repo as a zip. Extract the manual folder for testing. Thanks for your advice!

**Comment by sunderme** [comment]
I still recommend using git directly
