### ISSUE TITLE
Chapter not recognized properly outside book

### ISSUE THREAD

**Issue by fernandozucatelli** [texstudio-org/texstudio#2264]
Hello, TeXstudio Team.

As far as I like and see TeXstudio as the best LaTeX editor, there are still some issues every now and then after a new release in version 4 family. In my humble opinion, I must say the version 3 family was the best regarding to every feature I use and like.

I update to version 4.2.3 to solve the autocomplete problem (it has been solved) and now found some new undesirable behaviors. 

### Environment
- TeXstudio: 4.2.3 (git 4.2.3)
- Qt: 6.3.0, compiled with Qt 6.3.0 R
- OS: Windows 10
- TeX distribution: MiKTeX-pdfTeX 4.10 (MiKTeX 22.3)

### Expected behavior

As it was in version 3.1.2, it should present `\chapter` as a main division, like `\section`, independently of `documentclass`, even like `article` that does not use it, and should also correctly identify it on the _structure panel_.

![fig_v3_1_2_chapterWorks](https://user-images.githubusercontent.com/2475760/164304362-08b18a5e-7295-430e-9b65-58b273be1426.PNG)

Mainly when I'm working with my own class, that loads book, and use `\include` to insert each chapter from a different file.

![fig_v3_1_2_chapterWorksDissertacao](https://user-images.githubusercontent.com/2475760/164304948-acf34eff-327a-41eb-875e-2db023999ad2.PNG)

So I created a simplified version of the class to remove every unrelated thing.

![fig_myOwnClass_LoadClassBook](https://user-images.githubusercontent.com/2475760/164309027-464bd847-9894-4918-bf8b-84846ed6a1dc.PNG)

And version 3.1.2 works as fine as I have always seen and loved.

![fig_v3_1_2_justOpenedEverythingFine](https://user-images.githubusercontent.com/2475760/164310603-5cfb44c3-56be-48d4-a462-e84a855d1b60.PNG)

It worked fine and it was very clear to understand how the document was organized.

### Actual behavior

I notice in version 4.2.2 that my own class didn' t recognize `\chapter` correctly anymore.

![fig_v4_2_2_chapterProblemDissertacao](https://user-images.githubusercontent.com/2475760/164309235-3c45249b-7f91-42f4-a6c3-c4d1608af07f.PNG)

Same happened in version 4.2.3.

![fig_v4_2_3_chapterProblemBookIncludeChapterDissertacaoComErro](https://user-images.githubusercontent.com/2475760/164313706-d78579f2-a7e0-460c-986f-233ab274c9bd.PNG)

Then I searched here and tested it is related with the chosen class.

![fig_v4_2_2_chapterWorks_andTellsNotPartOfArticle](https://user-images.githubusercontent.com/2475760/164309240-64898d36-28c4-4a2a-b2c8-c676179c22e9.PNG)

![fig_v4_2_2_chapterWorks_andTellsPartOfBook](https://user-images.githubusercontent.com/2475760/164309242-252bbacc-5494-4db4-bf9c-ef2c508e8eaa.PNG)

#### Simplifying the causes

I created  `myOwnClass` and now it is clear that in both versions, 4.2.2 and 4.2.3, after opening a file with `myOwnClass` the chapters of included files are not recognized.

![fig_v4_2_3_beforeClickBack](https://user-images.githubusercontent.com/2475760/164309987-01449a8c-a4f1-4686-869b-0744afb80fb7.PNG)

After changing class to `book`  and clicking on the included file and clicking back on the main file it seems to be a little bit better, but still not right.

![fig_v4_2_3_afterChangingToBookAndClickBack](https://user-images.githubusercontent.com/2475760/164310120-5debc229-12a7-438b-b60d-6c20aa692221.PNG)

With `book`, it seems to use the correct blue color, although it still does not recognize the command correctly and still do not organize the _structure panel_ correctly.

![fig_v4_2_3_chapterProblemBookIncludeChapterFile](https://user-images.githubusercontent.com/2475760/164317164-9b5cf86d-db55-4d2a-860a-85f7a2e9f459.PNG)

### How to reproduce

The following files seem to be the minimum I needed to reproduce the issue.

Main file:
```
\documentclass{book}
%\documentclass{myOwnClass} %LoadClass{book}
\begin{document}
\include{include_test}
\end{document}
```
include_test:
```
\chapter{title}
\section{sec}
```
myOwnClass.cls:
```
\def\filename{myOwnClass.dtx}
\def\fileversion{v1.0}
\def\filedate{2022/04/20} 	 % aaaa / mm / dd

\NeedsTeXFormat{LaTeX2e}[1995/12/01] % aaaa / mm / dd
\ProvidesClass{myOwnClass}[\filedate\ \fileversion\ myOwnClass Dissertations and Thesis]
\ProvidesPackage{myOwnClass}[\filedate\space\fileversion]
\LoadClass[12pt,a4paper,twoside]{book}
```

### Similar issues and possible fixs
 - [2058](https://github.com/texstudio-org/texstudio/issues/2058)
 - [2003](https://github.com/texstudio-org/texstudio/issues/2003)
 - [1474](https://github.com/texstudio-org/texstudio/issues/1474)

I don't understand how this issue started to happen and didn't understand how it was fixed in 2058.

Should I provided `cwl` files as stated in 1474 to every class I created? It was not the previous standard, and it seems to be a confusing step while providing classes to my students.

**Comment by sunderme** [comment]
see #2149
 work-around: active completion file class-book.cwl in options

**Comment by fernandozucatelli** [comment]
Ok. Workaround with `class-book.cwl` worked. Thanks.
