### ISSUE TITLE
Bad box log highlighting is hardly readable using Adwaita Dark

### ISSUE THREAD

**Issue by schtandard** [texstudio-org/texstudio#2268]
### Environment
- TeXstudio: 4.2.3
- Qt: 6.3.0
- OS: Windows 11
- TeX distribution: Tex Live 2022

### Description
In the log widget, the blue used to highlight bad box messages using the Adwaita Dark theme is a bit too dark, making the messages rather hard to read. Screenshots:
![texstudio01](https://user-images.githubusercontent.com/23075534/164627789-a358cf52-c3a3-4bca-99af-ee66bb983716.png)
![texstudio02](https://user-images.githubusercontent.com/23075534/164627848-682f0448-b4f6-498b-94bd-20ddd8b7c79d.png)

Searching in the code I gather that the setting is in this line, though I am not sure.
https://github.com/texstudio-org/texstudio/blob/e9604f22dd614b035747dcd1bd52761f6d6397ac/src/latexoutputfilter.cpp#L24

### How to reproduce
Compiling the following document will in the messages shown in the screenshots above.
```latex
\documentclass{article}

\begin{document}

\undefined

\ref{undefined}

\rule{1.1\textwidth}{1ex}

\end{document}
```

**Comment by sunderme** [comment]
the color is hard coded.
What color do you suggest instead (RGB) ?

**Comment by schtandard** [comment]
It's hard to say for sure without seeing it in the UI, but I'll give it a shot. Taking the opportunity to adjust the other two colors as well to make them match, I'd propose
```
QColor(250, 112, 66), QColor(230, 201, 65), QColor(98, 197, 246)
```
for the three colors. I moved each color away from the primary colors a bit, since that makes for much clearer contrasts. (I'm assuming these colors only affect dark mode.)
