### ISSUE TITLE
Preview starts unintendedly with mouse pointer on colors

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2269]
When I use the following then there is a preview:
\documentclass{article}
\usepackage{xcolor}
\begin{document}
	\color{red}
\end{document}
![grafik](https://user-images.githubusercontent.com/102688820/164888537-d48ef57d-1746-4d5c-8f64-1aa85674866a.png)
Changing color to green changes the box's color to green.

_Originally posted by @octaeder in https://github.com/texstudio-org/texstudio/issues/2116#issuecomment-1107440155_

**Comment by sunderme** [comment]
if you hover over "red", red is shown (normally as tooltip but that can be also shown in the preview pane)
For red that may be unnecessary, but xcolor knows tons of color names.
Intended behavior.

**Comment by octaeder** [comment]
What a surprise. Thanks for clarification!
