### ISSUE TITLE
Texstudio 4.2.3 Qt6 crashes on startup on Windows 8.1

### ISSUE THREAD

**Issue by ProcyonTheEvil** [texstudio-org/texstudio#2273]
Hello and thank your for your awesome work on Texstudio!

Texstudio 4.2.3 Qt6 (installer & portable version) crashes on startup on Windows 8.1 with a qt error:

This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem. Available platform plugins are: windows.

Reinstalling the application did not fix the problem.

Windows replorts the following crash information:
[texstudio-4.2.3-win-qt6_startup_error.txt](https://github.com/texstudio-org/texstudio/files/8552686/texstudio-4.2.3-win-qt6_startup_error.txt)

The portable Qt5 version works. I went back to 4.2.2 Qt6 for now. If you need more info I am happy to help out. I only checked the open issues back to #2210 before reporting this, I am sorry if this is a duplicate.

Sincerely, Procyon

**Comment by sunderme** [comment]
txs officially only supports win 8 until txs 2.12.22.
Qt6 officially only supports Win10+.
So, you run newer txs versions on your risk.
