### ISSUE TITLE
Bookmark 0 in the menus and shortcuts

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2275]
I have follow findings concerning bookmark shortcuts using current txs 4.2.3 Qt6 on Win 10:

For all bookmarks n from1 to 9 we have go to n with shortcut Ctrl+n, but not for n=0. Please add shortcut. Be aware that
section 4.13 of the manual uses the item name "Set Bookmark" instead of "Toggle Bookmark". That should be adjusted. It states shortcuts for both functions for bookmark 0.

If you like, I can update the manual accordingly, but before let me know what you do.

Thx

**Comment by sunderme** [comment]
ctrl+0 was intentionally left out, why I can't say, but I assume that there is a reason.
So I leave it as is.
You can change the manual if you like.

**Comment by octaeder** [comment]
Cant't figure out how to remove the shortcut shown in the menu Toggle Bookmark.

**Comment by octaeder** [comment]
Btw: U answered my question about ctrl+(+shift+)g. It is used on Mac for find next (previous) and you mentioned that ctrl+l is goto line for Mac. Since the fist 2 are noted in 4.13 Keyboard shortcuts I would conclude that ctrl+l has to be noted there, either. But this is not the case. Whow can I decide what should be there and what not?

**Comment by octaeder** [comment]
Usermanual is updated to reflect that Ctrl+0 is not used for jump to bookmark 0.

**Comment by octaeder** [comment]
@sunderme Note, Ctrl+0 is bound to Reset zoom. Since Zoom in and Zoom out are bound to Ctrl++ and Ctrl+- respectively, I bound Reset zoom to Ctrl+* (for german keyboards either use * on the ten key block or Ctrl with shift and plus). So I can use Ctr+0 for jump to bookmark 0 as usual. Seems quite nice to me.
