### ISSUE TITLE
Using Find with shortcuts

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2276]
I use current txs 4.2.3 Qt6 for Win10. We can find next with shortcut F3, the previous one with Shift+F3 (as statet in the menu Edit/Searching). But curiously enough the manual also states Ctrl+G and Ctrl+Shift+G respectively in section 4.13. Is there any reason for needing duplicates? Anyway, Ctrl-G is bound to function Go To line, while the other indeed does the same as Shift+F3. Could you please remove the two shortcuts with G and adjust the manual accordingly. If you like, I can update the manual.

Thx

**Comment by sunderme** [comment]
ctrl+g is the valid shortcut on mac (ctrl+l for goto line)
