### ISSUE TITLE
Q: What does option "Go to error when displaying log"?

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2278]
I tried to understand, what's the meaning of the text, but I couldn't figure out any case where it makes a difference if this adv. Editor option is set or not. I couldn't find hints in the manual nor is there a mouse over. Can you explan this function, please? I use curent txs 4.2.3 Qt6 for Win10.

Thx

**Comment by prakashvs613** [comment]
When this option is checked and the compiler throws error(s), the cursor automatically moves to the first error. Attached are the screenshots of when the option is checked and not checked. The gray highlighted line shows the cursor location (line 107 in the unchecked snapshot, 114 in the checked one). 

<p align="center"> <img width="250" src="https://user-images.githubusercontent.com/12219020/165640575-eba60f71-2ea8-4d81-b219-69d50217d8f7.png" alt="Slit slit damper"> &emsp; &emsp; <img width="250" src="https://user-images.githubusercontent.com/12219020/165640763-bb4d5215-375f-45e8-86e5-ba944c11d8d0.png" alt="Slit slit damper"></p><p align="center"> <b> (a) Unchecked &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;(b) checked. </p>

**Comment by octaeder** [comment]
Thanks for clarification, now I see it! Same as if I would click on the grey line.

**Comment by octaeder** [comment]
I will use your information in the usermanual.
