### ISSUE TITLE
\left. offers completion \left..\right instead of \left.\right.

### ISSUE THREAD

**Issue by kbauer** [texstudio-org/texstudio#228]
## Expected behavior

After typing `\left.`, the completion `\left.\right.` should be offered,
and upon completion, the cursor should be between `\left.` and `\right.`.

## Actual behavior

An completion `\left..\right` is offered, which is wrong syntax. 
The cursor is placed at the end instead of in between.

Cursor represented by |:

    Before completion: \left.|
    Expectation:       \left.|\right.
    Actual completion: \left..\right|

![image](https://user-images.githubusercontent.com/7498468/42398716-31371a6a-816b-11e8-86cc-50a130bebbae.png)

### Environment
- TeXstudio: 2.12.8
- Qt: Using Qt Version 5.8.0, compiled with Qt 5.8.0 R
- OS: Windows 10 (Microsoft Windows [Version 10.0.16299.492])
- TeX distribution: MikTeX

**Comment by sunderme** [comment]
your are wrong about the expected completion , it really is \left..\right, but ".." should be a placeholder. That has been fixed

**Comment by kbauer** [comment]
Just to be certain: What is the intended result of the expanded code?

`\left.<placeholder>\right.` would be `\left(<placeholder>\right)` with invisible braces.

`\left<placeholder>\right` would not compile.
