### ISSUE TITLE
text search stopped working

### ISSUE THREAD

**Issue by tbhkuiper** [texstudio-org/texstudio#2284]
### Environment
- TeXstudio: TeXstudio 2.12.22 (Build: 2.12.22+debian-1build1)
- Qt: Qt Version 5.12.8, compiled with Qt 5.12.5 R
- OS: Linux nutmeg2 5.16.11-76051611-generic #202202230823~1646248261~20.04~2b22243~dev-Ubuntu SMP PREEMPT Th x86_64 x86_64 x86_64 GNU/Linux
- TeX distribution: texlive

### Expected behavior
Finds text in search widget (Ctrl-F) when pressing up or down arrow to the right of widget

### How to reproduce
![Screenshot from 2022-04-26 16-24-43](https://user-images.githubusercontent.com/7907705/165408781-e500479e-7d4e-4b0d-ab60-491d663145cb.png)

See word "square" in the middle of the page and in the search widget.

The one thing I'm not sure about is the state of the "Select/Select" button for highlighted text but I think I tried both states.

**Comment by sunderme** [comment]
First of all, with only a screen shot, debugging is basically impossible.
Secondly development is done with the current version of txs 4.2.3, so unless you switch to that version, no bug fixed can be provided.
Thirdly if it suddenly stops working, it is probably not txs (which I assume was not changed) but either setting or something in the system.

**Comment by tbhkuiper** [comment]
Here is the system report
[System Report.txt](https://github.com/texstudio-org/texstudio/files/8574659/System.Report.txt)
