### ISSUE TITLE
Default shortcuts for next/previous placeholder on macOS

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#2287]
### Describe the feature and the current behavior/state
Currently, there isn't any default shortcuts for next/previous placeholder on macOS, unlike what happens on Linux and Windows.

A PhD student of the LaTeX course I gave today was very disappointed about that. Though he looked like a geek, he couldn't guess this was configurable. I explained how to proceed and he succeeded with the following shortcuts (which do not interfere with the OS ones): ⌥→ and ⌥←.
 
It is nice to provide them (or more clever other ones, if any) by default.

### Who will benefit with this feature?
All macOS users.

**Comment by sunderme** [comment]
alt+right is actually the official shortcut for next word. I have reset it to next word or placeholder, like in win/linux.
