### ISSUE TITLE
Structure Files in red after upgrading

### ISSUE THREAD

**Issue by hpcolus** [texstudio-org/texstudio#2289]
I upgraded to version 4.2.2 from 3.x and suddenly under my root documents all files included show in red.  It was something never had before the upgrade.  Under the file tree if I open the file in red, only changes to black if I click on the parent file.  It looks to me this is a bug
![image](https://user-images.githubusercontent.com/104551107/165687627-d4fe0b56-ae90-48f4-b953-789eb343b806.png)
![image](https://user-images.githubusercontent.com/104551107/165687830-f76a490f-71b3-49af-8dee-5bb602a7a98b.png)

**Comment by fernandozucatelli** [comment]
It seems to be the same as in: #1875. It probably has the same behavior as in the video presented at the cited issue.

**Comment by octaeder** [comment]
I can't reproduce. May I suggest something to try? While txs is not running rename (backup) the folder %appdata%\roaming\texstudio (Win 10). Check if you have other data in the installation folder of txs and backup it. Install latest version 4.2.3 that you can download from texstudio.org and install it. This will give u an installation with a new profile after starting and ending txs. See if this helps. You try on you own risk. But I work with large document without big problems with 4.2.3.

**Comment by sunderme** [comment]
probably fixed
