### ISSUE TITLE
FR: Add path option for app data

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2290]
Feature Request: Currently for Win 10 txs saves app data under %appdata%\roaming\texstudio. It would be usefull if there were a "General" option that would allow to choose a different path. This is usefull if you would like to install two (or even more) versions of txs in parallel, just to move the data to a place in the file system that is backuped, separation of OS and data, and so on.

Thx for the great project

**Comment by sunderme** [comment]
no, where should txs store the path to look for the path to store configs ?

**Comment by octaeder** [comment]
where the program is installed, not where the config is stored.

**Comment by octaeder** [comment]
Probably the current path for started txs process is set to the directory from where txs has been started. Then it could store or read from there the info where the config file is stored. Under windows maybe someone would store the path with config in the registry, but this will likely not work with a different OS.

**Comment by sunderme** [comment]
makes no sense.
Use portable txs.

**Comment by octaeder** [comment]
portable is a good suggestion
