### ISSUE TITLE
FR: Add LuaLaTex to preview commands

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2291]
There are already some commands to choose from a list in the Command option in segment Preview. Please add LuaLaTeX as it is already configured in the Commands like PdfLaTeX. txs version 4.2.3 Win10.

Thx

**Comment by octaeder** [comment]
@sunderme Now command for ini mode is extracted with path if necessary (s. buildmanager.cpp), it's no longer hard coded. No test with "no poppler" (how to do this?) and first process has errors. Sources see octaeder/luapreview. How to proceed?

Commands defined:
![grafik](https://user-images.githubusercontent.com/102688820/167314146-deb3a74c-30a2-498a-8201-a5bc7d12a4cb.png)
Preview select lualatex:
![grafik](https://user-images.githubusercontent.com/102688820/167314181-63a61a71-9ac5-4d11-8643-ac5e2bd2ed45.png)
![grafik](https://user-images.githubusercontent.com/102688820/167314173-3476395d-c610-4f72-a822-e100a04fb2de.png)
First process starts luatex (replacement for lualatex), second process starts lualatex command as defined:
![grafik](https://user-images.githubusercontent.com/102688820/167314249-cd25ea97-8098-40e0-842a-ef718b3146fd.png)
But ends with error(s). No clue why.
If command is with path:
![grafik](https://user-images.githubusercontent.com/102688820/167314325-7944355e-076f-400f-8807-711152662615.png)
First process starts luatex correctly with path, second process starts lualatex command as defined:
![grafik](https://user-images.githubusercontent.com/102688820/167314455-9f9b27bf-127f-4a10-b4e3-7483639f63d9.png)
This will work even if file extension .exe is missing.

**Comment by octaeder** [comment]
@sunderme Now command for ini mode is extracted with path if necessary (s. buildmanager.cpp), it's no longer hard coded. No test with "no poppler" (how to do this?) and first process has errors. Sources see octaeder/luapreview. How to proceed?

Commands defined:
![grafik](https://user-images.githubusercontent.com/102688820/167314146-deb3a74c-30a2-498a-8201-a5bc7d12a4cb.png)
Preview select lualatex:
![grafik](https://user-images.githubusercontent.com/102688820/167314181-63a61a71-9ac5-4d11-8643-ac5e2bd2ed45.png)
![grafik](https://user-images.githubusercontent.com/102688820/167314173-3476395d-c610-4f72-a822-e100a04fb2de.png)
First process starts luatex (replacement for lualatex), second process starts lualatex command as defined:
![grafik](https://user-images.githubusercontent.com/102688820/167314249-cd25ea97-8098-40e0-842a-ef718b3146fd.png)
But ends with error(s). No clue why.
If command is with path:
![grafik](https://user-images.githubusercontent.com/102688820/167314325-7944355e-076f-400f-8807-711152662615.png)
First process starts luatex correctly with path, second process starts lualatex command as defined:
![grafik](https://user-images.githubusercontent.com/102688820/167314455-9f9b27bf-127f-4a10-b4e3-7483639f63d9.png)
This will work even if file extension .exe is missing.

**Comment by sunderme** [comment]
The precompile does not work. For starters, turn that off. (options)

**Comment by octaeder** [comment]
@sunderme Now changing back first/preamble process to lualatex for ini mode (l. 1813). Now this process runs together with second/compile process without errors. But if second runs alone (no change of preamble) it gets errors.

**Comment by octaeder** [comment]
@sunderme Reason is a LaTeX error. But why? Is the fmt file incomplete?

Select tikzpicture environment in my tex document (s. below) and select "Preview Selection/Parenthesis". This extracts the original preamble of my tex file
```
\documentclass{report}
\usepackage{tikz,lipsum}
\usetikzlibrary{calc}
```
appends this
```
\usepackage[active,tightpage]{preview}
\usepackage{varwidth}
\AtBeginDocument{\begin{preview}\begin{varwidth}{\linewidth}}
\AtEndDocument{\end{varwidth}\end{preview}}
\pagestyle{empty}
```
and saves result in _horsGvM.tex_. Building format file _horsGvM.fmt_ s. messages panel:
```
Process started: lualatex.exe -interaction=nonstopmode -ini "&lualatex horsGvM \dump"
```
This process and the second one exited normally.

Now I change the document (no change in preamble). This creates tex file _dqloUL.tex_
```
%&horsGvM

\begin{document}
\begin{tikzpicture}[thick,scale=.9]\scriptsize
		\path (0,0) coordinate(A) (5,0) coordinate(B) (16/5,3*4/5) coordinate (C);
	\draw[fill=red!20] (C) arc[radius=2,start angle={atan(3/4)},delta angle=180]
	arc[radius=2.5,start angle=180,end angle={2*asin(3/5)}];
	\draw[fill=red!20] (B) arc[radius=1.5,start angle={-atan((3*4/5)/(9/5))},delta angle=180]
	arc[radius=2.5,start angle={atan((3*4/5)/(2.5-9/5))},end angle=0];
	\draw[fill=yellow!20] (A) to[edge label'=$c$] (B) to[edge label'=$a$] (C) to[edge label'=$b$] cycle;
	\path (A) node[below left]{$A$} (B) node[below right]{$B$} ($(A)!.5!(B)!1.05!(C)$) node[above]{$C$};
\end{tikzpicture}
\end{document}
```
and starts this process:
```
Process started: lualatex.exe -synctex=1 -interaction=nonstopmode "dqloUL".tex

Process exited with error(s)
```
lualatex writes following messages:
```
This is LuaHBTeX, Version 1.15.0 (MiKTeX 22.3) (format=lualatex 2022.4.21)  11 MAY 2022 23:18
 restricted system commands enabled.
**dqloUL.tex
(./dqloUL.tex
LaTeX2e <2021-11-15> patch level 1

... skipped lines ...

(C:/Users/WDAGUtilityAccount/AppData/Local/Programs/MiKTeX/tex/latex/base/ts1cm
r.fd
File: ts1cmr.fd 2019/12/16 v2.5j Standard LaTeX font definitions
)
LaTeX Font Info:    ... okay on input line 3.
LaTeX Font Info:    Checking defaults for TU/lmr/m/n on input line 3.
LaTeX Font Info:    ... okay on input line 3.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 3.
LaTeX Font Info:    ... okay on input line 3.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 3.
LaTeX Font Info:    ... okay on input line 3.


! LaTeX Error: The font size command \normalsize is not defined:
               there is probably something wrong with the class file.

```

**Comment by octaeder** [comment]
If both processes are started then the fmt file isn't used, so no error. Here file _VSWiln".tex_
```
\documentclass{report}
\usepackage{tikz}
\usetikzlibrary{calc }

\usepackage[active,tightpage]{preview}
\usepackage{varwidth}
\AtBeginDocument{\begin{preview}\begin{varwidth}{\linewidth}}
\AtEndDocument{\end{varwidth}\end{preview}}
\pagestyle{empty}
\begin{document}
\begin{tikzpicture}[thick,scale=.9]\scriptsize
		\path (0,0) coordinate(A) (5,0) coordinate(B) (16/5,3*4/5) coordinate (C);
	\draw[fill=red!20] (C) arc[radius=2,start angle={atan(3/4)},delta angle=180]
	arc[radius=2.5,start angle=180,end angle={2*asin(3/5)}];
	\draw[fill=red!20] (B) arc[radius=1.5,start angle={-atan((3*4/5)/(9/5))},delta angle=180]
	arc[radius=2.5,start angle={atan((3*4/5)/(2.5-9/5))},end angle=0];
	\draw[fill=yellow!20] (A) to[edge label'=$c$] (B) to[edge label'=$a$] (C) to[edge label'=$b$] cycle;
	\path (A) node[below left]{$A$} (B) node[below right]{$B$} ($(A)!.5!(B)!1.05!(C)$) node[above]{$C$};
\end{tikzpicture}
\end{document}
```
is compiled:
```
Process started: lualatex.exe -interaction=nonstopmode -ini "&lualatex hVvavWO \dump"
Process started: lualatex.exe -synctex=1 -interaction=nonstopmode "VSWiln".tex
Process exited normally
Process exited normally
```
So the preamble is unnecessarily compiled twice.

**Comment by octaeder** [comment]
@sunderme Current state of investigation:

- Create format/dump file for lualatex analog to pdflatex, e.g.
  ```p = newProcessInternal(QString("%1 -interaction=nonstopmode -ini \"&lualatex %2 \\dump\"").arg(getCommandInfo(CMD_LUALATEX).getProgramName(),preambleFormatFile), QFileInfo(tf->fileName()));```
- When compiling with pdflatex we use same CMD_PDFLATEX since pdflatex will recognize the "magic comment" for the format file (e.g. ```%&formatname```, s. above) to be used in the document to compile with that format. But LuaLaTeX does not. Thus CMD_LUALATEX has to be amended with option -fmt=formatname for compiling the preview document (if format already exists):
  ```
  QString command = getCommandInfo(CMD_LUALATEX).commandLine;
  if (preambleFormatFile != "") {
	QString pgm = getCommandInfo(CMD_LUALATEX).getProgramName();
	command = command.insert(pgm.length(), " -fmt=" + preambleFormatFile);
  }
  p1 = firstProcessOfDirectExpansion(command, QFileInfo(ffn));```

Example: hQzMazN.tex consists of preamble of original tex file plus definitions for preview. Format/dump file then is hQzMazN.fmt. BLdGOA.tex consists of contents of hQzMazN.tex plus document environment with preview snippet.
```
Process started: lualatex.exe -interaction=nonstopmode -ini "&lualatex hQzMazN \dump"
Process started: lualatex.exe -synctex=1 -interaction=nonstopmode "BLdGOA".tex
Process started: lualatex.exe -fmt=hQzMazN -synctex=1 -interaction=nonstopmode "JwMjuk".tex
```
Second run above is a full compile since process creating format file hasn't finished in time.

**Problem:** If the tikzpicture environment from package tikz is used in the original tex document the second run is still no problem. But the 3rd one using the format file ends with an error in the log:
```
(C:/Users/WDAGUtilityAccount/AppData/Local/Programs/MiKTeX/tex/latex/epstopdf-p
kg/epstopdf-base.sty
Package: epstopdf-base 2020-01-24 v2.11 Base part for package epstopdf
Package epstopdf-base Info: Redefining graphics rule for `.eps' on input line 4
85.

(C:/Users/WDAGUtilityAccount/AppData/Local/Programs/MiKTeX/tex/latex/00miktex/e
pstopdf-sys.cfg
File: epstopdf-sys.cfg 2021/03/18 v2.0 Configuration of epstopdf for MiKTeX
))
Preview: Fontsize 10pt
Preview: PDFoutput 1
luaotfload | db : Font names database loaded from C:/Users/WDAGUtilityAccount/Ap
pData/Local/MiKTeX/luatex-cache/generic/names/luaotfload-names.luc.gz
Preview: Tightpage -32891 -32891 32891 32891
[1{C:/Users/WDAGUtilityAccount/AppData/Local/MiKTeX/fonts/map/pdftex/pdftex.map}
]
! error:  (pdf backend): referenced object has wrong type others; should be obj
!  ==> Fatal error occurred, no output PDF file produced!
```

**Comment by octaeder** [comment]
[Answer by Ulrike Fischer Sep 2, 2016](https://tex.stackexchange.com/questions/326291/why-can-i-include-tikz-in-a-custom-latex-format-with-pdftex-and-not-with-luatex): _It looks as if luatex doesn't like it if one tries to reserve objects in the format. I can't tell you if this is intended, or some side effect, or even a bug: you will have to ask on the luatex list. Even if it works with pdftex: I would avoid to put objects in a format anyway (and so not move tikz there)._

**Comment by octaeder** [comment]
Implemented with the restriction (s. above), that you might have to disable (advanced) option Precompile Preamble.
