### ISSUE TITLE
Multicursor's behavior not as expected from previous versions

### ISSUE THREAD

**Issue by fernandozucatelli** [texstudio-org/texstudio#2292]
Multicursor is one of the best features of TeXstudio. but its behavior changed from previous versions to version 4.2.3.

### Environment
- TeXstudio: 4.2.3 (git 4.2.3)
- Qt:  Qt Version 6.3.0, compiled with Qt 6.3.0 R
- OS: Windows 11
- TeX distribution: MiKTeX-pdfTeX 4.10 (MiKTeX 22.3)

### Expected behavior

From Version 3.1.2 Backspace: Opening a file, the first usage of backspace remove every character of each row.

https://user-images.githubusercontent.com/2475760/165875421-ee051282-c75a-4570-9a07-87fa6667e800.mp4

From Version 3.1.2 Home, End and Direcional arrows: After using multicursor, Home and End let me go to all first and last column; Directional arrows don't.

https://user-images.githubusercontent.com/2475760/165875436-dd7f4820-c87b-488a-bb30-f8d3fcd1e0b3.mp4

### Actual behavior

From Version 4.2.3 Backspace: Opening a file, the first usage of backspace **doesn't** remove the first (top) character.

https://user-images.githubusercontent.com/2475760/165875453-daba4001-950d-47a4-bef9-b2ff277e18f4.mp4

From Version 4.2.3 Home and End: After using multicursor, Home and End **don't** let me go to all first and last column, I go only for the top row of the first or last column.

https://user-images.githubusercontent.com/2475760/165875465-d6a9e164-05f0-4864-8cd5-60636f70d14f.mp4

From Version 4.2.3 Direcional arrows: After using multicursor, Directional arrows don't to all columns, but it is ok. That's the same .

https://user-images.githubusercontent.com/2475760/165875471-6324a3f6-9b37-47ab-b94c-c3ce558586ee.mp4

### How to reproduce

Any use of multicursor, not necessarily in tabular.

**Comment by sunderme** [comment]
I don't see an issue with backspace. Any more details when it happens ?

The home/end is disabled intentionally as it leads to stange behaviour if the multicursors are placed in the same line.
You can open a feature request, so maybe someone wants to work out all the kinks associated with moving multicursors.

**Comment by fernandozucatelli** [comment]
> I don't see an issue with backspace. Any more details when it happens ?

In the video "Version 4.2.3 Backspace", every *first* time after opening a file pressing backspace in multicursor doesn't remove the element in the top position.  Afterwards it works fine.

> The home/end is disabled intentionally as it leads to stange behaviour if the multicursors are placed in the same line. You can open a feature request, so maybe someone wants to work out all the kinks associated with moving multicursors.

I knew there were some strange behavior, like the following one

https://user-images.githubusercontent.com/2475760/166110303-d7761637-0661-4570-baa8-6111180eadd3.mp4

but the Home/End feature was some much useful as I could always editing from the back of multiple lines adding periods, `}`, etc.

https://user-images.githubusercontent.com/2475760/166110315-677f9d77-15c3-4d63-b3ed-7f75b9c1d1cd.mp4

I missed it when editing my tables.

I will open a request to insert some option to choose between each behavior.

**Comment by sunderme** [comment]
I don't see the backspace behaviour on a different windows computer either.
So, unless I can get a reproducible case, I will close this and the feature request will stay open.

**Comment by fernandozucatelli** [comment]
> I will close this and the feature request will stay open.

I agree.
