### ISSUE TITLE
Search results not present after jump to pdfviewer

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2297]
I often use extendet search (opens Search Results tab in the message panel below). Thus I can quickly jump to lines of interest in the document(s). I also use Ctrl+mouse click in the text to jump further to the corresponding position in the pdf-viewer. Buth exactly then txs switches to the Messages tab. So I must always reopen the Search Results tab. This is tedious and not consistent with the Build option 'Show messages **when** starting compiling' that is checked. From my point of view there is no reason to swicht to the messages.

Thx for your help
current txs 4.2.3 Qt6 Win10

**Comment by sunderme** [comment]
deactivate options/show messages when compiling for that
