### ISSUE TITLE
TexStudio does not abide by --output-dir

### ISSUE THREAD

**Issue by raffam** [texstudio-org/texstudio#23]
If you go on `Options->Configure TexStudio->Commands `and modify the latex/pdflatex/xelatex commands introducing an  `--output-directory` option, the compiler put the output .pdf file in the directory specified by the  `--output-directory` parameter, but TexStudio continue to look in the directory of the .tex file

**Comment by sunderme** [comment]
txs does not scan the commands.
the log search path can be extended via options/build/additional search paths
