### ISSUE TITLE
Setup blocked by Windows Defender

### ISSUE THREAD

**Issue by Spenhouet** [texstudio-org/texstudio#230]
I tried to update my TeXstudio version to 2.12.10 but Windows Defender blocks the installer.

![image](https://user-images.githubusercontent.com/7819068/42420297-d89c9c18-82c3-11e8-8df3-6039ab5411a5.png)

TeXstudio should not be blocked / be detected as something bad by the Windows Defender.

### Environment
Current TeXstudio Version: 2.12.8
Os: Windows 10

**Comment by sunderme** [comment]
we can't control. We don't have a developer certficate (which costs money), so you need to set windows accordingly that it accepts this program from the internet.

**Comment by brjsp** [comment]
So how come versions 2.12.6 and earlier had certificates?

**Comment by sunderme** [comment]
the certificate expired
