### ISSUE TITLE
Line movement

### ISSUE THREAD

**Issue by LDprg** [texstudio-org/texstudio#2300]
### Describe the feature and the current behavior/state
Well just the option to move a line up and down by pressing for example alt-up or alt-down. A very common feature in other editors (VS-code). 

### Who will benefit with this feature?
Everyone using this software.

### Any Other info
Please implement drastically improves typing performance.

**Comment by octaeder** [comment]
If I understand right you want to use these functions from the edit menu

![grafik](https://user-images.githubusercontent.com/102688820/166157716-e9a4d945-9c92-4d09-bc2e-57cecd12eb6c.png)

Just open the config dialog (menu options) and choose Shortcuts to the left. Mouse overs give hints there.

**Comment by dbitouze** [comment]
Default shortcuts would be welcome.

**Comment by octaeder** [comment]
I was able to setup Alt+Up for moving up and Alt+Down for moving down (up and down with arrow keys). So it seems that these key bindings are free. Maybe someone can do it.

**Comment by sunderme** [comment]
the scrollbar is controlled by alt+up/down.
So, the binding has already some function and hence I am not changing defaults.

**Comment by dbitouze** [comment]
> the scrollbar is controlled by alt+up/down. So, the binding has already some function and hence I am not changing defaults.

Maybe another default shortcut could be provided.

**Comment by sunderme** [comment]
It is configurable. If someone wants to use, fine. 
There is absolutely no need to set it for everyone who does not need or want it.
(I have never missed that function in 15 years)

**Comment by octaeder** [comment]
> the scrollbar is controlled by alt+up/down. So, the binding has already some function and hence I am not changing defaults.

@sunderme I observed that inserting a shortcut in Shortcuts config dialog will warn if the shortcut is already in use. I did not get such a warning. So I'm sorry that I said these can be used. Have you any instructions on how to avoid such misunderstandings?

**Comment by sunderme** [comment]
the shortcut is not handled by txs but by qt, hence there is no definition of that shortcut in the config.
So, your claim was reasonable, but unfortunately not completely correct. Furthermore the shortcut does not work on OSX as there it is used.

**Comment by LDprg** [comment]
Ok, but is there any other available shortcut that could be set as default. Like Strg-Shift-Up and Strg-Shift-Down are also very common for line movement.

**Comment by sunderme** [comment]
again, you can set it to whatever you like. That does not mean that default settings need to be changed.

**Comment by dbitouze** [comment]
> again, you can set it to whatever you like (option/shortcuts).

Not easy to figure out for average users.

> That does not mean that default settings need to be changed.

If it is harmless, why not?

**Comment by sunderme** [comment]
it is not "harmless" in the sense, that it is already used for a sensible action. Maybe someone is already using it for scrolling.
The average user has no need for moving lines with that shortcut, this is coming from programming editors where it makes more sense. Hence the reporter should also be capable of changing shortcuts.
