### ISSUE TITLE
I installed TeXStudio and run the administrator. after that if i open it says cannot open. there is an error this kind of dialogue box will open. please help

### ISSUE THREAD

**Issue by Shruthicheth** [texstudio-org/texstudio#2304]

**Comment by Shruthicheth** [comment]
"The application was unable to start correctly (0Xc000007b)
click okay to close the application".   This is the error message i am getting.

I am a research student i need this please help me

**Comment by sunderme** [comment]
Since you left out all useful information which you were asked when submitting (OS, version of txs, etc), I wildly guess it is like #2210 ?

**Comment by Shruthicheth** [comment]
OS- windows 10 , TeXStudio 4.2.3, i downloaded and installed but after opening the installed TeXStudio this is the message displayed on the screen "The application was unable to start correctly (0Xc000007b)
click okay to close the application".

**Comment by octaeder** [comment]
some hints from a google search may help: Update .NET to latest version (check windows update), use MS defender instead of a different virus scanner, check under programs and features if there are old versions of MS Visual C++ Redistributables installed. Source: https://answers.microsoft.com/de-de/windows/forum/all/fehlermeldung-0xc00007b-windows-10/27ddac45-e542-45e2-8e72-94a2d7c2318f But this might not help, I don't know. It could also be a problem with 32/64 bit app vs. OS.

**Comment by sunderme** [comment]
txs is 64 bit. win10 should be 64 bit only, so ...

**Comment by sunderme** [comment]
you can try to use txs/qt5.

**Comment by sunderme** [comment]
no feedback

**Comment by Shruthicheth** [comment]
Device name	DESKTOP-VACFATL
Processor	Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz   2.50 GHz
Installed RAM	8.00 GB (7.90 GB usable)
Device ID	FBFF9450-8230-4F5B-AAC7-F0B433B8BF4C
Product ID	00331-10000-00001-AA683
System type	64-bit operating system, x64-based processor
Pen and touch	Pen support

this is the specification of my laptop. i will look into the suggestions you have given

**Comment by Shruthicheth** [comment]
Device name	DESKTOP-VACFATL
Processor	Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz   2.50 GHz
Installed RAM	8.00 GB (7.90 GB usable)
Device ID	FBFF9450-8230-4F5B-AAC7-F0B433B8BF4C
Product ID	00331-10000-00001-AA683
System type	64-bit operating system, x64-based processor
Pen and touch	Pen support
This is the system configuration. Please know your feedback

**Comment by Shruthicheth** [comment]
Hi i updated the java file. then texStudio opened without any error message display. THANKYOU SO MUCH FOR CO-ORDINATING AND HELPING TO FIX IT.

**Comment by sunderme** [comment]
What java file ? The java sdk ?

**Comment by Shruthicheth** [comment]
File description : Java platform SE binary. 
version : 8.0.3330.2
product name : Java platform SE 8 U333

this is the description i found
