### ISSUE TITLE
[FeatureRequest] Global TODO List

### ISSUE THREAD

**Issue by bonanza123** [texstudio-org/texstudio#231]
In light of previous feature request (https://sourceforge.net/p/texstudio/feature-requests/1358/, https://sourceforge.net/p/texstudio/feature-requests/1290/), I would like to ask for the following new feature:

A global TODO list which lists `%TODO`s also in sub-documents (`\include`,`\input`)

**Comment by sunderme** [comment]
was implemented with global TOC
