### ISSUE TITLE
TexStudio doesn't know where to place the cursor when there are lots of brackets

### ISSUE THREAD

**Issue by sylbeth** [texstudio-org/texstudio#2313]
Whenever I had too much text and text collapsed in brackets, the cursor would not be where the text was being typed at.
### Environment
- TeXstudio: VERSION 4.2.3 (git 4.2.3)
- Qt: 6.3.0 R
- OS: Windows 10 Pro
- TeX distribution: MiKTeX-pdfTeX 4.10 (MiKTeX 22.1)

### Expected behavior
The cursor should be exactly where the next character you type will appear.

### Actual behavior
The cursor is at a lower point in the text than the actual characters are being written at, but it is only moved in the y axis. Its x value is exactly the same, and command highlighting and other visual elements of the editor are also moved.

### How to reproduce
Write a lot of text inside brackets that are inside other brackets that are inside other brackets, and so on, and collapse them all. At some point the cursor starts acting erratically.

**Comment by sylbeth** [comment]
I don't have any screenshots on this, if there are any problems reproducing it I'll try to make them.

**Comment by muzimuzhi** [comment]
> I don't have any screenshots on this,

Please do provide some, either screenshots (images) or screen recordings (videos).

**Comment by sunderme** [comment]
including a text example. Nobody wants to copy text from a photo.

**Comment by sylbeth** [comment]
![image](https://user-images.githubusercontent.com/102521501/167308335-d94f408c-552d-48ce-a4f3-049463d67b66.png)

I'll try to make a screen recording tomorrow, but for now I have this screenshot, still no luck with the cursor though.

**Comment by sunderme** [comment]
a bit low quality screenshot. No idea what I see and what is wrong.

**Comment by sylbeth** [comment]
Yeah, sorry for that, I wanted to send something quick since I don't have much time right now. I have some sections which I don't need at this given time, so I commented them and collapsed? them, but now the arrows on the left are misaligned. I'm sorry, my English is not really good and I don't know the exact words to talk about it.

**Comment by sunderme** [comment]
no feedback.
Please come back, if you can provide a clearer picture (screencast. step by step instruction) on what is supposedly wrong.

**Comment by sylbeth** [comment]
Yeah, sorry, I have been busy this past week and every time I tried to replicate it I just couldn't. I'll try again whenever I can, I am sorry.

**Comment by sunderme** [comment]
no problem. Just come back when there is a way to reproduce it here.
