### ISSUE TITLE
Add tex's documents values as custom parameters before compiling

### ISSUE THREAD

**Issue by sylbeth** [texstudio-org/texstudio#2315]
### So, for this to make any sense it would need two main features:

1. The possibility to use the variables' values as a special chars (e.g. ?v{nameofthevariable})
2. The possibility to find the latest modified pdf in a folder to show in the viewer.

**Comment by sunderme** [comment]
this approach is the complete opposite of using git (or any version control system)
A release should just copy and rename the output pdf.

That said, there is no finding the latest pdf. It may be possible to use shell variables to change the filenames, but that is out of scope what txs wants to do, so I consider this a question for other users.

**Comment by sylbeth** [comment]
Yeah, I thought that with git it could be kind of stupid, given that you can just recover older pdfs from previous compilations, I'm sorry, I'm still new to all of this.

Still, I thought that it could be useful to have the name tied to the author variable, but I understand if that's out of the scope too.

Thank you, and I am sorry if I was annoying.

**Comment by sunderme** [comment]
no problem
