### ISSUE TITLE
[Question] CWL format

### ISSUE THREAD

**Issue by antshar** [texstudio-org/texstudio#2317]
I do really like the flexibility of `.cwl`s and it's ability to specify types of arguments, but also manage placeholders via `%<...%>`.

So my question is how to combine these two. I want to prioritize second argument to be selected first in my command, so I use the following
```
\mytest{%<name%>}{%<label%:select%>}
```
Now I want the second argument to be treated as a label. I tired so far
```
\mytest{%<name%>}{%<label%:select%>}#l
\mytest{%<name%>}{%<label%:select%>%labeldef}
\mytest{%<name%>}{%<label%:select,labeldef%>}
\mytest{%<name%>}{%<label%labeldef%:select%>}
```
but nothing from that seem to work. How can I do that properly?

**Comment by mbertucci47** [comment]
I think this should work:
```
\mytest{%<name%>}{%<label%:select%>}
\mytest{name}{label}#Sl
```
The line with `#S` is not shown in the completer.

**Comment by antshar** [comment]
@mbertucci47 thank you so much! I appreciate that.

**Comment by sunderme** [comment]
so, this is answered ?

**Comment by antshar** [comment]
@sunderme despite, the original question was "how to combine placeholders and modifiers like `%labeldef`", @mbertucci47's answer basically solves my original problem so such a workaround satisfies me.
