### ISSUE TITLE
Creating a user command may overwrite spacial commands.

### ISSUE THREAD

**Issue by sylbeth** [texstudio-org/texstudio#2319]
### Environment
- TeXstudio: VERSION 4.2.3 (git 4.2.3)
- Qt: 6.3.0 R
- OS: Windows 10 Pro
- TeX distribution: MiKTeX-pdfTeX 4.10 (MiKTeX 22.1)

### Expected behavior
Creating a new user command would not overwrite or delete special commands.

### Actual behavior
Creating a new user command with the same name (even in undercase/uppercase) as another command makes the first command be converted to a user command.

### How to reproduce
Creating a user command with the name git, for example.

![image](https://user-images.githubusercontent.com/102521501/167346164-dcf27faf-a24d-4845-8cad-9a895a7ef0a6.png)

**Comment by sunderme** [comment]
no idea what the issue is.

**Comment by sylbeth** [comment]
I created a user command, one named git:git and the command was cmd "/c git -am commit" or something along those lines. I clicked okay, and whenever I went back into settings, it got duplicated, now there were two git commands with exactly the same signature and the GIT command had suddenly disappeared. I erased the git commands that got created but that erased the original GIT command too. It got "magically" fixed, I don't know how, but at some point it just suddenly reappeared, probably when my texstudio crashed at some point. I don't know how it got fixed, it just did.

**Comment by octaeder** [comment]
It is not intended that you change the label userid0 (and the like). Especially it should not be the same as of an existing command (s. .ini file). In #2214 I discussed the problem with the editable label in more detail and some internals. But it's a little bit lengthy to read.

**Comment by sylbeth** [comment]
But isn't there any way to prevent it from happening? I didn't know that could happen and I feel like someone else could make the same mistake since I didn't find any warnings
