### ISSUE TITLE
High resolution icons

### ISSUE THREAD

**Issue by benjaminburkhardt** [texstudio-org/texstudio#232]
The icons have a pretty low resolution which makes them look pixelated

### Environment
- TeXstudio: TeXstudio 2.12.10
- Qt: Qt-Version 5.11.1, kompiliert mit Qt 5.11.1 R
- OS: Mac
- TeX distribution: texlive

### Expected behavior
High resolution icons that look great on builtin retina display and 4k Monitors

### Actual behavior
Low resolution icons that look pixelated on builtin retina display and 4k Monitors

### How to reproduce
Just run texstudio on a new macbook pro.

**Comment by sunderme** [comment]
use modern color scheme, classic does not support high res icons
