### ISSUE TITLE
TexStudio crashes when opening via start menu, but not via command line.

### ISSUE THREAD

**Issue by andrewlalis** [texstudio-org/texstudio#2322]
The title basically explains it all. When I start texstudio from my start menu, I see the window border appear and the texstudio application appear in my list of open applications for about 1 or 2 seconds, then it closes. If I open it by typing `texstudio` in my terminal, it opens and stays open just fine.

### Environment
- TeXstudio: 4.2.3
- Qt: 5.12.8
- OS: Linux Mint 20.3, with Cinnamon Desktop
- TeX distribution: texlive

In case it's needed, here is the `.desktop` file that triggers the application to open:
```
[Desktop Entry]
Categories=Office;Publishing;Qt;X-SuSE-Core-Office;X-Mandriva-Office-Publishing;X-Misc;
Exec=texstudio
GenericName=LaTeX Editor
GenericName[de]=LaTeX Editor
GenericName[fr]=Editeur LaTeX
GenericName[ru]=Редактор LaTeX
Comment=LaTeX development environment
Comment[de]=LaTeX Entwicklungsumgebung
Comment[fr]=Environnement de développement LaTeX
Comment[ru]=Среда разработки LaTeX
Icon=texstudio
Keywords=LaTeX;TeX;editor;
MimeType=text/x-tex;
Name=TeXstudio
StartupNotify=false
Terminal=false
Type=Application

```

**Comment by andrewlalis** [comment]
No, there is no mention of `LD_LIBRARY_PATH` in my `.bashrc`.

**Comment by sunderme** [comment]
there is a set-up problem on your computer. Nothing I can do to debug as txs is clearly working in principle.
