### ISSUE TITLE
Get pdf x and y position

### ISSUE THREAD

**Issue by egidioln** [texstudio-org/texstudio#2324]
Hey all, following up on my question in #2307, I implemented the following feature:

Ctrl+shift+LeftMouseClick on the pdfViewer copies to clipboard the mouse coordinates x and y in cm with respect to the bottom left corner of the page. This is useful to add floating elements (especially in beamer presentations) as in the following example:

```
\documentclass{beamer}
\usepackage{tikz}

\tikzstyle{float} = [overlay,remember picture, shift=(current page.south west)]

\begin{document}
		\tikz[float] \draw (0,0)  grid (16,10);
		\tikz[float] \node at (8.6955,4.32964) {\Huge a}; % this coordinate was obtained by ctrl+shift+click on the pdf and ctrl+v here
\end{document}
```
 
It's already working in the commit b7e0e9b80de943bb9389420b6809038efbd96bf8.

Let me know if there is interest in merging this.

**Comment by sunderme** [comment]
fine with me

**Comment by octaeder** [comment]
I observed that the mouse pointer changes to a cross when pressing Ctrl-Alt. But this is true for the magnifier pointer but not for the scroll (hand) pointer. I think it should be the same for the latter one.
Thx

**Comment by octaeder** [comment]
@sunderme @egidioln Did anyone get my last remark?

**Comment by egidioln** [comment]
@octaeder Not really... Here, with the magnifier tool selected, shift turns the pointer into a plus and alt, into a minus, which allows zooming in and out by clicking. Ctrl-alt has the same effect as alt and ctrl+shift, the same as shift... the new feature (ctrl+shift+click to get x and y) still works with the magnifier tool.

What maybe should be done is to deactivate the changing cursor when ctrl-shift is pressed (or even change it into something else, like a crosshair). Is that what you meant?

**Comment by octaeder** [comment]
@egidioln Thanks for clarification, I thought that the plus is the icon for your new feature, so one can better locate the point where you capture the coordinates. Newer seen that plus/minus before, now I see them in the View menu (only windowed pdfviewer). I use double click or scroll wheel with the scroll hand for zooming. And here Alt aswell as Shift doesn't change the hand to something else. And my point was that with Alt+Shift the hand also doesn't change the cursor into the plus (what I assumed to be your crosshair).
I'm with you that (regardless of scroll hand or magnifier) the mouse pointer should become some kind of a crosshair when pressing Ctrl+Shift. Even better if we could see the coordinates at the mouse pointer while moving it (s. app greenshot for an example), but I don't know how difficult it is to do so. Or they could be always shown in the bottom line of the pdfviewer when the mouse hovers over the pfd document. You may have a look at #2201: If scroll hand would have some kind of a crosshair (at the active point), I would say that changing to a crosshair on it's own would not be necessary anymore. I observe that the center of the small circle (the glass) of the magnifier is not the center of the enlarged part of the image. Thus it is not clear where you capture the coordinates. So one should enhance hand and magnifier to show where the active point is. If you have further questions then let me know.
Thx

**Comment by egidioln** [comment]
@octaeder These are very good ideas... I'll try to implement them little by little :)
