### ISSUE TITLE
Results from "Find Usages" reset after "Go to PDF" 

### ISSUE THREAD

**Issue by yzhang738** [texstudio-org/texstudio#2327]
Environment
TeXstudio: 4.2.3
Qt: 5.15.2
OS: Windows 10
TeX distribution: texlive

Expected behavior
Right-clicking `Find Usages` on a label will show a list of places that involve the label. If you do `Go to PDF`, the list should remain so that you can do `Go to PDF` on the next entry.

Actual behavior
Right-clicking `Find Usages` on a label will show a list of places that involve the label. But when you do `Go to PDF`, the list disappears. So this is a bug.

How to reproduce
Simply right-click `Find Usages` on any label and do `Go to PDF` on any entry. This will show the problem.

**Comment by octaeder** [comment]
s. #2297

**Comment by sunderme** [comment]
by the way, the list is still there, just change to the "Search Results" tab
