### ISSUE TITLE
LaTex PDF images embedded in document are not shown correctly by TexStudio preview

### ISSUE THREAD

**Issue by umbertolanza** [texstudio-org/texstudio#233]
In the image attached (sshot.png) I've opened the LaTex output PDF (document.pdf) file with a common reader (right) and with TexStudio preview (left). In my document I've embedded a PDF image of a plot made in R (brad.pdf), containing greek letters, which TexStudio doesn't show (in the axes titles of the plot). Hope you can fix it! Here is the source code:

\documentclass[11pt,a4paper,openany,hidelinks]{article}
\usepackage{times}
\usepackage{mathptmx}
\usepackage{textcomp}
\usepackage{graphicx}
\usepackage{sidecap}
\usepackage{caption}
\usepackage{float}
\usepackage{amsmath}
\usepackage{mathtools}
\usepackage{enumerate}
\usepackage{enumitem}
\usepackage{makeidx}
\usepackage{wrapfig}
\usepackage{subcaption}
\usepackage{amssymb}
\usepackage{ccicons}
\usepackage{hyperref}
\usepackage[svgnames]{xcolor}
\usepackage{footnote}
\usepackage{spreadtab}
\usepackage{titlesec}
\usepackage{lipsum}
\usepackage{multirow}
\usepackage{flafter}
\usepackage{gensymb}
\usepackage{tikz}
\usepackage{siunitx}
\usepackage{footnote}
\usepackage[bottom]{footmisc}
\usepackage[T1]{fontenc}
\usepackage[english]{babel}
\usepackage[english]{varioref}
\usepackage[utf8]{inputenc}
\usepackage[version=4]{mhchem}
\usepackage[makeroom]{cancel}
\usepackage[left=2.50cm, right=2.50cm, top=2.50cm, bottom=2.50cm]{geometry}
\usepackage{textgreek}

\hypersetup{colorlinks=false, linkbordercolor=blue, allcolors=blue}
\urlstyle{same}
%backend=bibtex, natbib=true, sorting=none, autocite=superscript

\usepackage{fancyhdr}

\pagestyle{fancy}
\fancyhf{}
\rhead{}
\lhead{\small \today}
\cfoot{\thepage}
\setlength\parindent{0pt}

\setcounter{secnumdepth}{4}

\titleformat{\paragraph}{\normalfont\normalsize\bfseries}{\theparagraph}{1em}{}\titlespacing*{\paragraph}{0pt}{3.25ex plus 1ex minus .2ex}{1.5ex plus .2ex}

\renewcommand{\textfraction}{0.05}
\renewcommand{\topfraction}{0.8}
\renewcommand{\bottomfraction}{0.8}
\renewcommand{\floatpagefraction}{0.75}

%CUSTOM TOC FONTSIZE
\usepackage{tocloft}

%\renewcommand\cftsecfont{\small\bfseries}
%\renewcommand\cftsecpagefont{\small}
%\renewcommand\cftsubsecfont{\small}
%\renewcommand\cftsubsecpagefont{\small}
%\renewcommand\cftsubsubsecfont{\small}
%\renewcommand\cftsubsubsecpagefont{\small}

\begin{document}
	
	\begin{figure}[h]
		\centering
		\includegraphics[scale=0.65]{brad}
		\caption{Calibration.}
		\label{fig:brad}
	\end{figure}
	
\end{document}

### Environment
- TeXstudio: 2.12.10
- Qt: 5.8.0
- OS: Windows 10
- TeX distribution: miktex 2.9
[document.pdf](https://github.com/texstudio-org/texstudio/files/2175519/document.pdf)
![sshot](https://user-images.githubusercontent.com/40993720/42442664-8ef6c554-836b-11e8-9842-0a665965398b.png)
[brad.pdf](https://github.com/texstudio-org/texstudio/files/2175525/brad.pdf)

**Comment by sunderme** [comment]
the fonts are not included in the image. Where does windows find its fonts ? (the windows viewer should be able to tell you that)

**Comment by sunderme** [comment]
it would be interestin to see where the symbol font comes from. Apparently txs does not find it ...

**Comment by umbertolanza** [comment]
The font comes with Windows.

![immagine](https://user-images.githubusercontent.com/40993720/42449728-1459e18e-8382-11e8-96c4-6b289d2f6721.png)

**Comment by sunderme** [comment]
I doubt that a little. At least your pdf viewer uses a type1 (post script) font for rendering ...

**Comment by umbertolanza** [comment]
Ok, so there's something I can do? Because in TexStudio's settings (advanced mode) I can't find anything useful. Otherwise I will continue using it anyway, but it would be interesting if it could be solved in some manner.

**Comment by umbertolanza** [comment]
Ok! here it is
![texstudio_2018-07-09_18-44-57](https://user-images.githubusercontent.com/40993720/42464062-3917edba-83a8-11e8-90de-5098f19a1d9d.png)

**Comment by sunderme** [comment]
apparently txs uses symbol.ttf which delivers incorrect results. I don‘t think that there is much I can do.
You could try whether texworks shows the same behaviour....

**Comment by Ar7ac** [comment]
Is there the possibility to increase the option: embed all fonts (including the 14 base fonts)

**Comment by umbertolanza** [comment]
Where is this option?

**Comment by aubreyz** [comment]
I think this is a LaTex issue and an issue with your particular figure -- not a TexStudio issue. 

If the font's are not embedded, not being able to see them in thre TexStudio viewer is the least of your problems -- in fact that is a good thing because it is telling you that some end users and professional printers are going to be receiving a mangled file depending on their external fonts. 

How are you compiling?
Where is this figure from? Is it an EPS Figure or what?

See 
https://tex.stackexchange.com/questions/149012/embed-all-the-fonts-during-compiling-with-pdflatex
https://tex.stackexchange.com/questions/24002/turning-off-font-subsetting-in-pdftex/24005#24005

and especially the below which tells you about how to fix your Figure. 

https://sites.google.com/site/xyzliwen/resource/embed_font_ieee_pdf_explore

Perhaps try XeLatex not PdfLatex
