### ISSUE TITLE
TexStudio can not show eps while using XeLaTeX

### ISSUE THREAD

**Issue by sun0727** [texstudio-org/texstudio#235]
### Environment
- TeXstudio: 2.12.10
- Qt: QT5
- OS: win10
- TeX distribution: TexLive 2017

### Expected behavior
Can show eps-image when using XeLaTeX

### Actual behavior
Can show pdf-image but not for eps-Image wihth XeLaTeX
Something I have found：
Case 1： xelatex + TexStudio -> eps-image can not show, pdf-image worked
Case 2： xelatex + Texworks -> both worked

#### MWE

```tex
\documentclass{article}
\usepackage{graphicx}
\begin{document}
    \includegraphics[scale=0.2]{testeps.eps}
    \\
    \includegraphics[scale=0.2]{testpdf.pdf} % worked
\end{document}
```

#### My TexStudio-Confi 
![confi](https://i.stack.imgur.com/M7kxH.png)

#### Log
```
This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017/W32TeX) (preloaded format=xelatex 2017.9.23)  9 JUL 2018 21:38
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**./document.tex
(./document.tex
LaTeX2e <2017-04-15>
Babel <3.13> and hyphenation patterns for 84 language(s) loaded.
(d:/TexLive/2017/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(d:/TexLive/2017/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2014/09/29 v1.4h Standard LaTeX file (size option)
)
\c@part=\count79
\c@section=\count80
\c@subsection=\count81
\c@subsubsection=\count82
\c@paragraph=\count83
\c@subparagraph=\count84
\c@figure=\count85
\c@table=\count86
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
)
(d:/TexLive/2017/texmf-dist/tex/latex/graphics/graphicx.sty
Package: graphicx 2017/06/01 v1.1a Enhanced LaTeX Graphics (DPC,SPQR)

(d:/TexLive/2017/texmf-dist/tex/latex/graphics/keyval.sty
Package: keyval 2014/10/28 v1.15 key=value parser (DPC)
\KV@toks@=\toks14
)
(d:/TexLive/2017/texmf-dist/tex/latex/graphics/graphics.sty
Package: graphics 2017/06/25 v1.2c Standard LaTeX Graphics (DPC,SPQR)

(d:/TexLive/2017/texmf-dist/tex/latex/graphics/trig.sty
Package: trig 2016/01/03 v1.10 sin cos tan (DPC)
)
(d:/TexLive/2017/texmf-dist/tex/latex/graphics-cfg/graphics.cfg
File: graphics.cfg 2016/06/04 v1.11 sample graphics configuration
)
Package graphics Info: Driver file: xetex.def on input line 99.

(d:/TexLive/2017/texmf-dist/tex/latex/graphics-def/xetex.def
File: xetex.def 2017/06/24 v5.0h Graphics/color driver for xetex
))
\Gin@req@height=\dimen103
\Gin@req@width=\dimen104
) (./document.aux)
\openout1 = `document.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 3.
LaTeX Font Info:    ... okay on input line 3.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 3.
LaTeX Font Info:    ... okay on input line 3.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 3.
LaTeX Font Info:    ... okay on input line 3.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 3.
LaTeX Font Info:    ... okay on input line 3.
LaTeX Font Info:    Checking defaults for TU/lmr/m/n on input line 3.
LaTeX Font Info:    ... okay on input line 3.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 3.
LaTeX Font Info:    ... okay on input line 3.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 3.
LaTeX Font Info:    ... okay on input line 3.
File: testeps.eps Graphic file (type eps)
<testeps.eps>
File: testpdf.pdf Graphic file (type pdf)
<use testpdf.pdf>
 [1] (./document.aux) ) 
Here is how much of TeX's memory you used:
 599 strings out of 492998
 7295 string characters out of 6137851
 66625 words of memory out of 5000000
 4640 multiletter control sequences out of 15000+600000
 3648 words of font info for 15 fonts, out of 8000000 for 9000
 1348 hyphenation exceptions out of 8191
 25i,5n,19p,203b,146s stack positions out of 5000i,500n,10000p,200000b,80000s

Output written on document.pdf (1 page).
```

related Question: [Why TexStudio can not show eps-figure?](https://tex.stackexchange.com/questions/439958/why-texstudio-can-not-show-eps-figure)

### update
1. epsfile: [testeps.eps](https://drive.google.com/file/d/1tqNoQAzq-x2UOLCdWU3rUuLDNJh7CV42/view?usp=sharing)
2. change xelatex to pdflatex worked... can not understand
3. pdf-file:  [xelatx_without_eps](https://drive.google.com/open?id=1OpU1Ri_uaVeHNMs2QW7YPcxUlREnUYpk)
[pdf_latex_with_eps](https://drive.google.com/open?id=1yRU1NM-t8bz1jeEhgbNDMelUTjKQ8yjk)

**Comment by sunderme** [comment]
please provide the missing image-files

**Comment by sun0727** [comment]
@sunderme  I have updated

**Comment by sunderme** [comment]
works fine here with xelatex

**Comment by sunderme** [comment]
please upload the xelatex result file (pdf)

**Comment by sun0727** [comment]
@sunderme  I have uploaded

**Comment by sunderme** [comment]
there is no image shown with any pdf viewer, so there is no image in the file.
Hence you xelatex set-up fails, texstudio is not to blame

**Comment by sun0727** [comment]
@sunderme , The question is, if I use Texworks or other editor like vs code. Under Xelatex all works well, only TeXstudio don't show the eps-img, see the [Gif](https://drive.google.com/open?id=17rq-phsbFfpVuzlMJcBVjV2snw4jg_mC)

**Comment by sunderme** [comment]
the pdf does not contain the eps, hence your setting for xelatex is faulty. Check the options.
you can cross check by opeing directly the pdf which you generate via texworks.

**Comment by sun0727** [comment]
@sunderme  I didn't find any faulty. chain is always: txs:///xelatex | txs:///view-pdf,

**Comment by sunderme** [comment]
how is the xelatex command defined ? (options/commands)

**Comment by sun0727** [comment]
@sunderme  uploaded  [command](https://drive.google.com/open?id=1SxJ9pQHJUE6DZVC6OVL7GTaIHaI_saxE)

**Comment by thatlittleboy** [comment]
What does 

```
\listfiles
\documentclass{article}
\usepackage{graphicx}

\begin{document}
	\includegraphics[scale=0.1]{testeps.eps}
\end{document}
```

give you in the log file? (look for `*File List*`)

Mine gives 

```
*File List*
 article.cls    2014/09/29 v1.4h Standard LaTeX document class
  size10.clo    2014/09/29 v1.4h Standard LaTeX file (size option)
graphicx.sty    2017/06/01 v1.1a Enhanced LaTeX Graphics (DPC,SPQR)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
graphics.sty    2017/06/25 v1.2c Standard LaTeX Graphics (DPC,SPQR)
    trig.sty    2016/01/03 v1.10 sin cos tan (DPC)
graphics.cfg    2016/06/04 v1.11 sample graphics configuration
   xetex.def    2017/06/24 v5.0h Graphics/color driver for xetex
 testeps.eps    Graphic file (type eps)
 ***********
```

**Comment by sun0727** [comment]
@thatlittleboy  mine gives, TeXStudio and Texworks have same output, but TeXStudio still can not show the img.. 
```
 *File List*
 article.cls    2014/09/29 v1.4h Standard LaTeX document class
  size10.clo    2014/09/29 v1.4h Standard LaTeX file (size option)
graphicx.sty    2017/06/01 v1.1a Enhanced LaTeX Graphics (DPC,SPQR)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
graphics.sty    2017/06/25 v1.2c Standard LaTeX Graphics (DPC,SPQR)
    trig.sty    2016/01/03 v1.10 sin cos tan (DPC)
graphics.cfg    2016/06/04 v1.11 sample graphics configuration
   xetex.def    2017/06/24 v5.0h Graphics/color driver for xetex
 testeps.eps    Graphic file (type eps)
 ***********
```

**Comment by thatlittleboy** [comment]
I cannot reproduce; The file list seems to indicate that the file is included in the output pdf. (1) Try without the file extension, and (2) draw a frame box around your eps, like 

```
\fbox{\includegraphics[scale=0.1]{testeps}}
```

**Comment by sun0727** [comment]
@thatlittleboy  still not work 😭
![image](https://user-images.githubusercontent.com/19495916/42715399-27661f5e-86f7-11e8-9ae5-408c4fb008e6.png)

**Comment by sun0727** [comment]
@thatlittleboy 
![pap](https://user-images.githubusercontent.com/19495916/42715601-fefb8aee-86f7-11e8-8ec4-7250239c8541.gif)

**Comment by Ablian** [comment]
@Liampor 
Has your problem been solved?
I have the same problem？
eps images cann't display in TeXStudio

**Comment by Liampor** [comment]
@Ablian  acutally no, but after re-install the system it wokrs again. I can't explain, alternatively you can first convert eps to pdf, then just use pdf-figure.

**Comment by muzimuzhi** [comment]
@Ablian 
It is more recommended to open a new issue, if you think that the problem is texstudio related (i.e., using the same compiling engine and tex doc, other editors works ok).

**Comment by Ablian** [comment]
@Liampor 
Simple and rude，but effective. 

The whole afternoon I reinstalled Windows.

 And now the software in the new system works well. 

Thank you!
