### ISSUE TITLE
Autocomplete selection rollover

### ISSUE THREAD

**Issue by skaanbilly2** [texstudio-org/texstudio#2350]
Dear

I love texstudio but often I encounter the case where I need to select a label when referencing something. The autocomplete helps a lot but even with many levels of structure, I find myself scrolling down the list with the down key. It would be handy if the up key would allow the selected value to rollover into the last entry instead of doing nothing.

I added a picture for  clarity. In this case I would want the up key to issue a jump of the selected entry from the first entry ..:2d_derivation to the last ..:vectors.
![texstudio_rollover](https://user-images.githubusercontent.com/25158966/169692387-561fdc7f-caeb-4d51-8d5b-88d6d5a4f605.png)

Kind regards

**Comment by sunderme** [comment]
unlikely to be implemented.
you know about partial completion with tab ?

**Comment by sunderme** [comment]
`home`/`end` work. `end` jumps to the last of the currently shown completion words. If there are more than 100, it jumps to the 100th and loads the next 100 into the completer, so more than one press of `end` may be necessary to get to really the last one.

**Comment by skaanbilly2** [comment]
> unlikely to be implemented. you know about partial completion with tab ?

Yes I know about partial completion with tab. 
I did not know the end key was available, that offers basically the same functionality. I suppose the end key is a bit less intuitive as fewer people use them nowadays but it should suffice.
