### ISSUE TITLE
doubletap AltGr-symbols required with E1-keyboard

### ISSUE THREAD

**Issue by maamx** [texstudio-org/texstudio#2351]
Using the E1-Europatastatur german keyboard layout, texstudio does not write symbols like backslash <\> or AltGr-Brackets <{ [ ] }> without doubletap. It requires me to doubletap for writing one initial symbol − additional followup-symbols of the same type are written with one tap though. 
Special symbols of the E1 layout requiring AltGr+F -> (release both) -> [press key you want] do not work at all.
All of this works in texmaker and non-latex texteditors (example: notepad++, libreoffice, …) tough.
All mentioned symbols (serving as an example) work in texstudio with a classic QWERTZ german layout.

### Environment
- TeXstudio:  TeXstudio 4.2.3 (git 4.2.3) 
- Qt:  Nutze Qt-Version 6.3.0, kompiliert mit Qt 6.3.0 R 
- OS:  Windows 10 
- TeX distribution:  texlive

### expected beahvior

AltGr-symbols get written in Editor after one tap.

### current behavior
AltGr-symbols get written in editor after doubletap only, if its the first symbol in a new "word".

### how to reproduce
Windows 10 newest version. Use E1-Europatastatur-layout as distributed here: https://www.europatastatur.de/e1 - the version with capslock becoming a second AltGr. Use latest texstudio version. Write in editor AltGr+7/8/9/0/ß

**Comment by sunderme** [comment]
sounds like a qt issue.
try txs qt5.
Otherwise than that, nothing we can do, as qt handles basically keyboard.

**Comment by sunderme** [comment]
no feedback

**Comment by maamx** [comment]
Here's my feedback:
QT5 doesn't work. Switched back to Linux, everything works fine.
Thanks for the suggestion though
