### ISSUE TITLE
TeXstudio editor window always remains active after compiling when using integrated PDF viewer in separated window

### ISSUE THREAD

**Issue by pat-githubber** [texstudio-org/texstudio#2352]
### Describe the feature and the current behavior/state
Initial state: Using TeXstudio in one window (editor window) and the integrated PDF viewer in a separate window (PDF window). Consequently, the _embedded viewer_ is **not** used.

When my courser is in the editor window and I start to compile the code, then - after the compiling process is finished - the PDF window becomes the active window and I have to click on the editor window again to continue writing. This process has to be repeated every time after compiling.

It would be beneficial if the editor window always stays the active window (or at least, there is an option for that).

### Who will benefit with this feature
Everyone who is working with the integrated PDF viewer as a separate window.

**Comment by sunderme** [comment]
by default, txs distinguishes between "compile" (F6) and "build" F5
compile does not shift focus to viewer, whereas build (in default set-up) does.

**Comment by pat-githubber** [comment]
Woah?! Somehow, I never realized that 😮 Thanks 🙏
