### ISSUE TITLE
Line thickness and rendering are different from actual ones.

### ISSUE THREAD

**Issue by mathliker** [texstudio-org/texstudio#2367]
### Environment
- TeXstudio: 4.2.3
- Qt: 5.15.2
- OS: Windows10
- TeX distribution: texlive2022 

### Expected behavior
I want to make the lines of the table bold. But the built-in pdf viewer is not the same as the actual result.

### Actual behavior
```tex
\documentclass{article}
\usepackage{makecell}
\newcolumntype{z}{p{1.5cm}<{\centering}}
\begin{document}
\centering
\begin{tabular}{z|z|z|z|z|z|z}
\Xhline{1.2pt}
\(x_i\)&0.4     & 0.55    & 0.65    & 0.80 & 0.95 & 1.05    \\ \hline
\(y_i\)&0.41075 & 0.57815 & 0.69675 & 0.90 & 1.00    & 1.25382 \\ \Xhline{1.2pt}
\end{tabular}
\end{document}
```
Please click the image below to view.
![QQ截图20220531101542](https://user-images.githubusercontent.com/104699857/171079653-73071f35-d483-4d0c-a658-d4d7e62c2fda.png)
After using magnifying glass or external pdf viewer, it will be found to be normal.

**Comment by sunderme** [comment]
no feedback
