### ISSUE TITLE
Violent Shaking With Wrong Panes Layout

### ISSUE THREAD

**Issue by ImperialSquid** [texstudio-org/texstudio#2373]
Violent shaking occurs with the right mix of scrolling and resizing the viewer.

### Environment
TeXstudio 4.2.3 (git 4.2.3)
Using Qt Version 6.3.0, compiled with Qt 6.3.0 R
- OS: Windows 10
- TeX distribution: mikrtex

### Expected behaviour
Not this...?

### Actual behaviour
The videos weren't taken at a high enough frame rate to show the full effect since it looks like it happens every frame, but it still shows movement at least.
![texstudio_lEubRC8AeE](https://user-images.githubusercontent.com/44560551/171423198-d85a65cc-b54e-4c5c-a24f-5e51d3b1b571.gif)
![texstudio_fIpXg6Wy60](https://user-images.githubusercontent.com/44560551/171426936-3abf9977-564d-4da3-8d12-37b5cf426152.gif)

### How to reproduce
- Be in half window mode, scroll down a document and with the viewer wider than the minimum width
- Scroll up to the very top
- Pull the viewer to the minimum width

Restarting and changing docs didn't help btw

**Comment by sunderme** [comment]
try tried on another computer, still not reproducible.
So, I close this for now.
