### ISSUE TITLE
Dead links to TXS for macOS 10.15+ (Qt5)

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#2375]
On http://texstudio.sourceforge.net/#download, the links to https://github.com/texstudio-org/texstudio/releases/download/4.2.3/texstudio-4.2.3-osx-qt5.dmg (10.15+ 	4.2.3 (Qt5) “dmg” and “download”) are dead (Page 404).

BTW, AFAIU, “Mac OS X” should nowadays be “macOS”.

**Comment by muzimuzhi** [comment]
BTW [v4.2.3](https://github.com/texstudio-org/texstudio/releases/tag/4.2.3) provides no Qt5 build for macOS. Qt5 on macOS is deactivated in https://github.com/texstudio-org/texstudio/commit/5557b7091bda8abbffda2ca59f90eba86adbb91d which takes effect since v4.2.1beta1.

**Comment by dbitouze** [comment]
> BTW [v4.2.3](https://github.com/texstudio-org/texstudio/releases/tag/4.2.3) provides no Qt5 build for macOS. Qt5 on macOS is deactivated in [5557b70](https://github.com/texstudio-org/texstudio/commit/5557b7091bda8abbffda2ca59f90eba86adbb91d) which takes effect since v4.2.1beta1.

Ah, good to know, thanks. Hence the corresponding line should be removed from http://texstudio.sourceforge.net/#download.
