### ISSUE TITLE
[Feature Request] Multiple parallel instances run on windows

### ISSUE THREAD

**Issue by Parlazo** [texstudio-org/texstudio#2380]
### Describe the feature and the current behavior/state
I have TexStudio installed on windows and then i did download the portable version too
now i would like to run them parallel in two or may multiple instances
but when the installes instance is open the portable version some how does not open a new instance.

### Who will benefit with this feature?
Every one.

### Any Other info
I would like to use different instances on different sub projects

**Comment by sunderme** [comment]
you can start txs with a command option "--start-always"
