### ISSUE TITLE
Expansion of filename in magic comments

### ISSUE THREAD

**Issue by samcarter** [texstudio-org/texstudio#2391]
### Environment
- TeXstudio:  4.2.3 (git 4.2.2-12-gf91ad0d15) (also tried 4.3.0beta1)
- Qt:  6.2.3, compiled with Qt 6.2.2 R
- OS:  MacOS 11.6
- TeX distribution:  texlive 2022

### Question

What is the currently recommended way to expand the base name in magic comments?

In old versions of texstudio (e.g. 2.12), I used a magic comment like

```
% !TeX program = txs:///view-pdf "?am)_notes.pdf"
```

to get the basename and modify it (e.g. adding the "_notes" bit), but with current texstudio it now seems to try to open the unexpanded name:

![Screenshot 2022-06-08 at 14 32 43](https://user-images.githubusercontent.com/43832342/172618829-e7c0203f-2f12-4d55-b96c-0a499f41f432.png)

Is there a way with current texstudio to do something similar?

### Bigger context:

In case you are wondering, why I'm trying to use such a complicate construct: I would like to automatically compile multiple versions from the same source. This previously worked: 

```
% !TeX program = latexmk -pdf -interaction=nonstopmode -synctex=1 -jobname=% -pretex="\newif\ifnotes \notesfalse" -usepretex % | latexmk -pdf -interaction=nonstopmode -synctex=1 -jobname=%_notes -pretex="\newif\ifnotes \notestrue" -usepretex % | txs:///view-log | txs:///view-pdf "?am)_notes.pdf"
\documentclass{beamer}

\begin{document}
\begin{frame}

this version has

\ifnotes
  notes
\fi

\end{frame}
\end{document}
```

**Comment by sunderme** [comment]
hmmm, not sure if that code worked, it probably has not worked for 5 years.
How do you trigger that command anyway, since I get a failure when calling `compile`.
The manual says:
```
% !TeX program = pdflatex

Defines the compiler to be used for the document. To be precise, it overrides the default compiler (command txs:///compile) which is used in the actions "Build & View" as well as "Compile". Valid options are "latex","pdflatex","xelatex","lualatex" and "usern" (e.g. user0 as user defined command 0)
```
So, best approach seems to define user commands.

**Comment by samcarter** [comment]
I just tried with 

```
latexmk -pdf -interaction=nonstopmode -synctex=1 -jobname=% -pretex="\newif\ifnotes \notesfalse" -usepretex % | latexmk -pdf -interaction=nonstopmode -synctex=1 -jobname=%_notes -pretex="\newif\ifnotes \notestrue" -usepretex % | txs:///view-log | txs:///view-pdf "?am)_notes.pdf"
```

as a user command, but get the exact same problem

**Comment by samcarter** [comment]
Your fix works perfectly fine! Thanks a lot!
