### ISSUE TITLE
Noto not recognized as a mono font

### ISSUE THREAD

**Issue by raffaem** [texstudio-org/texstudio#2394]
### Environment
- TeXstudio: 4.2.3
- Qt:  5.15.3
- OS: Fedora Workstation 36
- TeX distribution: TexLive

### Expected behavior

Click on Options -> Configure TexStudio .-> Editor.

Make sure "Show Only Monospaced Font" is unselected.

Notice how "Noto Sans Mono" is in the "Font Family" list.

Check "Show Only Monospaced Font".

Now "Noto Sans Mono" is not in the "Font Family" list anymore.

### Actual behavior
See above

### How to reproduce
See above

**Comment by sunderme** [comment]
txs uses the qt QFontDatabase to filter for "fixedPitch" fonts.
Apparently "Noto Sans Mono" is not listed as one of those.
Nothing I can do.
