### ISSUE TITLE
TS and TexLive: Package help not working

### ISSUE THREAD

**Issue by foreachthing** [texstudio-org/texstudio#24]
On Windows 7 x64, using Tex-Live (2017), the package help does not work (TS 2.12.6).
It _always_ tells me, that there is no documentation available.

![image](https://user-images.githubusercontent.com/10420187/35681692-7ea75c88-075e-11e8-9db7-45f87591831d.png)
This package's documentation is located in: `C:\texlive\2017\texmf-dist\doc\latex\base\ifthen.pdf`

_Scan LaTeX distro for installed packages_ is checked - not sure if that has anything to do with the docs.

Need more info? Please let me know.

**Comment by jonasstein** [comment]
I tried it with TL 2017 and TS 2.12.6 compiled from source in 2018-01 and it worked fine on Linux. Does texdoc ifthen work on your system?

**Comment by foreachthing** [comment]
> texdoc ?
I found out that right-click on the '\usepackage{ifthen}' and then "open package documentation" works! This is even better - much faster.
So, you could close this, as this workaround works for me even better!

**Comment by dbitouze** [comment]
>This is even better

Except when you want to read the documentation of a package you don't use in the document you're currently working on...

**Comment by sunderme** [comment]
this should be fixed in 2.12.8
