### ISSUE TITLE
Windows - NSIS no silent uninstall

### ISSUE THREAD

**Issue by Swarheley** [texstudio-org/texstudio#240]
### Environment
- TeXstudio: 2.12.10
- Qt: 5.8.0
- OS: Windows 10 - 1803
- TeX distribution:  texlive 2018

### Expected behavior
Silent uninstall using "uninstall.exe" /S

### Actual behavior
Silent switch does not work, when running the uninstall.exe, a message box appears instead.

I've reported this issue already in https://github.com/texstudio-org/texstudio/issues/92, but apparently this has not been fully fixed.

### How to reproduce
Install any release >= 2.12.8 on Windows.

**Comment by alex85k** [comment]
Also Windows installer has some wrong parameters: https://github.com/texstudio-org/texstudio/blob/master/utilities/texstudio.nsi
The version is still 2.12.8 and the description is a standard placeholder.

This leads to buggy automatic installation process with tools like puppet. It sees current version as
```
package { 'TeXstudio - A short description goes here':
  ensure => '"2.12.8"',
}
```

**Comment by sunderme** [comment]
possibly fixed, please try development build on bintray.com/sunderme/texstudio/texstudio-win
