### ISSUE TITLE
Feature Request: Allow pasting of spreadsheet data into the Quick Tabular or Quick Array windows.

### ISSUE THREAD

**Issue by fjpereny** [texstudio-org/texstudio#2401]
### Describe the feature and the current behavior/state
Currently users need to type each individual cell's data in manually.  I would like a feature that would allow users to select cells of data from a spreadsheet and past them in.  Normally this data is tab delineated.

### Who will benefit with this feature?
All users who work with spreadsheets and tables will benefit from this.

**Comment by the-science-guy** [comment]
Have you tried using the csvsimple-l3 package to directly read data from a file? Considering you can convert your spreadsheet to a CSV format.

Here is a minimal example:
File contents:

x, y, z
1, 2, 3
4, 5, 6
7, 8, 9

`\begin{tabular}{|c|c|c|}
\hline
x & y & z \\ \hline
\csvreader[late after line = \\ \hline]{file.csv}{1=\a,2=\b,3=\c}{\a & \b & \c}
\end{tabular}`

![image](https://user-images.githubusercontent.com/98602834/173164947-e103e068-d797-4abf-b80c-5173075cbd0d.png)

The csvreader command uses 3 arguments, 1st the filename, 2nd assigning the columns to names and the 3rd allows you to arrange them in any desired order for the table. The option `late after line` appends any assigned code, here to terminate the row and place a line at each end. If your data has no header line with strings, add the `no header` option in addition to `late after line`.

**Comment by fjpereny** [comment]
> Have you tried using the csvsimple-l3 package to directly read data from a file? Considering you can convert your spreadsheet to a CSV format, maybe as a stop-gap.
> 
> Here is a minimal example: File contents:
> 
> x, y, z 1, 2, 3 4, 5, 6 7, 8, 9
> 
> `\begin{tabular}{|c|c|c|} \hline x & y & z \\ \hline \csvreader[late after line = \\ \hline]{file.csv}{1=\a,2=\b,3=\c}{\a & \b & \c} \end{tabular}`
> 
> ![image](https://user-images.githubusercontent.com/98602834/173164947-e103e068-d797-4abf-b80c-5173075cbd0d.png)
> 
> The csvreader command uses 3 arguments, 1st the filename, 2nd assigning the columns to names and the 3rd allows you to arrange them in any desired order for the table. The option `late after line` appends any assigned code, here to terminate the row and place a line at each end. If your data has no header line with strings, add the `no header` option in addition to `late after line`.

I have done it, but there are so many times I just want to copy and paste a few things into my document for a quick table and it becomes more work than it should.

I would like this task assigned to me.  I have started to implement this feature and I will submit a pull request once I am complete on it.

**Comment by fjpereny** [comment]
I have issued a pull request for this issue.

https://github.com/texstudio-org/texstudio/pull/2402
