### ISSUE TITLE
syntax highlighting stays in math mode

### ISSUE THREAD

**Issue by BrauerSuzuki** [texstudio-org/texstudio#2411]
### Environment
- TeXstudio: 4.2.3
- Qt: 6.3.0
- OS: arch linux kernel 5.18.0
- TeX distribution: texlive 2021

### Expected behavior
In "large" tex files the syntax highlighting breaks at some point, in the sense that it stays in math mode for the remainder of the document. In the attached screenshot it happens after \[\boxed{...}\]. Strangely, such a construct was used earlier in the same document without any issues. Also, the file compiles without errors.
![texstudio_bug](https://user-images.githubusercontent.com/107473466/173559605-53706b1e-b0a0-44d8-a51d-b128c0f4939b.png)
.

**Comment by muzimuzhi** [comment]
Please provide a textual, hence copiable, example/snippet that can reproduce the highlighting issue.

**Comment by BrauerSuzuki** [comment]
Well, I was wrong, it is not related to large files. In fact, the following is a minimal example:

`\documentclass{minimal}
\usepackage{amsmath}

\begin{document}

$\boxed{a}$ works $\boxed{{a}}$ broken

\end{document}`

The issue is the use of parenthesis inside \boxed.
