### ISSUE TITLE
Allow [CRTL] + [/] as shortcut combination

### ISSUE THREAD

**Issue by randolf-scholz** [texstudio-org/texstudio#2426]
Many editors use this as a default hotkey combination for comments, it would be appreciated if TeXstudio could

- enable is automatically as a default alternative hotkey combo for comments
- at least allow to configure this hotkey combination

### Environment
- TeXstudio: 4.2.3 (via https://code.launchpad.net/~sunderme/+archive/ubuntu/texstudio)
- Qt: Using Qt Version 5.15.3, compiled with Qt 5.15.3 R
- OS: Ubuntu 22.04 LTS
- TeX distribution: texlive-2021

**Comment by sunderme** [comment]
I don't see why this shortcut should not work ?
Can't test as don't have a US keyboard.
I will not change the default as on other language keyboards ctrl+/ is odd.

**Comment by randolf-scholz** [comment]
@sunderme I tried changing it in the shortcut selection (`shortcuts>Menus>Idefix>Toggle Comment`), but it only allows to select shortcuts of the form

- [crtl] + [alt] + [...]
- [crtl] + [shift] + [...]
- [crtl] + [F-Key]
- [crtl] + [number]
- [crtl] + [Alpha]
- [crtl] + [tab]/[backspace]/[del]/[arrow]/[Page-up/down]
- shortcuts that don't start with [crtl]

**Comment by randolf-scholz** [comment]
> I will not change the default as on other language keyboards ctrl+/ is odd.

That's absolutely fine. I would recommend though to consider setting it as a default for the "Additional Shortcut".

**Comment by sunderme** [comment]
maybe I miss a point, but you can edit shortcuts by either directly writing the code,i.e. `ctrl+/` or by pressing ctrl+/ when the shortcut combobox is active. So you can enter the shortcut for comments.

**Comment by randolf-scholz** [comment]
@sunderme Oh! There was nothing indicating that was an option, it seemed like it was just a drop-down menu. Most UIs write something like `<press keys>` to notify the user this is possible.

**Comment by octaeder** [comment]
> @sunderme Oh! There was nothing indicating that was an option, it seemed like it was just a drop-down menu. Most UIs write something like `<press keys>` to notify the user this is possible.

![grafik](https://user-images.githubusercontent.com/102688820/175253459-72b44716-4e09-470a-aaec-5f0bdd77272f.png)
Have a look at the mouse over.

**Comment by randolf-scholz** [comment]
@octaeder Guess I'm the DAU, never noticed this tool-tip.

**Comment by octaeder** [comment]
> maybe I miss a point, but you can edit shortcuts by either directly writing the code,i.e. `ctrl+/` or by pressing ctrl+/ when the shortcut combobox is active. So you can enter the shortcut for comments.

@sunderme [User manual section 1.6](https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html#SECTION05) only mentions two ways of changing: "A shortcut can be selected from the drop down list or put in as text directly." Hit shortcut combination (option (2) in tooltip above) is not mentioned. Should manual be amanded?
