### ISSUE TITLE
Compilation not save the file

### ISSUE THREAD

**Issue by andrexleitao** [texstudio-org/texstudio#2429]
### Environment
- TeXstudio: 4.0.2 and 4.2.3
- OS:  Windows 11
- TeX distribution: miktex

### Expected behavior
When pressing the key to run any file, the modifications in the text are automatically saved.

### Actual behavior
When pressing the key to run any file, all the previous changes in the text are not saved.

### How to reproduce
Create a simple file, run it, make a change and run it again.

**Comment by muzimuzhi** [comment]
Have you tried latest stable release [v4.2.3](https://github.com/texstudio-org/texstudio/releases/tag/4.2.3)?

**Comment by andrexleitao** [comment]
> I think, it saves but the marker (green/yellow) was not updated. And I think this is fixed in dev.

Yeah, you are right, @sunderme, but what do you mean by "fixed in dev"?

**Comment by sunderme** [comment]
current development state

**Comment by andrexleitao** [comment]
@sunderme you mean in the version 4.2.3?
If so, the same bug happens!
