### ISSUE TITLE
Esc-Button does not work anymore

### ISSUE THREAD

**Issue by FloMiLe** [texstudio-org/texstudio#243]
In previous versions (prior to 2.12.10), one could "Close Element[s]" with the Esc button. Now, however, Esc does not do anything anymore. It seems the button is not recognized at all as it does not close the auto completion menu or any tooltips either.

### Environment
- TeXstudio: 2.12.10
- Qt:  5.11.1
- OS: macOS 10.13.6

**Comment by sunderme** [comment]
qt 5.11 bug

**Comment by sunderme** [comment]
fixed

**Comment by FloMiLe** [comment]
It would be great to have Esc functionality back. – When do you think you will release the next update?
