### ISSUE TITLE
Error: Could not start the command: pdflatex.exe -synctex=1 -interaction=nonstopmode "Day-1-Practice File".tex

### ISSUE THREAD

**Issue by profbhumika** [texstudio-org/texstudio#2430]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution:

**Comment by profbhumika** [comment]
Error: Could not start the command: pdflatex.exe -synctex=1 -interaction=nonstopmode "Day-1-Practice File".tex

**Comment by sunderme** [comment]
no feedback
