### ISSUE TITLE
when close texstudio, it prompts "Storing session information into /Users/username/.config/texstudio/lastSession.txss2 failed. File exists but is not writeable." 

### ISSUE THREAD

**Issue by xy-zheng** [texstudio-org/texstudio#2434]
But I find that there is no folder './configure/textstudio'

**Comment by sunderme** [comment]
sounds like osx app security prevents txs from writing into the home folder. Probably you need to allow it to the app (txs).

**Comment by sunderme** [comment]
all assuming, it is OSX for lack of any answers to the template.

**Comment by sunderme** [comment]
assume osx rights issue

**Comment by FriedrichYang** [comment]
I also encountered this problem after I changed my windows user name😭

**Comment by FriedrichYang** [comment]
I also have various problems with other programs, but most of them can be solved by in an unbeliveable way: run the program as an administrator, yes. But in this case, you have to right-click and select "run as admin" each time you open texstudio.  You can set "run as admin" as default in "property---compability"
![runasadmin](https://user-images.githubusercontent.com/59993831/194710285-9f2ddfe1-d9ac-4ee5-b7cd-302db1d42163.png)

**Comment by Ronchy2000** [comment]
[ithub error message in saving files. #3736](https://github.com/texstudio-org/texstudio/issues/3736)

check this issue plz, I solved this problem.
