### ISSUE TITLE
Query regarding the bibliography {Decomposition. Bib} is not working in my .tex file?

### ISSUE THREAD

**Issue by Mathi50** [texstudio-org/texstudio#2435]
Hi,
I could not run the bibliography file in my .tex file. It is showing the following errors,
Can any one help me to clear this ?
Any help will be appreciated.
 
`Process started: latex.exe -src -interaction=nonstopmode "Decomposition".tex

Process exited with error(s)

Process started: dvips.exe -o "Decomposition".ps "Decomposition".dvi

This is dvips(k) 5.999 Copyright 2019 Radical Eye Software (www.radicaleye.com)
dvips.exe: DVI file can't be opened: Decomposition.dvi: No such file or directory
Process exited with error(s)

Process started: ps2pdf.exe "Decomposition".ps

MiKTeX GPL Ghostscript 9.25: Unrecoverable error, exit code 1`

regards, 
Mathi

**Comment by sunderme** [comment]
this is a latex question, please use tex.stackexchange.com for that. You need to provide the source code if anyone should be able to help.

**Comment by Mathi50** [comment]
Ok I will do that. Thank you.
