### ISSUE TITLE
TeXstudio does not work with qt5-wayland

### ISSUE THREAD

**Issue by homocomputeris** [texstudio-org/texstudio#244]
### Environment
- TeXstudio 2.12.10 (git n/a)
- Using Qt Version 5.11.1, compiled with Qt 5.11.1 R
- OS: ArchLinux 4.17.5, Gnome 3.28.2
- TeX distribution: TexLive

### Expected behavior
Be usable with `qt5-wayland `

### Actual behavior
Basically, unusable. No window titlebar. Window is not shown in Gnome when Alt-Tabbed. Window is click-through. Windows becomes invisible, but when clicked, some parts appear.

### How to reproduce
Run in Gnome with `qt5-wayland` an `QT_QPA_PLATFORM=wayland` environment variable.

**Comment by sunderme** [comment]
as txs works fine on all supported platforms with qt5 and qt4, it is arch's task to provide an environment which represent txs correctly.
Since arch is infamous for strange, we will not debug this.

**Comment by timhoffm** [comment]
We’re not doing anything special to the window. This sounds more like an issue between Qt and wayland on Arch. I don‘t think there‘s anything we can do in our codebase.
