### ISSUE TITLE
[Bug] Return (Enter) key for removing the current placeholder

### ISSUE THREAD

**Issue by antshar** [texstudio-org/texstudio#2440]
I have been using TeXStudio 2.12.22 for a really long time, I am used to all the features it has. Recently I decided to update my beloved program, but I find it less and less practical than the older version. Some API functionality got removed (I reported that earlier), now this issue that I'm going to describe here

I have the following macro
![image](https://user-images.githubusercontent.com/54121465/176230959-8e3bb2bd-3275-4fdc-be92-ee0a8d182ef1.png)
_although the problem relates to any placeholders_

In 2.12.22 version and other version around that has the following behavior 

https://user-images.githubusercontent.com/54121465/176232269-e0ee2ef0-617b-4e6f-8715-0017056e036e.mp4

But in newer versions (at least on 4.3.0 beta2) Enter (return) key doesn't clear the current placeholder but rather inserts just a new line

https://user-images.githubusercontent.com/54121465/176231819-4c2ca137-ae5c-4295-a684-e55a78acd674.mp4

It was insanely convenient feature. You didn't need additional shortcut for removing placeholders. You only needed to select the placeholder and press Enter (return) to clear it. Can you bring this feature back? At least as an option in the settings?

**Comment by antshar** [comment]
But there might sill be a persistent placeholders. Could you revert this change?

**Comment by sunderme** [comment]
Please give a concrete example where the current logic misses.
Nobody wants to press enter to remove a placeholder. This is rather non-intuitive and I was completely unaware that that logic existed.

**Comment by antshar** [comment]
I agree that normally placeholders should be automatically removed once you type something in there. However, there are persistent placeholders that are also useful in some scenarios and it's rater inconvenient to have additional shortcut for removing the current one rather than press Enter while it's selected. Especially when you are used to it and have been using such behavior for years.

**Comment by antshar** [comment]
I even had to come up with such a workaround based on scripts
![image](https://user-images.githubusercontent.com/54121465/176990684-ca8226c9-5adb-4028-8520-41fc30880308.png)

But it's not how it's supposed to be realized, because it has some flaws:
- Creating new line by pressing Enter now is followed by a tint delay because of macro trigger, but this tiny delay is still noticeable
- Because the macro runs after it detects `\r`, the content of placeholder erases, so I have to press `Ctrl+Z` for undo additionally.

https://user-images.githubusercontent.com/54121465/176990875-3660bb1c-89cb-442f-9b8f-bb63eaa037e8.mp4

- Adding `editor.undo()` doesn't help because it happens so quickly that everything breaks

https://user-images.githubusercontent.com/54121465/176990955-1eb218c4-b082-41e2-bb93-03c3c1d674fc.mp4

**Comment by sunderme** [comment]
ctrl+shift+k removes all placeholders.
Give a concrete example when the current logic fails. General speculations are no base for design decisions.

**Comment by antshar** [comment]
I'm not asking for revering the old behavior when none of placeholders got removed once you type in. Thus there are no complains about the current logic, except one: pressing Enter while the entire placeholder was selected used to be a really useful feature and it doesn't conflict with the current logic, even though many people might not know about this unexpected feature, for me it became a must have and severe time saver.

Here is the concrete example of use case: I often use persistent paceholders because I need to jump back and forth between content of two nearby commands by `Ctrl+→` and `Ctrl+←`. Once I'm done with one of the command, I jump to that placeholder with mentioned shortcuts and press Enter so that it gets removed. And now I can jump between remained placeholders. In my workflow this little thingy with Enter saves tons of time and I don't need to some other shortcuts.

**Comment by sunderme** [comment]
I have not seen an argument why enter is an essential feature (except it used to work for no benefit)
The placeholder logic was changed as it was broken and led to some very weird bugs, so there is no reverting and I am not investing time to reimplement a function for which I see no benefit.

**Comment by antshar** [comment]
Alright then. Could you give some a piece of advice how I can improve the my script so that it wouldn't erase the content?

**Comment by sunderme** [comment]
not sure that it is possible by script. Probably much simpler to use a different shortcut or even better, adapt to the current use model.

**Comment by antshar** [comment]
But what is wrong with `editor.undo()`? When I press undo by myself it works just perfectly.
Maybe I need to add a delay? How can I do that via scripting? I know there is `setTimeout` function in javascript, but it doesn't seem to work in scripts.

**Comment by antshar** [comment]
# Fixed it with scripts!
After lots of trials and errors, in the long run, I came across with this method in the docs
```
editor.cutBuffer
```
![image](https://user-images.githubusercontent.com/54121465/177289044-bf1eb8c0-cb18-49d4-b3c0-843f595b1881.png)

I was so happe that there is such a method that contains previously selected text that has been replaced by a macro's trigger.

Now with the following script I managed to get back the exact previous behavior of Enter key that removes the current placeholder when it's selected and puts new line in all other cases
![image](https://user-images.githubusercontent.com/54121465/177289478-a1f94142-2a8f-475b-90ff-074cad2c2408.png)

https://user-images.githubusercontent.com/54121465/177289957-545658d0-51c2-4347-96c4-a8cc9e49a877.mp4
