### ISSUE TITLE
structure menu: no more option to expand/collapse all (sub)sections of a document

### ISSUE THREAD

**Issue by modulo-n** [texstudio-org/texstudio#2445]
In previous versions there was a convenient way to expand all subitems at once in the document's structure view on the left side. Now I upgraded from Ubuntu 20.04 to Ubuntu 22.04 and the Texstudio version there (installed via apt install texstudio) does not provide this feature anymore. Not sure whether this is a bug or whether it has been removed intentionally.

### Environment
- TeXstudio: TeXstudio 4.2.1 (Build: 4.2.1+ds-1)
- Qt: Qt Version 5.15.3, compiled with Qt 5.15.2 R
- OS: Ubuntu 22.04
- TeX distribution: texlive-full

**Comment by octaeder** [comment]
If I understand right, your wish will be fullfilled in next official release 4.3.0 (no release date known) by pull request #2335. Enhancement is already available in 4.3.0alpha1, beta1 and  current beta2. If you like, you may download one of them (but I think not for Linux) on texstudio's [releases site](https://github.com/texstudio-org/texstudio/releases/).
