### ISSUE TITLE
Broken editor display on secondary display (Windows)

### ISSUE THREAD

**Issue by JuliusMuschaweck** [texstudio-org/texstudio#245]
I use a Dell Precision notebook, Windows 10, German, with a 3840x2160 primary display at 200%, On the primary display, TeXStudio looks ok. I also use a secondary display at 2560x1440. On the secondary display, the editor text font is broken. The font size is way too large and overlapping.
![grafik](https://user-images.githubusercontent.com/25162263/42934066-9016d52c-8b46-11e8-99fe-99d940334843.png)
Except for the line where the cursor is: this line is shown correctly, and when I move the cursor up and down, the line which the cursor just left goes from good to bad, and the line where the cursor enters goes from bad to good:
![grafik](https://user-images.githubusercontent.com/25162263/42934197-df1ce206-8b46-11e8-8717-d9e8981cef99.png) 
![grafik](https://user-images.githubusercontent.com/25162263/42934223-ee452090-8b46-11e8-81ee-5e77757c43fd.png)
Note that "line" means a line with CR/LF at the end, which may be broken across multiple editor lines (I have Soft Line break enabled, but the behavior doesn't depend on this setting).

The issue goes away when I set the primary display resolution to 1920x1080: It apparently has to do with the primary display resolution, even when TeXStudio is on the secondary display only.

Also, the line numbers seem to be off by one: The first actual line has no number, while the second line gets number 1. I don't know whether that's a related or separate bug.
![grafik](https://user-images.githubusercontent.com/25162263/42934573-d4c9d0b0-8b47-11e8-8ca1-c40e0bec000a.png)

### Environment
- TeXstudio:  2.12.10 (git 2.12.10)
- Qt:  Qt version 5.8.0, compiled with Qt 5.8.0 R
- OS:  Windows 10
- TeX distribution:  miktex 2.9

### Expected behavior
font size in editor should be correct

### Actual behavior
font size in editor is  way too large except for the line where the cursor is

### How to reproduce
Use a combination of 4K primary display, 200% magnification, and a secondary display on windows 10

**Comment by sunderme** [comment]
try to change options/advanced option/adv. editor   
disable "try to automtically chose best display option"
select "Disable cache of rendered lines"

**Comment by JuliusMuschaweck** [comment]
Works for me! Thank you sunderme.
