### ISSUE TITLE
Split Horizontally and Split Vertically wording

### ISSUE THREAD

**Issue by RamonAbudAlcala** [texstudio-org/texstudio#2450]
This is a minor suggestion/enhancement.

When a user tries to use the split view for the editor, having two files visible at once. One can decide between "Split Vertically" and Split Horizontally".

I find the use of "Split Horizontally" and "Split Vertically" confusing. I've read this often the case for some users (although I can't remember a specific source right now). I would have to agree that there is a certain ambiguity about what one may mean when saying "split vertically". There is a choice between:
-the objects are on top of each other
-the splitting line is a vertical line
Either are reasonable, but contradictory, thus making the wording confusing for the portion of users that find the second option more intuitive (myself included).

I suggest to use something else that cannot be misinterpreted by the user. Perhaps the root of the problem is the word "split", I can think of the following suggestions.
- Split Horizontally / Split Vertically (current)
- Side by Side View /  Stacked View
- Split Side by Side / Split Top to Bottom
- Split Width / Split Height
- Vertical view / Horizontal view (I'm liking this one the best, does it remove ambiguity? I'm aware of my bias :) )
- ... (more suggestions?)

I'm aware that this would have to be changed in every language. I can only help with the same options for Spanish.
- División Horizontal / División Vertical (current)
- Vista de lado a lado /  Vista Apilada
- División de lado a lado / División de arriba a abajo
- División a lo ancho / División a lo alto (I like how this translates )
- Vista Vertical / Vista Horizontal (This is still the one I like the best).
- ... (más sugerencias?)

**Comment by sunderme** [comment]
I will not change the wording.
As it is adaptive and pressing the point changes from horizontal to vertical and vice versa without any choice, there is no real need to be precise.
