### ISSUE TITLE
Loading of temp files when using Magic comment % !TeX root

### ISSUE THREAD

**Issue by RamonAbudAlcala** [texstudio-org/texstudio#2452]
### Environment
- TeXstudio: 4.2.3
- Qt: 6.3.0
- OS: Windows 10
- TeX distribution: MiKTeX 2.9

### Expected behavior
When working on a file ( rootFile.tex ) with various children files, 1 level deep, adding `% !TeX root = rootFile.tex` to all children and then running `latex` (pdflatex, lualatex, etc...) from any one of the children should run `latex` calling the rootFile.tex instead.

### Actual behavior
Running `latex` from a child (say childFileN.tex ) ends up with error messages on temporary file such as "texstudio_jZBDsV.tex" whose contents are exactly the same as those of childFileN.tex. I believe errors here are unimportant, these are just latex complaining that it can't run without \documentclass or \begin{document} on "texstudio_jZBDsV.tex".

### How to reproduce
Please note that I am working in a shared project that calls the children using a \foreach call from the pgffor package, and unfortunately I can't change this. Furthermore, this is needed to reproduce the problem.
The file structure that matters is 
- .
   - rootFile.tex
   - Children
      - child1.tex
      - child2.tex
      - ...
      - childn.tex

The contents of the rootFile.tex

```
% !TeX root = rootFile.tex

\documentclass{article}
\usepackage{pgffor}

\begin{document}

% Children documents
\foreach \i in {1, 2, 3, ..., 5} {
\input{./Children/child\i}%
}

\end{document}
```
The contents of the children files are unimportant other than having the magic comment in the first line.

```
% !TeX root = rootFile.tex
```

**Comment by RamonAbudAlcala** [comment]
Upon thinking about it and playing 2 more seconds with the code. I realise that pgffor is not needed to reproduce the problem. Here is an updated rootFile.tex

```
% !TeX root = root.tex

\documentclass{article}

% Choose a child to load
% Loading child2.tex for this example
\def\i{2}

\begin{document}

% Child documents
\input{./Children/child\i}%

\end{document}
```

**Comment by sunderme** [comment]
`% !tex root=....` is not used for anything else but compilation. No structure view, no label detection, etc.
why is there a tex root **in** the root file ?

**Comment by sunderme** [comment]
the magic comment only replaces the filename for compilation. When in a child document is in a sub-folder, it needs to point to the correct file from there. The whole idea of this magic comment is that you can open only the child document and still compile the whole document. All other txs functionality concerning parent/child relations is then not used.

**Comment by RamonAbudAlcala** [comment]
> `% !tex root=....` is not used for anything else but compilation. No structure view, no label detection, etc. why is there a tex root **in** the root file ?

Ha! that slipped through. Of course you don't need to point at the root from the root file. :D

Although, your other comment seems rather strange, given the behaviour of the TOC tree in txs after I added `% !TeX root = ../rootFile.tex`. I'm sure you'd be able to reproduce it too. I wouldn't know what would be the underlying reason.

After this other things such as the ones you mentioned also changed, like prediction of user defined commands from other children files.

**Comment by octaeder** [comment]
@sunderme For me TOC (not structure) shows tree starting from root doc, when I open a child document from a subfolder of the folder containing the root document, and no other documents. So I assume that the parser builds the document tree as soon as it knows the root from the magic comment. This is under the conditions that the magic comment uses ../_root doc_ and the root doc include{subfolder/_child doc_}. So it's a little bit more than just compile.

If the magic comment is missing and I add it, TOC is updated immediately to show the whole document tree (not meaning structure). So this works at least for latest dev version.

**Comment by RamonAbudAlcala** [comment]
The reason why I needed the magic comment is because I was calling the `\include` in a programatic way, calling several children using a few lines and a for loop. You can see this from my original MWE `child\i` is not the name of a filename until you run LaTeX and `\i` becomes a number.

In fact my (real) example uses several "latex variables" levels of folders and a (bit) more complicated file structure. But adding the magic comment fixed the problem.

Perhaps a short mention in the usuer manual that "paths" instead of "filenames" are allowed ---or required--- for the root magic comment is pertinent (?)
