### ISSUE TITLE
Allow Ctrl + Tab shortcut on Mac OS

### ISSUE THREAD

**Issue by netw0rkf10w** [texstudio-org/texstudio#246]
Hello,

On Mac OS, the current shortcut for going to the next document is Cmd + Tab, which is already a global shortcut of the OS for switching between apps and thus it does not work in TeXstudio.

I tried changing it to Ctrl + Tab but this is not allowed. This shortcut is used for switching between tabs in different apps such as Safari or Finder, so I think it would be nice (and make sense) if it can be used for switching between "tabs" in TeXstudio as well.

Thanks.

**Comment by crstnbr** [comment]
+1 for this. I was super surprised to see that a simple CTRL+Tab can't be used to switch between tabs/documents like in every other application. As explained by the OP, the default doesn't make any sense on macOS and strangely one can't change it to CTRL+Tab (why?). Please add/fix this.

(I wonder what other shortcuts macOS users chose for switching between documents. I went with ⌃⌘→ and ⌃⌘← out of necessity.)

**Comment by muzimuzhi** [comment]
I am using texstudio 2.12.22 on macOS 10.15.4. 

To manually set a "Ctrl + Tab" shortcut, I find the following steps useful:
 1. double click one shortcut cell, most possible in "Current Shortcut" column
 1. Press "Ctrl + A", then release these two keys. This leaves `^A` in the cell.
 1. Do not touch keyboard. Use mouse to select `A`, then input three characters `tab`.
 1. Click elsewhere, and this successfully leaves `^<Tab>` in the cell.
To set "Shift + Ctrl + Tab", change the key combinations in step 2 to "Shift + Ctrl + A", then follow the steps. 

As a last solution, you can always select the targeted key combination(s) through that long drop-down list.

![image](https://user-images.githubusercontent.com/6376638/80134196-f77bd100-85d0-11ea-9b97-d8950fc20043.png)

**Comment by crstnbr** [comment]
Thanks for this hint @muzimuzhi. I realised myself that I could select `Ctrl + Tab` from the dropdown menu. However, even if I do so (I have exactly what you have in your screenshot) the keyboard shortcut still doesn't work. Nothing happens when I press `Ctrl + Tab`. I'm surprised to hear that it works for you. I'm also on Catalina 10.15.4 and use precisely the same TeXstudio version. Any ideas what the difference/issue could be?

**Comment by muzimuzhi** [comment]
Guess there exist some shortcut conflicts among texstudio and other macOS app, or the macOS itself.

If you leave texstudio.app opened only, does the `Ctrl + Tab` still not work?

**Comment by crstnbr** [comment]
Alright, I figured it out. CTRL+TAB works for me when I set it as "Current shortcut". Strangely, it does not work when set as "Additional Shortcut", which is what I had before. Other shortcuts work just fine, independent of whether they are additional or not. Very strange.

In any case, thanks for the suggestions @muzimuzhi.

**Comment by crstnbr** [comment]
I would still suggest to make ctrl+tab and ctrl+shift+tab the default shortcuts for switching documents on macOs.

**Comment by mloning** [comment]
Adding support for switching to tabs directly using command + <number> as you can do in Safari and other browsers would be even nicer!

**Comment by sunderme** [comment]
it is really not a good idea to add feature requests in closed bug reports.
If you want to make it visible, open a new issue.

**Comment by mloning** [comment]
Here we go #1314

**Comment by netw0rkf10w** [comment]
To make it more convenient for users, it would be great to follow modern editors' standard and add a shortcut (`Ctrl+TAB`) for switching to the **Previous Document in History**, i.e. the most recently viewed document prior to the current document.
