### ISSUE TITLE
git auto check-in is not working when auto-recompile is on

### ISSUE THREAD

**Issue by zhangjunhua** [texstudio-org/texstudio#2460]
### Environment
- TeXstudio: 4.2.3
- Qt:  6.30 
- OS: Windows 11
- TeX distribution:  texlive

### Expected behaviour
I've set the auto git check-in and the auto re-compile document on file change. Each time I change and save the tex files, it should commit the changes to the git repository as well as re-compile the document.

### Actual behaviour
It only re-compiles the document on changes and doesn't check in the changes to git.

If I tick off the auto-recompile, the auto-check-in works as expected.

**Comment by sunderme** [comment]
hmmmmm, checking in every tiny change with any context is excessive. I am not sure if that is really a good idea.

**Comment by sunderme** [comment]
no feedback
