### ISSUE TITLE
Automatically open internal pdf viewer on startup

### ISSUE THREAD

**Issue by antodc** [texstudio-org/texstudio#2461]
Is there any way to have both the tex and pdf files opened at the same time when opening a tex file? I mean, without using F7 or "Restore Previous Session at Startup". Clearly, only when a pdf version of the tex file is available. Thanks a lot for any hint!

**Comment by sunderme** [comment]
no

**Comment by antshar** [comment]
There is actually a workaround with scripts!
![image](https://user-images.githubusercontent.com/54121465/182110265-4f9ccb90-f3a8-4efd-a7d1-9eb1a18b903c.png)
```
%SCRIPT
app.getManagedAction("main/tools/view").trigger();
```
with a trigger
```
?load-file
```

**Comment by antodc** [comment]
Amazing!!! That is what I was looking for! Thanks  lot!
