### ISSUE TITLE
Add "open .sty file" to right click menu on commands and packages

### ISSUE THREAD

**Issue by RamonAbudAlcala** [texstudio-org/texstudio#2467]
I find really helpful to have the documentation open by going to a command and using ctrl+click or right click + "open package documentation" (are there any other shortcuts?). But sometimes I'd like to see the package .sty file instead. It would be great to have a shortcut to it just below "open documentation".

The current alternative (correct me if I am wrong) is to navigate the local LaTeX distribution and find the particular package in question, which sometimes I do, but most times it feels like too much effort.

### Who will benefit with this feature?
All users would benefit, sometimes it is just helpful to know how the package actually loads, even if the user can only read basic TeX. Advanced users could quickly check for inconsistencies or tweaks, etc...

**Comment by samcarter** [comment]
> The current alternative (correct me if I am wrong) is to navigate the local LaTeX distribution and find the particular package in question, which sometimes I do, but most times it feels like too much effort.

Instead of looking in your distribution for the package you could also open it directly, if you get the path from

1. kpsewhich, e.g. run in a terminal `kpsewhich indentfirst.sty` 
2. open your .log file and search for the package

---

On mac I'm using the following texstudio user macro to directly open .sty files:

```
%SCRIPT
var selection=cursor.selectedText();
system('zsh -c "open `kpsewhich ' + selection + '.sty`"')
```

**Comment by sunderme** [comment]
as there is a macro solution, I close this.

**Comment by RamonAbudAlcala** [comment]
@samcarter Thanks! I have not had the time to play with this until now. I have one windows computer and after a bit of searching online I managed to get the following user macro / script.

```
%SCRIPT
var selection=cursor.selectedText();
system('powershell "start (kpsewhich ' + selection + '.sty)"')
```

I couldn't figure out how to make it work with `cmd`. Also, I don't know if I'm missing the equivalent flag for `-c` that you have. For now it works as is. I'll leave it here for other people to find.

**Comment by yashpalgoyal1304** [comment]
hi!

* from the initial description and the solution shared, the concern in this issue seems to be primarily with the *default packages* included in the tex distribution's installation directory

whereas i find this capability to be very important for the self made packages which reside in the project directory itself.

i usually have two of my own style files in every project i am working with (one is the experimenting one, and one is the main one).

**Comment by yashpalgoyal1304** [comment]
* ctrl+click to open custom style files 
* by [texlab LSP] for LaTeX
* in vscodium

[texlab LSP]: https://github.com/latex-lsp/texlab "An implementation of the Language Server Protocol for LaTeX"

https://user-images.githubusercontent.com/19423063/206869524-378a7561-2381-4e74-ab67-7022f577b545.mp4

**Comment by yashpalgoyal1304** [comment]
hi @sunderme , can you please reopen this?

**Comment by yashpalgoyal1304** [comment]
> as there is a macro solution, I close this.
> /- @ sunderme at https://github.com/texstudio-org/texstudio/issues/2467#issuecomment-1186269688


> if you get the path from ... `kpsewhich` ...
> /- @samcarter at https://github.com/texstudio-org/texstudio/issues/2467#issuecomment-1185838859

kpswchich works only for the distribution wide packages, it doesn't work on custom packages, so, there is NO solution for those.

**Comment by samcarter** [comment]
> `kpswchich` works only for the distribution wide packages, it doesn't work on custom packages, so, there is NO solution for those.

If you place your custom packages somewhere where texlive can find them, e.g. in your TEXMFHOME tree, you can get their path with kpsewhich

**Comment by yashpalgoyal1304** [comment]
> If you place your custom packages somewhere where texlive can find them, e.g. in your TEXMFHOME tree, you can get their path with kpsewhich

my custom packages are project specific, tuned to and inherent part of the individual project
