### ISSUE TITLE
Improve support for "subfiles" package.

### ISSUE THREAD

**Issue by kbauer** [texstudio-org/texstudio#247]
The subfiles package is useful for speeding up previews when working on large documents, without overwriting the main file with incomplete `\includeonly` settings. Currently, compilation of the subfile can be enabled by setting the root document either through *Options > Root Document* or by using the `% !TeX root = sub` magic comment. Either way, by changing the root document, completion information is lost.

![image](https://user-images.githubusercontent.com/7498468/43034015-59b34558-8cd4-11e8-8c12-2c5ca04c0c55.png)

### How to reproduce

- Download the example files [example.zip](https://github.com/texstudio-org/texstudio/files/2216036/example.zip)
- Type `\ref` in `sub.tex`.

### Expected behavior
- Completion for `\ref{sec:A}` should be suggested.

### Actual behavior
- No completion is suggested.

### Partial Workaround

- Set up pdflatex to compile the current document instead, by specifying `?c:m"` instead of `%` or `?m"` as the file name. Sadly, this breaks the "View" command, as `?c:m"` expands to the *root* document in the context of the viewer command (see #248).

### Environment
- TeXstudio: 2.12.10
- Qt: Using Qt Version 5.8.0, compiled with Qt 5.8.0 R
- OS: Windows 10 (Microsoft Windows [Version 10.0.17134.165])
- TeX distribution: MikTeX

**Comment by ComFreek** [comment]
I think the lack of support also breaks completion for bibliography and `\cite` as `\addbibresource` is not found.

**Comment by muzimuzhi** [comment]
@kbauer 
With the right position and content of magic comment `% !TeX root = <root filename>`, your example now works on texstudio 2.12.16 on macOS.

* right position: magic comment should be at the beginning of file, not after `\documentclass`
* right content: `! TeX root = ` accepts name of root filename, e.g. `main.tex` in your example, not the current filename.

Modified `sub.tex`:
```latex
% !TeX root = main.tex
\documentclass[main]{subfiles}

\begin{document}
\section{B}
\lipsum[2]

\end{document}
```

Screenshot of auto-completion:
![image](https://user-images.githubusercontent.com/6376638/58540806-b1858400-822c-11e9-8a4c-105fb578f8eb.png)

**Comment by muzimuzhi** [comment]
@ComFreek 
`\addbibresource` is defined in package `biblatex`, and is currently included in completion file `biblatex.cwl`.
https://github.com/texstudio-org/texstudio/blob/42252b2fb222b21abd6858dfb36fe0e2733f7d47/completion/biblatex.cwl#L10-L11

The original issue has nothing to do with `biblatex`. So if you come up with a similar problem, you can open a new issue and refer to the current one.

**Comment by mbertucci47** [comment]
I think this issue is fixed regardless of specification of `% !TeX root = ...` so can be closed. Screenshot below:
<img width="572" alt="subfiles_ex" src="https://user-images.githubusercontent.com/61854785/167931091-e117e3fb-afba-4206-8171-6f7c4ef15c18.png">
