### ISSUE TITLE
Change order of completion suggestions

### ISSUE THREAD

**Issue by samcarter** [texstudio-org/texstudio#2476]
### Environment
- TeXstudio: 4.3.0beta
- Qt: 6.3.1
- OS: macOS 11.6
- TeX distribution: TL2022

### Question

Is there any way to influence the order in which commands are shown in the completion window?

Use case: I would like to show `\makeatletter` before `\makeatother` (because that's the order in which I normally use them)

I already tried to switch their order in the `.cwl` file, but irregardless they are always listed like this in the completion window:

![Screenshot 2022-07-15 at 14 48 07](https://user-images.githubusercontent.com/43832342/179226042-6cec4e99-bdf2-4b21-ab9a-d630466800b6.png)

Is there any option, short of using `\makeatother#S` in the cwl file, to get `\makeatletter` first? 

My `.cwl` file looks like this

```
\makeatletter#*
\makeatother#*
\makeatletter%<%>\makeatother#*
```

**Comment by sunderme** [comment]
or you use regularly `\makeatletter%<%>\makeatother` and that one is directly offered

**Comment by samcarter** [comment]
I think I found the commit https://github.com/texstudio-org/texstudio/commit/4563c5ab200a934abfb05d5c7493d1443ff6718a 

Thanks for mentioning the right keywords to find this!

**Comment by sunderme** [comment]
so, can we close this ?

**Comment by samcarter** [comment]
Yes, compilation without https://github.com/texstudio-org/texstudio/commit/4563c5ab200a934abfb05d5c7493d1443ff6718a yielded exactly what I need. Thanks again!
