### ISSUE TITLE
CD: homebrew formula `poppler` doesn't depend on `qt6` anymore

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#2483]
Recently on macOS, the homebrew formula `poppler` doesn't depend on `qt6` anymore. It seems texstudio needs its own `poppler-qt6` formula. This makes texstudio's CD workflow job running on macOS fails, as found/reported by @fjpereny in https://github.com/texstudio-org/texstudio/pull/2474#issuecomment-1189060597. See
 - Should poppler include QT by default? https://github.com/orgs/Homebrew/discussions/3428
 - https://github.com/Homebrew/homebrew-core/pull/105964

> If we eventually pick up more formulae that actually need Poppler with Qt 6 support, we'll have to re-evaluate adding it as a formula. The only two packages Arch Linux has that currently depend on their `poppler-qt6` package are `texstudio` and `gimagereader-qt`, neither of which currently have formulae. There are quite a few others that use their `poppler-qt5` package, but we don't have formulae for any of those either.
> 
> _quoted from https://github.com/orgs/Homebrew/discussions/3428#discussioncomment-3162959_

I'll try with a `poppler-qt6` formula in my homebrew tap.

**Comment by muzimuzhi** [comment]
Tested with a `poppler-qt6.rb` [1] and a modified `cd.yml` [2], but the `make install` fails with `Error 2` [3].

[1] https://github.com/muzimuzhi/homebrew-texstudio-beta/blob/master/Formula/poppler-qt6.rb
[2] https://github.com/texstudio-org/texstudio/compare/master...muzimuzhi:texstudio:poppler-qt6
[3] https://github.com/muzimuzhi/texstudio/runs/7412806452?check_suite_focus=true

PS: Currently homebrew provides formulae [`poppler`](https://github.com/Homebrew/homebrew-core/blame/master/Formula/poppler.rb) and [`poppler-qt5`](https://github.com/Homebrew/homebrew-core/blame/master/Formula/poppler-qt5.rb).

**Comment by muzimuzhi** [comment]
Noticed from `brew info glib`
```
==> Caveats
Python executables and libraries are no longer included with this formula, but they are available separately:
  brew install glib-utils
```
Hence I added dependency `glib-utils` to `poppler-qt6` and then the local execution of `brew install --build-bottle muzimuzhi/texstudio-beta/poppler-qt6` succeeds.

Waiting for result from re-run job: https://github.com/muzimuzhi/texstudio/runs/7413847387?check_suite_focus=true .

**Comment by muzimuzhi** [comment]
After adding dependency `glib-utils`, the CD run on macos-11 (finally) succeeds. See https://github.com/muzimuzhi/texstudio/actions/runs/2699835837.
  - It's macos-11, not the current macos-10.15 because https://github.com/actions/virtual-environments/issues/5583.
  - With the help of workflow files created by `brew tap-new USER/REPO`, now the bottles (binary packages) for `poppler-qt6` on macos-11 are provided automatically, hence the time for `brew install <tap>/<repo>/poppler-qt6` is reduced.
  - But the time for step "Build" almost doubles ([~12min](https://github.com/texstudio-org/texstudio/runs/7370679282?check_suite_focus=true) -> ~24min). Not sure if it's related to the change from macos-10.15 to macos-11.

Other info is written in https://github.com/orgs/Homebrew/discussions/3428#discussioncomment-3183607.

**Comment by muzimuzhi** [comment]
On github, currently in my homebrew tap [muzimuzhi/homebrew-texstudio-beta](https://github.com/muzimuzhi/homebrew-texstudio-beta).
 - The exact formula file is https://github.com/muzimuzhi/homebrew-texstudio-beta/blob/master/Formula/poppler-qt6.rb .
 - It now provides binary `poppler-qt6` for `big_sur` and `x86_64_linux` as release files, but can be changed to github package files.
 - This `poppler-qt` formula can be installed in texstudio's workflow (or any homebrew user) by `brew install muzimuzhi/texstudio-beta/poppler-qt6`, as can be seen in https://github.com/texstudio-org/texstudio/compare/master...muzimuzhi:texstudio:poppler-qt6

**Comment by sunderme** [comment]
my idea would be to make a texstudio-dependencies repository and source the tap from there.
For that it should be build with an osx runner on github. I don't see that an action in that repository is doing it ?

**Comment by muzimuzhi** [comment]
It's done by a special work flow provided by homebrew, see [Homebrew tap with bottles uploaded to GitHub Releases](https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/).
 - `brew tap-new USER/REPO` creates two workflow files `tests.yml` and `publish.yml`.
 - When a PR is opened, `tests.yml` is triggered, which will run tests on `macos-latest` and `ubuntu-latest`, build bottles, and upload them to artifacts.
 - Then I manually add label `pr-pull`, which will triggle `publish.yml`, which will download artifacts, publish them as a new release (or package), and insert or update the bottle block in corresponding formula file, here `poppler-qt6.rb`.

**Comment by sunderme** [comment]
do you happen to know how to build binary locally which in turn can be installed with brew ?
I would rather get away from homebrew and build an adapted poppler. (no glib, no static libs and adapted rpath)

**Comment by muzimuzhi** [comment]
Sorry I don't know. If I remembered correctly, once there was such steps in texstudio's CD script, maybe in Travis CI time.

**Comment by sunderme** [comment]
I'll figure it out

**Comment by muzimuzhi** [comment]
76e85cfa61bda73dac59c64f2c18d2044c3b3c9c
```
        brew install qt5
        brew install --only-dependencies poppler
        wget https://poppler.freedesktop.org/poppler-21.03.0.tar.xz
        tar xvf poppler-21.03.0.tar.xz
        cd poppler-21.03.0
        mkdir build
        cd build
        cmake ..
        make -j 2
        make install
```

**Comment by sunderme** [comment]
can figure out on OSX, how to make a "bottle"
should be 
```brew install --build-bottle formula/poppler-qt6.rb
brew bottle formula/poppler-qt6.rb```
but that seems not to work ,see https://github.com/sunderme/poppler-build/actions

**Comment by muzimuzhi** [comment]
```
Error: Formula not from core or any installed taps: poppler-qt6
```

This error is solved by adding `brew bottle` option [`--force-core-tap`](https://docs.brew.sh/Manpage#bottle-options-installed_formulafile-) (its name is misleading, but the [source code](https://github.com/Homebrew/brew/blob/9c08c5b8bac6a9795a8856007f942e32f5007e69/Library/Homebrew/dev-cmd/bottle.rb#L296-L301) suggests it's the option we need), but then the new errors thrown by `brew bottle` is something I didn't succeed to resolve.
```
==>Determining poppler-qt6 bottle rebuild...
Error: undefined method `path' for nil:NilClass
Did you mean?  paths
/usr/local/Homebrew/Library/Homebrew/formula_versions.rb:25:in `initialize'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:322:in `new'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:322:in `bottle_formula'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:104:in `block in bottle'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:103:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:103:in `bottle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

Instead, I tried converting the whole repo to a real hombrew tap which meets the required naming and directory structure conventions.
 - https://docs.brew.sh/Taps#repository-naming-conventions-and-assumptions
 - https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

And now `brew bottle` succeeds, see https://github.com/muzimuzhi/homebrew-poppler-build/runs/7441332482

**Comment by muzimuzhi** [comment]
> And now `brew bottle` succeeds, see https://github.com/muzimuzhi/homebrew-poppler-build/runs/7441332482

Well, rerun failed today. Having no idea what's changed during the last 24h.

Setting `real-tap` branch (in my fork) which converted the repo to a real homebrew tap, as the default branch seems to work, see https://github.com/muzimuzhi/homebrew-poppler-build/actions/runs/2715379723.

And, I learnt from log of [step `brew test-bot --only-formulae`](https://github.com/muzimuzhi/homebrew-texstudio-beta/runs/7458034126?check_suite_focus=true#step:8:37) that homebrew can install a bottle file directly, for example `brew install ./poppler-qt6--22.06.0.big_sur.bottle.1.tar.gz`.
- brew doc: https://docs.brew.sh/Manpage#specifying-formulae

**Comment by sunderme** [comment]
so, I have actiavted OSX build again.
Can you check that the OSX build actually works ?
https://github.com/texstudio-org/texstudio/actions/runs/2727168748

**Comment by muzimuzhi** [comment]
> so, I have actiavted OSX build again.
> Can you check that the OSX build actually works ?
> https://github.com/texstudio-org/texstudio/actions/runs/2727168748

Yes it works. Many thanks.

**Comment by cilia** [comment]
Encountered the same issue on `macOS 10.15.7`, tried compiling `TeXstudio 4.3.0` but got `"Project ERROR: poppler-qt6 development package not found"`. The 4.3.0 built app downloaded from the official website does not launch, hence the attempt to compile it locally. Is there any way to use the 4.x version on `macOS 10.15.x`?

**Comment by muzimuzhi** [comment]
@cilia You can try the artifact `texstudio-osx` in https://github.com/muzimuzhi/texstudio/actions/runs/2822437091, which is built on macOS 10.15, with poppler-qt6. See also #2517.
