### ISSUE TITLE
Cwl files are classified as a wrong language

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#2489]
**Problem**

Currently cwl files are wrongly detected as Common Workflow Language. This is controlled by GitHub's Linguist library: https://github.com/github/linguist.
![image](https://user-images.githubusercontent.com/6376638/180578735-58206085-7810-4d77-9881-174a64071bde.png)

The real Common Workflow Language

> (CWL) documents are written in [JSON](http://json.org/) or [YAML](http://yaml.org/), or a mix of the two.
> _from https://www.commonwl.org/user_guide/02-1st-example/index.html_

**Possible solutions**

Ideally, contribute a syntax-highlighting grammar for (la)tex completion language and then add that new language to Linguist. 
 - See https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language.
 - Question: Does (la)tex completion language meet the usage criteria set by linguist?
    > In most cases we prefer that each new file extension be in use in at least 200 unique `:user/:repo` repositories before supporting them in Linguist.

As a compromise, texstudio could use a `.gitattributes` file to reclassify `.cwl` files.
 - See https://github.com/github/linguist/blob/master/docs/overrides.md.
 - See https://github.com/github/linguist/blob/master/lib/linguist/languages.yml for a full list of languages known to Linguist.
 - Which language? [`TeX` language][tex-lang] doesn't support `%` used in `\cmd{arg-desp%arg-type}`, special role of `#`, and keyvals list. [`Text` language][text-lang] is the perhaps most conservative option.

[tex-lang]: https://github.com/github/linguist/blob/249bbd1c2ffc631ca2ec628da26be5800eec3d48/lib/linguist/languages.yml#L6476-L6501
[text-lang]: https://github.com/github/linguist/blob/249bbd1c2ffc631ca2ec628da26be5800eec3d48/lib/linguist/languages.yml#L6533-L6573

An example `.gitattributes` file that reclassifies `.cwl` files to plain text but makes them included in the language statistics:
```gitattributes
*.cwl linguist-language=Text linguist-detectable
```

**Comment by sunderme** [comment]
fixed

**Comment by muzimuzhi** [comment]
aha the language stats is already refreshed
![image](https://user-images.githubusercontent.com/6376638/180655305-5fde178b-32a8-421b-99ed-9dd6db1a8340.png)
