### ISSUE TITLE
siunitx: too radical removal of key/val pairs

### ISSUE THREAD

**Issue by sunderme** [texstudio-org/texstudio#2491]
siunitx.cwl does not contain math-sf= as key any more
### Environment
- TeXstudio: git 4.3.0beta2-48-g9639e4956

### Expected behavior
Not all users do use the latest packages, especially on linux, older packages are quite common.
Hence not all changes should be directly flagged as errors when they probably are still valid.

@mbertucci47

**Comment by mbertucci47** [comment]
I see, I will add back the keyvals.
