### ISSUE TITLE
GitHub actions will remove macos-10.15 environment by 8/30/22

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#2494]
I saw a warning in each of recent workflow runs
![image](https://user-images.githubusercontent.com/6376638/180654299-d8407966-0dc7-47fb-b4f5-e6eec1b3f462.png)

The title of referenced issue explains everything:
 - https://github.com/actions/virtual-environments/issues/5583

Well, the motivation is missing:

> ### The motivation for the changes
> GitHub Actions maintains the latest two stable versions of any given OS version.

I was about to provide a PR to do `s/macos-10.15/macos-11/g` on all the workflow files (actually only `cd.yml` is affected), but just realized that this change would influence texstudio's minimum supported version of macOS.

Therefore perhaps a more gentle way is to release a special, last version that supports macOS 10.15 just before 8/30/22, and then upgrade both the runner environment and corresponding description in manual and website to `macos-11`.

**Comment by sunderme** [comment]
I agrre

**Comment by sunderme** [comment]
switched to osx11 as github employs "brown outs" which means they break the cd on OSX for some days.
