### ISSUE TITLE
Q: Linux Version List korrekt?

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2495]
I look at the list here [https://www.texstudio.org/#linuxdownloads](https://www.texstudio.org/#linuxdownloads) and compare the link text with the link:

![grafik](https://user-images.githubusercontent.com/102688820/180657028-e7bba50b-08d6-4229-ab36-84d260b3a354.png)
![grafik](https://user-images.githubusercontent.com/102688820/180657035-2a0ca9bf-0567-4509-83ab-e95974e96cf6.png)

Typically the given version is the same in the file name, so I suspect a mistake.

**Comment by sunderme** [comment]
fixed
