### ISSUE TITLE
[Question] Measure compilation time

### ISSUE THREAD

**Issue by antshar** [texstudio-org/texstudio#2499]
I want to measure the precise compilation time of any command, say if I have the following query:
```
pdflatex -draftmode %.tex | pdflatex -synctex=1 %.tex | txs:///view
```
the timer should stop after the end of the whole command taking into account several `pdflatex` calls.

I tried to find such an option, but couldn't, so I decided to create a workaround myself. I could, for example, use `Measure-Command` function from powershell, this doesn't work
```
powershell Measure-Command {txs://build}
```

After some more researches, I found `?after-command-run` trigger and it's almost exactly what could help me. With this trigger the script runs after the complete command execution. However, it's not enough to measure the time, because I need to start a timer somehow.

How can I `alert` the compilation time? Any suggestions are welcome.

**Comment by sunderme** [comment]
you can create a batch file which actually calls pdflatex (or whatever) and times it.
First argument is the filename.

**Comment by antshar** [comment]
It's important for me to use texstudio command `txs:///compile` because it will allow me to simply change the engine without modifying the script itself.

Is there any way to expand txs commands before passing it to my script?
