### ISSUE TITLE
^ in mhchem commands should not be highlighted as syntax error \ce{^3He}

### ISSUE THREAD

**Issue by jonasstein** [texstudio-org/texstudio#25]
^ in mhchem commands should not be highlighted as syntax error.
It is very common to type isotopes like `\ce{^3He}`
Texstudio highlights this as syntax error, which is distracting.

![selection_464](https://user-images.githubusercontent.com/298682/35781126-266e673e-09e6-11e8-9a3d-77bfe7a2c870.png)

```
Version
TeXstudio 2.12.8 (hg n/a)
Using Qt Version 5.9.4, compiled with Qt 5.9.4 R
```

**Comment by timhoffm** [comment]
See also https://sourceforge.net/p/texstudio/feature-requests/1286/.

I'm working on migrating the sf issues.

**Comment by sunderme** [comment]
no interpretation/syntax check on \ce arguments, implemented in repository

**Comment by timhoffm** [comment]
@sunderme is this case general enough to add a "formula" tag? Unless we intend to add special highlighting for this, I'd rather go with a `%plain` qualifier, i.e. `\ch{formula%plain}`. This will be useful in other situations as well.

**Comment by sunderme** [comment]
tokenizer has been extended to use "formula" argument as well.
This may be the base for future extensions
