### ISSUE TITLE
Broken TexStudio download links for debian 9

### ISSUE THREAD

**Issue by AgostinoSturaro** [texstudio-org/texstudio#250]
On this page
https://www.texstudio.org/

These two links are broken
http://download.opensuse.org/repositories/home:/jsundermeyer/Debian_9.0/amd64/texstudio_2.12.10-1+3.1_amd64.deb
http://download.opensuse.org/repositories/home:/jsundermeyer/Debian_9.0/i386/texstudio_2.12.10-1+3.1_i386.deb

They should probably point to
http://download.opensuse.org/repositories/home:/jsundermeyer/Debian_9.0/amd64/texstudio_2.12.10-1+3.2_amd64.deb
http://download.opensuse.org/repositories/home:/jsundermeyer/Debian_9.0/i386/texstudio_2.12.10-1+3.2_i386.deb

**Comment by sunderme** [comment]
fixed
