### ISSUE TITLE
[Feature Request] Compilation Time display on GUI panel

### ISSUE THREAD

**Issue by antshar** [texstudio-org/texstudio#2502]
It's a follow up ticket for https://github.com/texstudio-org/texstudio/issues/2499

I spent a couple of hours trying to construct a dirty hack and quirks abusing some TXS api and windows prompt+powershell, but couldn't done it.

Since TeXStudio already has `?after-command-run` trigger for scripts that activates as soon as the _stop compilation_ button gets disabled I think it won't be hard at all to set up a QT [timer](https://doc.qt.io/qt-6/qtimer.html) to measure the compilation time and show it up on the bottom panel. It has lots of free space down there and won't disturb anyone

![image](https://user-images.githubusercontent.com/54121465/181498231-3b4d647a-f87f-418c-89a4-29047dd65745.png)

**Comment by sunderme** [comment]
if someone wants to work on it, the result needs to be shown in the message pane along with all other information.

**Comment by antshar** [comment]
You are right, probably it's even better to have it in Messages tab along with other messages after a compilation.

Actually, this feature doesn't seem complex at all. It's so useful for me that I would invest time on creating it, however it might take me lots of hour in order to figure out only the relation between different source files and decide where it should be coded.

Don't you find this debug info useful? I think for a person who coded everything it would be much easier and faster to implement such a subtle feature, because you know where it should be written.

**Comment by antshar** [comment]
I investigated the code a bit and found the place where timer can be added
https://github.com/texstudio-org/texstudio/blob/88b471b2e74ef3cd2c7cb15af975e07670dfece4/src/buildmanager.cpp#L2497-L2532

Inside `void ProcessX::onStarted()` make a timer start and inside `void ProcessX::onFinished(int error)` make it stop in addition to printing the elapsed time.

First of all, I tried to simply build TXS from the source code to see if it works, but I faced some issues during a compilation. But even if I managed to build, I might have other troubles with making the timer work correctly. @sunderme could you help me with that?

**Comment by sunderme** [comment]
I am not interested in that functionality and it is not of general use.
I will review a PR but I will not involve myself in figuring out program code.

**Comment by antshar** [comment]
Wait, what is this piece for?
https://github.com/texstudio-org/texstudio/blob/88b471b2e74ef3cd2c7cb15af975e07670dfece4/src/buildmanager.cpp#L2535-L2538

Looks like some kind of time time measurement

**Comment by antshar** [comment]
@sunderme seems like it's the exact feature I'm really in need of.

Just look, inside `startCommand()` the timer starts 
https://github.com/texstudio-org/texstudio/blob/88b471b2e74ef3cd2c7cb15af975e07670dfece4/src/buildmanager.cpp#L2386-L2389

And when the command has been finished it stops the timer and prints the time
https://github.com/texstudio-org/texstudio/blob/88b471b2e74ef3cd2c7cb15af975e07670dfece4/src/buildmanager.cpp#L2534-L2539

Now the only question is how to get into debug mode and make `#ifdef PROFILE_PROCESSES` make those lines of code run?

**Comment by sunderme** [comment]
just look for `#define PROFILE_PROCESSES`, uncomment that and compile your own version of txs.

**Comment by sunderme** [comment]
no.
The solution for your problem is using powershell measure command.
Set as pdflatex command: `powershell "Measure-Command { pdflatex.exe -synctex=1 -interaction=nonstopmode %.tex }" > txs:///messages`

**Comment by foreachthing** [comment]
@sunderme, maybe you know this right out of your head:
I tried to clean up the output from the command you provided. I got it working in PS but for some reason txs failes at "select":
`powershell -command 'Measure-Command {pdflatex.exe -synctex=1 -interaction=nonstopmode %.tex} | select @{n="""Build Time""";e={[int]$_.TotalMinutes,"""min""",$_.Seconds,"""sec""",$_.Milliseconds,"""ms""" -join """ """}}' > txs:///messages`

Try it from PS (with `dir` as command):
`powershell -command 'Measure-Command {dir} | select @{n="""Build Time""";e={[int]$_.TotalMinutes,"""min""",$_.Seconds,"""sec""",$_.Milliseconds,"""ms""" -join """ """}}'`

Message from txs:
```
Process started: powershell -command 'Measure-Command {pdflatex.exe -synctex=1 -interaction=nonstopmode "main".tex}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 3
Milliseconds      : 789
Ticks             : 37899835
TotalDays         : 4.38655497685185E-05
TotalHours        : 0.00105277319444444
TotalMinutes      : 0.0631663916666667
TotalSeconds      : 3.7899835
TotalMilliseconds : 3789.9835
Process exited normally



Error: Could not start the command: select 321{n="""Build Time""";e={[int]$_.TotalMinutes,"""min""",$_.Seconds,"""sec""",$_.Milliseconds,"""ms""" -join """ """}}'

```

Thanks!

**Comment by antshar** [comment]
@foreachthing yeah I had the same problem. This happens because of quotes treatment, especially `"main".tex` breaks everything, it should be `"main.tex"`, so instead of `&` you need to use another special selector, see **4.4 External Commands** section in the manual.

Btw, as far as I can see, you're trying to print the time in a nice `mm:ss:ms` way, I wanted that too and ended up with a much smaller code.
```
powershell $etime = Measure-Command { pdflatex.exe -synctex=1 -interaction=nonstopmode --shell-escape '?me"' }; Write-Host "Time: "$etime -NoNewline > txs:///messages
```
![image](https://user-images.githubusercontent.com/54121465/184883896-d40ddbc9-ffd1-4708-b7a8-05613fc286ad.png)

**Comment by foreachthing** [comment]
@antshar cool!!

Something's off with your script, I think. I got this lengthy doc and it rebuild in 00:00:8.58 ms? If I time it with my messy code, I get 8.67 seconds...

Well, I don't think _everybody_ needs this. So, if some want's it, it's right here for them to find 😏 
And, if you change the meta command "build & view" to `txs:///user1 | txs:///view` you'll get the results even when presssing F5, instead of ALT+SHIFT+1 (or whatever index your user command has).

**Comment by octaeder** [comment]
I can't do it, maybe because the path to lualatex contains a blank. But Lua needs the path ohterwise it is not found. I mean this part:

`Measure-Command { C:\Users\daCake\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\lualatex.exe -synctex=1 -interaction=nonstopmode --shell-escape '?me"' };`

Can someone tell me what I have to change? Thx

**Comment by octaeder** [comment]
I can't do it, maybe because the path to lualatex contains a blank. But Lua needs the path ohterwise it is not found. I mean this part:

Measure-Command { C:\Users\WDAGUtilityAccount\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\lualatex.exe -synctex=1 -interaction=nonstopmode --shell-escape '?me"' };

Can someone tell me what I have to change? I tried several ways of using quotes and so on. Thx

**Comment by antshar** [comment]
@octaeder Try to quote the path, so that you end up with
```
Measure-Command { "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\lualatex.exe" -synctex=1 -interaction=nonstopmode --shell-escape '?me"' };
```
If that didn't help, I would suggest you adding `lualatex.exe` into your PATH, so that you can access it as `pdflatex.exe` i.e without writing the whole path, but just the program name. Here's a quick [video-guide](https://www.youtube.com/watch?v=mxVfa6q-03M).

**Comment by octaeder** [comment]
Thanks, that's the way the commands look like in txs. I tried this. But I got:

```
Process started: powershell $etime = Measure-Command { "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\lualatex.exe" -synctex=1 -interaction=nonstopmode --shell-escape '"document.tex"' }; Write-Host "Time: "$etime -NoNewline

C:\Users\WDAGUtilityAccount\AppData\Local\Programs\MiKTeX : Die Benennung "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\MiKTeX" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausfhrbaren Programms erkannt.
```
So I tried combinations of singe-quotes and double-quotes, reversed order of them and set them at different places. But I couldn't manage it. Once that the path was not broken at the blank the message complained about -synctex. Maybe I'll come back to changing path variable.

**Comment by octaeder** [comment]
With the help of a description at [stackoverflow.com](https://stackoverflow.com/questions/57441095/running-a-powershell-command-using-full-path-and-arguments-from-command-line) I changed my command to:

```
Measure-Command { "& 'C:\Users\WDAGUtilityAccount\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\lualatex.exe' -synctex=1 -interaction=nonstopmode --shell-escape ?me"" };
```
This runs lualatex and writes following messages:

```
Process started: powershell $etime = Measure-Command { "& 'C:\Users\WDAGUtilityAccount\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\lualatex.exe' -synctex=1 -interaction=nonstopmode --shell-escape "document.tex"" }; Write-Host "Time: "$etime -NoNewline

The "gnuplot" command is either misspelled or could not be found.
Time: 00:02:43.7442258
Process exited normally
```
I'm surprised that the two double-quotes after document.tex (s. output) make no problems.
gnuplot is not found, even so path variable contains the directory path known to cmd.exe. Maybe I should call powershell from cmd.exe.

**Comment by foreachthing** [comment]
I had to reinvent the wheel on this topic. I wanted it to work on LuaLaTeX and all other engines as well. So, I changed it to this:

Create a Python file with this code:

```
import subprocess
import time
import sys
import os
import shlex

def measure_build(engine, options, tex_file):
    """
    Measure LaTeX build time for a given engine and file.

    Args:
        engine (str): Executable name (e.g. 'pdflatex', 'lualatex' or 'xelatex' ...).
        options (str): Command-line options for the engine.
        tex_file (str): The .tex file to compile.
    """
    # You don't need the .exe extension on any OS... so just to make sure it works everywhere:
    exe = engine if os.name == "nt" else engine.replace(".exe", "")

    # Split options into a list
    args = shlex.split(options)
    cmd = [exe, *args, tex_file]

    # Start timer and run the command
    start = time.perf_counter()
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    elapsedTime = time.perf_counter() - start

    # Format and print elapsed time
    minutes = int(elapsedTime // 60)
    seconds = int(elapsedTime % 60)
    milliseconds = int((elapsedTime * 1000) % 1000)
    print(f"Time to build: {minutes:02d}:{seconds:02d}.{milliseconds:02d}", end='')

if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage in Commands: python path:\\to\\txsRuntime.py <engine[pdflatex|xelatex|lualatex]> <options[-synctex=1 -interaction=nonstopmode]> <file[%.tex]>")
        sys.exit(1)

    engine = sys.argv[1]
    options = sys.argv[2]
    tex_file = sys.argv[3]

    measure_build(engine, options, tex_file)
```

Then change the TeXstudio commands:

<img width="1341" height="223" alt="Image" src="https://github.com/user-attachments/assets/125f5b9f-fa66-47ac-94c7-6b392069c704" />

- LaTeX:    `python z:\Data\latex\txsRuntime.py "latex" "-src -interaction=nonstopmode" %.tex > txs:///messages`
- PdfLaTeX: `python z:\Data\latex\txsRuntime.py "pdflatex" "-synctex=1 -interaction=nonstopmode" %.tex > txs:///messages`
- XeLaTeX:  `python z:\Data\latex\txsRuntime.py "xelatex" "-synctex=1 -interaction=nonstopmode" %.tex > txs:///messages`
- LuaLaTeX: `python z:\Data\latex\txsRuntime.py "lualatex" "-synctex=1 -interaction=nonstopmode" %.tex > txs:///messages`

Output:
<img width="683" height="118" alt="Image" src="https://github.com/user-attachments/assets/56a2f888-63f6-4fd0-bdc2-0d268553419d" />

**Comment by octaeder** [comment]
From my pov, build time is a special case of how long any process did run. So I added the current time to the start and end messages. But sunderme refused to add my PR on this. So I use it in my own build (s. #3161).
