### ISSUE TITLE
[Feature Request] Port Org-Mode from Emacs 

### ISSUE THREAD

**Issue by JanWaldhorn** [texstudio-org/texstudio#2507]
### Org-Mode for LaTex Documents

I like using TextStudio very much for years. Recently I came across [org-mode](https://orgmode.org/) in conjunction with LaTex.
I like the easy to read structure of org-mode documents  and especially for recurring applications (letters, or [transcripts of lectures](https://www.youtube.com/watch?v=sxpwBqcCyzA) etc.) it is very nice to see how with very few lines in org-mode practically no latex commands are needed anymore.
So far, to my knowledge, Org-mode to Latex is tied to the Emacs editor, which I think is a pity. It is a very powerful tool, but I like the graphical interface of TexStudio with all the other advantages (PDF viewer and source code linking etc.).

Would it be possible to port the org-mode to latex support from Emacs to TexStudio? In my humble opinion this should be (easily) possible.

### More Articles
[https://opensource.com/article/20/4/emacs-org-mode](https://opensource.com/article/20/4/emacs-org-mode)
[https://devyn.ca/blog/latex-in-two-flavours-a-review-of-org-mode-and-texstudio/](https://devyn.ca/blog/latex-in-two-flavours-a-review-of-org-mode-and-texstudio/)

**Comment by sunderme** [comment]
org mode seems to be one of the many markdown languages.
There is no real advantage in using that against latex except that some commands are simpler to type. 
TeXstudio is focused on latex, there is really no point in trying to support any other markdown as well.
