### ISSUE TITLE
Invalid citation and reference highlighting spontaneously changes

### ISSUE THREAD

**Issue by Linguista** [texstudio-org/texstudio#2512]
When using TexStudio, reference and citation highlighting sometimes spontaneously changes, showing incorrect states (valid vs. invalid). Other times it doesn't change when an invalid reference is fixed. Still other times, the breakage of one item causes unrelated items to be highlighted as if they were invalid, when they are not.

### Environment
TeXstudio 4.2.3 (git n/a)
Qt Version 5.15.5, compiled with Qt 5.15.3 R
Fedora 36
TexLive 2021

### Expected behavior
With my syntax highlighting configuration in TexStudio, valid references should always be green; invalid references should always be red; highlighting should always reflect the validity of the reference; and highlighting of one item should not be affected at all by breakage in unrelated items.

### Actual behavior
The highlighting of both references (not shown here) and citations (shown here) is sometimes incorrect, with valid entries being marked as invalid and vice versa. Also, breaking in one item can cause an unrelated item to be highlighted as if it had become invalid, when it hasn't.

See the following animated GIF for an example of highlighting changing when it shouldn't, and not changing back when it should. In it, I break and fix different citations by adding a space inside them or deleting this space.

![Peek 2022-08-06 23-25](https://user-images.githubusercontent.com/5791472/183275094-3f0285ae-03e3-45ad-b2a3-3dfa00445893.gif)

As I said above, this also happens with references. Furthermore, this incorrect highlighting can be present immediately upon opening a file, without any user intervention. It can be fixed by changing the incorrectly highlighted item's label and then undoing the change.

Below is another example. Upon opening a file, a valid cross-reference was highlighted as invalid. After I added an extra letter to it (making it a truly invalid cross-ref) and then deleted the extra letter, the original cross-ref was now highlighted in green as valid...

![Peek 2022-08-07 11-32](https://user-images.githubusercontent.com/5791472/183298786-a92b2e1d-a358-4d42-be01-8e6f56c30b41.gif)

### How to reproduce
Use syntax highlighting that distinguishes between valid and invalid references and citations. Add references and citations.

**Comment by sunderme** [comment]
I need a minimal example (text file) with instruction on how to reproduce the issue.

**Comment by Linguista** [comment]
Thanks for your response. A MWE will take some doing, as this is from a book and many packages are involved. Though that's not unusual with Latex, of course.

As to instructions for reproducing the problem, the second screencap both explains and shows how to reproduce it -- take a valid cite that is improperly highlighted as invalid (in red), change it in any way at all (by adding a spurious "X" character here), then undo the change. The broken highlighting "magically" fixes itself (turns green), at least temporarily.

**Comment by mbertucci47** [comment]
I can replicate the issue. In the source below if you enter new lines or mess with the label names as mentioned by @Linguista it can cause the `\ref`'s to (improperly) toggle between being marked valid or invalid.

<img width="152" alt="Screenshot 2022-08-07 193710" src="https://user-images.githubusercontent.com/61854785/183321883-eef828fa-0077-4023-b51a-fa0e99b1573f.png">

Source:
```
\documentclass{article}
\begin{document}
abc \label{lab1}
def \label{lab2}
\ref{lab1}
\ref{lab2}
\end{document}
```
