### ISSUE TITLE
small translation to german error for updatechecker.cpp

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2513]
![grafik](https://user-images.githubusercontent.com/102688820/183313838-f74738f8-71e5-432b-9afa-04df4c10d0ac.png)

texstudio_de.ts:
![grafik](https://user-images.githubusercontent.com/102688820/183313789-1585df8b-6698-4e9a-b67b-6310bb75d63e.png)

Since the code adds the point itself (after anchor), translation should be without it (as it is for english):
![grafik](https://user-images.githubusercontent.com/102688820/183314078-a007190d-0f54-41e4-a6d3-93109f50346c.png)

This error from rc1 was passed to new version 4.3.0.

Win10 Qt6 miktex

**Comment by sunderme** [comment]
You can fix translations yourself on transifex, see webpage.
