### ISSUE TITLE
Subimport structure pane functionality broken with update from 4.2.2 to 4.2.3

### ISSUE THREAD

**Issue by baloe** [texstudio-org/texstudio#2514]
I use the command
```
\subimport{path_to_folder/}{file}
```
a lot, because it makes things so much easier when working on bigger projects where the need to restructure content may occur.
This has never been fully supported, meaning that if the file did not exist and you clicked it in the structure pane, TeXstudio wanted to create `./file.tex` instead of `path_to_folder/file.tex` (c.f. also https://github.com/texstudio-org/texstudio/issues/1052)

That was not a big deal though, because once the file did exist, clicking the corresponding item in the structure tree would actually open `path_to_folder/file.tex`.

After updating from 4.2.2 to 4.2.3 though, not even that is working any more.

### Environment
- TeXstudio: 4.2.3
- OS: Ubuntu 20.04.4

### Expected behavior
With
```
\subimport{path_to_folder/}{file}
```
e.g. in the root file, a corresponing item appears in the structure menu and clicking it opens `path_to_folder/file.tex`

### Actual behavior

The item appears, but prompts a dialog asking to create  `./file.tex`.

### How to reproduce

```
mkdir path_to_folder
echo "foo" > path_to_folder/file.tex

echo "\documentclass{article}
\usepackage{import}
\begin{document}
\subimport{path_to_folder/}{file}
\end{document}" > main.tex

texstudio main.tex
```

**Comment by baloe** [comment]
Upgrading to version 4.0.3 resolved the issue.

**Comment by muzimuzhi** [comment]
> Upgrading to version 4.0.3 resolved the issue.

4.3.0, not 4.0.3?

**Comment by baloe** [comment]
> > Upgrading to version 4.0.3 resolved the issue.
> 
> 4.3.0, not 4.0.3?

Uups, 4.3.0, of course

**Comment by baloe** [comment]
Upgrading to version 4.3.0 resolved the issue.
