### ISSUE TITLE
texstudio 4.3.0 doesn't start on OS Catalina 10.15.7

### ISSUE THREAD

**Issue by mroeve** [texstudio-org/texstudio#2517]
Hi I successfully updated texstudio to 4.3.0 via homebrew on my OS Catalina 10.15.7 and the program is installed, but it doesn't start. 
The texstudio icon jumps up and down, stops and nothing happens, the program never opens up. 

(I went through the security alert, opened the context menu on the TXS icon (Ctrl + Click) and selected open).

Is the previous version 4.2.3 available for download anywhere? I didn't find it on the sourceforge site.

Thanks

**Comment by sunderme** [comment]
https://github.com/texstudio-org/texstudio/releases/tag/4.2.3
OSX version is build with OSX11, so it probably does not work with OSX <11 as stated on texstudio.org.

**Comment by muzimuzhi** [comment]
@mroeve Can you try the [texstudio-osx](https://github.com/muzimuzhi/texstudio/suites/7725669185/artifacts/323720562) artifact in https://github.com/muzimuzhi/texstudio/actions/runs/2822437091? It's built with macOS 10.15.

If it works, I can make a release in my fork, or even the `.dmg` can be added to the 4.3.0 release assets.
