### ISSUE TITLE
Align columns account for cmidrule

### ISSUE THREAD

**Issue by baloe** [texstudio-org/texstudio#2519]
The _Align Columns_ tool does not know booktabs' `\cmidrule`. 

### Environment
- TeXstudio: 4.3.0
- OS: Ubuntu 20.0.4

### How to reproduce

Move your cursor inside
```
\begin{tabular}{l l}
\toprule a & b \\\midrule c & d \\\cmidrule{1-2} e & f \\\bottomrule
\end{tabular}
```
then hit the ![Align columns](https://user-images.githubusercontent.com/12622691/183684959-bf012f48-7ed7-4474-bcc4-e612fb8a4fa5.png) button

### Expected behavior
```
\begin{tabular}{l l}
	\toprule
	a & b \\ \midrule
	c & d \\ \cmidrule{1-2}
	e & f \\ \bottomrule
\end{tabular}
```

### Actual behavior
```
\begin{tabular}{l l}
	\toprule
	a                & b \\ \midrule
	c                & d \\
	\cmidrule{1-2} e & f \\ \bottomrule
\end{tabular}
```

**Comment by sunderme** [comment]
you can adapt the setting yourself.
<img width="1159" alt="grafik" src="https://user-images.githubusercontent.com/14033169/183712690-fed926d1-a1b7-4d5b-8c40-3343152ce034.png">

**Comment by baloe** [comment]
Fantastic, thank you.

I ran into another issue though:
I did as suggested, opened the configure dialog → Adv. Editor → added `, \cmidrule` at the end of the special commands field → hit OK.
Even though I did not touch any other setting, I now have a vertical line at the end of the 66th character and any text pass that line gets soft-wrapped. Looking for the place where to deactivate it.

**Comment by muzimuzhi** [comment]
Guess it's related to line wrapping
![image](https://user-images.githubusercontent.com/6376638/183856026-c0da8516-3e36-499a-b847-347a58397580.png)

**Comment by jonasbb** [comment]
@sunderme Changing the suggested option only partially works. `\cmidrule` has a weird syntax, namely the optional argument in `()` parentheses.
`\cmidrule[〈wd 〉](〈trim〉){a–b}`
Adding `\cmidrule(r)` as a special command is possible, if it appears before `\cmidrule`, but given that the `trim` argument can have arbitrary forms, e.g., `(lr{.75em})`, this seems like a poor solution.

Example from the booktabs documentation:
```tex
\begin{tabular}{@{}llr@{}} \toprule
\multicolumn{2}{c}{Item} \\ \cmidrule(r){1-2}
Animal & Description & Price (\$)\\ \midrule
Gnat & per gram & 13.65 \\
& each & 0.01 \\
Gnu & stuffed & 92.50 \\
Emu & stuffed & 33.33 \\
Armadillo & frozen & 8.99 \\ \bottomrule
\end{tabular}
```

After formatting with TeXstudio 4.3.1
```tex
\begin{tabular}{@{}llr@{}}
	\toprule
	   \multicolumn{2}{c}{Item}    &  \\ \cmidrule
	(r){1-2}
	Animal & Description & Price (\$) \\ \midrule
	Gnat             & per gram    &      13.65 \\
	                 & each        &       0.01 \\
	Gnu              & stuffed     &      92.50 \\
	Emu              & stuffed     &      33.33 \\
	Armadillo        & frozen      &       8.99 \\ \bottomrule
\end{tabular}
```
