### ISSUE TITLE
Preview shuts down unexpectedly

### ISSUE THREAD

**Issue by pbertin84** [texstudio-org/texstudio#2520]
Hello! When I compile a document, a preview appears, as usual (and as expected), but after some time (about 1 or 2 minutes), it suddently disappears, without any specific action from me. It's the first time I'm having this issue.

### Environment
- TeXstudio: 4.3.0
- Qt: 6.3.0
- OS: Windows 11
- TeX distribution: 

### Expected behavior

![Capture d’écran (33)](https://user-images.githubusercontent.com/36085348/183693122-ebf4319a-258d-4044-b283-36f3c958a304.png)

### Actual behavior

![Capture d’écran (34)](https://user-images.githubusercontent.com/36085348/183693235-aaf52694-7f5c-43ec-94af-19c65e851729.png)

**Comment by sunderme** [comment]
the "how to reproduce" needs to have an answer.
synced folder ? (dropbox etc.)

**Comment by sunderme** [comment]
no feedback
