### ISSUE TITLE
Search/replace tasks taking for so long and constantly "freezing" the computer

### ISSUE THREAD

**Issue by javifcano** [texstudio-org/texstudio#2524]
### Environment
- TeXstudio: 4.3.0
- OS:  Windows10
- TeX distribution: miktex

### Description
Hi there. I have been using TexStudio for many years, and there has never been any problem. However, in the last year or so, the search & replace tasks are taking an annoying amount of time, with the editor freezing for some seconds every time I must do a search/replace operation. It happens even when I only have one file open. I have seen some related discussions in the forums, but nothing that really helps. Is there any way I can fix that? 

![image](https://user-images.githubusercontent.com/29042309/184026545-da98d711-27ce-401e-a3b9-2cab41aa3ee8.png)

Thanks and regards

**Comment by sunderme** [comment]
there needs to be a test case which demonstrates the issue. That means a tex file, some instructions how to see the issue and possibly a screencast. Windows offers tools for that (e.g. snippet tool for screenshots, google for scrrencast & windows)

**Comment by antshar** [comment]
I had the same problem on Windows 10. Try to use QT6 version of the program, it seems to be quicker for me.

**Comment by sunderme** [comment]
no feedback

**Comment by antshar** [comment]
@javifcano I noticed that your source `.tex` file is located on a portable flash drive. I know that some of them have ridiculously slow reading speed. Do you have the same issue with projects that are located on the same hard drive where your TeXStudio is installed?

**Comment by sunderme** [comment]
is txs portable or installed version ?
If installed, is %appdata%\texstudio\texstudio.ini contain lots of data in `Search\Find%20History` ?
Does it get better if that key is removed ? If texstudio.ini is removed/renamed ?

**Comment by javifcano** [comment]
Hi there, thanks for your support.

I have TexStudio installed. I tried to copy the source files in the same hard drive C:, but still the same problem.

texstudio.ini contains lots of data within Search\Find%20History, with the search&find history, plus tens of thousands of this weird character Ã. I have removed those lines, but still the same problem.

I haven’t tried to remove texstudio.ini? Should I do it? Is it safe to do it?

Thanks


________________________________
De: sunderme ***@***.***>
Enviado: martes, 30 de agosto de 2022 19:53
Para: texstudio-org/texstudio ***@***.***>
Cc: Javier Cano Cancela ***@***.***>; Mention ***@***.***>
Asunto: Re: [texstudio-org/texstudio] Search/replace tasks taking for so long and constantly "freezing" the computer (Issue #2524)


is txs portable or installed version ?
If installed, is %appdata%\texstudio\texstudio.ini contain lots of data in Search\Find%20History ?
Does it get better if that key is removed ? If texstudio.ini is removed/renamed ?

**Comment by sunderme** [comment]
You can remove it but it contains your settings (if you changed something).Renaming allows you to use it again later. Txs needs not to run while you change anything here.

**Comment by javifcano** [comment]
Yes, removing texstudio.ini worked!! I'll try to edit the original file, removing all the unnecessary information but still keeping the necessary settings, but it seems to be what was causing the problem. Thanks and regards
________________________________
De: sunderme ***@***.***>
Enviado: martes, 30 de agosto de 2022 22:44
Para: texstudio-org/texstudio ***@***.***>
Cc: Javier Cano Cancela ***@***.***>; Mention ***@***.***>
Asunto: Re: [texstudio-org/texstudio] Search/replace tasks taking for so long and constantly "freezing" the computer (Issue #2524)


You can remove it but it contains your settings (if you changed something).Renaming allows you to use it again later. Txs needs not to run while you change anything here.

**Comment by sunderme** [comment]
It would be interesting to know what in texstudio.ini caused the issue. In case you like to dig.

**Comment by javifcano** [comment]
As you said, it was the log at the Search\Find%20History. Before removing that, the file size was 3.5MB; after, only 20KB. That has made the difference. Now, everything has back to normal: outstanding performance of TexStudio!!

________________________________
De: sunderme ***@***.***>
Enviado: martes, 30 de agosto de 2022 23:39
Para: texstudio-org/texstudio ***@***.***>
Cc: Javier Cano Cancela ***@***.***>; Mention ***@***.***>
Asunto: Re: [texstudio-org/texstudio] Search/replace tasks taking for so long and constantly "freezing" the computer (Issue #2524)


It would be interesting to know what in texstudio.ini caused the issue. In case you like to dig.
