### ISSUE TITLE
Dictionary not found

### ISSUE THREAD

**Issue by jpluddite** [texstudio-org/texstudio#253]
- TeXstudio: 2.12.10  
- Qt: 5.95 compiled with Qt 5.9.5 R 
- OS:  Linux, Ubuntu 18.04. 
- TeX distribution: texlive

The automatic spellchecker doesn't work, and if I try the Check Spelling command in the Tools menu, the error message says that the dictionary can't be found.

As I understand it, texstudio uses Libreoffice's dictionary. But, the spellchecking for Libreoffice Writer works fine. I'm using Libreoffice 1:6.0.3

Thank you,

**Comment by sunderme** [comment]
txs uses hunspell for checking.
The dictionaries (de/en/fr) can be found in /usr/share/texstudio which needs to be set (if not already) in options/language/dicttionary directory

apart from that you can directly install hunspell dictionaries as ubuntu packages (hunspell-*)

**Comment by jpluddite** [comment]
Thank you, sunderme. Your response was very helpful.
