### ISSUE TITLE
[Question] Access "Contents" window via scripting

### ISSUE THREAD

**Issue by antshar** [texstudio-org/texstudio#2531]
Apparently, the scripting api is more advanced than it's documented so that I usually use this snippet from manual example

![image](https://user-images.githubusercontent.com/54121465/184620480-7979bc15-5bc9-4437-87c4-74ce31905fa0.png)

<details><summary>Copy-paste the code</summary>
<pre>
%SCRIPT
function write_properties(obj) {
    app.fileNew();
    newEditor = documentManager.currentDocument.editorView.editor;   //access the newly created document
    newEditor.setText(Object.getOwnPropertyNames(obj).join("\n"));   //print the properties
}

obj = editor;                                                        //object to show (e.g. the current editor)
write_properties(obj)
</pre>
</details>

However, this time I couldn't manage to find the route to this Contents window.

![image](https://user-images.githubusercontent.com/54121465/184621640-0d0803d9-0c98-4be9-8545-d00972c23503.png)

But I have a feeling, it's somewhere in `pdfs[0].<chain>` or `pdfs[0].widget().<chain>`

**Comment by sunderme** [comment]
I don't think that dock content is accessible via javascript.

**Comment by antshar** [comment]
@sunderme Can I open it at least via `getManagedAction`? For example the following code can access menu item and activate it
```
app.getManagedAction("main/tools/stopcompile").trigger();
```
more precisely it stops the compilation, which button is located in this top bar
![image](https://user-images.githubusercontent.com/54121465/184974786-96b11032-3b3e-433f-a2e5-c480d9c938cd.png)

So there should be a way to access `Window > Show > Contents` of the internal viewer.

**Comment by sunderme** [comment]
unlikely that you can read out a widget.
Anyhow if you want to use undocumented function, you need to look at the source code.

**Comment by antshar** [comment]
@sunderme that's why I asked here: I couldn't find it myself, so I need help from a developer (you) who knows exactly where it's coded in the source files.

**Comment by antshar** [comment]
@sunderme You marked the issue as completed. So how can I access it now?

**Comment by sunderme** [comment]
no, you can't. The question was, is it accessible and the answer is no.
