### ISSUE TITLE
Everything is in bold, can't change back to normal state

### ISSUE THREAD

**Issue by cathy1124** [texstudio-org/texstudio#2534]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior
![image](https://user-images.githubusercontent.com/35569556/185029411-7e830e4d-3d13-4e0a-bf47-8c1b39014843.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/35569556/185029479-2dc575d1-9ad7-41d6-a015-43c324091434.png)

### How to reproduce
[resume_test2.zip](https://github.com/texstudio-org/texstudio/files/9356124/resume_test2.zip)

**Comment by sunderme** [comment]
This is a latex question. Please ask on tex.stackexchange.com
