### ISSUE TITLE
Window geometry saved incorrectly in settings

### ISSUE THREAD

**Issue by hseliger** [texstudio-org/texstudio#2536]
### Environment
- TeXstudio: 4.3.1 (git 4.3.0-17-gd6f13e06f)
- Qt: 5.15.5, compiled with Qt 5.15.5 R
- OS: Linux (Fedora 36, Gnome)
- TeX distribution: texlive

### Expected behavior
When closing TeXstudio, the correct geometry of the application window should be stored in texstudio.ini to restore the session at next application launch

### Actual behavior
The X and Y coordinates are always saved as -1 and -38. This causes TeXstudio to ignore the settings and always start with a default size. If manually changing the texstudio.ini file to e.g. use X and Y of 100 and 100, the window is restored correctly.

E.g., manually setting (my screen is 3440x1440, so big enough)
```
Geometries\MainwindowHeight=500
Geometries\MainwindowWidth=1000
Geometries\MainwindowX=100
Geometries\MainwindowY=100
```

After closing the application, the settings again show incorrect X and Y ( but correct width and height, after I manu

```
Geometries\MainwindowHeight=500
Geometries\MainwindowWidth=1000
Geometries\MainwindowX=-1
Geometries\MainwindowY=-38
```

### How to reproduce
Happens every time now. Issue did not exist 3 weeks ago (was on vacation and updated everything when I came back, so cannot say which change created the problem).

**Comment by sunderme** [comment]
not reproducible
(win/linux)

**Comment by hseliger** [comment]
Are you on X11 or Wayland? Fedora 36 uses Wayland as default. I can try tomorrow when I'm at my desk again what happens in an X11 session.

Is there an easy way to get the **texstudio** view of the window geometry, e.g. using a macro? I don't want to ask what Gnome thinks it is, in case there is an issue in one of the libraries.

If x(), y(), width() and height() do not reliably return sensible values, maybe setting the config in texstudio.cpp needs similar sanity checks as you already implemented when reading the config?

**Comment by octaeder** [comment]
__Example__ txs win10 qt6, FHD display, after window had been maximized:

MainWindow\Maximized=__true__
MainWindow\FullScreen=false
Geometries\MainwindowWidth=1920
Geometries\MainwindowHeight=1017
Geometries\MainwindowX=0
Geometries\MainwindowY=-8

When you click ![grafik](https://user-images.githubusercontent.com/102688820/185241018-24373a46-d857-470e-a223-4d75bfa76fe1.png) then after closing the app the ini file shows:

MainWindow\Maximized=false
MainWindow\FullScreen=false
Geometries\MainwindowWidth=800
Geometries\MainwindowHeight=600
Geometries\MainwindowX=10
Geometries\MainwindowY=10

When I move the top left corner of the window (Alt+Space, V) exactly to the left top corner of the display I see:

MainWindow\Maximized=false
MainWindow\FullScreen=false
Geometries\MainwindowWidth=800
Geometries\MainwindowHeight=600
Geometries\MainwindowX=0
Geometries\MainwindowY=0

**Comment by hseliger** [comment]
@octaeder Thanks, but since you're on Windows it seems to not be an issue

I can now confirm the problem only shows when using Wayland. If I run a Gnome session using X, the coordinates come across correctly.

I have added a debug line in the part where texstudio.cpp saves the config. It seems indeed that the x() and y() functions return -1 and -38 when under Wayland.

However, I could not find yet where the functions are defined; unless someone gives me a hint, I'd have to read the whole code. My guess now would be it's a qt problem with Wayland, but I have too little experience in cpp+qt to quickly home in on the issue.

A suggestion could be to make the readSettings-function in texstudio.cpp is bit more robust. Currently it uses a default for x/y and width/height if the point is off the screen. Maybe one could just move the window onto the screen, but keep the size of the window (i.e. lines 4195+4196 only if size plus x/y is larger than screen). 

I know its a workaround for a bug maybe somewhere else, but I guess this is the case for the whole check if screen contains the coordinates.

**Comment by hseliger** [comment]
Here a patch to texstudio.cpp that would set correct window size even if wayland passes back insane x/y values:

```
diff --git a/src/texstudio.cpp b/src/texstudio.cpp
index 543238837..7317fa260 100644
--- a/src/texstudio.cpp
+++ b/src/texstudio.cpp
@@ -4183,17 +4183,23 @@ void Texstudio::readSettings(bool reread)
     config->beginGroup("texmaker");
 
     QRect screen = QGuiApplication::primaryScreen()->availableGeometry();
-    int w = config->value("Geometries/MainwindowWidth", screen.width() - 100).toInt();
+	// Save the screen dimensions, as the next call will overwrite the correct values
+    int screen_w = screen.width();
+	int screen_h = screen.height();
+	int screen_r = screen.right();
+	// Read window size from config
+	int w = config->value("Geometries/MainwindowWidth", screen.width() - 100).toInt();
     int h = config->value("Geometries/MainwindowHeight", screen.height() - 100).toInt() ;
     int x = config->value("Geometries/MainwindowX", screen.x() + 10).toInt();
     int y = config->value("Geometries/MainwindowY", screen.y() + 10).toInt() ;
     screen = UtilsUi::getAvailableGeometryAt(QPoint(x, y));
     if (!screen.contains(x, y)) {
         // top left is not on screen
+		//Problem: then the other coordinates are incorrect as well!! So we need to use width and height from above
         x = screen.x() + 10;
         y = screen.y() + 10;
-        if (x + w > screen.right()) w = screen.width() - 100;
-        if (y + h > screen.height()) h = screen.height() - 100;
+        if (x + w > screen_r) w = screen_w - 100;
+        if (y + h > screen_h) h = screen_h - 100;
     }
     resize(w, h);
     move(x, y);
```

**Comment by sunderme** [comment]
Would prefer pull requests

**Comment by hseliger** [comment]
Done.

**Comment by hseliger** [comment]
Leaves the question open how to get absolute coordinates consistently under Wayland, but that IMHO is an issue for QT to address. Thus I'll close this issue.
