### ISSUE TITLE
Multiple Instances, per Project Instance

### ISSUE THREAD

**Issue by alceu-git** [texstudio-org/texstudio#2537]
### Describe the feature and the current behavior/state
One feature I miss from other LaTeX editors (like TexnicCenter) is the ability to have a 'project file' which when selected would restore that project 'last session' in a separated instance.

### Who will benefit with this feature?
advance/heavy LaTeX/TeX users who, like me, is frequently having to work in separate articles/projects, some co-related, but most of time not (like when I'm reviewing students sent files).

I know of the --start-always, which opens a 'new instance', but the 'new instance' carries the files of the last session/instance (quite annoying, specially given that some projects of mine might have upwards of 20 files).

another scenario where it is very important is when working on a class/package file, normally one will have a test file (the 'master/main' file, whilst many package files opened, it is quite annoying to remember that texstudio knows nothing of such scenario and I have to remember to switch over the 'test file' for a test compile (I keep pressing the compile now button in the package/class file... which obviously can't be associated to any 'master file')

### Any Other info
I recently switched over to windows 11, and rather sadly, TeXnicCenter is showing it's age (and lack of support/development): it still kind of works, but with lots of anomalies, which forced me to look after alternatives. TeXstudio seems to be the one to replace, but the lack of a true 'project file' and true multiple instance, might be the reason to leave it as it is, and look elsewhere... 

Looking past 'issues' I found a few related/equal to this (sorry, I forgot to keep track of the issues numbers), and I'm aware that, although others have requested this already, developers are not found of such a scenario (the few tickets I found, where all closed without any change).

**Comment by sunderme** [comment]
maybe you should check txs capabilities.
1) txs automatically detects the root document (master) if it was opened in txs. Hence you can easily use more than one root document by letting txs automatically detect it.
2) you can store/open sessions
3) you can define an explicit root file when detection is not possible,e.g. when working on a package file.

So, I have not seen a scenario which is not currently covered. txs is not texniccenter and it does not try to emulate it. That does not mean, it does not offer solutions for most common scenarios.

**Comment by dbitouze** [comment]
One of the missing features is the notion of TODOs per project. Currently, if you have a parent (root) file with a few child (sub) files and you add TODOs to several child files, these TODOs are not collected and you have to inspect all the child files as well as the root file to check if there are still unprocessed TODOs.

**Comment by alceu-git** [comment]
sorry, sunderme, your approach (that I have already saw as the standard reply to this kind of request) doesnt come even close to it...
At my university department, I'm the local maintainer of a few dedicated LaTeX packages and classes, it is quite common that I have to open a few colleagues' (or my own) projects with the underline packs/classes side by side (code maintenance).
with TeXnicCenter this never was an issue, if I edited a package file in an instance, the other instances got notified, each instance with it's dedicated 'compilation workflow' (project based) so I could track down any issue that would surface in any case.
besides, it is quite common (for me at least) to have about 10+ files opened PER project, at same time. I already noticed that, with TeXstudio it is a mess (in that regard), bacause, yeah, you can set the !TeX directives per file belonging to a project (if a file belongs to one, and only one, project (which, again, isn't my typical case... bib files being a simple case))...
but, even so, you end up with a single workplace, everything in different tabs (again, it is ok if you only have to deal with a single project at a time... not my case)

**Comment by alceu-git** [comment]
I mean, even back 'in my days' (early 80s) any integrated system (deserving such a denomination) would start by a project declaration file/config/database... quite harsh to see that such, otherwise fantastic IDE system, doesn't support the notion of PER project workflow, definitions, files, etc...

**Comment by sunderme** [comment]
> One of the missing features is the notion of TODOs per project. Currently, if you have a parent (root) file with a few child (sub) files and you add TODOs to several child files, these TODOs are not collected and you have to inspect all the child files as well as the root file to check if there are still unprocessed TODOs.

unless you accidentally switch to global TOC ... et voilá, all TODOs.

**Comment by sunderme** [comment]
> TeXstudio seems to be the one to replace, but the lack of a true 'project file' and true multiple instance, might be the reason to leave it as it is, and look elsewhere...

That is why open source (and commercial) offers a number of specialized (and non-speczialized) latex editors, so the users can find the best suited.

**Comment by dbitouze** [comment]
> unless you accidentally switch to global TOC ... et voilá, all TODOs.

Sorry, I don't see what you mean: how to switch to global TOC?

**Comment by sunderme** [comment]
<img width="427" alt="grafik" src="https://user-images.githubusercontent.com/14033169/185204851-26c17876-924d-4db8-8955-fb10603d087e.png">

Todo here is a comment starting with `%TODO`. (Manual 2.4.1)

**Comment by octaeder** [comment]
[manual 2.4.2](https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html#SECTION142)
2.4.1 is the structure view

**Comment by dbitouze** [comment]
> In any case, switching from “Structure” to “TOC” in the left panel doesn't expose any TODO.

Sorry, it does work with TXS 4.3.0.

**Comment by sunderme** [comment]
<img width="743" alt="grafik" src="https://user-images.githubusercontent.com/14033169/185206380-533c820e-d014-4017-9b7e-b1745a26ce8c.png">

**Comment by sunderme** [comment]
and it works with structure, but then limited within a file

**Comment by alceu-git** [comment]
yeah, "let's agree to disagree"... if you, part of the developers team, sees no value in a true project based system, no point in talking about one.
a single comment: with TeXnicCenter (damn, it's development stopped long ago...) one had that feature, out of the box, never having to use any pragma or being careful about 'which tab am I looking at', it was enough to set, 'for this project, main file is...' done, from then on you just had to open the project file and everything would be appropriately set.

'the structure view', yes it works, and it is all fine if your projects have just a few files each, and (at most) you need to just a few pragmas telling TeXstudio, 'look, my main file is...'... and you are comfortable having all files of many unrelated projects opened at once (or you are fine closing everything before opening a second project, working in just one at a time...) 

but, it's ok, as you said : " That is why open source (and commercial) offers a number of specialized (and non-speczialized) latex editors, so the users can find the best suited. "
meaning (my guess) if one wants it, TeXstudio isn't the tool for it (and never will be, well, just because it isn't an important feature...). fine.

no point in arguing about it, it is what it is.

**Comment by sunderme** [comment]
indeed no point in arguing.
Somehow users from other editor fail to accept the idea that txs can automatically detect root files and act accordingly (no "pragma" needed)
The main point is that txs is not texniccenter, using it affords some (philosophical) adaptations.

**Comment by alceu-git** [comment]
big time lol, it isnt just the case 'of some mental adjustment', would that be the case, I wouldn't be here...
problem that made me take the time to try to shine some light on the matter is that, given my workflow, quite often (trying to adapt myself to the oddities of TeXstudio) I found myself asking the damn thing to 'just compile', but then realizing 'damn the cursor is in the *.cls file' no 'associated master file' (and none that would make any sense). so, the same fate of others that have asked the same thing here, and got the very same answer: go away, we dont care about that.

**Comment by octaeder** [comment]
to have a separate instance of txs with second project, see [synopsis](https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html#TEXSTUDIO-CMD): <html><body>


--start-always | start a new instance, even if TXS is already running. This allows using of multiple instances.
-- | --



</body>
</html>

save the project as a session so you can reopen it with all the files/tabs as it ahs been before.

**Comment by alceu-git** [comment]
> to have a separate instance of txs with second project, see [synopsis](https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html#TEXSTUDIO-CMD):
> 
> --start-always	start a new instance, even if TXS is already running. This allows using of multiple instances.
> save the project as a session so you can reopen it with all the files/tabs as it has been before.

Indeed (I knew that), not to say I haven't tried to adapt. 
I mean, my current workaround:
1) for each project I create a 'session'
2) when I want to open/work in that project I go to  powershell and manually start a new instance 
  >>  & 'C:\Program Files\texstudio\texstudio.exe' --start-always 
  2.1) why that? well, windows and it's quirks, there is no reliable way to associate the program option to it's call (graphic interface). sure, one can edit the register for it to work (and remember to redo it every time the program gets update).
 3) in the new instance I restore a previously saved session.
4) ...not forgetting : I have to remember to save the current session by the end of it (the "save all" doesn't save/update the session file)

this kind of deceives the idea of an integrated graphic interface... but indeed, albeit not perfect, would one have the option to tell texstudio 'start a new instance' when called, regardless, it would help a lot...

it still won't completely help my 'workflow' in which, more often that not, I'm working on some package/class file (no associated master file that would make any sense)... but, 
just being able to 'double click a saved session', and that action resulting in a new instance being opened, and, even better, when pressing the 'save all' the "session" would also be updated, that would go a long way helping people like me ;)

**Comment by octaeder** [comment]
I see you already tried many options. Maybe try it with a new request for an option that works as if command option --start-always had been given. But I'm not sure if such an option is possible.

**Comment by alceu-git** [comment]
> I see you already tried many options. Maybe try it with a new request for an option that works as if command option --start-always had been given. But I'm not sure if such an option is possible.

from what I saw in previous requests (besides the same standard reply): there are some issues (read synctex) associated with simultaneous instances (specially if one is using an external pdf viewer...). so, --start-always seems to be just a work around. (and might be the reason it isn't an out of the box option/behavior)

**Comment by yashpalgoyal1304** [comment]
i was wondering about same thing - and no, i ain't coming from any other software txs is my very first and only point of reference for latex editors. still, i felt the need of this option to "open a new window" so that i can open different project there. some usecases from my side:


| simultaneous scenarios | remark |
| --- | --- |
| working on main project, say P1 | one window of TXS occupied |
| want to focus on honing a Ti*k*Z figure with live preview being "Shown in embedded viewer" | new TXS window required |
| have to refer an old project say P2, for deciding the edits in P1 | new TXS window required |
| incurred some query, want to create a Minimal Working Example for posting on forums | new TXS window required |
