### ISSUE TITLE
Extra spacer in Graphics Wizard

### ISSUE THREAD

**Issue by tmelorc** [texstudio-org/texstudio#2538]
### Environment
- TeXstudio: 4.3.1 (git 4.3.0-17-gd6f13e0)
- Qt: Using Qt Version 5.11.1, compiled with Qt 5.11.1 R
- OS: Linux Mint

### Description
In the Insert Graphics Wizard I found that there is an extra spacer in front of the Center Horizontally checkbox, as we can see in the image below.

![Seleção_256](https://user-images.githubusercontent.com/15181573/185150197-5b9772df-e9d3-4f48-9d34-a5091ef5b7f7.png)

I'm not sure if that alignment is the desired one but in my opinion, removing that spacer would look better, as below.

![Seleção_257](https://user-images.githubusercontent.com/15181573/185150226-847449d8-4230-45c5-b5ea-e5f045ef81d7.png)

**Comment by sunderme** [comment]
this was intentionally added in 2011.
I don't care one way or another, so I would let it stay as it is.

**Comment by tmelorc** [comment]
Thanks for attention. 
Since I consider the well alignment an improvement on the layout, do you mind to update it? 
I agree that it is just cosmetic but... why not?
Regards.

**Comment by sunderme** [comment]
I usually don't change other author's work, especially as it probably cost some effort to set it up the way it is.

**Comment by tmelorc** [comment]
> 

Oh, I didn't know that it is not your code. Sorry. 
So, lets keep it for a while and see if someone changes it. Regards.
