### ISSUE TITLE
Packages are all marked as unknown

### ISSUE THREAD

**Issue by pospiech** [texstudio-org/texstudio#2543]
All packages are underlined as "unknown"

### Environment
- TeXstudio: 4.3.0
- Qt: 6.3.0
- OS: Windows 11
- TeX distribution: texlive

### Expected behavior
All packages are not marked as unknown

### Actual behavior
![image](https://user-images.githubusercontent.com/1280544/185805494-6f9d997e-fcb2-4210-a76b-4c674d0c693e.png)

### How to reproduce
Install Version 4.3.0
Previous version did not show this error.

**Comment by sunderme** [comment]
what is the result of help/check latex installation

and on cmd.exe (or powershell): `kpsewhich --show-path ls-R` ?

**Comment by pospiech** [comment]
Here the output:

 

C:\Users\matth>kpsewhich --show-path ls-R ?

C:/texlive/texmf-local;C:/texlive/2022/texmf-config;C:/texlive/2022/texmf-var;C:/texlive/2022/texmf-dist

 

Viele Grüße,

Matthias Pospiech

 

Von: sunderme ***@***.***> 
Gesendet: Sonntag, 21. August 2022 21:39
An: texstudio-org/texstudio ***@***.***>
Cc: Matthias Pospiech ***@***.***>; Author ***@***.***>
Betreff: Re: [texstudio-org/texstudio] Packages are all marked as unknown (Issue #2543)

 

what is the result of help/check latex installation

and on cmd.exe (or powershell): kpsewhich --show-path ls-R ?

**Comment by sunderme** [comment]
what is the result of help/check latex installation ?

**Comment by sunderme** [comment]
and in the paths `C:/texlive/texmf-local;C:/texlive/2022/texmf-config;C:/texlive/2022/texmf-var;C:/texlive/2022/texmf-dist`, there should be a file ls-R. Is it present and do any of them contain "eurosym.sty"

**Comment by pospiech** [comment]
In C:/texlive/2022/texmf-dist

 

./tex/latex/eurosym:

eurosym.sty

 

Viele Grüße,

Matthias Pospiech

 

Von: sunderme ***@***.***> 
Gesendet: Montag, 22. August 2022 18:26
An: texstudio-org/texstudio ***@***.***>
Cc: Matthias Pospiech ***@***.***>; Author ***@***.***>
Betreff: Re: [texstudio-org/texstudio] Packages are all marked as unknown (Issue #2543)

 

and in the paths C:/texlive/texmf-local;C:/texlive/2022/texmf-config;C:/texlive/2022/texmf-var;C:/texlive/2022/texmf-dist, there should be a file ls-R. Is it present and do any of them contain "eurosym.sty"

**Comment by pospiech** [comment]
dpi: 96

where pdflatex: C:\texlive\2022\bin\win32\pdflatex.exe

 

PDFLATEX: pdflatex.exe -version

pdfTeX 3.141592653-2.6-1.40.24 (TeX Live 2022)

kpathsea version 6.3.4

Copyright 2022 Han The Thanh (pdfTeX) et al.

There is NO warranty.  Redistribution of this software is

covered by the terms of both the pdfTeX copyright and

the Lesser GNU General Public License.

For more information about these matters, see the file

named COPYING and the pdfTeX source.

Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.

Compiled with libpng 1.6.37; using libpng 1.6.37

Compiled with zlib 1.2.11; using zlib 1.2.11

Compiled with xpdf version 4.03

 

Environment variables:

=::=::\

__COMPAT_LAYER=DetectorsAppHealth

ALLUSERSPROFILE=C:\ProgramData

APPDATA=C:\Users\matth\AppData\Roaming

CommonProgramFiles=C:\Program Files\Common Files

CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files

CommonProgramW6432=C:\Program Files\Common Files

COMPUTERNAME=DESKTOP-D1P97HN

ComSpec=C:\WINDOWS\system32\cmd.exe

DriverData=C:\Windows\System32\Drivers\DriverData

FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer

FPS_BROWSER_USER_PROFILE_STRING=Default

HOMEDRIVE=C:

HOMEPATH=\Users\matth

LOCALAPPDATA=C:\Users\matth\AppData\Local

LOGONSERVER=\\DESKTOP-D1P97HN

NUMBER_OF_PROCESSORS=16

OneDrive=C:\Users\matth\OneDrive

OneDriveConsumer=C:\Users\matth\OneDrive

OS=Windows_NT

Path=C:\Program Files\Python310\Scripts\;C:\Program Files\Python310\;C:\Program Files (x86)\VMware\VMware Player\bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Inkscape\bin;C:\texlive\2022\bin\win32;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git\cmd;C:\Users\matth\AppData\Local\Microsoft\WindowsApps;

PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

PROCESSOR_ARCHITECTURE=AMD64

PROCESSOR_IDENTIFIER=AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD

PROCESSOR_LEVEL=23

PROCESSOR_REVISION=0802

ProgramData=C:\ProgramData

ProgramFiles=C:\Program Files

ProgramFiles(x86)=C:\Program Files (x86)

ProgramW6432=C:\Program Files

PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules

PUBLIC=C:\Users\Public

SESSIONNAME=Console

SystemDrive=C:

SystemRoot=C:\WINDOWS

TEMP=C:\Users\matth\AppData\Local\Temp

TMP=C:\Users\matth\AppData\Local\Temp

USERDOMAIN=DESKTOP-D1P97HN

USERDOMAIN_ROAMINGPROFILE=DESKTOP-D1P97HN

USERNAME=matth

USERPROFILE=C:\Users\matth

windir=C:\WINDOWS

 

TeXstudio:

Path        : C:\Program Files\texstudio\texstudio.exe

Program call: C:\Program Files\texstudio\texstudio.exe

Setting file: C:\Users\matth\AppData\Roaming\texstudio\texstudio.ini

 

Command configuration in TeXstudio:

    SVNADMIN (svnadmin): 

    Precompile (pre-compile): 

    PDF Viewer (view-pdf): txs:///view-pdf-internal --embedded

    DVI->PDF Chain (dvi-pdf-chain): txs:///latex | txs:///dvipdf | txs:///view-pdf

    External Terminal (terminal-external): C:\WINDOWS\system32\cmd.exe

    Default Compiler (compile): txs:///lualatex

    Asymptote PDF Chain (asy-pdf-chain): txs:///pdflatex | txs:///asy | txs:///pdflatex | txs:///view-pdf

    Xindex (xindex): xindex.exe -l * %.idx

    Latexmk (latexmk): latexmk.exe -pdf -silent -synctex=1 %

    Build & View (quick): txs:///compile | txs:///view

    DVI Chain (dvi-chain): txs:///latex | txs:///view-dvi

    Default Glossary Tool (glossary): txs:///makeglossaries

    PDF Chain (pdf-chain): txs:///pdflatex | txs:///view-pdf

    DVI->PS->PDF Chain (dvi-ps-pdf-chain): txs:///latex | txs:///dvips | txs:///ps2pdf | txs:///view-pdf

    PS Viewer (view-ps): "C:\texlive\2022\bin\win32\psviewer.exe" "?am.ps"

    Biber (biber): biber.exe %

    texdoc (texdoc): texdoc.exe 

    GIT (git): git.exe 

    Default Index Tool (index): txs:///makeindex

    DviPdf (dvipdf): dvipdfmx.exe %.dvi

    Default Bibliography Tool (bibliography): txs:///bibtex

    Asymptote DVI Chain (asy-dvi-chain): txs:///latex | txs:///asy | txs:///latex | txs:///view-dvi

    BibTeX (bibtex): bibtex.exe %

    DviPs (dvips): dvips.exe -o %.ps %.dvi

    Ps2Pdf (ps2pdf): ps2pdf.exe %.ps

    LaTeX (latex): latex.exe -src -interaction=nonstopmode %.tex

    PS Chain (ps-chain): txs:///latex | txs:///dvips | txs:///view-ps

    LuaLaTeX (lualatex): lualatex.exe -synctex=1 -interaction=nonstopmode %.tex

    XeLaTeX (xelatex): xelatex.exe -synctex=1 -interaction=nonstopmode %.tex

    Ghostscript (gs): "C:\texlive\2022\bin\win32\rungs.exe" "?am.ps"

    DviPng (dvipng): dvipng.exe -T tight -D 120 %.dvi

    Texindy (texindy): texindy.exe %.idx

    Default Viewer (view): txs:///view-pdf

    Makeindex (makeindex): makeindex.exe %.idx

    Makeglossaries (makeglossaries): makeglossaries.exe %

    Internal Precompile (internal-pre-compile): txs:///pre-compile | txs:///conditionally-recompile-bibliography

    DVI Viewer (view-dvi): "C:\texlive\2022\bin\win32\dviout.exe" "?am.dvi"

    PdfLaTeX (pdflatex): pdflatex.exe -synctex=1 -interaction=nonstopmode %.tex

    External PDF Viewer (view-pdf-external): "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --single-argument ?am.pdf

    MetaPost (metapost): mpost.exe -interaction=nonstopmode ?me)

    Recompile Bibliography (recompile-bibliography): txs:///compile | txs:///bibliography | txs:///compile

    Asymptote (asy): asy.exe ?m*.asy

    SVN (svn): 

    BibTeX 8-Bit (bibtex8): bibtex8.exe %

 

Additional Search Paths:

    Command: 

    Log: 

    Pdf:

 

Viele Grüße,

Matthias Pospiech

 

Von: sunderme ***@***.***> 
Gesendet: Montag, 22. August 2022 10:11
An: texstudio-org/texstudio ***@***.***>
Cc: Matthias Pospiech ***@***.***>; Author ***@***.***>
Betreff: Re: [texstudio-org/texstudio] Packages are all marked as unknown (Issue #2543)

 

what is the result of help/check latex installation ?

**Comment by sunderme** [comment]
option to scan package names is on, right ?
<img width="1226" alt="grafik" src="https://user-images.githubusercontent.com/14033169/185994398-d2403570-840e-4a9e-af40-9ff3450504a0.png">

**Comment by sunderme** [comment]
?

**Comment by pospiech** [comment]
![image](https://user-images.githubusercontent.com/1280544/186967688-efab11be-0d51-4601-a0c7-98a957e72ae9.png)

**Comment by sunderme** [comment]
I have installed texlive on win10 and I can't reproduce the issue.
You can check if %appdata%\texstudio contains packageCache.dat , but I have no further ideas.
May be a win11 issue but I don't have win11.

**Comment by pospiech** [comment]
packageCache.dat contains only packages that are placed in C:\texlive\texmf-local

% detected .sty and .cls filenames
MinionPro
MinionPro-FontDef
MyriadPro
MyriadPro-FontDef
asyntax
bera
beramono
berasans
beraserif
classico
europs
eurosans
fontaxes
fourier
fourier-orns
fourierx
frutiger
futura
gandhi
garamondx
gillsans
literat
ltxmdf
luximono
mathpmnt
mdframed
mdsymbol
optima
otfontdef
tabfigures
uarial
ulgothic
xagaramon
xutopia

**Comment by pospiech** [comment]
Looks like it is enabled.

 

Viele Grüße,

Matthias Pospiech

 

Von: sunderme ***@***.***> 
Gesendet: Montag, 22. August 2022 20:38
An: texstudio-org/texstudio ***@***.***>
Cc: Matthias Pospiech ***@***.***>; Author ***@***.***>
Betreff: Re: [texstudio-org/texstudio] Packages are all marked as unknown (Issue #2543)

 

option to scan package names is on, right ?
 <https://user-images.githubusercontent.com/14033169/185994398-d2403570-840e-4a9e-af40-9ff3450504a0.png>

**Comment by sunderme** [comment]
so, it is working now ?

**Comment by pospiech** [comment]
I downloaded the latestest release and it seems to work now.

 

Viele Grüße,

Matthias Pospiech

 

Von: sunderme ***@***.***> 
Gesendet: Dienstag, 11. Oktober 2022 20:00
An: texstudio-org/texstudio ***@***.***>
Cc: Matthias Pospiech ***@***.***>; Author ***@***.***>
Betreff: Re: [texstudio-org/texstudio] Packages are all marked as unknown (Issue #2543)

 

so, it is working now ?
