### ISSUE TITLE
Chapter / Section Display in TOC

### ISSUE THREAD

**Issue by erwin-sommerauer** [texstudio-org/texstudio#2546]
### Environment
- TeXstudio: late 3.x versions up to 4.3.0
- Qt: 6
- OS: Windows 10 Pro
- TeX: texlive 2022

### Expected behavior
In the TOC view chapters should be displayed with a "C" symbol, sections with a "S" symbol after loading a document.

### Actual behavior
- TOC immediately after opening a TEX file: only sections are shown, and \chapter{} is often (not always!) marked with pink background
![image](https://user-images.githubusercontent.com/105913478/185887777-b8c8946e-eb83-4873-8068-e7482f4c1bbb.png)
![image](https://user-images.githubusercontent.com/105913478/185888385-3efba8a1-45df-42cb-ada6-008b767bd95d.png)

- After an edit operation in the \chapter{} line (e.g. adding and immediately removing a character), the chapter where the edit happened ist displayed in TOC, and all sections from the document are shown as if they would be from this chapter (that is, all following chapters are omitted in TOC):
![image](https://user-images.githubusercontent.com/105913478/185889342-c49d5adc-a488-4f04-8458-c4814b16ccb6.png)

- After editing each \chapter{} line everything is displayed as it should be:
![image](https://user-images.githubusercontent.com/105913478/185890126-b61675f9-9e50-4821-801d-57a84c9febac.png)

After saving the document an re-opening it the same happens once again. This behaviour startet with a late 3.x version - I only have a 3.0.1 version available where everything works as expected.

### How to reproduce
Just create a document based on the scrreport document class with chapters and sections.

### Additional info:
My document setup is as follows:
I have an default document with all settings called 'dev.tex'. This document contains the document class as well as the used packages and command redefinitions. All main documents contain as the very first line
\input{R:/def.tex}, then some individual definitions and finally the document content with \begin{document}.

**Comment by sunderme** [comment]
please provide a text document.
"just do this and that" has proven to be ineffective time and again.

**Comment by erwin-sommerauer** [comment]
OK - sorry.
As long as everything is in one single tex file all works correct.

If I put the preamble in a separate file (in this example, 'global.tex') to be re-used by other documents the problem occurs:
If you open 'document.tex' you will see only the sections but not the chapters in the TOC. The chapters are shown only if you do an edit action (e.g. add/remove a character) in the chapter line; to see all chapters you have to modify all chapter lines.

[test.zip](https://github.com/texstudio-org/texstudio/files/9399691/test.zip)
