### ISSUE TITLE
CUT+Paste removes whole line with Shift+ENTF

### ISSUE THREAD

**Issue by pospiech** [texstudio-org/texstudio#2549]
Cutting out a string with SHIFT+ENTF removes the whole line as if the whole line was marked.
Insert with STR+V inserts the whole line.

### Environment
- TeXstudio: 4.3.0
- Qt: 6.3.0
- OS: Win 11
- TeX distribution: texlive

### Expected behavior
extrect from editor only marked code and insert only marked code

### Actual behavior
as described above

### How to reproduce
as described above

**Comment by sunderme** [comment]
That description is too ambiguous. No idea what expected behavior is supposed to mean.

shift+entf is supposed to cut the whole current line. If that is undesired, you can change the shortcut in options.

**Comment by pospiech** [comment]
I used computers since the late 80s. On windows Ctrl+C/V was not avaliable 

and the shortcut was Shift+Delete/CTL+Insert for cut and paste

 

The meaning of shift (+ direction key) up to date is: mark the text.

The meaning of Delete is: delete next or marked text

The meaning of Shift+Delete is copy and remove the marked text.

 

This works in all editors and application on windows, but not in texstudio.

 

There is no definition of copy and remove the whole line on windows,

other then POS1, Shift+END, Shift+DELETE

 

I therefore recommend to keep the usual behaviour that is expected on the OS-plattform.

 

Viele Grüße,

Matthias Pospiech

 

Von: sunderme ***@***.***> 
Gesendet: Dienstag, 23. August 2022 21:45
An: texstudio-org/texstudio ***@***.***>
Cc: Matthias Pospiech ***@***.***>; Author ***@***.***>
Betreff: Re: [texstudio-org/texstudio] CUT+Paste removes whole line with Shift+ENTF (Issue #2549)

 

That description is too ambiguous. No idea what expected behavior is supposed to mean.

shift+entf is supposed to cut the whole current line. If that is undesired, you can change the shortcut in options.

**Comment by pospiech** [comment]
> well, all modern IDEs use shift+del for cutting lines.

Thats the point where I disagree – Notepad++ and Visual Studio Code (the one I have open currently) do not use it for cutting lines (and Word/Office 365).

I do not even know any IDE that has this definition apart from texstudio.

 

Which IDEs use this definition?

 

Viele Grüße,

Matthias Pospiech

 

Von: sunderme ***@***.***> 
Gesendet: Mittwoch, 24. August 2022 19:13
An: texstudio-org/texstudio ***@***.***>
Cc: Matthias Pospiech ***@***.***>; Author ***@***.***>
Betreff: Re: [texstudio-org/texstudio] CUT+Paste removes whole line with Shift+ENTF (Issue #2549)

 

well, all modern IDEs use shift+del for cutting lines.
txs did not use shift+del for anything before, so using it as a new shortcut seems to be fair.
You can easily adapt the shortcuts to your likings. options/shortcuts -> menus/edit/line operations/cut line -> set shortcut here to <none>

**Comment by sunderme** [comment]
visual studio code does, so does pycharm & qtcreator.
ctrl+x is the commonly used shortcut for cutting. There is really no benefit in making that redundant with a second shortcut. 
Again, freely configurable.

**Comment by sunderme** [comment]
brought closer to the behavior of vs code. If there is a selection cut, otherwise cut line.
e1bedc6c4c50e6e39c77ffe1a1a5bac29f39efcd
