### ISSUE TITLE
\begingroup..\endgroup completion doesn't mark ".." as placeholder.

### ISSUE THREAD

**Issue by kbauer** [texstudio-org/texstudio#255]
This issue is similar to https://github.com/texstudio-org/texstudio/issues/228, indicating that it might be more widespread.

### Environment
- TeXstudio: 2.12.10
- Qt: Using Qt Version 5.8.0, compiled with Qt 5.8.0 R
- OS: Windows 10 (Microsoft Windows [Version 10.0.17134.167] "April Update" (2018))
- TeX distribution: MikTeX

### How to reproduce
  - Type `\begingroup`
  - Complete to `\begingroup..\endgroup`

### Expected behavior
  - `..` should be a placeholder.

### Actual behavior
  - `..` is normal text, and thus cannot be navigated to as a placeholder with <kbd>Ctrl+Left/Right</kbd>

### List of completions known to be affected
  - `\begingroup..\endgroup`
  - `\bgroup..\egroup`

**Comment by sunderme** [comment]
you are welcome to correct the tex.cwl and others. There is no automatic substitution for ".." and none is intended.

**Comment by kbauer** [comment]
@sunderme After cloning the repository, I realized that you've already fixed this 13 days ago as part of the fix for #228 and it's just not yet in the release version. Sorry for the double-report.
