### ISSUE TITLE
[4.3.0] Right context menus eventually get stuck to upper window border

### ISSUE THREAD

**Issue by muxina-credo** [texstudio-org/texstudio#2551]
**Environment**

```
TeXstudio: 4.3.0
Qt: 6.3.1
OS: Manjaro 21.3.7
TeX distribution: texlive
```

**Expected behaviour**

Right click context menus should drop from pointer position.  Lower Language and Encoding menus should ascend rom their headers.

**Actual behaviour**

After changing to a file window and back to texstudio, the right click context menus stop dropping from pointer and the Lower Language and Encoding menus don't ascend from their headers.

**How to reproduce**

Setting: delete or move the content of ~/.config/texstudio (once the problem appears doing this temporarily solves the issue).

1. Open texstudio.
2. Load document.tex.
3. Open a file widow.
4. Right click a few times in the pdf preview window on its lower part. After a couple of tries, the context menu stops dropping from the pointer. The Language and encoding context menus also don't ascend from the appropriate places.

**document.tex**

```
\documentclass{article}

\begin{document}
	content...
\end{document}
```

**Comment by sunderme** [comment]
not reproducible.
Screencast ?

**Comment by muxina-credo** [comment]
It turned out it was more subtle then what I had described. I was able to find a minimal example of the problem. As time goes on the problem gets worse and worse after its onset. I'll edit the first post. Please @sunderme try again :smile: .

**Comment by sunderme** [comment]
that looks rather like a qt and/or wayland error ?

**Comment by sunderme** [comment]
try xorg desktop to verify

no further feedback
