### ISSUE TITLE
Inode file number changed (hardlink breaks)

### ISSUE THREAD

**Issue by HamsterofPi** [texstudio-org/texstudio#2553]
### Environment
- TeXstudio: 4.2.1 (Build: 4.2.1+ds-1)
- Qt: 5.15.3, compilé avec Qt 5.15.2 R
- OS: Ubuntu 22.04.1 LTS
- TeX distribution: pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian)

### Expected behavior
When modifying a file It's inode number should not change.

### Actual behavior
When modifying a file It's inode number changes, breaking hardlinks.

### How to reproduce
create a file test.tex and run the command "ls -i" then open the file with texstudio, type some text and save. Run "ls -i" again, the number has changed.

**Comment by HamsterofPi** [comment]
Possibly related topic : https://sourceforge.net/p/texstudio/feature-requests/912/

**Comment by sunderme** [comment]
it can be turned off: option/advanced editor/safe writing of files.
