### ISSUE TITLE
TS prompts me to update from 4.3.00 to 4.3.0

### ISSUE THREAD

**Issue by ColourGrey** [texstudio-org/texstudio#2554]
### Environment
- TeXstudio: 4.3.0
- Qt: 6.3.0
- OS: Windows 10 64bit
- TeX distribution: MikTeX

Right after launch, TS checks to see if a newer version is available. I currently have version 4.3.0, which it somehow sees as 4.3.00, which it considers to be older than 4.3.0, so it keeps prompting me to update from 4.3.00 to 4.3.0. The following screenshot explains it visually.
<img width="210" alt="updater" src="https://user-images.githubusercontent.com/57685970/186919534-42ce1734-fc18-4daf-858a-596d1c71fede.png">

**Comment by octaeder** [comment]
This is fixed with PR #2527 (for next release). Meanwhile you may increase the time interval for the automatic update checker in the configuration (menu __options__). I would recommend not turning off the update checker completely.
