### ISSUE TITLE
mismatch in version numbers in own build

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2557]
After build of current repo I see following info from TXS. About-Dialog:

![image](https://user-images.githubusercontent.com/102688820/187049401-c146c7e5-59ab-40b4-a782-872e4e8ae459.png)

Txs version (outside parentheses) reflects change towards next version coming up, and git says, this is a build that is 4 commits after release 4.3.1. This is ok. But Update-Check:

![image](https://user-images.githubusercontent.com/102688820/187049432-0c3ed21c-ac3a-4089-a144-ea36d88c6525.png)
 
From my point of view update check should show 4.3.**1**-4.

Thx
Win10, Qt6

**Comment by octaeder** [comment]
Hint: Changed first post because of different results after using make clean and rebuild.

**Comment by sunderme** [comment]
1. I am not really concerned with update check on git builds. You should know, what version you build.
2. the current cycle is for version 4.3.2. if anything the version stated could be something like 4.3.2 dev4
3. the whole thing needs to work outside a git clone (when you directly download the source) and there is no guarantee that the tag is even there on git

**Comment by octaeder** [comment]
Own build 4.3.2-4 is most likely (not totally sure because of recent changes here) handled as 4.3.2stable0-4 when comparing versions. If someone is using such a version cause he needs a recent fix, his txs won't notify him in the future that 4.3.2alpha1 is available (because 4.3.2stable is handled as a version higher than 4.3.2alpha - which is higher than 4.3.1stable). Hopefully he receives a git mail about the alpha release. But since nothing can be done, this issue can be closed from my side.
