### ISSUE TITLE
The .cwl file for Tabularray package is not working.

### ISSUE THREAD

**Issue by MiltosTex** [texstudio-org/texstudio#2558]
Tabularray package .cwl file not working 

Environment
- TeXstudio: version 4.3.1
- Qt: qt6
- OS: Windows 10
- TeX distribution: texlive

As for the other packages .cwl work so is expected and for Tabularray package.

Actual behavior
Tabularray .cwl not working, no commands pop up window is open for this package

Just create a Tabularray environment: \begin{tblr}{options} commands \end{tblr} and try to pass some options in the "options" brackets.

**Comment by sunderme** [comment]
I assume it is similar to #2310
If that is not the case, open a new issue with a clear example (text file!) what is not working. (whatever "some options" are in this context)
