### ISSUE TITLE
Why not support MacOS Mojave any more?

### ISSUE THREAD

**Issue by TopologyApplied** [texstudio-org/texstudio#2565]
When openning with texstudio-4.3.1-osx.dmg, get an error:
"You have macOS 10.14.6. The application requires macOS 10.15 or later."

MacOS Mojave is fast and stable, why TexStudio not support MacOS Mojave any more? 
Is there anyway to walk around the version restriction?

**Comment by sunderme** [comment]
txs uses the toolchain from github which is OS-X 11 which also sets the lower version limit for txs.
