### ISSUE TITLE
notepad

### ISSUE THREAD

**Issue by gooly** [texstudio-org/texstudio#2566]
### Describe the feature and the current behavior/state
I would like to have a kind of notepad, on which I could e.g. enter a ToDo list or enter and organize side thoughts. It should be independent of the current text window, like a window floating above the TexStudio.

### Who will benefit with this feature?
Anybody elaborating a more complex text ..

### Any Other info
Great program!

**Comment by sunderme** [comment]
you can split the editor and open your notes in the second part (open two documents, right click on tab title -> move to other view)
That is about all I can offer. If it really should float above, a second program (notes, etc.) is the simpler solution.

**Comment by gooly** [comment]
Thanks - didn't have such a simple idea - great!
