### ISSUE TITLE
user defined fall down menu

### ISSUE THREAD

**Issue by gooly** [texstudio-org/texstudio#2567]
### Describe the feature and the current behavior/state
I would like to be able to enter my own latex commands in an extra fall down menu - maybe with comment. There are so many latex commands and often you need a few unusual ones over and over again, for those this would be.

### Who will benefit with this feature?
Anybody working on a not so common text.

**Comment by sunderme** [comment]
you can change the menu entries in tools, latex and math.
<img width="1011" alt="grafik" src="https://user-images.githubusercontent.com/14033169/188278633-c3c9972c-d8f0-4bd3-bac5-c5e8967c0b75.png">
You can also define entries in a user toolbar. 
That should suffice.

**Comment by gooly** [comment]
Thanks - didn't know and didn't expect this - great!
