### ISSUE TITLE
[Regression] TexStudio Ignores Custom Build & View Pipeline

### ISSUE THREAD

**Issue by randolf-scholz** [texstudio-org/texstudio#2571]
I am not sure when this started happening, and I didn't notice it immediately, but for some reason `TexStudio` has started to ignore my build & view pipeline. It will always perform the default build & view pipeline instead.

### Environment
- OS: Ubuntu 22.04
- TeXstudio:Tested with both Ubuntu shipped 4.2.1 and 4.3.1 provided by sunderme ppa.
- TeX distribution: texlive

### How to reproduce

Add a random user command like `echo "TEST"` and change the Build & View pipeline to this command. TexStudio will still perform the default pipeline.

**Comment by sunderme** [comment]
Before i need to start guessing again, please provide profile file with all the tools set up (including the echo command) and how do you execute build&view.

**Comment by randolf-scholz** [comment]
@sunderme I can reproduce it after restoring to default settings. I attached this example profile. I also attached my regular profile, which has a bunch of macros. I use the build & view to hide all compiled files in a `__tex__` folder.

Usually I use F1 / F5 to execute Build & View, sometimes the double green arrow button.

[echo_test.txt](https://github.com/texstudio-org/texstudio/files/9496732/echo_test.txt)
[texstudio.txt](https://github.com/texstudio-org/texstudio/files/9496733/texstudio.txt)

**Comment by sunderme** [comment]
Macros are stored as files extra.

**Comment by sunderme** [comment]
looks like it works when you use normal naming. Probably I have to restrict the naming options.

<img width="1346" alt="grafik" src="https://user-images.githubusercontent.com/14033169/188697748-7befe69c-9f64-48eb-b02d-a735dcea6182.png">

**Comment by sunderme** [comment]
it works also with  echo_test as name but after I set it that way.

**Comment by randolf-scholz** [comment]
Although, it seems that's still a bug since, according to the documentation

> `% !TeX program = pdflatex`
>
> Defines the compiler to be used for the document. To be precise, it overrides the default compiler (command txs:///compile) which is used in the actions "Build & View" as well as "Compile". Valid options are "latex","pdflatex","xelatex","lualatex" and "usern" (e.g. user0 as user defined command 0)

**Comment by sunderme** [comment]
can you open a new issue report with the correct error description ?

**Comment by randolf-scholz** [comment]
Sure.

**Comment by randolf-scholz** [comment]
New Issue opened here https://github.com/texstudio-org/texstudio/issues/2573
