### ISSUE TITLE
& in tabular environment wrongly marked as syntax error

### ISSUE THREAD

**Issue by immanuelplattner** [texstudio-org/texstudio#2575]
### Environment
- TeXstudio: 4.3.1
- Qt: 6.3.1
- OS: Windows 10
- TeX distribution: texlive full 2022

### LaTeX code

```latex
\documentclass{article}
\usepackage[a4paper, landscape, margin=2cm]{geometry}
\usepackage[utf8]{inputenc}
\usepackage{graphicx}

\begin{document}
	\resizebox{\textwidth}{!}{%
		\begin{tabular}{|l|l|l|l|l|l|l|l|}\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
			1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\\hline
		\end{tabular}%
	}
\end{document}
```

### Error

![_wrong_marked](https://user-images.githubusercontent.com/50355397/188944977-5fc55d85-e665-4d04-a44b-6e7fbdf8b899.png)

In the image above you can see that the table column delimiters `&` in the last 3 table rows (starting a code line 39) are highlighted as syntax errors. If I move the cursor above them I get the message "more colsin tabular than specified". The code compiles fine and the generated PDF shows what you expect to see. If I remove the `\resizebox{\textwidth}{!}{%` on line 7 and the corresponing `}` on line 43, the syntax error markings disappear as they should. It's very interesting, that the error occurs after exactly 30 table lines.

**Comment by sunderme** [comment]
it is a fallback mechanism to avoid extensive failing syntax checks in unclosed environments.
The limit is set to 30 lines.
You can increase the limit in texstudio.ini by setting
`Editor\RUNAWAYLIMIT=50`  (50 or higher)

**Comment by sunderme** [comment]
I consider this answered.
