### ISSUE TITLE
Latest version of TexStudio cannot now find the bst file

### ISSUE THREAD

**Issue by pirlite2** [texstudio-org/texstudio#2577]
### Environment
- TeXstudio:4.3.1
- Qt: 5.12.8
- OS: Linux Mint 20.3
- TeX distribution: texlive 2020

### Description
I have been working without any problems on a Latex document. I have just upgraded to the latest version of TexStudio but now the file will not build - it complains that it cannot (now!) find the bst file that is installed in exactly the same place in the texlive tree. It was all working fine before I upgraded TexStudio - I have not changed anything to do with texlive. What has happened to mean that the bst file cannot now be found? Is there some change in the configuration of the new version of TexStudio?

FWIW:  if I run pdflatex + bibtex + pdflatex twice in a shell, the PDF builds properly, so I do not think this problem is anything to do with my texlive. Similarly, if I copy the bst file into the same directory as the tex file, it all works again from inside TexStudio.

I have never had this problem with upgrading versions of TexStudio before.

Peter

**Comment by sunderme** [comment]
Please provide an example (files) which demonstrate the issue. I am not guessing how the project is set up.

**Comment by pirlite2** [comment]
Herewith an MWE based on an edited down version of the IEEE Transactions template example. Note that I have had to rename the tex file as 'txt' because github does seem to allow the upload of tex files. I have also had to hack the extension for the minimal bib file for the same reason.

I also include two log files: the one named "New..." is what is generated by building _within_ TexStudio; this build fails by not resolving the references.  The second log file "shell-New..." is what results from successfully building the pdf from the shell by invoking pdltatex, bibtex, and pdflatex twice more. Running these two log files through diff shows differences starting around 359 indicating some issues with the two references. Maybe somebody with a deeper understanding of Latex can spot what is going wrong from the log files?

As I have pointed out, simply copying the IEEEtran.bst file into the directory allows TexStudio to work properly... but this is not very elegant since it already exists in the default texlive tree (which, of course, is why I can build from the shell!).

Many thanks,
P.

[New_IEEEtran_how-to.txt](https://github.com/texstudio-org/texstudio/files/9533439/New_IEEEtran_how-to.txt)
[New_IEEEtran_how-to.log](https://github.com/texstudio-org/texstudio/files/9533441/New_IEEEtran_how-to.log)
[shell-New_IEEEtran_how-to.log](https://github.com/texstudio-org/texstudio/files/9533520/shell-New_IEEEtran_how-to.log)
[test.bib.txt](https://github.com/texstudio-org/texstudio/files/9533524/test.bib.txt)

**Comment by TimoHocker** [comment]
I'm having a similar issue here. ([example](https://github.com/TimoHocker/latexstudio_test))
compiling works fine, but when I click on sub2 in the file tree it tries to find it in `/sub2` instead of `/sub1/sub2`

**Comment by sunderme** [comment]
> I'm having a similar issue here. ([example](https://github.com/TimoHocker/latexstudio_test)) compiling works fine, but when I click on sub2 in the file tree it tries to find it in `/sub2` instead of `/sub1/sub2`

this is something completely different. subimport is not supported completely. 
**Please** don't mix issues !

**Comment by sunderme** [comment]
works here.
the important point is why bibtex does not find the bib and there I can only speculate. The issue is tex set-up.

**Comment by pirlite2** [comment]
> works here. the important point is why bibtex does not find the bib and there I can only speculate. The issue is tex set-up.

Is bibtex failing to find the bib file (which is in the same directory) or is it failing to find the bst file? I am not clear from the log files. When I copy the bst file into the same directory, it works, which suggests the issue lies solely with finding the bst file.

I am not so sure about the "it's a tex issue" explanation. I suppose it is possible that my tex installation threw  some strange aberration at just the same time as I upgraded to v4.3.1 of TexStudio - stranger things happen at sea! But all the evidence seems to point at something has gone wrong with my TexStudio configuration. (In my experience, things can sometimes reconfigure themselves spontaneously on Linux.) In particular:

1. I was halfway through writing the paper when I upgraded to v4.3.1. It all worked fine up to that point.
2. After the upgrade, it all went wrong
3. I can still build the pdf from the shell, which implies that my texlive is still working properly. (I posted the log file from this build previously.)

I'll continue to work on this because it is a nuisance.

Are there any paths (which might apply) to bst files set anywhere in TexStudio's many options?

P.

**Comment by pirlite2** [comment]
FWIW: I had a look at the aux and blg files that result from building TexStudio:

The .aux file is:
```
\relax 
\citation{Karpatne2017}
\citation{Kraft1994}
\bibstyle{IEEEtran}
\bibdata{test}
\@writefile{toc}{\contentsline {section}{\numberline {I}Introduction}{1}{}\protected@file@percent }
\gdef \@abspage@last{1}
```

The .blg file starts with:
```
This is BibTeX, Version 0.99d (TeX Live 2019/Debian)
Capacity: max_strings=200000, hash_size=200000, hash_prime=170003
The top-level auxiliary file: New_IEEEtran_how-to.aux
I couldn't open style file IEEEtran.bst
---line 4 of file New_IEEEtran_how-to.aux
 : \bibstyle{IEEEtran
 :                   }
I'm skipping whatever remains of this command
I found no style file---while reading file New_IEEEtran_how-to.aux
```
So all of this inclines me to think the problem is with the bst file, not with finding the bib file.

Also, `kpsewhich IEEEtran.bst` reports:

`/usr/local/texlive/2020/texmf-dist/bibtex/bst/IEEEtran/IEEEtran.bst`

which looks right to me?

P.

**Comment by sunderme** [comment]
from the log "BibTeX, Version 0.99d (TeX Live 2019/Debian)" is not texlive 2020. I assume txs calls the wrong bibtex. That is usally a path issue (desktop commands see different path, .bashrc is not called)

**Comment by pirlite2** [comment]
Ah! Great spot! In fact, thinking back I have a similar problem before...

After investigation, it seems that the 2019 version of texlive, which comes in  the Ubuntu repo, has become installed. This has happened before where a package has added a dependence on latex which usually results in an update of the package trying to install the repo version of texlive. I have absolutely definitely not installed the repo version of texlive myself because I know having two simultaneous versions causes problems. But this has clearly sneaked past me at some point. Curious that the problem manifested itself at the same time as I updated TextStudio... unless TexStudio itself is the culprit? Does TexStudio have a dependency on the repo version of texlive? I updated from the ppa. I can see that the TexStudio ppa "recommends" textlive, which if I understand correctly, will be the repo version. Does "recommend" mean "will install it whether you want it or not"?

I have removed the repo texlive and it all works as expected :-)

P.

**Comment by sunderme** [comment]
deb package of txs recommends texlive. Some package manager install texlive then automatically.

**Comment by pirlite2** [comment]
"Some package manager install texlive then automatically."

Well maybe that's what has been happening? The timing of my problems seems too much of a coincidence...

I think I can guard against the problem by adding the _full path_ to all of the texlive components I actually want as opposed to ones that the OS foists upon me silently. In fact, maybe adding a path to the texlive tools you actually want would be a good addition to TexStudio? I can't help thinking that the current state of affairs where an external agent can break a program is not great software engineering - for example, IDEs usually have a path to the development toolchain.

Many thanks for you help in unraveling this.

Peter

**Comment by pirlite2** [comment]
Looking at the texlive source code, I realised that this is installed in /usr/bin by default, and not on the /usr/local/texlive path that the TexLive installer puts it on by default. (Unclear why the texlive installer does this.) So the simple solution would therefore seem to be to install the up-to-date version of texlive on /usr/bin. That way, any package update would not try to install the older repo version of texlive (in /usr/bin).  Will try this...

**Comment by sunderme** [comment]
/usr/local is normally used for user installed programs whereas /usr/bin is rather used by the package managers.
So, just be sure that you don't overwrite managed files...
