### ISSUE TITLE
Math symbols in the left pane are not displayed correctly

### ISSUE THREAD

**Issue by nik0380** [texstudio-org/texstudio#2579]
### Environment
- TeXstudio: 4.3.1 (git n/a)
- Qt: Using Qt Version 5.15.2, compiled with Qt 5.15.2 R
- OS:  Linux (Fedora 35 + KDE)
- TeX distribution: texlive

I installed the program from the official repository (Fedora Linux). In general, the program works excellently. However, the math symbols in the left pane are not displayed correctly (See screen shot). How can this be fixed?

![изображение](https://user-images.githubusercontent.com/63895207/189849336-1b269036-e517-4e6a-ab81-a69d0cd3c9b9.png)

**Comment by sunderme** [comment]
no idea where that is coming from.
Please try:
1) use txs appimage (https://github.com/texstudio-org/texstudio/releases/download/4.3.1/texstudio-4.3.1-x86_64.AppImage)
2) try to compile locally. My guess is that the qt5 svg package is missing/faulty.

**Comment by nik0380** [comment]
Hi!
A very strange situation. On another computer with the same system, everything works fine. Reinstalling qt5-qtsvg and **TexStudio** does nothing. The App image works well. Thanks for the help!

**Comment by sunderme** [comment]
So, we can close it as it is not a general txs issue?

**Comment by nik0380** [comment]
Hi!
If there are no more ideas, then the question can be closed. On the other hand, I would like to understand the reasons. As far as I know, I'm not the only one with this problem. What font is used to generate math symbol icons in TexStudio? Can it be changed in settings? Is icon caching used in local folders? Thank you very much for your help!

**Comment by sunderme** [comment]
txs presents svg/png graphics in the symbol pane. All of them are part of the binary.

**Comment by nik0380** [comment]
Hi!
Images are generated at the stage of assembling a binary file. It's right? In this case, one would assume that the problem is in the rpm-package. However, a similar package installed on the same system works correctly. Tried to compile TexStudio from sources, got the same problems.
What mechanism was used to generate the images? Where can I find it in the source?

**Comment by sunderme** [comment]
symbols-ng/

**Comment by nik0380** [comment]
Hi!
Found an interesting detail. In file _img058greek.svg_, the value **&#13319;** is given as the character code (unicode), which just corresponds to the displayed hieroglyph. Probably, qt displays not a glyph, but a unicode character. Perhaps it makes sense to update the **svg**- files, because for example, **inkscape** also displays them incorrectly.
