### ISSUE TITLE
Outline-pane font sizes change occassionally, if title becomes too wide for pane.

### ISSUE THREAD

**Issue by kbauer** [texstudio-org/texstudio#258]
### Environment
- TeXstudio: 2.12.10
- Qt: Using Qt Version 5.8.0, compiled with Qt 5.8.0 R
- OS: Windows 10 (Microsoft Windows [Version 10.0.17134.167] "April Update" (2018))
- TeX distribution: MikTeX

### Description
I am occassionally seeing font sizes in the outline pane become inconsistent for titles, that are too wide to fit into the pane.
![image](https://user-images.githubusercontent.com/7498468/43320310-5ea02ddc-91a8-11e8-8b7c-631fc0dd08ed.png)

The behaviour is inconsistent though, and while it looked reproducible at first, after a while it wasn't anymore. 
![image](https://user-images.githubusercontent.com/7498468/43320373-90f5dd04-91a8-11e8-85bd-3d94ad8dd564.png)

I have been seeing this behaviour several times over the last days, noticing it ever since I started using a monospaces font for the UI, and editorial `\TODO` and `\DONE` prefices for section titles.

It may have been triggered to recent changes of the system-wide scaling options, but I *think* that the issue was present even before that.

**Comment by timhoffm** [comment]
Do you use a multi-monitor setup with different scalings?

**Comment by kbauer** [comment]
@timhoffm No, all monitors use the same scaling. 

Anyway, I have no way of reproducing it meaningfully right now and it is possible, that I am mistaken about it occurring before messing with the magnification settings. It is possible it was a one-time thing due to such changes.

If it's fine by you, I'll close the issue until I can reproduce it.
