### ISSUE TITLE
on click

### ISSUE THREAD

**Issue by parpamgr** [texstudio-org/texstudio#2587]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior
on internal pdf viewer:
on click (mouse) do nothing

### Actual behavior
on click goes next page, right click goes to previous pages
No means to disable this behavior !!!
### How to reproduce
simply click on a page of the internal pdf viewer

**Comment by octaeder** [comment]
While using the internal (build-in) windowed pdf viewer (s. _3.3 Internal pdf viewer_ in the [manual](https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html)), this is intended behavior, when you are in presentation mode (Presentation option in menu View, or key F5).

**Comment by sunderme** [comment]
I assume, this is answered ?
