### ISSUE TITLE
"Build & View" (F5) and "Compile" (F6) treat magic comments inconsistently

### ISSUE THREAD

**Issue by schtandard** [texstudio-org/texstudio#2588]
### Environment
- TeXstudio: 4.3.1
- Qt: 6.3.1
- OS: Windows 11
- TeX distribution: TeX Live 2022

### Description
When both the `program` magic comment and the `TXS-program:compile` one are given, e.g.
```latex
% !TeX program = pdflatex
% !TeX TXS-program:compile = txs:///pdflatex/[-shell-escape]
```
one of them should take precedence, as they may conflict. Why would both of them be used? I use `program` in all of my documents, as it is understood by many editors and there is a high chance it will work for others typesetting my document. When I need `-shell-escape`, I additionally use `TXS-program:compile`, as `program` does not support setting that flag. Thus, others will still get the benefit of `program` even if they don't use TeXstudio and they will only have to enable `-shell-escape` manually.

Since the functionality of `TXS-program:compile` is a superset of that of `program`, it seems natural to me that the former should override the latter, which is indeed what happens when pressing the "Compile" button (or F6). However, when using "Build & View" (F5), which should be the same as compiling (F6) and then viewing (F7), it is the other way around; only `program` is adhered to.

Both commands should behave the same way. Either with the current behavior of "Compile" (`TXS-program:compile` taking precedence) or by order of the magic comments in the source (last one takes precedence).

### How to reproduce
Compile the following MWE both with "Build & View" (result: Restricted shell escape) and with "Compile" (result: Unrestricted shell escape).
```latex
% !TeX program = pdflatex
% !TeX TXS-program:compile = txs:///pdflatex/[-shell-escape]
\documentclass{article}

\usepackage{pdftexcmds}

\begin{document}

\makeatletter
\ifcase\pdf@shellescape
  No shell escape\or
  Unrestricted shell escape\or
  Restricted shell escape\fi
\makeatother

\end{document}
```

**Comment by sunderme** [comment]
duplicate #2573
