### ISSUE TITLE
Labels in bibliography files

### ISSUE THREAD

**Issue by barry-dowdeswell** [texstudio-org/texstudio#259]
### Environment
- TeXstudio: versions after 2.10.8
- Qt: 5.5.1
- OS:  Windows 7, Windows 10
- TeX distribution: texlive, 

### Expected behavior
I use commands like \label{A} in my bibliography .bib files in texStudio. 

### Actual behavior
In version 2.10.8 and previous, those labels show in the left Structure pane when I have the bibfile open for editing. They make it very useful for navigation when building the bibliography of large documents.

### How to reproduce
In later versions, the labels show fine for .tex files but not for .bib files.

**Comment by sunderme** [comment]
\label does not have any useful meaning in the bib-file, does it ?

**Comment by sunderme** [comment]
you could change the syntax highlighting to latex (view/highlighting) but then bibtex is not supported.
I don't really see this use case as meaningful, so won't fix

**Comment by barry-dowdeswell** [comment]
Hi sunderme,
When you say "so won't fix" I am sorry, I do not understand what you mean. This worked in version 2.10.8. Are you saying that this was deprecated?

**Comment by sunderme** [comment]
yes

**Comment by barry-dowdeswell** [comment]
Thank you for looking into this. I appreciate your time. texStudio is awesome.
