### ISSUE TITLE
autocompletion for \usepackage{lipsum} not working

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2594]
In general it works, for ex. with amsmath, but not with lipsum.

### Environment
- TeXstudio: latest 4.3.1
- Qt: 6
- OS: Win10
- TeX distribution: miktex

### Actual behavior
![grafik](https://user-images.githubusercontent.com/102688820/190931709-8caad9b2-ca89-4146-a2a6-c983fec06f41.png)

Even with tab "all" lipsum is not found, and after typing:

![grafik](https://user-images.githubusercontent.com/102688820/190931803-15716854-30de-4dea-bb3a-2a890382a659.png)

Document compiled and the log says ...\AppData\Local\Programs\MiKTeX 2.9\tex/latex/lipsum\lipsum.sty

### How to reproduce
Hope you can do so.

**Comment by sunderme** [comment]
is the package visible in kpsewhich lipsum.sty ?

**Comment by octaeder** [comment]
yes, this command shows exactly the path given above.

**Comment by octaeder** [comment]
miktex downloaded and installed this package automatically while compiling.

I found in the manifest:
[lipsum]
copyrightOwner=Patrick Happel
copyrightYear=2014-2019
creator=mpc
ctanPath=/macros/latex/contrib/lipsum
description[]=This package gives you easy access to 150 paragraphs of the Lorem Ipsum dummy text provided by https://lipsum.com, plus a growing list of other dummy texts in different languages.
digest=bc039e330a95e7681f0ecb7260feceff
displayName=lipsum
licenseType=lppl1.3
run[]=texmf/tex/latex/lipsum/cicero.ltd.tex
run[]=texmf/tex/latex/lipsum/lipsum-cs.ltd.tex
run[]=texmf/tex/latex/lipsum/lipsum.ltd.tex
run[]=texmf/tex/latex/lipsum/lipsum.sty
run[]=texmf/tpm/packages/lipsum.tpm
runSize=353907
timePackaged=1633291873
title=Easy access to the Lorem Ipsum and other dummy texts
version=2.7

[lipsum__doc]
copyrightOwner=Patrick Happel
copyrightYear=2014-2019
creator=mpc
ctanPath=/macros/latex/contrib/lipsum
description[]=This package gives you easy access to 150 paragraphs of the Lorem Ipsum dummy text provided by https://lipsum.com, plus a growing list of other dummy texts in different languages.
digest=e19550812424c9acce5e7c59ce8ec06f
displayName=lipsum__doc
doc[]=texmf/doc/latex/lipsum/DEPENDS.txt
doc[]=texmf/doc/latex/lipsum/lipsum-cicero.txt
doc[]=texmf/doc/latex/lipsum/lipsum-cs.txt
doc[]=texmf/doc/latex/lipsum/lipsum-la.txt
doc[]=texmf/doc/latex/lipsum/lipsum.pdf
doc[]=texmf/doc/latex/lipsum/README.md
doc[]=texmf/doc/latex/lipsum/README.txt
docSize=979598
licenseType=lppl1.3
run[]=texmf/tpm/packages/lipsum__doc.tpm
runSize=1254
timePackaged=1633291873
title=Easy access to the Lorem Ipsum and other dummy texts
version=2.7

[lipsum__source]
copyrightOwner=Patrick Happel
copyrightYear=2014-2019
creator=mpc
ctanPath=/macros/latex/contrib/lipsum
description[]=This package gives you easy access to 150 paragraphs of the Lorem Ipsum dummy text provided by https://lipsum.com, plus a growing list of other dummy texts in different languages.
digest=6467445ce445c58cdd13f304fe674af1
displayName=lipsum__source
licenseType=lppl1.3
run[]=texmf/tpm/packages/lipsum__source.tpm
runSize=1112
source[]=texmf/source/lipsum/CHANGELOG.md
source[]=texmf/source/lipsum/lipsum.dtx
source[]=texmf/source/lipsum/lipsum.ins
sourceSize=64671
timePackaged=1633291873
title=Easy access to the Lorem Ipsum and other dummy texts
version=2.7

**Comment by sunderme** [comment]
then a debugger run on your side should answer the question.
The final result should end in packageCache.dat (where texstudio.ini is located)

**Comment by octaeder** [comment]
miktexPackageNames.dat and packageCache.dat don't contain the word lipsum.

**Comment by octaeder** [comment]
Quite random, miktex (right) says package is not installed, but the LaTeX log (left) says that it's there:

![grafik](https://user-images.githubusercontent.com/102688820/191320925-d2a5eae8-18a6-4622-936b-0c083e20cdbd.png)
