### ISSUE TITLE
4.3.1 build crashs on OSX 10.15.7

### ISSUE THREAD

**Issue by philectro** [texstudio-org/texstudio#2604]
### Environment
- TeXstudio: 4.3.1
- Qt: i can't, it don't run anymore
- OS: Mac OSX 10.15.7
- TeX distribution: texlive 2021

### Expected behavior
run

### Actual behavior
nothing appears

### How to reproduce
install official release 4.3.1 on osx 10.15.7 on a old mac with unsupported OS 11

It worked on 4.2.3

**Comment by sunderme** [comment]
only osx 11+ is supported with txs 4.3+. see webpage (texstudio.org)
