### ISSUE TITLE
Add additional dictionary path to the settings dialog.

### ISSUE THREAD

**Issue by hannes101** [texstudio-org/texstudio#2605]
Currently the path for spell check dictionaries is by default set to "/usr/share/myspell;[txs-settings-dir]/dictionaries". In recent fedora version the hunspell path changed from /usr/share/myspell to /usr/share/hunspell/. 
https://fedoraproject.org/wiki/Changes/Hunspell_dictionary_dir_change
Would it be possible to also add that path to the default settings on linux?

![image](https://user-images.githubusercontent.com/11256578/191831198-46d39b09-3e51-4ef9-b493-16e092f65ca7.png)

### Who will benefit with this feature?
Linux users would be able to directly have their spell-checking dictionaries recognised.

### Any Other info
I could probably also write a patch for configmanager.cpp, where I think the current default settings are set, but I thought it might be something, which could also be adressed upstream.

Thanks a lot
johannes

Please see upstream bug report for fedora 36: https://bugzilla.redhat.com/show_bug.cgi?id=2128670

**Comment by sunderme** [comment]
fallback paths are 
```fallBackPaths << PREFIX"/share/hunspell" << PREFIX"/share/myspell"
                          << "/usr/share/hunspell" << "/usr/share/myspell"
                          << parseDir("[txs-app-dir]/../share/texstudio") ;```
Should be fine. Fedora tends to patch txs, so no idea if they have changed this.

**Comment by hannes101** [comment]
There is no patch changing any of these settings. And I don't understand why "/usr/share/hunspell" is not added, if it's supposed to be added as a fallback? Or how is the hierarchy in this case? Sorry no real big c++ experience.

**Comment by hannes101** [comment]
Ok, nevermind, apparently it's caused by an upgrade from an older fedora version with an older texstudio settings file. So there's nothing wrong.
