### ISSUE TITLE
Cutting relatively large amount of text takes a few seconds

### ISSUE THREAD

**Issue by jzniu** [texstudio-org/texstudio#2613]
Whenever I try to cut a relatively large amount of text in a document, it may take quite a few seconds for texstudio to complete the action. Usually in an editor, this gets done instantly.

### Environment
- TeXstudio: 4.2.1 (having the same issue before this version I believe)
- Qt: 5.15.2
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior

The cut operation should complete instantly.

### Actual behavior

For a few seconds, texstudio freezes and doesn't respond to any further interaction.

### How to reproduce

Just select a large amount of text, 20 lines or more perhaps, and Ctrl+X to cut.

**Comment by octaeder** [comment]
I tried to reproduce in the following way. Enter following code in txs in a new document and build a pdf with pdflatex.

\documentclass{article}
\usepackage{lipsum}
\begin{document}
\lipsum[1-20]
\end{document}

View it with an external viewer (Acrobat DC). Select the output in the pdf and copy paste it in the document (more than 170 lines). No problem. Select the first 50 lines and cut it with Ctrl+X, no problem. Paste it at the end of the document. No problem.

I used my build from the latest git sources available:
Windows 10 pro, miktex
TeXstudio 4.4.0 (git 4.3.1-98-g8670cf306)
Using Qt Version 6.3.0, compiled with Qt 6.3.0 R

Maybe it is some option? You may try what I did with your version with default options. For this end txs, goto %appdata% (i.e. ...\AppData\Roaming) and rename the folder texstudio, then start txs. After ending txs you can revert the renaming.
You may do the same test with latest portable version (4.3.1 and Qt6) from the [TeXstudio web-page](https://www.texstudio.org/#download).

**Comment by jzniu** [comment]
I meant cutting text in the editing panel, not the generated PDF document.

Also to clarify, this issue happens with a large .tex document, 14+K lines. I just tested with small files, which have no this issue. So the issue seems to be related to both the size of the entire .tex file and the size of selected text to cut.

**Comment by octaeder** [comment]
I used the pdf to create a document with many (appr. 180) lines. As I said I then cut 50 lines in the editor and inserted them somewhere else. Anyway, now that we know what relatively large means, I created one document with roughly 14,600 lines (pasted five of the largest includes of a document into the editor: 6,000+3,600+2,000+1,400+1,600). Then I cut almost everything and txs is off for some minutes. Undo works immediately. Cutting 100 lines takes some seconds, cutting 1,000 lines about 15s. When I close the left panel showing the document structure (I think this prevents the structure from being updated) cutting 1,000 lines takes 1s, and cutting all lines takes about 5s. Instead of closing the side panel you can switch to the Bookmarks view with the same effect. Maybe @sunderm can tell if the problem can be fixed.

**Comment by octaeder** [comment]
btw. here I couldn't observe your problem #2614:

![image](https://user-images.githubusercontent.com/102688820/193168460-01101558-2fc7-4c66-b18c-1ae3106e0f9a.png)

**Comment by jzniu** [comment]
> I used the pdf to create a tex document with many (appr. 180) lines. As I said I then cut 50 lines in the editor and inserted them somewhere else. Anyway, now that we know what relatively large means, I created one document with roughly 14,600 lines (pasted five of the largest includes of a document into the editor: 6,000+3,600+2,000+1,400+1,600). Then I cut almost everything and txs is off for some minutes. Undo works immediately. Cutting 100 lines takes some seconds, cutting 1,000 lines about 15s. When I close the left panel showing the document structure (I think this prevents the structure from being updated) cutting 1,000 lines takes 1s, and cutting all lines takes about 5s. Instead of closing the side panel you can switch to the Bookmarks view with the same effect. Maybe @sunderm can tell if the problem can be fixed.

I originally thought this is related only to the amount of selected text, but obviously the size of the document is also relevant. And yes, I guess some sort of parsing is involved causing the issue.

**Comment by sunderme** [comment]
fix with 6b650baf877458a858216eb07b162e3d4ead5f14 and previous
