### ISSUE TITLE
can't input Chinese characters

### ISSUE THREAD

**Issue by shx2pi** [texstudio-org/texstudio#2624]
### Environment
- TeXstudio: texstudio-4.3.1-x86_64.AppImage
- Qt: 使用 Qt 5.9.5，由 Qt 5.9.5 R 构建
- OS: Linux (Debian 11.4), 桌面环境xfce
- TeX distribution: texlive 20220331

### Expected behavior
切换到中文输入法，应该出现中文输入法候选框，但是没有弹出

### Actual behavior

在汉语模式下，也显示的是英文字母

### How to reproduce
安装搜狗输入法Linux版，并设置为当前输入法，切换到汉语输入模式，不能输入汉字

**Comment by muzimuzhi** [comment]
> ### Environment
> * TeXstudio:
> * Qt:
> * OS:

Please complete the these fields.

**Comment by reckel-jm** [comment]
This problem can occur when using `fcitx4` and is most likely not a problem of TeXStudio. Try an other Chinese input method or update to `fcitx5`.

**Comment by sunderme** [comment]
no feedback
