### ISSUE TITLE
keyboard shortcut Save All not work

### ISSUE THREAD

**Issue by Michele-Cagno** [texstudio-org/texstudio#2628]
### Environment
- TeXstudio: 4.31
- Qt: 6.3.1
- OS: Windows 10
- TeX distribution: 

### Expected behavior
save all open files

### Actual behavior
not work shortcut

### How to reproduce
press ctrl-shift-S

**Comment by sunderme** [comment]
fixed with 1e3441e352c9c2dbd6a59d066ec9b11b58dd0fdc
apparently there are few conflicting shortcuts in txs.
