### ISSUE TITLE
For pdf-viewer move/add "Fit to Text Width"

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2629]
### Current behavior:
While using pdf-viewer I couldn't remember the number n in the shortcut Ctrl-n for "Fit to Window". So I looked at the toolbar and counted icons from left to right:
![grafik](https://user-images.githubusercontent.com/102688820/194734333-d54b1510-71ef-4446-9547-31aae51f34b8.png)

So I assumed n=4, but actually Ctrl+4 is "Fit to Text Width" as can be seen from the view menu:
![grafik](https://user-images.githubusercontent.com/102688820/194734370-06060714-3f3e-43a3-ab3f-efdccc458e43.png)

Thus I would like to interchange the two entries in the menu and the two icons in the toolbar for actions "Fit to Window" and "Fit to Text Width". This would give consistent ordering with respect to shortcuts and avoids changing shortcuts.

Additionally the context menu of the pdf doesn't show action "Fit To Text Width" at all:
![grafik](https://user-images.githubusercontent.com/102688820/194734526-9690c57a-581d-4a76-b70c-5cf84f094153.png)

### Expected (images from a change I can provide as PR):
![grafik](https://user-images.githubusercontent.com/102688820/194734601-5b9cc928-c273-49e5-91e2-1efbb3628ac8.png) ___ ![grafik](https://user-images.githubusercontent.com/102688820/194734621-508c3461-9522-49d6-82d1-81337d2c30d2.png) ___ ![grafik](https://user-images.githubusercontent.com/102688820/194734646-91d2a769-4e6a-4d2e-b65d-60dfe58ae7f4.png)

**Comment by sunderme** [comment]
don't change the order of the menu.
You can adapt the shortcuts if you deem it indispensable.

**Comment by octaeder** [comment]
you are not talking about the missing "Fit to Text Width" in the context menu (3rd image). Not add it? (then of course in original order of the view menu I suppose)
you always have good reasons. can you let me know why not interchange these two items?

**Comment by sunderme** [comment]
1) the order seems logical as is, the two width variants next to each other. Splitting it looks odd. (and changing menu position will challenge muscle memory if anyone is using it)
2) nobody has missed the option in the context menu. Unless you intend to use it, changes for a user base of 0 is a waste of time.
You can question if these options need to be in the context menu at all as they are more easily available in the toolbar, but there is no need to change that either.

**Comment by octaeder** [comment]
ad 1) For me "text width" entry looks like a foreign body, as something that has been added at a later time: Ctrl-1, Ctrl-2 and Ctrl-3 had already been in use, so one had to accept the disordering of the shortcuts (if one follows your ordering logic of the items). My "logic" would be to keep those items/icons together which use page dimensions (fit to width, fit to height and width). On the one hand I wouldn't change this in any case, if the shortcuts would be in increasing order. On the other hand I believe changing shortcuts to get increasing order is not a good idea, because many people already know them. So my proposition could be a way out. Since all options offer key accelerators/mnemonics (A, D, T, and W) no one (or muscle) needs to remember exact positions.

ad 2) In times of increasing screen sizes up to 49'' moving the cursor around becomes a more and more tedious work. This can be simplified with the context menu. Gimp even offers the full menu as a context menu. The reason why nobody misses "fit to text width" in the context menu could be that no one uses this option or they do not use the context menu at all. I don't know.

**Comment by sunderme** [comment]
anyway, the change is *very* cosmetic and philosophical as there is no real benefit in making txs better.
I would prefer to tackle more impactful changes ...
