### ISSUE TITLE
Result of "find usage" (Label Search) offers no checkboxes

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2630]
### Current:
In case of Label Search txs doesn't offer checkboxes:

![grafik](https://user-images.githubusercontent.com/102688820/194150615-e0634a6b-6cde-4511-a771-d1eacd098006.png)
Same issue can be seen in an image in the (new) [manual](https://texstudio-org.github.io/editing.html#finding-reference-use). The manual says that I can select/deselect the found occurrences before applying "Replace all". But this is not the case.

### Expected
Checkboxes should be available as it is is with a normal text search/replace (s. [here](https://texstudio-org.github.io/editing.html#extended-search)).

**Comment by sunderme** [comment]
fixed manual to match implementation
