### ISSUE TITLE
Macro trigger and shortcut in configuration window

### ISSUE THREAD

**Issue by hermis128** [texstudio-org/texstudio#2635]
### Describe the feature and the current behavior/state
feature: I want the trigger and shortcut of each macro to be displayed in the 'Edit Macros' window. I added a desired revision of the Edit Window.

### Who will benefit with this feature?
Those who heavily rely on the macros for editing. The feature will help organize and edit the macro efficiently. Thank you.
![edit_macros_current](https://user-images.githubusercontent.com/33988694/195370661-8cb9d0ba-6253-4bb4-80a0-ee18ebcc2baf.png)
![edit_macros_feature](https://user-images.githubusercontent.com/33988694/195370668-bf5ac6b4-d685-4a4c-b1fa-69e744c6a679.png)

**Comment by sunderme** [comment]
done
