### ISSUE TITLE
New Icons & Icon Themes

### ISSUE THREAD

**Issue by geolta** [texstudio-org/texstudio#2637]
### Environment
- TeXstudio: 4.3.1
- Qt: 5.15.6
- OS: Fedora
- TeX distribution: TexLive

### Description
The icons currently used look quite old and have no really consistent style. The designers of LibreOffice created the incredible [Colibre Icon Theme](https://github.com/rizmut/libreoffice-style-colibre), I partially adapted for TexStudio for testing. I haven't changed all icons yet but here is a screenshot of what I tried in comparison to the old icons:
![grafik](https://user-images.githubusercontent.com/115890454/196006176-914e71e2-8271-4ff4-b15a-38e3e60fd31a.png)
![grafik](https://user-images.githubusercontent.com/115890454/196006183-0f4b1a09-9aa6-4942-ae33-92937f7821b7.png)

Not everything is perfect and there are still a few things to change. But what do you think about the idea of updating the icons in general?

Since different people always favour different styles, I would additionally suggest adding the option for icon themes so that everyone can choose the style he likes most.

**Comment by sunderme** [comment]
I agree that a icon theme selection would be great.
If you provide an icon set, I can make it work.

**Comment by geolta** [comment]
Thank you for your positive feedback!
I'm now working on the implementation of icon themes in the configure dialog as well as on further improving the Colibre icon theme for TXS.

Until now, the icon theme was combined with the setting for the color scheme, I separated this to offer the possibility to create icon themes without theming the entire application (but the detection of dark mode still works).

There are a few hard referenced icons that are not loaded via one of the `getRealIcon` functions in `src/utilsSystem.cpp`. Should we ignore them or try to integrate them in the theming as well? (They look like the person who wrote the code just forgot to use the functions but I'm not sure since I'm no that deep into the code...)

**Comment by sunderme** [comment]
As you like. If there are new icons, i can probably integrate them, but it will take a bit of time.
