### ISSUE TITLE
Artefacts in math symbols in preview mode

### ISSUE THREAD

**Issue by mranvick** [texstudio-org/texstudio#2641]
## Bug description

Some weird artefacts do appear in preview mode under some mathematical symbols - especially under-braces and square roots - depending on the level of zoom used, as illustrated below. Zooming in or out may improve or worsen these artefacts.

![image](https://user-images.githubusercontent.com/17085178/197134526-0c2b23b0-d2cd-43dc-ba90-1400564751eb.png)
![image](https://user-images.githubusercontent.com/17085178/197134598-3634e8d2-57bc-42b2-a337-3e28d28463cb.png)
![image](https://user-images.githubusercontent.com/17085178/197134665-002646e6-89bb-4c0c-8357-85a041451c68.png)
![image](https://user-images.githubusercontent.com/17085178/197134720-b148e285-34b6-4548-9e12-f473751101d6.png)
![image](https://user-images.githubusercontent.com/17085178/197134753-d72b074d-0aec-4456-89ef-49fa08187556.png)

What is especially strange is that if the produced PDF is opened with the system PDF viewer (i.e. MacOS's preview app) the artefacts disappear.

## Step to reproduce

Here is a code snippet which may be used to reproduce the above-described issue:

```Latex

\documentclass{article}
\date{}

% *** MATH PACKAGES ***
\usepackage[cmex10]{amsmath}
\usepackage{amssymb}

% Closed square root
\usepackage{letltxmacro}
\makeatletter
\let\oldr@@t\r@@t
\def\r@@t#1#2{%
	\setbox0=\hbox{$\oldr@@t#1{#2\,}$}\dimen0=\ht0
	\advance\dimen0-0.2\ht0
	\setbox2=\hbox{\vrule height\ht0 depth -\dimen0}%
	{\box0\lower0.4pt\box2}}
\LetLtxMacro{\oldsqrt}{\sqrt}
\renewcommand*{\sqrt}[2][\ ]{\oldsqrt[#1]{#2} }
\makeatother

\begin{document}

\begin{equation}
	S = \sqrt{\sum_{n=0}^{N-1} s_n \cdot e^{-i \cdot \frac{2\cdot \pi \cdot k \cdot n}{N}}}
\end{equation}

\begin{equation}
	S = \underbrace{\sum_{n=0}^{N-1} A_s \cdot \frac{e^{i \cdot \left( \frac{2\cdot \pi \cdot f_0 \cdot n}{f_s} + \varphi + p_n \right)} + e^{- i \cdot \left( \frac{2\cdot \pi \cdot f_0 \cdot n}{f_s} + \varphi + p_n \right)}}{2} \cdot e^{-i \cdot \frac{2\cdot \pi \cdot k \cdot n}{N}}}_{T} + \underbrace{\sum_{n=0}^{N-1} x_n \cdot e^{-i \cdot \frac{2\cdot \pi \cdot k \cdot n}{N}}}_{U}
\end{equation}

\begin{equation}
	\frac{2 \cdot T}{A_s} = \underbrace{e^{i\cdot \varphi} \sum_{n=0}^{N-1} e^{i\cdot \left[ 2 \cdot \pi \cdot \left(\frac{f_0}{f_s} - \frac{k}{N}\right) \cdot n + p_n\right]}}_{V} + \underbrace{e^{-i\cdot \varphi} \sum_{n=0}^{N-1} e^{-i \cdot \left[ 2 \cdot \pi \cdot \left(\frac{f_0}{f_s} + \frac{k}{N}\right) \cdot n  + p_n \right]}}_{W}
\end{equation}

\begin{equation}
	V= e^{i\cdot \varphi} \underbrace{\sum_{n=0}^{N-1} e^{i\cdot p_n}}_{A} \quad \text{and} \quad W = e^{-i\cdot \varphi} \sum_{n=0}^{N-1} e^{- i \left( 4 \cdot \pi \cdot \frac{k}{N} \cdot n + p_n\right)}
\end{equation}

\begin{equation}
	\mu_A = \mathbf{E}\left( \sum_{n=0}^{N-1} e^{i\cdot p_n} \right) = \sum_{n=0}^{N-1} \mathbf{E}\left( e^{i\cdot p_n} \right)
\end{equation}

\begin{align}
	\sum_{n=0}^{N-1} cos^2 \left(\frac{2\cdot \pi \cdot k \cdot n}{N} \right) &= \frac{1}{2}\sum_{n=0}^{N-1}\left(cos\left(\frac{4 \cdot \pi \cdot k \cdot n}{N}\right) + 1\right)\\
	&= \frac{N}{2} + \frac{1}{2} \cdot \underbrace{\Re \left(\sum_{n=0}^{N-1}e^{\frac{4 \cdot i \cdot \pi \cdot k \cdot n}{N}}\right)}_{=0} = \frac{N}{2}
\end{align}

\end{document}
```

## Configuration

MacOS BigSur 11.4 (20F71)
MacBook Pro (13-inch, 2017)
3,5 GHz Intel Core i7 double cœur
Intel Iris Plus Graphics 650 1536 Mo
TeXstudio 4.3.1 (git 4.3.1)
Utilise Qt version 6.3.1, compilé avec Qt 6.3.1 R
Compiling using pdflatex

## Related issues

I think that this issue is distinct from #1773 (horizontal lines appearing when using magnifying glass in preview mode).

**Comment by mranvick** [comment]
Actually, I found that this issue is much more generic than TexStudio: it seems to be a problem in the way that LaTeX is producing big math symbols from a collection of simpler shapes / glyphs - [underbraces, for instance, are composed of several subparts](https://github.com/latex3/latex2e/issues/194#issuecomment-539973628) - and in the way that PDF viewers interpret it. As an example, I also have the above-mentioned display issue if I use Adobe Reader...

See [here](https://github.com/latex3/latex2e/issues/194), [there](https://github.com/latex3/latex2e/issues/194) and [there](https://groups.google.com/g/comp.text.tex/c/Zrloi7xJMnE?pli=1), for further discussions on this topic.

However, there does not seems to be a fix at the moment. If anyone has an idea about:
  - how to fix this
  - what people / forums / issue reporting system / communities may be contacted to fix this

I would greatly appreciate it!

**Comment by sunderme** [comment]
it is a poppler issue.
Poppler demo previewer shows the same issue.
<img width="677" alt="grafik" src="https://user-images.githubusercontent.com/14033169/197325912-1b776b04-37a9-4b9c-9338-c5b0fad9c804.png">
You may want to report there, best with a demonstration on the poppler previewer.

**Comment by sunderme** [comment]
by the way, google-chrome shows the same artifacts (google-chrome uses a different pdf engine). So probably the pdf is odd.

**Comment by octaeder** [comment]
I would say that I know this display problem for a long time. Maybe it is related to the way how LaTeX creates under- and overbraces.
With txs 4.4.0 (git 4.3.1-147-g324a7e778), win10, qt6, and internal pdf-viewer:
```
\[
	\vec{e}_i \coloneqq \{ \underbrace{0, \ldots, 0}_{i \text{ Nullen}}, 1, 0, \ldots 0 \}
\]
```
scaled at 100%, 94dpi:
![image](https://user-images.githubusercontent.com/102688820/197333472-bcc3f5b6-595c-4c24-8081-8b7f8fb7812b.png)

scaled at 400%, 94dpi:
![image](https://user-images.githubusercontent.com/102688820/197333490-26bfd676-ddfd-4aa0-93b7-023f061b5010.png)

Compare to external viewer (acrobat reader):

scaled at 100%, 96dpi
![image](https://user-images.githubusercontent.com/102688820/197333334-c0b82123-f6fa-40e4-811c-47e740a1b625.png)

scaled at 400%, 96dpi
![image](https://user-images.githubusercontent.com/102688820/197333345-d3023fae-a434-4fd6-a5ab-bb3f871cd770.png)

Screen dpi varies slightly, is detected automatically by the viewers. acrobat seems to do a little bit better, especially at 100%, but even so not perfect.

This problem seems not to be present with env dcases (vertical brace):
```
\[
	f(n) \coloneqq \begin{dcases*}
		n/2		 \\
		3\,n+1	
	\end{dcases*}
\]
```

![image](https://user-images.githubusercontent.com/102688820/197333812-e4e1224f-0ad3-4d52-9d81-5ad295910b53.png)

**Comment by dbitouze** [comment]
It depends also on the font used:
```latex
\documentclass{article}
\usepackage{kpfonts}
\begin{document}
\[
  \vec{e}_i \coloneqq \{ \underbrace{0, \ldots, 0}_{i \text{ Nullen}}, 1, 0, \ldots 0 \}
\]
\end{document}
```
gives (with `Okular` at zoom 5000%):
![Capture d’écran_2022-10-22_12-32-59](https://user-images.githubusercontent.com/1032633/197334519-b7f5b0c5-748d-419a-9e86-8e8ae71da8ee.png)

**Comment by octaeder** [comment]
It seems in any case that high zoom factors are likely to give better results than lower ones. This might also depend on screen density (screen dpi). The previous example with acrobat at 400% shows artefacts:

![image](https://user-images.githubusercontent.com/102688820/197339219-768d5230-dee5-47af-abac-aaf37cfb91e1.png)
One note for those who want to try above examples: \\coloneqq needs (for example) package mathtools.

**Comment by sunderme** [comment]
I close this as this seems to be rather a problem of latex/pdf
