### ISSUE TITLE
4.4.0beta1 requires macOS 11.7 or higher

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#2647]
### Environment
- TeXstudio: 4.4.0beta1
- Qt: 
- OS: macOS 11.6.7
- TeX distribution: mactex

### Description
Just a note.

When I tries to open 4.4.0beta1 on macOS 11.6.7, I get
![image](https://user-images.githubusercontent.com/6376638/197950331-609b61e1-acde-4512-b063-4bfd4dea87e9.png)

Thus when 4.4.0 is officially released, the [texstudio.org](https://www.texstudio.org/) need to adapt the change
![image](https://user-images.githubusercontent.com/6376638/197950654-169e8fdc-ffcd-4cc6-a7b9-28ed6adee770.png)

**Comment by sunderme** [comment]
webpage annotated
