### ISSUE TITLE
App icon missing in 4.4.0 betas (1 and 2)

### ISSUE THREAD

**Issue by somelinguist** [texstudio-org/texstudio#2650]
The app icon appears to be missing for the 4.4.0 betas (1 and 2), at least on macOS. It appears like this the downloaded .dmg file as well as in the dock.

<img width="687" alt="Screenshot 2022-10-31 at 9 22 32 AM" src="https://user-images.githubusercontent.com/3488298/199045211-03142667-b8b2-4102-9f12-bb9eeb5a601e.png">

### Environment
- TeXstudio: 4.4.0beta2
- Qt: 6.3.2
- OS: macOS 13.0
- TeX distribution: TeX Live 2022

**Comment by sunderme** [comment]
can you try https://github.com/texstudio-org/texstudio/suites/9052670493/artifacts/418461376

**Comment by somelinguist** [comment]
Hi. It still looks the same.

I did `Show Package Contents` on texstudio.app, and I didn't see the file `texstudio.icns` referred to by `CFBundleIconFile` in `Info.plist` is anywhere inside, whereas in previous releases, it was in `/Contents/Resources`.

Actually, in the current betas and the artifact you linked, the only file that exists ins `/Contents/Resources` is `qt.conf`. The same directory in the app package for version 4.3.1 has 159 items.

I guess things aren't getting copied correctly during the build?

**Comment by sunderme** [comment]
fixed, please try https://github.com/texstudio-org/texstudio/suites/9056795466/artifacts/418737255

**Comment by somelinguist** [comment]
That works. Thanks!
