### ISSUE TITLE
Newest Ubuntu version (Kinetic Kudo) build missing

### ISSUE THREAD

**Issue by friciwolf** [texstudio-org/texstudio#2651]
### Describe the feature and the current behavior/state

Upon upgrading to kinetic kudo, texstudio is automatically uninstalled by the ```sudo do-release-upgrade``` upgrader. After the upgrade, it has to be installed from the official repositories manually. The official ppa build for ```kinetic``` seems to be missing.

### Who will benefit with this feature?

All Ubuntu users upgrading to 22.10.

### Any Other info

Tested on Kubuntu 22.04 upgraded to 22.10.

**Comment by sunderme** [comment]
needs new dependency.
Use the daily ppa for now , this can only be fixed with a new release.
