### ISSUE TITLE
Inconsistent icon sizes in replace panel

### ISSUE THREAD

**Issue by geolta** [texstudio-org/texstudio#2654]
### Environment
- TeXstudio: 4.4.0
- Qt: 5.15.6
- OS: Fedora
- TeX distribution: TexLive

### Expected behavior
All icons in the replace panel have the same size.
![grafik](https://user-images.githubusercontent.com/115890454/199062662-dd3c0ad2-41e6-43bf-9bd5-8b94314939bf.png)

### Actual behavior
The icons for searching are much bigger than the ones for replacing.
![grafik](https://user-images.githubusercontent.com/115890454/199062997-1d5d4707-c6e3-4153-a374-3cfb7b839062.png)

### Solution
The solution is quite simple, I can easily implement the needed changes. The problem are the `setIconSize()` calls in `qsearchreplacepanel.cpp`.

**Comment by sunderme** [comment]
sure, go ahead
