### ISSUE TITLE
Colors in braces are not recognized as possible values for hypersetup options, unless starting a new line

### ISSUE THREAD

**Issue by ghost** [texstudio-org/texstudio#2655]
### Environment
- TeXstudio: 4.3.1
- Qt: 5.12.8
- OS: Linux (Pop OS 20.04)
- TeX distribution: MikTeX

### Actual behavior
Colors in braces are not recognized as possible values for citecolor in hypersetup, unless citecolor starts a new line.
![Screenshot from 2022-11-01 09-49-25](https://user-images.githubusercontent.com/94167482/199198721-34fd1f7f-c2b7-4919-890f-de8ac6242826.png)
![Screenshot from 2022-11-01 09-50-02](https://user-images.githubusercontent.com/94167482/199198739-0965b9f7-1ca7-41d0-aece-af5087a6325e.png)

It also happens with linkcolor, urlcolor...
If the option starts a new line, everything you write in braces is "recognized", whether it's a possible value or not.
If the option does not start a new line, everything you write in braces is "unrecognized", whether it's a possible value or not.

![Screenshot from 2022-11-01 10-18-43](https://user-images.githubusercontent.com/94167482/199201418-37d4288a-32b5-4b22-a4bc-7511acd75400.png)
![Screenshot from 2022-11-01 10-19-00](https://user-images.githubusercontent.com/94167482/199201430-363a2563-0e5b-4b35-8b07-bbd9a269f1c9.png)

Also, "mixed" colors with xcolor package are not "recognized" without braces, even if the option starts a new line.

![Screenshot from 2022-11-01 10-36-57](https://user-images.githubusercontent.com/94167482/199204632-acba61fc-137f-41e2-a9fb-513fbaf946c5.png)
![Screenshot from 2022-11-01 10-37-04](https://user-images.githubusercontent.com/94167482/199204640-ff151509-df38-4450-9de7-ab98dae8cebb.png)

### Expected behavior

I'm not sure, maybe the best option is that everything between braces is "recognized" even if the option does not start a new line, as it is less invasive.

### How to reproduce

Just copy and paste this in a new document:
```
\usepackage{hyperref}
\hypersetup{colorlinks,
	urlcolor={red},
	linkcolor={red!40!black},
	citecolor={notacolor01234}}
\hypersetup{colorlinks,urlcolor={red},linkcolor={red!40!black},citecolor={notacolor01234}}
\hypersetup{colorlinks,urlcolor=red,linkcolor=red!40!black}
\hypersetup{colorlinks,urlcolor=red,
	linkcolor=red!40!black}
```

**Comment by sunderme** [comment]
fixed
