### ISSUE TITLE
When type "/s" the program lost response

### ISSUE THREAD

**Issue by PatchouliHina** [texstudio-org/texstudio#2657]
### Environment
- TeXstudio: 4.4.0 beta 3
- Qt: Qt 6.4.0
- OS: Windows 10 21H2
- TeX distribution: TexLive 2022

As the title

**Comment by sunderme** [comment]
Works without problem.

**Comment by PatchouliHina** [comment]
I try a new document, it works without problem.
It seems to occur only in my larger documents.

**Comment by PatchouliHina** [comment]
It occurs when I edit the document from https://github.com/YangLaTeX/hitszthesis

**Comment by sunderme** [comment]
Please provide a screencast to illustraze the issue.

**Comment by cpierquet** [comment]
Hi- same issue for me with existing document... if I want to include a \smallskip for example, it's freezing...

https://user-images.githubusercontent.com/45103962/199605578-803e5044-66be-4c4b-848a-f3889ec98c4b.mp4

**Comment by sunderme** [comment]
probably fixed with a28979a26b9cf39745aed0361ed2eb2d343e47a8

**Comment by cpierquet** [comment]
Hi- it's ok for me with the [https://github.com/texstudio-org/texstudio/commit/a28979a26b9cf39745aed0361ed2eb2d343e47a8](https://github.com/texstudio-org/texstudio/commit/a28979a26b9cf39745aed0361ed2eb2d343e47a8) ;-)

**Comment by PatchouliHina** [comment]
It has been fixed.
Thanks!
