### ISSUE TITLE
SIGSEV after switching main document often

### ISSUE THREAD

**Issue by bonanza123** [texstudio-org/texstudio#266]
### Environment
- TeXstudio: TeXstudio 2.12.10 (git 2.12.10-61-gf5d206a7)
- Qt: 5.11.1,
- OS: ArchLinux 
- TeX distribution: TexLive 2018

### Expected behavior
Texstudio should continue normally when switching main document file

### Actual behavior
Texstudio crashes with a SIGSEV

> SIGSEGV (TXS-Version 2.12.10-61-gf5d206a7 R )
> [bt] texstudio(_ZN12SimulatedCPU13set_from_realEv+0) [0x556eb8178c20]
> 

### How to reproduce
1) Open your most recent master document, then close it
2) Open another recent master document (not the same as before), then close it
3) Repeat 1) and 2) until crash

**Comment by sunderme** [comment]
trries your instruction a few times and it does not crash.
Since we are talking about Arch-Linux, we are not investing further effort here.

**Comment by bonanza123** [comment]
Just for the record, the same happens on OpenSuse Tumbleweed with
TeXstudio 2.12.10 (git n/a)
Using Qt Version 5.11.1, compiled with Qt 5.11.1 R

**Comment by sunderme** [comment]
well, I canˋt reproduce and I assume that the documents itself play a role. Why don‘t you compile txs with debug symbols ( without crash handler) and run it in a debugger in order to get a useful backtrace.

**Comment by bonanza123** [comment]
@sunderme Sorry for the stupid question.
Is it correct to build texstudio with debug symbols and then rung `gdb texstudio` ?

**Comment by sunderme** [comment]
there is a middleMousebutton call in the backtrace ... so, how do you close a document ?
And if you you use qtcreator , you might a easy access to the variables as well ( i am interested in the conzent of „doc“)

**Comment by bonanza123** [comment]
I used to close with middle-mouse click, but the same happens with CTRL+W for closing.

I'm sorry, I not familiar with qtcreator. I attached its debugger to texstudio and let it crash. Where/how to get the variables?

(also in gbd `info variables` and `info locals` does not show anything)

**Comment by sunderme** [comment]
just open texstudio.pro with qtcreator and start debugging (F5).
variables are shown in a pane on the right hand side.

**Comment by sunderme** [comment]
add NO_CRASH_HANDLER=1 into the qmake set-up (project in qtctreator)

**Comment by bonanza123** [comment]
I hope this is helpful: https://gist.github.com/bonanza123/ad55db6a69e8ce9c4eda528b1279c780

**Comment by benibela** [comment]
I encountered something similar
```
#9  0x000000000066344e in recover () at texstudio.cpp:10114
#10 0x00007fcd01c0dbc3 in malloc_consolidate (av=av@entry=0x7fcd01f38620 <main_arena>) at malloc.c:4157
#11 0x00007fcd01c0e6a1 in _int_free (av=0x7fcd01f38620 <main_arena>, p=<optimized out>, have_lock=0) at malloc.c:4057
#12 0x00007fcd034b8ee5 in QImageData::~QImageData() () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#13 0x00007fcd034b8f5b in QImage::~QImage() () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#14 0x00007fcd034e4371 in QRasterPixmapData::~QRasterPixmapData() () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#15 0x00007fcd034e43a9 in QRasterPixmapData::~QRasterPixmapData() () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#16 0x00007fcd034d4a8a in QPixmap::~QPixmap() () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#17 0x00007fcd034d4ab9 in QPixmap::~QPixmap() () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#18 0x00000000009cf1b9 in QCache<QDocumentLineHandle*, QPixmap>::clear (this=0x7951318) at /usr/include/qt4/QtCore/qcache.h:139
#19 0x00000000009cec6f in QCache<QDocumentLineHandle*, QPixmap>::~QCache (this=0x7951318, __in_chrg=<optimized out>) at /usr/include/qt4/QtCore/qcache.h:103
#20 0x00000000009c2a6d in QDocumentPrivate::~QDocumentPrivate (this=0x7951200, __in_chrg=<optimized out>) at qcodeedit/lib/document/qdocument.cpp:6404
#21 0x00000000009aae8c in QDocument::~QDocument (this=0x77cf700, __in_chrg=<optimized out>) at qcodeedit/lib/document/qdocument.cpp:446
#22 0x000000000083dfde in LatexDocument::~LatexDocument (this=0x77cf700, __in_chrg=<optimized out>) at latexdocument.cpp:57
#23 0x000000000083e252 in LatexDocument::	~LatexDocument (this=0x77cf700, __in_chrg=<optimized out>) at latexdocument.cpp:73
#24 0x000000000084fb60 in LatexDocuments::deleteDocument (this=0x2510388, document=0x77cf700, hidden=false, purge=false) at latexdocument.cpp:2188
#25 0x000000000061b9d4 in Texstudio::fileClose (this=0x2510260) at texstudio.cpp:2807
#26 0x0000000000b12486 in Texstudio::qt_static_metacall (_o=0x2510260, _c=QMetaObject::InvokeMetaMethod, _id=49, _a=0x7ffe897a2960) at .moc/moc_texstudio.cpp:942
#27 0x00007fcd02b8c1c0 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#28 0x00007fcd033f3912 in QAction::triggered(bool) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#29 0x00007fcd033f4c73 in QAction::activate(QAction::ActionEvent) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#30 0x00007fcd033f51cc in QAction::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#31 0x00007fcd033f98dc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#32 0x00007fcd03400816 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#33 0x00007fcd02b77abd in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#34 0x00007fcd034307b8 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#35 0x00007fcd034309a7 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
```

but too random to reproduce at will. But the documents seemed fine, just  the QCache/QPixmap was corrupted internally

**Comment by sunderme** [comment]
could you try the latest version from the repository ?

**Comment by bonanza123** [comment]
Unfortunately, the problem persist also with the latest version from git.

**Comment by bonanza123** [comment]
I just wanted to report that for the time being I seem to have solved it with removing the current ini config.
I would close that issue until it occurs again if you are fine with that.

**Comment by sunderme** [comment]
okay, letˋs keep the fingers crossed
