### ISSUE TITLE
Open subimport nested existing file 

### ISSUE THREAD

**Issue by pepramon** [texstudio-org/texstudio#2662]
### Environment
- TeXstudio: 4.3.1
- Qt: 6.3.1
- OS: Arch Linux
- TeX distribution: texlive

### Folder structure
I use massively \subimport into a book of solved problems, I organize every chapter in a folder and every problem of these chapter in a subfolder like:

- main.tex
- chapter1
   - chp1.tex
   - problem1
      - prob1.tex
- chapter2
   - chp2.tex
   - problem1
      - prob1.tex
   - problem2
      - prob2.tex

For example chap2.tex is just a list of subimports to organize the problems in correct order. Every problem is independent of others (some times it's made for different people) and it's easy to move to other sections (just move de folder and add the \subimport command in correct file)

### Expected behavior
Until version 4.3.1, when I use treeview and double click to (for example) prob2.tex inside chp2.tex, it opens correctly as a new tab and I can continue editing. Work fine for first level of subimport

### Actual behavior
In second level of subimport try to create the file (the file exist an LaTeX works fine when compile) as you can see in the image (sorry the interface is in Spanish) TexStudio try to create the file, and if you say yes, create in root folder.

I know the enhancement in the issue #1052 and for me it's easy to create en root part and move to correct location, but the behavior that can't open directly in the tree view, provokes that I need to find the correct location via folder browser every time, not just one.

![image](https://user-images.githubusercontent.com/5684403/200168659-79b94ac4-a7fc-4a1b-9e22-c7d81349f315.png)

### How to reproduce
I made just a easy test to reproduce the issue

[sample.zip](https://github.com/texstudio-org/texstudio/files/9945757/sample.zip)

P.D --> Sorry my English level.

**Comment by sunderme** [comment]
arreglado ;-)

**Comment by pepramon** [comment]
@sunderme Gracias!!!!!!!!!!!!!!!!!!!!!!!
