### ISSUE TITLE
Request Feature: Compatible with Windows 11

### ISSUE THREAD

**Issue by qyua3175** [texstudio-org/texstudio#2664]
Millions of desktop users have transfer to the next generation operating system Windows 11 developed by Microsoft, many of them are TeX/TeXStudio users covering beginners to professionals. Currently, however, the TS is yet to be runnable on this new platform. Please implement any upgrade to extend TS's spectrum to the new system.

**Comment by sunderme** [comment]
texstudio runs fine on win11.
However, on win11 vcruntime is missing.
See https://answers.microsoft.com/en-us/windows/forum/all/vcruntime140dll-was-not-found/f43d5afd-9239-4913-8f32-20e44a959e13
So, quick fix: download and run  https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by sunderme** [comment]
I consider this answered.

**Comment by jpmaroco** [comment]
nope, I have VC installed in Win11.

**Comment by esojli** [comment]
We were 'lucky' to be rolled on to Windows11 last week. Since then my TexStudio does not work. It looks like it's starting and running but it is just not visible. I have the MV C++ 15-22 and I even installed 4.5.1. It is still now orking.

**Comment by sunderme** [comment]
never a good idea to comment on closed issues.

you can open a new issue. You should check if the portable version works.
I don't have win11 but in the VM, installing vc_redist solved the issue.

**Comment by thymaro** [comment]
for any future reader: it sometimes helps to install or repair the current installation of vcredist, and also install the x86 version from the provided link. I had the same problem with KeePassXC and this was the suggested solution (which also worked).
