### ISSUE TITLE
Ignore button does not work as expected in spelling checker, extra button needed?

### ISSUE THREAD

**Issue by ralphrmartin** [texstudio-org/texstudio#2667]
The `Ignore` button in spelling checks does not function as its name would suggest.

If I run a spelling check, and something is flagged as an error, there are choices to replace the wrong item, or to ignore it.

The label `Ignore` is rather ambiguous, it could mean
- ignore this single instance of this dubious word
- ignore this dubious word here, AND in the rest of the current spell check.

The current implementation of ignore takes the first meaning,
I would suggest this is nether what the user expects nor wants.
For example, if I use some abbreviation like EFD many times in my document, I do not want to have to click Ignore for every single instance - yet I may also not want to learn it, as it may be too close to some other valid abbreviation I ofen use.

I would also note that TeXShop for the Mac uses Ignore in the second sense.

However,  perhaps the best solution would be to add an extra button to the spelling check dialog, to allow both possibilities

`Ignore Once` - ignore this single instance (behaviour of current ignore button)
`Ignore All` - Ignore all instances for the rest of this check

Having two buttons would be clearer, and give the user the choice.

[Sorry if my bug report is thus perhaps a feature request - but to me the natural meaning of ignore is not the current behaviour).

### Environment
- TeXstudio: 4.3.1
- Qt: Qt Version 5.15.6, compiled with Qt 5.15.4 R
- OS: Debian testing
- TeX distribution: texlive

### Expected behavior
Ignore the flagged word in the rest of the document.

### Actual behavior
Ignore just the current occurrence of the flagged word.

### How to reproduce
Just run a spelling check.

**Comment by sunderme** [comment]
txs only can add a word to the "dictionary" or , in case of the spellchecker dialog, just skip over (ignore) a word (and that is not permanent).
So ignore all is basically "add".

**Comment by ralphrmartin** [comment]
Sorry, but I dont understand your comment. You appear to be just restating what the current behaviour is, apart from the mysterious use of the word "can". Are you implying that there is some reason that the current behaviour cannot be improved as suggested? 

"Ignore all" should certainly not be "add", as I may wish to ignore all occurrences of  something in the current document, but not in future documents, as I  explained in my original comment.

**Comment by sunderme** [comment]
the question is: why do you not want to add the word to the dictionary ?
There is no storage of that kind of data per document. So, ignoring it will be reversed for the next start of txs.
So far, I don't really see why adding to dictionary is not the right choice.

**Comment by ralphrmartin** [comment]
Suppose I am writing a book, and in it discussing work by a guy with an unusual name of "Smoth". I may write Smoth 50 times in my book. I do not want to click Ignore 50 times. However, in pretty well any other books or papers I write, Smoth os probably a misspelling of Smith, or Smooth. So I also do not want to add it to the dictionary.

While the above is perhaps a contrived example, I can assure you that it crops up all the time, as in my area of work, people use many strange acronyms, which are OK in one document, but typos in another.

**Comment by ralphrmartin** [comment]
I should perhaps also add that TeXShop on the Mac provides an Ignore All button of the kind I am suggesting, and when using a Mac, I use it pretty much in every document I edit.

**Comment by abelokoj-github** [comment]
> Suppose I am writing a book, and in it discussing work by a guy with an unusual name of "Smoth". I may write Smoth 50 times in my book. I do not want to click Ignore 50 times. However, in pretty well any other books or papers I write, Smoth os probably a misspelling of Smith, or Smooth. So I also do not want to add it to the dictionary.
> 
> While the above is perhaps a contrived example, I can assure you that it crops up all the time, as in my area of work, people use many strange acronyms, which are OK in one document, but typos in another.

I understand what you mean. Clicking Ignore in WinEdt usually defaults to the ignore all option.  I think this will be a good Idea to add the ignore all to TXS or just default the current ignore to ignoring all in the current document.

**Comment by sunderme** [comment]
implemented with [d190d9d](https://github.com/texstudio-org/texstudio/commit/d190d9da8572f947302481cb9c17a3112760c9d4)

**Comment by ralphrmartin** [comment]
Thank you!
