### ISSUE TITLE
pdf issue in texstudio

### ISSUE THREAD

**Issue by Jasdeep-2307** [texstudio-org/texstudio#2669]
<!==unknown at 71c640 (TXS-Version 4.3.1 R )
[bt] 000000000064dd70  ??? error: 487

- Qt: 
- OS: 
- TeX distribution:

**Comment by sunderme** [comment]
the questions above (version, os and reproducible test case) are a minimum for a bug report that can be solved.
Unless that is added, I will close this report for insufficient information.

**Comment by sunderme** [comment]
no feedback
