### ISSUE TITLE
TXS hasn't a basic CLI?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [texstudio-org/texstudio#2671]
### Environment
- TeXstudio: TeXstudio 4.3.1 (git 4.3.1)
- Qt: Qt Version 6.3.1, compiled with Qt 6.3.1 R
- OS: Windows 10 20H2
- TeX distribution: MiKTeX

### Description
Just a question that TXS doesn't have CLI right? for example for `texstudio --version` or `texstudio --help` ?

**Comment by octaeder** [comment]
Do you search for this [https://texstudio-org.github.io/background.html#overview-of-texstudio-command-line-options](https://texstudio-org.github.io/background.html#overview-of-texstudio-command-line-options)?

**Comment by yashpalgoyal1304** [comment]
yes, something like that, but for the following 3 options available in "Help" items:
* About TeXstudio... : something like `--version` or `-V` option optionally with flags `-v` , `-vv` for verbosity level (inspired by `pacman` verbosity levels under `-Si` like -ii or -iv etc)
* User Manual... : something inspired from `git --help` menu which launches the relevant page in the browser
* LaTeX Reference... 

![image](https://user-images.githubusercontent.com/19423063/201527160-a0550e6b-f9a3-4885-86c6-d412feb9129d.png)

**Comment by sunderme** [comment]
txs is a gui program. CLI is usually not that helpful.
There is the usual `--help` and `--version` but it gives text only hints on command line and that is it.

**Comment by yashpalgoyal1304** [comment]
> There is the usual `--help` and `--version` but it gives text only hints on command line and that is it.

the thing is, even those are not working

![image](https://user-images.githubusercontent.com/19423063/201700109-e846a90b-75ef-46b6-8bda-c4c424ee2b39.png)

**Comment by dbitouze** [comment]
@yashpalgoyal1304 Are you using the portable version of TXS? Because, here:

```
╭─bitouze@drums ~  
╰─➤  texstudio --version
TeXstudio 4.4.0 (N/A)
╭─bitouze@drums ~  
╰─➤  texstudio --help   
Usage: texstudio [options] [file]

Options:
  --config DIR              use the specified settings directory
  --master                  define the document as explicit root document
  --line LINE[:COL]         position the cursor at line LINE and column COL
  --insert-cite CITATION    inserts the given citation
  --start-always            start a new instance, even if TXS is already running
  --pdf-viewer-only         run as a standalone pdf viewer without an editor
  --page PAGENUM            display a certain page in the pdf viewer
  --no-session              do not load/save the session at startup/close
  --texpath PATH            force resetting command defaults with PATH as first search path
  --version                 show version number
╭─bitouze@drums ~  
╰─➤  texstudio --help   
```

**Comment by yashpalgoyal1304** [comment]
hey, one small off-topic question - i am being asked again and again to download these packages:
* `preview.sty` in `preview` package
* glossary
* i guess there was one more

but the thing is i haven't used them in my document - i tried looking for preview package online, but it's showing up only in context of emacs and auctex - and i am using neither. 

so, can u help me - what those are about, and why do they keep on popping up randomly?

sorry again for this offtopic question, feel free to hide it

**Comment by sunderme** [comment]
preview probably for txs previewing parts of the document (formulas, colors,etc.)

**Comment by yashpalgoyal1304** [comment]
> the thing is, even those are not working
\- https://github.com/texstudio-org/texstudio/issues/2671#issuecomment-1313940193

ping

**Comment by sunderme** [comment]
source says: `// note: stdout is not supported for Win GUI applications.  Will simply not output anything there.`

**Comment by yashpalgoyal1304** [comment]
this should be closed as not planned then
