### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by sekigh** [texstudio-org/texstudio#2673]
I intensively use Texstudio as usual these days. Today when I closed TexStudio by click file -> finish on completion of today's work, it showed TexStudio clush with following error message on pop-up window saying "TexStudio clush due to unknown at 7ff762b71bbb. Backtrace is written to texstudio_backtrace1_.txt." I attached the screen shot of error message and trace file here.

### Environment
- TeXstudio: 4.2.3
- OS: Windows10
- TeX distribution: texlive

### Expected behavior
Conduct normal close on TexStudio.

### Actual behavior
See attached screen shot.

### How to reproduce

[texstudio_backtrace1.txt](https://github.com/texstudio-org/texstudio/files/9997831/texstudio_backtrace1.txt)
[20221113_texstudio_crush_screen_with_messages.pptx](https://github.com/texstudio-org/texstudio/files/9997837/20221113_texstudio_crush_screen_with_messages.pptx)

**Comment by sunderme** [comment]
unfortunately the backtrace currently is useless.
So, without a reproducible test case, there is nothing we can do.
