### ISSUE TITLE
Feature request: completion support for tikz libraries

### ISSUE THREAD

**Issue by mbertucci47** [texstudio-org/texstudio#2676]
### Describe the feature and the current behavior/state
As far as I know there's no support for autocompletion of commands from tikz libraries loaded with `\usetikzlibrary`. For example, the `tikzmark` library provides the `\tikzmark` command, among others, which can't be recognized by the completer.

<img width="416" alt="tikzlib" src="https://user-images.githubusercontent.com/61854785/202078641-9c71eb2c-004f-4850-95a3-dc3085f10259.png">

I'm imagining the code would be analogous to the way Beamer themes are currently handled, so the line `\usetikzlibrary{tikzmark}` could generate and activate `tikzlibrarytikzmark.cwl` from the file `tikzlibrarytikzmark.code.tex` if a cwl of that name is not already present. If one is, it would just be activated.

### Who will benefit with this feature?
Anyone who uses tikz libraries. Additionally, it would allow for more localization of tikz keyvals. At present, `tikz.cwl` just lists all the keyvals from the libraries that ship with tikz even though they aren't automatically loaded, which makes the keyval completion clunkier than necessary.

### Any Other info
Source for image:
```latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{tikzmark}

\begin{document}
\tikzset{tikzmark prefix=ex4-}
\begin{tikzpicture}[remember picture,overlay]
\draw[->,line width=1mm,cyan] (pic cs:a) to[bend left] (pic cs:b);
\end{tikzpicture}
By placing the \tikzmark{a}code before the marks, the arrow goes
under the subsequent text and picture.
\begin{tikzpicture}
\filldraw[fill=gray] (0,0) circle[radius=1cm];
\tikzmark{b}{(-1,-1)}
\end{tikzpicture}
\end{document}
```

**Comment by sunderme** [comment]
implemented
