### ISSUE TITLE
completer could add the macro name after usertag

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2679]
_Originally posted by @octaeder in https://github.com/texstudio-org/texstudio/issues/2675#issuecomment-1314359155_

![image](https://user-images.githubusercontent.com/102688820/201760659-677987e7-f50d-46cf-98d4-81f8ad888140.png)

I changed the code to

cw.setName(macro.abbrev + tr(" (Usertag ") + macro.name + ")");

and tested with a macro named "beta is a greek letter" which has abbreviation "b":

![image](https://user-images.githubusercontent.com/102688820/202568175-bae9696f-d81b-400f-85a4-a142574d18c4.png)

Maybe something other?

**Comment by sunderme** [comment]
If a name is given, there is not much need for the word "Usertag")
