### ISSUE TITLE
Load `.bib` file from package

### ISSUE THREAD

**Issue by li-po** [texstudio-org/texstudio#268]
### Expected behavior
I import my centralized bibliography from inside a own package `...sty`:

`\bibliography{../something/biblio}`

I expected that the bibliography would be found and the auto-completion for `\cite{}' would work.

### Actual behavior
The whole build works fine, but the auto-completion does not work.

There are, in my opinion, two solutions:

- Extend the parsing of `bib` in packages
- Add an option where a bibliography file can be defined.

**Comment by sunderme** [comment]
the txs philosophy is that packages are kind of fixed and handled via cwl-files (which are automatically generated for unknown packages) and inludes (.tex) are dynamic which are loaded and parsed whenever something changes, inlcuding the import of bibliographies.
So, in your case, change your "package" to a tex-file and be done with it.
No need to create the hassle that sty-files are mostly packages but sometimes not.

You can add bibfile-search path in option/adv. editor, but that is it.

**Comment by li-po** [comment]
Thank you. Yes, this solve some problems.
But now I have to maintain the same identical file in the git repo of every single book, because `\include` does not seem to work with relative link.
Sym-link also does not work.

**Comment by li-po** [comment]
The bibliography is not a problem any more. It supports relative links. Now I have lost the centralized maintenance of the style and the commands. But I will solve the problem with a script that copies the common include with the settings in the folder of every book. Thank you.
