### ISSUE TITLE
two notes on texstudio.org

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2683]
![image](https://user-images.githubusercontent.com/102688820/202844878-70a05f72-cadf-4ac2-9dd7-e69d0cec370c.png)

1. Release notes 4.4.0 say **no** win/qt5 build, but the home page offers those versions.

2. Since column size seems to be useless one could use the space to increase width of first column Platform to remove newlines in the items for better readability.

Thx

**Comment by sunderme** [comment]
qt5 removed
