### ISSUE TITLE
show Advanced Options notifications only one time

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2684]
In the config dialog you can silently disable Advanced Options. Turning back to Advanced Options always needs to confirm this notification:

![image](https://user-images.githubusercontent.com/102688820/202851272-606c4707-c2a4-4881-99c4-3c3c0944c7a2.png)

This can be annoying, so I suggest a second option at the bottom of the General options (turned on by default):

![image](https://user-images.githubusercontent.com/102688820/202853402-9795b178-f2a6-4467-ad89-0febb83ccaee.png)

May I implement this?

**Comment by sunderme** [comment]
you only need to click that dialog once.
I really don't think that we need a check box for that.

**Comment by octaeder** [comment]
Well I often switch to advanced options and back. And always clicking OK drives me crazy. Do we really need that message? It is not a clear warning, it only explains what advanced options are for. But this is obvious.

**Comment by sunderme** [comment]
if it bothers you so much, you can let txs remember that you have accepted that dialog prior

**Comment by octaeder** [comment]
Hence this will be for everyone. Nobody can turn back after looking what advanced options are. Ok?

**Comment by sunderme** [comment]
sure, there is no need to warn again.
