### ISSUE TITLE
Horizontal Spacing commands in the menu for common commands

### ISSUE THREAD

**Issue by GniLudio** [texstudio-org/texstudio#2687]
It would be nice to have common horizontal spacing commands in the LaTeX-Command-Dropdown.

### Who will benefit with this feature?
Everybody who wants to add horizontal spacing? (especially me)

### Any Other info
The menu already includes the commands for vertical spacing.

**Comment by octaeder** [comment]
You can customize the menus, for example:

![image](https://user-images.githubusercontent.com/102688820/202880239-c0d2bc69-49f3-4520-a75c-ad027b1299c2.png)

To do so, open menu Options/Configure TeXstudio...
In the lower left corner of the Config Dialog check "Show Advanced Options".
Choose the now visible "Menus" category to the left.
Then you can change the menu with the context menu (right mouse button click):

![image](https://user-images.githubusercontent.com/102688820/202880339-273da73d-0dda-4327-afab-0af052d97860.png)
Compare to first image.
If desired use & before that character of the submenu name or the menu item name that should be used as command accelerator (mnemonic).

Horizontal spacing commands in math mode can be found in menu Math/Math Spaces.

**Comment by sunderme** [comment]
@GniLudio you can hand in a new version of https://github.com/texstudio-org/texstudio/blob/master/uiconfig.xml if you are interested.
