### ISSUE TITLE
Compilation on Fedora 28

### ISSUE THREAD

**Issue by li-po** [texstudio-org/texstudio#269]
### Environment
- TeXstudio: main branch
```
$ qmake-qt5 --version
QMake version 3.1
Using Qt version 5.10.1 in /usr/lib64
```
- Fedora 28 64 bit

- TeX distribution: texlive (not relevant, I assume)

### Actual behavior

After cloning the repository and after executing `qmake`, I get following error:

```
$ qmake-qt5 texstudio.pro
Project MESSAGE: Building with Qt5
Project MESSAGE: GIT
Project ERROR: Unknown module(s) in QT: uitools
```

If I remove `uitools` from `texstudio.pro` (line 23) I do not get the error by qmake, but by make.
```
-lpthread 
.obj/scriptobject.o: In function `ScriptObject::createUI(QString const&, QWidget*)':
scriptobject.cpp:(.text+0x4052): undefined reference to `QUiLoader::QUiLoader(QObject*)'
scriptobject.cpp:(.text+0x4060): undefined reference to `QUiLoader::load(QIODevice*, QWidget*)'
scriptobject.cpp:(.text+0x406b): undefined reference to `QUiLoader::~QUiLoader()'
```

Probably a package in my installation is missing but with uitools I do not find anything.
Could you guess from the error some missing file? so I could look for a package containing it.

**Comment by sunderme** [comment]
the .spec file demands following packages:

BuildRequires:  gcc-c++
BuildRequires:  qt5-qtbase-devel
BuildRequires:  qt5-qtsvg-devel
BuildRequires:  qt5-qtscript-devel
BuildRequires:  qt5-qttools-devel
BuildRequires:  qt5-qttools-static
BuildRequires:  poppler-qt5-devel

**Comment by li-po** [comment]
Thank you.
