### ISSUE TITLE
Enviroment name

### ISSUE THREAD

**Issue by abelokoj-github** [texstudio-org/texstudio#2690]
### Environment
- TeXstudio:  4.3.1 (git 4.3.1) 
- Qt: Version 6.3.1, compiled with Qt 6.3.1 R
- OS:  WIndows 11 
- TeX distribution: TeXlive 2022

### Expected behavior
Pressing **CTRL+E** should allow editing/renaming both the name field of the begin and end environment
Using Qt Version 6.3.1, compiled with Qt 6.3.1 R

### Actual behavior

When you press **CTRL+E** you get 
```
\begin{environment-name}
content
\end{environment-name}
```
There should be a way to make editing the namefield of **begin** and **end** environment at the same time. This current option exists but somehow, you have to wait for like 5 seconds after clicking on the namefield before it does simultaneous editing.

A better situation should be to make this work in such a way that when the user presses **CTRL+E** there should be no wait time before switching to multi-cursor mode to edit both the begin and end namefields. the wait time might remain if the **CTRL+E** option is  not used

**Comment by sunderme** [comment]
ctrl+e inserts the environemnt, with the cursor at "environment-name" and both selected as mirror cursor.
Are you working with default settings ?

**Comment by abelokoj-github** [comment]
Yes, its the default.  Pressing **CTRL +E** correctly gives the mirror cursor like you said. However, when I delete the default text, it works in the mirror version of both begin and end, however when I start typing the new text (environment name) it only  reflects on the begin environment namespace

**Comment by sunderme** [comment]
Why don't you just overwrite the selected text ?

**Comment by abelokoj-github** [comment]
> Why don't you just overwrite the selected text ?

doing that produces this. It only reflects on the begin namefield

![image](https://user-images.githubusercontent.com/69094732/202897939-3d0c5b84-4487-4b5a-986e-2557a07a5632.png)

**Comment by octaeder** [comment]
First deleting "environment-name with del key after ctrl+e works for me (win10), the mirror cursors are not removed:

![image](https://user-images.githubusercontent.com/102688820/202898308-f67b5dee-b3f6-430a-9651-b18c9bb69d83.png)

Then typing simultaneously is possible.

**Comment by octaeder** [comment]
does it look like this directly after pressing ctrl+e?

![image](https://user-images.githubusercontent.com/102688820/202898508-07702e05-d461-49fd-b340-a8b3d219e42a.png)

You should see 3 rectangles surrounding text (here red, black and blue). The last is missing in your screenshot posted.

**Comment by abelokoj-github** [comment]
Yes. It happens just like this.

**Comment by abelokoj-github** [comment]
> First deleting "environment-name with del key after ctrl+e works for me (win10), the mirror cursors are not removed:
> 
> ![image](https://user-images.githubusercontent.com/102688820/202898308-f67b5dee-b3f6-430a-9651-b18c9bb69d83.png)
> 
> Then typing simultaneously is possible.

Try this and start typing, it will only be reflected on the `\begin{environment-name}` part. The bottom will remain blank.

Mine behaves that way.

**Comment by octaeder** [comment]
I can't reproduce. Can you test with latest portable version 4.4.0 from [here](https://www.texstudio.org/#download)? I have no Win11.

**Comment by abelokoj-github** [comment]
> I can't reproduce. Can you test with latest portable version 4.4.0 from [here](https://www.texstudio.org/#download)? I have no Win11.

This works flawlessly.

I will try to update my TXS version.

Thanks to you @octaeder  and @sunderme  for all the effort on TXS. I have been using it since like  around 2017 and I can say it has been excellent.

**Comment by octaeder** [comment]
We all thank @sunderme for his continuous work.

**Comment by sunderme** [comment]
so, this can be closed ?

**Comment by abelokoj-github** [comment]
> so, this can be closed ?

Unfortunately, when I updated my TXS, it still retained the old behavior. I will probably have to uninstall and reset all settings to default to get it working again.

Is there a way I can probably backup my shortcuts and restore them?

**Comment by abelokoj-github** [comment]
> so, this can be closed ?

Yes, you can go ahead and close this now.

However updating did not fix the problem for mw. I had to uninstall previous version and deleted the temporary files of TXS before reinstalling the new one. Doing this fixed the problem for me.

However, the issue of spell check not highlighting the words is still not fixed as yet.

So you can go ahead and close this one and then we follow up the other issue.

thanks a lot for your time.

**Comment by abelokoj-github** [comment]
> so, this can be closed ?

Unfortunately,  it has reverted to it's previous behavior. Not sure what the problem is currently. I did not backup or make use of my previous TXS profile in the old installation just to make sure that there are no conflicts

**Comment by sunderme** [comment]
no lead where the problem may be.
When there is a minimal example to replicate, open a new issue.
