### ISSUE TITLE
User manual

### ISSUE THREAD

**Issue by GyorgySZEIDL** [texstudio-org/texstudio#2692]
OS is Windows 10. Portable version of Texstudio 4.4.0 (QT6) does not work if I want to reach the User Manual. If I click on Help, then User Manual  I get an error message: file not found. Everything is OK, however, under Texstudio 4.3.1.

**Comment by octaeder** [comment]
The files are here: texstudio-4.4.0-win-portable-qt6\help\build\html\index.html or [online](https://texstudio-org.github.io/).
Thanks to @sunderme there is already a fix that will be provided with next txs version.

**Comment by sunderme** [comment]
can you try https://github.com/texstudio-org/texstudio/suites/9407228873/artifacts/444108764 ?

**Comment by octaeder** [comment]
Your download fixes the issue. Used path is
texstudio-win-qt6-4.4.1-202211201405-git_cc7842b9f/help/build/html/getting_started.html.
Thx.
