### ISSUE TITLE
Move option MRU Document Chooser to Files part?

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2694]
I wanted to know what is affected by advanced option _MRU Document Chooser_ in General options. This option looks a little bit lost in the Appearance part of the General options:

![image](https://user-images.githubusercontent.com/102688820/202931883-ab11624a-76bc-4dcb-a551-d264ac878b43.png)

I looked into the code and found that it influences the sort order of the file list presented by menu View/List Of Open Documents. I think it should be moved to the Files part (where we also find some kind of related item "Use system file dialogs"):

![image](https://user-images.githubusercontent.com/102688820/202931901-46dcab37-ddab-47e0-a38f-97510a7c8b27.png)

The dialog would then look clearer and more compact.
Since the text of the option is not quite clear, a detailed description may be added to the manual.

**Comment by octaeder** [comment]
As you can see from the second image I just need to know if I should create a PR for what I've done.
Updating the manual I would leave to someone else.

**Comment by sunderme** [comment]
done myself as I wanted to have the resulting checkboxes in two columns then
