### ISSUE TITLE
(lack of) compatibility with windows 11

### ISSUE THREAD

**Issue by alceu-frigeri** [texstudio-org/texstudio#2697]
In my laptop I have windows 11 pro,
and, as of now, I'm stuck with TexStudio 4.3.0 qt5.
I have tried many times to upgrade to TexStudio 4.3.1 (either qt6 (won't even install and qt5 (it does install but once I try to run it just crashes right away).
Now, with 4.4.0 things got worst. there is no qt5 version anymore and the qt6 installer just crashes.

BTW, some have said that 'it is necessary' to install a Visual C++ run-time library. Well, I have a FULL Visual C++ installation, and nope, the 4.4.0 qt6 installer crashes.

Any hope that it will get fixed, or it 'as is', windows 11 isn't and won't be supported ?

### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution:

**Comment by foreachthing** [comment]
I have no issues with win11pro and texstudio.
I am sure you've read this: https://github.com/texstudio-org/texstudio/issues/2664

**Comment by alceu-frigeri** [comment]
yes, I saw #2664, that's why I mentioned that I have a full Visual C++ instalation, not just the runtime DLLs.
textstudio-4.4.0-win-qt6.exe won't even install. It dies/crashes right away (as all qt6 previous versions under windows 11).

**Comment by sunderme** [comment]
you mean, the installer itself crashes ?

**Comment by alceu-frigeri** [comment]
> you mean, the installer itself crashes ?

exactly. I have already downloaded it many times (just to be sure the download itself, didn't got corrupted).
but, nope, once I try to run the installer, it just dies right away.

BTW, I tried to 'upgrade' it using winget as well (since it shows up as a 'possibility'). winget downloads it (from  https://github.com/texstudio-org/texstudio/releases/download/4.4.0/texstudio-4.4.0-win-qt6.exe), it verifies the file hash (ok) and once it tries to install it dies with exit code  3221225595)

**Comment by sunderme** [comment]
but then it is something completely outside txs/qt6.
The installer is generated by nsis on msys2. 
Please try to use the portable version.
By the way, are you sure that you don't have some aggressive anti-virus software or similar running ?

**Comment by alceu-frigeri** [comment]
Antivirus, I have McAfee (livesafe) installed. Just to be sure, I 'scanned' the installer to see if McAfee would complain, nope, no problems there)... and it also hasn't raised any warning when trying to run the 4.4.0-qt6 installer.
btw, 4.3.1-qt5 would, as said, install but the installed version crashes. the 4.3.0-qt6, as well, don't install, BUT the 4.3.0-qt5 installs without any issues.

**Comment by sunderme** [comment]
both installers are generated with nsis. One on linux with mxe (txs/qt5). One on windows with msys (txs/qt6).
That should not make a difference but whyever it does on your system.
So, txs is working fine on win11, the issue is rather something between your system and the nsis installer.

**Comment by alceu-frigeri** [comment]
"thanks"... it is so reassuring that, one just has to follow the many requests here in github to see that it is never a textstudio problem, but always 'users problem' (even though many have the same problem).
No need to reply, I already know the trill here. good bye and as always, thanks for nothing.

**Comment by sunderme** [comment]
You received an advise that got the latest version running on your system and that is bad ?
