### ISSUE TITLE
Build failure with cmake on s390x

### ISSUE THREAD

**Issue by hannes101** [texstudio-org/texstudio#2698]
### Environment
- TeXstudio: 4.4.0
- Qt: Qt Version 5.15.7
- OS: fedora 37
- TeX distribution: 

### Description
During the switch from qmake to cmake, which I am trying to also implement for fedora. I came across the following build failure with s390x. I think this should be easily fixable, or?

`/builddir/build/BUILD/texstudio-4.4.0/src/debug/debughelper.cpp:1271:2: error: #error Unknown cpu architecture
 1271 | #error Unknown cpu architecture
      |  ^~~~~
/builddir/build/BUILD/texstudio-4.4.0/src/debug/debughelper.cpp:87:21: warning: inline function 'void SimulatedCPU::leave()' used but never defined
   87 |         inline void leave();
      |                     ^~~~~
/builddir/build/BUILD/texstudio-4.4.0/src/debug/debughelper.cpp:84:21: warning: inline function 'void SimulatedCPU::call(char*)' used but never defined
   84 |         inline void call(char *value);
      |                     ^~~~
gmake[2]: *** [CMakeFiles/texstudio.dir/build.make:9474: CMakeFiles/texstudio.dir/src/debug/debughelper.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: Leaving directory '/builddir/build/BUILD/texstudio-4.4.0/redhat-linux-build'
gmake[1]: *** [CMakeFiles/Makefile2:248: CMakeFiles/texstudio.dir/all] Error 2
gmake[1]: Leaving directory '/builddir/build/BUILD/texstudio-4.4.0/redhat-linux-build'
gmake: *** [Makefile:139: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.pubJND (%build)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.pubJND (%build)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.10/site-packages/mockbuild/util.py", line 598, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed: 
 # bash --login -c /usr/bin/rpmbuild -bb --noclean --target s390x --nodeps /builddir/build/SPECS/texstudio.spec`

Full build log: [build.log](https://github.com/texstudio-org/texstudio/files/10070558/build.log)

**Comment by sunderme** [comment]
cmake -DTEXSTUDIO_ENABLE_CRASH_HANDLER=OFF ..... should do the trick.

**Comment by hannes101** [comment]
Thanks, will just do that, by any chance is there a list of the available options?

**Comment by sunderme** [comment]
I need to write instructions, so for now, no.

**Comment by sunderme** [comment]
But cmake is better at auto-detectiong, so there are less than before ...

**Comment by hannes101** [comment]
So currently, we were using the following:
%{qmake_qt5} \
%ifnarch %{ix86} x86_64 %{arm}
    NO_CRASH_HANDLER=1 \
%endif
    USE_SYSTEM_HUNSPELL=1 \
    USE_SYSTEM_QTSINGLEAPPLICATION=1 \
    INTERNAL_TERMINAL=1 \
    USE_SYSTEM_QUAZIP=1 QUAZIP_LIB=-lquazip5 QUAZIP_INCLUDE=%{_includedir}/quazip5/ \

Obviously, I didnt remember that the first option was presumably for a build failure on s390x :-)

**Comment by sunderme** [comment]
the other options should not be necessary any more as cmake detects the dependencies and acts accordingly.
USE_SYSTEM_QTSINGLEAPPLICATION seems to be fedora specific.

**Comment by hannes101** [comment]
The build just succeeded, thanks for the quick answer!
