### ISSUE TITLE
MacOS Icon 

### ISSUE THREAD

**Issue by ptoche** [texstudio-org/texstudio#2701]
After updating to 4.4.0 on MacOS Monterey, the icon has changed to something that is hard to see. Not sure if it's a new icon or a generic icon that is selected after the system failed to find the correct icon. For comparison, the new/generic icon is shown next to the old one. I looked inside texstudio.app/Contents/Resources/texstudio.icns and saw the old icon there. I know how to change the icon for one single file (as I did below), but not sure how to change it for all "tex" files, any suggestion welcome, thanks!

![icons](https://user-images.githubusercontent.com/6339274/203878539-3dface8a-74cc-4053-ab15-8e7a6eaa0659.jpg)

To clarify, just in case, the first icon is the "old" one that I would like to use, the second icon is the one that is currently showing for all "tex" files.

**Comment by sunderme** [comment]
Can you try txs 4.4.1beta1 from here https://github.com/texstudio-org/texstudio/releases/tag/4.4.1beta1

**Comment by ptoche** [comment]
That solved it, you're amazing!

Thank you!
