### ISSUE TITLE
TexStudio 4.4. 0 takes minutes to compile a file that 4.3.1 took seconds...

### ISSUE THREAD

**Issue by jpmaroco** [texstudio-org/texstudio#2703]
### Environment
- TeXstudio: 4.4.0
- Qt: Qt5.6.
- OS: <Win11 22H2
- TeX distribution: MikTex

### Expected behavior

LuaLaTex compilation take seconds to compile 50 page file

### Actual behavior
LuaLaTex takes minutes to compile the same file in TexStudio 4.4.0

**Comment by octaeder** [comment]
I tried with a book that has over 750 pages of A5. One run of lualatex took 3:34 (min:sec) with 4.3.1 and 3:20 with 4.4.0. For simplicity I assume 750 pages in 210 seconds and divide by 15. So I would expect 50 pages in 14 seconds, say 30 seconds when A4. The book draws some lindenmayer systems which are time and memory consuming. No real change here. Win10, Qt6.3.1.

**Comment by sunderme** [comment]
in principle, lualatex is just called by txs. So, there should not be any influence.
Are you really using qt5.6 ?

**Comment by jpmaroco** [comment]
From TexStudio's Help:
TeXstudio 4.4.0 (git 4.4.0)
A usar Qt versão 6.4.1, compilada com Qt 6.4.1 R

**Comment by sunderme** [comment]
so, there is no indication, it is txs fault.
if you want to follow up:
1) check compilation time on command shell vs txs.
2) if it can be demonstrated, that txs execution is slower, provide a example (document) which allows to replicate the situation.
