### ISSUE TITLE
Make the left and right parts of the Config Dialog resizable with a splitter

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2707]
Green arrow points to the splitter handle (for a larger version click on the image):

![SplitterInAction](https://user-images.githubusercontent.com/102688820/205197284-170eadfd-7480-48a4-a8de-ec20334b18e4.gif)

I'm working on that...

Thx

**Comment by sunderme** [comment]
the page selection should never collapse, icons only can be minimum width.
