### ISSUE TITLE
fake TOC entry in structure for quickly moving between different parts of long document

### ISSUE THREAD

**Issue by jzniu** [texstudio-org/texstudio#2708]
### Describe the feature and the current behavior/state

A feature (or bug) allowed in older versions of texstudio (up to 4.2.1 at least) but no longer working in 4.4.0 is to use things like the following in a document to artificially add an entry in the Structure panel, which is very convenient for me to quickly switch between different parts of a long document when those parts are not associated with any actual TOC entries.

`\iv{\subsubsection{Any text to show as an entry in Structure Panel}}`

where `\iv{}` eats its content and simply produces nothing in the result document. Here is a screenshot of texstudio 4.2.1 with this trick:

![Screenshot 2022-11-26 194247](https://user-images.githubusercontent.com/6538395/204114481-fc4e39c6-e1ee-4d77-9920-900cce6d1576.jpg)

The latest 4.4.0 version seems to have fixed this, which I totally understand as people may not want to produce an actual Section item for the document. However as you can see, there is benefit nevertheless. I hope you could support things like the following:

`% !TeX structure = \section{blabla}`

to allow artificial addition of an entry in the Structure panel only.

This would work better than bookmarks because these are embedded in the document directly shown in the Structure tree, which comes naturally. Bookmarks are not that visible and are limited when multiple documents are used and across texstudio sessions.

The `TODO` comment could help a bit for this particular purpose but the corresponding entry doesn't appear along with actual TOC entries in the Structure panel.

### Who will benefit with this feature?

Anyone who are editing a long document and needs to switch between different parts which are not associated with actual TOC items.

**Comment by sunderme** [comment]
looks like you basically do what `%TODO` is supposed to do.
Please use to that instead.

**Comment by sunderme** [comment]
original behavior was not intended, so there is no going back ...

**Comment by sunderme** [comment]
so, what you actually want is to have %TODO present under the section entries.
That is something, that can be done.

**Comment by sunderme** [comment]
I would strongly suggest to rephrase the title accordingly, or this will be lost.

**Comment by jzniu** [comment]
> so, what you actually want is to have %TODO present under the section entries. That is something, that can be done.

Yes, that will do. Even better if one could somehow specify which level the TODO entry is added in the section entries.

**Comment by sunderme** [comment]
it would be below the previous valid section.

**Comment by sunderme** [comment]
the term which is recognized is freely definable. So you could also use other terms and organize a bit more.

**Comment by sunderme** [comment]
by the way, how did you define `\iv`, because in principle that approach still works.

**Comment by jzniu** [comment]
> by the way, how did you define `\iv`, because in principle that approach still works.

No, it's doesn't work any more in txs 4.4.0. It works in 4.2.1. Didn't try 4.3.1.

The `\iv` command simply ignores the content:
`\newcommand{\iv}[1]{}%`

**Comment by jzniu** [comment]
> then it is unclear why it does not work on your side, it works here.

It's very weird. I tried to create a minimal document, but failed. However in the recording below see how it doesn't work in the long document I ran into the issue originally. I don't know what exactly caused the issue.

![2022-11-30_19-19-44](https://user-images.githubusercontent.com/6538395/204956081-a293d1a7-22fc-4cf1-bcb7-0cf74f16c937.gif)

It's strange to notice that `\i\section{Title}` works, but `\iv\section{Title}` or `\iv{\section{Title}}` doesn't in that document. If you know how the source code detects the TOC entries, you might be able to figure out what's wrong.

**Comment by sunderme** [comment]
without that document, there is nothing i can do.
You can try to rename your macro, and check if it is still the same outcome.

**Comment by octaeder** [comment]
I wonder where my old post is. So I repeat it here:

![grafik](https://user-images.githubusercontent.com/102688820/205051417-87124dc0-83fc-4da8-b9bc-20663d29e164.png)

Can you please clarify: Does this short example work on your machine? Document is created via wizard/Quick Start/OK and adding some lines.

Tested with Win10, TeXstudio 4.4.1 (git 4.4.1)
Using Qt Version 6.4.1, compiled with Qt 6.4.1 R

**Comment by jzniu** [comment]
> I wonder where my old post is. So I repeat it here:
> 
> ![grafik](https://user-images.githubusercontent.com/102688820/205051417-87124dc0-83fc-4da8-b9bc-20663d29e164.png)
> 
> Can you please clarify: Does this short example work on your machine? Document is created via wizard/Quick Start/OK and adding some lines.
> 
> Tested with Win10, TeXstudio 4.4.1 (git 4.4.1) Using Qt Version 6.4.1, compiled with Qt 6.4.1 R

This minimal example works on my 4.4.0 as well. However as I said earlier, the same line with `\iv{}` doesn't work in the particular long document I work on if I switch from 4.2.1 to 4.4.0. I cannot share with you guys that document. And I couldn't figure out a minimal example that reproduces the issue. I hope my animated recording above could give you some idea, like about how texstudio searches for section entries, but if you couldn't, that's okay.

**Comment by jzniu** [comment]
Now I sort-of figured out why commands like \iv{\section{title}} do not work as I want it to.

If \iv is collected and listed in a .cwl file, my trick stops working. So I manually remove the \iv entry from the cwl file and then it works. I guess whenever that .cwl file is regenerated automatically, I'll have to do it again.
