### ISSUE TITLE
Search again (F3) should not remove keyboard focus from the document editor

### ISSUE THREAD

**Issue by TomasRiker** [texstudio-org/texstudio#271]
### Environment
- TeXstudio: 2.12.10

### Expected behavior
Pressing F3 (search again) while the document editor has the keyboard focus should keep the document editor focused so that it's easy to perform modifications at the location where the search term was found.

### Actual behavior
The document editor loses keyboard focus, and the search box gains focus.

**Comment by li-po** [comment]
I had the same issue, and here is how I work now

- Ctrl-F
- enter the pattern
- Esc (or Esc Esc)
- F3, F3 as many time as needed and without the focus problem
- If you need to change the search pattern, Ctrl-F again

**Comment by JonathanLevine657** [comment]
I can't reproduce this with 3.1 on linux, fixed?
