### ISSUE TITLE
Some missing icons in version 4.4.0

### ISSUE THREAD

**Issue by helour** [texstudio-org/texstudio#2711]
- TeXstudio: 4.4.0
- OS: Windows 10, Manjaro Linux
- Qt: 5.9.5
- TeX distribution: miktex, texlive

Hello, some icons are missing in version 4.4.0 (Windows 10). These icons were in version 4.3.1 but are not in the latest version.
![MissingIcons](https://user-images.githubusercontent.com/79715809/204131303-60bf95d1-41de-4ac6-a078-644d85356023.png)
Please fix it if possible.
Thx

**Comment by sunderme** [comment]
already fixed
