### ISSUE TITLE
Show Old Revisions to be like "Show differences between two files"

### ISSUE THREAD

**Issue by DvP17** [texstudio-org/texstudio#2712]
This is a question and perhaps a feature request.

### Question
Under `File > SVN/GIT > Show old Revisions` you can see old commits for your file (I'm using git). However, I can only see the commit messages and the identifier number but not the actual revisions/changes like when browsing the file history or doing `Show differences between two files`. Is this supposed to be like that or is this a bug? 

### Feature Request
It would be great if one could compare changes between different versions inside TexStudio in a way it is done with `Show differences between two files`.

**Comment by sunderme** [comment]
looks like a bug
