### ISSUE TITLE
Commands (+ Package Commands) of custom template not recognized

### ISSUE THREAD

**Issue by GniLudio** [texstudio-org/texstudio#2723]
When importing (usepackage) or defining commands in my custom template,
they are not recognized in the LaTeX file.

When importing the package or defining the command directly in the LaTeX file,
TexStudio recognizes the commands.

Compiling works fine in both cases.

### Environment
- TeXstudio: 4.4.1
- Qt: 6.4.1
- OS: Windows 11 (same behavior on Linux Mint)
- TeX distribution: miktex

### Expected behavior
TexStudio should autocomplete commands, show parameter names, etc. of the stuff in the custom template.

### Actual behavior
When I try to use the custom commands and imported packages in the main LaTeX file, 
TexStudio doesn't recognize them:
![image](https://user-images.githubusercontent.com/50866361/205485452-6f1b7b29-d191-478b-a19e-b1760e81f5a5.png)

### How to reproduce
Import the `listings` package and define the command `helloWorld` in the custom template:
```
\usepackage{listings}
\newcommand\helloWorld{Hello World}
```

**Comment by sunderme** [comment]
well, take a look at the wiki: https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions#how-does-the-custom-highlighting-work
See also: https://texstudio-org.github.io/background.html#description-of-the-cwl-format

Summary: unknown packages are scanned for syntax but not for completion if they are in the tex system texmf.
Everything else needs to be provided by cwl files.

**Comment by sunderme** [comment]
The pointis **custom** class !
