### ISSUE TITLE
Texstudio editor sometimes stops accepting inputs

### ISSUE THREAD

**Issue by cxxszz** [texstudio-org/texstudio#2726]
I have Texstudio-4.4.1 on macOS Big Sur (11.7.1) and the editor frequently ignores my keyboard inputs.

This first happened last week when I was still using Texstudio-4.3.0 on macOS Catalina (10.15.8). I tried to address this issue by updating Texstudio from 4.3.0 to 4.4.1. Since this didn't work out, I upgraded my macOS from 10.15.8 to 11.7.1. I have also reinstalled Texstudio multiple times, both by compiling it from source and directly installing the dmg file provided by https://github.com/texstudio-org/texstudio/releases/download/4.4.1/texstudio-4.4.1-osx.dmg

However, this issue does not disappear. Originally, it happens several times within a day. Now it occurs every few minutes, which is intolerable. Does anyone have some suggestions?

Any advice would be greatly appreciated.

**Comment by sunderme** [comment]
you can try to compile against qt5 and you can try to use an older version 4.2.1  or even older.
Though it may also be a qt issue or something else.

**Comment by sunderme** [comment]
no feedback, no hint how to proceed.

**Comment by cxxszz** [comment]
> 

Sorry, I forgot to bring the latest update. After downgrading TexStudio to 3.0.0, the issue disappeared. Thanks a lot for the advice😀
