### ISSUE TITLE
How to change tab/indent size (to say 4)?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [texstudio-org/texstudio#2727]
### Environment
- TeXstudio: TeXstudio 4.3.1 (git 4.3.1)
- Qt: Version 6.3.1, compiled with Qt 6.3.1 R
- OS: Windows 10 20H2
- TeX distribution: miktex

### Description

* On enabling "Replace Indentation Tab by Spaces" 
* a tab character for indentation is replaced with 3 spaces, is this quantity of "3" intentional?
* i want to make it 4, is it possible in TeXstudio? how?

![image](https://user-images.githubusercontent.com/19423063/205677670-dda58278-0a48-4bd3-8455-d02b45a52e0b.png)

**Comment by sunderme** [comment]
<img width="903" alt="grafik" src="https://user-images.githubusercontent.com/14033169/205696933-56d07cb1-35c9-44b0-a5a1-096ad0aaa649.png">

**Comment by sunderme** [comment]
it does as it says.
If you use "replace indentation tab by spaces" and press space from col 0, n spaces are inserted.

**Comment by yashpalgoyal1304** [comment]
> n spaces are inserted

where is that n specified? for me, it's 3 spaces are inserted, i want the n to be 4

**Comment by yashpalgoyal1304** [comment]
okay :_1:
