### ISSUE TITLE
Searching for regular expressions with quantifiers ? * + in look-ahead groups does not work

### ISSUE THREAD

**Issue by UhrMensch** [texstudio-org/texstudio#2729]
### Environment
- TeXstudio: 4.2.3 and newer (and possibly older versions, too)
- Qt: 5 and 6
- OS: Windows 10
- TeX distribution: miktex

### Description

When searching the text (or replacing text) with regular expressions, the quantifiers ? * + do not work in look-ahead groups (?<=...). (It seems that no match is found at all if such a regex is searched for.) I assume that this is not connected to [Issue 2728](https://github.com/texstudio-org/texstudio/issues/2728) since contrary to that issue, it already existed in version 4.2.3 (but still is present in version 4.4.0), and here the sign | in the look-ahead expression and quantifiers outside of look-ahead expressions work fine.

### Expected behavior
Searching for the regular expression
(?<=a+)b
should find the "b" in "aab".

### Actual behavior
Searching for the regular expression
(?<=a+)b
seems to find nothing at all
Searching for (?<=a|b)c works as expected.

### How to reproduce
The issue is completely reproducible on my system and does not depend on the actual letters or expressions used.

**Comment by sunderme** [comment]
txs now uses perl regex compatible engine (QRegularExpression)
That engines thinks your expression is faulty: "lookbehind assertion is not fixed length"
I probably need to add a syntaxchecker/error reporter here.

**Comment by sunderme** [comment]
https://regex101.com/ seems to use a similar engine.

**Comment by UhrMensch** [comment]
Thank you for the quick answer and for clarifying! So I will adapt my macros.

Still, the fact that quantifiers ? * + are now non-greedy in trigger macros (as mentioned in [https://github.com/texstudio-org/texstudio/issues/2728](https://github.com/texstudio-org/texstudio/issues/2728)) is annoying. As far as I know, they are defined/expected too be greedy (if not followed by a ?), so I would consider this a bug.

**Comment by sunderme** [comment]
well, it is not a bug, I recommend reading this: https://github.com/texstudio-org/texstudio/issues/2465#issuecomment-1195678074

**Comment by UhrMensch** [comment]
Ok, thanks again for the clarification.
