### ISSUE TITLE
High load when opening project with multiple includes

### ISSUE THREAD

**Issue by bastie87** [texstudio-org/texstudio#273]
I am using Texstudio for a manual system.
It consists of a main file, some package includes and a file called structure - this then holds the outline and includes the tex-files. I'd say - about 300 included .tex files.
Whenever I open this project, texstudio becomes irresponsive for quite a while.

I'd love to contribute - but I need a starting point - is there any built-in option to measure the parts that take longest?

### Environment
- TeXstudio: current git
- Qt: 5.10.1
- OS: Fedora Linux 28, 64bit
- TeX distribution: texlive

### Expected behavior
Little delay

### Actual behavior
High delay

### How to reproduce
unsure.

**Comment by sunderme** [comment]
txs loads all included files automatically in memory, so that it can scan them for label/command definition.
If you don't want that, you can disable that behavior with option/editor/automatically load included files.

Apart from that, nothing we can do.
