### ISSUE TITLE
Localize DateTime display for last update

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2731]
The General config page shows date and time of last update check.

not typically german/english:
![grafik](https://user-images.githubusercontent.com/102688820/205923236-78465944-d321-4086-a250-d14e7718f2bb.png)
![grafik](https://user-images.githubusercontent.com/102688820/205923336-243ca54d-a8eb-4db2-a159-73c149425fa1.png)

look at this:
![grafik](https://user-images.githubusercontent.com/102688820/205923426-7c531d65-77a3-45a5-ada5-04a3210e8d8e.png)
![grafik](https://user-images.githubusercontent.com/102688820/205923453-f3429973-bbf0-4aa7-9450-8ae67a83cc55.png)

So I suggest following change:
`` QLocale::QLocale().toString(lastCheck, QLocale::ShortFormat)`` 
instead of
``lastCheck.toString("d.M.yyyy hh:mm")``

Shall I?

**Comment by sunderme** [comment]
sounds reasonable, so go ahead.
