### ISSUE TITLE
Change Title of Command Config Page

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2736]
The title

![grafik](https://user-images.githubusercontent.com/102688820/205975636-ed0a11e5-edbe-4e48-bf52-75d50cfbb55f.png)

is not a good page title and a complete duplicate of what can be found below the table (with or without adv. options)

![grafik](https://user-images.githubusercontent.com/102688820/205975915-d3968a30-a01d-4447-baba-487eec0f003a.png)

With respect to translation files should this be changed in the ui file or should I change the german translation only?

**Comment by sunderme** [comment]
As only half the languages are actively maintained, I would not change long standing texts without very good reason.
So, I would not change that particular title.
The translation should follow the original text, other wise any instructions in English will lead to wondering users.

**Comment by sunderme** [comment]
yes
