### ISSUE TITLE
spellchecker issue with `\%`, `\&`, etc.

### ISSUE THREAD

**Issue by mbertucci47** [texstudio-org/texstudio#2749]
### Environment
- TeXstudio: 4.4.1
- Qt: 6.4.1
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
TeXstudio should not mark as misspelled properly spelled words (or words with two letters or less) starting or ending with "escaped" symbols like `\%` and `\&`.

### Actual behavior
For `\$`, `\{`, and `\}`, the behavior is as expected. For `\%`, `\_`, `\&`, and `\#`, it marks the words misspelled.

<img width="250" alt="Screenshot 2022-12-09 150431" src="https://user-images.githubusercontent.com/61854785/206803376-645c5dec-c96f-41ec-bde7-d582f3bd1e96.png">

### How to reproduce
Source:
```latex
\documentclass{article}

\begin{document}

text\$	\$text
text\%	\%text
text\_	\_text
text\{	\{text
text\}	\}text
text\&	\&text
text\#	\#text

\end{document}
```

**Comment by sunderme** [comment]
I don't agree that e.g. text\& marked as misspelled is a bug.
There are names containing '&' possibly other characters which need to be spelled exactly one way. (e.g S&P)
Txs considers that character as part of the text which is checked.

**Comment by mbertucci47** [comment]
You're right, my initial requests were too extreme. If these symbols are to be treated like letters, however, I think that two-"letter" combinations like `A\%` should not be marked incorrectly spelled (demonstrated below) just like they aren't for inputs `xy` or `KB`. There is also some unexpected spellcheck behavior depending on whether or not the text containing one of the escaped characters is immediately followed by a linebreak. For example,

<img width="250" alt="Screenshot 2022-12-10 111818" src="https://user-images.githubusercontent.com/61854785/206869851-15a733a0-d4c0-41ac-a6f5-10205e20e051.png">

#### Source:
```latex
\documentclass{article}

\begin{document}

text\%
msspldtxt\%
text\% more text

text\#
msspldtxt\#
text\# more text

A\%	\%A
A\_	\_A
A\&	\&A
A\#	\#A

\end{document}
```

**Comment by sunderme** [comment]
I would stick with my approach.
If a user starts to use something like `A\%` or similar, it is probably a special abbreviation which will come up again.
If it is set to be ignored, deviations from that abbreviation will be marked, which is probably what the user needs.
