### ISSUE TITLE
Shift + mouse wheel scroll should scroll horizontally

### ISSUE THREAD

**Issue by yashpalgoyal1304** [texstudio-org/texstudio#2758]
### Describe the feature and the current behavior/state
In the embedded pdf viewer, when zoomed in, shift + mouse wheel should scroll horizontally

### Who will benefit with this feature?
Anyone using a normal mouse and using pdf zoom

### Any Other info
* TXS: 4.3.1
* Using Qt Version 6.3.1
* OS: Windows 10 20H2

**Comment by sunderme** [comment]
alt+scroll does that
