### ISSUE TITLE
 texmaker fails to start on ubuntu 18.10

### ISSUE THREAD

**Issue by marvin-ad-martianum** [texstudio-org/texstudio#276]
texmaker fails to start on ubuntu 18.10 
reinstall does not help, different sources also.

### Environment
- TeXstudio: 
  Installed: 2.12.10-1+3.1
  Candidate: 2.12.10-1+3.1
  Version table:
 *** 2.12.10-1+3.1 100
        100 /var/lib/dpkg/status
     2.12.10-0~201807041908~ubuntu18.04.1 500
        500 http://ppa.launchpad.net/sunderme/texstudio/ubuntu bionic/main amd64 Packages
     2.12.6+debian-2 500
        500 http://ch.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

- Qt: QT5
- OS:  Linux X1-18 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- TeX distribution: <! texlive but any should work -->

### Expected behavior
texmaker starts

### Actual behavior

marvin@X1-18:~$ texmaker 
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: dxcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)

~$ ldd /usr/bin/texstudio
	linux-vdso.so.1 (0x00007ffc80f68000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fcd16ff1000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fcd16dd4000)
	libpoppler-qt5.so.1 => /usr/lib/x86_64-linux-gnu/libpoppler-qt5.so.1 (0x00007fcd16b5b000)
	libQt5PrintSupport.so.5 => /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so.5 (0x00007fcd168ec000)
	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007fcd160a5000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007fcd1593c000)
	libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007fcd155b0000)
	libQt5Xml.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5 (0x00007fcd15374000)
	libQt5Script.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Script.so.5 (0x00007fcd14ede000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007fcd14793000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fcd14574000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fcd141e6000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fcd13e48000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fcd13c30000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcd1383f000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fcd13617000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fcd13413000)
	libpoppler.so.73 => /usr/lib/x86_64-linux-gnu/libpoppler.so.73 (0x00007fcd12f7f000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007fcd12cf3000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fcd12ac1000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fcd12823000)
	libicui18n.so.60 => /usr/lib/x86_64-linux-gnu/libicui18n.so.60 (0x00007fcd12382000)
	libicuuc.so.60 => /usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007fcd11fcb000)
	libdouble-conversion.so.1 => /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.1 (0x00007fcd11dba000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fcd11aa4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcd18213000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fcd118a0000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fcd1169a000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fcd113e6000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fcd111a1000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007fcd10f39000)
	libnss3.so => /usr/lib/x86_64-linux-gnu/libnss3.so (0x00007fcd10bf5000)
	libsmime3.so => /usr/lib/x86_64-linux-gnu/libsmime3.so (0x00007fcd109c9000)
	libnspr4.so => /usr/lib/x86_64-linux-gnu/libnspr4.so (0x00007fcd1078c000)
	liblcms2.so.2 => /usr/lib/x86_64-linux-gnu/liblcms2.so.2 (0x00007fcd10534000)
	libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007fcd102bd000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007fcd1008c000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007fcd0fdd6000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fcd0fba9000)
	libicudata.so.60 => /usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007fcd0e000000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fcd0dd8e000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fcd0db79000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fcd0d947000)
	libnssutil3.so => /usr/lib/x86_64-linux-gnu/libnssutil3.so (0x00007fcd0d718000)
	libplc4.so => /usr/lib/x86_64-linux-gnu/libplc4.so (0x00007fcd0d513000)
	libplds4.so => /usr/lib/x86_64-linux-gnu/libplds4.so (0x00007fcd0d30f000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fcd0d107000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fcd0cee1000)
	libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 (0x00007fcd0ccd3000)

**Comment by sunderme** [comment]
I am confused, texstudio and texmaker are two completely different programs.

**Comment by marvin-ad-martianum** [comment]
AH, did I mix it? Both programs produce the same error and since it sais
the following on the texstudio page I thought they are still quite close in
parts.

TeXstudio has been forked from Texmaker <http://www.xm1math.net/texmaker/> in
2009, because of the non-open development process of Texmaker and due to
different philosophies concerning configurability and features. Originally
it was called TeXmakerX because it started off as a small set of extensions
to Texmaker with the hope that they would get integrated into Texmaker some
day. While at some points you can still see that TeXstudio originates from
Texmaker, significant changes in features and the code base have made it to
a fully independent program.

marvin@X1-18:~$ texstudio
This application failed to start because it could not find or load the Qt
platform plugin "xcb"
in "".

Available platform plugins are: dxcb, eglfs, linuxfb, minimal, minimalegl,
offscreen, vnc, xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
marvin@X1-18:~$ texmaker
This application failed to start because it could not find or load the Qt
platform plugin "xcb"
in "".

Available platform plugins are: dxcb, eglfs, linuxfb, minimal, minimalegl,
offscreen, vnc, xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
marvin@X1-18:~$

**Comment by sunderme** [comment]
if both fail, then you have quite a good indication, that you have a system issue.
Wayland ? xwayland missing ? or qt5/wayland plug-in ?
