### ISSUE TITLE
Recognize Russian bibliography entries (\RBibitem)

### ISSUE THREAD

**Issue by ramayasket** [texstudio-org/texstudio#2764]
### Describe the feature and the current behavior/state
Suggested: TeXstudio recognizes \RBibitem bibliography entries and suggests their names when I type \cite{}
Current state: TeXstudio only recognizes standard \bibitem entries

### Who will benefit with this feature?
The authors who use Russian bibliography entries

**Comment by mbertucci47** [comment]
@ramayasket which package provides the command `\RBibitem`?

**Comment by ramayasket** [comment]
That's amsbib 
https://github.com/SergejZnamenskij/amsbib

**Comment by sunderme** [comment]
seems not to be a ctan package.
