### ISSUE TITLE
Toolbar illegible colour

### ISSUE THREAD

**Issue by Atcold** [texstudio-org/texstudio#2767]
### Environment
- TeXstudio: 4.4.1
- Qt: 6.4.1
- OS: Mac.
- TeX distribution: N/A

### Expected behaviour

The text on the toolbar should be readable (light colour on dark background).
(Also the ‘undo’ and ‘redo’ arrows could use a brighter blue, for visibility purposes.)

### Actual behaviour

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/2119355/207153255-043e3815-2d60-4502-af69-2c598fd9e733.png">

**Comment by sunderme** [comment]
looks rather like dark-mode is not detected.
please provide a complete image of txs.
Also, how was the dark-mode triggered.

**Comment by Atcold** [comment]
My Mac is just set on dark.
This is how the interface looks.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/2119355/207443543-dc240b52-7424-4ebd-bf39-11c51db10e1b.png">

**Comment by sunderme** [comment]
Have you tried to use another icon theme ?

**Comment by sunderme** [comment]
by the way, what is set in color scheme and style ?

**Comment by sunderme** [comment]
looking at the picture again, txs uses dark-mode, the unexpected part is that the characters in the drop-down (like `\left(` or `part`) are still black.

**Comment by geolta** [comment]
Hi, the screenshot indeed uses the icons for dark mode. The problem is though, that different dark modes use different shades of gray and therefore for some dark modes, the colors are too dark while for others, they are too light.

My original colors were chosen accordingly to what [rizmut](https://github.com/rizmut/libreoffice-style-colibre) the creator of the icon theme, used. For the creation of the dark mode icons, I used a script. Can you send the exact colors you changed, so I can adjust the script (I think, I will add it to the folder of the icons)?

**Comment by sunderme** [comment]
@Atcold have you tried a current dev build to check if the colors are better ? (see https://github.com/texstudio-org/texstudio/actions/workflows/cd.yml )

**Comment by Atcold** [comment]
> Have you tried to use another icon theme?

The icon theme does not affect the text colour.

> by the way, what is set in colour scheme and style?

- macOS
- Modern - dark
- Colibre

> […] different dark modes use different shades of gray

I'm confused. All Macs use the same dark mode.

> and therefore for some dark modes, the colors are too dark while for others, they are too light.

If the background is dark, the font should be bright.
Here it is back.

<img width="165" alt="image" src="https://user-images.githubusercontent.com/2119355/209530637-167da625-ccf3-4da5-ae8b-4a2b1e7e0ea4.png">

> My original colors were chosen accordingly to what [rizmut](https://github.com/rizmut/libreoffice-style-colibre) the creator of the icon theme, used.

I can read the text from rizmut's style. They are not black.

<img width="439" alt="image" src="https://user-images.githubusercontent.com/2119355/209530953-a34daf01-8097-4f17-9bba-1285afb6fdce.png">

> Can you send the exact colors you changed, so I can adjust the script (I think, I will add it to the folder of the icons)?

I did not change anything. This is what it looks like out of the box.

> @Atcold have you tried a current dev build to check if the colors are better? (see https://github.com/texstudio-org/texstudio/actions/workflows/cd.yml )

Nothing's changed.
https://user-images.githubusercontent.com/2119355/209531652-6d5fb964-8339-4bff-b386-0d1f52a02d0c.mov

**Comment by sunderme** [comment]
I have looked at a mac.
Please change the style to "classic" and then the colors are basically given by colibre & osx.

**Comment by Atcold** [comment]
Yup, that did work. Thanks.
Still, the bug still stands.

**Comment by sunderme** [comment]
the issue seems to be the macOS style with manhattan color scheme.
colibri icon scheme seems to be okay.
So, I create a new issue for macOS/manhattan issue

**Comment by geolta** [comment]
> > Can you send the exact colors you changed, so I can adjust the script (I think, I will add it to the folder of the icons)?
> 
> I did not change anything. This is what it looks like out of the box.

Sorry, I was referring to the wrong person, sorry :D

**Comment by groverlynn** [comment]
@geolta All colors are from the light theme, but applied differently on the dark theme.

- Gray: #fafafa (lighter) #c8c6c4 (light) #797774 (dark) #3a3a38 (darker)
- Red: #ff9198 (light) #ed3d3b (medium) #d42314 (dark)
- Blue: #83beec (lighter) #7bcbff (light) #1e8bcd (dark) #0063b1 (darker)
- Purple: #d492d8 (light) #a846b2 (medium) #922e9b (dark)
- Orange: #f8db8f (light) #fb983b (medium) #ed87cc (dark)
- Green: #a1ddaa (light) #309048 (dark)
