### ISSUE TITLE
Crash compiling with LuaLaTex texstudio 4.1

### ISSUE THREAD

**Issue by jpmaroco** [texstudio-org/texstudio#2769]
### Environment
- TeXstudio: 4.4.1
- Qt: 6.4.1
- OS: Win11 22H2
- TeX distribution: Miktex 

### Actual behavior
Crash when compiling 

### How to reproduce

LuaLateX compiling!

**Comment by jpmaroco** [comment]
well, reverted to 4.3.1 with qt6... working like a charm. I have no clue why 3.4.1 crashes when compiling... it gives no error messages.

**Comment by octaeder** [comment]
Problem with vcruntime? See [here](https://github.com/texstudio-org/texstudio/issues/2664#issuecomment-1307787069).

**Comment by sunderme** [comment]
please provide a test case, otherwise there is really nothing that can be done.

**Comment by jpmaroco** [comment]
%Compile with `LuaLatex'
\documentclass[../Book.tex]{subfiles}
\usepackage{tabularray}
\begin{document}
\begin{resumo}{\textsf{Estatística Descritiva}}{ex:EstDescr}
	\setlist{nolistsep}	
\begin{tabresumo}
\begin{enumerate}[label=\Alph*.]
\item \textbf{Para que serve?}
\begin{enumerate}[label=\roman*.,leftmargin=*]
\item Caracterizar variáveis quanto à sua tendência central, dispersão e forma.
\end{enumerate}
\item \textbf{Quando se aplica?}
\begin{enumerate}[label=\roman*.,leftmargin=*]
\item Quando é necessário descrever caracterizar as variáveis (amostra)
\end{enumerate} 
\item \textbf{Estatísticas}

\vspace*{2mm}
\renewcommand{\arraystretch}{1.1}
{\footnotesize 
\begin{tblr}{Q[l,t]Q[l,t]Q[l,t]Q[l,t]}
	\hline 
	{Escala de\\Medida} & {Medidas de\\ Tendência Central} & {Medidas de Dispersão} & {Medidas de Forma} \\
	\hline 
	Nominal & {$Mo=$ valor mais\\frequente} &--& --	\\
		\hline 
	Ordinal & {$Mo$ \\$\tilde{Y}=$ valor central} & $AIQ=Q3-Q1$ &-- \\
		\hline 
	Quantitativa & {$Mo$\\$\tilde{Y}$\\$\bar Y=\dfrac{\sum\limits_{i=1}^{n}Y_i}{n}$} & {$AIQ$\\$S'=\dfrac{\sum\limits_{i=1}^{n}Y_i^2\!-\!n\!\bar Y^2}{n\!-\!1}$\\$CV=\dfrac{S'}{|\bar Y|}\times 100\%$} & {$sk=\dfrac{n^2M_3}{(n\!-\!1)(n\!-\!2)S'^3)}$\\ $ku =\dfrac{n^2(n+1)}{(n\!-\!1)(n\!-\!2)(n\!-\!3)}\cdot$\\ \qquad $\dfrac{M_4}{S'^{4}}\!-\!3 \dfrac{(n\!-\!1)^{2}}{(n\!-\!2)(n\!-\!3)}$}\\
	\hline
\end{tblr}}
\vspace*{2mm}
\item \textbf{\textit{Outliers}}
\item [] Inferior moderado: $y_i \le Q1-1.5\times AIQ$ \quad \, Extremo: $y_i \le Q1-3\times AIQ$
\item [] Superior moderado: $y_i \ge Q3+1.5\times AIQ$ \quad Extremo: $y_i \le Q3+3\times AIQ$

\end{enumerate}
\end{tabresumo}
\end{resumo}
\end{document}

**Comment by sunderme** [comment]
incomplete

**Comment by sunderme** [comment]
insufficient info
when you can demonstrate a crash with a complete example which allows replication of the issue, please open a new issue.
