### ISSUE TITLE
bibliographic entries disappeared

### ISSUE THREAD

**Issue by parpamgr** [texstudio-org/texstudio#2774]
suddenly opening the file "bibliography_bib.bib" containing the entries 
the data of the entries not shown. Opening the same file
in Editt++ everything appears as it should.
What did suddenly happen and caused this change?
![entries disapear !!!!](https://user-images.githubusercontent.com/86319225/208036024-df3265ba-c2e3-40a2-a13e-14306f5df253.png)

**Comment by sunderme** [comment]
any special reason to ignore **all** instructions on how to make a issue request ?

**Comment by sunderme** [comment]
if I have to guess wildly, you fiddled with the syntax highlighting.

**Comment by parpamgr** [comment]
You are right. I apologize.

Στις Παρ 16 Δεκ 2022 στις 7:37 μ.μ., ο/η sunderme ***@***.***>
έγραψε:

**Comment by sunderme** [comment]
so, we can close this ?

**Comment by parpamgr** [comment]
yes

Στις Κυρ 18 Δεκ 2022 στις 4:37 μ.μ., ο/η sunderme ***@***.***>
έγραψε:

**Comment by parpamgr** [comment]
... where are all these instructions

Στις Παρ 16 Δεκ 2022 στις 7:37 μ.μ., ο/η sunderme ***@***.***>
έγραψε:

**Comment by sunderme** [comment]
The preset text in the issue report?

**Comment by parpamgr** [comment]
yes

Στις Δευ 19 Δεκ 2022 στις 12:45 μ.μ., ο/η sunderme ***@***.***>
έγραψε:
