### ISSUE TITLE
Partial placeholders and use of argument names in cwl format

### ISSUE THREAD

**Issue by thatlittleboy** [texstudio-org/texstudio#278]
### Environment
- TeXstudio: 2.12.10 (git bd838cd)
- Qt: 5.8.0
- OS: Windows 10 64bit
- TeX distribution: MikTeX

In the cwl format, what is the correct way to declare args with (i) only part of the option marked as a placeholder, via `%<...%>` while also making use of (ii) the pre-defined argument names?

E.g., suppose we have the definition and test scenario:
```
\documentclass{article}
\usepackage{graphicx}
\newcommand{\testcmd}[3]{%
    \begin{figure}[htbp]
        \includegraphics{#1}
        \caption{#2}
        \label{#3}
    \end{figure}
}
\begin{document}
    \testcmd{example-image}{This is an example image with wrong spellng.}{fig:testfig}
    \ref{fig:testfig}
\end{document}
```

and we want the following behaviour for the completion:

- The completion prompt to read: `\testcmd{<imagefile>}{<caption>}{fig:<label>}` where the `<...>` only serve to represent the placeholder location.
- Spelling checks to be in place for the second argument (i.e., treat caption as text).
- The entire `fig:label` argument to be provided as completion suggestion in `\ref{...}`.

Because of the partial completion in the third argument for the label, we are forced to use the following:
```
\testcmd{%<imagefile%>}{%<caption%>}{fig:%<label%>}#l
```

So far so good. But now, there are a few issues:

- Caption is not spell-checked. For that, we need to declare a `%text` suffix as per the user manual.
- The label argument isn't being recognized as a label. For that, we need `%labeldef` suffix. 

The question is, how to incorporate these suffixes into the cwl declaration?

---------------

The following combinations do not work:
```
\testcmd{%<imagefile%>}{%<caption%>%text}{fig:%<label%>%labeldef}#l
\testcmd{%<imagefile%>}{%<caption%text%>}{fig:%<label%labeldef%>}#l
```

whereas the typical command declarations without partial placeholders work: e.g.,

```
\testcmd{imagefile}{text}{label}#l
\testcmd{imagefile}{caption%text}{othertext%labeldef}#l
```

I expect the first combination declaration to work, since the user manual states: 

> A %-suffix takes precedence over detection by name, i.e. an argument file%text will be treated as text not as file.

yet this behaviour is not respected once partial placeholder syntax (`%<...%>`) is used. Am I missing something here?

**Comment by sunderme** [comment]
there will not be any partial place holders.
You can define a second line with placeholders which don't hold syntax info for completion only.
You can play around which order the two lines have have in the cwl file to work.

**Comment by thatlittleboy** [comment]
Okay, this works. 
```
\testcmd{%<imagefile%>}{%<caption%>}{fig:%<label%>}#l
\testcmd{imagefile}{caption%text}{othertext%labeldef}#S
```

Thanks @sunderme, I'll leave it to you to decide if it's worth keeping this open as enhancement or close it if you have no intention to support this (by which, I mean having the syntax to achieve this in 1 line; without having to resort to using two cwl lines).

**Comment by thatlittleboy** [comment]
Okay, this works:

```
\testcmd{%<imagefile%>}{%<caption%>}{fig:%<label%>}#l
\testcmd{imagefile}{text}{label}#S
```
![texstudio_2018-08-12_17-14-05](https://user-images.githubusercontent.com/30731072/44006518-b40d27f4-9e53-11e8-9644-908e157625f6.png)

(spellcheck is on for the second argument, and the third argument with partial placeholder is correctly recognized as a label.)


Thanks @sunderme, I'll leave it up to you whether to leave this issue open as a potential enhancement (to achieve this without having to resort to using 2 cwl lines) or to close it if you have no intention to support this.

**Comment by sunderme** [comment]
you are the first to play around this way. No need to change lots of code for this if it can allready be implemented via two lines in cwl.
