### ISSUE TITLE
Online templates not found

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#2780]
### Environment
- TeXstudio: 4.4.2 (git N/A)
- Qt: version 5.15.2
- OS: Mageia 8

### Expected behavior
The online templates are found.

### Actual behavior
The online templates are listed. But not found.
### How to reproduce
Menu File → New From Template → Online Repository → testing → template_Article → OK results in:

>File not found:
>/home/bitouze/.config/texstudio/cachedTemplates//testing/template_Article.tex

**Comment by sunderme** [comment]
Apparently another qt5 issue.
I will fix it later.

**Comment by dbitouze** [comment]
Despite commit https://github.com/texstudio-org/texstudio/commit/401520f39aa338ee934a2d6eba3708d7c0e67d06, still a popup with (only): “File not found:”

**Comment by sunderme** [comment]
can you delete cachedTemplates/*
