### ISSUE TITLE
Make “Online Repository”  translatable

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#2781]
### Environment
- TeXstudio: 4.4.2 (git N/A)
- Qt: version 5.15.2
- OS: Mageia 8

### Expected behavior
The “Online Repository” string is translatable.

### Actual behavior
The “Online Repository” string is not translatable.

### How to reproduce
1. Menu: Options → Configure TXS... → General → Language → French → OK
2. Menu: Fichier → Nouveau à partir d'un modèle → Online Repository.

**Comment by sunderme** [comment]
Translation needs to go through several steps.
It will be translatable later.
