### ISSUE TITLE
“Online Repository” item shouldn't be collapsed

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#2782]
### Environment
- TeXstudio: 4.4.2 (git N/A)
- Qt: version 5.15.2
- OS: Mageia 8

### Expected behavior
The “Online Repository” item shouldn't be collapsed.

### Actual behavior
The “Online Repository” item is collapsed.

### How to reproduce
Menu: Menu File → New From Template and see:
- “Builtin” item isn't collapsed,
-  “User” item isn't collapsed,
-  “Online Repository” item is collapsed.

**Comment by sunderme** [comment]
This is intentional since online access is not triggered before manually expanding it.
One reason is that github limitsbthe number of api accesses.
