### ISSUE TITLE
PHONON support is not ported to cmake build stack

### ISSUE THREAD

**Issue by idamir** [texstudio-org/texstudio#2784]
Qmake build stack supports phonon for the video player in pdf files.
Cmake stack lost phonon using.

**Comment by sunderme** [comment]
indeed.
So, do you build txs with phonon ?

**Comment by sunderme** [comment]
as far as I see it, phonon is deprecated and there is no Qt6 variant.
So, unless someone ports that functionality to qtMultimedia, that functionality will be lost.

**Comment by idamir** [comment]
txs in Debian is built with phonon.
However, since Qt5 phonon is substituted by QtMultimedia. May be txs should be migrated to QtMultimedia?

**Comment by sunderme** [comment]
so, you can open a feature request for that port.
cmake will not support phonon. (qmake is still functional, so probably only building needs to be tweaked.)
