### ISSUE TITLE
Project home site link: “https://texstudio.org/” in the “About dialog” opens a local random file

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#2786]
### Environment
- TeXstudio: 4.4.2 (git N/A)
- Qt: 5.15.2
- OS: GNU/Linux Mageia 8

### Expected behavior
Project home site link: “https://texstudio.org/” in the “About dialog” should go to https://texstudio.org/.

### Actual behavior
Project home site link: “https://texstudio.org/” in the “About dialog” opens a local random file (e.g.  `file:///home/bitouze/.cache/kioexec/krun/1009707_0/unnamed`) in my default browser (Firefox).

**Comment by sunderme** [comment]
works here (ubuntu, using latest release (ppa) )

**Comment by dbitouze** [comment]
> works here (ubuntu, using latest release (ppa) )

Sigh... Here TXS has been built with `sh BUILD.sh` and:

- Enter SYSTEM:  UNIX
- Enter PREFIX: `/usr/local`
- Enter path to QT4/5 base directory: `/usr/lib64/qt5`
- Enter path to QT4/5 executable file: `cmake`
- Do you want to use the internal pdf viewer: yes
- Do you want to use the video player in pdf files: no
- Do you want an internal terminal widget: yes
- Do you want to build a debug or release version?: debug
- Do you want to include tests in the debug build?: yes
- Do you want to enable the debug logger? no
- Do you want to install TexStudio after building it? yes

and everything went smoothly, except:

> CMake Error: The source directory "/home/bitouze/Public/Repositories/texstudio/CONFIG-=release" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by sunderme** [comment]
I am a bit confused how you got a cmake error with BUILD.sh which does not use cmake at all.

**Comment by sunderme** [comment]
looking at the code, the link is a html link in a html text.
So, any action coming from that is qt and qt alone, nothing I can do.

**Comment by octaeder** [comment]
Works with Win10 and FireFox as expected (txs 4.4.1 or dev).

**Comment by dbitouze** [comment]
> I am a bit confused how you got a cmake error with BUILD.sh which does not use cmake at all.

That's because, at 4th step above, I asked for it as QT4/5 executable file, instead of `qmake` or `qmake-qt5`. But the result is the same them.

**Comment by octaeder** [comment]
Maybe you can change the adwaita text "link" (https://github.com/FedoraQt/adwaita-qt) into a html link and retest. There are also two positions where strings are concatenated without a plus sign. I'll provide PR #2788 2788 for both now.

**Comment by dbitouze** [comment]
> Maybe you can change the adwaita text "link" (https://github.com/FedoraQt/adwaita-qt) into a html link and retest. There are also two positions where strings are concatenated without a plus sign. I'll provide PR #2788 for both now.

I tested with TXS that contains:

> 82c08d226 (upstream/master) About dialog - adwaita link (#2788)

but, the problem remains. For instance, cliking on the link “https://github.com/FedoraQt/adwaita-qt” in the “About TeXstudio” popup opens in my default browser (Firefox) the file: `file:///home/bitouze/.cache/kioexec/krun/1660841_0/adwaita-qt`.

**Comment by octaeder** [comment]
I searched for "kioexec cache links" and found this [link](https://askubuntu.com/questions/1277683/links-from-apps-always-open-a-file-url). Does this help?

**Comment by dbitouze** [comment]
Indeed, thanks!
