### ISSUE TITLE
some actions don't use position of edit contextmenu for actions

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2794]
Not sure if this is a bug or a feature. I currently observe that I often can't start a preview of an environment via context menu. The reason for this is that it only works when the cursor is moved to the opening or closing part of the environment (i.e. somewhere in \begin{xyz} or \end{xyz}) and then use Preview from the context menu (i.e. without having selected the whole code including the environment).  By the way a nice feature. But I often forget the condition for this procedure: First move the cursor there. It is not sufficient that the pointer is there. Maybe I'm used to the fact that right click moves the cursor mark to the location (or at least to the line) of the pointer (see notepad++ as an example).

Win10, txs 4.4.1, Qt6, MikTeX

**Comment by sunderme** [comment]
just out of curiosity, you had a prefilled issue report or was it empty ?

**Comment by octaeder** [comment]
It was prefilled (other template).

**Comment by sunderme** [comment]
I am not changing the cursor movement on right-click.

if I am not mistaken, the complaint is that right click on `\begin..` and then choosing preview does not preview that construct, right ?

**Comment by octaeder** [comment]
Yes, because before right click the cursor is somewhere far away and the right click doesn't move the cursor. So I have to learn that I need to do a left click (or at least check if the cursor is at the desired position) first and then use a right click (which hence can be done anywhere) to open the menu.

Since I expected that this behavior would affect not only Preview Parenthesis/Selection I tried with Thesaurus... and it doesn't move the cursor either but uses the word at pointer position:

Cursor in second word, pointer over the fourth one:

![grafik](https://user-images.githubusercontent.com/102688820/209318017-bbc4c26f-644e-4594-a868-645d7e02124e.png)

Menu opens at pointer's position:

![grafik](https://user-images.githubusercontent.com/102688820/209318239-9528d2ad-02b6-401a-9de6-653e58506f34.png)

and surprisingly Thesaurus... uses the word under the pointer:

![grafik](https://user-images.githubusercontent.com/102688820/209318345-a47e7b35-0598-4061-8ee7-c8cb2e0aa349.png)

Hey, that's what I would like to have if possible.

**Comment by sunderme** [comment]
the issue is that the context menu just uses the "preview command" which can also be triggered by pressing alt+p and so it uses the current cursor as point of reference.
You can probably adapt to use the context menu point for reference...
