### ISSUE TITLE
keyword highlighting

### ISSUE THREAD

**Issue by parpamgr** [texstudio-org/texstudio#2795]
strange behavior of keyword highlighting

### Environment
- TeXstudio: Version 4.4.0
- Qt:   6.4.1 compiled with Qt 6.4.1 R  
- OS:  Windows (11)  
- TeX distribution:  miktex 

### Expected behavior
uniform highlighting

### Actual behavior
![bad highliting](https://user-images.githubusercontent.com/86319225/209281848-6bac11e0-7b44-4c5c-872a-e0ba2eb30deb.png)

### How to reproduce
don't know for your machine 
![bad highliting](https://user-images.githubusercontent.com/86319225/209282013-60725081-3600-4d31-ab78-f92ad1706441.png)

**Comment by muzimuzhi** [comment]
Do you have any (active) user `.cwl` files?

**Comment by parpamgr** [comment]
... yes. I see the problem. Must complete with all keywords used ...
I apologize ...

Στις Παρ 23 Δεκ 2022 στις 8:27 π.μ., ο/η muzimuzhi ***@***.***>
έγραψε:
