### ISSUE TITLE
This tool has been deprecated, use 'gio open' instead.

### ISSUE THREAD

**Issue by jonasstein** [texstudio-org/texstudio#28]
Opening the user manual

![selection_467](https://user-images.githubusercontent.com/298682/35782396-9b9e32da-09f7-11e8-8263-f8c2df0cd4ad.png)

raises the warning on stderr/stdout:

```
This tool has been deprecated, use 'gio open' instead.
See 'gio help open' for more info.
```

**Comment by timhoffm** [comment]
We're just using `QDesktopServices::openUrl("file:///" + latexHelp)` (http://doc.qt.io/qt-5/qdesktopservices.html).

This is probably a configuration issue on your desktop concerning the standard tool to open html files.

**Comment by jonasstein** [comment]
Thank you for the pointer. I saw this on a Mate 1.18 desktop. I will try to find out more.

**Comment by genodeftest** [comment]
The message itself is being caused by calling `gvfs-open`,  a deprecated part of GNOME's virtual file system implementation.
Since I cannot reproduce this warning on a updated GNOME desktop (3.26 on Fedora 27), I guess it is caused by a misconfiguration or a bug in Mate.
