### ISSUE TITLE
TexStudio doesn't detect packages or class files in local texmf folder

### ISSUE THREAD

**Issue by ShaiAvr** [texstudio-org/texstudio#2800]
### Environment
- TeXstudio: 4.4.1 (git 4.4.1)
- Qt: 6.4.1, compiled with Qt 6.4.1 R
- OS: Mac
- TeX distribution: texlive

I am using TexStudio for my homework assignments, both because I think it's a great Latex editor and because it's one of the only editors I found that display RTL text nicely (I am working in Hebrew).
I made a personal `homework.cls` class file to have all my customizations and personal commands and I wanted to install it in my local `texmf` folder to have access to it globally (since I use it in almost every project and it becomes tedious to copy it around everywhere).
While everything compiles successfully and documents turn out completely as expected, it seems that TexStudio fails to recognize my class file whether it's right next to the project files or if it's in the `texmf` folder. Look at this screenshot:

<img width="1440" alt="Screenshot 2022-12-24 at 13 43 04" src="https://user-images.githubusercontent.com/35605235/209434926-3682d82d-7fc1-47a2-a528-8fe81bd8ff9a.png">

As you can see, in the main file, TexStudio fails to find the class file, and wherever I use a command which is loaded from this file, TexStudio thinks it's undefined and fails to provide auto-completion. If I have the `cls` file open in TexStudio, then it manages to find the commands and provide auto-completion, but in the main file, it still says that the homework class is not found.

A screenshot of the `TEXMFHOME` variable and the `texmf` directory structure is also provided:
<img width="1440" alt="Screenshot 2022-12-24 at 13 58 49" src="https://user-images.githubusercontent.com/35605235/209435112-b44e7f60-b040-444f-8832-4c2589672f34.png">

Once again to be clear, everything **compiles fine**. The problem is that TexStudio fails to find the corresponding files and provide auto-completion. Is there a way to make TexStudio find files in the local `texmf` folder, so I get no warnings and auto-completion?

Even if the class file is in the project folder, TexStudio can't recognize it which is really odd. How can I fix this?

**Comment by octaeder** [comment]
Please have a look at #2723. Does it give the answer?

**Comment by ShaiAvr** [comment]
@octaeder So, if I understand correctly, I need to create a `cwl` file for my class file and put it in the settings directory of TexStudio and then it should work?

I can try it, but my class is quite big (I have many custom commands and more are going to be added as time goes on), so do I really need to create a matching `cwl` file?

I think it's quite tedious. Is there a way to make it automatic, or perhaps provide the `texmf` folder to TexStudio so it can scan the class files itself?

**Comment by mbertucci47** [comment]
@ShaiAvr In my setup (Windows 10, miktex) texstudio auto-generates cwls for sty/cls files in my texmf tree. You do need to close and reopen texstudio for this to happen. It will place the cwl in `...\texstudio\completion\autogenerated`; you can move it to `...\texstudio\completion\user` and remove the `#S` after the commands you want auto-completed.

**Comment by ShaiAvr** [comment]
@octaeder I tried to create a `cwl` file and it indeed worked for highlighting and auto-completion. However, one problem remains: TexStudio still says that the class is not found in the main file when I declare `\documentclass{...}`. Here's a screenshot:

<img width="1440" alt="Screenshot 2022-12-25 at 16 39 00" src="https://user-images.githubusercontent.com/35605235/209472258-2e2b2b50-e543-4f5c-aa39-ad3f31037ad3.png">

Is there a specific command for the `cwl` file to make TexStudio recognize the "missing" `homework-hebrew` class?
The file is named `homework-hebrew.cwl` like the class file and is placed in `~/.config/texstudio/completion/user` as it should be.

**Comment by sunderme** [comment]
class detection checks the texlive package database.
Just ignore it.
