### ISSUE TITLE
Spellchecking for Russian

### ISSUE THREAD

**Issue by kuznetsov2** [texstudio-org/texstudio#281]
### Environment
- TeXstudio: 2.12.10 (git n/a)
- Qt: 5.6.1
- OS: Linux Deepin 15.6
- TeX distribution: texlive

### Expected behavior
in texstudio 12.4 spellchecking for Russian works well

### Actual behavior
in 12.10 neither LanguageTool nor standard spellchecking via dictionary not working for Russian, but works well for English

**Comment by sunderme** [comment]
you have downloaded a russian dictionary (hunspell - ru) and pointed txs to use that (option/language) ?

**Comment by sunderme** [comment]
works fine on ubuntu

**Comment by sunderme** [comment]
in /usr/share/hunspell, you need a .aff and a .dic file.
The .aff describes the encoding of the .dic. In all likelihood, something is wrong there.
