### ISSUE TITLE
Hard returns and broken lines

### ISSUE THREAD

**Issue by mauvia2018** [texstudio-org/texstudio#2812]
### Environment
- TeXstudio: 4.4.1 (git 4.4.1) 
- Qt: 6.4.1
- OS: MACOS
- TeX distribution: miktex

### Description
I moved to macOS from Win10 and as a Latex user I moved from WinEdt (under Win), a LaTeX editor, to TexStudio, under MacOS. I noticed that with WinEdt (with appropriate settings) I can create a document with one paragraph and a few lines in it, 10 lines, say Each line is numbered (thus it is not one single line wrapped) and if I add text in a line, say line 5, the text reflows smoothly. If I open the very same file in TexStudio and I try to add text I get broken lines, which is not what I want. Of course I can fix everything afterwards but I wonder if I could get the same situation as in WinEdt. I hope I was clear.

Thanks,
Maurizio

**Comment by sunderme** [comment]
I can't say that I fully understand the problem stated.
I assume that winedt saves the text with hard line wrap (i.e. CR at end of line) and you expect txs to automatically remove the CR and work as if the lines are not broken ?

**Comment by sunderme** [comment]
no feedback
