### ISSUE TITLE
Add sub menus for Math Delimiter Sizes, and Dotted Ellipses to Math menu

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2815]
This also allows to add them to customizable toolbars for quick access.

![grafik](https://user-images.githubusercontent.com/102688820/210181834-eaddb704-c3f7-4dc3-98cb-1879f1944445.png)    ![grafik](https://user-images.githubusercontent.com/102688820/210181843-be079b98-7e1f-4485-b17a-4a173f82a41a.png)

This necessarily moves the \left and \right items from the Math menu to the new sub menu.

I'll add a PR for this.

**Comment by sunderme** [comment]
I would not move stuff around.
Either replicate left/right or leave it out.

by the way, are **you** going to use this ?
The issue is that this changes may have a user base of 0 which make it futile.

**Comment by octaeder** [comment]
I never use \left and \right due to the problems described in the amsmath manual. And the new "big" ones are also better when used with amsmath. I use these big commands often but it's hard for me to remember them in increasing order. This could be seen easily from the menu. But again I would add it to the math toolbar. Others could deactivate it. With the amsmath dots it's similar, Even so I use them regularly I often mix up for example cdots from latex with dotsc from AMS (c-enter vs. c-omma, so totally different placement) and so on. Same with font sizes, I don't remember all the names or I'm not sure about the increasing order. But with the format toolbar it's easy. I think it would be good to help beginners work with LaTeX, All others should use txs' numerous configuration elements. But of course its not a must have. An option similar to the advanced options option is used from some software to manage the sort of problem.

**Comment by sunderme** [comment]
if you use this, a PR is fine.

**Comment by sunderme** [comment]
are there any plans for this ?

**Comment by octaeder** [comment]
s. #2816 for a macro solution

**Comment by octaeder** [comment]
I'll add the necessary menu definitions to texstudio-macro
