### ISSUE TITLE
ntheorem's Math Definitions in English and German

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2816]
Some time ago I added the math definitions (aka ntheorem's standard environments) to the math menu (#2222). But there are only the English variants of them (Corollary, Proof, ... that print in English). This decision was the result of a discussion about too many entries in the menu list. So the German variants (Korollar, Beweis that print in German) were dropped.

I'm currently experimenting with a different approach that is similar to the solution for the \left/\right brackets commands combined with parentheses of all kind (s. ![grafik](https://user-images.githubusercontent.com/102688820/210185609-6a891d96-224d-44ce-9b5d-6f7c35d66e49.png) in the side panel). That means there could be a tags xml file that contains the sections English and German with tags of the env names in English and German respectively. This would give following options: 1) The tags list would be integrated in the side panel (like left/right). 2) The desired tags (either German or English) could be easily added to customizable toolbars which offer quick access (s. image below).

So those writing English documents as well as those writing in German could easily take advantage of the ntheorem package.

This solution would need a new icon for the side panel (maybe in 3 variants for the icon sets) and maybe the Math definitions menu should be removed.

![grafik](https://user-images.githubusercontent.com/102688820/210185803-d8667608-339a-41a2-a736-1d50cc180161.png)

A slightly different solution could be to keep the Math definitions menu and add only the German tags to the xml file. That's the state of my current build (and I reuse the icon for left/right):

![grafik](https://user-images.githubusercontent.com/102688820/210186328-7d5a6516-6703-4b78-84f6-d720b18dd370.png)

Any suggestions/ideas on my proposal?

**Comment by sunderme** [comment]
the maybe most important question: are **you** going to use the ntheorem via the tags or menus ?

if yes, and be honest about that, I would prefer no change in the math menu (removal of the menu) but rather a xml tags.
The probably nicer solution would be a dynamic solution to add the additional entries to the math menu if the user wants them.

**Comment by octaeder** [comment]
I mainly use the side panel with the first four views. I tried before to avoid adding the definitions tags to the side panel. But the code depends on the xml being there. I would prefer the math toolbar as the place (see my picture). Automatic insertion of the code is more reliable than typing. If you don't need a label use completion. My concern is rather the less experienced user, the power user may even remove the menus via config dialog. I also thought about an option. But where should it be in the config? Menus page seems to fit best, but I don't think that we can put it there. For now I'll stop working on that issue for a while...

**Comment by sunderme** [comment]
the user based solution could work with macros:
```
%SCRIPT
var menu = app.getManagedMenu("main/math/definitions");                   //get edit menu
var act = app.newManagedAction(menu, "script", "scripttest"); //add action
act.triggered.connect(function(){editor.insertText("\\test");});          //register simple handler
registerAsBackgroundScript("test");      
```

**Comment by sunderme** [comment]
alternatively I have added a script command `app.loadManagedMenu(filename)` which loads a uiconfig.xml (or similar)
So, the user can overwrite or extend the menu structure as he pleases.
If somebody could document the format in background.md ... :-)

**Comment by sunderme** [comment]
I will close this, as I don't have the intention to make a general extended ntheorem menu.
Two solutions for users to adapt txs to their needs are presented.
They can be offered to more users via testudio-macro.

**Comment by octaeder** [comment]
What filenames are supported by app.loadManagedMenu?

* I know it works with ...("C:/.../.../name.xml")
* Can I use something like %appdata%/Roaming/texstudio/...?
* Can I use a relative path by omitting double quote characters? Relative to which directory?

Issue: After starting txs the additional menus that had been added to the math toolbar are missing.

**Comment by sunderme** [comment]
relative to texstudio working directory, %appdata%, you have to test yourself.
