### ISSUE TITLE
Auto-completion in TeXstudio 4.4 is (unusably) slow

### ISSUE THREAD

**Issue by HolgerGerhardt** [texstudio-org/texstudio#2823]
### Environment

- TeXstudio: 4.4.1
- Qt: 6.4.1
- OS: macOS 13.1 (also present on Windows 11 on ARM)
- TeX distribution: MacTeX-2022 (MiKTeX)

### Expected behavior

Everything that I type should be displayed immediately—or at least without any severe delay.

### Actual behaviour

With TeXstudio 4.4.0 or 4.4.1, as soon as a document is rather complex, TeX commands like `\usepackage`, `\textbf`, etc. are only displayed with a delay of more than a second (on an M1 Pro MacBook Pro) when they are added somewhere in the middle of the document. When the commands are added at the end of the document, no delay can be observed.

This does not happen in short documents, and it does not happen in 4.3.1.

The issue affects TeXstudio 4.4 for both macOS and Windows.

### How to reproduce

To illustrate the issue, we can use

https://github.com/HolgerGerhardt/TeXTemplates.

For this purpose, I download the entire repository and add elements to the file

_Template_Paper.tex_ (https://github.com/HolgerGerhardt/TeXTemplates/blob/master/Template_Paper.tex).

This reveals a noticeable delay in 4.4.1, compared to 4.3.1.

More specifically, when I start typing

`\newcommand{cmd}{def}`

in line 56, the backslash is displayed instantaneously in 4.3.1, while in 4.4.1, it appears only after some delay. The delay gets even more pronounced when I when I fill in the curly braces that are autogenerated by TeXstudio. A short delay is noticeable in 4.3.1 as well, but it is much shorter than in 4.4.1.

The difference grows even larger when I enter

`\newcommand`

in line 56 entirely manually. A trailing opening curly brace is displayed in 4.3.1 after about 0.5 seconds. In 4.4.1, it is displayed after a full 2.5 seconds (!).

The same applies to _closing_ curly braces: If I type

`\newcommand{\test`

in line 56 and then add

`}`,

it takes 4.4.1 about 2 seconds (!) until the closing brace is finally displayed. In 4.3.1, there is also a short delay but it is much less noticeable (around 0.5 seconds).

When deleting braces, the same effect can be observed.

By contrast, when adding commands (say, `\newcommand{\test`, followed by `}`) _at the end of the document_—so that no already existing text follows—these delays do not happen.

**Comment by sunderme** [comment]
I have looked into this.
The issue is that the unclosed brace basically declares all late `\subimport` as part of the argument and invalidates them.
If the argument is closed correctly again, they become valid again and they will be loaded. The loading process causes the delay.
I will look into this further but there is no simple solution (except maybe disabling automatically import (txs option) but that means txs does not know about them for command completion etc.).

**Comment by sunderme** [comment]
and as an additional remark.
This is not about completion but tex parsing, so the title is misleading.

**Comment by HolgerGerhardt** [comment]
Thank you for looking into this so quickly! And please feel free to change the title of the issue to a more accurate one.

> The loading process causes the delay.
>
> I will look into this further but there is no simple solution

Well, the question is, of course, why the loading process is so much faster in TeXstudio 4.3.1 than in 4.4.1. What is it that changed between the two versions?

**Comment by sunderme** [comment]
from what I see, there is no difference between 4.3.1 and current, but there is a difference between qt5 and qt6.
Whether something can be done about that, I don't know. I rather fix the actual issue (loading/unloading files unnecessarily) than analyzing what qt6 does differently.

**Comment by sunderme** [comment]
fixed, please test

**Comment by HolgerGerhardt** [comment]
> fixed, please test

Awesome—thanks a lot!

I have downloaded https://github.com/texstudio-org/texstudio/suites/10239992785/artifacts/502137593 (from https://github.com/texstudio-org/texstudio/actions/runs/3863898913) and performed the steps described in my [initial report](https://github.com/texstudio-org/texstudio/issues/2823#issue-1518776062) above.

I can confirm that inserting `\newcommand` and other LaTeX commands in the middle of the document is now *much* faster than it was in 4.4.1.
