### ISSUE TITLE
Button/Menu to open included *.bib, if any; Option to open the bib file to the end. 

### ISSUE THREAD

**Issue by lRadha** [texstudio-org/texstudio#2829]
Hi, I think these two features can make working with references easier for many users:

1. A button, menu, or submenu to open the attached ```references.bib``` file. And as soon as that file opens in the editor
2. Move the cursor to the end of the file to edit.

Thanks

**Comment by muzimuzhi** [comment]
> 1. A button, menu, or submenu to open the attached `references.bib` file. And as soon as that file opens in the editor

I find on macOS cmd+click on `<file>` in `\bibliography{<file>}` will open `<file.bib>` if it's a path relative to current working directory. If `<file.bib>` is found by `kpsewhich`, for example `kpsewhich oberdiek-source.bib`, the cmd+click way fails.

> 2\. Move the cursor to the end of the file to edit.

There's a general shortcut to move cursor to document end, see Configure TeXstudio - Shortcuts - Editor - Basic Key Mapping - Move cursor to document end.
![image](https://user-images.githubusercontent.com/6376638/210810866-e2797bf9-5913-423e-9f6d-a0656d8ab1b4.png)

**Comment by octaeder** [comment]
When you open the structure view of your root document in the side panel you can expand subitems and double click on the bib file to open it (win10):

![grafik](https://user-images.githubusercontent.com/102688820/210894211-bf45bd6e-fabb-4e7d-bd19-3d463c21f345.png)

**Comment by lRadha** [comment]
Thanks, guys!
