### ISSUE TITLE
On hide single editor tab feature

### ISSUE THREAD

**Issue by tmelorc** [texstudio-org/texstudio#2834]
### Environment
- TeXstudio: 4.5.1 (git 4.4.0-197-g58f8d7682)
- Qt: Using Qt Version 5.12.8, compiled with Qt 5.12.8 R
- OS: Linux Mint with XFCE

### Description
This is just an opinion (not necessarily an issue) about the new feature related with the commit 58f8d7682a5fc27446a043b37021fcd4d10da6e1 

Now, the tab bar is hidden if a single document is opened, as image below.

![Seleção_033](https://user-images.githubusercontent.com/15181573/211362901-1d14245e-5680-47fd-a364-9ddd1ab149d5.png)

In my opinion I prefer the tab even with a single opened file. Otherwise we have to look to window title (in the center of window) to read the filename. 
But on full screen mode, the title disappears (at least in my XFCE Mint).

Maybe an option to disable this auto hide tab?

**Comment by octaeder** [comment]
With split view (one doc left, one right), we have no tabs (and no tooltips). So even with the window title you can't see both file names at the same time.
And how do I move the document in the right view back to the left view without a tab❓

Other things to mention: I can't close the document from the tab's Close button, and I can't use the context menu: Set Read-Only, Close, or Move to other view (yes I do so sometimes with only one editor open) any longer 😢.

And yes, the title also disappears on Windows 10 in full screen mode.

I think an option is no option.

**Comment by sunderme** [comment]
I close this issue as the commit with reverted.
If a new change should come, it would be appreciated that it
a) works with split documents sensibly
b) can be disabled/is disabled by default as currently the majority of editors do not change appearance with one open tab.
