### ISSUE TITLE
Texstudio keeps crashing on startup

### ISSUE THREAD

**Issue by Nerithi** [texstudio-org/texstudio#2835]
- TeXstudio: 4.3.1
- Qt: 5
- OS: Windows 8.1 Professional
- TeX distribution: texlive

### Expected behavior
Texstudio editor opens

### Actual behavior
![image](https://user-images.githubusercontent.com/93002925/211379556-da13a39d-d10e-45bf-af58-29211e0cb88b.png)

That is the latest result. Yesterday I was still able to click away the emergency notification and work, although I was warned that files could get corrupted. Today, after running through points 3+4 from list below, that notification shows up as a blank window without any text.

Stuff I've tried so far:
1. install latest version (didn't work because Qt6)
2. reinstall of last version with Qt5
3. complete deinstall of Texstudio, computer reboot
4. reinstall of 4.3.1 with Qt5

### How to reproduce
I don't know if it's reproducible, but I found two backtrace files I'm attaching below. The whole issue first appeared after I had accidentally renamed and moved a file I was working on without closing the file in Texstudio. At first, I could still open other files and it only crashed when I tried to open the renamed/moved file, but now it isn't even starting anymore.

[texstudio_backtrace2.txt](https://github.com/texstudio-org/texstudio/files/10375867/texstudio_backtrace2.txt)
[texstudio_backtrace1.txt](https://github.com/texstudio-org/texstudio/files/10375868/texstudio_backtrace1.txt)

**Comment by sunderme** [comment]
I would suggest to delete texstudio.ini  (%appdata%\textstudio\texstudio.ini)

**Comment by sunderme** [comment]
also delete in the same folder lastSession.*

**Comment by Nerithi** [comment]
Nope, still the same result unfortunately. Same also happens when I try with the portable version of 4.3.1. But I found an older portable install

`TeXstudio 2.12.22 (git 2.12.22)
Using Qt Version 5.12.1, compiled with Qt 5.12.1 R`

and that works? At least until I try to open the file in question, so my best guess is currently that it's the file causing the issue.

**Comment by sunderme** [comment]
no issue reported on win10
win 8.1 is end of life, so no effort is invested here.
