### ISSUE TITLE
highlighting issues with 4.5.1beta2

### ISSUE THREAD

**Issue by mbertucci47** [texstudio-org/texstudio#2836]
### Environment
- TeXstudio: 4.5.1beta2
- Qt: 6.4.2
- OS: Windows 10
- TeX distribution: miktex

### Actual behavior
After the completion/highlighting code changes in 4.5.1beta2, there are odd interactions that lead to incorrect highlighting. In the example below the presence of `\babelprovide` leads to `\usepackage{tikz}` not being picked up. Removing the `\babelprovide` line fixes it.
<p float="left">
<img width="181" alt="withbabelprovide" src="https://user-images.githubusercontent.com/61854785/211470498-33cf2005-e5df-4fd6-9fd2-01c78fe76da3.png">
<img width="174" alt="nobabelprovide" src="https://user-images.githubusercontent.com/61854785/211470511-ca3e3a43-aaf1-466e-bf73-a4f23595dbc0.png">
</p>

Also the keyval completion in the optional arg of `\babelprovide` is broken. Everything above is true if you replace `\babelprovide` with any other command with `[keyvals]` like `\babelensure` or any command whose args are not written out, e.g.

<img width="177" alt="incomplete arg" src="https://user-images.githubusercontent.com/61854785/211471350-d0d056d3-d3c4-4209-9a1e-c2bfac92bf01.png">

### Edit!
In the process of experimenting the highlighter would somewhat randomly work and stop working correctly after deleting and re-entering the same text, or hitting Return on a line then sending it back, to the point that the original document incorrectly highlighted above can be made to highlight/complete correctly. It seems the parser is not updating with regular input and needs several (meaningless) text operations done in order for it to recognize everything.

Here's how the same file looks when I close and reopen it.

<img width="177" alt="nohighlight" src="https://user-images.githubusercontent.com/61854785/211472423-44801109-fbe7-4909-9e20-76a5ebf5f487.png">

I'll note the above behavior has been common for several versions of TXS; you just need to place your cursor in front of `\documentclass` and hit Enter and Backspace to make the package/env highlighting turn back on, but the problem of not recognizing `\usepackage{tikz}` still stands.

#### Source

```latex
\documentclass[]{article}
\usepackage[english]{babel}
\babelprovide[]{} %% delete this line, replace with other commands, etc

\usepackage{tikz}

\begin{document}

\begin{tikzpicture}

\end{tikzpicture}

\end{document}
```

**Comment by sunderme** [comment]
fixed
