### ISSUE TITLE
lualatex failes due to locale issues

### ISSUE THREAD

**Issue by tschoepping** [texstudio-org/texstudio#2839]
Compilation using `latexmk -lualatex` fails due to locale issues. Please refer to my question at Stackoverflow (https://stackoverflow.com/questions/74864243/texstudio-locale-issues-with-lualatex) for more details and a workaround solution.

### Environment
- TeXstudio: 4.4.1
- Qt: 5.15.7
- OS: Fedora Linux 37
- TeX distribution: TeXLive 2022

### Expected behavior
Compilation should be executed without locale issues:

```
Process started: latexmk  -lualatex -silent -synctex=1 Document

Rc files read:
  latexmkrc

...

Latexmk: Getting log file 'Document.log'

Process exited normally
```

### Actual behavior
```
Process started: latexmk -lualatex -silent -synctex=1 "Document"

perl: warning: Setting locale failed. perl: warning: Please check that your locale settings: LANGUAGE = (unset), LC_ALL = (unset), LC_MEASUREMENT = "de_DE.UTF-8", LC_MONETARY = "de_DE.UTF-8", LANG = "Default.UTF-8" are supported and installed on your system. perl: warning: Falling back to the standard locale ("C").
Unable to read environment locale: exit now.
Latexmk: fls file doesn't appear to have been made. Latexmk: Couldn't read log file 'Document.log': No such file or directory ---------------------- This message may duplicate earlier message. Latexmk: Failure in processing file 'Dissertation': *LaTeX didn't generate the expected log file 'Document.log' ---------------------- Latexmk: If appropriate, the -f option can be used to get latexmk to try to force complete processing.
Process exited with error(s)
```

### How to reproduce
Change the "Latexmk" command (in the command configuration options menu) to use `lualatex` instead of `pdflatex` by replacing the default `-pdf` option by `-lualatex` or just `-lua`.

**Comment by sunderme** [comment]
works on ubuntu just fine
(user command: locale  -> de... )

**Comment by sunderme** [comment]
not reproducible
