### ISSUE TITLE
Please test OSX pinch zoom

### ISSUE THREAD

**Issue by sunderme** [texstudio-org/texstudio#2849]
### Environment
- TeXstudio: 4.5.1beta3
- Qt: 6.4.2
- OS: OSX
- TeX N/A

### Description
pinch zoom behaviour on OSX has been addressed with a work-around.
Please test if that really does its job.

**Comment by muzimuzhi** [comment]
I can still see small vertical shifting when zooming in and out, but compared to 4.5.1beta2 and prior it's much better now.

**Comment by ponte-vecchio** [comment]
Much better 👍

**Comment by sunderme** [comment]
I assume that it works.
