### ISSUE TITLE
Inconsistent behaviour: \ensuremath

### ISSUE THREAD

**Issue by ponte-vecchio** [texstudio-org/texstudio#2853]
#### System A
- TeXstudio: `4.5.1beta3`
- Qt: `Qt 6.4.1`
- OS: macOS
- TeX distribution: `TeXLive` (UNIX, not through brew)

#### System B
- TeXstudio: `4.4.1`
- Qt: `Qt 5.15.8`
- OS: openSUSE Tumbleweed
- TeX distribution: `TeXLive` (UNIX, not through distro package manager)

### Expected behaviour

I write a simple macro that creates up to 3 asterisks for denoting statistical significance. The below examples effectively do the same thing, but Examples 1 and 2 are defined using `\def{ ... }`, and Examples 3 and 4 are defined using `\newcommand{ ... }`. Of note is *how* they are formatted—where Examples 1 and 4 are indented as necessary, and Examples 2 and 3 are one-line definitions.

Because these definitions are practically identical (as understood by TeX), I expect the behaviour of the syntax highlighting to be consistent as seen with Github's:

##### Example 1
```tex
\protected\def\sig#1{%
	\leavevmode\hbox{%
		\ensuremath{%
			\ifcase#1-%
			\or\ast%
			\or\ast\ast%
			\or\ast\!\ast\!\ast%
			\fi%
		}%
	}%
}
```

##### Example 2
```tex
\def\sigA#1{\leavevmode\hbox{\ensuremath{\ifcase#1-\or\ast\or\ast\ast\or\ast\!\ast\!\ast\fi}}}
```

##### Example 3
```latex
\newcommand{\sigB}[1]{\leavevmode\hbox{\ensuremath{\ifcase#-\or\ast\or\ast\ast\or\ast\!\ast\!\ast\fi}}}
```

##### Example 4
```latex
\newcommand{\sigC}[1]{%
	\leavevmode\hbox{%
		\ensuremath{%
			\ifcase#1-%
			\or\ast%
			\or\ast\ast%
			\or\ast\!\ast\!\ast%
			\fi%
		}%
	}%
}
```

### Actual Behaviour

There is an inconsistency in how TeXStudio handles `\ensuremath`. Let's check out the screenshots:

System A
<img width="1496" alt="" src="https://user-images.githubusercontent.com/64239070/212607094-6c12df17-3aed-4280-bf8e-6f9ea05753bc.png">

System B
![ensuremath_openSUSE](https://user-images.githubusercontent.com/64239070/212608625-ce7705d3-6903-4506-94a4-8031d3bb0690.png)

I can summarise the current behaviour as follows:

| Macro used | Manner of definition | Contents within `\ensuremath` | Contents after closing `\ensuremath` |
| :---: | :---: |  :---: | :--- |
| `\def` | single line | Highlighted | All contents in the same line are highlighted as maths |
| `\def` | multi line | Highlighted | Contents are not highlighted as maths |
| `\newcommand`| single line  | Not Highlighted | Contents are not highlighted as maths |
| `\newcommand` | multi line | Not Highlighted | Contents are not highlighted as maths |

#### Further examination
To examine this oddity, I've gone a level further to see what keywords they are detected as in the case of using `\def` + single line uses.

<img width="425" alt="Screen Shot 2023-01-16 at 17 17 21" src="https://user-images.githubusercontent.com/64239070/212610808-225d63f5-a733-4a33-8a47-157744d7cd83.png">

<img width="1016" alt="Screen Shot 2023-01-16 at 17 18 05" src="https://user-images.githubusercontent.com/64239070/212610888-ba224907-5382-4666-b146-5bf0865d7b25.png">

Here we can see that *every control word*, including primitives—like `\catcode` and `\bgroup` is—detected as `math-keyword`, and everything else—including control symbols—is detected is `numbers`.

### Suggestions

1. If we aim to treat contents within `\ensuremath` the same way we treat contents within `$ ... $` or `\[ ... \]`, then the highlighting should persist for `\newcommand` and friends as well, or;
2. `\ensuremath` should not highlight contents within it—at all, or;
3. If we want to be selective about when `\ensuremath` should treat its contents as maths, then it should only work with LaTeX's control words like `\newcommand` and friends but that of TeX's (e.g. `\gdef`, `\def`) as `\ensuremath` is a keyword from LaTeX2e.

This is my first issue here, so please be nice! and I'm happy to add more info, have discussions and contribute. ❤️

**Comment by ponte-vecchio** [comment]
Possible dupe of #1865 and #2738 but I thought I'd demonstrate that the behaviour persists, with extra information.

**Comment by mbertucci47** [comment]
The cwl spec of `\newcommand` is 
```
\newcommand{cmd}[args][default]{def}#d
\newcommand{cmd}[args]{def}#d
\newcommand{cmd}{def}#d
```
This means anything in the "def" (=definition) arg is not checked for syntax at all. This is so, for example, in the declaration `\newcommand{\eulerform}{e^{\phi i}+1=0}`, the `^` and `\phi` are not marked as a syntax mistake for being outside math mode.

The syntax for `\def` is much more variable since it can take arbitrarily delimited arguments (e.g. `\def\cmd[#1]#2(#3){...}`) so no attempt to make a "definition" arg has been made.

**Comment by ponte-vecchio** [comment]
I am beginning to think that this is more to do with `\ensuremath` than `\def` or `\newcommand`.

Here are further behaviours I have observed:

<img width="558" alt="Screen Shot 2023-01-17 at 12 24 41" src="https://user-images.githubusercontent.com/64239070/212789612-2f1087d3-3b9c-44a0-8194-dd2adb35369b.png">

It seems that the unexpected behaviour only occurs when the `\ensuremath`'s closing brace is followed by `}`, `[, ]` and `(, )` as well as `<, >`.

**Comment by mbertucci47** [comment]
If possible please also post your examples in plain text so it can be copied and pasted

**Comment by ponte-vecchio** [comment]
> If possible please also post your examples in plain text so it can be copied and pasted

Sincerest apologies. Here is the code:

```tex
\documentclass[varwidth]{standalone}
\begin{document}
{\leavevmode\hbox{\ensuremath{\ast\kern-.1em\ast}}}

{\leavevmode\hbox{\ensuremath{\ast\kern-.1em\ast}}!}

{\leavevmode\hbox{\ensuremath{\ast\kern-.1em\ast}}@}

{\leavevmode\hbox{\ensuremath{\ast\kern-.1em\ast}}\#}

{\leavevmode\hbox{\ensuremath{\ast\kern-.1em\ast}}}%}

{\leavevmode\hbox{\ensuremath{\ast\kern-.1em\ast}}*}

{\leavevmode\hbox{\ensuremath{\ast\kern-.1em\ast}}()}

{\leavevmode\hbox{\ensuremath{\ast\kern-.1em\ast}}[]}

{\leavevmode\hbox{\ensuremath{\ast\kern-.1em\ast}}<>}

{\leavevmode\hbox{\ensuremath{\ast\kern-.1em\ast}}{}}

{\leavevmode\hbox{\ensuremath{\ast\kern-.1em\ast}}}^^M

{\leavevmode\hbox{\ensuremath{\ast\kern-.1em\ast}}\egroup

{\leavevmode\hbox{\ensuremath{\ast\kern-.1em\ast}}abc}

{\leavevmode\hbox{\ensuremath{\ast\kern-.1em\ast}}123}
\end{document}
```

**Comment by sunderme** [comment]
unfortunately you are mixing different topics in this issue.
1) \def does not suppress highlighting and syntax check in the cmd definition.
That was explained by [mbertucci47](https://github.com/mbertucci47) and there are no plans to change that.
2) highlighting on ensuremath does not stop at the closing brace. That has been fixed.

Normally that would be annotated here and this issue would be closed, which does not work now as more than one issues are described.
This is not tragic, just for future use ...

**Comment by ponte-vecchio** [comment]
>1. \def does not suppress highlighting and syntax check in the cmd definition.
>    That was explained by [mbertucci47](https://github.com/mbertucci47) and there are no plans to change that.

Understood :)

> 2. highlighting on ensuremath does not stop at the closing brace. That has been fixed.
> 
> Normally that would be annotated here and this issue would be closed, which does not work now as more than one issues are described. This is not tragic, just for future use ...

Just compiled the new commit and it does fix it. I think it's safe to close it unless you think there's any other unresolved issues?

**Comment by sunderme** [comment]
let's close this
