### ISSUE TITLE
Bug with macro triggers in 4.4.1

### ISSUE THREAD

**Issue by t-lundstrom** [texstudio-org/texstudio#2865]
I have many TexStudio macros whose trigger end with a tab character. The triggering stopped working when I updated to 4.4.1. 

I can trigger a macro just fine if it doesn't end in the tab character. For example I can create a macro whose trigger is 
`test`
which expands to 
`hello`
But if I change the tigger to
`test\t`
the macro won't trigger when I type test(tab)

So something about the macro trigger with regular expressions is probably not working.

**Comment by sunderme** [comment]
works on linux.
Do you mind giving all the details which you were asked to give when opening a new issue ?

**Comment by t-lundstrom** [comment]
- TeXstudio: 4.4.1
- Qt: Using Qt Version 6.4.1, compiled with Qt 6.4.1 R
- OS: MacOs Ventura 13.1 
- TeX distribution: MacTex

**Comment by sunderme** [comment]
Duplicate #2866
