### ISSUE TITLE
Macro triggers ending in tab character

### ISSUE THREAD

**Issue by t-lundstrom** [texstudio-org/texstudio#2866]
### Environment
- TeXstudio: 4.4.1
- Qt: Using Qt Version 6.4.1, compiled with Qt 6.4.1 R
- OS: MacOs Ventura 13.1
- TeX distribution: MacTex

### Expected behavior
When typing a macro trigger that ends in tab-character the macro should trigger

### Actual behavior
The macro does not trigger

### How to reproduce
Create a new macro with trigger
`test\t`
and content, say, "hello". Typing 
`test<Tab>`
does not trigger the macro, no "hello" text is inserted.

**Comment by sunderme** [comment]
this is a QT6/OSX issue.
The tab key event does not provide "\t" as text.
So, probably a osx qorkaround is needed.
