### ISSUE TITLE
Loaded menus missing that had been added to a toolbar

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2869]
The new script macro command app.loadManagedMenu() allows loading own menus form file. Using this in a macro with trigger ?txs-start ensures that the menus are loaded automatically after starting txs. I added two new menus to the math toolbar. So far so good. But when restarting txs the menus are missing in the toolbar. The debugger writes the messages ``Unknown toolbar command main/math/delimsizes`` and ``Unknown toolbar command main/math/ellipses``.

### Environment
- TeXstudio: git 4.5.1beta5-11-g40d3ab188
- Qt: 6.4.2
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
It is expected that the toolbar shows the menu after restarting txs

### Actual behavior
Menus are missing (only splitters are there, s. yellow area):

![grafik](https://user-images.githubusercontent.com/102688820/213931954-fc01eec7-c281-4732-bfaf-b9822dd0d76a.png)

### How to reproduce
s. above

**Comment by octaeder** [comment]
Investigation: A change of texstudio.cpp is needed because

- setupToolBars is called in line 353
- autoRunScripts is called in line 462 (and with a delay of 500ms)

One solution could be to insert a call to autoRunScripts (without delay) immediately before line 353 and remove line 462.
So loadManagedMenu has already setup the new menus which can be added to the toolbars later on.

@sunderme Is this a good idea? Removing delay time and executing autorunscripts several steps earlier may interfere with things I dont's see. A short test showed the correct toolbar:

![grafik](https://user-images.githubusercontent.com/102688820/214299123-b9cde203-473c-4947-8a6a-192872a829e3.png)

**Comment by sunderme** [comment]
I have to check.

**Comment by sunderme** [comment]
I would rather vote against executing autoRunScripts earlier. txs is not yet fully set up and the script may want to access things not ready yet.

**Comment by octaeder** [comment]
alternatively this code (l. 353ff)
```
	/* setup toolbars after autoRunScripts */
	setupToolBars();
	connect(&configManager, SIGNAL(watchedMenuChanged(QString)), SLOT(updateToolBarMenu(QString)));

	restoreState(windowstate, 0);
	//workaround as toolbar central seems not be be handled by windowstate
	centralToolBar->setVisible(configManager.centralVisible);
```
code be moved before line 472 (if).

**Comment by sunderme** [comment]
solution: in the script, call `app.setupToolBars()` after `app.loadManagedMenu()`.
(`setupToolBars()`is new)

**Comment by octaeder** [comment]
Thanks, this is ok.
