### ISSUE TITLE
The `&` in `alignedat`

### ISSUE THREAD

**Issue by i3v** [texstudio-org/texstudio#287]
### Environment
- TeXstudio: 2.12.10 (git 2.12.10)
- Qt: Qt Version 5.8.0, compiled with Qt 5.8.0 R
- OS: Windows 10
- TeX distribution: TexLive 2018

### Expected behavior
The `&` in `alignedat` should not produce `tabular command outside tabular env` - it should work as well as `alignat` .  Same for `aligned`.

### Actual behavior
![image](https://user-images.githubusercontent.com/920364/44179902-3c641a80-a102-11e8-9cf5-1236734b8f43.png)

--------------------------
Maybe that's just [this](https://github.com/texstudio-org/texstudio/blob/652bd52fd8a50a35904e479fe80071a2e8dbbab5/completion/amsmath.cwl#L14)?

A user-level cwl with the following changes seem to work for me:
- `\begin{alignedat}`  ->  `\begin{alignedat}{ncols}#m\array`
- `\begin{aligned}[alignment]`  -> `\begin{aligned}[alignment]#m\array`
- `\begin{aligned}` -> ` `  (why keep it if there's a version with an optional arg?)

**Comment by sunderme** [comment]
fixed
