### ISSUE TITLE
Math definitions needs `ntheorem` loaded with its `standard` option 

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#2875]
### Describe the feature and the current behavior/state
The new “Math definitions” feature states `ntheorem` package is needed. But most of the users who would use it would be puzzled that it is not enough: without the `standard` option given to  `ntheorem`, the theorems from the standard set provided by `ntheorem` don't work.

I don't know how to warn the users but, if they aren't warned, the feature is misleading IMO.

**Comment by octaeder** [comment]
Probably you will also have to use amsmath and hyperref (remember options column in #2831, but ntheorem is no longer there).
Reading the manual is always a good idea before using a package. Or you use existing examples.
Btw. enter \usepackage{pgkname} and the context menu of pkgname opens the documentation. Very easy and you may know all this.

One solution could be adding info attribute (but follow discussion in #2810). I made a quick build for that:

![grafik](https://user-images.githubusercontent.com/102688820/214180924-b8180bb3-9564-4967-8df6-5655cc7e1a0b.png)

Moving the pointer over the menu item shows the info in the status line. After inserting the environment into the editor the info is printed in the Messages pane.

Option [standard] defines English and German environments. But the entries from Math Definitions menu always (!) insert the English ones (as statet in #2222).

So let's see what @sunderme says.

Meanwhile you may give suggestions for the info text. We could add "in the preamble" for example.

**Comment by dbitouze** [comment]
> Probably you will also have to use amsmath and hyperref (remember options column in #2831, but ntheorem is no longer there).

- `amsmath` is required if (and only if) you rely on `align` and friends but the “(amsmath)” warning in the Maths → Math equations menu is enough to make them work.

- `hyperref` is generally not needed, though (generally) harmless and very useful.

> Reading the manual is always a good idea before using a package. Or you use existing examples.

Indeed, but that's not the point. The point is this new menu entry is misleading in its current state since the user could legitimately think that, to be able to use the entries in it, it is enough to load `ntheorem` (BTW not recommended anymore: `thmtools` would be more advisable, though it doesn't provide predefined “theorems” -- maybe a feature request for @muzimuzhi :wink:), just as `amsmath` is indeed enough to be able to use the entries in the Maths → Math equations.

> Btw. enter \usepackage{pgkname} and the context menu of pkgname opens the documentation. Very easy and you may know all this.

The LaTeX newbie would just think: “All stuff in this menu entry just doesn't work!” and would give up.

> One solution could be adding info attribute (but follow discussion in #2810).

What about, in the menu entry: “('ntheorem' with its 'standard' option)”

> I made a quick build for that:
> 
> [...]
> 
> Moving the pointer over the menu item shows the info in the status line. After inserting the environment into the editor the info is printed in the Messages pane.

Why not? Another option would be to add, just before the inserted environment, a comment such as:

``` % The following needs '\usepackage[standard]{ntheorem}' in preamble!```

> Option [standard] defines English and German environments.

That's another drawback: it just “doesn't work” e.g. in French.

> Meanwhile you may give suggestions for the info text. We could add "in the preamble" for example.

Yes.

**Comment by octaeder** [comment]
you have overseen that I wrote "options" column, so I was talking about \usepackage[standard,amsmath,hyperref]{ntheorem}.
annotation "(package)" primarily means you should load the package. This may include giving options.
I would prefere info attribute.

**Comment by dbitouze** [comment]
> you have overseen that I wrote "options" column, so I was talking about \usepackage[standard,amsmath,hyperref]{ntheorem}.

Sorry, I indeed misunderstood what you meant.

> annotation "(package)" primarily means you should load the package.

Indeed.

> This may include giving options.

Which “giving” options? Those needed are not obvious to guess.

> I would prefere info attribute.

The point with the Info attribute is that most of the users would miss it.

**Comment by octaeder** [comment]
de rien :)
Inserting a comment would be easy, but it could be annoying for all non newbies.
Difficult case because there seems to be no canonical way.

**Comment by dbitouze** [comment]
> Inserting a comment would be easy, but it could be annoying for all non newbies.

That's what does e.g. https://tablesgenerator.com/.

What about a first line (that cannot be “selected”), warning the users: “The following needs '\usepackage[standard]{ntheorem}' in preamble!”? Okay, that would maybe take too much place horizontally...

**Comment by octaeder** [comment]
well, much effort for such a simple thing. I tried to (miss) use a placeholder. Funny result:

![grafik](https://user-images.githubusercontent.com/102688820/214333249-32678956-98d9-4c5e-9e7a-465abbafea27.png)

I think this could be acceptable.

Btw (related to your label issue): In the original version the key placeholder is not selected since the cursor is placed in the next (empty) line. So removing the label statement is awkward.

**Comment by octaeder** [comment]
about language: latest development allows loading/adding your own menus form xml (as in uiconfig.xml). Example:

```
<TexMakerXUI>
<menu id="main/math" text="&amp;Math">

  <menu id="definitions" text="Definitions">
    <menu id="GERntheorem" text="Deutsch">
      <insert id="ntheoGerBeispiel" text="Umgebung &quot;Beispiel&quot; (ntheorem)" insert="\begin{Beispiel}\label{%&lt;key%>}%\%|%\\end{Beispiel}"/>
      <insert id="ntheoGerBemerkung" text="Umgebung &quot;Bemerkung&quot; (ntheorem)" insert="\begin{Bemerkung}\label{%&lt;key%>}%\%|%\\end{Bemerkung}"/>
      <insert id="ntheoGerBeweis" text="Umgebung &quot;Beweis&quot; (ntheorem)" insert="\begin{Beweis}%\%|%\\end{Beweis}"/>
      <insert id="ntheoGerDefinition" text="Umgebung &quot;Definition&quot; (ntheorem)" insert="\begin{Definition}\label{%&lt;key%>}%\%|%\\end{Definition}"/>
      <insert id="ntheoGerKorollar" text="Umgebung &quot;Korollar&quot; (ntheorem)" insert="\begin{Korollar}\label{%&lt;key%>}%\%|%\\end{Korollar}"/>
      <insert id="ntheoGerLemma" text="Umgebung &quot;Lemma&quot; (ntheorem)" insert="\begin{Lemma}\label{%&lt;key%>}%\%|%\\end{Lemma}"/>
      <insert id="ntheoGerSatz" text="Umgebung &quot;Satz&quot; (ntheorem)" insert="\begin{Satz}\label{%&lt;key%>}%\%|%\\end{Satz}"/>
      <insert id="ntheoGerTheorem" text="Umgebung &quot;Theorem&quot; (ntheorem)" insert="\begin{Theorem}\label{%&lt;key%>}%\%|%\\end{Theorem}"/>
    </menu>
  </menu>

</menu>
</TexMakerXUI>
```

All you need is a macro like this:

```
{
    "abbrev": "",
    "description": [
        "This Macro loads menus",
    ],
    "formatVersion": 1,
    "menu": "",
    "name": "Load private menus",
    "shortcut": "",
    "tag": [
        "%SCRIPT",
        "app.loadManagedMenu('C:/Users/.../AppData/Roaming/texstudio/myMenus/GERntheorem.xml');",
        ""
    ],
    "trigger": "?txs-start"
}

```
Just use the pathname you need.

**Comment by dbitouze** [comment]
> well, much effort for such a simple thing. I tried to (miss) use a placeholder. Funny result:
> 
> [...]
> 
> I think this could be acceptable.

Well... looks ugly IMO (sorry!). And, that's not the purpose of placeholders.

> Btw (related to your label issue): In the original version

Which original? Version of what?

> the key placeholder is not selected since the cursor is placed in the next (empty) line.

Indeed, for both equations and math definitions.

> So removing the label statement is awkward.

Awkward? Why?

**Comment by octaeder** [comment]
original version means that before the changes discussed here (or master branch).
But it is a solution, and I have no more ideas, especially not ones I can do, I assume.
I think it's easier adding a label when needed than deleting the code when not needed. If the label were in a separate line it were easy to delete the line with a shortcut. Instead I have to move and jump the cursor.
Should I remove the label statement from the inserted text? I think that I inserted it, because other envs have it, too.

**Comment by dbitouze** [comment]
> I think it's easier adding a label when needed than deleting the code when not needed.

Agree.

> If the label were in a separate line it were easy to delete the line with a shortcut. Instead I have to move and jump the cursor.

Indeed: painful and risky.

> Should I remove the label statement from the inserted text?

Maybe, though IMO a better long term solution would be as asked in #2880.

**Comment by octaeder** [comment]
I think we don't move any further.

>>    the key placeholder is not selected since the cursor is placed in the next (empty) line.

> Indeed, for both equations and math definitions.

All equations are reworked (#3022), add no label statement, and add reasonable code with placeholders.

My suggestions regarding ntheorem: 
- Add tooltip "Needs \usepackage[standard]{ntheorem}, and
- remove label statements
