### ISSUE TITLE
texstudio freezes when bib file is updated in the background

### ISSUE THREAD

**Issue by rantanplan77** [texstudio-org/texstudio#288]
### Environment
- TeXstudio 2.12.10 (git 2.12.10)
- Qt: Qt-Version 5.11.1, compiled with Qt 5.11.1 R
- OS: macOS 10.13.6
- TeX distribution: pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017)

### Actual behavior
I have a large .bib file (bib.bib, 800 entries, ~1MB), produced by Papers3. I include it into my .tex file using `\bibliography{bib}`.
Whenever bib.bib is updated by Papers3, texstudio freezes for ~20 seconds, no matter whether it is open or closed in texstudio too. I see the spinning wheel mouse icon when texstudio is in the foreground.

### Expected behavior
texstudio doesn't freeze.

### Thoughts
Is there some process in texstudio that checks whether the .bib-file has been updated?

**Comment by sunderme** [comment]
we need the test case, including the files !

**Comment by sunderme** [comment]
insufficient info

**Comment by wenglingmei** [comment]
This bug can be reproduced on my side with any large size bib file(I tested with 1000 citations) in the following steps:
1.open the project in TeXstudio, with the bib file opened in a tab
2.using vim to touching the bib file, or just touch the bib file from the terminal
3.clip the TeXstudio App, and the spinning beachball shows up

With my tracing, the touching of the bib file triggered a callback function from the daemon fseventd. The callback function executed for a long time in the main thread of TexStudio.

**Comment by sunderme** [comment]
please provide a/the bib file then

**Comment by wenglingmei** [comment]
> please provide a/the bib file then

Can you please use your own bib file? copy & paste to get a large one.
If you can not reproduce it with your bib file, I will be happy to share mine.

**Comment by anonymous4argus** [comment]
Hello,
I am testing my debugging tool and investigated this case. I could reproduce this issue with the bib file below
```
https://github.com/anonymous4argus/cases/blob/master/database.bib
```
To reproduce it, I just open the bib with texstudio and in terminal execute
```
touch database.bib
```
After confirm the reload dialog in the main window, the spinning beachball appears.

Our tool realized the main thread spends over 3s to execute 
```
QDocument::startChunkLoading().
```
While the main thread is bugged by IPI interrupts, it is mostly busy with
```
QDocumentPrivate::indexOf(QDocumentLineHandle const*, int)
```
"QDocument::lineDeleted(QDocumentLineHandle*)" and "LatexEditorView::lineDeleted(QDocumentLineHandle*)" also appear frequently.

Hope this helps, and I hope to hear from you soon.

**Comment by sunderme** [comment]
I see the behavior, I'll take a closer look.

**Comment by sunderme** [comment]
should be faster now
