### ISSUE TITLE
Drop-down menu in toolbar should display tooltips/info

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2881]
### Describe the feature and the current behavior/state
Example: Open menu math equations. The items there have the info attribute set in uiconfig.xml. It is presented in the statusbar (for ex. _The gather* environment is an unnumbered gather environment_) when you hover over the items with the cursor.
Add the menu to the math toolbar and repeat the procedure with these items in the toolbar. No info is  shown.

### Who will benefit with this feature?
All those who want to use toolbars for quick access to items and need only small hints to decide which item to use.

### Any Other info
No idea how this is done in the menus and how this can be ported to the toolbars.

**Comment by sunderme** [comment]
info is shown as tooltip

**Comment by octaeder** [comment]
no tooltip:

![grafik](https://user-images.githubusercontent.com/102688820/214636600-d03bb5be-1734-4ef7-9f1b-3e7a4de3af68.png)

**Comment by sunderme** [comment]
it works on tool buttons. 
Seems not to work drop-down lists.

**Comment by octaeder** [comment]
second is my case

**Comment by octaeder** [comment]
Tooltips, no StatusTips, ok? This makes hovering over items with the cursor and reading much easier than with statusTips. No change to "normal" menus.

![image](https://user-images.githubusercontent.com/102688820/215248329-121c98ff-159d-4a5f-9ce7-45f56fb6687f.png)

![image](https://user-images.githubusercontent.com/102688820/215248342-3c022db6-d8c4-4b82-910c-dd7b52ca8c85.png)

**Comment by sunderme** [comment]
yes
