### ISSUE TITLE
A lot of new translation messages

### ISSUE THREAD

**Issue by tmelorc** [texstudio-org/texstudio#2891]
### Environment
- TeXstudio: 4.5.1 (git 4.4.0-274-gd46f10165)
- Qt: 5.12.8
- OS: Linux Mint
- TeX distribution: texlive

### Description
I noticed a lot of new messages to be translated in Transifex. For example, _The \newpage command ends the current page_ occurs in `../src/additionaltranslations.cpp:123`

But I'm not able to find where such message (and many others) are being used. To do a good translation it is important to know the context. 

I'm not sure if inserting a lot of help messages could be a good decision. We should be careful to not write erroneous messages. Maye a topic here to discuss this could help.

Regards.

**Comment by octaeder** [comment]
s. uiconfig.xml (you can find by content search for "command ends the current page")
more or less tooltips, some details [here](https://github.com/texstudio-org/texstudio/issues/2798#issuecomment-1364602156)
open main menu LaTeX/Vertical Spacing, hover over first item \newpage of the submenu and look at status bar. Click item and look at Messages Pane.

**Comment by sunderme** [comment]
The tooltips for the latex/math commands have been there for years, so it has not been possible to translate them until recently.

**Comment by tmelorc** [comment]
Thanks guys. Now I can read the discussion about the translations. 
IMHO long strings is not useful in the status bar since it could be difficult to read all of them until they disappear.  Also we have to be careful to not make txs a kind of LaTeX user manual. Documentation is complicated to produce.

Regards.

**Comment by sunderme** [comment]
can we close this
