### ISSUE TITLE
In Wizards → Quick Start, the `⟨language⟩` should be given at the `\documentclass` level

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#2892]
# Describe the feature and the current behavior/state

When a `⟨language⟩` is specified thanks to the `babel` class option in Wizards → Quick Start, this `⟨language⟩` option is given at the package level: `\usepackage[⟨language⟩]{babel}`.

It is advised to give it at the document class level instead: `\documentclass[⟨language⟩]{article}`. Indeed, hence all packages sensible to the language(s) (for instance, `varioref`, `cleveref`, etc.) are aware of the underlying `⟨language⟩` and no need to repeat the `⟨language⟩` at the package level of all these packages.

# Who will benefit with this feature?

Everybody relying on Wizards → Quick Start.

**Comment by octaeder** [comment]
My suggestion: Rename option to "Language" and move the Babel to the list of packages. Thus Class Options (including language) and Packages are fully separated.

**Comment by dbitouze** [comment]
> My suggestion: Rename option to "Language" and move the Babel to the list of packages. Thus Class Options (including language) and Packages are fully separated.

This would work only if the two were connected:

- `babel` loaded without any `⟨language⟩` specified doesn't make sense,
- a `⟨language⟩`specified  without `babel` loaded would issue the warning: “Unused global option(s): [⟨language⟩].”

**Comment by octaeder** [comment]
Should be possible with signals: changing one changes the other.
So we do not support the case that a beginner(?) needs the language for something else without babel.

**Comment by dbitouze** [comment]
> So we do not support the case that a beginner(?) needs the language for something else without babel.

IMO, no if no package sensible to the language other than `babel` is listed in the wizard.

**Comment by octaeder** [comment]
Simple solution: If and only if a language is selected, then add the language to the class options and add a \usepackage{babel}.
No need to add Babel Package to the list of the Package tab. This avoids confusion when changing one option will change another on a different tab.

**Comment by dbitouze** [comment]
> Simple solution: If and only if a language is selected, then add the language to the class options and add a \usepackage{babel}.

A possible improvement would be to ask the user to choose between `babel` and `polyglossia` when (s)he selects a language.

**Comment by octaeder** [comment]
Why? I wouldn't say that I'm a newbie but I don't know the difference between babel and polyglossia.

**Comment by muzimuzhi** [comment]
> > Simple solution: If and only if a language is selected, then add the language to the class options and add a \usepackage{babel}.
> 
> A possible improvement would be to ask the user to choose between `babel` and `polyglossia` when (s)he selects a language.

@dbitouze `polyglossia` needs xelatex or lualatex, which will complicate the Quick Start wizard.

**Comment by dbitouze** [comment]
> Why? I wouldn't say that I'm a newbie but I don't know the difference between babel and polyglossia.

As said in its introduction, “[g]enerally speaking, `polyglossia` aims to remain as compatible as possible with the fundamental features of `babel` while being cleaner, light-weight, and modern.” 

But, it is admittedly not widely used. And, since, as said by @muzimuzhi, it needs `xelatex` or `lualatex`, probably it doesn't worth to complicate the Quick Start wizard with it.
