### ISSUE TITLE
Local building with msys2 not longer possible?

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2897]
### Environment
- TeXstudio: current master
- Qt: 6.4.2
- OS: Win10
- TeX distribution: miktex

### Expected behavior
Local Build should run.

### Actual behavior
I still build with msys2 and qmake6. But as mentioned with a comment in this [PR](https://github.com/texstudio-org/texstudio/commit/3b53fdf68c7e56073f5c311025c4486d0cf31852#commitcomment-98236624) I can't build anymore. Workaround is to revert this PR locally (remove line 80 from latexdocument.h).
Today an issue with msys2 appeared on CD workflow (s. [here](https://github.com/octaeder/texstudio/actions/runs/4031935973/jobs/6931514491)).
Please help, I need assistance.

### How to reproduce
Not sure if you can reproduce. I now need that workaround.

**Comment by sunderme** [comment]
use cmake.

**Comment by sunderme** [comment]
your CD, don't know , texstudio CD works.
