### ISSUE TITLE
Why .exe 2.12.8 so huge compared to 2.12.6?

### ISSUE THREAD

**Issue by sergiokapone** [texstudio-org/texstudio#29]
Why .exe 2.12.8 so huge compared to 2.12.6? Did you include all dll's in .exe? I'm asking because in [changelog](http://texstudio.sourceforge.net/manual/current/CHANGELOG.txt) there is no information.

**Comment by sunderme** [comment]
because the libs are statically linked in the exe

**Comment by RoyiAvital** [comment]
@sunderme , Any chance to release notes for each release on the GitHub Release page?
I can't find any information about 2.12.8 (Website still shows 2.12.6).

Thank You.

**Comment by timhoffm** [comment]
2.12.8 is not yet officially released.

**Comment by assarbad** [comment]
> 2.12.8 is not yet officially released.

@timhoffm I think I was also confused by the fact that this is actually shown as the primary download option on the website and appears as a News item:

![2018-03-21 13_04_10-texstudio](https://user-images.githubusercontent.com/3238620/37711411-8a8c37d8-2d08-11e8-80de-e8268146d26b.png)

With that big button leading straight to [the download here from GitHub](https://github.com/texstudio-org/texstudio/releases/download/2.12.8/texstudio-2.12.8-win-qt5.exe).

Maybe that was published in error? However, [the latest release](https://github.com/texstudio-org/texstudio/releases) here on GitHub refers to 2.12.8 as well.

**Comment by sunderme** [comment]
it is

**Comment by RoyiAvital** [comment]
@sunderme , Could we have a Changelog published?
