### ISSUE TITLE
Order of packages with Quick Start wizard

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#2901]
### Describe the feature and the current behavior/state
The order in which packages are inserted with the Quick Start wizard doesn't follow usual advises. AFAIK:

- `inputenc` and `fontenc` should preferably be the first ones,
- `babel` should be the last one, except exceptions,
- `hyperref` is such an exception and should be the last one, except exceptions (`cleveref` is a notable one).

Currently, if all the packages are asked, they are inserted in the following order.:
```latex
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{amssymb}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{mathtools}
\usepackage{amsthm}
\usepackage{nameref}
\usepackage{thmtools}
\usepackage{xcolor}
```
A better one would be:
```latex
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{graphicx}
\usepackage{mathtools}
\usepackage{amssymb}
\usepackage{amsthm}
\usepackage{thmtools}
\usepackage{xcolor}
\usepackage{nameref}
\usepackage{babel}
\usepackage{hyperref}
```

### Who will benefit with this feature?
Everybody who is relying on the Quick Start wizard.

**Comment by muzimuzhi** [comment]
Since LaTeX2e 2018-04-01, utf8 is the default input encoding thus (in most cases (?)) there's no need to use `\usepackage[utf8]{inputenc}`. See `texdoc ltnews`, Issue 28
<img width="379" alt="image" src="https://user-images.githubusercontent.com/6376638/215286009-8e00c4eb-6803-4ee2-9282-9bf88720e8c8.png">

**Comment by dbitouze** [comment]
@muzimuzhi Indeed. My point was that, should `inputenc` be loaded, that should be in the 1st or 2nd place.

BTW, a friend of mine, who has written the book “LaTeX pour l'impatient” (for beginners and intermediate users), is still using `latin1` as input encoding and is very reluctant to switch to UTF-8 (despite some friends and me are strongly advising her to do so) :wink:

**Comment by octaeder** [comment]
Where in this list

```latex
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{graphicx}
\usepackage{mathtools}
\usepackage{amssymb}
\usepackage{amsthm}
\usepackage{thmtools}
\usepackage{xcolor}
\usepackage{nameref}
\usepackage{babel}
\usepackage{hyperref}
```

geometry should appear?

**Comment by dbitouze** [comment]
I would say, anywhere between `\usepackage[T1]{fontenc}` and `\usepackage{babel}`.

Note that some packages here are  useless:

1. `\usepackage[utf8]{inputenc}`: is nowadays the default,
2. `\usepackage{nameref}`: is automatically loaded by `hyperref`.

**Comment by octaeder** [comment]
Thanks.
Ad 1) This issue clearly states: `inputenc and fontenc should preferably be the first ones,`. Now you want to change this as 99% of work (including test) has finished. For now this is really not a problem, but generally this leads to unnecessary work.
Ad 2) This was taken into account with the last change as can be seen from the dialog (txs 4.5.2):
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/33e5c0dd-97b0-4da8-91f2-7e5adee3451f)

**Comment by octaeder** [comment]
Now static sequence is as follows (geometry at second place):
```C++
// LaTeX code for all packages used
	tag += fontenc + geometry + graphicx + mathtools + amssymb + amsthm + thmtools + xcolor + nameref + babel + hyperref + userPackages;
```
