### ISSUE TITLE
Text studio installation facing unmet dependencies.

### ISSUE THREAD

**Issue by aniket-nath** [texstudio-org/texstudio#2905]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Description

I cannot install the texstudio. The following error is thrown.

The following packages have unmet dependencies:
 <div>texstudio : Depends: libpoppler-qt5-1 (>= 0.81.0) but it is not installable </br>
             Depends: libqt5concurrent5 (>= 5.6.0~rc) but it is not installable </br>
             Depends: libqt5core5a (>= 5.15.1) but it is not installable </br>
             Depends: libqt5dbus5 (>= 5.0.2) but it is not installable </br>
             Depends: libqt5gui5 (>= 5.14.1) but it is not installable or </br>
                      libqt5gui5-gles (>= 5.14.1) but it is not installable </br>
             Depends: libqt5network5 (>= 5.0.2) but it is not installable </br>
             Depends: libqt5printsupport5 (>= 5.0.2) but it is not installable </br>
             Depends: libqt5qml5 (>= 5.12.2) but it is not installable </br>
             Depends: libqt5svg5 (>= 5.6.0~beta) but it is not installable </br>
             Depends: libqt5widgets5 (>= 5.15.1) but it is not installable </br>
             Depends: libqt5xml5 (>= 5.0.2) but it is not installable </br>
             Depends: libquazip5-1 (>= 0.7.3) but it is not installable </br>
             Recommends: texlive-latex-extra but it is not installable </br>
             Recommends: latex-beamer but it is not installable </br>
             Recommends: dvipng but it is not installable</div>  </br>
I cannot get access to any of the above packages

**Comment by sunderme** [comment]
describing what OS you are actually using and how you try to install texstudio might be a good information to start with ...

**Comment by aniket-nath** [comment]
OS: Ubuntu 22.04.1 LTS

I have tried to install using PPA, the required dependencies, which are not getting installed and showing the above mentioned errors.

**Comment by sunderme** [comment]
I have checked in a virtual machine. The ppa on Ubuntu 22.04 works just fine.
So. What **exactly** do you do to install texstudio.
The messages above point to a rather fundamental issue on your installation as the mentioned packages are common packages.

**Comment by aniket-nath** [comment]
I'll list the commands I have used.
sudo add-apt-repository ppa:sunderme/texstudio
sudo apt update
sudo apt install texstudio

The following error is shown:
The following packages have unmet dependencies:
 texstudio : Depends: libpoppler-qt5-1 (>= 0.81.0) but it is not installable
             Depends: libqt5concurrent5 (>= 5.6.0~rc) but it is not installable
             Depends: libqt5core5a (>= 5.15.1) but it is not installable
             Depends: libqt5dbus5 (>= 5.0.2) but it is not installable
             Depends: libqt5gui5 (>= 5.14.1) but it is not installable or
                      libqt5gui5-gles (>= 5.14.1) but it is not installable
             Depends: libqt5network5 (>= 5.0.2) but it is not installable
             Depends: libqt5printsupport5 (>= 5.0.2) but it is not installable
             Depends: libqt5qml5 (>= 5.12.2) but it is not installable
             Depends: libqt5svg5 (>= 5.6.0~beta) but it is not installable
             Depends: libqt5widgets5 (>= 5.15.1) but it is not installable
             Depends: libqt5xml5 (>= 5.0.2) but it is not installable
             Depends: libquazip5-1 (>= 0.7.3) but it is not installable
             Recommends: texlive-latex-extra but it is not installable
             Recommends: latex-beamer but it is not installable
             Recommends: dvipng but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by sunderme** [comment]
`E: Unable to correct problems, you have held broken packages.` is probably the culprit.
There is something clogged up in your package system.

**Comment by aniket-nath** [comment]
can you suggest some solution to this problem?

**Comment by sunderme** [comment]
no, usually apt status/update/upgrade give hints.
