### ISSUE TITLE
How to set the path to link to MikTex on Mac?

### ISSUE THREAD

**Issue by FrankXinqi** [texstudio-org/texstudio#291]
I have installed MacTex before. Now, I would like to use MikTex with texstudio. However, I do not know the correct way to set the path in 'Configuration-Command'

**Comment by sunderme** [comment]
if latex can be found in the $PATH variable, you don't have to set anything
otherwise adapt options/commands and possibly options/build/commands ($PATH)

**Comment by FrankXinqi** [comment]
The problem may be that Textstudio always links to MacTex, which I installed before.

I am thinking to manually set that to MiKTex.

**Comment by sunderme** [comment]
then your PATH-variable is not set correctly ...

**Comment by sunderme** [comment]
and you should know where you put miktex on your disc ...
