### ISSUE TITLE
Update Wiki description of MSYS2 preparation

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2910]
- [x] Since msys2 ucrt64 cli is started out of installation process of msys2 it might be better to use ``ucrt-`` in the package names.
- [x] Add prefix ``mingw-w64-ucrt-x86_64-`` to ``cmake``.
           Reason: Otherwise poppler not found.
- [x] Add package ``mingw-w64-ucrt-x86_64-quazip-qt6`` to packages list.
     Reason: Avoids two messages: ``Could NOT find QUAZIP`` and ``Using internal QuaZIP``.
- [ ] Change text to "Start msys2 ucrt64 commandline."
   Reason: This cli is started from within the msys2 installation process.
- [ ] Extend command given in Wiki to ``cmake .. -Wno-dev`` to suppress large amount of messages.
- [ ] Directory ``build`` should not be in the repository directory subtree.

**Comment by octaeder** [comment]
Maybe you can use this as a starting point:

For simplicity we assume here that 1) the TeXstudio source files are stored locally in the directory sub tree ``texstudio-org/texstudio/``, and 2) your build target folder ``_build/`` is located in the ``texstudio/`` folder as indicated here:
```
texstudio-org/
   texstudio/	     (build source folder)
      translation/
      utilities/
         manual/
      ...
   _build/            (build target folder)
```
Build TeXstudio as follows by executing following commands in the msys2 console:

1. Use the ``cd`` command to set the current directory to ``_build/``
2. Prepare the build with the command ``cmake ../texstudio/``
3. Run the build with ``cmake --build . --parallel``
4. Start TeXstudio with the command ``./texstudio`` (``./`` needed, ``.exe`` not necessary)
5. If you want to use translations or the manual in your version of TeXstudio, then copy following folders (s. above) to ``_build/``: 1) ``translation/`` as is, or 2) ``manual/`` renamed to ``help/``

**Comment by sunderme** [comment]
cmake is usually used with `mkdir build` and so on.
I don't see why txs should deviate from that.

**Comment by octaeder** [comment]
_build is a relic before I changed type setting. Since the word build is often used, the underscore should make clear that _build means a folder. As I said use it as a starting point. This includes that you can change things. Nonetheless, some of the things that have been said involve my experiences that might be helpful to others.

**Comment by octaeder** [comment]
no progress
