### ISSUE TITLE
multilines and block  comment/uncomment 

### ISSUE THREAD

**Issue by dallouche** [texstudio-org/texstudio#2912]
### Describe the feature and the current behavior/state
comment and comment on several lines in a single operation
### Who will benefit with this feature?
all users  could add or remove by commenting / uncommenting a subpart of a latex document
(handy feature during report/presentation building ) 
### Any Other info
seems to be easy to do 
add or remove % the lines begin of a previously done selection

**Comment by octaeder** [comment]
select some lines, press Ctrl+T toggles between comment/uncomment

![grafik](https://user-images.githubusercontent.com/102688820/216040794-92308d8e-6e70-4ad6-b7a4-3400278c300f.png)

**Comment by dallouche** [comment]
ok in the main text   but we cannot comment or uncomment folded block ??

**Comment by octaeder** [comment]
commenting folded block works whether you only select the first line of the block (i.e. anchor or cursor is at the beginning of first line after the block) or if the folded lines of the block are a real subset of the selected lines.

But uncommenting surprisingly doesn't work.

Can you confirm that this is the issue?

**Comment by sunderme** [comment]
toggling comment on fold implemented

**Comment by sunderme** [comment]
if the comment invalidates folding (e.g. \begin...\end folding becomes %\begin  ...%\end which is not folded anymore ...), reversing does not work.
