### ISSUE TITLE
pending translations of units starting with a space

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2920]
I ask for acceptance of following German translations of units starting with a space (s. #2890):

No 492
![grafik](https://user-images.githubusercontent.com/102688820/216460235-f290b34d-7497-457e-b53f-308ea1c38b1f.png)

No 510
![grafik](https://user-images.githubusercontent.com/102688820/216460256-8c327a93-92f3-42e0-8444-b11d582a7162.png)

**Comment by sunderme** [comment]
did you remove or add a space ?

**Comment by octaeder** [comment]
added

**Comment by octaeder** [comment]
this can't be seen from the preview, but if u say use then the editor shows the space

**Comment by sunderme** [comment]
then it is in

**Comment by octaeder** [comment]
I see, you accepted 3h ago.
