### ISSUE TITLE
error: invalid application of ‘sizeof’ to incomplete type ‘LatexEditorView'

### ISSUE THREAD

**Issue by svenstaro** [texstudio-org/texstudio#2925]
### Environment
- TeXstudio: 4.5.1
- Qt: 6.4.2
- OS: Arch Linux
- TeX distribution:  N/A

### Expected behavior

Texstudio should compile.

### Actual behavior

It fails to compile with this log: [log.txt](https://github.com/texstudio-org/texstudio/files/10608914/legal-tetra.txt)

### How to reproduce

Compile texstudio 4.5.1 wih gcc 12.2.1 and Qt 6.4.2.

**Comment by sunderme** [comment]
qmake building is broken, use cmake

**Comment by octaeder** [comment]
Project MESSAGE: Building via qmake (.pro) deprecated. Please use cmake instead.

**Comment by sunderme** [comment]
this should be answered

**Comment by svenstaro** [comment]
Alright, cmake works for me. However, if qmake is still included in the releases and it's not meant to be used, shouldn't it just be removed then?
