### ISSUE TITLE
Add CHANGELOG.html to source repository

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2932]
All html files for the manual are present in the source repository, but not CHANGELOG.html. We need it since the manual is opened locally via Help menu. For this we need that the build/html/ folder is complete when it is copied to the help/ folder while packaging the txs release.

### Environment
- TeXstudio: current dev

### Expected behavior
file is located in utilities/manual/build/html

### Actual behavior
md file is in build/source

**Comment by octaeder** [comment]
A complete build/html folder is also useful when testing local builds. Otherwise the manual will be incomplete, too. So it would not suffice to only add the html file into releases packages but not to the repository.

**Comment by sunderme** [comment]
fixed
