### ISSUE TITLE
Please show a tooltip for all the TeX/LaTeX2e commands on mousehover

### ISSUE THREAD

**Issue by Grosskopf** [texstudio-org/texstudio#2933]
### Describe the feature and the current behavior/state
Currently, whenever I do not know what a certain line of code does, I google the command, find some random person on the Internet explaining it or if I'm lucky I find a piece of documentation from some University. In the End I copy some code from stackoverflow and see if it works. This takes hours if not days to finetune the layout. What I would want, is a tooltip for this exact command.
In pycharm when I hover over any python command for a second, I get a bit of text shown about this command, where it comes from, and what it does, something like that would help me massively.

 I found this page: https://www.tug.org/utilities/plain/cseq.html and now I am wondering why I don't get a bit of text from for example that page or some place similar shown when I hover over for example "\pagetotal" with a link to the documentation to learn more

### Who will benefit with this feature?
Texstudio Users that don't like searching all across the Internet for documentation

**Comment by sunderme** [comment]
You have seen that you can right click on a command and get "open package documentation" which opens the appropriate manual and let's you search for the command ?

**Comment by sunderme** [comment]
no feedback.
original feature request is impossible, as there is no complete list "command" -> "help text"

**Comment by Grosskopf** [comment]
> You have seen that you can right click on a command and get "open package documentation" which opens the appropriate manual and let's you search for the command ?

Does not work on my machine, is this maybe due to packaging on arch?

**Comment by Grosskopf** [comment]
oh, I found one command where it worked, but the basic tex commands like \textbf have no documentation, that's quite bad

**Comment by Grosskopf** [comment]
> no feedback. original feature request is impossible, as there is no complete list "command" -> "help text"

you mean  noone has a complete list of helptexts for all the commands that are usable without including a package? O.o that's quite terrifying
