### ISSUE TITLE
Appstream metainfo file no longer gets installed after switch to cmake

### ISSUE THREAD

**Issue by Alexander-Wilms** [texstudio-org/texstudio#2934]
This looks looks like an issue due to the switch to cmake:

https://github.com/texstudio-org/texstudio/blob/3fda475ed7d33e7c97f596c8aa0d772d115bcd02/CMakeLists.txt#L427-L429

I tried to undefine NO_APPDATA with -DNO_APPDATA= and -UNO_APPDATA, but neither worked.

### Environment
- TeXstudio: 4.5.1
- Qt: 6.4
- OS: Linux
- TeX distribution: na

### Expected behavior
```
-- Installing: /app/share/applications/texstudio.desktop
-- Installing: /app/share/icons/hicolor/scalable/apps/texstudio.svg
-- Installing: /app/share/metainfo/texstudio.metainfo.xml
```

### Actual behavior

```
-- Installing: /app/share/applications/texstudio.desktop
-- Installing: /app/share/icons/hicolor/scalable/apps/texstudio.svg
```

### How to reproduce
```
mkdir build
cd build
cmake ..
make
make install
```

See also https://github.com/flathub/org.texstudio.TeXstudio/pull/129 and the build log https://buildbot.flathub.org/#/builders/33/builds/2633/steps/8/logs/stdio

**Comment by sunderme** [comment]
use `-DAPPDATA=on/off`
