### ISSUE TITLE
Hidden feature of About dialog

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2935]
The About dialog (menu Help) shows at top the TeXstudio logo (image size 500x300). It's not obvious that it has a context menu attached with action "large". This action opens a new window showing an enlarged version of the image (999x599). Any ideas about that?

- leave it as is?
- remove?
- add a tooltip to the image like "right click for menu"?
- replace menu action by a mouse action and add tooltip "click to enlarge"?
- anything else?

**Comment by sunderme** [comment]
leave it as it is
