### ISSUE TITLE
incorrect syntax highlighting upon opening document

### ISSUE THREAD

**Issue by mbertucci47** [texstudio-org/texstudio#2937]
### Environment
- TeXstudio: 4.5.1
- Qt: 6.4.2
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
One would expect the syntax highlighting for packages, environments, etc. to be active immediately upon opening a .tex file. Usually this is true, but as long as I've used texstudio (~4 years) I've noticed examples of this failing. My unscientific observations show two cases: large, complicated documents and any document using beamer.

### Case 1: Large, complicated documents
Open the proflycee package [documentation](http://mirrors.ctan.org/macros/latex/contrib/proflycee/doc/ProfLycee-doc.tex). I see this:
<img width="872" alt="proflycee_bad" src="https://user-images.githubusercontent.com/61854785/217142403-685abf02-0b2f-4bbf-a0ec-e0638679a221.png">
No highlighting of packages or the article class.

Scroll down a bit:
<img width="935" alt="proflycee_bad2" src="https://user-images.githubusercontent.com/61854785/217142611-f18fd174-4695-4228-8c6e-7cf2a474a99c.png">
The environments are the correct color of `\begin` and `\end` but the envname is not the right color. The section titles are also not colored. The TikZ env highlighting is correct.

Usually I can fix this by just hitting Return on the line containing the document class, then putting it back where it started:
<img width="867" alt="proflycee_enter" src="https://user-images.githubusercontent.com/61854785/217143051-6fcbba7e-b5d1-4b98-9f9c-b9bfe29a039b.png">
then voilà:
<img width="872" alt="proflycee_good" src="https://user-images.githubusercontent.com/61854785/217143090-2cc261bd-9329-4be9-9adb-044e2293f1f7.png">
and if I scroll down
<img width="932" alt="proflycee_good2" src="https://user-images.githubusercontent.com/61854785/217143182-48434c3c-2020-458c-93b5-70a17f20e981.png">
All highlighting is correct.

If I open any normal, smallish document, I have no problems and the highlighting is good from the start.

### Case 2: beamer documents
Every beamer document I open starts off like the one above, with incomplete highlighting. Sometimes it can be fixed in the same way, but sometimes not. For example, if you open the texstudio Beamer [template](https://github.com/texstudio-org/texstudio/blob/master/templates/template_Beamer.tex) it looks like this:
<img width="186" alt="bad_highlighting" src="https://user-images.githubusercontent.com/61854785/217143604-d6680888-5a5a-47e9-8b5b-e77e9ff6bb4d.png">

Trying the same trick as above looks like it might work:
<img width="182" alt="one_enter" src="https://user-images.githubusercontent.com/61854785/217143700-99e1e6b2-cb11-47f8-830d-81508a1fb354.png">

But if I put the `\documentclass` line back at the top, it just returns to its initial state of no package, env, etc. highlighting.

If I mess with other things in the document, it partially highlights those things. Hitting backspace on the `}` of `\begin{document}` does this:
<img width="190" alt="backspace_doc" src="https://user-images.githubusercontent.com/61854785/217144026-cf360216-9cba-47a6-a4a8-ef688e77193f.png">
Just `\begin{document}` and the first `\begin{frame}` are correctly highlighted.

Hitting enter on the second `\begin{frame}` line and putting it back does this:
<img width="199" alt="enter_frame" src="https://user-images.githubusercontent.com/61854785/217144202-fa28ceba-5830-4835-9967-4aa6f5335447.png">
So everything except the first `\end{frame}` is correctly highlighted.

No amount of moving or deleting and re-entering things managed to make the highlighting work all at once.

**Comment by sunderme** [comment]
I think this is fixed now, please check.

**Comment by sunderme** [comment]
commit 2e84559986d9f495fd9006a3ecb48ae15c5bf3bd

**Comment by mbertucci47** [comment]
Looks like it, thanks!
