### ISSUE TITLE
Automatic dark mode

### ISSUE THREAD

**Issue by dctreu** [texstudio-org/texstudio#2938]
On my Windows 11 PC, I use a utility to automatically switch between Dark mode and Light mode depending on time of day. At the moment, I manually change between "Adwaita" style and "Adwaita dark" style on TeXstudio.
Would it be feasible to have an option to change between styles depending on the system theme?

EDIT: originally got styles and color schemes mixed up.

**Comment by sunderme** [comment]
in principle it should work (at least on osx) with classic colorscheme and default style.
But I need to check.
If that works the same way on win11, I don't know.

**Comment by Mine-Modder** [comment]
> in principle it should work (at least on osx) with classic colorscheme and default style. But I need to check. If that works the same way on win11, I don't know.

Automatic theme switching does not occur with the classic color scheme and default style on Windows 10 and 11. I verified that it does work on macOS.

As a side note, would an idea be to add a separate setting for which theme to use in light and dark mode?

**Comment by dctreu** [comment]
Letting the user choose a theme for light mode and a theme for dark mode seems like a good idea to me!

Indeed at the moment on Windows there is no automatic theme switching.

**Comment by sunderme** [comment]
Qt6.5 introduces theme detection, so txs 4.5.2 will detect dark/light.
