### ISSUE TITLE
Content navigator highlighting color

### ISSUE THREAD

**Issue by kteppris** [texstudio-org/texstudio#2943]
First, thanks for your great work, really love to use this editor in daily life. 
There is only one little thing that is bothering me all day long, the neon green highlighting color in the content navigator.
I read that it's more of a QT thing and it could be influenced by the system color palette, but I really don't know how to change it.
System: Windows 11
![image](https://user-images.githubusercontent.com/66556136/217481293-3bed2e61-d943-484b-9a81-cf05f1c011f9.png)

How can I change the highlighting color of the content navigator? If it's only possible to do it over qss, would you be so kind to share with me how to do it?

**Comment by octaeder** [comment]
There is an option for this. Open configuration (Options Menu), select "Adv. Editor" group and find the color dropdown list here:

![image](https://user-images.githubusercontent.com/102688820/217484234-04bde647-8420-4c85-897f-5fec40e1a7e4.png)

**Comment by kteppris** [comment]
Oh wow, I and tried so many things, in the end so obvious 🤦‍♂️
Now it looks amazing without any highlighting. 
Thanks for the fast answer!
