### ISSUE TITLE
Error in building texstudio

### ISSUE THREAD

**Issue by pisabos1705** [texstudio-org/texstudio#2947]
Since several years I use texstudio with macos. With the aim of introducing my own pannels of tags I  used to buid the application by means of command qmake. 
Actually, I work with macos13.1 and the compilation of texstudio-4.5.1 with qmake does not work with QT6.4.2. I have just tried to build texstudio.app in using the commands file BUILD.sh. I installed QT6.4.2 and command Cmake with brew and I typed  sh BUID.sh. The commands file runs without any error messages and ends with the messages 
[100%] Linking CXX executable texstudio.app/Contents/MacOS/texstudio
[100%] Built target texstudio
Compilation done
I find texstudio.app in the build file but I cannot launch this application, the file texstudio.app appears corrupted. 
Where can the mistake be?

**Comment by sunderme** [comment]
complete logs may give more insight.
Also provide step-by-step insights what you do. E.g. "lauching aplication does not work"  double click, command line ? error messages ? Details matter.
In principle compiling on OSX works.

**Comment by pisabos1705** [comment]
More precisons.  I work with MacOS13.1, at the terminal application I type the command
sh BUILD.sh
the following dialog takes place
TeXstudio compilation :
----------------------------------------
Darwin
-n Enter SYSTEM (1: UNIX ; 2: MACOSX)
 (default is 2) :

-n Do you want to use the video player in pdf files (requires the qtmulitmedia library)? (yes/no)
 (default is no) :

-n Do you want to build a debug or release version?
 (default is debug) :
release
-n Do you want to enable the debug logger? (yes/no)
 (default is no) 
Then compilation starts, I 
[build.log](https://github.com/texstudio-org/texstudio/files/10714455/build.log)
[build.log](https://github.com/texstudio-org/texstudio/files/10714459/build.log)
attach the log file under the name build.log 

The compilation ends with the mesages 
[100%] Linking CXX executable texstudio.app/Contents/MacOS/texstudio
[100%] Built target texstudio
Compilation done
Into the folder texstudio-4.5.1/build I find the icon of the application texstudio.app and  I double click on it, but the application is not launched, without any error message. However the size of the file texstudio.app appears to be only 1 byte! Moreover, if I go into contents of texstudio.app and I click on MacOS/texstudio I get an error message "the file texstudio has inconsistent line terminations"

[build.log](https://github.com/texstudio-org/texstudio/files/10714461/build.log)

**Comment by sunderme** [comment]
have you tried command line "open texstudio.app" in the appropriate folder ?

**Comment by pisabos1705** [comment]
I have just tried. I get the following message (in french):
"Impossible d'ouvrir texstudio-4.5.1 car  le développeur ne peut pas être vérifié"
This message is send by MacOS which cannot verify if this application includes some malware.
I verified the content of application texstudio.app which looks fine. I suspect that my problem is not a bug in compilation but I think that the security system of MacOS prevents me to open texstudio. In  Security of  MacOS Preferences, it's indicated that texstudio is locked because this application comes from an unidentified developer. I click on the button
"open anyway" but this has no effect, texstudio doesnt open. I don't know what I can do, maybe call the Apple support.

**Comment by sunderme** [comment]
here it worked to start, on command line, `texstudio.app/.../macos/texstudio` but in principle OSX security is the issue.

**Comment by pisabos1705** [comment]
I think so too. But, in so far as the button  "open anyway" in Preferences does not work I dont see any solution for unlocking texstudio.app, especially since I don't have this problem with earlier versions of texstudio. Today Sunday, 
tomorrow I'll call Apple support to ask if they have a solution to force the unlocking of an application

**Comment by pisabos1705** [comment]
In the log file of the command sh BUID.sh, I find something that seems strange to me:
-- The C compiler identification is AppleClang 11.0.3.11030032
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/local/bin/git (found version "2.39.1") 
-- No git present.
CMake Warning at cmake/project_version.cmake:52 (message):
  Version from git (0.0.0) doesn't match PROJECT_VERSION (4.5.1)
Call Stack (most recent call first):
  CMakeLists.txt:29 (include)

What is this git? What is its role? 
Isn't it weird to have "Found Git: /usr/local/bin/git (found version "2.39.1")"  before the following line "No git present."?  
What does mean this line "Version from git (0.0.0) doesn't match PROJECT_VERSION (4.5.1)"?

**Comment by sunderme** [comment]
you did not fetch the tags.

**Comment by pisabos1705** [comment]
Sorry, I dont understand. What sort of tags? The files .xml into the folder texstudio/tags? Why the command BUILD.sh dont fetch them?

**Comment by sunderme** [comment]
git tags

**Comment by pisabos1705** [comment]
OK, but when I should run this command? Before sh.BUILD? Why the file BUILD does not include such a command?

**Comment by sunderme** [comment]
https://github.com/texstudio-org/texstudio/issues/2870#issuecomment-1402131626

**Comment by pisabos1705** [comment]
The case of dbitouze looks similar to mine, I tried  to draw inspiration from it. For that I typed the commands 
make clean
cd build
cmake ..

When it ends I typed the git commands
git fetch --tags origin master then git merge FETCH_HEAD.
Both produce the error french message "fatal : ni ceci ni aucun de ses répertoires parents n'est un dépôt git : .git"
whose meaning I did not understand. 
Then I tried again  sh BUILD.sh which fails, always with the messages 
-- Found Git: /usr/local/bin/git (found version "2.39.1") 
-- No git present.
CMake Warning at cmake/project_version.cmake:52 (message):
  Version from git (0.0.0) doesn't match PROJECT_VERSION (4.5.1)

At the end, I get in the build folder a texstudio.app icon of size 1 byte. I suppose it's not the applicatio texstudio but only a link. Of course, double-clicking does not work. In security og MacOS system, texstudio is not referenced as locked. I think really that it is the compilation that has failed.

**Comment by sunderme** [comment]
1) my guess is that you are downloading txs source but do not checkout via git ?
2) warnings are **not** errors and can be ignored unless something really fails down the line, which seems not to be the case here.

**Comment by pisabos1705** [comment]
OK, you are right. I only downloaded txs source as I did with previous release when I could compile it with qmake. Of course, I dont checkout via git because I  dont know git and what role it plays. Moreover, I dont know what is this operation "do checkout via git"
