### ISSUE TITLE
Button not visible in dark mode

### ISSUE THREAD

**Issue by aregkarapetyan** [texstudio-org/texstudio#2951]
### Environment
- TeXstudio: 4.51
- Qt: 6.42
- OS: Windows 11
- TeX distribution: miktex

### Expected behavior
This issue happens in dark mode.  When PDF is switched to a windowed viewer, there is a button that switches back to the embedded mode, and it is visible to the user.

### Actual behavior

The button which should switch back to the embedded viewer is not visible at all, and you can see it only if you hover over it.

![image](https://user-images.githubusercontent.com/38075172/218321533-8a068d9f-ddfa-48d0-b871-7a207f1a3000.png)

**Comment by sunderme** [comment]
should be fixed with 4fee6989817f992d6b7319c5f654c9cad59e0c41
