### ISSUE TITLE
Show list of defined labels when typing \label just like it's already done with \ref

### ISSUE THREAD

**Issue by SGJ99** [texstudio-org/texstudio#2954]
### Describe the feature and the current behavior/state
Currently, when you type \ref you get a list of all defined labels. However, when you type \label, you get no such list. The issue is that I cannot know if a label is already defined when typing \label until I define the label and get the underline showing the label was already defined. It would be nice if we could get the list of all defined labels when typing  \label, just like it already happens with \ref, just like in the picture below

![image](https://user-images.githubusercontent.com/125371140/218748564-02b4d7a0-6f92-417a-a2e9-54c66fa343db.png)

This would help defining new labels, as the list narrows as you type and you can easily see if the label you are defining is already used

**Comment by octaeder** [comment]
after typing \label use the completer to complete the command to \label{key} (key is selected). Start typing your label. As soon as the name is one already used the color changes from green to violet (for all label commands using the duplicate name).
There is a list of all labels in the structure view.

**Comment by octaeder** [comment]
The list is limited as I can see above. So you can't see if 19 is already used or all numbers up to 39. In which way will you use the list to figure out the smallest (or any) free number?

**Comment by SGJ99** [comment]
> The list is limited as I can see above. So you can't see if 19 is already used or all numbers up to 39. In which way will you use the list to figure out the smallest (or any) free number?

I can easily (and very fast) press page down or page up on the list to check the rest of the labels. It even shows the ones starting from 20, so I can spot a free label in between numbers if there is one. It would be nice if the size of the autocomplete box was tunable, but I don't think it's necessary

**Comment by sunderme** [comment]
That is not what the completer is for.
You have a list of labels in structure/TOC view.

**Comment by SGJ99** [comment]
> That is not what the completer is for. You have a list of labels in structure/TOC view.

Ok, I thought I'd ask if it was possible. That is how it works in winedt, \label opens a list just like \ref does. I'm currently getting the desired functionality using \ref first to see the list of labels, and after defining the new label I just replace \ref with \label.  

Thanks

**Comment by sunderme** [comment]
this probably something where a script may be helpful.
See https://texstudio-org.github.io/advanced.html#script-macros (and there editor.document().labelItems/refItems/bibItems ) 
see also https://github.com/texstudio-org/texstudio/wiki/Scripts for some inspiration.

**Comment by SGJ99** [comment]
> this probably something where a script may be helpful. See https://texstudio-org.github.io/advanced.html#script-macros (and there editor.document().labelItems/refItems/bibItems ) see also https://github.com/texstudio-org/texstudio/wiki/Scripts for some inspiration.

Yes, I was thinking I would eventually do a macro or something similar to get what I want. Thank you for the info

**Comment by saxyx** [comment]
> > That is not what the completer is for. You have a list of labels in structure/TOC view.
> 
> Ok, I thought I'd ask if it was possible. That is how it works in winedt, \label opens a list just like \ref does. I'm currently getting the desired functionality using \ref first to see the list of labels, and after defining the new label I just replace \ref with \label.
> 
> Thanks

Perhaps the solutions in the following website can solve your problem. Replace "\alternative{label}#r" in the tutorial with" \label{label}#r".
https://tex.stackexchange.com/questions/414281/configuring-auto-completion-with-texstudio

**Comment by octaeder** [comment]
I have a question regarding label list and focus. I often autocomplete the label command, i.e. I see \label{key} with placeholder _key_ selected in the editor. Then I open the label list in the structure pane with a mouse click to check which labels are already used. Then I want to go back to the editor to fill the placeholder. I expected some `tab` key action or a mouse click on the editor tab to bring focus back to the editor/placeholder. The first way needs 16 tab keys, depending on the number of drop down boxes available below the menu bar. But I can't notice for each tab where the focus goes to. The latter doesn't work at all. Is there a quick way to achieve the desired result? The one I found is a double click on the placeholder.

More generally spoken: After clicking on a structure item how can I come back to the editor without changing cursor/selection in the text? Both, a click action on the tab and a key action would be nice.
