### ISSUE TITLE
no new line in editor tab tooltip for included documents

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2955]
### Environment
- TeXstudio: all incl. current dev, language German, maybe others
- OS: Win10, but likely not OS specific

### Expected behavior
The line break should appear in any translations as it is for English (s. image below).

### Actual behavior
Code affected: txstabwidget.cpp - ``tooltip += tr("\nincluded document in %1").arg(rootDoc->getName());``

with standard app language English we see:
![grafik](https://user-images.githubusercontent.com/102688820/218698043-b785f356-8914-470c-9c33-03c0fc78b0d7.png)

with app language German no line break happens:
![grafik](https://user-images.githubusercontent.com/102688820/218698123-80dd8028-a877-4afb-9176-b6bb2c2a568a.png)

Attention: For language change take effect here txs has to be restarted.

The reason for this is most likely the German translation:
![grafik](https://user-images.githubusercontent.com/102688820/218698640-5f438593-d0b6-4680-b776-623f162508b0.png)
Be aware of the new line character to the left of the English version.

Suggestion: Remove the new line character from the part to be translated in the code to avoid such  problems:
```
tooltip += "\n" + tr("included document in %1").arg(rootDoc->getName());
```
From a technical point of view the tooltip is misleading since the document is not directly included in the given document. It's rather the root document.

### How to reproduce
Open a root document and a document included by this root. Look at tooltips of editor tabs.

#### In the TOC view a space is missing as a separator

English:
![grafik](https://user-images.githubusercontent.com/102688820/218705277-8e537b78-1e67-4f5c-8424-94fbd5387df2.png)
German (translation 2183):
![grafik](https://user-images.githubusercontent.com/102688820/218705393-d7b562d6-cecb-4bbf-96b1-d16a3e523dab.png)

texstudio.cpp (check 3 places in the code):
```
item->setToolTip(0,tr("Document: ")+docName);
```
Suggestion: Change to:
```
item->setToolTip(0,tr("Document:")+" "+docName);
```

#### In the list of recently opened documents a space is missing as a separator

![grafik](https://user-images.githubusercontent.com/102688820/218717645-afe6016e-a05c-450f-9706-692c125c08e1.png)

Translation 808, configmanager.cpp line 1987

**Comment by sunderme** [comment]
the translation was fixed
