### ISSUE TITLE
Tex Studio Help opens Calibre EPub Editor

### ISSUE THREAD

**Issue by BlackSouthIndian** [texstudio-org/texstudio#2959]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior
Open Latex Reference

### Actual behavior

Opens Calibre Epub Editor
### How to reproduce
Click latex reference from Help on Tex Studio after installing Calibre first

**Comment by sunderme** [comment]
Environment ????

    TeXstudio:
    Qt:
    OS:
    TeX distribution:

**Comment by muzimuzhi** [comment]
> Click latex reference from Help on Tex Studio after installing Calibre first

Any chance that Calibre, not a web browser, is configured to be the default application for html files?

**Comment by sunderme** [comment]
no feedback of essential information.
txs asks the OS to open a html file, calibre probably has changed html default application to calibre.
