### ISSUE TITLE
Include a Latex document from Jupyter inside a another LateX document  

### ISSUE THREAD

**Issue by mezaacor** [texstudio-org/texstudio#296]
<Hello everybody, please I need help with the following issue: How can I include a Latex document from Jupyter inside a another document in TEXstudio?

 I was using **\include{latex_document}**, but it doesn't work

Thanks a lot>

**Comment by sunderme** [comment]
this looks like a LaTeX question. Please use tex.stackexchange.com for questions which are not related to txs, a latex text editor.
