### ISSUE TITLE
Missing `JlCompress.h`

### ISSUE THREAD

**Issue by tmelorc** [texstudio-org/texstudio#2961]
Where is the file `JlCompress.h`? 
I tried to compile on Linux and I got the following error: `src/spellerutility.cpp:14:24: fatal error: JlCompress.h:`

### Edit

```
# qmake texstudio.pro 
Project MESSAGE: Building via qmake (.pro) deprecated. Please use cmake instead.
Project MESSAGE: Building with Qt 5.11.1
Project MESSAGE: Static hunspell
Cannot read ***/texstudio/src/quazip/quazip/quazip.pri: No such file or directory
Project MESSAGE: Creating release version
Project MESSAGE: tests are disabled
Project MESSAGE: GIT sh
create git_revision.cpp
```

**Comment by octaeder** [comment]
I find it here C:\msys64\home\WDAG\texstudio-org\texstudio\src\quazip\quazip
Build of current master for win10 worked for me

**Comment by tmelorc** [comment]
> I find it here C:\msys64\home\WDAG\texstudio-org\texstudio\src\quazip\quazip Build of current master for win10 worked for me

Oh, yes, it is there. But I don't know why compiling on my Linux Mint machine does not work.

**Comment by octaeder** [comment]
there were changes some hours ago regarding quazip, maybe one has to search there 2955ffbb8ad15f26ba7481cbfb75dfa191b8a991

**Comment by sunderme** [comment]
qmake will not be supported any longer.
(qmake does already not build with qt6)
I would suggest to transition to cmake see INSTALL, wiki and manual.

**Comment by sunderme** [comment]
quazip1.4 does not support qmake either, short term work around would be to use system quazip.

**Comment by tmelorc** [comment]
> qmake will not be supported any longer. (qmake does already not build with qt6) I would suggest to transition to cmake see INSTALL, wiki and manual.

Thanks. I'll take a look.
