### ISSUE TITLE
keyval `label=##l` does not work if `#c` specified

### ISSUE THREAD

**Issue by mbertucci47** [texstudio-org/texstudio#2966]
### Environment
- TeXstudio: 4.5.2
- Qt: 6.4.2
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
You can specify a keyval that, for the purposes of autocompletion, defines a label with `keyname=##l` in the cwl. This should work regardless of whether or not that command was given the `#c` specifier.

### How to reproduce
The cwl
```
# mypkg.cwl

\foo{keyvals}
\footwo{keyvals}

#keyvals:\foo#c,\footwo
label=##l
#endkeyvals
```
results in

<img width="155" alt="Screenshot 2023-02-21 125846" src="https://user-images.githubusercontent.com/61854785/220445935-75e9927f-8f47-4676-af39-d42b7b3b8bf8.png">

The command given the `#c` specifier does not define the label given as a keyval, but the command without `#c` does.

#### Source
```latex
\documentclass{article}

\usepackage{mypkg}

\begin{document}
\foo{label=abc}
\footwo{label=xyz}

\ref{abc}
\ref{xyz}
\end{document}
```

**Comment by sunderme** [comment]
`#keyvals:\foo#c` was not supposed to be an option
#c was defined for actual keys.
So, what is supposed to happen with with foo#c keyvals ?

**Comment by mbertucci47** [comment]
Hmm the usage `#keyvals:\foo#c` was here long before I started contributing cwls. Whether or not it is intended, the effect of using `#c` in this way is to have completion of keyvals without marking anything in the arg as invalid. Using the same mypkg.cwl above, you can see this in
<img width="155" alt="Screenshot 2023-02-22 083737" src="https://user-images.githubusercontent.com/61854785/220673814-84ad14fc-18ae-4d66-a063-c2ad328ba26e.png">
This is useful when a command has lots of keyvals, especially with syntax that texstudio couldn't hope to parse, such as tikz commands.

Quick experiments show that actually using `c` in `\foo#c` is necessary; replacing it with something like `\foo#k` breaks the autocompletion.

I'm not sure what you mean when you say "#c was defined for actual keys". What is the expected effect of something like
```
\foo{keyvals}

#keyvals:\foo
somekey
anotherkey#c
#endkeyvals
```
or is this not the syntax you're hinting at?

**Comment by sunderme** [comment]
the original intention was something like
```
#keyvals:\foo
somekey=a,b,c#c
#endkeyvals
```
where also other values but a,b or c are valid.

I will adapt the code that #c in `#keyvals` is handled sensibly.
