### ISSUE TITLE
update state of Quick Build icon in pdf viewer

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2967]
### Describe the feature and the current behavior/state
txs has a button icon ![grafik](https://user-images.githubusercontent.com/102688820/220460967-df53ffe2-4d18-404c-8487-04b43fb670ef.png) (tooltip Build & View) in the task bar. The pdf viewer shows the same icon (tooltip Quick Build). Pressing each of the buttons locks following buttons in txs: ![grafik](https://user-images.githubusercontent.com/102688820/220460507-bef27e9a-083b-4202-b711-291bcadbbda4.png) (ignore the extra PDF-LaTeX button). This is the same in the menu:
![grafik](https://user-images.githubusercontent.com/102688820/220461856-6485c695-4954-419e-8c29-96dc00ae6de1.png)

But the look of the icon in the pdf viewer never changes the look to locked. Thus it's not clear if you can start a build or if still one is running in the background.

### Who will benefit with this feature?
Those who start builds from the viewer receive visual feedback when a build is running.

**Comment by idamir** [comment]
A note: the PDFViewer must be compiled and moved to a separate window to reproduce described issue.

**Comment by idamir** [comment]
Got the fix.

**Comment by octaeder** [comment]
so you make a PR?

**Comment by idamir** [comment]
i will asap after tests
