### ISSUE TITLE
Unwanted Chinese characters in the cite command key list.

### ISSUE THREAD

**Issue by yaskoetemovic** [texstudio-org/texstudio#2969]
### Environment
- TeXstudio: 2.12.6
- OS: Windows(10)
- TeX distribution: miktex

### Expected behavior
Cite command key list should list the keys as I defined already.

### Actual behavior
![image](https://user-images.githubusercontent.com/101531157/220614947-e9094f9c-4bb0-43c7-a7f1-cd4bab739ab5.png)

I have written to tex.stackexhange for the issue, but they directed me here, since this looked them as an encription problem due TeXstudio.

Thanks for helping.

**Comment by muzimuzhi** [comment]
Looks like an encoding-decoding issue. What's the encoding of your bib file and how are bib entries in it named?

**Comment by yaskoetemovic** [comment]
Well, I do not understand what you say. But, I created my bib file by copy/pasting my sources like here,
```
@article{gurbulak1999optical,
  title={The optical absorption edge of p-type Tl$_{(1-x)}$ GaPr$_x$Se$_2$ and TlGaSe$_2$},
  author={G{\"u}rbulak, B},
  journal={Physica Scripta},
  volume={60},
  number={6},
  pages={584},
  year={1999},
  publisher={IOP Publishing},
%doi = {10.1238/Physica.Regular.060a00584}
}
```
I do not know more details, I am working with iopart class and related styles.

Thanks

**Comment by muzimuzhi** [comment]
Can you check the encoding of both your tex file and the bib file? Online Q&A: [Get encoding of a file in Windows](https://stackoverflow.com/questions/3710374/get-encoding-of-a-file-in-windows). In the bib file snippet, that bib item/entry is named `gurbulak1999optical`.

**Comment by sunderme** [comment]
any particular reason why to use such an old version of texstudio (2.12.6) ?

**Comment by sunderme** [comment]
and I would suggest that you upload here a complete example of a failing document.

**Comment by sunderme** [comment]
any news. With utf8, there definitely no chinese characters.

**Comment by sunderme** [comment]
no feedback
likely coding issue.
