### ISSUE TITLE
show nesting of foldable groups 

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2970]
### Describe the feature and the current behavior/state
Currently the first line of any foldable group shows a small triangle. By hovering the mouse pointer of the triangle a vertical line is inserted below the triangle and visualizes the extent of the group. For a large group this doesn't suffice to get an overview of the group because we need to scroll. But then the line will disappear. Also it's difficult to see how groups are nested or to find incomplete groups. The following images show how it could look like. The graphic design is a slightly adopted/simplified version of what notepad++ uses.

![grafik](https://user-images.githubusercontent.com/102688820/220791595-3dbbdc39-1602-4fd1-b339-30582c92fb31.png)  ![grafik](https://user-images.githubusercontent.com/102688820/220792349-36999c79-d6a2-40ae-82bd-d87d620cdb75.png)

The group directly containing the cursor is highlighted.

### Who will benefit with this feature?
Anyone who has higher nesting levels in the document.

**Comment by sunderme** [comment]
I may misunderstand, but currently txs draws a line from the hovered triangle to the end of the range.
So, coming back to the picture above, that seems to be clearer than adding some gray lines additionally which reduces contrast especially as in reality, everything is distinctly smaller on screen.

**Comment by sunderme** [comment]
placing the cursor behind the `\begin{env}|` shows the context also way clearer.
<img width="158" alt="grafik" src="https://user-images.githubusercontent.com/14033169/220936159-76fa1856-5a64-46b2-8ab2-8f8703005767.png">

So, overall, I am not in favor to have persistant markers on the sidepanel.

**Comment by octaeder** [comment]
Assume the cursor is midway of a larger group, then your solution needs to search the first line of the group (and moving the cursor might not be desired). Also it doesn't work for groups defined by sectioning commands, or made from curly braces or brackets. What can make the situation more difficult is code without indentations. Color seems to be a minor problem (s. following images).


What I simplified at first but might be desirable is that the subgroup relation is  presented in a clearer way by drawing the red line only over the left half of the square (right image) for subgroups of the current group (the one with the cursor):

![grafik](https://user-images.githubusercontent.com/102688820/221069029-2fd23155-e7ba-402a-83ca-26962ff2823b.png)

A less noticable solution could be to show only the smallest group where the cursor is in. This should help in all cases discussed so far.

**Comment by sunderme** [comment]
My guess is that the marker is persistent and the red is the outer/inner (?) environment for the current cursor position ?
In normal circumstances, the left part is simply visual clutter.
For the case that you really need to find opening/closing, it makes it visually more difficult to see where what starts and end. If everything is within the viewport, the current solution is **way** better by hovering and highlighting the range.
If it is larger than viewport, jumping to the end is the best solution. Your visualization offers a slight advantage but you may not move the cursor and it is not a clear winner as the start is not visible either.

**Comment by octaeder** [comment]
sorry, right image was wrong, cursor is in the center env. This is now corrected. yes static display.
the red marked group is the smallest (innermost, or current) group containing the cursor
if everything is in the viewport the case is simple. Think of lists of items of text, lists, equations, tex groups and so on.
what do you mean by jumping to the end - how do you jump to the end of a group?
while scrolling it's quite easy to find the start or the end with the red mark and thus go up hierarchy of groups.
What does VScode?

**Comment by sunderme** [comment]
idefix:
<img width="571" alt="grafik" src="https://user-images.githubusercontent.com/14033169/221186820-70e95788-60db-4e3e-a34b-09e794feb847.png">

**Comment by sunderme** [comment]
the less intrusive solution may, be that double/triple click selects the whole environment/paragraph.
This would make it very clear where it starts and ends, scrolling is allowed.
Currently triple click selects a line.

**Comment by octaeder** [comment]
funny, understood long time ago that pdf preview selection/parenthesis accepts begin-end-envs as "parenthesis", but didn't transfer this to parentheses menu (select inner/outer shortcuts are well known to me). So no need to change triple click behavior in the config. Only problem this doesn't work for sectioning commands.

so your latest suggestion works like this: when the cursor is set to the left or right of an opening or a closing "parenthesis" then yellow coloring of the "parenthesis" happens and in addition the line (that normally shows when the mouse hovers over the triangle) is present as long as the cursor isn't moved away. So scrolling to the end or start would be no problem. This would clearly be an improvement. Any idea what could be done with sections?

A drawback is that this solution depends on being at the start or end of the group. There is no functionality that finds the start (or end). Do you have an idea, that also works for sections? This would come close to what I described with current group for the cursor.

**Comment by sunderme** [comment]
sections are rather handled in the structure view/TOC.
context menu/copy would select the complete section.

**Comment by octaeder** [comment]
this is a little bit disruptive. Copying a complete section (chapter, ...) to the clipboard just to see where it is sounds not good. Maybe add item "select" to the menu? But all this looks not well integrated and doesn't look satisfactory.
It seems that data is missing that allows mapping the current line to the foldable group.

**Comment by sunderme** [comment]
the actual question is, what do you want to achieve here ?
Why scroll along a red line when you can directly jump to the next section via TOC ?

**Comment by octaeder** [comment]
Mainly searching and moving selected code.
Since all this seems useless to you I would conclude that the vertical line shown as a "tooltip" below foldmarks is useless too, and this is obviously true if the group is larger than the viewport. You suggested using highlighting process for parentheses but this will not affect all foldable groups. Is there anything that can be improved here? The TOC shows subsection relation, the structure shows file includes relation, and there are foldable groups but nothing shows the subgroup relation. I think that each of these relations is usefull. Not having it can make life sometimes more complicated.

**Comment by sunderme** [comment]
how about enabling scrolling via wheel when hovering over the range mark (and keeping the mark until a tbd criteria ) ?
