### ISSUE TITLE
Parsing Error in DeclarePairedDelimiterXPP

### ISSUE THREAD

**Issue by Sam-OT** [texstudio-org/texstudio#2971]
The use of `\DeclarePairedDelimiterXPP` from [mathtools](https://texdoc.org/serve/mathtools/0#subsection.3.6) causes some confusion in TeXstudio's parsing. The following snippet compiles fine, with no errors, but the parser gives some "unrecognised command" errors, as well as "no error" on "\Pr". The code-linting part also gets confused.

> ![image](https://user-images.githubusercontent.com/81111289/220890627-a08f3f70-64b1-41c2-b489-85d27b4c9445.png)

```
\documentclass[]{article}

\usepackage{mathtools}
\DeclarePairedDelimiterXPP{\PR}[1]{\Pr}(){}{#1}
\newcommand{\eps}{\varepsilon}
\newcommand{\vph}{\varphi}
\newcommand{\vsi}{\varsigma}

\begin{document}
\[ \PR{X_t > \eps \vph \vsi} \]
\end{document}
```

The same happens with `\DeclarePairedDelimiterX{\tst}[1](){#1}`, but the basic `\DeclarePairedDelimiter` seems fine.

As I said, it does compile, so all is ok. But, it does mean that I have lots of 'fake' errors in my document, and I can't use completion as easily as it thinks that certain commands don't exist.

---

- TeXstudio 4.2.3 (git 4.2.3)
- Using Qt Version 6.3.0, compiled with Qt 6.3.0 R
- Windows 10 Enterprise, 21H2

**Comment by sunderme** [comment]
I am not sure how that is supposed to work.
Your code deviates significantly from the definition in mathtools `\DeclarePairedDelimiterXPP{〈cmd〉}[〈num args〉]{〈pre code〉}{〈left_delim〉}{〈right_delim〉}{〈post code〉}{〈body〉}` and txs just follows that recipe.
That the mathtools parser tries to make sense of that wrong syntax and succeeds (?), is not really a fault of txs.

**Comment by Sam-OT** [comment]
> I am not sure how that is supposed to work. Your code deviates significantly from the definition in mathtools `\DeclarePairedDelimiterXPP{〈cmd〉}[〈num args〉]{〈pre code〉}{〈left_delim〉}{〈right_delim〉}{〈post code〉}{〈body〉}` and txs just follows that recipe. That the mathtools parser tries to make sense of that wrong syntax and succeeds (?), is not really a fault of txs.

@sunderme It is pretty much copied straight from the linked mathtools documentation: see `\Prob` on Page 28, just simplified a bit. Precisely, `\Prob` is given by
```
\DeclarePairedDelimiterXPP\Prob[1]{\mathbb{P}}(){}{
\renewcommand\given{\nonscript\:\delimsize\vert\nonscript\:\mathopen{}}#1}
```

It does seem to follow the recipe, as far as I can tell, but I don't fully understand what is going on.

```
\DeclarePairedDelimiterXPP{〈cmd〉}[〈num args〉]{〈pre code〉}{〈left_delim〉}{〈right_delim〉}{〈post code〉}{〈body〉}
\DeclarePairedDelimiterXPP{\PR}[1]{\Pr}(){}{#1}
```
`〈cmd〉 = \Pr`, `〈num args〉 = 1`, `〈pre code〉 = \Pr`, `〈left_delim〉 = (`, `〈right_delim〉 = )`, `〈post code〉 = ` (empty), `〈body〉 = {#1}`

This appears to follow perfectly to me, but maybe I'm mistaken and/or misunderstanding

**Comment by sunderme** [comment]
okay, I got confused about the `()`
Change it to `{(}{)}` and it should be fine.
(Not sure where `\Pr` is coming from though)

**Comment by Sam-OT** [comment]
> okay, I got confused about the `()` Change it to `{(}{)}` and it should be fine. (Not sure where `\Pr` is coming from though)

I guess you didn't see my edit before posting this, saying that I had tried that and that it didn't work?

**Comment by sunderme** [comment]
works here.
<img width="371" alt="grafik" src="https://user-images.githubusercontent.com/14033169/220908695-d0a8c630-547b-443e-9e30-b473f910fef0.png">

for comparison:
<img width="371" alt="grafik" src="https://user-images.githubusercontent.com/14033169/220908824-8da4ff00-98bb-4f13-84d9-5ceee70f525d.png">

**Comment by Sam-OT** [comment]
> works here. <img alt="grafik" width="371" src="https://user-images.githubusercontent.com/14033169/220908695-d0a8c630-547b-443e-9e30-b473f910fef0.png">
> 
> for comparison: <img alt="grafik" width="371" src="https://user-images.githubusercontent.com/14033169/220908824-8da4ff00-98bb-4f13-84d9-5ceee70f525d.png">

Yep, that's the same as I shared in my previous post. Not sure why `\Pr` is highlighted. The same happens if you try to put something like `\mathbb P` in, making sure to load `amssymb`: the `\mathbb` is highlighted, like it wants to say "math command outside math env", but says "no error". As I said, hardly a big issue :)

>  ![image](https://user-images.githubusercontent.com/81111289/220909574-039e7a0c-8ec7-41df-9066-823cf1f255ec.png)

**Comment by sunderme** [comment]
the last bit is fixed in the repository.
