### ISSUE TITLE
texstudio-4.5.1-win-qt6.exe install fails on Windows 10 (up to date)

### ISSUE THREAD

**Issue by csmcrvrs** [texstudio-org/texstudio#2973]
I have TeXstudio 4.4.1 (git 4.4.1) Using Qt Version 6.4.1, compiled with Qt 6.4.1 R running on Windows 10.

It works fine; I use it a lot.

Last week I got the 4.5.1 upgrade message so I downloaded texstudio-4.5.1-win-qt6.exe. I clicked on it, it brought up the usual do you want to allow changes dialog, I clicked yes, nothing happened.

I tried again today. Same story. 
I tried running it in Administrator mode from the get go, still nada.
I tried turning off all anti-virus protections, still nada.

4.4.1 continues to work fine so this is not an urgent question. Still...
### Environment
- TeXstudio: 4.5.1
- Qt: UNKNOWN.  previous working version:  Qt Version 6.4.1, compiled with Qt 6.4.1 R
- OS: Window's 10
- TeX distribution: miktex

### Expected behavior
Install TeXlive 4.5.1

### Actual behavior
Aborts after permissions dialog.

### How to reproduce
Download texstudio-4.5.1-win-qt6.exe to Windows 10 system and click on it.

**Comment by sunderme** [comment]
4.5.1 installs on win10 here.

**Comment by sunderme** [comment]
not reproducible

**Comment by Excellentelle** [comment]
I use Windows 8.1, pls what version of text studio should I use?

**Comment by octaeder** [comment]
win 8.x is not longer supported with new txs versions.

**Comment by Excellentelle** [comment]
Thanks
