### ISSUE TITLE
Reintroduce templates

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#2975]
With TeXstudio 4.5.2 (git 4.5.1-118-g9c7c37a15), almost all the templates (File → New From Template...) have disappeared: in my case, only the “Article (French) for LuaLaTeX” is still here.

It would be nice to reintroduce the old templates.

**Comment by sunderme** [comment]
works fine here

**Comment by octaeder** [comment]
that' what I see with my Win10 build (TeXstudio 4.5.2 (git 4.5.1-70-gd194111e3)):

![grafik](https://user-images.githubusercontent.com/102688820/221288190-0ced6042-6c4a-4bcf-afbe-e4377a6dcddf.png)

Btw: The text in the middle may need a spacer at the bottom.

**Comment by muzimuzhi** [comment]
fine on macOS (texstudio 4.5.1)
![image](https://user-images.githubusercontent.com/6376638/221292170-12d7f998-fa01-409c-9a25-d2afd4216c31.png)

**Comment by sunderme** [comment]
win build is local cmake build or one from github ?

**Comment by dbitouze** [comment]
Here is what I can see:

![Screenshot_20230224_220821](https://user-images.githubusercontent.com/1032633/221292792-6cc4374e-0996-410a-ba4b-bd49baaede2e.jpg)

**Comment by octaeder** [comment]
> win build is local cmake build or one from github ?

local cmake

**Comment by sunderme** [comment]
@dbitouze also linux local build ?

**Comment by dbitouze** [comment]
> @dbitouze also linux local build ?

I don't see what you mean by “local build”.

**Comment by sunderme** [comment]
a) are you still running linux ?
b) do you build texstudio yourself (with build.sh or directly cmake) or do you download builds from github ?

**Comment by sunderme** [comment]
copy from the source the templates folder to the build folder
(cmake --build . -t install probably works as well, but install txs ususally in /usr/local )

**Comment by dbitouze** [comment]
> a) are you still running linux ? b) do you build texstudio yourself (with build.sh or directly cmake) or do you download builds from github ?

Still running GNU/Linux (Mageia 8), build thanks to `BUILD.sh` (sorry, I added these details afterwards in a previous comment).

**Comment by octaeder** [comment]
![grafik](https://user-images.githubusercontent.com/102688820/221295875-ea9f39d1-fcfa-4b37-9b29-3e2a3ebbd468.png)
copy translation helped

**Comment by dbitouze** [comment]
Copying the `templates` directory into the `build` doesn't help since (AFAICS) it is remove by `BUILD.sh`.

**Comment by octaeder** [comment]
maybe you should copy it after the build. The files are not needed for the build. You not even need to restart txs. When you start the templates dialog then the templates are read

**Comment by octaeder** [comment]
> that' what I see with my Win10 build (TeXstudio 4.5.2 (git 4.5.1-70-gd194111e3)):
> 
> ![grafik](https://user-images.githubusercontent.com/102688820/221288190-0ced6042-6c4a-4bcf-afbe-e4377a6dcddf.png)
> 
> Btw: The text in the middle may need a spacer at the bottom.

PR #2976 will add the spacer

**Comment by sunderme** [comment]
@dbitouze if you choose not to install but run txs directly from the build directory, copying templates should solve the problem. I will check later if something goes wrong when installing to /usr/local ...

**Comment by sunderme** [comment]
install to /usr/local seems to work template wise.

**Comment by sunderme** [comment]
do you tweak the install prefix ? Do you let texstudio to be installed ?

**Comment by dbitouze** [comment]
> maybe you should copy it after the build. The files are not needed for the build. You not even need to restart txs. When you start the templates dialog then the templates are read

It doesn't work either: same result.

**Comment by dbitouze** [comment]
> @dbitouze if you choose not to install but run txs directly from the build directory, copying templates should solve the problem. I will check later if something goes wrong when installing to /usr/local ...

```
$ pwd
/home/bitouze/Public/Repositories/texstudio/build
$ ls -1 templates 
tabletemplate_fullyframed_firstBold.js
tabletemplate_fullyframed_firstBold.png
tabletemplate_fullyframed_longtable.js
tabletemplate_fullyframed_longtable.png
tabletemplate_fullyframed_longtabu.js
tabletemplate_fullyframed_longtabu.png
tabletemplate_plain_tabular.js
tabletemplate_plain_tabular.png
tabletemplate_plain_tabularx.js
tabletemplate_plain_tabularx.png
tabletemplate_rowcolors_tabular.js
tabletemplate_rowcolors_tabular.png
template_Article_French.json
template_Article_French.png
template_Article_French.tex
template_Article.json
template_Article_LuaLaTeX_French.json
template_Article_LuaLaTeX_French.png
template_Article_LuaLaTeX_French.tex
template_Article.png
template_Article.tex
template_Beamer.json
template_Beamer.png
template_Beamer.tex
template_Book.json
template_Book.png
template_Book.zip
template_HA-prosper.json
template_HA-prosper.tex
template_Letter.json
template_Letter.png
template_Letter.tex
template_Moderncv_French.json
template_Moderncv_French.png
template_Moderncv_French.tex
template_Moderncv.json
template_Moderncv.png
template_Moderncv.tex
template_Prosper.json
template_Prosper.tex
template_Report.json
template_Report.png
template_Report.tex
template_Scrartcl.json
template_Scrartcl.png
template_Scrartcl.tex
template_Scrbook.json
template_Scrbook.tex
template_Scrlttr2.json
template_Scrlttr2.tex
template_Scrreprt.json
template_Scrreprt.tex
$ ./texstudio&
```
and still only a single template: “Article (French) for LuaLaTeX”.

**Comment by dbitouze** [comment]
> do you tweak the install prefix ?

I just ran `BUILD.sh` with the defaults options.

> Do you let texstudio to be installed ?

I'm not sure to understand, but the installation went smoothly.

**Comment by sunderme** [comment]
I have replayed all steps here and it works (after copying the templates folder).
```
./BUILD.sh 
TeXstudio compilation :
----------------------------------------
Enter SYSTEM (1: UNIX ; 2: MACOSX) (default is 1) :
Enter PREFIX (/usr , /usr/local or /opt) (default is /usr/local) :
Do you want to use the video player in pdf files (requires the qtmulitmedia library)? (yes/no) (default is no) :
Do you want to build a debug or release version? (default is debug) :
Do you want to include tests in the debug build_ (yes/no) (default is yes) :
Do you want to enable the debug logger? (yes/no) (default is no) :
Do you want to install TexStudio after building it? (yes/no) (default is yes) : no
```
(empty answer, means that the default was used).
Installation refers to last question "Do you want to install TexStudio after building it?" which means all relevant files are copied to /usr/local if permissions are provided.

If that was answered with yes, you should find files in /usr/local/share/texstudio ?

**Comment by dbitouze** [comment]
Sigh...
```bash
$ pwd                                                                                  
/home/bitouze/Public/Repositories/texstudio
$ cp -r templates build
$ ls -1 build # Note: The `templates` directory is there
CMakeCache.txt
CMakeFiles
cmake_install.cmake
git_revision.cpp
install_manifest.txt
Makefile
src
templates
texstudio
texstudio_autogen
$ sh BUILD.sh
sh BUILD.sh                  
TeXstudio compilation :
----------------------------------------
Enter SYSTEM (1: UNIX ; 2: MACOSX) (default is 1) :

Enter PREFIX (/usr , /usr/local or /opt) (default is /usr/local) :

Do you want to use the video player in pdf files (requires the qtmulitmedia library)? (yes/no) (default is no) :

Do you want to build a debug or release version? (default is debug) :

Do you want to include tests in the debug build? (yes/no) (default is yes) :

Do you want to enable the debug logger? (yes/no) (default is no) :

Do you want to install TexStudio after building it? (yes/no) (default is yes) :
yes
[...]
Installation done
Icons and desktop file can be found in the /usr/local/share/texstudio directory
$ ls -1 build # Note: The `templates` directory has been removed
CMakeCache.txt
CMakeFiles
cmake_install.cmake
git_revision.cpp
install_manifest.txt
Makefile
src
texstudio
texstudio_autogen
$ ls -1 /usr/local/share/texstudio/template_*
/usr/local/share/texstudio/template_Article_French.json
/usr/local/share/texstudio/template_Article_French.png
/usr/local/share/texstudio/template_Article_French.tex
/usr/local/share/texstudio/template_Article.json
/usr/local/share/texstudio/template_Article_LuaLaTeX_French.json
/usr/local/share/texstudio/template_Article_LuaLaTeX_French.png
/usr/local/share/texstudio/template_Article_LuaLaTeX_French.tex
/usr/local/share/texstudio/template_Article.png
/usr/local/share/texstudio/template_Article.tex
/usr/local/share/texstudio/template_Beamer.json
/usr/local/share/texstudio/template_Beamer.png
/usr/local/share/texstudio/template_Beamer.tex
/usr/local/share/texstudio/template_Book.json
/usr/local/share/texstudio/template_Book.png
/usr/local/share/texstudio/template_Book.zip
/usr/local/share/texstudio/template_HA-prosper.json
/usr/local/share/texstudio/template_HA-prosper.tex
/usr/local/share/texstudio/template_Letter.json
/usr/local/share/texstudio/template_Letter.png
/usr/local/share/texstudio/template_Letter.tex
/usr/local/share/texstudio/template_Moderncv_French.json
/usr/local/share/texstudio/template_Moderncv_French.png
/usr/local/share/texstudio/template_Moderncv_French.tex
/usr/local/share/texstudio/template_Moderncv.json
/usr/local/share/texstudio/template_Moderncv.png
/usr/local/share/texstudio/template_Moderncv.tex
/usr/local/share/texstudio/template_Prosper.json
/usr/local/share/texstudio/template_Prosper.tex
/usr/local/share/texstudio/template_Report.json
/usr/local/share/texstudio/template_Report.png
/usr/local/share/texstudio/template_Report.tex
/usr/local/share/texstudio/template_Scrartcl.json
/usr/local/share/texstudio/template_Scrartcl.png
/usr/local/share/texstudio/template_Scrartcl.tex
/usr/local/share/texstudio/template_Scrbook.json
/usr/local/share/texstudio/template_Scrbook.tex
/usr/local/share/texstudio/template_Scrlttr2.json
/usr/local/share/texstudio/template_Scrlttr2.tex
/usr/local/share/texstudio/template_Scrreprt.json
/usr/local/share/texstudio/template_Scrreprt.tex
```
But still only a single template: “Article (French) for LuaLaTeX”.

**Comment by sunderme** [comment]
do you have something under `/usr/share/texstudio`

**Comment by dbitouze** [comment]
> do you have something under `/usr/share/texstudio`

Probably a good catch! Indeed:
```bash
$ ls -1 /usr/share/texstudio
advanced.html
background.html
compiling.html
configuration.html
editing.html
genindex.html
getting_started.html
_images
index.html
search.html
_sphinx_design_static
_static
template_Article_LuaLaTeX_French.json
template_Article_LuaLaTeX_French.png
template_Article_LuaLaTeX_French.tex
texstudio_ca.qm
texstudio_ie.qm
texstudio_nb_NO.qm
texstudio_si.qm
texstudio_ug.qm
viewing.html
```

**Comment by dbitouze** [comment]
I removed `/usr/share/texstudio` and, now, all the templates are listed. I don't understand how this folder appeared.
