### ISSUE TITLE
Disable the ability to change options with scroll wheel

### ISSUE THREAD

**Issue by ShaiAvr** [texstudio-org/texstudio#2977]
I often customize the building options in TexStudio and I noticed a feature that I think is more harmful than useful. When there is a drop list to select options from you can change the options by hovering the mouse over the drop box and scrolling with the mouse wheel. I find it very annoying since I often do it unintentionally when I just want to scroll up or down the settings panel. This is most noticeable in the build menu:

![texstudio_Jq6vDrFfWz](https://user-images.githubusercontent.com/35605235/221360685-3f6f6aed-5526-4e18-8c3a-dcce23351da6.gif)

I almost always want to scroll the panel and not the options of a particular box and when doing that accidentally I have to cancel the changes out of fear I changed something I didn't want to change, which is really annoying.

I think this feature should be removed entirely or at least there should be an option to disable it because I find it very user-unfriendly.

**Comment by octaeder** [comment]
Please be kind and add some information about your OS and txs version.
Meanwhile you may want to read the 6<sup>th</sup> section beginning with 'I want to note one drawback of oversized combo (and spin) boxes' in  #2747. Tip: position mouse cursor far right, possibly over scrollbars.
Did you shrink width of the window? Normally there should be a scrollbar for the _Meta Commands_ section you are scrolling, and no scrollbar at the bottom of the config page. Also some options have a strange alignment:

![grafik](https://user-images.githubusercontent.com/102688820/221365413-1930e279-f481-4443-ae24-504f4e16036f.png)
Win10, dev 4.5.2

**Comment by ShaiAvr** [comment]
@octaeder OS Info:
Edition	Windows 11 Pro
Version	22H2
Installed on	‎24/‎12/‎22
OS build	22621.1265
Experience	Windows Feature Experience Pack 1000.22638.1000.0

TXS Version: TeXstudio 4.5.1 (git 4.5.1)
Using Qt Version 6.4.2, compiled with Qt 6.4.2 R

The window was indeed shrunk a bit, but it's the size it always opens when clicking `Options->Configure TeXstudio...` (or pressing `Ctrl+,`). After resizing the window a bit the scrollbars behaved as you mentions. However, the alignment of some options remains. Not sure what's the cause:

![texstudio_JBL4nPv6qF](https://user-images.githubusercontent.com/35605235/221369603-346b3d7e-e3fe-4d84-90e7-c737b98b1ee5.png)

I suppose your tip helps, but this is what's counterintuitive in my opinion. I don't what to think about where to place the mouse to avoid changing settings accidentally. Moreover, I don't see many situations in which I'd want to scroll the options of a drop box like this. I'd rather click the drop box to open the options explicitly.

**Comment by octaeder** [comment]
Moved options seems to be a problem of the Adwaita Dark style. Doesn' appear with other styles like Orion Dark.
Are these your settings (page General)?
![grafik](https://user-images.githubusercontent.com/102688820/221372346-fb7beb16-73c4-4557-9060-73218462a9e7.png)

Sorry, I can't help more (both scrolling and misalignment of options). We need an expert.

**Comment by ShaiAvr** [comment]
@octaeder yes. These are my settings.

**Comment by goyalyashpal** [comment]
hi, coming here from https://texstudio-org.github.io/CHANGELOG.html#texstudio-4-5-2

was this behaviour removed entirely or was the behaviour changed to not cycle through just on hover? like say, trigger the cycling through setting options only after clicking on them?

**Comment by sunderme** [comment]
on hover when not focused is disabled.
