### ISSUE TITLE
It crashes after mac hibernation and sometimes needs to switch the interface to restore the input function.

### ISSUE THREAD

**Issue by geek12138** [texstudio-org/texstudio#2984]
### Environment
- TeXstudio: 4.5.1
- Qt: 
- OS:macOS Ventura 13.2.1，macbook pro 16 M1 max
- TeX distribution: mactex

### Expected behavior
1. After the computer is closed or sleeps, tex will crash and flash back.
2. Sometimes you will suddenly be unable to enter any characters until you restart texstudio or switch the interface.
3. Sometimes when other tex documents are opened, the various colors of texstudio will change greatly.

**Comment by BrauerSuzuki** [comment]
I have the same problem with TeXstudio 4.6.3, but on arch linux using Qt 6.6.0.

**Comment by sunderme** [comment]
maybe fixed by qt: https://bugreports.qt.io/browse/QTBUG-127085
