### ISSUE TITLE
Macro Editor allows multiple lines for env macros

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2989]
### Environment
- TeXstudio: 4.5.1

### Expected behavior
As far as I understand an env macro consists solely of one line with the env name.
- in any case this should be clarified in the manual
- if I'm right then the editor should prevent the user from doing anything else as much as possible

### Actual behavior
It seems as one could also add text that prefills the environment like
\begin{info}
   A can tell you that this won't be a good idea.
\end{info}

### How to reproduce
Use the Macro Editor and select env type

**Comment by sunderme** [comment]
there is no need to baby proof txs.
In all the years, no one has complained about that.

**Comment by octaeder** [comment]
it would suffice to spend some words in the manual to clarify this.
