### ISSUE TITLE
Where are the special characters?

### ISSUE THREAD

**Issue by deVampyris** [texstudio-org/texstudio#299]
After updating to 2.12.10, I miss some panels on the left hand side of the window. I enjoyed the vast selection of special characters (cf. https://upload.wikimedia.org/wikipedia/commons/5/53/TeXstudio_2.12.6.png).

Is this a problem of my installation (Win10)? Is there a new solution (I could not find one)? I found them very useful.

**Comment by thatlittleboy** [comment]
It's in the left panel (see the red boxes):

![texstudio_2018-08-22_16-33-17](https://user-images.githubusercontent.com/30731072/44489324-33ef7080-a629-11e8-8e44-9aef9fdb6b6a.png)
