### ISSUE TITLE
Label describing type of text should depend on the type selected in Macro Editor

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#2990]
### Environment
- TeXstudio: 4.5.1

### Expected behavior
![grafik](https://user-images.githubusercontent.com/102688820/222963314-728cb4ca-4eda-4c76-a917-b1950182a39a.png)

When changing the macro type then the text should change to _Env. Name_, or _Script Text_ respectively.

### Actual behavior
The label is static

### How to reproduce
Change type for the macro

**Comment by sunderme** [comment]
just `Content` then ?

**Comment by octaeder** [comment]
I think no one will complain when the label is removed and the area for the editor increases. I made two builds for comparison, my preferred one with the group box comes first, the one without second. If you agree, I can create a PR. Click on image for full size.

![grafik](https://user-images.githubusercontent.com/102688820/222991756-c68dac65-fa9c-42b3-b08c-47cc16e7cc47.png)

![grafik](https://user-images.githubusercontent.com/102688820/222991627-82f116fa-9465-427e-9e3e-f46ceaa4802d.png)

and for comparison the current state follows:

![grafik](https://user-images.githubusercontent.com/102688820/222992301-a22f2e46-86b0-4d53-af9d-a4768bfb43d1.png)

**Comment by sunderme** [comment]
minute cosmetics

**Comment by octaeder** [comment]
c.f. #2999
