### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [texstudio-org/texstudio#2997]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [PDFVideoWidget](https://github.com/texstudio-org/texstudio/blob/c5e8daae9a539dbe88014d4dbce8737f2d3ceda5/src/pdfviewer/PDFDocument.cpp#L590 "Destructor for PDFVideoWidget")
- [TerminalWidget](https://github.com/texstudio-org/texstudio/blob/254cfc69201d6462dc6b7a71d60b6c31ef8ccf6b/src/toolwidgets.cpp#L198 "Destructor for TerminalWidget")

**Comment by sunderme** [comment]
yes, not necessary but does not lead to bad behaviour either.
If you want to provide a PR, go ahead.
