### ISSUE TITLE
Using TeXstudio as a library

### ISSUE THREAD

**Issue by steadysupply** [texstudio-org/texstudio#30]
Hello,

A purely speculative question; I'm interested in using some of the functionality of TeXstudio in a no-GUI application, would it be possible to use the code in this repo as a library in another C++ application?

If so, how feasible would it be to incorporate the TeXstudio build process in (for example) a CMake project so I can call TeXstudio functions from my own code?

Regards,

Ben

**Comment by sunderme** [comment]
txs is not set-up to be used as library and in all likelihood this is not (easily) doable

**Comment by steadysupply** [comment]
Great, thanks for the reply @sunderme. If anyone finds themselves here via a search engine, these more "restrictricted responsibility" projects https://vog.github.io/texcaller/ and https://github.com/mgieseki/dvisvgm might be of interest :)
