### ISSUE TITLE
Long environment causes incorrect syntax highlighting

### ISSUE THREAD

**Issue by i3v** [texstudio-org/texstudio#300]
### Environment
- TeXstudio: 2.12.10 (git 2.12.10)
- Qt: Qt Version 5.8.0, compiled with Qt 5.8.0 R
- OS: Windows 10
- TeX distribution: TexLive 2018

### Expected behavior
Syntax highlighting should work correctly regardless of the number of lines between `begin{scope}` and `end{scope}`.

### Actual behavior
It looks like the syntax checker forgets about "opening" statements after a fixed number of lines, and thus highlights innocent statements as incorrect in some cases.

### How to reproduce
Here's an MWE:

```
\documentclass{article}
\RequirePackage{graphicx}
\usepackage{tikz}                         


\newcommand{\somePlot}[1]{
	\begin{tikzpicture}
	\node (image) [anchor=south west,inner sep=0] { #1 };
	\begin{scope}[x={(image.south east)},y={(image.north west)}]
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%  The number of commented out lines here is important.
% 
%  x
%  xx
%  xxx
%
%
%
%
		\draw [blue, line width=0.2em] (1em,1.2em) -- (5em,1.2em) {};
	\end{scope}
	\end{tikzpicture}%
}

\begin{document}
	\begin{figure}
		\somePlot{\includegraphics[width=0.2\linewidth]{example-image-a}}%		
	\end{figure}
\end{document}
```
It works OK for me, but TeXstudio highlights 3 statements:
![image](https://user-images.githubusercontent.com/920364/44484781-6021e600-a657-11e8-8128-224486693bb8.png)

If I remove a single line (e.g. line 30), and do "Idefix->Refresh Structure" after that (to force a refresh), the highlighting changes (now only 2 statements are highlighted):
![image](https://user-images.githubusercontent.com/920364/44484979-e3433c00-a657-11e8-9cd2-087222842029.png).

If I repeat that, there would be only 1 statement highlighted:
![image](https://user-images.githubusercontent.com/920364/44485076-2b625e80-a658-11e8-9106-d37dd283ed77.png)

Finally, after removing one more line, there would be no lines highlighted:
![image](https://user-images.githubusercontent.com/920364/44485122-58af0c80-a658-11e8-9c61-7b1080906eee.png)

**Comment by i3v** [comment]
I must admit that the original MWE is misleading a bit. The issue is not related to `tikz`  (but it seem to be related to `\newcommand` somehow).

Here's an even simpler MWE, without tikz:

```latex
\documentclass{article}             


\newcommand{\somePlot}[0]{
	\begin{enumerate}
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%  The number of commented out lines here is important.
%
% 
%  delete one commented-out line, and the issue would be gone
%
%
%
%
%
	\end{enumerate}
}

\begin{document}
	\somePlot{}%		
\end{document}
```
The erroneous highlighting is still there:
![image](https://user-images.githubusercontent.com/920364/44497816-097ed100-a684-11e8-8e0c-022eb9922847.png)

**Comment by sunderme** [comment]
txs uses a runaway-limit that stops any open argument after 30 lines. This is intentional since it would change syntax update through the whole document if you write a new command with an opening brace only at the start of the document.

Apart from the examples, did you run into real problems with the length-limit ?

**Comment by i3v** [comment]
@sunderme ,

Yep, my real-life case was related to the real `tikzpicture` inside `\newcommand`. Much like the code from the original message but with real commands instead of commented-out lines. I was quite puzzled with all that highlighting at first. 

I'm not sure if this could be treated as a "very common" case, but that's probably not a unique case.

**Comment by sunderme** [comment]
with the latest commits, you can change the limit in .config/texstudio.ini: editor/RUNAWAYLIMIT

**Comment by i3v** [comment]
Great, thanks!
