### ISSUE TITLE
Suggestions of improvements for translatable strings

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#3002]
The following translatable strings:

- >The equation environment centers one equation on the page and places the equation number in the margin.

  isn't quite right. Indeed:

  - the equation is centered only if the `fleqn` option — normally selected through the `\documentclass` command — has not been used,
  - more important, the number isn't in the margin but at the end of the line (or at its beginning if the `leqno` option — normally selected through the `\documentclass` command — has been used).

- > Fraction - \dfrac{}{}”

  could be precised:
  > Big Fraction - \dfrac{}{}”

  in order to make it different from the previous line in the menu:
  > Fraction - \frac{}{}”

- >The cases environment provides a strucure that displays as a brace left to an array of lines with two left-aligned columns.

  could be precised:
  >The cases environment provides a structure that is displayed as a left brace extending vertically across the height of an array of lines left-aligned with two left-aligned columns.

**Comment by sunderme** [comment]
The tooltip in txs is not the place for extreme precision.
Ideally it gives just a **very short** hint that the user recognizes a command and what it does.
It is not a perfect definition, it is not a tutorial and it is not a help text.
So, summary, in my opinion, the tooltips are already too long.

**Comment by dbitouze** [comment]
Okay. here is what I suggest for the above tooltips texts:

- The equation environment typesets a numbered equation on its own line.
- The case environment is used e.g. in equations where different cases are distinguished.

**Comment by sunderme** [comment]
These two sound reasonable.
I noticed that some more tooltips may need some improvement:
* `\dfrac is an amsmath package shorthand for \displaystyle\frac...` , so whatever \displaystyle does
* `The alignat* environment is an unnumbered alignat environment.` , refers to other command

**Comment by octaeder** [comment]
??
\dfrac sets it's parameters in displaystyle, this is needed for recursively using \frac. Otherwise those use \textstyle
env alignat* ***is** a version of env alignat without a number, fits perfectly

**Comment by octaeder** [comment]
in this way "definition" of alignat* refers to the "definition" of alignat, the latter comes first in the list. So no need to repeat an extended "definition"

**Comment by sunderme** [comment]
that assumes that the user is scrolling down, one-by-one.
Maybe he already knows, he wants an unnumbered equation (starred version) but which one ?
Especially with the very similar names, some explanation is helpful.

**Comment by sunderme** [comment]
but you see the point ?

**Comment by octaeder** [comment]
there are already several constraints for the solution. Maybe you can prepare one and hopefully we are all fine with it

**Comment by octaeder** [comment]
one note: Some of the info give usage hints. I assume that you want to remove them. But then the code inserted should be enhanced accordingly. Example: cases env: The text inserted is nothing more than
```
\begin{cases}

\end{cases}
```
But the info gives the hint that it should be entered as an array with two columns. So menu entry should expand to something like this (_ could be a placeholder):
```
\begin{cases}
 _ & _ \\
 _ & _ 
\end{cases}
```
u see the point?

**Comment by octaeder** [comment]
I made a build of a new version. The following list presents the new info texts and the code (including placeholders) inserted. I tried to give code that is minimal and still necessary. This is to avoid that to much needs to be deleted afterwards.

I still think that the star-ed versions should not repeat the text of the unstar-ed versions just to add that it has no number. But I still have no good solution. One could be to let follow the star-ed version directly after the unstar-ed version as it had been for equation and equation* some time ago (but not for all other envs, s. [here](https://github.com/texstudio-org/texstudio/blob/4f2c0885d260bf252b4fec51c8061ea6b70f7cec/uiconfig.xml), l. 243ff) and keep the info texts of the star-ed versions as is.

Please make comments and suggestions.

Center an equation
![image](https://user-images.githubusercontent.com/102688820/224817576-9863496d-c3fd-4cb8-9aa6-bc2ea334ac3c.png)

Align equations within columns
![image](https://user-images.githubusercontent.com/102688820/224817778-8bbc03d8-bb03-4e25-926e-4ff6034bf7b1.png)

Align equations within columns with custom column separation
![image](https://user-images.githubusercontent.com/102688820/224818010-2fe9414a-8557-4454-871b-80941635806b.png)

Align equations within columns having maximum separation
![image](https://user-images.githubusercontent.com/102688820/224818303-8fc48498-aa34-4245-9009-4698a738ad97.png)

Center several equations
![image](https://user-images.githubusercontent.com/102688820/224818518-cde44b6c-431e-4dc9-b61c-937121350f4f.png)

Spread an equation over multiple lines
![image](https://user-images.githubusercontent.com/102688820/224818882-cb6141f7-1ec9-4b86-aa87-de358f469b65.png)

Add cases to an equation
![image](https://user-images.githubusercontent.com/102688820/224819258-1b09107c-84c6-4f11-befc-aaf7cfb8ed7d.png)

Spread and align an equation over multiple lines within another environment
![image](https://user-images.githubusercontent.com/102688820/224819421-19bb0772-efe2-4bcc-ade2-4b02cd019a77.png)

**Comment by dbitouze** [comment]
It would be very useful! Some suggestions (coming from the `amsmath` documentation):

* Center an equation → Single equation on a single line
* Align equations within columns → Grouped equations with vertical alignment and automatic horizontal space between equations
* Align equations within columns with custom column separation → Grouped equations with vertical alignment and horizontal space between equations to be explicitly specified
* Align equations within columns having maximum separation → Grouped equations with vertical alignment within columns having maximum separation
* Center several equations → Grouped equations without vertical alignment
* Spread an equation over multiple lines → Single equation split into multiple lines without vertical alignment
* Add cases to an equation → Distinction of cases (within another math environment)
* Spread and align an equation over multiple lines within another environment → Single equation split into multiple lines with vertical alignment (within another math environment)

**Comment by sunderme** [comment]
I would rather prefer shorter (though not so precise) tooltips.
(the most condensed information would be images anyway which the amsmath documentation also uses to compare the different variants)

**Comment by octaeder** [comment]
@sunderme Maybe it's better to cut down things and go into some details later on.
1. Which of the codes produced by the actions are not ok, if any?
2. I've shrunk the tooltips noticeably. Which are still too long?
If possible make notes exactly related to one case so I know where to work on.

**Comment by sunderme** [comment]
I meant to say that I prefer your shorter text. 
Some of Denis' suggestion seem a bit more elegant and maybe worth to incorporate in parts, like 
"Single equation split into multiple..." , so maybe "Equation split into multiple lines"

**Comment by octaeder** [comment]
In general I change the point of view as used by sunderme. Instead of telling what to do I tell what we get: "Align equations in columns" vs. "Equations aligned in columns". Bullet points indicate new descriptions.

Equation:
>     * Center an equation → Single equation on a single line
* Equation centered in a row

Align:
>     * Align equations within columns → Grouped equations with vertical alignment and automatic horizontal space between equations
Equation group means all lines, so I use equations for this.
* Equations aligned within columns

Alignat:
>     * Align equations within columns with custom column separation → Grouped equations with vertical alignment and horizontal space between equations to be explicitly specified
* Equations aligned within columns with custom column spacing

Flalign:
>     * Align equations within columns having maximum separation → Grouped equations with vertical alignment within columns having maximum separation
* Equations aligned within columns having column spacing to fill full line

Gather:
>     * Center several equations → Grouped equations without vertical alignment
* Equations centered in rows

Multline:
>     * Spread an equation over multiple lines → Single equation split into multiple lines without vertical alignment
Centering lines is a kind of vertical alignment
* Equation split into multiple lines

Cases:
>     * Add cases to an equation → Distinction of cases (within another math environment)
adding to an equation implies there is an outer env
* Distinction of cases (within other math environment)

Split:
>     * Spread and align an equation over multiple lines within another environment → Single equation split into multiple lines with vertical alignment (within another math environment)
* Equation split into multiple aligned lines (within other math environment)

### Live examples
#### Tooltip overview
Real length of info depends on translation. In English we have now:

![grafik](https://user-images.githubusercontent.com/102688820/225780925-1a7d6d95-2abd-48b4-addc-380dfa94c445.png)

#### Reordering of items
Info of stared versions refer to unstared versions. So pairing items of unstared and stared version might be a solution. Following images show comparisons for the menu and the toolbar:

![grafik](https://user-images.githubusercontent.com/102688820/225784082-40d7c5d2-d4e8-4e53-bb5a-a994668be8d6.png)

![grafik](https://user-images.githubusercontent.com/102688820/225784111-54c585ff-9596-4f4d-aca0-5695ef6a40a4.png)

**Comment by sunderme** [comment]
looks good

**Comment by dbitouze** [comment]
> Equation:
> 
> > ```
> > * Center an equation → Single equation on a single line
> > ```
> 
>     * Equation centered in a row

“centered” is improper in case of you make use of `fleqn`. And my wording, more precise (“Equation” may be not immediately understood as “Single equation”), isn't much more lengthy.

> Align:
> 
> > ```
> > * Align equations within columns → Grouped equations with vertical alignment and automatic horizontal space between equations
> > ```
> 
> Equation group means all lines, so I use equations for this.
> 
>     * Equations aligned within columns

“Equations“ is, at a first glance, not clearly different from “Equation“. What about “Multiple equations aligned within columns”

> Alignat:
> 
> > ```
> > * Align equations within columns with custom column separation → Grouped equations with vertical alignment and horizontal space between equations to be explicitly specified
> > ```
> 
>     * Equations aligned within columns with custom column spacing

Same remark as above (“Multiple equations”). Plus “custom” could be puzzling: custom by who?

> Flalign:
> 
> > ```
> > * Align equations within columns having maximum separation → Grouped equations with vertical alignment within columns having maximum separation
> > ```
> 
>     * Equations aligned within columns having column spacing to fill full line

Same remark as above (“Multiple equations”). 

> Gather:
> 
> > ```
> > * Center several equations → Grouped equations without vertical alignment
> > ```
> 
>     * Equations centered in rows

Same remarks as above (“Single equation” plus improper “centered“). 

> Multline:
> 
> > ```
> > * Spread an equation over multiple lines → Single equation split into multiple lines without vertical alignment
> > ```
> 
> Centering lines is a kind of vertical alignment

Centering lines? 

>     * Equation split into multiple lines

Same remark as above (“Single equation”). 

> Cases:
> 
> > ```
> > * Add cases to an equation → Distinction of cases (within another math environment)
> > ```
> 
> adding to an equation implies there is an outer env

“Add cases to an equation” may suggest that that works only in an `equation` env.

>     * Distinction of cases (within other math environment)

Okay.

> Split:
> 
> > ```
> > * Spread and align an equation over multiple lines within another environment → Single equation split into multiple lines with vertical alignment (within another math environment)
> > ```
> 
>     * Equation split into multiple aligned lines (within other math environment)

Same remark as above (“Single equation”). Otherwise, okay.

> ### Live examples
> #### Tooltip overview
> 
> Real length of info depends on translation. In English we have now:

Didn't you consider to add images to the tooltips (don't know if it is possible but would be nice: in French, we say “A good drawing is better than a long speech”).

> #### Reordering of items
> 
> Info of stared versions refer to unstared versions. So pairing items of unstared and stared version might be a solution. Following images show comparisons for the menu and the toolbar:

This order needs for the user to read more items when (s)he's looking for a given env.

**Comment by sunderme** [comment]
* I agree that the difference between equation and equations is visually a bit subtle.
* for equation, the case with fleqn is not really relevant. No latex user should really struggle to know what equation does. Completeness is not the goal here.
* The same is true for some similar remarks (e.g. " “Add cases to an equation” may suggest that that works only in an equation env.". If the user is struggling at that level, he **needs** to consult some more documentation. Expecting to learn latex with all subtleties from tooltips is a bit optimistic). Main purpose is to help to select the right environment when the user has a basic understanding what he is doing.
* I am not really for or against reordering the entries, both orders have its merits.

**Comment by sunderme** [comment]
The "single/multiple" is probably helpful as it allows a quick distinction.

**Comment by octaeder** [comment]
some notes:
txs uses all the time env and cases, split do so too. It should be not difficult to figure out that equation does not mean the environment.
gather: AMS says at the beginning of chapter 3.5 "centered", even so it's not true with option fleqn
multline: dito
split: in fact this is a simple version of align with one column and no number. Thus you can use
```
\begin{equation}
  \begin{split}
    a & = b \\
    c & = d
  \end{split}
\end{equation}
```
We see, not everything is explained exactly as is.
Never seen tooltips with images. you could add icons to the menu. Hard work, should be done also for dark mode, different icon themes, ...

**Comment by octaeder** [comment]
I hope following solution (for the numbered envs) is acceptable to you so we can come to an end:

env equation "Single equation centered in a row"
env align "Multiple equations aligned within columns"
env alignat "Multiple equations aligned within columns with customizable column spacing"
env flalign "Multiple equations aligned within columns having column spacing to fill full line"
env gather "Multiple equations centered in rows"
env multline "Single equation split into multiple lines"
env cases "Distinction of cases (within other math env)"
env split "Single equation split into multiple aligned lines (within other math env)"

What about the envs without numbers (which I would keep together at the end of the list)?

env equation* "The equation* environment is an unnumbered equation environment."
env align* "The align* environment is an unnumbered align environment."
env alignat* "The alignat* environment is an unnumbered alignat environment."
env flalign* "The flalign* environment is an unnumbered flalign environment."
env gather* "The gather* environment is an unnumbered gather environment."
env multline* "The multline* environment is an unnumbered multline environment."

I think the user will quickly see how the menu items are organized and will look into the tooltips of the upper half of them.

**Comment by octaeder** [comment]
As you can see from my last code example I prefer indenting the code relativ to the env. My screenshots of the inserted codes didn't show this:

![image](https://user-images.githubusercontent.com/102688820/224817576-9863496d-c3fd-4cb8-9aa6-bc2ea334ac3c.png)

Question: _Is it ok that I change this?_ For example like this:

![grafik](https://user-images.githubusercontent.com/102688820/226061747-f2181789-4b67-4643-b803-bafa3dbbdacf.png)

**Comment by sunderme** [comment]
the indentation is okay.
The texts are okay as well.

**Comment by octaeder** [comment]
first I wanted to use 4 blanks, then I thought tabs could be better. But neither a real tab nor \t works as expected (\t is output as is and tab key as one blank, if my test was correct). I couldn't figure out if tabs are possible at all. What would you suggest?

**Comment by sunderme** [comment]
probably auto-indent is influencing this.
Have you tried with indent: keep indentation ?

**Comment by octaeder** [comment]
The option is set to keep indentation.
The problem seems to be the XML. A search on google found following from TU Berlin: A single whitespace character is formed in XML 1.0 by a space, tab (horizontal) character, carriage return, or newline character. So I will use four blanks.

**Comment by JellyWX** [comment]
I realise this issue has been and gone but I only just got hit by it. I'm not a fan of the change to `\begin{align*}` personally. I use these primarily for my maths formatting, but usually don't actually need the column format.

**Comment by octaeder** [comment]
do i understand correctly , that you don't need the ralign placeholders in the following template (same for align*)?

![grafik](https://user-images.githubusercontent.com/102688820/226061747-f2181789-4b67-4643-b803-bafa3dbbdacf.png)

**Comment by JellyWX** [comment]
Yes

**Comment by octaeder** [comment]
This template addresses a more general case. I think there are four ways to work with this:
- While jumping from placeholder to placeholder and entering code, press always Del once when arriving at a ralign placeholder do delete it
- Proceed in the same manner as before but delete ralign with multiple cursors afterwards
- use completer to insert align environment (type a then press Ctrl+Alt+Space (completer list appears) and then press Enter
- Write a macro to insert your environment as needed
