### ISSUE TITLE
Comment support in .bib files

### ISSUE THREAD

**Issue by yjhn** [texstudio-org/texstudio#3004]
### Describe the feature and the current behavior/state

Currently, comments are not supported in bibliography (.bib) files:  
- lines cannot bet commented out using standard <kbd>CTRL</kbd>+<kbd>T</kbd>
- comments are the same colour as regular text:
![image](https://user-images.githubusercontent.com/54238857/223792844-ebd7a162-f51d-45c9-80e0-08c8a8aed561.png)

Biber supports comments in .bib files and complains if there is non-commented-out text outside bibliography entries (BibTeX does not, it just ignores any text not in bibliography entries).

### Who will benefit with this feature?

People using biber and arguably also BibTeX (commenting things out makes the intent clearer in any case).

**Comment by sunderme** [comment]
apparently `%` is only valid for bibber but not for bibtex.

**Comment by yjhn** [comment]
Yes, I have clumsily explained it in the description. But BibTeX does not break if comments are included, so I see no harm in adding this.
