### ISSUE TITLE
Can't push my .tex file

### ISSUE THREAD

**Issue by djcaesar9114** [texstudio-org/texstudio#3005]
### Environment
- TeXstudio: .TeXstudio 4.5.1 (0.0.0++)
- Qt: ???
- OS: Ubuntu 22.04
- TeX distribution: Texlive

### Expected behavior

I expect to have a checkbox asking me if I want to push the code when I commit.

### Actual behavior

There is no checkbox.

### How to reproduce

When I click on "File" "SVN/Git" then the first choice (in French it's "Propager (SVN)"), A dialog appears asking me to set a comment, what I do. In the log I see that the .tex fils has been committed, but I don't know how to push.

I tried this: https://github.com/texstudio-org/texstudio/wiki/Scripts#git-commit-and-push
But it resulted in this error:

```
Exception manquée à la ligne 2 : TypeError: Cannot call method 'setWindowTitle' of undefined
```

When I read the documentation (https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html > paragraph 5.6), this part doesn't seem maintained as there are two "doc17" occurrences...

So, I don't understand if git pushing is a feature or a script/macro I have to add. I just want to push the code TexStudio has correctly committed.

**Comment by sunderme** [comment]
you are aware that the manual is under https://texstudio-org.github.io/getting_started.html ?

**Comment by sunderme** [comment]
there is no push support in txs (yet)

**Comment by sunderme** [comment]
(but a simple user script could do that as well)

**Comment by djcaesar9114** [comment]
> you are aware that the manual is under https://texstudio-org.github.io/getting_started.html ?

Well, I saw two different documentations, the other one seemed more detailed so I thought it was more accurate. My bad!

**Comment by djcaesar9114** [comment]
> (but a simple user script could do that as well)

actually now I'm writing "git push" in my terminal, but I must admit having the possibility to do it natively in the menu (or with a system of checkbox) would be a great feature.

**Comment by sunderme** [comment]
push added as check box.

**Comment by octaeder** [comment]
s. https://github.com/texstudio-org/texstudio/commit/a2a1d665773e714ada550902e05b7aaea2bf4eee

**Comment by djcaesar9114** [comment]
Thanks a lot! Any idea when it will be available? I saw the 4.5.1 didn't have this feature.

**Comment by mbertucci47** [comment]
@djcaesar9114 [4.5.2beta1](https://github.com/texstudio-org/texstudio/releases/tag/4.5.2beta1) is public now

**Comment by djcaesar9114** [comment]
Well, it works like a charm. Thank you for this feature that will save me a lot of time in my writing process.
