### ISSUE TITLE
internal PDF viewer flickers

### ISSUE THREAD

**Issue by dkz-phys** [texstudio-org/texstudio#3009]
### Environment
- TeXstudio:  4.5.1
- Qt: 6.4.2 
- OS: MacOS 12.6.3 
- TeX distribution: texlive

### Expected behavior
Smooth scrolling across pages in the internal PDF viewer

### Actual behavior
When two pages are in the scope the whole viewer flickers. The two pages flicker alternately. I experienced this for a few months across several versions around 3.x.x, and it was fixed shortly afterwards a year or two ago. It resurfaced since  version 4.3.X or 4.4.X released last year.

**Comment by sunderme** [comment]
can't reproduce

so demonstrate with a screencast. 
If it was fixed because of an issue report, you can search that report as well as I ...

**Comment by dkz-phys** [comment]
Should've mentioned the problem only occurs when zoomed in and that the page is wider than the viewer window.

**Comment by sunderme** [comment]
screencast ...

**Comment by dkz-phys** [comment]
Here is a short clip demonstrating this:

https://user-images.githubusercontent.com/69955356/224878556-c3178352-4068-4eec-9850-bf5be6aa2427.mov

**Comment by sunderme** [comment]
you have reduced config/internal pdf viewer/Cache Size , haven't you ? (default 512MB)

**Comment by sunderme** [comment]
anyway, what are your settings for config/internal pdf viewer ?

**Comment by dkz-phys** [comment]
Increase the cache size solved the issue. Thanks for pointing this out!

**Comment by sunderme** [comment]
so, what was the cache size ?
