### ISSUE TITLE
Code Folding shouldn't include empty lines at the end

### ISSUE THREAD

**Issue by GniLudio** [texstudio-org/texstudio#3011]
### Problem
Currently it is not possible to separate folded regions. (for example with empty lines)

### Solution
A folded regions shouldn't include empty lines at the end.

**Comment by sunderme** [comment]
I assume that you are talking about folding sections.

**Comment by sunderme** [comment]
anyway, the folding code only works with single lines and it needs a target where to start and where to end.
It can't end in an empty which is followed by another line which contains abc.
So, no changes are planned.
