### ISSUE TITLE
"Smart" Home key

### ISSUE THREAD

**Issue by sven-frotscher** [texstudio-org/texstudio#3012]
### Describe the feature and the current behavior/state
Currently, pressing the `Home` key puts the cursor the beginning of the line, before any indentation characters. To edit the actual beginning of the line (after the indentation), you have to move the cursor manually or using `Ctrl`+`Right Arrow`.

I'd like presses of the `Home` key to alternate placing the cursor at the end of the indentation and the beginning of the line (= before the indentation). This would save time (fewer cursor movements), while still allowing you to increase or decrease the amount of indentation with `Tab` or `Shift`+`Tab`, respectively.

If you deem this feature intrusive, you may place it behind a configuration option (e.g. in the Editor category).

### Any Other info
Quite a few editors/IDEs have the feature I am requesting here. [Geany](geany.org), for example, has the following setting, which is enabled by default:
> #### "Smart" home key
> When "smart" home is enabled, the HOME key will move the caret to the first non-blank character of the line, unless it is already there, it moves to the very beginning of the line. When this feature is disabled, the HOME key always moves the caret to the start of the current line, regardless of its current position.

IDEs from Jetbrain (e.g. Pycharm) have the following setting:
> #### Home moves caret to first non-whitespace character
> When this checkbox is selected, on pressing `Home`, the caret is positioned at the first non-whitespace character of the current line. Pressing `Home` subsequently moves the caret from the **Smart Home position** to the first column and back.

**Comment by octaeder** [comment]
Expected:
> Pressing Home subsequently moves the caret from the Smart Home position to the first column and back.

@sunderme Implementation seems not fully functional: Cursor jumps left in two steps to the beginning of the line, but then not back to the first non blank character.

**Comment by octaeder** [comment]
now fully functional

**Comment by sven-frotscher** [comment]
Thank you for implementing this, works like a charm in the AppImage.
When do you plan on releasing version 4.5.2? :)

**Comment by jzniu** [comment]
The bug that I reported in [#3098](https://github.com/texstudio-org/texstudio/issues/3098), which is now closed with a quick fix, seems to be related to this feature. I hope that quick fix doesn't break the implementation of this feature.

Is this smart Home feature available in v4.5.2? I cannot find it in configuration.

**Comment by octaeder** [comment]
This is the case as can be seen from the changelog (s. about dialog in 4.5.2):

- pos1 (home) key now sets cursor to start or to first non-blank character of editor lines ([#3012](https://github.com/texstudio-org/texstudio/issues/3012))

This feature is not configurable in a sense that there is a checkbox. You have to reconfigure the behavior of the Home key to default in the shortcut settings (Editor/Basic Key Mapping) in the config:

![image](https://user-images.githubusercontent.com/102688820/236055227-97716fe3-cd5f-4223-9d84-12cc36fec38e.png)

**Comment by octaeder** [comment]
@jzniu 
> I hope that quick fix doesn't break the implementation of this feature.

Home now works as expected.

**Comment by jzniu** [comment]
Great!

**Comment by Yery** [comment]
I have just updated to the new version, and notice that the "home" behavior has changed. For long sentences that span many lines, the "home" button used to move to the beginning of the current line, now it moves to the beginning of the sentence/text block. Is this intended  (it does seem in contradiction with what is "move cursor to first character in line"), and is there a way to make home just jump to the beginning of the line?

**Comment by octaeder** [comment]
the configuration is described 3 comments above yours.
in such a case
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/8b3f2cf4-820a-4a98-a553-822da5a514cf)
with home the cursor first jumps to first non blank character of the line where the cursor is (red cirlce), then to the first non blank character of the line with the line number, from then on between here and the first position of the line with line number.

**Comment by Yery** [comment]
Oh I am sorry - I missed this. thanks a lot, this indeed solves my problem!
