### ISSUE TITLE
"Generate environment after typing trigger code" trigger mistake

### ISSUE THREAD

**Issue by vsanchez** [texstudio-org/texstudio#3021]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior
!mabc\s is supposed to activate the script with "abc" as the parameter. 

### Actual behavior

It does not work, due to a mistake in the shown trigger: it should be !m(\S+)\s   
The given one is missing the "+" sign, hence \S only matches a single character.

**Comment by sunderme** [comment]
I would appreciate a complete context what we are talking about.
Is this a question about a specific macro ?

**Comment by sunderme** [comment]
okay fixed.
It would have been helpful to mention that you are talking about a macro example in the wiki.
