### ISSUE TITLE
add icons and separators from submenu to toolbar combobox drop-down list

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3025]
### Describe the feature and the current behavior/state
As an example add the Commands menu from main menu Tools to the Custom Toolbar in the Config dialog (page Toolbars). Then compare the to menus:

![grafik](https://user-images.githubusercontent.com/102688820/226180742-b8821888-6384-473e-9ae1-94265d7a0df0.png)

All icons and separators are missing.

### Who will benefit with this feature?
All who use such a configuration.

### Any Other info
Work in progress

**Comment by dbitouze** [comment]
I would have added such a separator in the Math → Equation sub menu as well, between numbered and unnumbered environments.

**Comment by octaeder** [comment]
just to be clear, I didn't add any separator. I just made sure that the menu added to the combobox looks the same as the source from that it is a copy.

Work on the math menu is still in progress. I'll implement this then.
