### ISSUE TITLE
cursor in Macro Editor blinks but Editor has no focus

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3027]
### Environment
- TeXstudio: 4.5.1, current build
- OS: Windows10
- TeX distribution: miktex

### Expected behavior
The cursor mark should only blink when the editor accepts changes

### Actual behavior
When I open the Macro Edit dialog with at least one macro the cursor blinks but I can't edit:
![MacroCursorBlinking](https://user-images.githubusercontent.com/102688820/226189655-65c22834-6b0b-4384-8bc1-fea39635b9ee.gif)

### How to reproduce
s. above
Note: I couldn't find out where this comes from

**Comment by sunderme** [comment]
fixed
