### ISSUE TITLE
Change menu accelerators for the main menu (German)

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3033]
Currently there are (ordered) these:
``A, A, B, B, D, H, I, M, O, R, T``
So A and B have duplicates. While repeating alt+b switches between Bearbeiten und Bibliographie, this seams not to be possible for Assistenten and Anzeige with alt+a (well repeating one more time helps, but not nice).

Hope you have a good idea. Thanks.

**Comment by sunderme** [comment]
fixed
