### ISSUE TITLE
continue work on Math menu

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3036]
@dbitouze @sunderme , there are still things to discuss.

| Item | Info |
|--------|---|
| Inline math mode ``$``...``$`` | The math environment can be used in both paragraph and LR mode |
| less technical tooltip needed | _Write math in the line of text (math mode), same as ``\(``...``\)`` or env math_ |
| LaTeX inline math mode `` \(`` ...`` \)`` | The LaTeX math environment can be used in both paragraph and LR mode_ |
| less technical tooltip needed | _Write math in the line of text (math mode), same as ``$``...``$``_ |
| Display math mode ``\[``...``\]`` | The displaymath environment can be used only in paragraph mode |
| less technical tooltip needed | _Set math apart from text (display math mode), same as env displaymath_ |
| Fraction - ``\frac{}{}`` | inserts ``\frac{%&lt;num%\|%:translatable%>}{%&lt;den%:translatable%>}`` |
|  | In general: do we need translations for placeholders?|
| Fraction - ``\dfrac{}{}`` (1) | \dfrac is an amsmath package shorthand for \displaystyle\frac... |
| suggestion | _\dfrac (amsmath) always uses display math mode style for the fraction_ (2) |
| \begin{array} | \begin{array}{col1col2...coln}%ncolumn 1 entry &amp; column 2 entry _............_ |
| be consistent: _env array_ | do not repeat code: _tabular for math_ |

Footnotes:

(1) @dbitouze suggested in #3002 following change to the menu entry:
>    Fraction - \dfrac{}{}” could be precised: Big Fraction - \dfrac{}{}”

I'm not sure what people expect when reading Big Fraction.
What do you think?

(2) Let me mention that the third entry of the Math menu is "Display math mode ``\[``...``\]``" (s. table above). So the info should make some sense to the user.

**Comment by dbitouze** [comment]
Thanks for the suggestions!

- (For $...$) less technical tooltip needed 	_Write math in the line of text (math mode), same as `\(`...`\)` or env math_: nice, except I don't see the point of “env math”.
- (For `\[`...`\]`) less technical tooltip needed _Set math apart from text (display math mode), same as env displaymath_: maybe “Set math” → “Set single unnumbered equation” and “same as env displaymath” → “same as env equation*” (I guess `displaymath` is mostly unknown).
- “In general: do we need translations for placeholders?”: French people often need them! :wink: 
- “suggestion 	_\dfrac (amsmath) always uses display math mode style for the fraction_ (2)”: nice.
- “be consistent: _env array_ 	do not repeat code: _tabular for math_”: more consistent but less explicit IMO.

> (1) @dbitouze suggested in #3002 following change to the menu entry:
> 
> > Fraction - \dfrac{}{}” could be precised: Big Fraction - \dfrac{}{}”
> 
> I'm not sure what people expect when reading Big Fraction. What do you think?

I suggested this as a clear distinction from the previous “Fraction”. I must admit that I haven't any better idea.

> (2) Let me mention that the third entry of the Math menu is "Display math mode `\[`...`\]`" (s. table above). So the info should make some sense to the user.

See my suggestion above.

BTW, “LaTeX” in the second entry “LaTeX inline math mode” doesn't  help: that's just technical. Why not a single entry “Inline math mode” in place of the current first two that inserts `$...$` or `\(...\)` depending on an option that let the user “definitively“ choose between `$...$` or `\(...\)` for inline math mode?

**Comment by octaeder** [comment]
For a short version go to end .-)

> nice, except I don't see the point of “env math”.

Since I'm neither a TeX nor a LaTeX expert I'm a little bit reserved. I looked in the Latex2e manual linked in txs. It says that there are three equivalents for math mode (but this proposition might be restricted to LaTeX): `$`...`$`, `\(`...`\)`, and `\begin{math}`...`\end{math}`. You can find env math already in the current menu if you look closely:

| Item| Info |
| - | - |
|  Inline math mode `$`...`$`  |  The __math environment__ can be used in both paragraph and LR mode   |
| LaTeX inline math mode  `\(` ... `\)` / | The LaTeX __math environment__ can be used in both paragraph and LR mode |

What about dropping word LaTeX on the left? And changing Inline to Text? Reason see my words about math mode and display math mode below.
In the second case I would like to simply referring to `$`...`$` (s. table below).

From this knowledge I would agree that one of the items is superfluous. But maybe not in TeX? txs somehow biases the user towards `$`...`$` by having a shortcut for it. The manual says in chapter 16 that "`\(` ... `\)` is preferred" (but I don't know why). I wouldn't change/remove items here because this might have greater impact to the user. An option doesn't help here, and maybe not everyone would like to be restricted to one of the both. Overall it's likely that the user doesn't use the menu at all for this after a very short time.

A LaTeX beginner will read about env equation, env displaymath, and that the latter is equivalent to `\[`...`\]`.  Be aware that equation* is amsmath. In all three cases you can use split, aligned, and so on, so the result may be more than one equation in one line. So I would change my suggestion to simply be _Set math apart from text (display math mode)_.

I want the user to understand that some envs use math mode, while others use display math mode. I need this with regard to dfrac, which uses "display math mode style"\footnote{I correct this to "display style", see the following}. Here the reader should conclude that math in display math mode is set in display style (which can be used on parts of the math), however not easy. As said above, I would like to use _"text" math mode_ for env math and the like. Then it's clear that we have text style and display style (compare to tfrac and dfrac), and this can be related easily to env displaymath, too.

While looking into the menu I would now suggest:

| Item | Info |
|--------|---|
| Inline math - `$`...`$` | _In the text line set math in text style_ |
| Inline math - `\(` ...`\)` | _Same as `$`...`$` and env math_ |
| Display math - `\[`...`\]` | _Set math apart from text in display style_ |
| Fraction - `\dfrac{}{}` | _\dfrac (amsmath) always uses display style for the fraction_ |
| \begin{array}...\end{array} | _Tabular for math (use inside other env)_ |

I made a quick build for comparison. Left current, right new menu items:

![grafik](https://user-images.githubusercontent.com/102688820/226496367-c21344b9-6ae8-4789-80e5-85df6c580549.png)
(click to enlarge)

I suggest adding following tooltips (currently none given):
| Item | Info |
|--------|---|
| \left | size for opening parentheses |
| \right | size for closing parentheses |

**Comment by dbitouze** [comment]
> For a short version go to end .-)

:wink: 
 
> > nice, except I don't see the point of “env math”.
> 
> Since I'm neither a TeX nor a LaTeX expert I'm a little bit reserved. I looked in the Latex2e manual linked in txs. It says that there are three equivalents for math mode (but this proposition might be restricted to LaTeX): `$`...`$`, `\(`...`\)`, and `\begin{math}`...`\end{math}`. You can find env math already in the current menu if you look closely:
>
>| Item | Info |
>|--------|--------|
>| Inline math mode `$`...`$` | The **math environment** can be used in both paragraph and LR mode |
>| LaTeX inline math mode `\(` ... `\)` | The LaTeX **math environment** can be used in both paragraph and LR mode |

You're right but I guess `math` env is only rarely used.

Moreover, in the tips, despite “The”, the user in too much of a hurry may confuse “math environment” and “`math` environment” : is the former **any of the** “math environment**s**” or is it **the** “`math` environment”?

> What about dropping word LaTeX on the left? And changing Inline to Text? Reason see my words about math mode and display math mode below. In the second case I would like to simply referring to `$`...`$` (s. table below).

Okay.

> From this knowledge I would agree that one of the items is superfluous. But maybe not in TeX? txs somehow biases the user towards `$`...`$` by having a shortcut for it. The manual says in chapter 16 that "`\(` ... `\)` is preferred" (but I don't know why).

IIRC, the argument is that is easier to parse for a parser (unlike `$...$`, opening is distinct from closing). But IMO less easy to parse for a human.

> I wouldn't change/remove items here because this might have greater impact to the user. An option doesn't help here, and maybe not everyone would like to be restricted to one of the both. Overall it's likely that the user doesn't use the menu at all for this after a very short time.

Not convinced but okay :smile: 

> A LaTeX beginner will read about env equation, env displaymath, and that the latter is equivalent to `\[`...`\]`. Be aware that equation* is amsmath.

Good point.

> In all three cases you can use split, aligned, and so on, so the result may be more than one equation in one line.

Indeed, but it will be considered as a single equation: typically, inside an `equation` env, it will give a single number.

> So I would change my suggestion to simply be _Set math apart from text (display math mode)_.

Okay.

> I want the user to understand that some envs use math mode, while others use display math mode. I need this with regard to dfrac, which uses "display math mode style"\footnote{I correct this to "display style", see the following}. Here the reader should conclude that math in display math mode is set in display style (which can be used on parts of the math), however not easy. As said above, I would like to use _"text" math mode_ for env math and the like. Then it's clear that we have text style and display style (compare to tfrac and dfrac), and this can be related easily to env displaymath, too.

Okay.

> While looking into the menu I would now suggest:
>
> Inline math - `$`...`$` 	_In the text line set math in text style_

Okay but I would have use the following wording: “Math (in text style) within a paragraph of text”

> Inline math - `\(` ...`\)` 	_Same as `$`...`$` and env math_

Okay but I would have use the following wording: “Same as `$`...`$` and the math env”
 
> Display math - `\[`...`\]` 	_Set math apart from text in display style_

Okay but I would have use the following wording: “Math (in display style) apart from paragraph of text”

> Fraction - `\dfrac{}{}` 	_\dfrac (amsmath) always uses display style for the fraction_

Okay, except that the user has to read the tip in order to guess the difference with `\frac{}{}`

> \begin{array}...\end{array} 	_Tabular for math (use inside other env)_

Okay but I would have use the following wording: “Tabular for math (used inside one of the other math envs)”

(BTW, why not use the whole “environment” word?)

> I made a quick build for comparison. Left current, right new menu items:
> 
> ![grafik](https://user-images.githubusercontent.com/102688820/226496367-c21344b9-6ae8-4789-80e5-85df6c580549.png) (click to enlarge)

Thanks.
 
> I suggest adding following tooltips (currently none given):
> Item 	Info
> \left 	size for opening parentheses
> \right 	size for closing parentheses

I would use the singular form and “delimiter” instead of “parenthesis”.

**Comment by octaeder** [comment]
* [x] “Math (in text style) within a paragraph of text” (indeed, env makes __menu__ items smaller, no need for in tooltips)
* [x] “Same as $...$ and the math environment”
* [x] “Math (in display style) apart from paragraph of text”
* [x] "Size for opening delimiter"
* [x] "Size for closing delimiter"
* [x] “Tabular for math (used inside one of the other math environments)”

Currently no good ideas for item text of \dfrac.

Hope you noticed that the menu width decreased even so the array item now is `\begin{array}...\end{array}`, and that all items up do the root have the same format (text - cmd). Think that's quite nice.

So the final solution for my PR is ✨

![grafik](https://user-images.githubusercontent.com/102688820/226642638-7db80d55-5267-4686-8de6-2986a5a429cd.png)
(click to enlarge)
green dots mark changed item texts
blue dots mark new tooltips

Be aware that tooltips are not shown for main menu items (s. status bar), but they are if you add the menu to a combobox in the toolbars.

Thanks @dbitouze

**Comment by dbitouze** [comment]
> * [x]  “Math (in text style) within a paragraph of text” (indeed, env makes **menu** items smaller, no need for in tooltips)
> * [x]  “Same as ... and the math environment”
> * [x]  “Math (in display style) apart from paragraph of text”
> * [x]  "Size for opening delimiter"
> * [x]  "Size for closing delimiter"
> * [x]  “Tabular for math (used inside one of the other math environments)”

Okay, nice.

> Currently no good ideas for item text of \dfrac.

Neither do I :frowning_face: 

> Hope you noticed that the menu width decreased even so the array item now is `\begin{array}...\end{array}`, and that all items up do the root have the same format (text - cmd). Think that's quite nice.

Indeed! I didn't notice: thanks for pointing out.

> So the final solution for my PR is sparkles
> 
> [...]

Looks good!
 
> Be aware that tooltips are not shown for main menu items (s. status bar),

Sorry: I wrote tooltips but meant status bar messages.

> but they are if you add the menu to a combobox in the toolbars.

I don't see what you mean.

> Thanks @dbitouze

You're welcome: thanks to you!

**Comment by octaeder** [comment]
![ToolbarMath](https://user-images.githubusercontent.com/102688820/226682315-bba83f52-764e-4d22-871a-74a7151cc2c6.gif)
