### ISSUE TITLE
`_` and `^` marked invalid in "text"-type arguments

### ISSUE THREAD

**Issue by mbertucci47** [texstudio-org/texstudio#3040]
### Environment
- TeXstudio: 4.5.1
- Qt: 6.4.2

### Expected behavior
The `_` and `^` characters should be recognized in math mode.

### Actual behavior
If they are inside a "text"-type argument, and further inside curly braces that are not part of the argument of a recognized command, then they are not recognized as in math-mode.

<img width="377" alt="Screenshot 2023-03-23 111923" src="https://user-images.githubusercontent.com/61854785/227286399-467fa893-26a9-41e9-b1d7-fc69d6f13c5d.png">

This issue does not affect other math-only commands, as you can see with `\alpha`. Also, the `_` and `^` are highlighted the correct color, just marked as invalid.

### How to reproduce
```latex
\documentclass{article}

\begin{document}

some text $X_{f_i}$ and $X_{f^i}$ and $X_{\alpha}$

\textit{some text $X_{f_i}$ and $X_{f^i}$ and $X_{\alpha}$}

\textit{some text ${a_i}$ and $\mathit{a_i}$}

\end{document}
```

**Comment by octaeder** [comment]
@sunderme I assume that this issue could be unpinned.
