### ISSUE TITLE
Scrollwheel stops working after resume from disk

### ISSUE THREAD

**Issue by MaPePeR** [texstudio-org/texstudio#3041]
If I leave TexStudio open and set my system to hibernate, the scroll wheel does not work anymore after resuming from disk.

I can still scroll by dragging the scroll bars, but the scrollwheel does not work in any of the panes.
It does not fix itself by closing and reopening files or panes.

Have to restart TexStudio to get scrollwheel behavior back.

### Environment
- TeXstudio 4.5.1 (git 0.0.0++)
- Using Qt Version 6.4.2, compiled with Qt 6.4.2 R
- OS: Linux (ArchLinux)
- TeX distribution: texlive, though that probably does not matter

### Expected behavior

Scroll wheel to work after resuming from disk.

### Actual behavior

Scroll wheel does not work inside TexStudio anymore, but everywhere else.

### How to reproduce

* Launch TexStudio
* Hibernate with `systemctl hibernate`
* Boot with `resume=` set (using rEFInd) 
* Try to scroll in TexStudio

**Comment by sunderme** [comment]
This sounds rather like a qt6 issue.
Have you checked that other qt6 programs don't show that behavior ?

**Comment by sunderme** [comment]
and what is the desktop environment ?

**Comment by sunderme** [comment]
I will not spend effort here.
I seems to work fine with sleep on ubuntu and windows.
So, it is a specific problem with arch and the special window manager. (txs uses qt for anything scrollwheel related anyway)
