### ISSUE TITLE
spellchecker active always active in final arg with certain delimiters

### ISSUE THREAD

**Issue by mbertucci47** [texstudio-org/texstudio#3044]
### Environment
- TeXstudio: git 4.5.2
- Qt: 6.4.3

The syntax checker does not seem to like the last arg of commands if they're delimited by `[`,`]`,`<`, or `>`. From https://github.com/texstudio-org/texstudio/issues/2012#issue-1077071417 we know keyval completion doesn't work, but the spellchecker is also active when it shouldn't be. For example with `mypkg.cwl`
```
# mypkg.cwl
\foo{arg1}[arg2]
\footwo{arg1}<arg2>
\foothree{arg1}(arg2)
```
we get

<img width="199" alt="Screenshot" src="https://user-images.githubusercontent.com/61854785/228380307-c0a429a4-bafe-4fc4-8a12-f9d1237ba95b.png">

If the last arg is delimited by curly braces or parentheses it's fine, but if it is square or angle brackets then the spellchecker is active even though it is not a `%text` arg. The problem occurs for any number of trailing args of this form, e.g. for a command with cwl spec `\command{arg1}[arg2][arg3]`, both `arg2` and `arg3` would have the spellchecker active. Similarly for `\command{arg1}[arg2]<arg3>`, `\command{arg1}<arg2>[arg3]`, etc.

### Source
```latex
\documentclass{article}
\usepackage{mypkg}

\begin{document}

\foo{mspldtext}[mspldtext]

\footwo{mspldtext}<mspldtext>

\foothree{mspldtext}(mspldtext)

\end{document}
```

**Comment by sunderme** [comment]
txs does not apply pattern matching for arguments.
It simply counts argument types and assumes that mandatory argument is always the last, i.e. `
\footwo<mspldtext>{mspldtext}` would work.
So, where is this behavior really an issue ?

**Comment by mbertucci47** [comment]
> It simply counts argument types and assumes that mandatory argument is always the last

Is there a reason these other argument types can't be treated the same way as curly braces? Like I mentioned it already seems parentheses are treated correctly. I say this knowing nothing about the actual code.

> So, where is this behavior really an issue ?

It is obviously not a huge issue. It's just the tiniest bit unpleasant to have things that look like this:

<img width="254" alt="Screenshot 2023-03-29 193833" src="https://user-images.githubusercontent.com/61854785/228706314-2cb044e4-aac8-44dd-afd0-9e3996336a57.png">

Source (from fontspec manual):
```latex
\documentclass{article}
\usepackage{fontspec}

\setmainfont{Optima.ttc}[
	Path = /System/Library/Fonts/ ,
	UprightFeatures = {FontIndex=0} ,
	BoldFeatures = {FontIndex=1} ,
	ItalicFeatures = {FontIndex=2} ,
	BoldItalicFeatures = {FontIndex=3} ,
	]
	
\begin{document}
text
\end{document}
```

**Comment by sunderme** [comment]
the issue is that [] and <> are optional arguments which may or may not be present.
The current (simple) logic assumes that after the mandatory argument, no optional may appear. Otherwise some speculation would need to occur which makes the code complicated.
So, I take this as an enhancement request but I don't intend to change this short term.

**Comment by mbertucci47** [comment]
This seems to be fixed with the support for "positional" arguments, 4.8.3alpha1 and later.

**Comment by muzimuzhi** [comment]
(linking similar issues)

Support for "positional" arguments is added by PR #3778 in resolving issue #3732.
