### ISSUE TITLE
Incomplete display of page numbers under Orion Dark Style

### ISSUE THREAD

**Issue by earlSagrada** [texstudio-org/texstudio#3046]
### Environment
- TeXstudio:  4.5.1 (git 4.5.1)
- Qt:  Using Qt Version 6.4.2, compiled with Qt 6.4.2 R
- OS:  Microsoft Windows 11 Home Edition
- TeX distribution:  MiKTeX

### Expected behaviour
Display of full and exact page number, in the built-in PDF viewer, under Orion Dark Style.

### Actual behaviour

Only the last digit of the page number is displayed. Increasing font size can help a bit.

_Font size: 7, the page number is not visible._
![image](https://user-images.githubusercontent.com/39267845/228847916-eeb4d555-911a-4766-874b-f8e72dbc5153.png)

_Font size: 12, the first digit of page number starts to show._
![image](https://user-images.githubusercontent.com/39267845/228848052-82223ad9-20e0-49f5-ad0c-6dc0feca50b7.png)

### How to reproduce
Simply change the 'General - Appearance - Style' to 'Orion Dark'. Then view PDFs with more than 10 pages.

**Comment by sunderme** [comment]
duplicate #2816
