### ISSUE TITLE
Cursor, viewport, tab page jump around when leaving fullscreen and after compilation

### ISSUE THREAD

**Issue by foerster-rwth** [texstudio-org/texstudio#3047]
### Environment

- TeXstudio: TeXstudio 4.5.1 (git 4.5.1)
- Qt: Using Qt Version 6.4.2, compiled with Qt 6.4.2 R
- OS: Windows 10 Education
- TeX distribution: MiKTeX

### Expected behavior

(1) I have the program window maximised.

(2) I grab the top of the window and drag it down to quickly read something in the browser window below and then push the program window back to the top of the screen, reentering fullscreen (all the while keeping the mouse button pressed).

(3) Everything should be as before:

- The tab page displayed should be the same,
- The cursor should be where it was.
- The viewport should show the same part of the code as before.

Similar issue with compiling.

(4) I have the root document open in a tab page.

(5) The cursor is somewhere on the page, viewport showing that part of the code. 

(6) I compile.

(7) Everything should be as before.

### Actual behavior

(1) Sometimes the tab page has changed. This doesn't happen every time. I don't know how to reproduce it, but it happens regularly.

(2) The cursor is somewhere else, (almost) every time.

(3) The viewport is somewhere else, (almost) every time.

(4) After compilation, the cursor and viewport of the tab page of the root document is at the bottom. Every time.

### How to reproduce

See above.

This may seem like a minor issue. But it's not. When you are experimenting with parametrisations of commands and the like, for example, you need to compile again and again to see the effects. And then you need to search for the line where you were before in a long root doc. It becomes rather aggravating after a few times. Same for the window-dragging issue.

Thank you for a fab program, btw.

**Comment by sunderme** [comment]
1) one issue per report, otherwise things get messed up like here.
2) I can't reproduce any cursor jumping on compiles, so concrete test case is needed and probably a screencast.
(again one issue only per report and it needs to be reproducible here)

**Comment by sunderme** [comment]
no feedback

**Comment by foerster-rwth** [comment]
The problem seems to come with "Scrolling follows cursor" and "Cursor follows scrolling". I have both settings enabled most of the time. Plus I have a root document and separate chapter files. These settings make the cursor jump -- which is somewhat their purpose, but it should be done differently.

The synchronisation between code and PDF viewer should not affect the state of the GUI in any way when I just go in and out of fullscreen. But it does.

I have no time at the moment to find out exact testcases. I also assume that this issue requires an extended discussion about a number of usage scenarios.
