### ISSUE TITLE
Search box text and PDF page number only partially visible

### ISSUE THREAD

**Issue by foerster-rwth** [texstudio-org/texstudio#3048]
### Environment

    TeXstudio: TeXstudio 4.5.1 (git 4.5.1)
    Qt: Using Qt Version 6.4.2, compiled with Qt 6.4.2 R
    OS: Windows 10 Education
    TeX distribution: MiKTeX

### Expected behavior

The text entered in the search box should be completely visible. Page numbers of the PDF should be completely visible.

### Actual behavior

They're not. See screenshots.

![Untitled-2](https://user-images.githubusercontent.com/72136104/228926528-3c7608d0-d095-49cc-a666-2abec16069c0.png)

![Untitled-1](https://user-images.githubusercontent.com/72136104/228926570-c77f5eeb-949f-451c-a9ab-87ab090b27a0.png)

### How to reproduce

Bug is permanent. Just search for something, or have a longer PDF open.

**Comment by octaeder** [comment]
Issues regarding find and zoom should be fixed (by Qt version?):

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/5b38d9d1-17d7-4a0a-a240-fd85ee8de71c)

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/86ba1af4-d7c8-44c5-8763-513b22d3a03f)
