### ISSUE TITLE
Alt closes suggestions

### ISSUE THREAD

**Issue by AlexD97** [texstudio-org/texstudio#305]
### Environment
- TeXstudio: 2.12.10
- Qt: 5.11.1
- OS: Arch Linux
- TeX distribution: texlive

### Expected behavior
Pressing AltGr should have no impact on suggestions. 

### Actual behavior
Pressing AltGr key closes suggestions. The problem is that I write with (german) neo2 keyboard layout. Therefore it is possible to use arrow keys with AltGr+{e,s,d,f}. But unfortunately I cannot navigate to a suggestion in TeXstudio because of this behaviour.

### How to reproduce
Press AltGr when suggenstions are open.

**Comment by sunderme** [comment]
it works fine on lubuntu. So it is eitehr arch or the neo2 keyboard ...

**Comment by AlexD97** [comment]
It's the neo2 keyboard. Sorry that I didn't test it before. But texstudio is the only application that I encountered this behaviour.

**Comment by sunderme** [comment]
it apparently sends some unexpected key-code to txs and qt5 interprets it someway. 
You could try to debug txs/qt5 there, but here I can't do anything.

**Comment by sunderme** [comment]
works for me (on normal keyboard)
