### ISSUE TITLE
preview should call external programs

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3052]
I use tikz to draw functions. For this tikz calls gnuplot. I installed gnuplot, added option --shell-escape (for pdflatex and lualatex) and added the path `C:\Program Files\gnuplot\bin` to the config dialog's PATH field. While this works fine for compiles it happens that the preview doesn't generate the plot. I assume that gnuplot could not be found because PATH isn't used.

Package pgf Warning: Plot data file `HaXxuw.curve.table' not found. on input line 11.

```
\documentclass{article}
\usepackage{tikz}
\begin{document}
\begin{tikzpicture}[domain=-1:1]
\draw (-1,0) -- (1,0);
\draw[color=red] plot[id=curve] function{(1-(x**2)**(1./3))**(3./2)};
\end{tikzpicture}
\end{document}
```

**Comment by sunderme** [comment]
the issue is probably rather that preview latex does not use `--shell-escape`.

**Comment by octaeder** [comment]
so it isn't the command defined in the config that is used for preview?

![image](https://user-images.githubusercontent.com/102688820/229287676-9975188d-65f4-4a01-aca9-87e384c29f36.png)

**Comment by sunderme** [comment]
only the base of it, not the arguments.

**Comment by octaeder** [comment]
what's your suggestion? Any simple solution?

**Comment by octaeder** [comment]
an editable field for any option if necessary or just a checkbox for shell-escape?

**Comment by sunderme** [comment]
checkbox should suffice.

**Comment by octaeder** [comment]
I tried again, and the message pane shows the following command including --shell-escape:

![image](https://user-images.githubusercontent.com/102688820/229304205-7507e83e-0a1b-45e3-9db5-62065fd3d383.png)

the .gnuplot file is created but the .table file is missing. Doesn't this say that there is a problem with path?
Further detail: I'm running a msys2 build.

**Comment by sunderme** [comment]
okay, the preview works on linux.
Is gnuplot set in the path variable ?

**Comment by octaeder** [comment]
I forgot that gnuplot is installed on Win10 with the option to add the directory to PATH. But this doesn't affect the msys2 environment. After updating $PATH in msys2 it works and there is no need to add it to the config field PATH.
Thanks,
