### ISSUE TITLE
TOC won't refresh unless sections are edited

### ISSUE THREAD

**Issue by prakashvs613** [texstudio-org/texstudio#3057]
### Environment
- TeXstudio: 4.5.1
- Qt: 6.4.2 R 
- OS: Windows 10 Enterprise 
- TeX distribution: miktex 

### Description
It is expected for TOC in the left pane to show all headings (section, subsection, subsubsection) on the fly. Sometimes, it gets stuck and only shows what is edited. Close and open TexStudio to resume the expected behavior.

**Comment by octaeder** [comment]
any hints on how to reproduce?

**Comment by sunderme** [comment]
no feedback

**Comment by prakashvs613** [comment]
> any hints on how to reproduce?

If I detach pdf from right pane to make it independent and change the tex file, build it again, the TOC links from left pane vanish.

**Comment by prakashvs613** [comment]
![image](https://user-images.githubusercontent.com/12219020/232867625-d31f6925-ce47-442c-a51b-565fd34ce486.png)

Sorry for the confusing term, I meant windowed Viewer highlighted in the image above. 

So, the TOC links from the left pane vanish after the windowed viewer is activated and the tex file is recompiled.

**Comment by sunderme** [comment]
please provide a screencast.
Please check that it happens with a bare minimum tex file.

not reproducible on linux nor windows.

**Comment by prakashvs613** [comment]
I tried reproducing on a bare minimum file, but the TOC worked fine. May have something to do with the file itself (although my original file contains text, equations, and algorithms). 

Anyway, thanks! Guess we can close this.
