### ISSUE TITLE
release note difficulte to read

### ISSUE THREAD

**Issue by dallouche** [texstudio-org/texstudio#3059]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior
no \n  after each new  feature in the about windows 

### Actual behavior

![image](https://user-images.githubusercontent.com/13035682/230026508-df5d76d0-e991-4920-a729-f894bbf9ae22.png)

### How to reproduce
click on the  about or a propose texstudio

**Comment by octaeder** [comment]
please let us know something about your OS and the txs version (s. about dialog) you are running. My test doesn't show this issue:

Win10
TeXstudio 4.5.2 (**git 4.5.2beta4**)
Using Qt Version 6.4.2, compiled with Qt 6.4.2 D

![image](https://user-images.githubusercontent.com/102688820/230040636-91c58b47-9f41-4f51-bacc-38b8f9a62adb.png)

**Comment by sunderme** [comment]
not reproducible
