### ISSUE TITLE
Add the option to change panels fonts

### ISSUE THREAD

**Issue by ShaiAvr** [texstudio-org/texstudio#3068]
### Describe the feature and the current behavior/state
I am using TeXstudio to do my homework in our native language Hebrew. I can change the editor's font through "Options - Configure TeXstudio... - Editor - Font Family" to a font that supports both languages, which is critical for me obviously. However, I was looking through the settings and couldn't find a way to change the font of the bottom panel which means I can't read Hebrew text there:

![Screenshot 2023-04-15 161500](https://user-images.githubusercontent.com/35605235/232226250-d89dea43-b5c7-4ca2-8299-166a12e2449d.png)

It's not a deal breaker, but it's annoying that I can't read Hebrew messages in the bottom panel, especially file paths. I wish you could add the option to change the font for the bottom panel so I can select a font that displays Hebrew text correctly.

### Who will benefit from this feature?
Anyone who uses TeXstudio with non-English characters and also people who simply want a better-looking font for the bottom panel.

**Comment by sunderme** [comment]
As far as I see it, the font in the message pane is the same as the font for options/appearance/font .
Looks rather like the batch output is an unexpected encoding ?

**Comment by sunderme** [comment]
This needs user testing.
I would suggest a batch that echo hebrew characters.
If that leads to similar behavior, we have (hopefully) a test case to reproduce here.

**Comment by idamir** [comment]
1. Your OS has no appropriate fonts with required glyphs.
2. This is highly likely the same as #2771 and #2681, because in Linux it works fine:
![image](https://user-images.githubusercontent.com/4737692/233408594-cec8164f-8783-40f3-a1b6-4872c4f189c8.png)

**Comment by sunderme** [comment]
I rather think that the output encoding is different from what txs expects.
Because structure view and log panel should use the same font, but only in the log panel shows unknown characters appear.

**Comment by sunderme** [comment]
linux is nowadays utf8 everywhere, so that makes things easier.

**Comment by sunderme** [comment]
no user feedback
