### ISSUE TITLE
Will not render \Delta in a .png

### ISSUE THREAD

**Issue by zhulcher** [texstudio-org/texstudio#307]
### Environment
- TeXstudio:  2.12.10
- Qt: 
- OS:  Mac 10.13.6
- TeX distribution:  pdflatex

### Expected behavior
.png of a graph with a \Delta\eta and a \Delta\phi for the axis labels

### Actual behavior
.png rendered as \eta and \phi in the viewer, however the .pdf produced is fine.

**Comment by sunderme** [comment]
please provide a test case

**Comment by sunderme** [comment]
insufficient information
