### ISSUE TITLE
git: nothing added to commit but untracked files present

### ISSUE THREAD

**Issue by Zerotask** [texstudio-org/texstudio#3072]
### Environment
- TeXstudio: 4.5.2
- Qt: 6.5.0
- OS: Windows 10
- TeX distribution: texlive

### Expected behavior
I have a git repository (connected to GitHub) in my parent folder.
I try to use the auto-check-in feature where it should automatically commit (and push?) when I save the document.
I expect that after I saved a file to see a new commit in GitHub.

### Actual behavior
![image](https://user-images.githubusercontent.com/20150243/232451677-0588f032-7d53-4218-a36d-239ee0de088e.png)

Do I have to manually open a terminal and add those files? I'd assume that it would add them automatically via git add or git commit -a

**Comment by Zerotask** [comment]
Update: it seems that texstudio created a new local repository inside my latex folder.
What makes my curious is that before the creation, the revisions actually showed commit messages from the parent folder. Therefore I assumed that this works, but I guess there is an option missing to define / select an existing git repository

**Comment by sunderme** [comment]
txs does not push on save, only when file/git/checkin is executed (with the option activated)

**Comment by sunderme** [comment]
txs tries to find the .git directory, by default (options ...) is looks through 2 directory levels.

**Comment by Zerotask** [comment]
I just re-tried it. I deleted the newly created git repository inside my latex folder.

My settings are:
![image](https://user-images.githubusercontent.com/20150243/232567375-cf42e846-0779-4ec9-be14-85fa50de311b.png)

I made a change and saved the file and it committed the change successfully in the parent git repo, but it does not push it.
Shouldn't it push the commit with "Check-in after File/Save only"? I did a save only.
What's the definition of a check-in? is it a git add, commit and push? For a better user experience, can this be clarified, since this is not a git wording.

There are 3 use cases:
1) you want every change to be synchronized with your remote repository (add, commit and push): I thought my option would do that
2) you want every change to be committed, but you want to push it manually: how does this work?
3) you want to commit and push manually (File - SVN/Git - Check in)

Additionally it would be great to have a quick access (buttons, keyboard shortcuts) to git operations like commit and push.

**Comment by sunderme** [comment]
as stated above, txs does not push with save.
Only if you explicitely check in
<img width="645" alt="grafik" src="https://user-images.githubusercontent.com/14033169/232574425-bc588d2d-de66-4841-ae21-d7cd3ecfdf82.png">

for the rest, user menus/toolbar are your friends.

**Comment by Zerotask** [comment]
I just tried a manual check in:
![image](https://user-images.githubusercontent.com/20150243/232581473-3ed30bf8-77d0-4058-8eab-d8051c228d04.png)

this worked, but it created (again) a new local repository inside my latex folder. This is a bug and seems to happen only if I check "Push to repository ?".

**Comment by sunderme** [comment]
works fine.
You have understood `txs tries to find the .git directory, by default (options ...) it looks through 2 directory levels.`

**Comment by Zerotask** [comment]
No, it does not work fine. Please test it.

My structure looks like:
```
.git
latex/main.tex
```

With txs I open main.tex, do changes, save it and it commits those changes in the correct repository.

![image](https://user-images.githubusercontent.com/20150243/232584787-08108f0d-c924-4428-aeb1-261d03105824.png)


now I do another change and do a **manual check in**.
It commits the changes but in a newly created git repo.
My structure now looks like:
```
.git
latex/.git
latex/main.tex
```

I can make a video if you don't believe me.

And what about my feature request from above?

**Comment by sunderme** [comment]
please don't mix feature request with bug reports.
Manual push is one line in "user tools", so no.
And txs will not auto push, so script with timer ?

**Comment by sunderme** [comment]
concerning the actual issue.
it works fine here on win11. The question now is why it does not on your side, so:
1) complete GIT settings in txs
2) step by step (screen cast) how txs fails, with a before/after what git sees in the folders.

**Comment by sunderme** [comment]
no feedback on actual bug report.
auto-checkin for git was extended that it can add files on save.
