### ISSUE TITLE
Auto save

### ISSUE THREAD

**Issue by Zerotask** [texstudio-org/texstudio#3074]
### Describe the feature and the current behavior/state
An auto save function, which many of us are using in programs like [visual studio code](https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save), would help concentrating on the text itself since you don't have to press a shortcut / think about it.
I can also help if your computer crashes.

Combined with an auto build & view, the workflow would be more smoothly. You could define a delay (ex. 1 second) and after it, the file will be saved and a build & view will be executed.

### Who will benefit with this feature?
Everyone who opt-in.

**Comment by sunderme** [comment]
<img width="904" alt="grafik" src="https://user-images.githubusercontent.com/14033169/232578480-7a6985e2-b997-4a2d-b67f-c4ff439ee6cd.png">

**Comment by Zerotask** [comment]
Thank you for pointing that out.

Additionally to auto save I also mentioned an auto build & view. Kinda like a watch mode (don't want to create multiple similar issues).
In vscode the delay for auto save is by default 1 s (1000 ms) and I can use tools which rebuild stuff on file changes.
That's a behaviour I'd like to see in txs, too.

**Comment by samcarter** [comment]
@Zerotask You could have a look at latexmk with the `-pvc ` option. This would automatically compile your document when the source changes.
