### ISSUE TITLE
References are not auto-completed in TeXStudio when using a template in the same  directory

### ISSUE THREAD

**Issue by neoglez** [texstudio-org/texstudio#3078]
Assume a tex document and a personalized template in the same directory as the document. The template contains a defined command to print the bibliography. Everything works fine, except that texstudio does not auto-complete the references. Also adding bib paths does not help.

### Environment
- TeXstudio: 4.5.2
- Qt: 5.12.8
- OS: Kubuntu 20.04
- TeX distribution: texlive 2022

### Expected behavior

TexStudio should display a list with the references defined in a bib file.

### Actual behavior

TexStudio does NOT display a list with the references defined in a bib file.

### MWE ###

There are three files: 1) the tex document `master.tex` 2) the personalized template `MyTemplate.cls` and 3) the reference file `references.bib`.

All files must be in the same directory.

**The tex document master.tex** 

```
\documentclass{MyTemplate}
\title{References are not auto-completed in TeXStudio when using template in same 
directory as master.}
\author{Author}
		
\begin{document}
	\maketitle
	
	\section{Introduction}
	Unfortunately, references are not auto-completed :(
	\cite{myref}.
	
	\backmatter
	
\end{document}
```

**The personalized template MyTemplate.cls**

```
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{MyTemplate}[2023/04/23 v1.0 MyTemplate Class]
\LoadClass{book}

\renewcommand{\backmatter}{
	\clearpage
	\bibliography{references}
	\bibliographystyle{plain}
}

```

**The references file references.bib**

```
@article {myref,
	author = {Some Author},
	title = {Some Title},
	year = {2023},
	publisher = {Some Publisher}
}

```

**Comment by sunderme** [comment]
txs does not read custom classes.
Put the bibliography definition into an included file.

**Comment by neoglez** [comment]
Thanks for the answer. As I already mentioned, it does not work even when adding the path manually.

![grafik](https://user-images.githubusercontent.com/3646037/232848008-3ceea342-6610-441f-b99d-3807a25e79b0.png)

**Comment by sunderme** [comment]
As the title state, it is given search paths (folders) where txs will look for the .bib files which are described in the latex source (by setting `\bibliography{references}`).
txs does not load any bib files from any folder until the file is mentioned in the source.

**Comment by sunderme** [comment]
maybe for completeness sake, `\bibliography{references}` needs to be in source as a complete command.
txs does not interpret the content of defined commands,i.e. `\newcommand{\something}{this is ignored completely}`

**Comment by neoglez** [comment]
@sunderme Can you point me out to the code in the repo where the autocompleting parsing takes place? I may check out the possibility of resolving this issue by adding a custom [.cwl file](https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions#what-are-cwl-files-good-for-and-how-do-they-work). Then, the user (me ;) ) could put the `\newcommand{\something}{this will trigger autocompletion by reading the file references, if the command \bibliography{references} is here}` in the `.cwl` file and txs would trigger references autocompletion function.

**Comment by neoglez** [comment]
@sunderme Which solution do you propose?

**Comment by sunderme** [comment]
Just put the three lines in the root document like everybody else.

**Comment by neoglez** [comment]
The problem is that the bibliography is defined and formatted in the class file.

**Comment by sunderme** [comment]
txs behavior explained.
