### ISSUE TITLE
Mismatch between source language and language used by LanguageTool

### ISSUE THREAD

**Issue by mlep** [texstudio-org/texstudio#3079]
I am encountering an issue similar to #2368 

### Environment
- TeXstudio: 4.5.2
- Qt: 5.12.8
- OS: Linux Mint LMDE 5
- TeX distribution: texlive

### Expected behavior
LanguageTool conforms to the defined language.

### Actual behavior
While language is defined as fr_classique in TexStudio, LanguageTool is suggesting English words.

Even more strange: for a text in English with language defined as EN_US at the window bottom, LanguageTool is suggesting French words...

It looks like there could be a mix-up between the default language defined in TeXstudio preferences, what language is set at the bottom of the window, and the file header (such as % !TeX spellcheck = en_US)...

### How to reproduce

While trying to reproduce the behavior, currently, TXS works as expected...

**Comment by sunderme** [comment]
please come back if you have a reproducible test case
