### ISSUE TITLE
Ampersand in aligned-block highlighted as an error

### ISSUE THREAD

**Issue by psisquared2** [texstudio-org/texstudio#308]
If I type the following in TexStudio
```latex
\usepackage{amsmath}
[...]
\begin{equation}
\begin{aligned}
a & b
\end{aligned}
\end{equation}
```

the ampersand is highlighted in red with a tootip saying something along the lines of "tabular command outside a tabular environment".

### Environment
- TeXstudio: 2.12.10
- Qt: 5.8.0
- OS: Windows 10
- TeX distribution: MikTex

### Expected behavior
The ampersand should be recognized as a valid character in an `aligned` block.

### Actual behavior
See above

### How to reproduce
See above

**Comment by sunderme** [comment]
this has already been fixed. You could use a development snapshot, see homepage.
