### ISSUE TITLE
Compilation of files closed in the work session

### ISSUE THREAD

**Issue by jpmaroco** [texstudio-org/texstudio#3082]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior

Compile only files open in the TextStudio editor

### Actual behavior

Compiles files that were open before, but are not open anymore in the current work session.

### How to reproduce

Open two latex files, and then close one, and compile the other...

**Comment by sunderme** [comment]
I am pretty sure that your example is incorrect.
I would assume that the second file is a child of the first ?

**Comment by sunderme** [comment]
And any particular reason to not to fill in basic minimum information about your set-up ?

**Comment by jpmaroco** [comment]
I do not know how to fill all the request information. The problem are as follows (Win 11):
1. Takes a long time to open the .tex fil
2. Compiles ok with Lualatex, but when it tries to open the pdf, TexStudio closes....
It was working fine, before with 4.51.  I reinstalled 4.5.1 but gives the same problem. I wonder if has anything to do with Qt v6...
I can send you the log files or others you think necessary.
Thanks for your concern.

**Comment by jpmaroco** [comment]
Sorry, 
Here it is:
TeXstudio: all since v4
Qt: 6
OS: win
TeX distribution: MikTex

**Comment by sunderme** [comment]
Then we still need a concrete example where txs behaves unexpected. 
I have not seen any irregularities, but txs does not close a root document completely if a child document is still open and then the root document is compiled.
But similar things happen if root is explicitely set via options or `%TeX` comment.

**Comment by sunderme** [comment]
I am missing a user answer here on github.

>I do not know how to fill all the request information. The problem are as follows (Win 11):
>    Takes a long time to open the .tex fil
>    Compiles ok with Lualatex, but when it tries to open the pdf, TexStudio closes....
>    It was working fine, before with 4.51. I reinstalled 4.5.1 but gives the same problem. I wonder if has anything to do with Qt v6...
>    I can send you the log files or others you think necessary.
>    Thanks for your concern.

First basic test is to check against a bare minimum tex file with no other open tex files.

I gather that txs crashes when opening the pdf, so the tex sources and said pdf is needed to reproduce the issue.
Files can be sent directly to me (sunderme@gmx.de), preferably already stripped down to smaller test documents which show the issue.
Without anything concrete here, without knowing anything about the document, the set-up,etc., it is basically impossible to give any sensible support.

**Comment by jpmaroco** [comment]
Thanks! 
I will email you the files where the error happens. Really appreciate your help

**Comment by sunderme** [comment]
this is the same as #3083
