### ISSUE TITLE
TexStudio automatically closes after compilation with LuaLatex

### ISSUE THREAD

**Issue by jpmaroco** [texstudio-org/texstudio#3083]
### Environment
- TeXstudio: 4.5.2
- Qt: 6.4.2 
- OS: Windows 11.
- TeX distribution: miktex

### Actual behavior
Automatically closes after compilation with lualatex and just before opening the pdf compiled file.

### How to reproduce

Compile file with LuaLatex

**Comment by sunderme** [comment]
no, it does not (in general).
If some basic functionality is reported as wrong and there is not a flood of reports, then there are more details needed to determine what goes wrong.
Stated again, "Compile file with LuaLatex" just works fine.

**Comment by sunderme** [comment]
The minimum check should always be if a bare minimum tex file, as only file in txs, shows the same behavior.

**Comment by sunderme** [comment]
as stated on the other issue, a complete test case is need, i.e. a concrete document & pdf.

**Comment by jpmaroco** [comment]
ok. Should I annex the .tex file? (it is a heavy one with subfiles...)

**Comment by jpmaroco** [comment]
I noticed that if I deleted the .synctex and the .pdf file, and then recompile the .tex file again, it will not crash for the first time.... The second time, crashes again.

**Comment by sunderme** [comment]
I could reproduce the issue.
On win only, synctex unloading causes the crash (on this particular case).
I have updated synctex in txs, and that seems to solve the issue.
Can you please check with latest [dev build](https://github.com/texstudio-org/texstudio/actions/runs/4835224825)

**Comment by sunderme** [comment]
unfortunately this is not fixed.
The updated synctex sources contained a bug which basically disables synctex on windows (and thus avoids the crash)

**Comment by sunderme** [comment]
fixed, try latest dev build
