### ISSUE TITLE
Chapters are not displayed in the structure-tree

### ISSUE THREAD

**Issue by NTrnka** [texstudio-org/texstudio#3086]
When opening a Document with chapters, sections etc. in the structure tree on the left side, the chapters are not shown. They reappear, if the \chapter{chaptername}-command is edited.

### Environment
- TeXstudio 4.5.2 (git 4.5.2)
- Qt-Version 6.5.0, kompiliert mit Qt 6.5.0 R
- OS: Windows 10
- TeX distribution: texlive

### Expected behavior
Open a .tex-File and see all chapters with sections and so on in the structure-tree on the left side
![TexstudioBugAfter](https://user-images.githubusercontent.com/111888766/234265217-b65d1216-e442-4177-b632-52c0b78b5a89.png)

### Actual behavior
If TexStudio is opened and reopens the .tex OR if the .tex is opened via the Structure-tree OR if the .tex is opened via TexStudio, the chapters do not appear in the structure-tree. If the corresponding \chapter{chaptername}-command is edited (for example if a space is inserted and deleted anywhere in the command or the name inside the command), the entry reappears.
![TexstudioBug](https://user-images.githubusercontent.com/111888766/234265101-b3f02747-888c-4bdc-8dd6-2162087d995d.png)

### How to reproduce
- Open texstudio
- see the structure of a automatic restored .tex-file 
OR
- open a .tex-file

**Comment by idamir** [comment]
Confirm.
TXS: 4.5.2
Qt 5.15.2 and Qt 6.4.1

**Comment by idamir** [comment]
![Screenshot_20230428_104155](https://user-images.githubusercontent.com/4737692/235050497-e62aef11-0f0c-4a9b-83fc-7981b7f275e1.png)
Open 30-design.tex
![Screenshot_20230428_104233](https://user-images.githubusercontent.com/4737692/235050560-fadc1393-c9e6-4ca2-b821-a56214b05135.png)
No \chapter, but \{sub}section are present.
Move \chapter to the next line
![Screenshot_20230428_104633](https://user-images.githubusercontent.com/4737692/235050641-caf4fcf8-26ef-4b25-bb35-65821f2f0ba6.png)
All sections disappear until they are edited.

Some video.
https://user-images.githubusercontent.com/4737692/235053288-00931700-eb6a-49e7-a924-37501a427ad2.mp4

Exactly the same as described in #3091

**Comment by kinelite** [comment]
This problem #3086 has occurred to me for almost a year now.
It always occurs when .tex subfiles are loaded but the .tex main file has not been loaded.

The only solution I found is
1. Load the main file first after you open TexStudio.
2. Make sure your subfiles are included in the main file, i.e., there must be this line \subfile{yoursubfilename.tex} in the main file
3. Load the your subfiles next, and enjoy the fixed structure-tree.

However, this is just a temporary solution and it's very inconvenient. If you are working with many subfiles at once, then having all subfiles included in the main file will result it a major increase in compiling time because ALL files will have to be compiled. The only fix is you have to exclude the other subfiles you are not working with at the moment from the main file. This is very tedious because you have to do that each time you are working with different subfile.

I hope the structure-tree is fixed and recovered again without having to load the main file.

**Comment by octaeder** [comment]
Please check if you have unreferenced labels. Following example can reproduce the behavior in 4.5.1 and 4.5.2 on Win10:
```
\documentclass{article}
\begin{document}
%
%
\section{Nothing}
\label{a}
\end{document}
```
Insert this in an editor and the structure looks like this:

![image](https://user-images.githubusercontent.com/102688820/236588483-98310c59-1c2e-4296-a036-af47f5665f2a.png)

Now set cursor at the beginning of the line with the first percent sign. Press enter, then undo with Ctrl+Z, and be aware of the removed section in the structure:

![image](https://user-images.githubusercontent.com/102688820/236588322-86554836-2fa9-4e3e-bd73-600e23ba21d8.png)

It won't happen if you start with the cursor in the line of the second percent sign, or if you have only one line with a percent sign, or if you remove the label.

It took me a lot of time to find this example and I hope it helps to find the reason why this happens.

**Comment by octaeder** [comment]
it seems that it is rather a problem of deleting lines:
```
\documentclass{article}
\begin{document}
a
b
c
d
e
\section{Nothing}
\label{a}
\end{document}
```
set cursor in any of the lines a, b, ..., d and press Ctrl+K, or with cursor at the end of one of those lines and press enter, then backspace.
This doen't happen with line e.

**Comment by sunderme** [comment]
> --Edited-- it seems that it is rather a problem of deleting lines and labels (referenced or not):
> 
> ```
> \documentclass{article}
> \begin{document}
> a
> b
> c
> d
> e
> \section{Nothing}
> \label{a}
> \ref{a}
> \end{document}
> ```
> 
> set cursor in any of the lines a, b, ..., d and press Ctrl+K, or with cursor at the end of one of those lines and press enter, then backspace. This doen't happen with line e.

This is probably an example for  #3091.
Anyway fixed, though it has nothing to do with chapters not showing up.
