### ISSUE TITLE
command completion from `\usetikzlibrary` fails if arg contains linebreak

### ISSUE THREAD

**Issue by mbertucci47** [texstudio-org/texstudio#3087]
### Environment
- TeXstudio: 4.5.2
- Qt: 6.5.0
- OS: Win 10

### Expected behavior
A common way to load multiple packages or libraries is by adding linebreaks; some variation of
```latex
\usetikzlibrary{
	tikzmark,
	decorations,
	tikzlings
	}
```
This shouldn't affect texstudio's command completion, added in commit 74b4042.

### Actual behavior
Any linebreaks in the argument break the recognition of the libraries:

<img width="155" alt="Screenshot 2023-04-25 122601" src="https://user-images.githubusercontent.com/61854785/234370008-da874a85-4d41-4c82-a99d-c11b2d64ed30.png">

The same is true for the other package-specific library-loading commands recently added, `\usepgfplotslibrary`, `\tcbuselibrary`, etc. 

This is not a problem with `\usepackage`.

### How to reproduce
```latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{
	tikzmark,
	decorations,
	tikzlings
	}

\begin{document}
\tikzmark

\tikzling
\end{document}
```

**Comment by muzimuzhi** [comment]
Guess it's caused by the whitespaces before library names. For example
```tex
% reproduces the problem
\usetikzlibrary{ tikzmark}

% passes
\usetikzlibrary{%
tikzmark}
```

I did a try in https://github.com/muzimuzhi/texstudio/commit/f44ad118e52ce878d60ba8771c9d9d1f5ba99a37 and am waiting for the CI to complete.
