### ISSUE TITLE
Impossible to search after deselection of a portion of the document

### ISSUE THREAD

**Issue by djcaesar9114** [texstudio-org/texstudio#3092]
### Environment
- TeXstudio: 4.5.2 (git 0.0.0++)
- Qt: Qt version 5.15.3, compilé avec Qt 5.15.3 R
- OS:Ubuntu 22.04
- TeX distribution: texlive

### Expected behavior

I expect the string to be found in the whole text every time I enter a new string, even when I deselect a part of the text.

### Actual behavior

It doesn't find anything because it saves what I've selected before.

### How to reproduce

Activate the "limit the search to selected text" option (I don't know the name in English but it's the button with the "document" icon).
Press CTRL+F, enter a string and press "enter". It finds the occurrences of the string in the whole text.
Then select a part of the text. Press the arrow that would go to the next occurrence of the string: it says the end of the zone has been reached and nothing has been found.
Deselect the previous selection, what has been selected remains blue (a lighter blue than when it was selected), and it's still impossible to find occurrences as it for some reason saved the selection.
Press the cross to remove the search toolbar, what has been light-blue loses the color and you can search and find again the occurrences by pressing CTRL+F.

### Note

If that is the intended behavior, it's quite misleading, above all when the  "limit the search to selected text"  is activated by default. It should be a positive action from the user to activate this option, in my opinion.

**Comment by sunderme** [comment]
I would like to see a screencast or sceeenshots to illustrate what you are doing.

**Comment by djcaesar9114** [comment]
There you go.
When my mouse is out of the GIF it's that I press the "down" arrow to go to the next result.

![Peek 27-04-2023 14-51](https://user-images.githubusercontent.com/19804251/234867596-05997554-4f36-47af-a689-b29dd9c9698c.gif)

**Comment by sunderme** [comment]
the search works as advertised. 
However "limit search" is now automatically disabled if no multi-line selection is given at opening the panel.
