### ISSUE TITLE
trigger with variables

### ISSUE THREAD

**Issue by RabahHouna** [texstudio-org/texstudio#3094]
### Environment
- TeXstudio:  4.5.2
- Qt: 6.5.0
- OS:  Windows10
- TeX distribution: texlive

### Description
I want to write a macros in TeXstudio, in this way for example : 
normofuequal1 
so the result : 
||u||=1
normofyequal10.89 
so the result : 
||y||=10.89
in other words I want to be able to input variable in the trigger.
Thank you

**Comment by sunderme** [comment]
see [manual](https://texstudio-org.github.io/advanced.html#regular-expressions)
