### ISSUE TITLE
Git commit every file (including images and bibliography)

### ISSUE THREAD

**Issue by djcaesar9114** [texstudio-org/texstudio#3095]
### Describe the feature and the current behavior/state
For the moment, it seems the only file being committed when using the Git function is the ".tex" we're on.
It could be great to get all the changes, except the ones in the ".gitignore" file, of course.
This could be useful when we add images or change the bibliography (".bib" file).

### Who will benefit with this feature?
Every person using git to save their changes.

### Any Other info
If it's already the functionality I'm sorry, in that case it's me who didn't understand how to set my texstudio properly.

**Comment by sunderme** [comment]
there is no program out there which simply commits everything. Chances are quite high that garbage is commited.
So, you can handle your requirements with scripts of your own, but txs will not go that route.

**Comment by djcaesar9114** [comment]
I understand the "garbage" thing, but with a simple "git add ." In the folder of the "tex" file, it includes everything you need.

But I understand the choices between what is the purpose of Texstudio and what it the purpose of project management.

**Comment by sunderme** [comment]
Just be aware that latex compilation generates a **lot** of helper files. I would not assume that they are already covered in `.gitignore`.

**Comment by djcaesar9114** [comment]
Indeed, in my project I put a rule to prevent all those files to be committed.

**Comment by sunderme** [comment]
closed as no intention to implement that in txs.
(per scripts/tools, this can be easily done)
