### ISSUE TITLE
Pressing HOME key goes to start of paragraph directly rather than start of line first

### ISSUE THREAD

**Issue by jzniu** [texstudio-org/texstudio#3098]
### Environment
- TeXstudio: 4.5.2
- OS: Windows 10

### Expected behavior
Pressing HOME once moves the cursor to start of the line, pressing it again to start of the paragraph.

### Actual behavior
In TXS 4.5.2, pressing HOME goes directly to start of paragraph (one long line actually but soft wrapped) rather than start of line first. Pressing END has the desired behavior, end of line first and then end of paragraph.

**Comment by octaeder** [comment]
@sunderme Home now jumps always to first character of line when no soft line wrapping happens, but it works with line wrapping. Please check again.

**Comment by octaeder** [comment]
with f83a147c0 Home works as expected

**Comment by jzniu** [comment]
Great!

**Comment by kienpham89** [comment]
@jzniu did you find a solution to have pressing Home key return to first character of a line with Soft Line Wrapping at Windows Edge? I went to commit fix pos1 but not sure how to implement the fix from there.

**Comment by octaeder** [comment]
Home works as expected with current dev.
