### ISSUE TITLE
Script Macros `system` command fails silently on Mac.

### ISSUE THREAD

**Issue by jacobleft** [texstudio-org/texstudio#3103]
### Environment
- TeXstudio: 4.5.2
- Qt: 6.5.0
- OS: macOS Ventura 13.3.1 (M2)
- TeX distribution: mactex

### Expected behavior
Script Macros containing `system` commands can be run.
For example, the "Launch Zotero Picker" macro uses `system` to run `curl`.
A "Process started: ..." message should appear in the Messages tab.

### Actual behavior
`system` commands fail silently.
No message appears in the Messages tab.

### How to reproduce
I have Windows machines, and `system` commands run normally.
So this could be a Mac-only problem. Try the "Launch Zotero Picker" macro on Mac.

**Comment by sunderme** [comment]
works as expected.
what happens with a script as simple as:
```
system("echo hello");
```

**Comment by jacobleft** [comment]
A pop-up window asked me if I trust this script.
I clicked "yes, allow all calls it will ever make".
And nothing happened.
If I run the script again, the pop-up window will appear again, as if the script was never run.
