### ISSUE TITLE
"Push to repository" checkbox has no effect on macOS 13

### ISSUE THREAD

**Issue by samcarter** [texstudio-org/texstudio#3108]
### Environment
- TeXstudio: 4.5.2
- Qt: 6.5.0
- OS: macOS 13.3.1 (a)
- TeX distribution: texlive 2023
- git version 2.40.1

### Expected behavior

commits will be pushed to the repository

### Actual behavior

files are committed, but not pushed

### How to reproduce

I was very happy to see that you recently added an option to allow push on git checkin:  https://github.com/texstudio-org/texstudio/commit/a2a1d665773e714ada550902e05b7aaea2bf4eee

I now tried this option by going to `File->SVN/GIT...->Check in..` and selecting the checkbox like this

<img width="535" alt="Screenshot 2023-05-12 at 11 05 04" src="https://github.com/texstudio-org/texstudio/assets/43832342/36f00f93-6195-4472-baef-1968c1d79445">

The commit works fine, however it does not seem to push the changes. I can't see any message about "git push" in the "Messages" pane and if I check the status of my git repository, it shows that the commit was not pushed.

<img width="1130" alt="237933422-497fcb46-eb26-46c5-ba1f-f106fc1aed86" src="https://github.com/texstudio-org/texstudio/assets/43832342/95cc5218-ea7d-469f-a0d2-526246d1355c">

Am I using this option incorrectly? Or are my expectations wrong?

### Additional information

- My git setting in TeXstudio are like this:

    <img width="416" alt="Screenshot 2023-05-12 at 11 09 14" src="https://github.com/texstudio-org/texstudio/assets/43832342/0f4dcb7e-acc8-4ff1-9779-4ce7350b7bc1">

- In case it matters, the git repository from the example above is hosted at github https://github.com/samcarter/beamerthemeSam I tried other repositories as well, both public and private, and experience the same problem with all of them

- I can execute `git push` from terminal without problems. Pushing works also fine from other apps like gitkraken or sourcetree.

- I already tried to open TeXstudio from the terminal to see if there are maybe any error messages, but nothing. Is there something else I could try to debug the problem?

**Comment by sunderme** [comment]
fixed with https://github.com/texstudio-org/texstudio/commit/31565b400fbf6ab734bc3db895fbf5af228e37ee

**Comment by samcarter** [comment]
@sunderme Works great! Thanks a lot for the quick fix!

**Comment by muzimuzhi** [comment]
> fixed with [`31565b4`](https://github.com/texstudio-org/texstudio/commit/31565b400fbf6ab734bc3db895fbf5af228e37ee)

31565b400fbf6ab734bc3db895fbf5af228e37ee is just a merge commit.  I think it is a5921a88de31a959d393093bf0aff4da26d26d51 that resolved current issue.
