### ISSUE TITLE
Launch Zotero Picker script doesn't work: Request not allowed

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#3109]
### Environment
- TeXstudio: 4.5.2
- Qt: 5.15.2
- OS: GNU/Linux Mageia 8
- TeX distribution: TeX Live 2023
### Expected behavior
Launch Zotero Picker script should work.

### Actual behavior
Launch Zotero Picker script doesn't work. When running it, it fails with the following error message:

```
Process started: curl -s http://127.0.0.1:23119/better-bibtex/cayw?format=biblatex&command=autocite&texstudio=true&minimize=true

Request not allowed
```

### How to reproduce
Install Launch Zotero Picker script:

1. Macros → Edit Macros...
2. Browse → Zotero Picker
3. Check the `zoteroPicker.txsMacro` checkbox
4. OK
5. OK
6. Create a `test.tex` file containing:
```latex
\documentclass{article}
\usepackage{babel}
\usepackage{csquotes}
\usepackage{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}

\printbibliography
\end{document}
```
7. Run the Launch Zotero Picker script (trigger `aaa`).
8. Click on “Yes, allow this call” when the TeXstudio script watcher popup appears.
9. Look at the message.

**Comment by sunderme** [comment]
this looks rather like an issue with zotero.
Txs executes the curl call, but zotero does not react as expected.
Anybody wants to debug the curl call ?

**Comment by retorquere** [comment]
`Request not allowed` is what Zotero says if it thinks it is being accessed by a browser. Either tweak the user-agent, or add a `zotero-allowed-request` header with any non-empty value.

**Comment by dbitouze** [comment]
> `Request not allowed` is what Zotero says if it thinks it is being accessed by a browser. Either tweak the user-agent, or add a `zotero-allowed-request` header with any non-empty value.

@retorquere Thanks, that did the trick! But only tweaking the user-agent (I hope in a proper way), like this:
```
%SCRIPT
var url = 'http://127.0.0.1:23119/better-bibtex/cayw??format=biblatex&command=autocite&texstudio=true&minimize=true';
system('curl -s -A "TeXstudio" ' + url);
```
Adding `zotero-allowed-request` hadn't any effect without with the tweaked user-agent and did not hurt with the tweaked user-agent.
