### ISSUE TITLE
Context menu item "Go to Definition" brings error message

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3114]
### Environment
- TeXstudio: 4.5.2, current alpha build ((git 4.6.0alpha1-1-gbe257d72b))
- Qt: Qt Version 6.4.2
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
Hovering over the name of a \ref (\refname or \refpage) a large tooltip shows a filename and below a preview of the part of the definition of the label. Choosing "Go to Definition" from context menu should open the file (in fact it should show the hidden loaded file) and position to the defining text.

### Actual behavior
with 4.5.2 nothing happens at all

with git 4.6.0alpha1-1-gbe257d72b the following message appears:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/73e3ebc0-a129-421a-9a4c-4b67030477f8)

### How to reproduce
Situation is as follows:  A root document is opened. Also a file is open that is a (not necessarily direct) child (always use \input). It contains a \ref{label} of a label that is defined in a different child (probably of a node that is not a direct parent for both nodes). The child file has not been opened explicitly, but other child nodes. The new option "Cache documents" is not active. No split view is active.

**Comment by octaeder** [comment]
Note: when the file with the definition has been opened (visible Editor tab) then "Go to definition" works as expected.

**Comment by sunderme** [comment]
probably fixed

**Comment by octaeder** [comment]
Retest git 4.6.0beta1-9-gfd8243120 as of July 7

Create following three files for testing:

#### test.tex
```latex
\documentclass[10pt,a5paper]{article}
\usepackage{mathtools}
\begin{document}
%
\include{label}
\include{ref}
%
\end{document}
```

#### label.tex
```latex
\begin{equation}
    x=\sqrt{2} \implies x^2=2\label{implies}
\end{equation}
```

#### ref.tex
```latex
see \ref{implies}
```
### First test:
Open test.tex and label.tex (ref.tex is in the list of hidden files).
Hover with mouse over label name `implies`. We expect to see a tooltip with a usage count of 1. But I see 😮:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/b2f7a151-7d50-4e93-9a26-203ff2fdc6ee)

Try `Find Usages` from context menu

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/5cc15c39-b408-4374-b73f-a3c565e1433a)
but only the \label command is found 😮

### Second test:
Close the files. Open test.tex and ref.tex (label.tex is in the list of hidden files).
Hover with mouse over ref name `implies`. We expect to see a text preview of the \label context in a tooltip. But I see no tooltip 😮

Try `Go to Definition` from context menu, and yes, we jump to the definition 😀
From now on I can see in ref.tex a text preview of the \label context in a tooltip

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/2f53bd9f-55e5-4367-a277-adc8fb729a39)

even when I close label.tex

**Comment by octaeder** [comment]
Note: same with `\input`

**Comment by octaeder** [comment]
added above test results with 4.5.2 above. While master improves go to definition, all other things tested don't work but worked with 4.5.2.

**Comment by octaeder** [comment]
@sunderme You have seen that some things from 4.5.2 are missing now?

**Comment by sunderme** [comment]
that is the consequence of "cached files". I will mention it in the release notes. You can turn off caching.

**Comment by octaeder** [comment]
thanks for clarifying this.
