### ISSUE TITLE
new from template handshake SSL failed

### ISSUE THREAD

**Issue by Dtress** [texstudio-org/texstudio#3118]
### Environment
- TeXstudio: texstudio-4.5.2-x86_64.AppImage 
- Qt: Qt version 5.12.8, compilé avec Qt 5.12.8 R
- OS: Operating System: Debian GNU/Linux 12
KDE Plasma Version: 5.27.2
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.0-9-amd64 (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-2310 CPU @ 2.90GHz
Memory: 7.7 Gio of RAM
Graphics Processor: NV106
- TeX distribution: texlive 2022

### Description
When I try to create a new document from templates, the window "select Latex template", online repository, loading begins and nothing happens.
here is the standard and stderr output
qt.network.ssl: QSslSocket: cannot resolve EVP_PKEY_base_id
qt.network.ssl: QSslSocket: cannot resolve SSL_get_peer_certificate
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
Network error: "le handshake SSL a échoué"

I do not understand SSL protocol, so could you help me ?
Best regards

**Comment by sunderme** [comment]
works fine on ubuntu.

**Comment by sunderme** [comment]
looks like unreleased debian distribution ?

**Comment by sunderme** [comment]
not reproducible
