### ISSUE TITLE
Unexpected enter behaviour in \begin{} environment

### ISSUE THREAD

**Issue by idsetakken** [texstudio-org/texstudio#3121]
# Environment:
- TeXstudio: 4.5.2
- Qt: 6.5.0, compiled with Qt 6.5.0 R
- OS: Windows 10 22H2
- TeX distribution: MiKTeX

# Summary
When writing any items in \begin, the enter does not remove the placeholder and instead writes a newline. 

# How to reproduce

```
\begin<ENTER>itemize<ENTER>
```
# Expected behaviour
I would expect that it removes the placeholder instead of writing an enter in the \begin environment. 

https://github.com/texstudio-org/texstudio/assets/78415771/08c638c8-a040-4b08-9d47-dc1b957dc0f1

**Comment by sunderme** [comment]
you don't need to press enter, just move the cursor wherever you need. 
This is the case for all placeholders in txs.
By the way, faster method is entering "item" and then ctrl+shift+space (complete environment)

**Comment by idsetakken** [comment]
I understand that I can move the cursor, but I would like to remove the placeholder as it is distracting in the sense that I might have not completed an environment yet. ctrl+shift+k is an option, but that then does not allow me to go to 'content...' anymore with ctrl+->. 

Also, I might be doing something wrong but ctrl+shift+space does not seem to complete the environment for me, it simply does nothing in my client.

**Comment by idsetakken** [comment]
Furthermore, it also doesn't seem to disappear by default. I started with \begin{figure} and ignored the placeholder whilst adding the centering, includegraphics etc. and it is yet to disappear automatically. 
![Screenshot_1309](https://github.com/texstudio-org/texstudio/assets/78415771/9acb1e44-f77c-4f51-afad-14bcf9116373)

**Comment by idsetakken** [comment]
The placeholder around the top itemize remains when I follow these instructions

https://github.com/texstudio-org/texstudio/assets/78415771/d554196b-709f-4fdd-ad93-14c1e2a63eff

**Comment by idsetakken** [comment]
I originally had "Indent and Unindent Automatically", but all three settings have no influence on the itemize issue. The same also occurs when I for example do \begin{figure}, the placeholder around 'figure' remains even when my cursor moves. 

https://github.com/texstudio-org/texstudio/assets/78415771/6c025bfc-0523-40cd-92be-a521f3a9f40f

**Comment by octaeder** [comment]
I have no more ideas...

**Comment by octaeder** [comment]
We may try if txs starts with defaults. So end texstudio.exe and ensure with task manager that this process is not running. Go to %AppData%/texstudio and rename texstudio.ini to texstudio~.ini. Now try to start texstudio.exe.

If that doesn't work, end txs as described above, make a backup of the texstudio folder (containing the .ini file) somewhere else and delete the texstudio folder. Try to start txs. If this doesn't help then restore the backup folder.

**Comment by idsetakken** [comment]
The same issue still occurs. Similar as previous videos so not re-recording.

**Comment by sunderme** [comment]
let's close. The original post is intended behavior.
Issue with placeholders is not reproducible.

**Comment by GraefinZahl** [comment]
I have the same "issue" and I believe the behaviour changed in one of the recent version updates.
On my Windows 11 Laptop I still had texstudio 4.0.1 and pressing return simply removed the placeholder without a new line as I would expect.
After updating to the current version 4.6.2 I get the behaviour described in the original post. Is this really intended? Is there any option to get the old behaviour back or is there a different way of closing a placeholder? Typing the closing bracket seems to be the only way for me.

**Comment by idsetakken** [comment]
@GraefinZahl placeholders can be removed using Ctrl + Shift + K. It's unfortunately to my knowledge the only working solution for removing the placeholder (but it removes all placeholders), as I indeed remember the original behavior that was indeed in older versions.

**Comment by octaeder** [comment]
You may use 
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/988a99fb-a08d-4ed8-bd79-fc7ed3b607b4)
from the Idefix menu. For quick access you may add a shortcut in the config.
