### ISSUE TITLE
Math Equations in Toolbar

### ISSUE THREAD

**Issue by hair-splitter** [texstudio-org/texstudio#3122]
### Environment
- TeXstudio: 4.6.0 (git 4.6.0alpha1)
- Qt: Qt Version 6.5.0, compiled with Qt 6.5.0 R
- OS: Windows 10
- TeX distribution: TeX Live 2023

### Actual behavior

All settings at default value. 
Open the TXS, then

Options / Configure TeXstudio
Show Advanced Options
Toolbars
Toolbar Customization: Math
All menus / Math / Math Equations
<== "This adds an action to the toolbar"
OK

Open a new document, and choose the "env equation* (amsmath)" on the toolbar.
The result will be:
```
\begin{align*}
```

### Expected behavior

The result will be:
```
\begin{equation*}
```

**Comment by octaeder** [comment]
That's reproducible (also in 4.5.2). More observations: for all *-ed envs the first (equation*) produces the second (align*), the second the third (alignat*) and so on, but the last (multline*) gives cases (which is the first after the second separator), while cases and split don't work at all (and in fact it's the same for equation*). But tooltips pop up correctly, and everything works when using main menu.
This error is not specific to the equations menu, this shift also happens to the main/tools/commands menu (for ex. use "View PDF" and it will run Biber instead.
Likely copying the separators to the combo box menu makes this happen. But why does Qt find the correct tooltips but not the correct insertion text?

**Comment by octaeder** [comment]
putting line 162 in utilsUI.cpp in comment
``//			QAction *mAction = mMenu->addSeparator();``
seems to solve the problem, but of course at the cost of loosing the separators in the combobox menu.
