### ISSUE TITLE
Window focus

### ISSUE THREAD

**Issue by zoof** [texstudio-org/texstudio#3123]
### Environment
- TeXstudio: 4.5.2 (ubuntu 23.04 ppa build)
- Qt: 5.15.8
- OS: Debian Bookworm with Gnome Shell 43.4
- TeX distribution: texlive

### Expected behavior

* Click build and view or pressing f5 should compile and the switch focus to the viewer window.
* CTRL - left-click should move cursor to position in text and bring editor window into focus.

### Actual behavior

* Clicking build and view or pressing f5 no longer changes focus to the viewer window.
* CTRL - left-click moves cursor to position in text but no longer brings editor window into focus.

### How to reproduce

* Click build and view or press f5
* CTRL - left-click

**Comment by dbitouze** [comment]
> * Click build and view or pressing f5 should compile and the switch focus to the viewer window.

I wouldn't like this behavior by default.

**Comment by octaeder** [comment]
What @zoof describes is exactly what happens with current windows version (and happened in the past) in both directions.
@dbitouze When using view, or build&view actions in txs main window, this is the desired behavior for the (internal windowed) PDF-viewer. This doesn't happen with the build action (F6).

**Comment by sunderme** [comment]
the focussing works fine on ubuntu, lxqt, qt6/qt5
Probably a qt/gnome issue which we can't fix.

**Comment by sunderme** [comment]
works fine on windows.
I will not spend more time on this.
If you compile txs against qt6, that might help, but there is nothing I can do.
