### ISSUE TITLE
txs built locally crashes on start after update to Win 22H2

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3129]
### Environment
- TeXstudio: current dev, or 4.6.0alpha1
- Qt: 6.5.1, compiled with Qt 6.5.1 R
- OS: Win 10 Home 22H2
- TeX distribution: miktex

### Expected behavior
txs shouldn't crash with segmentation fault or with signal unknown

### Actual behavior
I build txs on a regular basis. Everything was fine until yesterday. Today I had to update Win10 Home from 21H2 to 22H2. Version 4.5.2 and my build still started properly. After that I made a new build with msys2 to integrate fix for #3125. From now on txs failed to start. Following did not help: turn back to latest commit before commit of #3125, build 4.6.0alpha1, update msys2 and all it's packages. It worked after deleting ini file. Further investigation revealed a problem with the last line `Files\CacheStructure=true` in my ini file. Changing value true to false solved the problem. Now being able to start txs again I set option `cache documents for faster reopening`. Thus after closing txs the value of false turned to true. Even so txs now starts as usual. I checked what else changed in the ini file:

Original vs. saved after setting cache option in config dialog:

![image](https://github.com/texstudio-org/texstudio/assets/102688820/4be4f91c-9930-479e-accf-b7beea313450)

Maybe you have any thoughts. My idea was that users might have problems when updating to release 4.6.0 when available.

### How to reproduce
If you can do so, see above.

**Comment by sunderme** [comment]
without a backtrace which indicates where it crashes, debugging is nearly impossible.

**Comment by sunderme** [comment]
anyway, I have fixed one crash.
If you come across another crash, please run txs in a debugger and get a detailed backtrace.

**Comment by octaeder** [comment]
I can't reproduce anymore after having used above workaround.
