### ISSUE TITLE
Add Realtime Typesetting Feature

### ISSUE THREAD

**Issue by gs22078** [texstudio-org/texstudio#3137]
### Describe the feature and the current behavior/state
I would like to request a real-time typesetting feature to TeXstudio. Currently, users need to manually compile their LaTeX documents to view the updated output, which can be time-consuming for large or complex documents. Real-time typesetting would automatically update the typeset output in real-time as the user makes changes to the LaTeX code, providing a more interactive and efficient editing experience.

### Who will benefit with this feature?
This feature would greatly benefit all LaTeX users, particularly those who work on large or complex documents. Some benefits include:
- Save time and effort by eliminating repetitive manual compilations after each change.
- Immediate feedback on the impact of modifications, aiding in error identification and formatting.
- Enhance productivity for users who frequently switch between writing and previewing their LaTeX documents.

### Any Other info
Real-time typesetting has been successfully implemented in other LaTeX editors like Texifier (previously known as TexPad). Incorporating this feature into TeXstudio would make it more competitive, attract a broader user base, and enhance its usability as a powerful and user-friendly LaTeX editing tool.

While initially focusing on basic editing functionalities, such as adding simple paragraphs and math equations, I believe it would be beneficial to have a long-term vision of gradually expanding real-time typesetting support to encompass a wide range of LaTeX functions. This would significantly enhance the editing experience and make TeXstudio an even more powerful LaTeX editing tool.

Thank you for considering this feature request, which I believe would significantly improve the editing experience in TeXstudio.

**Comment by sunderme** [comment]
This has been asked before and there is no intention to implement this.
txs offers preview feature on lines which are updated as you type.
Also `latexmk -pvc` recompiles on every save, so that basically already does what you want.
