### ISSUE TITLE
changes in Menus config not always take effect

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3141]
### Environment
- TeXstudio: I would say any
- Qt: any
- OS: any
- TeX distribution: irrelevant

### Actual behavior
Currently there are four menu items from uiconfig.xml that are defined as actions (they call slots) instead of inserts. Thus the Menus Config Panel texts are empty. Changing the text to be inserted in the Menus Config Panel has (surprisingly) no effect. In detail:
```
231:  <action id="ref" text="ref" slot="1insertRef()" info="Insert \ref with a label selected from a drop down list."/> 
232:  <action id="eqref" text="eqref" slot="1insertEqRef()" info="Insert \eqref with a label selected from a drop down list."/> 
233:  <action id="pageref" text="pageref" slot="1insertPageRef()" info="Insert \pageref with a label selected from a drop down list."/> 
241:  <action id="bibliography" text="\bibliography{}" slot="1insertBib()"/> 
```
Note: The info attributes are new as I plan to add them. Three empty fields for Cross References:

![image](https://github.com/texstudio-org/texstudio/assets/102688820/b1d8b4ce-27e5-4fae-b59f-9b8373e47684)

Note: It may be important to know that ongoing work will also change _label_ to an action (automatic labeling, s. #2880). So it might be desirable for the user to change back the text to `\label{%<key%>}`.

Here my questions:
Is this a known/intended behavior?
Would you change this (with respect to effort and benefit) such that changes take effect?

**Comment by sunderme** [comment]
This is a logical consequence. Defining a slot means the action jump there. Only the default slot "insertFromAction" sets text from "insert" into txs.
