### ISSUE TITLE
TXS shouldn't insert active characters (such as  `:`)  in labels

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#3142]
### Describe the feature and the current behavior/state
Currently, in some cases, TXS automatically inserts the `:` character in labels, e.g. with the graphic wizards. But this character is problematic in some cases, as the following one:
```latex
\documentclass[french]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{cleveref}
\begin{document}
\Cref{fig:foo}
\begin{figure}[ht]
  Foo
  \caption{Bar}
  \label{fig:foo}
\end{figure}
\end{document}
```
The compilation error of this example is due to the fact that `:` is an active character with `babel-french`. So it would be nice for TXS to not automatically insert in labels any of the `babel`'s active characters. These are the following (according to the list page 14 of `babel`'s documentation):
```
Basque " ' ~
Breton : ; ? !
Catalan " ' `
Czech " -
Esperanto ^
Estonian " ~
French (all varieties) : ; ? !
Galician " . ' ~ < >
Greek ~
Hungarian `
Kurmanji ^
Latin " ^ =
Slovak " ^ ' -
Spanish " . < > ' ~
Turkish : ! =
```

(Note that it looks like `polyglossia` has (kind of) active characters as well.)

### Who will benefit with this feature?
All the (numerous) users of `babel` with the previous languages.

**Comment by sunderme** [comment]
This sounds like a bug of Babel.
Does it also interfere with urls and paths?

**Comment by dbitouze** [comment]
> This sounds like a bug of Babel.

I wouldn't say that and, IMO, it is more a `cleveref` deficiency. For instance, `tikz` provides the `babel` library that make the interaction with the `babel` package easier. But we cannot ask all of the authors of the packages sensible to active characters to take care of the interaction with `babel` and, since a long time, it is advised to not use such characters in labels. 

Hence it would be better for TeX editors to avoid them.

> Does it also interfere with urls and paths?

No, I guess thanks to `hyperref`'s magic.

**Comment by octaeder** [comment]
maybe change the source when language is one of Breton, French, Turkish, or simply use underscore.
```
QString InsertGraphics::generateLabel(QString fname)
{
	QFileInfo info(fname);
	return "fig:" + makeLatexLabel(info.baseName());
}
```
and
```
void InsertGraphics::chooseFile()
{
	QString fn;
	QStringList exts;
	foreach (const QString &fmt, m_imageFormats) {
		exts.append("*." + fmt);
	}
	QString filter = tr("Images") + " (" + exts.join(" ") + ")";
	filter += QString(";;PGF/TikZ (*.pgf *.tex)");
	fn = FileDialog::getOpenFileName(this, tr("Select a File", "Wizard"), texFile.absolutePath(), filter);
	if (!fn.isEmpty()) {
		ui.leFile->setText(fn);
		if (ui.leLabel->text().isEmpty()) {
			QFileInfo fi(fn);
			QString bn = "fig:" + fi.baseName();
			ui.leLabel->setText(bn);
		}
		emit fileNameChanged(fn);
	}
}
```

**Comment by sunderme** [comment]
I can't reproduce an issue.
<img width="625" alt="grafik" src="https://github.com/texstudio-org/texstudio/assets/14033169/f579725d-47c8-45fd-83ab-3b1caee7a6d8">

**Comment by dbitouze** [comment]
>I can't reproduce an issue.

Very strange. Here is my:
```
 *File List*
 article.cls    2022/07/02 v1.4n Standard LaTeX document class
  size10.clo    2022/07/02 v1.4n Standard LaTeX file (size option)
 fontenc.sty    2021/04/29 v2.0v Standard LaTeX package
   babel.sty    2023/05/11 v3.89 The Babel package
  french.ldf    2023/03/08 v3.5q French support from the babel system
babel-french.tex
scalefnt.sty    
  keyval.sty    2022/05/29 v1.15 key=value parser (DPC)
cleveref.sty    2018/03/27 v0.21.4 Intelligent cross-referencing
l3backend-pdftex.def    2023-04-19 L3 backend support: PDF output (pdfTeX)
 ***********
```

**Comment by sunderme** [comment]
apparently texlive-lang-french was missing.

I consider this a feature request as it only (?) affects cleveref.

**Comment by dbitouze** [comment]
> And to be clear, the FR is to change the default separation character if and only if cleveref and babel/affected languages are active.

I wouldn't restrict to such cases:

- it is generally better to avoid characters potentially active in labels,
- the `cleveref` package could be added afterwards, once the trapped labels are in place.

**Comment by jbezos** [comment]
It’s a bug in `cleveref`, which does a full expansion with arbitrary code. See https://tex.stackexchange.com/a/627447/5735.

**Comment by sunderme** [comment]
I will not follow this "race to the bottom", i.e. in some circumstances `:` is undesirable, because of that **everyone** should not use it because ... ?
The scheme `category:label` is very common, easy to understand, I really see no necessity to deviate from that.

**Comment by dbitouze** [comment]
Too bad! Active characters are like time bombs.

What about `_` which is:

- widely understood as a space,
- harmless in labels?

`\ref{fig_foo}` does make sense.

**Comment by octaeder** [comment]
is there any guaranty that underscore will never become an active character in some package maybe because of an issue as with cleveref?

**Comment by dbitouze** [comment]
There is no guaranty but it looks unlikely that a package author would make active a special character of TeX, but I may be wrong.

**Comment by dbitouze** [comment]
> It's been part of a convention to use `:` as label name separator. Several LaTeX books, including the original _LaTeX---A Document Preparation System_ (2nd edition, 1994) by Lamport uses this way.

Indeed but, at this time, there was no packages that defined some characters as active.

But, okay, I admit defeat :wink:

**Comment by muzimuzhi** [comment]
Recent book _The LaTeX Companion_ 3rd edition, published in May, 2023 uses `:` as label name separator in its examples (see https://github.com/FrankMittelbach/tlc3-examples) too.

```
grep -rn '\\label{.*:.*}' **/*.ltx | wc -l
     123
```

To list some,
```tex
NORMAL/10-13-2.ltx:25: \item The first item in the list.\label{lst:a}
NORMAL/11-2-34.ltx:26:  x^2+y^2 &= z^2 \label{eq:A}            \\
NORMAL/2-2-3.ltx:25:\section{This is correct}\label{sec:OK}
NORMAL/2-4-13.ltx:26:    \begin{figure}\caption{A}\label{fig:a}\end{figure}
NORMAL/2-4-16.ltx:26:\begin{thm} A theorem.  \label{thm:a}\end{thm}
NORMAL/2-4-16.ltx:27:\begin{lem} A lemma.    \label{lem:a}\end{lem}
```

**Comment by dbitouze** [comment]
@muzimuzhi Maybe the authors didn't notice the trouble with `babel-french` and some packages (`cleveref` at least).
