### ISSUE TITLE
Aligning columns on `tblr` environment adds a new column

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#3148]
### Environment
- TeXstudio: git 4.5.2-42-g3494e80a0
- Qt: 6.5.0
- OS: macOS 12.6.5
- TeX distribution: irrelevant

### Expected behavior

No new column added.

### Actual behavior

Each time "Align Column" is clicked, a new column is added.

### How to reproduce

The first mandatory argument of `tblr` and other `tabularray` envs can take two forms,
- the traditional tabular-like syntax `\begin{tblr}{<table preamble>}`
- new syntax `\begin{tblr}{colsepc=<table preamble>, <other kay-vals>}`

Currently the "Align columns" function works for old syntax, but not for the new syntax.

Using the example below, move cursor in `tblr` env content, click "Align Columns"
```tex
\documentclass{article}
\usepackage{tabularray}

\begin{document}
\begin{tblr}{colspec={ccc}}
  a & b & c \\
  a&b&c\\
\end{tblr}
\end{document}
```

Expected:
```tex
\begin{tblr}{colspec={ccc}}
  a & b & c \\
  a & b & c \\
\end{tblr}
```
Actual:
```tex
\begin{tblr}{colspec={ccc}}
  a & b & c &  \\
  a & b & c &
\end{tblr}
```

**Comment by sunderme** [comment]
"new syntax \begin{tblr}{colsepc=<table preamble>, <other kay-vals>}" is not supported by txs.
Basically the function causes hickups because of misinterpreting the column definition.

**Comment by muzimuzhi** [comment]
Many thanks!
