### ISSUE TITLE
Selecting references - bibliographic or internal to the document - removes subsequent text until the next closing bracket.

### ISSUE THREAD

**Issue by hannes101** [texstudio-org/texstudio#315]
If inside a caption or footnote environment, if one would like to include a reference with \ref{} or \textcite{} and after selecting one of the presented options, all the following text inside the caption or the footnote is deleted until the closing bracket of the footnote or caption is reached. 
I hope the description is clear, it probably doesn't happen so often, since most of the time one does this on the fly and there's no text following the reference to be inserted, but in my case this happened repeatedly.

### Environment
- TeXstudio  2.12.10
- Qt: Using Qt Version 5.10.1, compiled with Qt 5.10.1 R
- OS: fedora 28 x86_64
- TeX distribution: texlive

### Expected behavior
No text inside the footnote is removed after the insertion of a reference.

### Actual behavior
Text is removed.

### How to reproduce
Create a \footnote and enter some text. Then start adding a reference with \ref and select an item from the dropdown menu. Hit enter and the text after it is gone and the closing bracket is missing as well.

**Comment by sunderme** [comment]
please provide a video of what you see or a more precise example with starting text, where is the cursor, what do you enter.

**Comment by hannes101** [comment]
While doing the screencast and trying to replicate it. I found out that one has to write \textcite{ and then select the reference and then all the text between the starting bracket and the end of the caption or footnote is removed. If you don't write the first bracket it works just fine. 
I hope this clarifies it:
https://jlips.next-cloud.org/index.php/s/tNxPbMmqDNBWkYe

**Comment by thatlittleboy** [comment]
It's not that surprising a behaviour. You can simplify the problem further, consider the following MWE:

**bib.bib**
```
@article{abcd,
	title={Test article title},
	author={A. B. Charles},
	journal={Phys. Rev. B}
}
@article{efgh,
	title={Test article title 2},
	author={A. B. David},
	journal={Phys. Rev. C}
}
```

**main.tex**
```
\documentclass{article}

\begin{document}
	BEFORE BEFORE{within the | brackets is some test text}AFTER AFTER
	
	\nocite{*}
	\bibliography{bib}
	\bibliographystyle{plain}
\end{document}
```

Put the cursor on `|`, then type `\cite{`. Note what happens:

<img src=https://user-images.githubusercontent.com/30731072/45242553-76b67700-b2be-11e8-863e-7e521badec52.gif width=450px>

The words `brackets is some text` become parsed as a bibliography key (because of the `}` present after that), and when you select the `abcd` bib key, it _replaces_ the current bib key (i.e., the `brackets is some text`).

This 'replacement' behaviour is probably intended (the devs can confirm this?), for example:
<img src=https://user-images.githubusercontent.com/30731072/45242889-bcc00a80-b2bf-11e8-950c-9d8ad17ba1ed.gif width=450px>

**Comment by sunderme** [comment]
the replacement behaviour is intended. So everything between { and } will be deleted and replaced.

**Comment by sunderme** [comment]
@hannes101 please provide the text of the example (including usepackage etc). It is not reproducible with \caption{sdsdf \textcite{abc} dsfgsdgsfg}

**Comment by hannes101** [comment]
It also happened in a \footnote environment, don't have time today, but will provide it tomorrow.

**Comment by sunderme** [comment]
@hannes101 now i saw it.
Same issue as with @thatlittleboy . txs replaces evrything between \textcite{ and }.
If you type \textcite{ and then do the completion, everything after is replaced.
Just type "\textci" , choose what you want to choose and insert it.

**Comment by hannes101** [comment]
I don't mind using `\textcit`, but the issue I had was that I didn't notice the replacement behavior the first time and then just wondered where all the text went. I think the problem is that documents could become corrupted and no one notices.
