### ISSUE TITLE
double click selects 0 characters

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3160]
### Environment
- TeXstudio: likely all
- Qt: 6..5.1
- OS: Win10
- TeX distribution: miktex

### Expected behavior
Since nothing is selected I would expect that the status line doesn't show Selected: 0.

### Actual behavior
A double click right to the end of a line displays following in the status line:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/58d604aa-5286-4831-927f-c76e785e2762)

But as far as I can see there is no selection. Anchor and cursor positions are the same, but by definition of a selection, it is not a selection then.

### How to reproduce
s. above

**Comment by sunderme** [comment]
That is so fringe and purely cosmetic, I don't care at all.
