### ISSUE TITLE
Add current time or process id to process messages

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3161]
### Describe the feature and the current behavior/state
I would like to ask what you think about following:

1. Prepend a time string (say format HH:mm:ss) to process notifications (I already use this and could provide a PR):

   ![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/d10b14dd-0a81-4d66-a12d-ecf3a0e0d231)

2. Insert a process id in process notifications like "Process x started: ..."

### Who will benefit with this feature?
ad 1: Since I have long running compiles I track compile time. This helps me plan my time slots for other things.
ad 2: Sometimes several processes are running but not all end successfully (preview and compile). But then it's not clear which of the processes was in error.

**Comment by sunderme** [comment]
I would prefer to keep it minimal and as non-technical as possible.
So "process exited normally after xyz seconds" ?
For process id, maybe tooltip ? link ?

**Comment by octaeder** [comment]
I think there were some discussion about elapsed time last year, but without changes.
So simplest solution should be what the image shows. This needs a change of one line, the time text inserted has constant length, and no need to figure out what 4.200 seconds are or how to convert to a sensible format.

I have no idea what the code should look like for handling pids. So I would leave it to others (likely you 😀). But I think that I should see the pid directly in the text for comparison. Otherwise I would have to hover over each link/tooltip to match start and end. Or should the link in the end message should jump to the start message?

**Comment by sunderme** [comment]
I don't think, that putting the current time in front of the process info is helpful.
It is irrelevant most of the time, an then you need to subtract times in your head to get the info which you want ...
Also, it simply looks to technical...

**Comment by octaeder** [comment]
and for long running processes start time is of interest since it tells me how long it may take to finish (when I have knowledge about runtimes) or when it will finish

**Comment by sunderme** [comment]
I don't want clutter. And most of the time, the time stamp is simply uninteresting and takes away from the important info.
So, any interactive info (link/tooltip) is fine, but static information irrelevant for most is not desirable.

**Comment by stefanlloyd** [comment]
I would find a timestamp useful, as in editing sessions, it would remind me when I last re-compiled the tex file.
