### ISSUE TITLE
Bibliography has to be manually regenerated

### ISSUE THREAD

**Issue by juhaszp95** [texstudio-org/texstudio#3163]
### Environment
- TeXstudio: 4.5.2 
- Qt: 6.5.0 
- OS: Win 10 
- TeX distribution: MikTeX 

### Expected behavior
TexStudio very helpfully regenerates the biblopgraphy (by rerunning biber/bibtex) when it changes. However, if a project contains multiple files (e.g. a PhD thesis) and the root document changes only rarely, it does not pick up on the .bib file being changed and the bibliography tools have to be run manually (which is annoying - this is perhaps because it compares the timestamp of the .bib file to the root latex file in the project?).

It would be great if it would always pick up changes in the .bib file - perhaps by saving what timestamp on the .bib file was used when the last PDF was generated, and if the .bib file is newer than before, bibliography would be automatically regenerated.

### Actual behavior

See above.

### How to reproduce
Create a project with a root tex file which \includes other tex files. If you change the bibliography and the included tex files (but not the root tex file), bibliography isn't regenerated automatically.

**Comment by sunderme** [comment]
I am not bored enough to set up random documents and hope that something does or does not happen.
So, if you want someone to look into this, please provide text documents and a step-by-step instruction how to trigger/see the issue.
