### ISSUE TITLE
Refine order of packages with Quick Start wizard

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#3164]
### Describe the feature and the current behavior/state

#3151 changed the order of packages to

> Now static sequence is as follows (geometry at second place):
> ```C++
> // LaTeX code for all packages used
> 	tag += fontenc + geometry + graphicx + mathtools + amssymb + amsthm + thmtools + xcolor + nameref + babel + hyperref + userPackages;
> ```
> 
> _Originally posted by @octaeder in https://github.com/texstudio-org/texstudio/issues/2901#issuecomment-1584450993_

But in most cases, `hyperref` should be loaded after all `userPackages`.  `cleveref` is a common exception which should be loaded even _after_ `hyperref`. One possible order could be

```c++
// LaTeX code for all packages used
	tag += ... + userPackagesFreeOrder + hyperref + userPackagesSpecial;
```

### Who will benefit with this feature?

Any one who use Quick Start wizard with user packages.

**Comment by octaeder** [comment]
@dbitouze I would like to hear your opinion.
I can add a similar exception for cleveref as I did for all those named packages above. Then I can move it to the end of the list together with hyperref.
This has do be done (in the future) for any package that needs special placement.
But I hope that I need not to change this every week.

**Comment by dbitouze** [comment]
About, the order of packages, here is what I am aware of (if I'm not mistaken):

1. `inputenc`: input encoding
2. `fontenc`: font encoding
3. ⟨other packages⟩
⋮
n − 2. `natbib`: flexible bibliography support
n − 1. `beamerarticle`: production of an article-type document from a beamer document
n.     `babel`: language management
n + 1. `eurosym`: € symbol
n + 2. `varioref`: enhanced cross-referencing
n + 3. `floatrow`: customize floats page layout
n + 4. `caption`: customize floats captions
n + 5. `subcaption`: sub-figures/sub-tables
n + 6. `listings`: insert computer listings
n + 7. `datetime2` : display dates
m.     `hyperref` : hypertext links
m + 1. `hypcap`: hypertext links to enhanced legends
m + 2. `bookmark`: enhanced bookmarks
m + 3. `multimedia`: inclusion of external animation or sound files
m + 4. `glossaries` (or glossaries-extra): glossaries, acronyms, etc.
p.     `cleveref`: clever cross-references
p + 1. `autonum`: numbered equations only if referenced

where:

- n > 5
- m ≥ n + 7
- p ≥ m + 4

**Comment by octaeder** [comment]
Thanks, this is quite overwhelming. But your list confirms that I should move inputenc (new) to the beginning, and hyperref and cleveref (new) to the end.
Since the user can choose any package, this will never be perfect. And I want to remind that this is a first try dialog, more sophisticated solutions can be done with templates.
I hope this is ok.
