### ISSUE TITLE
Show inline preview using original preamble only

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3166]
### Describe the feature and the current behavior/state
Compiling the document with the complete include tree has many advantages: Layout is exactly as expected, you have full access to the contents and the index, no problems with missing references. An obvious disadvantage is that this method can be quite time consuming especially when multiple runs are necessary. Cutting down the include three may speed up things but all the advantages have gone.

But txs offers a great preview functionality. Unfortunately the result is often not similar to what you get from a full compile. This happens because the preview compile adds some extra code at the end of the original preamble (s. texstudio.cpp):
```latex
\usepackage[active,tightpage]{preview}
\usepackage{varwidth}
\AtBeginDocument{\begin{preview}\begin{varwidth}{\linewidth}}
\AtEndDocument{\end{varwidth}\end{preview}}
```
This optimizes the output, which is quite nice particularly for tooltips. But the inline preview will not be what one will get from the final compile, since \parindent is changed (anything else?). But I often need to check if the text layout is fine in each line: Spacing between words, text fits in the line so nothing is moved into the right margin, and I want to avoid line breaks within inline formulae. Fine tuning the document in this way is very time consuming, thus a preview option that gives you a preview similar to the final document would be of great help. In fact this is available when you set Preview Display Mode to Show in embedded viewer. But in this way you can't compare the new result to the old one.

### Who will benefit with this feature?
Almost anyone want's to avoid the time consuming work of adjusting text. Therefore a preview with original preamble should be of great help.

### Any Other info
Current behavior;
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/035540a9-4784-47ac-9d4e-84f8f056a637)

Expected behavior:
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/da5b9755-56de-48af-8a43-dad3c550db9f)

Derived from (build with lualatex):
```latex
\documentclass[ngerman,10pt,a5paper]{article}
\usepackage[T1]{fontenc}
\usepackage[width=11cm, height=17cm]{geometry}
\usepackage{mathtools}
\usepackage{babel}
\begin{document}
Lorem ipsumdolor sitamet, consetetur sadipscing elitrsed diamnonumy eirmod
tempor invidunt utore etadolor magna ali $\forall (a,b,c,d,e,f,g,\ldots,z)$
erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea
rebum. Stet clita kasd gubergren

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren
\end{document}
```

**Comment by octaeder** [comment]
@sunderme please comment following state of development:

New standard (not advanced) option with tooltip, checked by default (i.e. old behavior):

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/78859e01-518d-471d-b1a0-0d078edfc2e3)
(click image to enlarge)

Also quick access via menu (`Alt+I`, `S`):

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/17a25db4-1e4b-47eb-8300-ccfd8557a470)

Compare old vs. new inline preview (be aware of differences in word spacing, line breaks, and footnote marks). To toggle between the two results use `Alt+I`, `S`, `Alt+P`:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/29d74f19-bb78-4602-93c7-b419fe9a6da7)
(click image to enlarge)

That works analogously when Preview Display Mode is set to Preview Panel. When you choose Tooltip as Preview Display Mode:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/c7253dbf-04d0-4af2-879b-eac26855c6a5)
(click image to enlarge)

The option has no effect when Preview Display Mode is set to Show in embedded viewer, or on math tooltips:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/afd3a175-5831-495f-a68d-c68e9ff9074e)

Slightly changed code to:
```latex
\documentclass[ngerman,10pt,a6paper]{article}
\usepackage[T1]{fontenc}
\usepackage[width=7cm, height=10cm]{geometry}
\usepackage{mathtools}
\usepackage{babel}
\begin{document}
Lorem ipsumdolor sitamet, consetetur sadipscing elitrsed diamnonumy eirmod
tempor invidunt utore etadolor magna ali $\forall (a,b,c,d,e,f,g,\ldots,z)$
erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea
rebum. Stet clita kasd gubergren\footnote{ae öds edod}

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren
\end{document}
```

**Comment by sunderme** [comment]
the inline preview is definitely not intended to contain whole pages. 
Hence "shrink page" is not really meaningful, especially as it contradicts the first idea, to achieve results like a full compile.
The inline preview is for formulas and the like and there the current solution works as intended.

**Comment by octaeder** [comment]
"shrink page" means the old behavior, and that is definitely shrinking the page and the minipage. Since it's the default, it will work as you expect it and and as it is "intended".

But what you think is intended doesn't always happen. Out of the box choose _Preview with dvips/ghostscript_ and you will see exactly what I developed here for pdf. Seems that these manipulations in the preamble would not work with dvips. But I would not recommend removing option _Preview with dvips/ghostscript_, because it may be usefull for someone.

Of course, the main target is not to preview whole pages. But it guarantees that preview works as well as possible not only for formulas. And you can still choose where to see it, it doesn't have to be inline. So anyone who has to cope with overfull boxes/lines (and I believe there are many people doing so) can quickly analyze effects of changing the LaTeX code at some point without waiting for large compiles. But this is not possible when you use a minipage. Looking at formulas is not the end. With this new option the value of txs really increases. So why stick with limited functionality?

**Comment by sunderme** [comment]
I don't like to have two modes here. It basically means that you are "always" in the wrong mode.
Looking at compilation result, especially for the actual text typesetting, is exactly what the embedded viewer is for.
If your compile times get too long, maybe take a look at `\includeonly` or subfiles.
Last option may be using macro for special compilations.

**Comment by octaeder** [comment]
As said using preview in embedded viewer is not suitable for cases described above. I give more arguments: Even when you open a second pdf viewer window then you will simply see your document twice. Now running the preview will replace the document by the preview in both viewers. You may argue that `Ctrl`+click will at least bring back the original document. But there is another problem you may not have thought of: Moving over the editor may start previews and your main document will be missing again. That leads to nothing useful because txs is not made for previewing two different documents.
I also mentioned why cutting down the document is not the best way for working. So I have given a whole bunch of arguments that speak for doing the change. Even so you don't want to accept it because one could "always" be in the wrong mode what can be fixed with three key strokes that toggle mode *and* update preview. Maybe all those should simply stay with the default, i.e. nothing changes.

**Comment by octaeder** [comment]
Final words can be found in PR #3175 that has been closed without merging.

**Comment by octaeder** [comment]
@sunderme What about this?

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/79c30aec-2cd8-4f94-8315-5755cd9e902e)

This can be achieved by simply adding some latex code (no other changes, no need for options) in makePreviewHeader as follows:

header << "\\usepackage[active,tightpage]{preview}"
				<< "\\usepackage{varwidth}"
				<< "\\AtBeginDocument{**_\\newlength{\\txsParindent}\\setlength{\\txsParindent}{\\parindent}_**\\begin{preview}\\begin{varwidth}{\\linewidth}**_\\setlength{\\parindent}{\\txsParindent}_**}"
				<< "\\AtEndDocument{\\end{varwidth}\\end{preview}}";

This sets parindent correct, but will not show, that the formula protrudes the margin. But  parindent is the more important one.

**Comment by octaeder** [comment]
with env varwidth this doesn't really help. We would need to replace it by minipage.
