### ISSUE TITLE
Update check: SSL handshake failed. Debian 12

### ISSUE THREAD

**Issue by mlmateos** [texstudio-org/texstudio#3167]
Can't check update, get this error: SSL handshake failed
### Environment
- TeXstudio: 4.5.2
- Qt: 5.12.8
- OS: Linux Debian 12 (BookWorm)
- TeX distribution: TeXLive

### Expected behavior
Check update

### Actual behavior
![Screenshot from 2023-06-18 08-24-56](https://github.com/texstudio-org/texstudio/assets/6385699/0e473095-d80b-4cf1-bf1a-5428aa17b252)

### How to reproduce
Go to Configure TeXstudio  -> Check Now

**Comment by sunderme** [comment]
related to #3118

looks like debian issue. Ubuntu works fine.

**Comment by mlmateos** [comment]
Yes , it works fine in debian 11. Any suggestion?

**Comment by sunderme** [comment]
I have no idea. Nothing we can do on our side.
it is probably, certificate, openssl or qt issue.

**Comment by mlmateos** [comment]
Maybe TeXStudio has an older openssh version, and  for some reason won't accept something with the authentication from the newer machine!

**Comment by sunderme** [comment]
nothing we can do.
