### ISSUE TITLE
Home key acting oddly in Version 4.5.2

### ISSUE THREAD

**Issue by cohensm52** [texstudio-org/texstudio#3171]
I just updated to texstudio version 4.5.2 (and also just updated miktex). Now the Home key is acting differently than it used to, and this is (for me) undesirable. 

### Environment
- TeXstudio: 4.5.2
- Qt: 
- OS: Windows 10
- TeX distribution: miktex 2.9 

### Expected behavior
I would expect the Home key would take the cursor to the beginning of the current line. This is what it always used to do. Similarly, the End key should take the cursor to the end of the current line, which it does.

### Actual behavior
The Home key take the cursor to the beginning of the current paragraph, not to the beginning of the current line.

### How to reproduce
Place the cursor in the middle of a paragraph and then hit the Home key.

**Comment by octaeder** [comment]
Way back is described [here](https://github.com/texstudio-org/texstudio/issues/3012#issuecomment-1533787738)

**Comment by octaeder** [comment]
Since your issue is resolved you may close it, thanks.

**Comment by cohensm52** [comment]
Is there a way to fix this related issue which happens even after implementing the fix you suggested, @octaeder? If the cursor is on the first line of a paragraph, the Home button now takes it to the left-most position of that line, even if the line starts with a tab character, so that the entire paragraph is indented. I'd like it to move to a point just to the left of the first "letter" character, which would be to the right of that tab character, which I'm pretty sure is what it used to do. For example,

         some text here
        ^here
^rather than to here
Hopefully that's clear what I'm asking.

**Comment by octaeder** [comment]
I see no way doing so other than implementing a new feature. I suggest opening a feature request for that.
