### ISSUE TITLE
Trigger and the enter bottom 

### ISSUE THREAD

**Issue by RabahHouna** [texstudio-org/texstudio#3177]
### Environment
- TeXstudio:  4.5.2	
- Qt: Version 6.5.0, compiled with Qt 6.5.0 R
- OS: Windows 10
- TeX distribution:  texlive

### Expected behavior
I would like to ensure that when I use the `(\S+)\s` in the trigger and write the trigger, nothing happens when I press Enter immediately afterwards. 

### Actual behavior
This is because I have created a macro with the trigger `begin(\S+)\s` to simplify the process of writing environments. However, I face the issue that when I press Enter after typing `\begin{env}` which already exists in my .tex file, TeXstudio triggers the macro and disrupts my existing environment.

**Comment by sunderme** [comment]
Replace '\s' with just ' '. (Space)

**Comment by RabahHouna** [comment]
Thank you.

**Comment by RabahHouna** [comment]
I  have created the following macro: 
![Screenshot 2023-06-27 083208](https://github.com/texstudio-org/texstudio/assets/132083925/9198ec66-3457-4312-ac38-bdd1623e6cf8)
But when I used the trigger after a space the result is like this (for example after tap space)
![Screenshot 2023-06-27 093736](https://github.com/texstudio-org/texstudio/assets/132083925/95fae6c1-b0aa-421a-b86f-85ae0796f5c1)
what I want is this :

![Screenshot 2023-06-27 093736](https://github.com/texstudio-org/texstudio/assets/132083925/e29e350c-eca1-4423-b703-8ec4e2c3c0fd)
