### ISSUE TITLE
Word completion made easier and faster, emacs/kile style

### ISSUE THREAD

**Issue by guigui-ln** [texstudio-org/texstudio#3179]
Make word completion (not command completion) easier and faster. 

### Describe the feature and the current behavior/state

Current word completion is : type letters, press ctrl+space, look at the menu, select the word you want to complete with (sometimes using the mouse is necessary) , press enter or tab.

It works well, though it is quite long and disrupts the user from the flow of his typing. Most of the time you're better just typing the word completely.

The smoothest way I've seen it done is in emacs, or kile, or many code-oriented editord : type letters, press a shortcut (tab key is nice !), have your letters completed by the closest word above starting with those letters in the document. If this is not the word you want, just press shortcut again and it gives you the second most recent word and so on.

This way there is no disrupt in your typing. The word "probability" just becomes pro-tab, or even pr-tab and you gain time.
Plus there is no real need for a dictionnary. Just type the word completely the first time in your document, then just complete it.

### Who will benefit with this feature?

Any user used to this type of word completion, and the others fast-typers will love it.
See for instance request here : 
https://tex.stackexchange.com/questions/341173/does-texstudio-offer-word-complete-feature

### Any Other info

emacs is too professionnal for me, kile is not well maintained. Texstudio actually looks and runs better, and offers really nice functionnalities like macros. But I just cannot seem to part from my 20 years letters+tab=word habit. Give it back to us !

**Comment by sunderme** [comment]
I have played with kile, and it is by no way a better solution.
Obviously you can define "tab" as "normal complete" but it will never be the default in txs.

**Comment by sunderme** [comment]
<img width="734" alt="grafik" src="https://github.com/texstudio-org/texstudio/assets/14033169/96c2ee34-96e1-4192-9e56-26744db30520">
Normal complete automatically distinguishes text completion or command completion.

**Comment by dbitouze** [comment]
That's much less handy than with Emacs (with appropriate completion package) which directly displays suggestions in a unobtrusive way (in light gray). Here, you have to trigger the shortcut in order to see them.

**Comment by guigui-ln** [comment]
Thanks for pointing the place out sunderme, it was obvious. Now that I could set the shortcut for normal completion to the tab key, things start to get a bit smoother.

Now is it possible to have the words suggested come only from the current document, and not from external sources ? 
I tried the "most used" option but I get suggestions that I never wrote in the document.

@dbitouze : I did not use emacs recently. In my memory there were no suggestions at all, just press tab and your word is completed.

**Comment by dbitouze** [comment]
@guigui-ln I guess what you experienced with `Emacs` required some package (plug-in). What I was talking about is the [`company-mode` package](http://company-mode.github.io/).

**Comment by sunderme** [comment]
text completion only takes words from the current document ...

**Comment by guigui-ln** [comment]
Yes it does, no idea where my last message came from, sorry again.

So now it looks like what I'm used too. Differences are : 

* pop up menu : any way to disable it and have the suggested word written directly when pressing shortcut ?
* cycle through the different suggested words: any way to do it with the shortcut assigned to text completion, instead of with arrows ?

This way typing a word could look like : type letters - press shortcut until you see the word you want - type next word.

**Comment by sunderme** [comment]
this will not be implemented in txs, it has already a working completer.
it may be possible to realize this with macros.

**Comment by guigui-ln** [comment]
Alright I'll look into the macro possibility. Thanks for your time sunderme.
