### ISSUE TITLE
Commands not recognized in ≥4.6.0 alpha2

### ISSUE THREAD

**Issue by l1n00x** [texstudio-org/texstudio#3180]
### Environment
- TeXstudio: TeXstudio 4.6.0 (git 4.6.0alpha3)
- Qt: 6.5.1, compiled with Qt 6.5.1 R
- OS: Windows 11
- TeX distribution: TL 2023

### Expected behavior
Recognize commands.

### Actual behavior
Some commands are not recognized starting with alpha2. Alpha1 is fine.

What I checked and works in ≤4.6.0alpha1). Output is from alpha3:
![grafik](https://github.com/texstudio-org/texstudio/assets/137958291/e18fba1d-eb0e-4ddf-9ed6-0e728a4637c2)

### How to reproduce
Type commands into editor.

**Comment by sunderme** [comment]
complete examples please.
txs understands usepackage, so without a complete test document, nothing we can do.

**Comment by l1n00x** [comment]
**main.tex**
```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[
	backend=biber,
]{biblatex}

\begin{document}

\include{01.tex}
\parencite{bibid}

\end{document}
```

**01.tex**
```
\parencite{bibid}
```

The problem occurs for commands of the respective package if the following conditions are both met: 
- Using the command in an included file
- Using a comma (,) after the last package option

Removing the comma after "biber" fixes the problem present in ≥4.6.0 alpha2. Commands within the main document are always recognized.

**Comment by dbitouze** [comment]
Aside remark: `backend=biber` is useless since `biber` is the default backend nowadays.

**Comment by l1n00x** [comment]
It seems that only changes to the respective package options inside the root file will "fix" the problem (e. g. adding a space after "biber".

**Comment by l1n00x** [comment]
I forgot to mention that you will have to used \include{}. The issue does not occur for commands used in the root document.

**Comment by l1n00x** [comment]
Using txs 4.6.0b1, the issue still persists. I used my previous example which works if it is copied into the txs editor. If txs is closed and reopened however, commands are not recognized within 01.tex still.

 **main.tex**
 
 ```
 \documentclass{article}
 \usepackage[utf8]{inputenc}
 \usepackage[
 	backend=biber,
 ]{biblatex}
 
 \begin{document}
 
 \include{01.tex}
 \parencite{bibid}
 
 \end{document}
 ```
 
 **01.tex**
 
 ```
 \parencite{bibid}
 ```
