### ISSUE TITLE
Add comprehensive text macro example to doc

### ISSUE THREAD

**Issue by Toorero** [texstudio-org/texstudio#3181]
I think it would be wise to add a comprehensive example of a macro that uses the placeholder syntax to show how to combine multiple options like:
`%<foo%:mirror,id:123%>`

### Current state
Currently, you can only look at the following code
https://github.com/texstudio-org/texstudio/blob/dc851822750f1ffc232d9642af23a4e97d7b203f/src/codesnippet.cpp#L76-L96
to figure out how to combine multiple options or look at the docs here:
https://github.com/texstudio-org/texstudio/blob/dc851822750f1ffc232d9642af23a4e97d7b203f/utilities/manual/source/advanced.md?plain=1#L175-L215

But on the [website](https://texstudio-org.github.io/advanced.html#text-macros) documentation there is no mentioning of this at all.

## So it's rather a request to update the website to reflect the changes in the docs.

**Comment by octaeder** [comment]
when I follow your website link I would assume that what I see is exactly what the advanced.md file shows above:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/e912e290-ae08-4bd7-8025-a94fe683edd5)

**Comment by Toorero** [comment]
Yes but it isn't.

At least the following two lines are different where crucially the example on how to combine multiple options is shown:
https://github.com/texstudio-org/texstudio/blob/dc851822750f1ffc232d9642af23a4e97d7b203f/utilities/manual/source/advanced.md?plain=1#L185-L186

**Comment by octaeder** [comment]
I see the first line

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/a9f78c4d-c2e8-4782-b209-76ef27faeec4)

I'll check what happend with the second one.

**Comment by octaeder** [comment]
Preview of current git master branch shows the part missing:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/963a159d-5990-4080-9827-b98851c40dbb)

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/5619109b-4fb2-4d8f-8c9e-dbb7ab80fc26)

It seems that it is present from Sep 29, 2022 at least. Html file was generated last May 8, 2023, while md file was changed last time on April 8, 2023. So anything should be ok. But the html file is wrong. For some reason line 186 is ignored:
```html
<li><p>Write %&lt;something%&gt; to mark it as placeholder which is highlighted
in the text and can be selected by <code class="docutils literal notranslate"><span class="pre">Ctrl+Left/Right</span></code>.
Additional properties of the placeholder can be set after a %:, e.g.</p>
<p>are:</p>
```
From my point of view the generator works different from git hub preview. Hopefully @sunderme can figure out.

**Comment by Toorero** [comment]
Oh, yes I get it. Good find.

I think the problem is that [myst-parser](https://myst-parser.readthedocs.io/en/latest/index.html) interprets the line as a comment as stated [here](https://myst-parser.readthedocs.io/en/latest/syntax/typography.html#comments).

**Comment by octaeder** [comment]
That's mystic: "At the beginning of a line" means after some white space characters. But there is nothing said how to stop this interpretation other than adding some text before the % sign. Typically such a character needs to be at position one as the example there suggests.

**Comment by octaeder** [comment]
master is fixed

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/e1dfb19c-351d-47d1-90b2-a690a5d909d9)
