### ISSUE TITLE
issue with icon set in integrated pdv viewer

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3184]
### Environment
- TeXstudio 4.6.0 (git 4.6.0alpha3)
- Qt-Version 6.5.1
- OS: Win 10
- TeX distribution: miktex

### Actual behavior
I deleted my ini file to check some initial settings. Some time ago default icon set was changed to Colibre. Imbedded viewer shows well icons to the right:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/d9796f1d-9b95-4260-8b9f-19c88fca3b0e)

But I cant clearly see it in the windowed viewer: 

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/7b41f40f-7cae-4024-b7fa-eef456b8c37e)

**Comment by sunderme** [comment]
fixed
