### ISSUE TITLE
Compile file and show result via script macro

### ISSUE THREAD

**Issue by faltfe** [texstudio-org/texstudio#319]
### Environment
- TeXstudio: 2.12.10
- Qt: 5.8.0
- OS: Windows 10
- TeX distribution: miktex

## MWE

_main-document.tex_

```LaTeX
\documentclass{article}
\usepackage{subfiles}
\begin{document}
  My main file text.
  \subfile{subfile-document}
\end{document}
```

_subfile-document.tex_

```LaTeX
\documentclass[main-document.tex]{subfiles}
\begin{document}
    Some subfile text
\end{document}
```

## Question

Coming up from [TeX.SE](https://tex.stackexchange.com/questions/450546/in-texstudio-how-to-compile-only-the-subfile/450716) there was a question on how to compile a `subfiles` class document without changing manually the _Root document_.

I've created a macro script to run the file via `system` but I can't figure out how to show the created pdf file in the preview.

```javascript
%SCRIPT
var filename = app.getCurrentFileName();
var dir = filename.substring(0, filename.lastIndexOf("/"));
var proc = system("pdflatex " + filename, dir);
proc.waitForFinished();
var pdfFile = filename.replace(/\.[^/.]+$/, ".pdf");
// how to read/open the created pdf file?
```

Is it possibile to show a PDF file within the inline PDFViewer using a macro script and when so, how?

**Comment by sunderme** [comment]
I have extended txs that it can run the viewer via script.
The command is `app.runInternalCommand("txs:///view-pdf-internal",completeFilename,"--embedded")`

**Comment by timhoffm** [comment]
The change was included in the master development branch two days ago. You cannot expect this to be included in a version that was released two months ago.

Please wait for the next official release or compile TXS yourself.

**Comment by faltfe** [comment]
Thanks for your response. I misunderstood the answer and thought it is an available solution. Thanks for the implementation.

**Comment by sunderme** [comment]
or use the dev builds, see webpage

**Comment by choonkiatlee** [comment]
Hi! I believe I encountered an error running the function provided by @sunderme. What worked for me was the following command: 

```javascript
app.runInternalCommand("txs:///view-pdf-internal" , "--embedded", pdfFilename);
```

The script I used to run and display the current file is (thank you @faltfe !):
```javascript
%SCRIPT

function quote(filename){
	return '"' + filename + '"';
}

var filename = app.getCurrentFileName();
var dir = filename.substring(0, filename.lastIndexOf("/"));
var pdflatexcmd = '../MikTex/texmfs/install/miktex/bin/x64/pdflatex.exe  -src -interaction=nonstopmode '
var proc = system(pdflatexcmd + quote(filename), dir);
proc.waitForFinished();

var pdfFilename = quote(filename.replace(/\.[^/.]+$/, ".pdf"));

app.runInternalCommand("txs:///view-pdf-internal" , "--embedded", pdfFilename);

```
