### ISSUE TITLE
txs starts slowly

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3191]
### Environment
- TeXstudio: yesterdays master, current master
- OS: Windows 10
- TeX distribution: miktex, texlive

### Expected behavior
If possible, a faster start of txs. Reason seems to be https://github.com/texstudio-org/texstudio/commit/ebd9fa2dd9551d3909243f8fb79c36056b6640dc.

### Actual behavior
I start txs with several tabs open, all from a large master file using includes. With 4.5.2 it takes 14s, same with master from June 28 (https://github.com/texstudio-org/texstudio/commit/4183325d2c06f598807e9a3095065799808094d1). But with yesterdays master it takes 63s, but with current master 30s.

### How to reproduce
Maybe use a large master file with includes.

**Comment by octaeder** [comment]
Improving with https://github.com/texstudio-org/texstudio/commit/a185aac1fb147c08ae5c2af97638cd3cace983da, it takes 24s. That's good.

**Comment by octaeder** [comment]
Since I assume that nothing more can be done I close the case.

**Comment by octaeder** [comment]
current master now needs slightly more than 1 minute.

**Comment by mbertucci47** [comment]
On my Windows 10 system it's about 45 seconds with one document pre-loaded, longer if there are more.

**Comment by sunderme** [comment]
without an example which I can test, this information is totally useless.
Caching here works well and loading is significantly faster with a release build.
Apart from that, the plan is to rework txs load/session restore code, but this will take some time/releases.
