### ISSUE TITLE
preview compile error on \textcolor and \color

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3193]
### Environment
- TeXstudio: 4.5.2, and current master
- Qt: 6.5.1
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
pdflatex should end with no error

### Actual behavior
pdflatex ends with error

### How to reproduce
I use the following document that compiles fine with pdflatex:
```latex
\documentclass[10pt,a5paper]{article}
\usepackage[T1]{fontenc}
\usepackage{xcolor}
\begin{document}
%
\textcolor{black}{text}
%
\end{document}
```
When the mouse pointer hovers over the word "black" a pdflatex process is started in background, ends normal, and a tooltip shows a preview (black square). The code from the generated document is:
```latex
\documentclass[10pt,a5paper]{article}
\usepackage[T1]{fontenc}
\usepackage{xcolor}
\usepackage[active,tightpage]{preview}
\usepackage{varwidth}
\AtBeginDocument{\begin{preview}\begin{varwidth}{\linewidth}}
\AtEndDocument{\end{varwidth}\end{preview}}
\pagestyle{empty}
\begin{document}
\noindent{\color{black} \rule{1cm}{1cm} }
\end{document}
```
But when the mouse hovers further to the left over the left brace, then the started pdflatex process ends with error. The code from the generated document now is:
```latex
\documentclass[10pt,a5paper]{article}
\usepackage[T1]{fontenc}
\usepackage{xcolor}
\usepackage[active,tightpage]{preview}
\usepackage{varwidth}
\AtBeginDocument{\begin{preview}\begin{varwidth}{\linewidth}}
\AtEndDocument{\end{varwidth}\end{preview}}
\pagestyle{empty}
\begin{document}
\noindent{\color\textcolor \rule{1cm}{1cm} }
\end{document}
```
Latex message:
```
! Package xcolor Error: Undefined color `\textcolor '.

See the xcolor package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.10 \noindent{\color\textcolor
                                \rule{1cm}{1cm} }
```
Same happens when the original document has the text \color{black}{text}. Generated code changes to `\color\color`.

I could find following lines:

latexcompleter.cpp
`text = QString("{\\color{%1} \\rule{1cm}{1cm}}").arg(listModel->words[index.row()].word);`

latexeditorview.cpp
`text = QString("\\noindent{\\color%1 \\rule{1cm}{1cm} }").arg(tk.getText());`

I hope this helps with the investigation.

**Comment by octaeder** [comment]
Btw: Preview of colors can't be disabled. Since they are more or less some kind of an image, I would like to make this preview depend on Adv. Editor option _Show image tooltip on image files_. What do you think?

l. 2707 in latexeditorview.cpp `if (config->imageToolTip && tk.subtype == Token::color) {`

**Comment by sunderme** [comment]
> Btw: Preview of colors can't be disabled. Since they are more or less some kind of an image, I would like to make this preview depend on Adv. Editor option _Show image tooltip on image files_. What do you think?
> 
> l. 2707 in latexeditorview.cpp `if (config->imageToolTip && tk.subtype == Token::color) {`

sounds okay.

**Comment by octaeder** [comment]
there is similar code in latexcompleter. cpp, l. 2016
```
	if (config->tooltipPreview && forcedSpecialOption && workingDir == "%color") {
		QToolTip::hideText();
		QString text;
		text = QString("{\\color{%1} \\rule{1cm}{1cm}}").arg(listModel->words[index.row()].word);
		emit showPreview(text);
		return;
	}
```
This currently depends on tooltipPreview (i.e. option _Show preview as tooltip on formulas in editor_). I probably should change this also, but I can't figure out, when this code is executed (code example?).

**Comment by octaeder** [comment]
Now found it:  For ex. when completing word red with `Ctrl`+`Space`.

**Comment by sunderme** [comment]
> there is similar code in latexcompleter. cpp, l. 2016
> 
> ```
> 	if (config->tooltipPreview && forcedSpecialOption && workingDir == "%color") {
> 		QToolTip::hideText();
> 		QString text;
> 		text = QString("{\\color{%1} \\rule{1cm}{1cm}}").arg(listModel->words[index.row()].word);
> 		emit showPreview(text);
> 		return;
> 	}
> ```
> 


why should this be changed ?

**Comment by octaeder** [comment]
Because it depends on option _Show preview as tooltip on formulas in editor_, not on _Show image tooltip on image files_. Or nor?

**Comment by octaeder** [comment]
I think disabling preview of colors should not disable preview of formulas.

**Comment by sunderme** [comment]
this is a misunderstanding, there are two variables `tooltipPreview`, one in completerConfig, one in editorConfig.
The latexcompleter part should therefore not be touched.

**Comment by octaeder** [comment]
so this is a completer configuration that can't be changed by the config dialog.

**Comment by sunderme** [comment]
it is changed by the config dialog, but with a different checkbox.

**Comment by octaeder** [comment]
![image](https://github.com/texstudio-org/texstudio/assets/102688820/2336f809-d2b4-4aa5-aab6-3eb522f1b909)

**Comment by octaeder** [comment]
thanks
