### ISSUE TITLE
TOC sidebar updated with customized \input command

### ISSUE THREAD

**Issue by graouilly987** [texstudio-org/texstudio#3194]
### Environment
- TeXstudio: 4.3.1
- OS: Windows 11
- TeX distribution: miktex,

### Description
In order to automate the generation of some LaTeX codes, I created customized `\input` command :
`\newcommand{\inputfromvoldir}[1]{\input{./\thevolumedir/#1}}`
where` \thevolumedir` is defined in another tex file:
`\newcommand{\thevolumename}{toto}`

The command `\inputfromvoldir{aerodyn}` is then correctly interpreted as `\input{./toto/aerodyn}` .

The compilation works nice but this customized input command is not recognized in the TexStudio TOC sidebar.
I saw on few posts that .cwl is the way to tell TexStudio about new commands (http://svn.code.sf.net/p/texstudio/code/trunk/utilities/usermanual_en.html#CWLDESCRIPTION) but I was not able to make it work in the case above. My attempts in the cwl were:
```
\ChapterNoEpigraph{chap}#L1
\ChapterEpigraph{chap}{epig}{author}#L1
\inputcommon{file}#i file
```
The cwl is well parsed and recognized by TexStudio since the two first commands are correctly identified as chapters in the structure sidebar.

Is there a way to make TexStudio properly recognize such commands?

**Comment by sunderme** [comment]
this is impossible, especially since the path is defined via a tex command.
