### ISSUE TITLE
Scale image tooltip preview with respect to resolution, and optionally load larger image files

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3197]
### Describe the feature and the current behavior/state
When Adv. Editor option _Show image tooltip on image files_ is checked then txs shows a preview of image files in a tooltip when the mouse hovers over the file name. To avoid large tooltips, the preview width is limited to 400pix by scaling down images wider than this. This process has two limitations: 

1. By default Qt doesn't load large image files (limit approx. 30MiPix) and the user can't change this value.
2. Print size of the image (say in cm) in the tooltip depends on the screen's dpi value because the image's dpi info is ignored (and the 400pix limit).

I would like to add an option so the user can change the 30MiPix limit, and would scale preview images with respect to dpi ratio. What do you think?

### Example:
A typical way to include images is the following:
```latex
\documentclass[10pt,a5paper]{article}
\usepackage{graphicx}
\begin{document}
\includegraphics{image}
\end{document}
```
Assume image is of type png, has 8'504pix width and 4'783pix height (38.79MiPix, 16:9), and has 2'400dpi (a typical value for book printing). Thus it would be printed with 9cm x 5.1cm (calculation of width: 8'504pix/2'400dpi*2.54cm/in = 9cm). Currently one would see no image:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/a53a376f-e8bb-4b64-9d20-264a90ccc2d3)
(zoomed 2x)

The tooltip shows part of the frame that surrounds the image and a shadow for the frame, but the image is not loaded (by 1st limitation).

To circumvent 1st limitation, we reduce the number of image pixels by a factor of 1/16 to 2.54MiPix. For this scale width, height and dpi by a factor of 1/4. Hence the print size doesn't change. The image now has a width of 2'126pix, is loaded,  and is then scaled to a width of 400pix (limited tooltip size):

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/a1e48766-2f57-4b84-ae76-ecff7df3c336)

But a short calculation shows that the image displays larger on a screen with 94dpi than it would be printed: 400pix/(94pix/in)*2.54cm/in = 10.8cm. The correct number of pixels would be 9cm/(2.54cm/in)*94pix/in = 333pix. So the image is displayed about 20% larger. In fact it can happen that images are displayed with the same size even so they don't print in the same size, or vice versa.

### Who will benefit with this feature?
Anyone who uses image preview.

### Any Other info
void QImageReader::setAllocationLimit is available since Qt 6.0.

**Comment by octaeder** [comment]
Added spinBox looks like this:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/6e556b7d-efc1-4263-8ada-21124b7e7bd5)

Tooltip could be:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/d9e38ebb-ce4b-4838-a1a5-c103287c0895)

Large image now is loaded:

**Comment by octaeder** [comment]
I don't like that users fiddle around in the ini file. Moreover such "hidden" options are not documented, so the user has even no idea that there is an option that could solve his problem. In best case she has to sign in at github and opens an issue (as the missing image looks like a  program error). Then we have to explain where to find and how to change the ini file (and I will not remember the option name). Otherwise we just make a screenshot of the option. This makes it quite easy for the user to change it. Said this, the option is obviously not needed every day. But this is the case for many advanced options. 

When you can add a description in the manual about the option (the image tooltip option can be found in the manual) and how to change it, then skipping the gui element should be ok.

**Comment by octaeder** [comment]
Meanwhile I started testing a second branch with a gui free solution... Hope you think about my last comment.

**Comment by sunderme** [comment]
Yes, the option can be mentioned in the manual or wiki

**Comment by octaeder** [comment]
I didn't get mails from your edits, did I miss something?

**Comment by octaeder** [comment]
since pull request was not accepted I close the case
