### ISSUE TITLE
Problem with qt_hu.qm

### ISSUE THREAD

**Issue by hair-splitter** [texstudio-org/texstudio#3198]
### Environment
- TeXstudio 4.5.2 (Qt: 6.5.0) and TeXstudio 4.6.0 (git 4.6.0beta2) (Qt: 6.5.1)
- OS: Windows10
- TeX distribution: TeX Live 2023

### Actual behavior

I use TeXstudio in Hungarian. There are several message windows in which the button labels are not translated into Hungarian. For example, when I close the TeXstudio with an unsaved document, the "Save", "Discard", "Cancel" buttons of message window appear in English. 

I think the problem is with the `qt_hu.qm` file. **If I replace this with the `qt_hu.qm` file from the Texmaker, then the problem is fixed.** 

I experienced similar problems with other languages.

**Comment by muzimuzhi** [comment]
Would you like to contribute to Hungarian  translation for TeXstudio at https://explore.transifex.com/texstudio/texstudio/ ? See also wiki page https://github.com/texstudio-org/texstudio/wiki/Translating.

**Comment by hair-splitter** [comment]
Only `texstudio_hu.qm` can be edited there, not `qt_hu.qm`!

**Comment by muzimuzhi** [comment]
Sorry, my bad.

It seems `qt_hu.qm` is provided by Qt, which is maintained in https://code.qt.io/cgit/qt/qttranslations.git/ (github mirror https://github.com/qt/qttranslations) and linked to https://explore.transifex.com/qtproject/qttranslations/ as I infer.  That `qt/qttranslations` repo provides TS files, which will transform into QM files here in TeXstudio repo.

Related links
- Creating translation files https://doc.qt.io/qt-6/linguist-creating-ts-files.html
- Localizing Applications https://doc.qt.io/qt-6/localization.html

**Comment by hair-splitter** [comment]
I downloded this file:
https://github.com/qt/qttranslations/blob/dev/translations/qtbase_hu.ts

I converted qtbase_hu.ts to qtbase_hu.qm with lrelease.exe.

I renamed qtbase_hu.qm to qt_hu.qm

Finally I replaced it with the original one in TeXstudio.

The result: Every button labels is translated into Hungarian!

It follows for me that the file used in TeXstudio is not suitable.

**Comment by hair-splitter** [comment]
Unfortunately, the correction is not yet correct, because the new `qt_*.qm` does not contain language elements, it only loads the files `qtbase_*.qm` and `qtmultimedia_*.qm`.

In my opinion, it would be enough to use `qtbase_*.qm` instead of `qt_*.qm`.
