### ISSUE TITLE
CHangeLog  windows log

### ISSUE THREAD

**Issue by dallouche** [texstudio-org/texstudio#3200]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 
TeXstudio 4.6.0 (git 0.0.0++)
Utilise Qt version 5.12.8, compilé avec Qt 5.12.8 R

### Expected behavior

line return after each new commit 

### Actual behavior

![image](https://github.com/texstudio-org/texstudio/assets/13035682/0f198b84-bc71-4be5-b94d-af8274c1103c)
### How to reproduce
ubuntu release

**Comment by sunderme** [comment]
won't fix
