### ISSUE TITLE
Can't type unicode Vietnamese characters (macos)

### ISSUE THREAD

**Issue by nguyendinhsontg** [texstudio-org/texstudio#3203]
When typing Vietnamese unicode characters texstudio displays wrong.
For example:
Type: vaayj correct: vậy  texstudio: v
Type: nhaapj correct: nhập  texstudio: nh

**Comment by sunderme** [comment]
there is no mention of the actual input method
osx offers 5 for vietnamese, I have tried 2, none produced a result as described in osx notes.
Please be more precise and complete. Mind you, you are talking to people who are not using these input methods at all.

**Comment by sunderme** [comment]
no clarification
