### ISSUE TITLE
Move and magnify cursors are stretched/pixelated on Mac for Colibri icon theme

### ISSUE THREAD

**Issue by somelinguist** [texstudio-org/texstudio#3210]
### Environment
- TeXstudio: 4.6.0rc1
- Qt: 6.5.1 R
- OS: macOS 13.4
- TeX distribution: TeX Live 2022

When using the Colibri icon them on Mac, the cursors for move and magnify modes in the internal PDF preview are stretched and distorted. I think it's been this way ever since the Colibri theme was introduced. The corresponding icons for both in the toolbar render correctly. See the screenshots below (the colors are a bit off only because of capturing a screenshot).

<img width="221" alt="Screenshot 2023-07-17 at 1 55 39 PM" src="https://github.com/texstudio-org/texstudio/assets/3488298/dbfa9675-1350-4edd-9dff-b042b7117837">

<img width="159" alt="Screenshot 2023-07-17 at 1 59 51 PM" src="https://github.com/texstudio-org/texstudio/assets/3488298/70ef5a25-319d-4dc9-8f36-dc35b523d2c1">

They appear the same on the built-in display (16-in MacBook Pro 2019) and external displays, regardless of the OS display setting for scaling.

I haven't noticed any issues with other cursors or text rendering on Mac with the Colibri theme.

I installed one of the TexStudio betas on an Ubuntu (22.04) machine recently and was surprised to see that the those two cursors actually rendered pretty well on it.

Is there a TexStudio setting I could try changing, or can something else be done? Thanks!

**Comment by sunderme** [comment]
should be fixed
