### ISSUE TITLE
Zooming out as far as possible in the Messages window hangs TeXstudio

### ISSUE THREAD

**Issue by schicho** [texstudio-org/texstudio#3212]
### What is it about?

You can zoom in the Messages window using CTRL + scrolling.
There seems to be an optical limit on how small the text can get, but it quite quickly hangs TeXstudio and you need to force quit.

### Environment
- TeXstudio: TeXstudio 4.5.2 (0.0.0++) installed from https://launchpad.net/~sunderme/+archive/ubuntu/texstudio
- Qt: Using Qt Version 5.12.8, compiled with Qt 5.12.8 R
- OS: Ubuntu 20.04.6 LTS x86_64 
- TeX distribution: texlive 2019.20200218-1 

### Expected behavior

There is a zoom limit for how small one can make the text.

### Actual behavior

You can zoom out and the text gets smaller, but if you scroll to far it hangs the whole program.
I don't have a screen recording tool installed. Reproduction of the issue should be easy.

### How to reproduce

1. compile some document
2. zoom out in the message window
3. texstudio hangs

**Comment by octaeder** [comment]
This seems not to happen with Win10 (4.5.2 and almost current dev build). I started an inline preview and zoomed as far as possible in the message panel, but no crash.

![image](https://github.com/texstudio-org/texstudio/assets/102688820/5f9e389d-a008-4f46-a162-f04599df9863)

Could it depend on some config settings?

**Comment by schicho** [comment]
I have to correct, it does not crash, it only hangs. Basically having to force quit when I do that.
Could be a Linux thing. It does not depend on the font used. Zooming out to max level hangs it.
