### ISSUE TITLE
now much too large pfd viewer cursor

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3215]
![image](https://github.com/texstudio-org/texstudio/assets/102688820/9c91302a-ffae-49c4-b079-572d8438884d)

one or both of:
https://github.com/texstudio-org/texstudio/commit/44e434354402d2c2f0304f867e7fad7807c3c81e
https://github.com/texstudio-org/texstudio/commit/6969a7e9811132c98d9943143cc78d362aa0b521

**Comment by octaeder** [comment]
magnifier.svgz and focusedhand.svg are drawn on a plane of size 128x128, while zoom-in-magnifier.svg (also zoom-out-magn.) uses 32x32 (icon theme Oxygen Classic). Loading these images will result in a pixmap/cursor of the respective size.

![image](https://github.com/texstudio-org/texstudio/assets/102688820/71277cf3-db1b-4260-8910-db76f14e8181)

So the original code scaled all the images to 32x32. This also has to be done because other icon themes may use different icon sizes.

**Comment by sunderme** [comment]
this should be fixed

**Comment by octaeder** [comment]
yes, indeed. thanks
