### ISSUE TITLE
PDF page number text box is very thin

### ISSUE THREAD

**Issue by TimeTravelPenguin** [texstudio-org/texstudio#3222]
### Environment
- TeXstudio: 4.5.2
- Qt: 6.5.0
- OS: Windows 11
- TeX distribution: miktex

### Problem
The PDF viewer's page number input box is very thin as shown in the screenshot

![image](https://github.com/texstudio-org/texstudio/assets/35803538/914029a3-bcb9-42d2-a008-c7059b039bf4)

GUI scaling doesn't seem to fix the issue, and I cannot find any options that may resolve this issue.

**Comment by muzimuzhi** [comment]
Is this behavior specific to the dark theme in use? Then maybe related to #2186.

**Comment by TimeTravelPenguin** [comment]
I checked and it only occurs with the styles "Adwaita (txs)" and "Adwaita Dark (txs)". Neither the colour scheme nor the icon theme changes this. So, yes, that issue appears to be the same one that I am dealing with.

**Comment by octaeder** [comment]
@TimeTravelPenguin Should be fixed, s. #2186
