### ISSUE TITLE
Release.key expired 

### ISSUE THREAD

**Issue by mlmateos** [texstudio-org/texstudio#3223]
Trying to install TeXStudio in Debian 12

From:
https://software.opensuse.org/download/package?project=home:jsundermeyer&package=texstudio

Trying to:

Add repository and install manually
For Debian 12 run the following:

echo 'deb http://download.opensuse.org/repositories/home:/jsundermeyer/Debian_12/ /' | sudo tee /etc/apt/sources.list.d/home:jsundermeyer.list
curl -fsSL https://download.opensuse.org/repositories/home:jsundermeyer/Debian_12/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_jsundermeyer.gpg > /dev/null
sudo apt update
sudo apt install texstudio

---

After:
sudo apt update

Get a Warning about signature home_jsundermeyer.gpg is invalid.

**Comment by sunderme** [comment]
looks fine on opensuse webpage: https://build.opensuse.org/projects/home:jsundermeyer/signing_keys

**Comment by sunderme** [comment]
obs handles the signing, key data looks fine.
