### ISSUE TITLE
Extra temp files under C:

### ISSUE THREAD

**Issue by TLCFEM** [texstudio-org/texstudio#3225]
https://github.com/texstudio-org/texstudio/blob/3a0df2677b4c475892b0a3abdcfb218f3f55e75a/src/latexdocument.cpp#L1892

v 4.6.0 portable on windows.

Extra folder created under C:, which I believe shall be placed somewhere else.

<img width="677" alt="explorer_cGL6q6zvjX" src="https://github.com/texstudio-org/texstudio/assets/19872523/a543d2e2-ca2f-4674-9b62-53c0ddd7396e">

**Comment by sunderme** [comment]
ugly bug, thanks
