### ISSUE TITLE
TeXstudio portable freezes

### ISSUE THREAD

**Issue by hair-splitter** [texstudio-org/texstudio#3228]
### Environment
- TeXstudio: 4.6.1 portable
- Qt: 6.5.1 R
- OS: Windows 10
- TeX distribution: TeX Live 2023

I have a large document consisting of many tex files, which I load into the main file with the `\include` command. The document contains many cross-references. When I want to load the main file into the TeXstudio 4.6.1 portable (with default settings), the TeXstudio freezes.

The problem disappears if I turn off the 
Options / Configure TeXstudio / Editor / Automatically load included files
function.

The last "Dev Builds" that didn't have this bug:
CD #3236
https://github.com/texstudio-org/texstudio/actions/runs/5432369676
texstudio-win-qt6-zip 
https://github.com/texstudio-org/texstudio/suites/14000393756/artifacts/781193048

The "CD #3237" already produces this bug.

**Comment by ThexXTURBOXx** [comment]
Actually, I have exactly the same problem, but with the _installed_ version. I can also provide more information if necessary

**Comment by sunderme** [comment]
Have you tried to wait it out ? 
Reloading should be much faster, once txs can store caching information ...

Otherwise I would need a test case.

**Comment by ThexXTURBOXx** [comment]
I tried to wait it out and after around 3 minutes it just crashed. I can provide you with a test case, but it would be my (yet unpublished) Master's thesis, so I don't feel comfortable sharing everything publicly here.
Can I send it to you via email?

**Comment by hair-splitter** [comment]
The cache files are not created because TXS crashes before that.

**Comment by sunderme** [comment]
freeze is not necessarily a crash ... so, it crashes with a backtrace ?

**Comment by sunderme** [comment]
> I tried to wait it out and after around 3 minutes it just crashed. I can provide you with a test case, but it would be my (yet unpublished) Master's thesis, so I don't feel comfortable sharing everything publicly here. Can I send it to you via email?

yes, sunderme@gmx.de

**Comment by hair-splitter** [comment]
> freeze is not necessarily a crash ... so, it crashes with a backtrace ?

You're right, I worded it wrong. It freezes and doesn't crash.

**Comment by ThexXTURBOXx** [comment]
@sunderme Thank you very much, sent!
My TeXStudio _crashed_ after some time. How can I obtain the backtrace? Is there some log folder?

**Comment by sunderme** [comment]
a dialog should pop-up

**Comment by hair-splitter** [comment]
At first it seems to freeze, but after about 10 minutes it crashes with the following message:
![message](https://github.com/texstudio-org/texstudio/assets/31892631/598985ac-2461-42d8-9413-04c066d4b74f)

texstudio_backtrace1.txt:
unknown at 0 (TXS-Version 4.6.1 R )
[bt] 00007ff7526b3359  q+3478829
[bt] 00007ff7526b256b  q+3475263
[bt] 00007ff7525cc253  q+2532391

**Comment by sunderme** [comment]
I have just released 4.6.2rc1 which should solve the issue at cost of not removing marked errors at certain circumstances. 
I need to find another solution for that and the given test case may help.

**Comment by sunderme** [comment]
I have published 4.6.2 to get rid of the crash at cost of the other bug.
Please confirm that it helps.

**Comment by ThexXTURBOXx** [comment]
Tested it, 4.6.2 fixes at least this issue. Thank you very much!

**Comment by hair-splitter** [comment]
The problem seems to have been fixed. Thanks.
