### ISSUE TITLE
Internal PDF viewer not compiled?

### ISSUE THREAD

**Issue by cilia** [texstudio-org/texstudio#3229]
### Environment
- TeXstudio: 4.6.2
- Qt: qt5 5.15.10
- OS: macOS 13.4.1
- TeX distribution: MacTex 2023

### Description
Compiled TeXstudio 4.6.2 from source as below:

```
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH="$(brew --prefix)/Cellar/qt@5/5.15.10/lib/cmake" ..
cmake --build . --parallel
```

Since `homebrew` broke `poppler` without including `qt6`, I'm using `poppler-qt5` instead. Not ideal but feasible for now.

Binary was generated and app launched. However, the internal pdf view apparently was not compiled. See screenshot attached.

![Screenshot 2023-07-31 at 3 23 55 PM](https://github.com/texstudio-org/texstudio/assets/1176473/39c5c3e0-f39d-4f11-982b-7ce9bf6cf823)

Don't think I had this issue before using the same compilation process above, anything has changed?

**Comment by cilia** [comment]
I guess I've found the cause, when doing `cmake -DCMAKE_PREFIX_PATH="$(brew --prefix)/Cellar/qt@5/5.15.10/lib/cmake" ..`

One of the outputs says: `Poppler not found, internal pdf previewer disabled.`

So I tried the following:

```
mkdir build
cd build
export LDFLAGS="-L/opt/homebrew/Cellar/poppler-qt5/23.05.0/lib"
export CPPFLAGS="-I/opt/homebrew/Cellar/poppler-qt5/23.05.0/include"
export PKG_CONFIG_PATH="/opt/homebrew/Cellar/poppler-qt5/23.05.0/lib/pkgconfig"
cmake -DCMAKE_PREFIX_PATH="/opt/homebrew/Cellar/qt@5/5.15.10/lib/cmake" ..
cmake --build . --parallel
```

But still `Poppler not found, internal pdf previewer disabled.`, and obviously the compiled app does not have internal PDF viewer included.

**Comment by sunderme** [comment]
Since homebrew deliberately broke support for txs, I don't give support using it.
Local build of poppler works well and avoids restrictions from homebrew.

**Comment by abhi-jha** [comment]
Hey @cilia. I just had this exact same issue and I have solved it with a lot of time spent on installing dependencies.

First check if have qt installed. Note that poppler DOES NOT get insatlled automatically with qt6. So you need to build poppler from source. 

Build poppler :

1. Download source : https://poppler.freedesktop.org/
2. brew reinstall pygobject3 gtk+3 boost gpgme pdftotext quazip qt
3. mkdir build
4. cd build
5. cmake ..
6. make
7. make install

Now build tex studio, it should find poppler.

1. Download source
2. mkdir build
3. cd build
4. CMAKE_PREFIX_PATH=/opt/homebrew/Cellar/qt cmake ..
5. make -j2
6. Run the binary   :         ./texstudio.app/Contents/MacOS/texstudio

Let me know if something is still complaining as I just went through this whole process.

**Comment by cilia** [comment]
@abhi-jha Thanks for the detailed instructions. Yes, `qt6` does not come with poppler anymore as mentioned by @sunderme, the only reservation I have for installing via `cmake` is that there seems no clean/officially supported way to uninstall a package
