### ISSUE TITLE
Double cursor

### ISSUE THREAD

**Issue by eldiep** [texstudio-org/texstudio#323]
Sometimes there are two cursors in different lines. If I type some text it is written in both lines.
### Environment
- TeXstudio: 2.12.6 (hg 6632:7777b2b8a906)
Nutze Qt-Version 5.9.1, kompiliert mit Qt 5.9.1 R
- TeXstudio: 
- Qt: 5.9.1
- OS: Windows 7
- TeX distribution: miktex

### Expected behavior
It only should write text to the line I set the cursors.

### Actual behavior
There are at least two cursors in different lines. The text is written to both cursor-positions.  After a restart of texstudio the bug disappears.

### How to reproduce
Don't know for shure. It appears randomly.

**Comment by sunderme** [comment]
if you leave the cursor on an env-name (e.g. \begin{|env} ... \end{env} ), then txs generates a mirror-cursor which allows to change both "env" entries simultaneously. If you leave the "env" area (also marked with colored boxes), only single cursor is active.

With ctrl+left mouse button, you can generate a mirror cursor directly which allows putting in text on several lines. A mouse-click somewhere else in the text to move the cursor, terminates this mode.
