### ISSUE TITLE
Problem Highlighting Bibliography Id

### ISSUE THREAD

**Issue by FrederikWolter** [texstudio-org/texstudio#3233]
### Environment
- TeXstudio: 4.6.2 (fresh upgrade from 4.5.1)
- Qt: 6.5.1
- OS: Windows 10
- TeX: miktex

### Actual behavior
After upgrading to Version 4.6.2 all my citations using `\autocite` are not correctly highlighted:
![image](https://github.com/texstudio-org/texstudio/assets/35914049/d9303b17-9108-4603-8367-2f5e44d42b1f)
As you see the _bibid_ is not highlighted. On the contrary i even get an error for using an underscore outside of a formula in this case.

Restarting TexStudio, reopening the files and creating the PDF file do not help. However, when creating the PDF file, the citations in the output PDF file are set correctly.

It **fixes** the highlighting if you just make any change to the line where the `\autocite` is located in. But this does not seem very convenient in my opinion.
![image](https://github.com/texstudio-org/texstudio/assets/35914049/f4bbb55c-b84a-4c68-b61c-8ca6b711e4cf)

**HOWEVER:**
citations of multiple sources with `\cites` or `\autocites` are not correctly highlighting whatever i do:
![image](https://github.com/texstudio-org/texstudio/assets/35914049/151b19f7-7b7a-4899-8b34-15f74b298e69)
No matter the combination of sources and optional arguments - after the second bibid nothing is highlighted anymore.

### Expected behavior
Correct highlighting of `\autocite` and `\autocites`, with the corresponding suppression of (spell) errors in bibids.

### How to reproduce
Opening a Latex project created in another TexStudio version with TexStudio for the first time.
Or opening any Latex project containing `\(auto)cites` with more than 2 bibids.

**Comment by sunderme** [comment]
please try txs 4.6.3beta1 (currently building)

alternatively, activate biblatex.cwl in option/completion

**Comment by FrederikWolter** [comment]
> please try txs 4.6.3beta1 (currently building)
> 
> alternatively, activate biblatex.cwl in option/completion

@sunderme thanks for your quick reply. 
activating the `biblatex.cwl` helped with that problem.
In the mean time i noticed that the same issue appears with e.g. `\includegraphics`. 

Do i understand that correctly that this is due to a current bug with the auto detection of completion lists you are already fixing in 4.6.3beta1?

**Comment by sunderme** [comment]
yes, can you try https://github.com/texstudio-org/texstudio/releases/tag/4.6.3beta1 with deactivated biblatex.cwl ?

**Comment by colichri** [comment]
Yeah, I noticed the same issue today and just by upgrading to Version 4.6.3 beta 1 the issue seems to be solved at first glance.
