### ISSUE TITLE
TeXstudio editor field not considered an 'input window' on Linux

### ISSUE THREAD

**Issue by aaannestad** [texstudio-org/texstudio#3237]
The editor field (i.e. the bit where you actually write your document) in TeXstudio does not seem to count as an 'input window' in at least my Linux situation. The result is that I cannot use any input method editor while writing in TeXstudio - I have to switch to some other window, type there, and copypaste the result back in. This is extremely inconvenient!

### Environment
- TeXstudio: 4.5.2
- Qt: 6.5.2
- OS: Manjaro 6.1.41
- TeX distribution: TeXLive

### Expected behavior
I can switch to an input method editor and type e.g. Japanese directly into my document in TeXstudio

### Actual behavior
Attempting to switch input methods does nothing, and the taskbar icon for the IME reports 'no input window'; I can only type directly from my basic keyboard layout

### How to reproduce
Install TeXstudio from the Manjaro repository
Ensure you have fcitx installed with at least one input method editor beyond your basic keyboard
Open a new document in TeXstudio
Attempt to switch input methods with fcitx

**Comment by sunderme** [comment]
seems to be a qt6 issue. txs qt5 works. Even qt6 examples don't work with pinyin.

**Comment by sunderme** [comment]
I have just checked in a virtual machine. fcitx-qt6 needs to be installed and then texstudio works fine with google pinyin.

**Comment by aaannestad** [comment]
@sunderme Does that require a reboot as well? Does it work without fcitx5?

**Comment by sunderme** [comment]
i got it working with fcitx4

**Comment by aaannestad** [comment]
@sunderme I'm just using the direct `fcitx` package from Manjaro's repository, and have also installed `fcitx-qt6`. Do I need to restart fcitx somehow to get it to take effect?

**Comment by sunderme** [comment]
I just tried.it once , so I can't say.

**Comment by sunderme** [comment]
from my point of view, this is resolved. txs is not to blame.
