### ISSUE TITLE
Texstudio main window not starting up on multi screen setup

### ISSUE THREAD

**Issue by oystersandwich** [texstudio-org/texstudio#3239]
_(Sorry, if I reopen something that is already fixed. I searched but found no open issue for this)_

### Environment
- TeXstudio: 4.6.2 (stable), (updated after finding this in 4.3.2)
- Qt: 6.5.1
- OS: Win10
- TeX distribution: miktex

### Expected behavior
Main window starts up when desktop icon is clicked.

### Actual behavior
Title screen shows. When everything is loaded in the background, it disappears. But the main window is not showing up (hangs, icon in taskbar lights up).

### How to reproduce
Place the main window on a connected second screen (maybe second screen has to be configured to be to the left of the first one). Close main window on second screen.
Disconnect second screen. Start texstudio again.

### Problem analysis
Main window tries to start on second screen, which is not present anymore. Texstudio should then start on first display, but that fails, because it wants to start where it was closed (for convinience reasons, I guess).

Fortunately, I was able to traced the problem down to the config file `texstudio.ini`.
I had the second screen placed "left" of the first one. That results in a negative x-position (possibly a platform-dependent problem) of the main window.
**Removing** the following line in `texstudio.ini` made starting texstudio possible again:
```
Geometries\MainwindowX=-3037
```

I tried but found no other way to force the window to start up on first screen, when it hangs up, than having to go into config files (besides reconnecting the second screen, which is implossible with my laptop when not at home).

Unsure how this should be handled in code, but it should become fail-safe.

**Comment by sunderme** [comment]
should be fixed
