### ISSUE TITLE
bibtex.exe: unrecognized option `--include-directory= . . . 

### ISSUE THREAD

**Issue by cohensm52** [texstudio-org/texstudio#3242]
I'm running TexStudio with TexLive on Windows 10. I just recently switched over from MikTeX because the latter somehow got corrupted and there appeared to be no way to recover from it (I apparently cannot completely remove MikTeX because of the corruption, which means, apparently, that I cannot reinstall it). Anyway, TexLive is much faster, which is a good thing. However, the following problem has arisen with bibtex. When I run "build and view", I get this error message:
bibtex.exe: unrecognized option --include-directory=C:\Users\cohen5\Documents\Research' Try bibtex --help' for more information.
Process exited with error(s)

As such, I cannot add any new citations to my bibliography. Does anyone know how to fix this issue?
Thanks much.

P.S. The entire string of messages I get when I do "build and view" is below, in case this helps:
Process started: pdflatex.exe -synctex=1 -interaction=nonstopmode "AsympLOCCQChannels".tex
Process exited normally
Process started: bibtex.exe --include-directory="C:\Users\cohen5\Documents\Research" "AsympLOCCQChannels"

bibtex.exe: unrecognized option --include-directory=C:\Users\cohen5\Documents\Research' Try bibtex --help' for more information.
Process exited with error(s)

Process started: pdflatex.exe -synctex=1 -interaction=nonstopmode "AsympLOCCQChannels".tex
Process exited normally
Process started: pdflatex.exe -synctex=1 -interaction=nonstopmode "AsympLOCCQChannels".tex
Process exited normally

### Environment
- TeXstudio: 4.6.2
- Qt: Using Qt Version 6.5.1, compiled with Qt 6.5.1 R
- OS: Windows 10
- TeX distribution: texlive

### Actual behavior
Here is how I have Build configured in TXS (advanced options not shown):
![image](https://github.com/texstudio-org/texstudio/assets/79482316/bdccf048-1d91-488c-be23-1bc5f01a87ca)

**Comment by cohensm52** [comment]
I did a google search and found this possibly similar issue: https://github.com/Hannah-Sten/TeXiFy-IDEA/issues/882

**Comment by cohensm52** [comment]
I did a google search and found these possibly similar issues: https://github.com/Hannah-Sten/TeXiFy-IDEA/issues/257; https://github.com/Hannah-Sten/TeXiFy-IDEA/issues/882

**Comment by cohensm52** [comment]
I've found something that seems like it should be helpful but maybe not. Anyone know?
I found it here: https://tex.stackexchange.com/questions/70425/xelatex-problem-with-aux-directory-and-include-directory-options-on-texlive
This (from 12 years ago) says TexLive doesn't have -include-directory, but only -output-directory. So I tried putting this into my txs configuration under commands, bibtex as: bibtex.exe -output-directory=<path> %
This didn't help. So I tried restoring it to default, which is simply: bibtex.exe
That didn't work either. I also tried bibtex.exe -outdir=<path>, which I saw here: https://github.com/James-Yu/LaTeX-Workshop/issues/3023, but that also didn't work.

Now I have no bibliography at all. Uggh.

What should the command be for bibtex in txs configuration when using texlive?

**Comment by sunderme** [comment]
just use the default command settings, copy bibliography into your work directory.

**Comment by muzimuzhi** [comment]
> So I tried restoring it to default, which is simply: bibtex.exe

On macOS the default is `bibtex %.aux`. According to the source code, I'm guessing on Win it's `bibtex.exe %`.

https://github.com/texstudio-org/texstudio/blob/f1a6ba1ec73e1e9de76d4be3a79f9e2068a0b649/src/buildmanager.cpp#L15-L23
https://github.com/texstudio-org/texstudio/blob/f1a6ba1ec73e1e9de76d4be3a79f9e2068a0b649/src/buildmanager.cpp#L345

**Comment by cohensm52** [comment]
Fabulous! @sunderme's suggestion works. Thank you so much.
I'm not sure how to implement @muzimuzhi's suggestion, but thank you, as well.

**Comment by cohensm52** [comment]
Actually, I found a better way, which doesn't require placing the bibliography in every new working directory. Just use the full path in the latex file when calling \bibliography. That is, for example, \bibliography{C:/Users/cohen5/Documents/Research/Qrefs} instead of \bibliography{Qrefs}. I had tried this before but with backslashes (\) in the path, but I just found a post explaining that latex always uses forward slashes (/).

**Comment by muzimuzhi** [comment]
> [...] That is, for example, \bibliography{C:/Users/cohen5/Documents/Research/Qrefs} instead of \bibliography{Qrefs}.

If the path to all bib files are (relatively) static, you can move or link them to `$TEXMFHOME/bibtex`, in which the value of `TEXMFHOME` is given by running `kpsewhich --var-value TEXMFHOME`.  You can also add your path to kpathsea variable [`BIBINPUTS`](https://github.com/TeX-Live/texlive-source/blob/989c4229c9b699cf4c89789e2245b06e4c92a18f/texk/kpathsea/texmf.cnf#L364-L366), by running
```
tlmgr conf texmf BIBINPUTS '$TEXMFDOTDIR;$TEXMF/bibtex/bib//;<your path>'
```
