### ISSUE TITLE
Main screen recognition error

### ISSUE THREAD

**Issue by WJD1005** [texstudio-org/texstudio#3252]
### Environment
- TeXstudio: 4.6.3 
- Qt: 6.5.2 
- OS: Windows10 
- TeX distribution: texlive

### Expected behavior
When I have two screens and set Screen 1 as the main screen, it should run on Screen 1 (such as open a window or drop-down menu).

### Actual behavior

Actually, it will run on screen 2. Even if it is moved to screen 1, the newly opened window or drop-down menu will appear on screen 2.If screen 2 is set as the main screen, it will appear opposite on screen 1.

### How to reproduce
Use two monitors and set them to extended mode.

**Comment by marcelomijas** [comment]
I can relate to this. I updated to 4.6.3 a few hours ago.

Now the scale of the menus in my primary display is very tiny, and when I right click something, the context menu appears on my secondary display.

Here's a screenshot with TeXstudio on my primary display and the context menu on the secondary (left):

![imagen](https://github.com/texstudio-org/texstudio/assets/62946623/2e1f0329-e7f8-44be-9639-d9e0891f304a)

Whatever I do, if I have two displays connected, TeXstudio opens on the secondary by default. Also, if I hide the TeXstudio window on the primary display and then show the window again, it opens on the secondary display.

**Comment by sunderme** [comment]
I can't reproduce any of this on win11.

**Comment by egorpugin** [comment]
Same.
Same with other qt6.5 apps.

**Comment by RemiDav** [comment]
Same problem here. I just updated to 4.6.3 from 4.5.x.
TeXstudio loads on screen 2. I move it to screen 1, but right click menu and toolbar menus open on screen 2.

**Comment by WinkyFFM** [comment]
Same here. Updated from 4.1.? to 4.6.3 on Win 10
@RemiDav also tried 4.6.2, Qt-Version 6.5.1, compiled with Qt 6.5.1 R, and it works. Thx for the hint.

**Comment by jrmoserbaltimore** [comment]
Same problem, 4.6.3, downgraded to 4.6.2 to fix.

**Comment by sunderme** [comment]
assume fixed, see #3289
