### ISSUE TITLE
Integrating Video into a latex (Beamer) pdf

### ISSUE THREAD

**Issue by Eraste** [texstudio-org/texstudio#3253]
### Describe the feature and the current behavior/state
Good morning, 
I am NSHIMIRIMANA Eraste, a network administrator, university lecturer and ICT entrepreneur. 

I have had interest in latex and Beamer since 2016. Up to date. Since then, there was a way to integrate a video into a pdf presentation and we could play it inside the pdf using adobe flash player. Now, that flash player is not longer supported, I am unable to use that beautiful feature.

### Who will benefit with this feature?
Once this feature is enabled, professionals, lecturers will benefits from this.

**Comment by sunderme** [comment]
txs can play videos in pdf, just not in the default build.
You need to compile it on your own with the apropriate options, see https://texstudio-org.github.io/background.html#building-texstudio

**Comment by Eraste** [comment]
I would like you to give a code. Suppose I am integrating a video called
V.mp4 to my tex document.

How do I do that?.

**Comment by sunderme** [comment]
Have you tried google?
https://tex.stackexchange.com/questions/89088/how-to-embed-video-and-animation-in-latex-and-latex-beamer-step-by-step#195828
