### ISSUE TITLE
Issue with the -output-directory option and the Stop Compile button

### ISSUE THREAD

**Issue by bgstcola** [texstudio-org/texstudio#3254]
### Environment
- TeXstudio: 4.6.3
- Qt: 6.5.2
- OS: macOS Ventura 13.5
- TeX distribution: texlive

### Expected behavior

When there is an error in the tex document and I press the Stop Compile button it should go from bright red to normal color, and I should able to correct my error and compile again.

### Actual behavior

The Stop Compile button stays bright red and I get a message box with the error message:

_Could not start Build & View:PdfLaTeX:
pdflatex -output-directory=xxx  "test".tex._

I click OK and the Stop Compile button is now unresponsive, and I have to quit and reopen TeXstudio to be able to compile again.

### How to reproduce

1. Create a minimal .tex document in an empty folder.
2. Introduce an error in the document (like a single $).
3. Compile with `pdflatex -output-directory=xxxx  %.tex`.
4. The issue appears.

If a .log file is in the same directory as the .tex file it works as expected, even when using the -output-directory option, but I like to keep my .tex files separate from the build files.

It use to work just fine but it broke when I upgraded texstudio about week ago. I think it was from 4.5.x to 4.6.2, and the issue is still present in 4.6.3

**Comment by muzimuzhi** [comment]
> 1. Create a minimal .tex document in an empty folder.
> 2. Introduce an error in the document (like a single $).
> 3. Compile with `pdflatex -output-directory=xxxx  %.tex`.
> 4. The issue appears.

With or without option `-output-directory=xxxx`, I can confirm clicking "Stop Compile" results in an empty `.log`.  Adding back option `-interaction=nonstopmode`, then the `.log` content is restored.

Tested with TeXstudio 4.6.3beta1 on macOS 13.4.1.

**Comment by bgstcola** [comment]
adding -interaction=nonstopmode, makes no difference for me. It still behaves like described.

**Comment by bgstcola** [comment]
@muzimuzhi, this is embarrassing. I had only specified the PDF File search path, not the Log File path. After specifying the Log File path it works. Thank you. 

I was sure it was a bug since it stated after upgrading. I guess the earlier versions were able to ignore missing log files.

**Comment by sunderme** [comment]
I take it, this is resolved ?

**Comment by muzimuzhi** [comment]
Without option `-interaction=nonstopmode`, clicking "Stop Compile" to stop a hanged compilation results in an empty `.log`.  Is this the long-existing behavior?

**Comment by bgstcola** [comment]
> I take it, this is resolved ?

After I filled out the correct search path for the log file it works perfectly. But should a missing log file make the program freeze? Maybe it would be better if it showed a log file missing error. I don't know.

**Comment by sunderme** [comment]
The actual issue is that another compile is started and that you need to stop again. 
After repeating that a few times, you are a back to normal.

**Comment by flenzen** [comment]
Yes, the two cases seem to have in common that non-existence of a log file causes txs to hang. But no matter how often I press Esc, I don't get back to normal behaviour.

**Comment by flenzen** [comment]
Interestingly, opening the preferences and closing brings txs back to normal work. Changing the build command to `pdflatex -nonstopmode ?me"` solves the issue permanently. In this case, a log file is produced, although I find this somehow less elegant, and a missing log file shouldn't have the mentioned effect I think.
