### ISSUE TITLE
Custom syntax highlighting of custom expressions, not only %TODO

### ISSUE THREAD

**Issue by alchemiker** [texstudio-org/texstudio#3256]
### Describe the feature and the current behavior/state

Just like we can change the colour and style of TODO-comments, it would be cool if we were able to define our own tokens for custom highlighting in the editor, which would have a different color and style from the TODO-comments or other already existing syntax-highlighting.

### Who will benefit with this feature?
People who have not only %TODO, but also %CORR for correction or %INFO or whatever while writing lengthy documents and want to see an overview all of their construction sites at first glance while scrolling the source code of their documents. I know there exist packages for cooler coloured todo-notes, but as far as I am aware they only change the looks in the output document and not in the editor itself.

### Any Other info
I use TeXstudio 4.5.2 on Windows 10.

**Comment by sunderme** [comment]
<img width="676" alt="grafik" src="https://github.com/texstudio-org/texstudio/assets/14033169/e2b5c086-74f9-4c5b-8c86-e43e6ec4df11">

**Comment by alchemiker** [comment]
> ...which would have a different color and style from the TODO-comments or other already existing syntax-highlighting.

@sunderme how do I setup with your solution the format of the TODO-comments to be in a different colour than INFO-comments, for example? I have found the setting which you showed already, which is very near to what I would want, but I can't figure out how to customize them after that

**Comment by sunderme** [comment]
the color can't be changed and there is no intention to change that.
You could extend the syntax definition, see https://texstudio-org.github.io/background.html#writing-your-own-language-definitions.

**Comment by pizdjuk** [comment]
I would have that feauture too. For example it would be cool to be able to define different colors for different TODO priorities. Like TODO2 should be blue and TODO1 like red, etc.
