### ISSUE TITLE
Project menu items are being ellipsized, while enough space is present.

### ISSUE THREAD

**Issue by lfdversluis** [texstudio-org/texstudio#326]
### Environment
- TeXstudio: TeXstudio 2.12.6 (hg 6631:16db084dae24)
- Qt: Using Qt Version 5.9.5, compiled with Qt 5.9.3 R
- OS: Ubuntu 18.04
- TeX distribution: Texlive
### Expected behavior

The project menu should use the full width available, at all times.

### Actual behavior

Best seen on this image: https://gyazo.com/4094c147227bd525b97081f01db034b0 (ignore the weird lines, this is caused by gyzo, it's about the items being ellipsized)

### How to reproduce

If I open a project, tab away and tab back into Texstudio (or just click on the program from the menu), the project menu has ellipized as seen in the figure. If I resize the window by 1 millimeter it will correctly behave again, until I remove window focus and regain focus.

**Comment by sunderme** [comment]
use a newer version of txs

**Comment by lfdversluis** [comment]
Sure, if it appears in the repositories... `texstudio is already the newest version (2.12.6+debian-2).`
