### ISSUE TITLE
texstudio: QListData::detach(): texstudio killed by SIGABRT

### ISSUE THREAD

**Issue by hannes101** [texstudio-org/texstudio#3263]
I received the following bugreport downstream.

https://bugzilla.redhat.com/show_bug.cgi?id=2233029

### Environment
- TeXstudio: 4.6.3
- OS: fedora

**Comment by sunderme** [comment]
no obvious bug in txs. Seems also qt/alloc related. 
Without test case, nothing I can do.

**Comment by sunderme** [comment]
no reproducible test case, looks like crash in qt malloc
