### ISSUE TITLE
QArrayData::allocate(): texstudio killed by SIGABRT

### ISSUE THREAD

**Issue by hannes101** [texstudio-org/texstudio#3264]
I got the following downstream bugreport downstream, let me know if I can provide more Information.

https://bugzilla.redhat.com/show_bug.cgi?id=2233035

### Environment
- TeXstudio: 4.6.3
- OS: Fedora linux

**Comment by sunderme** [comment]
It crashes is a qt memory allocation.
Without a reproducible test case, nothing I can do.

**Comment by hannes101** [comment]
Did you reopen this by accident?

**Comment by sunderme** [comment]
I closed it by accident.
I am waiting for agreement or dissent.
