### ISSUE TITLE
Last line of selected text not cut

### ISSUE THREAD

**Issue by sambo57u** [texstudio-org/texstudio#3268]
I select a block of text to be cut but the cut operation leaves the last line uncut even though it  is highlighted as selected. To cut the desired block I need to go one line lower. 
I remember seeing a similar issue in the past but could not find it.

### Environment
- TeXstudio:  4.6.4 git
- Qt:  5.15.10
- OS:  Linux, Fedora 38
- TeX distribution:  texlive 20230311

### Expected behavior
The text that look selected is not cut.

### Actual behavior
<!-- visuals or even better screencasts are very helpful. Please provide test cases as text as well if applicable.->

### How to reproduce
Select a block of text to cut, choose cut, the last line remains.

**Comment by sunderme** [comment]
Please provide screenshots to avoid ambiguity.

**Comment by sambo57u** [comment]
I promise this happened but now I cannot reproduce it so we can close the issue.  Thanks!

**Comment by sambo57u** [comment]
Cannot duplicate
