### ISSUE TITLE
Script crashes at double % marks

### ISSUE THREAD

**Issue by jonasstein** [texstudio-org/texstudio#327]
### Environment
- TeXstudio: TeXstudio 2.12.10 (git n/a)
- Qt: Qt Version 5.11.1, compiled with Qt 5.11.1 R
- OS: Gentoo Linux
- TeX distribution: texlive

Reproduce: Open test.tex

Example file: test.tex
```
% !TeX program = pdflatex
% !TeX root = test.tex
% !TeX TXS-SCRIPT = foobar
% //Trigger = ?load-this-file
% app.load("/tmp/emptyfile.tex");
%% app.load("/tmp/test/test.tex");
% TXS-SCRIPT-END 

\documentclass[10pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\begin{document}
Hello World
\end{document}

```

### Expected behavior

- TeXStudio should ignore %% lines as comments, or
- catch the error and provide an errormessage

### Actual behavior
Uncaught exception at line 3: SyntaxError: Parse error
Backtrace 
![image](https://user-images.githubusercontent.com/298682/45889080-d2552a00-bdbf-11e8-8cc2-3975fa5314da.png)

**Comment by sunderme** [comment]
between !TeX TXS-SCRIPT and ...script-end, java script is expected (minus the leading % which is ignored), so to comment out a command, you need to use javascript syntax
