### ISSUE TITLE
Additionally show real PDF page numbers under viewer

### ISSUE THREAD

**Issue by erstr2ggl** [texstudio-org/texstudio#3273]
### Describe the feature and the current behavior/state
When using custom page numbering and using hyperref, the true page numbering (e.g. Roman numerals from page 1-3, then arabic numerals from page 4, ...) is encoded in the produced PDF.

Currently only the absolute page number is shown below the PDF previewer.
As an improvement, the true page number should also be shown, for example like this: "Page 1 (i) of 8".

### Who will benefit with this feature?
When editing a TeX document using such custom page numbering, seeing the real page number can benefit the editor by allowing for better orientation and navigation within the PDF preview.

### Any Other info
A small TeX document to reproduce this "issue":
```TeX
\documentclass{article}

\usepackage{hyperref}
\usepackage{lipsum}

\begin{document}
	\lipsum
	\lipsum
	\pagenumbering{roman}
	\lipsum
	\lipsum
	\pagenumbering{arabic}
	\lipsum
	\lipsum
\end{document}
```

If the feature is deemed useful enough, I can provide a pull request for an implementation (see https://github.com/erstr2ggl/texstudio/commit/14101a5fdc63588b682a965661b370eee690425a).

**Comment by sunderme** [comment]
to be honest, I don't really see the point.
The numbering in the status bar serves as point for orientation, i.e. start of doc, middle, end.
What meaningful info can the author derive that the first page is numbered with roman numerals in that status bar ? Do you not rather look on the page itself ?

**Comment by sunderme** [comment]
so I close this, as I don't see a benefit.
