### ISSUE TITLE
(Solved) TexStudio crashes instantly when scrolling to the bottom of the suggestions popup

### ISSUE THREAD

**Issue by MyApaulogies** [texstudio-org/texstudio#3277]
Hello, I figured out my problem but I thought I would report it anyway. (Is this the right place?)

### Environment
- TeXstudio: 4.6.3
- Qt: 5.15.10, compiled with Qt 5.15.10 R
- OS: Fedora 38 via .rpm
- TeX distribution: texlive (I think via `sudo dnf install texlive-scheme-full` from [this guide](https://docs.fedoraproject.org/en-US/neurofedora/latex/)) 

### How to reproduce

Fresh install of TexStudio after installing `texlive-scheme-full`. Open TexStudio, make a new document, type in a backslash and hit Ctrl+Space to trigger autocomplete. Scroll down to roughly the lowercase b's -> TexStudio instantly crashes.

### Fixed

`sudo dnf reinstall 'texlive*'`

**Comment by sunderme** [comment]
it is a bit unclear how the crash and the latex installation should be related.
In case, that someone can provide a reproducible example, please open a new issue and talk us through how to reproduce.
