### ISSUE TITLE
Not possible to set Cmd+Option+F as shortcut and to remove default shortcut

### ISSUE THREAD

**Issue by formiel** [texstudio-org/texstudio#3278]
Hello,

I'm on macOS and I would like to set the shortcut for Replace to "Cmd+Option+F" (which is represented as "Ctrl+Alt+F" in the config file). **The first issue is that I cannot set "Cmd+Option+F" in the current shortcut or the additional shortcut** (TeXstudio didn't recognize this combination). So what I did is that I added the following lines directly to `texstudio.ini`:

```
keysetting\1\id=main/edit/searching/replace~0
keysetting\1\key=Ctrl+Alt+F
```

Unfortunately this didn't work either, and the cause seem to be that "Ctrl+Alt+F" is already the default shortcut for "Definition". **The issue is that it seems to be impossible to remove this default shortcut**. 

Could you please help? Thank you so much in advance!

**Comment by sunderme** [comment]
txs does not recognize cmd+alt+letter in the keysetting dialog, but you can scroll down to that short cut in the drop-down box.
<img width="514" alt="Bildschirmfoto 2023-09-01 um 19 32 33" src="https://github.com/texstudio-org/texstudio/assets/14033169/ced257bf-e934-4535-a369-4a7fd471cf27">
The corresponding symbols for said shortcut are on the screenshot to the right.

To do that via direct manipulation in texstudio.ini, the settings are:
```
keysetting\1\id=main/edit/searching/replace~0
keysetting\1\key=Ctrl+Alt+F
keysetting\2\id=main/edit2/goto/definition~0
keysetting\2\key=
keysetting\size=2
```
