### ISSUE TITLE
Completion does not work while editing after the first time

### ISSUE THREAD

**Issue by arman00** [texstudio-org/texstudio#328]
Completion works well while typing a label/command, but when I wanted to change it later it doesn't work; to make it work again, I need to delete the whole word and re-type all the letters. This is a bit cumbersome.

### Environment
- TeXstudio: 2.12.10
- Qt: 5.9.5
- OS: Ubunut 18.04
- TeX distribution: texlive

### Expected behavior
When I start typing on a reference of a label or a command, by clicking at any position on the word, auto completion should work by showing suggestions, as done when I write the reference the first time. 

### Actual behavior
Nothing appears

### How to reproduce
Write \ref{label_word}. label_word should have been defined. Then try to edit label_word in \ref{.}.
Or, for instance, write \subsection, then try to change it to \subsubsection by first deleting the section part. Normally it should show the list of suggestions following \sub

**Comment by sunderme** [comment]
I think ctrl+space is sufficient
