### ISSUE TITLE
Macro completion of a local style file when master doc is automatic

### ISSUE THREAD

**Issue by Bromind** [texstudio-org/texstudio#3285]
### Environment
- TeXstudio: TeXstudio 4.2.1 (Build: 4.2.1+ds-1)
- Qt: Qt version 5.15.3, compliled with Qt 5.15.2 R
- OS: Ubuntu 22.04.3 LTS
- TeX distribution: texlive

### Expected behavior

I have a local .sty file (macros.sty) which defines a few macros and a single file LaTeX document (say main.tex) which includes macros.sty. When I explicitly set the master file to main.tex, TeXStudio autodetects the macros defined in macros.sty and makes them available in autocompletion. The expected behaviour would be that the same autodetection happens when the master file is automatic.

Here is a screenshot with the detection working (notice that the master file is explicitly set "Maître: main.tex").
![Screenshot from 2023-09-04 14-05-11](https://github.com/texstudio-org/texstudio/assets/6730712/5292a9ca-349c-482a-833e-21717100d3b2)

### Actual behavior
When the master file is auto detected, TeXStudio does not autodetect the macros in the local .sty file. I would suggest TeXStudio should search the folder of the guessed master file. 

Here is a screenshot with the detection not working (notice that the master file is automatically guessed "Automatique").
![Screenshot from 2023-09-04 14-03-21](https://github.com/texstudio-org/texstudio/assets/6730712/fcbef603-7221-4180-bcfd-d669bb1b891d)

### How to reproduce

Create the two following files in the same folder: 
macros.tex:
```
\ProvidesPackage{macros}

\newcommand{\macros}[1]{Macro(#1)}
```

main.tex:
```
\documentclass{article}

\usepackage{macros}

\begin{document}
	% type "\macros{}" with and without explicit master
\end{document}
```

Then, with and without master file automatic detection, type "\macros{}" where indicated.

**Comment by Bromind** [comment]
I noticed that the .sty file should be opened in TeXStudio. If macros.sty is not opened, the detection does not work, even if the master file is explicitly set.

**Comment by octaeder** [comment]
look at #2800 and #2723 (the issues link to each other)

**Comment by Bromind** [comment]
Thanks. Yes, looks like the same; although I find it quite surprising that things works as expected when the master file is manually selected, even without cwl files. 

(Also, I searched for existing issues, but searching for "macro completions" and "master file" did not give anything. I'll close this issue, hopefully having those new search terms will prevent new duplicates.)
