### ISSUE TITLE
Magnifier in macOS dark mode

### ISSUE THREAD

**Issue by zhuaiballl** [texstudio-org/texstudio#3287]
### Environment
- TeXstudio: 4.6.3
- Qt: 6.5.2
- OS: Mac
- TeX distribution: texlive

### Expected behavior

In macOS dark mode, the magnifier pointer should look the same as in light mode.

### Actual behavior

The magnifier pointer seems to be using the magnifier icon in the toolbar. The icon looks good in the toolbar, but it looks terrible in the viewer where a more realistic magnifier is needed.
<img width="281" src="https://github.com/texstudio-org/texstudio/assets/18435488/23b34c16-aa55-4a10-8f00-1a467b19252a">

### How to reproduce

Set macOS to dark mode, open TeXstudio, open the embeded pdf viewer, and set the pointer to magnifier.

**Comment by zhuaiballl** [comment]
I positioned the magnifier cursor on a gray box to enhance its visibility while capturing the image. However, if I were to place it on a white sheet of paper, the circle and the handle of the magnifier would become almost indiscernible, resulting in a large black dot. This appearance is highly unappealing.

**Comment by sunderme** [comment]
fixed
