### ISSUE TITLE
TexStudio resolution and secondary menu bar issues on Windows

### ISSUE THREAD

**Issue by cxx221016** [texstudio-org/texstudio#3289]
### Environment
- TeXstudio: 4.6.3
- Qt: 6.5.2
- OS: Windows 10
- TeX distribution: texlive

### Expected behavior
My computer has a main screen and a secondary screen, and version 4.3 can drag between two screens arbitrarily without any bugs

### Actual behavior

However, after the update, my texstudio default secondary screen is turned on, and even if I move texstudio to the main screen, texstudio's menu bar will still be displayed to the edge of the secondary screen
### How to reproduce
![屏幕截图 2023-09-08 220824](https://github.com/texstudio-org/texstudio/assets/115924630/ac4c4dc2-63c8-4166-964d-8ccb9b07f6b2)
![屏幕截图 2023-09-08 220858](https://github.com/texstudio-org/texstudio/assets/115924630/e603a2a8-12b5-42f6-a8c5-c853d639ee81)

This has a great impact on dual-screen workers and I hope to deal with it as soon as possible

**Comment by cxx221016** [comment]
I rolled back the version to TeXstudio 4.5.1 and that disappeared. 
At the same time, I found that the same Qt-based [wireshark](https://www.wireshark.org/) software also has this problem, possibly due to a Qt flaw.

**Comment by EricGend** [comment]
While working on secondary monitor (where the application starts for some reason) it woks just fine, while dragging it to my main monitore the context menu still opens on the top left of my secondary monitor.

For everyone who needs to finish some kind of homework with TeX like me, I recommend to make your main monitor to the secondary in the windows settings, this just avoids the bug and I can write my stuff peacefully :D

Ohhh, roll back to 4.5.1 will obviously work too.

**Comment by trandria2020** [comment]
With the latest stable version: 4.6.3, everything works as expected.

**Comment by dpwilt** [comment]
Sorry, on my Windows 10 machine with dual monitors and the latest stable 4.6.3, I still have the issue of the secondary menu opening on the monitor where TexStudio was started when the TexStudio main window is dragged to a different monitor.

**Comment by timolohrenz** [comment]
Just installed the latest 4.7.0alpha4 and it seems to be fixed. With alpha2 before the problem still occured.

**Comment by sunderme** [comment]
assume fixed

**Comment by momer** [comment]
Confirmed that 4.7.0rc2 resolved the issue for me on Win 11!
