### ISSUE TITLE
File name is missing in the side with \makeglossaries

### ISSUE THREAD

**Issue by fr24pk** [texstudio-org/texstudio#3292]
### Environment
- TeXstudio: 4.3.1 using Qt Version 6.3.1, compiled with Qt 6.3.1 R

### Expected behavior

The side bar shall list files `fileA`, `fileB`, and `fileC.`

![test-good](https://github.com/texstudio-org/texstudio/assets/141419460/87015d5c-0b07-48b5-9ecb-1e5640e16496)

```
\documentclass[a4paper]{report}%

\usepackage{etoolbox}

\newbool{EnableGlossary}\booltrue{EnableGlossary}
\ifbool{EnableGlossary}{
  \usepackage{glossaries-extra}
}{%
}

\input{fileA}
\ifbool{EnableGlossary}{\makeglossaries}{}% 
\input{fileB}

\begin{document}%
\input{fileC}
\end{document}%

\endinput
```

### Actual behavior

Files `fileA`, and `fileC` are listed. File 'fileB' is missing.

![test-bad](https://github.com/texstudio-org/texstudio/assets/141419460/d2264218-4be1-4ab1-be77-deb0e1c48aff)

```
\documentclass[a4paper]{report}%

\usepackage{etoolbox}

\newbool{EnableGlossary}\booltrue{EnableGlossary}
\ifbool{EnableGlossary}{
  \usepackage{glossaries-extra}
}{%
}

\input{fileA}
\ifbool{EnableGlossary}{%
  \makeglossaries%
}{}% 
\input{fileB}

\begin{document}%
\input{fileC}
\end{document}%

\endinput
```

**Comment by sunderme** [comment]
the point is that `\makeglossaries` has an optional argument but not a mandatory one.
This detection gets confused if a linebreak is introduced.
