### ISSUE TITLE
identical condition

### ISSUE THREAD

**Issue by maddin200** [texstudio-org/texstudio#3295]
/src/hunspell/affixmgr.cxx line 1888

Code:
   // check FORCEUCASE
            if (rv && forceucase && (rv) /* <-- identical */  &&
                (TESTAFF(rv->astr, forceucase, rv->alen)) &&
                !(info && *info & SPELL_ORIGCAP))
              rv = NULL;

**Comment by sunderme** [comment]
as it is not harmful and it is imported code, I will not change that.

**Comment by muzimuzhi** [comment]
The redundant duplicate conditional has been removed in hunspell v1.7.2 (2022-12-30), in commit https://github.com/hunspell/hunspell/commit/d345f733349f74b242ae4656b4fc5bd10bd4b3df. Currently texstudio uses (a modified?) hunspell v1.7.0 (2018-11-12).
