### ISSUE TITLE
Missing application icon

### ISSUE THREAD

**Issue by joaopauloalbq** [texstudio-org/texstudio#33]
![screenshot_20180208_101719](https://user-images.githubusercontent.com/9905202/35975332-2095e7a6-0cbb-11e8-882a-19c1560626e4.png)

![screenshot_20180208_102942](https://user-images.githubusercontent.com/9905202/35975319-116d616e-0cbb-11e8-8fed-f9c4921fbe50.png)

**Comment by fearthebear** [comment]
It is not missing. KDE/Qt seems to have problems with the provided texstudio.svg located in `/usr/share/icons/hicolor/scalable/apps/` . It seems to be a namespacing issue. For testing purposes i ran the svg through `svgcleaner-cli` (and `xmlstarlet fo` for proper formating) and that solves the issue.

[texstudio.svg.gz](https://github.com/texstudio-org/texstudio/files/1730812/texstudio.svg.gz)

(I gzip'd the file for github upload ... :-/ )

**Comment by sunderme** [comment]
I have includede the svg in the repository.
