### ISSUE TITLE
GUI layout is left-right mirrored after installation on WIN11

### ISSUE THREAD

**Issue by erezgilad** [texstudio-org/texstudio#3301]
### Environment
- TeXstudio: 4.6.3
- Qt: 6.5.2, compiled with Qt 6.5.2 R
- OS: Windows 11
- TeX distribution: miktex 23.4

### Expected behavior
GUI from left to right.
Taskbar: File  Edit  Idefix   ...

### Actual behavior
GUI from right to left.
Taskbar: Help   ...   Idefix   Edit   File

ALL GUI is mirrored.

![Screenshot 2023-09-19 14 27 01](https://github.com/texstudio-org/texstudio/assets/11707570/5c46a965-bf41-4b95-b917-91f9fd8a3d10)

### How to reproduce
Happens in every installation. Happens also for the portable version.

**Comment by erezgilad** [comment]
![Screenshot 2023-09-19 14 27 01](https://github.com/texstudio-org/texstudio/assets/11707570/0f742ed7-c01c-4d0e-91c3-0fa03eafcf90)

**Comment by idamir** [comment]
Do you have any of Arabic, Hebrew, Persian, or Urdu locale settings?

**Comment by erezgilad** [comment]
I have Hebrew installed. But I have it installed also on other two computers, win11 and win10, without this problem.
 
![Screenshot 2023-09-19 15 58 10](https://github.com/texstudio-org/texstudio/assets/11707570/02eb170e-e0b6-4d7c-88f0-b9733e0eb19d)

**Comment by erezgilad** [comment]
changing the "Country or region" solves this issue. Thanks.
