### ISSUE TITLE
per-file/per-session tab size

### ISSUE THREAD

**Issue by dharvey37** [texstudio-org/texstudio#3302]
I am running texstudio 4.3.1 on debian 12.

I often work on multiple projects with different people, and I'm not always in a position to choose what tab size is used for each project.

Currently the tab size in texstudio appears to be a global setting. This means I need to change this setting whenever I switch projects. I would much prefer texstudio to somehow remember this for me.

Perhaps this information could be saved in a session file?

Another possibility would be to add a "magic comment", something like

`% !TeX tabsize = 4`

Or is there already some other way to achieve this that I am unaware of?

**Comment by octaeder** [comment]
maybe you can use different profiles with options --config or --ini-file (s. [manual](https://texstudio-org.github.io/background.html#overview-of-texstudio-command-line-options))

**Comment by sunderme** [comment]
no plans.
