### ISSUE TITLE
highlighting for \eqref not correct

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3303]
### Environment
- TeXstudio: git 4.6.3-55-g990a2e634 Using Qt Version 6.5.1
- OS: Windows10
- TeX distribution: miktex

### Expected behavior
- number of references in tooltip for \label should be correct
- preview of label should be shown as tooltip for \eqref
- argument of \eqref should be colored green

### Actual behavior/How to reproduce
Enter the following in a new document:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/e7658911-c62c-46d6-ab81-e92e451fd1b7)

**Comment by muzimuzhi** [comment]
LaTeX2e doesn't provide `\eqref`, it's `amsmath` package that defines it. After loading `amsmath`, the problem seems to disappear.

Another problem: Why in your screenshot `\eqref` is not marked as unrecognized.

```tex
\documentclass{article}
\usepackage{amsmath}

\begin{document}
\begin{equation}
  ab \label{test}
\end{equation}

Equation: \eqref{test}
\end{document}
```

![image](https://github.com/texstudio-org/texstudio/assets/6376638/950f2a6b-af92-44d9-899e-06b7153477e5)
![image](https://github.com/texstudio-org/texstudio/assets/6376638/55f5364e-a762-4c90-bbaa-4283121b2943)

**Comment by octaeder** [comment]
I Forgot to insert \include{mathtools}. The screenshot is a cut down of a larger document that has this include where I observed the problem.

Maybe the command is known because the original document is still open? I have to recheck because now the coloring works in the cut down but not always in the larger document.

**Comment by octaeder** [comment]
sorry, I can't reproduce in the original document. What I see in the small document: When the line with \usepackage{mathtools} is added as the last one then the label name in \eqref stays colored black. When you change the line with \eqref then the color is updated to green. Similar when \usepackage is removed afterwards.

Still without package mathtools/amsmath \eqref is not highlighted as unrecognized. Here the code as text:

```latex
\documentclass[10pt,a5paper]{article}
\begin{document}
\begin{equation}
abc \label{abc}
\end{equation}
equation: \eqref{abc}
\end{document}
```

**Comment by muzimuzhi** [comment]
> * TeXstudio: git 4.6.3-55-g990a2e634 Using Qt Version 6.5.1

My result https://github.com/texstudio-org/texstudio/issues/3303#issuecomment-1727815863 was tested with TeXstudio 4.6.3 (git 4.6.3beta1).
