### ISSUE TITLE
ps2pdf not working

### ISSUE THREAD

**Issue by alerodriguezor** [texstudio-org/texstudio#3305]
### Environment
- TeXstudio: 4.6.3
- Qt: 6.5.2,
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
Successfully compiling ps2pdf

### Actual behavior
I already uninstalled everything and reinstalled and I can't get it to work. The strange thing is that when I run it from the CMD, the command ps2pdf.exe "delay_V8".ps works but in Tex Studio it doesn't work

![image](https://github.com/texstudio-org/texstudio/assets/40036108/5db6f07d-033a-4c7a-9fb3-158bf977a8be)
![image](https://github.com/texstudio-org/texstudio/assets/40036108/131602e4-f795-4606-977c-bf76984f1b36)
![image](https://github.com/texstudio-org/texstudio/assets/40036108/fdf7c492-063c-45c9-960b-c1fa7a905b61)
![image](https://github.com/texstudio-org/texstudio/assets/40036108/19c57fb3-3d0c-4643-a185-248e58d24ac0)

### How to reproduce
The PS->PDF command does not run either in the compile routine or independently

**Comment by sunderme** [comment]
in this scenario, usually a path variable is not set correctly. ps2pdf probably tries to call ghostscript and that fails.
On the other hand, this is a really old/obsolete workflow, pdflatex ?
Since I work on linux, someone else can try to figure this one out.

**Comment by alerodriguezor** [comment]
@sunderme Thanks for responding, it currently happens to me on Windows and on Mac I also tried and the same thing happens. I use the DVI > PS > PDF compilation method. To be able to make text changes in images such as

![image](https://github.com/texstudio-org/texstudio/assets/40036108/a66f3993-5b8d-41f5-a5ae-9d01d9e1514a)

**Comment by octaeder** [comment]
maybe package tikz (based on package pgf) can help

**Comment by sunderme** [comment]
div/ps/pdf toolchain works fine on linux.
As stated above, usually something to do with path settings.
I can't debug user installation, so closing.
