### ISSUE TITLE
TeXstudio freezes when opening certain file

### ISSUE THREAD

**Issue by samcarter** [texstudio-org/texstudio#3306]
### Environment
- TeXstudio: current head version https://github.com/texstudio-org/texstudio/commit/014e1c47bd378f9db59639a1187958b53580894b
- Qt: 6.5.0
- OS: macOS 13.5.2
- TeX distribution: TeXlive 2023

I'm trying to open this file in TeXstudio 

https://github.com/josephwright/beamer/blob/20b8b7a50f364453fa40da3dbc6313650c843a63/base/beamerbaseframe.sty#L57

Instead of opening the file, TeXstudio becomes unresponsive and freezes.

The problem seems to be connected with the definition of `\newenvironment{beamer@frameslide}`. If I remove this code block, I can open the file again.

**Comment by muzimuzhi** [comment]
In texstudio 4.6.3 (git 4.6.3beta1) installed on macOS 13.4.1, I can open such file on that specific commit as normal.

**Comment by sunderme** [comment]
should be fixed

**Comment by samcarter** [comment]
@sunderme  Thanks a lot!
