### ISSUE TITLE
resetMessagesAndLog() for macros

### ISSUE THREAD

**Issue by snorthman** [texstudio-org/texstudio#3308]
### Environment
- TeXstudio: 4.5.2
- Qt: 6.5.0
- OS: W 10
- TeX distribution: miktex

### Description

For my macro, I want to clear and show the Messages tab when the macro script is run.

`app.viewLog()` allows me to simply view the log, but I want to run `resetMessagesAndLog()`. How can I run this function from within my macro?

My assumption was `app.outputView` holds the function, but it appears as undefined to me.

Suggestions?

**Comment by octaeder** [comment]
Maybe this: app.clearLogs();

**Comment by sunderme** [comment]
clearLogs does run resetMessageAndLog()
