### ISSUE TITLE
Highlighting wrong for latest dev

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3309]
### Environment
- TeXstudio: git 4.6.3-145-g607747273
- Using Qt Version 6.5.1, compiled with Qt 6.5.1 R
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
recognize commands/envs as usual:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/db33103d-ead2-423e-9c3e-60a501a98661)
(same doc as below with txs 4.5.2)

### Actual behavior
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/c031fe9a-753b-49bd-97ae-e52ffccd68e7)

```latex
    \begin{multline*}
        3x^4 + x^3 + 2x^2 + 1 = \\ (3x^2 - 11x + 40)(x^2 + 4x + 2) - 138x - 79
    \end{multline*}
```
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/8155861a-f51a-43f1-b819-9df63431a3f0)

```latex
    \begin{equation*}
        p(x) \coloneq 16x^4 - 16x^2 + 1
    \end{equation*}
```

I assume that this is related to the eqref change(s).

**Comment by sunderme** [comment]
I would really appreciate to see complete examples.
Both examples are amsmath commands.
Looking at the example alone, it is supposed to flagged as false.

**Comment by octaeder** [comment]
Today I found that the structure view highlights the file affected in red. So all commands from used packages in the master file are not known. Now I can reproduce this in a similar way with small files:

__master:__
```latex
\documentclass[10pt,a5paper]{article}
\usepackage{mathtools}
\begin{document}
\input{a1}
\end{document}
```

__a1:__
```latex
\input{a2}
\begin{equation*}
    $\sqrt{2}$
\end{equation*}
```

__a2:__
```latex
\begin{equation*}
    $\sqrt{2}$
\end{equation*}
```
Highlighting in a2 and only in a2 missing/wrong.

Pretty sure that one of the last three commits is the reason:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/eaf8b652-e01f-4d77-a4a7-309dd085cca4)

Probably TOC issue #3310 is also related.
Caching docs is not activated.

**Comment by octaeder** [comment]
Seems that last two commits solve this issue and the TOC issue:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/35e30664-ee4c-4e20-81b8-b1639022d987)

Thanks
