### ISSUE TITLE
TOC wrong for current dev

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3310]
### Environment
- TeXstudio: git 4.6.3-145-g607747273
- Using Qt Version 6.5.1, compiled with Qt 6.5.1 R
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
show TOC for complete document:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/66d07d93-33a5-4043-b10b-2b53d7ce94b8)

### Actual behavior
TOC shows only per file/editor selected

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/009b7133-36cf-4e08-bad7-8b46fad7bc85)
(the part with the blue line is the same as above)

### How to reproduce
I assume with any multi parted document

**Comment by sunderme** [comment]
How is this supposed to be debugged ?
It basically says, toc may be wrong under undisclosed circumstances.

**Comment by octaeder** [comment]
fixed, s. #3309
