### ISSUE TITLE
New behaviour when using the align* environment

### ISSUE THREAD

**Issue by WilliamADon** [texstudio-org/texstudio#3315]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior
I have a shortcut for \begin{align*}.  Starting just recently, when I use she shortcut the environment is created but it includes two template lines.  How do I stop this happening?  Previously it just created a blank environment
\begin{align*}
		ralign & lalign \\
		ralign & lalign
\end{align*}

**Comment by octaeder** [comment]
This was changed in 4.5.2 released in April (s. #3002, #3022). You can use a macro to change this behavior to your needs ([environment macros](https://texstudio-org.github.io/advanced.html#environment-macros) in section personal macros).

**Comment by WilliamADon** [comment]
Thanks.  Is there a simple way to stop this behaviour?  I could not penetrate the environment macros section.

Assheton
***@***.***

**Comment by octaeder** [comment]
No, this is a permanent change. Be aware that the change affects align, align* and many others, as you can see from the issue given above.

Creating an Environment Macro is quite simple:

- choose from main menu `Macros/Edit Macros...` to start "Edit Macros" dialog
- press `Add` button at lower left to add a new macro
- fill in your data at the right: Name, Description, Shortcut
- select type Environment and add following line:
  
  ![image](https://github.com/texstudio-org/texstudio/assets/102688820/2f494591-11f4-4a7b-8852-3f7525c56001)

You can execute the macro in the `Macros` menu or with your shortcut. This is what you get:

![image](https://github.com/texstudio-org/texstudio/assets/102688820/8b65e2ba-8277-4032-b01b-a1a100a4a9f7)

**Comment by WilliamADon** [comment]
Thanks for taking the time to reply and suggest a work around.

Assheton
***@***.***

**Comment by sunderme** [comment]
you can change what is placed from "math/math equations/env align*"
To do so, use options/menus/&math ...  (advanced option) where you can edit the entry.
`%\` means new line, `%<something%>` is a placeholder.

[test.txt](https://github.com/texstudio-org/texstudio/files/12777216/test.txt)
The file needs to be renamed to test.txsprofile. Load it with `option/load profile`. It changes the menu to insert only begin/end (restart required).

**Comment by WilliamADon** [comment]
Many thanks – just what I was looking for.

Assheton
***@***.***
