### ISSUE TITLE
Parentheses surrounding math command highlighted red

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3319]
### Environment
- TeXstudio 4.7.0 (git 4.7.0alpha2-9)
- Using Qt Version 6.5.3, compiled with Qt 6.5.3 R
- OS: Windows 10
- TeX distribution: miktex

### How to reproduce
Start with a new editor (f.ex. quick wizard):
```latex
\documentclass{article}
\begin{document}

\end{document}
```

- Enter `\ne` in the empty line, then press enter to finish auto completion. `$\ne$` is created. Move cursor left 4 steps.
- Press shift and move cursor right 3 steps to select `\ne`.
- Press `(` and auto complete parentheses happens with result `$(\ne)$`, closing parentheses is marked for overwriting.
- Press `ctrl+shift+k` to remove mark.
- Move cursor 3 times left with cursor key. Red highlighting appears:

  ![image](https://github.com/texstudio-org/texstudio/assets/102688820/9a9c684b-8c87-4831-8a2f-4d6093e033e3)

**Comment by sunderme** [comment]
can't reproduce

**Comment by octaeder** [comment]
It may help the following: When it doesn't work then start with a new document (this seems to be necessary every time you deviate from the procedure given) but use different direction of selecting `ne`, i.e. 

- Enter \ne in the empty line, then press enter to finish auto completion. `$\ne$` is created. Move cursor **left 1 step**.
- Press shift and move cursor **left 3 steps** to select `\ne`.

Try several times.

**Comment by octaeder** [comment]
I also observed this in TeXstudio 4.6.3 (git 4.6.3)
Using Qt Version 6.5.2, compiled with Qt 6.5.2 R
(installed release for Win10)

**Comment by sunderme** [comment]
I don't see any problem here, so I leave it at that.

**Comment by sunderme** [comment]
please come back when there is a reproducible way of provoking the issue.

**Comment by octaeder** [comment]
Screencast with current dev:

https://github.com/user-attachments/assets/72e52b26-6655-49cb-ac3b-bd9ebd57cc48
