### ISSUE TITLE
Inline Preview cannot work when using unicode-math package

### ISSUE THREAD

**Issue by KSALFH** [texstudio-org/texstudio#3321]
### Environment
- TeXstudio:4.6.3 
- Qt: qt5.6
- OS:Windows 10 
- TeX distribution: texlive

### Expected behavior
When I move my mouse to the equations,  it should show the inline preview.

### Actual behavior
![image](https://github.com/texstudio-org/texstudio/assets/107134674/4e082d66-f86f-48e7-9d2b-9462263bea17)

( just like the image above)It did not show the inline preview properly. There are some errors in the message box and nothing in log box.

**Comment by sunderme** [comment]
option/preview/command -> preview with lualatex
option/preview/precompile preamble (advanced opion) -> off
