### ISSUE TITLE
Crashing when pasting into texstudio

### ISSUE THREAD

**Issue by hannes101** [texstudio-org/texstudio#3322]
### Environment
- TeXstudio: texstudio-4.6.3-1.fc38 
- Qt: Using Qt Version 5.15.10, compiled with Qt 5.15.10 R
- OS: fedora 38

### Actual behavior
Texstudio is apparently crashing, when pasting something from the clipboard. This happens in Xfce with X11

Please see https://bugzilla.redhat.com/show_bug.cgi?id=2242394 for more information.

**Comment by sunderme** [comment]
the last call before "recover from crash" starts is:
```
#35 xkb_state_get_keymap at ../src/state.c:619
 #36 QXkbCommon::lookupLatinKeysym(xkb_state*, unsigned int) at qxkbcommon.cpp:758
 #37 QXkbCommon::keysymToQtKey(unsigned int, QFlags<Qt::KeyboardModifier>, xkb_state*, unsigned int, bool, bool) at qxkbcommon.cpp:528
```

Does not really look like txs fault.
Without a proper test case, impossible not narrow down further.

**Comment by hannes101** [comment]
Well, ok then. Doesn't really make sense to report anything in the future.
