### ISSUE TITLE
a special case with smart home cursor movement

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3323]
For previous discussion see #3172 

### Environment
- TeXstudio: 4.6.3 and current dev build
- Qt: 6.5.2, 6.5.3
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
Smart home should work in the same way
1.  regardless in which line the cursor is. But this is not the case for line 1 of the editor.
    reason is `if ( atStart() )` in qdocument.cpp (l. 4937ff), a shortcut in case document is empty?
2. for all lines starting with space/tab characters (white space). But this is not the case when the line contains only space/tab characters. So the user needs to use end key instead of home before typing new code at the end of line.
   reason is `if(offset==end)` in qdocument.cpp (l. 4937ff)

### Actual behavior
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/36b5f056-2d7f-4a69-9e62-d6d753c73b87)

Line 1: Cursor doesn't move from start of line to the first character that is not a space/tab when pressing home.
Line 3: Cursor doesn't move from start of line to first position after last space/tab (because no other characters follow), in fact smart home always moves the cursor to start of line.
Line 4 shows well behavior of smart home.

### How to reproduce
As an example (indentation is done with spaces):
```latex
    \documentclass{article}
\begin{document}
    
    adsfadf
\end{document}
```
### Other information
Notepad++ behaves as expected in both special cases.

**Comment by sunderme** [comment]
1) fixed
2) the function is called "move to first character in line". I will not change the behavior here.

**Comment by octaeder** [comment]
that's ok, thanks.
