### ISSUE TITLE
left click and cmd+click no longer working on internal viewer on mac

### ISSUE THREAD

**Issue by val461** [texstudio-org/texstudio#3324]
### Environment
- TeXstudio: 4.6.3 (git 4.6.3)
Using Qt Version , compiled with Qt 6.5.2 R
- Qt: 6.5.2
- OS: Mac macOS 14.0 (23A344) Apple M1
- TeX distribution: TeX Live (installed by MacTeX)
- I use a trackpad.

### Expected behavior
The cursor jumps to the corresponding part in the Latex code. The focus goes from the internal viewer to the editor.

### Actual behavior
The cursor stays in place. The focus stays on the internal viewer. The internal viewer scrolls one page lower.

### How to reproduce
Compile a Latex document.
Show it with the internal viewer.
Hold the command key, click on a part of the pdf, then release the command key.

### Workaround
Right-click on internal viewer and "Go to Source".

### Seemingly related bug
A left click (without the Cmd key) on the internal viewer also scrolls one page lower, whether clicking on regular text or on a link of the hyperref package. (Links still work with other viewers.)

### Other details
I tried two different files, they had this same bug.
This bug started about a week ago I think. Or maybe since my last update of macOS, from 13.5.2 to 14.0 on 2023-09-28 11:51 AM.

**Comment by muzimuzhi** [comment]
Are the `.synctex.gz` files generated? Did you use something like `-output-directory`? And, in Configure TeXstudio - Commands, is CLI option `-synctex=1` used for commands PdfLaTeX, XeLaTeX, and LuaLaTeX?
![image](https://github.com/texstudio-org/texstudio/assets/6376638/b32ab275-1b97-4d19-8c5c-b284d9c24d39)

**Comment by val461** [comment]
> Are the `.synctex.gz` files generated? Did you use something like `-output-directory`? And, in Configure TeXstudio - Commands, is CLI option `-synctex=1` used for commands PdfLaTeX, XeLaTeX, and LuaLaTeX? ![image](https://user-images.githubusercontent.com/6376638/273906865-b32ab275-1b97-4d19-8c5c-b284d9c24d39.png)
> 
> > ### Workaround
> > Right-click on internal viewer and "go to source".
> 
> Ah, so the synctex is working, just shortcut Cmd + Click doesn't work as expected.

**Comment by val461** [comment]
> Are the `.synctex.gz` files generated?

Yes.

> Did you use something like `-output-directory`?

No.

> And, in Configure TeXstudio - Commands, is CLI option `-synctex=1` used for commands PdfLaTeX, XeLaTeX, and LuaLaTeX?

Yes.

> Ah, so the synctex is working, just shortcut Cmd + Click doesn't work as expected.

Yes. On another editor (VSCode with Latex Workshop extension), Cmd + Click still works for inverse search. But forward search never worked on VSCode for me, which is one reason I use TexStudio.

**Comment by val461** [comment]
Also, links with the hyperref package no longer work in the internal viewer (but still work with other viewers).

And a left click (without the Cmd key) on the internal viewer also scrolls one page lower.

I use a trackpad.

**Comment by val461** [comment]
Today, during use, this suddenly turned into a different bug. Click and cmd+click now work on the preview, but the preview toolbar is now missing. So I can no longer use the "fit text width" feature.

**Comment by val461** [comment]
The issue suddenly got resolved during use. Thanks.

**Comment by octaeder** [comment]
s. Pdf-Viewer menu Window/Show/Toolbar

**Comment by val461** [comment]
I don't find "Window/Show/Toolbar", but the viewer is working now anyway.

**Comment by octaeder** [comment]
In the windowed viewer you find:

![image](https://github.com/texstudio-org/texstudio/assets/102688820/9201b1f1-6933-4c1a-80d9-67cb9b7580b2)

**Comment by WRether** [comment]
Sorry for resuming this thread, but I have the exact same problem. I tried this bit didn't solve it. Any suggestion? Thanks!

**Comment by val461** [comment]
Just a guess.

1. Click the button "Windowed Viewer" at the top right of the internal viewer.
2. Close the windowed viewer.
3. Press F7 to display the internal viewer (or click the menu Tools > View).

**Comment by lluisvena** [comment]
I am also having the same issue.
After doing what the comment suggest (messing a bit with the viewer), 
it works for a couple of inverse searches, but then it stops working again.

**Comment by lluisvena** [comment]
It seems that the issue has been resolved, possibly through an update to the macos (written on the 15.3.2 version of the OS)
