### ISSUE TITLE
[Feature request] "Richt Text" mode

### ISSUE THREAD

**Issue by NikoKrause** [texstudio-org/texstudio#333]
Recently I tried Overleaf (an online LaTeX editor) for the first time and the have cool new feature in beta called "Rich text". 

The "![rich text mode renders headings, formatting and equations directly in the editor, to make it seem more familiar to WYSIWYG users.)](https://www.overleaf.com/blog/81-having-a-hard-time-convincing-your-coauthors-to-learn-latex-with-our-rich-text-mode-you-no-longer-need-to-dot-dot-dot)"

It can be tried here: https://www.overleaf.com/docs?template=overleaf

Would be cool to have something similar in TeXstudio.

**Comment by sunderme** [comment]
if you like to have something like "rich text", look at lyx.
We are providing a text editor with good support for latex, no rich text is intended.

**Comment by kbauer** [comment]
TeXstudio actually already kind of has rich-text support through its highlighting and preview features. It just currently doesn't utilize them for decluttering the source code.

E.g. it would be useful to be able to declare, that certain commands and environments are automatically replaced by their preview, once the cursor leaves them. This would greatly help navigating source files, that are heavily cluttered (e.g. with complex equations).

Regarding LyX, it sadly doesn't fit the same niche, as it doesn't edit plain TeX files, and doesn't give the user full control over the preamble.

**Comment by mattmajic** [comment]
I also would like to see a rich text feature in TexStudio - this would be extremely useful for proofreading, where I often find myrself reading from the pdf and having to then find the right place in the editor in order to make edits.

**Comment by timhoffm** [comment]
Rich text could just be an approximation and thus could still mislead your proofreading.

Reading the PDF is the only way to see what's really going on. For finding the right place use forward and backward synchronization between source and PDF:
- In editor context menu: "Go to PDF"
- In PDF viewer context menu "Go to Source" (or `Ctrl+Click`).

**Comment by mattmajic** [comment]
I understand rich text is a compromise, but for me switching between the pdf and code is a barrier to fast and seamless editing. Its nothing like editing what you see, even if its an approximation. I see no harm in having it as an option for those who prefer.

**Comment by timhoffm** [comment]
This is not the focus of TeXstudio. And it would be a major several hundred hour development to bring it into TXS. Unless someone with the respective time and knowledge steps up, it won't come.

If you really need that way of working you should look for other editors like emacs/AucTeX, BakomaTeX or Overleaf.

**Comment by smihael** [comment]
It would definitely be a nice option to have.  It also fits the goal "to make writing LaTeX documents as easy and comfortable as possible". 

As TexStudio is Qt-based, I was looking for other Qt-based editors that provide rich text editing or previews for some ideas for possible implementation. 

A similar thread on [LaTeX Stack exchange]( https://tex.stackexchange.com/questions/308256/editors-with-rich-text-viewing-similar-to-overleaf/671122#671122) mentions [notepadqq](https://github.com/notepadqq/notepadqq), which can [render math equations in code comments](https://notepadqq.com/s/images/snapshot_math.png). This might be a good starting point for a richt-text alternative to QCodeEdit widget which is used now.  
Another Qt-based editor worth looking into is [Ghostwriter](https://ghostwriter.kde.org/), but it merely renders markdown preview.
