### ISSUE TITLE
SIGSEGV on GNOME 45

### ISSUE THREAD

**Issue by MarDiehl** [texstudio-org/texstudio#3333]
### Environment
- TeXstudio: 4.6.3
- Qt: Qt Version 6.6.0, compiled with Qt 6.5.2 R
- OS: Arch Linux
- TeX distribution: Texlive

### Expected behavior
No segmentation fault.

### Actual behavior
I get 'random' messages about a segmentation fault. 
The error message in the backtrace file is
```
SIGSEGV (TXS-Version 0.0.0++ R )
[bt] /usr/bin/texstudio(_Z15print_backtraceRK7QString+0x4) [0x55aa369ef254]
```

### How to reproduce
I could not figure that out yet. The error appears during normal work. I believe they started after the update to GNOME 45.0, but that could be a coincidence.

![Screenshot from 2023-10-16 17-05-11](https://github.com/texstudio-org/texstudio/assets/6196733/05186c67-2cc9-4c6e-9fd9-ddad2c334ef1)

**Comment by sunderme** [comment]
please compile txs yourself with debug symbold and run it in a debugger (or use qtcreator) so that we can get a complete backtrace.

**Comment by MarDiehl** [comment]
`gdb` can download debug symbols for Arch packages automatically, it gives me

```
Thread 1 "texstudio" received signal SIGSEGV, Segmentation fault.
0x000015553c4f7c31 in QGnomePlatformDecoration::forceRepaint() ()
   from /usr/lib/qt6/plugins/wayland-decoration-client/libqgnomeplatformdecoration.so
```
The symbol belongs to `qgnomeplatform-qt6` which is not longer available for Arch, I've uninstalled it.

**Comment by sunderme** [comment]
so, this is finished ?
