### ISSUE TITLE
Lauch Zotero Picker

### ISSUE THREAD

**Issue by endomorphisme59** [texstudio-org/texstudio#3337]
### Environment
- TeXstudio: 4.6.3
- Qt: 5.15.3
- OS: Ubuntu 22.04.3 LTS
- TeX distribution: TexLive 2023

When I trigger Lauch Zotero Picker, a small Zotero window opens itself so that I can select one (or several) references. But when I press the enter key, the window closes itself and nothing happens (the references are not added in the document).

The following message appears then : 

```
Processus en cours : curl -s -A "TeXstudio" http://127.0.0.1:23119/better-bibtex/cayw?format=biblatex&command=autocite&texstudio=true&minimize=true
TeXstudio not found
Processus terminé normalement
```

When I lauch TexStudio via the command prompt, I also get the follwing message : 

```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
BibTeX-File <PATH TO THE CURRENT .tex FILE>/< .bib FILE LOADED IN THE BEGINNING OF THE DOCUMENT> not loaded
```

I precise that curl and Zotero BBT are installed on my computer.

**Comment by sunderme** [comment]
I just checked (ubuntu 22.04)
```
Prozess gestartet: curl -s -A "TeXstudio" http://127.0.0.1:23119/better-bibtex/cayw?format=biblatex&command=autocite&texstudio=true&minimize=true

\autocite{sundermeyerJanTest}
Prozess endete normal
```
So, wayland issue ?

**Comment by sunderme** [comment]
works also under gnome/wayland.

**Comment by sunderme** [comment]
not reproducible, no feedback
