### ISSUE TITLE
Autocompletion Bug in a Multilingual Linux Environment

### ISSUE THREAD

**Issue by sleepychemist27** [texstudio-org/texstudio#3338]
### Environment
- TeXstudio: 4.6.3
- Qt: 5.15.3
- OS: Kubuntu 22.04
- TeX distribution: texlive-full

### Expected behavior

After typing \ expected autocompletion floating list to pop up as configured. This didn't happen. However, autocompletion does work when I run the app image instead of the one installed via the ubuntu PPA. I am have multiple input methods configured with fcitx 5. 

### How to reproduce

Configure fcitx 5 with more than one input methods and Ctrl+space to shift between them. You will observe that this shortcut doesn't work when TeXstudio is open.

**Comment by sunderme** [comment]
There is a lot "doesn  not work" leaving a lot of ambiguity what exactly happens or was expected to happen.
So "ctrl+space" in txs was supposed to open the completer or did it change fcitx ?
Anyway, when assigning conflicting shortcuts, things are pretty unpredictable, so better change either fcitx or txs shortcut ?

**Comment by sunderme** [comment]
no feedback
