### ISSUE TITLE
Question about the IEEEtran.cls font in Texstudio

### ISSUE THREAD

**Issue by eejyin** [texstudio-org/texstudio#3339]
### Environment
- TeXstudio: 4.6.3
- Qt: 6.5.2 R
- OS: Windows 11
- TeX distribution:  texlive2023

### Expected behavior
I am using the very common class file [bare_jrnl.tex](http://mirrors.ctan.org/macros/latex/contrib/IEEEtran/bare_jrnl.tex) to finish my journal paper [IEEEtran – Document class for IEEE Transactions journals and conferences](https://ctan.org/tex-archive/macros/latex/contrib/IEEEtran/?lang=en). The default font is **Times New Roman**, and it display correctly on Texworks or Overleaf (figure attached below). 

**I WANT THE TIMES FONT.**
![Quicker_20231019_133509](https://github.com/texstudio-org/texstudio/assets/57343270/b7f1a564-567f-4854-a327-c14951e55734)

### Actual behavior

But when the files are opened in Texstudio, the default font is **Computer Modern**. It is certain that the original class file [IEEEtran.cls](http://mirrors.ctan.org/macros/latex/contrib/IEEEtran/IEEEtran.cls) contain the font definition lines, which never be changed:

```
% The IEEE uses Times Roman font, so we'll default to Times.
% These three commands make up the entire times.sty package.
\renewcommand{\sfdefault}{phv}
\renewcommand{\rmdefault}{ptm}
\renewcommand{\ttdefault}{pcr}
```

**BUT IN TEXSTUDIO, IT IS COMPUTER MODERN FONT.**
![Quicker_20231019_133550](https://github.com/texstudio-org/texstudio/assets/57343270/bea25439-3df9-42c1-ac80-8af4d77f2a29)

### How to reproduce

Just run this file [bare_jrnl.tex](http://mirrors.ctan.org/macros/latex/contrib/IEEEtran/bare_jrnl.tex).
**BUT IN TEXSTUDIO, IT IS COMPUTER MODERN FONT.**
**I WANT THE TIMES FONT.**

**Comment by enxit** [comment]
You are totally wrong!

1. First of all you should install the Times New Roman fonts in your local system (I suppose it is Linux) or import them by indicating the path in the TEX document  where they can be found.
Solution: in Ubuntu there is a package which can install **Times New Roman** automatically (Regular, **Bold**, _Italic_).
sudo apt install ubuntu-restricted-extras 
2. After font install, or download, add to your TEX file, just before  the document begins the two lines:
%---------
\usepackage{fontspec}
\setmainfont{Times New Roman}
%---------
\begin{document}

3. Commented, by adding % symbol at the beginning of the following three lines in the TEX file to compile the PDF with the help of XeLaTex.

%\IEEEPARstart{T}{his} demo file is intended to serve as a ``starter file''
%for IEEE journal papers produced under \LaTeX\ using
%IEEEtran.cls version 1.8b and later.

4. Choose the right compiler to succeed
 Options - Configure Texstudio ... -  Build - Default Compiler - XeLaTex

**Comment by enxit** [comment]
The Short answer was found in the Documentation provided by the package:
http://mirrors.ctan.org/macros/latex/contrib/IEEEtran/IEEEtran_HOWTO.pdf

Include these three lines in the TEX file just before document begins:

\usepackage[T1]{fontenc} % optional
\usepackage{amsmath}
\usepackage[cmintegrals]{newtxmath}
\usepackage{bm} % optional

\begin{document}

**Comment by muzimuzhi** [comment]
> The default font is **Times New Roman**, and it display correctly on Texworks or Overleaf (figure attached below).

No, IEEEtran never used Times New Roman which is a commercial font, just some free Times family font shipped with TeX Live.

Compiling `bare_jrnl.tex` without any modifications, I get Times, not Computer Modern embedded into the resulting pdf.

```
$ pdffonts bare_jrnl.pdf
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
RDEFCO+NimbusRomNo9L-Regu            Type 1            Custom           yes yes yes      4  0
DPFNYU+NimbusRomNo9L-ReguItal        Type 1            Custom           yes yes yes      5  0
LREKMX+NimbusRomNo9L-MediItal        Type 1            Custom           yes yes yes      6  0
YYBHGV+NimbusRomNo9L-Medi            Type 1            Custom           yes yes yes      7  0
```

If TeXworks and TeXstudio gave different outputs on the same computer on the same [`bare_jrnl.tex`](http://mirrors.ctan.org/macros/latex/contrib/IEEEtran/bare_jrnl.tex), then perhaps you have two LaTeX distributions installed and the one used by TeXstudio lacked some font packages.

**Comment by eejyin** [comment]
Actually, this [answer](https://tex.stackexchange.com/a/698994/306315) is correct: should use pdflatex, not Xelatex.
