### ISSUE TITLE
MacOS 13 bug with the accent menu.

### ISSUE THREAD

**Issue by Mrlucastd** [texstudio-org/texstudio#3340]
### Environment
- TeXstudio:  4.6.3
- Qt:  6.5.2
- OS:  MacOS 13
- TeX distribution:  MacTeX

### Expected behavior
When I want to add an accent to my tex file, the MacOS accent menu is activated, but after typing, the letter appears twice with and without an accent. Example: eé instead of é.  

### How to reproduce
Hold down the key with the desired accent on the keyboard.

**Comment by muzimuzhi** [comment]
Reproducible on macOS 13.4.1, texstudio 4.7.0alpha2-10-gcc701cec1.

Some other text fields like the search bar in "Configure TeXstudio" window and description field in "Edit Macro" window don't have this problem.

https://github.com/texstudio-org/texstudio/assets/6376638/373e64b2-3c2b-49a2-8e47-b7c8f2a231f2

**Comment by sunderme** [comment]
the latest commit fixes the issue.
Please verify that it does not intefere with other language input methods.

**Comment by muzimuzhi** [comment]
I confirm the original issue is fixed with https://github.com/texstudio-org/texstudio/commit/2fb5223ef8ab85947057162be135f3e71557edd1, and at least the macOS' built-in Chinese input source "Pinyin - Simplified" is still working.
