### ISSUE TITLE
eps. documents can't be imported

### ISSUE THREAD

**Issue by StarSage** [texstudio-org/texstudio#3341]
xdvipdfmx:fatal: Image inclusion failed for "model1case1new.eps" (page=1). No output PDF file written.
xelatex.exe: fwrite: Invalid argument

**Comment by muzimuzhi** [comment]
Not TeXstudio's fault, which is just an editor. You should be able to reproduce the same error by running `xelatex` in terminal yourself.

BTW, do you have ghostscript installed?

**Comment by StarSage** [comment]
The same error hasn't appeared when i use texlive to edit it.
i have  installed ghostscript, but this issue still can't work out.

> Not TeXstudio's fault, which is just an editor. You should be able to reproduce the same error by running `xelatex` in terminal yourself.
> 
> BTW, do you have ghostscript installed?

**Comment by muzimuzhi** [comment]
> The same error hasn't appeared when i use texlive to edit it.

If you have only one LaTeX distribution (neither two different dists nor different releases of the same dist) installed, then the programs from that distribution are used by TeXstudio too. TeXstudio, as an editor, doesn't provide any LaTeX programs.

Is your problem reproducible with a minimal example? When compiling with pdflatex? When using another editor? Was your  TeXstudio configured to using `-output-directory` or similar setting? There're so many possibilities...

**Comment by StarSage** [comment]
I was successful with TeXwork editor in texlive,  using Xelatex to compile it. But with texstudio I got an error, which is linked to texlive. TeXstudio is configured to using its own Xelatex,  and I connect them in Commands.
I think it's possible that ghostscript haven't been imported into texstudio.

**Comment by StarSage** [comment]
> I was successful with TeXwork editor in texlive, using Xelatex to compile it. But with texstudio I got an error, which is linked to texlive. TeXstudio is configured to using its own Xelatex, and I connect them in Commands.
> I think it's possible that ghostscript haven't been imported into texstudio.



> > The same error hasn't appeared when i use texlive to edit it.
> 
> What did you mean in "use texlive to edit it", the TeXwork editor?
> 
> If you have only one LaTeX distribution (neither two different dists nor different releases of the same dist) installed, then the programs from that distribution are used by TeXstudio too. TeXstudio, as an editor, doesn't provide any LaTeX programs.
> 
> Is your problem reproducible with a minimal example? When compiling with pdflatex? When using another editor? Was your TeXstudio configured to using `-output-directory` or similar setting? There're so many possibilities...

**Comment by StarSage** [comment]
> > The same error hasn't appeared when i use texlive to edit it.
> 
> What did you mean in "use texlive to edit it", the TeXwork editor?
> 
> If you have only one LaTeX distribution (neither two different dists nor different releases of the same dist) installed, then the programs from that distribution are used by TeXstudio too. TeXstudio, as an editor, doesn't provide any LaTeX programs.
> 
> Is your problem reproducible with a minimal example? When compiling with pdflatex? When using another editor? Was your TeXstudio configured to using `-output-directory` or similar setting? There're so many possibilities...

I was successful with TeXwork editor in texlive, using Xelatex to compile it. But with texstudio I got an error, which is linked to texlive. TeXstudio is configured to using its own Xelatex, and I connect them in Commands.
I think it's possible that ghostscript haven't been imported into texstudio.

**Comment by sunderme** [comment]
looks like this has nothing to do with txs.

**Comment by wzx0202** [comment]
> xdvipdfmx:fatal: Image inclusion failed for "model1case1new.eps" (page=1). No output PDF file written. xelatex.exe: fwrite: Invalid argument

StarSage May I ask if you have solved this problem? I encountered the same error and tried many methods but couldn't solve it.
