### ISSUE TITLE
files with many \input's take prohibitively long to open

### ISSUE THREAD

**Issue by mbertucci47** [texstudio-org/texstudio#3347]
### Environment
- TeXstudio: 4.7.0alpha3
- Qt: 6.5.3
- OS: Windows 10
- TeX distribution: texlive

Files with many other files `\input` or `\include`d take an exceptionally long time to open. For some files, in practice this means they cannot be opened. For example, if I try to open the doc file `tcolorbox.tex` from my texlive distribution, TXS stays in a perpetual state of "Not responding". You can find the file on CTAN [here](http://mirrors.ctan.org/macros/latex/contrib/tcolorbox/tcolorbox.tex), though it might be important to open it with all the `\include`d files present in the same directory.

Interestingly, it also takes a very long time to open one of the included files by itself, e.g. `tcolorbox.doc.verbatim.tex`.

A similar thing happens when very long, self-contained files are opened. I opened an issue about this [previously](https://github.com/texstudio-org/texstudio/issues/2856#issue-1538463345) and it was fixed, but there seems to have been a regression (perhaps related to the caching changes?). The example from that issue, [`glossaries-user.tex`](http://mirrors.ctan.org/macros/latex/contrib/glossaries/glossaries-user.tex), takes 5 minutes to open on my machine.

**Comment by sunderme** [comment]
first one is fixed
the other files open fine, i will look if they should open faster.
