### ISSUE TITLE
%specialDef key completion broken

### ISSUE THREAD

**Issue by mbertucci47** [texstudio-org/texstudio#3349]
### Environment
- TeXstudio: 4.7.0
- Qt: 6.6.0

### Expected behavior
The `%specialDef` marker in the arg of a command in a cwl should add that arg to a list that can be used for key completion in other commands.

### Actual behavior
This is currently not working. The example below shows this. You can also see it with colors:
```
\definecolor{blub}{}{}
\color{}
```
"blub" does not show up in the arg completion for `\color`.

#### cwl
```
# mypkg.cwl
\mycmd{arg%specialDef}#s#%mykeys
\anothercmd{keyvals}

#keyvals:\anothercmd
foo
%mykeys
#endkeyvals
```
#### tex file
```
\documentclass{article}
\usepackage{mypkg}

\begin{document}

\mycmd{blub}

\anothercmd{}

\end{document}
```
#### Screenshot
<img width="384" alt="nokeycompletion" src="https://github.com/texstudio-org/texstudio/assets/61854785/a3e30390-37cb-4d77-8582-36e821834e70">

**Comment by sunderme** [comment]
fixed
