### ISSUE TITLE
Select characters/lines with shift + arrows

### ISSUE THREAD

**Issue by jczhang07** [texstudio-org/texstudio#335]
I use Texstudio on Mac. When I edit text, I find it is difficult to do selection without mouse. 

One usually uses shift + arrows to select characters/lines starting from the cursor position, for example, in Notepad, MS Word, etc. But I find this common shortcut does not work in Texstudio. 

I know I can select word/line with Command + D/L, but that is too limited.

**Comment by sunderme** [comment]
selecting text via shift+arrow works fine here.
Which version of txs ? Which version of OSX ?

**Comment by jczhang07** [comment]
I have 
TeXstudio 2.12.10 (git 2.12.10), Using Qt Version 5.11.1, compiled with Qt 5.11.1 R
MacOS High Sierra, 10.13.6

Thanks.
