### ISSUE TITLE
 How to get TeXStudio Path's automated in TeXStudio?

### ISSUE THREAD

**Issue by Pter2023** [texstudio-org/texstudio#3350]
### Environment
- TeXstudio: 4.2.3
- Qt: 
- OS:Debian 12
- TeX distribution: texlive

### Description
As a newbie.
I downloaded texlive, also TexStudio. My question is: is there an automatic fill in of all the required date (PATHS) in TexStudio?
Pter2023

**Comment by sunderme** [comment]
latex should be in your PATH variable, hence there is no need for texstudio to know exact paths.
