### ISSUE TITLE
Add support to rich text editor like Overleaf

### ISSUE THREAD

**Issue by viocha** [texstudio-org/texstudio#3351]
### Describe the feature and the current behavior/state
In a rich text editor, some of the Latex code will be rendered, which helps to preview the document in advance and reduce the number of compilations.
![image](https://github.com/texstudio-org/texstudio/assets/66580331/71fcc060-590d-407e-a2df-a19ccda20d03)
![image](https://github.com/texstudio-org/texstudio/assets/66580331/70574f92-97a6-4382-9741-17707feb3aa9)

### Any Other info
the link to the file and online editor: https://www.overleaf.com/read/ctsjxhwgjdvk#4f869c

**Comment by octaeder** [comment]
This was discussed some time ago (5 years), s. #333.

**Comment by sunderme** [comment]
There is no intention to change the scope of txs.
