### ISSUE TITLE
Txs doesn't hide mouse pointer when typing

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3353]
### Environment
- TeXstudio: current dev
- Qt: Qt 6.5.3
- OS: Windows 10
- TeX distribution: miktex

In Win 10 you can change the pointer options of the Mouse properties. I set up that the pointer gets hidden when I start typing. But this doesn't apply when typing in txs. Why?

**Comment by sunderme** [comment]
if qt does not do it automatically, txs does not support it.
