### ISSUE TITLE
crash on changing location of files

### ISSUE THREAD

**Issue by goyalyashpal** [texstudio-org/texstudio#3356]
### Environment
- TeXstudio: 4.6.3 R
- Qt: 6.5.2 
- OS: win 10 22H2
- TeX distribution: miktex

### Expected behavior

no crash

### Actual behavior

crash

stacktrace:

```log
unknown at 7ff7062f2854 (TXS-Version 4.6.3 R )
```

![image](https://github.com/texstudio-org/texstudio/assets/19423063/93b0fda4-85cd-4489-9e06-2bea501b14a7)

### How to reproduce

* open a file in txs, set it as root
* enable "monitor open files" and "silently reload" at < advanced editor < configure texstudio < options 
* change the location of the file from outside txs
* navigate back to txs
* choose "ignore" for all open files in the txs' file changed/removed dialog

**Comment by sunderme** [comment]
I can't reproduce. 
Have you checked that it really leads to a crash with a single document.
If not, please publish a complete example file(s).

**Comment by goyalyashpal** [comment]
hi! thanks a lot for trying.

> If not, please publish a complete example file(s).

i will do within 2-3 days.

**Comment by sunderme** [comment]
you can reopen the issue when you provide the example
