### ISSUE TITLE
spellcheck magic comment is ignored in subdocuments in TS 4.7.0

### ISSUE THREAD

**Issue by lashkevi** [texstudio-org/texstudio#3358]
Spellcheck magic comment ("% !TeX spellcheck = ...") is ignored in subdocuments (i.e. parts added by the \include command). en_US is used instead.

### Environment
- TeXstudio: 4.7.0
- Qt: 5.15.10
- OS: Linux, OpenSUSE 15.4 (texstudio-4.7.0-lp154.2.1.x86_64)
- TeX distribution: texlive

### Expected behavior

Spellchecking according to the magic comment.

### Actual behavior

Spellchecking for en_US.

### How to reproduce

1. Create a document consisting of the master file and subdocuments.
2. Open all of them.
3. Set spellcheck to a language other than English US and create the corresponding magic comment in the main document and the subdocuments.
4. Close all and open again.

You see that the spellcheck is set to en_US in every tab except the master file.
![Screenshot_20231107_004358](https://github.com/texstudio-org/texstudio/assets/13115223/cab6a3d0-bafd-41a2-b17e-d6a8ca49d2cd)

**Comment by sunderme** [comment]
not reproducible.
The active spellcheck language is the one shown in the status bar (en_US in your case).
The active language changes (here) when switching tabs with different magic comments.

**Comment by lashkevi** [comment]
_My_ magic comments are ru_RU in _every_ file. But in the master file it takes effect: the active spellcheck language is ru_RU:
![Screenshot_20231108_011037](https://github.com/texstudio-org/texstudio/assets/13115223/177bd69f-f94a-43b2-8a18-77d94cbb9cf3)
while in the included files it does not take any effect:
![Screenshot_20231108_011256](https://github.com/texstudio-org/texstudio/assets/13115223/8b361dc6-5b21-4abf-9013-6f2e4edbc220)

**Comment by lashkevi** [comment]
I want to stress that I never had such an issue in the previous versions of TS, and that I did not make any changes in configuration. I just closed my files, updated TS from 4.6.3 to 4.7.0 and reopened the session.

**Comment by sunderme** [comment]
can't reproduce
please provide step by step instruction with files to let me reproduce the issue.

**Comment by lashkevi** [comment]
> can't reproduce please provide step by step instruction with files to let me reproduce the issue.

I attach here a minimal check. It consists of a master file "x.tex", a subdocument "y.tex", a session file "x.txss2" and the results of compilation. Please, unpack the archive and open "x.txss2".
[ts-test.tar.gz](https://github.com/texstudio-org/texstudio/files/13300957/ts-test.tar.gz)

**Comment by sunderme** [comment]
I have seen the issue once or twice, but it is not reliable the case and rather seldom. Is this the case on your side as well ?

**Comment by lashkevi** [comment]
> I have seen the issue once or twice, but it is not reliable the case and rather seldom. Is this the case on your side as well ?
For me it occurs every time I open such multipart documents. At least from a session file.

**Comment by lashkevi** [comment]
> apparently document caching is disabled on user side.

What means "document caching"?
