### ISSUE TITLE
Autocompletion for files in user texmf tree

### ISSUE THREAD

**Issue by jchampavere** [texstudio-org/texstudio#336]
TeXstudio does not provide autocompletion for files located in user texmf tree. Assume I have some ~/texmf/tex/latex/mydirectory directory with some files, e.g., myfile.tex which loads packages and/or provide new commands. When using \input{myfile} in preambule of some test.tex file (not located in ~/texmf, of course), TeXstudio won't recognise any command from myfile.tex, nor command from packages myfile.tex would load. This does not affect the compilation of test.tex, but it can be annoying to edit this file without the expected autocompletion.

This has already been pointed at https://sourceforge.net/p/texstudio/feature-requests/634/ but I could find no good solution to this trouble. I have to symlink or copy/past files in ~/texmf tree, which I would rather not to do…

### Environment
- TeXstudio: 2.12.10
- Qt: 5.9.5, compiled with Qt 5.7.1 R
- OS: Linux Mint 19
- TeX distribution: TeX Live

### Expected behavior

Autocompletion when \input files located in ~/texmf tree.

### Actual behavior

No autocompletion.

### How to reproduce

See description above. I will provide MWE if needed.

**Comment by sunderme** [comment]
txs distinguishes between "included" tex files which are (typically) automatically loaded, analyzed and used for completion/syntax check and "packages" in texmf directories. Those are handled via cwl files (see wiki/manual for details). So, you can either copy the included file next to your main document or you can generate/write a cwl file and put it into ~/.config/texstudio/completion/user and activate it via options/completion (since package detection only works with \usepackage{...} )

**Comment by jchampavere** [comment]
Thanks for the answer.
Should one rename myfile.tex to myfile.sty to get a "regular" package filename?
Is it possible to automatically generate such .cwl file from the .tex/.sty source file?
Why autocompletion when including myfile.tex from ~/texmf tree can not be handled as including it next to the main document?

**Comment by sunderme** [comment]
txs scans all packages (.sty) which are given in a \usepackage-command and which can be found via "kpsewhich packagename". It generates a simplified cwl and puts it in ~/.config/texstudio/completion/autogenerated. The main issue is that it uses the content only for syntax checking, not for completion as automated argument detection is unreliable, see manual/wiki.
However that file is a good start for adaptation.

**Comment by jchampavere** [comment]
Thanks again for your answer. Renaming (or simlinking) myfile.tex to myfile.sty located in ~/texmf, then loading it with \usepackage{myfile} generates myfile.cwl to ~/.config/texstuio/completion/autogenerated. It's indeed a good starting point to write/complete such a cwl file.

But it lacks for commands declared with \DeclareSIUnit from siunitx package, for instance, and probably many other features I should get when simply including the file with \input. That's why I would still request for such feature in txs. To sum up, the main reasons are :

- If txs is able to handle autocompletion for files included with relative path, it should be able to do the same for files included with "absolute" ~/texmf path.

- I should not have to consider a .tex as a .sty file.

- Writing a fonctional .cwl file makes sense only for classes or "real" packages, not for "personal" config files.

I hope my view is clear.

**Comment by dbitouze** [comment]
>But it lacks for commands declared with `\DeclareSIUnit` from `siunitx` package

Aside remark: for this, it is enough to add `#include:siunitx` in the `.cwl` file.

**Comment by sunderme** [comment]
txs uses on linux the tex database for recognizing packages, I assume that ~/texmf is not part of that database.

The declared commands would need to be add by hand into the cwl then.

**Comment by jchampavere** [comment]
Maybe txs could have an option to let the user add paths like ~/texmf to be parsed in the same way as the regular TeX-distribution tree? Again, in my opinion, txs should be able to handle user files stored anywhere, since it can do it for files located in relative directories.

**Comment by dbitouze** [comment]
@sunderme `~/texmf`, the default `TEXMFHOME`, is by default searched by TeX (see https://www.tug.org/texlive/doc/texlive-en/texlive-en.html#x1-110002.3).

**Comment by sunderme** [comment]
yes, but not via the ls-R file database, which is used by txs to check which packages are available.

**Comment by sunderme** [comment]
so, concerning the original issue, can we close it as there is a way to handle it ? (cwl )

**Comment by dbitouze** [comment]
>yes, but not via the ls-R file database, which is used by txs to check which packages are available.

By default, `$TEXMFVAR` and `$TEXMFHOME`'s folders are parsed by TeX. Maybe TXS could have the same behavior.

**Comment by sunderme** [comment]
if txs wants to be fast, it can't

**Comment by jrmoserbaltimore** [comment]
@sunderme LyX parses ~/.texmf on Windows and Linux.  TeXStudio could eaily run an ls-R and cache it itself.  Often there are few files in ~/.texmf anyway.

Without this feature, txs seems to struggle to be a TeX editor.  It constantly highlights syntax errors that aren't errors, so isn't much better than using Notepad.

LyX uses its own format, and I'd rather convert back to TeX.  txs could provide an option to disable this if you think it's going to cause problems.
