### ISSUE TITLE
Key/option autocompletion exits after typing in a space

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#3362]
### Environment
- TeXstudio: 4.7.0beta1
- Qt: 6.6.0
- OS: macOS 13.4.1
- TeX distribution: irrelevant

### Expected behavior

When typing in a key containing space(s), hit space continues autocompletion.

### Actual behavior

The autocompletion exits immediately after typing in a space.

### How to reproduce

To use tikz option `line width=1pt`, type in "line" and the autocompletion pops and reduces normally, then hit space. The autocompletion exits.

https://github.com/texstudio-org/texstudio/assets/6376638/7b0bf6a5-9ca4-47e7-b78f-58786cab18c1

```tex
\documentclass{article}
\usepackage{tikz}
% type in "line", then hit space
\tikzset{}

\begin{document}
content
\end{document}
```

**Comment by octaeder** [comment]
(maybe as a workaround) enter space as `ctrl+space`

**Comment by octaeder** [comment]
This workaround shows a further problem: when you then type `w` then the completer positions on `line width=`. But now pressing `ctrl+space` inserts `white`.

**Comment by octaeder** [comment]
Fix is ok from my side, thanks.
