### ISSUE TITLE
Commands/Envs become unrecognized after irrelevant changes

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#3364]
### Environment
- TeXstudio: 4.7.0beta1
- Qt: 6.6.0
- OS: macOS 13.4.1
- TeX distribution: latest basicTeX 2023

### Expected behavior

When package A is loaded, commands or environments provided by package A are always recognized.

### Actual behavior

Specific changes will make the highlighting changes as if package A is no longer loaded.

### How to reproduce

In example below, delete the second line `\usepackage{amsmath}`, then undo the change. `\includegraphics` from `graphicx` package will become unrecognized.

Commenting then uncommenting line `\usepackage{graphicx}` solves the problem.

```tex
\documentclass{article}
\usepackage{amsmath}
\usepackage{graphics}

\begin{document}
\begin{align}
  content
\end{align}

\includegraphics{example-image}
\end{document}
```

https://github.com/texstudio-org/texstudio/assets/6376638/d663a68d-c90d-4765-bb01-7496351917d1

**Comment by sunderme** [comment]
fixed
