### ISSUE TITLE
Unexplainable error turns up repeatedly, and program crashes sometimes

### ISSUE THREAD

**Issue by foerster-rwth** [texstudio-org/texstudio#3365]
### Environment
- TeXstudio: 4.6.3
- Qt: 6.5.2
- OS: Windows 10 Education, version 22H2
- TeX distribution: Miktex

### Expected behavior

No error, no crashes.

### Actual behavior

I keep getting the error "You can't use `\prevdepth' in horizontal mode.", and I cannot fathom why.

Sometimes the program just disappears in the middle of writing.

### How to reproduce

I do not know how to reproduce these behaviours, therefore I am posting this report primarily as information that something may be wrong with TeXstudio.

The prevdepth error is weird: I compile, and all is well. I write a couple of lines of plain text, compile again and get the error. I write a few lines more, compile, and all is well again. I then delete what I just wrote, and the error returns upon compiling.

I have no idea how a document that compiles ok can then produce an error after the deletion of a bit of plain text.

The document I am working on has 12 chapters and about 170 pages.

Furthermore: the program has recently crashed a few times, just disappearing from the screen.

I have noticed today that version 4.6.0 introduced a file caching feature, followed by a quick succession of bugfix releases. This looks as if the new feature -- or subsequent attempts at fixing the bugs that it had or precipitated -- may have led to problems elsewhere.

I am now reverting to version 4.5.2.

**Comment by octaeder** [comment]
You may check what happens when you disable file caching here:
![image](https://github.com/texstudio-org/texstudio/assets/102688820/847b9ffa-f6ee-4ed7-90e4-3c0d1dbad2af)

**Comment by foerster-rwth** [comment]
Hi, thanks for your quick reply!

I have tried versions 4.5.2 and 4.5.1, and they produce the same prevdepth error. Therefore I think the fault may not be attributable to TeXstudio, or at least it wasn't recently introduced. 

I also have experimented a bit as follows:

- prevdepth error turns up.
- I write a further paragraph with a few words only.
- Compile.
- No error.
- I delete the new paragraph.
- Compile.
- prevdepth error returns.
- Instead of a normal paragraph I now insert two lines of text that are commented out (!!).
- Compile.
- No error.

Whenever the error appears, the document gets an additional blank page a few pages further down in the chapter that I'm currently writing.

I'm at a loss. I don't wish to bother you, but if you have any idea what might cause this remarkable behaviour, I'm all ears.

At least I know now that inserting just a bit of text that is commented out "fixes" the bug. That's a relief.

**Comment by foerster-rwth** [comment]
UPDATE >> I've found the culprit!

It's afterpage. I've got an \afterpage{clearpage} statement at about the place where the empty page is inserted when the prevdepth error happens. If I comment this statement out, the error disappears.

Thanks for your help, and to all of you for a fab program!

**Comment by sunderme** [comment]
this report mixes issues.
The main issue seems to be a compiling/latex question which has (probably) nothing to do with txs.

The only thing relevant here are potential crashes.
Not sure whether the reporter was using latest txs version, but that would be the first step, potentially checking out current beta.
Especially for crashes, some hint what leads to a crash is imperative.
