### ISSUE TITLE
Menus show up on secondary monitor

### ISSUE THREAD

**Issue by tgrohser** [texstudio-org/texstudio#3369]
### Environment
- TeXstudio:  4.6.3 (git 4.6.3)
- Qt:  Qt Version 6.5.2, compiled with Qt 6.5.2 R
- OS:  Windows(11
- TeX distribution:  miktex

### Expected behavior
Menu opens on the screen the application runs

### Actual behavior
Menu opens on the secondary monitor at the exact location it should open on the monitor running the application. If i move it to the other screen it works as expected. It does not do this on my second system. The only difference I see is that on the system with the issue the two monitors are identical (resolution, make and model) while on the one it works they are from different manufacturers and have different resolution.

### How to reproduce

All i have to do is open a menu (either the main window or a context menu (right click)

**Comment by octaeder** [comment]
Please try one of the artifacts of the latest dev build (for example portable version):

[https://github.com/texstudio-org/texstudio/actions/runs/6853856939](https://github.com/texstudio-org/texstudio/actions/runs/6853856939)

**Comment by sunderme** [comment]
duplicate #3316
