### ISSUE TITLE
Previewer fails for indirect dependencies. 

### ISSUE THREAD

**Issue by kbauer** [texstudio-org/texstudio#337]
Inline preview fails, if the file includes indirect inputs from the current directory.

### To reproduce

  - Create the following files:
```
%% file: document.tex
\input{preamble.inc}
\begin{document}
\begin{equation}
  \rr T
\end{equation}
\end{document}

%% file: preamble.inc
\documentclass{article}
\usepackage{localpackage}

%% file: localpackage.sty
\ProvidesPackage{localpackage}
\def\rr{\mathbf{r}}
```
  - Open document.tex and try to preview the equation.
    ![image](https://user-images.githubusercontent.com/7498468/46219193-f75d1600-c346-11e8-8f77-aa77ddc2c877.png)

### Actual Behaviour
  - In the Messages pane, compilation errors are reported.
    ![image](https://user-images.githubusercontent.com/7498468/46219295-45721980-c347-11e8-8877-ea1a3c9b7d3b.png)
  - The corresponding logfile in the TEMP directory reads:
    ```
    ! LaTeX Error: File `localpackage.sty' not found.
    ```

### Cause
For previewing a file
```
\input{C:/tmp/preview/preamble.inc}
\usepackage[active,tightpage]{preview}
\usepackage{varwidth}
\AtBeginDocument{\begin{preview}\begin{varwidth}{\linewidth}}
\AtEndDocument{\end{varwidth}\end{preview}}
\pagestyle{empty}
\begin{document}
\begin{equation}
  \rr T
\end{equation}
\end{document}
```
was created, i.e. `\input` forms have absolute paths inserted.

This approach is however limited; It came up here, because I was reusing a preamble across multiple files, this creating indirect `\input`s of local files through the shared preamble file, but the same issue occurs when using the `\subfiles` documentclass to inherit the preamble, when trying to preview equations in the subfile.

```
%% file: subfile.tex
\documentclass[mainfile]{subfiles}
\begin{document}
\begin{equation}
  \rr T
\end{equation}
\end{document}

%% file: mainfile.tex
\documentclass{article}
\def\rr{\mathbf{r}}
\begin{document}
content...
\end{document}
```

I.e. the current approach fails whenever an unexported input behavior is encountered.

### Possible solution

Instead of processing the arguments of the `\input` command, it might be better to add the document root directory as first entry of `TEXINPUTS`.

### User-Level Workaround

It may be possible to fix the preview in some cases, by explicitly declaring the root directory with ```\def\input@path{{/path/to/folder/}}```. This however comes with its own pitfalls (e.g. handling of paths with spaces).

### Environment
- TeXstudio: 2.12.10
- Qt: Qt Version 5.8.0, compiled with Qt 5.8.0 R
- OS: Windows 10 (winver 1803)
- TeX distribution: Miktex

**Comment by kbauer** [comment]
That's surprising then – if TEXINPUTS is changed, I don't see how <code>`localpackage.sty' not found.</code> can happen.

**Comment by sunderme** [comment]
since all previews are compiled in /tmp (or similar on windows), txs already substitutes some relative filenames with absolute ones. I really don't see the feasibility to support any kind of "uncommon" document set-up and try to invent a logic which fails sooner or later again. 
So, long story short, you need to make sure that any packages, you use, are available for a tex-file which is compiled in /tmp. Automated logic can only go so far ...

**Comment by kbauer** [comment]
> > Instead of processing the arguments of the \input command, it might be better to add the document root directory as first entry of TEXINPUTS.
> 
> It does that. But many commands ignore TEXINPUTS

It checked by wrapping pdflatex into a script, that dumps TEXINPUTS into the logfile while generating the preview and found that TEXINPUTS is *not* changed for generating previews.

For the previous comment I assume it is supposed to be?

**Comment by kbauer** [comment]
@sunderme I was referring to https://github.com/texstudio-org/texstudio/issues/337#issuecomment-425555704 by @benibela. 

As I understand, the previewer is supposed to set up TEXINPUTS to include the root directory of the document. I did however find, that it doesn't on my work system.

Closer inspection showed, that given a document `E:\docroot\document.tex`

  - If TEXINPUTS *is not* set globally, the preview compiler will set it to `E:\docroot;.;`
  - If TEXINPUTS *is* set globally, the preview compiler will *not change it*.

That latter part seems like a bug to me; It would make more sense to prepend `E:\docroot` to the global value of TEXINPUTS in this case.

**Comment by benibela** [comment]
Perhaps the global setting overrides it after texstudio has set it?

**Comment by sunderme** [comment]
since we are not fixing the opriginal issue, I close this ticket
