### ISSUE TITLE
problem with '\underbrace'

### ISSUE THREAD

**Issue by TomBim** [texstudio-org/texstudio#3370]
### Environment
- TeXstudio: 4.6.3
- Qt: 6.5.2
- OS: Windows 10 Pro
- TeX distribution: miktex

### Expected behavior
\underbrace{ }
Delete the close bracket "}"

#### Screen

![image](https://github.com/texstudio-org/texstudio/assets/43795382/10132686-6095-45fa-83d5-0e57f3339b09)

#### My code

```
\begin{equation}
	\vec{v_w}(t_0+T) =
	\underset{\mtx{A}}{\underbrace{\exp{\left( T \mtx{F} \right)}}} \vec{v_{w0}} +
	\underset{\mtx{B}}{\underbrace{ \left\{
			\left[ \mtx{I_4} - \exp{(T \mtx{F})} \right]
			k \mtxInv{C}{V} \right]}} \right\}
		\vec{u},
\end{equation}
```
For the last \underbrace, when I try to delete its close bracket, '}', the program just crashes.

### How to reproduce

Delete the close bracket of the second '\underbrace'

**Comment by octaeder** [comment]
I can't reproduce with 4.6.3 nor with current dev. I suggest testing latest dev with your document. I assume that in the following image the character to the left of the cursor mark should be deleted. Anyway, I can delete any of those or all with backspace or del.

![image](https://github.com/texstudio-org/texstudio/assets/102688820/2c0f6cdf-3c4d-4ed9-876d-f572b77622ad)

Maybe we need your document or a cut down that can reproduce the issue.

**Comment by sunderme** [comment]
have you checked that your example without further lines does actually crash?

**Comment by TomBim** [comment]
1. Well, apparently, it is extremely important for the part `\right\}` to reproduce the error.
2. Without the further lines, it stops crashing.
3. Without the lines before, it still crashes.

Try with these lines:

```
\begin{equation}
	\label{eq:stateEq:ZOH}
	\vec{v_w}(t_0+T) =
	\underset{\mtx{A}}{\underbrace{\exp{\left( T \mtx{F} \right)}}} \vec{v_{w0}} +
	\underset{\mtx{B}}{\underbrace{ \left\{
			\left[ \mtx{I_4} - \exp{(T \mtx{F})} \right]
			k \mtxInv{C}{V} \right\} }} \right\}
		\vec{u},
\end{equation}
that we can rewrite as:
\begin{equation}
	\label{eq:myxt}
	\vec{v_{w,t}} = \mtx{A} \vec{v_{w,t-1}} + \mtx{B} \vec{u_t}.
\end{equation}

Note that we got a linear equation.


%____________________________________________________________________________
%l																			l
%l						**		NOISE xt		**							l
%l__________________________________________________________________________l

\begin{equation}
	\label{eq:myxtnew}
	\vec{\omega_t} = \mtx{A} \vec{\omega_{t-1}} + \mtx{B} \vec{u_t} + \vec{\epsilon_t},
\end{equation}


%____________________________________________________________________________
%l																			l
%l						**		OBS MODEL		**							l
%l__________________________________________________________________________l

```

Obs.:

1. If I remove any of those comment sections, it stops crashing
2. This equation between the comments is also relevant for some reason
3. The text outside the equations remaining is also important

I find it pretty interesting how relevant these conditions are, although they seem harmless at first sight. Kind of... why does the comment is important??? lol

Anyway, I tried to filter out the lines that don't change the outcome. These lines seem very important to reproduce the bug.

Hope you can do it now

**Comment by sunderme** [comment]
what usepackages are used or do you set completion files in options ?

**Comment by sunderme** [comment]
and just to be perfectly clear.
You open txs with no documents, open one document with the text above.
You delete the brace at line 7, column 37 and it crashes ?

**Comment by TomBim** [comment]
I just want to say that I am a little busy these days, so I won't have a lot of time to test a lot of things.

But when I have more time I will test what it needs to reproduce the error. 

Since this file is imported by other files, the problem is a little bigger than I thought.

Anyway, I wanted to say this so you don't think I am not reading this...

**Comment by TomBim** [comment]
I import several packages, I will make a list after...

Actually, you have to delete both because if you delete only one, it understands that you deleted underset's close bracket. I don't know if this was clear... but needs deletion of both 37 & 38.

But if I open a new document and paste the code, it doesn't crash. So I will need to see what is useless for reproducing the bug.

**Comment by sunderme** [comment]
You can send the complete document to me directly (sunderme@gmx.de) for debugging to keep it private.

**Comment by sunderme** [comment]
insufficient information for reproducing
