### ISSUE TITLE
SIGSEGV error after some seconds

### ISSUE THREAD

**Issue by 945fc41467** [texstudio-org/texstudio#3373]
### Environment

TeXstudio 4.6.3 (git 0.0.0++)
Utilise Qt version 6.6.0, compilé avec Qt 6.5.2 R
System:
  Kernel: 6.1.62-1-MANJARO arch: x86_64 bits: 64 compiler: gcc v: 13.2.1
  Desktop: GNOME v: 45.1 tk: GTK v: 3.24.38 wm: gnome-shell dm: GDM v: 45.0.1
    Distro: Manjaro Linux base: Arch Linux

### Expected behavior

Nothing.

### Actual behavior

After some actions a prompt appear saying a SIGSEGV error happened and asking if I want to continue or to close the program.

```bash
$ texstudio
crashed with signal SIGSEGV
SIGSEGV (TXS-Version 0.0.0++ R )
SIGSEGV (TXS-Version 0.0.0++ R )
SIGSEGV (TXS-Version 0.0.0++ R )
SIGSEGV (TXS-Version 0.0.0++ R )

[bt] texstudio(_Z15print_backtraceRK7QString+0x4) [0x556f6a441254]
[bt] texstudio(_Z15print_backtraceRK7QString+0x4) [0x556f6a441254]

"/tmp/texstudio_backtrace1.txt"
crashed with signal SIGSEGV
SIGSEGV (TXS-Version 0.0.0++ R )
SIGSEGV (TXS-Version 0.0.0++ R )
SIGSEGV (TXS-Version 0.0.0++ R )
SIGSEGV (TXS-Version 0.0.0++ R )

[bt] texstudio(_Z15print_backtraceRK7QString+0x4) [0x556f6a441254]
[bt] texstudio(_Z15print_backtraceRK7QString+0x4) [0x556f6a441254]

"/tmp/texstudio_backtrace2.txt"
"Current: 0/0"
Killed on user request after error: SIGSEGV
```

### How to reproduce

No pattern identified. It can happen more or less quickly. Sometimes I can compile. Sometimes it crash before. Just start working and it should happen. Generally you don’t need to wait more than one minute.

**Comment by sunderme** [comment]
the stacktrace is unfortunately not helpful.
Please compile txs locally (https://github.com/texstudio-org/texstudio/wiki/Compiling) and run in a debugger (or use qtcreater if possible)

**Comment by sunderme** [comment]
only seen on arch, nothing I can do.
If the gdb backtrace uncovers something in txs, please report here.
