### ISSUE TITLE
How to switch between structure pane and editor?

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3376]
### Describe the feature and the current behavior/state
I often autocomplete the label command, i.e. I see \label{key} with placeholder key selected in the editor. Then I open the label list in the structure pane with a mouse click to check which labels are already used (since autocomplete shows no list as discussed earlier). Then I want to go back to the editor to fill the placeholder. I expected some tab key action or a mouse click on the editor tab to bring focus back to the editor/placeholder. The first way needs 16 tab keys, depending on the number of drop down boxes available below the menu bar. But I can't notice for each tab where the focus goes to. The latter doesn't work at all. Is there a quick way to achieve the desired result? The one I found is a double click on the placeholder.

More generally spoken: After clicking on a structure item how can I come back to the editor without changing cursor/selection in the text? Both, a click action on the tab and a key action would be nice.

### Who will benefit with this feature?
Anyone using labels

**Comment by muzimuzhi** [comment]
Tested in 4.7.0beta2, menu "View / Focus Editor" seems to work, although cursor is not blinking after that.

**Comment by octaeder** [comment]
Thanks for the hint. Thought this is for switching from the pdf viewer. For me both the menu item and its shortcut ctrl+alt+left work. Even so, shouldn't clicking on the editor tab give focus back to the editor? Seems to be quite natural.
