### ISSUE TITLE
Structure panel is empty in 2.12.10

### ISSUE THREAD

**Issue by sensorhound-vinai** [texstudio-org/texstudio#338]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior
\section{Introduction}
\input{sections/intro}

The structure panel should populate this section.

### Actual behavior
The structure view is empty.  I didn't notice this issue before upgrading to 2.12.10. My previous version was 2.12.4.

**Comment by sunderme** [comment]
is option/completion/latex-document.cwl disabled ?
which OS ?

**Comment by sunderme** [comment]
no feedback

**Comment by arman00** [comment]
Hi @sunderme , I have the same problem. It happened with the version 2.12.10, although I was using the same version before without this problem. I have not used texstudio for about a month, then when I opened, the structure panel was completely empty. I also installed the last version, 2.12.12, but still the panel is empty with any tex file. I checked that option/completion/latex-document.cwl is enabled. Help is appreciated.

* TeXstudio: 2.12.12, 2.12.10
* Qt: Qt Version 5.9.5, compiled with Qt 5.9.5 R
* OS: Ubuntu 18.04, 4.15.0-38-generic #41-Ubuntu
* TeX distribution: TeX Live 2017/Debian

**Comment by sunderme** [comment]
looks okay
can you attach a screenshot of the issue

**Comment by arman00** [comment]
![screenshot from 2018-11-26 16-20-37](https://user-images.githubusercontent.com/23243866/49016489-513b5a00-f197-11e8-90a3-3c95ff778403.png)

**Comment by sunderme** [comment]
can you close txs, rename ~/.config/texstudio/texstudio.ini to ...bak in order to start with default settings ?

**Comment by arman00** [comment]
I did it, it works! Thanks!
Do you know the source of the problem? If possible, I would like the keep my config in that file by only modifying that problematic part to fix it

**Comment by sunderme** [comment]
if you can make a diff of the old and newly genrated texstudio.ini, i might find out...

**Comment by arman00** [comment]
Here it is. Thanks
diff texstudio.ini texstudio.ini.bak

[ini_diff.txt](https://github.com/texstudio-org/texstudio/files/2619463/ini_diff.txt)

**Comment by sunderme** [comment]
the culprit is "Symbols\hiddenlists=structureTreeView"
You hid the structure panel (right click on the symbols on the left hand side), no wonder nothing is shown ...

**Comment by arman00** [comment]
Oh I see, that simple, thanks for helping!
Since the structure title was always there even though it was hidden and the panel was empty, had never thought about it, am not familiar with that UI (Perhaps you can update the GUI so that it switches off the structure panel as soon as it is made hidden, showing the next enabled panel instead) . I had checked the view menu and other menus though to check if it is disabled or not (in many GUIs these kind of things are in the view menu). Thanks again
