### ISSUE TITLE
Preview lines are not removed near end of editor

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3393]
### Environment
- TeXstudio: current dev, 6.4.3
- Qt: 6.5.2
- OS: Win 10
- TeX distribution: miktex

### Expected behavior
Preview lines should be removed

### Actual behavior
![image](https://github.com/texstudio-org/texstudio/assets/102688820/4374bf6f-0c8b-4548-9010-56e2c75b8913)
![image](https://github.com/texstudio-org/texstudio/assets/102688820/cce7cc39-3d67-46bb-83cd-e325779d2b58)
![image](https://github.com/texstudio-org/texstudio/assets/102688820/e7606184-a042-4c61-8c26-2b5d679b95c4)

### How to reproduce
The point seems to be that the inline preview lines need space below last line of editor. In this case the lines are not removed immediately. If it's easy to fix, the fix would be welcome. Otherwise no issue.

**Comment by sunderme** [comment]
I have not seen that happen with current dev.
However the line numbers were not properly updated and that is fixed now.
