### ISSUE TITLE
texstudio 4.7.0 on macOS does not open files anymore

### ISSUE THREAD

**Issue by FloMiLe** [texstudio-org/texstudio#3395]
Texstudio 4.7.0 on macOS opens properly, but after that files cannot be opened in it. I have tried it from Finder and via the Open menu item.

### Environment
- TeXstudio: 4.7.0
- Qt: 6.6.1
- OS: macOS 14.1.2
- TeX distribution: MacTeX 2023

### Expected behavior

It is possible to open .tex files in texstudio.

### Actual behavior

Files do not open.

### How to reproduce

Open texstudio. Try to open a file.

**Comment by sunderme** [comment]
works fine on OSX 11.7

Have granted txs access to those files ?
OSX interferes heavily ...

**Comment by muzimuzhi** [comment]
Not reproducible on macOS 13.6.1. Relevant to macOS 14?

**Comment by sunderme** [comment]
can you try the 4.7 release candidates ?

**Comment by sunderme** [comment]
or the current dev build ?

**Comment by FloMiLe** [comment]
I have gone through all dmg releases:

texstudio-4.7.0alpha1-osx ➞ cannot be opened
texstudio-4.7.0alpha2-osx ➞ cannot be opened
texstudio-4.7.0alpha3-osx ➞ opens files, seems to work
texstudio-4.7.0alpha4-osx ➞ opens files, seems to work
texstudio-4.7.0alpha5-osx ➞ opens files, seems to work
texstudio-4.7.0beta1-osx ➞ opens files, seems to work
texstudio-4.7.0beta2-osx ➞ opens files, seems to work
texstudio-4.7.0rc1-osx ➞ opens files, seems to work
texstudio-4.7.0rc2-osx ➞ opens files, seems to work
texstudio-4.7.0rc3-osx ➞ opens files, seems to work
texstudio-4.7.0-osx ➞ does not open files

I'm sorry, but I don't know how to install a dev build.

**Comment by joeyfug** [comment]
Same issue as @FloMiLe , 
Same software configuration.   
Can't open and .tex files, OR the Preference window.
Revert to 4.6.3, and it works OK.

Then I tried TeXstudio 4.7.0 (git 4.7.0rc3), and it work fine!
Tried again the official release, and again, unable to open any file.

**Comment by sunderme** [comment]
dev build: https://github.com/texstudio-org/texstudio/actions/runs/7071311707

**Comment by sunderme** [comment]
Qt does officially not support osx 14...

https://doc.qt.io/qt-6/supported-platforms.html

**Comment by muzimuzhi** [comment]
See also [QTBUG-114315](https://bugreports.qt.io/browse/QTBUG-114315) Task related to supporting macOS 14 Sonoma, mentioned in a Qt blog [Qt on macOS 14 Sonoma](https://www.qt.io/blog/qt-on-macos-14-sonoma) posted shortly after Apple's WWDC 2023.

**Comment by sunderme** [comment]
I have checked on a intel mac with OSX 14.1.2 and there it works.

**Comment by FloMiLe** [comment]
> dev build: https://github.com/texstudio-org/texstudio/actions/runs/7071311707

Alright, I have tried this dev build, and that version does not open .tex files. I've gone back to texstudio-4.7.0rc3-osx, which seems to work fine.

Btw, I am using an Intel-based iMac running Sonoma 14.1.2.

**Comment by FloMiLe** [comment]
Using this version, I can open .tex files again!

**Comment by sunderme** [comment]
fixed in 4.7.1
