### ISSUE TITLE
Highlighting regular expression %TODO does not work correctly

### ISSUE THREAD

**Issue by betz-michael** [texstudio-org/texstudio#3398]
### Environment
- TeXstudio: 4.7.0
- Qt: 6.6.1
- OS: Windows 10)
- TeX distribution: miktex

### Expected behavior
With Version 4.6.3 every character after the %TODO key got highlighted for the whole document.

### Actual behavior
With Version 4.7.0 just the %TODO key before the \begin{document} command are highlighted.
Commenting out %\begin{document}, saving the file, opening it again, leads to all %TODO keys being highlighted.
The same behaviour occurs with other environment like \begin{figure}. %TODO keys in those environments are not highlighted after opening a .tex file.

Newly added %TODO keys are highlighted in all cases.
Therefore the issue is connected to opening a file.

### How to reproduce
Open a .tex-file which contains %TODO keys before and after the \begin{document} or in another environment command.

**Comment by sunderme** [comment]
apparently it needs to be a single file document.
