### ISSUE TITLE
Several Menu Options Not Working

### ISSUE THREAD

**Issue by thanhqtran** [texstudio-org/texstudio#3399]
### Environment
- TeXstudio:  4.7.0
- Qt:  6.6.1
- OS:  Mac
- TeX distribution:  mactex

### Keys

Clicking (or using hotkey) for **Preferences**, **New**, **Wizards** does not open expected windows.

### Actual behavior

- Cmd + , : no window opened
- Wizards -> Quick Start / Quick Beamer: no window opened (but Quick Letter works)

### Note

I reinstalled 4.6.3, and everything is back to normal. So the problem is probably exclusive to the latest version.

**Comment by sunderme** [comment]
duplicate to #3395
