### ISSUE TITLE
Correct upstream project

### ISSUE THREAD

**Issue by hannes101** [texstudio-org/texstudio#34]
Hi all,

I would like to know what's the correct upstream for texstudio. Are there any plans to migrate to another hosting site than sourceforge and which websites are still actively maintained. Is the release 2.12.8 here on github the latest release and will all other websites be updated?
Is there some information somewhere on the migration plan or what's going on? 

Thanks
Johannes

**Comment by sunderme** [comment]
we have moved development to github. Since one of the developers is busy, the release has not been completed yet and hence no website has been updated.
