### ISSUE TITLE
Wrong language code for de_CH translation

### ISSUE THREAD

**Issue by nairboon** [texstudio-org/texstudio#3400]
The translation file `texstudio_de_CH.ts` is for a Swissgerman dialect (`gsw_CH`), not for the Swiss High German language `de_CH`.

This file should be renamed to `texstudio_gsw_CH.ts`

**Comment by sunderme** [comment]
this needs to be changed on transifex (https://app.transifex.com/texstudio)

**Comment by nairboon** [comment]
How can you rename it on transifex?

**Comment by sunderme** [comment]
I don't know. 
Maybe start a new one with correct name ?

**Comment by beatjaeckle** [comment]
I made a request.

**Comment by sunderme** [comment]
so, the language is offered on transifex, now it needs to be filled.

**Comment by beatjaeckle** [comment]
I went through all the strings.
Is it allright? What will be the next step?

**Comment by sunderme** [comment]
okay, it is in.

**Comment by thymaro** [comment]
Thanks for your work. When I started that endeavor, I actually meant to translate it all the way. It wasn't meant as a joke. That was when I still had lots of time on my hands, before I understood the language code system, and before I knew there even was something like “gsw”. Thanks for transferring that to its own file. Right now, I don't think I will ever continue working on it, even though I'd love to.
