### ISSUE TITLE
Toggling on advanced options in Preferences crashes TeXstudio

### ISSUE THREAD

**Issue by chemistryPhD** [texstudio-org/texstudio#3402]
### Environment
- TeXstudio: 4.7.0
- Qt: 6.6.1
- OS: MacOS 14.1.2 (with ARM M2 Pro, not an x86 machine)
- TeX distribution: MacTex 2023

### Expected behavior
Toggling on "Show Advanced Options" within the Preferences menu should display and allow me to edit the "advanced" features.

### Actual behavior
The application immediately closes and a message is displayed stating TeXstudio quit unexpectedly

### How to reproduce

Open TeXstudio preferences and attempt to toggle on "Show Advanced Options"

**Comment by sunderme** [comment]
Please try txs 4.7.1rc1
