### ISSUE TITLE
Remove auto inserted closing parenthesis if the opening one is removed via backspace

### ISSUE THREAD

**Issue by Epaulard** [texstudio-org/texstudio#3406]
I've just downloaded the last version of TexStudio. After reading release notes,  I tried the new feature "Remove ...." without success. I guess I'm missing something.

### Environment
- TeXstudio: 4.7.1
- Qt: 6.6.1
- OS: Windows 11 Family
- TeX distribution: texlive

### Expected behavior
remove auto inserted closing parenthesis if the opening one is removed via backspace

### Actual behavior
no removal of  auto inserted closing parenthesis if the opening one is removed via backspace

### How to reproduce
(zzz) and remove opening ( with backspace

**Comment by octaeder** [comment]
This is a misunderstanding. Assume according option is set, then typing `(` will be completed with `)` and the cursor is set between the two parentheses automatically. When you type nothing more than a backspace (not zzz), then the pair of parentheses is removed.

**Comment by octaeder** [comment]
@sunderme Have you ever thought about or is there even a simple solution to remove parentheses surrounding something like in `(abc)`? There is no such function in menu Idefix/Parentheses. I use select inner, cut to clipboard, remove parentheses and insert from clipboard.

**Comment by Epaulard** [comment]
Thanks for the swift reply. It was indeed a misunserstanding.

**Comment by benibela** [comment]
> @sunderme Have you ever thought about or is there even a simple solution to remove parentheses surrounding something like in `(abc)`? There is no such function in menu Idefix/Parentheses. I use select inner, cut to clipboard, remove parentheses and insert from clipboard.

@ octaeder  There is "select inverting" for that.  And then backspace.

 But you have to place the cursor at the first parenthesis first. It was supposed to work with either. Perhaps something broke

**Comment by octaeder** [comment]
@benibela Thanks, It works as long as the cursor "touches" the open or closing parentheses: |( or (| or |) or )|. So as a workaround I can use `Ctrl+Shift+P,I` followed by `Ctrl+Shift+P,S`

**Comment by sunderme** [comment]
alt+del will also work in the next release.
