### ISSUE TITLE
Autocompletion jumps to wrong reference element with large number of references

### ISSUE THREAD

**Issue by Niklas123Niklas** [texstudio-org/texstudio#3409]
Hi there,
I am working on a large document with a large number of labels, glossary entries and bibliography.
There, autocompletion always jumps to the second element if `<tab>` is used to complete commands like `gls`, `glsdisp`, `ref`, `cref`... I don´t know what else is affected. Interestingly, this is not the case for `autocite` and `cite` commands.

### Environment
- TeXstudio: 4.7.1
- Qt: 6.6.1
- OS: Win11
- TeX distribution: texlive, updated yesterday

### Expected behavior
Jump to the first element in the list and show possibilities from there:
![grafik](https://github.com/texstudio-org/texstudio/assets/24720108/c3d272ae-61e7-4e20-928c-b8d15e3a1704)

### Actual behavior (explained with \glsdisp{})
If I use autocomplete for `glsdisp`, after typing `\glsd` the autocomplete list with all references shows up:
![grafik](https://github.com/texstudio-org/texstudio/assets/24720108/9c47c555-8254-46c2-87fc-daa08134374f)
Now, if i press tab, the second element is selected and autocompleted until there are differences in the elements, in this case, `\glsdisp{acr:` and it is possible to select from all labels starting with acr:, but other elements are omitted.
![grafik](https://github.com/texstudio-org/texstudio/assets/24720108/8fbe9a9e-58f8-4482-b7c4-7f0a1c0c11f4)
After deleting and scrolling, TeXstudio shows all possible elements, even those not starting with `acr:`. Shown are references to `\labels`, but there are more references to glossary entries below.
![grafik](https://github.com/texstudio-org/texstudio/assets/24720108/cd18aa24-745f-4e0d-abc9-17afc7f689c8)

### How to reproduce
I tried to build a MWE, but there everything works fine. Maybe, with a large number of references (I count more than 100 for glsdisp), something goes wrong?

**Comment by Niklas123Niklas** [comment]
I was expecting to autocomplete to `\glsdisp{`, so that the autocomplete list remains active, and I can proceed with the label selection. This is also the behaviour for other documents with fewer labels. I was finally able to create a document that recreates the behaviour. [Autocomplete.txt](https://github.com/texstudio-org/texstudio/files/13645817/Autocomplete.txt)
Here, you can autocomplete `\glsd` with tab, and it will go to `\glsdisp{acr:`, with the dropdown still active. If you comment out the marked ones, it will autocomplete `\glsd` to `\glsdisp{`, with the dropdown still active, and you can select from all labels available, not the ones starting with `acr:`. This is the expected behaviour.

In detail the expectation with images:
1. write `\glsd`
![grafik](https://github.com/texstudio-org/texstudio/assets/24720108/63f7171a-1744-4997-a512-04f82947a36d)
2. press `tab` to autocomplete this up to the last common characters of all elements in the list, in this case up to `\glsdisp{`
![grafik](https://github.com/texstudio-org/texstudio/assets/24720108/56bde3f8-eb13-4335-9230-12eb63a590f7)
(Here, it fails and autocompletes to `\glsdisp{acr:`, while there are also elements like `\glsdisp{sym:` in the list.)
3. Proceed with the selection of the reference. Here, autocomplete works as expected:
If I press tab in the case below, it autocompletes up to the `:`, which is the last common character for all elements below. This is what I expected for step 1 also.
![grafik](https://github.com/texstudio-org/texstudio/assets/24720108/ff35c337-71b1-46e3-84b2-50af4b8302df)
4. Finally, press enter and add the text for the second argument.

I hope, this is clearer now, especially since I could provide an example document, and I hope that this document creates the same behaviour.

**Comment by sunderme** [comment]
there is simply no good solution for this.
tab is used for "completion of common prefix". It uses only the currently displayed elements for completion, since anything furtherdown in the list is not easily detectable for the user.
Here it completes to "\glsdisp{acr:" ...
for you, selecting "\glsdisp{label}{text}" with enter and then start typing the label. The label completer is opened automatically.

**Comment by Niklas123Niklas** [comment]
Alright, I got the problem. If there are 10 or more elements starting with `acr:`, it autocompletes up to `acr:`, for 9 or fewer, it autocompletes up to `{`.
But you helped me to circumvent this autocomplete. If I add a dummy reference to an element that is alphabetically before `acr`, and not starting with and `a`, like a reference `A`. This is shown to the user and taken into account for autocompletion. It requires no change to TeXStudio then. Thanks for your support! I think this is solved for me.
