### ISSUE TITLE
Editor language change, then the compiling commands are messed up somehow

### ISSUE THREAD

**Issue by Zhonglu** [texstudio-org/texstudio#3416]
After changing the editor language back and forth between simplified Chinese and English, I cannot compile the pdf as normal.

After some playing with the setting, I figured out that the compiling commands in "Preferences" -> "Build" -> default compiler etc. are messed up somehow. It can become Chinese or English phrases rather than actual command. 

Probably not high priority issue but annoying.

### Environment
TeXstudio 4.7.1 (git 4.7.1)
Using Qt Version 6.6.0, compiled with Qt 6.6.0 R
- OS: macOS 14.1.2
- TeX distribution: texlive 2023

### Expected behavior
compile as normal 

### Actual behavior
error could not start the command: compile & view

### How to reproduce
just change language once or back and forth and then try compiling.

**Comment by sunderme** [comment]
works here. (linux)

**Comment by sunderme** [comment]
not reproducible.
If a step by step instruction can be provided, please reopen.
