### ISSUE TITLE
internal pdf viewer "original size" is bigger than open complied pdf by Adobe PDF reader

### ISSUE THREAD

**Issue by rfhamz** [texstudio-org/texstudio#3417]
### Environment
- TeXstudio: 4.7.1
- Qt: 6.6.1
- OS:  Windows10
- TeX distribution:   texlive 2023 

### Expected behavior
Config internal PDF viewer scale option => Original Size, then use build & view command to compile the tex files,
 after the tex files complied complete, the internal PDF viewer popup and show the pdf with 100% scale with right DPI.

### Actual behavior

once all the tex files build complete, I opened the output pdf by Adobe pdf viewer or Sumatra pdf viewer, the actually size is not same as Texstudio internal pdf viwer with original size.

**Comment by rfhamz** [comment]
does this relates to the screen resolution setting? I am confused.

**Comment by octaeder** [comment]
Check screen resolutions in Adobe Reader and txs. At least they should be the same, but the settings should also be the same as the physical screen resolution (see monitor menu). In txs have a look at the config menu of pdf viewer here:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/d026f572-f7ad-4591-929a-d265ac79a0ea)

Do you use a multi screen setup?

**Comment by rfhamz** [comment]
@octaeder yes, 
**Background**:
I am using one 4k monitor(DELL U2723QX) with 3840 x 2160 resolution as my 2nd monitor, I am using one laptop connected to the 2nd monitor with scale 125%(100% scale cause font size is so small)

the DELL spec said the PPI=163.18, by using that, I can split my monitor into two sides, I can edit my tex file by left side and right side show the PDF output, after you mentioned the dpi info by your screenshot, then I checked the texstudio recognized the system dpi=161(per my understanding, PPI is not same as DPI, right?), 

when I disconnected 2nd monitor, texstudio cannot detect the right DPI value and still keep DPI=161, after I change that value to 96dpi manually in the texstudio. internal pdf viewer works fine. so based on my descriptions, texstudio need to fix below functionality.

**Potential fix**
1. DPI value auto change by the texstudio GUI location, especially for "internal PDF viewer", that will impact the PDF display size.
2. texstudio can deal with the high resolution monitor, Windows support scale value, for my case scale = 125%

**Comment by octaeder** [comment]
A switch between imbedded and windowed internal pdf viewer should refresh the __system dpi value detected by txs__. Closing and reopening the viewer should have the same effect. But txs __won't change__ the value set in the spin box to the right. This should be the same behavior with Adobe Reader. Scaling can be set via this option:
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/b3103786-a144-4239-9c61-19e99d6bd0d0)

@sunderme Should we add an option allowing txs to auto update the spin box value when it's different from the detected value (when the viewer is opened)?

**Comment by sunderme** [comment]
I would not invest much time here, as mostly the pdf is rather rendered to taste.
Anyway, not sure which value you want to autodetect.

**Comment by octaeder** [comment]
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/8188d27b-c32e-40f5-b481-037f0d482a4c)

The label shows the resolution retrieved. When this value changes this has no effect on the value in the spinbox. But this would be necessary so the pdf is shown in the correct size. The option could be used to tell txs that the retrieved value should be used instead of the one in the spinbox.

**Comment by sunderme** [comment]
unless you personally need that, it is not worth the effort.

**Comment by octaeder** [comment]
then we leave it as is
