### ISSUE TITLE
erase matching delimiters should work differently

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3420]
### Environment
- TeXstudio: since commit 6ce8c81d3ef6cb994ab07d01c149abd258337229 in current dev
- Qt: 6.6.0
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
In case of `\sin(\tan(x))\cos(x)` it should be possible to delete the parentheses of `\sin` with Alt+Del, i.e. position cursor at opening or closing parentheses for `\sin`.

### Actual behavior
But implementation needs to position the text cursor at the backslash of the tan command (s. below). But then \tan with its parentheses is removed.

### How to reproduce
Following images show where to place the cursor such that you can remove the parentheses with Alt+Del in following examples:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/820e005e-f947-49b4-b651-1b41bc2141f7) and ![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/c431aa2a-1c3f-4e4f-a197-4436f75603da)

In the first case cursor is positioned at number 2, in the second case after closing parentheses.
Apply cases to example above.

**Comment by octaeder** [comment]
Please also check this case. The cursor is positioned at the first character (slash):

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/1b7fee86-4e29-4d2e-be90-a5373ac61166)

After pressing `Alt+Del` the cursor moves one to the right but `\[` and `\]` aren't removed:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/5b3f408b-2d64-414a-9068-cf1848a342f7)

**Comment by sunderme** [comment]
fixed

**Comment by octaeder** [comment]
thanks
