### ISSUE TITLE
Bad highlight of the & character in the tabular environment with unchecked Syntax setting

### ISSUE THREAD

**Issue by hair-splitter** [texstudio-org/texstudio#3421]
### Environment
- TeXstudio: TeXstudio 4.7.1 (git 4.7.1)
- Qt: 6.6.1
- OS: Windows 11
- TeX distribution: TeX Live 2023

### Actual behavior
Make the following setting:
 - Options
 - Configure TeXstudio
 - Editor
 - (Unchecked) Syntax

Restart TeXstudio, and type the following:

```tex
\begin{tabular}{|c|c|}
	\hline
	&  \\
	\hline
	&  \\
	\hline
\end{tabular}
```
The resulting highlight:

![badhl](https://github.com/texstudio-org/texstudio/assets/31892631/1c5ab58c-08ae-4ac0-84e9-8844788bc4bd)

The expected highlight is the next:

![goodhl](https://github.com/texstudio-org/texstudio/assets/31892631/272da706-4b5f-449e-9e29-69fd1aace62f)

Remark: TeXstudio 4.6.3 did not produce this incorrect behavior.

**Comment by sunderme** [comment]
the syntax checker is now used for more ambiguous highlighting, e.g. the '&' character in tables.
