### ISSUE TITLE
Search doesn't open project files containing search result

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3422]
### Environment
- TeXstudio: current dev
- Qt: 6.6.0
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
When selecting a result from Search Results pane txs should open the file to show the location with the text found.

### Actual behavior
txs jumps somewhere in the text of the current editor where the search was started

### How to reproduce
Create files test.tex and a1.tex as follows:
```latex
\documentclass{article}
\usepackage{mathtools}
\begin{document}
\input{a1}
$\sqrt{2}$
\end{document}
```
```latex
$\sqrt{2}$
```
Now start txs without editors, open test.tex. After `Ctrl+F` enter sqrt into the search field, choose nothing else than highlighting from the option buttons. Open Search Results pane and choose Project to search. Now update search results, expand all results (context menu) and click on the first result (file test.tex). This should be ok. Then click on the hit of a1. But cursor jumps to first line of current file test.tex, file a1.tex stays hidden.

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/866469b0-847a-4de1-a60a-3886de97f412)

Click on result of test.tex:
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/3ffebe54-94c6-4a0d-8569-e14d5a6ba429)

Click on result of a1.tex:
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/e038bf76-433a-4082-89af-3325f1ca23a0)
gives
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/f7f804a6-c138-499d-b5a4-fc7311ba8149)

**Comment by sunderme** [comment]
can't reproduce

**Comment by octaeder** [comment]
When I remove the `%appdata$/texstudio folder` and proceed as said above I can reproduce. Then I close txs (with test.tex open) and restart txs. Same procedure for the search (search field remembers only s not sqrt, so I type sqrt again) now doesn't find the hit in the second file at all.

**Comment by octaeder** [comment]
OK, thanks
