### ISSUE TITLE
Using ESC to return from fullscreen of txs main window (F11) stops a running build

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3436]
### Environment
- TeXstudio: current dev
- Qt: 6.6.0
- OS: Windows(10)
- TeX distribution: miktex

### Expected behavior
I would expect that main window returns to normal mode as defined in shortcut config when main window has focus.

### Actual behavior
There seems to be no shortcut defined for action Stop Compile. But when pressing ESC while working in txs main window and a build&compile is running, the build process ends immediately and pdf-viewer pops up and shows a message that it is continuously retrying to find a pdf. Since the build is aborted I need to run the build twice to restore all intermediate files, which takes more than 6 minutes.

### How to reproduce
If not clear then let me know.

**Comment by sunderme** [comment]
Now, if stop compile shortcut is set, esc is not used for that any more.
Furthermore, fullscreen toggle shortcut should be system default. It can be set to something else *and* it can be disabled to use esc for that (option/shortcuts at the bottom)
