### ISSUE TITLE
Temporary files should be in a temporary folder

### ISSUE THREAD

**Issue by PrasadNR** [texstudio-org/texstudio#3437]
When I have a .tex file and I have multiple "images" in a folder and I compile, I usually get some dozens of temporary files. It is irritating to see that because I have to manually delete so many files if I have to think about sharing the "parent" folder

**Comment by tmelorc** [comment]
> When I have a .tex file and I have multiple "images" in a folder and I compile, I usually get some dozens of temporary files. It is irritating to see that because I have to manually delete so many files if I have to think about sharing the "parent" folder

Are you talking about the auxiliary files created by pdflatex, for example? If yes, you can use the Clean Auxiliary Files feature to delete them.

**Comment by sunderme** [comment]
see also https://github.com/texstudio-org/texstudio/wiki/Tips-And-Tricks#using-a-separate-directory-for-auxiliary-files

**Comment by sunderme** [comment]
I think, this is answered.
