### ISSUE TITLE
Deteriorated resolution upon wake-up on Mac

### ISSUE THREAD

**Issue by michong268** [texstudio-org/texstudio#3450]
### Environment
- TeXstudio:  4.7.2
- Qt: 6.6.0
- OS:  macOS Sonama 14.1.2 (Apple Silicon M3 Pro)
- TeX distribution:  miktex

### Expected behavior
Maintained resolution upon waking up

### Actual behavior

When TexStudio is first launched, the resolution appears satisfactory. However, if the computer enters sleep mode without closing TexStudio, upon waking up, the resolution deteriorates. The editor window displays as blanks, and the text becomes blurred. Additionally, the content in the internal PDF viewer also becomes blurry. Nonetheless, restarting TexStudio restores everything to normal.

**Comment by sunderme** [comment]
maybe fixed: https://bugreports.qt.io/browse/QTBUG-127085
