### ISSUE TITLE
Request for a feature that allows to find and replace in multiple files.

### ISSUE THREAD

**Issue by AndreiDragomirescu** [texstudio-org/texstudio#3452]
### Describe the feature and the current behavior/state

The requested feature is a "find and replace" in multiple files located in the current directory or a directory that the user can specify. This feature request is similar to "Find in Files" available in Kate. The dialog should allow to specify both the string to be found and the string to be replaced with, to specify the directory in which the files to be searched in are located, to specify the file type(s) to be searched in, to see the proposed replacements and in what files the replacements will be made, and to choose using checkboxes the desired replacements. The request is illustrated in the image attached in the Section "Any other info".

### Who will benefit from this feature?

This feature will be beneficial for all users of TexStudio who work with large projects consisting of many files and who now and then need to find and replace strings throughout their projects. 

### Any other info

![image](https://github.com/texstudio-org/texstudio/assets/38186978/f8e29a1a-9d37-4b1c-9f7c-747066a62623)

**Comment by sunderme** [comment]
duplicate #3311
