### ISSUE TITLE
masOs apple silicon version crash

### ISSUE THREAD

**Issue by m4w13** [texstudio-org/texstudio#3457]
### Environment
- TeXstudio: 4.7.2
- Qt: 6.6.1
- OS: macOs
- TeX distribution: mactex

### Actual behavior

I compiled version 4.7.2. 

I have compiled with poppler with qt6, internal pdf reader works fine. 

Texstudio crashes when opening any auxiliary window (preference, open-file, etc.). The intel version works fine, no problems.

This may be due to the latest macOs update, there have been bug reports here reporting the intel version crashing, you fixed that, report #3395.

Please fix the same for Apple ARM.

**Comment by m4w13** [comment]
**Below is the crashlog when the preferences window is opened:**

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   texstudio [32304]

Application Specific Information:
abort() called


Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x188ad20dc __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x188b09cc0 pthread_kill + 288
2   libsystem_c.dylib             	       0x188a15a40 abort + 180
3   libc++abi.dylib               	       0x188ac1070 abort_message + 132
4   libc++abi.dylib               	       0x188ab112c demangling_terminate_handler() + 348
5   libobjc.A.dylib               	       0x18875798c _objc_terminate() + 144
6   libc++abi.dylib               	       0x188ac0434 std::__terminate(void (*)()) + 16
7   libc++abi.dylib               	       0x188ac3520 __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 88
8   libc++abi.dylib               	       0x188ac3464 __cxa_throw + 308
9   libobjc.A.dylib               	       0x18874e01c objc_exception_throw + 420
10  CoreFoundation                	       0x188bd2d10 -[__NSArrayM objectAtIndexedSubscript:] + 584
11  libqcocoa.dylib               	       0x106d8656c -[QMacAccessibilityElement initWithId:role:] + 296
12  libqcocoa.dylib               	       0x106d865ec +[QMacAccessibilityElement elementWithId:] + 64
13  libqcocoa.dylib               	       0x106d84b88 QCocoaAccessibility::notifyAccessibilityUpdate(QAccessibleEvent*) + 104
14  QtWidgets                     	       0x10884e888 QListView::selectionChanged(QItemSelection const&, QItemSelection const&) + 204
15  QtCore                        	       0x108d04b00 void doActivate<false>(QObject*, int, void**) + 1248
16  QtCore                        	       0x108e66a74 QItemSelectionModel::emitSelectionChanged(QItemSelection const&, QItemSelection const&) + 792
17  QtCore                        	       0x108e665f8 QItemSelectionModel::select(QItemSelection const&, QFlags<QItemSelectionModel::SelectionFlag>) + 368
18  QtCore                        	       0x108e6645c QItemSelectionModel::select(QModelIndex const&, QFlags<QItemSelectionModel::SelectionFlag>) + 60
19  QtCore                        	       0x108e66e60 QItemSelectionModel::setCurrentIndex(QModelIndex const&, QFlags<QItemSelectionModel::SelectionFlag>) + 212
20  QtWidgets                     	       0x1086e02e8 QComboBoxPrivate::setCurrentIndex(QModelIndex const&) + 612
21  QtWidgets                     	       0x1086dfb5c QComboBox::setCurrentIndex(int) + 112
22  QtWidgets                     	       0x1086e3038 QComboBoxPrivate::rowsInserted(QModelIndex const&, int, int) + 344
23  QtCore                        	       0x108d048f8 void doActivate<false>(QObject*, int, void**) + 728
24  QtCore                        	       0x108e53ec4 QAbstractItemModel::endInsertRows() + 160
25  QtGui                         	       0x109558e78 QStandardItemPrivate::insertRows(int, QList<QStandardItem*> const&) + 424
26  QtWidgets                     	       0x1086e5cdc QComboBox::insertItems(int, QList<QString> const&) + 308
27  texstudio                     	       0x104baeb60 QComboBox::addItems(QList<QString> const&) + 48
28  texstudio                     	       0x104bd49c8 ConfigDialog::populateComboBoxFont(bool) + 528
29  texstudio                     	       0x104baf50c ConfigDialog::ConfigDialog(QWidget*) + 1228
30  texstudio                     	       0x104bd5238 ConfigDialog::ConfigDialog(QWidget*) + 36
31  texstudio                     	       0x104c0f988 ConfigManager::execConfigDialog(QWidget*) + 96
32  texstudio                     	       0x104f377bc Texstudio::generalOptions() + 1948
33  texstudio                     	       0x104a60804 Texstudio::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 14284
34  QtCore                        	       0x108d04b00 void doActivate<false>(QObject*, int, void**) + 1248
35  QtGui                         	       0x1095b0288 QAction::activate(QAction::ActionEvent) + 368
36  QtCore                        	       0x108cff4ac QObject::event(QEvent*) + 284
37  QtWidgets                     	       0x1085f7118 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 272
38  QtWidgets                     	       0x1085f7f80 QApplication::notify(QObject*, QEvent*) + 512
39  QtCore                        	       0x108cc94c0 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 208
40  QtCore                        	       0x108cca18c QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 524
41  libqcocoa.dylib               	       0x106d2d878 QCocoaEventDispatcherPrivate::processPostedEvents() + 192
42  libqcocoa.dylib               	       0x106d2e534 QCocoaEventDispatcherPrivate::postedEventsSourceCallback(void*) + 412
43  CoreFoundation                	       0x188be7a4c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
44  CoreFoundation                	       0x188be79e0 __CFRunLoopDoSource0 + 176
45  CoreFoundation                	       0x188be7750 __CFRunLoopDoSources0 + 244
46  CoreFoundation                	       0x188be6340 __CFRunLoopRun + 828
47  CoreFoundation                	       0x188be59ac CFRunLoopRunSpecific + 608
48  HIToolbox                     	       0x193194448 RunCurrentEventLoopInMode + 292
49  HIToolbox                     	       0x1931940d8 ReceiveNextEventCommon + 220
50  HIToolbox                     	       0x193193fdc _BlockUntilNextEventMatchingListInModeWithFilter + 76
51  AppKit                        	       0x18c3c28a4 _DPSNextEvent + 660
52  AppKit                        	       0x18cb9c980 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
53  AppKit                        	       0x18c3b5d50 -[NSApplication run] + 476
54  libqcocoa.dylib               	       0x106d2c98c QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 1936
55  QtCore                        	       0x108cd0c74 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 448
56  QtCore                        	       0x108cc99c0 QCoreApplication::exec() + 112
57  texstudio                     	       0x104de47f8 main + 636
58  dyld                          	       0x1887890e0 start + 2360

**Comment by sunderme** [comment]
since that code runs on all other platforms, I don't see a way to debug it.
Have you tried our build ?

**Comment by m4w13** [comment]
Yes, your build under intel works great. Unfortunately you don't provide a build for apple silicon, so I have to compile it myself.

I solved the problem by installing qt version 6.6.0 instead of 6.6.1. After I recompiled poppler with qt 6.6.0 and recompiled texstudio - everything worked as it should.

**Comment by m4w13** [comment]
The problem seems to be that texstudio for macOs does not currently support qt 6.6.1. Is this correct?

**Comment by sunderme** [comment]
no, the problem is that apparently qt 6.6.1 has issues on osx.

**Comment by m4w13** [comment]
Ok, thanks for the clarification. I will wait for this to be fixed in qt 6.6.2 )
