### ISSUE TITLE
CRITICAL: TexStudio 4.7.2 crashed on windows 11 when opening

### ISSUE THREAD

**Issue by greenscreenflicker** [texstudio-org/texstudio#3465]
### Environment
- TeXstudio: 4.72
- Qt: 
- OS: Windows
- TeX distribution: 

### Actual behavior

Crashes when opening, slash screen apprears, than closes.

### How to reproduce
Install on Windows 11, open it.

**Comment by greenscreenflicker** [comment]
Downgrading to 4.6.3. resolves the problem. 
(My guess it's something with the file paths, that where open in the old version.)

**Comment by sunderme** [comment]
It does not simply crash by opening on win11.

Start txs 4.7.2 with no files.
(Use the portable version if you don't want to install it) and open your file.
You should close txs 4.63 with no open files before.

**Comment by sunderme** [comment]
Just as a remark. This bug report needs collaboration from the reporter. The "how to reproduce" does not work on other computers, so it is either configuration or something to do with automatically opened documents.
If no further details are provided, there is really nothing I can do.

**Comment by greenscreenflicker** [comment]
@sunderme sorry for the dump question, but could be be more precise, what I can contribute?

**Comment by sunderme** [comment]
with txs 4.7.2
1) remove %appdata%\texstudio\lastSession.txss2 (or rename)
2) start txs 4.7.2
3) does it crash -> 3a
3a) remove/rename %appdata%\texstudio\texstudio.ini

it does not crash -> 4a
4a) load one by one the documents you were using
b) in case it crashes, upload that document here (probably with child documents)
 - possibly reduce the document(s) as much as possible while still causing a crash to simplify finding the issue

**Comment by Lidocacine** [comment]
I'm having a similar problem, I'm using the 4.72 installer board to open a template file I downloaded from github, and after opening it the first time, it crashes the second time I open the file.

**Comment by Lidocacine** [comment]
> I'm having a similar problem, I'm using the 4.72 installer board to open a template file I downloaded from github, and after opening it the first time, it crashes the second time I open the file.
Downgrading to 4.6.3. resolves the problem.

**Comment by sunderme** [comment]
What is the template ?

**Comment by sunderme** [comment]
no relevant feedback
