### ISSUE TITLE
Excessive Completion

### ISSUE THREAD

**Issue by salbrusco1** [texstudio-org/texstudio#3467]
When I'm working in a math environment and I want to type something like `\sec^2x`, as soon as I type the `^` after the `\sec`, it autocompletes the `\sec` to `\section`. Or when I'm working in a `tikzpicture` environment and I want to type `rotate = 90`, it will autocomplete `rotate =` to `rotate around x=` as soon as I type the `=`. Is there a way to stop auto completion for specific commands? I don't want to give up the automatically putting the `\end{}` for whatever environment I'm working in.

I'm working in TeXstudio version 4.7.2. Some examples are I'm writing out some Pythagorean Identities:

```
\[\tan^2\theta=\sec^2\theta-1\]
```

Or I'm drawing a diagram and want some nodes rotated:

```
\begin{tikzpicture}
    \draw (0,0) -- (0,3) -- (3,0) -- (0,0);
    \node[anchor = south, rotate = 90] at (0,1.5) {Silo};
    \node[anchor = south, rotate = -90] at (0,1.5) {50 feet};
    \node[anchor = north] at (1.5,0) {Shadow};
    \node[anchor = south] at (1.5,0) {$L$};
    \node[anchor = south east, xshift = -.4cm] at (3,0) {$\theta$};
\end{tikzpicture}
```

I've added a gif of what's happening.
![Animation](https://github.com/texstudio-org/texstudio/assets/155650389/9265c5f6-e4a9-4abf-a61b-e28301d23d45)

**Comment by sunderme** [comment]
"options/completion/Complete selected text when next non-word character is pressed" should be off.

**Comment by salbrusco1** [comment]
Thank you!
