### ISSUE TITLE
Unable to upgrade TeXStudio on Windows 10

### ISSUE THREAD

**Issue by friendly** [texstudio-org/texstudio#3468]
IT at my university installed Microsoft Defender Smartscreen, and now I'm unable to install an upgrade because Microsoft does not recognize TeXStudio.

The IT guy explained: "As part of the campus-wide switch from Trend Micro Apex One Antivirus to Microsoft Defender for Enterprise, a component call SmartScreen was enabled. This component protects systems from installation of potentially unsafe, unsigned software. To achieve this, Microsoft keeps a list of the executable hashes of known software, and while their list is extensive, certain lesser known but legitimate software may not be on the list. This causes the blue blocking pop-up you're seeing."

The solution seems to be to register TeXStudio with Microsoft.

**Comment by sunderme** [comment]
can you run the portable version of txs, it does not need installation ...

**Comment by sunderme** [comment]
by the way, as it is open source, anybody can try to get txs whitelisted by Mircrosoft.

**Comment by friendly** [comment]
Thanks. IT at my university applied to get it whitelisted.

**Comment by Finni123** [comment]
> can you run the portable version of txs, it does not need installation ...

I just downloaded the 4.7.2 portable for windows and a SmartScreen warning appeared. Using the portable doesn't help.

**Comment by sunderme** [comment]
https://github.com/texstudio-org/texstudio/releases/download/4.8.3alpha1/texstudio-4.8.3alpha1-win-qt6-signed.exe is now code signed, please check.
