### ISSUE TITLE
Texstudio extremely slow to start

### ISSUE THREAD

**Issue by Sviktor22** [texstudio-org/texstudio#3470]
Texstudio is extremely slow to start on my laptop. Last time it started in 8 minutes!
I can see the process in the built-in process explorer in Windows and it seems to be doing something as it uses 5-9% of CPU not just showing 0 or a constant value.
The same problem happens after uninstalling and installing again Texstudio.

The issue started to appear around 2 months ago, before that there was no issue.

I have uninstalled miktex and the problem presists.

The laptop is an ASUS Zenbook 14 UX425J with 10th gen i7 processor.

On my much older desktop PC there is no issue yet but I have just installed Miktex and Texstudio to that machine.

### Environment
- TeXstudio: 4.7.2
- Qt: 6.6.1 compiled with 6.6.1R
- OS: Windows 11 ( up-to-date as of today )
- TeX distribution: basic-miktex-23.10 but the issue is the same without any latex distribution

### Expected behavior
Start up in seconds but definitely not in tens of minutes.

### Actual behavior
Last time it has started in 8 minutes.

### How to reproduce
Simply start Texstudio.

**Comment by sunderme** [comment]
remove %appdata%/texstudio/texstudio.ini

just a remark: if one computer does not show the issue but a second one does, then "how to reproduce":just start texstudio is pretty useless.

**Comment by sunderme** [comment]
no idea what causes this.

**Comment by sunderme** [comment]
if it happens again, we can try to analyse what causes it by looking at the config files.
But that requires that you send them to me or put them in the issue report.
