### ISSUE TITLE
Handling a new file created from the context menu

### ISSUE THREAD

**Issue by bykhov** [texstudio-org/texstudio#3471]
After typing `\input{some_file}`, by right mouse click, Texstudio gives the option to create a new file if a file with such name does not exist. However, this file is not related as part of the main file (compilation, relation to new command definition, etc.) until Texstudio restarts.
### Expected behavior
The new file created by Texstudio is correctly related to the main file (file with `\input{}` command).
### Actual behavior
Works correctly only after Texstudio restart. 

### How to reproduce
* Write `\input{test}` inside some file.
* Create a new test.tex file from `Open test` context menu (right-mouse button).
* Try to compile the document while the new file is active (won't work).
* Restart Texstudio and the repeat the previous step (will work).

### Environment
- TeXstudio: 4.7.2
- Qt: 6.6.1
- OS: Windows10
- TeX distribution: miktex

**Comment by sunderme** [comment]
"try to compile..." ?
So, you have created a new file but you have not saved it ?
