### ISSUE TITLE
TeXstudio 4.7.2 freeze when click "Help->About TexStudiio..."

### ISSUE THREAD

**Issue by yinghui** [texstudio-org/texstudio#3474]
### Environment
- TeXstudio:  4.7.2
- Qt: N/A
- OS: Pop OS
- TeX distribution: TexLive 2023

### Expected behavior
Open a dialogue showing texstudio information

### Actual behavior
texstudio freeze, lost response

### How to reproduce
start textstudio, click "Help->About Texstudio..."

**Comment by sunderme** [comment]
not reproducible on ubuntu.
Where is the binary from ?

**Comment by yinghui** [comment]
I downloaded the AppImage file

**Comment by yinghui** [comment]
downloaded from https://www.texstudio.org/

**Comment by sunderme** [comment]
still works on ubuntu

**Comment by yinghui** [comment]
Pop OS is build on ubuntu version 22 rather 24, how you tried this on ubuntu 22?

**Comment by sunderme** [comment]
I am using ubuntu 22.04

**Comment by yinghui** [comment]
https://github.com/texstudio-org/texstudio/assets/1584823/25c6d42c-ca52-40c6-a6dc-b2d758b11e11

I made a screen recording, and hopefully it helps.

**Comment by yinghui** [comment]
Here is the link to youtube
https://youtu.be/Ty-_tN2WhX4

**Comment by yinghui** [comment]
It just freeze, none of these you mentioned.

**Comment by sunderme** [comment]
I have started POP OS in a virtual machine, txs appimage works fine.
So, nothing I can do.
(by the way, pop os seems to be based on ubuntu 22.04 , so the ppa should work)
Not reproducible.
