### ISSUE TITLE
TeXstudio cannot automatically launch languagetool using dynamic paths

### ISSUE THREAD

**Issue by jintaxi** [texstudio-org/texstudio#3477]
### Environment
- TeXstudio: 4.7.2 (portable)
- Qt: 6.6.1 R
- OS: Windows 11, 22H2 22621.2861
- TeX distribution: TeX Live 2023 (portable installation)

### Expected behavior
In setting, spell check, Languagetool, the program should convert `[txs-app-dir`] to the current directory with the executable file.

### Actual behavior
When i type something like this `[txs-app-dir]\LanguageTool-6.3\java\bin\java.exe` which in my case should be transformed into `D:\Portable\TeXstudio\LanguageTool-6.3\java\bin\java.exe` not trasnform.

### How to reproduce
Type `[txs-app-dir]` in setting, spell check, Languagetool in java path and languagetool path.

### Crutch
Run texstudio via a batch file, which will be changed in the texstudio.ini file in `Grammar\Language%20Tool%20` and `Grammar\Language%20Tool%20Java%20Path`
`[txs-app-dir]` on `%cd%` (the current path to the batch file), which will lead to the expected operation of the variable `[txs-app-dir]`

**Comment by sunderme** [comment]
the only path not handling txs-app-dir was java
