### ISSUE TITLE
Using space in filename works for old system package version but not flatpak version (Linux Mint)

### ISSUE THREAD

**Issue by Ainstain438** [texstudio-org/texstudio#3479]
### Environment
- TeXstudio 4.7.2 (git 4.7.2)
- Qt: Using Qt Version 6.6.1, compiled with Qt 6.6.1 R
- OS: Linux Mint 21.3
- TeX distribution: First tried with TexLive but installed SDK extension Tex while troubleshooting.

### Expected behavior

I can't use a space in the filename when using the flatpak version of TexStudio even though it was possibly with the system package-version (4.2.1).

### How to reproduce

Texstudio Flatpak rename a valid .tex file to a name utilising a space in the filename. This will cause a compilation to say "
`Could not start Build & View:PdfLaTeX:
flatpak-wrapper pdflatex -synctex=1 -interaction=nonstopmode "filename using space".tex.`

It produceses no logs except texput.log which says:
```
This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023 - Flatpak) (preloaded format=pdflatex 2024.1.11)  17 JAN 2024 09:22
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**filename using space.tex

! Emergency stop.
<*> filename 
             using space.tex
*** (job aborted, file error in nonstop mode)

 
Here is how much of TeX's memory you used:
 3 strings out of 476025
 114 string characters out of 5791510
 1849388 words of memory out of 5000000
 20558 multiletter control sequences out of 15000+600000
 512287 words of font info for 32 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 0i,0n,0p,1b,6s stack positions out of 10000i,1000n,20000p,200000b,200000s
!  ==> Fatal error occurred, no output PDF file produced!
```

### My thoughts

If it wasn't for the system package version of TexStudio being able to handle spaces in the filename I wouldn't have thought much of it. Based on the newline at the first space in the filename in the texput.log-file to me it feels like it could be as simple as TexStudio treating space as a string seperator.

**Comment by sunderme** [comment]
we don't provide the flatpack.

**Comment by Ainstain438** [comment]
Oh, that's my bad. I'll close this issue then.
