### ISSUE TITLE
Language Button in Package Help dialog

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3482]
### Environment
- TeXstudio: current dev
- Qt: 6.6
- OS: Windows 10
- TeX distribution: miktex

### Actual behavior
At first it is not clear what 'en' could be and what this button does (I had to look into the code):

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/85f86264-7b90-41e8-ba76-53dc209220f8)

Since other cases are very rare (in my case only 10 out of 6524 packages have 2 descriptions in different languages, none found with more than 2), nothing seems to change for the user while selecting different packages. So there are no further hints what this is for. This might need some clarification. Maybe a tooltip saying "set description language to 'en'" could help.

This is one of the rare cases:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/d49eb74b-2cc0-41ee-b970-0cf6f5551513)

The json part is:
```
"descriptions": [
   {
      "language": "en",
      "text": "<p>\n      A simple class that allows production of an invoice, with or\n      without VAT; different addresses for delivery and for billing\n      are permitted.\n    </p>"
   },
   {
      "language": "fr",
      "text": "<p>\n      Une classe simple permettant de produire une facture, avec ou sans\n      TVA, avec gestion d’une adresse différente pour la\n      livraison et pour la facturation.\n    </p>"
   }
],
```

It seems that in cases with one description language is null. This case is handled here:
```
description.language = (language.isNull() || language.isEmpty()) ? "en" : language;
```

This could be changed while generating the json and also for the following.
After all, screenshot in https://github.com/texstudio-org/texstudio/pull/3478 shows 'English'.
So why don't use tr("English") with translation strings instead of en?
Could it be that a description with an empty language is not in English? Then tr("Default") maybe better.
I would prefer long names like "English" and "French" and so on (for common languages).

**Comment by CSMathematics** [comment]
That's what I had in mind from the beggining but I used "en" in a rush to see if everything works fine and I forgot to change it.

**Comment by sunderme** [comment]
language code is now only shown when there are more than one language
