### ISSUE TITLE
TOC sidebar no longer allows switching current document

### ISSUE THREAD

**Issue by jrmoserbaltimore** [texstudio-org/texstudio#3489]
### Environment
- TeXstudio: 4.7.2
- Qt: 6.6.1
- OS: Windows 11

### Expected behavior

Clicking a document in the TOC sidebar switches to that document's tab.

### Actual behavior
Clicking a document in the TOC sidebar does nothing.  Double-clicking the document expands or collapses a list of sections and includes, but doesn't change the current document being edited.  Clicking a section switches to that document's tab and places the cursor at the section start, as is expected; clicking an included file opens the included file, as expected, which doesn't help if you want to open the file that's including that file.

### How to reproduce

Load multiple TeX files and try to navigate using the TOC sidebar.

**Comment by sunderme** [comment]
Duplicate to #3472

**Comment by jrmoserbaltimore** [comment]
"Structure panel," okay, that's what I needed to search for.   Thanks!
