### ISSUE TITLE
How to enable auto-completion for LaTeX macros?

### ISSUE THREAD

**Issue by dense-set** [texstudio-org/texstudio#3490]
### Environment
- TeXstudio: 4.7.2
- Qt: 6.6.0, compiled with Qt 6.6.0 R
- OS: MacOS Sonoma 14.2.1
- TeX distribution: texlive

### Description

What `.cwl` files should I include in Preferences > Completion to enable the autocompletion of commands like `\ExplSybtaxOn`, `\makeatletter`, _etc._?

----

I also asked the [same question on SE](https://tex.stackexchange.com/q/708081/207649).

**Comment by dense-set** [comment]
Is there a way so that the following illegible code in TeXstudio
<img width="480" alt="Screenshot 2024-01-27 at 9 04 01 PM" src="https://github.com/texstudio-org/texstudio/assets/102873841/b24208d2-72b7-45a4-b88d-7bfc6bf46352">
becomes pretty like this?:
<img width="410" alt="Screenshot 2024-01-27 at 9 04 43 PM" src="https://github.com/texstudio-org/texstudio/assets/102873841/b50b8b1b-ca49-44f0-8261-245e5fb5b9c0">

**Comment by mbertucci47** [comment]
Not currently: https://github.com/texstudio-org/texstudio/issues/61

**Comment by dense-set** [comment]
Is there a hack to make it more manageable? (Not necessarily within TeXstudio.) I am okay with copying it from someplace that is conscious of `expl3` syntax.

**Comment by mbertucci47** [comment]
`\makeatletter` and `\ExplSyntaxOn` are in latex-dev.cwl but you need to change the preferred command set from "Typical" to "All" in the Completion section of settings

**Comment by dense-set** [comment]
Thanks! If I could, I would close this issue as a dupe, and do a +1 to the original one (#61).
