### ISSUE TITLE
Can one disable the highlighting of underscores?

### ISSUE THREAD

**Issue by dense-set** [texstudio-org/texstudio#3491]
### Environment
- TeXstudio: 4.7.2
- Qt: 6.2.2
- OS: MacOS Sonoma
- TeX distribution: texlive

### Description
While using `expl3`, underscores `_` are prominently used in function/variable names. However, TeXstudio triggers a warning highlight:
<img width="260" alt="Screenshot 2024-01-28 at 12 39 18 AM" src="https://github.com/texstudio-org/texstudio/assets/102873841/05030398-cd6b-4031-81c9-5daec0f7d6c3">

This makes everything between `ExplSyntaxOn` and `\ExplSyntaxOff` look horrendous. Is there a way to disable this?

On second thought, it'd be better if one could simply disable the usual syntax highlighting between `ExplSyntaxOn` and `\ExplSyntaxOff`. Can this be achieved?

**Comment by sunderme** [comment]
basic highlighting for ltx3 is implemented on 4.7.4 (dev)
