### ISSUE TITLE
Editor-entry error with printbibliography

### ISSUE THREAD

**Issue by aerilon91** [texstudio-org/texstudio#3492]
### Environment
- TeXstudio: 4.7.2
- Qt: 6.6.1
- OS: Windows 11
- TeX distribution:  miktex

### Actual behavior

![Screenshot 2024-01-27 223652](https://github.com/texstudio-org/texstudio/assets/157922495/f55e5f46-6feb-42d7-a100-a221bdfd85f7)

### How to reproduce

\documentclass[12pt,titlepage]{scrartcl}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[style=geschichtsfrkl]{biblatex}
\bibliography{Literaturliste.bib}
\begin{document}			
	test\cite[Vgl.][169f]{dettenhoferverweigerung}

	\printbibliography
\end{document}

with entries in the .bib file:

@inbook{dettenhoferverweigerung,
	author={Maria H. Dettenhofer},
	title={Verweigerung als Form der Abstimmung oder: Von der Ausnahme zur Regel},
	maintitle={Genesis und Dynamiken der Mehrheitsentscheidung},	
	location={München},
	year={2013},
	pages={153--172},
	editor={Egon Flaig},
}

@book{flaigmehrheitsentscheidung,
	author={Egon alaig},
	maintitle={Die Mehrheitsentscheidung},
	mainsubtitle={Entstehung und kulturelle Dynamik},
	location={Paderborn},
	year={2013},
}

The solution was to cite a bib entry, which comes alphabetical before the entry with the editor.

![Screenshot 2024-01-27 224336](https://github.com/texstudio-org/texstudio/assets/157922495/4624ea39-929e-430f-9f43-1f500b24a0a7)

**Comment by sunderme** [comment]
This is a latex question. Nothing to do with the editor texstudio ?
