### ISSUE TITLE
How do you use % in texmaker command arguments? (such as --output="%f-%p")

### ISSUE THREAD

**Issue by bluerosegarden** [texstudio-org/texstudio#3495]
### Environment
- TeXstudio:  4.7.2 
- Qt: 6.6.1
- OS: Windows10
- TeX distribution: miktex

### Description
I have the following command in under `[texmaker]` in my texstudio.ini

`Tools\Commands\dvi2svg-no-fonts="txs:///latex | dvisvgm --no-fonts --page=1- --output=%f-%3p %.dvi"`

What I want is for the command to create an svg for each page of the original document with the output formatting options of `<filename>-<page number>.svg`. However, every % is replaced by the filename of the .tex file (which is filename in this instance) before it gets to dvisvgm

As a result, instead of properly creating a svg with the a filename like `filename-1.svg`, it instead creates a svg with the filename `filenamef-filenamep.svg` I tried escaping the %'s like `\%f-\%p`, but that resulted in the filename `f-p.svg`

I am very new to latex and texstudio, so I'm sorry if the solution is otherwise very obvious!! Many, many thanks in advance.

**Comment by muzimuzhi** [comment]
Doubled percent char should work: `%%`.

Configure TeXstudio - Commands
![image](https://github.com/texstudio-org/texstudio/assets/6376638/702d05cc-d5d7-4244-89b2-240415522832)

**Comment by bluerosegarden** [comment]
That was it!! thank you so much
