### ISSUE TITLE
Error building texstudio on fedora

### ISSUE THREAD

**Issue by hannes101** [texstudio-org/texstudio#35]
Hi all,
the latest build does not build on fedora. I am not 100% sure if this might be caused by the patches I need to apply, but I didn't change them between versions, so it probably is not my fault, but not sure.
Build
[build.log](https://github.com/texstudio-org/texstudio/files/1714127/build.log)

[texstudio-debughelper-arm-fix.txt](https://github.com/texstudio-org/texstudio/files/1714128/texstudio-debughelper-arm-fix.txt)
[texstudio-disable-update-check.txt](https://github.com/texstudio-org/texstudio/files/1714129/texstudio-disable-update-check.txt)
[texstudio-use-system-qtsingleapplication-instead-of-bundled-on.txt](https://github.com/texstudio-org/texstudio/files/1714130/texstudio-use-system-qtsingleapplication-instead-of-bundled-on.txt)
[texstudio-wtf_flags.txt](https://github.com/texstudio-org/texstudio/files/1714131/texstudio-wtf_flags.txt)

**Comment by sunderme** [comment]
crash handler does not buiold with Qt 5.10.0 , 59.4 is okay.

**Comment by hannes101** [comment]
Thanks a lot, was worried that I introduced the issue with my packages. Then I'll just wait until it's fixed.

Cheers 
Johannes

**Comment by benibela** [comment]
Not sure how qt could affect this part

Perhaps they overrode geteip? Try to put `#undef geteip` before it

**Comment by sunderme** [comment]
@Benito: please download qt5.10 and debug it directly. Doing it via email seems to be tedious...

**Comment by benibela** [comment]
On OpenSUSE it compiles with qt5.10 and gcc 7.3

**Comment by hannes101** [comment]
Ok, it seems that this little patch fixes the issue indeed. Thanks for your help!
[0003-fix-for-compile-failure.txt](https://github.com/texstudio-org/texstudio/files/1739562/0003-fix-for-compile-failure.txt)
