### ISSUE TITLE
TeXstudio crashes when trying to change config

### ISSUE THREAD

**Issue by ogauthe** [texstudio-org/texstudio#3502]
Hi! I have TeXstudio installed using debian package manager. As my computer default language is french, TeXstudio also speaks French by default and uses the french dictionary spelling. When I try to change any of these, TeXstudio crashes and after restart, no change has been made.

In details, I go to "configure TeXstudio" and do any of these actions:
- in "General" I set TeXstudio language from "default" to any another language 
- in "Language control" I change "default language" from fr_FR to en_US
- in "Language control" I change "Dictionaries directory" from /usr/share/hunspell to /usr/share/myspell/dicts

TeXstudio crashes when I press Ok after making any of theses changes. The dictionaries files I try to use do exist and should not cause any issue (Texmaker for instance has no problem switching dictionary).

As a side note, there is a field "thesaurus data base" that is set to /usr/share/mythes/thes_fr.dat and I do not have an EN equivalent for this file, but I think this is unrelated.
 

### Environment
- TeXstudio: TeXstudio 4.3.1 (Build: 4.3.1+ds-3)
- Qt: 5.15.10
- OS: Debian trixie/sid
- TeX distribution: texlive

### Expected behavior
TeXstudio does not crash and changes its language / the spelling dictionary

### Actual behavior
TexStudio crashes. After restart, no change has been made.

### How to reproduce
Try changing the language / the spelling dictionary. I would gladly provide more information but I just have a crash. Is there some log file I can look at?

**Comment by sunderme** [comment]
Changing languages works in general.

So, 2 options for you:
1) compile latest source and check there. That would also allow you to run with a debugger and see where it actually crashes.
See wiki formhow to compile.
2) try current txs appimage.

**Comment by shoaib-mi** [comment]
after updating linux via terminal, when I tried to change build engine to xelatex, texstudio crashes. I get the same error @ogauthe mentioned, with one more line: `zsh: IOT instruction  texstudio`.

**Comment by ogauthe** [comment]
I confirm this behavior. So this has nothing to do with language actually: TeXstudio crashes whenever one tries to change a configuration parameter. Even changing editor font size triggers the crash.

**Comment by sunderme** [comment]
as I don't see anything like this on any platform, please follow my suggestions above.
There is nothing more I can do.

**Comment by ogauthe** [comment]
So, I updated my computer with `apt upgrate` and the problem vanished. texstudio was upgraded and some new qt-related packages were installed (`libqt5multimedia5` `libqt5multimediawidgets5` `libquazip1-qt5-1`). Now everything is fine and I can change the configuration as I want.

I suppose this was more a packaging issue than a texstudio one. I am closing this issue.
