### ISSUE TITLE
Alt+Del removes only command when argument contains newline

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3503]
### Environment
- TeXstudio: current dev, current release 4.7.2
- Qt: 6.6.1
- OS: Windows10
- TeX distribution: miktex

### Expected behavior
`Alt`+`Del` removes braces and keeps anything between in case of \someCmd{  ... (a newline) ... }

### Actual behavior
Only the part up to the opening brace is removed. The closing brace remains (unpaired).

### How to reproduce
before (uses | for current text cursor, so command \textbf looks like \tex|tbf) 
```latex
\begin{document}
abc\tex|tbf{adsffffffffffffffff
asdfa adsf}
\end{document}
```
after
```latex
\begin{document}
abc|adsffffffffffffffff
asdfa adsf}
\end{document}
```

**Comment by octaeder** [comment]
Thanks

**Comment by tercelxy** [comment]
For 4.7.3 beta3, Alt+Del removes opening brace but keeps right brace in case of \cmd{words}. For example:

before (uses | for current text cursor, so command \textbf looks like \tex|tbf)
`\tex|tbf{abc}`

after
`|abc}`
