### ISSUE TITLE
[Request] TeXStudio feature for XML first Workflow

### ISSUE THREAD

**Issue by pskumaresh06** [texstudio-org/texstudio#3505]
Hi,

I want to use SyncTeX for my XML first workflow and I have mentioned my process in below:

**My process**:
Input XML 
--> XML to TeX (using XSLT) 
--> TeX to PDF using LaTeX compiler (Removing TeX file once PDF created)
--> PDF preview

Attached sample:
[XMLfirst.zip](https://github.com/texstudio-org/texstudio/files/14194142/XMLfirst.zip)

When I use a TeX file as my main input, synchronization between the TeX and PDF files works well. However, I’m considering switching my main input to an XML file and I’m curious if it’s possible to achieve synchronization between the XML and PDF files.

**Comment by sunderme** [comment]
this has nothing to do with texstudio.
Please ask on tex.stackexchange. And the probable answer is "no, it does not work".
