### ISSUE TITLE
\cite and \ref auto-complete in subfile depends on the order the files were opened

### ISSUE THREAD

**Issue by Sean-Dave** [texstudio-org/texstudio#3508]
### Environment
- TeXstudio: 4.7.2
- Qt: ?
- OS: Windows 10
- TeX distribution: miktex 

### Expected behavior

I have a main file, say `main.tex` and some subfiles, say `sub1.tex` and `sub2.tex`. In each subfile, I use `\externaldocument` to reference the other subfile, and in the main file I have a bibliography loaded using biblatex and `\addbibresource`.

When I type `\cite{` in one of the subfiles, it should auto-complete (or auto-suggest) items from my loaded bibliography in the main file. By "auto-complete (or auto-suggest)" I mean something like this picture where there is the drop-down menu appearing:
![image](https://github.com/texstudio-org/texstudio/assets/138178311/4bafdec5-8aa8-4c15-bf55-900cb9caeff2)

And similarly, when I type `\ref{` in one of the subfiles, say `sub1.tex`, it should auto-complete (or auto-suggest) items from the other subfile, `sub2.tex`. 

The key is that this behaviour should occur _all the time_ and not just sometimes. 

### Actual behavior

In reality, I can get the above behaviour to work _some of the time_ but not all the time. Specifically, I have found that, when I open texstudio on my computer and it has no files open, if I open `main.tex` **_after_** opening the two subfiles, then the expected behaviour above occurs. But, if I open `main.tex` **_before_** opening either of the subfiles, then the subfiles which were opened after `main.tex` do not experience the expected behaviour. 

### How to reproduce

The citation part would require an entire bibliography/biblatex setup, but the label referencing is easier. For this, I believe the following three files (in the same directory) would be as minimal as possible: 

`main.tex`
> \documentclass{article}
> \usepackage{xr}
> \usepackage{subfiles}
> \usepackage{hyperref}
> \begin{document}
> \subfile{sub1}
> \subfile{sub2}
> \end{document}

`sub1.tex`
> %! TeX root = sub1
> \documentclass[main]{subfiles}
> \externaldocument{sub2}
> \begin{document}
> \section{blah} \label{sec:blah}
> \end{document}

`sub2.tex`
> %! TeX root = sub2
> \documentclass[main]{subfiles}
> \externaldocument{sub1}
> \begin{document}
> %TRY TYPING \ref{ AND SEE IF THERE IS AUTO-COMPLETE
> \end{document}

To get the error, try opening `main.tex` _**before**_ `sub2.tex`. And to get the expected behaviour, open `main.tex` **_after_** both `sub1.tex` and `sub2.tex`.

**Comment by sunderme** [comment]
not reproducible.
1) What are your setting concerning editor/automatically load included... and editor/cache documents...
2) (current) txs understands subfiles and \externaldocument does nothing for txs.

**Comment by Sean-Dave** [comment]
Thank you for trying to reproduce this. 

I do not have automatically load files on, although I have tried having that setting on. 

![image](https://github.com/texstudio-org/texstudio/assets/138178311/20e84452-1614-4e39-839a-a1308ce7c07a)
![image](https://github.com/texstudio-org/texstudio/assets/138178311/4e1a054b-830d-434a-9cf9-ae31093590ff)
![image](https://github.com/texstudio-org/texstudio/assets/138178311/989e6339-00de-48aa-bf51-7d590a32909b)

What do you mean by "\externaldocument does nothing for txs"? If I want to reference sub1 in sub2, my understanding is that I need \externaldocument{sub1} in sub2.

**Comment by sunderme** [comment]
1) automatically load ... needs to be on, otherwise sub2 is never loaded and its content (i.e. the label) is not known to txs.
2) txs only takes the subfile documentclass and the given root document in order to load the whole document structure and enable syntax checking and completion.

**Comment by sunderme** [comment]
not reproducible if automatic loading is active
