### ISSUE TITLE
2 questions regarding DE translations of insert Graphics Dlg

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3511]
Start txs with DE translations

1) Even so all texts for the five checkboxes in the first row are translatable, only the last one has been translated to DE. 
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/72dce10f-b953-4538-a9ec-de608d68e652)
Tooltip translation explains the English words used:
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/9171fdb8-c3f5-4675-89e4-8f49c7b93a9f)
Thus I would like to revert translation to _here (H)_ instead of _hier (H)_.
OK?

2) The code sets window title twice (s. translations # 930 & 931):
l. 50: setWindowTitle(tr("Insert Graphic"));
l. 78: setWindowTitle(tr("Insert Graphics", "Wizard"));
I would like to replace l. 50. with l. 78
OK?

**Comment by sunderme** [comment]
1) maybe "HERE (H)" to distinguish between the two variants
2) okay

**Comment by octaeder** [comment]
ad 1) What about changing both to `here (h)` and `Here (H)` ?

**Comment by sunderme** [comment]
Also fine

**Comment by octaeder** [comment]
done (also for tooltip, text 932), but text 923 here (h) needs acceptance (can't save it, is suggestion)
