### ISSUE TITLE
Sidebar in template dialog shows file name instead of template name for online repository

### ISSUE THREAD

**Issue by Alexander-Wilms** [texstudio-org/texstudio#3513]
### Environment
- TeXstudio: 4.7.2
- Qt: 6.6.1
- OS: openSUSE Tumbleweed
- TeX distribution: TeX Live

### Expected behavior
The sidebar in the template dialog should show the name field of each template's JSON.

[template_DIN 5008 B.json](https://github.com/texstudio-org/texstudio-template/blob/3d936b0df195b7105dedbdcb50404dff6d037a4c/Letters/template_DIN%205008%20B.json)

```json
{
    "Author": "Alexander Wilms",
    "Date": "2023-09-10",
    "Description": "A letter template conforming to the German national standard DIN 5008 B",
    "License": "Public Domain",
    "Name": "DIN 5008 B",
    "Version": "1.0"
}
```

### Actual behavior

I shows the file name:
![image](https://github.com/texstudio-org/texstudio/assets/3226457/23660b8a-1f10-4723-8ac7-bee55915bbbc)

### How to reproduce
File > New from Template...

A local template is shown as expected:
![image](https://github.com/texstudio-org/texstudio/assets/3226457/272d131a-a57b-4ac7-aaad-fba0e2737a0c)

**Comment by octaeder** [comment]
works as expected

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/4b811690-1951-4c3b-a20c-82c1488769fa)

json file:
```json
{
    "Author": "Alexander Wilms",
    "Date": "2023-09-10",
    "Description": "A letter template conforming to the German national standard DIN 5008 B",
    "License": "Public Domain",
    "Name": "DIN 5008 B",
    "Version": "1.0"
}
```
I created the necessary tex file by choosing the same letter from the online repository and let it insert into an editor. Then I saved it where the json file is located (base name `template_DIN_5008 B`).

Maybe you mixed up something. Your link above opens a quite large json file.

**Comment by Alexander-Wilms** [comment]
I mean the one listed under Online Repository > Letters > template_DIN 5008 B

**Comment by octaeder** [comment]
This is indeed the file name of the template. The reason for this is that the tree is build without loading the json-file. It gets loaded when you click on the (file) name in the tree. From that point on the name from the Json could be set in the tree.
@sunderme I could make a PR for this from my local build.

Example: I clicked on the three names to the left. The result can be seen to the right:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/e54e1546-a025-4c9d-ac8d-dcc66b871b52) ![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/937b649b-151b-4ecb-89be-d1217229455b)

And these are the same names shown in the info area:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/91789891-4b63-4a79-8ccf-a4628af07189)
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/f393fe27-4b18-466d-a226-669778af566d)
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/c95ec77c-a591-414f-aca1-f80c384e9d4d)

**Comment by Alexander-Wilms** [comment]
It would be nice if always show the correct name.

Maybe the template_ prefix could just be removed from all files in https://github.com/texstudio-org/texstudio-template

Or one could use Github Actions to create an additional .json file that contains all the necessary info, but that seems overkill.

**Comment by octaeder** [comment]
I need a statement from @sunderme

**Comment by octaeder** [comment]
@sunderme Please add Enhancement label

**Comment by sunderme** [comment]
removing template_ is fine.
