### ISSUE TITLE
Provide a more recent and complete "LaTeX Reference"

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#352]
The current version of "LaTeX Reference" shipped with TXS (in the Help menu) is rather old (October 2015). A more recent (October 2018) and more complete one is [available](https://latexref.xyz/dev/latex2e.html).

**Comment by sunderme** [comment]
the repository contains july/2018

**Comment by sunderme** [comment]
our latex2e css style sheet does not work with that version ...

**Comment by dbitouze** [comment]
Still a new "LaTeX Reference", now available [as a package](https://www.ctan.org/pkg/latex2e-help-texinfo) (current versions in English and in French).

**Comment by sunderme** [comment]
done
