### ISSUE TITLE
[RFE] Allow easy renaming of existing labels in a document

### ISSUE THREAD

**Issue by chskcau** [texstudio-org/texstudio#3525]
### Describe the feature and the current behavior/state

TeXstudio has integrated handling of labels and references; that is to say, it recognizes commands such as `\label`, `\ref` and `\eqref`, recognizes whether the label of a reference has been defined, detects duplicate label definitions, and allows the user to go to a label's definition or find its usages.

What TeXstudio does not yet allow is renaming a label such that it is updated everywhere in a document. I would therefore like to propose this as a possible new feature in a future version of TeXstudio. I imagine this feature as being available from the context menu upon right-clicking a label, together with "Go to Definition" and "Find Usages".

This feature would, therefore, be similar to the "Rename Variable in Scope" functionality found in many IDEs, except that there would be no need to care about scope.

Some background: when writing large documents, I usually use prefixes for labels (e.g. `fig:`, `tab:`, `theo:`, `lem:`, `fn:`, `eq:` and so on), but sometimes I find myself needing to update these prefixes, e.g. when a theorem turns into a corollary of a more general theorem or when a lemma is upgraded to a theorem (or the converse). I also sometimes forget these prefixes (notably `eq:`), and only realize later. Finally, I sometimes want to change established labels, e.g. to more clearly indicate what a theorem says and when I realize upon referencing (at a later date) that the original label was unclear.

### Who will benefit with this feature?

Users using TeXstudio to write larger texts with many labels referenced multiple times; in particular, users who do not use consistent naming schemes for labels right from the start, or later found that they want or need to tweak their labeling scheme.

Furthermore, users who collaborate with others on the same document will benefit since coherent coding standards can be maintained more easily this way.

### Any Other info

n/a

**Comment by octaeder** [comment]
This should do the job:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/b75eef6c-b45d-4f34-b8b5-e0ed5ad99ee7)

change and press replace, works for projects, if necessary.

**Comment by sunderme** [comment]
So, I take it that the requested feature is already there.
