### ISSUE TITLE
Autocompletion of enviroment not in the main file

### ISSUE THREAD

**Issue by bykhov** [texstudio-org/texstudio#3528]
### Environment
- TeXstudio: 4.7.2
- Qt: 6.6.1
- OS: Windows10
- TeX distribution: miktex

### Expected behavior
If I have environment definition 
```
\newtcolorbox{critical_remark}
{ 
    breakable,
    colframe=red!75!black
}
```
auto-completion is expected with `\begin{`

### Actual behavior
If the environment definition is not in the "main" file, auto-completion for this custom environment does not work.

### How to reproduce
* Create a file with some custom environment, e.g. `conf.tex'
* In the "main" file, use
``` 
\input{conf.tex}
\input{chap1.tex}
```
While editing `chap1` auto-completion for a custom environment wouldn't work.

**Comment by sunderme** [comment]
please provide a complete example with all files to avoid ambiguities.

**Comment by bykhov** [comment]
Here is the code.
Please note that some changes in the code will require a reboot in order to change an auto-completion behavior.
[tex.zip](https://github.com/texstudio-org/texstudio/files/14341414/tex.zip)
