### ISSUE TITLE
add support to change Editor font for Chinese

### ISSUE THREAD

**Issue by rfhamz** [texstudio-org/texstudio#3540]
### Describe the feature and the current behavior/state
now there is only English font defined in Editor setting. could you add Chinese font option when I use English + Chinese in edtior window.
### Who will benefit with this feature?
who use Chinese.
### Any Other info
currently there is no good dispaly for Chinese, see attachment.

**Comment by rfhamz** [comment]
![2024-02-29 22 31 20](https://github.com/texstudio-org/texstudio/assets/93310949/58c2f984-99c3-4aaf-9535-52227ee0d1ca)

**Comment by muzimuzhi** [comment]
What are your OS, OS version, TeXstudio version, and the current TeXstudio font setting?

**Comment by rfhamz** [comment]
> What are your OS, OS version, TeXstudio version, and the current TeXstudio font setting?

OS win10(not remember the version)/ texstudio=4.7.2, current font setting is consolas

**Comment by sunderme** [comment]
as far as I see it, the fonts should have all needed characters.
There is little the app can do about it as Qt handles fonts and font-substitution.

**Comment by sunderme** [comment]
I close this as this is rather an issue with the used font
