### ISSUE TITLE
bibtex doesn't work when aux files separated: couldn't open file name 'main.aux'

### ISSUE THREAD

**Issue by DiffPetrovich** [texstudio-org/texstudio#3542]
Hello!

Seems bibtex doesn't work when aux files stored in separate folder. The command I use in settings:
`bibtex.exe -include-directory=E:\LaTeX\Temp %`

(But it's somewhat unclear what the syntax of this particular command should be from the [guide](https://github.com/texstudio-org/texstudio/wiki/Tips-And-Tricks))

I thought the problem is with bibtex.exe itself, but somehow it works fine when I use SublimeText + LaTeXTools + aux file storing in [\<<temp\>>](https://latextools.readthedocs.io/en/latest/settings/#:~:text=values%20are%20honored%3A-,%3C%3Ctemp%3E%3E,-%3A%20uses%20a%20temporary).

### Environment
- TeXstudio: 4.7.2
- Qt:  6.6.1
- OS: Windows 10
- TeX distribution: MiKTeX 24.1-x64

Additional:
- SublimeText Build 4121
- LaTeXTools v4.0.0-beta.0

### Expected behavior
Should work as with no aux separation: fully ready document

### Actual behavior
I receive message:
> I couldn't open file name `main.aux'

Bibliography doesn't compile, citation numbers are `?`

### Additional

Related LaTeXTools settings:
"aux_directory": "\<<temp\>>"
"output_directory": "\<<temp\>>" (use to hide synctex.gz)
"copy_output_on_build": true (get pdf only)
"builder": "basic"

Content of \<<temp\>> folder used for Sublime after compilation:
![image](https://github.com/texstudio-org/texstudio/assets/89711035/993c5e16-dcc8-4d48-b133-303f33f1582b)

Content of my custom temp folder used for TeXstudio:
![image](https://github.com/texstudio-org/texstudio/assets/89711035/6aa8f00d-1ca8-4597-a683-57779608dec1)

**Comment by sunderme** [comment]
this is a general latex set-up question.
I propose to ask on tex.stackexchange
This list is focused on texstudio, the editor, issues.
