### ISSUE TITLE
export and import all macros into one file

### ISSUE THREAD

**Issue by rfhamz** [texstudio-org/texstudio#3543]
### Describe the feature and the current behavior/state
OS: win10
TeXstudio 4.7.2 (git 4.7.2)
Using Qt Version 6.6.1, compiled with Qt 6.6.1 R

now at menu bar, there is Macors defined by user, but after I made lots of macros, I found I cannot export all macros into one file for better maintain in local, I have to export one by one, it is not convinience. could you all button to export all and import all? thanks.
### Who will benefit with this feature?
who would fresh OS or uninstall texstudio to fix issue, they can use this export/import customized macros quickly.

**Comment by octaeder** [comment]
you can import several files at once from one directory. Just select what you need in the file selection dialog.
export all will be available with next release ([s. changelog](https://github.com/texstudio-org/texstudio/blob/master/utilities/manual/source/CHANGELOG.md)), maybe available in less than a few weeks.

**Comment by sunderme** [comment]
export all should suffice.
