### ISSUE TITLE
Closing \item auto completion

### ISSUE THREAD

**Issue by tmelorc** [texstudio-org/texstudio#3544]
### Environment
- TeXstudio: 4.7.4 (git 4.7.1-149-g458e45ec4)
- Qt: Qt 5.15.3 R
- OS: Linux Mint 21.2
- TeX distribution: texlive

### Description
What is the default behavior when finish typing an item?  I mean, my txs show the auto completion but it does not close it after I type the whole command plus a blank space.

See the screenshot below. 

![Seleção_005](https://github.com/texstudio-org/texstudio/assets/15181573/7d6fbbb4-cb41-45d8-9954-23f1e2cdf1fd)

IMHO after typed `\item<space bar>` the panel should close. 
But it only closes after a second space (for ex. `\item<space bar><space bar>`) or after any letter and another space (for ex. `\item<space bar>foo<space bar>`).

Is this the default or only in my txs?
Regards.

**Comment by octaeder** [comment]
I see the same behavior with 4.7.2 and current build (win10).

**Comment by sunderme** [comment]
it is defined as "\item "

**Comment by tmelorc** [comment]
> it is defined as "\item "

So you say that the command used in the completion feature contains a blank space after it? 

When I type `\alpha` the completion closes after the 1st blank space. Maybe the same could be done for `\item`.

**Comment by sunderme** [comment]
the point is that people want it to complete as "\item " (unlike "\alpha")

**Comment by tmelorc** [comment]
> the point is that people want it to complete as "\item " (unlike "\alpha")

Oh, now I got the point. To close the panel we have to type exactly the same string as the one inserted when using the completion tool.

For me is faster to type `\item` instead of use the completion. But then I need to type space twice.

**Comment by octaeder** [comment]
why not use `ctrl+i`?

**Comment by tmelorc** [comment]
> why not use `ctrl+i`?

In my txs, it is for `\textit{}`.

**Comment by octaeder** [comment]
sorry, it's `ctrl+shift+i`
