### ISSUE TITLE
Closing file without saving changes doesn't discard changes

### ISSUE THREAD

**Issue by jcasale** [texstudio-org/texstudio#3550]
### Environment
- TeXstudio: 4.7.3
- Qt: 6.6.2
- OS: Windows 11
- TeX distribution: miktex

### Expected behavior
After editing a file and then closing it without saving changes, I expect that reopening it loads the original, unsaved version.

### Actual behavior
When the file is reopened, the changes are still present despite choosing to discard them.

### How to reproduce
My document files are as follows:

1. `document.tex`

    ```latex
    \documentclass[letterpaper]{article}
    
    \usepackage[sfdefault]{roboto}
    \usepackage[utf8]{inputenc}
    \usepackage[T1]{fontenc}
    
    \title{Title}
    \author{Author}
    \date{\today}
    
    \begin{document}
      \maketitle
      \pagebreak
      \tableofcontents
    
      \newpage
      \input{introduction}
    \end{document}
    ```

2. `introduction.tex`

    ```latex
    \section{Introduction}
    ```

After opening the `introduction.tex`, adding the second and third lines, then closing it without saving and selecting discard, the changes are still present when the file is reopened until restarting texstudio.

![Screenshot 2024-03-03 093747](https://github.com/texstudio-org/texstudio/assets/9957114/e90ed012-e14e-41e2-9259-553b10d9e697)

An archive of the document files and a video capture illustrating the behavior is attached.
[repro.zip](https://github.com/texstudio-org/texstudio/files/14473756/repro.zip)

**Comment by octaeder** [comment]
I can reproduce in the following way (win10, current dev): Open root, select included file "introduction" in structure tree (which is opened then). Edit the opened file, then click on the close button of the tab. Discard changes. As before open the second file by clicking on the file name "introduction" in the structure tree. The file is opened with status edited:

![image](https://github.com/texstudio-org/texstudio/assets/102688820/912acc77-cd50-490c-ad17-8e601963afba)

This is somewhat similar to my  #2965, but not a duplicate.
No document caching activated.

**Comment by octaeder** [comment]
addition: When I try to close the root doc after the procedure given above I'm asked again about "introduction".

**Comment by sunderme** [comment]
This comes from txs keeping *all* documents of a project (root&child docs) in memory until the project is closed.
I agree, closing a doc and selecting discard may handled better by a reload.
