### ISSUE TITLE
CJK Puncuation support.

### ISSUE THREAD

**Issue by KazamaHoshino** [texstudio-org/texstudio#3551]
While writing in CJK (Chinese, Japanese, Korean), the current location of some of the puncuations is in a strange location. It is very difficult for formatting.
Hope there could be a better support. 
Those characters:
U+FF08 U+FF09
U+FF3B U+FF3D 
U+3010 U+3011
U+300C U+300D
U+300A U+300B
are having such problem.
[图片](https://github.com/texstudio-org/texstudio/assets/162074974/91f765d1-ca24-48f5-959c-be53d2790e2e)
It could help people like me, who is trying to use special CJK puncuations.

**Comment by muzimuzhi** [comment]
Does https://github.com/texstudio-org/texstudio/issues/851#issuecomment-571298949 work for you?

**Comment by KazamaHoshino** [comment]
Yes, The fixed pitch must be disabled for the proper display.

**Comment by sunderme** [comment]
so, now, at least *also* for the mentioned characters, txs automatically uses "non-constant character width" mode
