### ISSUE TITLE
Additional Search Paths: Allow Special Chars for specifying `Log File` and `PDF File`

### ISSUE THREAD

**Issue by randolf-scholz** [texstudio-org/texstudio#3552]
When compiling `main.tex` using the output-directory `__tex__/%/`, i.e.

```bash
pdflatex -shell-escape -synctex=1  -halt-on-error -output-directory=__tex__/%/  %.tex
```

Then TeXstudio does not find the log-file if I specify the `Additional Search paths: Log File` as `__tex__/%`, but it does if `__tex__/main` is used. So it appears the special character `%` is currently not supported in this field.

**Comment by randolf-scholz** [comment]
Alternatively, if `Additional Search paths: Log File` would search subfolders as well, it would be sufficient to specify it simply as `__tex__`.

**Comment by sunderme** [comment]
general remark: `%` is replaced by the filename, no matter where it is placed in the command. i.e. `.... __tex__/*%*/...` is also replaced.

**Comment by sunderme** [comment]
additional search files is a general path

**Comment by sunderme** [comment]
I really don't see the necessity to change something here.
There are usually two ways, adapt to the program or adapt the program. No need to change txs to add a special feature for the userbase <= 1, just create a dump folder.

**Comment by randolf-scholz** [comment]
Previously, I only used `-output-directory=__tex__`, but putting all the junk in the subdirectory `__tex__/$fname` is nice if multiple files with similar names are compiled from the same directory (e.g. `chapter1.tex`, `chapter2.tex`, etc.). Makes it easier to find what you are looking for if you need to inspect some of the build files.

**Comment by sunderme** [comment]
looking at it again, a relative path like "log" has to suffice.

This will not be implemented.
