### ISSUE TITLE
Compilation of bib file (Biblatex, biber) suddenly not working

### ISSUE THREAD

**Issue by IsGira** [texstudio-org/texstudio#3555]
This morning my .tex file refused to compile my .bib file, although yesterday it worked just fine. I thought it was a problem with the .bib, so I created a new .bib with very few refs and tried to compile a shorter .tex with it. It compiles up to two refs, but as soon as I add a third ref to the new .bib it gives me an error message. I am working on Mac, but I have an additional computer running on Ubuntu. I compiled my file with TexStudio on Ubuntu, and it works just fine. so I just downloaded the latest TexStudio version for Mac (March 1, 2024). It still doesn't work.

### Environment
- TeXstudio: 4.7.3
- Qt: Sorry, I don't know what this means.
- OS: Mac
- TeX distribution: texlive

### Expected behavior

To produce the bibliography.

### Actual behavior

It doesn't produce the bibliography although it says it finds the file.

Process started: biber "Manuscript-[4March-2024]"

INFO - This is Biber 2.19
INFO - Logfile is 'Manuscript-[4March-2024].blg'
INFO - Reading 'Manuscript-[4March-2024].bcf'
INFO - Found 132 citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex file '/Users/ifuchs/Documents/Work/GenderJUNE24.bib' for section 0
INFO - LaTeX decoding ...
INFO - Found BibTeX data source '/Users/ifuchs/Documents/Work/GenderJUNE24.bib'

Process exited with error(s)

Process started: pdflatex -synctex=1 -interaction=nonstopmode "Manuscript-[4March-2024]".tex

Process exited normally

**Comment by sunderme** [comment]
compilation are most likely  due to latex setups.
Please ask on tex.stackexchange

**Comment by IsGira** [comment]
Well, apparently I just needed to reboot the machine.
