### ISSUE TITLE
Icelandic letters in \section{}, \chapter{}

### ISSUE THREAD

**Issue by Tomminn** [texstudio-org/texstudio#356]
Dear people

I just upgraded the TexStudio and now I get error's that I didn´t have few weeks ago. 

Missing \endcsname inserted. ...}{{1}{9}{Borðspil á Íslandi}{chapter.1}{}} 
...
Missing \endcsname inserted. ...Mylla og Færingatafl}{subsection.1.1.3}{}}

\chapter{Borðspil á Íslandi}
\label{sec:BordspilAIslandi}
.. 
\subsection{Mylla og Færingatafl}
\label{sec:MyllaOgFaeringatafl}

It seems only to affect Icelandic letters like Þ,þ,Æ,æ,Ð,ð but not others like á, í and others

I have these commands in the tex-file
\usepackage[english,icelandic]{babel}
\usepackage[T1]{fontenc}
\usepackage[latin1]{inputenc}

Kind regards
Tómas V. Albertsson

**Comment by sunderme** [comment]
if the error comes up in the log file, this is a latex problem, not a problem of the editor txs.
please ask this kind of questions on tex.stackexchange.com
