### ISSUE TITLE
make table template,wrong

### ISSUE THREAD

**Issue by aabarler** [texstudio-org/texstudio#3560]
### Environment
- TeXstudio: 
[texstudio_backtrace1.txt](https://github.com/texstudio-org/texstudio/files/14558601/texstudio_backtrace1.txt)

- Qt: 
- OS: 
- TeX distribution:

**Comment by muzimuzhi** [comment]
>   [texstudio_backtrace1.txt](https://github.com/texstudio-org/texstudio/files/14558601/texstudio_backtrace1.txt)

Content of the attachment:

```
unknown at 7ffe823e97f2 (TXS-Version 4.7.3 R )
[bt] 00007ff766bfa8b9  q+3508877
[bt] 00007ff766bf9acb  q+3505311
[bt] 00007ff766b127f7  q+2558411
```

**Comment by sunderme** [comment]
insufficient information, no feedback
