### ISSUE TITLE
Add custom beamer commands to side panel (beamer section)?

### ISSUE THREAD

**Issue by luisvalenzuelar** [texstudio-org/texstudio#3561]
How can I add items to the "beamer commands" section in the side panel? I know how to create macros ([example](https://tex.stackexchange.com/a/393725/77895)), but would like to add them to the beamer section.

**Comment by sunderme** [comment]
the tags are fixed in the source code.
If you can compile txs yourself, you can change them in the source tags folder.

**Comment by luisvalenzuelar** [comment]
Probably a low frequency use but maybe they could become editable in the future :)

**Comment by octaeder** [comment]
@luisvalenzuelar They will be editable with next release (s. #3566 for a description).
