### ISSUE TITLE
Session file doesn't record language

### ISSUE THREAD

**Issue by trg818** [texstudio-org/texstudio#3562]
Session data can be saved in the session logs with the extension `.txss2`. However, it seems that the language of the individual files is not saved. I frequently have several tabs with different files in different languages open, but when I start TeXStudio and load the previous session from `.txss2` file, all tabs are opened with the default language (US English in my case), and I have to set those in other languages anew.
This is, in my view, a bug; in case it isn't, it should be taken as a feature request. At any rate, it has been a very long-standing issue.
### Environment
- TeXstudio: 4.7.3
- Qt: 6.6.2
- OS: Mac Ventura 13.6.5
- TeX distribution: TeXLive (I think), installed via homebrew

### Expected behavior
When loading a session with various files in different languages, the appropriate language as set and saved in the previous session should be restored.

### Actual behavior
When loading a session with various files in different languages, all of them are open with the default language.

**Comment by sunderme** [comment]
I don't think that spellchecker language should be part of the session.
For your issue, just use magic comments for language codes (https://texstudio-org.github.io/advanced.html#advanced-header-usage)
