### ISSUE TITLE
Moving the cursor to the beginning/end of a word

### ISSUE THREAD

**Issue by FloMiLe** [texstudio-org/texstudio#3567]
### Describe the feature and the current behavior/state
Currently, the shortcuts "Move cursor right (1 word)" and "Next placeholder or one word right" move the cursor to the beginning of the next word. In other editors (e.g. VS Studio Code, Obsidian, and I believe previously in TXS as well), moving right places the cursor at the end of a word, and moving left places the cursor at the beginning of a word. This way one can reach both ends of a word, which is particularly helpful with multiple cursors.

### Who will benefit with this feature?
Anyone who is used to other editors or uses multiple cursors to sift through lines of code.

**Comment by sunderme** [comment]
duplicate to  #975
Basically for every day navigation, I find the current behaviour more intuitive.
If someone wants to to provide code (which can configured), okay, but I will not look into it.
