### ISSUE TITLE
Several "Basic Key Mapping" shortcuts appear multiple times

### ISSUE THREAD

**Issue by FloMiLe** [texstudio-org/texstudio#3568]
### Environment
- TeXstudio: 4.7.3
- Qt: 6.6.2
- OS: Mac 14.2.1
- TeX distribution: TeX Live

### Expected behavior
"Basic Key Mapping" shortcuts should appear only once in the list, as there is the extra column "Additional Shortcut".

### Actual behavior
Several "Basic Key Mapping" shortcuts appear multiple times.

### How to reproduce
I don't know whether this is intended or possibly an artefact of a settings file that has endured many TXS versions.

**Comment by sunderme** [comment]
It is historic.
But I don't think it is worth to spend effort here.
