### ISSUE TITLE
Jump to source file

### ISSUE THREAD

**Issue by chentaolue** [texstudio-org/texstudio#3569]
### Describe the feature and the current behavior/state

I am currently using the latest version 4.7.3. In the previous version, there is a functionality to jump to the source (latex) code when right-clicking the pdf file. This feature is unavailable now.

**Comment by muzimuzhi** [comment]
Works well with version 4.7.3-18-g124682036 installed on macOS 13.6.5.

Can you provide your environment?
https://github.com/texstudio-org/texstudio/blob/007c734b4a210f4e1e73fd39ee274a9473e1e83e/.github/ISSUE_TEMPLATE/bug.md?plain=1#L8-L12

**Comment by sunderme** [comment]
no feedback
