### ISSUE TITLE
Custom dictionary not saved

### ISSUE THREAD

**Issue by PlamenToby** [texstudio-org/texstudio#3572]
### Environment
- TeXstudio:  VERSION 4.7.3
- Qt: 
- OS: Windows 11
- TeX distribution: miktex

### Actual behavior
Words added to the custom dictionary get cleared up after restart. When I check the dictionary, they are there before closing Tex Studio, and disappear after restart. 

### How to reproduce

Misspell a word, right click on it and add it to the dictionary. Close the software and open it again. That word is marked as misspelled again.

**Comment by PlamenToby** [comment]
Followed the advice here: 

https://sourceforge.net/p/texstudio/discussion/907840/thread/93912035/

Seems to have solved the problem.

**Comment by sunderme** [comment]
so, we can close this ?

**Comment by PlamenToby** [comment]
Yes, I think that the link I posted would help anyone experiencing the same problem, and it seems to solve it.
