### ISSUE TITLE
grammar checking with languagetools

### ISSUE THREAD

**Issue by JPelda** [texstudio-org/texstudio#3576]
Using
TeXstudio 4.7.2 (git 4.7.2) on Windows 10
Nutze Qt-Version 6.6.1, kompiliert mit Qt 6.6.1 R

### Expected behavior
Highlighting not only of spelling mistakes but also of grammar mistakes.

### Actual behavior
With running spellchecker either languagetool 4.1, languagetool 4.8 or languagetool 6.3. None of these checkers mark any grammar mistakes. Misspelling, however, is marked. Marking of mistakes in options are all set to TRUE. Grammar mistakes should be highlighted with colour.

What version of languagetool provides a correct highlighting of grammar mistakes? Or is it a texstudio bug?
In texstudio documentation languagetool 4.8 is shown in the corresponding section with file languagetool.jar which is not in the package of languagetool 4.8 and seems not to be the right link to the LT, that is languagetool-server.jar (related to languagetool 6.3).

**Comment by sunderme** [comment]
Can't confirm. It finds "falscher Kasus" on "Die Haus ist zu groß." (german)
Tested with LT 5.9.
