### ISSUE TITLE
TeXstudio crashes when opening a file from the sidelist

### ISSUE THREAD

**Issue by typohandwerker** [texstudio-org/texstudio#3577]
When I try to open a file (via \input) from the sidelist, TeXstudio crashes.

### Environment
- TeXstudio: 4.7.3
- Qt: 6.6.2
- OS: Win10 22H2 (19045.4170)
- TeX distribution: miktex

### Expected behavior
TeXstudio should open the file in a new tab.

### Actual behavior
TeXstudio crashes.

**Comment by sunderme** [comment]
no feedback

**Comment by typohandwerker** [comment]
https://github.com/texstudio-org/texstudio/assets/126964739/c994610f-955d-4671-9132-9d9acbf1cac8

When I try to open the included file "vars", nothing happend, the status bar changed to no feedback (in german: "Keine Rückmeldung").

**Comment by sunderme** [comment]
example means, you need to give us files which crash. We need to replicate the situation here.
Furthermore I assume, the second file does notmcrash?

**Comment by typohandwerker** [comment]
Different files with different contents can lead to a crash. It is not limited to this one file.

**Comment by muzimuzhi** [comment]
To debug, usually an example document and list of steps which can reliably trigger the problem are needed.

**Comment by tscheckie** [comment]
I have the same problem. It isn't related to any specific file. It just happens on a regular basis on any project I'm working on. Furthermore, it does not happen always, but often. It seems to me like you need to have TeXstudio open for a while and then try to open a file from the side list. Right after program start, everything is fine. Even when I try to open the file that caused the crash and restart TeXstudio, everything works fine. For me, it looks like it is not file related. It doesn't matter which file I want to open. Is seems to be a problem with the side list itself.

The directory I'm working with is a Nextcloud directory. Maybe this is causing the problem?
