### ISSUE TITLE
\autocites could parse more bibliographical references

### ISSUE THREAD

**Issue by Euan-Wall** [texstudio-org/texstudio#3578]
### Describe the feature and the current behavior/state

When \autocites is entered, two bibliographical references are parsed, highlighted and it is possible to search the bibliography for them. If there are more than two references, the third and following ones simply appear in plain text.

It would be nice if \autocites could parse more bibliographical references, allowing for their easy search and preventing mistakes in entering the reference key.

### Who will benefit with this feature?

Users with bibliographical reference-heavy documents.

**Comment by sunderme** [comment]
duplicate #3234
