### ISSUE TITLE
TexStudio non-responsive Ubuntu 22.04.1

### ISSUE THREAD

**Issue by dadelson** [texstudio-org/texstudio#3579]
### Environment
- TeXstudio:  4.7.3.0
- Qt: Qt5
- OS: Linux HP-G4 6.5.0-26-generic 26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- TeX distribution: Version 3.141592653 (TeX Live 2022/dev/Debian)

### Expected behavior
TeXstudio should open and respond to mouse.

### Actual behavior

TeXstudio opens, does not respond to mouse and a popup window comes up asking if you want force quit or wait. You can wait forever and nothing happens.  I have tried re-installing TexStudio package and also tried the AppImage. Both give the same outcome and are non-responsive.

**Comment by sunderme** [comment]
not reproducible.
you can try to remove ~/.config/texstudio

**Comment by dadelson** [comment]
Tried that, still getting not responding.

________________________________

**Comment by dadelson** [comment]
Checked syslog when starting texstudio and these entries correspond to start through force quit.

Mar 27 19:35:19 HP-G4 org.gnome.Nautilus[9054]: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Mar 27 19:35:19 HP-G4 gnome-shell[1745]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x2a00008 specified for 0x2a00006.
Mar 27 19:35:20 HP-G4 org.gnome.Nautilus[9054]: qt.network.ssl: QSslSocket: cannot resolve EVP_PKEY_base_id
Mar 27 19:35:20 HP-G4 org.gnome.Nautilus[9054]: qt.network.ssl: QSslSocket: cannot resolve SSL_get_peer_certificate
Mar 27 19:35:27 HP-G4 systemd[1]: tmp-.mount_texstuGFb6dT.mount: Deactivated successfully.

________________________________

**Comment by sunderme** [comment]
It works also on gnome(wayland)
What system are exactly running ? Kernel 6.5 is not the default for Ubuntu 22.04.

**Comment by dadelson** [comment]
It’s a new HP Dragonfly G4 with Windows removed and Linux installed. Installation of Linux was done by one of our IT people. I can inquire about specifics. My old laptop with 22.04 has had TexStudio working flawlessly on it for years. It’s something specific to this new machine and it’s configuration. I might have to reinstall Ubuntu.

Cheers,

Dave

Sent from my phone, please excuse the typoos.
________________________________

**Comment by sunderme** [comment]
yes probably. The only other way forward would be to compile txs locally with debug symbols and run it in a debugger to see where exactly it fails. (see https://github.com/texstudio-org/texstudio/wiki/Compiling#linux)

**Comment by dadelson** [comment]
FYI. I opted to reinstall Ubuntu 22.04 using 22.04.1 install USB and the HWE version. After running software update and installing updates, I used synaptic to install the full texlive set of packages and then TexStudio 4.2.1 with synaptic. This works perfectly. After software updates my kernel version is 6.5.0-26-generic. i'm not sure what the previous problem was, but it is not an issue now. Thanks for your prompt responses.

________________________________
