### ISSUE TITLE
"Search selection in the document" button of text analysis is dysfunctional

### ISSUE THREAD

**Issue by clecap** [texstudio-org/texstudio#3581]
### Environment
- TeXstudio: 4.6.3
- Qt: 6.5.2
- OS: MacOS
- TeX distribution: texlive

### How to reproduce
1. Open a tex document
2. Select a text portion
3. Tools -> Analyse Text...
4. In popup window press "Search selection in the document"

### Expected behavior
Popup window "Text Analysis" shows a count restricted to the selection made in the document (similarly as when pressing "Count").

### Actual behavior
Popup window stays empty 

<img width="983" alt="Screenshot 2024-03-27 at 09 34 49" src="https://github.com/texstudio-org/texstudio/assets/7084049/fdcaa481-bf0a-4fc0-9c62-1f766809a16b">

**Comment by sunderme** [comment]
for restricting the scope, change the entry for "Source".
<img width="646" alt="grafik" src="https://github.com/texstudio-org/texstudio/assets/14033169/53880203-f60b-468d-85e9-1e5570c3e0ef">

**Comment by sunderme** [comment]
The "search selection in document" is for, after having counted all occurences, select a word on the right hand side pane and search that word in the actual document.

Looks like that dialog needs some description in the manual ...
