### ISSUE TITLE
regarding "Use docks #3583"

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3584]
### Environment
- TeXstudio: current dev
- Qt: 6.6.2
- OS: Windows 10

* the docks should appear similar to previous versions by default. Otherwise the height of each of them is so small that they are useless (because they are separated) and I have to move all of them into one box.

* Window can't be maximized nor restored. When resizing by drag and drop the window disappears from screen. I can't restore it.

**Comment by muzimuzhi** [comment]
Aha I just posted a similar issue https://github.com/texstudio-org/texstudio/issues/3585.

**Comment by sunderme** [comment]
4.8.0alpha2 has a menu view/show/reset sidepanel/docks
That should reset the docks to a useful state.
This is automatically called when the ini was written before txs 4.8.0
Since you already started 4.8.0 that trigger is not executed for you.

**Comment by octaeder** [comment]
Reset is ok. Windowsize now works as expected, too.
Maybe you could also add the tooltips for the icons as before.

**Comment by octaeder** [comment]
images are missing in `...\utilities\manual\build\html\_images`
dock_start.png, dock_move.png, dock_split.png

**Comment by octaeder** [comment]
where are the new rotated icons needed?

**Comment by octaeder** [comment]
- [ ] the splitter now adds visible space that was not there before:

   ![image](https://github.com/texstudio-org/texstudio/assets/102688820/cb44cddd-4989-498f-8ef9-6af9c6bfdb9b)
   
   This looks odd.

- [ ] With large font (Segoe UI, size 25) first tab not connected to structure widget:

   ![image](https://github.com/texstudio-org/texstudio/assets/102688820/6b59333f-04b2-4a59-878a-7307efcb3db9)
   
   Maybe add a spacer above the tab bar with size of the title.

- [ ] In any case selected tab is separated from widget:

   ![image](https://github.com/texstudio-org/texstudio/assets/102688820/72dcf285-54ab-4ff2-a349-3637333e6551)

   Exception is Symbols (has no surrounding frame):
   
   ![image](https://github.com/texstudio-org/texstudio/assets/102688820/a19a247b-d63f-497e-a1eb-3658ddc2d742)
   
   Maybe all widgets added to the dock should have a frame at top, right, and bottom, but not at left.

- [ ] Maybe a Qt issue. Select lowest visible tab (XY), scroll down, select lowest tab (Macro). I can't scroll upwards:

   ![image](https://github.com/texstudio-org/texstudio/assets/102688820/6bf08b83-42b1-477d-8c9b-6c48e14e6334) then ![image](https://github.com/texstudio-org/texstudio/assets/102688820/66476269-0e63-4b8f-a411-c4be008d6bc1)

**Comment by sunderme** [comment]
cosmetics except last which is qt issue.
Nothing which I will fix.

**Comment by octaeder** [comment]
> images are missing in `...\utilities\manual\build\html\_images` dock_start.png, dock_move.png, dock_split.png

as mentioned above, I think this still needs to be done. Otherwise manual is incomplete.

**Comment by octaeder** [comment]
✔
