### ISSUE TITLE
4.8.0alpha1 on macOS: Side Panel shows contents of all views

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#3585]
### Environment
- TeXstudio: 4.8.0alpha1
- Qt: 6.6.3
- OS: macOS 13.6.5
- TeX distribution: BasicTex 2024

### Expected behavior

Opening Side Panel shows one or empty views, and doesn't change size of window.

### Actual behavior

Opening Side Panel shows no icons to select views but contents of all views, which makes the bottom of a full-screen window lower than bottom of screen.

### How to reproduce

Click on the lower left Side Panel icon.

https://github.com/texstudio-org/texstudio/assets/6376638/708b0b46-dd45-4b66-a75c-f05da8870894

**Comment by sunderme** [comment]
4.8.0alpha2 has a menu view/show/reset sidepanel/docks
That should reset the docks to a useful state.
This is automatically called when the ini was written before txs 4.8.0
Since you already started 4.8.0 that trigger is not executed for you.

**Comment by muzimuzhi** [comment]
> 4.8.0alpha2 has a menu view/show/reset sidepanel/docks

Thanks. That new menu fixed the problem for me.
