### ISSUE TITLE
TS freezes on start when netwrok is down and autocheck new version is on

### ISSUE THREAD

**Issue by lashkevi** [texstudio-org/texstudio#3591]
### Environment
- TeXstudio: 4.8.0 / 4.7.4
- Qt: 5.15.8
- OS: Linux OpenSUSE 15.5
- TeX distribution: texlive

### Expected behavior
TS starts and works. All network functions work in the background and do not affect the main functionality

### Actual behavior
When the network is down (or somehow does not function correctly) and the automatic new version check is on, the main window appears, but it does not respond to the keyboard and mouse clicks. It does not load files, even if it is launched from the file manager. It freezes forever and can be stopped by the KILL (9) signal only.

### How to reproduce
1. Turn on the version autocheck.
2. Turn off network connections (or set a disfunctional proxy, as it was in my case).
3. Launch TS.
4. Try to interact with the window.

**Comment by sunderme** [comment]
not reproducible on ubuntu

**Comment by sunderme** [comment]
not reproducible, no further feedback
