### ISSUE TITLE
biblatex/bibtex choice

### ISSUE THREAD

**Issue by titims** [texstudio-org/texstudio#3594]
One can choose normaly the bibliographic compiler biblatex/bibtex with the menu Bibliography->Type
But it does not work : for one opened document, changing the type does not change . The only way is to change the default build option with the menu Options-> Production 
### Environment
- TeXstudio: 4.7.3
- Qt: 6.6.2
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
![image](https://github.com/texstudio-org/texstudio/assets/60370444/7d9d860d-25b4-4944-a7cb-e54b341d5442)

### Actual behavior
![image](https://github.com/texstudio-org/texstudio/assets/60370444/60e98cf4-b5aa-43a8-a446-dbe4a28716c6)

**Comment by sunderme** [comment]
The type reflects only what menu entries are offered in menu/Bibliography
It has nothing to do with the actual biber/biblatex/etc. run

**Comment by titims** [comment]
Ok so there is no bug !
Sorry for pointing this
Kind regards
