### ISSUE TITLE
Auto completion stops after opening side panel

### ISSUE THREAD

**Issue by tmelorc** [texstudio-org/texstudio#3598]
### Environment
- TeXstudio: 4.8.0 (git 4.7.1-246-g02b4ecd8d)
- Qt: 5.15.3, compiled with Qt 5.15.3 R
- OS: Linux Mint 21.2
- TeX distribution: texlive 2024

After I installed the version cited above, I noticed that the side panel had changed the buttons style, as in the image below. Maybe this change produces some bug.

But, in my case, I don't know, when I open the side panel (usually I keep it closed) the auto-completion stops, I mean, the tab with suggested commands does not appear.

The only way to solve this is restarting txs.

![Seleção_026](https://github.com/texstudio-org/texstudio/assets/15181573/2cae5205-b9d9-4bac-874a-0e66094cc5b3)

### Update

I checked now and the problem appears not when I open the side panel for 1st time but it does when I click on some button on it, for example, Symbols.

**Comment by octaeder** [comment]
I can't reproduce with win10
TeXstudio 4.8.0 (git 4.8.0alpha3-15-g0404a36b5)
Using Qt Version 6.7.0, compiled with Qt 6.7.0 R

**Comment by sunderme** [comment]
I have also seen it on windows. But I have not seen a correlation to anything before it stops.
Unforfunately txs is not running in a debugger.

**Comment by hair-splitter** [comment]
I experienced the same bug as '**tmelorc**'.

My system:
Windows 11
TeX Live 2024
TeXstudio 4.8.0 (git e23e4a5b6) Using Qt Version 6.7.0, compiled with Qt 6.7.0 R
