### ISSUE TITLE
Broken pipe TeXstudio > 4.6.3

### ISSUE THREAD

**Issue by ncgrechlni** [texstudio-org/texstudio#3599]
### Environment
- TeXstudio: > 4.6.3 
- Qt: 6.7
- OS: [Tumbleweed](opensuse:tumbleweed:20240410) 
- TeX distribution: TeX 3.141592653 (TeX Live 2024/TeX Live for SUSE Linux)

### Actual behavior
I had to downgrade 4.8.2 to 4.6.3, but the app image 4.7.3 does run as well. 

Even if Texstudio 4.6.3 is running fine, any version higher than 4.6.3 installed from the tumbleweed jsundermeyer repo ends up with a blank screen. There is no additional information if started in the terminal, but there is a process texstudio running and the journal contains entries: „texstudio error reading events from display: Gebroken pijp“. 
I noticed that there was a qt update to 6.7 for tumbleweed, short before I noticed that my TeXstudio 4.8.2 didn't start anymore. I tried the app image 4.7.3 which is running as fine as does the version from the tumbleweed repo.

I consider this as low priority and informational, because I'm very satisfied with 4.6.3 and 4.7.3 . Thanks for your great work!

### How to reproduce
Start TeXstudio > 4.6.3 .

**Comment by sunderme** [comment]
the report is confusing. 
There is no txs 4.8.2 ?

**Comment by ncgrechlni** [comment]
I'm so sorry, you are absolutely right. It was 4.8.0-2.2-x86_64 which
didn't work for me. Meanwhile I tested the 4.8.0-2.3, too, but no luck
so far (and the same error as before).

Thanks!

-------- Ursprüngliche Nachricht --------
Van: sunderme ***@***.***>
Antwoord-naar: texstudio-org/texstudio
***@***.***>
Aan: texstudio-org/texstudio ***@***.***>
Cc: ncgrechlni ***@***.***>, Author
***@***.***>
Onderwerp: Re: [texstudio-org/texstudio] Broken pipe TeXstudio > 4.6.3
(Issue #3599)
Datum: 12.04.2024 19:11:38

the report is confusing.
There is no txs 4.8.2 ?
—
Reply to this email directly, view it on GitHub [1], or unsubscribe
[2].
You are receiving this because you authored the thread.

[1] view it on GitHub
    https://github.com/texstudio-org/texstudio/issues/3599#issuecomment-2052155378
[2] unsubscribe

**Comment by ncgrechlni** [comment]
After changing the session from xwayland to X, all versions of txs are running fine. Using xwayland I have to stay with 4.6.3-1.4 . Example of the latest running version in a gnome x session:  „TeXstudio 4.8.0 (git 0.0.0++) Maakt gebruik van Qt Versie 6.7.0, gecompileerd met Qt 6.7.0 R“

In general I don't have any problems with xwayland and I never had to complain.

**Comment by ncgrechlni** [comment]
I found another machine with latest tumbleweed running txs just  fine, so I suppose the problem is not txs related. I will stay starting txs from bash with  „QT_QPA_PLATFORM=xcb texstudio“ which works fine for me.
