### ISSUE TITLE
Selecting text word by word in editor view using mouse. 

### ISSUE THREAD

**Issue by ChrisPHL** [texstudio-org/texstudio#36]
I tend to select several words in a row by using double click + hold which does not work in TeXsstudio.

What I expect (and know to work with almost all applications):
```
This is my test text to illustrate the issue.
             |             |
             |             \--- 2.: Move the mouse coursor here: --> "test text to illustrate" will be highlighted.
             \--- 1.: Double click here and hold the second click: --> "test" will be highlighted.
```
Because of the double click instead of single click one can select word by word which is more convinient for me.

What happens:
```
This is my test text to illustrate the issue.
             |             |
             |             \--- 2.: Move the mouse coursor here: --> The selection hangs on the word "test".
             \--- 1.: Double click here and hold the second click: --> "test" will be highlighted.
```

Please insert proper code to enhance the user experience concerning that behaviour.
Thank you!

**Comment by timhoffm** [comment]
Which version are you using? There has been a bug concerning this, which was fixed in 2.12.0.

**Comment by ChrisPHL** [comment]
Oh, this was what I forgot, sorry.
--> TeXstudio 2.10.8 (hg 5802:5ee1d048e556) from the repositories on Linux Mint 18.3.

**Comment by sunderme** [comment]
so, we can close this ?

**Comment by ChrisPHL** [comment]
Yes we can! ;-)
I just tried the requested feature with "TeXstudio 2.12.6 (hg 6631:16db084dae24)
Using Qt Version 5.5.1, compiled with Qt 5.5.1 R" and it worked like a charm.

Sorry for the inconvenience.

Kind regards
Christian
