### ISSUE TITLE
Bring back oxygen classic icon set

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3600]
### Environment
- TeXstudio: s. below
- Qt: s. below
- OS: Windows10
- TeX distribution: miktex

### Expected behavior
Icon set should look consistent as it was before.

### Actual behavior

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/3adb932d-1c11-491d-803a-03e3fe312d64)
left: current dev build, Qt6.7.0
right overlay: 4.7.2 Qt6.6.1

### How to reproduce
Use following settings:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/c73085fb-4776-4b96-b765-3e3ae886a369)

**Comment by sunderme** [comment]
disable "Use system Theme icons", the new icons come from qt
