### ISSUE TITLE
Lists of comboboxes unreadable due to black background

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3601]
### Environment
- TeXstudio: current dev (msys2 build)
- Qt: 6.7.0
- OS: Windows10
- TeX distribution: miktex

Maybe new Qt bug?

### Expected behavior
Text should be readable. Maybe Qt bug?

### Actual behavior
Black background:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/ab29fe96-c042-4787-8fe7-7b65e0628d8f)

Some of the styles like Windows still use white background:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/ecfff2e8-cad9-4272-ba3d-31003db5637d)

### How to reproduce
Just set options as you can see above, close and reopen options dialog.

**Comment by sunderme** [comment]
can't reproduce on win11, looks like qt issue
qt 6.7 delivers a new win11 style

**Comment by octaeder** [comment]
Note: This is a know [Qt6.7 issue](https://wiki.qt.io/Qt_6.7_Known_Issues): 

>Windows: WindowsVistaStyle: Embedding QComboBox into QScrollArea results in black QComboBox-Popup.
