### ISSUE TITLE
No Preferences in the option menu

### ISSUE THREAD

**Issue by Fahazavana** [texstudio-org/texstudio#3603]
I can not access on the preference (Configure TeXStudio) menu 
### Environment
- TeXstudio: 4.7.3
- OS: Mac M3
- TeX distribution: MacTex

<img width="253" alt="Screenshot 2024-04-14 at 19 03 29" src="https://github.com/texstudio-org/texstudio/assets/68125192/5515f816-d00b-4e07-ba29-16b6478e6cc5">

**Comment by sunderme** [comment]
on mac, the preference menu is directly under the "texstudio" menu. That is a mac thing.

**Comment by samcarter** [comment]
@Fahazavana Alternatively press `cmd`+`,`. This opens the preferences in almost all applications.
