### ISSUE TITLE
Add inspection for longtblr labels

### ISSUE THREAD

**Issue by jcasale** [texstudio-org/texstudio#3605]
### Environment
- TeXstudio: 4.8.0 alpha 3
- Qt: 6.6.3
- OS: Windows 11
- TeX distribution: miktex

### Expected behavior
A reference to a longtblr label is not marked as missing.

### Actual behavior
A reference to a longtblr label is marked as missing.

### How to reproduce

Create the document below and note the inspection that indicates the reference is missing.

```latex
\documentclass[letterpaper]{article}
\usepackage[table]{xcolor}
\usepackage{tabularray}

\begin{document}

This reference table~\ref{tbl:my-table} is marked as missing.

\begin{longtblr}[
  caption = {My Table},
  label = {tbl:my-table}
  ]{
    colspec = {X[1]X[1]X[3]X[4]},
    width = \linewidth,
    hlines = {black,solid,0.4pt},
    vlines = {black,solid,0.4pt},
    rowhead = 1,
    rowfoot = 1
  }
  ID & Code & Name & Notes \\
  42 & My Code & My Name & My Notes \\
  ID & Code & Name & Notes
\end{longtblr}
\end{document}
```
![repro](https://github.com/texstudio-org/texstudio/assets/9957114/25447b41-3c9d-46c3-bca0-020f1422c5c0)

**Comment by sunderme** [comment]
just remove the braces from the label definition
`label = tbl:my-table` works fine
