### ISSUE TITLE
some German translation missing?

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3606]
### Environment
TeXstudio 4.8.0 (git 4.8.0alpha5-2-g62bab1d6d)
Qt-Version 6.7.0, kompiliert mit Qt 6.7.0 R
OS: Windows 10

### Expected behavior
config shows German translations. Are there translations pending?
Works in release 4.7.2:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/078c7f6d-fc8c-4777-80e2-e9498b5274f3) and for all other pages

### Actual behavior
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/e534a22b-26c2-46dd-94a7-d14a10b9ee8b)

QListWidget shows all items in German. Some, but not all, pages of the QStackedWidget are translated to German: Erzeugen, Tastaturkürzel, Menüs, Syntaxhervorhebung. In other cases a mix of German and English appears:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/30370b04-99c1-40be-926c-cb663abd2310)

### How to reproduce
Open config dialog and check different items.

**Comment by sunderme** [comment]
fixed

**Comment by octaeder** [comment]
Thanks!
