### ISSUE TITLE
txs crashes when editing

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3607]
### Environment
- TeXstudio: current dev, not with installed release 4.7.2
- Qt: 6.7.0
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
work with no crash

### Actual behavior
I open a new document with `Ctrl+N`, then paste the following code:
```
%
%-------------------------------------------------------------------------------
\chapter{Part A}
%-------------------------------------------------------------------------------
%
%-------------------------------------------------------------------------------
\section{Day 1}
%-------------------------------------------------------------------------------
%
```
After that start deleting with backspace. This may be related to the structure panel, I don't know.

I've also seen other cases (pasting code) where messages have been written to the console:

```
QString::arg: Argument missing: "INSERT COMMAND: 0:0" , 9
QString::arg: Argument missing: "INSERT COMMAND: 0:0" , 0
```

**Comment by sunderme** [comment]
What is "After that start deleting with backspace." ?

**Comment by sunderme** [comment]
thanks
