### ISSUE TITLE
icons missing

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3609]
### Environment
- TeXstudio: current dev
- Qt: 6.7.0
- OS: Windows 10

### Actual behavior
Ui should show for embedded PDF-viewer icons Auto-hide Toolbar, Enlarge Viewer, Windowed Viewer, and Close.
Ui also misses Close icon for messages pane.

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/21c109b3-0c6b-4193-ad8e-31b6cf2fcb90)

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/b5c850f2-5b91-467e-b2af-d066bcd1911f)

**Comment by octaeder** [comment]
Now I see that Magnify is also missing in the first image.

**Comment by sunderme** [comment]
to clarify, these are oxygen classic icons (icon theme disabled)
Looks like a qt6.7 issue which does not render some svg. 
May be a bug, but the pragmatic way may be to convert/remake the icons. If someone can look into this, I am rather busy with the other issues (qt6.7 translations)

**Comment by octaeder** [comment]
Thanks!
