### ISSUE TITLE
autocompletion on elementary os loki doesn't work

### ISSUE THREAD

**Issue by ollie1124** [texstudio-org/texstudio#361]
### Environment
- TeXstudio: 2.12.10
- Qt: 5.5.1 (compiled in 5.5.1 R)
- OS: Linux (elementary os loki based on ubuntu 16.04)
- TeX distribution:  texlive

### Expected behavior
Auto-completion of any commands
e.g. 
`\begin{...`
show possible options in argument and automatically complete with \end{...} as well 

### Actual behavior
doesn't complete automatically.
manual completion works fine (ctrl+space).
(reinstalling texstudio and texlive as well doesn't solve the problem)

More detail can be found in [https://tex.stackexchange.com/questions/456497/texstudio-auto-completion-doesnt-work](https://tex.stackexchange.com/questions/456497/texstudio-auto-completion-doesnt-work)

configure option :1st_place_medal: 
![screenshot from 2018-10-20 22 11 54](https://user-images.githubusercontent.com/44423837/47406693-86b4e800-d792-11e8-95aa-88148376bc7f.png)

\begin{equation} trial screenshot:
![screenshot from 2018-10-24 13 42 09](https://user-images.githubusercontent.com/44423837/47406716-a3512000-d792-11e8-9876-8635c96c6b60.png)

**Comment by sunderme** [comment]
first of all, you don't need to set the active cwl files manually, txs does it automatically depending on \usepackage

second, if you want to go back to default settings, remove ~/.config/texstudio/texstudio.ini

Autocompletion only works on commands when typing \...

**Comment by ollie1124** [comment]
> first of all, you don't need to set the active cwl files manually, txs does it automatically depending on \usepackage

I know this because I have been using tex studio for years and not it doesn't work after reinstalling the same os again.

going to default setting (by following your suggestion) doesn't make things work.

What do you mean by this?

> Autocompletion only works on commands when **typing ...**

**Comment by sunderme** [comment]
typing `\...`

**Comment by sunderme** [comment]
works fine here (lubuntu 18.04, centos 7), so I don't see any reason why it should not work on your system, not reproducible
