### ISSUE TITLE
Shortcuts for macros insert macro code to editor

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3611]
### Environment
- TeXstudio: current build
- Qt: 6.7.0
- OS: Windows(10)

### Expected behavior
Macro code should be executed.

### Actual behavior
I have some macros which can be executed by shortcuts like `Alt+X`, `Alt+Y`, ... Instead of executing the macro in the context of the editor txs now simply inserts the code to the editor text. I assume this is a side effect of the AI functionality.

**Comment by sunderme** [comment]
Quick test shows that it still works as expected.
More context needed...

**Comment by octaeder** [comment]
sorry, I now see that all macros turned there type to Normal instead of Script. So I close this quickly.
