### ISSUE TITLE
Invisible icons in the Oxygen Modern icon theme

### ISSUE THREAD

**Issue by hair-splitter** [texstudio-org/texstudio#3615]
### Environment
- TeXstudio: TeXstudio 4.8.0 (git 4.8.0beta1)
- Qt: 6.7.0, compiled with Qt 6.7.0 R
- OS: Windows 11
- TeX distribution: TeX Live 2024

If the icon theme is **Oxygen Modern**, the following icons will be invisible in the embedded PDF viewer:

- Auto-hide Toolbar
- Enlarge Viewer
- Windowed Viewer
- Close
- Zoom Out
- Zoom In

**Comment by samcarter** [comment]
Some icons in the main toolbar also changed colour, e.g. `Stop compile` used to be a filled square and now is an open gray rectangle, which is a bit hard to see on a background in a similar shade of gray:

![Screenshot 2024-04-22 at 12 29 32](https://github.com/texstudio-org/texstudio/assets/43832342/d1411ed7-7b6b-49a8-a53f-4c9e8384b30d)

**Comment by sunderme** [comment]
fixed

**Comment by samcarter** [comment]
If one uses the "Magnify" option of the pdf viewer, there used to be a small magnifying glass as mouse pointer. This seems to be invisible with Qt 6.7.0 (magnifying still works, one just does not now where the mouse is...)

Should I open a new issue or is it the same problem as this?

**Comment by octaeder** [comment]
I assume the following need to be replaced by .svg:
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/0ef29e6a-f87f-44ad-aa29-d1c8b24aa822)

with Oxygen Classic:
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/9124afbc-5cba-49b1-b226-d813dd57e72b)


Opening magnifier-button_dm.svgz with Inkscape I see two white objects on white background:
![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/2e4ed56a-b60f-424a-9fd4-ac015dcc13b2)
Not sure if this ok.

**Comment by samcarter** [comment]
The missing mouse pointer might be a problem with the .svg file. I tried to convert ./images-ng/modern/magnifier.svgz to .svg with inkscape, but the mouse pointer was still invisible.

If I re-draw the image, the mouse pointer becomes visible again.

Re-drawn .svg file:

![magnifier](https://github.com/texstudio-org/texstudio/assets/43832342/3b406fb4-778f-4724-99d1-506300ffa3f0)

**Comment by sunderme** [comment]
fixed.
The issue is that the svgs contain a "filter" attribute which is not supported in qt6.7.
the issue report at qt states that it was not supported before but it was handled differently, apparently in a way that still an image was rendered.
My current approach is to convert to "optimized svg" (inkscape) and remove the filter attribute per editor.

**Comment by samcarter** [comment]
@sunderme Thank you very much for the explanation!
