### ISSUE TITLE
Make line numbers default

### ISSUE THREAD

**Issue by glor** [texstudio-org/texstudio#3617]
Reading #804 I thought to myself "Why isn't this default behavior?".

### Describe the feature and the current behavior/state
Make "Show Line Numbers: All" default behavior instead of "No Line Numbers". Even without having "Advanced Options" it is still not that easy to find because of the overall high number of options. Line numbers make lines referencable but more importantly they make it easier to see where a new line starts which I find especially important working with git-versioned documents where each sentence is a new line.

The only reason I can imagine why people wouldn't want line numbers in texstudio is because of small screen sizes. And then I think it would be ok to configure.

### Who will benefit with this feature?
New users, collaborating users, lazy user :wink:

**Comment by sunderme** [comment]
I don't change defaults unless there is an objective benefit.
There are many who don't need line numbers.
It is configurable, so that you can adapt it to your taste and that should suffice.

**Comment by octaeder** [comment]
Entering the search term _line numbers_ in the search field of the configuration dialog finds exactly the option you are looking for - even when option _Advanced Options_ is checked. That's pretty intuitive.

**Comment by glor** [comment]
@octaeder thanks. I did not see the filter option.

@sunderme I respect and understand that from a governance point of view but I believe that you give defaults and their influence too little credit. That strategy might create a blind spot regarding usability...
