### ISSUE TITLE
User manual should explain "load/save profile"

### ISSUE THREAD

**Issue by jondo** [texstudio-org/texstudio#362]
### Environment

- TeXstudio: 2.12.10
- Qt: 5.8.0
- OS: Windows 7
- TeX distribution: miktex

### How to reproduce
The options menu contains the commands "Load Profile..." and "Save Profile...".
These commands should be described in Help->"User Manual", but they aren't.

**Comment by octaeder** [comment]
A comparison reveals that about 30% of a saved profile is almost the same as the .ini file. I found main differences here:
![grafik](https://user-images.githubusercontent.com/102688820/166107626-3669d660-bc38-476d-b682-b1a6b63aac8d.png)
These lines are missing in the profile. Hope that this is not a bug. The remaining 70% look like this:
![grafik](https://user-images.githubusercontent.com/102688820/166107683-87673d5b-c63a-48da-81d1-cb9c7ac4ba3b.png)
How can this be described? Of course the description shouldn't go into depth. In short terms the state of the application can be saved in a user defined file and loading this (pro)file would restore that state later on. Correct me if I'm wrong.

@sunderme With this little knowledge I could start describing it, if this is still wanted. So let me know and maybe you could provide profound information. I would place this peace of information at the end of chapter 2 'Configuring TeXstudio'.

**Comment by octaeder** [comment]
I would say this is solved [here](https://texstudio-org.github.io/advanced.html#save-load-profile) and can be closed.
