### ISSUE TITLE
Are there any fast ways to rename the image file name inside the tex file and in the local harddisk

### ISSUE THREAD

**Issue by asmwarrior** [texstudio-org/texstudio#3620]
Suppose, I have a image file named `abc.png`, and in the `demo.tex` file, I have such code snippet:

~~~~
\includegraphics[scale=1.5]{abc}
~~~~

Now, I would like to change the image file name to `xyz.png', so what I have to do is:

1, change the file name in the local harddisk, so rename the file name to `xyz.png`
2, in the latex code, I have to change the code to:

~~~~
\includegraphics[scale=1.5]{xyz}
~~~~

My question is: can this be done inside the TexStudio? I mean I can mouse right click on the "abc", and there is a feature named to rename both the local file and the text inside latex code.

Any ideas?

Thanks.

**Comment by octaeder** [comment]
Currently not. But upcoming next release of txs will have a file browser in the left side bar. It shows the file tree relative to your current document. The files have a context menu that currently contains one action, namely _Insert filename_. So you could change the name in a different file browser and then use the context menu to insert the filename into your document.

Maybe the rename action could be added before next release of txs.

**Comment by asmwarrior** [comment]
Hi, @octaeder , thanks for the reply and explanation.

As a long time TexStudio user, I think the "image file and latex code rename" feature is a good function, hopefully it will be added before the next release.

**Comment by sunderme** [comment]
I am not inclined to put this functionality into txs.
However you can use macro/script to realize it on your own.

**Comment by sunderme** [comment]
not planned

**Comment by asmwarrior** [comment]
Hi, I'm a bit sad that this issue is not planed. 
Here is a bash script I use to rename both a file name and text in the tex file.

~~~~
old_text=abc
new_text=xyz

sed  -i "s/{$old_text}/{$new_text}/g" *.tex
echo  -i "s/$old_text/$new_text/g" a.tex

if [ -f "image/$old_text.jpg" ]
then
	echo "jpg found."
    git mv "image/$old_text.jpg" "image/$new_text.jpg"
else
	echo "png found."
    git mv "image/$old_text.png" "image/$new_text.png"
fi
~~~~

With the above script, I can rename the "abc.jpg" to "xyz.jpg". But I'm not satisfied with the above code, because I have to manually enter the text "abc" and "xyz" inside the bash script. (note I'm using the git command to rename the file)

I would see some faster way integrated into the IDE. Can you help to make it? Thanks.
