### ISSUE TITLE
TeXstudio completion strangely slow whenever typing a command (+ CPU spike)

### ISSUE THREAD

**Issue by godblessourdeadkotatsu** [texstudio-org/texstudio#3622]
### Environment
- TeXstudio: 4.7.3
- Qt: 6.6.2
- OS: Windows 10
- TeX distribution: MikTeX

### Description
While typing in a document (about 4200 lines), every time I type \ to enter a command, a noticeable delay (sometimes almost a second long) is introduced. During this delay time TeXstudio freezes completely. Moreover, from Task Manager it appears that during these freezes TeXstudio hits 20% CPU spikes (while normally sitting around 0.5%-1%). This issue is not constant, sometimes disappearing without having done apparently anything.
More info that could be useful:

- When disabling "automatically start completer when typing LaTeX commands" the delay does not appear when typing \, but it does appear (albeit smaller) when opening the completer window (Ctrl+Space).
- The longer a document is, the longer the delay.
- The delay is longer when typing inside an environment.
- I disabled most of the features suggested to lighten the CPU load (as inline checking of the grammar and loading external files). My TeXstudio profile is included as an attachment.

Thank you in advance!

[profile.txt](https://github.com/texstudio-org/texstudio/files/15139468/profile.txt)

**Comment by sunderme** [comment]
without a test case i.e. document, there is really nothing I can do.
You can send it to me directly (sunderme@gmx.de)

**Comment by godblessourdeadkotatsu** [comment]
Hi, thank you very much for your quick response. 
I apologize for not including the document. I had this problem with fairly large document (which I could not make a dummy example of). I'll send you via mail a version of the document I am working on (in which I checked that the error still persists). 

For further clarity, I attach a screengrab of TeXstudio showing the aforementioned behavior. As you can see, the cursor stops blinking after typing \, meaning that the editor has frozen completely. As you can see while TeXstudio is "frozen" everything I type appears only after a few moments. Please note how at the end of the line typing \\ various times freezes the editor every other \ charachter.
I also captured in the video another behavior I encountered about this issue. I found out that whenever the \ character causes this behaviour if I delete the \, break the line, type \ in the new line _and_ delete it, then upon typing \ again the editor behaves normally.

Again, thank you very much for your support.

https://github.com/texstudio-org/texstudio/assets/81176913/67835e1a-7782-4441-974a-e6e596236e1e

**Comment by sunderme** [comment]
you can verify with dev build: https://github.com/texstudio-org/texstudio/actions/runs/8868081415
