### ISSUE TITLE
When editing a macro, Ctrl D adds the wrong character `/\*` at the beginning of the selected line

### ISSUE THREAD

**Issue by saxyx** [texstudio-org/texstudio#3628]
### Environment
- TeXstudio: 4.7.3
- Qt: 6.6.2
- OS: Windows 10

### Expected behavior
When editing a macro, Ctrl D adds the character `//` at the beginning of the selected line.

### Actual behavior
When editing a macro, Ctrl D adds the wrong character `/\*` at the beginning of the selected line, when you run this macro, you get an error message: `Uncaught exception at line 3:SyntaxError:Unterminated regular expression literal`

### How to reproduce
Edit a macro and annotate some lines with Ctrl D, then run it

**Comment by octaeder** [comment]
@saxyx This works with current local build (4.8.0):

![MacroCtrlD](https://github.com/texstudio-org/texstudio/assets/102688820/b60d7087-968e-46cf-a006-b9f789238426)
