### ISSUE TITLE
makeindex Command Fails to Find .acn File When Run Inside TeXstudio

### ISSUE THREAD

**Issue by Foadsf** [texstudio-org/texstudio#3629]
### Environment
- TeXstudio: 4.7.3
- Qt: 6.6.2
- OS: Windows 10
- TeX distribution: MiKTeX 24.4

### Description
as explained [here](https://tex.stackexchange.com/q/717322/102825) and [here](https://www.reddit.com/r/LaTeX/comments/1cljt8l/issues_with_makeindex_command_in_texstudio_input/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button), I am experiencing an issue with the `makeindex` command configured in TeXstudio to manage files in a separate build directory. Despite configuring it similarly to how it successfully runs from the command line, it fails when run within TeXstudio.

#### Settings:
In TeXstudio, I have configured the command as follows:

```plaintext
makeindex -s .\build\%.ist -t .\build\%.alg -o .\build\%.acr .\build\%.acn
```

This command runs perfectly when executed directly in the command line. However, when executed inside TeXstudio, it results in the following error:

```
Input index file main.acn not found.
```

I have tried multiple variations and confirmed the paths and file existence. I am looking for insights or solutions to resolve this issue within TeXstudio, focusing directly on how to get `makeindex` to recognize and process files correctly from the specified build directory without resorting to external tools like `ltx2any` or `latexmk`.

**Comment by sunderme** [comment]
apparently, there is no interest to debug user specific set-ups.
This issue is mainly focused on txs bugs/enhancements.
