### ISSUE TITLE
Option to never autoload recent tex files at start

### ISSUE THREAD

**Issue by jondo** [texstudio-org/texstudio#363]
### How to reproduce
- Edit a tex file.
- Close TeXstudio.
- Open another tex file in TeXstudio via doubleclick.

### Expected behavior
Optionally, only the second file should be opened. This will be especially useful with #354.

### Actual behavior
TeXstudio always "remembers the session" and opens both tex files.

### Environment
- TeXstudio: 2.12.10
- Qt: 5.8.0
- OS: Windows 7
- TeX distribution: miktex

**Comment by sunderme** [comment]
you can disable "restore session" -> option/general/restore previous session
or you can start txs via command line option --no-session (which you have to set for double clicking on a file name)

**Comment by jondo** [comment]
For the record, I adapted Linux Mint's menu entry for the flatpack version of TeXstudio accordingly by changing it from
`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=texstudio.sh --file-forwarding org.texstudio.TeXstudio @@ %F @@`
to
`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=texstudio.sh --file-forwarding org.texstudio.TeXstudio -- --no-session @@ %F @@`.

(The standalone double hyphen (--) tells Flatpak to stop parsing options so everything after it is passed to the app command.)
