### ISSUE TITLE
Crash when clicking on lateral panel

### ISSUE THREAD

**Issue by taxipomme** [texstudio-org/texstudio#3632]
### Environment
- TeXstudio: 4.7.3
- Qt: 6.6.2
- OS: MacOS Sonoma Version 14.3.1 (23D60)
- TeX distribution: Texlive 1.54

### Expected behavior
When clicking on an item of the left panel / table of contents, the editor should open the corresponding file and move to the corresponding section.

### Actual behavior
Crashes.

### How to reproduce
[report.txt](https://github.com/texstudio-org/texstudio/files/15272852/report.txt)

**Comment by sunderme** [comment]
if you have a reproducible test case, we need that test case with documents and steps, how to reproduce.

**Comment by sunderme** [comment]
no way to reproduce
