### ISSUE TITLE
Screen size/resolution  issue

### ISSUE THREAD

**Issue by MrI2C** [texstudio-org/texstudio#3634]
I worked at home with my HP win11 laptop, connected to an external 4k Dell monitor, running at 150% scaling
at work i connect to a 1080p monitor and now the "full-screen" appears half on the bottom monitor. There's no way i can do a vertical narrowing of the window.

### Environment
- TeXstudio: 
- TeXstudio 4.8.0 (git 4.8.0)
Using Qt Version 6.7.0, compiled with Qt 6.7.0 R
- Qt: 
- OS: 
- TeX distribution: 

### How to reproduce
Connect a 4k monitor and dispaly TexSTudio full screen on that one. have the laptop display still active
disconnect the 4k and connect a 1080p. watch the behavior

**Comment by homocomputeris** [comment]
Same on macos 14: the height of the window cannot be made smaller. The lower edge of the window is always outside the visible part of the screen.

TeXstudio 4.8.0 (git 4.8.0)
Using Qt Version 6.7.0, compiled with Qt 6.7.0 R

**Comment by sunderme** [comment]
this and OSX issue are probably not the same.
Obviously the way to reproduce is not feasible, please come up with an alternative way.

**Comment by sunderme** [comment]
no way to reproduce.

**Comment by MrI2C** [comment]
Using win11 here: place a 4k monitor in a scaling mode 150% or 200%. open TexStudio: it will not show the bottom part of the window. There seems to be an issue when scaling <> 100%

**Comment by sunderme** [comment]
I am not sure that I can follow
1) default txs window size at 150% is within the monitor on 4k (win11)
2) if it is is larger, you can resize and txs stored the latest win size/position

2) is not sufficient ?

**Comment by MrI2C** [comment]
That's the weird thing, i cannot receize it 


Van: "sunderme" ***@***.***> 
Aan: "texstudio-org/texstudio" ***@***.***> 
Cc: "didier vereecke" ***@***.***>, "Author" ***@***.***> 
Verzonden: Vrijdag 14 juni 2024 19:28:56 
Onderwerp: Re: [texstudio-org/texstudio] Screen size/resolution issue (Issue #3634) 





I am not sure that I can follow 

    1. 

default txs window size at 150% is within the monitor on 4k (win11) 
    2. 

if it is is larger, you can resize and txs stored the latest win size/position 
    3. 

is not sufficient ?

**Comment by sunderme** [comment]
Can you try the fusion visual style (options/appearance)
