### ISSUE TITLE
Dropdown lists black font on black background

### ISSUE THREAD

**Issue by betz-michael** [texstudio-org/texstudio#3636]
### Environment
- TeXstudio: 4.8.0 portable
- Qt: 6.7.0
- OS: Win 10 64bit
- TeX distribution: miktex

### Expected behavior
Dropdown lists in settings should have black font on white background.

### Actual behavior
Dropdown lists in settings have black font on black background.

### How to reproduce
Open TeXstudio and go to settings.
Changeing the Colormodesettings in Windows did not change the behaviour of the drop down color.
The installation was done by deleting the old version and copiing the new files from the zip into the old location. After this, the profile was reloaded.
![Menu](https://github.com/texstudio-org/texstudio/assets/152782044/0887159b-2f38-443c-a77d-4eec542e00e2)

**Comment by muzimuzhi** [comment]
What are your style and color scheme settings?
![image](https://github.com/texstudio-org/texstudio/assets/6376638/124454d2-62af-4874-9547-e2e9e5ee2726)

**Comment by octaeder** [comment]
This is a know [Qt6.7 issue](https://wiki.qt.io/Qt_6.7_Known_Issues): 

>Windows: WindowsVistaStyle: Embedding QComboBox into QScrollArea results in black QComboBox-Popup.

This is a duplicate to #3601.

Simple workaround: Click into combo box (list opens), click again (list closes), now use arrow keys to walk through the list items.
As mentioned in #3601 not all Styles have the issue.

**Comment by betz-michael** [comment]
Thanks for you support and the hint with the color scheme!
![grafik](https://github.com/texstudio-org/texstudio/assets/152782044/ae19452a-7ea2-47c4-bab4-cc8680fe798d)

It works fine for the Style "Windows".
It does not work for WindowsVista and Windows11, just like described in [#3601 ](url)

I changed it to Windows, that works fine for me.

**Comment by GyorgySZEIDL** [comment]
Changing the Style to Windows resolved my problem. Thank you all for the hint. György Szeidl.
