### ISSUE TITLE
Option to delete intermediate files after final compile.

### ISSUE THREAD

**Issue by Srebby** [texstudio-org/texstudio#3638]
### Describe the feature and the current behavior/state
After compiling a document there are a number of files (.aux, .log, .nav, .out, .snm, .dvi) that are created in addition to the final PDF/.ps output.  I would like there to be a feature that would optionally delete these extra files.  Ideally, I would like a "clean folder" button that would delete all non-essential files in a folder (regardless of whether they related to the current document or not), but it would also be OK to have a "clean-up" button to remove all such files for the current document.  Another alternative would be a "build final" button that would build the document and delete all of the work files.

I realize that, while working on a document, there may be value in keeping these files around, but I would like to be able to easily delete these files after the final compile.
### Who will benefit with this feature?
This would help clean up folders in which I have several different documents and make it easier to navigate when I am searching 
### Any Other info
I love using TeXstudio.  I've tried several other platforms for LaTeX document production, but have not found one that suits my needs better than TeXstudio.  Thank you for all your work.

**Comment by muzimuzhi** [comment]
There's a menu item Tools - Clean Auxiliary Files... and you can add it to Toolbar.
![image](https://github.com/texstudio-org/texstudio/assets/6376638/2e3be4eb-74c3-4429-893c-9acd9172b7ee)
![image](https://github.com/texstudio-org/texstudio/assets/6376638/74d14d67-c21b-4728-a67d-b3a80bdc8a94)

**Comment by sunderme** [comment]
should be answered
