### ISSUE TITLE
\(...\) and \[...\] instead of $ / $$

### ISSUE THREAD

**Issue by domi413** [texstudio-org/texstudio#3641]
TeXstudio automatically adds math delimiters when  a mathematical symbol is inserted, e.g.`$\rightarrow$`

However, as far as I know, `$` and `$$` are from the old TeX days and should no longer be used in LaTeX.
Although they work fine most of the time, they can lead to package conflicts and inconsistencies in vertical spaces, which is the reason `\(...\)` and `\[...\]` should be used.

It would be nice to add an option to select between "default math delimiters" e.g. through a checkbox or a drop-down menu

Such an improvement would make TeXstudio an even better Editor :)

**Comment by sunderme** [comment]
My summary would be (from chapter 16), `\(..\)` and `$..$` are synonyms, hence txs sticks with `$` as it is simpler (and very common)

**Comment by mbertucci47** [comment]
@domi413 `\[...\]` and `$$...$$` are not identical, see the answers here: https://tex.stackexchange.com/q/503/208544

**Comment by octaeder** [comment]
the latex reference says `$$` is TeX and not supported by LaTeX (s. 8.5):

> (Aside: The construct `$$math$$` from Plain TeX is sometimes mistakenly used as a synonym for displaymath. It is not a synonym, and is not officially supported in LaTeX at all

**Comment by mbertucci47** [comment]
@domi413 For almost all purposes `\begin{math}...\end{math}`, `$...$`, and `\(...\)` are identical. It's the display environments `\[...\]` and `$$...$$` where differences show up; not sure if the txs reference says anything about this. The form `\[...\]` should be used with LaTeX

**Comment by octaeder** [comment]
Chapter 8.5

> `$$` doesn’t support the fleqn option (see Document class options), has different vertical spacing, and doesn’t perform consistency checks
