### ISSUE TITLE
Entries of the context menu in the Structure view don't work

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#3642]
### Environment
- TeXstudio: 4.8.0
- Qt: 6.4.1
- OS: Linux Mageia 9
- TeX distribution: TeX Live

### Expected behavior
Entries of the [context menu in the Structure view](https://texstudio-org.github.io/editing.html#the-structure-view) should work (or not be displayed).

### Actual behavior
Entries of the [context menu in the Structure view](https://texstudio-org.github.io/editing.html#the-structure-view) are available in both Structure and in TOC views but works only in TOC view.

### How to reproduce
1. Open a document containing sections, e.g.:
```latex
\documentclass{article}
\begin{document}
\section{Foo}
\section{Bar}
\end{document}
```
2. Click on the Structure view.
3. Open the context menu and click on “Indent Section”.
4. Nothing happens.
2. Click on the TOC view.
3. Open the context menu and click on “Indent Section”.
4. The section becomes a subsection.

**Comment by octaeder** [comment]
fine, thanks
