### ISSUE TITLE
Go back to 4.7.3 theme in newest 4.8.0 version on windows 11

### ISSUE THREAD

**Issue by HumpyBlumpy** [texstudio-org/texstudio#3643]
### Environment
- TeXstudio:  4.8.0
- Qt: Qt Version 6.7.0
- OS: Windows 11
- TeX distribution: miktex

I updated texstudio to 4.8.0. Is there a way to go back to the style and color scheme of the previous version?

**Comment by sunderme** [comment]
options/general/style -> windows or fusion

**Comment by Konstantius** [comment]
Unfortunately, **options/general/style** does not depend on the theme of application. Theme remains dark in any case

**Comment by sunderme** [comment]
It is unclear what you want to achieve.
What exactly do you mean with theme here ?
Screenshots ?

**Comment by Konstantius** [comment]
I don't know how to add picture here, but I've added screenshot with black theme
![snap360](https://github.com/texstudio-org/texstudio/assets/12594558/1360bb5a-9e6c-4b82-9a02-2e97be694660)

**Comment by ludengxiademao** [comment]
I would like to have previous theme too ！

**Comment by sunderme** [comment]
I guess you are looking for options/general/ignore most system colors ?

**Comment by Konstantius** [comment]
I'm looking to possibility to take on the light theme/skin as previously 
<img width="1134" alt="txs_symbol" src="https://github.com/texstudio-org/texstudio/assets/12594558/697ad0ed-b0ad-484a-8b70-5b4967cd9857">
when menu and toolbars are light

**Comment by aaron-oppong** [comment]
I would like previous theme too
4.7.3 wasn't affected when I had windows setup in dark mode

Is there a way to toggle between light and dark mode in 4.8.0? options/general/ignore most system colors is messy

**Comment by shenlebantongying** [comment]
It is not really TeXstudio's problem.

Qt6.7 has a new built-in dark theme that syncs with the system on Windows. It is buggy and conflicts with existing theming. https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5

The workaround is to start TeXstudio with these parameters and select the theme as "fusion" in options.

```
texstudio.exe -platform windows:darkmode=1
```

I failed to fix them in another app, so I simply [disable Qt6.7's dark theme](https://github.com/xiaoyifang/goldendict-ng/pull/1512/files#diff-7b9337fcff3141736997afd31f7a2764b3538153922282c8407af5f43d543cabR355-R376)

An alternative is simply roll back to Qt6.6.

To my best knowledge, it cannot be fixed reasonably until Qt6.8 that allows us to request the light theme https://github.com/qt/qtbase/commit/95d4e6bababfeb36fa8a355a8487b64eb3ffb587

**Comment by Konstantius** [comment]
Thank you
This workaround tackled the issue

> The workaround is to start TeXstudio with these parameters and select the theme as "fusion" in TeXstudio's options.
> 
> ```
> texstudio.exe -platform windows:darkmode=1
> ```
Besides "Fusion", other themes are workable
For example, my favorite "Windows":
![snap364](https://github.com/texstudio-org/texstudio/assets/12594558/157f1f11-ee9f-4931-ae36-4de0829a3b2e)

**Comment by aaron-oppong** [comment]
> It is not really TeXstudio's problem.
> 
> Qt6.7 has a new built-in dark theme that syncs with the system on Windows. It is buggy and conflicts with existing theming. https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5
> 
> The workaround is to start TeXstudio with these parameters and select the theme as "fusion" in TeXstudio's options.
> 
> ```
> texstudio.exe -platform windows:darkmode=1
> ```
> 
> I failed to fix them in another app, so I simply [disable Qt6.7's dark theme](https://github.com/xiaoyifang/goldendict-ng/pull/1512/files#diff-7b9337fcff3141736997afd31f7a2764b3538153922282c8407af5f43d543cabR355-R376)
> 
> An alternative is simply roll back to Qt6.6.
> 
> To my best knowledge, it cannot be fixed reasonably until Qt6.8 that allows us to request the light theme [qt/qtbase@95d4e6b](https://github.com/qt/qtbase/commit/95d4e6bababfeb36fa8a355a8487b64eb3ffb587)

Thank you

**Comment by sunderme** [comment]
hopefully most is fixed with qt 6.7.1
