### ISSUE TITLE
Tooltips of displayed by `\ref` should be fully readable

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#3644]
### Environment
- TeXstudio: 4.8.0
- Qt: 6.4.1
- OS: Linux Mageia 9
- TeX distribution: TeX Live

### Expected behavior
Tooltips displayed by `\ref` should be fully readable.

### Actual behavior
Tooltips displayed by `\ref` aren't fully readable (see screenshot).
![image](https://github.com/texstudio-org/texstudio/assets/1032633/7f7e4ba8-9c16-4166-9ef2-bf0f31646540)

**Comment by sunderme** [comment]
looks like interaction with window manager ? what is used ? dark mode ?

**Comment by hair-splitter** [comment]
I experience this when the style is Adwaita (txs).

**Comment by dbitouze** [comment]
> looks like interaction with window manager ? what is used ? dark mode ?

- Window Manager: KWin (default window manager of the desktop environment Plasma).
- Mode: default one (not dark).
- TXS style: default one.

I tried with other TXS styles and, since that, it is fully readable with all styles but the text in the tooltip is in white on the black background: no more colors as on the screenshot in the OP.
