### ISSUE TITLE
Compilation on Mac: 'GlobalParams.h' file not found

### ISSUE THREAD

**Issue by tianyi21** [texstudio-org/texstudio#3647]
### Environment
- TeXstudio: 4.8.0
- Qt: 6.7.0
- OS: macOS
- TeX distribution: macTeX
- cmake: 3.29.3
- poppler: 24.05.0 built from source with Qt6

### Actual behavior
I always compile from source with my M-series MBP, although a precompiled version has been included (thanks!). For v4.8.0 release, when compiling from source on macOS, cmake threw the following error:

`texstudio-4.8.0/src/pdfviewer/pdfrendermanager.cpp:21:10: fatal error: 'GlobalParams.h' file not found`

Should be a Mac-specific problem since the source code says

```
#ifdef Q_OS_MAC
// enable setting datadir relative to binary on mac
#include "GlobalParams.h"
#endif
```

There were no problem compiling 4.7.3 whose source code has `#include "GlobalParams.h"` commented out. `texstudio-4.8.0/src/pdfviewer/PDFDocument.cpp` also has this line commented out. Could potential be a problem with my poppler installation but 4.7.3 didn't complain.

**Comment by sunderme** [comment]
poppler needs to be compiled with "unstable header"

`cmake .. -DENABLE_UNSTABLE_API_ABI_HEADERS=ON`

**Comment by tianyi21** [comment]
> poppler needs to be compiled with "unstable header"
> 
> `cmake .. -DENABLE_UNSTABLE_API_ABI_HEADERS=ON`

Now it's working. Thank you.
