### ISSUE TITLE
LangugeChecking -- 

### ISSUE THREAD

**Issue by GyorgySZEIDL** [texstudio-org/texstudio#3649]
I have just downloaded the portable version of Texstudio 4.8.0. The language checking does not work.
If I click on Language Checking and make an attempt at changing the Default  Language  I get a black 
rectangle. (Operating System is Windows 10. I have no problem with changing the Default  Language 
under the portable version of Texstudio 4.7.3.

![LanguageChecking](https://github.com/texstudio-org/texstudio/assets/37615412/7cf3d019-312a-4eb4-b4a6-1b47782b42af)

**Comment by octaeder** [comment]
duplicate s. #3636
