### ISSUE TITLE
#Help → Packages Help...” should expose all the packages by default

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#3650]
### Describe the feature and the current behavior/state
Currently (TXS 4.8.0), “Help → Packages Help...” exposes only the packages that are used (or, AFAICS, loaded by the class and the packages used) in the current document. IMO, it should by default expose all the packages.

### Who will benefit with this feature?
All the users who want to look at the documentation of a package they might want to use in their current document.

**Comment by dbitouze** [comment]
>But baffling everyone that there are over 1000 packages and make them scroll for ages seems not very comfortable.

Instead of scrolling, you can just type in the search bar the (beginning of the) name of the package you're looking for.

At least, the status of the check box could be not changed until TXS is closed.

**Comment by octaeder** [comment]
Wouldn't it be better if the “Open” button didn't close the dialog? Currently, a few clicks and possibly re-entering the filter text are required to open a second document.
If you agree, I would provide a PR.

**Comment by sunderme** [comment]
I don't think that the dialog needs to stay open.
Majority of use cases is to search for one manual at a time.
