### ISSUE TITLE
Texstudio opens wrong panels on start-up

### ISSUE THREAD

**Issue by jevdplas** [texstudio-org/texstudio#3653]
### Environment
- TeXstudio: 4.8.0
- Qt: 6.7.0
- OS: Mac
- TeX distribution: texlive

### Expected behavior
When TexStudio is opened, the same panels should open as when it was last closed, i.e., the panels selected in View > Show (e.g., the side panel or the messages panel). Changing the selected panels in the menu should cause the editor panels to be shown or hidden.

### Actual behavior
When TexStudio is opened, the side panel is opened and the messages panel is closed. There is no Status bar either. In View > Show, only the messages and status bar are selected. Hence, the layout of the editor does not match the selected layout. Additionally, selecting or deselecting panels in the menu does not change the layout of the editor.

Attached to this issue (below) is a link to a screen recording where I change the layout settings, but where it is clear that nothing changes.

### How to reproduce
Open TexStudio and see that the layout does not match the selected panels.
Try to change the selected panels in View > Show, to see that the layout is not updated when the selection is changed.

Note: sometimes, random actions may trigger the correct layout. I am not sure how this can be reproduced.

https://github.com/texstudio-org/texstudio/assets/21293809/e22e6ee8-a481-4e50-8407-ab2a16edf355

**Comment by sunderme** [comment]
Can you try view/show/reset sidepanel ?
If that fails, change to to fusion style and do the same again?

**Comment by jevdplas** [comment]
Hello

Resetting the sidepanels/docks does not work. 

When changing to the fusion style, resetting the sidepanels/docks still does not work.

Also, in the fusion style, the buttons in the view>show menu still do not have any effect, except for the side panel which I can now close by first selecting it in the menu and then deselecting it again (it - however - opens again when reopening TexStudio although it's deselected).

**Comment by sunderme** [comment]
What exactly is your set up? (Computer, os)

Can you try the latest dev build (actions)?
There you can reduce the number of docks by hiding them (view/show/... )

**Comment by jevdplas** [comment]
Using the latest dev build (CD #3975: Commit [ef09076]), TexStudio now remembers the settings when the app is opened. However, the first time, still these were ignored and the sidebar just opened with no status bar or messages so I deselected and reselected the bars that I wanted and vice versa for the side bar (with default layout style instead of fusion again). 

(Using the reset button did nothing. The messages panel and dock open with very minor delay on start-up.)

Setup:
* 2019 Macbook Pro
* Intel i9
* 32GB DDR4
* MacOS 14.4.1 (23E224)

**Comment by sunderme** [comment]
What is the screen size?

Have you reduced the number of docks ?

**Comment by sunderme** [comment]
When you terminated txs before upgrading to txs 4.8, the sidebar was closed/hidden ?

**Comment by jevdplas** [comment]
Indeed, I did not change my settings. I never used the sidebar, only the message and status bars on the bottom.

**Comment by sunderme** [comment]
fix showing the previous dock on top when closing and reopening the sidepanel

**Comment by ansisec** [comment]
I'm encountering a recurring problem with TextStudio. When I open the application, the window appears with a height that's at least twice the size of my screen. This makes it impossible to use the program effectively.

To be able to resize the window and work with TextStudio, I have to repeatedly select and deselect the "Show Sidebar" option from the menu. Unfortunately, this issue persists every time I close and reopen TextStudio.
