### ISSUE TITLE
Files listed in sidebar remain after closing editor

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3657]
### Environment
- TeXstudio: current dev
- Qt: 6.7.0
- OS: Windows(10)
- TeX distribution: miktex

### Expected behavior
Side panel view Files should be empty when no editor is present

### Actual behavior
Two cases:
- Starting txs without any editors (i.e. all editors were closed before ending txs) files of the installation path are shown
  ![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/58e81859-7913-4e51-8ce8-38c4fa2dff8e)
- After opening and closing a .tex file the Files of the .tex are still there

### How to reproduce
as said above

**Comment by sunderme** [comment]
1) explorer path without open editors is "current pah" aka current working dir.
This makes sense, maybe more so on Linux and OSX where txs can be started from command line.
-> no change
2) keeping the last path open is not detrimental and one may even try to open a file from the same dir
-> no change
