### ISSUE TITLE
Restricted window resizing in 4.8.0

### ISSUE THREAD

**Issue by trg818** [texstudio-org/texstudio#3659]
I just updated TeXStudio to v.4.8.0 on my MacBook (M1, Ventura 13.6.6) and found that the window is too large for the notebook's display and cannot be shrunk. When moving it to the secondary screen, which is bigger, I can at least reach the bottom boundary, but it is nonetheless not possible to diminish the size to less than the size at startup in the vertical dimension. Horizontal resizing seems to be unrestricted.
Please fix this asap, because this is obviously quite annoying.
### Environment
- TeXstudio: 4.8.0
- Qt: 6.7.0
- OS: MacBook M1, Ventura 13.6.6
- TeX distribution: texlive (from Homebrew)

**Comment by octaeder** [comment]
have a look at #3637

**Comment by sunderme** [comment]
duplicate to #3637
