### ISSUE TITLE
Embedded viewer icon missing in Colibre icon theme? 

### ISSUE THREAD

**Issue by jakelamtn** [texstudio-org/texstudio#3660]
### Environment
- TeXstudio: TeXstudio 4.8.0 (git 4.8.0)
- Qt: Using Qt Version 6.7.0, compiled with Qt 6.7.0 R
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
The "embedded viewer button" should be visible when in windowed viewer mode

### Actual behavior
I can't see the embedded viewer button when in windowed viewer mode
![image](https://github.com/texstudio-org/texstudio/assets/54130243/fc7c6e05-7077-44e8-bd8a-7f7338c09a2e)

### How to reproduce
I just click on windowed viewer while using the Colibre icon theme

**Comment by sunderme** [comment]
fixed
