### ISSUE TITLE
Wrong window size and stacked texts on macOS, using the M1 build

### ISSUE THREAD

**Issue by leo-maxwell** [texstudio-org/texstudio#3664]
The TeXstudio window size is wrong in macOS 14.5 on the Apple Silicon machine, using the native build.
The bottom is always out of the screen, presenting part of the window on my screen.
The Mac used here is a Macbook Pro 16-inch 2021, and no external monitor was used.
### Environment
- TeXstudio: 4.8.0
- Qt: 6.7.0
- OS: macOS Sonoma 14.5
- TeX distribution: MacTeX 2022

### Expected behavior
The window should be correctly sized.

### Actual behavior
The bottom is out of the screen bond, here is the screenshot:
<img width="803" alt="image" src="https://github.com/texstudio-org/texstudio/assets/147984036/cf73e540-65a3-4c31-b85d-1ee7621251e4">

Sometimes the size is made correct by constantly re-sizing the window, but the texts are stacked, like this:
<img width="216" alt="image" src="https://github.com/texstudio-org/texstudio/assets/147984036/1c0ddfa6-aed3-4e21-8bea-a1461116e0c4">

### How to reproduce
Open the TXS in the described environment.

**Comment by sunderme** [comment]
duplicate #3637 
try changing style to "Fusion"

**Comment by leo-maxwell** [comment]
Thank you for your advice, but it didn't work😢
I tried every possible style, and after changing each style, I re-launched the TXS.

**Comment by sunderme** [comment]
what happens if you choose style "fusion", restart
Then use view/show/reset sidepanel ?

Have you tried to move the docks manually ? (You can now grab the titlebar and move the docks to top/right and onto other docks.

**Comment by sunderme** [comment]
And a last solution is using the dev build: https://github.com/texstudio-org/texstudio/actions/runs/9169678533
Here you can hide docks on the side panel to reduce the number of docks and avoid the issue. (view/show/... at the bottom(
(reset dock may be necessary after all)

**Comment by leo-maxwell** [comment]
It looks like that side-panel is causing the problem. After disabling the side-panel display, I double-clicked the top of the window (to resize) and the TXS window was the right size.
I moved the docks manually to the right side of the window to prevent them all from aligning to the left causing a too-long vertical bar-like panel, and it worked as well.
I assume that the cause has already been found now, for developers, and this issue is okay to close.

**Comment by sunderme** [comment]
the plan is to put all docks of the sidepanel into one dock which should present itself similar to what txs was doing previously.
You can stack docks ?

**Comment by leo-maxwell** [comment]
Yes, docks are stacking correctly when dragged on top of each other.

**Comment by sunderme** [comment]
and the reset sidepanel works ?

**Comment by leo-maxwell** [comment]
Yep, it actually works the best! The docks are automatically organized into tabs. I reckon that you should recommend this fix to others experiencing this problem.

**Comment by sunderme** [comment]
I did propose changing to "fusion" and perform reset sidepanel, but the feedback I got so far is, that does not work and I am not sure why or what the missing steps are.

**Comment by sunderme** [comment]
closed as duplicate
