### ISSUE TITLE
Missing line numbers

### ISSUE THREAD

**Issue by jakelamtn** [texstudio-org/texstudio#3666]
### Environment
- TeXstudio: TeXstudio 4.8.0 (git 4.8.0)
- Qt: Using Qt Version 6.7.0, compiled with Qt 6.7.0 R
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
I think there should be line numbers displayed on the side of the editor? It's possible I've just disabled them somehow, but I can't find where to re-enable if that's the case (and I'm sorry)

### Actual behavior
No line numbers
![image](https://github.com/texstudio-org/texstudio/assets/54130243/fa0d25ef-d81f-4182-bcbc-f8530936bcf4)

### How to reproduce
I'm not sure exactly, I tried completely uninstalling and reinstalling and using different themes, but I was not able to see the line numbers.

**Comment by octaeder** [comment]
just go to menu Options/Configure TeXstudio. In the config switch to options group Editor (on the left). On the right find:

![grafik](https://github.com/texstudio-org/texstudio/assets/102688820/003fe710-9000-4947-a5bd-16e176882456)
