### ISSUE TITLE
Side panel is opened by default upon restart

### ISSUE THREAD

**Issue by ptoche** [texstudio-org/texstudio#3667]
Minor issue:

### Environment
- TeXstudio 4.8.0 (git 4.8.0)
- Qt Version 6.7.0, compiled with Qt 6.7.0 R
- OS: MacOS Sonoma 14.4.1 Apple M1 Pro
- TeX distribution: texlive

### Expected behavior
The side panel is closed

### Actual behavior
The side panel is open upon restart

### Workaround
To close the panel, you need to check and then uncheck:

Go to View -> Show -> check/uncheck "Side Panel".

You may set a shortcut In `Preferences -> Shortcuts - > Menus -> View - > Show -> Side Panel`. I set "CMD+F1".

**Comment by sunderme** [comment]
Can you try latest dev build. That is probably fixed.

**Comment by ptoche** [comment]
Thanks for the reply!

Right now I see 4.8.0 from 11 May on https://www.texstudio.org/#download

Is there another place for more recent builds?

**Comment by muzimuzhi** [comment]
@ptoche The latest build can be found in the artifacts of most recent [successful `cd.yml` workflow run](https://github.com/texstudio-org/texstudio/actions/workflows/cd.yml?query=is%3Asuccess). For example https://github.com/texstudio-org/texstudio/actions/runs/9177227001.

**Comment by ptoche** [comment]
Interesting, thank you!

**Comment by sunderme** [comment]
I assume, this is fixed.

**Comment by ptoche** [comment]
The behavior is unchanged in the latest stable release. Still opens the "structure" side bar on a restart.

(P.S. couldn't figure out the "latest build" thing so was just waiting for the latest stable version to report back) 

TeXstudio 4.8.1 (git 4.8.1)
Using Qt Version 6.7.1, compiled with Qt 6.7.1 R

Project home site: https://texstudio.org/
Latest stable version: 4.8.1
