### ISSUE TITLE
TeXstudio has CRASHED due to a SIGSEGV on stack.

### ISSUE THREAD

**Issue by togo65** [texstudio-org/texstudio#3669]
### Environment

TeXstudio 4.8.0 (git 0.0.0++)
Using Qt Version 6.7.0, compiled with Qt 6.7.0 R

Operating System: EndeavourOS 
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.0
Kernel Version: 6.9.1-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-3437U CPU @ 1.90GHz
Memory: 5.7 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 4000
Manufacturer: TOSHIBA
Product Name: PORTEGE Z930
System Version: PT235E-03T04GEN

dpi: 96
which pdflatex: /usr/bin/pdflatex

PDFLATEX: pdflatex -version
pdfTeX 3.141592653-2.6-1.40.26 (TeX Live 2024/Arch Linux)
kpathsea version 6.4.0
Environment variables:
BROWSER=firefox
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DEBUGINFOD_URLS=https://debuginfod.archlinux.org 
DESKTOP_SESSION=plasma
DIFFPROG=meld
DISPLAY=:1
EDITOR=nano
GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:/home/roger/.gtkrc-2.0:/home/roger/.config/gtkrc-2.0
GTK_RC_FILES=/etc/gtk/gtkrc:/home/roger/.gtkrc:/home/roger/.config/gtkrc
HOME=/home/roger
INVOCATION_ID=2eb8738abc204419ba048bd5ce025e0c
JOURNAL_STREAM=9:10478
KDE_APPLICATIONS_AS_SCOPE=1
KDE_FULL_SESSION=true
KDE_SESSION_UID=1000
KDE_SESSION_VERSION=6
LANG=en_GB.UTF-8
LANGUAGE=
LC_ADDRESS=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_MONETARY=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_NUMERIC=en_GB.UTF-8
LC_PAPER=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LOGNAME=roger
MAIL=/var/spool/mail/roger
MANAGERPID=717
MEMORY_PRESSURE_WATCH=/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/session.slice/plasma-plasmashell.service/memory.pressure
MEMORY_PRESSURE_WRITE=c29tZSAyMDAwMDAgMjAwMDAwMAA=
MOTD_SHOWN=pam
PAM_KWALLET5_LOGIN=/run/user/1000/kwallet5.socket
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
PWD=/home/roger
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_WAYLAND_RECONNECT=1
SESSION_MANAGER=local/Z930:@/tmp/.ICE-unix/861,unix/Z930:/tmp/.ICE-unix/861
SHELL=/bin/bash
SSH_AUTH_SOCK=/run/user/1000/gcr/ssh
SYSTEMD_EXEC_PID=890
USER=roger
WAYLAND_DISPLAY=wayland-0
XAUTHORITY=/run/user/1000/xauth_NEtrDK
XDG_CONFIG_DIRS=/home/roger/.config/kdedefaults:/etc/xdg
XDG_CURRENT_DESKTOP=KDE
XDG_MENU_PREFIX=plasma-
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_CLASS=user
XDG_SESSION_DESKTOP=KDE
XDG_SESSION_ID=2
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
XDG_SESSION_TYPE=wayland
XDG_VTNR=1
XKB_DEFAULT_LAYOUT=gb

TeXstudio:
Path        : /usr/bin/texstudio
Program call: /usr/bin/texstudio
Setting file: /home/roger/.config/texstudio/texstudio.ini

Command configuration in TeXstudio:
    Biber (biber): 
    Latexmk (latexmk): latexmk -pdf -silent -synctex=1 %
    Default Viewer (view): txs:///view-pdf
    LaTeX (latex) (r): latex -src -interaction=nonstopmode %.tex
    SVN (svn): 
    Internal Precompile (internal-pre-compile): txs:///pre-compile | txs:///conditionally-recompile-bibliography
    Default Glossary Tool (glossary): txs:///makeglossaries
    XeLaTeX (xelatex) (r): xelatex -synctex=1 -interaction=nonstopmode %.tex
    GIT (git): git 
    BibTeX (bibtex): bibtex %.aux
    PdfLaTeX (pdflatex) (r): pdflatex -synctex=1 -interaction=nonstopmode --shell-escape %.tex
    Texindy (texindy): texindy %.idx
    PS Chain (ps-chain): txs:///latex | txs:///dvips | txs:///view-ps
    SVNADMIN (svnadmin): 
    LuaLaTeX (lualatex) (r): lualatex -synctex=1 -interaction=nonstopmode %.tex
    Default Compiler (compile) (r): txs:///pdflatex
    PS Viewer (view-ps): xdg-open %.ps > /dev/null
    DviPs (dvips): dvips -o %.ps %.dvi
    PDF Chain (pdf-chain): txs:///pdflatex | txs:///view-pdf
    Asymptote DVI Chain (asy-dvi-chain): txs:///latex | txs:///asy | txs:///latex | txs:///view-dvi
    Build & View (quick): txs:///compile | txs:///view
    texdoc (texdoc): texdoc 
    External PDF Viewer (view-pdf-external): xdg-open %.pdf > /dev/null
    Recompile Bibliography (recompile-bibliography): txs:///compile | txs:///bibliography | txs:///compile
    DVI Viewer (view-dvi): xdg-open %.dvi > /dev/null
    DviPng (dvipng): dvipng -T tight -D 120 %.dvi
    DVI Chain (dvi-chain): txs:///latex | txs:///view-dvi
    Asymptote (asy): 
    Xindex (xindex): xindex -l * %.idx
    External Terminal (terminal-external): gnome-terminal
    Default Index Tool (index): txs:///makeindex
    DVI->PDF Chain (dvi-pdf-chain): txs:///latex | txs:///dvipdf | txs:///view-pdf
    Ghostscript (gs): gs "?am.ps"
    Asymptote PDF Chain (asy-pdf-chain): txs:///pdflatex | txs:///asy | txs:///pdflatex | txs:///view-pdf
    Makeindex (makeindex): makeindex %.idx
    Precompile (pre-compile): 
    Default Bibliography Tool (bibliography): txs:///bibtex
    DviPdf (dvipdf): dvipdfmx %.dvi
    BibTeX 8-Bit (bibtex8): bibtex8 %.aux
    DVI->PS->PDF Chain (dvi-ps-pdf-chain): txs:///latex | txs:///dvips | txs:///ps2pdf | txs:///view-pdf
    Ps2Pdf (ps2pdf): ps2pdf %.ps
    PDF Viewer (view-pdf): txs:///view-pdf-internal --embedded
    Makeglossaries (makeglossaries): makeglossaries %
    MetaPost (metapost): mpost -interaction=nonstopmode ?me)

### Expected behavior
Try to open a file either from the File menu or the file icon
Using Wizard, try to open a graphics file. 

### Actual behavior
TeXstudio crashes.

### How to reproduce
on my laptop:
Try to open a file either from the File menu or the file icon
Using Wizard, try to open a graphics file. 

Please note I have been using TeXstudio for as long as I can remember. Possibly over 20 years? Never seen it this unstable.

**Comment by sunderme** [comment]
very likely not an txs issue.
I am working with it daily, so definitely no crashes when opening files.
As it is reported on arch based OS, I am also not looking into it as arch with its rolling release scheme tends to have issue all over the place.

**Comment by sunderme** [comment]
by the way, as it is linux, you can compile txs yourself and run txs in a debuger to get a more sensible backtrace.

**Comment by togo65** [comment]
@sunderme You were quite right, it was an OS issue. And what I love about the rolling release scheme is that bugs don't persist for long. Weird that it only affected txs.
