### ISSUE TITLE
Disappearing file

### ISSUE THREAD

**Issue by BruceWestbury** [texstudio-org/texstudio#3671]
### Environment
TeXstudio 4.8.0 (git 4.8.0)
Using Qt Version 6.7.1, compiled with Qt 6.7.0 R

Pop_OS (based on Ubuntu)
texlive

### Actual behavior
I am using Dropbox and a file keeps disappearing from the shared folder

[texstudio_backtrace1.txt](https://github.com/texstudio-org/texstudio/files/15413076/texstudio_backtrace1.txt)
[texstudio_backtrace2.txt](https://github.com/texstudio-org/texstudio/files/15413078/texstudio_backtrace2.txt)
[texstudio_backtrace3.txt](https://github.com/texstudio-org/texstudio/files/15413079/texstudio_backtrace3.txt)

**Comment by sunderme** [comment]
How do disappearing files connect to backtraces ?

**Comment by sunderme** [comment]
Is safe writing of files active ? (Option)

**Comment by BruceWestbury** [comment]
I don’t know. I included backtracked because the error message said to do
that.

I dont know about safe writing.

The project is large (for me) at just over 80 pages. Each section has its
own file which we include in the master using \input. I believe, with
circumstantial evidence, that only one file is causing a problem.

**Comment by sunderme** [comment]
Just to clarify, you are not reporting a crash, but your file disappears on the dropbox folder ?

**Comment by BruceWestbury** [comment]
Yes, but I don't know how to reproduce it. I have had the same error
message seven times this morning.

**Comment by sunderme** [comment]
this is likely a dropbox issue.
As I don't have dropbox, I close this.
