### ISSUE TITLE
Dropdown is black - no options available in Configure TeXstudio

### ISSUE THREAD

**Issue by ststst123123** [texstudio-org/texstudio#3673]
### Environment
- TeXstudio: 4.8.0
- Qt: 6.7.0
- OS: Windows10
- TeX distribution: miktex

### Expected behavior
When I go to Configure TeXstudio in options, I only see a black background where the alternative choices should be (see screenshot). This holds for every single drop down in Configure TeXstudio. I don't have this problem with version 4.7.3 and can see all alternatives. 

### Actual behavior

![txs_bug](https://github.com/texstudio-org/texstudio/assets/170688459/84390e83-67c8-4adc-bf2c-91afdc7a4bca)

**Comment by octaeder** [comment]
duplicate, s. #3636 for an explanation/workaround

**Comment by ststst123123** [comment]
Thank. Choosing a style other than Windows11 or WindowsVista is a workaround to the issue.
