### ISSUE TITLE
Add ability to search across multiple files

### ISSUE THREAD

**Issue by elyahw** [texstudio-org/texstudio#3678]
### Describe the feature and the current behavior/state
Currently, if the main tex file includes other tex files (say each contains a chapter), when a search is performed, only the main file is searched. The included files aren't searched.

It will be nice if the search also included results from all included files..

### Who will benefit with this feature?
Everyone. It will increase productivity. Instead of going into each file and searching for a term, it would be possible to search the whole book/all included tex files.

**Comment by sunderme** [comment]
https://texstudio-org.github.io/editing.html#extended-search
