### ISSUE TITLE
Only a limited length of text can be copied to clipboard on Wayland

### ISSUE THREAD

**Issue by DerryAlex** [texstudio-org/texstudio#3681]
### Environment
- TeXstudio: 4.3.1, [e21bf65](https://github.com/texstudio-org/texstudio/commit/e21bf65c70c0e14548898ff0ad58b6921cec44a9)
- Qt: 5.15.8
- OS: Linux debian 6.1.0-21-amd64
- TeX distribution: texlive 2022

### Expected behavior
Unlimited length(or at least 1,000,000) of text can be copied on Wayland.

### Actual behavior
Only a limited length (~ 60000) can be copied to clipboard while one can copy at least 70000 characters using GNOME Text Editor.
A workaround is to set `QT_QPA_PLATFORM=xcb`. The AppImage works because libqwayland is not shipped with it.

Possibly related #2387

**Comment by sunderme** [comment]
Looks like a qt issue.
Txs relies on qt to handle clipboard interaction. Txs does not know anything about the underlying window manager, its code is always the same.

You can try to use txs with qt6 from obs, see texstudio.org.

**Comment by sunderme** [comment]
Quick test on windows shows no issue with 150k characters.

**Comment by DerryAlex** [comment]
qt6 does work

**Comment by sunderme** [comment]
So, can we close this ?
