### ISSUE TITLE
Enhance Language Checking by Integrating LanguageTool API

### ISSUE THREAD

**Issue by niekdomi** [texstudio-org/texstudio#3682]
### Feature Description
Currently, TexStudio integrates LanguageTool for grammar and spelling checks via a local server. This setup limits the tool's capability to catch more complex errors, such as missing punctuation in nested clauses.

### Proposed Change
Integrate the LanguageTool API directly into TexStudio. This would streamline the setup process and enhance the language checking capabilities. For example, while the local server setup may not identify missing commas in complex sentences, the API can detect and suggest corrections effectively.

### Benefits
- **Easier Setup:** Users will no longer need to configure and maintain a local server.
- **Improved Accuracy:** Enhanced detection of grammatical errors, especially in complex sentences.

### Example
Current local server setup:
- Input (german): "Der Hase der Hunger hatte"
- Output: No errors detected.

Using the LanguageTool API:
- Input: "Der Hase der Hunger hatte"
- Output: Suggests adding a comma: "Der Hase, der Hunger hatte"

**Comment by sunderme** [comment]
txs let's you set a "server url" for LanguageTool. That can be *any* url and the actual rest api is (or was) the same as for a local server. 
The main drawback is that txs sends every change to that server as you type and as far as I know, LanguageTool bills by the number of words which can rise drastically this way.
So, it may be necessary to have an alternate mode which only sends texts when asked...

**Comment by sunderme** [comment]
Have you tried setting just "https://api.languagetool.org/" ? txs add v2/check to the path.
