### ISSUE TITLE
Problems since 4.8.0: window height and side panel

### ISSUE THREAD

**Issue by ansisec** [texstudio-org/texstudio#3683]
### Environment
- TeXstudio: 4.8.0+
- Qt: 6.7.1
- OS: MacOS (intel)

### Expected behavior
to work!

### Actual behavior
doesn't work!
Since version 4.8.0, I have had to stop using TeXstudio on macOS (x86) and go back to TeXmaker. I just tried installing version 4.8.1, and the problems remain the same. Do they release versions without even testing them or asking someone to test? The window starts at a size that is probably more than twice the height of the screen (honestly, I don't know), making it unfeasible to use because part of it extends below the visible line, and we don't know what is happening. Associated with this (and maybe the cause of it all) is the "side panel" appearing with all the tools open. To get anything done, it is necessary to go to View->Show->Side Panel twice... until it finally allows you to resize the window to make it usable. In my case, using it means closing and opening the files in TeXmaker.

![Screenshot 2024-06-08 at 10 53 30 (2)](https://github.com/texstudio-org/texstudio/assets/93681611/38f0449b-9100-4961-a1fa-7f132d53727a)

**Comment by sunderme** [comment]
duplicate to #3637
