### ISSUE TITLE
Some Close Button Disappear under Dark Mode

### ISSUE THREAD

**Issue by Jack251970** [texstudio-org/texstudio#3685]
### Environment
- TeXstudio: 4.8.1
- Qt: 6.7.1 R
- OS: Windows 22631.3672
- TeX distribution: Miktex

### Actual behavior
<img width="529" alt="Close Button Bug" src="https://github.com/texstudio-org/texstudio/assets/53996452/5d353f16-d977-4bc7-bf92-1118e2efc271">

### How to reproduce
Switch windows to dark mode.
Use ctrl+r or ctrl+s to open search & replace card, you will find this close button just disappear.
You can see this button if your mouse move to corresponding position.

**Comment by sunderme** [comment]
not reproducible on linux.
Have you restarted txs ?

**Comment by Jack251970** [comment]
> not reproducible on linux. Have you restarted txs ?

txs means?

**Comment by Jack251970** [comment]
Yes, I have restarted texstudio. Here is the demo video.

https://github.com/texstudio-org/texstudio/assets/53996452/c3634f8a-7c82-4744-b0a1-0ae2ebe1009d

**Comment by Jack251970** [comment]
It's very strange. Some close buttons can display normally, such as the close button in the right top of the message pane. Some close buttons just cannot, such as this close button, and the close button of the tab.

All close buttons have been selected with red circle.

<img width="1133" alt="Close Button Bug" src="https://github.com/texstudio-org/texstudio/assets/53996452/6bc8f611-2662-4b56-9964-be29e3dae6d6">

**Comment by sunderme** [comment]
what is your exact setting under config/appearance

**Comment by Jack251970** [comment]
Just the default settings.

<img width="835" alt="屏幕截图 2024-06-08 233220" src="https://github.com/texstudio-org/texstudio/assets/53996452/d3c1d02f-44e2-4411-9323-b2e64d7f05f6">
