### ISSUE TITLE
I need for the scroll bars NOT to collapse

### ISSUE THREAD

**Issue by alanrunner** [texstudio-org/texstudio#3686]
In the current release of Texstudio (4.8.1) the vertical scroll bar collapses unless the mouse is hovering over it.  Also, it seems to me that the scroll bar is narrower than it used to be. This is very annoying. I NEVER want scroll bars to collapse. I think this is one of the significant design flaws in recent UI's from both Microsoft and Google. It makes editing a document much more difficult.

Please make an option to restore the scroll bars so that they never collapse. And also make the option for a normal width scroll bar instead of the extra narrow scroll bar.

**Comment by sunderme** [comment]
change the style to anything but windows11.
<img width="690" alt="grafik" src="https://github.com/texstudio-org/texstudio/assets/14033169/504f7c10-c095-4b95-9ef9-3b0cd95f8a8f">
