### ISSUE TITLE
Hyperlinks work but no colors

### ISSUE THREAD

**Issue by dsdrumh** [texstudio-org/texstudio#3688]
### Environment
-Texstudio version 4.8.1
- Qt: 
-OS Window 7
- MikTex updated today

### Description
The MWE is below.  It does not produce hyperlink color in either internal or external pdf viewer. It works fine in my Pctex distribution.

\documentclass{article}
\usepackage[dvips]{graphicx,color}
\usepackage{hyperref}

% Customize hyperlink colors (optional)
\hypersetup{
    colorlinks=true,
    linkcolor=blue,
    filecolor=magenta,
    urlcolor=cyan,
    pdftitle={Hyperlink Example},
    pdfauthor={Your Name},
    pdfsubject={PDF with Hyperlinks},
    pdfkeywords={LaTeX, PDF, hyperlinks}
}

\begin{document}

\title{Creating Hyperlinks in PDF}
\author{Your Name}
\date{\today}
\maketitle

\tableofcontents
\clearpage
\section{Introduction}
Welcome to the introduction section. For more details, visit \href{https://www.example.com}{this link}.
\clearpage

\section{Link to Section}
In this section, we will link to another section. Go to \hyperref[sec:conclusion]{ab}.
\end{document}

**Comment by muzimuzhi** [comment]
> \usepackage[dvips]{graphicx,color}

The `dvips` driver is specified, which requires a latex -> dvips -> ps2pdf chain. If you compile the tex file with for example pdflatex, then just remove that `dvips` option.

BTW TeXstudio is just an editor and for questions with LaTeX use, forums like tex.stackexchange.com is recommended.

**Comment by dsdrumh** [comment]
Im new at this thankyou ill move. but i did discover that removing the whole line worked.

**Comment by dsdrumh** [comment]
even the graphs now works.  ThanQ
