### ISSUE TITLE
(FR) Please provide official FlatPak for TeXstudio

### ISSUE THREAD

**Issue by zWhdmB5T** [texstudio-org/texstudio#3693]
Dear all,

there is a [TeXstudio FlatPak](https://flathub.org/apps/org.texstudio.TeXstudio) available. Unfortunately, it is not officially maintained like others (e.g. [Firefox FlatPak](https://flathub.org/apps/org.mozilla.firefox), [LibreOffice FlatPak](https://flathub.org/apps/org.libreoffice.LibreOffice) or [digiKam FlatPak](digiKam)).

I would appreciate that very much. I expect high security as well as an up-to-date release (including all used libraries and such) of an official package.

Thank you!

**Comment by zWhdmB5T** [comment]
Because one could counter that the examples of officially maintained FlatPaks mentioned above are not _community driven_ (i.e. a single persons or just a few ones) but maintained by an organisation resp. a company, here are other examples:

- [KeePassXC](https://flathub.org/apps/org.keepassxc.KeePassXC) (community)
- [Strawberry Music Player](https://flathub.org/apps/org.strawberrymusicplayer.strawberry) (solo)
- [fre:ac](https://flathub.org/apps/org.freac.freac) (solo)
- [FSearch](https://flathub.org/apps/io.github.cboxdoerfer.FSearch) (solo)
- [Qalculate! (GTK UI)](https://flathub.org/apps/io.github.Qalculate) (solo)
- [Metadata Cleaner](https://flathub.org/apps/fr.romainvigier.MetadataCleaner) (solo)

**Comment by sunderme** [comment]
if it can be build automatically via github actions, It would be okay.
But also someone else can set up a build script and hand in a pull-request.

**Comment by sunderme** [comment]
I have looked into the current texstudio flatpak build and that looks fine.
I am not really inclined to jump through hoops to get a green tick. If the flatpack author wants to get an "official" badge, we can discuss.

**Comment by Alexander-Wilms** [comment]
This is all that's required to verify the Flat hub package:

Create a page at https://texstudio.org/.well-known/org.flathub.VerifiedApps.txt containing the following token:

92b73b87-f3f9-4dea-a84b-1c83d9e9699e

Pull request with updates are created automatically, triggering test builds. In the past, these were merged automatically, but this now requires an exception approved by the Flat hub admins.

**Comment by sunderme** [comment]
token was placed

**Comment by Alexander-Wilms** [comment]
![image](https://github.com/texstudio-org/texstudio/assets/3226457/c0c1f975-d5e8-46f1-93f3-7622558c04a7)

**Comment by zWhdmB5T** [comment]
Very nice! Thank you!
