### ISSUE TITLE
Menu Coloring

### ISSUE THREAD

**Issue by drfloren** [texstudio-org/texstudio#3694]
Have a dark system theme, but use light for TexStudio (yalls dark is too dark). Have style as default, color scheme as classic, icon theme as colibre, checked "ignore most system colors".

In this, the theme for everything looks great (normal), but the menus are all in black and unreadable. The dropdowns for options on the helper bar (e.g., \right( and \left) ) are also unreadable.

Have restarted program and computer.

### Environment
- TeXstudio: 4.8.1
- Qt: Using Qt Version 6.7.1, compiled with Qt 6.7.1 R
- OS: Windows 11
- TeX distribution: miktex

### Expected behavior
Menus would match the theme color (be their classic white/gray).

### Actual behavior
![image](https://github.com/texstudio-org/texstudio/assets/88336500/799cd7b3-9acd-441f-9fea-31d1561c1b18)

### How to reproduce
Open TexStudie with a dark theme and check "Ignore most system colors" in general options.

**Comment by drfloren** [comment]
Sorry: just saw in closed issue #3636 that this is fixed by changing the style to be something else (other than Windows 11 or default which, for me, is probably Windows 11!). Changing this and restarting the program completely solves the issue.

**Comment by octaeder** [comment]
Hm, this issue should be fixed with latest Qt. [Changelog](https://texstudio-org.github.io/CHANGELOG.html) from txs 4.8.1 says: fix black background on comboxes with windows11 style (qt6.7.1).

**Comment by sunderme** [comment]
It looks rather like this is a different variant of a similar bug like #3636.

**Comment by sunderme** [comment]
seems like the windows11 style uses an inaccessible color palette unlike the other palette.
So, the "ignore system colors" only works with styles other than windows11.
