### ISSUE TITLE
Issue when scaling is set to 150% or 200%: window is outside visible area

### ISSUE THREAD

**Issue by MrI2C** [texstudio-org/texstudio#3695]
Win11: When scaling of a monitor is set to eg 150% or 200%, placing TeXStudio in full screen displays part of the active area outside the visible area.
Addition: seems to be the issue when my monitor 4 is NOT placed as primary-monitor. 

### Environment
- TeXstudio: TeXstudio 4.8.1 (git 4.8.1)
- Qt: Version 6.7.1, compiled with Qt 6.7.1 R
- OS: Windows11

### Expected behavior
proper scaling

### Actual behavior
Underneath a screen shot of a 4 monitor setup:
![image](https://github.com/texstudio-org/texstudio/assets/145350751/70248b36-fccc-447d-8e7c-74b00f83a8b2)
and here how it looks when TeXstudio is on monitor4 with a scaling of 200% (all others have 100%)
you can see the active areas "expands" to monitor 1 and there's no way to get it all on monitor4

![image](https://github.com/texstudio-org/texstudio/assets/145350751/a73afa9b-9690-4532-a2ce-43d49acc3a1a)

### How to reproduce
place a monitor in 200% scaling mode

**Comment by sunderme** [comment]
by the way, it looks like it is a similar issue #3637 
you can try the OSX workaround:
      * change option/general/style to fusion
      * execute menu: view/show/reset sidepanel
      * double click on window title bar for window resize (don't know if that works on win)
      * reduce number of visible docks (menu view/show/...)

**Comment by sunderme** [comment]
no feedback
