### ISSUE TITLE
side panel is opened by default

### ISSUE THREAD

**Issue by ptoche** [texstudio-org/texstudio#3696]
A follow-up on [this issue](https://github.com/texstudio-org/texstudio/issues/3667), which remains unresolved.

The behavior is unchanged in the latest stable release. Still opens the "structure" side bar on a restart.

(P.S. couldn't figure out the "latest build" thing so was just waiting for the latest stable version to report back)

TeXstudio 4.8.1 (git 4.8.1)
Using Qt Version 6.7.1, compiled with Qt 6.7.1 R

Project home site: https://texstudio.org/
Latest stable version: 4.8.1

**Comment by foreachthing** [comment]
> "latest build"

https://github.com/texstudio-org/texstudio/actions/workflows/cd.yml
At the bottom of each workflow run, there are the artifacts.

**Comment by ptoche** [comment]
Thanks @foreachthing , I just don't know what to do with that information...

**Comment by foreachthing** [comment]
Well, there you can find the "latest builds". Artifacts are the (automated) builds which you can download.
muzimuzhi already explained it in issue 3667.

Try the latest build (as of today):
1. go to: https://github.com/texstudio-org/texstudio/actions/runs/9437868998
2. Scroll all the way down
3. Download the file for your OS

**Comment by ptoche** [comment]
Got it thanks!

Well the latest build does not even open for me!

**Comment by domokane** [comment]
How can I close the structure window pane ? Very annoying.

**Comment by octaeder** [comment]
Button at lower left

![image](https://github.com/texstudio-org/texstudio/assets/102688820/276a7973-0ee2-4b4a-b2ae-9f1e281c6ee4)

or with menu view:

![image](https://github.com/texstudio-org/texstudio/assets/102688820/487c2013-944c-4e64-88e8-2af2b9e24586)

**Comment by domokane** [comment]
Thanks ! I found it by chance just after my rant. It's not intuitive. I was expecting something in the view menu or by right clicking or a cross on the pane that I could click. Thanks again.

**Comment by octaeder** [comment]
In earlier versions the panel had its own close button (cross at upper right). However, the vertical tabs can now be rearranged, so the button had to be removed.

**Comment by ptoche** [comment]
Alternative ways to close the view:

Go to View -> Show -> check/uncheck "Side Panel".

Set a shortcut In Preferences -> Shortcuts - > Menus -> View - > Show -> Side Panel. I set "CMD+F1".

**Comment by octaeder** [comment]
I use `Alt+F1` for the side panel and `Alt+F2` for the message pane (at lower end of UI):

![image](https://github.com/texstudio-org/texstudio/assets/102688820/e042b448-4de7-4dc9-97aa-eea62b86f167)

**Comment by nheerten** [comment]
> Button at lower left
> 
> ![image](https://private-user-images.githubusercontent.com/102688820/346268885-276a7973-0ee2-4b4a-b2ae-9f1e281c6ee4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTI4NDQsIm5iZiI6MTcyMjg1MjU0NCwicGF0aCI6Ii8xMDI2ODg4MjAvMzQ2MjY4ODg1LTI3NmE3OTczLTBlZTItNGI0YS1iMmFlLTlmMWUyODFjNmVlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxMDA5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzA5OGIwNmJjYjJhNTc0NDhmMjM1MWQ4OGM3MzU3NjkyM2YyY2I2Zjg2NjkxMTk0M2ViODc1ZTJmY2NiMjU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.euvsLQY05ghemn44ual3SeJl0NZXP0d-cowflaQ0J0k)
> 
> or with menu view:
> 
> ![image](https://private-user-images.githubusercontent.com/102688820/346268923-487c2013-944c-4e64-88e8-2af2b9e24586.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTI4NDQsIm5iZiI6MTcyMjg1MjU0NCwicGF0aCI6Ii8xMDI2ODg4MjAvMzQ2MjY4OTIzLTQ4N2MyMDEzLTk0NGMtNGU2NC04OGU4LTJhZjJiOWUyNDU4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxMDA5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWE4MDQ3YmE2NmEzMDlmNTkzNjdjMTYwY2JmMDNhNzk5M2IxZjljMDY2YTI1ZTBjYjQzOWU1YzIwZGUxYWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xso_4sB6MtFGrVv3BUm0v42Skj7w-yoXj4x6iY6DxeY)

With the latest stable Version (4.8.1 from https://www.texstudio.org), every time the program is launched, the dimension of the window is too wide (from top to bottom) so that these items for hiding the panel are not visible. Sidebar still opens at every launch. That so annoying.

**Comment by ptoche** [comment]
And also upon restart, I need to do a resize action on the window in order to be able to scroll down the document. The window size is fine, but scrolling down the text with the cursor is blocked/ineffective at the bottom of the window until a tiny click on the window resets it nicely. This is a bug, not a feature. If the next update doesn't fix it, I'll post a proper issue.

**Comment by sunderme** [comment]
should be fixed with 4.8.2
