### ISSUE TITLE
Unpolished new AI chat feature

### ISSUE THREAD

**Issue by Atcold** [texstudio-org/texstudio#3699]
### Environment
- TeXstudio: 4.8.1
- Qt: 6.7.1
- OS: macOS 14.5
- TeX distribution: 3.141592653 (TeX Live 2023)

### Expected behavior

If I select `Local Model`, the `API key` field should not be asserted to be non-empty.

### Actual behavior

<img width="510" alt="image" src="https://github.com/texstudio-org/texstudio/assets/2119355/f26d2a0d-8699-4b3b-b815-10ce9ca5a5ab">

### Expected behavior

I should be able to read the answer.

### Actual behavior

White text on white background is unlegible.

<img width="644" alt="image" src="https://github.com/texstudio-org/texstudio/assets/2119355/c239a5a8-ae0a-451f-b832-53ff0f6b1f6b">

### How to reproduce

Select `Local Model` and do not insert anything in `API key`.
Use a dark theme.

**Comment by Atcold** [comment]
Moreover, I do have the following question: "How can we use a language model be used for correcting grammar and spelling?". This would be my usage number one. Being not a native speaker, having a bot double checking my content would be rather helpful!

**Comment by Atcold** [comment]
Also, I think there's some confusion (at least on my side) on how the "start the language model with TeXstudio" works. Currently, it asks for Java and a LT Path, whereas *llamafile* does not require any of this nor it's selectable.

**Comment by Atcold** [comment]
One more screenshot, since the output look different.
In this case the selected text is "\begin{bsmallmatrix}" and the query is "What does this instruction do?".

<img width="1259" alt="image" src="https://github.com/texstudio-org/texstudio/assets/2119355/9ed7c1b5-7cff-4e4f-a90e-1488965a583d">

**Comment by sunderme** [comment]
the original issue is fixed
LanguageTool is not related to LLM at all.
Examples of usage of LLMs is given in the manual. It can be discussed in discussion forum.
Obviously I don't fix LLMs concerning the last example. Mistral and ChatGPT usually give helpful results.

**Comment by Atcold** [comment]
For "original issue" are you referring to the empty API key?

Regarding LanguageTool, I didn't know what it was, two days ago.
I thought the two things were related.

The last example was concerning the light background colour with white text.
Not the actual model output. Perhaps I was not clear.
Please, see screenshot in https://github.com/texstudio-org/texstudio/issues/3699#issuecomment-2176828502.
