### ISSUE TITLE
Export config

### ISSUE THREAD

**Issue by raffam** [texstudio-org/texstudio#37]
It would be useful a feature to export and import the configuration settings of TexStudio (including shortcuts and custom macros)

Also, maybe this configuration can be synced over the cloud (lie Firefox or Chrome sync bookmarks and settings)

**Comment by sunderme** [comment]
config/macrso are stored in .config/texstudio (see wiki for info for windows).
If you sync that directory to the cloud, you would have a synchronous set-up

**Comment by raffam** [comment]
Hi sunderme.
Thank you for your reply. Unfortunately, I don't think this is a good solution.
I have copied my windows's config.ini to the ubuntu's config.ini.
TexStudio stopped compiling the file, because the path of XeLaTeX differs from Windows to Ubuntu.
The config.ini files contain such information as the path of the compilers, which should not be cross-copied over operating systems.
Thanks you for your attention

**Comment by timhoffm** [comment]
Then again, there would be people who would want to switch their TeX environment using configs. For now, we are not going down this road of keeping or discarding parts of a config.
