### ISSUE TITLE
Broken side panels

### ISSUE THREAD

**Issue by Atcold** [texstudio-org/texstudio#3700]
### Environment
- TeXstudio: 4.8.1
- Qt: 6.7.1
- OS: macOS 14.5
- TeX distribution: 3.141592653 (TeX Live 2023)

### Expected behavior

After updating, the side panels are now all broken.

### Actual behavior

<img width="390" alt="image" src="https://github.com/texstudio-org/texstudio/assets/2119355/a2265de4-2c17-4f15-8870-8e3ffb0d5346">

### How to reproduce

Install the latest version for osx-m1.

**Comment by sunderme** [comment]
duplicate #3637 
See also https://github.com/texstudio-org/texstudio/wiki/Known-Issues#osx

**Comment by Atcold** [comment]
Ah, totally missed that. Sorry about that.

I'd update the wiki, though. All it's necessary is the following:

1. View → Show → Reset Sidepanel/docks
2. Options → Save Current Settings
