### ISSUE TITLE
Issues with setting up LanguageTool

### ISSUE THREAD

**Issue by Atcold** [texstudio-org/texstudio#3701]
### Environment
- TeXstudio: 4.8.1
- Qt: 6.7.1
- OS: macOS 14.5
- TeX distribution: 3.141592653 (TeX Live 2023)

### Bug description

I'm trying to set up LanguageTool, but there are several issues.
First, without specifying a correct path for Java, nothing works (even though LanguageTool is already running in the background).
Second, the default language is set by TeXstudio to `<none>` which breaks LanguageTool, which answers with the following

```
LT current status: error
Error: '<none>' is not a language code known to LanguageTool. Supported language codes are: ar, ast-ES, be-BY, br-FR, ca-ES, ca-ES-balear, ca-ES-valencia, crh-UA, da-DK, de, de-AT, de-CH, de-DE, de-DE-x-simple-language, de-DE-x-simple-language-DE, de-LU, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, es-AR, es-ES, fa, fa-IR, fr, fr-BE, fr-CA, fr-CH, fr-FR, ga-IE, gl-ES, it, it-IT, ja-JP, km-KH, nl, nl-BE, nl-NL, pl-PL, pt, pt-AO, pt-BR, pt-MZ, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sv, sv-SE, ta-IN, tl-PH, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See https://dev.languagetool.org/java-api for details.
```

How can I specify a language?

**Comment by Atcold** [comment]
Installing a dictionary was necessary to be able to change the value of `<none>` to anything else.
This should not be necessary if one simply wants to use LT, since the two things are unrelated.

**Comment by Atcold** [comment]
Renaming `texstudio.ini` to `texstudio.ini.bak` allows me to specify any language under Spell Check.
<img width="275" alt="image" src="https://github.com/texstudio-org/texstudio/assets/2119355/50a32a93-56bc-4e06-91b3-87c8f27762f7">

With my default `texstudio.ini` file only `<none>` was available.
My old `texstudio.ini` file has the following
```
Spell\DictionaryDir="/Applications/texstudio.app/Contents/Resources;[txs-settings-dir]/dictionaries"
```
while the new one has changed the app name
```
Spell\DictionaryDir=/Applications/texstudio-4.8.1-osx-m1.app/Contents/Resources
```

So, the app renaming broke my previous configuration.

**Comment by sunderme** [comment]
changed default setting for SpellDic to `[txs-app-dir]/../Resources` which is independent of the actual folder name.

**Comment by Atcold** [comment]
Thanks! 🙏🏻
