### ISSUE TITLE
Missing space in parsed log file for multiline L3 warnings/errors

### ISSUE THREAD

**Issue by samcarter** [texstudio-org/texstudio#3702]
The parsing of multiline L3 warnings/errors has been greatly improved in #1410. 

One tiny problem are missing spaces at the line break, e.g.

```
\documentclass{article}

\usepackage[
    load-configurations=abbreviations,
]{siunitx}

\begin{document}
.
\end{document}
```

will currently be parsed as

```
siunitx.sty: warning: : Option "load-configurations" has been removed in thisrelease.
```
(missing space in `thisrelease`)

If https://github.com/texstudio-org/texstudio/blob/master/src/latexoutputfilter.cpp#L743 would only strip 15 spaces instead of 16, the result would be

```
siunitx.sty: warning: : Option "load-configurations" has been removed in this release.
```

### Environment
- TeXstudio: https://github.com/texstudio-org/texstudio/commit/81306ec1818eb53fcf50294270bf7db07fa282d7
- Qt: 6.7.0
- OS: macOS 14.5
- TeX distribution: TL'23

**Comment by sunderme** [comment]
Is the space also missing with other warnings when they are multiline ?

**Comment by samcarter** [comment]
Thanks for the quick fix!

I haven't yet come across missing spaces in other types of warnings. I'll let you know if I see one.
