### ISSUE TITLE
adjustable linespacing in editor

### ISSUE THREAD

**Issue by libroraptor** [texstudio-org/texstudio#3705]
### Describe the feature and the current behavior/state
It is currently possible to set the font size in the editor, but not the leading.

I recommend adding an option to adjust linespacing. This might take one of the following forms:
- specify leading as number of points
- specify linespacing as a multiplier with one or two decimal places (1.0 for singlespacing, 2.0 for double)
- specify linespacing as a percentage (100% for singlespacing, 200% for double)

### Who will benefit with this feature?
- people with reading and visual processing disabilities
- people with tired eyes

**Comment by sunderme** [comment]
you can specify line spacing in percentage.
Options/editor/Line Spacing

**Comment by libroraptor** [comment]
Thanks. I found it and have come back to mention that it is hidden as an "advanced" option.

**Comment by octaeder** [comment]
@libroraptor  Options can be found quickly by using the options filter field:

![image](https://github.com/texstudio-org/texstudio/assets/102688820/aaab995c-99dc-4900-8170-9fd2da376aa3)

The filter behaves as if the `Show Advanced Options` option is activated.

**Comment by libroraptor** [comment]
That's all nice but the reason that I raised this is cognitive and visual processing disabilities. Nesting features within features achieves the opposite purpose. The solution is to improve the interface design so that it communicates itself – every time something needs to be explained, it's evidence that the interface has failed.
