### ISSUE TITLE
Printing document prints the codebase instead of the compiled document

### ISSUE THREAD

**Issue by ZenKyma** [texstudio-org/texstudio#3710]
Printing from texstudio outputs the codebase, especially wasteful for color if dark mode is enabled and tricky as a preview is not always supplied.

### Environment
- TeXstudio: 4.8.1 
- Qt: qt6
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior

Printing with Ctrl+P should send the compiled pdf document to the printer.

### Actual behavior

Printing with Ctrl+P sends the codebase text to the printer.

### How to reproduce

Press Crtl+P and confirm.

**Comment by sunderme** [comment]
current policy is to use external pdf viewer to print pdf.

**Comment by samcarter** [comment]
related feature request which explains some of the challenges: https://github.com/texstudio-org/texstudio/issues/201

**Comment by ZenKyma** [comment]
Thank you fore the swift response, it came to my mind that the issue could be solved by adding a warning dialogue that one is going to print the source code, which could optionally be disabled for future instances. In this way, a user would not print the source code accidentally by pressing Ctrl+P while thinking that the compiled document will be printed.

**Comment by samcarter** [comment]
> Thank you fore the swift response, it came to my mind that the issue could be solved by adding a warning dialogue that one is going to print the source code, which could optionally be disabled for future instances. In this way, a user would not print the source code accidentally by pressing Ctrl+P while thinking that the compiled document will be printed.

You can remove the ctrl+P shortcut in the preferences to avoid accidentally printing the source

**Comment by ZenKyma** [comment]
I know this, but my point is that the expected behaviour for an unexperienced user might be that ctrl+p prints the pdf. The user will only realize after printing that the outcome was unexpected. Especially when the source code is long, an erroneous printing of it might result in a huge waste of paper and ink.

On Wednesday, 3 July 2024 13:03 (+01:00), samcarter wrote:



Thank you fore the swift response, it came to my mind that the issue could be solved by adding a warning dialogue that one is going to print the source code, which could optionally be disabled for future instances. In this way, a user would not print the source code accidentally by pressing Ctrl+P while thinking that the compiled document will be printed.

You can remove the ctrl+P shortcut in the preferences to avoid accidentally printing the source

**Comment by ZenKyma** [comment]
![2024-07-03-13-47-21-694_1](https://github.com/texstudio-org/texstudio/assets/116916092/baefeb53-09fe-4508-867a-31fe181ec8c1)

**Comment by sunderme** [comment]
shortcut removed as suggested

**Comment by ZenKyma** [comment]
Thank you!
