### ISSUE TITLE
Menu dissapears when moving mouse to menu item  

### ISSUE THREAD

**Issue by fft2865** [texstudio-org/texstudio#3711]
Platform: TexStudio Versions 4.8.x, on Win 11 22H2 

### Expected behavior
Click on a menue item in the top bar, move to item and click selection - all items and menu fully visible.

### Actual behavior
When clicking on a menu in the top bar the full list of options appears. However when moving the mouse downwards the menue dissappears (=becomes invisible) but still seems to be there. Items of the menu appear when the mouse hovers over  (=highlights selection). Behavior/mistake  is consistent for all menus under the top bar items. 

Current fix is to go back to version 4.7.3 or earlier which seems to be stable. 4.8.0 and 4.8.1 both show this error. Could not find similar error descriptions in the internet, no clue what's the reason except probabaly Microsoft update which came in recently.

**Comment by sunderme** [comment]
please provide screenshots/screencast

my guess would be that you want to change options/general/style to fusion ?
