### ISSUE TITLE
Include files do not inherit root properties

### ISSUE THREAD

**Issue by GeoffRiley** [texstudio-org/texstudio#3712]
### Environment
- TeXstudio: 4.8.0 (git 4.8.0)
- Qt: 5.1.2.8
- OS: Linux Ubuntu 22.04.4 LTS (running on Intel i7)
- TeX distribution: TeXLive 2023

### Expected behaviour
When starting a new included file, the new file should inherit the various styles loaded in the root document, especially concerning syntax highlighting in maths mode.

### Actual behaviour
Standard environments such as `align' are not recognised as being in maths mode until the program is exited and reloaded; just closing and reopening the root file does not appear to work.

### How to reproduce
Create a container root document that uses `include` to pull in individual part files, attempt to create an `align` environment, then type something like `\frac{1}{2}` within the environment. Two things may be observed:
* if the autocomplete is allowed to enter the `\frac{}{}` it will add dollar signs before and after;
* if you type the full thing, then the `\frac` is highlighted with the popup hint of `math command outside of math env`.

If the file is pre-existing, then neither of these problems is present.

The solution is to exit the program and reload afresh.

**Comment by sunderme** [comment]
Please provide a minimal example with all the files and step by step instruction on how to reproduce the issue.

**Comment by sunderme** [comment]
no feedback
