### ISSUE TITLE
AI Assistant - Error transferring https://api.openai.com/v1/chat/completions

### ISSUE THREAD

**Issue by lejos46703** [texstudio-org/texstudio#3713]
### Environment
- TeXstudio:  4.8.1
- Qt: 6.7.1 
- OS: Windows 10
- TeX distribution: Texlive 2024

### Expected behavior
As described in the manual (https://texstudio-org.github.io/advanced.html)

### Actual behavior

While the ChatGPT macros (https://github.com/icarecti/chatgpt_macro_for_texstudio)  work perfectly, the AI assistant apparently cannot connect to ChatGPT correctly, even though all settings (API-key, model) in Options are correct

![grafik](https://github.com/texstudio-org/texstudio/assets/65977562/71a0d8c1-6c16-47a3-9cba-3b3e22ac0d9e)

![grafik](https://github.com/texstudio-org/texstudio/assets/65977562/970b585c-14e4-4a5e-8587-2ae4ba62490a)

Is there any further information on which settings may still need to be made?
![grafik](https://github.com/texstudio-org/texstudio/assets/65977562/d1f4af4b-7c41-41ee-8246-a0bf455533cd)

Best regards,
Josef

**Comment by djberg96** [comment]
I am also seeing this.

TeXstudio 4.8.9 (git 4.8.9) Using Qt Version 6.9.2 on Mac.

**Comment by ap0305-thunder** [comment]
Same problem for me...
TeXstudio 4.9.0 (git 4.9.0)
Using Qt Version 6.10.0, compiled with Qt 6.10.0 R
on windows 11

**Comment by sunderme** [comment]
openai expired my purchased credit. I am not giving them more money for testing, so somebody else can look into any issue with openai.
local models and mistral work fine.
