### ISSUE TITLE
Add 'scroll past end' functionality to TeXstudio editor

### ISSUE THREAD

**Issue by samer5301** [texstudio-org/texstudio#3714]
**Feature Request: Scroll Past End**

**Description:**
I would like to request the addition of a "scroll past end" feature in the TeXstudio editor. This feature allows users to scroll beyond the last line of the document, positioning the last line at the top of the editor window. This is especially useful for long documents where constantly looking at the bottom of the screen can be straining.

**Current Behavior:**
Currently, in TeXstudio, when editing a document, the editor stops scrolling as soon as the last line of text reaches the bottom of the window. This requires users to always look at the bottom of the screen when working on the last few lines of a document.

**Expected Behavior:**
With the "scroll past end" feature enabled, users should be able to scroll beyond the last line of the document, allowing the last line to be positioned at the top of the editor window. This would provide a more comfortable and flexible editing experience.

**Example:**
An example of this feature can be seen in Visual Studio Code. When the "editor.scrollBeyondLastLine" setting is enabled, users can scroll beyond the last line of the document.

**Benefits:**
- Improves readability and comfort for users working on the last lines of a document.
- Reduces eye strain by allowing users to position the text at a more comfortable viewing height.
- Enhances overall user experience by providing more control over the document's position in the editor window.

Thank you for considering this feature request.

**Comment by foreachthing** [comment]
You can already do that. It might be an advanced feature (you have to enable that in the preferences). Use the search for "scroll".

**Comment by octaeder** [comment]
The old overscroll did only scroll 50% past the end. The full overscroll was introduced here:

Changelog 4.5.2
change Adv. Editor option "Vertical Overscroll" to scroll last line to top (#2944)

A slightly better search/filter for this option is `overs` cause it's unique. With `scroll` you might end up with Internal PDF Viewer options (when it has been selected last time). The filter result is independent of the `Show Advanced Options` setting.

![image](https://github.com/texstudio-org/texstudio/assets/102688820/86a8b1d5-796f-4884-a2f2-1cd855f86b70)

**Comment by samer5301** [comment]
Thank you for the information. I wasn't aware that this functionality already exists. I appreciate your help.

I will go ahead and close this issue now.
