### ISSUE TITLE
Required program gswin32c not found in PATH

### ISSUE THREAD

**Issue by frankkunderwood** [texstudio-org/texstudio#3717]
### Environment
- TeXstudio: 4.8.1
- Qt: 6.7.1
- OS: Win10
- TeX distribution: texlive

### Actual behavior
Texstudio reprts that:
"epstopdf ($Id: epstopdf.pl 71584 2024-06-21 22:40:28Z karl $) 2.35 !!! Error: Required program gswin32c not found in PATH, which contains: 'd' '/work_program/texlive/2024/tlpkg/tlgs/bin;d' '/work_program/texlive/2024/tlpkg/tlperl/bin;C' '/WINDOWS/system32;C' '/WINDOWS;C' '/WINDOWS/System32/Wbem;C' '/WINDOWS/System32/WindowsPowerShell/v1.0/;C' '/WINDOWS/System32/OpenSSH/;C' '/Program Files/NVIDIA Corporation/NVIDIA NvDLISR;C' '/Program Files (x86)/NVIDIA Corporation/PhysX/Common;C' '/Program Files/gs/gs10.03.1/bin;C' '/Program Files (x86)/gs/gs10.02.0/bin;C' '/Users/ark/AppData/Local/Microsoft/WindowsApps;D' '/work_program/texlive/2024/bin/windows'
D:\work_program\texlive\2024\bin\windows\runscript.tlu:922: command failed with exit code 2: perl.exe d"

And then it can not convert eps figures to pdf.  However I do have installed Ghostscript in these paths as shown in the screenshot. Please help me where the problem is.

<img width="350" alt="1" src="https://github.com/texstudio-org/texstudio/assets/31367029/51a9642e-03be-4803-a0e4-69f0524096e4">
<img width="346" alt="2" src="https://github.com/texstudio-org/texstudio/assets/31367029/a7a828f6-d52f-46cb-ab39-6561fb14da90">

**Comment by sunderme** [comment]
txs reports the PATH it sees with "help/check latex installation" (env vars)

To debug your setup:
1) does it work when you call pdflatex from cmd.exe ?
2) does it work when you start txs from cmd.exe and then compile or whatever you do to call epstopdf ?

**Comment by frankkunderwood** [comment]
> txs reports the PATH it sees with "help/check latex installation" (env vars)
> 
> To debug your setup:
> 
> 1. does it work when you call pdflatex from cmd.exe ?
> 2. does it work when you start txs from cmd.exe and then compile or whatever you do to call epstopdf ?

It reports the same error when I call epstopdf from cmd. I have solved the problem by reinstalled the texlive in C:\texlive. It was previously installed in D:\work\texlive. I don't know if the problem is caused by not installing it in C or not installing it in the root directory.

**Comment by frankkunderwood** [comment]
> > txs reports the PATH it sees with "help/check latex installation" (env vars)
> > To debug your setup:
> > 
> > 1. does it work when you call pdflatex from cmd.exe ?
> > 2. does it work when you start txs from cmd.exe and then compile or whatever you do to call epstopdf ?
> 
> It reports the same error when I call epstopdf from cmd. I have solved the problem by reinstalled the texlive in C:\texlive. It was previously installed in D:\work\texlive. I don't know if the problem is caused by not installing it in C or not installing it in the root directory.

But I haven't installed it in the C root directory before, and I haven't had this problem.
