### ISSUE TITLE
FR: Propagate "citation" and "reference" syntax highlighting through macro definitions

### ISSUE THREAD

**Issue by jessexknight** [texstudio-org/texstudio#372]
### Feature Request:

I find myself writing wrapper macros for `\cite{}`, `\label{}`, and `\ref{}` commands in some situations, where the `{id}` of the cite / label / ref is exactly one of the macro arguments. It would be nice if this argument could be identified  (e.g. regex like `\\cite\{\#(\d.*?)\}`) and the sytnax highlighting for the cite / label / ref applied to the macro where it is used in the document.

Thanks,

### e.g. desired behavior:
```latex
\newcommand{\citefull}[1]{\citeauthor{#1}\ (\citeyear{#1})}
...
\cite{Ashburner2005} % <- "Ashburner2005" is highlighted as "citationPresent" here
\citefull{Ashburner2005} % <- but can we get that here too?
```

### Environment
- TeXstudio: 2.12.6
- Qt: ?
- OS: Linux (Ubuntu 16.04)
- TeX distribution: pdfTeX 3.14159265-2.6-1.40.19 (TeX Live 2019/dev/Debian)

**Comment by sunderme** [comment]
take a look into the manual/wiki on how cwl work and how to use them

**Comment by jessexknight** [comment]
Just jotting down solution for future users:

Auto-completion and highlighting in texstudio are managed through `.cwl` files.
The general format of a line-by-line entry in `.cwl` file is:
`<command>[#category]`
which, for latex in texstudio, looks like:
`\cite{keylist}#c`
which registers `\cite` as a valid command, provides `keylist` as the argument suggestion to the user, and categorizes this as a [**c**]ite command, for syntactic highlighting.

To add your own cwl entries:

0. explore the [default latex cwl file](https://sourceforge.net/p/texstudio/hg/ci/default/tree/completion/latex-document.cwl) to find category syntax, if you need it.
1. navigate to `[`[`texstudio-settings-directory`](https://sourceforge.net/p/texstudio/wiki/Frequently%20Asked%20Questions/#where-are-the-settings-stored)`]/completion/user`
2. create a file `user.cwl` (name doesn't matter), and add your cwl entries, each on a new line
3. open TeXstudio > Options > Configure > Completion. Look for `user.cwl` in the list, and check the box.
4. you may have to close and open TeXstudio to refresh the highlighting.

[related tex.stackexchange question](https://tex.stackexchange.com/questions/110539/where-does-texstudio-store-the-cwl-files-for-hyperref-and-xspace)
