### ISSUE TITLE
Auto compile executes even when disabled

### ISSUE THREAD

**Issue by jcasale** [texstudio-org/texstudio#3720]
### Environment
- TeXstudio: 4.8.1
- Qt: 6.7.1
- OS: Windows 11
- TeX distribution: miktex

### Expected behavior
With Internal PDF Viewer > Auto-recompile disabled, I expect the document not to recompile on its own.

### Actual behavior
When I drag the mouse cursor across a color used in a command (e.g., `\colorbox{LightGray}{\texttt{null}}`) the editor rebuilds a temporary random file.
![Screenshot 2024-07-04 152635](https://github.com/texstudio-org/texstudio/assets/9957114/7335b720-d340-42af-a735-3df08021aa81)
![Screenshot 2024-07-04 152946](https://github.com/texstudio-org/texstudio/assets/9957114/c04aeb7d-6c09-44df-a3d8-85ec143e1470)

### How to reproduce
Load the following document in TexStudio and build and view it. Then drag the mouse over the `LightGray` declaration in the document section. The editor will rebuild each time.

```Latex
\documentclass[letterpaper]{article}

\usepackage[sfdefault]{roboto}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[left=0.5in,right=0.5in,top=0.5in,bottom=0.65in]{geometry}
\usepackage[table,dvipsnames]{xcolor}

\definecolor{LightGray}{gray}{0.95}

\usepackage{ipsum}

\begin{document}

Lorem ipsum \colorbox{LightGray}{\texttt{null}} dolar.

\end{document}
```

**Comment by octaeder** [comment]
For this, option `Show image tooltip on image files` is used. It can be found in the Adv. Editor setup of the config dialog (simply use the options filter).

**Comment by jcasale** [comment]
Ahh, brilliant.

Thank you!
