### ISSUE TITLE
Do not automatically open previous files when opening the application

### ISSUE THREAD

**Issue by PeterTaylor2** [texstudio-org/texstudio#3722]

**Comment by PeterTaylor2** [comment]
Sometimes you were editing a large file - you open the application and it takes ages to open up. Don't do it. It is a stupid design decision.

**Comment by samcarter** [comment]
Have you tried to disable "Restore Previous Session at Startup" in the preferences?

**Comment by PeterTaylor2** [comment]
@samcarter - thanks for getting back so quickly - I couldn't see that option - but now I see that if I click "show advanced options" in Options | Configure TexStudio | General then that option appears - so I will close this thread with the suggestion that this option becomes more immediately visible

**Comment by octaeder** [comment]
Finding options: It is very simple and independent of the 'Show advanced options' setting: Enter the name of the option you are looking for in the filter field at the bottom left. It seems that this filter is regularly overlooked.

You may use `Cache documents for faster reopening`. But this has some restrictions (s. [manual](https://texstudio-org.github.io/background.html#loaded-documents)). Another way is using command line option `--no-session`.
