### ISSUE TITLE
TexStudio - the left sidebar displays abnormally on MacOS

### ISSUE THREAD

**Issue by tsingke** [texstudio-org/texstudio#3723]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior

The latest version of TexStudio displays issues on macOS. After launching TexStudio, the left sidebar displays abnormally, with all icons automatically expanded, resulting in an unappealing appearance. It is recommended to conduct in-depth design and improvements to the user interface.

**Comment by muzimuzhi** [comment]
May be similar to #3637.

**Comment by sunderme** [comment]
see also https://github.com/texstudio-org/texstudio/wiki/Known-Issues#osx

**Comment by sunderme** [comment]
assume duplicate #3637 , no feedback
