### ISSUE TITLE
Can't compile images in esp format correctly

### ISSUE THREAD

**Issue by KajiMaCN** [texstudio-org/texstudio#3725]
### Environment
- TeXstudio: TeXstudio 4.8.1 (git 4.8.1)
- Qt: Qt 6.7.1
- OS:  Windows10
- TeX distribution: TeX 3.141592653 (TeX Live 2023)

### Expected behavior
Inserting esp images doesn't load correctly and always reports an error:

main.tex: 错误: 118: Package pdftex.def Error: File `logo-eps-converted-to.pdf' not found: using draft setting.

It can only be compiled correctly by using the following command in CMD:
`pdflatex -shell-escape XXX.tex`

### Actual behavior
Converts and displays images correctly without having to execute commands from the command line.

### How to reproduce
Use images in esp format and compile them.

**Comment by sunderme** [comment]
have you set the command accordingly in txs ?

**Comment by sunderme** [comment]
any special reasons to use eps ?

**Comment by KajiMaCN** [comment]
> have you set the command accordingly in txs ?

I have kept the default commands in texStudio unchanged, in previous versions it was possible to convert esp files without additional settings.

**Comment by sunderme** [comment]
`-shell-escape` is not active by default.

**Comment by KajiMaCN** [comment]
> `-shell-escape` is not active by default.

You're right, but versions prior to 2023 are compiling and converting esp directly without additional setup, is TexStudio giving up on esp?

**Comment by sunderme** [comment]
in principle, it is a compilation issue, not an txs issue. 
txs just calls pdflatex with the options you specify.

That said, for image inclusion in pdf, png and pdf are way more efficient. Unless there are other reasons, there is absolutely no advantage in using eps.

**Comment by KajiMaCN** [comment]
> in principle, it is a compilation issue, not an txs issue. txs just calls pdflatex with the options you specify.
> 
> That said, for image inclusion in pdf, png and pdf are way more efficient. Unless there are other reasons, there is absolutely no advantage in using eps.

I definitely think you're right, but in some of the templates provided by journals, they provide some files in esp format, which leaves us with the task of converting the esp files. For example, IEEE TRANSACTIONS AND JOURNALS TEMPLATE, their file structure is shown in the figure:
![image](https://github.com/texstudio-org/texstudio/assets/28567261/33810bf9-88d7-40de-b049-52533191a4ed)

They provide the logo in esp format. Of course, there are many other journals that offer images in esp format. Considering that most people don't know how to set up the correct commands, I think it would save a lot of time for a lot of people if they could convert esp by default.

**Comment by sunderme** [comment]
indeed

**Comment by octaeder** [comment]
works for me with Win10, TeXstudio 4.8.2 (git 4.8.1-29-g8a3b2743f):

```latex
\documentclass[10pt]{article}
\usepackage{graphicx}
\pagestyle{empty}
\parindent0mm
\begin{document}
\includegraphics{image}
\end{document}
```
![image](https://github.com/texstudio-org/texstudio/assets/102688820/b288f608-93cc-469f-b59a-f9e6a5ca4e89)

![image](https://github.com/texstudio-org/texstudio/assets/102688820/6ecb04b7-1cf8-49f6-b5db-76775848fc59)

```
13:04:02 Process started: "C:\...\miktex\bin\x64\pdflatex.exe"  -synctex=1 -interaction=nonstopmode --shell-escape "exp".tex

13:04:02 Process exited normally
```

**Comment by KajiMaCN** [comment]
> indeed

Absolutely, you can search **Package pdftex.def Error: File `××-eps-converted-to.pdf' not found: using draft setting.** in Google or bing to find a lot of people with the same doubts.

**Comment by KajiMaCN** [comment]
> --shell-escape

As you can see from your command, `--shell-escape` has been automatically activated

**Comment by octaeder** [comment]
> As you can see from your command, --shell-escape has been automatically activated

No, I added this to the definition a long time ago because I use gnuplot. Now I tried it wihtout shell-escape and it works again (I removed all intermediate files before build):

```
13:26:40 Process started: "C:\...\MiKTeX\miktex\bin\x64\pdflatex.exe"  -synctex=1 -interaction=nonstopmode "exp".tex

13:26:41 Process exited normally
```

**Comment by octaeder** [comment]
This is the line in the options:

![image](https://github.com/texstudio-org/texstudio/assets/102688820/d325d8ad-2918-4fa4-8b2f-93993cb9d0a6)

**Comment by KajiMaCN** [comment]
> This is the line in the options:
> 
> ![image](https://private-user-images.githubusercontent.com/102688820/346270539-d325d8ad-2918-4fa4-8b2f-93993cb9d0a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNjYwMDIsIm5iZiI6MTcyMDI2NTcwMiwicGF0aCI6Ii8xMDI2ODg4MjAvMzQ2MjcwNTM5LWQzMjVkOGFkLTI5MTgtNGZhNC04YjJmLTkzOTkzY2I5ZDBhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQxMTM1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTVkOTFkNjFjMTliYzYwZjNhMzgyMTRjZDk5OTA3NTJhMWI3MjE4NjljM2RiNGQ4NTUxYTJiNDQ5MzRkNDMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ILe6Or8OnnjR7gG3GL4w4i9yEQweohz1AWZckZ20ym8)

![image](https://github.com/texstudio-org/texstudio/assets/28567261/cfb29f4b-a40a-4fe3-b871-d05766f5c9a5)
I have the same settings as you, which are the default settings for TexStudio, but it doesn't work for me. I don't know what is the reason.

**Comment by octaeder** [comment]
You may try my example. The image code is:
```
%!PS-Adobe-2.0 EPSF-2.0
%%BoundingBox: -15 -2 148 176

save

/f {-.6 mul 2.7182818 exch exp 4.5 mul} def % x => 4.5*e^{-.6x}
/tangent {-.6 mul 1 add 0 f mul} def % tangent to f in 0 , x => t(x)
/invtangent {0 f div 1 sub -.6 div} def % y => t^{-1}(y)

%graph builds path of the graph of f over [a,b] with resolution appx. dpi
%stack: name a b dpi => --
%example: /f 0 1 100 graph

/graph
{
   5 dict begin % use own dict. -> local variables !
   /dpi exch def /b exch def /a exch def load /func exch def
   b a sub 2.54 div dpi mul round cvi /numpoints exch def
   a dup func moveto
   1 1 numpoints {numpoints div b a sub mul a add % calc. x
                    dup func lineto
                 } for
   end % dicard dictionary
} def

/a 2.3 def /b 4.6 def % shaded area over [a,b]

72 2.54 div dup scale % now unitlength is 1cm

.017 setlinewidth
1 setlinecap
[] 0 setdash
0 setgray

% following lines: calc. graph of y=5*exp(-x/2) over [-0.5 , 5.0]

newpath /f -.5 a 300 graph stroke
newpath /f b 5 300 graph stroke
newpath /f a b 300 graph
gsave .9 setgray b 0 lineto a 0 lineto fill grestore
stroke

.9 setgray
0 a f moveto 0 invtangent dup a f lineto b f lineto 0 b f lineto fill
0 setgray

.01 setlinewidth

/tangent -.5 -.05 invtangent 1 graph stroke
-.05 a f moveto a .1 add a f lineto stroke % upper border of box
-.05 b f moveto b .1 add b f lineto stroke % lower border of box
0 invtangent dup -.05 moveto dup f .1 add lineto stroke %right border

%draw x-axis with arrow and scale

.025 setlinewidth

-.5 0 moveto 5 0 lineto stroke
1 1 4 {dup -.1 moveto 0 lineto stroke} for
5.2 0 moveto -.2 .05 rlineto 0 -.1 rlineto fill

%draw y-axis with arrow and scale

0 -.1 moveto 0 6 lineto stroke
1 1 5 {dup -.1 exch moveto 0 exch lineto stroke} for
0 6.2 moveto .05 -.2 rlineto -.1 0 rlineto fill

restore
```

**Comment by KajiMaCN** [comment]
> You may try my example. The image code is:
> 
> ```
> %!PS-Adobe-2.0 EPSF-2.0
> %%BoundingBox: -15 -2 148 176
> 
> save
> 
> /f {-.6 mul 2.7182818 exch exp 4.5 mul} def % x => 4.5*e^{-.6x}
> /tangent {-.6 mul 1 add 0 f mul} def % tangent to f in 0 , x => t(x)
> /invtangent {0 f div 1 sub -.6 div} def % y => t^{-1}(y)
> 
> %graph builds path of the graph of f over [a,b] with resolution appx. dpi
> %stack: name a b dpi => --
> %example: /f 0 1 100 graph
> 
> /graph
> {
>    5 dict begin % use own dict. -> local variables !
>    /dpi exch def /b exch def /a exch def load /func exch def
>    b a sub 2.54 div dpi mul round cvi /numpoints exch def
>    a dup func moveto
>    1 1 numpoints {numpoints div b a sub mul a add % calc. x
>                     dup func lineto
>                  } for
>    end % dicard dictionary
> } def
> 
> /a 2.3 def /b 4.6 def % shaded area over [a,b]
> 
> 72 2.54 div dup scale % now unitlength is 1cm
> 
> .017 setlinewidth
> 1 setlinecap
> [] 0 setdash
> 0 setgray
> 
> % following lines: calc. graph of y=5*exp(-x/2) over [-0.5 , 5.0]
> 
> newpath /f -.5 a 300 graph stroke
> newpath /f b 5 300 graph stroke
> newpath /f a b 300 graph
> gsave .9 setgray b 0 lineto a 0 lineto fill grestore
> stroke
> 
> .9 setgray
> 0 a f moveto 0 invtangent dup a f lineto b f lineto 0 b f lineto fill
> 0 setgray
> 
> .01 setlinewidth
> 
> /tangent -.5 -.05 invtangent 1 graph stroke
> -.05 a f moveto a .1 add a f lineto stroke % upper border of box
> -.05 b f moveto b .1 add b f lineto stroke % lower border of box
> 0 invtangent dup -.05 moveto dup f .1 add lineto stroke %right border
> 
> %draw x-axis with arrow and scale
> 
> .025 setlinewidth
> 
> -.5 0 moveto 5 0 lineto stroke
> 1 1 4 {dup -.1 moveto 0 lineto stroke} for
> 5.2 0 moveto -.2 .05 rlineto 0 -.1 rlineto fill
> 
> %draw y-axis with arrow and scale
> 
> 0 -.1 moveto 0 6 lineto stroke
> 1 1 5 {dup -.1 exch moveto 0 exch lineto stroke} for
> 0 6.2 moveto .05 -.2 rlineto -.1 0 rlineto fill
> 
> restore
> ```

Thanks for the example, but where should I use this code?

**Comment by sunderme** [comment]
1) miktex offers an option to activate `--shell-escape" for all runs (by default, should be off)
2) please run octaeders example with and without the command option `--shell-escape`
3) you need to present the logs from the pdflatex runs.

**Comment by sunderme** [comment]
> > You may try my example. The image code is:
> > ```
> > %!PS-Adobe-2.0 EPSF-2.0
> > %%BoundingBox: -15 -2 148 176
> > 
> > save
> > 
> > /f {-.6 mul 2.7182818 exch exp 4.5 mul} def % x => 4.5*e^{-.6x}
> > /tangent {-.6 mul 1 add 0 f mul} def % tangent to f in 0 , x => t(x)
> > /invtangent {0 f div 1 sub -.6 div} def % y => t^{-1}(y)
> > 
> > %graph builds path of the graph of f over [a,b] with resolution appx. dpi
> > %stack: name a b dpi => --
> > %example: /f 0 1 100 graph
> > 
> > /graph
> > {
> >    5 dict begin % use own dict. -> local variables !
> >    /dpi exch def /b exch def /a exch def load /func exch def
> >    b a sub 2.54 div dpi mul round cvi /numpoints exch def
> >    a dup func moveto
> >    1 1 numpoints {numpoints div b a sub mul a add % calc. x
> >                     dup func lineto
> >                  } for
> >    end % dicard dictionary
> > } def
> > 
> > /a 2.3 def /b 4.6 def % shaded area over [a,b]
> > 
> > 72 2.54 div dup scale % now unitlength is 1cm
> > 
> > .017 setlinewidth
> > 1 setlinecap
> > [] 0 setdash
> > 0 setgray
> > 
> > % following lines: calc. graph of y=5*exp(-x/2) over [-0.5 , 5.0]
> > 
> > newpath /f -.5 a 300 graph stroke
> > newpath /f b 5 300 graph stroke
> > newpath /f a b 300 graph
> > gsave .9 setgray b 0 lineto a 0 lineto fill grestore
> > stroke
> > 
> > .9 setgray
> > 0 a f moveto 0 invtangent dup a f lineto b f lineto 0 b f lineto fill
> > 0 setgray
> > 
> > .01 setlinewidth
> > 
> > /tangent -.5 -.05 invtangent 1 graph stroke
> > -.05 a f moveto a .1 add a f lineto stroke % upper border of box
> > -.05 b f moveto b .1 add b f lineto stroke % lower border of box
> > 0 invtangent dup -.05 moveto dup f .1 add lineto stroke %right border
> > 
> > %draw x-axis with arrow and scale
> > 
> > .025 setlinewidth
> > 
> > -.5 0 moveto 5 0 lineto stroke
> > 1 1 4 {dup -.1 moveto 0 lineto stroke} for
> > 5.2 0 moveto -.2 .05 rlineto 0 -.1 rlineto fill
> > 
> > %draw y-axis with arrow and scale
> > 
> > 0 -.1 moveto 0 6 lineto stroke
> > 1 1 5 {dup -.1 exch moveto 0 exch lineto stroke} for
> > 0 6.2 moveto .05 -.2 rlineto -.1 0 rlineto fill
> > 
> > restore
> > ```
> 
> Thanks for the example, but where should I use this code?

That code is the eps file content.

**Comment by sunderme** [comment]
what was the solution ?
