### ISSUE TITLE
Add self-hosted AI api accessible on local network

### ISSUE THREAD

**Issue by colichri** [texstudio-org/texstudio#3726]
### Describe the feature and the current behavior/state
With the addition of the AI Chat feature, only OpenAI, Mistral and the self-hosted (on your local machine) LLM are available options to choose from. In my company we have a self hosted LLM based on chatgpt in our Cloud for security reasons. 

To make use of it in TeXstudio, I need to state my credentials and server address somewhere, which is still yet to be an available option in the drop-down menu. 
### Who will benefit with this feature?
Like users who already use AI features, users that have special business requirements for data security can use their own LLMs aside from the three beforementioned options.

### Any Other info
The model I'd like to use is a gpt-4o model hosted in an azure environment.

**Comment by sunderme** [comment]
implemented, can't test, please check with current dev build
