### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by MysaaJava** [texstudio-org/texstudio#3730]
I was just moving with the mouse between files.
Four files were open "header.tex","M2Report.tex","header-test.tex","test.tex".
I changed tab to "header.tex", and then i selected (with mouse) the line "\usepackage{autofe}".
Then i pressed backspace to delete it, and crash.

Texstudio proposed to recover, i did recover and it crashed again when i tried to edit the second line.
I recovered again, and modified other lines than the first or second, it worked. I modified the second line, it crashed.

I stopped texstudio and started it again, and it was not crashing anymore.

### Environment
- TeXstudio: TeXstudio 4.8.1 (git 0.0.0++)
- Qt: Using Qt Version 5.15.13, compiled with Qt 5.15.13 R
- OS: Ubuntu 24.04 LTS -- Linux 6.8.0-38-generic #38-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  7 15:25:01 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- TeX distribution: texlive-full package (i think it is unrelated)

### How to reproduce
I did not find how to reproduce it :(

I am joining the backtraces of the different crashes that happened. They all happened during the same texstudio session (no restart)
[texstudio_backtrace1.txt](https://github.com/user-attachments/files/16196805/texstudio_backtrace1.txt)
[texstudio_backtrace2.txt](https://github.com/user-attachments/files/16196806/texstudio_backtrace2.txt)
[texstudio_backtrace3.txt](https://github.com/user-attachments/files/16196807/texstudio_backtrace3.txt)
[texstudio_backtrace4.txt](https://github.com/user-attachments/files/16196808/texstudio_backtrace4.txt)
[texstudio_backtrace5.txt](https://github.com/user-attachments/files/16196809/texstudio_backtrace5.txt)
[texstudio_backtrace6.txt](https://github.com/user-attachments/files/16196810/texstudio_backtrace6.txt)

I can conduct other tests if you want.
Here is the faulty file, converted to txt, and the recover file:
[header.txt](https://github.com/user-attachments/files/16196861/header.txt)
[header.tex.recover.bak~.txt](https://github.com/user-attachments/files/16196873/header.tex.recover.bak.txt)

**Comment by sunderme** [comment]
any chance that "header.tex" was included in two open tex files ?

**Comment by MysaaJava** [comment]
I think it was opened in two files (M2report.tex and test.tex), and i removed the depedency from test.tex (i removed the include) and after the depedency was removed, i had the segfault

**Comment by sunderme** [comment]
I have played around with two root documents to the same header, but I get no crash.
Can you try to reproduce the issue ?

**Comment by sunderme** [comment]
can you provide your complete files ?

**Comment by sunderme** [comment]
I have found and fixed "a" crash.
Can you try out the latest dev build ? (https://github.com/texstudio-org/texstudio/actions/runs/11129741620)

**Comment by sunderme** [comment]
assume fixed
