### ISSUE TITLE
wrong keyval syntax checking with multiple optional arguments

### ISSUE THREAD

**Issue by mbertucci47** [texstudio-org/texstudio#3732]
### Environment
- TeXstudio: 4.8.1
- Qt: 6.7.1
- OS: Windows

### Actual behavior
If a command has multiple optional arguments, say of the form `\mycmd[opt1]{arg1}[opt2]{arg2}` where `[opt1]` and `[opt2]` can be omitted, and `opt1` is a keyval argument, then the syntax highlighter tries to check `opt2` for keyvals if `[opt1]` is not present.

If `opt2` is the keyval argument, then the syntax checking is correct.

### How to reproduce
Example cwl file:
```
# mypkg.cwl

\mycmd{arg1}{arg2}
\mycmd{arg1}[opt2]{arg2}
\mycmd[opt1%keyvals]{arg1}{arg2}
\mycmd[opt1%keyvals]{arg1}[opt2]{arg2}

#keyvals:\mycmd
mykey
#endkeyvals

\mycmdtwo{arg1}{arg2}
\mycmdtwo{arg1}[opt2%keyvals]{arg2}
\mycmdtwo[opt1]{arg1}{arg2}
\mycmdtwo[opt1]{arg1}[opt2%keyvals]{arg2}

#keyvals:\mycmdtwo
anotherkey
#endkeyvals
```
Example tex file:
```tex
\documentclass{article}
\usepackage{mypkg}

\begin{document}

\mycmd{arg1}{arg2}
\mycmd{arg1}[whatever goes here]{arg2}
\mycmd[mykey]{arg1}{arg2}
\mycmd[mykey]{arg1}[whatever goes here]{arg2}

\mycmdtwo{arg1}{arg2}
\mycmdtwo{arg1}[anotherkey]{arg2}
\mycmdtwo[whatever goes here]{arg1}{arg2}
\mycmdtwo[whatever goes here]{arg1}[anotherkey]{arg2}

\end{document}
```

<img width="334" alt="syntax-highl" src="https://github.com/user-attachments/assets/2661aa6d-924d-4ad6-8838-23f4c0d74e57">

**Comment by sunderme** [comment]
currently txs just counts down arguments/optional arguments
Positions are not considered. A fix needs some more code change.

**Comment by sunderme** [comment]
is there an example for this in the cwl files. i.e. optional/mandatory/optional ?

**Comment by muzimuzhi** [comment]
https://github.com/texstudio-org/texstudio/blob/670bc06f34c7cd1663a74694872437a5fba4c948/completion/fontspec.cwl#L29
