### ISSUE TITLE
error message in saving files. 

### ISSUE THREAD

**Issue by piapiaux** [texstudio-org/texstudio#3736]
just installed latest version of Texstudio 4.8.1. OS14.5.
Each time, when i closed off the file, there is an error message popped up: 

storing session information into /users/myname/.config/texstudio/lastsession.txss2 failed. file exists but is not writeable.

i tried to follow some suggestions online. But i could not locate such a file in the mac book air. 
what are the options to solve the porblem?

**Comment by muzimuzhi** [comment]
To locate to hidden folders: Open Finder.app, press Cmd + Shift + G (or use the menu Go - Go to folder...), then enter "~/.config".

But your problem seems like texstudio doesn't have write permission in that folder or to that file.

**Comment by piapiaux** [comment]
yes, I managed to creat a new folder texstudio under .config  
but the problem persists.

**Comment by sunderme** [comment]
Osx restricts file access to some apps. You need to check that txs has write access.

**Comment by sunderme** [comment]
no feedback, OSX file access restriction ?

**Comment by Cheeseofneo** [comment]
change the folder property of ~/.config using "chmod" and "chown"

**Comment by alessandropeca** [comment]
I have the same issue, any updates?

**Comment by Ronchy2000** [comment]
@Cheeseofneo provides insight  ideas!
I asked chatGPT ,then I solved it.
1. open termimal, `cd ~/.config`, then `sudo mkdir texstudio`
2. `sudo chmod -R 755 /Users/ronchy2000/.config/texstudio`
3. `sudo chown ronchy2000:staff /Users/ronchy2000/.config/texstudio`
4. reopen texStudio app, it works!
tips: plz change your own path replace the `ronchy2000`

**Comment by Ronchy2000** [comment]
> I have the same issue, any updates?
you can try the answer I pushed, any questions plz.

**Comment by bslchokr** [comment]
> [@Cheeseofneo](https://github.com/Cheeseofneo) provides insight ideas! I asked chatGPT ,then I solved it.
> 
> 1. open termimal, `cd ~/.config`, then `sudo mkdir texstudio`
> 2. `sudo chmod -R 755 /Users/ronchy2000/.config/texstudio`
> 3. `sudo chown ronchy2000:staff /Users/ronchy2000/.config/texstudio`
> 4. reopen texStudio app, it works!
>    tips: plz change your own path replace the `ronchy2000`
>    ![image](https://github.com/user-attachments/assets/06bf6f38-026b-42a5-b4c9-97e44bde4fb4)

I had the same issue and this solution worked, make sure to use your own user path name

**Comment by alessandropeca** [comment]
I also used the solution provided by @Cheeseofneo on my mac-m3, it works!
