### ISSUE TITLE
unuseable slow scrolling in pdf previewer

### ISSUE THREAD

**Issue by capnahab** [texstudio-org/texstudio#3737]
I am using Texstudio on Mac (Macpro M2 ultra , 192GB RAM) 
Version is 4.8.0
Using Qt Version 6.7.0, compiled with Qt 6.7.0 R

For the last few versions the scrolling of the pdf viewer has been unuseably slow for any document longer than 1 page. This has been across several upgrades. 

I have searched for solutions and apart from a brief mention on reddit very little out there.

**Comment by octaeder** [comment]
This seems to happen very rare. Let's see what other information might be useful here:
- do you use default settings of options?
- which build do you use (pdflatex, ...)?
- what is the source of a minimum example to reproduce (maybe without use of any packages)?
- have you checked version 4.8.1?

**Comment by pizdjuk** [comment]
I think this is a Qt6 issue, https://github.com/Nheko-Reborn/nheko/issues/1527

**Comment by sunderme** [comment]
no feedback
