### ISSUE TITLE
How can I retrieve information when open the file in texstudio.

### ISSUE THREAD

**Issue by SSR1012-GIT** [texstudio-org/texstudio#3738]
How can I retrieve information when open the file in texstudio. I have tried to create Qt (Javascript codings) but not achieved.

I am requesting to get the file open time and close time in the TexStudio.

Thanks,

**Comment by sunderme** [comment]
you are asking about event triggers in macros ? https://texstudio-org.github.io/advanced.html#event-triggers

**Comment by sunderme** [comment]
no feedback
