### ISSUE TITLE
TeX Studio crashes when adding a word to dictionary

### ISSUE THREAD

**Issue by e-dervieux** [texstudio-org/texstudio#3739]
### Environment
- TeXstudio: 4.6.3
- Qt: 6.5.2
- OS: MacOS 14.2.1 (MacBook Pro M2 Pro 2023)
- TeX distribution: TeX Live 2023

### Expected behaviour

Right-clicking a word and clicking "Add to Dictionary" should add the word to the dictionary.

### Actual behaviour

TeX Studio crashed without any error message.

### How to reproduce

This is not easily reproducible. It happened to me several times though, it seems to be random.

**Comment by e-dervieux** [comment]
**Of note:** the word that caused the crash is in deed added to the dictionary.

**Comment by sunderme** [comment]
First step: use current version of txs with m1 binary

**Comment by e-dervieux** [comment]
Yep, I just switched to latest, I'll keep you posted if it happens again. Of note, I recall it happened some 2-years ago on a 2017 Intel MacBook Pro (Catalina OS perhaps, not sure).

**Comment by sunderme** [comment]
I close this for, please open it up, when it comes up again (or better, there is a reproducible test case)
I have never seen it crash there. I am not often adding words, but it happens...

**Comment by e-dervieux** [comment]
I think this has been solved. Been using 4.8.1 for several weeks now, spent hours daily and added maybe 10 words to the dictionary without problem.
