### ISSUE TITLE
Preferences are not saved when TeX Studio crashes

### ISSUE THREAD

**Issue by e-dervieux** [texstudio-org/texstudio#3740]
### Environment
- TeXstudio: 4.6.3
- Qt: 6.5.2
- OS: MacOS 14.2.1 (MacBook Pro M2 Pro 2023)
- TeX distribution: TeX Live 2023

When changing something into the "Preferences" menu, it seems to be saved to a temporary location and only saved definitively when TeX Studio is properly closed. In case of a crash, all changes are lost, even if the crash occurs hours after the change in the preferences. The same is true for currently opened files: when TeX Studio crashes, it does not open the files that were opened when it crashed. Instead the files that were opened at the last properly-terminated Tex-Studio run are opened. This is quite annoying as some changes to the compilation toolchain may be significant...

### Expected behaviour

In case of a crash, the file which were opened when the crash occurred should reopen, the preferences should also have been saved.

### Actual behaviour

None of the above.

### How to reproduce

This is not easily reproducible, since it needs TeX Studio to crash, which is not **that** easy to do (it's not Inkscape after all ^^).

**Comment by octaeder** [comment]
Changing options should not be a common task. Same for txs crashes. But in case a changed option together with other circumstances always leads to a crash, then saving options immediately may prevent starting txs again. This would be much more harmful.

**Comment by sunderme** [comment]
I rather agree with the issuer that directly saving options sounds valid.
Sessions however not necessarily.

**Comment by sunderme** [comment]
The argument that you can cancel a change by killing txs is a rather dirty trick. It probably better to use profiles for that.
