### ISSUE TITLE
Not Loading Complete Package on win-11 ( only the exec )

### ISSUE THREAD

**Issue by HenryMakowitz** [texstudio-org/texstudio#3742]
it should take four hours or so to download complete TexStudio Package
Only downloads and installs exec. 20 sec or so.  When I import and run a
TexStudio file it does not run correctly. However this file runs fine on another
machine and win version ( Ver 4-7-3-win ).

**Comment by sunderme** [comment]
I don't understand what is reported here ?

**Comment by muzimuzhi** [comment]
> it should take four hours or so to download complete TexStudio Package

Seems your Internet connection is slow, or are you describing downloading the complete TeX Live ISO image, like [texlive2024.iso](https://mirrors.ctan.org/systems/texlive/Images/texlive2024.iso)?

**Comment by sunderme** [comment]
no feedback
