### ISSUE TITLE
TXS always opens file in new instances

### ISSUE THREAD

**Issue by ysalmon** [texstudio-org/texstudio#3743]
### Environment
- TeXstudio: 4.8.1
- Qt: 5.15.3
- OS: KUbuntu 22.04
- TeX distribution: texlive

### Expected behavior
When opening ``.tex`` from the File manager or by invoking ``texstudio bla.tex`` from the command line, an already running instance of TXS should open the file in a new tab.

### Actual behavior
Each invocation starts a new TXS instance. This seems to happen since a recent update.

### How to reproduce
For example, run ``texstudio somefile.tex`` twice.

Note that opening a file using TXS GUI still correctly opens the file within that instance, and running ``texstudio file1.tex file2.tex`` still creates one instance that opens both files.

**Comment by sunderme** [comment]
works fine on Ubuntu 22.04 (lxqt)

**Comment by sunderme** [comment]
and it works with ubuntu 22.04 plasma (KDE)

**Comment by ysalmon** [comment]
Thank you for checking. I have two different machines that exhibit this behaviour.

I rolled back to 4.2.1 and that version does work. 4.8.2 from the nightly ppa has the same problem as 4.8.1.

From the main PPA, I got the 4.7.2 version (built for 23.04, but installs on my system) and it works properly.

So I really think there is something weird going on. How can I bisect or trace this more precisely ?

**Comment by sunderme** [comment]
you can build txs from source/git, description in [wiki](https://github.com/texstudio-org/texstudio/wiki/Compiling)

qtsingleapplication has been untouched for a very long time, so I doubt it directly plays a role.

**Comment by ysalmon** [comment]
OK, I tracked it down :

 - commit 4160496d450d6e100142f7db5508ba7f0d88507e works
 - commit 495a49a03b0444f0e47e34003e4abb73670f6e03 does not, so it seems to have introduced that regression.

**Comment by sunderme** [comment]
The given commit does not change anything about the single application interface, so I fail to see what should be wrong (and it works here as on windows)

**Comment by ysalmon** [comment]
I tracked it down to two lines of code. I too do not understand why they have this impact ; I also do not know what they are intended for, but at least in the latter you will be more knowledgeable ;-) !

**Comment by ysalmon** [comment]
I have been trying to hardcode some paths for ``setRootPath`` and this is weird : the bug seems to trigger only when the path is ``/tmp``.

Can you reproduce this on your system, with files eg. ``/tmp/a.tex`` and ``/tmp/b.tex`` ?

**Comment by sunderme** [comment]
How do you end up with files in /tmp in the first place ?

**Comment by ysalmon** [comment]
When doing some tests, eg. to report a bug, or while trying to help a colleague finding out why his code does not work as he intends, I will usually have files in ``/tmp``. This is also where my browser and mail client put downloaded files and attachments unless specified otherwise.

**Comment by sunderme** [comment]
with `/tmp/a.tex` and `/tmp/b.tex`, no issue

**Comment by sunderme** [comment]
qt6 shows the same behavior

**Comment by ysalmon** [comment]
I have been able to test other mountpoints, on a system where ``/opt``, ``/home`` are all different mounts, and no, the problem seems to only arise with ``/tmp`` (not a subfolder of ``/tmp``).

More precisely, TXS seems incapable of transferring the opening of a file (from the desktop) to an existing instance if that instance previously has opened a file in ``/tmp`` : a new, full instance will spawn instead, and that new instance will manage successive opens (until another one is in ``/tmp``).

Maybe this is related to QtSingleApplication spawning network sockets in ```/tmp``.

It is claimed [somewhere](https://stackoverflow.com/a/34799562) that QtSingleApplication is obsolete, but I am incompetent in these matters.

**Comment by sunderme** [comment]
can you release the pull request, so that the work-around can be taken into txs ?
