### ISSUE TITLE
After changing an open file there are two undo steps available in a special case

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3744]
### Environment
- TeXstudio: 4.8.0
- Qt: 6.7.0
- OS: Windows(10)
- TeX distribution: miktex

### Expected behavior
After a single change there should be only one undo step available that brings the file back to unchanged state (s. Editor tab).

### Actual behavior
Open a root file and one of its includes files. The included file shows as unchanged in Editor tab. A disc icon appears in the tab after a change of text in the included file. Pressing `Ctrl+Z` removes the change and the icon. Using `Ctrl+Z` again marks the file as changed again even so no change is there. This does not happen with the root document.

![image](https://github.com/user-attachments/assets/2df97f94-b7d8-4424-ab79-2e394bdf0215) first change

![image](https://github.com/user-attachments/assets/da8c1b56-0d27-416e-92e5-6dad9313a7ab) first undo

![image](https://github.com/user-attachments/assets/14f19d43-109a-49c0-960c-38dcb5766e68) second undo

### How to reproduce
as said above

```latex
% test.tex
\documentclass{article}
\usepackage{mathtools}
\begin{document}
\input{a1}
$\sqrt{2}$
\end{document}
```
```
% a1.tex
\section{root inline}\label{sec:root-inline}
$\sqrt{2}$
```

**Comment by sunderme** [comment]
not reproducible on linux. Special settings ? Anything noteworthy ?

**Comment by octaeder** [comment]
I retested after deleting profile. Since TeXstudio 4.8.2 (git 4.8.2alpha3-20-gc3861b192) Qt 6.7.2 (msys2 build) wasn't able to create a profile (is this normal? you know there has been a change -- immediate saving of options), I started 4.8.2 (installed version) without tabs, ended it and started my latest build. Same behavior.

**Comment by octaeder** [comment]
This is what exactly happens: I remove `%appdata%/texstudio`, then start my txs build `./texstudio.exe` from msys2 cmd line. After this, folder `%appdata%/texstudio` is created and contains only two things: The folders `completion` and `templates` (these contain some other folders but no files). The main problem is the following message:

![image](https://github.com/user-attachments/assets/4c10cccd-1abf-4e8f-b9eb-63e68266f3ea)

Currently I can't tell, if this is a normal behavior or a new one.

**Comment by sunderme** [comment]
In order to avoid ambiguity, can you try out 4.8.3alpha4 ?

**Comment by octaeder** [comment]
undo issue still happens here:

![image](https://github.com/user-attachments/assets/b68f5800-7463-495b-8041-a54cd0b5ef3c)

I'll open an issue regarding the profile issue if necessary.
