### ISSUE TITLE
Automatically change/cycle the environment from math to align.

### ISSUE THREAD

**Issue by pizdjuk** [texstudio-org/texstudio#3745]
Very often I use the math environment, and then after some time it turns out, that the environment needs to be referred and changed from math \\[\\] to \begin{align}\end{align}

It is annoying to switch it by hands and I wrote some script. But I'm a beginner and don't know if the script could be written better.

```
function find_env_lastline(curr, str) {
	for (let i = curr; i<= curr+20 && i < editor.document().lineCount(); i++) {
		col = editor.text(i).search(str);
		if (col >= 0) {
			return [i, col];
		}
	}
}

function find_env_firstline(curr, str) {
	for (let i = curr; i >= curr-20 && i >= 0; i--) {
		col = editor.text(i).search(str);
		if (col >= 0) {
			return [i, col];
		}
	}
}

function math_to_align(curr) {
	[line2, col2] = find_env_lastline(curr, '\\\]');
	[line1, col1] = find_env_firstline(curr, '\\\[');
	curs = new QDocumentCursor(editor.document(), line1, col1-1, line1);

	curs.replaceSelectedText('\\begin{align}');
	delete curs;
	curs = new QDocumentCursor(editor.document(), line2, col2-1, line2);
	curs.replaceSelectedText('\\end{align}');
	delete curs;

//	cursor.beginEditBlock();
//	cursor.eraseLine();
//	cursor.insertLine();
//	cursor.moveTo(line1, col1-1);
//	editor.insertText('\\begin{align}');
//	cursor.moveTo(line2, col2-1);
//	editor.insertText('\\end{align}');
//     cursor.endEditBlock();
}

function align_to_math(curr) {
	[line2, col2] = find_env_lastline(curr, 'end{align}');
	[line1, col1] = find_env_firstline(curr, 'begin{align}');
	curs = new QDocumentCursor(editor.document(), line1, col1-1, line1);

	curs.replaceSelectedText('\\\[');
	delete curs;
	curs = new QDocumentCursor(editor.document(), line2, col2-1, line2);
	curs.replaceSelectedText('\\\]');
	delete curs;
}

currenv = editor.document().getLastEnvName(cursor.lineNumber());
if (currenv == 'math') {
	math_to_align(cursor.lineNumber());
}

if (currenv == 'align') {
	align_to_math(cursor.lineNumber());
}
```

The problems I encountered:

- it is not easy to select and replace text. I needed to create a new cursor object for that.
- I did not found how to delete part of a line
- something was wrong with escaping as you can see in line ```[line1, col1] = find_env_firstline(curr, 'begin{align}');``` I did not found a good solution and simply tried without escaping of '\\'
- it would be a good feature to can just replace a line with other like editor.text(linenum) = 'some new line of text'
- because of creating new cursor objects it was not possible for me to mark begin and end of editing blocks.

**Comment by sunderme** [comment]
just a side note, my handling of the situation without any scripts would be.
Select the equation (if need be with idefix/parenthesis/select outer)
type alig and complete env (ctrl+shift+space)
remove the \[/\] by placing the cursor before \[ and press alt+del.

**Comment by pizdjuk** [comment]
Thanks! Didn't know about alt+del :)
And I found a problem in a script. It can fail if there is nested align environments, even if its not allowed by LaTeX, it could happen. How can I get the first and last line of an active environment?

**Comment by sunderme** [comment]
there is no automatism available for macros.

**Comment by octaeder** [comment]
When using packages amsmath/mathtools then it's quite convenient to use the equation env. The equation* env is equivalent to `\[...\]`. Thus it's easy to switch to align env when you find that your formula needs a line break. Click on the env name, wait a short while and a mirror-cursor appears. Now changing the name will change the name in `\begin`and `\end` simultaneously.

**Comment by tmelorc** [comment]
> just a side note, my handling of the situation without any scripts would be. Select the equation (if need be with idefix/parenthesis/select outer) type alig and complete env (ctrl+shift+space) remove the `\[/\]` by placing the cursor before `\[` and press alt+del.

I'm using
```
TeXstudio 4.8.2 (git 4.7.1-420-g6872e90d1)
Using Qt Version 5.15.3, compiled with Qt 5.15.3 R
```
on Linux Mint 21.2 but the `Alt+Del` shortcut does not work. 
It is set in the txs Shortcuts panel but nothing happens.

Do you know why?

**Comment by pizdjuk** [comment]
Txs 4.8.1, Alt+Del works
