### ISSUE TITLE
Doesn't recognise packages imported through a .sty file

### ISSUE THREAD

**Issue by samrobbins85** [texstudio-org/texstudio#375]
### Environment
- TeXstudio: VERSION 2.10.10	
- Qt: 5.11.2 
- OS: Linux (Arch)
- TeX distribution: texlive

### Expected behavior
When using a .sty file to import the same packages for many files, the packages in that file should be recognised by the autocomplete and should not be highlighted as an unrecognised command.

### Actual behavior
Autocomplete doesn't suggest commands provided by the packages in the .sty file and highlights them red as unrecognised commands

### How to reproduce
Have a format.sty file with \usepackage{amssymb} and in the .tex file have the command \usepackage{format}.

When trying to put in \geqslant it will not be suggested and highlighted red when typed.

However, adding \usepackage{amssymb} to the .tex file will allow \geqslant to be inserted through autocomplete and will no longer be highlighted red

**Comment by sunderme** [comment]
please take a look at our [wiki](https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions#why-does-texstudio-mark-a-command-as-unrecognized)
