### ISSUE TITLE
The window of TexStudio is not maximized to the window of OS

### ISSUE THREAD

**Issue by schaidee** [texstudio-org/texstudio#3754]
### Environment
- TeXstudio: 4.8.1 
- Qt: 
- OS: Mac Sonoma 14.5 (MacBook Pro M1 16 GB)
- TeX distribution: texlive

### Expected behavior
As usual, the TexStudio window was fitted to the frame.

### Actual behavior
When I scroll the text window, it is fine. The problem happens when I scroll the preview tab.
After I scrolled the preview tab, the size of the TexStudio window changed, so I could not zoom in or zoom out of the preview panel.

Before that, I used the old version of TexStudio for a long time (4.0.2).
After I updated the new one, it seems that the bug happened, as shown in the attached VDO.
I think that the bug is similar to #3653.

https://github.com/user-attachments/assets/6f8f4ab6-e72b-4bd1-8fdb-2c0c3dda6945

**Comment by sunderme** [comment]
No feedback
