### ISSUE TITLE
Qt Platform plugin could not be initialized

### ISSUE THREAD

**Issue by Norschmann** [texstudio-org/texstudio#3755]
TexStudio till version 4.7.3 are running fine. Upgrade to any 4.8.X version the application won't starts and give the Error out: "This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem. 
Available platform plugins are: windows."

It does not matter if I use the portable version or the installed version of TexStudio. 

### Environment
- TeXstudio: Portable 4.8.1
- Qt: 
- OS: Win11 23H2 (Build 22635.3672)
- TeX distribution: miktex2.9 

### Expected behavior
Normal start.

### Actual behavior
![grafik](https://github.com/user-attachments/assets/6803e3d1-ea22-4d24-9246-f42680cad8e1)

### How to reproduce
Just start Texstudio

**Comment by sunderme** [comment]
"just start texstudio" and it does (current win11)

**Comment by Norschmann** [comment]
And the error message shows up. On TexStudio 4.7.3 no problem with starting the executable, it runs perfectly fine. On TexStudio 4.8.X as soon as I doubleclick on TexStudio.exe it shows the Error message. No Qt platform could be initialized.

**Comment by octaeder** [comment]
Note: The words `this application failed to start because no qt platform plugin could be initialized` seem to be asked quite often in Google search. While the txs build for win11 should use qt6, the search results refer to qt5.

Maybe update vsr?  \`On win11, visual studio runtime is required. See [here](https://github.com/texstudio-org/texstudio/issues/2664) ...\`

**Comment by Norschmann** [comment]
Visual Studio runtime is up to date. I just checked it. I only wonder why is there a problem. Same machine 4.7.3 runs fine but fails to start 4.8.X

**Comment by sunderme** [comment]
have you tried the installed version of txs ?
Compilation on the computer ?

**Comment by Norschmann** [comment]
Yes, I tried different installed version of Texstudio all 4.8.X are giving me the same result. No I did not compile on my computer.

**Comment by sunderme** [comment]
is `QT_PLUGIN_PATH`set ?

**Comment by sunderme** [comment]
and could you try https://forum.qt.io/topic/118817/could-not-find-the-qt-platform-plugin-windows/2

**Comment by Norschmann** [comment]
The QT_PLUGIN_PATH is set to C:\Program Files\MiKTeX 2.9\miktex\bin\x64,
I set it to 1 and TexStudio now starts fine. Thank you!

**Comment by sabertoaster** [comment]
> The QT_PLUGIN_PATH is set to C:\Program Files\MiKTeX 2.9\miktex\bin\x64, I set it to 1 and TexStudio now starts fine. Thank you!

Confirmed working with newest version texstudio 4.8.9 

<img width="1642" height="1025" alt="Image" src="https://github.com/user-attachments/assets/50bb3144-9e15-49cf-ba10-794063f909a6" />
