### ISSUE TITLE
loaded file doesn't work

### ISSUE THREAD

**Issue by parpamgr** [texstudio-org/texstudio#3757]
### Environment
- TeXstudio:   4.7.3
- Qt:  Qt 6.6.2.R
- OS: Windows(11)
- TeX distribution:  miktex

### Expected behavior
rv(X):=(X[1])[1]; /* for  matrix  X([a],[b]); */
should return  a

### Actual behavior
Does not work when the definition is in a file of functions which is loaded.
But does work when declared in the actual work sheet.

### How to reproduce
Try it yourself

**Comment by muzimuzhi** [comment]
Could you please elaborate further? The snippet `rv(X):=(X[1])[1]; /* for matrix X([a],[b]); */` you posted doesn't look like (La)TeX.

**Comment by sunderme** [comment]
no feedback

**Comment by parpamgr** [comment]
I am sorry and apologise. It was mistakenly addressed to texstudio. It
concerned an error I made in maxima. Many apologies. Paris Pamfilos

Στις Παρ, 16 Αυγ 2024, 14:28 ο χρήστης sunderme ***@***.***>
έγραψε:
