### ISSUE TITLE
Integrate git tools for version control

### ISSUE THREAD

**Issue by Jack251970** [texstudio-org/texstudio#3758]
#### Feature Request
Integrate Git tools directly within TexStudio for seamless version control of LaTeX projects. This integration should allow users to perform common Git operations (such as commit, push, pull, branch management, and viewing diffs) without leaving the TexStudio interface.

#### Current Behavior/State
I do version control almost exclusively by compressing the project into a zip file, which makes it difficult to compare versions. Maybe I can use Git command-line tools to manage version control, which can be cumbersome and disrupt the workflow, especially for those who prefer a more integrated development environment. 

#### Researchers and Academics

Frequently working with complex LaTeX documents, they often require version control to manage changes and track the history of their documents. Also, for those who are new to LaTeX or Git will find it easier to manage their projects within a single interface, reducing the learning curve and potential for mistakes.

#### Collaborative Teams

Teams working on joint LaTeX documents would benefit from easier collaboration and conflict resolution directly within TexStudio.

#### Suggested Implementation

The integration could include a simple Git sidebar or panel within TexStudio, offering essential Git operations with intuitive GUI controls. Advanced users could have access to a command palette for more complex Git commands.

#### User Interface

Visual indicators (e.g., color-coded file names) to show the status of files, tables, and figures (modified, staged, etc.) would be helpful, along with a built-in diff viewer to compare changes between commits.

**Comment by muzimuzhi** [comment]
There is already some basic support, see https://texstudio-org.github.io/advanced.html#git-svn-support.

Similar issues:
- https://github.com/texstudio-org/texstudio/issues/59
- https://github.com/texstudio-org/texstudio/issues/340
- https://github.com/texstudio-org/texstudio/issues/1588
- https://github.com/texstudio-org/texstudio/issues/3541

**Comment by Jack251970** [comment]
Thank you for your reply. I haven't notice this option in TexStudio! 😢
