### ISSUE TITLE
The file icon in the sidebar looks not good in dark mode

### ISSUE THREAD

**Issue by tercelxy** [texstudio-org/texstudio#3759]
### Describe the feature and the current behavior/state

In dark mode, the white background of the file icon in the sidebar is inconsistent with other icons (see the picture attached). Can it be adjusted to a more appropriate icon?
![file_icon](https://github.com/user-attachments/assets/19501f20-fbb6-45be-86d4-9941e57a7670)

My appearance setting: 
- TeXstudio version: 4.8.1
- Style: Adwaita Dark (txs)
- Color Scheme: Classic
- Icon Theme: Colibre

**Comment by foreachthing** [comment]
Same issue with other settings:
 
![image](https://github.com/user-attachments/assets/72220a36-b1a9-4cc9-9c86-a9865692d7d7)

This is in Windows 11.

**Comment by sunderme** [comment]
fixed
