### ISSUE TITLE
update for LaTeX Reference available

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3764]
you may want to provide latest reference with next version of txs, s.
[https://www.ctan.org/ctan-ann/id/mailman.8752.1715708467.3764.ctan-ann@ctan.org](https://www.ctan.org/ctan-ann/id/mailman.8752.1715708467.3764.ctan-ann@ctan.org)

**Comment by sunderme** [comment]
a pull-request would be nice
