### ISSUE TITLE
Texstudio in fullscreen crashes when external display is disconnected (MAC)

### ISSUE THREAD

**Issue by Spiros713** [texstudio-org/texstudio#3767]
When I have TexStudio in FullScreen mode while my laptop (Mac) is connected to an external display and the lid is closed, if I either disconnect the display or open my MacBook's lid, TexStudio always crashes. This behaviour does not happen if it's not in fullscreen mode.
When I re-open, it opens the tex files I had open in the last session where it quitted properly, so it will not re-open files I opened since then.

Here are the first few lines of the Apple report ( I uploaded the full report as a separate file):
[TexStudio_Apple_crash_report.odt](https://github.com/user-attachments/files/16621885/TexStudio_Apple_crash_report.odt)

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               texstudio [88041]
Path:                  /Applications/texstudio.app/Contents/MacOS/texstudio
Identifier:            texstudio
Version:               4.8.1 (???)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-08-15 14:44:53.3082 +0900
OS Version:            macOS 14.5 (23F79)
Report Version:        12
Anonymous UUID:        F469860A-2766-46E3-8BC1-7CD0B1954AB4

Sleep/Wake UUID:       BB163B12-D70D-4F31-A4DF-635C125D8D8A

Time Awake Since Boot: 1700000 seconds
Time Since Wake:       283 seconds

System Integrity Protection: enabled

Notes:
PC register does not match crashing frame (0x0 vs 0x1128CD453)

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000018
Exception Codes:       0x0000000000000001, 0x0000000000000018

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [88041]

VM Region Info: 0x18 is not in any region.  Bytes before following region: 4342022120
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      102ce0000-1047bc000    [ 26.9M] r-x/r-x SM=COW  /Applications/texstudio.app/Contents/MacOS/texstudio

Error Formulating Crash Report:
PC register does not match crashing frame (0x0 vs 0x1128CD453)

**Comment by sunderme** [comment]
from backtrace, it seems that it crashes in manhattan style.
Could you use classical color scheme ? (unless I am mistaken ?)

**Comment by Spiros713** [comment]
That's a good find! It seems to be colour theme related. If I make changes to some of the setting it stops crashing.

**Comment by sunderme** [comment]
maybe fixed: https://bugreports.qt.io/browse/QTBUG-127085
