### ISSUE TITLE
ERROR: invalid pattern in "path:pattern"

### ISSUE THREAD

**Issue by linchthe1st** [texstudio-org/texstudio#3772]
### Environment
- TeXstudio: 4.8.1
- Qt: 6.7.1
- OS: Windows 11 (23H2)
- TeX distribution: miktex

### Description
Hi, I've tried to install LanguageTool, without success. When checking the LanguageTool configuration in the Help tab, the LT report only appears shortly, thats why i couldnt copy past it, heres a picture i took:
![image](https://github.com/user-attachments/assets/149c14a3-91fb-45d6-94c4-90dcc7336d0d)

The message window displayed this:
Prozess gestartet: where "C:\Program Files\Java\jre1.8.0_421\bin\java.exe"

FEHLER: Ungltiges Schema in "path:pattern" angegeben.
Prozess endete mit Fehler(n)

This is the configuration i use:
<img width="752" alt="image" src="https://github.com/user-attachments/assets/18b2018d-c3db-4aec-a4f8-73f2230705f4">

I freshly installed java, checked the path like a hundred times, tried just using "java" as the path (i saw that in other threads).

I couldn't find any other helping issues with the same problem, Chatgpt was of no use as well. 
I would really appreciate some help. Thanks

**Comment by sunderme** [comment]
maybe quotes around the all paths ? 
Can you start languagetool directly ? They offer a gui which also allows to start is as a server. The started server is all txs needs.

**Comment by linchthe1st** [comment]
Quotes did not work, but i started languagetool directly and set the server options.
The report still asks for another path to java, but languagetool works and marks stuff in the text. 
Thanks for the help
