### ISSUE TITLE
how to change the background color for the AI box in the newest texstudio?

### ISSUE THREAD

**Issue by pottergxy** [texstudio-org/texstudio#3776]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior
The background for the AI chat box shoud be clear. Hope this issue could be solved soon. Thanks so much!

### Actual behavior

now the background is not clear to read.

![微信截图_20240827001550](https://github.com/user-attachments/assets/1674acba-ed4e-4b9d-b1fa-f87d499931fa)

**Comment by sunderme** [comment]
This is a fixed bug. Try rxs4.8.2rc3 or newe
