### ISSUE TITLE
Repeated crash when editing

### ISSUE THREAD

**Issue by scheiblechner** [texstudio-org/texstudio#3777]
Repeatedly, texstudio crashes when I edit a file. I get the attached error statement, and when I click "Ja, versuche es wiederherzustellen" (yes, try to restor it), then texstudio closes. When I click "Nein, beende TeXstudio" (no, abort TeXstudio) then it continues running. So one problem is that the actions of the two buttons seem to be switched.

But the main problem is of course the crash itself. It just happens, when I type certain symbols into the open file. I don't see any pattern. It happened a lot, when I typed inside the curly brackets of an \include statement. Now I realize that I can reproduce it typing a backslash in the beginning of a line.

That's the file content:

% !TEX encoding = UTF-8 Unicode

\input{pythonBasic-inputs}

%\includeonly{./pythonBasic_b04_en}

\begin{document}

\include{./pythonBasic_b00_titel_en}

\include{./pythonBasic_b01_en}

\include{./pythonBasic_b02_en}

\include{./pythonBasic_b03_en}

\include{./pythonBasic_b04_en}

\include{./pythonBasic_b05_en}

%\include{./topics/pythonBasic-normal}
%
%\include{./topics/pythonBasic-matrizen}

\end{document}

See the backtraces below.

![texstudio-crash](https://github.com/user-attachments/assets/10207cdb-eb0a-4dbe-8bb2-a6d55049ee94)

### Environment
- TeXstudio: 4.8.1
- Qt:  6.7.1, compiled with Qt 6.7.1 R
- OS: Windows 10 Enterprise H22H, build 19045.4780, Windows Feature Experience Pack 1000.19060.1000.0
- TeX distribution: texlive

### Expected behavior
No crash.

### Actual behavior
crash, see above.

### How to reproduce
Enter backslash (\\) in the beginning of an empty line.

[texstudio_backtrace7.txt](https://github.com/user-attachments/files/16783936/texstudio_backtrace7.txt)
[texstudio_backtrace6.txt](https://github.com/user-attachments/files/16783938/texstudio_backtrace6.txt)
[texstudio_backtrace5.txt](https://github.com/user-attachments/files/16783939/texstudio_backtrace5.txt)
[texstudio_backtrace4.txt](https://github.com/user-attachments/files/16783940/texstudio_backtrace4.txt)
[texstudio_backtrace3.txt](https://github.com/user-attachments/files/16783941/texstudio_backtrace3.txt)
[texstudio_backtrace2.txt](https://github.com/user-attachments/files/16783942/texstudio_backtrace2.txt)
[texstudio_backtrace1.txt](https://github.com/user-attachments/files/16783944/texstudio_backtrace1.txt)
[texstudio_backtrace13.txt](https://github.com/user-attachments/files/16783945/texstudio_backtrace13.txt)
[texstudio_backtrace12.txt](https://github.com/user-attachments/files/16783946/texstudio_backtrace12.txt)
[texstudio_backtrace11.txt](https://github.com/user-attachments/files/16783947/texstudio_backtrace11.txt)
[texstudio_backtrace10.txt](https://github.com/user-attachments/files/16783948/texstudio_backtrace10.txt)
[texstudio_backtrace9.txt](https://github.com/user-attachments/files/16783949/texstudio_backtrace9.txt)
[texstudio_backtrace8.txt](https://github.com/user-attachments/files/16783951/texstudio_backtrace8.txt)
[texstudio_backtrace18.txt](https://github.com/user-attachments/files/16783953/texstudio_backtrace18.txt)
[texstudio_backtrace17.txt](https://github.com/user-attachments/files/16783954/texstudio_backtrace17.txt)
[texstudio_backtrace16.txt](https://github.com/user-attachments/files/16783955/texstudio_backtrace16.txt)
[texstudio_backtrace15.txt](https://github.com/user-attachments/files/16783956/texstudio_backtrace15.txt)
[texstudio_backtrace14.txt](https://github.com/user-attachments/files/16783957/texstudio_backtrace14.txt)

**Comment by sunderme** [comment]
Complete examples including subfiles are needed.
And it needs to be verified that the example without any other open files actually shows the crash.

**Comment by scheiblechner** [comment]
Unfortunately, I cannot reproduce the problem at all anymore.

Von: sunderme ***@***.***>
Gesendet: Mittwoch, 28. August 2024 16:01
An: texstudio-org/texstudio ***@***.***>
Cc: Scheiblechner Peter HSLU T&A ***@***.***>; Author ***@***.***>
Betreff: Re: [texstudio-org/texstudio] Repeated crash when editing (Issue #3777)


Complete examples including subfiles are needed.
And it needs to be verified that the example without any other open files actually shows the crash.

**Comment by sunderme** [comment]
the backtraces unfortunately do not give sufficient information why txs crashes

**Comment by sunderme** [comment]
Are you also editing includes which are used in two different open root documents like #3730 ?

**Comment by Henri-Salha** [comment]
Hello, it seems that I have the same issue, and to me it seems related indeed to another one. (my version TeXstudio 4.8.1 (git 4.8.1) Using Qt Version 6.7.1, compiled with Qt 6.7.1 R, on Windows)

The same repeated crashes appeared when I copied a multiple-file project to a new folder and started changing the names of the files and deleting some the includes in the master file, or changing the % !TeX root =xxx.tex header at the beginning of the children-files.

The other issue (which I don't know if it was reported) is the project navigator. Typically, if I click on a chapter or section that is in a file which is not opened yet, TeXstudio freezes. But there are also other freeze phenomena linked to the navigator, the pattern of which is difficult to identify.

I wonder if all of this is not rooted in the way TeXstudio references files in a project, and gets confused with references. And maybe this is Windows specific?

**Comment by scheiblechner** [comment]
> The same repeated crashes appeared when I copied a multiple-file project to a new folder and started changing the names of the files and deleting some the includes in the master file, or changing the % !TeX root =xxx.tex header at the beginning of the children-files.
This is exactly what I did. In the meantime, the problem  disappeared and reoccurred. I have the impression that the more references and filenames are fixed, the less often it occurs.

**Comment by sunderme** [comment]
Again, i need a complete example and at best a step-by-step guide to make txs crash.
It may be some packages which you are using or special set up with subfolders.
You can send a test case directly to me (sunderme@gmx.de) if you want to keep it private.

**Comment by sunderme** [comment]
I have found and fixed "a" crash.
Can you try out the latest dev build ? (https://github.com/texstudio-org/texstudio/actions/runs/11129741620)

**Comment by sunderme** [comment]
assume fixed

**Comment by scheiblechner** [comment]
Thanks a lot!
Sorry for not answering your question earlier. But the error did not occur again and was difficult to reproduce. I simply didn’t have the time to research on that.

Von: sunderme ***@***.***>
Gesendet: Samstag, 12. Oktober 2024 13:46
An: texstudio-org/texstudio ***@***.***>
Cc: Scheiblechner Peter HSLU T&A ***@***.***>; Author ***@***.***>
Betreff: Re: [texstudio-org/texstudio] Repeated crash when editing (Issue #3777)


assume fixed
