### ISSUE TITLE
texstudio.org: download links are broken (Win)

### ISSUE THREAD

**Issue by deining** [texstudio-org/texstudio#3781]
Not sure if this is the right place to report:

Download links on [texstudio.org](https://www.texstudio.org/) are broken:

![grafik](https://github.com/user-attachments/assets/158574c3-2cbd-4f6f-8ecc-8258f7146754)

![grafik](https://github.com/user-attachments/assets/ce27fa8c-dcaa-43cc-a164-affed2f31f7c)

**Comment by octaeder** [comment]
link should be
`https://github.com/texstudio-org/texstudio/releases/download/4.8.2/texstudio-4.8.2-win-qt6-signed.exe`
but is
`https://github.com/texstudio-org/texstudio/releases/download/4.8.2/texstudio-4.8.2-win-qt6.exe`

s. [here](https://github.com/texstudio-org/texstudio/releases/tag/4.8.2):

![image](https://github.com/user-attachments/assets/391c7a73-e161-42e1-bf67-dd21110b583a)

**Comment by sunderme** [comment]
fixed
