### ISSUE TITLE
cite autocomplete supporting multiple .bib files

### ISSUE THREAD

**Issue by ycwang-hello** [texstudio-org/texstudio#3785]
### Describe the feature and the current behavior/state
Suppose I have multiple bib files (e.g. `\bibliography{ref1, ref2}`).
It seems that when automatically completing bib keys, it only knows the keys in the first bib file. Also, these keys are underlined, and it says "citation missing".
I think it should be useful to detect bib items in all bib files in case more than one file is used.

**Comment by tmelorc** [comment]
I'm not able to reproduce the problem on Linux with
```
TeXstudio 4.2.1 (Build: 4.2.1+ds-1)
Using Qt Version 5.15.3, compiled with Qt 5.15.2 R
```
In my case, all bib entries from all bib files are suggested in auto-completion.

**Comment by ycwang-hello** [comment]
I am using 
```
TeXstudio 4.8.1 (git 4.8.1)
Using Qt Version 6.7.1, compiled with Qt 6.7.1 R
```
on Windows and get this problem.

**Comment by sunderme** [comment]
my guess: remove the space before the second `ref2`, i.e. `\bibliography{ref1,ref2}`

**Comment by ycwang-hello** [comment]
> my guess: remove the space before the second `ref2`, i.e. `\bibliography{ref1,ref2}`

Thanks! Removing the spaces fixes the problem.
