### ISSUE TITLE
MacOS: Close buttons do not scroll properly with the tabs of open files

### ISSUE THREAD

**Issue by FF-code** [texstudio-org/texstudio#3786]
### Environment
- TeXstudio: 4.8.2
- Qt: 6.7.2
- OS: macOS 14.6.1
- TeX distribution: pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020)

TeXstudio Configuration in General:
- style: Fusion, color scheme: classic, iconset: Colibre, font: .AppleSystemUIFont, font size: 13, language: standard

### Expected behavior
When I have opened multiple files (and there are more open file tabs than is space left), I can scroll the tabs horizontally using the Trackpad and the close buttons scroll with each file tab.

### Actual behavior
When I have opened multiple files (and there are more open file tabs than is space left), and I scroll the tabs horizontally using the Trackpad, the close button of each tab stays in its former position.
When I click on one button after scrolling, the tab that was originally associated with the button is closed.

Before scrolling:
<img width="779" alt="before-scrolling" src="https://github.com/user-attachments/assets/fb737a79-0566-44ea-8207-4a9a1af66bde">

After Scrolling:
<img width="779" alt="after-scrolling" src="https://github.com/user-attachments/assets/f48b2ab9-8282-41d3-b2a5-db364d562781">

Video:

https://github.com/user-attachments/assets/80d8f7e6-f967-415b-8b35-a00d988ddc4b

Workaround:
I can click on the left/right arrow to the right of the tabs to reposition the tabs and its close buttons.

### How to reproduce
1. Open so many files that there are more file tabs than space (for example file "aaaaaaaaaa.tex", "bbbbbbbbbb.tex",...)
2. Focus TeXstudio (so that TeXstudio is the latest program that was clicked on...)
3. Place the mouse cursor on one file tab
4. Swipe left or right with two fingers on the MacBook Trackpad or Magic Trackpad

This bug is not applicable for classic mouse usage (scrolling with the wheel...)

**Comment by octaeder** [comment]
I can only report that I can't reproduce this with win10 and 4.8.1 or latest msys2 build. I simply opened several new (empty) documents and scrolled with fingers on the touch pad. For the test I used Fusion, Classic color scheme, and icon set Colibre and font Segoe UI. But I don't know if any of these settings affects the result.

**Comment by muzimuzhi** [comment]
> When I have opened multiple files (and there are more open file tabs than is space left), and I scroll the tabs horizontally using the Trackpad, the close button of each tab stays in its former position.

Interesting. I can reproduce this on macOS 14.6.1, texstudio 4.8.2. Also it works find when scrolling the tabs using mouse wheel.

**Comment by sunderme** [comment]
looks like a qt bug

**Comment by paubanon** [comment]
I can reproduce the error on MacOS 14.7and TexStudio 4.8.2

**Comment by sunderme** [comment]
duplicate #3280
