### ISSUE TITLE
Recognize the label in the optional parameter of the frame environment (in beamer class)

### ISSUE THREAD

**Issue by tercelxy** [texstudio-org/texstudio#3787]
### Describe the feature and the current behavior/state

In the beamer class, one can add label for a frame environment by using
`\begin{frame}[label=key]`
However, auto-complete does not recognize the label in the optional parameter of the frame environment. This makes it impossible to automatically fill in these labels in the parameters of commands such as \ref.

Is it possible to add such a recognization to auto-complete?

Moreover, it would be nice to recognize the label in the following two cases:

1. `\begin{frame}[label=key]`
2. `\begin{frame}[label={key}]`

**Comment by fdifonzo** [comment]
It is happening the same with \ref, \eqref etc... in other classes than beamer.  I am using amsart, but the same is occurring with article, for example. It looks like a regression
![Uploading Screenshot 2024-09-26 080917.png…]()

**Comment by sunderme** [comment]
beamer is inventing its own logic again.
frame has 3 optional arguments, two of them delimited by [] and they are distinguished by containing ` <>` or not.
So, this would require to add new optional argument type for just this case.
Unless I overhaul the parser again, this will not happen.

**Comment by sunderme** [comment]
the first case is now handled correctly.
