### ISSUE TITLE
toLocaleString function does not work within texstudio macros as expected

### ISSUE THREAD

**Issue by pizdjuk** [texstudio-org/texstudio#3788]
Following macro
```
const date = new Date();
const formatted = date.toLocaleString("default", { month: "long", day:"numeric", year:"numeric" });
editor.insertText(formatted);
```

should output a today date formatted as provided. Instead of this it gives numeric date like this
06.09.24 14:51

### Expected behavior

output formatted date as expected

**Comment by sunderme** [comment]
qt uses ecma javascript 7th edition (2016) (https://doc.qt.io/qt-6/qtqml-javascript-hostenvironment.html)
That definition does not explicitely define the arguments of the toLocaleString and qt apparently does not make much use of it.

Nothing we can do about it.
