### ISSUE TITLE
Keys defined in per-library cwls missing in completion list

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#3791]
### Environment
- TeXstudio: 4.8.2
- Qt: 6.7.2
- OS: macOS 14.6.1
- TeX distribution: BasicTeX 2024

### Expected behavior

After loading a package library, the keys defined in cwl of that library are shown in the corresponding completion list(s).

### Actual behavior

Those keys are recognized (no "unrecognized key in key option" prompt), but missing in completion list(s).

### How to reproduce

```tex
\documentclass{article}
\usepackage{tcolorbox}
\tcbuselibrary{breakable}

\tcbset{}

\begin{document}
\begin{tcolorbox}[]
  content
\end{tcolorbox}
\end{document}
```

The corresponding cwl for tcolorbox library `breakable` provides key `breakable` and many more for the option list of `\tcbset`, `\begin{tcolorbox}`, etc.

https://github.com/texstudio-org/texstudio/blob/ed175a79f13e24f26716b1627b6ee4b4dcc9bdf9/completion/tcolorboxlibrarybreakable.cwl#L8-L9

- In the argument of `\tcbset{...}`, type in "break" and see that there's no "breakable" in the completion list, "all" tab.
- `\tcbset{break}` shows "break" is unrecognized, but `\tcbset{breakable}` is recognized.
- In the optional argument of `\begin{tcolorbox}[...]`, type in "break" and check the similar behavior.

Commands provided by libraries are both recognized and shown in completion list, for example `\tcbbreak` in `breakable` library.

![image](https://github.com/user-attachments/assets/a93fb69e-a78b-464f-b604-842a523d0d96)

![image](https://github.com/user-attachments/assets/5bdc7f8a-4581-4f04-a667-440d92b3677f)

------

It seems to me this is a regression, though I'm not sure.

**Comment by sunderme** [comment]
not reproducible on linux
<img width="357" alt="grafik" src="https://github.com/user-attachments/assets/e7a8043c-0645-4dbc-96a4-121b1396558f">

**Comment by muzimuzhi** [comment]
> but it works if you load the document.

Still cannot see the options from library.

**Comment by mbertucci47** [comment]
It works as expected for me on Windows

**Comment by sunderme** [comment]
do you see any keyvals when trying to complete an empty `\tcbset` ?

**Comment by muzimuzhi** [comment]
Yes, the options from the main `tcolorbox` package is shown.

https://github.com/user-attachments/assets/06be57ca-c48b-4fa2-b09d-4045c1970306

**Comment by sunderme** [comment]
probably fixed

**Comment by muzimuzhi** [comment]
Tried with the build for 89d3411 (fix updating keyvals for completion, 2024-09-11) and the problem is fixed, thank you!

![image](https://github.com/user-attachments/assets/059f23ff-3251-4c7c-ac19-2f0db5f65295)
