### ISSUE TITLE
Citation popup life is too short

### ISSUE THREAD

**Issue by ianhbell** [texstudio-org/texstudio#3796]
### Environment
- TeXstudio: 4.8.2 (but same in 4.6 and previous versions)
- Qt: Using Qt Version 6.7.2, compiled with Qt 6.7.2 R
- OS: mac (same problem on windows)
- TeX distribution: 

### Expected behavior

The secondary popup stays on screen long enough to be read

### Actual behavior

The secondary popup appears on screen and then almost immediately goes away

### How to reproduce

The secondary popup with the information about the highlighted reference appears on screen for a fraction of a second, for instance when I select this reference:

<img width="557" alt="image" src="https://github.com/user-attachments/assets/fdc7bafc-c248-436f-827d-3a8fe1327976">

but it disappears so quickly that I cannot see the information about the reference. It would be nice if that on-screen time could be user-configurable or at least a second or two.

**Comment by ianhbell** [comment]
Joy - so it's a mac specific thing; I can confirm that windows works fine with 4.8 and Qt 6. Maybe it is a Qt version thing. How does one get an updated Qt on mac?

**Comment by octaeder** [comment]
Qt 6.7.2 is also used in my version/build. Qt 6.7.3 is [planned for 09/19/2024](https://wiki.qt.io/Qt_6.7_Release)

**Comment by sunderme** [comment]
duplicate to #523 
qt is already latest and yes, it is a qt/osx issue.

**Comment by ianhbell** [comment]
So we're stuck. At least it is good to know that clicking(!) on the entry in the tooltip keeps the preview on screen. I can live with that until this issue is fixed

**Comment by sunderme** [comment]
it may be unfixable. The point is that the tooltip does not appear where the mouse cursor is and that is something OSX does not support.

**Comment by ianhbell** [comment]
It appears in the right place, just doesn't stay there

**Comment by sunderme** [comment]
duplicate to #523
