### ISSUE TITLE
Add amsthm to the AMS packages menu item

### ISSUE THREAD

**Issue by tmelorc** [texstudio-org/texstudio#3798]
When using the AMS Packages from LaTeX menu, the following two lines of code are inserted:

```
\usepackage{amsmath}
\usepackage{amssymb}

```
But IMHO (and based on this [TEX.SE](https://tex.stackexchange.com/a/32103/14757) answer) it would be good to add also the `amsthm` package. 

Regards.

**Comment by octaeder** [comment]
Quick Start wizard also offers amsthm, so this might be reasonable
maybe replace amsmath with mathtools,
@sunderme I could provide a PR.

**Comment by sunderme** [comment]
Any other comments on what it should be ?
I have no opinion on this.

**Comment by tmelorc** [comment]
> Quick Start wizard also offers amsthm, so this might be reasonable maybe replace amsmath with mathtools, @sunderme I could provide a PR.

I don't know if `mathtools` is a basic package, I mean, if we do a minimal/basic LaTeX install, would it be installed? Otherwise some new user could get problems.

**Comment by octaeder** [comment]
mathtools is part of miktex and texlive, so the package manager can load it if needed. mathtools loads amsmath. I would expect both packages to be available. @dbitouze any hints?

**Comment by dbitouze** [comment]
@octaeder I don't know if `mathtools` is provided by the minimalist TeX distributions (like TinyTeX, for which I haven't found the list of packages). In TeX Live, it's part of the "latexrecommended" collection and it's a package I would indeed recommend.
