### ISSUE TITLE
TOC and Structure (in sidepanel) do not recognize sections with optional parameter

### ISSUE THREAD

**Issue by tercelxy** [texstudio-org/texstudio#3799]
### Environment
- TeXstudio: 4.8.3 rc1
- Qt: 
- OS: Win11
- TeX distribution: 

See the figure below.
![sec](https://github.com/user-attachments/assets/01d4f30a-facf-4a35-a8e3-6fe6485816af)

The TOC contains the two sections introduced by
`\section{1}`
`\section*{2}`
but not contains the section introduced by
`\section[short title]{title}`

The same happens in Structure

**Comment by sunderme** [comment]
not reproducible on linux

**Comment by sunderme** [comment]
same on win11, 4.8.2rc1

**Comment by octaeder** [comment]
@sunderme you mean that you see title in the TOC not short title?

**Comment by sunderme** [comment]
I see short title

**Comment by tercelxy** [comment]
I tried it in a version with initial settings and there was no problem. It seems that this is caused by some special settings of mine.

Morever，I agree with @octaeder that it should be title not short title in the TOC

**Comment by mbertucci47** [comment]
Not to hijack the thread, but I disagree about the title/short title issue. The point of the optional argument of `\section` is to specify what should go in the document TOC (and pdf bookmarks if hyperref is loaded). It would be odd for the sidepanel TOC and document TOC to contain different entries.

**Comment by sunderme** [comment]
I agree with @mbertucci47 , so closing this.

**Comment by octaeder** [comment]
@mbertucci47 good point
