### ISSUE TITLE
LanguageTool errors not underlined

### ISSUE THREAD

**Issue by danielnaber** [texstudio-org/texstudio#38]
What can be the reason that errors found by LanguageTool are not underlined? I can see in the server's logs that it gets the request and finds errors, but nothing gets underlined in TexStudio. I have checked the syntax highlighting colors and they are set. I have tested with German and English. How to debug this?

Server URL: http://localhost:8081/v2/check  (using http://localhost:8081/ doesn't work at all, as the request is sent to `/` instead of `/v2/check`)

Software: 
* LanguageTool 4.1-SNAPSHOT
* TeXstudio 2.12.6 (hg 6631:16db084dae24), Using Qt Version 4.8.7, compiled with Qt 4.8.7 R

Check LanguageTool:

```
Real-time checking is enabled.
Grammar checking is enabled.
Autostart disabled.
LT current status: working
LT-URL: http://localhost:8081/v2/check
```

**Comment by benibela** [comment]
With qt4 texstudio only supports the old xml api. 

v2 json depends on qt5
