### ISSUE TITLE
Splash screen black (Linux)

### ISSUE THREAD

**Issue by Esokrates** [texstudio-org/texstudio#380]
### Environment
- TeXstudio: 2.12.10
- Qt: 5.11.1,
- OS: Ubuntu, Gnome Shell
- Intel graphics

The following happens in both, Gnome Wayland session and Gnome Xorg sessionl

### Expected behavior
When starting TeXStudio the splash screen appears.

### Actual behavior
TeXStudio launches with black screen.
![screenshot from 2018-11-11 19-57-45](https://user-images.githubusercontent.com/17780185/48317063-8a4aca80-e5ec-11e8-8f81-666984d81540.png)

### How to reproduce
Start TeXStudio and observe a slight shadow of the splash screen and after that the whole window is black until TeXStudio is done starting up.

**Comment by Esokrates** [comment]
I forgot to mention: It does only happen when there were tabs it restores from the last session.

So it's triggered by session restore. If I outlined exactly when it does happen and when not, would you be willing to reproduce and have a look?

**Comment by sunderme** [comment]
we are talking about a cosmetic problem ?
In general txs works fine on LXDE,xfce,gnome etc. I don't deem it feasible to exactly reproduce your set-up and hope the issue arises. In all likely hood it is caused by a problem between qt and gnome and we are not bug fixing gnome or qt.
