### ISSUE TITLE
Menu bar text not visible due to theme/style issues

### ISSUE THREAD

**Issue by chiavez** [texstudio-org/texstudio#3801]
### Environment
- TeXstudio: 4.8.2 (git 4.8.2)
- Qt: Using Qt Version 6.7.2, compiled with Qt 6.7.2 R
- OS:  Windows 11 Home; version 23H2
- TeX distribution: miktex
- windows theme: dark
- texstudio settings: in the image below
![image](https://github.com/user-attachments/assets/800582fe-3ef2-4af6-af5f-e167c53f6a08)

### Expected behavior
text is visible

### Actual behavior
text is not visible

![image](https://github.com/user-attachments/assets/294eafe4-b3fa-4c54-8b23-9b93f2434f47)
![image](https://github.com/user-attachments/assets/6774831f-c14e-45d7-9898-f4f432ec0e20)

### Temporary fix
change the style to "Fusion"
![image](https://github.com/user-attachments/assets/39c9079b-1f66-4c47-928c-8fd3f48da756)
![image](https://github.com/user-attachments/assets/ef05d66c-01af-4a2b-b993-3998dc9f0392)

**Comment by chiavez** [comment]
It seems a duplicate of #3694, it seems that is an issue with Qt. Still, the bug is still there, so i am not sure why people are closing the issues. I let someone else close this one.

**Comment by sunderme** [comment]
duplicate #3694
