### ISSUE TITLE
Crashing after upgrade to LinuxMint 22

### ISSUE THREAD

**Issue by wujastyk** [texstudio-org/texstudio#3802]
### Environment
- TeXstudio: 
- Qt: Using Qt Version 5.12.8, compiled with Qt 5.12.8 R (in the appimage)
- OS: Linux Mint with Cinnamon desktop
- TeX distribution: TeXLive
- TeXstudio version 4.8.3 installed from deb.

I have fallen back to using the Appimage, which works fine.

### Expected behavior
normal startup

### Actual behavior
```
$ texstudio

(texstudio:57550): GLib-GObject-CRITICAL **: 19:28:10.892: cannot register existing type 'GdkDisplayManager'

(texstudio:57550): GLib-CRITICAL **: 19:28:10.892: g_once_init_leave_pointer: assertion 'result != 0' failed

(texstudio:57550): GLib-GObject-CRITICAL **: 19:28:10.892: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(texstudio:57550): GLib-GObject-CRITICAL **: 19:28:10.892: invalid (NULL) pointer instance

(texstudio:57550): GLib-GObject-CRITICAL **: 19:28:10.892: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(texstudio:57550): GLib-GObject-CRITICAL **: 19:28:10.892: invalid (NULL) pointer instance

(texstudio:57550): GLib-GObject-CRITICAL **: 19:28:10.892: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(texstudio:57550): GLib-GObject-CRITICAL **: 19:28:10.894: cannot register existing type 'GdkDisplay'

(texstudio:57550): GLib-CRITICAL **: 19:28:10.894: g_once_init_leave_pointer: assertion 'result != 0' failed

(texstudio:57550): GLib-GObject-CRITICAL **: 19:28:10.894: g_type_register_static: assertion 'parent_type > 0' failed

(texstudio:57550): GLib-CRITICAL **: 19:28:10.894: g_once_init_leave_pointer: assertion 'result != 0' failed

(texstudio:57550): GLib-GObject-CRITICAL **: 19:28:10.894: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Segmentation fault (core dumped)

```

### How to reproduce

run `/usr/bin/texstudio`

**Comment by sunderme** [comment]
no sure where you got the deb from, but ubuntu 24.04 (base for linux mint 22) uses qt 5.15.12.
Please just install the proper package or use the ubuntu ppa (https://code.launchpad.net/~sunderme/+archive/ubuntu/texstudio)

**Comment by wujastyk** [comment]
> no sure where you got the deb from, but ubuntu 24.04 (base for linux mint 22) uses qt 5.15.12. Please just install the proper package or use the ubuntu ppa (https://code.launchpad.net/~sunderme/+archive/ubuntu/texstudio)

The deb _is_ from the LPP that you maintain.  It is the "proper" package.  

![image](https://github.com/user-attachments/assets/d0dcf043-7bb3-4f11-ab3f-1f49d9ae2c55)

I have tried both the deb from your Launchpad site and from the Mint package manager.  Here are the versions:

```
~$ texstudio --version
TeXstudio 4.8.3 (0.0.0++)
:~$ texstudio --version
TeXstudio 4.7.2 (4.7.2+ds-2build3)
```
Both exhibit the same core dump on launch.

My system has QT 5.15.13 installed.

That's why I have written this issue.  It's not obvious to me what's wrong on my system.

**Comment by sunderme** [comment]
I can only state that texstudio from ppa work fine on ubuntu 24.04.
I can't/won't debug remote systems.

**Comment by wujastyk** [comment]
Well, it obviously doesn't.  But I understand that there's only so much you can do.  I was hoping the core-dump messages would signal more to you than they do to me.

I've been trying all sorts of checks with QT and Python versions and libraries and conf files.  No luck yet.

I have another Mint 22 installation on a laptop where the same texstudio deb works just fine.  The problem on my desktop machine arose immediately after the 22 upgrade that I did yesterday.  That's another variable that's changed recently.

**Comment by sunderme** [comment]
Only suggestion is to remove .config/texstudio to start clean.

**Comment by wujastyk** [comment]
Thanks, I tried that but it didn't cure the core dump.  I'll nail it eventually, and I'll report back here.

**Comment by wujastyk** [comment]
After reading [this page](https://forums.linuxmint.com/viewtopic.php?t=423513), I said at the CLI:
```
$export QT_QPA_PLATFORMTHEME="qt5ct"
```
and Texstudio started up nicely, without all those Gdk errors.

**Comment by sunderme** [comment]
so, we can close this ?

**Comment by wujastyk** [comment]
I just updated another Linux Mint machine that I have responsibility for from 21 to 22, and I had the same texstudio startup problem.  I added the environment variable mentioned above, but it did not cure the problem.  So it's the environment variable PLUS one of the other changes I made that fixes things.  I am working on it, again, and I'll report back.
