### ISSUE TITLE
Accepting newlines in tabular preambles

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#3804]
### Describe the feature and the current behavior/state

It seems in texstudio v4.8.3, the tabular content is not properly recognized (e.g., `&`s are not highlighted) when the tabular preamble contains (non-consecutive) newlines.

```tex
\documentclass{article}
\usepackage{siunitx}

\begin{document}
\begin{tabular}{ll}
  a & b
\end{tabular}

\begin{tabular}{
ll}
  a & b
\end{tabular}

\begin{tabular}{
  |S[table-alignment-mode=format,table-number-alignment=right]
  |S[table-alignment-mode=format,table-number-alignment=center]
  |S[table-alignment-mode=format,table-number-alignment=left]
  |
}
  1.1 & 2.2 & 3.3
\end{tabular}
\end{document}
```
![image](https://github.com/user-attachments/assets/2f0d1084-d544-428b-8c28-b132d5582335)

### Who will benefit with this feature?

Especially users of `S` column type from `siunitx` package, see https://github.com/lvjr/tabularray/issues/512 and examples in the `siunitx` package manual, sec. 4.12 Tabular material.

**Comment by sunderme** [comment]
implemented with [b16af3e](https://github.com/texstudio-org/texstudio/commit/b16af3e676fc3677700db946f195060e2dcc61ce)
