### ISSUE TITLE
regexp Search with replace all sometimes causes txs to spin

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3806]
### Environment
- TeXstudio: current dev, assume all current versions affected
- Qt: 6.7.2
- OS: Windows10
- TeX distribution: miktex, texlive

### Expected behavior
normal replacement

### Actual behavior
maybe txs may hang in an infinite loop of recursion

### How to reproduce
open new editor
insert `\draw plot[prefix=GnuPlot/,id=S`
extended search for `gnuplot/` as regExp ![image](https://github.com/user-attachments/assets/eaa4ed70-7bd7-4e44-8409-273c4dd1853f)
set Replace by to `GnuPlot/2019-`
press `Replace all`
result: `\draw plot[prefix=GnuPlot/2019-2019-2019-2019-2019-2019-2019-2019-2019-2019-2019-2019-2019-2019-2019-,id=S`

In the real case txs did not respond on mouse or keybord actions.

**Comment by sunderme** [comment]
is only replaced once here

**Comment by octaeder** [comment]
After the replacement press `Ctrl+z` until the replacement is undone. Then repeat the extended search and the replacement (you have to insert the replacement text again). Each time I undo and repeat, the number of inserts increases by one.
The behavior seems not to depend on the number of open documents. I can reproduce without .ini file.

**Comment by sunderme** [comment]
screencast ?

**Comment by octaeder** [comment]
https://github.com/user-attachments/assets/7fa44518-ffdd-4770-aff0-26a193ec335b
