### ISSUE TITLE
Shortcuts for new macros not propagated into menu

### ISSUE THREAD

**Issue by thatlittleboy** [texstudio-org/texstudio#381]
### Environment
- TeXstudio: 2.12.12 beta 1 (git_b183983) 
- Qt: 5.8
- OS: Win 10
- TeX distribution: MikTeX 

Considering we are in beta, I thought I'ld log some of the bugs I found with the new macro system.

### Actual behavior
Changes to the `shortcut` from the usermacro dialog does not propagate to the user toolbar (`Macros->...` ) as it used to.
Currently, **it doesn't**:
- automatically create/assign the default shortcuts `Shift+Fn` if no shortcut was provided
- update changes made in the `shortcut` box from the macro dialog

### How to reproduce
1. Create new macro. Don't assign a shortcut.
2. Click Ok to exit out of the macro dialog.
3. Go to `Macros` from the main toolbar: no shortcuts assigned.

-----------

1. For an existing macro with an existing shortcut (properly assigned), make some changes.
2. Click Ok to exit out of the macro dialog.
3. Go to `Macros` from the main toolbar: shortcuts didn't get updated.

![mwe](https://user-images.githubusercontent.com/30731072/48385708-89359e00-e6bd-11e8-819b-c3c8a3287f4a.gif)

------------------

Another situation but same problem:

Swap order of 2 macros, (Macro 1 has the shortcut Shift+F12 initially, but after swapping and clicking Ok, macro 2 has the shortcut in the user menu toolbar, even though according to the user macro dialog shortcut box, Shift+F12 is still assigned to Macro 1)

![mwe](https://user-images.githubusercontent.com/30731072/48387525-2f84a200-e6c4-11e8-92ba-efea2e7d1adb.gif)

**Comment by dbitouze** [comment]
BTW, would be nice if https://github.com/texstudio-org/texstudio/issues/64 could be resolved for 2.12.12 version...
