### ISSUE TITLE
Add compile instruction for Arch Linux

### ISSUE THREAD

**Issue by user202729** [texstudio-org/texstudio#3811]
Currently the [wiki](https://github.com/texstudio-org/texstudio/wiki/Compiling#linux) has build instruction for Ubuntu. I think we can add one for Arch Linux.

Maybe something like the following

> One way is to install it from the AUR repository: https://aur.archlinux.org/packages/texstudio-git
> 
> Another way is to install the dependencies (including build dependencies marked with `(make)`):
> 
> ```bash
> sudo pacman -Syu --needed desktop-file-utils hicolor-icon-theme hunspell libxkbcommon-x11 poppler-qt6 qt6-5compat qt6-declarative qt6-svg quazip-qt6 cmake imagemagick librsvg mercurial ninja qt6-tools
> ```
> 
> then obtain the source and build as above.

The list of dependencies are directly copied from the [official package](https://archlinux.org/packages/extra/x86_64/texstudio/).

**Comment by sunderme** [comment]
not sure about: ` hicolor-icon-themeimagemagick librsvg mercurial`

**Comment by sunderme** [comment]
apparently this is not really important.
no feedback.
