### ISSUE TITLE
Double-click selection of words with special character

### ISSUE THREAD

**Issue by roundplanet** [texstudio-org/texstudio#3812]
Selection of words with a double-click in the editor will only work until a special character lilke 'ä', 'ö' or 'ñ', so that the whole word will not be selected.

### Environment
- TeXstudio: 4.8.3
- Qt: 6.7.2
- OS: Windows 10
- TeX distribution: texlive

### Expected behavior
![grafik](https://github.com/user-attachments/assets/5cf08f2c-ec2e-4ac5-95ec-67985f1589d0)
![grafik](https://github.com/user-attachments/assets/2c3c6746-f308-43e1-b569-180c96d8a615)

### Actual behavior
![grafik](https://github.com/user-attachments/assets/83327091-7328-4cf5-ab3f-9b4df430811d)
![grafik](https://github.com/user-attachments/assets/0da0e5f1-64a4-4d44-9914-ec9533f8b1bd)

### How to reproduce
Double click left or right of the special character

**Comment by kiganev** [comment]
I can confirm this behaviour, double-click works only for the standard Latin set, words in Cyrillic are not selected at all.

**Comment by octaeder** [comment]
confirm with Win10, current dev, miktex, Qt6.7.2
click on right side:
![image](https://github.com/user-attachments/assets/c0e50219-e138-47c8-b05b-d5e0da9bda4b)
click on left side:
![image](https://github.com/user-attachments/assets/98cd4faf-089b-4224-94e2-da9dd7720e44)

settings:
![image](https://github.com/user-attachments/assets/4dcc8a9f-6f39-4206-9a1b-a486a2479f5c)

not the case in 4.8.2 (`texstudio-4.8.2-win-qt6-signed.exe`)
![image](https://github.com/user-attachments/assets/ca13c1b0-3b5b-45ec-ac69-e4337b91c471)

**Comment by sunderme** [comment]
fixed
