### ISSUE TITLE
Suggestions for new features

### ISSUE THREAD

**Issue by mirspan** [texstudio-org/texstudio#3813]
1. Export to EPUB, DjVu.
2. Convert Markdown syntax + Markdown Extended Syntax to Latex.
3. In the new document wizard. Add a feature to set pagination and their position + external fonts for the whole documment. 
4. To be able to store multiple independent documents under one file. In the style of LibreOffice calc.
5. When spell checking, look in all activated dictionaries e.g. German+French and Russian.
6. Add character map.

**Comment by sunderme** [comment]
1) no, use ` pandoc` 
2) no, use ` pandoc` 
4) no, the point of latex is that uses simple text files. This is also determined by latex itself.

**Comment by sunderme** [comment]
6) also no, that is what the latex symbols are for.

**Comment by sunderme** [comment]
3) there is already a pagination tab and you can add any package (i.e. font) you like

**Comment by sunderme** [comment]
and 5. was asked before: #1241
