### ISSUE TITLE
Selecting word with umlauts

### ISSUE THREAD

**Issue by EricNoJokes** [texstudio-org/texstudio#3815]
When I double click on a word that has an umlaut in it (ä, ö, ü; maybe other special characters like the Swedisch å, too) not the whole word is selected but only the part before/after the umlaut.

### Environment
- TeXstudio: 4.8.3
- Qt: 6.7.2 (R)
- OS: Windows 11
- TeX distribution: miktex

### Expected behavior
The whole word should be selected.

### Actual behavior
![Screenshot 2024-09-27 081939](https://github.com/user-attachments/assets/4b49e32f-74d9-4a3a-9da2-cef0f88ccd0c)

### How to reproduce
Just type a word with an umlaut in it and double click on the part of the word before/after the umlaut.

**Comment by octaeder** [comment]
duplicate, already fixed for next release, s. #3812

**Comment by sunderme** [comment]
fixed, new release published
