### ISSUE TITLE
Label missing with existing label

### ISSUE THREAD

**Issue by fdifonzo** [texstudio-org/texstudio#3816]
I am experiencing bad behaviors with \ref and \eqref is amsart and article class (as far as I know). 
For example, I see this:
![image](https://github.com/user-attachments/assets/116fd192-c94f-44ed-acb2-4a5c6206030b)

### Environment
- TeXstudio: 4.8.4
- Qt: 6.7.2
- OS: Windows 11
- TeX distribution: texlive

### Expected behavior

I should not see any label missing sign on existing labeled equations.

### Actual behavior
![Screenshot 2024-09-28 144459](https://github.com/user-attachments/assets/0cadcbfe-72b3-43c9-b9f3-cba45be99bf5)

### How to reproduce

\documentclass[11pt]{amsart}
\usepackage[english]{babel}
\usepackage[latin1]{inputenc}
\usepackage{amssymb,geometry,color,xcolor,graphicx}
\usepackage{amsmath,amsthm}
\usepackage{booktabs}
\usepackage{caption}
\usepackage{datetime}
\usepackage{dsfont}
\usepackage{amstext}
\usepackage{graphicx}
\usepackage{fancyhdr}
\usepackage{latexsym}
\usepackage{mathrsfs}
%\usepackage{stmaryrd}
\usepackage{cases}
\usepackage{mathtools}
\usepackage{bm}
\usepackage{subfigure}
\usepackage{hyperref}
\hypersetup{
    colorlinks=true, %set true if you want colored links
    linktoc=all,     %set to all if you want both sections and subsections linked
    linkcolor=blue,  %choose some color if you want links to stand out
}
\geometry{tmargin=3cm,bmargin=4cm,lmargin=3.5cm,rmargin=3.5cm}
\hyphenation{}

\newcommand{\de}{\mathrm{d}}

\begin{document}

\begin{equation}\label{eq:stocKdV}
\begin{cases}
\de u(x,t)=(6u(x,t)u_x(x,t)-u_{xxx}(x,t))\de t+\varepsilon u(x,t)\de W(t), & x\in(-\infty,\infty),\;t\in(0,T), \\
u(x,0)=-2k^2\sech^2(kx),
\end{cases}
\end{equation}
\ref{eq:stocKdV}
\eqref{eq:stocKdV}

\end{document}

**Comment by fdifonzo** [comment]
The issue is still there, and the autocomplete does not help with the equation, which is quiete uncomfortable...
![image](https://github.com/user-attachments/assets/118bee3a-882e-4e59-ae58-a652969f819f)

**Comment by octaeder** [comment]
do you test with alpha version or 4.8.4? The fix is currently on alpha.

**Comment by Q-0-Q** [comment]
I also face the same problem on TeXstudio 4.8.4 with Windows 11 24H2. BTW, my CPU comes from AMD intead of Intel.

**Comment by fdifonzo** [comment]
It works on alpha :)
