### ISSUE TITLE
autocompletion for \documentclass broken

### ISSUE THREAD

**Issue by mbertucci47** [texstudio-org/texstudio#3817]
### Environment
- TeXstudio: 4.8.4
- Qt: 6.7.2
- OS: Window 10
- TeX distribution: texlive

### Expected behavior

The mandatory argument of `\documentclass` should show a list of classes in the autocompleter.

### Actual behavior
The autocompleter opens but there is no list.

<img width="363" alt="no-autocomplete" src="https://github.com/user-attachments/assets/dbb6e60c-1203-4cc2-aca8-f27cf12ad568">

There is no problem with the completion for `\usepackage`.

<img width="362" alt="autocompl" src="https://github.com/user-attachments/assets/beff7d75-981c-4687-907d-289db12f8763">

### How to reproduce
Open a new file, type `\documentclass{a}` and open the autocompleter after `a`. It should also work with an empty argument.

**Comment by sunderme** [comment]
as fas as I can tell, document class completion has never been implemented.

**Comment by mbertucci47** [comment]
@sunderme Interesting. There must be some code for something related to `\documentclass` because the completer opens with Ctrl+Space. Also the [documentation](https://texstudio-org.github.io/background.html#command-format) lists `class` as a special argument type.

**Comment by sunderme** [comment]
implemented
