### ISSUE TITLE
The typing within \usepackage is very slow

### ISSUE THREAD

**Issue by pizdjuk** [texstudio-org/texstudio#3818]
# Environment

    TeXstudio: 4.8.0
    Qt: Usando Qt Version 5.12.8, compilado con Qt 5.12.8 R
    OS: Linux Mint
    TeX distribution: Texlive

# Actual behaviour

If I edit some package or option name within \usepackage command, every letter takes around 2 seconds.

# Expected behavior

Typing is normal

# Steps to reproduce

1. Open some big project (around ten tex-files)
2. Type \usepackage{
3. The typing will be immediately slowed

# What I tried

I tried do disable autocompletion in Options->Editor and in Options->Autocompleteion, restarting Texstudio every time. Nothing helped.

**Comment by sunderme** [comment]
This is the consequence of txs trying to load all defined packages.
As you are using an unclosed argument, all following lines are interpreted as package names and txs tries to load them.
To avoid this, use the completer an inser `\usepackage{}` and then insert the package name.

**Comment by pizdjuk** [comment]
It is slow even if I just edit already defined string like `\usepackage{enumitem}`
And if I edit the option string like `\usepackage[shortopts]{enumitem}`.

**Comment by FRuehl** [comment]
The option "Auto-recompile on document change" (In preferences/Internal PDF Viewer) enforces a complete reload of the document, if changes in the header section are encountered. Either disable "Auto recompile" or type the complete string \usepackage{...} somewhere in the body section, cut the string, and paste in the header.
The bug will hopefully be eliminated, if the bug #3822 is reolved.

**Comment by pizdjuk** [comment]
I never enabled the autorecompile option.

**Comment by sunderme** [comment]
without a concrete example, there is nothing I can do about this.

**Comment by sunderme** [comment]
nothing to work with
