### ISSUE TITLE
AI wizard doesn't save query and results

### ISSUE THREAD

**Issue by Ticonderoga** [texstudio-org/texstudio#3820]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior
I tried the AI wizard with Groq. (https://groq.com/) Groq has a standard API with several models available. It means that the Wizard should work without any problem. I set the wizard like this : 
* Local model
* API key : gsk_geVHYc ...... 
* URL : https://api.groq.com/openai/v1/chat/completions

### Actual behavior
The queries are not stored, so it means I have to copy / paste my query text each time. I often use AI for a translation purpose and here is the prompt I always use : 

"I want you to act as an English translator, spelling corrector and improver. I will speak to you in french and english and you will  translate it (if necessary) and answer in the corrected and improved version of my text, in English. I want you to replace my simplified A0-level words and sentences with more beautiful and elegant, upper level English words and sentences. Keep the meaning same, but make them more literary. I want you to only reply the correction, the improvements and nothing else, do not write any explanations."

The result is OK and I always receive a fine translation or correction of my text. Unfortunately, I would like to store my prompt and use other ones. 

### How to reproduce
set an Groq account (free one) with an API Key and then use the AI wizard

**Comment by sunderme** [comment]
by the way, the prompt can be stored in the ai chat options,
![grafik](https://github.com/user-attachments/assets/a7adfb61-35fc-45b1-8d42-2f3766fe2237)

**Comment by Ticonderoga** [comment]
Well done Thanks 
but **the queries are not saved** even if I check the box in the config pane

**Comment by sunderme** [comment]
have you compiled from source ?

**Comment by Ticonderoga** [comment]
No I used the arch package. I changed to the git package aur/texstudio-git an it seems to work now. Thanks for the fix
