### ISSUE TITLE
`package` cwl keyword should only show completion for .sty files

### ISSUE THREAD

**Issue by mbertucci47** [texstudio-org/texstudio#3821]
### Describe the feature and the current behavior/state
The `package` cwl keyword that autocompletes package files, such as in `\usepackage{package}`, should only list installed .sty files. Right now it lists both .sty and .cls files. The latter should be shown in commands with the `class` keywords (related #3817). For example there is memoir.cls but no memoir.sty so "memoir" showing in the completer for `\usepackage` is not useful.

<img width="363" alt="sty-comp" src="https://github.com/user-attachments/assets/49863293-c40a-437a-ad15-019c1b4d0fb6">

### Who will benefit with this feature?

All users. This would remove unnecessary entries from the `\usepackage` list.

**Comment by sunderme** [comment]
done
