### ISSUE TITLE
Auto-recompile document on changes drops characters typed during calculation of text-width

### ISSUE THREAD

**Issue by FRuehl** [texstudio-org/texstudio#3822]
### Environment
- TeXstudio: 4.8.4
- Qt: 6.7.2 R
- Apple M2 Pro
- OS: Sequoia 15.0
- TeX distribution: texlife

### Expected behavior
During auto-recompile all characters typed on the keyboard should appear in the editor window.

### Actual behavior
During auto-recompile, sometimes a modal window is displayed (In my case for less than one second) displaying "calculating text width" and a "Cancel" button.
Characters typed during the display of the window are dropped, i.e. are not forwarded to the editor.

### How to reproduce
Switch on Auto-recompile in the settings for the internal PDF viewer, preferably on a large input file containing mathematical content.

### Suspected cause of the error
The modal window drops all characters coming from the keyboard, while waiting for the "cancel" button being pressed.

### Possible Remedy   
Change the type of the window to modeless

**Comment by sunderme** [comment]
pdf viewer mode "fit to text width" seems not to be a good choice

**Comment by sunderme** [comment]
duplicate #3824
