### ISSUE TITLE
Capturing Cursor Coordinates along with Page Numbers

### ISSUE THREAD

**Issue by pskumaresh06** [texstudio-org/texstudio#3823]
### Environment
- TeXstudio: 4.6.3
- Qt: Using Qt Version 6.5.2, compiled with Qt 6.5.2 R
- OS: Windows 11 Pro
- TeX distribution: MikTeX 2.9

### Description
I am working on automating float positioning in LaTeX. 
When I use Ctrl+Shift+MouseClick on the preview, the cursor's coordinates (x-axis, y-axis) are copied to the clipboard. 
How can I also include the current page number (x-axis, y-axis, current page number) in the list?

**Comment by octaeder** [comment]
I think the feature was mainly intended for copying coordinates into drawing commands. So adding a page would mean, that one must delete the extra information.
@egidioln: What do you think?

**Comment by egidioln** [comment]
> I think the feature was mainly intended for copying coordinates into drawing commands. So adding a page would mean, that one must delete the extra information. @egidioln: What do you think?

Hey! I would like if there was an option to customise the string copied to the transfer area, maybe exposing a formatting string settings for Ctrl+Shift+MouseClick?

**Comment by octaeder** [comment]
I think this is a quite special requirement and I see no nice solution. Maybe open a menu when you click. But then you always have to select what you want. And I wouldn't create a new config option for this. Building txs on yourself would be possible. The code change of `PDFDocument.cpp` is easy (s. the long line):

```c++
void PDFWidget::getPosFromClick(const QPoint &p){
	int page = pageFromPos(p);
	if (page < 0) return;
	const float ptToCm = 2.54 / 72; // 1pt = 1/72 inch = 2.54/72 cm.
	QRect r = pageRect(page);
	QPointF pos = (p - r.topLeft()) / totalScaleFactor();
	float height = (r.height()/totalScaleFactor()) * ptToCm;
	QClipboard *clipboard = QGuiApplication::clipboard();
	QString tmp;
	QTextStream(&tmp) << "" << pos.x() * ptToCm  << ", " << height- pos.y() * ptToCm << ", " << page + 1;
	clipboard->setText(tmp);
	//qDebug() << "Position: " << qPrintable(tmp) << "\n";
}
```

**Comment by pskumaresh06** [comment]
Thanks for your update. We will check this.
