### ISSUE TITLE
Annoying modal window "Calculating text width" 

### ISSUE THREAD

**Issue by FRuehl** [texstudio-org/texstudio#3824]
### Environment
TeXstudio: 4.8.4
Qt: 6.7.2 R
Apple M2 Pro
OS: Sequoia 15.0
TeX distribution: texlife

### Expected behavior
texstudio should do its job silently, without annoying messages. 

### Actual behavior
A modal window "Calculating text width" with a "Cancel" button pops up seemingly randomly which leads to input character drops. ("Auto-recompile ...", and tolltips disabled!)

### How to reproduce
See #3822

### Possible cause
The unnecessary and annoying modal window could be the result of a debug flag.

**Comment by sunderme** [comment]
the progress window is blocking because the process behind is blocking.
Just do not use "fit to text width" as txs needs to go through all pages to find the overall text width.
