### ISSUE TITLE
Make symbols side panel menu more identifiable as a drop-down menu (arrow, greek, misc symbols)

### ISSUE THREAD

**Issue by AlphaHasher** [texstudio-org/texstudio#3827]
### Describe the feature and the current behavior/state

More menus that have additional symbols that are used often inside the side panel (similar to Texmaker). Ones that I have in mind are:
1. Arrow
2. Greek
3. Misc symbols
 
![image](https://github.com/user-attachments/assets/a30faca6-fcc8-4702-a204-6e663a578071)

**Comment by octaeder** [comment]
what about this menu?

![grafik](https://github.com/user-attachments/assets/6c5217af-8a56-4a17-bcc2-25faba1f7cb4)

**Comment by AlphaHasher** [comment]
Oh, I did not see that menu. In that case I want to change this feature request to make this menu more identifiable as a drop-down menu.

**Comment by sunderme** [comment]
symbol panel is like this for years, no intention to change
