### ISSUE TITLE
Macros located inside an `\input{}` are unknown until the containing file is opened

### ISSUE THREAD

**Issue by jcasale** [texstudio-org/texstudio#3828]
### Environment
- TeXstudio: 4.8.5 alpha 1
- Qt: 6.7.2
- OS: Windows 11
- TeX distribution: Miktex

### Expected behavior

Opening a document containing macros in an `\input{}` file should recognize the macros in other files without first opening the input file.

### Actual behavior

All my macros show unknown and cannot be autocompleted until I open the file containing the macros.

### How to reproduce

1. Fetch the repro at [/jcasale/latex-repro](https://github.com/jcasale/latex-repro)
2. Open the `Repro.tex` file
3. Click through the `introduction` file
4. Take note of the unknown macro
    ![ts-initial](https://github.com/user-attachments/assets/c1d7ddd7-1d9e-4360-8fdd-50878332f3d6)
6. Click through the `macros` file
7. Take note of the known macro
    ![ts-final](https://github.com/user-attachments/assets/83d4b389-916e-4a9b-a44a-2eb93d67b276)

**Comment by octaeder** [comment]
have you checked Editor option `Automatically load included files`?

**Comment by jcasale** [comment]
Yes, the option to automatically load included files is enabled.
