### ISSUE TITLE
Labels not detected with memoir class

### ISSUE THREAD

**Issue by lempeo** [texstudio-org/texstudio#3829]
### Environment
- TeXstudio: 4.8.4
- Qt: 6.7.2
- OS: MacOS Ventura 13.7 (22H123)
- TeX distribution: TeX Live 2024

### Expected/actual behavior
Labels are not detected by TeXStudio with memoir class. The declaration of the name of the label is not colored as it should, and the label doesn't appear in the structure panel. Any reference to this label shows "Label missing", whereas the compilation produces no error, and of course autocompletion doesn't work either.

### How to reproduce

Compare this MWE:
> \documentclass{article}
> \begin{document}
> Here is a label\label{labelname}.
> Here is a reference to this label \ref{labelname}.
> \end{document}

which works perfectly fine (also with book class);

To this one:

> \documentclass{memoir}
> \begin{document}
> Here is a label\label{labelname}.
> Here is a reference to this label \ref{labelname}.
> \end{document}

which shows the problem.

Tested on a fresh TexStudio profile.

**Comment by lempeo** [comment]
Yes, I didn't go into this detail in my first post, but after a lot of different tries I've found that the labels **keep** being recognized after a simple change of class (article to memoir), but are not anymore recognized if their name is changed, and the same for new labels added. The opposite behavior is observed if one starts with memoir class with some labels, and change the class to article one: the labels already here keeps being unrecognized, but the new ones are recognized, and changing the name of the old ones make them recognized.

There's probably some cache involved in this "swing" mecanism I suppose.

**Comment by octaeder** [comment]
thanks
