### ISSUE TITLE
A default shortcut should be set for any new macro

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#383]
### Environment
- TeXstudio: 2.12.12 (git 2.12.10-193-g67e33f53
- Qt: 5.9.4
- OS: Linux Mageia
- TeX distribution: TeX Live 2018

### Actual behavior
When a new macro is added in the user macro dialog (menu Macro → Edit Macros...), the selected element in the "Shortcut" drop down list is the empty one.

### Expected behavior
When a new macro is added in the user macro dialog (menu Macro → Edit Macros...), a default shortcut (the first free in the Shift+F* list) should be selected in the "Shortcut" drop down list (it would be up to the user to change it if desired).

**Comment by sunderme** [comment]
not sure if I want that.
The advantage now is that the menu structure can be set more complex and easily with more than 10 macros. That the first macro is automatically bound to shift+F1, even if the users tend not to use shortcuts, the macros can be moved around etc.
I rather like the user to really want to have a (permanent) shortcut, which can be more complex.
For example ctrl+m + ctrl+a works as well.

**Comment by dbitouze** [comment]
>The advantage now is that the menu structure can be set more complex and easily with more than 10 macros.

OK.

>That the first macro is automatically bound to shift+F1, even if the users tend not to use shortcuts,

If the user doesn't want to use shortcut, it is harmless that the first macro is automatically bound to shift+F*.

> the macros can be moved around etc.

I don't see what you mean.

> I rather like the user to really want to have a (permanent) shortcut, which can be more complex.

A macro is supposed to be used quite often and providing a default shortcut was IMO a nice feature, especially for beginners (who are told the macros feature of TXS).

>For example ctrl+m + ctrl+a works as well.

I inserted "ctrl+m + ctrl+a" in the Shorcut drop down (data?) list but it doesn't work: "ctrl+m" is already bound to "Continue Find".

**Comment by dbitouze** [comment]
>"the macros can be moved around etc."
-> the "first" macro is not guaranteed to stay the first macro. Drag and drop works with the macro set-up.

OK, nice.

>My personal experience is that there are some often used macros of which I know the shortcut and then there are those used once in a while where the menu is handy.

OK but it is harmless that not often used macros have associated shortcuts.

>Especially with the possibility to directly download macros from the internet, assigning the first 10 to shortcuts is not really meaningful.

OK.

>"ctrl+m ctrl+a"...
unbind for it for "Continue find" (which I consider to do as default) and then ctrl+m ctrl+a works.

I cleared the "Current Shortcut" for "Continue Find" but now nothing happens when I hit "ctrl+m + ctrl+a" (letting the "ctrl" key hit, hitting the "m" key, hitting the "a" key and finally releasing the "ctrl" key).

**Comment by sunderme** [comment]
the syntax is "CTRL+M,CTRL+A"   (upper or lower case, the comma is important)

**Comment by sunderme** [comment]
I have thought about it a little more, and I won't change the behaviour.
The issue is that after creating n macros, user can change the shortcut to onme which may come up automatically later, they can remove macros with its shortcut, so a shortcut is free in the middle of the default shortcuts, etc. Too much hassle for too little gain.

**Comment by dbitouze** [comment]
> > the syntax is "CTRL+M,CTRL+A" (upper or lower case, the comma is important)
> 
> OK, it works now. IMO, this syntax should be documented.

Or, better, the user should be able to select macros shortcuts just as for ordinary shortcuts (#385).
