### ISSUE TITLE
Hiding and moving parts of documents

### ISSUE THREAD

**Issue by mirspan** [texstudio-org/texstudio#3830]
For larger documents, I would welcome: 

1. Hiding parts of the document that use /parts or /chapter. For example, using the space bar. 

2. Easily move parts of the document that use /parts or /chapter.

Everything would take place in the left column "Document Construction".

Another option is to automatically split the document into multiple files based on /parts or /chapter. File management would have to be improved with this.

**Comment by sunderme** [comment]
1) that is what code folding is for
2) structure view allows copy/cut/paste before&after on any sections/parts/chapters which allows moving around sections easily

There will be no automatic file splitting. This needs to be a user decision and it is easy enough (for something which is rarely used)
