### ISSUE TITLE
Completion for profmaquette package

### ISSUE THREAD

**Issue by jeanpat** [texstudio-org/texstudio#3835]
hello
There's no code completion for the package profmaquette (and profcollege or proflycee don't seem to be update)

### Describe the feature and the current behavior/state
Nothing happen when typing \begin{Maqu... nor \begin{exercice

### Who will benefit with this feature?
every teacher using these packages

Thanks for TexStudio

**Comment by sunderme** [comment]
txs offers completion for really a lot of packages, thanks to @mbertucci47.
If a package is not yet covered, it is easy for any user to provide this on his own (and can hand it in to us).
See also [wiki](https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions#why-does-a-command-not-show-up-in-the-completion)
