### ISSUE TITLE
Make horizontal space of "Line Numbers" smaller

### ISSUE THREAD

**Issue by hsvfan-jan** [texstudio-org/texstudio#3837]
### Describe the feature and the current behavior/state
Currently, the Line Numbers columns are pretty wide and take away too much horizontal space.
<img width="82" alt="Screenshot 2024-10-14 at 16 50 19" src="https://github.com/user-attachments/assets/4c754a55-e226-4a24-9dc9-52d0f21745de"> <img width="88" alt="Screenshot 2024-10-14 at 17 21 10" src="https://github.com/user-attachments/assets/bdcc45de-58cc-4dfd-9248-e13f4b800034">

Especially on a laptop in the 10"-14" screen size it'd be great to not waste any space. I think a few pixels would be enough.
It's currently about 3x the size of the line numbers' width in my example with the three-digit-numbers but about 5x the size for one- or two-digit numbers.
edit: I realize on the right hand side of the numbers there's the arrow to collapse or open a section, but on the left there's still a lot of unused space.
The freed up space could be used to have the PDF view larger or simply have more characters in a line before the end on the right hand side.

### Who will benefit with this feature?
Everyone without a ultra widescreen monitor or just someone who likes to have a bit more horizontal space.

**Comment by octaeder** [comment]
When I remember well minimum width for the numbers is 3 digits in all cases. For documents with more than 999 lines the number of digits for the max. line number is used. The rest to the left should be for labels (s. mouse cursor change to a pointing hand). Deactivating Adv. Edit option "Show Line Change State" would gain some pixels.

**Comment by hsvfan-jan** [comment]
With your comment in https://github.com/texstudio-org/texstudio/issues/3709 I see you mean bookmarks, not labels. They do indeed show up there, didn't know that.
Perhaps an option to collapse the width if no bookmark is used or display e.g. a red (colour of the current bookmark symbol) line, similar to how new lines are marked with a green line on the right? That'd be a nice "compact" solution imo

**Comment by octaeder** [comment]
the marks column to the left of the line numbers is used for bookmarks and marks of other kind: BadBox, Warning, and Error ![image](https://github.com/user-attachments/assets/1cfcd67a-6002-4212-be9c-e08ea06975e6)

You may also deactivate Editor option `Folding` to remove the folding column to the right of the line numbers.

**Comment by sunderme** [comment]
You can also turn-off line numbers, so that would help.
I have little intention to tweak settings here, mainly because I don't like horizontal shifts depending on the number of lines.
If you add the 10th line, the text width changes, again with 100th line. 
1000th is probably seldom enough.

**Comment by octaeder** [comment]
other options: reduce app text size or editor text size
Have you removed left side pane?
Have you removed the Central secondary toolbar?
![image](https://github.com/user-attachments/assets/990edaea-e1c9-4b60-9cca-06aa30c2dd60)

**Comment by hsvfan-jan** [comment]
> You may also deactivate Editor option Folding to remove the folding column to the right of the line numbers.
> Have you removed the Central secondary toolbar?
Didn't know these two were possible (or not how), thanks, that helped!

> the marks column to the left of the line numbers is used for bookmarks and marks of other kind: BadBox, Warning, and Error image
Those symbols only pop up when I click in the log on the warning/bad box/..., is that normal? (I hope you don't mind all the questions if this isn't the right space for it)

> You can also turn-off line numbers, so that would help.
I turned them on, default was one of the other settings iirc. The lines are helpful when checking errors and such so I'd rather have them stay on.

> I have little intention to tweak settings here
I see, figured that! Thanks you two for pointing out so many other options, though.

**Comment by sunderme** [comment]
As there are no plans to change anything, I close this.
