### ISSUE TITLE
Integrating Grammarly

### ISSUE THREAD

**Issue by khaihanhtang** [texstudio-org/texstudio#3839]
Is it possible to make Grammarly work with TexStudio? 

I usually write scientific papers due to its fast compiling time, convenience for using offline, and good rendering of preview of the pdf.

However, when submitting the manuscript proposed from TexStudio, I need to migrate the source code to Overleaf to make Grammarly work for checking grammar and typos, as Grammarly works with well the browser.

It would be great if you can make this feature for TexStudio.

**Comment by sunderme** [comment]
Grammarly does not offer an API for txs to use, so I see no way forward.
They claim, their desktop app can work with any program, so that is probably the intended way.

**Comment by muzimuzhi** [comment]
Previous discussion:
- #528
