### ISSUE TITLE
Shortcuts changed from within config menu not propagated back to macro dialog

### ISSUE THREAD

**Issue by thatlittleboy** [texstudio-org/texstudio#384]
### Environment
- TeXstudio: 2.12.12 beta1 8b6b025 
- Qt: 5.8 
- OS: Win 10
- TeX distribution: MikTeX 

Similar to #381 but the reverse this time.

### Actual behavior
Manually changing the shortcut of a macro from within the shortcuts menu (`Config TXS -> Shortcuts -> Macros -> ...`); the changes are updated in the main toolbar (`Macros -> ..`) but not in the 'shortcut' field of the user macro dialog.

If the user does not enter the user macro dialog again after this, and quits TXS, the changes are hence not updated in the `.txsmacro` file as well.

### Expected behavior
Changes to a macro's shortcut from within the config dialog should propagate _back_ to the shortcut field in the user macro dialog. 

### How to reproduce

1. Create a new macro.
2. Open the Config dialog, change the macro's shortcut from within the config dialog. Here I changed from default `Shift+F1` to `Shift+F2`.

![texstudio_2018-11-13_20-48-44](https://user-images.githubusercontent.com/30731072/48454534-8dc58980-e785-11e8-9436-eb05090489b9.png)

3. Click ok, Exit the window, The changes are updated to the main toolbar (ok..) It should be noted that at this point in time, the actual, working shortcut is `Shift+F2`, the changed version.

![texstudio_2018-11-13_20-49-41](https://user-images.githubusercontent.com/30731072/48454567-ad5cb200-e785-11e8-9c26-6d48f2b08ccd.png)

4. But not in the user macro dialog:

![texstudio_2018-11-13_20-50-33](https://user-images.githubusercontent.com/30731072/48454590-c5cccc80-e785-11e8-956a-2e4e7e8e3cd9.png)

**Comment by sunderme** [comment]
fixed
