### ISSUE TITLE
Master branch successfully compiled but fails to run

### ISSUE THREAD

**Issue by ashinpan** [texstudio-org/texstudio#3840]
### Environment
- TeXstudio: master
- Qt: 6.7.3
- OS: Linux Mint 22
- TeX distribution: texlive 

### Expected behavior
Having been built successfully with QT 6.7.3, it should run from the command "texstudio". 

### Actual behavior

Texstudio crashed at start with the following message:
texstudio: /usr/lib/x86_64-linux-gnu/libQt6Qml.so.6: no version information available (required by texstudio)
texstudio: /usr/lib/x86_64-linux-gnu/libQt6Core.so.6: version `Qt_6.7' not found (required by texstudio)
texstudio: /usr/lib/x86_64-linux-gnu/libQt6Core.so.6: version `Qt_6.7' not found (required by /home/pan/Qt/6.7.3/gcc_64/lib/libQt6Svg.so.6)
texstudio: /usr/lib/x86_64-linux-gnu/libQt6Core.so.6: version `Qt_6.7' not found (required by /usr/local/lib/libquazip1-qt6.so.1.4.0)
texstudio: /usr/lib/x86_64-linux-gnu/libQt6Core.so.6: version `Qt_6.7' not found (required by /home/pan/Qt/6.7.3/gcc_64/lib/libQt6MultimediaWidgets.so.6)
texstudio: /usr/lib/x86_64-linux-gnu/libQt6Core.so.6: version `Qt_6.7' not found (required by /home/pan/Qt/6.7.3/gcc_64/lib/libQt6Core5Compat.so.6)
texstudio: /usr/lib/x86_64-linux-gnu/libQt6Core.so.6: version `Qt_6.7' not found (required by /home/pan/Qt/6.7.3/gcc_64/lib/libQt6Multimedia.so.6)
texstudio: /usr/lib/x86_64-linux-gnu/libQt6Core.so.6: version `Qt_6.7' not found (required by /usr/local/lib/libpoppler-qt6.so.3)
### How to reproduce

1. Install the latest QT (It is Qt 6.7.3 in my case, and installed in the home partition)
2. Clone texstudio github (master) branch. 
3. make a new folder, to be named "build," in the downloaded texstudio folder. 
4. cd into build, cmake-gui .. to open the cmake dialog box. 
5. configure, generate files, and close the dialog box. 
6. command line (make all, make install) 
7. Then try to run "texstudio" 

Please note that the path of Qt 6.7.3 is given in the .profile file as well as in the qt6.conf (etc/ld.so.conf.d)

**Comment by sunderme** [comment]
The error messages state:
```
/usr/lib/x86_64-linux-gnu/libQt6Core.so.6: version Qt_6.7' not found (required by /home/pan/Qt/6.7.3/gcc_64/lib/libQt6Svg.so.6
```
That indicates that Qt is installed/was compiled in /home/pan & /usr/lib 
The Qt setup is messed up. If you know what you are doing, LD_LIBRARY_PATH can help but that is something you have to solve on your system.

**Comment by sunderme** [comment]
maybe one short advice: the simplest way to build txs against latest qt, is using the script qt-cmake which is provided by Qt (in their bin folder).
If you need to adapt paths for cmake or need to use cmake-gui, you have already lost.

**Comment by ashinpan** [comment]
@sunderme Well, I use cmake-gui provided by the latest Qt (in home partition), because it is easier for me to change options in compiling txs. I cannot see how cmake and cmake-gui both provided by Qt can be different. 

Anyhow I have solved the problem by uninstalling qt6 "include" and "library" files in /usr. 

What I don't understand is why the qt6.conf file in /etc/ld.so.conf.d fails to work, since it is in that file that the default qt6 lib is defined as the latest one present in the home directory. Anyhow, this should be the problem of Linux Mint / Ubuntu, not of txs.
