### ISSUE TITLE
Mouse behavior completely unusable in Qt6 version (4.8.4).

### ISSUE THREAD

**Issue by ExecutorElassus** [texstudio-org/texstudio#3842]
### Environment
- TeXstudio: 4.8.4
- Qt: 6.7.3
- OS: Gentoo Linux
- TeX distribution: texlive

### Expected behavior
When I use the primary mouse button to click menus, dropdowns, the editor field, etc., it should behave like the primary mouse button

### Actual behavior
the primary mouse button doesn't appear to do anything, except that occasionally the context menu appears _only while the button is pressed_. The cursor does not move to the line number where I click the primary mouse button. Clicking a menu only works with the _secondary_ mouse button (in my case, the right-click). None of the buttons in, for example, the Options window respond to the primary mouse button, only the secondary. 

This behavior only happened when I upgraded from 4.8.1 (which uses Qt5) to 4.8.4 (which uses Qt6). This may be a problem with Qt6 itself: when I use qt6ct to set the Qt6 theme, that window also behaves erratically. 

I am not using a WM with integrated Qt; I'm using FVWM, so there's no WM-level Qt integration. 

### How to reproduce
Use a non-integrated WM with Qt6.

**Comment by sunderme** [comment]
That sound like a Qt/WM/Gentoo issue.
Nothing we can do.

**Comment by ExecutorElassus** [comment]
Fair enough. Welp, guess it's StackOverflow and the gentoo forum for me! Thanks for the help.
