### ISSUE TITLE
Crash after waking up from sleep on macOS

### ISSUE THREAD

**Issue by hsvfan-jan** [texstudio-org/texstudio#3843]
### Environment
- TeXstudio: 4.8.4
- Qt: 6.7.2
- OS: macOS 15.0.1
- TeX distribution: texlive

### Expected behavior
Don't crash.

### Actual behavior
After writing I just closed the lid which caused the Mac to go to "sleep". A few hours later, after opening the lid of my laptop and giving the password, the app crashed immediately. I had the laptop connected to a TV as a second monitor via USB-C/HDMI.
edit: Also, I just noticed despite the app having crashed and being able to open the app again, there was another instance of texstudio open. The second instance was still there in one of the fullscreen spaces. Now when I close the app with Cmd+Q, it closes the instance that is in the normal "desktop space" but still has another frozen version "running" in one of the fullscreen spaces.

I also have a full crash report but I'm not sure if there are sensitive information inside that shouldn't just be posted online without care. I already checked that filepaths don't contain my local username but I don't know whether things like UUIDs can be used to gain any information. Is it common practice to upload the file from /Users/user/Library/Logs/DiagnosticReports/texstudio-2024-10-18-235211.ips to GitHub or is there another way? Should I redact certain parts of the file instead?

### How to reproduce
Not sure, happened only once so far.

**Comment by sunderme** [comment]
the backtraces do not contain sensitive information.
That said, txs does not do anything special when the mac is asleep, so until now that crash is a Qt/Mac issue.
That said, newer version of Qt may help here, so you can try out the latest dev build.
Apart from that, nothing we can do.

**Comment by hsvfan-jan** [comment]
> the backtraces do not contain sensitive information.

Thanks for the info!

> That said, txs does not do anything special when the mac is asleep, so until now that crash is a Qt/Mac issue.
That said, newer version of Qt may help here, so you can try out the latest dev build.
Apart from that, nothing we can do.

Got it, closing then
