### ISSUE TITLE
Issues in my Mac

### ISSUE THREAD

**Issue by Forkeey** [texstudio-org/texstudio#3845]
### Describe the feature and the current behavior/state

Returning to the texstudio editing page after a Mac cuts the screen does not return to the position where you were just editing, but only stays at a specific position. It also appears that the PDF cannot be swiped up and down.

**Comment by sunderme** [comment]
txs relies on qt for this kind of things.
You can try the latest dev. version of txs which also come with newer wt versions.
Apart from that. there is nothing we can do.
