### ISSUE TITLE
Add opitions autocompletion for frame enviroment of beamer

### ISSUE THREAD

**Issue by tercelxy** [texstudio-org/texstudio#3846]
Is it possible to implement auto-completion for opitions within the frame environment of beamer to improve user experience?

If feasible,  I suggest adding code similar to the following to the relevant cwl file.

\begin{frame}[opt%keyvals]{title}
\againframe[opt%keyvals]{name}
#keyvals:\begin{frame},\againframe
allowframebreaks
allowframebreaks=%<fraction%>
b
c
t
s
noframenumbering
fragile
fragile=singleslide
label=##l
plain
shrink
shrink=%<min shk %%%>
squeeze
#endkeyvals

Thank you.

**Comment by sunderme** [comment]
implemented
