### ISSUE TITLE
French dictionary impossible to install

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#3847]
### Environment
- TeXstudio:  4.8.5 (git 4.8.5alpha1-22-gab76168fd)
- Qt: version 6.4.1
- OS: Linux Mageia 9/Linux Ubuntu/macOS
- TeX distribution: not relevant

### Expected behavior
The French dictionary can be enabled/installed.

### Actual behavior
Some users (on Ubuntu and on macOS) reported that the French dictionary cannot be enabled/installed anymore.

### How to reproduce
When they go to Option → Configure TeXstudio → Language Checking, they are advised to ‘Download additional dictionaries from OpenOffice or LibreOffice’. The French dictionary is [this extension](https://extensions.libreoffice.org/en/extensions/show/dictionnaires-francais) but after downloading the `.oxt` file, when they try to ‘Import the dictionary’ by selecting the `lo-oo-ressources-linguistiques-fr-v5-2.oxt` file, the popup ‘The selected file does not seem to contain a Hunspell dictionary. Do you want to import it nevertheless?’ appears. If they click on ‘Yes’, (they are eventually presented with the popup ‘The dictionary files have been imported to %1. However this path is not contained in the dictionary path list. Do you want to add it?’ If they click ‘Yes’,) nothing happens and the French dictionary is not activated/installed.

**Comment by sunderme** [comment]
Linux:
txs uses hunspell dictionaries. 
**All** linux distributions provide hunspell dictionaries, so on linux just install the french dictionary, make sure that dictionary path is set to /usr/share/hunspell and select the dictionary.
OSX:
txs provides tens of languages, including French.
The path (which should be the default), is ` [txs-app-dir]/../Resources`.

Handling oxt files is usually not needed.

**Comment by sunderme** [comment]
and the import still works.
The dictionaries are actually placed under `[txs-settings-dir]/dictionaries/lo-oo-ressources-linguistiques-fr-v5-2.oxt/dictionaries`

**Comment by dbitouze** [comment]
> Linux: txs uses hunspell dictionaries. **All** linux distributions provide hunspell dictionaries, so on linux just install the french dictionary, make sure that dictionary path is set to /usr/share/hunspell

Sure all Linux distributions install `hunspell` in `/usr/share/`?

> and select the dictionary.

But if you click on the ‘Import Dictionary’ button to select a dictionary, only `.oxt` files can be opened.

>OSX: txs provides tens of languages, including French. The path (which should be the default), is ` [txs-app-dir]/../Resources`.

Not sure to understand what you mean (I'm not a macOS user and can't look at its file system).
 
> Handling oxt files is usually not needed.

See above.

>The dictionaries are actually placed under [txs-settings-dir]/dictionaries/lo-oo-ressources-linguistiques-fr-v5-2.oxt/dictionaries

If I'm right, this supposes to extract the (in fact zip file) `lo-oo-ressources-linguistiques-fr-v5-2.oxt` and to copy the resulting folder into `[txs-settings-dir]/dictionaries/`, the `dictionaries` folder being manually created if it doesn't exist beforehand. Do you confirm?

**Comment by sunderme** [comment]
"select a dictionary" is *not* "import dictionary"
red marked: dictionary path, *here* you put `[txs-app-dir]/../Resources`on OSX
green marked: select (default) dictionary
![grafik](https://github.com/user-attachments/assets/20244870-6654-444e-ba5d-691318e84e1a)

**Comment by sunderme** [comment]
the "import dictionary" button extracts the oxt file. Apparently it used have only one folder which was directly copied to [settings]/dictionary but now it has more subfolders, all of it is copied to settings../dictionaries, keeping the folder structure of the oxt, and txs does not find the actual dictionaries directly.

**Comment by dbitouze** [comment]
> "select a dictionary" is _not_ "import dictionary" red marked: dictionary path, _here_ you put `[txs-app-dir]/../Resources`on OSX green marked: select (default) dictionary

Ah... If you had said ‘Select default language’, I would have understood on my own. :wink:

**Comment by sunderme** [comment]
I think, this is answered
