### ISSUE TITLE
Biblatex not compiling with bibtex default bibliography tool

### ISSUE THREAD

**Issue by zhou31415** [texstudio-org/texstudio#3849]
### Environment
- TeXstudio: <4.7.2>
- Qt: <6.6.0>
- OS: <Mac OS Sonoma 14.6.1>
- TeX distribution: <Tex Live 2024>

### Expected behavior
The following .tex and .bib files compile fine in Overleaf, but not in TexStudio. I am using Biblatex but want to keep Bibtex as my default bibliography tool (vs biber). This is because some of my files have bibtex bibliographies, so I don't want to have to change the settings between biber and bibtex when dealing with different files. I was under the impressions that Biblatex did work with bibtex.  

```
\documentclass[]{article}
\usepackage[style=numeric]{biblatex}
\addbibresource{references.bib}

%opening
\title{\texttt{Biblatex} MWE}

\begin{document}

\maketitle

First source to be cited \parencite{TaoBook} 

\printbibliography


\end{document}
```

```
@book {TaoBook,
	AUTHOR = {Tao, Terence},
	TITLE = {Topics in random matrix theory},
	SERIES = {Graduate Studies in Mathematics},
	PUBLISHER = {American Mathematical Society, Providence, RI},
	YEAR = {2012},
}
```

The result of the compiling in Overleaf (which works) is here: 

<img width="625" alt="Screenshot 2024-10-19 at 5 28 21 PM" src="https://github.com/user-attachments/assets/c0578dc3-bf1c-419b-b264-f9366ffe7c5c">

### Actual behavior
The result of the compiling in TexStudio (which fails) is here: 

<img width="432" alt="Screenshot 2024-10-19 at 5 25 45 PM" src="https://github.com/user-attachments/assets/88d08e0f-026a-4f33-a6cb-5ab7d4933dea">

### How to reproduce
Here are my settings. Again, I have bibtex chosen as my default bibliography tool, because I don't want to switch between biber/bibtex when editing different files that have bibtex/biblatex bibliographies. 

<img width="1369" alt="Screenshot 2024-10-19 at 5 21 21 PM" src="https://github.com/user-attachments/assets/b75a976a-f229-4360-a4cd-d9b782a80c92">

**Comment by muzimuzhi** [comment]
Just need to add `% !TeX TXS-program:bibliography = txs:///biber` as the first line in your main tex file. See more info in https://texstudio-org.github.io/advanced.html#advanced-header-usage.

**Comment by sunderme** [comment]
txs only call bibtex as instructed. If that tool does not deliver, but biber does, there is nothing txs can do.
