### ISSUE TITLE
Can't run TeXStudio under macOS 15

### ISSUE THREAD

**Issue by RicanStark** [texstudio-org/texstudio#3850]
I get the "Apple could not verify that “texstudio-4.8.4-osx-m1” is free of malware that could damage your Mac or violate your privacy." notification, without an option to run the program anyways.

I found a similar issue from 2021 (#1431), but the solution from back then doesn't work anymore (just moving the downloaded .app file into Applications and running it via right click yields the same outcome as described above).

Any fixes available?

**Comment by dbitouze** [comment]
See “Mac OS X” section [here](https://texstudio.org/#download).

**Comment by RicanStark** [comment]
> See “Mac OS X” section [here](https://texstudio.org/#download).

Same result. Ctrl + Click, then "open" only yields the above mentioned error message, without an option to actually run the program.

**Comment by sunderme** [comment]
google: https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac

**Comment by RicanStark** [comment]
> google: https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac

Thanks, that did the trick. Man, Apple can really be butthurt about people that don't conform to their Developer Account stuff, huh.

**Comment by dbitouze** [comment]
> google: https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac

Maybe a link to this page should, at https://texstudio.org/#download, replace the text:

>Please note: Because we do not have an Apple Developer Account, OS X may complain about an [unidentified developer](http://support.apple.com/kb/PH14369) and deny opening TXS. In that case, open the context menu on the TXS icon (Ctrl + Click) and select open.

- First advantage: the content of this page will be up to date.
- Second advantage: it is automatically localized.

**Comment by sunderme** [comment]
the link on texstudio.org is already updated

**Comment by dbitouze** [comment]
> the link on texstudio.org is already updated

Sorry, there is indeed a link (http://support.apple.com/kb/PH14369) on “unidentified developer” but it is currently dead. Should be replaced by https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac.

**Comment by sunderme** [comment]
now it is life
