### ISSUE TITLE
Supertabular(packakge) head and tail declarations are not identified as table environment in a single table document.

### ISSUE THREAD

**Issue by KazamaHoshino** [texstudio-org/texstudio#3852]
### Environment
- TeXstudio: 
- Qt: 6.7.2
- OS: Win11
- TeX distribution: miktex(Ctex)

### Expected behavior
\hline, booktabs, & symbol in supertabular tail and head declarations are not identified as syntax error; 

### Actual behavior
\hline, booktabs, & are highlighted, Texstudio tells me that "should be used in table environment only"

### How to reproduce
create an Article document with ouly a single supertabular.

### Note
 In another Report document, where supertabular is put inside a Chapter, this error could not be reproduced.
An error which does not prevents success compiling that i might not fully understand:

Running in backwards compatibility mode (unsuitable tick labels; missing features). Consider writing \pgfplotsset{compat=1.18} into your preamble.

**Comment by sunderme** [comment]
Please copy the complete example text into the report.
I don't want to start guessing

**Comment by KazamaHoshino** [comment]
> Please copy the complete example text into the report. I don't want to start guessing

Right, Please wait for a few days for me to reproduce again and bring in the code; I have changed the document into longtable and there are some business info inside the doc which need to be replaced.

**Comment by sunderme** [comment]
I think we can close this.
Not sure how well used supertabular is, I don't think it is worthwhile to write special code for that package.
