### ISSUE TITLE
Open the location in bibtex file from PDF

### ISSUE THREAD

**Issue by ashokreddy333** [texstudio-org/texstudio#3855]
Hello, 
 I thought the following feature would be great addition to TexStudio. 
 When we click (Ctrl+click) on a reference in the reference list of PDF file, application will open and point to the entry in the XX.bib file.

### Describe the feature and the current behavior/state
Currently, when we click on the list of references, it does not take us anywhere in the text file editor side. 

### Who will benefit with this feature?
Most people who use the TexStudio with bib file for managing the references. 

Thanks

**Comment by muzimuzhi** [comment]
Need to check whether the required information is recorded by SyncTeX.

**Comment by sunderme** [comment]
I don't think that is possible (with reasonable effort)
