### ISSUE TITLE
Configuration setting for syntax highlighting is reset every time the application is closed

### ISSUE THREAD

**Issue by ashokreddy333** [texstudio-org/texstudio#3856]
### Environment
TeXstudio 4.8.3 (git 4.8.3)
Using Qt Version 6.7.2, compiled with Qt 6.7.2 R
OS: Windows 11
Tex distribution: Texlive

### Expected behavior
When we save the TexStudio configuration, it should stay saved. When we open next time, it should start with the old saved configuration. 

### Actual behavior

For the syntax highlighting configuration, the setting corresponding to "braceMatch" is not retrieved after restarting the computer. 

### How to reproduce
1. Save this changed setting mentioned above (braceMatch). 
2. Check it is working 
3. Restart the computer.
4. Check if the saved setting is still effective.

**Comment by sunderme** [comment]
please be precise what exactly you change and is not saved. Screenshots help.

**Comment by ashokreddy333** [comment]
Not reproducible with the latest version.
