### ISSUE TITLE
texstudio-4.8.5beta1-win-portable-qt6.zip doesn't run

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3866]
### Environment
- TeXstudio: 4.8.5beta1 portable downloaded from the releases web page
- Qt: I think it's 6.8.0
- OS: Windows(10 home)
- TeX distribution: miktex

### Expected behavior
txs should start as usual

### Actual behavior
I see the splash screen then the front end. After some seconds the app disappears from the screen. I'm surprised because some minutes before I tried successfully portable versions of 4.8.3, 4.8.4 and 4.8.5alpha1.

**Comment by sunderme** [comment]
fixed with 4.8.5beta2 (qt bug)

**Comment by jcasale** [comment]
Thank you, 4.8.5beta2 is working fine with several projects.
