### ISSUE TITLE
Feature request: Extracting references for citation by online searching

### ISSUE THREAD

**Issue by sahaskn** [texstudio-org/texstudio#388]
Dear TexStudio developer,

Thanks for this wonderful software.

If possible, making bibliography entry by searching online or by actual link to online paper, would be highly appreciable feature.

**Comment by timhoffm** [comment]
Refined bibliography management is beyond the scope of TeXstudio. We suggest that you use existing tools such as JabRef, that are specialized on this. There is the possibility to easily insert citations from JabRef into TeXstudio.

If that‘s not sufficient I‘d rather improve the integration between TeXstudio and bibliography tools than reinventing the wheel and adding a full bibliography management to TeXstudio.

**Comment by koppor** [comment]
For the googlers: The documentation of JabRef's feature is available at https://docs.jabref.org/cite/pushtoapplications.
