### ISSUE TITLE
incorrect "cols in tabular missing"

### ISSUE THREAD

**Issue by pagenum** [texstudio-org/texstudio#3881]
### Environment
- TeXstudio: 4.8.4
- Qt: 6.7.2
- OS: Windows10
- TeX distribution: texlive2024

### Expected behavior
No highlight for "`\\`"

### Actual behavior
Highlighted "`\\`", mouse move onto "`\\`", a message :"cols in tabular missing" showed

### How to reproduce
```
\begin{NiceTabular}{|m[l]{185pt}|m[c]{110pt}|c|c|m[c]{42pt}|m[c]{42pt}|}
			\Hline
			1 & 1 & 1 & 1 & 1 & 1 \\
			\Hline
		\end{NiceTabular}
```

**Comment by pagenum** [comment]
> the issue is the `m[c]` definition. If you can provide the package and a clean definition on how this is supposed to work, I may add it to txs.

https://ctan.math.washington.edu/tex-archive/macros/latex/contrib/nicematrix/nicematrix.pdf

**Comment by muzimuzhi** [comment]
In the table preambles of `nicematrix` table environments, specifiers `|` (vertical table line), `p{...}`, `b{...}`, `m{...}`, `V{...}`, and `X{....}` all accept an optional argument.

`texdoc nicematrix` (v6.29b, 2024-11-12)
- sec. 4.2 The mono-column blocks
  > For a block in a column of type `p{...}`, `b{...}`, `m{...}`, `V{...}` or `X`, the alignment `c` will be used by default. However, those types of columns may have an optional argument for the horizontal alignment (eg: `p[l]{...}`) and, in that case, that type of
alignment is passed to the block.
- sec. 5.3 The tools of nicematrix for the rules
  > As well as the command `\Hline`, the specifier “`|`” supports an optional argument between square brackets for the characteristics of the rule.

`texdoc nicematrix-code`
- sec. 11 Construction of the preamble of the array
  > The specifier `p` (and also the specifiers `m`, `b`, `V` and `X`) have an optional argument between square brackets for a list of _key-value_ pairs. Here are the corresponding keys.

**Comment by sunderme** [comment]
a bit subtle as documentation goes, but okay.
