### ISSUE TITLE
Where to know what command will be executed with click [Help]>[Check LaTeX Installation]?

### ISSUE THREAD

**Issue by Explorer-cc** [texstudio-org/texstudio#3882]
### Environment
- TeXstudio:  4.8.4
- Qt:  I's not sure, if needed, I will implement
- OS:  Windows 11
- TeX distribution:  TeXLive2024

### Description

When I click the Toolbar [Help] -> [Check LaTeX Installation] > It show the below that:

The CJK character is here that: `where pdflatex: Error: "path:pattern" assign the invalid patterns` in red rectangle.

![image](https://github.com/user-attachments/assets/49a3d5b6-9d80-457e-b590-a9f1b9c6ffce)

But when I try to check the PATH with cmd on windows 11, it shows that everything go right as below. And with the `compile` button, `pdflatex` works normally and I can get the PDF file normally.

![image](https://github.com/user-attachments/assets/8c3119d6-bdf4-4ae3-8947-4bff87e02f95)

I wonder the behaviour of `Check LaTeX installation`, what commands will be executed after clicking the button, I have consulted from the [documanetation](https://texstudio-org.github.io/index.html) but didn't found some related to that. And how to make TeXstudio found the `pdflatex.exe` here?

**Comment by sunderme** [comment]
txs just runs the command `where pdflatex`. The rest is already output of that command.

**Comment by Explorer-cc** [comment]
@sunderme Could you provide me an example that the output `where pdflatex: Error: "path:pattern" xxxx` is generated by which `command`? is that I run `where pdflatex` in Command Line?

**Comment by sunderme** [comment]
yes, run in in "cmd.exe"

**Comment by Explorer-cc** [comment]
Yes, in `powershell` I need to use `where.exe pdflatex` to show the output. Thanks!
