### ISSUE TITLE
FR: Project-Specific cwl files and/or magic comment

### ISSUE THREAD

**Issue by incaseoftrouble** [texstudio-org/texstudio#3883]
### Describe the feature and the current behavior/state

Right now, cwl files need to be stored in a machine-local directory (according to the README). This makes it difficult to sync them across multiple devices / users. Especially larger projects (e.g. academic papers or lectures) define custom commands which the automatic completion only parses sub-optimally (e.g. if there is a lot of conditionals involved). These projects are also often shared / synchronized via git.

Example: Each slide set of a lecture may have `\input{../header}` or `\documentclass{lecture}` which reference files contained in within the project. Keeping a .cwl file in the project and then copying it to the settings folder every time is possible but tedious.

Proposed change: Introduce a way to include project specific .cwl files. I see two options:

 * Whenever there is a `\input{x}` or `\documentclass{x}` check if `x.cwl` exists (relative to the root document)
 * Add `% !TeX completion = path.cwl` (repeatable) that allows defining cwl files.

I think the second is best. If someone is able to write a cwl they probably are also able to utilize magic comments. This would also be nice as it allows to easily define completion for a hierarchy of included `.tex` files. I'm often too lazy to define a `.sty` and just have a bunch of `.tex` files that are included :-) Being able to `\input{macros}` + `% !TeX completion = macros.cwl` would be superb.

I had a look whether there is a related issue or note in the readme but couldn't find anything. Since cwl files can just be copied manually into the settings folder, this has fairly low priority.

### Who will benefit with this feature?

Users involved in a project (a) with someone who is willing to maintain a .cwl file (b) that is synced to multiple devices.

**Comment by sunderme** [comment]
`\input{x}` will not use x.cwl.
\input is used for loading child documents, cwl is only associated to `\usepackage`.
but searching cwl in the root directory may be feasible.

**Comment by incaseoftrouble** [comment]
> \input{x} will not use x.cwl.

Right, thinking about it, this makes sense. I think magic comment in the root document might be a good solution.

> cwl is only associated to \usepackage.

On that note: Maybe magic comment / cwl search in the directory where the package is located? I probably wouldn't use it but it may be relatively easy to add if the above is implemented.

I'm not too proficient with C/C++, so I probably can't contribute any implementation, but I could write documentation / help.

**Comment by sunderme** [comment]
imlemented

"When a usepackage refers to a local file with a relative path ("."
needed as first character), txs looks for packageName.cwl as the
corresponding cwl file and loads it."
