### ISSUE TITLE
Syntax error highlighting problem

### ISSUE THREAD

**Issue by jcasale** [texstudio-org/texstudio#3885]
### Environment
- TeXstudio: 4.8.5 beta 2
- Qt: 6.8.0
- OS: Windows 11
- TeX distribution: miktex

### Expected behavior
Projects that embed macros in files using `\input` statements should correctly incorporate those definitions into the error-checking semantics.

### Actual behavior
The repro package contains a `tcolorbox` definition that is highlighted as an error when opening the project.

If I open the project and load the `macros.tex` file into the editor, the erroneous highlighting disappears.

I've observed a few other possibly related details:
* The `macros.tex` file always highlights the color definitions at the top of the file as errors inside the `tcolorbox` definitions
* I frequently encounter primitives and other latex commands that get highlighted as errors, too (e.g., `nameref`). When this manifests, virtually everything gets marked as an error, and I need to restart TS to solve this.

I have the following settings enabled that I assume may be related and important:
* Automatically load included files
* Cache documents for faster reopening

![Screenshot 2024-11-21 113026](https://github.com/user-attachments/assets/c74f6cb7-ac4d-4080-bc9e-58e0f40ef406)

![Screenshot 2024-11-21 114532](https://github.com/user-attachments/assets/817be58e-ab85-4da6-8fe1-53c3af082045)

### How to reproduce
The repro at [jcasale/latex-repro](https://github.com/jcasale/latex-repro) contains the reproduction project.

1. Open the `repro.tex` main project file.
2. Open the `introduction.tex` file and observe the erroneous highlighting.
3. Open the `macros.tex` file, then switch back to the `introduction.tex` file and observe the correct highlighting.

**Comment by muzimuzhi** [comment]
Looks like TeXstudio doesn't auto append the `.tex` file extension. Changing `\input{macros}` to `\input{macros.tex}` does the trick.

**Comment by jcasale** [comment]
I figure TeXstudio should match the behavior of the compiler for `\input` and `\include`, however it looks like there is some variation between implementations and platforms.

**Comment by sunderme** [comment]
fixed with 0177cc44d6189f4f6190bc727deed36cdadd72e8

**Comment by jcasale** [comment]
@sunderme The problem is resolved with the repro project, but my actual project still suffers from the problem.

I originally built the MRE with the subfiles package, but while simplifying the MRE, I found the problem still existed with just an `\input` command, so I removed the `\subfile` command thinking it was of no value (I even forgot to remove the package reference).

However, the problem still exists with subfiles and the fix above. Is this something that can be fixed easily?

Thank you very much for the above fix.

**Comment by sunderme** [comment]
it is not the subfikle but the caching. Anyway, that should be fixed now as well.

**Comment by jcasale** [comment]
@sunderme I can confirm that solves my problem.

Thank you very much, that is a big improvement for me.

**Comment by jcasale** [comment]
@sunderme I have found another instance of the highlighting problem with a new definition.

Would it be best for you if I opened a new issue and referenced this one?

**Comment by sunderme** [comment]
New issue
