### ISSUE TITLE
New files are not centered in the editor

### ISSUE THREAD

**Issue by homocomputeris** [texstudio-org/texstudio#3886]
### Environment
- TeXstudio 4.8.4 (git 4.8.4)
- Using Qt Version 6.7.2, compiled with Qt 6.7.2 R
- OS: macos 15.1.1 (24B91)
- TeX distribution: mactexlive

### Expected behavior
Center files is editor when created.

### Actual behavior
New files are not centered in the editor. Sometimes files are not centered when opened.
The workaround is to re-check "Center document in editor" every time a new file is created.

https://github.com/user-attachments/assets/74f5a699-299b-458f-9e29-145887bdc71a

### How to reproduce
1. Check "Center document in editor" in "Adv. Editor"
2. Create a file.

**Comment by octaeder** [comment]
What are the following settings?

![grafik](https://github.com/user-attachments/assets/2e4df36e-f9be-43ee-a5e4-e019bb37da93)

**Comment by homocomputeris** [comment]
Soft wrap after max.
80.
Checked.
