### ISSUE TITLE
text highlighted as math after $ inside \Sexpr{}

### ISSUE THREAD

**Issue by antduarte** [texstudio-org/texstudio#389]
When using Knitr, if $ is used inside \Sexpr{}, everything after $ is highlighted as math (in green). Can this be fixed or worked arround?

### Environment
- TeXstudio: 2.12.10
- Qt: 5.8.0
- OS: Windows 10
- TeX distribution: miktex

### How to reproduce
For example, \Sexpr{d$x * 100}

**Comment by sunderme** [comment]
fixed in repository
