### ISSUE TITLE
adding a caption to the appstream metadata

### ISSUE THREAD

**Issue by ItsGamerik** [texstudio-org/texstudio#3890]
### Describe the feature and the current behavior/state

Currently, there is no caption for the screenshot in the appstream application description, I would propose to add a short description with the `<caption>` tag.

Something like `<caption>The TexStudio main window showing a TeX document and the rendered file</caption>` would probably suffice.

### Who will benefit with this feature?

Not having a caption for the screenshot generates a warning during the flatpak build process, so it would be nice to see one added. Even though it is not a requirement, it would just be nice to have for completeness

### Any Other info
relevant quote from the appstream documentation:

>defining a short (ideally not more than 100 characters) description of what the user can see on the referenced screenshot

links:
- [appstream screenshot tag](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-screenshots)
- [flatpak documentation](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#screenshots)

**Comment by sunderme** [comment]
what page are you talking about ?

**Comment by ItsGamerik** [comment]
This is referring to [texstudio.metainfo.xml](https://github.com/texstudio-org/texstudio/blob/master/utilities/texstudio.metainfo.xml). It is linted during the flatpak build process which generates the warning in accord with the flathub documentation.
