### ISSUE TITLE
unexpected silent update of text after first confirmation

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3895]
### Environment
- TeXstudio: current dev rc1 (local msys2 build)
- Qt: 6.8.0
- OS: Windows(10)
- TeX distribution: miktex

### Expected behavior
Anytime an external update of an file happens txs should ask for what to do

### Actual behavior
When the file is open simulatiously in txs and an external editor (e.,g. notpad++) the first saved change in npp is noticed by txs and I see a confirmation panel in txs. After updating the txs editor another change in npp will be updated silently in txs.

### How to reproduce
Save a smal file created in txs and open it with npp. Edit and save some change in npp and turn back to txs. A confirmation panel should appear. Let txs reread the file. Go back to npp and do a second change. Turn to txs and you will find immediately the new changes.

Note: I found this while investigating a crash after I confirmed the update. But I wasn't able to reproduce.

**Comment by sunderme** [comment]
the logic is that txs continues to reload silently a file if it was not changed by the user.
That is not really unreasonable, but I will think about it.

**Comment by sunderme** [comment]
I will not change this.
You can maybe make a PR for changing the dialog with checkbox to keep asking ?

**Comment by octaeder** [comment]
I've played around with this and it seems that confirming the reload has some effects I didn't expect. Can it be that one confirmation on a specific file change is enough that silent reload happens for any file even after restarting txs? I thought that in this case the Adv. Editor option `Silently reload saved files on external changes` should be checked, but this is not the case.
