### ISSUE TITLE
highlighting of \ProvidesExplClass etc. in filecontents

### ISSUE THREAD

**Issue by mbertucci47** [texstudio-org/texstudio#3897]
### Environment
- TeXstudio: 4.8.5
- Qt: 6.8.0

### Expected behavior
A declaration of `\ProvidesExplClass`, `\ProvidesExplPackage`, or `\ProvidesExplFile` should set the highlighting to expl3 mode, but if this occurs within a `filecontents` environment then that should stop at `\end{filecontents}` (actually right before so `\end{filecontents}` is highlighted normally).

### Actual behavior
The expl3 highlighting applies to the rest of the document.

<img width="219" alt="expl3hl" src="https://github.com/user-attachments/assets/7699a851-0c81-49d6-91bc-775019cca08b">

Here is what the highlighting should look like.

<img width="229" alt="noexpl3hl" src="https://github.com/user-attachments/assets/029ad282-648a-422d-8ed8-59f6c473ec77">

### How to reproduce
```tex
\begin{filecontents}{someclass.cls}
\ProvidesExplClass{}{}{}{}
\end{filecontents}

\documentclass{article}
\begin{document}
\section{blub}
\end{document}
```

**Comment by muzimuzhi** [comment]
Hmm that also applies to all verabtim-like environments.

**Comment by sunderme** [comment]
fixed
