### ISSUE TITLE
TXS eats a lot of CPU (only) for normally `.tex` saved files

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#3899]
### Environment
- TeXstudio: 4.8.5 (git 4.8.5rc1-1-g7b5279eb0), but same issue with TeXstudio 4.8.4 as well
- Qt: 6.4.1
- OS: GNU/Linux Mageia 9
- TeX distribution: (Up to date) TeX Live 2024

### Expected behavior
TXS doesn't eat so much CPU for normal work.

### Actual behavior
As shown by [this screencast](https://github.com/user-attachments/assets/323747cd-6c46-487f-9b99-3b049c4f2ea6), TXS eats:

- a lot of CPU when:
  - opening or switching between tabs (00:00:15 → 00:00:30 and 00:00:40 → 00:00:55),
  - compiling and refreshing the PDF viewer _for normally `.tex` saved files_ (00:00:00 → 00:00:15 and 00:00:55 → 00:01:25),
- a reasonable amount of CPU when compiling and refreshing the PDF viewer _for temporary `.tex` files_ (00:00:30 → 00:00:40).

**Comment by octaeder** [comment]
I haven't seen such a behaviour on Win10 with current dev versions (local build with msys2). But I observed about two weeks ago or so that ending txs took obviously and surprisingly much time and increased CPU load. I feared that this would loose my profile. But this happend only once.

**Comment by dbitouze** [comment]
Your reply mentioning the profile made me try restarting with a new profile. This may have led to a slight improvement in the refreshing of PDFs, but not in the compilation time.

Sigh, that's very inconvenient...

**Comment by sunderme** [comment]
Have you checked that compilation on command line does not show the same issue ?

**Comment by dbitouze** [comment]
> Have you checked that compilation on command line does not show the same issue ?

Of course, and no lag or high CPU usage with compilation on command line. Or, to be more precise, high CPU usage but as it has always been the case with `(pdf)latex` compilations, not causing any problem with TXS or my daily-used editor (`Emacs`). Moreover, as I said, no lag or high CPU usage with TXS  _for temporary `.tex` files_.

**Comment by sunderme** [comment]
not reproducible on ubuntu 24.04

**Comment by sunderme** [comment]
as it is not reproducible with a simple test case, I close this issue.
I have not seen any unexpected cpu load on linux or windows.

**Comment by dbitouze** [comment]
A friend of mine encounters the same issue with TeXstudio 4.8.5 (Qt version 6.8.1) on a MacBook Pro 2019. 2,4 GHz Intel Core i5 4 cores, MacOS Sequoia 15.2.
