### ISSUE TITLE
Clean Auxiliary Files does not clean all files (new suggestions)

### ISSUE THREAD

**Issue by Fifis** [texstudio-org/texstudio#39]
Specifically, there are two more extra files that need cleaning:

1. By default, SyncTeX creates a *.synctex.gz. This should be cleaned.
2. After working with Biber, you are left with a *.run.xml file. This should be cleaned, too.

Normally, this function should leave only the PDF and the TeX source, am I right?

**Comment by timhoffm** [comment]
The .synctex.gz file is intentionally left in place by default. It allows you to sync between editor and viewer. We want to keep this functionality even after cleaning. You are free to add it to the files to be removed yourself.

**Comment by Fifis** [comment]
Okay, but the *.run.xml file definitely deserves to be incinerated since it is a Biber artifact.  What do you think?

**Comment by timhoffm** [comment]
Agreed.

**Comment by Fifis** [comment]
One more suggestion. If someone is using minted for source code highlighting, it will create .pyg files by default. I suggest that .pyg files should be deleted as well.

**Comment by timhoffm** [comment]
Unsure. We cannot include every possible file generated by some package. On the other hand, it wouldn’t do much harm here.

**Comment by kbauer** [comment]
Maybe more relevant: Biblatex creates an auxiliary file "-blx.bib", which cannot by cleaned with the current interface.

**Comment by midan-mi** [comment]
In his first reply, timhoffm wrote that if one wants to always remove a particular file type one could: "You are free to add it to the files to be removed yourself." I didn't find a way to configure which files are cleaned. Could you please advise how this can be done?

**Comment by kbauer** [comment]
> In his first reply, timhoffm wrote that if one wants to always remove a particular file type one could: "You are free to add it to the files to be removed yourself." I didn't find a way to configure which files are cleaned. Could you please advise how this can be done?

In the "clean auxiliary files" dialog, there is a comma-separated list of extensions, that we users can extend ourselves. There is currently no way to delete files, whose extension doesn't start with the period (e.g. `JOBNAME-blx.bib`) or incorrectly do not use the \jobname at all (e.g. `comment.cut`).

**Comment by kbauer** [comment]
> Great, got it - thanks. I see though once I set something, e.g., add an extension, it stays there until I change it or revert to default. Is there a way to modify the default?

Not that I know of; Why would you want to? The interface is meant for deleting auxiliary files, which you usually will either want to keep or remove all of.

That said, we have moved quite off-topic. For usage questions that are not answered by looking into the manual, the mailing list or superuser.com are more appropriate and I expect the most recent comments to get deleted or hidden before long. I can especially recommend superuser.com (or other sites of the staxkexchange network as appropriate), since it is good at showing previously asked related questions and answers based on the given question title.

**Comment by midan-mi** [comment]
Noted, thanks.

**Comment by sunderme** [comment]
.run.xml was added, the rest stays as it is.

**Comment by thomas-daniels** [comment]
What about extensions from auxiliary files from `beamer` (being nav, pre, snm, and vrb)? Potentially interesting to add since `beamer` is a very commonly used document class.
