### ISSUE TITLE
Previous Session is not restored

### ISSUE THREAD

**Issue by kiravi** [texstudio-org/texstudio#390]
Version: 2.12.12beta1
Qt: As pushed in build
OS: Windows10
TeX distribution: miktex.

### Expected behavior
Recent session is remembered.
General --> "Restore Previous Session at Startup" is checked.

### Actual behavior
Recent session is not restored.

### How to reproduce
1. uncheck flag
2. open master latex document
3. check flag
4. save master latex document (just making sure).
5. exit application
6. open application --> previous session is not restore.

**Comment by sunderme** [comment]
works here as expected.
What exactly is "Recent session is not restored." ?

**Comment by kiravi** [comment]
I open a file and work on it.  Kept the option set to restore previous session. Do not know where the session files are stored.  When I exit the application on windows 10 (64 bit) laptop and restart the application it restores TexStudio with a blank screen.  

Other checks I made:

1. Do not see any entry in the ini  file saying it needs to restore the previous session.
    or any entry of what the previous session was.

2. Checked if sessions are actually working
    a. Saved a session and
    b. Restored the saved session.
   This works.

**Comment by sunderme** [comment]
works fine on win with 2.12.12beta2
You are using the installed version of txs ? And you have not messed around with the place where settings are stored ?

**Comment by timhoffm** [comment]
The session information is stored in `lastSession.txss` in the [settings folder](https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions#where-are-the-settings-stored). Does it exist? Does it get updated when you close TXS?

**Comment by kiravi** [comment]
Uninstalled TexStudio, and re-installed TexStudio.
Kept a backup of texstudio in appdata for comparing settings after re-install.  

This time it worked 

1. It created a lastSession.txss in the app folder. --> roaming\texstudio.
2. Checked differences in this folder:
    a. There seems to  some differences in the ini (that will grow as users customize their interface.
    b. Not sure what in the ini could possibly mess up with keeping the last session. (E.g. saving and loading multiple sessions etc.)

Attaching both ini to issue

**Comment by sunderme** [comment]
so assume resolved.
If somebody wants to to dig into the ini...

**Comment by abhineet123** [comment]
I had the same problem in 4.0.0 and found that using File>Exit to close the application causes the previous session to not be restored while using the X button works just fine.

**Comment by octaeder** [comment]
I can't reproduce with 4.2.2. Maybe you want to try current version txs 4.2.2 from the [downloads](https://www.texstudio.org/#download).

**Comment by abhineet123** [comment]
Yes, 4.2.2 doesn't have this problem.
