### ISSUE TITLE
TXS editor not not recogising \label command in Memoir class 

### ISSUE THREAD

**Issue by ISMZAM** [texstudio-org/texstudio#3902]
TXS for Memoir class documents don't seem to recognise the \label command, stopping me from autocompleting the label when using \ref, and stopping TXS from listing the labels. But it only seems to work when using the \label(){} variant.
### Environment
- TeXstudio: 4.8.4
- Qt:Using Qt Version 6.7.2, compiled with Qt 6.7.2 R
- OS: Windows 11
- TeX distribution: MikTex, fully updated.

### Expected behavior
![image](https://github.com/user-attachments/assets/ca92240e-3763-4bb8-947c-389b9692a421)
Example of what should happen, by using article class, both labels are listed.

### Actual behavior
However, when using memoir class, the \label{} command is not recognized as a label:
![image](https://github.com/user-attachments/assets/5d21b3f4-83f4-46bd-9c51-d3436b1cd3f8)

### How to reproduce

Begin a basic memoir class document and create a \label{test}, then type \ref{} and try to get the editor to list labels to auto complete.

```
\documentclass[]{memoir}

\begin{document}

	\label{test1}
	\label(){test2}
	

	
	\ref{}
\end{document}
```

**Comment by sunderme** [comment]
already fixed in git, use 4.8.5rc
