### ISSUE TITLE
\ref not working after Ubuntu upgrade

### ISSUE THREAD

**Issue by tbhkuiper** [texstudio-org/texstudio#3903]
### Environment
- TeXstudio: 4.7.2
- Qt:  5.15.13, compiled with Qt 5.15.12 R
- OS: Ubuntu 24.04

### Expected behavior
```\ref``` should produce a number, and ```\pageref``` a page number

### Actual behavior
![Screenshot from 2024-12-07 17-25-08](https://github.com/user-attachments/assets/4e942faa-b0e5-428b-9649-089a8a750df4)

### How to reproduce
```\item[\S\ref{sec:FaradaysLaw} \textit{Faraday's Law}](p.~\pageref{sec:FaradaysLaw}) has a footnote saying that Faraday and Maxwell used this term.\footnote{\ttfamily https://en.wikipedia.org/wiki/Line\_of\_force}```

**Comment by tbhkuiper** [comment]
Another document compiled without error.  Comparing files I found package cleverref missing.  Why did it work before the upgrade?

**Comment by muzimuzhi** [comment]
Looks like a LaTeX use problem. Raise a question on tex.stackexchange.com, with a minimal working example and your version of LaTeX2e and `cleveref`?

**Comment by tbhkuiper** [comment]
Alas, the problem is back. Switching between documents does not fix the problem.  The affected document no longer compiles.
![Screenshot from 2024-12-07 19-47-13](https://github.com/user-attachments/assets/7ccd5704-6523-4484-8fc4-34116cd9118e)

**Comment by tbhkuiper** [comment]
The reason for suspecting TexStudio is that two documents in different tabs behave differently while I had no problems before the upgrade.  Could there be some interaction between documents?

**Comment by tbhkuiper** [comment]
The issue was raised on StackExchange also as [#732413](https://tex.stackexchange.com/questions/732413/ref-not-working-after-ubuntu-upgrade).

**Comment by sunderme** [comment]
txs just starts "pdflatex" to generate a pdf.
If something is unexpected in the pdf, it is something between the document and latex.

**Comment by tbhkuiper** [comment]
Problem solved!  Use ```\footref{...}``` instead of ```footnotemark[\ref{...}]```.   It seems that ```\ref{...}``` no longer rerturns a number.
