### ISSUE TITLE
Saved File Bug

### ISSUE THREAD

**Issue by Barrietto** [texstudio-org/texstudio#3904]
I have a mac studio, Sonoma OS, M2 Chipset, bought 30 days ago. Installed the latest up dates,
but not to Sequoia. Installed TeXstudio 4.84(OSX M1 zip) for Mac OS 14.00 or higher.
Mine is 17.1. Also downloaded MikTex. I am writing a very technical math paper for the Journal of Number Theory using their paper template "elsarticle." After entering three of four pages of the paper, I tried to save what I had written. The log entry response was "Process exited with error(s)." Under the PDF screen was the quote:
"Failed to find file", followed by user data for me. Then tried the Hello World approach using the Wizard app. Surprisingly, it not only worked, but the code was in purple blue, green , yellow and white. I then got the idea to paste what I had written, but couldn't save into the Wizard app. To my surprise, it also worked. However,
when I went to save the working Wizard file, I got the error messages as just reported. In frustration, it went to the help app, and under "Language Tool". was the reply, "what Java, Java crashed." So I am wondering if the is a software bug? Has it been corrected? Anyone else experienced this?

### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution:

**Comment by sunderme** [comment]
OSX has very strict access limitations for app.
You have to give txs write access to your documents.
My guess is that has not been done on your computer.
Please google how to set that up.

**Comment by octaeder** [comment]
see here: https://github.com/texstudio-org/texstudio/issues/3736#issuecomment-2335097418

**Comment by sunderme** [comment]
I am talking about this: https://support.apple.com/guide/security/controlling-app-access-to-files-secddd1d86a6/web

**Comment by Barrietto** [comment]
I downoaded the file from the site you suggested: Controlling app access to files in
mac OS. Followed the mac OS 13 or later, got to Accessibity, but beyond that, User must edit system privacy settings and full internal storage access? Where do they come in? User prompted by app? No. You have been a big help but my ignorance is preventing me to move forward.

**Comment by sunderme** [comment]
I don't have a current mac and doing this kind of support remotely is difficult.
Any local friend with a bit more knowledge on osx could help ?

**Comment by Barrietto** [comment]
Interestingly, my partner, a senior programmer for the likes of Oracle
and Salesforce, took a look at my problem and advised me my problem was
that SVN needed to be turned off. After some work
(the instructions for doing this were a bit convoluted as things were not
where they were supposed to be) and then saved the file to
"Joseph.tex". Everything working now. Again thanks for your input and
patients.
