### ISSUE TITLE
Texstudio without menu

### ISSUE THREAD

**Issue by PietroDonatis** [texstudio-org/texstudio#3907]
I've been using Texstudio for years, but suddenly the top menu line with the tabs file, latex, mathematics, bibliography, options etc. disappears.

I am using 4.7.2 version of Texstudio on Ubuntu 24.04.1

TeX distribution is texlive

![Schermata a 2024-12-13 08-52-16](https://github.com/user-attachments/assets/1be78be9-084c-4c25-94f0-1c1cddd5e3a8)

I tried to reinstall Texstudio, but the problem is still there.

Can you help me to solve the problem?

Thank you in advance.

Pietro Donatis

**Comment by sunderme** [comment]
You can reset txs settings by removing ~/.config/texstudio/texstudio.ini

**Comment by sunderme** [comment]
by the way, this is probably some issue with the desktop environment.
What are you using ?

**Comment by sunderme** [comment]
no feedback
