### ISSUE TITLE
update utilities/packageDatabase.json

### ISSUE THREAD

**Issue by octaeder** [texstudio-org/texstudio#3909]
### Environment
- TeXstudio: 4.8.5

### Description
Open Packages Help, check all packages and search for `latex2e-help-texinfo`. The version info shows Jan 15 2023. Now press button open CTAN. There we find that latest version is May 13 2024. In fact this is the version of the LaTeX Reference shipped with current txs version.
Not clear how to recreate the json from https://github.com/texstudio-org/texstudio/pull/3478#issuecomment-1894474230.

**Comment by sunderme** [comment]
@CSMathematics , can we get some descriptions on how to update ? Maybe a script ?

**Comment by CSMathematics** [comment]
Sure. I will upload the script in a new repository in a few days. I'll give a feedback when it's ready.

**Comment by CSMathematics** [comment]
Here is the code [GTAN Database Creator](https://github.com/CSMathematics/CTAN-Packages-DataBase/tree/master). Fell free to merge it in TexStudio if needed. Let me know for any issues.

**Comment by sunderme** [comment]
Thanks.
I have ported the actual logic to python and added that to texstudio repository. The main idea is that 
a) we don't need a gui for that
b) maintenance is probably simpler as more people can program python
