### ISSUE TITLE
The Preview Panel not remain maximized consistently.

### ISSUE THREAD

**Issue by goshlive** [texstudio-org/texstudio#3910]
First, thank you for providing this incredible free software and continuously updating it. I have been using it since my studies, and it has been immensely helpful.

I would like to share a minor issue I encountered with the preview panel behavior since I used version 4.8.4. I have reinstalled the latest version, but the problem remains. I use the “Always show preview in the preview panel” configuration. Still, whenever I compile my LaTeX file, the preview panel opens in a tiny size, approximately 1/10 of my laptop screen. I always have to maximize it to view the results properly manually.

It would be great to add a toggle feature to allow users to set the preview panel to maximize after compilation automatically.

Thank you for considering this feedback, and I appreciate your continued support of this excellent software.

### Environment
- TeXstudio: 4.8.5
- Qt: 6.8.1
- OS: Windows 11
- TeX distribution: MikTex

### Actual behavior
As shown in the screenshots below, when I click on compile, the window consistently displays in a small size, even after I manually maximize it. Clicking compile again causes the window to revert to the small size.
![issue1](https://github.com/user-attachments/assets/1ce0144b-501a-41c5-9823-ef477db7b0f6)
![issue2](https://github.com/user-attachments/assets/b0e9b1fe-1c38-4ccb-9e0d-b31ef0964346)

### How to reproduce
1. Go to the menu and set the configuration: Options -> Preview -> Always show preview in preview panel.
2. Compile a `.tex` file.  
3. If the preview panel is not maximized, maximize it.  
4. Compile the `.tex` file again, and the preview panel will revert to its small size.

**Comment by sunderme** [comment]
Preview refers to previewing short parts of the document like formulas, see https://texstudio-org.github.io/viewing.html#preview

You are showing the internal pdf viewer, options in "option/internal pdf viewer"
That said, here the pdf viewer remembers its size, even after restart.
