### ISSUE TITLE
I hope to add a function that can switch between the compiler with one click. texlive and CTEX are often used, and the switch can only be switched between one item in the options. I hope a function can be created to switch between texlive and CTEX with one click.

### ISSUE THREAD

**Issue by lyk-wq** [texstudio-org/texstudio#3913]
I hope to add a function that can switch between the compiler with one click. texlive and CTEX are often used, and the switch can only be switched between one item in the options. I hope a function can be created to switch between texlive and CTEX with one click.

**Comment by octaeder** [comment]
To select specific compiles the Tools/Commands menu items are usefull. In the Toolbars options you can add them to the Tools or other toolbars as you like.

![grafik](https://github.com/user-attachments/assets/4e355ed9-46e5-408d-8882-b413399a688e)

**Comment by muzimuzhi** [comment]
Looks like OP wants to switch between LaTeX distributions.

@lyk-wq Could you explain how you "switched between one item in the options" now?

**Comment by sunderme** [comment]
There is also the "--texpath" command line option which tells txs to use latex & co. in a different path.

**Comment by sunderme** [comment]
no feedback, basic question assume answered
