### ISSUE TITLE
Completion entries for redefined commands

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#3925]
### Describe the feature and the current behavior/state

When a command redefinition via for example `\renewcommand` changes argument specification of the command, currently both the old (generated previously for `\newcommand`) and new completion entries are remembered. Ideally the old completion entries should be dropped.

```tex
\documentclass{article}
\newcommand{\mycmd}[1]{code [#1]}
\renewcommand{\mycmd}[2]{code [#1][#2]}

\begin{document}
\mycmd
\end{document}
```

![image](https://github.com/user-attachments/assets/196a04d8-7b88-4a05-9fb3-ff69184cf9d9)

### Who will benefit with this feature?

Users of LaTeX documents which alters argument specification(s) while redefining commands.

### Any Other info

It occurred to me when reviewing #3924 and wondering "do `\renew...` commands need `d1` modifier?"

**Comment by sunderme** [comment]
This will not happen.
For this, txs would need to track the validity of each redefinition within a file as well as over when includes are placed.
The current architecture does not allow this and the effort seems to high for this corner case.
