### ISSUE TITLE
SVN error

### ISSUE THREAD

**Issue by Afrothetics** [texstudio-org/texstudio#395]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior
Save document

### Actual behavior
I SAVE the doc, then the Error message appears [see below]

![txs-svn-error](https://user-images.githubusercontent.com/43934046/48718614-bb795b00-ebe9-11e8-8974-1f14bbfd5e87.png)

Next, I click OK on the error dialog, message exits, and any following action is not affected. What is affected is that the pdf docs are not created when compiling, although the auxiliary files are not affected.

### How to reproduce
The error occurs whenever a document is saved.

**Comment by sunderme** [comment]
you enabled option/svn/checkin after ... without providing a svn (subversion) command in option/commands/svn (possibly because subversion is not installed on your computer)

**Comment by Afrothetics** [comment]
@sunderme, thanks for your response. Yes, I see the issue now.
