### ISSUE TITLE
Update texstudio installer on sourceforge

### ISSUE THREAD

**Issue by thatlittleboy** [texstudio-org/texstudio#397]
Is there any reason the default install version on Sourceforge (when one clicks the big green "Download" 
 / "Download latest version" button) is still 2.12.8?

Users who are none-the-wiser might not be aware of the more recent version(s) (2.12.10, and soon, 2.12.12). They would just click the download button expecting the latest version. Either that or they would download the 'latest' 2.12.8 and be perplexed when they receive an update notice soon after they start up TXS, meaning unnecessary work for the end-user.

It's quite worrying considering the disparity in the number of downloads (since 2.12.10 has been out for a few months now):

![chrome_2018-11-20_09-48-38](https://user-images.githubusercontent.com/30731072/48781297-c0054880-eca9-11e8-89b9-8ebc575ac476.png)

**Comment by benibela** [comment]
default changed to 2.12.10
