### ISSUE TITLE
Autocompletion for local class files

### ISSUE THREAD

**Issue by flenzen** [texstudio-org/texstudio#399]
### Environment
- TeXstudio:  2.10.8
- Qt: 5.5.1
- OS: Linux Mint 18.3
- TeX distribution: TeX Live 2015/Debian

The project I am working on resides in one directory (no subdirectories). It contains a custom `.cls` file, placed in the same directory as the main `.tex`-file, used as the `\documentclass` for the project. `latex` compiles the project without problems.

### Expected behavior
TeXstudio should parse the `.cls`-file used as `\documentclass` and the packages loaded therein for autocompletion.

### Actual behavior
The `\documentclass` is squiggly underlined, with a tooltip saying "(not found)". Every command that is only available through that `.cls`-file has red background. Autocompletion not working.

### How to reproduce
Write a `document.tex`-file containing:

```
\documentclass{custom}
\begin{document}
  \blindtext
\end{document}
```
and a file `custom.cls` in the same directory, containing

```
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{custom}
\LoadClass{article}
\newcommand{\blindtext}{Some blind text.}
```
You will note that in `document.tex`, TeXstudio will underline the name `custom` of the documentclass. The macro `\blindtext` will not be available through autocompletion.

**Comment by sunderme** [comment]
you need to write a cwl file for that, see [wiki](
https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions#why-does-a-command-not-show-up-in-the-completion)

**Comment by kleinph** [comment]
Is there somewhere a tutorial how to do this? The link in the referenced wiki entry only leads to the general docs page (not a specific chapter).

**Comment by muzimuzhi** [comment]
@kleinph Links in wiki pages are updated. The fragment part of URL (`#<anchor name>`) was lost when the link is redirected.

**Comment by kleinph** [comment]
Thank you very much for the quick response!
