### ISSUE TITLE
texstudio started to freeze at startup (mac 10.13.2 )

### ISSUE THREAD

**Issue by enricobibbona** [texstudio-org/texstudio#4]
I tried to edit the .ini file but without any effect.
I canceled the whole texstudio directory  and downloaded the newest version of the app.
Nothing happens and the new version still freezes immediatly as launched.

**Comment by sunderme** [comment]
I can't test on osx 10.13.
Could you try a development build: https://bintray.com/sunderme/texstudio/download_file?file_path=texstudio-osx-2.12.7-201712272142-git_1e7fa04.dmg

**Comment by enricobibbona** [comment]
Thank you.
This one works!
Best, Enrico

2018-01-06 10:28 GMT+01:00 sunderme <notifications@github.com>:
