### ISSUE TITLE
Completer wont start when using remapped \ key on OS X

### ISSUE THREAD

**Issue by jonlachmann** [texstudio-org/texstudio#40]
Hi, I have been running TexMaker but wanted to try out TexStudio as it seems to pack more features. However I am very reliant on the completer writing a lot of things for me since I take notes in class and really need the speed increase it provides.

I have remapped the backslash to be the key above my tab button on my Swedish keyboard layout. This key usually makes the paragraph sign. For some reason pressing this key and writing something after it does not trigger the completer in TexStudio as it did in TexMaker.

I have added the row `    "§" = (insertText:, "\\");` in my defaultkeybindings.dict, you can read further on the subject here https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/EventOverview/TextDefaultsBindings/TextDefaultsBindings.html

If you can try to reproduce this and find out whats going on it would really help, since I have a hard time making the backslash on my keyboard layout as is (alt-shift-7).

Please let me know if you need any further info. OS is OS X 10.12.6 and texstudio is 2.12.6

Best regards!

**Comment by sunderme** [comment]
I have no idea how the OSX key substitution works internally, but I guess it does not play well with txs/QT mechanism.
The easiest solution for you is probably to define within txs a macro:
%SCRIPT
cursor.insertText("\\")
app.normalCompletion();

Set the trigger to what key you want it to start ("§" , without the quotation marks, obviously OSX key substitution should not be active)

**Comment by jonlachmann** [comment]
Just wanted to post back and let you know that the script supplied works as it should, i did have to add an extra backslash and ; Below is the working macro code. Thank you for this! =) Now I can start learning texstudio! 👍 

%SCRIPT
cursor.insertText("\\");
app.normalCompletion();
