### ISSUE TITLE
The default selected encoding in the quick start wizard should be `utf8` instead of `latin1`

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#401]
-  TeXstudio: 2.12.12 (git 2.12.12beta2-31-gfff9ed38)
  -  Qt: 5.9.4
  -  OS: Linux Mageia
  -  TeX distribution: TeX Live 2018

### Expected behavior
The quick start wizard should provide a the default selected encoding `utf8` rather than `latin1`. Indeed, [UTF-8 [is] the new default input encoding](https://www.latex-project.org/news/latex2e-news/ltnews28.pdf), hence `utf8` should be encouraged.

**Comment by sunderme** [comment]
done
