### ISSUE TITLE
Can choose other Languages in the new version.

### ISSUE THREAD

**Issue by idcm** [texstudio-org/texstudio#404]
### Environment
- TeXstudio: TeXstudio 2.12.12 (git 2.12.12)
- Qt: Using Qt Version 5.8.0, compiled with Qt 5.8.0 R
- OS:  Windows 10
- TeX distribution: miktex

### Expected behavior
In the General setting, I can set language to Chinese.

### Actual behavior
The only two choices in the "Language" is default and en. (But  in the old version I used, there are many languages that I can choose.)

**Comment by sunderme** [comment]
could you try https://bintray.com/sunderme/texstudio/download_file?file_path=texstudio-win-2.12.12-201811261205-git_24566d1.exe

**Comment by sergiokapone** [comment]
Confirm. I can't select any language with old one 2.12.12 (git 2.12.12). With new one, ok

**Comment by idcm** [comment]
@sunderme the new one https://bintray.com/sunderme/texstudio/download_file?file_path=texstudio-win-2.12.12-201811261205-git_24566d1.exe is ok
