### ISSUE TITLE
Hard line wrapping doesn't work for CJK chars

### ISSUE THREAD

**Issue by sumbrez** [texstudio-org/texstudio#406]
### Environment
- TeXstudio: 2.12.10 (git 2.12.10)
- Qt: 5.8.0, compiled with Qt 5.8.0 R
- OS: Windows 10 1803, 64-bit
- TeX distribution: texlive

When the context **includes** CJK chars:

### Expected behavior
Pre-saving: soft wrap after max chars.
Saved: hard wrap after max chars.

### Actual behavior
It performs as no line wrap, even for non-CJK lines.

### How to reproduce
Just put CJK chars into the context.

**Comment by sunderme** [comment]
please provide a test case with file.

**Comment by sumbrez** [comment]
A simple test file.
```
\documentclass[journal]{IEEEtran}

\begin{document}

一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十

\end{document}
```
Soft wrap works fine, but hard wrap doesn't.

Besides, I think it's about word segmentation of CJK chars. `Ctrl`+`Left/Right` doesn't work for CJK chars, even English-CJK mixed 'word'. For example, for '一二one two', '一二one' is treated as a word.

**Comment by sunderme** [comment]
just to clarify things (as none CJK user): you can break the line at any point without changing its meaning ?
The current logic does not break with "words" but only at spaces, since breaking within words would change its meaning (and it would at a space between the parts after latex)

**Comment by sumbrez** [comment]
For Chinese, yes, you can break at any point since every Chinese char is complete as a "word" (compared with English) and there is no space between chars. And for mixed "word" like "一二one", you can also break between "二" and "one".

But I'm not sure about Japanese and Korean.
From my limited knowledge, every Kanji in Japanese is complete. There is either no space between hiragana or katakana chars.
I know little about Korean. There seems to be no space between Hangul chars since every char is a syllabic block. (?)

**Comment by sumbrez** [comment]
Thanks, @rhodium-103, you mentioned line break about punctuation. There are also rules of placement of different punctuation in Chinese, e.g., no opening bracket at the end of line and no closing bracket at the beginning. These rules are about document built, I'm not sure whether breaks in source code in editor affect. There are also rules in English? Dot, comma, dash, quote, etc. I tried the following text with XeTeX, with less or more chars in the first line, and document built always conformed. So is (Xe)TeX ruling the document?
```
一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八
（
一
二
）
三
四
```

**Comment by sumbrez** [comment]
P.S. I'm using new version 2.12.14 (git 2.12.14) now.

**Comment by ipodipad** [comment]
see patch below, ( >= 5.14 ) Allow word break wrapping in Korean text

https://code.qt.io/cgit/qt/qtbase.git/commit/?id=d1bab5b1e3d28c0e2925ad3208cea785af755d54
