### ISSUE TITLE
Fuzzy autocompleter too greedy (in keyvals)

### ISSUE THREAD

**Issue by thatlittleboy** [texstudio-org/texstudio#407]
### Environment
- TeXstudio: 2.12.12 git 24566d1
- Qt: 5.8
- OS: win 10
- TeX distribution: miktex

### Actual behavior
Fuzzy autocompleter completes itself too readily, see below example.  Suppose `\testkv{keyvals}` has keyvals `mode=`, `midpenalty=`, `leftmargin=` and `rightmargin=`. Then typing <kbd>m</kbd> (only) in `\testkv{|}`, with fuzzy autocomplete as default in the config, automatically expands to `\testkv{mi}` with 3 suggestions even though there is the keyval `mode=` which is present in the cwl. 

![mwe](https://user-images.githubusercontent.com/30731072/49023452-3a7c0f80-f165-11e8-9aaa-ec4884deda54.gif)

I'm not sure if this is a more general problem that happens with citations/refs and/or command autocompletion. Haven't yet encountered an example.

**EDIT:** It occurs with citations as well. If you want a test case, let me know.

### Expected behavior
The fuzzy autocompleter should not expand too greedily. In my example, it should remain `\testkv{m}` with the 4 keyvals suggested.

### How to reproduce

**abcd.cwl**
```
\testkv{keyvals}

#keyvals:\testkv
mode=
midpenalty=
leftmargin=
rightmargin=
#endkeyvals
```

Set fuzzy autocomplete as default, ensure "Auto complete Common prefix" is checked, and activate the cwl.
Then type `\testkv{}`, then <kbd>m</kbd>

Or if you don't want to go through the trouble, this same problem applies with `\setlist{keyvals}` from the newly added `enumitem.cwl` as well. So just `\usepackage{enumitem}` at the top of the document. I just wanted to demonstrate here with a minimal example.

**Comment by sunderme** [comment]
fixed
