### ISSUE TITLE
Sort documents in "Structure" panel by name

### ISSUE THREAD

**Issue by mehelme** [texstudio-org/texstudio#409]
### Environment
- TeXstudio: TeXstudio 2.12.10 (git n/a)
- Qt: Using Qt Version 5.9.5, compiled with Qt 5.9.5 R
- OS: "Ubuntu 18.04.1 LTS"

### Expected behavior

Documents in "Structure" panel sorted by name

### Actual behavior

Documents in "Structure" panel sorted by open order

### How to reproduce

Create document with:
\include{part1}
\include{part2}
and open part2, then part1

**Comment by thatlittleboy** [comment]
More precisely, currently it's sorted by the tab order I think. If you rearrange the open file tabs (e.g., make part2 the second tab), the structure tree updates as well.

**Comment by sunderme** [comment]
global toc with 3.1.0 solves this issue as well
