### ISSUE TITLE
Replace Double Quotes: closing brace at first double quote when \enquote is chosen

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#41]
Currently, when "Options → Configure TeXstudio... → Editor → Replace Double Quotes → Package csquotes \enquote{ }" is chosen, the following happens:

1. when the first `"` is hit, only `\enquote{` is inserted,
1. when the second `"` is hit, the closing brace `}` is inserted.

The trouble is, until the second step above, the opening brace is marked as brace mismatched (by default in bold with red background) and so is the following `\end{document}`. This could be stressful and I suggest the closing brace being inserted at first double quote hit, with the cursor between the opening and closing braces.

BTW, this could apply to every replacement chosen in ""Options → Editor → Replace Double Quotes", that is only one `"` is needed and, when hit, both the opening and the closing parts of the replacement are inserted, for instance (`|` being the cursor):

- for English quotes: `"` → ` ``|'' `,
- for French Quotes (babel): `"` → `\og |\fg{}`,
- for Package csquotes \enquote{ }: `"` → `\enquote{|}`.

**Comment by sunderme** [comment]
if you want to adapt the behaviour to your liking, you can easily do it with the macros (which are internally used for quote substitution anyway) 
I don‘t see merit to change the default behaviour

**Comment by dbitouze** [comment]
>I don‘t see merit to change the default behaviour

Sigh...
