### ISSUE TITLE
ProcessX Object readAllStandardOutputStr() in macro does not return anything

### ISSUE THREAD

**Issue by kernie** [texstudio-org/texstudio#411]
### Environment
- TeXstudio: 2.12.12
- Qt: 5.11.2
- OS: Mac

Hi!
I added a simple script like:
```
%SCRIPT
ret = system("/bin/echo hi")
ret.waitForFinished()
information("exitCode: " + ret.exitCode() + 
" StdOut: " + ret.readAllStandardOutputStr())
```
and wanted to catch the output of a system command.

However, the returning string is empty.

Anyway, thank you for this genious Latex editor!

Maarten

### Expected behavior
Method readAllStandardOutputStr() should return all standard output of system command.

i.e. "hi" ...

### Actual behavior
Nothing returns.

### How to reproduce
Add macro:
```
%SCRIPT
ret = system("/bin/echo hi")
ret.waitForFinished()
information("exitCode: " + ret.exitCode() + 
" StdOut: " + ret.readAllStandardOutputStr())
```
and execute.

**Comment by sunderme** [comment]
see https://tex.stackexchange.com/questions/160916/texstudio-readallstandardoutputstr-seems-not-to-work
