### ISSUE TITLE
Autocompletion in math-environment inserts $$

### ISSUE THREAD

**Issue by HannahArndt** [texstudio-org/texstudio#412]
When I am inside an align environment and  at the first character of a new line
autocompletion surrounds the command with two $$.

### Environment
TeXstudio 2.12.12 (git 2.12.12)
Using Qt Version 5.8.0, compiled with Qt 5.8.0 R
- OS: Windows 10
- TeX distribution:  miktex

### Steps to reproduce:

Write the following text into a LaTeX document:
```
\begin{align}

\end{align}
```
2. Place your cursor into the middle row and remove any whitespaces on that line
3. Type `\intertext` and press Enter to accept the autocomplete

### Expected behaviour
The snippet `\intertext{...}` is inserted.

### Actual behaviour
 The snippet `$\intertext{...}$` is inserted.

### Complete example
```
\documentclass{article}
\usepackage{amsmath}
\begin{document}
	
\begin{align*}
	\intertext{this works fine}
$\intertext{\$ added within align by autocompletion}$
\end{align*}
	
\end{document}
```
(eddited after comment by @sunderme)

**Comment by sunderme** [comment]
your example does not compile.
in my book 
`\documentclass[article]`
is not a valid command and it messes up the txs parser.
With 
`\documentclass{article}` everything works as expected.

**Comment by HannahArndt** [comment]
Hi,
sorry for the typo. I have fixed that in my example and it still does not work for me (I have checked that it does compile this time, before I inserted the second `\intertext`.)

### Updated example:
```
\documentclass{article}
\usepackage{amsmath}

\begin{document}
	
\begin{align*}
	\intertext{this works fine}
$\intertext{word or phrase}$
\end{align*}
	
\end{document}
```

**Comment by sunderme** [comment]
please post a screenshot of the window with the example.
Works fine here...

**Comment by HannahArndt** [comment]
After some testing I discovered that the bug only shows when 
`Options > Configure TexStudio > Completion > amsmath.cwl` is checked.

Here are the screenshots you askek for (first before and then right after autocompletion):
![beforeautocomplete](https://user-images.githubusercontent.com/23188911/49279823-cc975700-f488-11e8-960a-b5cf1b57cc75.PNG)
![afterautocomplete](https://user-images.githubusercontent.com/23188911/49279825-ce611a80-f488-11e8-81c8-0bdc1c4789dd.PNG)

**Comment by HannahArndt** [comment]
good to know.
Thank you!
