### ISSUE TITLE
Multi word %-suffix not working

### ISSUE THREAD

**Issue by thatlittleboy** [texstudio-org/texstudio#416]
### Environment
- TeXstudio: 2.12.14 git 8232283
- Qt: 5.8
- OS: Win 10
- TeX distribution: Miktex

### Expected behavior
There are argument names which are >1 word long, e.g. `bib files` and `short title`. The expected behaviour for a cwl declaration that involves a %-suffix as an alias, like:

    \testDontWork{alias%bib files}#b

should be to see in the editor: `\testDontWork{alias}` and for the argument to be treated like a bib file.

### Actual behavior

Instead, you see `\testDontWork{alias files}` and the argument isn't treated correctly as a bib file (syntax highlighting wise).

![texstudio](https://user-images.githubusercontent.com/30731072/49334325-1a9f7e00-f5a1-11e8-82e6-b1f96e5287b7.png)

### How to reproduce
Compare the two results as cwl:

```
\testWork{bib files}#b
\testDontWork{alias%bib files}#b
```

### Suggestion
If you would allow me a suggestion, (which you might view either as a **solution** to the stated problem or an **enhancement**), is for the addition of a 1-word %-suffix alias for the `bib file`/`bib files`, e.g. `bib` or even `bibfiles`, to the code:

https://github.com/texstudio-org/texstudio/blob/fabb8549671341b92496e1cc202ceab1c7d84ff5/src/latexpackage.cpp#L652

All the other special argument names have at least one "1-word %-suffix" that we can use to mitigate the issue I described here..

**Comment by sunderme** [comment]
suffix declaration are not derived from normal arguments key declarations but are special ones. There is no "%bib files" suffix and there is not intended to be one. All available suffices are described in the manual.
(If extra ones are absolutely necessary we might add some, but in my opinion, having the same argument name for the same functionality, here "bib files", is actually preferable)

**Comment by thatlittleboy** [comment]
Okay, well, I only asked because someone else brought it up on SF: https://sourceforge.net/p/texstudio/bugs/2407/

![texstudio_2018-12-02_10-58-21](https://user-images.githubusercontent.com/30731072/49341844-321e4b80-f621-11e8-86c3-50052d77527a.png)

Indeed it adds to the bib file but the syntax highlighting is wrong regardless. Unlike #61, this seems easy enough to fix..

**Comment by sunderme** [comment]
for now, I would prefer it to be `\addbibresource{bib file}#b` as the command itself can only handle one filename. And if it keeps saying "resource", someone will come up to complain that it does not handle URLs  correctly.
