### ISSUE TITLE
Developmental version prompting for update

### ISSUE THREAD

**Issue by thatlittleboy** [texstudio-org/texstudio#417]
### Environment
- TeXstudio: 2.12.14 git 8232283
- Qt: 5.8
- OS: win 10 
- TeX distribution: miktex 

### Actual behavior
Not a big deal but the developmental versions (those provided on bintray) prompt for update of version even though it is _itself_ the latest version. This occurs for "update level" set to any of the 3 settings -- "stable", "release candidates" or "development version" in the config.

![tex](https://user-images.githubusercontent.com/30731072/49334449-791a2b80-f5a4-11e8-872f-e4b87179a21d.png)

The official release version (from the website) **does not** have this issue.
Though I wonder why checking for an update for "_development versions_" on the official released 2.12.14 version still says "Texstudio up-to-date". I'm confused what development version this option checks for? Shouldn't it prompt the user to download from bintray or similar?

### Expected behavior
No (unwarranted) prompts about updates in the developmental snapshots.

### How to reproduce
Click "Check now" under config->update of the developmental snapshots.

**Comment by sunderme** [comment]
fixed
