### ISSUE TITLE
The license of Texstudio is listed as "proprietary" in Ubuntu Software

### ISSUE THREAD

**Issue by Ethunxxx** [texstudio-org/texstudio#418]
See this screenshot:

![screenshot from 2018-12-04 09-24-40](https://user-images.githubusercontent.com/25529527/49428616-d4b40700-f7a6-11e8-8349-fe064f04aab6.png)

Any ideas why it doesn't show the correct free GPL license?

**Comment by sunderme** [comment]
I have no idea where ubuntu software center takes that assumption. The copyright file seems to be present.
This is as far I am willing to look into this.

**Comment by timhoffm** [comment]
Thanks for the hint.

The [ubunutu package page](https://packages.ubuntu.com/cosmic/editors/texstudio) links to [this copyrights](http://changelogs.ubuntu.com/changelogs/pool/universe/t/texstudio/texstudio_2.12.10+debian-1/copyright) maybe it's to do with that. Anyway, this seems rather a packaging problem than a issue with TXS itself. You may use the contact information in the first link if you want to follow up on this.
