### ISSUE TITLE
Crash of TeXStudio

### ISSUE THREAD

**Issue by mesti90** [texstudio-org/texstudio#42]
I use TeXstudio 2.12.6 (hg 6632:7777b2b8a906) (Qt Version 5.9.1, compiled with Qt 5.9.1 R) under Windows 10.
When starting multiline edition (by pressing Ctrl+Alt and clicking with the mouse), the application suddenly crashed with the following error code.

```
EXCEPTION_ACCESS_VIOLATION at 68aa6699 (TXS-Version 6632:7777b2b8a906 R )
[bt] 00527ea0  ??? error: 487
[bt] 68aa6699  ZN14QReadWriteLock11lockForReadEv+25
[bt] 004c73f1  ??? error: 487
[bt] 004c7967  ??? error: 487
[bt] 004b7dca  ??? error: 487
[bt] 0067cbf0  ??? error: 487
[bt] 03c16ec5  ZN7QWidget5eventEP6QEvent+2469
[bt] 00000000  ??? error: 126

```

**Comment by timhoffm** [comment]
Is this behaviour reproducible?

**Comment by mesti90** [comment]
I can't reproduce it.

**Comment by sunderme** [comment]
nothing we can do
