### ISSUE TITLE
command \subref not recognized by autocompletion

### ISSUE THREAD

**Issue by thymaro** [texstudio-org/texstudio#420]
I don't know how to write correct `.cwl` files, so, if there is a tutorial about that anywhere, I would be more than happy to be pointed to that website. What to include? What does the `#S` mean? What are the other triggers and commands and mandatory lines to include? Things like that.

### Environment
- TeXstudio: 2.12.10
- Qt: 5.5.1 R
- OS: Linux Ubuntu 16.04
- TeX distribution: MikTeX for Ubuntu

### Expected behavior

`\subref` command is recognized by autocompletion

### Actual behavior

`\subref` command is **not** recognized by autocompletion, even though `subcaption` package is loaded and `subcaption.cwl` is listed under `Settings > Completion`, so I assume `subcaption.cwl` exists (even though I can't find it in `[settings-directory]/completion/autogenerated`, so I assume it is one of the builtin `cwl`)

### How to reproduce
load `caption` and `subcaption` package in a working document and use `\subref` command in document.

**Comment by sunderme** [comment]
from what I see, the subref command was only added in August this year, so update to the current version of txs

**Comment by thymaro** [comment]
I didn't realize it was that new. Thx, will update.
