### ISSUE TITLE
Padding (extra space) between lines

### ISSUE THREAD

**Issue by QuillerTu** [texstudio-org/texstudio#421]
I was not able to find in Texstudio an option to add padding (extra space) between lines of the text editor (on screen). I am positive that this is supported by Qt5 (as it has been implemented in FocusWriter) and I was expecting to find it in Texstudio.
Extra spacing between lines is important for readability of the text. This is particularly useful for those users who have some eyesight impairment.
It may also be needed to display correctly the text in some languages, because some characters that need more vertical space than usual may not be displayed fully if there is no extra space between the lines, and naturally this is a problem.
Could you please implement this feature?

**Comment by sunderme** [comment]
Options/Editor/Line Spacing    defult is 100%, just increase it.

**Comment by andreasloe** [comment]
In case someone does not find it on its screen: Activate "extended options" far left bottom corner to see this option.
