### ISSUE TITLE
Cursor/Input jumps to end of word

### ISSUE THREAD

**Issue by benjo2000** [texstudio-org/texstudio#423]
### Environment
- TeXstudio: 2.12.14
- Qt: 5.11.2
- OS: OSX High Sierra
- TeX distribution: texlive

### Expected behavior
Input gets inserted on cursor position

### Actual behavior
Cursor jumps to end of word, input gets inserted there

### How to reproduce
Choose any word in file and try to make a correction within that word.

![untitled](https://user-images.githubusercontent.com/17175434/49651144-bbbd8700-fa2e-11e8-8831-99f01b14cf05.gif)

**Comment by sunderme** [comment]
please provide a text file. I am not going to replicate text from an image.

**Comment by benjo2000** [comment]
> please provide a text file. I am not going to replicate text from an image.

Sorry for my imprecise descprition. The words don't matter. When i create a new document and type a single random word  i can not edit it by clicking in the middle of that word. The only way to correct a typo is to set the cursor behind the word and delete the letters to the point of error using the backspace key.

**Comment by sunderme** [comment]
well, it does nit happen here.
you can delete .config/texstudio/texstudio.ini
if that does not help, there is nothing we can do.

**Comment by benjo2000** [comment]
Deleting texstudio.ini didn't help.
Thanks anyway

**Comment by sunderme** [comment]
works for me, no clue what happens on user side, close

**Comment by EliseyP** [comment]
This happens with macros default settings - macros **Auto-correct multiple capital letters** have trigger `[a-z]`.   
Deleting trigger solve problem.

**Comment by sunderme** [comment]
fixed, you need to browse/import the corrected version of the script

**Comment by EliseyP** [comment]
Sorry, after update:
 - by type all caps letters, auto-lowercased **only second letter**, typing TEST, get TeST.
 - If we edit **already typed uppercased-word**, and type one uppercase letter into this word, cursor jump to the end of this word again, and letter inserted in cursor-place - to the end of word.
 - inserting **caps letter** to start, after first, after second letters of **upper-cased, early typed** word give us different results.

--
TeXstudio 4.2.1 (git n/a)
Using Qt Version 5.15.2, compiled with Qt 5.11.3 R

**Comment by sunderme** [comment]
The macro scripts are user generated content which is provided "as is". As the script is open and easily accessible, you can adapt it to your needs. The page https://github.com/texstudio-org/texstudio-macro contains these macros for easy distribution.

**Comment by EliseyP** [comment]
All work correctly now. Thank you!
