### ISSUE TITLE
use docstring to learn autocomplete

### ISSUE THREAD

**Issue by alikazemkhanloo** [texstudio-org/texstudio#424]
## feature request
I know it is hard to find latex commands for autocomplete, but if there was something like `docstring` in latex, it would be really easy to find them. and for new custom commands, we don't need to write an extra cwl file somewhere else.

My first idea was to load custom cwl files from the current directory. But docstring would be a great work and maybe requires a great deal of time.

**Comment by sunderme** [comment]
well, there is no docstring for latex, so it is a bit mute

**Comment by alikazemkhanloo** [comment]
I know there is no docstring for latex. 
I mean, the TexStudio can treat some special kind of comments as docstring.
for example: 
```Latex
%%% 
% \fcite{keylist}#c
% footnote the english name of author while referencing 
\newcommand{\fcite}[1]{\cite{#1}\LTRfootnote{\citeauthor*{#1}}}
```
will tell texstudio what kind of command is the next line.
or maybe this one:
```Latex
\newcommand{\fcite}[1]{\cite{#1}\LTRfootnote{\citeauthor*{#1}}} % \fcite{keylist}#c
```
the point is writing comments is way easier than writing cwl file and restarting the texstudio.

**Comment by sunderme** [comment]
I assume you are talking about normal latex files which define commands, not packages.
I doubt that there are many to use this, somthemwork to implementmis not really worth the effort. And you can already use cwl...
