### ISSUE TITLE
Master document persists after closed

### ISSUE THREAD

**Issue by marczellm** [texstudio-org/texstudio#425]
### Environment
- TeXstudio: 2.12.14
- Qt:  5.8.0
- OS: Windows 10
- TeX distribution: miktex

### How to reproduce
1. Open a subfile (that has `\documentclass[...]{subfiles}`)
2. Open the master file
3. Close the master file
4. Hit F5

### Expected behavior
Since the master file is not open, the subfile is compiled. I would expect the "master file state" to be cleared on closing that file.

### Actual behavior
The master file is compiled regardless of what other unrelated files I open. I have to explicitly set master document, or close and reopen the subfile.

**Comment by marczellm** [comment]
If the current behaviour is intentional, then the Root Document menu could maybe include a menuitem called "Active" which would always compile the the document in the active tab.

**Comment by sunderme** [comment]
this is intentional
however, you can set your compile command to `pdflatex -synctex=1 -interaction=nonstopmode ?c:am.tex` , which will take always the current document as compiled document. Or you can define a user command this way to have both modes operations with easy access.
