### ISSUE TITLE
Saving a file resizes the structure view

### ISSUE THREAD

**Issue by RasmusAntons** [texstudio-org/texstudio#43]
Whenever I save a file (either with Ctrl+s or File->Save), the width of the structure view in the side panel resets to a very small value, while the with of the side panel itself is not changed.
[image](https://i.imgur.com/KQBTGzp.png)

This happens every time on both the version in the Archlinux repository (TeXstudio 2.12.6 (hg 6631+:16db084dae24+) Using Qt Version 5.10.1, compiled with Qt 5.9.3 R) and the current master (TeXstudio 2.12.8 (hg 2.12.8-1-g68cd3502) Using Qt Version 5.10.1, compiled with Qt 5.10.1 R).

**Comment by Piraty** [comment]
I can confirm to see the same behaviour as @RasmusAntons , but also a different symptom sometimes: In some cases it seems like a transparent overlay over the first level only, with width of about 10 characters...
I guess the resizing is done as well but the old area (right of the struct-tree's text) remains undefined and therefore still shows the old contents.
The actual pane that separates the struct-tree from source-view remains intact and can be used for restoring the struct-view's text.

Very strange.

_System:_ Void Linux
_TeXstudio_: 2.12.8
_qt_: 5.8

**Comment by Piraty** [comment]
It is a regression.

`TeXstudio 2.12.4 (hg n/a)`
`Using Qt Version 5.10.1`
`compiled with Qt 5.10.1 R`
Does **not** have this issue.

**Comment by sunderme** [comment]
Qt 5.10.1 bug (5.9.4 works fine)

**Comment by sunderme** [comment]
@timhoffm: apparently the refactoring of StructureTreeView plays a role as 2.12.4 works fine...

**Comment by timhoffm** [comment]
Back then, the container widget was a QDockWidget. I exchanged that for a normal QWidget with our TitledPanel to get a consistent appearance with the other parts of the UI. As part of this, the sizing is now controlled by a QSplitter instead of the QDockWidget size.

**Comment by sunderme** [comment]
2.12.4 seems already to use TitledPanel/QWidget

**Comment by timhoffm** [comment]
I can only reproduce this when running Qt 5.10. Possibly related to (but not identical) https://bugreports.qt.io/browse/QTBUG-65592
This is a Qt issue. I currently don't have the time to dig into checking if it's possible to workaround this Qt bug.

**Comment by sunderme** [comment]
the bug is gone again in qt5.11 beta4,only 5.10 and 5.10.1 are affected, so we will not work on work-arounds.

**Comment by sunderme** [comment]
bug is still present with 5.11 beta4, though it occurs a little later

**Comment by sunderme** [comment]
fixed (4cf5c2eb2a8a0353335c0ed6d6be4b3f19c950c3)

**Comment by Piraty** [comment]
thanks a lot for looking into it!
