### ISSUE TITLE
Source code disappears upon "Build & View"

### ISSUE THREAD

**Issue by rylandf** [texstudio-org/texstudio#430]
### Environment
- TeXstudio: 2.12.6
- Qt: 5.9.1
- OS: Windows 10 Home
- TeX distribution: miktex

### Expected behavior
Build and View

### Actual behavior
pdf was generated, but on the source code screen, all code disappears, blank document. After scrolling through pdf, the code will come back, usually with a message about another application changing this file. On latest build, source code disappeared and never came back

### How to reproduce

Build & View

**Comment by sunderme** [comment]
so, is the tex file in a drop box folder any ither folder which is syncronized or otherwise managed by some external resource ?

**Comment by sunderme** [comment]
no feedback
