### ISSUE TITLE
Mint 19 Segmentation fault

### ISSUE THREAD

**Issue by se-sve** [texstudio-org/texstudio#435]
### Environment
- TeXstudio: 2.12.14
- Qt: Qt 5.9.6 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.3.0) on "xcb" 
- OS: Linux Mint 19 [linux version 4.15.0-42-generic]
- TeX distribution: texlive

### Expected behavior
Run texstudio
### Actual behavior
Segmentation fault (core dumped)
### How to reproduce
Start texstudio

###Backtrace
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from texstudio...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/texstudio 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe92c2700 (LWP 10531)]
qt5ct: using qt5ct plugin
[New Thread 0x7fffdf22f700 (LWP 10532)]
[New Thread 0x7fffdddbe700 (LWP 10533)]
[New Thread 0x7fffdcdd6700 (LWP 10534)]
qt5ct: D-Bus global menu: no
[New Thread 0x7fffd5c8f700 (LWP 10535)]
[New Thread 0x7fffd548e700 (LWP 10537)]
[New Thread 0x7fffd4c8d700 (LWP 10539)]

Thread 5 "SafeThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdcdd6700 (LWP 10534)]
__strcmp_sse2_unaligned ()
    at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
31	../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
#1  0x00007fffd416a47c in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#2  0x00007fffd416a79e in OPENSSL_LH_insert () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#3  0x00007fffd41761da in OBJ_NAME_add () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#4  0x00007fffc3b4a5fb in bind_gost (id=0x0, e=0x7fffcc01cd70) at /home/sesve/engine-master/gost_eng.c:280
#5  bind_engine (e=0x7fffcc01cd70, id=<optimized out>, fns=<optimized out>) at /home/sesve/engine-master/gost_eng.c:305
#6  0x00007fffd414998c in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#7  0x00007fffd414916a in ENGINE_ctrl_cmd_string () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#8  0x00007fffd414870e in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#9  0x00007fffd40e4c82 in CONF_modules_load () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#10 0x00007fffd40e522e in CONF_modules_load_file () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#11 0x00007fffd40e5482 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#12 0x00007fffd4168a70 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#13 0x00007ffff4e28827 in __pthread_once_slow (once_control=0x7fffd448b248, init_routine=0x7fffd4168a60) at pthread_once.c:116
#14 0x00007fffd41be939 in CRYPTO_THREAD_run_once () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#15 0x00007fffd4168f10 in OPENSSL_init_crypto () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#16 0x00007ffff618c7d5 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#17 0x00007ffff61873e9 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#18 0x00007ffff6159977 in QSslCertificate::QSslCertificate(QByteArray const&, QSsl::EncodingFormat) () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#19 0x00007ffff615e0b9 in QSslConfiguration::QSslConfiguration() () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#20 0x00007ffff60ff4b8 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#21 0x00007ffff61082b2 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#22 0x00007ffff609e000 in QNetworkAccessManager::createRequest(QNetworkAccessManager::Operation, QNetworkRequest const&, QIODevice*) () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#23 0x00007ffff609b366 in QNetworkAccessManager::post(QNetworkRequest const&, QIODevice*) () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#24 0x00007ffff609b3d1 in QNetworkAccessManager::post(QNetworkRequest const&, QByteArray const&) () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#25 0x000055555578c010 in GrammarCheckLanguageToolJSON::check(unsigned int, int, QString const&, QString const&) ()
#26 0x000055555579410a in GrammarCheck::process(int) ()
#27 0x000055555579440d in GrammarCheck::processLoop() ()
#28 0x0000555555ad0ac5 in ?? ()
#29 0x00007ffff52f15b5 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007ffff52fe113 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007ffff52f20db in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff6ca582c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#33 0x00007ffff6cad0f4 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#34 0x00007ffff52c29a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x00007ffff531ad8e in QTimerInfoList::activateTimers() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x00007ffff531b551 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#37 0x00007ffff239a387 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007ffff239a5c0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007ffff239a64c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#40 0x00007ffff531b8ef in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#41 0x00007ffff52c09ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x00007ffff50df22a in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#43 0x00007ffff50e416d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#44 0x00007ffff4e206db in start_thread (arg=0x7fffdcdd6700) at pthread_create.c:463
#45 0x00007ffff420a88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by sunderme** [comment]
it crashes in a libcrypto from your system.
Nothing I can do about it since we don't offer linux mint builds anyway.
The usual ways to resolve:
1) delete texstudio.ini
2) recompile
