### ISSUE TITLE
Changes in toolbar icons not reloaded on restart

### ISSUE THREAD

**Issue by schwedenmut** [texstudio-org/texstudio#438]
After adding some additional functionality to the toolbar - such as the external pdf viewer to tools - the texstudio ui gets updated and the icon appears. These changes get also persisted in the settings file under `~/.config/texstudio/texstudio.ini` such as `FileToolBar=main/file/new, main/file/open, main/file/save, main/file/close, pdf/view/external`.
After completely restarting texstudio, the newly added functionality icon doesn't appear in the toolbar, but after checking the toolbar settings, it is shown in the settings and after pressing OK the icon appears.  
  
Funnily, removing Build & View and Compile from the toolbar, persists perfectly and after restart both are gone for good.
I also tested on a different Mac with another macOS version - same behavior.

### Environment
- TeXstudio: 2.12.14 (git 2.12.14)
- Qt: 5.11.2
- OS: Mac
- TeX distribution: texlive

### Expected behavior
After starting texstudio, customizations should be loaded and presented to the user. Starting texstudio should present my configured toolbar.

### Actual behavior
After starting texstudio, the icon for external viewer is not present. In Toolbar settings it is shown.

### How to reproduce
Add external viewer from the View category to the tools toolbar. Restart texstudio.

**Comment by sunderme** [comment]
you have been using a menu entry of the pdf viewer which is not valid in the context of txs main program.
the pdf menus are now not shown any more.
If you want to an explicit button for calling an external viewer, you probably need to define it as user command first.

**Comment by schwedenmut** [comment]
@sunderme thanks for your reply, which isn't quite clear to me.
Why is it not valid in the context of txs main program, if I can select the functionality in txs configuration?
![bildschirmfoto 2018-12-28 um 18 41 49](https://user-images.githubusercontent.com/9077622/50523440-6fff7a00-0ad0-11e9-877a-807d0baea14d.png)
And, just for clarification, after going to the configuration and pressing ok the icon correctly gets displayed - and it is not only in question of the pdf viewer icon, also others don't show up..

**Comment by sunderme** [comment]
it was not supposed to be shown in the config. That has been fixed.
