### ISSUE TITLE
PDF viewer window doesnt popup immediately after compile

### ISSUE THREAD

**Issue by pizdjuk** [texstudio-org/texstudio#439]
PDF viewer window doesnt popup immediately after compile (after press F1) if already running in background. The problem triggered with Marco window manager with option 

org.mate.Marco.general.disable-workarounds

enabled.

### Environment
- TeXstudio: 2.10.8
- Qt: 5.5.1
- OS: Linux Mint 18.3
- TeX distribution: texlive

### Expected behavior

To
### How to reproduce

1. Get into MATE, change settings of marco WM:
2. Set PDF viewer "internal windowed" (in the texstudio settings)
3. gsettings set  org.mate.Marco.general disable-workarounds true
4. Compile some tex file, go back, edit something. Compile again (F1). See, that the PDF viewer does not pop up.

**Comment by sunderme** [comment]
so, you are saying with org.mate.Marco.general.disable-workarounds=false it works as expected ?

**Comment by pizdjuk** [comment]
yes. But this means, that texstudio does not implement the modern standarts of WM, no?
