### ISSUE TITLE
Variable argument commands might break structure view

### ISSUE THREAD

**Issue by benibela** [texstudio-org/texstudio#44]
Section 2 is not shown in the structure view in this example, because  the parser confuses `\hyperref[label%ref]{text}
`  with `\hyperref[label%ref]{URL}{category}{name}{text}#S`

```
\documentclass[10pt,a4paper]{article}
\usepackage[latin1]{inputenc}
\usepackage{hyperref}
\begin{document}

\section{1}

using the menu commands \hyperref[a]{\textsf{Save}}.

\section{2}
Important parameters, e.g., the values of 

\section{3}

\end{document}
```

Simplest solution is to just remove `\hyperref[label%ref]{URL}{category}{name}{text}#S` from the CWL

**Comment by timhoffm** [comment]
I'm fine with removing the second version. But will this happen with other commands as well?

**Comment by sunderme** [comment]
fixed
