### ISSUE TITLE
custom grammar and spell checking  server

### ISSUE THREAD

**Issue by alikazemkhanloo** [texstudio-org/texstudio#440]
### Environment
- TeXstudio: latest
### A question and probably a feature request
I want to create a spell and grammar checking server for my language to be used with TexStudio. I found out TXS is already supporting LanguageTool.
#### The question
Should I (Is it a good idea to) use the API structure of LanguageTool to develop the server and make the TXS use my server instead of LanguageTool's?
or
#### The feature request
Add a custom language tool server. with your own API structure.

**Comment by alikazemkhanloo** [comment]
I used my server and it seems like it's working.
But there is a small problem:
for now, this local server simply removes white space before any commas. but texstudio send this text
`this is a text\footnote{a smalltext}, with comma`
as this
`this is a text , with comma`
so I get a space before comma, however it is correct in the LaTeX output.
is there a reason to convert inline commands to space instead of empty string?

**Comment by sunderme** [comment]
actually txs sends (or should send it) as "this is a text          a smalltext , with comma"
txs replaces unused commands/brackets with spaces in order to preserve the position of the words in the line, so that in case of an error, it knows where to put the wiggly line.

**Comment by alikazemkhanloo** [comment]
but the problem in my case is when I right click on the word (say `text ,` with a space before the comma) and replace with the correct form (i.e `text,`), txs will remove the commands/brackets that were supposed to be there.

**Comment by sunderme** [comment]
I don't see a practical way to avoid this.
