### ISSUE TITLE
Missing = inserted for \ifnum 

### ISSUE THREAD

**Issue by robopassio** [texstudio-org/texstudio#442]
### Environment
TeXstudio 2.12.10 (git 2.12.10)
Using Qt Version 5.8.0, compiled with Qt 5.8.0 R
- OS: <!-- Windows 10)
- TeX distribution: miktex
### Problem
I am a beginer in using .tex, I am trying to import the package 'siunitx' by:
\usepackage{siunitx}
Before adding this line, my file is successfully compiled. After adding it the following error is happen.
### Actual behavior
line 283: Missing = inserted for \ifnum. }
line 16: Missing = inserted for \ifnum. \RequirePackage{expl3}[2015/09/11]
line 26: Missing = inserted for \ifnum. \RequirePackage{expl3}[2018-04-12]
line 27: Missing = inserted for \ifnum. \@ifpackagelater{expl3}{2018-04-12}
line 18: Missing = inserted for \ifnum. \ProvidesExplPackage
line 20: Missing = inserted for \ifnum. \@ifpackagelater { expl3 } { 2015/09/11 }
line 22: Missing = inserted for \ifnum. \RequirePackage{expl3}[2018/02/21]
line 23: Missing = inserted for \ifnum. \@ifpackagelater{expl3}{2018/02/21}
line 49: Missing = inserted for \ifnum. \cs_new
### 
Please give me some instructions to solve this problem.
Thank you so much!

**Comment by sunderme** [comment]
That is a Tex problem, please use tex.stackexchange.com for this
