### ISSUE TITLE
$...$ and $$...$$ vs. \(...\) and \[...\]

### ISSUE THREAD

**Issue by DavidCheshire** [texstudio-org/texstudio#443]
TeXstudio is an integrated writing environment for creating LaTeX documents. This post "https://tex.stackexchange.com/questions/410863/what-are-the-differences-between-and" says:

The TeX delimiters for inline math are $ and $.
The LaTeX delimiters for inline math are \( and \).
The TeX delimiters for displayed math are $$ and $$.
The LaTeX delimiters for displayed math are \[ and \].

When I start to type, e.g. \phi in TeXstudio, it automatically puts it into the document as $\phi$. (I haven't found that it puts $$\phi$$ anywhere.)

The issue is: Since TeXstudio is for creating LaTeX documents, why doesn't it use the LaTeX notation?

**Comment by dbitouze** [comment]
>Since TeXstudio is for creating LaTeX documents, why doesn't it use the LaTeX notation?

The advantage of `\(...\)` over `$...$` is technically not significant and has some disadvantages (see the last two § of https://tex.stackexchange.com/a/305471/18401).

About `\[...\]` vs `$$...$$`, the former is technically significantly better (see `l2tabu` package).

**Comment by DavidCheshire** [comment]
The disadvantages mentioned are not significant and, in my view, are not sufficient reason to use TeX notation rather than the defined LaTeX notation. Since TeXstudio is for creating LaTeX documents it should use the LaTeX notation.

**Comment by sunderme** [comment]
First of all, I don't change behaviour for dogmatic reasons. $ is probably used by the vast majority of the users and it works.
If someone provides patches to offer user options to change the delimiters, they will be welcome.

**Comment by DavidCheshire** [comment]
Sorry, I did not mean to be offensive or dogmatic. I have to use \(...\) when writing inline math on web pages because $...$ does for inline mode not work with MathJax - see this tutorial https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference which is helpful, but the inline mode math expressions do not work.
