### ISSUE TITLE
Checksums and/or gpg-signature

### ISSUE THREAD

**Issue by desk7** [texstudio-org/texstudio#444]
Could you gpg sign the installers and/or provide checksums in order to increase security?

**Comment by desk7** [comment]
no answer?

**Comment by sunderme** [comment]
That would tedious work for a very limited number of users...

**Comment by desk7** [comment]
just 256-SHA checksum on download page?

**Comment by sunderme** [comment]
you have seen how many variants are on offer ?

**Comment by benibela** [comment]
The [Sourceforge download page](https://sourceforge.net/projects/texstudio/files/2.12.14/) has checksums, when you click the (i) button

For the linux downloads, you can remove the filename and look on the directory listing
