### ISSUE TITLE
Merge tool for shared tex files

### ISSUE THREAD

**Issue by fdifonzo** [texstudio-org/texstudio#446]
### Environment
- TeXstudio: 2.12.14
- Qt: 5.8.0 
- OS: Windows 10 Pro
- TeX distribution: texlive

### Expected behavior
Since tex file is a standard in scientific production, and papers are usually written by more than one author, which very likely share and work on the same tex file, it would be great to have some tool to merge different versions of the same tex file. 
Actually, there is no feature like this.

**Comment by aubreyz** [comment]
That is a massively complex thing to do and there are plenty of programs out there that specialise in doing exactly that. Like Winmerge http://winmerge.org

**Comment by timhoffm** [comment]
This is beyond the scope of TeXstudio and there are specialized tools for merging, which are more capable than anything we could reasonably add to TeXstudio. We recommend to use external tools for merging.
