### ISSUE TITLE
libpoppler and libtiff problem to compile txs from source

### ISSUE THREAD

**Issue by tmelorc** [texstudio-org/texstudio#448]
When I try to compile `texstudio-2.12.14`  from the source using QT.5.11, I get some _undefined reference to_ errors (in portuguese _referência indefinida para__):

> //usr/lib/x86_64-linux-gnu/libpoppler.so.58: referência indefinida para `TIFFDefaultStripSize@LIBTIFF_4.0'
> //usr/lib/x86_64-linux-gnu/libpoppler.so.58: referência indefinida para `TIFFFdOpen@LIBTIFF_4.0'
> //usr/lib/x86_64-linux-gnu/libpoppler.so.58: referência indefinida para `TIFFWriteScanline@LIBTIFF_4.0'
> //usr/lib/x86_64-linux-gnu/libpoppler.so.58: referência indefinida para `TIFFClose@LIBTIFF_4.0'
> //usr/lib/x86_64-linux-gnu/libpoppler.so.58: referência indefinida para `TIFFSetField@LIBTIFF_4.0'
> collect2: error: ld returned 1 exit status
> Makefile:1220: recipe for target 'texstudio' failed
> make: *** [texstudio] Error 1

I already have `libtiff` and `libpoppler` (but not sure if the correct version).

Any help, please. Thanks in advance.

**Comment by sunderme** [comment]
this looks like a problem of your poppler installation, nothing to do with txs. (arch ?)

**Comment by tmelorc** [comment]
> this looks like a problem of your poppler installation, nothing to do with txs. (arch ?)

I'm using Linux Mint 18. 
Do you have idea what poppler version should I use?

**Comment by tmelorc** [comment]
So do you suggest to update poppler or tiff? I didn't compile poppler, but only tiff. 
I really would like to compile txs.

**Comment by tmelorc** [comment]
Fixed. I compiled `tiff-4.0.10` and now it works.
