### ISSUE TITLE
Dark theme not consistent

### ISSUE THREAD

**Issue by francescoboc** [texstudio-org/texstudio#45]
Hi,
first of all thanks for the awesome work you are doing in maintaining this project, I love TeXstudio! 
There is just one thing that bothers me: the diffuclty to set up a consistent dark theme in the editor. 

I managed to edit my font colors so that now i have a nice dark combination, and setting the color combination to "modern" makes also the UI kind of dark, but still there is a big fat light gray frame around the page that i cannot get rid of:

![image](https://user-images.githubusercontent.com/33369475/36633129-302ab462-1990-11e8-97b8-dafe4cef27b9.png)

It would be PERFECT if I could set up that frame to be black as the rest of the edtior, or at least make it disappear.

thanks,
francesco

**Comment by timhoffm** [comment]
Those elements are styled by the OS theme and currently cannot be modified separately.

You can deactivate the bottom bar using `Config -> Adv. Editor -> Appearance -> Show State Panel`.

**Comment by francescoboc** [comment]
Hello Tim,
thanks for your kind answer. I deactivated the bottom bar and it already look better, indeed!

Are you planning to add the possibility to customize the colour of these bars in future releases?

TexStudio is amazing in terms of functionalities, but I have to say the UI looks a bit "outdated" when compared to other more "stylish" editors, like Atom for example:

![image](https://user-images.githubusercontent.com/33369475/36640582-01bb4a6e-1a22-11e8-9d12-fdba1d8ea0b8.png)

Thank you very much. And also, is there a way I can try to contribute? I am no expert in C++, but I can try...

F.

**Comment by francescoboc** [comment]
Thanks Tim,
that screenshot looks amazing!

What do you mean for "settings directory", is it the one in "Programs" or in "AppData"?

Thanks

**Comment by timhoffm** [comment]
It's the one in AppData.

**Comment by francescoboc** [comment]
Thanks Tim,
it looks great! That's exactly what I was looking for!

![image](https://user-images.githubusercontent.com/33369475/36641098-c3864f06-1a2a-11e8-81c1-8ddf082c84cc.png)

Thank you for your help and keep up the excellent work on this editor!

Francesco

**Comment by dbitouze** [comment]
Would be nice if one could be able to easily load the nice Francesco's theme. (Out of topic: Francesco, you should replace the space between `eq.` and `\ref{...}` by a  a `~`; or, better, you could consider the `cleveref` package which provides `\cref` that would e.g. write for you "following eq.~..." with just `following \cref{Ftot}`).

**Comment by francescoboc** [comment]
I made a rar archive with everything inside. You can download it here: https://www.dropbox.com/s/imkvx08gsjtzww8/TeXstudio_francesco_dark.rar?dl=0

There's also a README file that explains quickly what you have to do to load the UI and the editor themes. Be careful that you have to edit some lines in the stylesheet putting your username instead of "franc", i know it's stupid but I couldn't find a better way to do it...

Thanks for the suggestion on the eq. /ref thing!

**Comment by dbitouze** [comment]
@francescoboc Thanks for providing your theme. But I was asking more an integration in TXS in such a way users not comfortable with their computer may easily benefit from it. Currently, what you provide is Windows oriented and loading your profile may overwrite some customization made earlier.

**Comment by francescoboc** [comment]
@dbitouze Yes, it would be nice to see the dark theme integrated in TexStudio. I have been using this UI theme since yesterday and It's working perfectly. All the elements are in the right place.

**Comment by dbitouze** [comment]
BTW, if you want it to be really dark, you can invert the colors in the PDF viewer.

**Comment by Piraty** [comment]
> Those elements are styled by the OS theme and currently cannot be modified separately.

yes, that's right. in that regard, on linux using recent qt5.10 and all qt5 before, theming in texstudio is not inherited from the OS. This happens to be common issue on some qt-based applications that migrated from qt4 (when OS-specific theming was correctly applied to a qt-gui-app) to qt5 (now lacking the possibility to use the OS theme).
I don't know if it ever worked when qt4 was used.

**Comment by anhility** [comment]
@francescoboc Just a heads up that your profile change the interface language to Italian for everyone that loads your theme. To change that you need to open the file francesco_dark_win.txsprofile in a text editor and edit line 222 from "Interface\Language=**it**" to whatever language code you prefer (en_GB, en_US, de_DE etc) and reload the theme.

**Comment by francescoboc** [comment]
@anhility Yes, I was expecting that. Actually, It will load also other things that I changed according to my needs, for example the paths for the dictionaries and for the external pdf reader... But right now, exporting a complete TeXstudio profile it's the only way to export a color scheme (I think!). 

It would be nice to be able to export only the color scheme and not ALL the settings!

**Comment by sunderme** [comment]
you can edit the profile and remove anything which is not necessary (the ini keys are more or less self-explanatory)
The import of that file changes only the included values, the rest is ignored.
We have not bothered to extend the export-function to limit its scope as that is rather tedious and only a limited number of users may benefit

**Comment by suratovvlad** [comment]
Year ago I've made a fork from sourceforge, today I've moved to this repo:
[new fork](https://github.com/suratovvlad/texstudio/tree/darktheme)
I'm also using [ColinDuquesnoy/QDarkStyleSheet](https://github.com/ColinDuquesnoy/QDarkStyleSheet/tree/master/qdarkstyle)
however, I've built some time ago special [library](https://github.com/suratovvlad/libqdark) to encapsulate whole styles into one place. 

If someone want to help with building for Windows/MacOS this library and this fork, I would really appreciate - I don't have much time.
For Arch Linux users I maintain the special [package](https://aur.archlinux.org/packages/texstudio-dark-git/) in AUR repo

**Comment by Piraty** [comment]
No need for weird magic in linux, you can provide native qt-styles to texstudio.

For example, i have `QT_STYLE_OVERRIDE`. You can place sth like `gtk2` or `Adwaita-dark` in there if you have the corresponding, qt-compatible version of adwaita.
Also, `qt5ct` may be of interest.

Here is mine:
`QT_STYLE_OVERRIDE=gtk2`, where gtk2 picks up adwaita-dark.
![screenshot_2018-03-15_09-31-51](https://user-images.githubusercontent.com/23238955/37452376-b415645e-2834-11e8-9f40-dcc757d41ad7.png)

**Comment by Subratappt** [comment]
@francescoboc Everything is working fine. But the pop-up on hover are not dark. These are still white. How to make these dark ?
![clip](https://user-images.githubusercontent.com/40207448/41796038-84763d9e-7682-11e8-9a3b-c65a9dc548ab.png)
![clip2](https://user-images.githubusercontent.com/40207448/41796039-84bf73e2-7682-11e8-9a36-dddaa4ab6e91.png)
Thank you.

**Comment by timhoffm** [comment]
The dark theme is not part of the official TeXstudio release and we cannot provide any help or support for it.

That said, I can only do a wild guess. The above theme includes styles QToolTips. It may however be that this does only work for simple tooltips, but not for HTML tooltips. You may check if simple tooltips are styled (e.g. hover over an editor tab to display the filename in a test-only tooltip. If that's the case, there's probably nothing we can do about it.

**Comment by JamesLarkinWhite** [comment]
Wow this is extremly cool! IT worked out of the box. I do however have a small question/request....
Is it possible to change the "save icon" such that it has a well readable color on the dark baground?

**Comment by bf** [comment]
This dark theme is really great. Do we need to form texstudio to publish a release with dark theme as first class citizen or is it possible to add it? The white kills my eyes when working at night!

**Comment by Minjeong-Song** [comment]
@francescoboc @timhoffm 
Thank you for such a nice theme!! This is exactly what I looking for! But I can I ask some questions..? 

1/ Every other font color is white and it is very readable. But the color of symbols in the side panel is still black so it is hard to recognize each symbol. Is it possible to change the color of symbols in the side panel from black to white?
![symbol](https://user-images.githubusercontent.com/42118776/43688264-711c1514-9920-11e8-801c-a44a50f580ce.png)

2/ The similar problem in 'Syntax Highlighting' in 'configure TeXstudio' in 'Options'. The background color is white and the color of entries of Identifier is also white...
Is it possible to change background color here from white to black just like the other menu tap in 'configure TeXstudio'? for instance, in 'general' tap the background color is well-defined as black color.
![syntax](https://user-images.githubusercontent.com/42118776/43688370-63ec0c6c-9922-11e8-8033-e1d9adb79721.png)
![general](https://user-images.githubusercontent.com/42118776/43688375-705d1ac2-9922-11e8-8190-178176c1a2b5.png)

Thank you :)

**Comment by timhoffm** [comment]
#### 1) Symbol color
The symbols are SVGs with black symbols on transparent background. There's no out-of-the box way to fix that. One would have to either create light-colored copies of the SVGs or TXS would have to manipulate the SVGs before loading.

#### 2) Background of highlighting table
This used hard-coded styles for the background. I've now added a patch that we do not adapt the style if an external style sheet is present, i.e. this is fixed in master and will be included in the next release.

**Comment by thatlittleboy** [comment]
@timhoffm Considering that the default background colour of the symbols sidebar is white (#FFFFFF), would the team be open to accept a PR for changing all the symbol svg's to a white background instead of transparent?
Presumably these are the ones in the symbols and symbols-ng folder.

On the default user side, there should not be any visible changes, but would be extremely helpful for those implementing dark mode stylesheets.

I am also a little bothered by the fact that the symbols do not have equal width and height (cf. any up-down arrows vs. the left-right ones). I guess these could be fixed in the meantime as well?

I'm willing to undertake this work, but I want to know whether would be acceptable / any reasons for the symbol svgs background to remain transparent first.

**Comment by timhoffm** [comment]
> changing all the symbol svg's to a white background instead of transparent?

IMO that's not the way to go. Apart from the mentioned aspect issue, I'm not sure that this will work borderless with varying magnifications. If we want to enforce a white background, we can simply hard-code the stylesheet for the symbol widget. That's much simpler than messing with the SVG backgrounds.

On the down side, we're sort of breaking the dark style with a white background.

**Comment by timhoffm** [comment]
> Is the symbol widget accessible by stylesheet now, or is it still hard-coded as was the syntax highlighting table?

Neither. I don't think you can define styles for individual widgets via a qss file. You can however set a style for an individual widget via code `widget->setStyleSheet(text)`. This was the case for the highlighting table. If no style is set to the widget, the global style will be used.

My proposal for a fixed white background is exactly to  `widget->setStyleSheet("background: white")`. On the symbol widget.

As for "breaking the style": The menu symbols are only small areas. Changing the background of all symbols would result in a large white area, which may be perceived as not style-compliant. Anyway the general issue of dark symbols on dark background is not trivially solved, neither in the symbol widget nor in the menus. This is actually one of the main reasons we do not natively support a dark theme.

**Comment by thatlittleboy** [comment]
> Changing the background of all symbols would result in a large white area, which may be perceived as not style-compliant.

Yes, that's true. I missed that point.
Your proposal sounds good.

> Anyway the general issue of dark symbols on dark background is not trivially solved, neither in the symbol widget nor in the menus. 

At least for the menu icons, there's no issue of the "large white area" if the backgrounds were set to white. The math accents and math font style icons can at least be made consistent, no? (presumably with the svgs, not stylesheet)
But yes, I understand the devs' POV of not natively supporting dark theme. All these are non-issues if one does not use a dark theme. I won't push this any further. :)

**Comment by lhecht** [comment]
Wow, so impressed. It worked for me, too.
And I am really looking forward for the next release, to get the highlighting table back.
Thank you very much for the effort!

**Comment by timhoffm** [comment]
In the long run, I would like to improve the support for a dark theme (or maybe even include one). That means in particular to have a set of suitable menu icons, and thus a switching mechanism. We already have that partly for classic/modern. However, there's more to do to make it work smoothly. Pointing out or fixing open issues is worthwhile because we can gradually improve things.

**Comment by Minjeong-Song** [comment]
Thanks a lot for all your effort!! :)

**Comment by JamesLarkinWhite** [comment]
If using the dark sceme, the results displaced in the search bar are also obscured sometimes. If you search for a string , and it is not matched, the background turns red. The "search string" is not readable in this case.

**Comment by NikoKrause** [comment]
> In the long run, I would like to improve the support for a dark theme (or maybe even include one). That means in particular to have a set of suitable menu icons, and thus a switching mechanism.

If you are planing to support dark themes, have you considered switching to symbolic icons?
Those will work in bright and dark themes.

**Comment by Kardi5** [comment]
FYI and for people that might arrive here via internet search. 

If you want to have checkboxes/radio buttons/etc (icons) put the _rc_ folder from [here](https://github.com/ColinDuquesnoy/QDarkStyleSheet/tree/master/qdarkstyle) inside the _dictionaries_ folder of your TeXstudio installation and change all file paths inside the stylesheet.qss from 
`image: url(":/qss_icons/rc/...` 
to 
`image: url("rc/...`.

Before:
![grafik](https://user-images.githubusercontent.com/15264610/61719423-2b397a00-ad65-11e9-976c-730beb699bf2.png)
After:
![grafik](https://user-images.githubusercontent.com/15264610/61719348-06450700-ad65-11e9-92f1-a02fe6c2f9d4.png)

Why into the _dictionaries_ folder? Because, at least for me, it was the relative working directory of the texstudio.exe. I agree this is a hack, but I really wanted the checkboxes on the settings page back. 

Note: There are still no arrows displayed as the names inside the stylesheet.qss do not match the names of the arrow files. After changing this the arrows were scaled inappropriately (too large), so I changed it back.

**Comment by suratovvlad** [comment]
I used this stylesheet in my fork https://github.com/suratovvlad/texstudio , but I do not provide windows build yet, only AUR package https://aur.archlinux.org/packages/texstudio-dark-git/
If it would be interesting, I could provide window build, as I do it for qbittorrent-dark fork.

**Comment by adwaraki** [comment]
I was trying to adopt @francescoboc and @timhoffm's comments to work on my TXS on macOS, but I was not able to find the location of the stylesheets to make the modifications. Would anyone be able to shed some light on where these are located? Would love to get @francescoboc's look on my TXS, and cannot unzip and use his archive for the same reasons.

I did try looking in Package Contents and all the resource folders on macOS, but could not find the files anywhere. I am not sure if I am missing something here.

**Comment by thatlittleboy** [comment]
@adwaraki If the `stylesheet.qss` file does not exist, then just create a new one yourself and/or copy the one from the earlier comments. Place it in the config directory.

**Comment by adwaraki** [comment]
@thatlittleboy Thank you for that info. I kinda had figured that out already, but what I am confused with are the paths in the stylesheet. For example, 

```
QCheckBox::indicator:unchecked {
    image: url(C:/Users/XXXXX/AppData/Roaming/TeXstudio/rc/checkbox_unchecked.png);
}

```

I am not sure what path to replace here, since I am not able to find the TexStudio/rc folder on the macOS installation.

**Comment by Subratappt** [comment]
This is the path for macOS
`/Users/YourName/.config/texstudio`

![Screen Shot 2019-08-20 at 7 50 59 PM](https://user-images.githubusercontent.com/40207448/63355585-fc262080-c383-11e9-9cdd-1155e0d6d0fc.png)

**Comment by Subratappt** [comment]
`/Users/YourName/.config/texstudio`

> @thatlittleboy Thank you for that info. I kinda had figured that out already, but what I am confused with are the paths in the stylesheet. For example,
> 
> ```
> QCheckBox::indicator:unchecked {
>     image: url(C:/Users/XXXXX/AppData/Roaming/TeXstudio/rc/checkbox_unchecked.png);
> }
> ```
> 
> I am not sure what path to replace here, since I am not able to find the TexStudio/rc folder on the macOS installation.

The path for macOS is
/Users/YourName/.config/texstudio

![Screen Shot 2019-08-20 at 7 50 59 PM](https://user-images.githubusercontent.com/40207448/63355817-663ec580-c384-11e9-93e0-b721a362c0b6.png)

**Comment by adwaraki** [comment]
@Subratappt 
Ah, thank you. I mistakenly assumed that the .config folder was different from the TXS folder on Windows and was looking for it under Package-Contents. Silly me did not put 2 and 2 together. 

Let me try to get this working. Appreciate the help once again.

**Comment by adwaraki** [comment]
Worked like a charm. Thanks a ton!

**Comment by buran21** [comment]
Hello.
Many thanks for the dark theme, works for TeXstudio v2.12.22 win10. There is a small but annoying detail. I have a paper with few appendix sections. They are marked on the left tree view by a "greenish background" (#c8e6c8) and together comprise a bright spot with poorly readable text. It seems that appendix tree color is hard coded as it doesn't present in stylesheet.qss. Is there a way to change that color?

**Comment by xacbeyond** [comment]
> I made a rar archive with everything inside. You can download it here: https://www.dropbox.com/s/imkvx08gsjtzww8/TeXstudio_francesco_dark.rar?dl=0
> 
> Edit: just adding a final screenshot to show how it looks like if anybody else is interested in downloading the theme (i did some changes with respect to the previous screenshot, and I also updated the stylesheet of @timhoffm to the latest [QDarkStyleSheet](https://github.com/ColinDuquesnoy/QDarkStyleSheet/tree/master/qdarkstyle) which has blue highlighted tabs and new icons)
> 
> ![image](https://user-images.githubusercontent.com/33369475/36645380-16dd72be-1a68-11e8-801f-5ec7f7af7070.png)
> 
> Inside the .rar archive a README file explains quickly what you have to do to load the UI and the editor themes. Be careful that you have to edit some lines in the stylesheet putting your username instead of "franc", i know it's stupid but I couldn't find a better way to do it (%APPDATA% does not work for some obscure reason)...
> 
> PS. Thanks for the suggestion on the eq. /ref thing!

Thank you very much!

**Comment by sunderme** [comment]
looks good
1) how do you want to call the style
2) I see white background in the option/syntax hightlighting tab ?

**Comment by francescoboc** [comment]
> looks good
> 
> 1. how do you want to call the style
> 2. I see white background in the option/syntax hightlighting tab ?

Hi, are you asking to me?

**Comment by sunderme** [comment]
Ideally I am asking the author of the stylesheet, so maybe you ?

**Comment by francescoboc** [comment]
@sunderme 
1. Well, the colors are heavily inspired by https://github.com/nanotech/jellybeans.vim, so I guess I'd just call it jellybeans
2. Yes, I had that problem as well, until I updated the QDarkStyleSheet and things are now kind of ok:
![image](https://user-images.githubusercontent.com/33369475/113474997-6fa27600-9473-11eb-8464-5600aa0aea95.png)

**Comment by sunderme** [comment]
It has been added to txs.

**Comment by francescoboc** [comment]
> It has been added to txs.
> (Though not the syntax highlighting, I have not decided what to do with that or where to store a collection of that)

Oh ok. But then if you haven't added the syntax highlighting, it is not fair to call it "jellybeans", since that is really the name of a vim syntax highlighting colour scheme...

**Comment by sunderme** [comment]
then propose another name

**Comment by francescoboc** [comment]
> then propose another name

Ok, then let's say "Orion".

**Comment by hasecilu** [comment]
I created a dark theme for the text editor if someone is interested.
https://github.com/hasecilu/Dark-TeXstudio

**Comment by sunderme** [comment]
> I created a dark theme for the text editor if someone is interested.
> https://github.com/hasecilu/Dark-TeXstudio

probably best to write this in the wiki (tips&tricks ?)

**Comment by Atcold** [comment]
Is there (now, in 2023) a standard way to try out different syntax style sheets?
Where can I browse existing themes?
