### ISSUE TITLE
Editor jumps over `\` when it should not

### ISSUE THREAD

**Issue by halirutan** [texstudio-org/texstudio#450]
### Environment
- TeXstudio: 2.12.14
- Qt: 5.5.1
- OS: Ubuntu 16.04
- TeX distribution: not important

### Expected behavior

Type `\(` (or `\[`) to get the closing part `\)` inserted automatically. Now, try to type something like `\Gamma` to get `\(\Gamma\)`.

### Actual behavior

The editor thinks I want to jump over the already existing `\`. You will end up with `\(\Gamma)` which is of course wrong.

I believe the editor is trying to be too smart in this situation and the result is more annoying than helpful. With this, it will never be possible to insert a tex-command at the end of a math environment.

**Comment by sunderme** [comment]
this has already been fixed in the repository. Try a daily build.
