### ISSUE TITLE
Feature request: An AppImage that contains a minimal TeX installation

### ISSUE THREAD

**Issue by probonopd** [texstudio-org/texstudio#451]
### Environment
- TeXstudio: AppImage

### Expected behavior
I can double-click the AppImage and start writing a document, without needing to install TeX on my system first

### Actual behavior
I need to mess around and install TeX on my system first, which may or may not be possible (e.g., on locked down lab machines)

### How to reproduce
Run a Linux Live ISO and execute the AppImage, then try to make a PDF from a TeX document.

**Comment by sunderme** [comment]
no interest in also managing that.
