### ISSUE TITLE
2.12.14 fails to compile, file not found "JlCompress.h"

### ISSUE THREAD

**Issue by jonasstein** [texstudio-org/texstudio#454]
### Environment
TeXstudio 2.12.14
Using Qt Version 5.11.3, compiled with Qt 5.11.2 R
dev-libs/quazip-0.7.6

can not compile from the source:

```
src/spellerutility.cpp:14:10: fatal error: JlCompress.h: No such file or directory
 #include "JlCompress.h"
          ^~~~~~~~~~~~~~
compilation terminated.

```

https://github.com/texstudio-org/texstudio/blob/master/src/spellerutility.cpp#L14
(same for `templatemanager_p.cpp`)

There is no such file `JlCompress.h` in `src`
It should be
`#include <quazip5/JlCompress.h>`
and it needs to be linked.

**Comment by sunderme** [comment]
as it compiles fine on all platforms (see travis-ci), are you sure that it is not a problem on your side ?

**Comment by jonasstein** [comment]
Found it... my fault. Sorry....

**Comment by topazus** [comment]
```
src/spellerutility.cpp:14:10: fatal error: JlCompress.h: No such file or directory
   14 | #include "JlCompress.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:7378: .obj/spellerutility.o] Error 1
```
I got the same build error, Could you tell me how do you solve it? @jonasstein

**Comment by jonasstein** [comment]
Long time back... I do not remember, sorry. But I guess it was a missing dependency.

**Comment by Begasus** [comment]
There has been a patch around for a while, needed to use this on Haiku also to use the newer quazip version: https://gitlab.com/liguros/liguros-repo/-/blob/develop/app-office/texstudio/files/texstudio-3.0.5-quazip1.patch
