### ISSUE TITLE
\input and \include causing issues in documenti outline

### ISSUE THREAD

**Issue by arielsboiardi** [texstudio-org/texstudio#456]
### Environment
- TeXstudio: 2.12.14 
- Qt: 5.8.0
- OS: Windows 10 
- TeX distribution: miktex

### Expected behavior
The document ouline should be like this
![immagine](https://user-images.githubusercontent.com/29163384/50599037-0c4cc680-0ead-11e9-81b6-165225e815c1.png)

### Actual behavior
When I try to include a file using `\include` the file shows in the document outline (which is not optima IMO but i can see that somebody could like it). What I think is a bug is that the structure is not preserved. 
![immagine](https://user-images.githubusercontent.com/29163384/50599115-5d5cba80-0ead-11e9-86d6-4bc5683b7c0a.png)

### How to reproduce
This minimal example should reproduce the beahviour
\section{A}

\subsection{a}
\input{file}
\subsection{b}

![immagine](https://user-images.githubusercontent.com/29163384/50599200-9e54cf00-0ead-11e9-8dd9-350f727f0351.png)

**Comment by sunderme** [comment]
this behaviour can be changed in the option

**Comment by arielsboiardi** [comment]
Oh I found it, sorry; i could not imagine there was a use for this behaviour and so i thought it was a bug. Thanks for your kind reply and all the great work to TeXstudio.

**Comment by tilsche** [comment]
For reference: the specific option is to enable:

[x] Show Advanced Options
Adv. Editor
Structure Panel
[x] Keep indentation of includes in structure tree
