### ISSUE TITLE
minor code cleanup QT_VERSION

### ISSUE THREAD

**Issue by jonasstein** [texstudio-org/texstudio#459]
https://github.com/texstudio-org/texstudio/blob/master/src/spellerutility.cpp#L183

what do you think about the following change to make the code more readable?

    #if QT_VERSION >= 0x050400
    change to
    #if QT_VERSION >= QT_VERSION_CHECK(5, 0, 4)

**Comment by timhoffm** [comment]
Ok. Slightly more readable. But its `QT_VERSION_CHECK(5, 4, 0)` :smile:.

**Comment by sunderme** [comment]
no advantage of changing this, especially as it might introduce new bugs
