### ISSUE TITLE
The editor does not recognize commands defined in another subdocument

### ISSUE THREAD

**Issue by netw0rkf10w** [texstudio-org/texstudio#46]
Hello,

I have a main document `thesis.tex` that is based on different subdocuments:
```
\input{Preamble/preamble}
\begin{document}
\include{Chapter1/chapter1}
\end{document}	
```
In `./Preamble/preamble.tex` I define the following commands:

```
\newcommand{\x}{\mathbf{x}}
\newcommand{\y}{\mathbf{y}}
```
Now if I use them in `./Chapter1/chapter1.tex`:

- If I type `\x` then the editor suggestes `\xi`.
- if I type `\y` then it suggests `\year` (and I will have to delete `ear` to obtain `\y`).

This is very annoying. Could you please fix this? I would appreciate it a lot if somebody can help me with some workaround while waiting for this to be fixed.

Thank you very much in advance!

**Comment by Piraty** [comment]
I use a similar approach and autocompletion works for my custom commands. There is some option in the settings that regards this, don't know which exactly right now (you might have to enable advanced mode)

**Comment by timhoffm** [comment]
Which version?

Have you activated the advanced option `Options -> Editor -> Editor-> Automatically load included files`?

**Comment by netw0rkf10w** [comment]
@timhoffm Indeed, that solved my problem! Thanks a lot! (I had to temporarily switch to Texmaker over the last few days, but now I'm happy to switch back to TeXstudio.)

Also thanks to @samcarter8 and @Piraty for your replies.

**Comment by netw0rkf10w** [comment]
@timhoffm I think the option `Automatically load included files` should be enabled by default. (Asking for the sake of users who have had or will have the same problem).

**Comment by thatlittleboy** [comment]
@netw0rkf10w The TXS user manual mentions 

> More recent versions of TeXstudio have an advanced option `Editor -> Automatically load included files`. It's disabled by default for performance reasons with older systems.

Just fyi. :)

**Comment by netw0rkf10w** [comment]
Didn't see that. Thanks, @thatlittleboy !
