### ISSUE TITLE
Text search does not work as expected

### ISSUE THREAD

**Issue by gkvallis** [texstudio-org/texstudio#464]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior
Finds the content of a search string. For example, if I search for 'pass' the first occurrence that it finds will indeed be 'pass'

### Actual behavior
The search does not utilise the last letter in the search string on the first occurrence. Example: after entering 'pass' in the find box, the first string to be found is 'past' not 'pass',  if past appears earlier in the document, and if there is some separation between past and pass.  If I do a cmd-g the next occurrence found is, properly, 'pass'.  See also example below.  Other editors will automatically skip over 'past' and go straight to 'pass' on entering the second 's' in the search box. 

### How to reproduce
1. Create a document.  Add a page of random text to the top. 
2. Add the word atmosphere after the text.
3. Add another page of random text
4. Add the work atmospheric after this text
5. Put cursor to the top of the document and search for atmospheric.
6. The cursor will find atmosphere first.

**Comment by sunderme** [comment]
works as expected (linux,2.12.14).

There is a reason why we ask for OS,version number etc.

**Comment by gkvallis** [comment]
Sorry,  I thought I had included this, but evidently it was commented out.

Mac, OS 10.14
Tex Studio 2.12.14   (but same problem with earlier versions)
Qt 5.11.12

**Comment by sunderme** [comment]
works fine on osx as well.
Please provide a screencast in case I misunderstand your description ...

**Comment by gkvallis** [comment]
Here is a screenshot. 
<img width="1028" alt="screen shot 2019-01-07 at 10 38 34 pm" src="https://user-images.githubusercontent.com/7150751/50797673-75797300-12cd-11e9-8083-ddfb361f1bb5.png">
I am searching for the word 'atmospheric' which is off the screen. In the search box I have typed 'atmospheri'  and the cursor has highlighted atmosphere, and has not jumped forward to atmospheric.

**Comment by gkvallis** [comment]
I am afraid I also see the same problem with the default settings, after deleting texstudio.ini as per the instructions. The problem occurs both on my desktop and laptop, which are both Macs with very similar configurations.

**Comment by timhoffm** [comment]
@sunderme can you reproduce the example on OSX?

**Comment by sunderme** [comment]
not reproducible
