### ISSUE TITLE
Copy file name to clipboard

### ISSUE THREAD

**Issue by tmelorc** [texstudio-org/texstudio#465]
It would be useful to be able to copy to clipboard the name of an opened file from the structure tree, maybe using mouse right button.

**Comment by foreachthing** [comment]
Use "show in Explorer", then you can copy the file name.

**Comment by jonasstein** [comment]
![image](https://user-images.githubusercontent.com/298682/51275808-3cc75100-19d3-11e9-8a8b-78c9ac6db135.png)
something like this?

**Comment by tmelorc** [comment]
This is my idea, in addition of seeing the file in folder, simply copy its name.

**Comment by kbauer** [comment]
There is *File → Fixfix → Copy filename to clipboard". The functionality is however not available from the context menu of the structure view.
