### ISSUE TITLE
Remap "Home" and "End" keys

### ISSUE THREAD

**Issue by loefflerd** [texstudio-org/texstudio#467]
In Mac OS X, the "Home" and "End" keys are (weirdly) mapped by default to "start of document" and "end of document". On my system I have these re-bound to "start/end of line" using the system-wide config file ~/Library/KeyBindings/DefaultKeyBinding.dict. However TeXstudio does not obey this, and I cannot find any way to re-map these keys using the TeXstudio preferences screen. (I tried using Shortcuts -> Editor -> Basic Key Mapping but that does not seem to support assigning shortcuts to the Home / End keys). 

It would be nice if TeXstudio could support configuring the action of Home / End keys, either via the systemwide Library/KeyBindings interface or through its own preferences window.

If it matters, I'm using TeXstudio 2.12.14 under Mac OS X 10.14 (Mojave).

**Comment by timhoffm** [comment]
In `Shortcuts -> Editor -> Basic Key Mapping` one of the ways to insert a shortcut is double-clicking and typing the string of the shortcut. So just "end" should work. See also the tooltip

![grafik](https://user-images.githubusercontent.com/2836374/50979779-85749b00-14f7-11e9-9a79-693347df9f04.png)

**Comment by loefflerd** [comment]
Now I feel silly! That didn't work the first time I tried it (the OS hijacked the "End" key and moved to the end of the drop-down menu instead) but I didn't spot that it does indeed work if the drop-down menu isn't opened at the time. Apologies for the noise, I'll close the ticket.
