### ISSUE TITLE
Spell checker wants to correct Awordnowbodyknows with Awordnowbodyknows

### ISSUE THREAD

**Issue by jonasstein** [texstudio-org/texstudio#468]
```
TeXstudio 2.12.14 (git n/a)
Using Qt Version 5.11.3, compiled with Qt 5.11.3 R
```

### How to reproduce
write in a new document
```
awordnowbodyknows
awordnowbodyknows
Awordnowbodyknows

```

The spellchecker will not know it and mark it 
![image](https://user-images.githubusercontent.com/298682/50982452-827ca900-14fd-11e9-8852-65d8302e5bc8.png)
Now add the first word to the users ignore list by clicking on it with the right mouse button ...

TeXstudio ignores `awordnowbodyknows`  now, and knows that the uppercase version is fine too, but marks it red. It suggests to substitute `Awordnowbodyknows` with `Awordnowbodyknows`
![image](https://user-images.githubusercontent.com/298682/50982548-ba83ec00-14fd-11e9-9d4d-8d4d8074bac2.png)

**Comment by sunderme** [comment]
fixed
