### ISSUE TITLE
TexStudio crashes when it tries to open a file of my book.

### ISSUE THREAD

**Issue by kevinecahill** [texstudio-org/texstudio#469]
I have found that TeXShop 4.22 on Mojave repeatedly halts when compiling my book, so I decided to try TexStudio.  But TexStudio crashes when it tries to open a file of my book.  So it's even worse than TeXShop.  TeXShop 4.22 runs well on High Sierra but it's a hairshirt on Mojave.

A pdf of my book amounts to more than 1000 pages when compiled with the solutions to the exercises.

### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution:

**Comment by aubreyz** [comment]
This must be the most non-informative unhelpful bug report ever.  What file? What crash? What relevance is the size of the pdf? Were you trying to open the pdf?

**Comment by kevinecahill** [comment]
TexStudio became nonresponsive when I asked it to open the latex file of my book.
This happened three times.
TexStudio never was able to open my latex file.
TexStudio just displayed the Apple worry wheel.
Activity Monitor said TexStudio was not responding each time I tried to use it to edit my book.

I mentioned the size of the pdf of my book to give some idea of its size.

Apparently, TexStudio works only on latex files of modest sizes.
The latex file of my book is 2.6 MB.

Best wishes,
Kevin
---
Kevin Cahill
Professor of Physics & Astronomy
Physics Dept. 1919 Lomas NE, MSC 07 4220
University of New Mexico
Albuquerque, NM 87131-0001

kevinecahill@gmail.com<mailto:kevinecahill@gmail.com>
505 205 5448

[cid:C3C7D402-4BE8-44C7-BFD3-9ACC5D8F3BA0]

On Jan 11, 2019, at 1:38 AM, aubreyz <notifications@github.com<mailto:notifications@github.com>> wrote:


This must be the most non-informative unhelpful bug report ever. What file? What crash? What relevance is the size of the pdf? Were you trying to open the pdf?

**Comment by kevinecahill** [comment]
PS

I am running Mojave on a very new MacBook Pro with 32 MB of ram a 1 TB solid-state disk and a 2.9 GHz Core i9.

TeXShop compiles my book without problems under High Sierra, but halts intermittently under Mojave.
That’s why I tried TexStudio, which seems to work only on latex files of modest size.

Best wishes,
Kevin
---
Kevin Cahill
Professor of Physics & Astronomy
Physics Dept. 1919 Lomas NE, MSC 07 4220
University of New Mexico
Albuquerque, NM 87131-0001

kevinecahill@gmail.com<mailto:kevinecahill@gmail.com>
505 205 5448



On Jan 11, 2019, at 2:01 AM, Kevin Eric Cahill <cahill@unm.edu<mailto:cahill@unm.edu>> wrote:

TexStudio became nonresponsive when I asked it to open the latex file of my book.
This happened three times.
TexStudio never was able to open my latex file.
TexStudio just displayed the Apple worry wheel.
Activity Monitor said TexStudio was not responding each time I tried to use it to edit my book.

I mentioned the size of the pdf of my book to give some idea of its size.

Apparently, TexStudio works only on latex files of modest sizes.
The latex file of my book is 2.6 MB.

Best wishes,
Kevin
---
Kevin Cahill
Professor of Physics & Astronomy
Physics Dept. 1919 Lomas NE, MSC 07 4220
University of New Mexico
Albuquerque, NM 87131-0001

kevinecahill@gmail.com<mailto:kevinecahill@gmail.com>
505 205 5448

<Jacket.gif>

On Jan 11, 2019, at 1:38 AM, aubreyz <notifications@github.com<mailto:notifications@github.com>> wrote:


This must be the most non-informative unhelpful bug report ever. What file? What crash? What relevance is the size of the pdf? Were you trying to open the pdf?

**Comment by jonasstein** [comment]
@kevinecahill does everything work fine, if you disable the internal pdf viewer and use an external pdf viewer?

**Comment by kevinecahill** [comment]
I have not tried to use an external viewer.  I went back to TeXShop, which halts under Mojave.

Best wishes,
Kevin
Albuquerque

On Jan 16, 2019, at 11:51 AM, Jonas Stein <notifications@github.com<mailto:notifications@github.com>> wrote:


@kevinecahill<https://github.com/kevinecahill> does everything work fine, if you disable the internal pdf viewer and use an external pdf viewer?

**Comment by sunderme** [comment]
okay, since we don't have a test case, there is nothing more we can do.
