### ISSUE TITLE
Website does not provide the current version to download

### ISSUE THREAD

**Issue by Ethunxxx** [texstudio-org/texstudio#47]
The website of the project (https://texstudio.org/) still offers version 2.12.6 as the latest version to download. However, the current release in Github is 2.12.8 (https://github.com/texstudio-org/texstudio/releases).
I think it's important to keep the website up-to-date since most users will not compile Textstudio from source but instead just use the latest version available on the website.

**Comment by timhoffm** [comment]
The 2.12.8 release is not yet official. Therefore it's not announced on the website.

**Comment by Ethunxxx** [comment]
Ah ok, thanks for the fast reply. I thought since it is not marked as beta any more that it would already be official. 
This issue can be closed then. Cheers!

**Comment by timhoffm** [comment]
Well, basically it's ready. I just have to find time to update my build system for the windows binaries (changed vcs, newer Qt, changes to code signing).
