### ISSUE TITLE
ABI problem with appimage on Ubuntu 14.04.3 LTS

### ISSUE THREAD

**Issue by bouloumag** [texstudio-org/texstudio#472]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior

AppImage should work on Ubuntu 14.04.3 LTS

### Actual behavior

./texstudio-2.12.14-x86_64.AppImage 
./texstudio-2.12.14-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./texstudio-2.12.14-x86_64.AppImage)
./texstudio-2.12.14-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./texstudio-2.12.14-x86_64.AppImage)
./texstudio-2.12.14-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./texstudio-2.12.14-x86_64.AppImage)
./texstudio-2.12.14-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /tmp/XYZ/38637/.mount_texstuZWNBO0/usr/bin/../lib/libQt5Core.so.5)
./texstudio-2.12.14-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/XYZ/38637/.mount_texstuZWNBO0/usr/bin/../lib/libpoppler.so.58)
./texstudio-2.12.14-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/XYZ/38637/.mount_texstuZWNBO0/usr/bin/../lib/libproxy.so.1)
./texstudio-2.12.14-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/XYZ/38637/.mount_texstuZWNBO0/usr/bin/../lib/libproxy.so.1)
./texstudio-2.12.14-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /tmp/XYZ/38637/.mount_texstuZWNBO0/usr/bin/../lib/libicui18n.so.55)
./texstudio-2.12.14-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /tmp/XYZ/38637/.mount_texstuZWNBO0/usr/bin/../lib/libicuuc.so.55)

### How to reproduce

Download appimage and execute it on ubuntu 14.

**Comment by sunderme** [comment]
works for me, not approach to denug
