### ISSUE TITLE
\Big is linked to the wrong packaeg

### ISSUE THREAD

**Issue by jonasstein** [texstudio-org/texstudio#476]
- TeXstudio: 2.12.14

right click on `\Big` opens
![image](https://user-images.githubusercontent.com/298682/51277616-69319c00-19d8-11e9-9e96-0cf08ccdb518.png)

But it is not part of the `ctablestack` package. 
I found it in
`grep "Big"  ~/.config/texstudio/completion/autogenerated/ctablestack.cwl `

How can I fix this? Will I have to create a manually generated ctablestack.cwl  and prepare a PR to fix this?

**Comment by sunderme** [comment]
txs uses the cwl-lists to determine which command belongs to which package.
Since ctablestack is an automatically/personal cwl, it "\\Big" might be in there ...
