### ISSUE TITLE
TexStudio spell checking still claim error in comments

### ISSUE THREAD

**Issue by OyHMaths** [texstudio-org/texstudio#479]
### Environment
- TeXstudio:  2.12.14
- Qt: 
- OS:  Mac
- TeX distribution: 

### Expected behavior

The TexStudio spell checking should ignore contents in comments.
### Actual behavior

The TexStudio spell checking should claim errors in comments.
### How to reproduce
???

**Comment by sunderme** [comment]
works fine here.
please provide a screenshot

**Comment by OyHMaths** [comment]
Dear Sunderme,

Thanks a lot for your reply. Please kindly find the following screenshot.
![screenshot 2019-01-18 10 03 18](https://user-images.githubusercontent.com/46808820/51404546-98dfc180-1b08-11e9-911e-795e8a191d49.png)
![screenshot 2019-01-18 10 03 49](https://user-images.githubusercontent.com/46808820/51404566-a4cb8380-1b08-11e9-90a7-f9d3a4ec8b43.png)
![screenshot 2019-01-18 10 04 32](https://user-images.githubusercontent.com/46808820/51404577-abf29180-1b08-11e9-9475-8ca6fc82e33d.png)

**Comment by sunderme** [comment]
the online checking does not check in comments, the dialog does not know anything about latex syntax, so it checks everywhere.

**Comment by OyHMaths** [comment]
Dear Sunderme,

Do you have any easy way that we can quickly check only spelling in the text that I want to show in my PDF but ignore comments?  You mentioned "online checking", is this not what I am using? How can I use the online checking? I am sorry about my stupid question.

**Comment by sunderme** [comment]
"online" checking is spell checking as you type, the red wiggle line shows misspelled words.
Unless you have deactivated it, it should be active by default.

**Comment by OyHMaths** [comment]
I see. I didn't deactivate the online checking. Thanks a lot for your patient explanation.😀

**Comment by benibela** [comment]
You can use Tools/Find Word Repetition/wordRepetition/spellingMistake to find the next wiggle line

**Comment by OyHMaths** [comment]
Dear Benibela,
That is useful. It solves my question. Thanks a lot for your help. 😀
