### ISSUE TITLE
eqnarray environment and autocomplete

### ISSUE THREAD

**Issue by vahidajalluian** [texstudio-org/texstudio#485]
- TeXstudio: 2.12.14
- Qt: 5
- OS: ubuntu 16.04
- TeX distribution: texlive

### Expected behavior
In the eqnarray environment, using autocomplete should not add $ sign

### Actual behavior
In the eqnarray environment, using autocomplete, it adds $ sign

### How to reproduce
Make an eqnarray environment and then use autocomplete motor
It seems that it is okay in other mathematical environments

**Comment by dbitouze** [comment]
Anyway, `eqnarray` should be avoided. See § 3.3 "Mathematical typesetting" of [l2tabu](http://mirrors.ctan.org/info/l2tabu/english/l2tabuen.pdf).

**Comment by sunderme** [comment]
no feedback
