### ISSUE TITLE
FR: Macro Virus Protection

### ISSUE THREAD

**Issue by jonasstein** [texstudio-org/texstudio#486]
The `% !TeX TXS-SCRIPT =` functionallity opens a new path to create malicious documents.
I do not expect many .tex viruses within the next years, but
it would be great to have a good countermeasure before the first event.

Would it be sufficient to show the code and ask before execution?
Any other good ideas? There  could be three categories:

Do you want to execute the macro?
* never
* not this time, ask next time again
* only this time
* now and always in future

Is is safe enough to store the SHA-512 sum of the accepted script in the local config like

```
cat ~/.config/....
[scripts with run permission]
DEADBEEF 2018-01-01T0101 always
DEADB33F 2018-01-02T0101 never
DE4DB33F 2018-01-03T0101 ask

```

**Comment by sunderme** [comment]
wrong issue number in commit

**Comment by sunderme** [comment]
I think that is implemented
