### ISSUE TITLE
Bracket-matching problem

### ISSUE THREAD

**Issue by lirm-math** [texstudio-org/texstudio#489]
### Environment
- TeXstudio: 2.12.14
- Qt: 5.8.0
- OS: Win10, 1803 (17134.523)
- TeX distribution: texlive

### Expected behavior
Let `|` denote the caret. 
Type `(|)`, and then `(\cite{|)`. Then `)` is not matching `{`, and it is colored red. That's fine. 

As you type `\cite{`, a menu pops up. When you select an  entry from the popup menu, 
`(\cite{|)` should be like `(\cite{anything})` and nothing is colored red. 

### Actual behavior

`)` is still colored red (background color red). 

### How to reproduce

As in the "Expected behavior".

**Comment by sunderme** [comment]
not reproducible, please check with latest development version ,see webpage

**Comment by sunderme** [comment]
okay, I have seen the point

**Comment by octaeder** [comment]
Note: 
A workaround for me was inserting a line break before the closing parentheses:
```
(\cite{anything}
)
```
The mismatch disappears, and even more it doesn't come back when undoing or deleting the line break. The internal error has vanished. This is similar to cases #3319 (still unresolved) and #3226 (resolved).
