### ISSUE TITLE
Auto-aligning tables inserts linebreak in \\*

### ISSUE THREAD

**Issue by bambamal** [texstudio-org/texstudio#49]
`\\*` is used to prevent page breaks after a row in a table environment. Auto aligning puts a linebreak between `\\` and `*` so the asterisk is interreted as text. for example:

```
\begin{longtable}{ll}
	A & B \\*
	C & D \\
\end{longtable}
```

is auto-aligned to:

```
\begin{longtable}{ll}
	A    & B \\
	*
	C & D
\end{longtable}
```

**Comment by sunderme** [comment]
fixed in repository
