### ISSUE TITLE
TeXstudio is marking syntax error for certain commands from xy-pic

### ISSUE THREAD

**Issue by RamonAbudAlcala** [texstudio-org/texstudio#491]
TeXstudio is highlighting the command \xtwocell \dtwocell \utwocell \rtwocell \ltwocell \rutwocell ... etc, inside an \xymatrix{...} as syntax error "unrecognised command". Also inside \xymatrix sometimes it highlights the & sign with syntax error "tabular command outside tabular env". Perhaps there are other commands of the xy-pic package that are not recognised by TeXstudio but these ones are the ones I use regularly.

### Environment \xymatrix
- TeXstudio: VERSION  2.12.14
- Qt: Version 5.8.0 
- OS: Windows 10
- TeX distribution: miktex 

### Expected behavior
These commands should not be highlighted as syntax errors. 

### Actual behavior
Commands are highlighted even if they have the proper syntax. It seems that TeXstudio does not recognise \xymatrix as a tabular environment.

### How to reproduce
\[
\xymatrix{
\xtwocell[rd]{}<>{\alpha}&&\\
&&
}
\]

**Comment by sunderme** [comment]
I refer you to our wiki: https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions#why-does-texstudio-mark-a-command-as-unrecognized

We are happy to include a refined cwl for xy-pic
