### ISSUE TITLE
Can TeXStudio compile raw TeX?

### ISSUE THREAD

**Issue by CraftSpider** [texstudio-org/texstudio#495]
### Environment
- TeXstudio: 2.12.14
- Qt: 5.8.0
- OS: Windows 10
- TeX distribution: MiKTeX

### Expected Behavior
Is it possible for TeXStudio to be used on a raw TeX program (EG TeX.exe) instead of LaTeX? I see that TeXStudio supports multiple other TeX distributions, but it seems weird for it to not support TeX on its own

### Actual Behavior
No obvious way for TeXStudio to handle raw TeX documents

**Comment by CraftSpider** [comment]
I was hoping there was a way to have both active at once, like how under Tools -> Commands you have a list of valid 'types' of TeX. Also it's annoying to constantly switch it back and forth for working on different documents. But I'll do that for now.

**Comment by timhoffm** [comment]
If you want to use both, there is no need to overwrite existing commands. You can add your own commands at Build -> User commands.
