### ISSUE TITLE
Editor window doesn't use bold font for keywords

### ISSUE THREAD

**Issue by tweh** [texstudio-org/texstudio#496]
### Environment
- TeXstudio: 2.12.14 (git 2.12.14)
- Qt: 5.11.2, kompiliert mit Qt 5.11.2 R
- OS: macOS 10.14.2
- TeX distribution: TeX Live 2018 (via MacTeX)

### Expected behavior
Show keywords like `\chapter` or `\begin{…` in bold, as defined in the settings. It should look like this (mocked up with TextEdit):
![should look like this](https://user-images.githubusercontent.com/3011538/52164547-64b4f500-26f3-11e9-9235-34d9813f6a7e.png)

### Actual behavior
TeXstudio ignored the bold setting and displays everything in Regular, although the used font _Consolas_ has a bold version, which is active an available in the system (i.e. could be used to make the above screenshot e.g.). This is what TeXstudio displays
![looks like this](https://user-images.githubusercontent.com/3011538/52164565-ab0a5400-26f3-11e9-96fa-959987775ec8.png)

I’m not sure but I guess this was introduced with the latest TeXstudio version.

**Comment by sunderme** [comment]
works as expected here.
you need to change the syntax highlighting for "extra-keyword" for "begin" and "chapter"...

**Comment by tweh** [comment]
Hm … as far as I can tell my settings are correct, aren’t they?

![Settings](https://user-images.githubusercontent.com/3011538/52175484-f0d32500-27a4-11e9-99d5-483ccd50d449.png)

I also deleted the system font caches, de- and reactivated the font (*Consolas*), and de- an reactivated the bold settings in TeXstudio without success.

**Comment by sunderme** [comment]
I have rechecked on osx. works as expected also with Consolas.

**Comment by sunderme** [comment]
hmmm, why do you set only normal font to consolas and the rest as default ? The default is set in options/editor.

**Comment by tweh** [comment]
Test strange. I only set the default font (options/editor) to Consolas. I don’t know why there was a redundant setting in options/syntax highlighting. However nothing changes if I (a) remove the Consolas setting in the highlighting for _normal_ nor (b) add Consolas to the bold syntax settings, nor (c) us another font like Fira Mono or Arial. The editor still only displays the regular weight. Is there maybe an other option I’m missing?
Pleas note, that I didn’t change any of these settings at all. This bug (?) appeared after an update of TeXstudio (or my upgrade to Mojave).

**Comment by sunderme** [comment]
you could set everything to default by removing/renaming ~/.config/texstudio/texstudio.ini

**Comment by tweh** [comment]
Nope … that doesn’t help. The settings are reset to the default but bold fonts still don’t work.

**Comment by tweh** [comment]
Sorry for the late reply. While resetting TeXstudio didn’t help the latest update
> TeXstudio 2.12.16 (git 2.12.16)
> Nutze Qt-Version 5.12.3, kompiliert mit Qt 5.12.3 R
Fixed the issue and the bold fonts are back :-)
