### ISSUE TITLE
Annoying error popup when compiling

### ISSUE THREAD

**Issue by antoniodourado** [texstudio-org/texstudio#497]
### Environment
- TeXstudio: 2.12.14
- Qt: 5.8.0
- OS: Windows 10
- TeX distribution: miktex

###  Problem
I installed TeXstudio to check it but i'd like to disable error popup since it's totally counterproductive and it would be better if errors were displayed only in messages console. Is there a way to disable the popup itself and let the errors only to be displayed in messages console? Also, when an error occurs, error popup is displayed three times. So I have to click OK three times.
Here's an example of error popup after an intentional error: https://i.stack.imgur.com/YNxta.jpg

Thank you so much in advance.

**Comment by sunderme** [comment]
it seems that your command set-up is faulty. Please check there to fix the underlying problem. In normal operation, no pop-up will appear. This is not a compilation problem.

**Comment by antoniodourado** [comment]
I just figured out what was wrong and will post solution as soon as I get
home.

Em sáb, 2 de fev de 2019 17:54, sunderme <notifications@github.com escreveu:

**Comment by sunderme** [comment]
assuming it has been resolved
