### ISSUE TITLE
Incorrect parsing of Latex error messages

### ISSUE THREAD

**Issue by nfriess** [texstudio-org/texstudio#50]
The Latex compiler sometimes generates output with a ! at the beginning of a line, but it does so because it is printing out text from the input file, not due to an error message.  Here is an example of output from the Latex compiler:

> [117]
> Underfull \hbox (badness 10000) in paragraph at lines 1416--1418
> [][][]\T1/ptm/b/n/10.95 Some text   \T1/ptm/m/n/10.95 De-fine $\OML/ztmcm
> /m/it/10.95 T \OT1/ztmcm/m/n/10.95 : \U/msb/m/n/10.95 R[] \OMS/ztmcm/m/n/10.95 
> ! \U/msb/m/n/10.95 R$ \T1/ptm/m/n/10.95 by
>  []

In comparison, a real error has the line number after it:

> ! Undefined control sequence.
> l.4 \foo

It may be helpful to have the log parser in Texstudio ignore lines that start with ! and are not followed directly by a line that starts with "l." + a number.

**Comment by timhoffm** [comment]
> It may be helpful to have the log parser in Texstudio ignore lines that start with ! and are not followed directly by a line that starts with "l." + a number.

This is not feasible. There are various cases of error messages, in which the next line does not start with "l.xx".

Generally, parsing the log is a mess, since literally anything can happen (you could even have some quoted code from the tex, which cites an actual error message and there is no way to tell). I think we have to live with the small chance of positive false errors in this case.

**Comment by nfriess** [comment]
Yes, I understand that it is hard to do accurate log parsing with Latex.  I didn't realize that there are cases where the "l.xx" doesn't appear.

Another idea is to check the exit code of the latex process as another hint.  With Texlive the exit code of the latex process will be 0 when there are no errors.  In this case any lines that look like errors can probably be ignored, or maybe downgraded to a warning so they still appear in the log view.

**Comment by sunderme** [comment]
i assume we don‘t do anything about it
