### ISSUE TITLE
Autocomplete for Path makes wrong slash

### ISSUE THREAD

**Issue by the-rene** [texstudio-org/texstudio#500]
### Environment
- TeXstudio: TeXstudio 2.12.14 (git 2.12.14)
- Qt: Qt-Version 5.8.0, kompiliert mit Qt 5.8.0 R
- OS: Windows 10 10.0.17763
- TeX distribution: miktex
### Expected behavior
When using the command `\input{path/to/file}` to include the file with the relative path `path/to/file`
 in a tex File, when I manual type `\input{pa` and hit CTRL+SPACE  TexStudio should propose the mathching dir, type it in completely and add the slash symbol `/` after it.

### Actual behavior
When using the command `\input{path/to/file}` to include the file with the relative path `path/to/file`
 in a tex File, when I manual type `\input{pa` and hit CTRL+SPACE  TexStudio proposes the mathching dir,  types it in completely and adds the backslash symbol `\` after it.

That results in a LaTeX Error, because it leads to a wrong parameter for the input command
### How to reproduce
* Create a new LaTex document main.tex with TexStudio and the article template
* Create the folder structure 'path/to' in the same directory as the latex
* Create the file 'file.tex' in the folder 'path/to'
* Edit the main.tex in Latex and add somewhere between `\begin{document}` and `\end{document}` the code `\input{pa`
* Use CTRL+Space to autocomplete to the newly created file.tex

**Comment by sunderme** [comment]
fixed
