### ISSUE TITLE
line wrap ignores settings

### ISSUE THREAD

**Issue by lafidi** [texstudio-org/texstudio#503]
### Environment
- TeXstudio: 2.12.14
- Qt: 5.8.0
- OS: Win 10 Pro 1803
- TeX distribution: miktex

### Expected and actual behavior
Even I set line wrap in the advanced editor settings to "soft line wrap at window edge", it seems to wrap the line after the given number of characters in the field below that setting, when I change that value to any value, it works correctly.
This happens always at the start of the software. Even changing the width of the editor part does not change behavior.

**Comment by sunderme** [comment]
works as expected on linux and win.
have you tried default settings ?

**Comment by lafidi** [comment]
Ok, I worked on that; it was because TexStudio opened on my high DPI display and I always move it directly to a "normal DPI" one. When I leave it on the high DPI display, I don't notice the problem, because it wraps where the input field ends, but TexStudio seems to struggle with scaling changes. So, no problem at all.

*close*
