### ISSUE TITLE
line numbers are shifted "downwards"

### ISSUE THREAD

**Issue by lafidi** [texstudio-org/texstudio#504]
### Environment
- TeXstudio: 2.12.14
- Qt: 5.8.0
- OS: Win 10 Pro 1803
- TeX distribution: miktex

### Expected behavior
After turning on line numbers I expect line numbers to appear at the side the editor window and they are counted correctly.

### Actual behavior
Line numbers do appear, but they are shifted by one. They are counted correctly, as seen from the screenshow below, but the line wrap indicator is also shifted by one. It seems to be kinda weird how it is displayed.
![texstudio line numbers](https://user-images.githubusercontent.com/29579394/52552626-2dc09c80-2de1-11e9-98c9-3ad46222a53d.PNG)

### How to reproduce
Turn on line numbers.

**Comment by aubreyz** [comment]
I don't use line numbers but it looks to me as if it is being displayed (correctly) at the line end. 1 is at line 1

**Comment by lafidi** [comment]
I don't think so. If it was always at the line ends, the "1" should be at the first blank line. The wrap-signs say, that there was no line end mark, but it was just wrapped around because of the width.

Nevertheless it is very confusing that the lines seem to be shifted and if you don't remember it while tracking errors its hard to find them.

**Comment by sunderme** [comment]
works as expected on linux and win.
have you tried default settings ?

**Comment by lafidi** [comment]
Yep, I did. On my linux computer it works as expected, but on my Windows one, it doesn't. Deleted all local/temp data, reinstalled, opened new project etc.

**Comment by sunderme** [comment]
and this is uncorrelated to high/low dpi display as the other report ?

**Comment by lafidi** [comment]
It seems like. It occurs on both displays and independet from moving the window whereas the other issue appeard only after moving the window.

**Comment by sunderme** [comment]
probably obsolete
