### ISSUE TITLE
Macro for backslash in TeXstudio does not start autocomplete

### ISSUE THREAD

**Issue by bdespond** [texstudio-org/texstudio#506]
I defined a macro to map the § key to print the backslash \, as the latter is hard to reach on my keyboard.

Autocomplete works fine when I start the command with the "real" backslash (i.e. the keyboard key that has \ printed on it).

However, autocomplete does not work when I use the § key (which prints \ ). I do not understand why this is the case and how to fix it.

### Environment
- TeXstudio:  2.12.6 
- Qt:  Using Qt Version 5.9.5, compiled with Qt 5.9.3 R
- OS:  Ubuntu 18.04 
- TeX distribution:  TeX 3.14159265 (TeX Live 2018) 

### Expected behavior

Autocomplete to work when using a backslash defined through a macro

### Actual behavior

Autocomplete does not pop up. Autocomplete does only work when writing the backslash with the key that has \ printed on it

### How to reproduce

Define a macro as shown in the attached picture
Turn on autocomplete your package of choice
![backslash_autocomplete](https://user-images.githubusercontent.com/30444647/52632836-e90d3200-2ec2-11e9-959a-8b6affe6f0a8.png)

**Comment by sunderme** [comment]
update to txs 2.12.14

macros/edit macros/browse -> addedFeatures/startCommandCompletionWith...

(or see https://github.com/texstudio-org/texstudio/wiki/Scripts#insert-backslash-and-start-completion-with-)

**Comment by bdespond** [comment]
This works great. Thank you very much @sunderme
