### ISSUE TITLE
User Commands names does not appear in `Tools>User` menu

### ISSUE THREAD

**Issue by dariomangoni** [texstudio-org/texstudio#507]
### Environment
- TeXstudio: 2.12.14
- Qt: 5.8.0
- OS: Windows10
- TeX distribution: texlive

### Expected behavior
In `Options>Configure TeXstudio...>Build>User Commands` the user can add its own _User Commands_ and give them have a short name. We should expect to see such names displayed in the `Tools>User` menu.

### Actual behavior
In the `Tools>User` menu only an ordinal number (`1:`, `2:`, ...) is displayed instead of the user-defined name that we should expect.

### How to reproduce
Add a _User Command_ in `Options>Configure TeXstudio...>Build>User Commands` and check the `Tools>User` menu.

**Comment by sunderme** [comment]
works as expected.
please present screenshots of the menu as well as the corresponding config.

**Comment by dariomangoni** [comment]
Yes, sure

![2019-02-19 21_07_39-configure texstudio](https://user-images.githubusercontent.com/8025529/53044173-8e5b7380-348a-11e9-87b0-baa4e26b41c4.png)

![2019-02-19 21_07_59-texstudio](https://user-images.githubusercontent.com/8025529/53044179-94e9eb00-348a-11e9-81c5-b7b24401a605.png)

**Comment by sunderme** [comment]
please try: `user0:Canzoniere`
or `user1:HtLatex`

**Comment by dariomangoni** [comment]
Oh, you are right. Sorry, I didn't check the manual. I thought it was obvious that the string should have been rendered as it was, without any `userN:` stuff.

My fault,
sorry again

**Comment by sunderme** [comment]
no problem
