### ISSUE TITLE
texstudio internal PDF viewer shows streak white lines on image

### ISSUE THREAD

**Issue by nasser1** [texstudio-org/texstudio#51]
cross posted also [here](https://tex.stackexchange.com/questions/418308/why-does-texstudio-internal-pdf-viewer-shows-streak-white-lines-on-image)

When I compile this MWE latex file in texstudio, on windows, using MikTex, then view the result using texstudio internal PDF viewer, it shows white streak lines going over the image. These lines are not in the original image.

Also these lines do not show up when I view the compiled PDF file using external PDF reader such as adobe.

Why is that? The image is also a PDF file. Is it possible to resolve it? It is not a big issue really, since this seems to be just an artifact of texstudio pdf viewer itself, but thought to ask if there is an option to fix this.

Here is MWE

```
\documentclass{article}
\usepackage{graphicx}
\begin{document}
This is my image, as PDF file, imported using includegraphics

\includegraphics[width=\textwidth]{image}    
\end{document}
```

I put the file image.pdf is on my web page [here](https://www.12000.org/tmp/030418/image.pdf)

pdfinfo image.pdf 

Creator:        Wolfram Mathematica 11.2.0.0 for Microsoft Windows (64-bit) (September 10, 2017) Student Edition - Personal Use Only
Producer:       
CreationDate:   Sat Mar  3 16:13:39 2018
ModDate:        Sat Mar  3 16:13:39 2018
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      470 x 367 pts
Page rot:       0
File size:      99049 bytes
Optimized:      no
PDF version:    1.5
I am using

TeXstudio 2.12.6 (hg 6632:7777b2b8a906)
Using Qt Version 5.9.1, compiled with Qt 5.9.1 R
Windows 7.

**Comment by nasser1** [comment]
[image.pdf](https://github.com/texstudio-org/texstudio/files/1777970/image.pdf)

**Comment by nasser1** [comment]
attached image.pdf also

**Comment by samcarter8** [comment]
No idea how to fix this, but the reason the image works in adobe reader is that it has the option "enhance thin lines" enabled as default.

**Comment by timhoffm** [comment]
Your image does contain thin lines. There's no universal way how to handle these if they are thinner than a pixel on the screen. If one doesn't do anything about this, the lines can arbitrarily appear or vanish depending on their excact sub-pixel location. One common way is to render the lines thicker. This is what the Adobe Reader option claims to do (no Idea why it doesn't show them at all - maybe they have a hidden policy of not drawing the lines if the get really tiny).

The rendering in the case of TXS is done by the pdf library poppler. We have not taken any special measures concerning thin lines. You may try the alternative backend 'Arthur' at `Options -> 

Notes to devel

**Comment by samcarter8** [comment]
@timhoffm Adobe Reader does not show the white lines because there are no white lines in the image - what appears as white lines is where the edges of two bins meet. 

As far as I can tell Adobe Reader will do some voodoo with the edge of the bins so no gap between them will be visible.

**Comment by timhoffm** [comment]
Sounds plausible. If they really to some edge-merging, that's definitively beyond our possibilities, and afaik not implemented in poppler.

**Comment by samcarter8** [comment]
@nasser1 If you plan to distribute your document, you should consider fixing the image instead of trying to fix the pdf viewer as many other viewers, such as mac preview, will also show these lines.

**Comment by sunderme** [comment]
i see the lines on a ipad pdf viewer, so it is rather a poppler/fundamental problem.
Nothing we can do about it
