### ISSUE TITLE
Texstudio crashes if you forget closing } of beamer frame

### ISSUE THREAD

**Issue by Wicher2** [texstudio-org/texstudio#510]
### Environment
- TeXstudio: 2.12.14	

### Expected behavior

No crash

### Actual behavior

Crash

### How to reproduce

\documentclass{beamer}
\begin{document}
\frame{
Test
%there is a missing closing bracket here, and TeXStudio crashes when trying to compile and view
\end{document}

**Comment by aubreyz** [comment]
No Crash Here (windows 10, Texlive updated). Define "Crash"

**Comment by Wicher2** [comment]
By crash I mean texstudio stops and I need to restart it. Normally it happens when I press F5 to compile&view, but with the test code given above it only crashes when I press F5 and then F7 (view). I'm using windows 10 and miktex (not sure how to update texlive).

**Comment by sunderme** [comment]
no crash on linux.
what does the produced pdf look like ?

**Comment by Wicher2** [comment]
I see now that the pdf gets deleted, maybe that's the issue: the viewer tries to view a nonexistent pdf and then TeXStudio crashes. 

Just compiling doesn't cause a crash but gives an error message (as it should) and also removes the pdf. The error message is "File ended while scanning use of \beamer@howtotreatframe."

**Comment by Wicher2** [comment]
Yes, that seems to be it: if I remove the pdf by hand while it is open in the viewer, texstudio crashes as well.

So two solutions possible I guess: (i) prevent texstudio from crashing when trying to view nonexistent pdf or (ii) prevent texstudio from removing a pdf if there is an error message.

**Comment by sunderme** [comment]
no unexpected behaviour on windows 10/miktex as well.
Please provide a screencast to illustrate the issue.

**Comment by sunderme** [comment]
no feedback
