### ISSUE TITLE
Doesn't find input Files, when  \input@path is overwritten

### ISSUE THREAD

**Issue by BoergeSt** [texstudio-org/texstudio#512]
I like to have my Sections/Chapters in separate files in their own folder. In order to avoid having to write the relative path in front of each and every include file, I use the following commands to add the folder to the input path:

```
\makeatletter 
\providecommand*{\input@path}{}
\g@addto@macro\input@path{{<folder>/}}
\makeatother
```
LaTeX compiles without problems, but the Structure explorer can't find the files (because they are in a subfolder).

### Environment
- TeXstudio: TeXstudio 2.12.10
- Qt: Qt 5.8.0 R
- OS: Windows 10
- TeX distribution: MiKTeX-pdfTeX 2.9.6668 (1.40.19) (MiKTeX 2.9.6800 64-bit)

**Comment by sunderme** [comment]
pretty unlikely that txs will ever handle patched latex commands.
you could use search paths but I assume that it will not really do what you want.

**Comment by timhoffm** [comment]
TeXstudio can only use some simple rules to determine the semantics of a command. If you redefine some inner workings of the command this is not something TXS will be able to pick up. Note, that this a conscious design decision. LaTeX is a complex language in which you can redefine virtually any command. To really find out what a command does, one would need a full latex parser and parse the complete document. This is not suitable for an editor in which we need immediate information.
