### ISSUE TITLE
How to invoke the duck?

### ISSUE THREAD

**Issue by CsatiZoltan** [texstudio-org/texstudio#514]
### Environment
- TeXstudio: 2.12.14
- Qt: 5.8.0
- OS: Windows 7
- TeX distribution: miktex

### Experience

I pressed `Esc`, and a duck appeared. I read on forums that by pressing `Esc` many times, you can call the duck. However, I could not reproduce. What is the key to get this Easter egg again?

**Comment by CsatiZoltan** [comment]
I've just realized: hold `Esc` for a few seconds.

**Comment by CsatiZoltan** [comment]
Now it doesn't work. Is it random?

**Comment by benibela** [comment]
You need to press it at the time of the duck

**Comment by Cornul11** [comment]
> You need to press it at the time of the duck

In that case, the time of the duck is every 5 seconds. `seconds % 5 == 0` should be true when you press ESC if you wish to see the duck.

**Comment by CsatiZoltan** [comment]
Thanks!
