### ISSUE TITLE
DVI ID = 37 dvipdfmx:fatal: Something is wrong. Are you sure this is a DVI file? Output file removed.

### ISSUE THREAD

**Issue by sekigh** [texstudio-org/texstudio#518]
I use a one-click  icon to do everything  from platex-to-pdf for a multiple paths of compilation, dvipdfmx, upbib.  I have \label, \ref and \bibliographystyle in .tex. I use SumatraPDF for displaying pdf. 

I encounter the error message in the second dvipdfmx saying,

 DVI ID = 37 dvipdfmx:fatal: Something is wrong. Are you sure this is a DVI file? Output file removed. 

Still the process continues and somehow looks to produce .pdf.  
I would like to know the cause of this error and fix it. 

### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior

It is a bit strange that the second running of dvipdmfx has no output just below its starting output of its name, like: 
開始されたプロセス: dvipdfmx.exe "xxxxxx".dvi
開始されたプロセス: platex.exe -synctex=-1
At this point of processing, it might be like that a C compier spawns its child processes in parallel. I am not sure but I doubt that running tools in a order would be executed incorrectly. 

### Actual behavior ( Sorry for some Japanese messages included) 

The start of log message: 

開始されたプロセス: upbibtex.exe "xxxxxx"

This is upBibTeX, Version 0.99d-j0.33-u1.23 (utf8.uptex) (TeX Live 2018/W32TeX)
The top-level auxiliary file: xxxxxx.aux
The style file: yyyyyy.bst
Database file #1: zzzzzz/wwwwww.bib
Database file #2: zzzzzz/uuuuuu.bib

(guessed encoding: UTF-8 = utf8)(guessed encoding: UTF-8 = utf8)(guessed encoding: UTF-8 = utf8)

プロセスは正常に終了しました

開始されたプロセス: platex.exe -synctex=-1 -interaction=nonstopmode "xxxxxx".tex

(guessed encoding: UTF-8 = utf8)(guessed encoding: UTF-8 = utf8)(guessed encoding: UTF-8 = utf8)(guessed encoding: UTF-8 = utf8)(guessed encoding: UTF-8 = utf8)

プロセスは正常に終了しました

開始されたプロセス: platex.exe -synctex=-1 -interaction=nonstopmode "xxxxxx".tex

(guessed encoding: UTF-8 = utf8)(guessed encoding: UTF-8 = utf8)(guessed encoding: UTF-8 = utf8)(guessed encoding: UTF-8 = utf8)(guessed encoding: UTF-8 = utf8)

プロセスは正常に終了しました

開始されたプロセス: dvipdfmx.exe "xxxxxx".dvi

xxxxxx.dvi -> xxxxxx.pdf [1][2][3][4][5] 1570875 bytes written

プロセスは正常に終了しました

開始されたプロセス: upbibtex.exe "xxxxxx"

This is upBibTeX, Version 0.99d-j0.33-u1.23 (utf8.uptex) (TeX Live 2018/W32TeX)
The top-level auxiliary file: xxxxxx.aux
The style file: yyyyyy.bst
Database file #1: zzzzzz/wwwwww.bib
Database file #2: zzzzzz/uuuuuu.bib

(guessed encoding: UTF-8 = utf8)(guessed encoding: UTF-8 = utf8)(guessed encoding: UTF-8 = utf8)

プロセスは正常に終了しました

開始されたプロセス: platex.exe -synctex=-1 -interaction=nonstopmode "xxxxxx".tex

(guessed encoding: UTF-8 = utf8)(guessed encoding: UTF-8 = utf8)(guessed encoding: UTF-8 = utf8)(guessed encoding: UTF-8 = utf8)(guessed encoding: UTF-8 = utf8)

プロセスは正常に終了しました

開始されたプロセス: dvipdfmx.exe "xxxxxx".dvi

開始されたプロセス: platex.exe -synctex=-1 -interaction=nonstopmode "xxxxxx".tex

xxxxxx.dvi -> xxxxxx.pdf DVI ID = 37 dvipdfmx:fatal: Something is wrong. Are you sure this is a DVI file? Output file removed.

プロセスはエラー終了しました

(guessed encoding: UTF-8 = utf8)(guessed encoding: UTF-8 = utf8)(guessed encoding: UTF-8 = utf8)(guessed encoding: UTF-8 = utf8)(guessed encoding: UTF-8 = utf8)

プロセスは正常に終了しました

開始されたプロセス: dvipdfmx.exe "xxxxxx".dvi

xxxxxx.dvi -> xxxxxx.pdf [1][2][3][4][5] 1570877 bytes written

プロセスは正常に終了しました

開始されたプロセス: "C:\Program Files\SumatraPDF\SumatraPDF.exe" -forward-search "xxxxxx".tex 1322 "C:\Users\hhhhhh\xxxxxx.pdf"

The end of log message

### How to reproduce

It is rather hard to provide .tex file as is because this is a part of academia paper. The copywright is already transferred to the academia sciety.

**Comment by sekigh** [comment]
I add following information here.

### Environment
* TeXstudio:  2.12.14
* Qt: (I do not know ! )
* OS: Windows10
* TeX distribution:  texlive 2018

**Comment by timhoffm** [comment]
This looks more like a issue between your document and `dvipdfmx`. I don't think it has anything to do with TeXstudio. This tracker is only for issues with TeXstudio itself. General pupose TeX questions are better placed at https://tex.stackexchange.com.

**Comment by sekigh** [comment]
Thank you for your advice. I will submit the issue to the site you suggested.
