### ISSUE TITLE
Feature request: Add full math commands and symbols with preview

### ISSUE THREAD

**Issue by mirsamantajbakhsh** [texstudio-org/texstudio#519]
### Environment
- TeXstudio: 2.12.14
- Qt: 5.8.0
- OS: Windows10
- TeX distribution: miktex

### Expected behavior
TexStudio is a very easy to use editor for Tex. Two charming wizards (Insert Graphics and Math Assistant). Beside the Math Assistant, I like to have a fully available math commands as a window, with preview.

### Actual behavior
There are some math symbols in Math Menu but only some of them have preview.

### How to reproduce
I suggest adding a symbol and math command section in Wizards Menu.

**Comment by foreachthing** [comment]
Do you mean something like this: https://www.codecogs.com/latex/eqneditor.php ?

**Comment by mirsamantajbakhsh** [comment]
> Do you mean something like this: https://www.codecogs.com/latex/eqneditor.php ?

Very good example. Exactly.

**Comment by sunderme** [comment]
you know about the symbol panel on the left and the preview feature (select your math env,including $..$ and press alt+p or right mouse click->preview selection)

**Comment by mirsamantajbakhsh** [comment]
> you know about the symbol panel on the left and the preview feature (select your math env,including $..$ and press alt+p or right mouse click->preview selection)

Yes I know both features. But the preview is not real time such as Math Assistant. You should compile to see the result (or preview) which is time consuming in large documents.

**Comment by sunderme** [comment]
Have you tried the preview feature ?
It updates the preview after every change with a short lag. a math assistant will not work any diferently.

**Comment by mirsamantajbakhsh** [comment]
> Have you tried the preview feature ?
> It updates the preview after every change with a short lag. a math assistant will not work any diferently.

The preview feature do not work for me. I'm using Persian language and xelatex is the compiler (for xepersian). Is it the problem?

**Comment by sunderme** [comment]
possibly. You could set "xelatex" as pdflatex command (options/commands) and see whether that works out. (the commands called for preview are shown in the message pane)

**Comment by mirsamantajbakhsh** [comment]
> possibly. You could set "xelatex" as pdflatex command (options/commands) and see whether that works out. (the commands called for preview are shown in the message pane)

Worked perfectly. Thanks. It should satisfy my requirements with Symbols panel.
