### ISSUE TITLE
Biber / Bibtex switching

### ISSUE THREAD

**Issue by kschmid** [texstudio-org/texstudio#52]
I searched around, but I could not find s.th. appropriate, thus, I post it here as a potential enhancement. 

I am working with TexStudio and both Bibtex and biber with no problem. However, I am often using different projects and the question which tool to use is answered very different based on decisions beyond my control. So usually when I switch project, I first have to find out what is supposed to be used here then, change my settings. - When switching back, I have to change the preferences again. In my view preferences should be not s.th. I have to switch with a project. (and I am sometimes switching several times each day)
So, I am wondering whether there might be a way for TexStudio to autodetect per project the correct setting (e.g., annotations in the tex-file or simply looking at the files produced in a run). This could then be the basis for selecting the tool.. 
Or perhaps there is such a way, but I did not find them. I always found I have to switch the preferences.

**Comment by dbitouze** [comment]
As a semi-automatic solution, e.g. for a project requiring `biber`, you can put the following magic comment (I guess preferably at the very beginning of your (master) file):

`% !TeX TXS-program:bibliography = txs:///biber`

**Comment by kschmid** [comment]
Thanks, I try this!

**Comment by samcarter8** [comment]
Another workaround: compile with `latexmk` - this will automatically detect if bibtex or biber is needed.

**Comment by timhoffm** [comment]
`% !BIB program = biber`  is equivalent to  `% !TeX TXS-program:bibliography = txs:///biber`

and a bit more portable. (`% !TeX TXS-program` gives you more freedom of configuring the build system, but will only work within TeXstudio).

For more information see the [user manual](http://texstudio.sourceforge.net/manual/current/usermanual_en.html#SECTION_TEXCOM).
