### ISSUE TITLE
Macros save incorrect

### ISSUE THREAD

**Issue by OgnevI** [texstudio-org/texstudio#521]
### Environment
- TeXstudio: * 2.12.14
- Qt: * 5.8.0
- OS:  * Windows 7
- TeX distribution: * MiKTeX 2.9

### Expected behavior
Save the original text of added macros.

### Actual behavior
For example, following text of Macros:
%%%%
\begin{gather}
%|!formula 1!%|
\\
!formula 2!
\end{gather}
%%%%

after close TexStudio is transformed to:
%%%
\begin{gather}
	!formula 1!
	\",
	
	,
	
	,

### How to reproduce
Add to program example  of macros above.

**Comment by benibela** [comment]
The last character in a line cannot be a `\`

You could put a space or percent behind it


The minimal json parser does not work. I think we should use a real  json parser like https://github.com/eteran/qjson4

**Comment by timhoffm** [comment]
Qt5 has Jason support built in. The minimal parser was a way to obtain compatibility with Qt4.

By now, we could consider dropping support for Qtr.

**Comment by OgnevI** [comment]
> You could put a space or percent behind it

Thanks! It worked.

**Comment by benibela** [comment]
I use Qt4

**Comment by timhoffm** [comment]
Just saying. Qt4 has reached its official end of life. It 4.8 was released in 2011 and the last and final bugfix release 4.8.7 was in 2015.
Not being developed further it doesn‘t support well some more modern features like JSON support, HiDPI support, touch control. We can work around these, but I‘m wondering if it‘s worth the extra effort.

Is there a particular reason that you do not want to switch to Qt5?

**Comment by sunderme** [comment]
I am also working professionally with linux distributions which are rather old and don't offer Qt5.

**Comment by sunderme** [comment]
the macro editor probably works for most reasonable cases, I don't think that it needs a large overhaul.
For Qt5 the built-in json parser might be used.

**Comment by sunderme** [comment]
fixed for qt5 only
