### ISSUE TITLE
Crash on edit operations

### ISSUE THREAD

**Issue by stevenbjan** [texstudio-org/texstudio#522]
### Environment
- TeXstudio: TeXstudio 2.12.14
- Qt: Qt Version 5.8.0, compiled with Qt 5.8.0 R
- OS: Win 10 64 bit Version 10.0.17763 Build 17763. 16GB RAM
- TeX distribution: MikTex

Regular crashes on basic edit operations such as copy/paste. Also happens sometimes on file open. It most often occurs when I have a multi-file (book) project open. Have disabled some proofing (language tool), which used to ameliorate this behaviour.

**Comment by sunderme** [comment]
without any reproducible test case there is. othing we can do.
