### ISSUE TITLE
Totally Dark Gui - Dark Color Scheme

### ISSUE THREAD

**Issue by ScyllaHide** [texstudio-org/texstudio#524]
### Environment
- TeXstudio: 2.12.6, (not uptodate i know, current version uses double Memory and opens slow as hell for me)
- Qt: 5.6.2
- OS: Windows 10 Pro x64
- TeX distribution: miktex

### Expected behavior
i want a total dark Gui, no white, white is horrible when you type for long hours on something, it makes your eyes fatigue faster.
Actual something like Atom has, the dark Color Scheme would be perfect.

### Actual behavior
there is still the Modern Color Scheme, but it is still to bright to work with for long hours.

thank you!

**Comment by timhoffm** [comment]
See also #45, in particular 
https://github.com/texstudio-org/texstudio/issues/45#issuecomment-368334650.

**Comment by ScyllaHide** [comment]
thank for this link, but it is not working, i followed the steps, i still see the modern default color scheme.
Is there maybe a problem with that being a new version?

**Comment by timhoffm** [comment]
It should work in principle. There have been no changes to the stylesheet support since 2.12.6.

Please make sure that
- the file is in the settings directory
- the file is called `stylesheet.qss`

**Comment by ScyllaHide** [comment]
your tip solved it! it is now in black and i can live with it.

But i would still be nice to have a default theme complete in black!

appreciate your help and also all the work put into texstudio!

**Comment by timhoffm** [comment]
Closing as the stylesheet fixes the case for the user. General discussion on dark themes may be continued in #45.
