### ISSUE TITLE
Feature Request: Referencing with a number

### ISSUE THREAD

**Issue by mrquell** [texstudio-org/texstudio#525]
So I'm writing a document with lots of different equations, figures, and tables, and I find it difficult to keep track of the labels I've assigned to the references, as I'm sure most people do. I love how TexStudio gives suggestions as to which references you're looking for in the drop-down menu when you type \ref{}, but it would also be useful if there were the figure/equation/table number that it is printed out at next to the suggested label. That way, you could look at the PDF and say, I want to cite equation 3 but forgot the label you gave it. So you could type \ref{} and scroll through for the one that has the 3 and click that label. This feature would make label management much easier.

**Comment by sunderme** [comment]
that would require txs to keep track of different label types and order. Furthermore numbering scheme may become more complicated (subfigures).
So long story short, there will be no reference numbering, just use expressive label names (usually fig:ImportantPlot etc.)
