### ISSUE TITLE
Inconsistent behavior of placeholder removal upon pressing Enter

### ISSUE THREAD

**Issue by kbauer** [texstudio-org/texstudio#526]
### Environment
- TeXstudio: 2.12.14, but also reproduced for 2.12.12.
- Qt: 5.8.0, compiled with Qt 5.8.0 R
- OS: Windows 10, 1803
- TeX distribution: Miktex

### Summary

For any command, where completion of arguments is supported, typing an argument, TeXStudio did not suggest, changes the behavior of placeholder-removal upon pressing <kbd>Enter/Return</kbd> at the end of the argument, resulting in spurious line breaks.

### How to reproduce

With completion enabled, try typing the lines

```
\label{something}
\ref{something}
\ref{somethingelse}
```

Do so by using completion, i.e.

```
\lab<ENTER>something<ENTER><RIGHT><ENTER>
\re<ENTER>something<ENTER><RIGHT><ENTER>
\re<ENTER>somethingelse<ENTER><RIGHT><ENTER>
```

where `<ENTER>` represents a stroke of the Enter/Return key, meant to select the completion `\ref{label}` producing a completion with placeholder, and then to remove the completion at the end of the argument. `<RIGHT><ENTER>` is meant to leave the completed argument and start the next line.

### Observed behavior

When completions are offered, but a different text is typed, pressing enter not only disables the placeholder, but also inserts a linebreak, inconsistent with how pressing Enter at the end of placeholders works in all other cases. In the example given, it results in

```
\label{something}
\ref{something}
\ref{somethingelse
}
```

### Expected behavior

After typing `something` in the second line, and after typing `somethingelse` in the third line, pressing enter should disable the placeholder highlight, and do nothing else. This is how it behaves for commands, where no completions are offered for the argument.

### Screen Capture

![texstudio-complete](https://user-images.githubusercontent.com/7498468/53725069-84167d80-3e6b-11e9-801b-c8f8687873f3.gif)

**Comment by sunderme** [comment]
enter selects a element in the completer, if nothing is there, it can't be selected and a CR is added.
I am not sure that this behaviour can be considered a bug ...

**Comment by kbauer** [comment]
When the completer doesn't apply in the first place, Enter just removes the placeholder though. So, from a user-perspective, it looks inconsistent, as net-behavior ("adds CR") is different from all other cases.
