### ISSUE TITLE
Feature request: allow files included with \input{} to have arbitrary extension.

### ISSUE THREAD

**Issue by ElieGouzien** [texstudio-org/texstudio#527]
Files includes with `\input{file.something}` not having a `.tex` extension are not taken into account by TeXstudio for the completion system. It would be nice to be able to use whatever extension. This is particularly useful for headers.

Please note that I have activated the "autoload included files" option, and that my TeXstudio version is quite old : TeXstudio: 2.12.6 (6631:16db084dae24).

**Comment by dbitouze** [comment]
Why do you choose `.something` instead of `.tex`?

**Comment by ElieGouzien** [comment]
Apart from texstudio, I like to be able to simply execute `latexmk` without precising on which file to work, and obviously it will fail to compile a file containing only headers, like any command that tries to compile all `.tex` files found in a given folder.
More in general, I don't like to call `*.tex` files that are not true LaTeX but only part of it.

If you show me where texstudio decide whether to load or not the file, I could propose a pull request.

**Comment by sunderme** [comment]
pdflatex can't use files which don't end in ".tex" , so won't change.
