### ISSUE TITLE
[Feature-Request] Grammarly integration

### ISSUE THREAD

**Issue by MahatmaFatalError** [texstudio-org/texstudio#528]
https://www.grammarly.com/ offers great support for professional writing, especially for not-native speaker. 

So it would be great if there would be a way to incorporate Grammarly suggestions and into the writing experience of TexStudio.

**Comment by BeerStud** [comment]
I have the Grammarly desktop app installed on my Win 10 machine. I found that I can do a cut and paste from texstudio into Grammarly and it works fine. Grammarly ignores most of the special notations in the texstudio text. I am not sure exactly why though. You can manually ignore them yourself. When finished, just reverse the cut & paste operation. I have done this several times with great success. Plus, it finds spelling error the texstudio is missing.

**Comment by sunderme** [comment]
I don't see how grammarly integration can be possible.

**Comment by BeerStud** [comment]
I put in a feature request on the Grammarly site. I got the usual form letter back that their developers are looking into it. If enough people requested it, they might make an API or add-on as they have for MS Word.

**Comment by Dellu** [comment]
I would also love to have Grammarly on Texstudio. But, we have to  first convince the developers of Grammarly to support the (La)TEX format.

**Comment by BeerStud** [comment]
On Thu, 21 Mar 2019 06:31:17 -0700, Dellu stated:

>I would also love to have Grammarly on Texstudio. But, we have to
>first convince the developers of Grammarly to support the (La)TEX
>format. 

On March 4th, I contacted Grammarly regarding supporting Texstudio.
They said that they would pass the request on to the developers. They
also indicated that the number of requests they received would
influence what course of action they took. I think if enough users
requested the feature, they might be inclined to implement it.

-- 
Gerard

**Comment by pawelkudela** [comment]
I have found some solutions which are good enough for my needs. It consists of several steps.
A custom command is added to be executed after the compilation of the LaTex le. This custom command runs a batch script that runs a program for stripping out LaTeX commands. A new file without LaTeX command is saved as detex-out.tex. The content of the file is loaded to the locally hosted web page. Local hosting is done through Web server for Chrome. Grammarly will check your text because it is placed in an editable field.
However, it is not designed in the editions in mind - Java script refreshes this web page every 2 seconds. Once you see some mistakes in red on the web page in the Chrome browser you can immediately correct them in the TeXstudio editor and recompile the document.
More details, the manual and all files needed can be found in the attachment.
[Grammarly-LaTeX-man.zip](https://github.com/texstudio-org/texstudio/files/4245081/Grammarly-LaTeX-man.zip)

**Comment by m-zakeri** [comment]
It would be sweet if developer add such support.

**Comment by Ownezx** [comment]
Perhaps the integration of another tool that contains an API could be possible? https://www.grammarbot.io/ might be a viable option, although it limits you to 100 requests of 10k characters per day on the free plan. So perhaps a manual button to spell check.

Another inconvenience is the fact that you need to create a key for your personal use.

**Comment by Ayadmk** [comment]
It will be great if we can use grammarly with preferable editor texstudio. I agree with @MahatmaFatalError .

**Comment by ppizarror** [comment]
This would be a really nice addition. I'll take a look at this

**Comment by t-moe** [comment]
Visual studio code has an unofficial Grammarly extension. https://github.com/znck/grammarly
Maybe some code could be ported?

**Comment by thangckt** [comment]
Does anyone find a way to work with grammarly so far? 
thanks.

**Comment by jayjeo** [comment]
If you use VS Code instead of TexStudio, you can use Grammarly integration. There is an unofficial Grammarly integration software by Rahul Kadyan. 
https://marketplace.visualstudio.com/items?itemName=znck.grammarly

**Comment by tipf** [comment]
There is a beta API now (which is used by the VS Code plugin).
https://developer.grammarly.com/

**Comment by dhr999** [comment]
Do you know if this feature is being worked on?

**Comment by sunderme** [comment]
no work ongoing.
I tried,to get developer access and did not get an answer. They seem to provide javascript libraries for web development which is not useful for txs.

**Comment by thangckt** [comment]
I finally end up with TexStudio and find an interest in the Latex workshop. It supports Grammarly as an extension of VScode

**Comment by bykhov** [comment]
> no work ongoing. I tried,to get developer access and did not get an answer. They seem to provide javascript libraries for web development which is not useful for txs.

Maybe another try may be considered. Grammarly works with Texstudio forms(!), such as configuration fields (i.e. macro description). Probably there is some relatively simple way to convince it to work inside the editor as well.

**Comment by sunderme** [comment]
grammarly stopped any API support, see also https://developer.grammarly.com/
