### ISSUE TITLE
Macros' triggers don't work anymore

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#531]
### Environment
-   TeXstudio 2.12.14 (git 2.12.12beta2-148-g89cc6994)
-    Qt: 5.9.4
-    OS: Linux Mageia
-    TeX distribution: TeX Live 2018

### Expected behavior
Triggers should work as expected.

### Actual behavior
TXS says in the Edit Macro dialog box: "If this trigger string is written in any tex document, 
it is replaced by the current tag. [...]". It used to work but that's not the case anymore.

### How to reproduce

1. Got to Macros → Edit Macros... and create a new macro, with its trigger being, for example, "aaa" (without quotes) and its LaTeX content being `\foo`.
1. Close the Edit Macro dialog box.
1. Open a document and type "aaa" (without quotes). It is not replaced by `\foo`.

This has been tested even with an empty `texstudio.ini` file.

**Comment by sunderme** [comment]
have tried to change a macro and restart txs then ?

**Comment by dbitouze** [comment]
Indeed, works as expected after a macro change + a TXS restart. What is unexpected (and new) is to have to change a macro + restart TXS.

**Comment by sunderme** [comment]
agreed (not sure whether this is new), I take a look

**Comment by dbitouze** [comment]
Thanks for the effort! But:

### Environment
TeXstudio 2.12.12 (git 2.12.12beta2-16-g7517fb99)

### Actual behavior
Crash: as soon as something is added in "LaTeX Content" area of the "Edit Macros" dialog box. Backtrace attached: [texstudio_backtrace2.txt](https://github.com/texstudio-org/texstudio/files/2948789/texstudio_backtrace2.txt)

**Comment by sunderme** [comment]
hmm, you are using an obsolete version of txs ?

**Comment by dbitouze** [comment]
Indeed, sorry for the noise (my TXS repository became mixed up after I tried to track down the culprit commit with `git bisect`). It works like a charm now.
