### ISSUE TITLE
can't assign Alt-F to find on windows

### ISSUE THREAD

**Issue by catphive** [texstudio-org/texstudio#533]
### Environment
- TeXstudio: 2.12.14
- Qt: 5.8.0, compiled with Qt 5.8.0 R
- OS: Windows
- TeX distribution: miktex

### Expected behavior

I have ctrl-f assign to emacs style "forward." This works fine, but I want to reassign alt-F to find.

In configure texstudio I reassign Menus->Edit->Searching->Find to alt-F.

I do the same with Editor->Basic Key Mapping-> Find.

I would expect that Alt-F would trigger find from then on.

### Actual behavior

Alt-F is ignored. Sometimes it opens the "File" menu.

### How to reproduce

In configure texstudio reassign Menus->Edit->Searching->Find to alt-F.

Do the same with Editor->Basic Key Mapping-> Find.

**Comment by sunderme** [comment]
the OS default is that with alt+letter you can access menus via keyboard. This can't be deactivated (except with some tricks in the program). Just use another shortcut combination.
This will not be changed.
