### ISSUE TITLE
Search for line breaks

### ISSUE THREAD

**Issue by udopt** [texstudio-org/texstudio#535]
### Environment
- TeXstudio: 2.12.10
- Qt: 5.11.1
- OS: Ubuntu 18.10
- TeX distribution: texlive

### Expected behavior
Let us assume there is the following line in a *.tex document:

    abc

Searching for `abc\n` should find the line with `abc` including the following line break. This is useful if the line should be replaced including the line break.

### Actual behavior
When I search for `abc\n`, no result is found. The same is true for `abc\r` (unix line breaks are used though). Searching for `abc` or `abc$` does find `abc`, but without the following line break.

Regular expressions (<kbd>Reg</kbd>) and escape characters (<kbd>\1</kbd>) are enabled.

### How to reproduce
Always.

**Comment by sunderme** [comment]
because of technical limitations, search works on per-line basis only. There is no easy way around this.
