### ISSUE TITLE
How does root detection work?

### ISSUE THREAD

**Issue by tmelorc** [texstudio-org/texstudio#536]
### Environment
- TeXstudio: 2.12.14
- Qt: Using Qt Version 5.11.1, compiled with Qt 5.7.0 R
- OS: Linux (Mint 18 Sarah)
- TeX distribution: TeXlive 2018

I'd like to know how should work the option _Detect automatically_ from the _Root Document_ menu.

I have 2 files open, one is the main one and contains `% !TeX root = main.tex` (not at first line, there are other comments above it) and the other file is just text to input.

When I compile with the second file on the screen I got errors. So I think that the root tools is not so automatic. If I explicitly set the main file as the root file, then its name appears in the status bar and everything works.

Am I doing something wrong?

**Comment by sunderme** [comment]
this should work as advertised.
possible causes for error:
- build command cahnged
- main.tex is not in the same directory as your current file

for debug, we would need:
1) log of the pdflatex run
2) a minimal example which shows the problem

**Comment by tmelorc** [comment]
Daer @sunderme 
I think I found the problem (maybe not directly related to txs). Let me explain.

I have both files in the same path, that is my Dropbox folder on another partition of my hard disc.
The key fact is that I created a symlink from my Dropbox folder to my home folder. Now the problem appears. 

If txs shows on title bar the symbolic path when main.tex is on screen, when I use the _Go to source_ tool txs opens the real file from the other partition, so txs shows another path when the second file is on screen.

This situation breaks the root tool.

Can you understand? Sorry for my pour English.

**Comment by sunderme** [comment]
apparently pdflatex writes the real filenames into the synctex file. I don‘t see that txs can resolve this...
