### ISSUE TITLE
Text analysis - no counting 

### ISSUE THREAD

**Issue by vrm265** [texstudio-org/texstudio#537]
### Environment
- TeXstudio: 2.12.14 
- Qt: 5.11.2
- OS:  Mac OS 10.14.3 Mojave
- TeX distribution MacTeX-2018 

### Expected behaviour
Show the counting of numbers of lines, number of characters in phrases, number of total shown phrases, number of different phrases, number of comment lines, number of total lines, number of text lines. 

### Actually behaviour 
Instead of a number the character '?' is shown in all of the fields. This happens in text analysis of both the total document and only selected text. 

### How to reproduce 
Just open the text analysis tool and try to analyse.

**Comment by foreachthing** [comment]
This is with 2.12.14 on WIndows 7 x64:

![image](https://user-images.githubusercontent.com/10420187/54356159-306e1600-465b-11e9-8ed8-0f5c096d9cee.png)

**Comment by benibela** [comment]
have you clicked the "Count" button?

**Comment by vrm265** [comment]
Yes.. I have got the counting result now, but is look like the result are first shown after shifting between application windows. If I just wait for the result after pressing the “count“ button nothing is shown, but if i shift to another application and then back again the result are shown???

**Comment by sunderme** [comment]
works fine on linux.
Can you provide a tex file and its analysis results ?

**Comment by sunderme** [comment]
no feedback
