### ISSUE TITLE
[feature-request] Project-wide structure view

### ISSUE THREAD

**Issue by kbauer** [texstudio-org/texstudio#538]
Currently, the structure tree displays only contents of the current file. When working with larger, multi-file documents, it would be helpful to enable viewing the overall outline and TODO lists across all \include/\input files instead.

### Environment
- TeXstudio: 2.12.14
- Qt: 5.8.0
- OS: Windows 10 (1803)
- TeX distribution: Miktex 2.9

**Comment by OmerSakar** [comment]
To get some attention for this enhancement, I want to say that I support this. 

TexStudio currently does not have the idea of a project. It would be great if (for example) folders could be marked as a project and maybe a config file specifying what the main document is. 

The next step would be to have multiple projects open in a view where you would choose which project to build.

**Comment by sunderme** [comment]
txs 3.1.0
