### ISSUE TITLE
Preview pane shows unexpected previews

### ISSUE THREAD

**Issue by kbauer** [texstudio-org/texstudio#539]
From time to time, the preview pane unexpectedly shows previews of seemingly random snippets near the cursor position. Usually this happens with equations, but sometimes odd cases occur (see screenshot).

I have observed this behavior at least since sometime last year; It occurs erratically, and I couldn't yet pin down, what is causing it. It does *not* require having used the preview feature since the last restart of TexStudio, and occurs even when the "Preview > Auto Update" setting is set to "Never".

Since the Alt+P hotkey isn't easily hit by accident, that shouldn't be the cause.

## My preview settings
![image](https://user-images.githubusercontent.com/7498468/54460301-74e7d780-4769-11e9-9e5b-9f2cdabeb485.png)

## An example while editing macros in a document preamble.
![image](https://user-images.githubusercontent.com/7498468/54460329-8cbf5b80-4769-11e9-9c6f-da08ff1ef666.png)

### Environment
TeXstudio: 2.12.14
Qt: 5.8.0
OS: Windows 10 (1803)
TeX distribution: Miktex 2.9

**Comment by sunderme** [comment]
options/preview/show preview as tooltip on formulas in editor
and options/preview/display mode -> always show in panel or always both.

**Comment by kbauer** [comment]
@sunderme I sadly don't quite understand the comment. My problem is that previews show up, when none should at all, not where they do. For reference, there's also new source code highlighted for preview. 

Changing it to tooltips only would likely make the issue less noticable, but it would also make intentional previews less useful to me.

**Comment by sunderme** [comment]
the admittedly short answer states, that you probably see designed funtionality.
When hovering with the mouse over certain source code constructs, (e.g. $), txs can start automatically a tooltip preview which may also show up in the preview pane, see above. I am guessing that you are triggering the tooltip prview by accident and said options allow you to turn it off.

**Comment by sunderme** [comment]
I assume that the issue is explained
