### ISSUE TITLE
Different icons for .cls, .sty, .tex file types

### ISSUE THREAD

**Issue by sergiokapone** [texstudio-org/texstudio#540]
I open   .cls, .sty, .tex with TXS.  If there are opened many tabs, one of them is .cls or .sty-file, it is easy to mistakenly run the compilation and get an error. It is possible to make a feature to prevent compilation .cls or .sty?

**Comment by sunderme** [comment]
I think you can manually assign different icons. I will not invest time here.
And surely you could prevent compilation based on file extension, but again, only if someone provides a pull-request.
