### ISSUE TITLE
Shortcut to indent line where cursor is

### ISSUE THREAD

**Issue by bdespond** [texstudio-org/texstudio#542]
### Environment
- TeXstudio: TeXstudio 2.12.14 
- Qt: Qt Version 5.9.5, compiled with Qt 5.9.5 R
- OS: Ubuntu 18.04
- TeX distribution: texlive

### Expected behavior
I want to create a new shortcut, say ctrl+rightarrow, to indent the line where the cursor is.
This would be a combination of two existing shortcuts:
Expand Selection to Line  :  Ctrl+L ( present in the Shortcuts > Menus > Edit > Selection)
Tab or Indent selection: Tab (Shortcuts > Editor > Basic Key Mapping)

I do not see how to create such a shortcut. The "add row" in the Shortcuts > Editor  > Basic Key Mapping did not help.

I tried creating a macro to combine two shortcuts but did not understand how that would work.

**Comment by timhoffm** [comment]
You can directly use `Idefix > Indent`.
