### ISSUE TITLE
Autocomplete does not work for package imported through sty file

### ISSUE THREAD

**Issue by MR2387** [texstudio-org/texstudio#544]
Even with .cwl file selected from configure->completition the packages imported through a personal .sty file are not recognized by TeXstudio.

**Comment by MR2387** [comment]
Even with .cwl file selected from configure->completition the packages imported through a personal .sty file are not recognized by TeXstudio.

**Comment by sunderme** [comment]
way too little information for any sensible debugging attempt.
Please provide all information which were asked for in the issue template.

**Comment by MR2387** [comment]
Sorry.
I created a personal package that loads some packages and defines new commands (mysetting.sty).
Then I load \usepackage{mysetting} in the .tex file (paper.tex).
TexStudio does not perform auto-completion of the commands loaded in mysetting.sty file.
Also, it marks them as unrecognized commands.
I have tried everything I found on the net and TexStudio manual, but nothing seems to work.
I don't know if I'm just not able to do that or it's a TexStudio bug. 
Could you please show me the procedure to do that?
So that I can try and check what is wrong between me and the code!
Thank you very much!

**Comment by sunderme** [comment]
txs does not load and analyze custom packages. You need to provide a cwl file and place it where txs stores its settings, see wiki.

**Comment by MR2387** [comment]
Is there any way to automatically generate a .cwl file for a custom package?
If not, how do I do that? Is there a guide on how to write a .cwl file? Thanks.

**Comment by sunderme** [comment]
take a look at the wiki: 
https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions

**Comment by yashpalgoyal1304** [comment]
> I don't know if I'm just not able to do that or it's a TexStudio bug.

it sometimes work, sometimes doesn't.

And as it _does work_ sometimes, i'd say it's a texstudio bug

**Comment by yashpalgoyal1304** [comment]
> User-defined commands are unrecognized.
\- @ bykhov at https://github.com/texstudio-org/texstudio/issues/1163

> local sty files are not analyzed. You need to provide a cwl file.
\- @ sunderme at https://github.com/texstudio-org/texstudio/issues/1202#issuecomment-671444690

I just can't understand this usual hard take on "local sty" files, as if using local sty files is some sort of crime or what

on .cwl file generation for existing packages:
* https://github.com/texstudio-org/texstudio/issues/952
* https://github.com/texstudio-org/texstudio/issues/1346
