### ISSUE TITLE
List all compile dependencies

### ISSUE THREAD

**Issue by Krzmbrzl** [texstudio-org/texstudio#547]
I know there is this wiki page about compiling (https://github.com/texstudio-org/texstudio/wiki/Compiling) but the dependencies listed there are not remotely close to complete.

I am trying to compile TS on Linux so I can only talk about the dependencies there, but I find dependency after dependency that isn't listed on that wiki page.

I think someone should take his/her time to properly document what TS is currently depending on (and which version of it).

**Comment by sunderme** [comment]
done

**Comment by Krzmbrzl** [comment]
Nice - thank you!
