### ISSUE TITLE
Autoloading of glossaries.cwl is not working

### ISSUE THREAD

**Issue by Aentfs** [texstudio-org/texstudio#548]
### Environment
- TeXstudio: 2.12.14 (git 2.12.14)
- Qt: Using Qt Version 5.11.2, compiled with Qt 5.11.2 R
- OS: macOS Mojave
- TeX distribution: mactex

### Expected behavior
When writing a document the `glossaries` commands and labels should be auto completed and not marked as unknown.

### Actual behavior
Commands and labels are neither auto completed nor recognized as valid.

### How to reproduce
Sadly i don't know how to reproduce this behavior. It just started today. The only related update was languagetool. The `glossaries.cwl` file seems to be okay, as permanently activating the autocomplete file in preferences works around the problem. The document can be compiled and it only seems that the auto detection is malfunctioning.

If i can provide you with any logs pertaining to the issue, let me know.

**Comment by sunderme** [comment]
we would need a reproducible example
