### ISSUE TITLE
Counting number of referred labels

### ISSUE THREAD

**Issue by tmelorc** [texstudio-org/texstudio#549]
I'm using 
TeXstudio 2.12.14 (git n/a)
Using Qt Version 5.11.1, compiled with Qt 5.7.0 R

When I use `\label{}` and `\ref{}` it is possible to know if an specific `\label{}` was cited simply mousing over the command `\label{}`. So a tooltip appears showing the number of times it was referred to. But this feature does not work with `\eqref{}`. 

Is is possible to enable the citation counting when using `\eqref{}`?

**Comment by sunderme** [comment]
works as expected.
What package do you use for \eqref ?

**Comment by tmelorc** [comment]
> works as expected.
> What package do you use for \eqref ?

Well, I really don't understand. It works on another computer using 

```
TeXstudio 2.12.14 (git n/a)
Utilizando Qt Versão 4.8.6, compilado com Qt 4.8.6 R
```

I suspect that the problem is my compiled version of `txs` using Qt5.

By the way, I use `amsmath`. I also observed some math commands not recognized. Maybe it is because I'm loading `amsmath` within another package file.

Let's see if I discover the problem. I'm afraid that I'm compiling it wrong.

Regards.

**Comment by sunderme** [comment]
my guess would be that txs does not load the proper cwl files because of your package, see wiki
