### ISSUE TITLE
Automatically compiling a document, i.e. while typing

### ISSUE THREAD

**Issue by muelli** [texstudio-org/texstudio#550]
### Environment
- TeXstudio: TeXstudio 2.12.14 (git n/a)
Using Qt Version 5.12.2, compiled with Qt 5.12.0 R
via flatpak
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior

I think I would like to see the whole document getting compiled while I type, overleaf style.
I know I can have this with almost trivially by calling smth like `latexmk -pvc` but maybe TeXStudio can even be a bit better than that.

I am aware of the partial update function, i.e. Alt+P but it doesn't work well for larger paragraphs or tables. Currently I press F5 or F7, whatever I can hit more quickly, but it's a bit awkward, because I have to lift my hand for pressing those buttons.  I like the way overleaf does it and I am well aware that it's a rather primitive approach.

**Comment by sunderme** [comment]
not a direction I want to go
unless there are some pull-requests, this will not happen

by the way, with more experience, less compilations are needed

**Comment by manudroid19** [comment]
I see two problems with this: 

-First, the mouse icon changes to "loading" (spinning circle or whatever) whenever you clock compile, compile & see or any compilation order. It would be reaaally great if we could disable this in settings so hitting compile doesn't stop the workflow. 
-Second, we can use the latex -pvc but if we run it outside the program.
If we put the -pvc in TexStudio latexmmk command, the spinning mouse will be there forever and pdf won't update, no matter if we save the file. 

Note that my first comment about the spining mouse icon when compiling is a general improvement that I would love to see implemented, independently from the subject of this issue thread.

Keep up the good work!!!

**Comment by benibela** [comment]
implemented in 448af99890e736963edf8b6042617b8b61055d4c

>-First, the mouse icon changes to "loading" (spinning circle or whatever) whenever you clock compile

There was no spinning mouse here on linux. perhaps the cat ate it



> If we put the -pvc in TexStudio latexmmk command, the spinning mouse will be there forever and pdf won't update, no matter if we save the file.

It only waits for latex commands. If you mark latexmk as non latex command, it should work

**Comment by benibela** [comment]
>-First, the mouse icon changes to "loading" (spinning circle or whatever) whenever you clock compile, compile & see or any compilation order. It would be reaaally great if we could disable this in settings so hitting compile doesn't stop the workflow.

Actually, the spinning mouse (Qt::WaitCursor) it not shown during compilation, but when reloading the pdf
