### ISSUE TITLE
[RFE] Support non-LaTeX engines (xetex etc.)

### ISSUE THREAD

**Issue by chsk-uk** [texstudio-org/texstudio#551]
### Environment
- TeXstudio: 2.12.14
- Qt: 5.8.0
- OS: Windows 7
- TeX distribution: MikTeX

### Description
It would be cool if TeXstudio supported non-LaTeX engines (xetex as opposed to xelatex, etc) and allowed the user to select these for a document using the `%!TEX TS-program` magic comment.

For example, consider the following (hypothetical) plain TeX document:

```
%!TEX TS-program = xetex
Hello, \TeX!
\bye
```

Assume that the user attempts to compile this document using TeXstudio's "Compile" function (F6).

### Expected behavior
TeXstudio recognizes "xetex" as a valid engine, and compiles the document using xetex.

### Actual behavior
TeXstudio does not recognize "xetex" as a valid engine, and falls back to the default instead; the default (latex) engine then produces various errors, starting with " LaTeX Error: Missing \begin{document}."

**Comment by sunderme** [comment]
you can change any program to whatever you, here xelatex as `xetex ...` , so that '%!TEX TS-program = xelatex' actually uses xetex.

**Comment by chsk-uk** [comment]
Thanks for the reply --- yes, that will work, but then I can't use xelatex for actual LaTeX documents anymore.

(I suppose I could abuse another engine for this that I don't need, e.g. pdflatex; but IMHO proper support for xetex (and luatex, etc.) is the proper solution. Having a document specify e.g. `'%!TEX TS-program = pdflatex` and silently expect the editor to be configured to actually use xetex when pdflatex is requested would hamper readability, maintainability and portability.)

**Comment by sunderme** [comment]
I have extended txs to handle user-commands in the header (e.g. '! TeX program = user0')
Hence xetex or any other variant can be defined there additionally to any predefined commands.
Since the number of commands is endless and the number of potential users is rather limited, I don't see the necessity to adapt the command handling any further.

**Comment by chsk-uk** [comment]
Works for me. Thanks!
