### ISSUE TITLE
In menu "Macros" hided any macros

### ISSUE THREAD

**Issue by sergiokapone** [texstudio-org/texstudio#555]
### Environment
- TeXstudio 2.12.16 (git 2.12.16beta1) Portable
- Qt: Qt 5.12.1 R
- OS: Windows 10, 1803
- TeX distribution: Doesn't matter

### Expected behavior

Menu Macros does not apper any macros!!! 
When I start beta1, my macro section in ini-file of previous 2.12.14 version was replaced by 
Macros\0=, , , 
Macros\1=, , , 
Macros\2=, , , 
Macros\3=, , , 
Macros\4=, , , 
Macros\5=, , , 
Macros\6=, , , 
Macros\7=, , , 
Macros\8=, , , 
Macros\9=, , , 
Macros\10=, , , 
Macros\11=, , , 

### Video Illustration 

Video Illustration [Youtube](https://youtu.be/FqzPSH19CdQ)

### How to reproduce

Just click to TXS main menu item "Macros"

**Comment by sunderme** [comment]
Macros are not stored in the ini any more but in a directory macro, next to texstudio.ini

**Comment by sergiokapone** [comment]
Ok, I see. But by some miracle the macros themselves have moved after the third time.

**Comment by sunderme** [comment]
so, we can close this issue ?

**Comment by sergiokapone** [comment]
I, think, yes
