### ISSUE TITLE
UPX packer does not pack  2.12.16beta1

### ISSUE THREAD

**Issue by sergiokapone** [texstudio-org/texstudio#556]
### Environment
- TeXstudio 2.12.16 (git 2.12.16beta1) Portable
- Qt: Qt 5.12.1 R
- OS: Windows 10, 1803
- TeX distribution: Doesn't matter

### Actual behavior

UPX packer PX 3.94w do not want to pack new TXS    
with an error "CantPackException: superfluous data between sections (try --force)"

**Comment by sunderme** [comment]
I am not sure, how we can anything do about it.

**Comment by sergiokapone** [comment]
The UPX packed well TeXstudio 2.12.14, but TeXstudio 2.12.16 do not. Possible something went wrong during compilation sorces, I think.

**Comment by sunderme** [comment]
Still not sure how that is txs' fault.
Packer takes files -> generates packed files ? Should not depend on any details of the files .

**Comment by sergiokapone** [comment]
Packer takes texsudio.exe (>~200 Mb) -> generates packed file texsudio.exe (>~40 Mb) 
https://upx.github.io

**Comment by sunderme** [comment]
still the pint is valid: upx problem, not txs
