### ISSUE TITLE
\input cannot find the .tex file

### ISSUE THREAD

**Issue by annehulsey** [texstudio-org/texstudio#559]
I am trying to input another file from the same folder. The structure panel can identify and open the file so the file name is correct and TexStudio can find it. However, when I compile, I get an error that the file was not found. This happens with both a relative and an absolute path.

### Environment
- TeXstudio: 2.12.14
- Qt: 5.8.0
- OS: Windows 10
- TeX distribution: miktex

![input_error](https://user-images.githubusercontent.com/28743653/56060802-b47bf200-5d1c-11e9-97c0-a5424fa7c4db.JPG)

**Comment by dbitouze** [comment]
Avoid space in filenames (generally advised). Otherwise, put the name within quotes: `\input{"Recovery Framework_objective"}`.

**Comment by annehulsey** [comment]
You're right - removing the spaces fixed the issue. And thank you for the tip about the menu entry - that makes me realize that I am not using TeXstudio to it's full potential.
