### ISSUE TITLE
No reference to version 2.12.8 on texstudio.org

### ISSUE THREAD

**Issue by vmercuri** [texstudio-org/texstudio#56]
Not sure if this is the right place to point this out. However, I've just stumbled upon Texstudio's github repo to find out that a new version (after 2.12.6) [has been released](https://github.com/texstudio-org/texstudio/releases) (with the _Latest release_ tag, as opposed to _Pre-release_). No mention of this on the main [website](https://www.texstudio.org/).

**Comment by sunderme** [comment]
for lack of time, the 2.12.8  release is not yet complete
