### ISSUE TITLE
Building texstudio on a mac

### ISSUE THREAD

**Issue by a-reisberg** [texstudio-org/texstudio#565]
I keep getting error about poppler cannot be found when trying to build on a mac
```
poppler-qt5 development package not found
```
What is the correct way to get poppler to install in the right place so the build script can find it?

Thanks!

### Environment
- TeXstudio: current master
- Qt: 5.9.5
- OS: MacOS 10.14.4

**Comment by sunderme** [comment]
Have you followed the instructions on https://github.com/texstudio-org/texstudio/wiki/Compiling ?

**Comment by a-reisberg** [comment]
@sunderme Thanks for the quick reply! I realized that I kept getting 
```
Error: invalid option: --with-qt5
```
whenever I try to install poppler by running
```
brew install poppler --with-qt5
```
Is the guide up to date?

**Comment by sunderme** [comment]
possibly not.
Try 'brew install poppler --with-qt'

**Comment by a-reisberg** [comment]
Either one gives me the same error, unfortunately :/

**Comment by sunderme** [comment]
brew install poppler --with-qt should work, see https://formulae.brew.sh/formula/poppler#default

**Comment by sunderme** [comment]
okay, apparently "--with-qt" is not needed any more, try without any options.

**Comment by a-reisberg** [comment]
That's what I originally had and got the error
```
poppler-qt5 development package not found
```
Since it couldn't find `poppler`, I also tried running
```
./build.sh INCLUDEPATH=/usr/local/Cellar/poppler/0.74.0/include/poppler/qt5 LIBS=-I/usr/local/Cellar/poppler/0.74.0/lib
```
But that didn't work either.

**Comment by sunderme** [comment]
is pkg-config in your search path ?

**Comment by a-reisberg** [comment]
No! Should I install it with brew?

**Comment by sunderme** [comment]
it should be on the computer (by brew). Is /usr/local/bin part of the search path ?

**Comment by a-reisberg** [comment]
`/usr/local/bin` is part of the search path. I just installed `pkg-config` with brew and now am trying to compile.

**Comment by a-reisberg** [comment]
Awesome! It works now. So I guess it's just the `pkg-config` thing not being there already with `brew`.

One quick question (somewhat unrelated). Essentially, reloading pdf always flickers, so I was thinking of making it repaint more nicely. Any pointer where I should look?

**Comment by sunderme** [comment]
look at src/pdfviewer/PDFDocument
