### ISSUE TITLE
Typing lag on Linux

### ISSUE THREAD

**Issue by flberger** [texstudio-org/texstudio#567]
When typing, characters appear with a considerable delay, as if flushed from a buffer.

TeXStudio is the only software on my computer with this problem.

### Environment

- TeXstudio: 2.12.6
- Qt: 5.11.1
- OS: Gentoo Linux Kernel 4.10.11, X.Org X Server 1.20.0, DRI enabled
- TeX distribution: texlive 2017

### Expected behavior

Typed characters should appear immediately and fluently as soon as the key is being pressed.

### Actual behavior

Characters appear with a considerable delay.

For example, typing the word "well", the "w" might appear, but the "ell" letters do not appear until all of them have been typed.

Typing keys in a row very quickly, such as "asdlkjasdlkj", results in almost a second delay where no character is displayed. Then the characters appear all at once.

### How to reproduce

1. Open TexStudio.
2. Create an empty document.
3. Type "well" at the beginning of a line quickly. Observe the delay between "w" and "ell".
4. Enter a new line, and type "asdlkjasdlkj" quickly. Observe the ~1 second delay with nothing happening, followed by the flushing of the characters, appearing all at once after the delay.

### Additional information

I have just compiled and installed TeXstudio 2.11.2 from 2016, which shows the same behaviour. I would suspect a Qt component / setup, or a font rendering issue. However, since TeXStudio is the only program on my computer with this behaviour, and other heavy GUI tools as Thunderbirg or LibreOffice do fine, I would appreciate any help tracking this down.

**Edit:** I do not know the internals of TeXStudio apart from that it uses Qt, but learning about the text editor component / widget used would enable me to ask in other Qt related forums.

**Comment by flberger** [comment]
So I see TeXStudio uses `QCodeEdit` / `QEditor` as the editor component, which might be the culprit here.

What worries me a little about this is that the website looks [dead](http://www.qcodeedit.org/), the [repo has not had an update in 10 years](https://sourceforge.net/projects/edyuk/files/qcodeedit/), as has the [thread on QtCentre](https://www.qtcentre.org/printthread.php?t=3178&pp=50&page=5). Is that component still in active development?

**Comment by sunderme** [comment]
in deed, qcodeedit is not developed any more, but the code has been heavily extended for txs, so switching to anything else is difficult.

**Comment by flberger** [comment]
I found this issue in the Sourceforge bugtracker that is very similar to mine: https://sourceforge.net/p/texstudio/bugs/2121/

But in my case it already happens in a completely fresh document.

I will try again on MS Windows on the same machine as a cross-check.

**Comment by flberger** [comment]
Alas, on MS Windows v2.12.10 with Qt 5 runs smoothly. So this is likely a Qt issue on Linux in conjunction with how the txs components handle input and rendering.

I suspect `QDocument` of `QCodeEdit` and `Qpainter` of Qt of doing something very inefficently here, but I am not even remotly familiar with acutal Qt coding to track this down.

What would be helpful was a debug build of txs (or `QCodeEdit`) which emits exactly what it is doing when the user types characters into the document. Does such a setup exist?

**Comment by sunderme** [comment]
just for your information, there is no issue on ubuntu nor on centos.
So, it is like an issue with Qt and Gentoo ...

**Comment by benibela** [comment]
A profiler might help to figure this out, e.g. gprof, valgrind or gperftools

Or try different render settings (see advanced editor config page)

**Comment by timhoffm** [comment]
Just to be sure:

1. The lag only happens in the editor; not in any other text fields such as `Wizards -> Insert Graphics...`?
2. Does it still happen if you set `View -> Highlighting` to 'Plain Text'?

**Comment by flberger** [comment]
@timhoffm As a matter of fact:

1. The lag _does_ happen in other text fiels, such as in `Insert Graphics`.
2. Yes, it still happens with "Plain Text" highlighting.

I do not have detailled knowledge about what Qt + X + Freetype do in the background, but the lag apparently happens in the pipeline keyboard input -> processing in txs, Qt etc. -> glyph rendering and display.

What baffles me is that this _only_ happens in txs on my machine. Then again, I believe I do not have any other program that utilises elaborate richt text input using Qt.

**Comment by timhoffm** [comment]
That means, it's a general Qt/something issue and not related to `QCodeEdit` or our background parsing of the document.

**Comment by sunderme** [comment]
I agree, typing lag in text fields is outside of our scope.

**Comment by benibela** [comment]
You could also try to change the appearance settings (style, color scheme)
