### ISSUE TITLE
Change way TeXStudio handles references pushed from BetterBibTeX

### ISSUE THREAD

**Issue by sabotech** [texstudio-org/texstudio#57]
I use BetterBibTeX as a Zotero add-on and it has a function to "push references to TeXStudio". Using this produces /cite{CitationKey} at the point of the cursor in TeXStudio, and is a fast and easy way to include citations in the document I am working on.

I would like to customize the way TeXStudio handles these citations, specifically by bracketing them in \parencite[]{CitationKey} instead of \cite.

Apparently, from this conversation https://github.com/retorquere/zotero-better-bibtex/issues/862, BetterBibTeX only pushes the citation and TeXStudio decides to bracket them in \cite{}

Is it possible to change how TeXStudio handles these references pushed by BetterBibTeX from Zotero?

**Comment by dbitouze** [comment]
This has to be done at the `Better BibTeX` level:

Edit → Preferences → Better BibTeX → Citations Keys → LaTeX command → \parencite

IMHO, you should consider `\autocite` instead of `\parencite`.

**Comment by sabotech** [comment]
Thank you! 

With this workaround I was able to get my preferred LaTeX command (I used autocite[] instead of the standard cite) while dragging and dropping (or copying and pasting) the citation from Zotero into the LaTeX document. For others who would like to do this, please note that it also required changing another preference in Zotero to get working:

Preferences → Export → Default Format → Better BibTeX Citation Key Quick Copy 

However, to my original question, right clicking the citation in Zotero and using the "Push references to TeXstudio" function still yields the same `\cite` instead of `\autocite[]` even after changing my LaTeX command in BetterBibTeX preferences in Zotero. Although I now have a decent workaround, for curiosity's sake, is there a way to change how TeXStudio wraps the citation key pushed by Better BibTeX? The developer of BBT says that it only pushes the key to TeXStudio, and that how TeXStudio handles it should be configurable, and points to the `--insert-cite` command. I don't know how to edit this, but would it be possible to do so?

**Comment by sunderme** [comment]
insert-cite command is now configurable

**Comment by dbitouze** [comment]
@sunderme Thanks! I noted the corresponding string: 

> <html><head/><body><p>External programs can push citations into texstudio by calling texstudio --insert-cite &quot;citation&quot;.</p><p>If the cursor is not already within an citation command, the command given here is used as \cite-command.</p></body></html>

I guess:
1. "External programs" is rather vague and meaningless for some users. What about giving Zotero as example?
1. "the command given here is used as \cite-command" may be confusing. Do you mean: "the command given here is the one that is pushed".

If so, I suggest instead:

```html
<html><head/><body><p>External programs (such as Zotero) can push citations into TeXstudio
by calling: <code>texstudio --insert-cite &lang;command&rang;<code>.</p><p>If the cursor is
not already within an citation command, the <code>&lang;command&rang;<code> used will be
the one given here.</p></body></html>
```
