### ISSUE TITLE
[Question] texstudio "eating" curly brackets away, ways to change that?

### ISSUE THREAD

**Issue by ScyllaHide** [texstudio-org/texstudio#578]
### Environment
- TeXstudio: 2.12.6 (newer version does use double memory for me)
- Qt: 5.6.2
- OS: Windows 10 Pro x64 Version 1602 OS build: 14393.2214
- TeX distribution: miktex updated 16. April 2019

### Expected behavior
Lets say I have a \frac and inside I_{i=1} for example.
`\frac{I_{i=1}}{}`

### Actual behavior
`\frac{I_{i=0}{}` then texstudio shouldnt eat one curly bracket away.

**Question:** 
Why does texstudio use one upcoming curly bracket? Is this connected with texstudio closing brackets? (eg. when i type `{` i get `{}`?)
I takes me always hours to search for not closed brackets, and sometimes one can see how a bracket is used, because it is coming up!

Thank you for reading and maybe having a solution!
SH

**Comment by sunderme** [comment]
if "auto complete brackets" is activated, the second bracket is handled s a placeholder in order to avoid writing additional brackets.
So, you can either disable "auto complete brackets" or you make use of the autocompleters (for commands and brackets) and never write a closing bracket gain...
