### ISSUE TITLE
TexStudio & packages

### ISSUE THREAD

**Issue by aaasokol** [texstudio-org/texstudio#58]
Hello. I installed TexStudio (and reinstalled twice) of coarse from official site. But when i'm coding, i can place the cursor to the line "\usepackage{...}", where instead of "..." can be name of any package (just usual packages, nothing special). And my TexStudio says that tis package is "not found" (in russian "не найдено"). I worry about that, because TexStudio says me that a lot of commands that I use in ShareLaTeX are unknown, and it's a problem. What should I do?

**Comment by Alexander-Wilms** [comment]
Have you installed TeX Live or MiKTeX?

**Comment by aaasokol** [comment]
I installed MacTex, I found that it includes Tex Live. I opened mactex.pkg, it was installed, and I didn’t see anything else

**Comment by sunderme** [comment]
try 2.12.8
