### ISSUE TITLE
Do not retry rendering instantly if previews fail

### ISSUE THREAD

**Issue by jonasstein** [texstudio-org/texstudio#581]
### Environment
TeXstudio 2.12.16 (git n/a)
Using Qt Version 5.12.3, compiled with Qt 5.12.2 R
Gentoo Linux

### Expected behavior
TeXstudio should not repeat to render a preview image, if the compilation fails and the formula did not change.

Hash of failed previews could be stored for a while (a few minutes, or as long the client is not restarted?). 
Render formula, if its hash is not in the blacklist of failed formulas.

### Actual behavior
Endless loop of
```
Process started: latex -src -interaction=nonstopmode "hnaAsC".tex
Process exited with error(s)
Process started: dvipng -T tight -D 120 "rShmNs".dvi
Process exited with error(s)
Process exited with error(s)
...
```
as long the mouse cursor moves in vicinity of the formula.
High CPU load

**Comment by manudroid19** [comment]
I have just tried and when the compilation fails, it just stops the inline preview, it doesn't keep trying to compile. Could you provide a test file?

Remember you can disable this preview in settings

**Comment by jonasstein** [comment]
It is independent of the file. When I move the mouse close to the preview region, I can trigger this effect.
I am not sure, if the cursor is flipping between two pixels after every redraw and supports the loop. I will try to find out more, so that you can reproduce it easier.

**Comment by manudroid19** [comment]
Thank you. A video or screenshot could help also. In what OS are you running Texstudio?

**Comment by sunderme** [comment]
I don't see a repeated call either ...

**Comment by sunderme** [comment]
not reproducible
