### ISSUE TITLE
Please remove unused horizontal space in the sidebar

### ISSUE THREAD

**Issue by vporton** [texstudio-org/texstudio#583]
### Environment
- TeXstudio: 2.12.14
- Qt: 5.12.2
- OS: Ubuntu Linux 19.04
- TeX distribution: texlive

The unused horizontal free space in the sidebar should be decreased, to use the screen more effectively.

The unused free space is depicted with the right rectangle at the picture:

![shot](https://user-images.githubusercontent.com/2900574/56792868-50285a80-6813-11e9-85df-3136635d1757.png)

It can be done by making **volume-1.tex** a label rather than an item of the tree.

**Comment by dbitouze** [comment]
Open more than one file in TXS and you'll see the benefit of items rather than labels.

**Comment by vporton** [comment]
@dbitouze I disagree:

Bold labels can be used like headers (as in HTML). This is a good alternative to the tree.

Yes, the subtrees should be collapsible, but this can be done without making them an item of a tree, in some other way.

Saving space is here the most important point.

**Comment by timhoffm** [comment]
This is a `QTreeWidget` all elements get their collapse marker. It's not possible to configure this.

**Comment by vporton** [comment]
@timhoffm My proposal is to replace single `QTreeWidget` with several (vertically stacked) labels and `QTreeWidget`s. This way it is possible.

**Comment by timhoffm** [comment]
I see. That would in principle be possible. However, this has two practical problems:

1. You wouldn't be able to fold the content of the files. So having multiple files would result in a very long widget.
2. From the implementation side, all information is contained in one large model that is mapped by a QTreeView. You would have to untangle that and this structure is really not easy to handle. Maybe ProxyModels could do. But I wouldn't touch this stuff just for some space savings.

More generally, if one reworks the underlying model, it should be changed in such a way that one can have
- a plain or hierarchical list of files.
- a structure view that is document-centered, not file-centered. I.e. I get the section tree from all related documents and don't bother which file they are in.

IMO these changes would really add usability benefit. The gain/effort for just removing the whitespace is not worth it.

**Comment by vporton** [comment]
@timhoffm As I've already said, folding is possible to implement in some other way (by adding a collapse button by ourselves).

I don't get what you mean by space savings.

**Comment by timhoffm** [comment]
space savings = removed unused horizontal space

Of course, it's possible to implement additional folding explicitly again. But this another extra effort.

I'm not fundamentally against the concept. But it's a lot of work for a IMHO minor gain. You are welcome to provide a pull request if you feel strongly about it and like to take this on.

**Comment by vporton** [comment]
So, suggested to improve Qt: https://bugreports.qt.io/browse/QTBUG-75466

**Comment by timhoffm** [comment]
Note that you can already set `StructureView\Indentation=N` (N in pixels; -1 uses the OS default) in `texstudio.ini` to define how much indentation each level is given. Maybe that's already sufficient for you.

**Comment by vporton** [comment]
@timhoffm Thanks, `StructureView\Indentation=10` improves.

I'd try to set even smaller indentations, but that produces the collapse subwidgets to be placed outside of the screen.

To fix Qt would be better.

**Comment by sunderme** [comment]
since it is then a qt issue, nothing we want to do about it.
