### ISSUE TITLE
Labels of figures confused with those of sections or subsections.

### ISSUE THREAD

**Issue by jlucio2019** [texstudio-org/texstudio#588]
I'm doing this:
\begin{figure}[t]  \label{fig1}
  \centering
  \includegraphics[width=10cm]{drawing1.pdf}
  \caption{Particle at a distance $c$ from centre and $r$ from spin axis.}
\end{figure}

The 'issue' is with \label{fig1}. It is inside figure environment, but LaTeX is assigning it to the section or subsection.

Issue disappeared when I moved the \label{fig1} after the caption.

Was the fist location of label wrong?

### Environment
- TeXstudio: 2.12.14  
- Qt: TeXstudio 2.12.14 (git 2.12.14)
Using Qt Version 5.8.0, compiled with Qt 5.8.0 R 
- OS: Windows 10 
- TeX distribution: MiKTeX 2.9 

### Expected behavior
A label defined (with \label{}) inside a figure should give when referenced (by \ref{}) the number of the figure.
So first figure should be referenced as Figure "1", second as "2", etc.

### Actual behavior
They are actually giving the number of subsection (if it exists; if not, that of section).
First figure is referenced as Figure "1.2" and second figure also as "1.2" ("as"??? both are inside subsection 1.2).

### How to reproduce
Just compiling (F5).

**Comment by timhoffm** [comment]
Please note that this is issue tracker is for TeXstudio-related bugs only. However, your question is about LaTeX itself. Such questions are better placed at https://tex.stackexchange.com/.

In particular see https://tex.stackexchange.com/questions/32325/why-does-an-environments-label-have-to-appear-after-the-caption

**Comment by jlucio2019** [comment]
Sorry, I had interpreted it as a bug of TeXstudio.
Jesus.
