### ISSUE TITLE
Texstudio git integration

### ISSUE THREAD

**Issue by jpksh90** [texstudio-org/texstudio#59]
A new plugin to manage code using git instead of svn.

**Comment by thatlittleboy** [comment]
Some workarounds were proposed before on TeX.SE: [TexStudio / TexMaker and Github](https://tex.stackexchange.com/q/112396/117534) (for discussion's sake).

**Comment by i2000s** [comment]
Could it be possible to let users choose a version control software on the previous SVN command setting window in Options--either SVN, Git or something else? If this is possible, then let the software decide to choose a set of macros to show on the menu based on the name of files linked for git/SVN/Else commands.

**Comment by genodeftest** [comment]
I'd rather recommend using a git gui for your OS, e.g. [Gitg](https://wiki.gnome.org/Apps/Gitg) on Linux or the GitHub client on Windows. You may also want to use the cross-platform but clumsy git-gui shipped with upstream git.

**Comment by chrisma** [comment]
As a first step, would it be possible to show a Terminal window as a pane in TeXStudio (maybe as another tab in the lower left corner next to "Messages", "Log" etc.), instead of opening a separate Terminal window via `Tools -> Open Terminal`?
This would allow using git on the command line without having to leave TeXStudio.

**Comment by sunderme** [comment]
not possible for platform independent program

**Comment by genodeftest** [comment]
@sunderme wrote:
> not possible for platform independent program

Would you mind to explain, please? `git` is a cross-platform application and terminals exist on any platforms supported by TeXStudio.

**Comment by timhoffm** [comment]
There is no simple cross-platform way to interact with a console and also there's no good Qt widget for the frontend. Adding a buitlin console would be a major effort and thus is not likely to come.

See also https://sourceforge.net/p/texstudio/feature-requests/721/

**Comment by sunderme** [comment]
I close this for #340
