### ISSUE TITLE
CNTRL-SHFT-e not working

### ISSUE THREAD

**Issue by RainMountainSystems** [texstudio-org/texstudio#591]
The editor no longer inserts \emph{} around text to be emphasized when using the CTRL-SHFT_e method.

### Environment
- TeXstudio: 2.12.14 
- Qt: 5.12.1, compiled with Qt 5.11.3 R
- OS:  Linux (Distribution), Fedora 30 x86_64 

### Expected behavior
I expect CNTRL-SHFT-e to enclose a highlighted of text in a \emph{}

### Actual behavior
I'm not sure how to describe. It definitely screws up the code and it is not easy to unscrew it.

**Comment by muzimuzhi** [comment]
What is your current shortcut for `\empy`? For example
![image](https://user-images.githubusercontent.com/6376638/57203861-fb8c9880-6fe5-11e9-9d22-c2b7ccab7df1.png)

And you can config the shortcut by yourself. See [manual Sec. 1.6].(http://texstudio.sourceforge.net/manual/current/usermanual_en.html#SECTION05)

**Comment by sunderme** [comment]
Furthermore some window manager might reserve shortcuts for themselves. So no general problem, here. Closed.
