### ISSUE TITLE
Where is the latest manual hosted on?

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#593]
Currently, the links of manual of texstudio, both from the README of this repo and from texstudio.org, point to the same webpage hosted on sourceforge: http://texstudio.sourceforge.net/manual/current/usermanual_en.html .

However, the manual on sourceforge is outdated. For example, the explanation about supported `% !TeX program = <engine>`, added in this commit https://github.com/texstudio-org/texstudio/commit/7d5e836cb4ff60a1415d0433861423e0f41f1ae9, can not been found in the manual on sourceforge.

Hence the question:
 - Is the latest version of manual hosted?
 - If yes, where can I visit it, rather than open the html file from local clone?

**Comment by manudroid19** [comment]
Looks like it is not hosted, good point. @sunderme should we consider moving this manual to the wiki, the official website or a github.io webpage?

**Comment by sunderme** [comment]
Usually i would use the code git but if that is not feasible, I am open for suggestions...

**Comment by manudroid19** [comment]
The regular user won't be looking in git, and for sure the won't look in the source code. The website looks like the most appropiate place. I could get to it and also improve the style of the webpage in one month aprox.

**Comment by muzimuzhi** [comment]
I just found that menu `Help -> User Manual` will open local `usermanual_en.html`. This would be the best way for *regular user* to open the user manual, especially it corresponds to the locally installed version of texstudio.

At the same time, updating the hosted user manual to the latest version, or with multiple versions corresponding to main changes of user manual or stable releases of texstudio, still has its significance.

**Comment by muzimuzhi** [comment]
From https://github.com/texstudio-org/texstudio/pull/1119#issuecomment-649598788, it seems that users of texstudio are more aware of online user manual hosted on [sourceforge](http://texstudio.sourceforge.net/manual/current/usermanual_en.html) than the one bundles with texstudio itself.

This raised the need to keep sourceforge manual up-to-date (to the latest stable release).

**Comment by sunderme** [comment]
changed texstudio.org to link to github/master directly

**Comment by muzimuzhi** [comment]
Thanks. Some more things:

1. [`htmlpreview`'s README](https://github.com/htmlpreview/htmlpreview.github.com#usage) suggests to append a`github.com` url to `https://htmlpreview.github.io/?`. Currently a `raw.githubusercontent.com` url is appended. Not sure if there is any preference between them.
   - `github.com` url: https://github.com/texstudio-org/texstudio/blob/master/utilities/manual/usermanual_en.html
   - `raw.githubusercontent.com` url: https://raw.githubusercontent.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html
1. The linked text "user manual" in http://texstudio.sourceforge.net/#participate and https://github.com/texstudio-org/texstudio/#contribute should direct to github htmlpreview link as well. 
2. When searching for "texstudio manual" on google, the [user manual hosted on sourceforge](http://texstudio.sourceforge.net/manual/current/usermanual_en.html) is still at the top of search result. How about adding a warning (and link) at the top of that page, like what we did to [wiki page hosted on sourceforge](https://sourceforge.net/p/texstudio/wiki/Home/)?

**Comment by muzimuzhi** [comment]
Record progress:
 - [x] Use url `https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/blob/master/utilities/manual/usermanual_en.html`
 - [x] update both links to "user manual" on [texstudio.org](https://texstudio.org/)
 - [x] update link to "user manual" on https://github.com/texstudio-org/texstudio/#contribute (see https://github.com/texstudio-org/texstudio/commit/05a39777fde43e789744b5a9d80e893b72189ba5)
 - [ ] update or add warning at the top of http://texstudio.sourceforge.net/manual/current/usermanual_en.html

**Comment by sunderme** [comment]
forward set in  http://texstudio.sourceforge.net/manual/current/usermanual_en.html

**Comment by muzimuzhi** [comment]
Wow! Many thanks.
