### ISSUE TITLE
dark theme tool button color

### ISSUE THREAD

**Issue by Zaraka** [texstudio-org/texstudio#596]
### Environment
- TeXstudio: 2.12.14
- Qt: Using Qt Version 5.11.3, compiled with Qt 5.11.1 R
- OS: Fedora 29
- TeX distribution: texlive

### Expected behavior
Tool buttons are clearly visible in both light and dark theme

### Actual behavior
Some tool buttons are nearly invisible in the dark theme due to their icon color.

![Screenshot_20190507_173133](https://user-images.githubusercontent.com/1270094/57312966-e3547080-70ee-11e9-9795-69e54aa56ea5.png)

**Comment by manudroid19** [comment]
I'm new in this github and I just started contributing to this project, but I have never seen a dark theme in the options. Is that theme official?

It would indeed be great to include a dark theme, of course.

**Comment by Zaraka** [comment]
that is OS color theme. Qt applications get override colors by KDE, but this can also be done in GTK

**Comment by Sunsheep** [comment]
I would also like to mention that the sidebar with the Greek symbols, operators, etc. are difficult to read when using a dark theme.

**Some system Information:**
- TeXstudio 2.12.16
- Qt: Qt-Version 5.12.3, compiled with Qt 5.12.3 R
- OS: OpenSuse Tumbleweed
- Desktop: KDE Plasma 5.16

I have attached a screenshot below.

![hard-to-see](https://user-images.githubusercontent.com/15847409/60544542-4a6e5a00-9d19-11e9-904f-790dca615d1e.png)

**Comment by sunderme** [comment]
this is done
