### ISSUE TITLE
Undoing a bolding/italitization etc requires two uses of undo

### ISSUE THREAD

**Issue by stravant** [texstudio-org/texstudio#6]
# Reproduction steps:

1. Highlight some text 
2. Press the Boldface button in the toolbar to wrap it in `\textbf{ ... }`
3. Press Ctrl + Z to undo
4. The original text is not restored, instead the text is now `\textbf{}`
5. Pressing Ctrl + Z again restores the original text

# Expected behavior:

Since one button press was done to apply the bold styling, one press of Ctrl + Z should fully undo it.

**Comment by jonasstein** [comment]
I can confirm the description of @stravant  after compiling Texstudio 2.12.6 with the latest patches from commit https://github.com/texstudio-org/texstudio/commit/e7c5fe74067b367d11af2177fe3e46d103a9fa3b

**Comment by sunderme** [comment]
fixed
