### ISSUE TITLE
Incomplete syntax highlighting after Restoring Session, Manual "Refresh Structure" needed

### ISSUE THREAD

**Issue by basseur** [texstudio-org/texstudio#60]
I have _Restore Previous Session at Startup_ enabled.

When I open TeXstudio, all the macros are being recognized, but the arguments are not syntax highlighted as they should be.

For example,
* there is no reference or citation highlighting in `\autoref{}` and `\autocite{}` (just normal text).
* In `\includegraphics{}`,  underscores are highlighted as _math command outside math env_ (which they are usually not, as it recognizes them as parts of a filename).
* The argument of `\todo{}` is not highlighted as _commentTodo_.

These are just to name a few. Standard commands/macros work without problem (e.g. `\label{}`, `\section{}`, environments, etc.).
After _Idefix_->_Refresh Structure_, all works as intended.

I have the magic comment `% !TeX root = main.tex` in all my documents.
My preamble is in a separate file, which is being `\input{}` (Maybe that is the problem).

A possible fix might be to have the _Refresh Structure_  routine be executed after loading the files when _Restore Previous Session at Startup_ in enabled.

**Comment by sunderme** [comment]
probably you need to load/restore main.tex 
txs does not automatically load main.tex when it is defined in !Tex root

**Comment by basseur** [comment]
I leave main.tex as well as preamble.tex open the whole time because I noticed before that my own commands won't be correctly highlighted if I don't. So they are loaded each time I start txs and I guess that should not be the issue.

**Comment by sunderme** [comment]
please try the latest development build (https://bintray.com/sunderme/texstudio)

If that does not help, we need a working example which shoes the behaviour (make sure to test it before !!!!)

**Comment by basseur** [comment]
It says _No direct downloads selected for this package_ (or I don't know how to use cURL).

However, a minimal working example (with the commands I mentioned earlier) may be this:

The content of _main.tex_:
```
\documentclass{article}

\usepackage{graphicx}  % provides \includegraphics{}
\usepackage{todonotes} % provides \todo{}
\usepackage{biblatex}  % provides \autocite{}
\usepackage{hyperref}  % provides \autoref{}

\begin{document}
  \include{test.tex}
\end{document}
```
The content of _test.tex_:
```
% !TeX root = main.tex

\includegraphics{some_file.eps}
\todo{some todo note}
\autocite{some-bibid}
\autoref{some-label}
```

It does not matter, if you include the content into the main document with the preamble, or if you include the preamble into the document with the `document `environment. It only matters, that the mentioned commands are not in the same tex file as the `\usepackage{}` commands.

I am using TeXstudio 2.12.6 (hg 6632:7777b2b8a906); Using Qt Version 5.9.1, compiled with Qt 5.9.1 R

**Comment by sunderme** [comment]
https://bintray.com/sunderme/texstudio/texstudio-win/2.12.8-201803071849-git_8d62825#files

**Comment by basseur** [comment]
There is no difference in TeXstudio 2.12.8 (hg 2.12.8-9-g8d62825); Using Qt Version 5.8.0, compiled with Qt 5.8.0 R

**Comment by sunderme** [comment]
deployment has been broken, please try https://bintray.com/sunderme/texstudio/texstudio-win/2.12.8-201803151816-git_f5e3549#files

**Comment by basseur** [comment]
The issue remains with that version of txs:
(TeXstudio 2.12.8 (hg 2.12.8-19-gf5e3549); Using Qt Version 5.8.0, compiled with Qt 5.8.0 R)

**Comment by sunderme** [comment]
your example works fine here with 2.12.8-19
