### ISSUE TITLE
Rename macro folders in new macro gui

### ISSUE THREAD

**Issue by thymaro** [texstudio-org/texstudio#600]
### Environment
- TeXstudio: 2.12.14
- Qt: 5.8.0
- OS: Win 19
- TeX distribution: miktex

### Expected behavior

I want to rename created folders in the new macro gui "edit macros". When I create multiple folders, as they are all just named "Folder", I want to rename them with meaningful names.

### Actual behavior

Renaming folders is not possible. As all folders are named "Folder", when closing and reopening the "edit macros" screen, all the folders have been folded into one single folder named ... "Folder".

### How to reproduce

1. Create at least two macros of your choice.
2. Create two folders.
3. Put one macro in each folder.
4. Close "edit macros" screen.
5. Reopen "edit macros" screen.
6. One folder named "Folder" is left and it contains all macros previously separated into multiple folders.

**Comment by sunderme** [comment]
the folders need to have a unique name
Renaming folders is done by double clicking on the folder name.

**Comment by thymaro** [comment]
double-clicking. The invention of the century! I had not heard of it until only recently. Double-clicking has changed my life in many respects. Now, it has also changed it in in txs. Who'd have thought!?
