### ISSUE TITLE
Problem finding xelatex

### ISSUE THREAD

**Issue by vahidajalluian** [texstudio-org/texstudio#601]
- TeXstudio:  2.12.14
- Qt: 5.5.1
- OS: UBUNTU 16.04
- TeX distribution: Texlive

I have installed Texlive 2019 on my home directory and set the environmental variable as well. The ubuntu console "can" find the xelatex.

### Expected behavior

I hoped that texstudio console could find the xelatex as well.  

### Actual behavior

The message texstudio show in message box is : Error: Could not start the command: xelatex -synctex=1 -interaction=nonstopmode "cv".tex 

When I start texstudio from command line, everything is ok, but when I start it from desktop or other places, the problem appears.

Even manually setting the xelatex directory would solve the problem, but I am looking for automated solution
 
### How to reproduce
I dont know really where the problem is but this is what I had set on my ~/.bashrc file

PATH=/home/vahid/texlive/2019/bin/x86_64-linux:$PATH; export PATH

**Comment by timhoffm** [comment]
Programs started from the deskop do not run within a bash. Therefore settings in `.bashrc` are not available. Try setting the path in `.profile`.

**Comment by vahidajalluian** [comment]
OK, my problem was solved by your hint but that was not the total solution. I got the solution from this link 

https://askubuntu.com/questions/15108/why-is-path-different-in-the-nautilus-elementary-embedded-terminal

Log-out and log-in are obligatory, sourcing didn't work.
Thank you for your help
