### ISSUE TITLE
Autocomplete \displaystyle?

### ISSUE THREAD

**Issue by titizaki** [texstudio-org/texstudio#604]
It's a small thing, but TeXstudio doesn't seem to know the \displaystyle command: it's never present in the small menu that appears during autocompletion.

In the autocompletion part of the preferences, I didn't see any option or package that would make it available.

Did I miss something? If not, is it possible to add this command for autocompletion?

Thanks for your attention.

**Comment by sunderme** [comment]
you need to activate tex.cwl (options/completion)

**Comment by titizaki** [comment]
Thanks for your answer. It is already activated. Autocompletition works fine for all other basic commands except \displaystyle.

**Comment by sunderme** [comment]
change the completer to "all" commands ... after using it more than twice, it will appear in the typical tab.

**Comment by titizaki** [comment]
Aaaah, thank you, it works! I wasn't clear what this option was for.
