### ISSUE TITLE
Unreadable pdflatex log in "Log" panel

### ISSUE THREAD

**Issue by MatthiasNickles** [texstudio-org/texstudio#607]
### Environment
- TeXstudio: 2.12.14 
- Qt: 5.8.0, kompiliert mit Qt 5.8.0 R
- OS: Windows 8.1
- TeX distribution: miktex

### Expected behavior
Readable pdflatex log output in "Log" panel after compiling document.

### Actual behavior
Log panel contents is scrambled (charset or encoding issue?). Correct output (from running pdflatex on the command line) looks like, e.g., "This is pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6745 64-bit) [...] ! Double superscript. [...]", actual Log panel contents looks like "���ⷋ�焜�㎛�ꍌ�┎�攋�敋�擌�☈�㈒�ⷈ�昋 [...]"

### How to reproduce
Press F5, click on "Log". Bug seems independent of the provided LaTeX document.

**Comment by sunderme** [comment]
please provide a test case, containing the log file.

**Comment by MatthiasNickles** [comment]
thanks for the fast reply. Small test document and log file attached (.txt added after .tex to filename just to be able to attach file in github). 
Document content doesn't seem to matter for reproducing the bug.
[test1.tex.txt](https://github.com/texstudio-org/texstudio/files/3188500/test1.tex.txt)
[test1.log](https://github.com/texstudio-org/texstudio/files/3188499/test1.log)

**Comment by sunderme** [comment]
looks okay here.
What language settings do you have on your windows ?

**Comment by MatthiasNickles** [comment]
I can switch between English (US) and German, but it doesn't seem to make a difference for the issue. 
See attachment how it looks on the screen here. 
![texstudio_issue16052019](https://user-images.githubusercontent.com/40700252/57882607-059b6c00-781c-11e9-803b-27370d971b79.JPG)

**Comment by sunderme** [comment]
I guess that the text encoding of the file system is unexpected, you are using ntfs ?

**Comment by MatthiasNickles** [comment]
yes, ntfs. I can open the .log in Intellij and Notepad++ which both auto select encoding UTF-8.

**Comment by muzimuzhi** [comment]
The problem may have something to do with the encoding. The two uploaded files are both not in encoding UTF-8 (using macOS command line tool `file`), although editors like Atom (and others) will detect them as UTF-8.

```bash
$ file -I test1.log
test1.log: text/x-tex; charset=us-ascii
$ file -I test1.tex
test1.tex: text/x-tex; charset=us-ascii

# normal UTF-8 file
$ file -I normal_utf8.tex
normal_utf8.tex: text/plain; charset=utf-8
```

Maybe you can have a try: convert the encoding of `.tex` file, then compile and check the `.log` file.

**Comment by MatthiasNickles** [comment]
I just tried your suggestion and made two observations:

- The problem appears when the .log file is an ASCII file (i.e., UTF-8 with only the US-ASCII subset being used) 

- Whether or not the .log file is in "ASCII-UTF-8" (pure ASCII) or "extended UTF-8" seems to depend on the occurrence of characters in the .tex document which require multiple bytes to encode, such as € (U+20AC), but only outside comments: If at least one such character is part of the document, but not within a %comment, the Log panel is readable, otherwise it's scrambled here. So, interestingly, the bug can occur even if the .tex file itself is "extended UTF-8" if the multibyte character occurs only in a LaTeX comment, because then the generated .log file is "ASCII-UTF-8".

Switching between "ASCII-UTF-8" and "enhanced UTF-8" isn't possible using the "Encoding" menu item, presumable because an ASCII text is already UTF-8.

I've attached a zip with two .tex and .log pairs: one pair is affected by the "Log" problem and the 
other (which contains € outside a comment) isn't. 
[test23.zip](https://github.com/texstudio-org/texstudio/files/3192440/test23.zip)

Reported encodings:
$ file test2.tex  <<<<< bug occurs
test2.tex: LaTeX document, UTF-8 Unicode text, with CRLF line terminators  
$ file test3.tex
test3.tex: LaTeX document, UTF-8 Unicode text, with CRLF line terminators
$ file test2.log  <<<<< bug occurs
test2.log: LaTeX document, ASCII text, with CRLF line terminators   
$ file test3.log
test3.log: LaTeX document, UTF-8 Unicode text, with CRLF line terminators

**Comment by muzimuzhi** [comment]
@MatthiasNickles 
Forgot to say that, on macOS 10.14.4 and with texstudio 2.12.14, the log file you uploaded previews all right.

**Comment by timhoffm** [comment]
What is the setting `Options -> Advanced Editor -> Default Log Encoding`? 

Works fine here (with above set do "Document"). Does it work if you play with that option?

**Comment by MatthiasNickles** [comment]
Thanks! After changing this setting to "Document" it works. I wasn't aware of this setting. Previous setting/default here was one of the UTF-32 entries.
