### ISSUE TITLE
Appdata file is incompatible with flathub

### ISSUE THREAD

**Issue by jakobjakobson13** [texstudio-org/texstudio#608]
Dear developers,

the current ` texstudio/utilities/texstudio.appdata.xml ` file does not comply to flathub policies and the building fails. 

```terminal 
builddir/files/share/appdata/org.texstudio.TeXstudio.appdata.xml: FAILED:
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
• style-invalid         : <developer_name> is too long [Benito van der Zander, Jan Sundermeyer, Daniel Braun, Tim Hoffmann] maximum is 60 chars
```

Would you consider adapting it by adding a content rating and shorten the developer names in order to simplify to build process on flathub?

Regards

**Comment by sunderme** [comment]
I have no idea what content is supposed to look like. The link does not give useful results.

**Comment by tilosp** [comment]
@sunderme you can use the generator https://hughsie.github.io/oars/generate.html
This should be fine (used for example by gedit https://gitlab.gnome.org/GNOME/gedit/blob/master/data/org.gnome.gedit.appdata.xml.in#L45):
```xml
<content_rating type="oars-1.1" />
```
