### ISSUE TITLE
Updating to 2.12.16 but only 2.12.14 listed

### ISSUE THREAD

**Issue by BeerStud** [texstudio-org/texstudio#609]
### Environment
- TeXstudio: TeXstudio 2.12.14 (git 2.12.14)
- Qt: Qt Version 5.8.0, compiled with Qt 5.8.0 R
- OS: Win10 PRO / amd64 | version 1903
- TeX distribution: MiKTeX

When starting TexStudio, a popup indicates that a newer version, 2.12.16 is available, however, the site only has 2.12.14 shown. The actual file is: texstudio-2.12.14-win-qt5.exe

### Expected behavior
To download the correct file.

### Actual behavior
Downloading an older version

### How to reproduce
https://texstudio.org

**Comment by sunderme** [comment]
it takes a few minutes to set everything up ...
