### ISSUE TITLE
2.12.14 still mentionned in 2.12.16

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#611]
### Environment
- TeXstudio: 2.12.16 (git 2.12.14-207-g4c5f931e)

### Expected behavior
"2.12.14" (as above) should be dropped in "About TeXstudio" for TXS 2.12.16.

**Comment by sunderme** [comment]
I am assuming that you are talking about the build on your computer ?
You need to pull 2.12.16 (tag).

**Comment by dbitouze** [comment]
>I am assuming that you are talking about the build on your computer ?

Indeed.

>You need to pull 2.12.16 (tag).

Well, I don't know how to do that.

**Comment by sunderme** [comment]
since I don't have to load tags, I can't check it here.
Basically you need to do something liek
`git fetch --tags`

**Comment by manudroid19** [comment]
https://stackoverflow.com/questions/4330610/switch-to-another-git-tag

**Comment by dbitouze** [comment]
@sunderme and @manudroid19 I didn't succeed.

**Comment by sunderme** [comment]
okay. I am not quite sure how you manage your git repository.
The basic task is to load the tags from the central repository (origin) on to your repository.

`git tag`  gives you all the tags which you see.
Probably 2.12.16 is missing.
In your texstudio source path, `git fetch --tags` should fetch all tags from the central repository (you can check with the first command.

If your about dialog still does not show the correct version, you probably need to run `qmake ...` again and if all fails, you need to remove `git_revision.o`

**Comment by dbitouze** [comment]
>I am not quite sure how you manage your git repository.

After I forked the TXS repository, I ran:

`cd ~/Public/Repositories && git clone git@github.com:dbitouze/texstudio.git && cd texstudio && git remote add upstream git@github.com:texstudio-org/texstudio.git && git fetch upstream`

Once done, I pull thanks to:

`cd ~/Public/Repositories/texstudio && git pull upstream master`

>Probably 2.12.16 is missing.

Indeed.

>In your texstudio source path, git fetch --tags should fetch all tags from the central repository (you can check with the first command).

OK, got it: `git fetch --tags` failed but `git fetch upstream --tags` succeed: `2.12.16` is now there.

> If your about dialog still does not show the correct version, you probably need to run qmake ... again

Despite a `sh BUILD.sh`, still `2.12.14` in "About TeXstudio".

> and if all fails, you need to remove `git_revision.o`

Indeed: everything perfect now: thanks!
