### ISSUE TITLE
Version 2.12.16 cannot run on Mac OS X 10.10

### ISSUE THREAD

**Issue by photor** [texstudio-org/texstudio#612]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior
The official website http://texstudio.sourceforge.net/ says that this version works on the platform 10.10+. So, in my understanding, it should include 10.10, shouldn't it?

### Actual behavior
However, it cannot run on my Mac OS X 10.10.5.

### How to reproduce
Any one who use Mac OS X 10.10 can reproduce.

**Comment by sunderme** [comment]
lastest qt needs osx 10.12+
We don't offer other builds, but you can use homebrew without much trouble. (brew.sh)
