### ISSUE TITLE
Quick start on Bibel-Farsi have problem

### ISSUE THREAD

**Issue by mohammadsdtmnd** [texstudio-org/texstudio#615]
Problem!
After selecting this configuration:
![image](https://user-images.githubusercontent.com/43541304/58035098-43123900-7b3d-11e9-9684-a5ada8b8c7b2.png)
It gives me this code:
\documentclass[12pt,a4paper]{report}
\usepackage[utf8]{inputenc}
\usepackage[farsi]{babel}
\author{S. M. Saadatmand}
\begin{document}
	سلام%I've only added this
\end{document}

After running:
![image](https://user-images.githubusercontent.com/43541304/58035346-cd5a9d00-7b3d-11e9-83ad-f68baa888acf.png)

I can't see the output of code.

### Environment
- TeXstudio: 2.12.14
- Qt: 5.8.0
- OS: Windows 10
- TeX distribution: miktex
### Expected behavior
It help me to start at lest simplest code.

### Actual behavior
Error (second image I've uploaded)

### How to reproduce
Check what encodings are compatible or if other packages are need to recall, make this wizard run in minimal.
And also plz check if activating extra package like "AMS math" or "graphicx" will interfere with Bible Farsi or not, maybe it need to recall Bible in last package recall or maybe these are not compatible!

**Comment by sunderme** [comment]
probably you need to follow the given advice: https://scholar.harvard.edu/dromney/arabic-latex

**Comment by mohammadsdtmnd** [comment]
Thanks for your inspiring link, But I think it didn’t explain how to use Bible for typing Farsi/Arabic.
I think Quick start feature in must provide safe code for quick start, I think this is not really “QUICK”.
Reguard.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by sunderme** [comment]
the wizard provides a quick way to get a document skeleton which you can fill. It is intended for you to reduce typing, nothing more.
We can't provide basic documents for all possible set-ups, especially if the latex installation needs to be set up accordingly as well.

**Comment by mohammadsdtmnd** [comment]
This is only missing this:
\usepackage[LAE]{fontenc}
I’ve find it on stackexchange by asking question.
I can’t understand ‘specialy if the latex installation needs to be set up’?!
You’ve added ‘inputenc’ wich determine input coding, why not adding fontenc wich is for output and is really helpfull.
This is only suggestion. I hope it help to push the improvement progress bar further.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by sunderme** [comment]
which version of txs are you using ? Mine offers a field for fontenc.

**Comment by mohammadsdtmnd** [comment]
I'm sorry but can you explain exactly what you've asked? I perceived you asked the version of TeXstudio, but I've mentioned it on the post.

**Comment by sunderme** [comment]
alright, I missed the spot where the version is mentioned, I was expecting it at the start of the issue.

**Comment by sunderme** [comment]
fontenc is offered in quick wizard since 2.12.16, so everything is present now.
