### ISSUE TITLE
Apacite 

### ISSUE THREAD

**Issue by kady42** [texstudio-org/texstudio#617]
I use BibTex and the apacite style bibliography. It works fine and when I use \cite I get the elements from my bibliography proposed. But when I want to use \citeA I get no proposals. The command works fine when I type the abbreviation in by hand. I checked Options/ autocompletion but I did not find a solution.

Thanks for the help!

**Comment by sunderme** [comment]
We don't have a cwl-file for apacite. You are welcome to set it up and provide it, see also https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions#what-are-cwl-files-good-for-and-how-do-they-work .
