### ISSUE TITLE
autocomplete includegraphics beamer with <1> fails

### ISSUE THREAD

**Issue by kendonB** [texstudio-org/texstudio#621]
Autocomplete file paths fails for `includegraphics` with `<1>`.

### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution: texlive

### Expected behavior
Autocomplete file options comes up

### Actual behavior
Autocomplete file options do not come up

### How to reproduce

- Open a beamer file as template. 
- Save it
- within a frame, type `\includegraphics<1>{|}`
- Press Ctrl-Space

**Comment by muzimuzhi** [comment]
Maybe I have found the lines relating the hard step, as mentioned in my previous comment:
https://github.com/texstudio-org/texstudio/blob/42252b2fb222b21abd6858dfb36fe0e2733f7d47/src/latexpackage.cpp#L724-L725
