### ISSUE TITLE
Mouse scrolling does not work

### ISSUE THREAD

**Issue by nityesha** [texstudio-org/texstudio#623]
Mouse scrolling is not working

### Environment
- TeXstudio: 2.12.26
- Qt: qt5
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
Mouse wheel scrolls the text up or down

### Actual behavior
mouse wheel is unresponsive, scrolling does not work.

### How to reproduce
open a TeX document, scroll down.

**Comment by sunderme** [comment]
works fine here. (win 10)
Unlikely that it is a problem of txs, looks rather like some kind of system problem

**Comment by nityesha** [comment]
Mouse scrolling is working in all other applications. The only application affected was TexStudio.
However, reverting to Version 2.12.14 solved the problem. Let's see how it is with the next version after 1.12.16.

**Comment by nityesha** [comment]
On my 4K Dell laptop screen, using version 2.12.16, the scrolling of text by using the mouse wheel or trackpad does not work, which was working fine with the previous version 2.12.14. However, the scrolling is o.k. on a lower resolution monitor.

**Comment by hisenbug** [comment]
I have the same issue as nityesha on TeXtudio version 2.12.22. My laptop configuration is the same.
Downloading version 2.12.14 indeed solved the problem, but I did not experiment with other versions.

**Comment by keygenx** [comment]
Can confirm. Win 10 4K screen. 
version 2.12.22: scroll doesn't work
version 2.12.14: scroll does work
