### ISSUE TITLE
How to setup travis-ci to build and package texstudio (especially for osx)?

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#628]
Some issue (like #616) are osx only, and it seems the active maintainers both don't have access to osx. I am using osx and willing to provide more test feedbacks under osx, but I have problem using travis-ci for my forked repo.

As what I have observed from and tested with [.travis.yml](https://github.com/texstudio-org/texstudio/blob/master/.travis.yml) and travis itself, the official texstudio project sets travis-ci to package only for version numbered tags and relates packaging to deploy together.

How can I config travis (related to my forked texstudio repo) to help me get, for example the `.dmg` file for specific commit? I am new to either travis and ci, so any help are welcome.

**Comment by sunderme** [comment]
It is also set-up to send *every* build osx build to bintray...
 - provider: bintray
    skip_cleanup: true
    file: ${TRAVIS_BUILD_DIR}/travis-ci/bintray.json
    user: sunderme
    on:
      condition: -f ${TRAVIS_BUILD_DIR}/travis-ci/bintray.json
    key:

The json file needs to generated apropriately ...

**Comment by muzimuzhi** [comment]
@sunderme 
Thanks, I have found the related bintray page (https://bintray.com/sunderme/texstudio).

**Comment by a-reisberg** [comment]
You can also push it under the release tab on github. See: https://docs.travis-ci.com/user/deployment/releases/ 

You can also check out https://github.com/a-reisberg/texstudio/tree/NoFlicker2-CI where I did it for my own testing purposes.
