### ISSUE TITLE
After zooming out, internal pdf viewer shows old page view on newly uncovered area

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#629]
### Environment
- TeXstudio: 2.12.16
- Qt: Using Qt Version 5.12.3, compiled with Qt 5.12.3 R
- OS: macOS 10.14.5
- TeX distribution: texlive 2019

### Expected behavior
Since the page is narrower after zooming out, some rectangle areas at left, right and below are newly uncovered. These areas should be in gray.

![image](https://user-images.githubusercontent.com/6376638/58742570-44563680-8458-11e9-94c1-5fff2dea2342.png)

### Actual behavior
Newly uncovered areas still show page view before zooming out. Scroll up and down will not update these areas to gray (see this screen cast: [after-zooming-out.mov.zip](https://github.com/texstudio-org/texstudio/files/3243317/after-zooming-out.mov.zip)).

![image](https://user-images.githubusercontent.com/6376638/58742854-8633ac80-8459-11e9-8258-042c2ec8e7ec.png)

### How to reproduce
Zoom out a page using zoom bar. 

### More info
Zooming out by directly selecting display scale will not produce this problem.
![image](https://user-images.githubusercontent.com/6376638/58742560-238de100-8458-11e9-8d0c-e5d282d1c662.png)

In my memory, this problem exists from at least 2.12.14, but not some older versions.

**Comment by sunderme** [comment]
works fine in linux

**Comment by a-reisberg** [comment]
I can confirm that this happens to me. I think it's a mac issue. I've meant to fix it a while back but haven't found the time yet.

**Comment by muzimuzhi** [comment]
PS: 

1. This problem does not bother me, since I seldom use zoom out. So the priority to fix this, from my personal requirement, is not high.
1. And I opened the issue only because texstudio does not work as expected on *this* tiny aspect.

**Comment by timhoffm** [comment]
In lack of better knowledge I assume this is a regression in Qt on OSX.

- Works on other platforms.
- AFAIK we have not recently modified any possibly related code.
- Would probably have been recognized earlier if this was a long-standing issue.

**Comment by Andersmb** [comment]
I experience the same thing on MacOS using texstudio 2.12.14 (git 2.12.14), Qt Version 5.11.2, compiled with Qt 5.11.2 R.

**Comment by muzimuzhi** [comment]
3.0.0beta2 on macOS cannot reproduce this problem, so I'll close it.
