### ISSUE TITLE
Wait cursor no longer appers when compiling

### ISSUE THREAD

**Issue by ondrejtichacek** [texstudio-org/texstudio#630]
### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.3, compiled with Qt 5.12.3 R
- OS: arch linux, gnome 3.32.2
- TeX distribution: texlive

### Issue
When using the Build & View button (or F5 shortcut), the wait cursor no longer appears. Before the update (in 2.12.14) the wait cursor was normally showing until the compilation was finished. Was this behavior intended?

**Comment by sunderme** [comment]
the behaviour during compilation has been changed slightly, so the missing wait cursor is a side effect from that

**Comment by manudroid19** [comment]
> 
> ### Environment
> 
>     * TeXstudio: 2.12.16
> 
>     * Qt: 5.12.3, compiled with Qt 5.12.3 R
> 
>     * OS: arch linux, gnome 3.32.2
> 
>     * TeX distribution: texlive
> 
> 
> ### Issue
> 
> When using the Build & View button (or F5 shortcut), the wait cursor no longer appears. Before the update (in 2.12.14) the wait cursor was normally showing until the compilation was finished. Was this behavior intended?

Also in a future update, the compile buttons will be grey during compilation, so the user can know easily when the program is compilating.
