### ISSUE TITLE
Align columns hangs with formatting in first column

### ISSUE THREAD

**Issue by hudcap** [texstudio-org/texstudio#632]
Originally posted on Sourceforge [here](https://sourceforge.net/p/texstudio/bugs/2438/) before realizing that this looks like the correct place to post.

### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
Running LaTeX -> Manipulate Tables -> Align Columns when there is formatting in any of the cells in the first column (I tried \textbf{} and \textit{}) should align all the columns.

### Actual behavior
TeXStudio hangs

### How to reproduce
MWE:
    
    \begin{tabular}{lc}
        foo & bar \\
        \textbf{lorem} & ipsum
    \end{tabular}

**Comment by sunderme** [comment]
works fine on linux

**Comment by hudcap** [comment]
This works fine:
    
    \begin{tabular}{lc}
        foo & bar \\
        {\textbf{lorem}} & ipsum
    \end{tabular}
    
which leads me to believe it has something to do with the leading backslash.

**Comment by sunderme** [comment]
are we really talking about an empty document with just the MWE as text ? Did you change any options , especially concerning completion files ?

**Comment by hudcap** [comment]
Thanks for that pointer :)
I just looked at Special Commands under Table Autoformatting and found that I had left a trailing comma there. Now that I removed it, it works.
Sorry about that.
