### ISSUE TITLE
Opening document via symlink not working

### ISSUE THREAD

**Issue by johanzietsman-em** [texstudio-org/texstudio#635]
I created a symbolic link of my ``~/doc/document.tex`` file in another directory, ``~/shortcuts/doc-link``. When I click on the ``doc-link`` TeXstudio does not resolve the link to the original file and its location. When I try to build the document it does not work, since TeXstudio looks for files in ``~/shortcuts`` rather than in ``~/doc``.

### Environment
- TeXstudio: 2.12.6 
- Qt: 5.9.5
- OS: Linux (Kubuntu 18.04)
- TeX distribution: texlive

### Expected behavior
I expect TeXstudio to resolve the symbolic link, and open the actual file ``/home/johan/doc/document.tex``, and not the symbolic link.

### Actual behavior
TeXstudio does not opens the symbolic link ``~/shortcuts/doc-link``, expecting the document files to be located in ``~/shortcuts`` rather than in ``~/doc``.

### How to reproduce
Create a LaTex document at ``~/doc/document.tex``. Link another file to it through an ``\input`` statement. E.g. create the file ``~/doc/part.tex``, and incorporate the statement ``\input{part}`` into ``~/doc/document.tex``.

Create a symbolic link to ``~/doc/document.tex`` in ``~/shortcuts/doc-link``. Double-click on ``~/shortcuts/doc-link``, and press F5 to build the document. It should complain that it cannot find ``part.tex``, since it is looking for it in ``~/shortcuts``.

**Comment by aubreyz** [comment]
I'm on Windows not Linux, but I would not expect symbolic links to work the way you are expecting them to work. The symbolic link in shortcuts  should think it exists in shortcuts. It absolutely should not resolve to anywhere else. 

Apart from that, if there is an issue (there is not one I can see) it would be a LaTex issue not a Texstudio one (unless you are saying that compilation of document.tex in shortcuts works fine when executed outside of texstudio). 

Symbolic links are supposed to be transparent to users -- the links appear as normal files or directories, and refer to files exactly as they would do. Therefore it is behaving as expected.

**Comment by sunderme** [comment]
I agree, symlinks on linux are handled as files, there is no explizit resolution of the path

**Comment by timhoffm** [comment]
The requested behavior is also not present in latex itself. When run on a symlink, it creates log and other files next to the symlink and with the symlink filename.

I don't see why TeXstudio should behave differently.
