### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by wujastyk** [texstudio-org/texstudio#636]
### Environment
- TeXstudio:
TeXstudio 2.12.16 (git n/a)
Using Qt Version 5.9.5, compiled with Qt 5.9.5 R
from PPA

- OS: Linux Mint 19.5 
- TeX distribution: TeXLive 2019

Just crash on trying to compile.

Backtrace file:

SIGSEGV (TXS-Version  R )
[bt] texstudio(_ZN12SimulatedCPU13set_from_realEv+0) [0x55e907fdce70]

**Comment by sunderme** [comment]
Please compile txs on your machine with debug and run txs in a debugger. (See wiki)
The one line backtrace does not give any information about the crash and unless that there is at least a reproducible test case, we can do anything.

**Comment by wujastyk** [comment]
Thanks. At present I have no time, but I'll do this if the problem persists
later in the summer
