### ISSUE TITLE
Changelog for new releases

### ISSUE THREAD

**Issue by hannes101** [texstudio-org/texstudio#638]
I would like to ask if it's possible to create a changelog for new releases as has been done before. 
As a downstream maintainer it is great to directly get a glimpse of what's new and what might have been fixed in the new release.
Previously the changelogs were at:
https://raw.githubusercontent.com/texstudio-org/texstudio/1551ba13b224a38229d1049983ac572710d352cd/utilities/manual/CHANGELOG.txt
But for the 2.12.16 release I couldn't find one. I also couldn't find a commit history between the two latest releases.

Thanks

**Comment by dbitouze** [comment]
https://github.com/texstudio-org/texstudio/blob/431681643e11f1f28630e64e51fd627430fa0796/utilities/manual/CHANGELOG.txt#L1-L6

**Comment by hannes101** [comment]
Thanks, that's what I meant.

**Comment by muzimuzhi** [comment]
> I also couldn't find a commit history between the two latest releases.

@hannes101 
This link shows a list of commits between releases 2.12.14 and 2.12.16: https://github.com/texstudio-org/texstudio/compare/2.12.14...2.12.16

Also, this GitHub Help article introduces how to [Comparing commits across time](https://help.github.com/en/articles/comparing-commits-across-time#comparing-tags).
