### ISSUE TITLE
Ctrl+Space for completion on OS X does not work

### ISSUE THREAD

**Issue by KarlMagnusLarsson** [texstudio-org/texstudio#640]
### Environment
- TeXstudio 2.12.16 (git 2.12.16-22-g639c36d2)
- Qt: Using Qt Version 5.12.3, compiled with Qt 5.12.3 R
- OS: 10.13.6
- TeX distribution: MacTex 2019

### Expected behavior
ctrl+space should display auto-completion window. 

### Actual behavior
Nothing happens when ctrl+space is pressed.
(ctrl+cmd is mapped to trigger osx Spotlight search in my imac)

### How to reproduce
1. Turn of automatic start of completion: Preferences->Completion->untick "Automatically start completer when typing LaTex commands". 
2. Start editor and enter:
```
\documentclass{article}
\begin{document}
\begin{equation}
\fra
\end{equation}
\end{document}
```
3: Go to \fra line and press ctrl+space.
4: nothing happens. 
5. A list containing \frac{num}{den} (and other completions) should gave appeared.

in commit 136a925480e " use Ctrl+Space for completion on OS X (was Cmd+Space which conflicts with Spotlight search)" both Qt::META + Qt::Key_Space and Qt::CTRL + Qt::Key_Space are mapped to trigger auto-complete. In https://doc.qt.io/qt-5/qkeysequence.html, it is stated:
Note: On macOS, references to "Ctrl", Qt::CTRL, Qt::Key_Control and Qt::ControlModifier correspond to the Command keys on the Macintosh keyboard, and references to "Meta", Qt::META, Qt::Key_Meta and Qt::MetaModifier correspond to the Control keys. Developers on macOS can use the same shortcut descriptions across all platforms, and their applications will automatically work as expected on macOS.

So commit 136a925480e should work, but it does not. At least not for me. If I press crtl+space then nothing happens. If I press cmd+space I trigger Spotlight search (original issue). 

I am not sure what is going on here. Perhaps there are bugs in QT on OSX. I have not investigated that.

If I patch and map (Qt::SHIFT + Qt::META + Qt::Key_Space) to auto-complete, then I can trigger auto-complete using "shift"+"crtl"+"space" on my Imac.

```
diff --git a/src/texstudio.cpp b/src/texstudio.cpp
index f85c57df..b628e6d6 100644
--- a/src/texstudio.cpp
+++ b/src/texstudio.cpp
@@ -968,7 +968,7 @@ void Texstudio::setupMenus()
        newManagedAction(submenu, "findMissingBracket", tr("Find Mismatch"), SLOT(findMissingBracket()), QKeySequence(Qt::SHIFT + Qt::CTRL + Qt::Key_P, Qt::Key_M));
 
        submenu = newManagedMenu(menu, "complete", tr("Complete"));
-       newManagedAction(submenu, "normal", tr("Normal"), SLOT(normalCompletion()), MAC_OTHER(Qt::META + Qt::Key_Space, Qt::CTRL + Qt::Key_Space));
+    newManagedAction(submenu, "normal", tr("Normal"), SLOT(normalCompletion()), MAC_OTHER(Qt::SHIFT + Qt::META + Qt::Key_Space, Qt::CTRL + Qt::Key_Space));
        newManagedAction(submenu, "environment", tr("\\begin{ Completion"), SLOT(insertEnvironmentCompletion()), Qt::CTRL + Qt::ALT + Qt::Key_Space);
        newManagedAction(submenu, "text", tr("Normal Text"), SLOT(insertTextCompletion()), Qt::SHIFT + Qt::ALT + Qt::Key_Space);
        newManagedAction(submenu, "closeEnvironment", tr("Close latest open environment"), SLOT(closeEnvironment()), Qt::ALT + Qt::Key_Return);

```

**Comment by sunderme** [comment]
No need to patch anything. You can set the bindkeys in the options...

**Comment by KarlMagnusLarsson** [comment]
OK, thanks for pointing out the options. I understand I can define my own shortcut there.

However, my report what related to the "official" shortcut to start completion. On Linux I can trigger manual completion by "ctrl"+"space". This is also the helper text in preferences -> completion -> "Automatically start completer, when you move the mouse close to that tick mark: 

Help text:
"Starts the completer as soon as '\' is typed. Alternatively the completer can always be started manually by Ctrl+space"

But on OSX "ctrl"+"space" does nothing.

**Comment by muzimuzhi** [comment]
@KarlMagnusLarsson 
It works fine on my 10.14.5 macOS, in texstudio 2.12.16.

 - Does the completer pop up when you click the menu item `Idefix -> Complete -> Normal`?
 - Have you set some system-wide shortcuts relating `ctrl + space`?

**Comment by KarlMagnusLarsson** [comment]
@muzimuzhi,

Thank you for checking this. It helped.

Idefix -> Complete -> Normal: Works for me.

Have you set some system-wide shortcuts relating ctrl + space?: Yes, I had. I missed that. 

I did have a pre-assigned ctrl+space keyboard shortcut, i.e. a default shortcut om my 2010 Imac 10.13.6. If I remove that system-wide shortcut in OSX system-settings, then Texstudio crtl + space works. 

Interestingly my 2013 Macbook Air 10.14.1 did NOT have this system-wide shortcut as a default and Texstudio ctrl + space worked fine (the pre-assigned ctrl+space keyboard shortcut was/is related to input source/language selection).

It is clearly only related to OSX system settings. Again, on one of my systems ctrl+space was pre-assigned default, on another system it was not. I should have double checked regardless.

I think this issue can be closed.
