### ISSUE TITLE
Find al uppercase letters that are not the beginning of a sentence

### ISSUE THREAD

**Issue by JamesLarkinWhite** [texstudio-org/texstudio#641]
Dear all,
I need to find al uppercase letters that are not the beginning of a sentence.
they should just be marked for now, and i would convert them by hand if needed.

I have no clue where to start unfortunately.

**Comment by foreachthing** [comment]
This will **not** find a word starting in uppercase ... but a word _containing_ an (or more) uppercase letter.
Use this string in the search field:
`\w[A-Z]+\w*`
Then click these buttons next to the search field:
[cC] [Reg] [high]
That's  it!
![image](https://user-images.githubusercontent.com/10420187/59655867-17b25680-919c-11e9-9819-04fd9495a4d3.png)

**Comment by muzimuzhi** [comment]
@foreachthing 
`\w[A-Z]+\w*` will mistakenly match words like `aAa` and part-of-words like `cDef` in `abcDef`.

![image](https://user-images.githubusercontent.com/6376638/60317009-b9595500-999f-11e9-87db-221973abc9aa.png)

`\b[A-Z]\w*\b` or even `\b[A-Z][a-zA-Z]+\b` would be nicer.

**Comment by JamesLarkinWhite** [comment]
Thank you very much! Is it possible to extend this to find all words that end on the letter "s"?

**Comment by foreachthing** [comment]
https://regex101.com/r/AZeiSu/1
