### ISSUE TITLE
! LaTeX Error: File `moderncv.cls' not found.

### ISSUE THREAD

**Issue by Twoflower2** [texstudio-org/texstudio#642]
### Environment
- TeXstudio: 2.10.12
- Qt: 5.9.7
- OS: Linux opensuse leap 15.1 
- TeX distribution:
PDFLATEX: pdflatex -version
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017/TeX Live for SUSE Linux)
kpathsea version 6.2.3

### Expected behavior
no error

### Actual behavior
! LaTeX Error: File `moderncv.cls' not found.

### How to reproduce
Use moderncv template and compile

**Comment by dbitouze** [comment]
Not a TXS error but more likely only a partial TeX Live install. Maybe `texlive-scheme-full` package will be enough.

**Comment by Twoflower2** [comment]
**texlive-moderncv** installation works.
