### ISSUE TITLE
Caps lock to backslash, fulfill option in textstudio won't react

### ISSUE THREAD

**Issue by Prototypemax** [texstudio-org/texstudio#645]
Hello there,
I was installing karabiner 12.5.0 on my mac 10.14.5 to get easier access to backslash on my german keyboard. Before I had to use shift+alt+7 to get backslash. 
With this [complex modification](https://pqrs.org/osx/karabiner/complex_modifications/#caps_lock_german ) I get backslash on my caps lock key, which I was just not using before, so great. 

I did all of that to work more easy on texstudio 2.12.14. After some time working with the caps lock key I realized, that the auto-fulfill option of texstudio does not show up whenever I use backslash via the caps lock key. But when I use the shift-alt-7 backslash the pop-up window for autofullfill shows up again. 

I checked had a brief look in the texstudio references, but couldn't finde something so far. I think texstudio expects me to type shift-alt-7 for the pop-up window, but how could I get the pop-up window with my backslash on caps lock? I would appreciate any help :)!

**Comment by sunderme** [comment]
txs uses a key-press to active completion, not the insertion of the character '\'
see also https://github.com/texstudio-org/texstudio/wiki/Scripts#insert-backslash-and-start-completion-with-

**Comment by Prototypemax** [comment]
Thanks for your answer. Can you please tell me where i have to insert that script?
And do you have an idea how i have to modify the commands suggested in your link to use my caps-lock-backslash?

**Comment by sunderme** [comment]
I don't know how to solve your problem.
You could follow the macro by assigning a different character which is replaced by the macro.
You could also use "\" as a trigger, though I am not sure that it lead to unwanted side-effects.

**Comment by Prototypemax** [comment]
Hi, I quit using karabiner, even though it is a very nice program. Instead I now use the recommended macro with # as a trigger, hopefully i don't need the symbol somewhere else :) Should I close this question?

**Comment by sunderme** [comment]
Alright. I hope it works well.
I have closed the issue.
