### ISSUE TITLE
.cwl not used, siunitx does not know separate-uncertainty

### ISSUE THREAD

**Issue by jonasstein** [texstudio-org/texstudio#647]
### Environment
- TeXstudio 2.12.16 (git n/a)
- Using Qt Version 5.12.3, compiled with Qt 5.12.3 R
- OS: Gentoo Linux
- TeX distribution: texlive

### Actual behavior
`separate-uncertainty` is highlighted like an `unknown command`.

![image](https://user-images.githubusercontent.com/298682/60011773-d4b02180-967a-11e9-9736-910e6a1bffdd.png)

The completion file seems to define it properly in
https://github.com/texstudio-org/texstudio/blob/master/completion/siunitx.cwl#L194

The completion files are activated in the current configuration.
![image](https://user-images.githubusercontent.com/298682/60011991-396b7c00-967b-11e9-9549-167384077fa7.png)

I try to track the bug on my system. I could not find the place, where the `completion/siunitx.cwl` file was installed on my local system. Where should it be?

**Comment by timhoffm** [comment]
The default completions are bundled with the resource mechanism and compiled into the binary.

This was just added (https://github.com/texstudio-org/texstudio/commit/bd3514052877b799b827a4289429600ae37fe356#diff-074c200e53f072e37de646dc02b2bff2), so it will not be in your defaults. You can download the above file and place it in your  settings `completion/user` folder (http://texstudio.sourceforge.net/manual/current/usermanual_en.html#CWLDESCRIPTION) or build a new binary from master.

**Comment by jonasstein** [comment]
Thank you.
