### ISSUE TITLE
Magnifier switched on automatically when switching from editor to viewer

### ISSUE THREAD

**Issue by jingjingz** [texstudio-org/texstudio#649]
### Environment
- TeXstudio:  TeXstudio 2.12.16 (git 2.12.16)
- Qt:  Qt Version 5.12.3, compiled with Qt 5.12.3 R
- OS:  Mac Mojave 10.14.5 
- TeX distribution: 

### Expected behavior
Magnifier should not be activated without an extra clicking on the article in viewer.
Previous versions would not activate magnifier unexpectedly.

### Actual behavior
Magnifier of the viewer activated whenever switching from editor back to viewer.

### How to reproduce
Put the viewer window in pop-out mode as a separate window. Switch to focus on editor by clicking editor interface or "Go to source" in viewer. Then switch back to viewer by clicking anywhere on the article in viewer. The magnifier will show up automatically, which is causing the program to lag and is annoying.

**Comment by jingjingz** [comment]
can someone please respond thanks.

**Comment by sunderme** [comment]
hmmm, I am not sure what you expect.
If you click into a text editor, you also expect the cursor to appear there, even if it was not front before.
You either not click into the image or you can activate the "scroll" mode (hand) 
For now, I don't see a reason to change behavior...
