### ISSUE TITLE
texstudio crashes on Fedora 26, Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by mario6097** [texstudio-org/texstudio#65]
- Texstudio: texstudio-2.12.6-1.fc26.src.rpm
- Qt: ???
- OS: Fedora 26
- Tex distribution: texlive

texstudio crashes on Fedora 26, with a Segmentation fault (core dumped);
see  https://forums.fedoraforum.org/showthread.php?317615-Texstudio-on-F26-I-get-a-Segmentation-fault-(core-dumped)&p=1804872#post1804872

help is welcome. 
thanks  mario

**Comment by sunderme** [comment]
without a reproducible test case, I don‘t see any possibility to,solve this

**Comment by mario6097** [comment]
I just installed on Fedora 26 (dnf install texstudio), and try to launch from prompt (>texstudio). It crashes immediately. Which reproducible test case do you need? m.

**Comment by sunderme** [comment]
you could remove .config/texstudio/texstudio.ini and try again
otherwise the only approach would be debuging with a debug build and gdb/qtcreator.
txs does not crash on its own during start-up

**Comment by mario6097** [comment]
removing .ini file fixes it. THANKS! Otherwise it would have been too difficult for me.
