### ISSUE TITLE
Compound PATH on \input

### ISSUE THREAD

**Issue by Allmoz** [texstudio-org/texstudio#650]
Hi,
This works on LaTeX:

\def  \commonPath {../../common/}
\input{\commonPath common.tex}

But TeXstudio tries to load into the structure as "\commonPath common.tex".

This Is useful cause  "\commonPath" will be now defined in common.tex so it can load other files relative to himself.

Like:
\input{\commonPath packages.tex}
\input{\commonPath config.tex}
\input{\commonPath macros/headers.tex}
\input{\commonPath general/styles.tex}

It would be really nice if it can be added.

Keep The Great Work!

**Comment by timhoffm** [comment]
This is currently not possible. TeXstudio is not a full LaTeX interpreter; instead we have only heuristics what a command means. For the case of \input, we just assume that the parameter is the value, we are not trying to parse it. That would come with a number of additional problems and I don't think we want to go down this road.

**Comment by Allmoz** [comment]
What about getting the info from the complication files?( kind like the 2 times run to fix the forward references when there is no .aux yet)

For example  it could try to guess the real path from the fls when it fails to load it to the structure?

or maybe there are more useful ones.

:) Well just an idea, thanks for the prompt reply!

**Comment by timhoffm** [comment]
Compilation files are a rabbit hole themselves. We are not using them. One of the major issues is that they can be non-existent or outdated. That would mean that features based on this would only work sometimes; and that is a sure way to confuse users.

**Comment by timhoffm** [comment]
I would even argue that `\input{\commonPath packages.tex}` is an anti-pattern.

- `\commonPath` creates an indirection, which makes it more difficult for the user to see what path is actually used.
- Changing the path structure happens only rarely, so the benefit of a having just to change one place is small.
- It's still straight forward to seach/replace for `../../common/` or `\input{../../common/`.

Closing as too sophisticated. @sunderme feel free to reopen and implement this in case you feel there's a real need for this.
