### ISSUE TITLE
Missing textstudio.ini on Mac

### ISSUE THREAD

**Issue by gandarez** [texstudio-org/texstudio#651]
### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.3
- OS: macOS Mojave

I just downloaded the latest version `2.12.16` and there's no `texstudio.ini`.

**Comment by sunderme** [comment]
texstudio.ini is not part of the installer. txs generates it automatically with default values if it is not present ,i.e. at the end of the first run.
