### ISSUE TITLE
Does txs install texlive?

### ISSUE THREAD

**Issue by tmelorc** [texstudio-org/texstudio#652]
### Environment
- TeXstudio: TeXstudio 2.12.16
- Qt: Qt Versão 5.9.5
- OS: Ubuntu 18.04
- TeX distribution: texlive

I'd like to know if the texstudio_2.12.16-1+2.1_amd64.deb file from the website install quietly texlive from repository?

I've just installed texlive 2019 from the iso file and after, texstudio. But now I suspect that txs installed old version of texlive, since there are executable files from texlive 2017.

If this was the case, it was not a good idea. 

Regards.

**Comment by sunderme** [comment]
txs does not install texlive
probably you have bith on your system and he Path is not set correctly

**Comment by tmelorc** [comment]
Thanks for attention.
