### ISSUE TITLE
Unicode typing in editor is not proper

### ISSUE THREAD

**Issue by lRadha** [texstudio-org/texstudio#653]
### Environment
- TeXstudio: 

### Actual behavior
Typing Unicode characters in the editor should be proper as they are typed, rather shows some glitches and mixes them up.

### How to reproduce
Try to write something in Hindi or Telugu in Unicode.

**Comment by muzimuzhi** [comment]
Can you provide more specific info, such as screenshot, to show how the "glitches and mixed up" looks like, and how dose it look like (for example, in other work-fine editor)?

**Comment by lRadha** [comment]
Today, updated the TeXStudio. It's working like a charm. Thanks
