### ISSUE TITLE
How dows TeXstudio know the path of pdf file

### ISSUE THREAD

**Issue by OsbertWang** [texstudio-org/texstudio#655]
### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution: texlive 2019

### Expected behavior
Thank you for the excellent Special Chars.
I use them to define the command
```dde:///"SumatraPDF.exe":SUMATRA/control/[ForwardSearch("?am.pdf","?c:am.tex",@,0,0,1)]```
to use the SumatraPDF viewer.
Now, I wonder that how to know the value of `--outdir` automatically, then I can update the command.

### Actual behavior
Now I can manully to give the path of pdf file.
For example, when I compile with `--outdir=temp`, I can define the command like
```dde:///"SumatraPDF.exe":SUMATRA/control/[ForwardSearch("?a)temp\?m.pdf","?c:a)temp\?m.tex",@,0,0,1)]```
But if I change the value of `--outdir` or delete it, I have to modify the command by myself.

So please give me some tips about how to know the path of pdf files.
Thank you very much.

**Comment by sunderme** [comment]
I don't think that txs can offer an easy solution. If you manipulate the commands to write the pdf to somewhere else but the working directory, txs can't know about it unless you tell it about it explicitely.
The internal viewer uses search paths (see options) which mitigate the issue, but that does not work with external programs...

**Comment by OsbertWang** [comment]
OK. I will tell txs the path explicitely. Thank you for answering my question.
