### ISSUE TITLE
inconsistent text selection by dragging beyond the editor

### ISSUE THREAD

**Issue by mattmajic** [texstudio-org/texstudio#656]
When selecting text in the editor and dragging above or below the editor window to select large areas of text, the editor does not scroll smoothly all the way to the end of the document.

### Environment
TeXstudio 2.12.16 (git 2.12.16)
Using Qt Version 5.12.1, compiled with Qt 5.12.1 R

- OS -- Windows 10
- TeX distribution: miktex

### Expected behavior
The editor scrolls smoothly, with the highlighted region of text growing as it scrolls. This happens all the way to one end of the document, or until the cursor is moved back over the editor window.

### Actual behavior
the editor scrolls for a while, but then stops, and then about 1-2 secs later, jumps a few more lines. If the cursor is moved, this will happen again.

### How to reproduce
Create a document with a reasonably large amount of text, and attempt to highlight the text from some point to one end of the document, by clicking the cursor at some word in the editor and dragging below or above the editor window.

**Comment by timhoffm** [comment]
Actually, the scrolling happens only as long as the mouse moves. When you drag and then pause the mouse outside the editor, the scrolling stops. Moving the mouse further continues the scrolling.

As a workaround, you can continue to move the mouse slightly outside the editor region.

**Comment by mattmajic** [comment]
Yes this is true. But can you not reproduce the jump after a 1-2 sec delay after halting the cursor?

**Comment by timhoffm** [comment]
No. Scrolling is stopped as long as the mouse does not move.

**Comment by mattmajic** [comment]
On windows? 
I can get the desired result on the same tex document using texmaker.

**Comment by timhoffm** [comment]
Yes. Windows.

**Comment by sunderme** [comment]
I don't see any point in trying to fix anything

**Comment by mattmajic** [comment]
you cant reproduce this? This happened on a fresh install of TeXstudio
2.12.16 and still happens.

**Comment by sunderme** [comment]
I see the behavior as described by Tim (scrolling occurs only when the mouse is moved outside the text window)
The better approach is any way to set the cursor , scroll, shift-click to set the second limit.

**Comment by axkibe** [comment]
Just got a complaint about exactly this. Hmmm...

I know, I usually select using the scroll wheel either, but for example KWrite does smooth scrolling in this case (albeit current version with different speed upside and downside, something I recently got a patch applied for)

Would you need timer events for this?

**Comment by axkibe** [comment]
Or asked differently, in case I really want this fixed regardless selecting with shift is considered better, would you accept a patch for this?

**Comment by axkibe** [comment]
PS: texmaker does this correctly :(

**Comment by timhoffm** [comment]
I think the standard behavior in applications is to continue scrolling. So, yes IMHO a patch is welcome.
