### ISSUE TITLE
Long package error text is wrongly striped in "Issues panel"

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#658]
### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.3
- OS: macOS 10.14.5
- TeX distribution: mactex 2019

### Actual behavior
Middle lines of long package error text is missing in "Issues panel"

### How to reproduce
1. Compile this `tex` file
```latex
\documentclass{article}
\begin{document}
\PackageError{x-pkg}{Lorem ipsum dolor sit amet, consectetur adipiscing elit,
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
adminim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
exeacommodo consequat}{}
\end{document}
```

2. Then we can find full package error text in `log` file, and a shorten text in "Issues panel"

![image](https://user-images.githubusercontent.com/6376638/60773791-55702280-a13d-11e9-8871-06783a98643e.png)

3. Observe that the contents of shorten text is composed of:
```latex
% i) fist line of error message in full version, framed in blue in screenshot
Package x-pkg Error: Lorem ipsum dolor sit amet, consectetur adipiscing elit,

% ii) last line of error messge, framed in green
odo consequat. 

% iii) text after source line number, framed in yellow
exeacommodo consequat}{}
```

4. That observation shows that middle lines of full version is missing in shorten version, and this may add difficulty to understanding shorten text. For example, this is a long error message produced by `tikz`
![image](https://user-images.githubusercontent.com/6376638/60773659-37092780-a13b-11e9-9efb-3aaea0194b4a.png)

### Expected behavior
The Message column of Issues panel can show
 *  first line of error message + [more letters from middle lines up to a max count of letters + ] "..." + text after source line number

**Comment by sunderme** [comment]
@timhoffm  do you want to handle this ?

**Comment by timhoffm** [comment]
Yeah. *Should* be handled. Another of the endless log-parsing issues. But hopefully this is easier to fix. At least no parenthesis matching is involved.

**Comment by muzimuzhi** [comment]
Not reproducible in 3.0.3. Guess it has been fixed when resolving other issue(s). I will close this issue.

**Comment by sunderme** [comment]
From the code I would assume that the behaviour is intentional.
It add the log line after the line number as usually the offending command is shown there.

So, I am not 100% comfortable to change that because there may be other situation where that info is useful ?
