### ISSUE TITLE
Make "Hard Line Wrap after max. Characters" be the default of "Line Wrapping"

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#66]
IMHO, the default option of Configure TeXstudio → Adv. Editor → Line Wrapping should be "Hard Line Wrap after max. Characters" with e.g. "80" for "Maximal Characters:".

Indeed, otherwise, the LaTeX source code edited with TXS contains very long lines that make errors uneasy to locate.

**Comment by sunderme** [comment]
short answer: no

long answer: we have had so many (stupid) bug reports because people want „hard line wrap“ but still want it to react like soft line wrap when deleting words
I have been working with soft line wrap for many years and there is no fundamental problem.
error locating should be correct by the txs mechanism and it should work fine.
for sure, if you never press enter once in a while, the thing is a mess but the user is supposed to be able to learn. and if the user prefers hard line wrap, let him choose it

**Comment by dbitouze** [comment]
@sunderme Could you elaborate:

>bug reports because people want „hard line wrap“ but still want it to react like soft line wrap when deleting words

**Comment by sunderme** [comment]
some time ago on SF.

**Comment by sunderme** [comment]
but that is not the point. The point is, why do you want to burden everybody with a default behaviour which absolutely uncommon in any editor ??? to make the story short, I will not change the default. (and anybody can adapt it to its liking, so no harm here)

**Comment by dbitouze** [comment]
>a default behaviour which absolutely uncommon in any editor

Probably, but that makes life more difficult for LaTeX. 

And I observed many users who "never press enter once in a while, the thing [being] a mess" and who got into troubles when errors arose.

Moreover, pressing enter once in a while has more to do with hazard than with exact science :)

**Comment by timhoffm** [comment]
I agree with @sunderme.

Soft wrapping is the better choice in many cases and should remain the default.

A naive hard wrapping as we have does create troubles itself.

**Comment by dbitouze** [comment]
>A naive hard wrapping as we have does create troubles itself.

I see... What about a non naive hard wrapping? ;)

**Comment by timhoffm** [comment]
If someone wants to work on a PR, that would be welcome. I think none of the core developers has the time and motivation to work on this (we're all using soft wrapping).

**Comment by noppelmax** [comment]
Is it possible set the linewrap option per file? Like `% !TeX encoding = utf8` ?

**Comment by sunderme** [comment]
No

**Comment by octaeder** [comment]
I thought Hard Line Wrap after... would do real line breaks. But currently it doesn't. Am I wrong or should I open an issue?
![grafik](https://user-images.githubusercontent.com/102688820/162975820-40ec1f4d-a3f1-4a9d-b3c4-75a4c1e00545.png)
![grafik](https://user-images.githubusercontent.com/102688820/162976130-df055b21-8c15-40f3-bad4-728e60ae5d04.png)

Win10 miktex, current dev version 4.2.3 Qt6 (images above) and 4.2.2 Qt5 (this one doesn't show the vertical line).

**Comment by RemiDav** [comment]
> I thought Hard Line Wrap after... would do real line breaks. But currently it doesn't. Am I wrong or should I open an issue?

I think it splits the lines when you press save (the arrows should become numbers).
