### ISSUE TITLE
TeXstudio gets confused whith multiple log/PDF files

### ISSUE THREAD

**Issue by ysalmon** [texstudio-org/texstudio#661]
### Environment
- TeXstudio: 2.12.16
- Qt: 5.9.5 R
- OS: Kubuntu 18.04
- TeX distribution: texlive 2019

### Actual behavior
TXS has a nice feature to specify additional path for searching log files. This is useful when one compiles with a specific output directory and generally this works well.

However, I am dealing with a collaborative project where we have a makefile that does not make use of outputdir. So depending on whether I run the makefile (to compile all documents and assemble them) or click on the Compile button in TXS (to preview the document I am working on), the log files does not get written at the same place.

The difficulty is that when a log file is present in the source directory, TXS considers it to be "the" log file, even when it is stale because I made changes to the tex file and compiled to my output dir. This leads me to not being able to spot errors I would introduce in the code, because the resulting PDF might still look globally sane, and the error is buried in the log file that TXS does not display or care about.

EDIT : think about it, the same problem probably arises when displaying the PDF file, which would explain why I do not see defects either in the preview.

### Proposed behavior
I understand this might be tricky, but I think that when the "additional path for log/PDF file"-feature is activated, TXS should look for log files in every place (including the default) and display the most recent log/PDF, instead of giving precedence to the file in the default location.

**Comment by sunderme** [comment]
fixed with PR
