### ISSUE TITLE
Macro is not loading automatically

### ISSUE THREAD

**Issue by gandarez** [texstudio-org/texstudio#663]
### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.3
- OS: macOS Mojave

Creating a `txsMacro` file manually inside `macro` folder doesn't make texstudio to load it automatically.

<img width="139" alt="Screen Shot 2019-07-14 at 19 04 24" src="https://user-images.githubusercontent.com/782854/61189888-3a843d80-a66a-11e9-89c7-c57ff69f68b3.png">
<img width="145" alt="Screen Shot 2019-07-14 at 19 05 03" src="https://user-images.githubusercontent.com/782854/61189896-4ec83a80-a66a-11e9-9ac6-7b6e5cb323bd.png">

**Comment by sunderme** [comment]
why do you assume that a macro with any name is loaded from that directory ?
All other macros are named Macro_%d.txs (%d integer from 0..). You can import any macro and the automatic storage uses a name as described above. (FYI txs stops loading macros if one number is missing, i.e. Macro_0.txsMacro Macro_2.txsMacro, then only Macro_0.txsMacro is loaded)

**Comment by gandarez** [comment]
Thanks for the explanation. Didn't find any documentation regarding this. Now is working :)
