### ISSUE TITLE
[Feature request] Dark Mode integration

### ISSUE THREAD

**Issue by kbdsaga** [texstudio-org/texstudio#668]
There's a huge amount of work that has been done to create a functioning dark mode for TeXstudio, which looks great and works well on windows environements but is a bit more finicky on Unix.  Integrating the already extant dark modes to TeXStudio would be wonderful, it really us a powerful piece of software but the aesthetics have not aged well.

**Comment by timhoffm** [comment]
Getting the dark mode to integrate flawlessly with every aspect of TXS is a major effort. We cannot add a half-baked solution and don't have the capacity to work on fixing this.

See also https://github.com/texstudio-org/texstudio/issues/45#issuecomment-368301279.

**Comment by sunderme** [comment]
more or less done
