### ISSUE TITLE
Option to disable scroll wrapping in PDF viewer

### ISSUE THREAD

**Issue by imciner2** [texstudio-org/texstudio#669]
The internal PDF viewer wraps the scrolling from the end of the PDF file to the start of the PDF file. This is very inconvenient for trying to go to the end of the document, since you cannot just continuously scroll and have it stop at the end. There should ideally be an option to disable this behavior and force the scrolling to stop at the end of the file.

### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.4
- OS: Linux Fedora 30
- TeX distribution: Texlive

### Expected behavior

The wrapping of the scroll should be user-configurable.

### Actual behavior

The PDF viewer always wraps the scroll around from the end to the beginning.

### How to reproduce

Hold down Page Down to go to the end of the document, and it will just continuously cycle through the document (never stopping).

**Comment by benibela** [comment]
>The internal PDF viewer wraps the scrolling from the end of the PDF file to the start of the PDF file. 

That is probably just a bug, and not something that was implemented on purpose
