### ISSUE TITLE
moving between curly placeholders

### ISSUE THREAD

**Issue by mattmajic** [texstudio-org/texstudio#674]
- TeXstudio:  2.12.16
- OS:  Windows 10
- TeX distribution: miktex

### Expected behavior
when pressing ctrl+right to move the cursor from the first to the second placeholder in \frac{}{},
the cursor should end up in the second place holder.

### Actual behavior
The cursor moves to one space before the second placeholder. Moving back one placeholder - the cursor moves to the same place: one space before the second placeholder.

### How to reproduce
Untick "Insert Arguments" in completion settings. Type \frac{}{} and place cursor in first place holder and press ctrl right (or whatever the shortcut for "Next placeholder or one word right" is set to).

**Comment by sunderme** [comment]
could you draw a | to indicate where the cursor is and should be ? What do you describe a "place holder" ? The braces of the argument ?

**Comment by mattmajic** [comment]
Moving ideally from \frac{|}{} (presses ctrl right) to \frac{}{|}. But instead it moves to \frac{}{}| . 
By place holder I mean the braces.

**Comment by sunderme** [comment]
if there are no placeholders, ctrl-right jumps to next word {}{} is considered as a word (default behavior which is consistent with other editors)
In your case, activate "insert arguments" and the cursor jumps to the placeholders as you expect.

**Comment by mattmajic** [comment]
Is it possible to have placeholders without pre set words in them (eg. when creating a fraction to omit the num and den that appear in the curly braces?

**Comment by sunderme** [comment]
what is wrong with num/den ? The placeholder needs to contain characters ...
And since the complete placeholder is selected when you change to it (ctrl+right), all the text is replaced with what you want it to ...

**Comment by mattmajic** [comment]
it can be annyoing if you edit for example the numerator and want to come
back and do the denominator

**Comment by mattmajic** [comment]
could be nice to have atleast the option of no preset words in placeholders?

**Comment by sunderme** [comment]
that argument I don't understand. If there is text within the braces, jumping works fine

\frac|{a}{b} -> \frac{|a}{b} -> \frac{a|}{b}  -> \frac{a}{|b} -> \frac{a}{b|}

**Comment by mattmajic** [comment]
Sorry I mean if you move the cursor somewhere else (anywhere) before
editing the denominator

**Comment by sunderme** [comment]
the placeholder is persistent until you edit it ?

**Comment by mattmajic** [comment]
Yes. The thing is if have to access the denominator via mouse or arrow keys, you have to delete the "den" characters

**Comment by sunderme** [comment]
arows keys -> use ctrl+right/left
mouse -> double click on "den"

**Comment by mattmajic** [comment]
sounds like a pain
