### ISSUE TITLE
Editor font problem for complex scripts

### ISSUE THREAD

**Issue by MajidDaliri35** [texstudio-org/texstudio#675]
### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.1
- OS: Windows(10)
- TeX distribution: miktex

### Expected behavior
By changing the Editor's font it should appear in all text in the editor.

### Actual behavior
Changing editor font applies only to latin text and has no effect to complex script texts like persian.

### How to reproduce
Apply font to complex scripts like persian or add new font for complex scripts.

**Comment by muzimuzhi** [comment]
To ease the reproduction process, can you provide some more detailed info, like
 - which font (system font preferable) have you set as the editor font?
 - what sample "complex script texts" can be used to reproduce the problem?

**Comment by MajidDaliri35** [comment]
OS: Windows 10 Enterprise x64 10.0.17134
No matter. I used both system fonts like  Tahoma or Arial and other fonts like XB Niloofar.
This is sample text in persian:

در مقیاس ساده ترتیب وجود دارد اما میزان فاصله دو عنصر متوالی اهمیتی ندارد. برای درک این مقیاس می‌توانیم به صف مشتریان بانک اشاره کنیم. در این صف ترتیب ورود مشتری مهم است اما اختلاف زمان ورود دو نفر در صف اهمیتی ندارد و مزیتی ایجاد نمی‌کند. این دسته از ‌فنون، یک لیست مرتب از نیازمندی‌ها ایجاد می‌کنند. در مقیاس ساده فقط می‌توان گفت که اهمیت یک نیازمندی بیشتر یا کمتر از نیازمندی دیگر است اما نمی‌توان گفت میزان اختلاف اهمیت آنها چقدر است. این دسته شامل سه فن گروه‌های اولویت درخت دودویی جستجو و مرتب‌سازی حبابی است.

**Comment by sunderme** [comment]
are you sure that the changed font contains all needed characters ?
Qt falls back to other fonts in that case ...
