### ISSUE TITLE
German Translation Error / Typo

### ISSUE THREAD

**Issue by Cr4sZz** [texstudio-org/texstudio#676]
![Translation Error TeXstudio](https://user-images.githubusercontent.com/49496538/62025292-09fae280-b1d8-11e9-9a4a-5dd473d1e0d2.png)

### Environment
- TeXstudio: 2.12.16 (git 2.12.16)
- Qt: 5.12.1
- OS: Windows 7
- TeX distribution: miktex

### Expected behavior
"Speichern" instead of "Spechern"
German button descriptions

### Actual behavior
opposite of expected behavior ^^

### How to reproduce
Save a .tex file, open in TeXstudio and change it with another editor to see the warning

**Comment by sunderme** [comment]
fixed
