### ISSUE TITLE
Find all words ending on the letter s

### ISSUE THREAD

**Issue by JamesLarkinWhite** [texstudio-org/texstudio#677]
Dear all i would want to find all words ending on the letter s... 
I need this to find all plurals.

**Comment by muzimuzhi** [comment]
1. Not every plurals is ended with letter s.
2. To find words ending with letter s, this regular expression may help: `\w*s`.

For example:
![image](https://user-images.githubusercontent.com/6376638/62067491-76242780-b266-11e9-9faa-91293bf1f076.png)

**Comment by foreachthing** [comment]
This might work better, as it truly finds words ENDING with an s, not containing an s:
https://regex101.com/r/AZeiSu/1
https://regex101.com/r/AZeiSu/2 this will even find "industry's" as a word (right or wrong - you decide).

**Comment by sunderme** [comment]
I guess this is settled ?

**Comment by JamesLarkinWhite** [comment]
Yes thank you very much for your help! On a second note... are these regular expressions explained somewhere?

**Comment by foreachthing** [comment]
@JamesLarkinWhite 
Good luck :-)
https://www.regular-expressions.info/
