### ISSUE TITLE
Mouse hover prompt time is too short

### ISSUE THREAD

**Issue by siaimes** [texstudio-org/texstudio#678]
# Environment
- TeXstudio: 2.12.16
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution: miktex

# issue
I hovered over the command, TeXstudio will display the key information of the command in the floating window, but the display time is too short, I have not had a chance to view it and it has disappeared, so I hope you can improve this function.

**Comment by muzimuzhi** [comment]
> I hovered over the command, TeXstudio will display the key information of the command in the floating window

Does the following screenshot show the same thing you mentioned as "floating window"?
![image](https://user-images.githubusercontent.com/6376638/62828406-3bcc6a00-bc18-11e9-99af-da53538f78cd.png)

If it is, I find that the "floating window" keeps showing as long as the mouse hovers over the command. I tested in texstudio 2.12.16 on macOS 10.14.6.

**Comment by siaimes** [comment]
![t](https://user-images.githubusercontent.com/34199488/62832138-a1424a00-bc5c-11e9-8ff0-01c958839a92.gif)

@muzimuzhi I am using windows 10, texstudio perform like this!

**Comment by timhoffm** [comment]
Does this only happen on formulas? It might be that the doc tooltip and the preview tooltip interfere.

**Comment by siaimes** [comment]
![t1](https://user-images.githubusercontent.com/34199488/62835350-03657400-bc8a-11e9-88af-7a453a54dd7b.gif)

@timhoffm Maybe you are right, but when I test more about this issue,  I found this situation also will happen with section, subsection ... environments.

**Comment by sunderme** [comment]
linux is fine, OSX has a similar problem (Qt issue).
I assume, it is a Qt issue, maybe fixed with newer version of qt/txs.
Can you try a dev build ? (https://bintray.com/sunderme/texstudio/texstudio-win)

**Comment by siaimes** [comment]
@sunderme If you have found out where the problem is, then I will close the issue. I will not consider upgrading the developer version, because this will not affect the core of texstudio, but the developer version may bring more problems, so I will wait for the next stable version.

@muzimuzhi @timhoffm @sunderme Thank you for your reply.

**Comment by Thinking2018** [comment]
Same problem! Haven't been fixed!
