### ISSUE TITLE
TexStudio Version 2.12.16 and issues with OSX Mojave 10.14.6

### ISSUE THREAD

**Issue by Oxidrill** [texstudio-org/texstudio#679]
### Environment
- TeXstudio:  2.12.16
- Qt:  5.11.2
- OS:  Mojave 10.14.6
- TeX distribution:  mactex (texlive)

### Expected behavior
Fluid

### Actual behavior
Any operation (launch of the soft, open files, typesetting, etc.) freezes the finder for several minutes

### How to reproduce
It is permanent

**Comment by sunderme** [comment]
Looks like a problem on your side.
You can try to remove .config/texstudio

**Comment by Oxidrill** [comment]
It works!

Thanks a lot "sunderme"
