### ISSUE TITLE
Screen resolution for "Internal PDF viewer" is used incorrectly in page scaling

### ISSUE THREAD

**Issue by johan162** [texstudio-org/texstudio#681]
### Environment
- TeXstudio: eXstudio 2.12.16 (git 2.12.16) 
- Qt Version 5.12.3, compiled with Qt 5.12.3 R
- OS: macOS Mojave, 10.14.6
- TeX distribution: texlive

### Expected behavior
Setting the screen resolution that corresponds to my MBP 15' (220dpi) would make the "View actual size" scaling "roughly" correspond to the actual printed appearance
.

### Actual behavior
The text in "View actual size" will make scale the page to approx 4 times it real size when displayed.

Setting a srceen resolution of around roughly ~100dpi get a more correct view of the actual paper size on my Mac

### How to reproduce
1. Set the "Screen resolution" to 220dpi
2. View a PDF with the internal PDF viewer

**Comment by wryVotary** [comment]
I have the same problem for a long time.

**Comment by timhoffm** [comment]
This is due to the difference between device pixels and device-independent (or screen) pixels. The effective screen resolution for a a 15“ MBP is 110dpi. See e.g. https://stackoverflow.com/a/39308268.

**Comment by wryVotary** [comment]
Hi @timhoffm, 
Thanks for the reply and the information about device-independent pixels. So based on your reply, setting the screen resolution to 100 dpi would fix @johan162 's problem?

However, in my case, I am still confused about how to decide the dpi of my system. I use 25inch Dell as the secondary monitor to run TeXstudio its resolution is 2560 x 1440 based on the “Display Info” from the hardware. My operating system is Ubuntu 18.04 and the display resolution is "2560 x 1440" from the system's point of view as well. So I guess my dpi could be something around 100?

Moreover, I manually tested several dpis and found out that the internal pdf viewer of TeXstudio would not have to scale the pdf file if the Screen Resolution is 90 dpi in the configuration.

But still, 90 dpi gives me blurry pdf, unfortunately. : (

Is there any suggestion for me to explore the problem? I highly appreciate it!

And some of the images about the numbers I have mentioned above are as follows,

Resolution from display:
![IMG_1404](https://user-images.githubusercontent.com/18092300/75611937-ffe1ef00-5aec-11ea-9bdf-eb5e74de2c97.jpg)

Resolution from the system:
![DeepinScreenshot_select-area_20200229115917](https://user-images.githubusercontent.com/18092300/75611950-1e47ea80-5aed-11ea-888a-b368fd9d9a5d.png)

Dpi setting in TexStudio:
![DeepinScreenshot_select-area_20200229115827](https://user-images.githubusercontent.com/18092300/75611961-2a33ac80-5aed-11ea-8e54-9e3a0c014ba5.png)

Interface and blurry pdf preview in TeXstudio:
![DeepinScreenshot_texstudio_20200229115734](https://user-images.githubusercontent.com/18092300/75611967-3d467c80-5aed-11ea-92ab-555c05f38070.png)

**Comment by timhoffm** [comment]
AFAIK high-resolution handling on OSX works a bit different than on other operating systems. 
The MBP with a 2880x1800 in HiDPI mode tells software that the screen is 1440x900 (configurable). The software renders its contents such as window size etc. as for the low-resolution. Text rendering requests are intercepted by the OS and modified to be rendered with the higher resolution. Images are interpolated, or if the application is HiDPI aware it may provide images for the double resolution.

Windows and Linux always tell the application the physical resolution plus a desired magnification factor. It‘s up to the application to respect that factor and recalculate all sizes as needed. But in your case there is no magnification (100%). So that shouldn’t be the problem. However, you have a multi-monitor setup, which makes things even trickier if they have different magnification factor. Can you confirm that this is still an issue if you just use one display or if all displays have a magnification factor of 100% (restart of TeXstudio may be required)?

**Comment by wryVotary** [comment]
Thanks for the replay and sorry for the late response. Hope everyone stays healthy and safe under this special circumstance.

I have two laptops, one is Dell XPS 15 with 3840 x 2160 running pop_! OS 19.10. It works perfectly with TeXstudio and is able to generate sharp internal preview pdf (even with multiply external monitor).

However, the second laptop, Alienware 17R5 with 2560x1440 resolution running Ubuntu 1804, is the one I mentioned earlier in this thread. I confirm that in this laptop, with only the build-in screen, the internal preview TeXstudio is not able to generate clear pdf with screen resolution as 100 dpi in the TeXstudio setting. Meanwhile, in my Ubuntu system, the scaling is 100% in setting-display, the font scaling is 1.00 in gnome tweak.

I highly appreciate the work of the TeXstudio team and enjoy using this brilliant software. Therefore I curious about what could be the problem. It would be awesome if we could fix it together!

**Comment by 1358** [comment]
FYI: Same happens in Xorg+KDE (Kubuntu 19.10) where every dimension is reported correctly:
```$ xrandr | grep DP-1 && xdpyinfo | grep -B2 dots  && xrdb -query | grep dpi
DP-1 connected primary 3840x2160+0+0 (normal left inverted right x axis y axis) 597mm x 336mm
screen #0:
  dimensions:    3840x2160 pixels (597x336 millimeters)
  resolution:    163x163 dots per inch
Xft.dpi:        166
```
For example Okular at 100% displays the right dimensions and everything is sharp there.

**Comment by 1358** [comment]
Just compiled TeXstudio from git master (3.0.1-6-g46ef5a05, Qt 5.11.4 R) and this issue is gone.
