### ISSUE TITLE
'Auto-backup' files not deleted automatically

### ISSUE THREAD

**Issue by Socratesnote** [texstudio-org/texstudio#682]
When saving a foo.tex file, a copy of the file is generated, named foo.tex~txs# (where # is a number, incremented each time the file is saved). This happens every time the file is saved, not just according the timer for "Auto Save All Files" (settings --> Adv. Editor). These 'backup' saves are not automatically deleted, and clog up the folder.

### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution: MikTeX

### Expected behavior
foo.tex~txs# files deleted upon compiling, exiting TeXStudio, or saving.

### Actual behavior
foo.tex~txs# files are produced on every document save, and are never automatically deleted.

### How to reproduce
Create foo.tex in TeXStudio, modify the file, and save the file.

Attached screenshot.
![TeXStudio issue](https://user-images.githubusercontent.com/38224599/62639952-2a2c4f00-b906-11e9-9b25-0cc54698f85a.png)

**Comment by sunderme** [comment]
where are you saving the files ? some kind of dropbox folder ?

**Comment by Socratesnote** [comment]
> where are you saving the files ? some kind of dropbox folder ?

Good catch, the files were indeed saved in Box Sync. I didn't suspect this to be an issue, since I've used TexStudio in Dropbox and Google Drive just fine before.

Moving the 'project' out of Box or temporarily turning of syncing indeed fixed the issue. Thanks.
