### ISSUE TITLE
[txs-app-dir] is not expanded correctly in macOS Mojave

### ISSUE THREAD

**Issue by tabad** [texstudio-org/texstudio#683]
### The environment
- TeXstudio: 2.12.16 (git 2.12.16)
- Qt: 5.12.3, compiled with Qt 5.12.3 R
- OS: macOS Mojave 10.14.6
- TeX distribution: MacTeX-2019 (08 May 2019)

### Description

By default, `TeXstudio` [2.12.16](https://github.com/texstudio-org/texstudio/releases/download/2.12.16/texstudio-2.12.16-osx.dmg) is installed in the `/Applications/texstudio.app` directory in `macOS Mojave` and  therefore `[txs-app-dir]` should be equivalent to `/Applications/texstudio.app` as indicated in [TeXstudio User's Manual](http://texstudio.sourceforge.net/manual/current/usermanual_en.html), sections [*1.2 Configuring the latex related commands*](http://texstudio.sourceforge.net/manual/current/usermanual_en.html#SECTION02) and [*1.4.1 Configuring the spell checker*](http://texstudio.sourceforge.net/manual/current/usermanual_en.html#SECTION03).

Well, taken that into account, I want to configure *TeXstudio > Preferences... > Language Checking > Sell Check > Spelling Dictionary Directories* to change `/Applications/texstudio.app/Contents/Resources` (its default value)  for `[txs-app-dir]/Contents/Resources`. Having done this, *... >  Language Checking > Sell Check > Default Language* changes to `<none>` and no one language is available in the drop-down list.

It seems `[txs-app-dir]` is not expanded correctly. May be the same problem appears in previous macOS and TeXstudio releases.

**Comment by sunderme** [comment]
said path replacement is not present in every path-entry. It is a mechanism for ruuning latex commands, not for finding dictionaries. (Though that may be helpful)

**Comment by sunderme** [comment]
going through the code, it should actually work

**Comment by sunderme** [comment]
you can define a user command "echo [txs-app-dir]" and report what message it generates ...

**Comment by tabad** [comment]
Of course! That is the output of my user command "user0:echo" defined as you indicate to me.

````text
Process started: echo /Applications/texstudio.app/Contents/MacOS

/Applications/texstudio.app/Contents/MacOS

Process exited normally
````

It seems, as you said above, the expansion of `[txs-app-dir]` is correct. I apologize.

The places under *TeXstudio > Preferences... > Language Checking* regarding with paths for dictionaries are:

  *  *Spell Check*
     * *Spelling Dictionary Directories*
     * *Thesaurus Database* and
  * *Internal Grammar Check*
     * *Wordlist Directory*

and these are my tests about `[txs-app-dir]` and `[txs-settings-dir]` expansion:

Path / *Expecial String* | `[txs-settings-dir]` | `[txs-app-dir]`
:---: | :---: | :---:
*Spelling Dictionary Directories* | Expanded :+1: | Expanded :+1:
*Thesaurus Database* | Expanded :+1: | Expanded :+1:
*Wordlist Directory* | -- (*) | -- (*)

> (*): Sorry, I don't know how to test that. I have read something about `es_ES.badWords` or `es_ES.stopWords`files but I don't have any idea about how to use them.

**Comment by tabad** [comment]
I have been able to do all test. These are my complete tests about `[txs-app-dir]` and `[txs-settings-dir]` expansion:

Path / *Expecial String* | `[txs-settings-dir]` | `[txs-app-dir]`
:---: | :---: | :---:
*Spelling Dictionary Directories* | Expanded :+1: | Expanded :+1:
*Thesaurus Database* | Expanded :+1: | Expanded :+1:
*Wordlist Directory* | Expanded :-1: | Expanded :-1:

**Comment by sunderme** [comment]
so what are you setting to find the languages ?

**Comment by tabad** [comment]
### My user commands

Command Name | Definition | Ouput
:---: | :---: | :---:
user0:txs-settings | echo [txs-settings-dir] | `/Users/tabad/.config/texstudio`
user1:txt-app | echo [txs-app-dir] | `/Applications/texstudio.app/Contents/MacOS`

### My dictionaries

````text
/Users/tabad/.config/texstudio/dictionaries
├── es_ES.aff
├── es_ES.badWords
├── es_ES.dic
├── hyph_es_ANY.dic
├── th_es_ES_v2.dat
└── th_es_ES_v2.idx
````

> **Note**: I have created the same content under `/Applications/texstudio.app/Contents/Resources` to realize my expansion tests.
>
> ````text
> /Applications/texstudio.app/Contents/Resources/dictionaries
> ├── es_ES.aff
> ├── es_ES.badWords
> ├── es_ES.dic
> ├── hyph_es_ANY.dic
> ├── th_es_ES_v2.dat
> └── th_es_ES_v2.idx
> ````

### My tests

#### *TeXstudio > Preferences... > Language Checking > Spell Check > Spelling Dictionary Directories*

Content | Effect
:---: | :---:
`[txs-app-dir]/../Resources` | Languages `de_DE`, `pt_BR`, `en_GR`, `hu_HU`, `fr_FR` and `es_ES` are available in *Default Language* drop-down list. Expansion :+1:
`[txs-app-dir]/../Resources/dictionaries` | Only `es_ES` language is available in *Default Language* drop-down list. Expansion :+1:
`[txs-settings-dir]/dictionaries` | Only `es_ES` language is available in *Default Language* drop-down list. Expansion :+1:


#### *TeXstudio > Preferences... > Language Checking > Spell Check >Thesaurus Database*

Content | Effect
:---: | :---:
`[txs-app-dir]/../Resources/dictionaries/th_es_ES_v2.dat` | TeXstudio opens the *Thesaurus* windows suggesting Spanish synonymous. Expansion :+1:
`[txs-settings-dir]/dictionaries/th_es_ES_v2.dat` | TeXstudio opens the *Thesaurus* windows suggesting Spanish synonymous. Expansion :+1:

> **Note**: `/Applications/texstudio.app/Contents/Resources` doesn't include Spanish thesaurus.

#### *TeXstudio > Preferences... > Language Checking > Internal Grammar Check > Wordlist Directory* 

Content | Effect
:---: | :---:
`[txs-app-dir]/../Resources/dictionaries` | Words defined inside `/Applications/texstudio.app/Contents/Resources/dictionaries/es_ES.badWords` are not marked as bad words by the editor. Expansion :-1:
`[txs-settings-dir]/dictionaries` | Words defined inside `/Users/tabad/.config/texstudio/dictionaries/es_ES.badWords` are not marked as bad words by the editor. Expansion :-1:

> **Note**: To make possible bad words are detected *Wordlist directory* mush contain an absolute path, for example, `/Users/tabad/.config/texstudio/dictionaries`. `~/config/texstudio/dictionaries` doesn't work either.

### My current configuration

  * *TeXstudio > Preferences... > Language Checking*
    * *Spell Check*
      * *Spelling Dictionary Directories* > `[txs-settings-dir]/dictionaries;[txs-app-dir]/../Resources`
      * *Default Language* > `es_ES`
      * *Thesaurus Database* > `[txs-settings-dir]/dictionaries/th_es_ES_v2.dat`
    * *Internal Grammar Check*
      * *Wordlist Directory* > `/Users/tabad/.config/texstudio/dictionaries`

> **Note**: I suppose the `es_ES` dictionary of `[txs-settings-dir]/dictionaries` takes preference over the `es_ES` dictionary of `[txs-app-dir]/../Resources`.

**Comment by tabad** [comment]
One more note...

The expansion of `[txs-app-dir]` and `[txs-settings-dir]` in *TeXstudio > Preferences... > Language Checking > Internal Grammar Check > Wordlist Directory* doesn't work either in this environment.

- TeXstudio: 2.12.16 (git n/a)
- Qt: Qt Version 5.11.3, compiled with Qt 5.7.1 R
- OS: Debian 10 Burst
- TeX distribution: TeXLive-2019

TeXstudio 2.12.16 (git n/a)
Using Qt Version 5.11.3, compiled with Qt 5.7.1 R
