### ISSUE TITLE
extra color definitions in latex-document.cwl

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#686]
In `latex-document.cwl`, there are lines defining colors
https://github.com/texstudio-org/texstudio/blob/a30a043658ab6aaa90f67388fde8180c4e85ebda/completion/latex-document.cwl#L569-L577

But neither the latex2e format nor standard classes supports colors. Color support is added only when packages like `color` or `xcolor` is loaded. 

Hence I think the above color-defining lines should be removed from `latex-document.cwl`.

**Comment by sunderme** [comment]
fixed

**Comment by muzimuzhi** [comment]
fixed in https://github.com/texstudio-org/texstudio/commit/b5d25203caa569cf179026ca7bedf8248ac16024

thanks
