### ISSUE TITLE
Feature Request: cwl file - allow multiple commands in "#keyvals:<cmds>"

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#688]
This issue is a continue of the conversation under [#687](https://github.com/texstudio-org/texstudio/pull/687#issuecomment-520223496) , where I said

> `tcolorbox.cwl` is a 40k+ line file, I will check if we can reduce its size later (not in this pr of course).

After checking `tcolorbox.cwl`, I found the cwl file expands so many lines because 
there are several different commands in `tcolorbox` that each of them accepts a same and long list of key-value list. Hence there are multiple copies of a long key-value list between different pairs of `#keyvals:<cmd> ... #endkeyvals` in `tcolorbox.cwl`.

Therefore I suggest if txs can extend the syntax of cwl file to support multiple commands in one group of `#keyvals:<cmds> ... #endkeyvals`. That is, to support 
```
# use comma separated list to express the command list
#keyvals:\cmdA,\cmdB
key1
key2
#endkeyvals
```
in cwl files. This new syntax will help largely reduce the size of `tcolorbox.cwl` and potentially other cwl files.

The related source lines are (as I guess, since I hardly know cpp)
https://github.com/texstudio-org/texstudio/blob/a7fd0a3dc064f685d68b8a6792bb825f4669a085/src/latexpackage.cpp#L137-L148

**Comment by sunderme** [comment]
implemented

**Comment by muzimuzhi** [comment]
Thanks!
