### ISSUE TITLE
Trapmine virus?

### ISSUE THREAD

**Issue by mike-a** [texstudio-org/texstudio#691]
### Environment
- TeXstudio: 2.12.16 (git 2.12.16) 
- Qt:  5.12.1, compiled with Qt 5.12.1 R  
- OS: Windows(7,10)
- TeX distribution: 

### Expected behavior
No virus

### Actual behavior
Open Process Explorer (procexp.exe) whilst Tex Studio open. Virus Total = 1. Virus reported by Trapmine machine learning threat capture.

Real or false positive?

**Comment by timhoffm** [comment]
Where did you obtain the binary from?

**Comment by sunderme** [comment]
no feedback, assumed false alarm
