### ISSUE TITLE
Feature request: add these dark syntax schemes to the distribution

### ISSUE THREAD

**Issue by Fifis** [texstudio-org/texstudio#699]
### Environment
- TeXstudio: 2.12.16
- Qt: 5.13.0
- OS: Any
- TeX distribution: Any

### Preface
This is 2019, and the amount of jokes panning light IDE schemes has reached unhealthy amounts. Seriously, there is a reason why in most Linux distributions, the terminal emulator is dark, Sublime Text is dark, and there is a simple reasons: people who code a lot do not want the brightness to take toll on their eyes.

![dark-themes](https://user-images.githubusercontent.com/5990916/63701283-f36e9800-c824-11e9-96e6-24a62b3e0f4c.png)

### Suggestion
I am suggesting that TeXStudio, apart from ‘Style’ and ‘Colour Scheme’, should feature easily selectable highlighting schemes syntax without the need to re-load the entire `.txsprofile`. This has become a standard in many top plain text editors (gedit, Notepad++, Sublime, ...). There is a very popular StackExchange thread with multiple ready solutions:
https://tex.stackexchange.com/questions/108315/how-can-i-set-a-dark-theme-in-texstudio

Also, there is one suggested by Rob Hyndman:
https://robjhyndman.com/hyndsight/dark-themes-for-writing/

![dark-hyndman](https://user-images.githubusercontent.com/5990916/63700301-ebadf400-c822-11e9-97cd-1b90d1e69411.png)

Once there is a convenient way to manage the themes from the Preferences window, converting existing popular themes (Ambiance, Chaos, Clouds, ...) will be trivial because many people have their own custom themes. For now, adding the ones from the SE thread and Rob Hyndman’s one, which all are in public access, would be a huge improvement that could be featured on the project homepage and make life easier for power users.

**Comment by sunderme** [comment]
done
