### ISSUE TITLE
Suggestion: display of superscripts/subscripts

### ISSUE THREAD

**Issue by perrogg** [texstudio-org/texstudio#7]
Texstudio is wonderful and I always use it to deal with .tex files. 

Can superscripts/subscripts be displayed in TeXstudio as in Emacs+AucTeX (see picture) ?  I think it's clear, but  I don't know if it is difficult to achieve.

![emacs_auctex](https://user-images.githubusercontent.com/14990848/34761742-ea30b5dc-f5dc-11e7-854c-4c0c69ba8ccb.png)

**Comment by timhoffm** [comment]
This is non trivial. One would have to:
- parse the formulas to identify the sub/superscripts.
- adapt the line drawing mechanism to be able to vertically offset parts of the line.
- adapt the editor rendering to support lines with variable line height.

None of which is possible is available in the current code.

I propose to use the inline rendering of formulas instead (Preview Selection / Parentheses (`Alt+P`). This also gives you a readable formula.

**Comment by sunderme** [comment]
I don't see the point either.
Super-/subscript are hard to implement.
