### ISSUE TITLE
TeXLive2017 installation not detected and no trivial way to point TeXstudio to it

### ISSUE THREAD

**Issue by assarbad** [texstudio-org/texstudio#70]
### Environment
- TeXstudio: TeXstudio 2.12.8 (hg 2.12.8-1-g68cd350)
- Qt: Version 5.8.0, compiled with Qt 5.8.0 R
- OS: Windows 7 x64 with latest patches applied
- TeX distribution: TeXLive2017

### Expected behavior

TeXstudio should auto-detect the TeXLive installation or offer an easy alternative by pointing to the installation folder for supported TeX distros.

### Actual behavior

TeXstudio does not auto-detect the TeXLive2017 installation and complains about finding no installation, but offers no way to remedy it (other than manually filling over a dozen edit fields).

```
---------------------------
TeXstudio
---------------------------
No LaTeX distribution was found on your system. As a result, the corresponding commands are not configured. This means, that you cannot compile your documents to the desired output format (e.g. pdf).<br><br>Popular LaTeX distributions on windows are <a href='http://miktex.org/'>MikTeX</a> and <a href='https://www.tug.org/texlive/'>TeXLive</a>.<br><br>If you intend to work with LaTeX, you'll most certainly want to install one of those.
---------------------------
OK   Do not warn again.   
---------------------------
```

It appears to use some kind of heuristics to find MiKTeX by path.

### How to reproduce

Good question. I have no idea at this time. I ran a default installation (`install-tl-windows.bat`) from the TeXLive2017 DVD as privileged user. The only thing I did was to deselect the TeXworks installation, since I was going to use only TeXstudio anyway.

In my case I verified using ProcMon that the respective locations TeXstudio visits indeed weren't created by the TeXLive installer. So the blame may be with the TeXLive installer here. However, it would be really cool to be able to point TeXstudio to `C:\texlive\2017` and have it figure out the rest.

**Comment by dbitouze** [comment]
I observed this trouble on computers of students of mine who installed TeXstudio before TeX Live and it happens to be enough to re-install TeXstudio afterwards.

**Comment by assarbad** [comment]
Fascinating, so rerunning the TeXLive2017 installation _with_ TeXworks selected appears to fix the issue. Now the only thing I don't know is if the installation of TeXworks or rerunning the TeXLive installation caused the issue to be fixed.

**Comment by assarbad** [comment]
Simply reinstalling TeXLive solved the issue. If I ever find the time to set up the environment to tweak the TXS code, I'll contribute the requested patch and send a PR.

**Comment by timhoffm** [comment]
Actually, it's not that hard. https://github.com/texstudio-org/texstudio/wiki/Compiling is a bit dated and should be updated. Essentially:
- Download and install the latest Qt OpenSource version https://www.qt.io/
- Clone https://github.com/texstudio-org/texstudio
- Open texstudio.pro in QtCreator
- Run a Release Build (The linker will complain about missing dlls)
- Copy the dlls from a recent install or portable version to the created build folder
- Run the Release Build again
