### ISSUE TITLE
Textstudio crashes regularly

### ISSUE THREAD

**Issue by Quarkbeast** [texstudio-org/texstudio#702]
### Environment
- TeXstudio: 2.12.16 
- Qt: 5.12.1 compiled with Qt 5.12.1 R 
- OS: Windows 10 
- TeX distribution:  Not sure whether this is what you are looking for but the log mentions LaTeX2e <2016/03/31> patch level 3 

### Expected behavior
Should not crash.

### Actual behavior
Crashes regularly.

### How to reproduce

I haven't really found a pattern yet but it sometimes happens during recompilation and sometimes when using the magnifying glass on the pdf preview on the right.

**Comment by sunderme** [comment]
Without a test case, there is nothing we can do.
You can try to remove texstudio.ini.

**Comment by Quarkbeast** [comment]
Ok, I'll let you know if I find a reliable way to reproduce the problem.

Removing texstudio.ini did, unfortunately, not help.

**Comment by sunderme** [comment]
since we can't do anything, I close this issue.

Maybe related to the pdf ?
