### ISSUE TITLE
Mouse behaves as if left button were pressed all the time.

### ISSUE THREAD

**Issue by peci1** [texstudio-org/texstudio#706]
### Environment
- TeXstudio: 2.12.16
- Qt: Using Qt Version 5.9.5, compiled with Qt 5.9.5 R
- OS: Ubuntu 18.04
- TeX distribution: ??

Hi, I'm using texstudio on Ubuntu 18.04/Gnome, and as soon as I launch it, it behaves as if I were holding the left mouse button - moving over latex source selects text, moving over sections in the options dialog immediately selects the sections, etc... Clicking any mouse buttons in any order doesn't help getting rid of this behavior.

I tried motion with a wired mouse and with a touchpad, both do the same. Other applications behave normally.

Can you help me please?

**Comment by sunderme** [comment]
no idea. Looks rather like a qt issue

**Comment by ludwigbald** [comment]
Can't reproduce it on the same setup. I suppose you have already rebooted the computer.

**Comment by peci1** [comment]
Hmm, full system update and restart resolved the issue (I haven't updated for about a month before). So it was probably just a glitch...
