### ISSUE TITLE
Unicode characters display wrongly on side panel in TeXstudio 2.12.14 in Debian Buster

### ISSUE THREAD

**Issue by alphazhi** [texstudio-org/texstudio#709]
Recently I update Debian Stretch (9) up to Debian Buster (10), and a strange problem occurs to TeXstudio then. My computer is Thinkpad T420. The problem is: All the unicode characters of Symbols display wrongly in the side panel of texstudio. See below:
![Screenshot at 2019-08-30 10-23-59](https://user-images.githubusercontent.com/54695068/63988968-20ff5e00-cb11-11e9-80dc-bfd8a9e3f17d.png)
Even more strange: If I point to one of the strange character, the correct mathematical symbol will show up. See below:
![Screenshot at 2019-08-30 10-31-14](https://user-images.githubusercontent.com/54695068/63989077-91a67a80-cb11-11e9-9da4-e45dc42f453d.png)

I am using TeXLive 2019, with TeXstudio 2.12.14 qt5. My Linux Distribution is Debian Buster 64(bit). 

The locale of my OS is:
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

I have installed texstudio by debian-repository with commandline: apt install texstudio texstudio-doc.  

Maybe the reason is from qt5. But when I tried to install texstudio with qt4, by name of texstudio-qt4_2.12.16-1_amd64.deb, there are many dependence problems that I can not solve. Because Debian Buster uses qt5, not qt4. 

How can I let the side panel of texstudio show unicode characters correctly?

**Comment by sunderme** [comment]
Txs uses svg images to show the symbols.
Looks odd that that can be replaced by kanji somehow. Where did you get the binary?
Easiest solution may be to compile txs yourself which is quite simple on linux.

**Comment by alphazhi** [comment]
I have found the reason for this problem. It is caused by the package qt5dxcb-plugin. When I removed this package from my Debian Buster, Texstudio works well now. So my guess is right. The problem comes from qt5!
