### ISSUE TITLE
texstudio-2.12.8-win-qt5.exe is not signed, previous versions (e.g. 2.12.6) were signed

### ISSUE THREAD

**Issue by assarbad** [texstudio-org/texstudio#71]
Hi,

it appears the latest Windows installer binary is no longer code-signed, neither are the contained binaries. Maybe therefore it would be a good approach to offer at least detached PGP signatures alongside the release so users are able to validate the download as coming from you.

Optimal, of course, would be code-signed releases.

Best regards,

Oliver

**Comment by assarbad** [comment]
Hi there again,

some more things are odd about this installer. For starters it's about twice the size of the 2.12.6 version. Possibly the binaries weren't stripped of debug symbols?

Additionally it seems to be using a rather old NSIS version. Was this installer perhaps even generated with an old NSIS version from a Linux? Because NSIS installers didn't quite look this way for quite some time now by default.

**Comment by timhoffm** [comment]
There are [new rules for code signing](https://www.securityweek.com/casc-releases-minimum-requirements-code-signing-certificates), which makes the process more difficult and more expensive. I have not yet acquired a new certificate.

As for the size and installer, the 2.12.8 version you're referencing is from an automatic travis build. They are statically linked, possibly debug symbols are not stripped either. - Didn't have time to look into this so far. See also #29

**Comment by assarbad** [comment]
Admittedly I've not gone through the previous process, but took up the [offer by Certum](https://www.certum.eu/certum/cert,offer_en_open_source_cs.xml) recently for my own FLOSS projects and it turned out to be relatively simple. They required a copy of the ID and a recent utility bill (to verify the address, I presume). If you're getting it the first time from Certum, you need to also purchase the hardware token / smartcard. That costs more than the raw cost of the certificate only.

Never tried Comodo (your previous cert), my previous certificate was a class 3 from Symantec and from StartSSL before that. Both were more expensive than the Certum offer is.

Admittedly the signing will be difficult to achieve unless you have Travis running locally. But even then the hardware token poses an issue that likely requires at least human intervention to unlock once for every signing (presumably the state is cached for some limited time, haven't tested it in-depth).

As to the costs your profile says you're in Germany. I already offered Benito to donate, but he declined. I'll be happy to pay for the certificate and 50% of the reader, if that still needs to be purchased. Use `oliver@<my-GitHub-username>.net` to get in touch with me. With a national wire transfer we can get this going quickly.

**Comment by RoyiAvital** [comment]
@assarbad , What a lovely offer!

By the way, where can one see the release notes of version 2.12.8?

Thank You.

**Comment by timhoffm** [comment]
@assarbad Thank you very much for the offer. I may come back to this.

I've used Certum so far. But with the hardware and shipping it's gotten significantly more expensive. Did they also charge you an additional 35€ for shipping? Do you know if it has to be exactly their hardware token or are there maybe any cheaper alternatives?

**Comment by assarbad** [comment]
@timhoffm yes, they insist on their own hardware token. But you only need that once. If you already used Certum and already have it, you can simply request a new certificate at a much lower rate.

So if you have the hardware it's 28 € and no shipping because there's no shipping involved. Only if you choose to send your documents via letter will the postage have to be added to the overall cost.

Here's the cost structure _with_ the hardware token _and_ the certificate. Indeed the shipping cost was 35 €. My purchase was in February, so likely little has changed since then.

![certum](https://user-images.githubusercontent.com/3238620/37778628-55d59b58-2de2-11e8-9c69-d5b5544e519c.png)

**Comment by timhoffm** [comment]
Yes, that's the price I also get. I don't have a hardware token yet, so it would be the full price. I'm suspecting that the yeary fees may still rise in the future. Originally it was free for open source, then 15€, now 28€.

Alternatively, one can get a three-year Code Signing certificate from Comodo for approximately 180$ (they don't seem to have a hardware token so fare ?!). I'll look into this on the weekend.

**Comment by LyleRamshaw** [comment]
Signing the binary would be elegant, but it seems that it might be expensive.  In lieu of that, could the developers perhaps publish the MD5 or SHA-256 hash of the release binary, so that users could confirm that they have the right bits that way?  

I am not a security wizard -- perhaps this is a bad idea for some reason.

**Comment by LyleRamshaw** [comment]
Thank you, @assarbad, for your clear explanation of the next layer of security issues.

**Comment by timhoffm** [comment]
Singing is on it's way, but the validation procedures have become much more complicated. So it takes some time.

**Comment by assarbad** [comment]
Very cool, @timhoffm . Drop me a line via email when you're ready and I'll get the transfer going.

**Comment by sunderme** [comment]
builds are automatically generated.
I have not heard of any attempts to sign builds again.

**Comment by assarbad** [comment]
> builds are automatically generated.

Perhaps then [this](https://about.signpath.io/open-source) would be a viable solution for you?

> I have not heard of any attempts to sign builds again.

Hmm, okay. I thought this was seen as a regression.

**Comment by RoyiAvital** [comment]
By the way, where are the release notes for version 3 Alpha / Beta?
I guess there are significant changes to bump the main version.
