### ISSUE TITLE
The Delete Line operation should copy the deletion to the clipboard

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#715]
### Environment
TeXstudio: 2.12.16 (git 2.12.16-12-gac7700de)

### Feature request
The line operations "Delete Line" and, to a lesser extent, "Delete To the End of Line" should (silently?) copy the deletion to the clipboard. It could be useful for a user who would like to move elsewhere the content of a line.

**Comment by sunderme** [comment]
I am not a fan of this functionality since it unexpectedly removes the contents of the clipboard.

**Comment by dbitouze** [comment]
>it unexpectedly removes the contents of the clipboard.

A user who wants to reuse the clipboard's content would probably use it before deleting a line (except if he wants to replace the line's content with the clipboard's one but, in such a case, he just has to select the line and paste).

**Comment by sunderme** [comment]
Qtcreator uses that behavior and it sabotaged me several times.

**Comment by jonasstein** [comment]
`Delete` should delete. What you want is probably a new function called `Cut`

**Comment by dbitouze** [comment]
`Delete` could delete *and copy* :) A new function means an extra entry in the TXS's menu and an extra shortcut: IMHO not necessary.

**Comment by sunderme** [comment]
but then the function "delete and do *not* copy" is missing ...

**Comment by timhoffm** [comment]
If anything this should be an opt-in setting. Can‘t be default behavior because it‘s non-standard. Also a separate function does not make sense.
