### ISSUE TITLE
Feature request: Provide for a more flexible way to add custom commands with textual description

### ISSUE THREAD

**Issue by clecap** [texstudio-org/texstudio#720]
It would be cool if the user could also place a macro into a toolbar under a name and would not be forced to develop or use an icon.

See also https://tex.stackexchange.com/questions/507788/how-to-customize-texstudio-with-own-textual-macros-for-example-in-sidebar

Amended: The main motivation is: To have a larger list of user chosen macros / tex snippets available in a list with a textual description which is quickly accessible and always visible (ideally as in the sidebar). No need to come up with icons but able to use textual descriptions.

**Comment by clecap** [comment]
The sidebar mechanism (as used for xy and beamer) would be a great place to adjust the UI.

I studied the mechanism for doing this. It looks like texstudio uses QT resource file mechanisms and compiles the XML file in into the program. The good news: You cannot "forget" such a file on distribution. The bad news: Indeed it has to be compiled in every time.

Therefore I would amend my feature request: Allow the user configuration directory to have a directory ./tags where the user can place XML files, which then also are loaded (additionally)

**Comment by sunderme** [comment]
I assume that the solution is sufficient

**Comment by clecap** [comment]
The solution to edit and recompile resource files is, for probably 99% of the users, not sufficient. A solution is needed where add ons to the sidebar can be done better and faster, as outlined in the amended feature request.
