### ISSUE TITLE
Option to open new .tex file in separate window

### ISSUE THREAD

**Issue by tylerlekang** [texstudio-org/texstudio#722]
### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution: MiKTeX-pdfTeX 2.9.7029 (1.40.20) (MiKTeX 2.9.7140 64-bit)

### Desired behavior
There should be an option in the configuration to always open new .tex files in separate windows. In other words, disable the use of tabs in the same window. In other words, Single Document Interface.

### Actual behavior
Opening a new tex file (Ctrl-O) will open the file in the same TXS window. Using "--start-always" only opens a new window when you double-click or right click Edit a .tex file from a File Explorer window.

(Also, slightly annoying: it opens the new window with a blank tab called "--start-always" first, then another tab with the file you want to open/edit, ideally that would not happen. Maybe I did the command wrong?)

### How to reproduce
- Open a .tex file in TXS.
- Use Ctrl-O in the TXS window, to open a new .tex file
- The new file will open on a new tab in the same window.

**Comment by sunderme** [comment]
If you see a file "--start-always" as title, then you set up the command wrongly.
I don't see a benefit for this request since it potentially breaks quite a lot of things.
