### ISSUE TITLE
Package Documentation Not Being Displayed

### ISSUE THREAD

**Issue by BeerStud** [texstudio-org/texstudio#724]
### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.1, compiled with Qt 5.12.1 R
- OS: Win 10 PRO; amd 64
- TeX distribution: miktex

### Expected behavior
Until recently, when I right-clicked on a package name, a menu would be displayed tht would give me the option of opening the package documentation.

### Actual behavior
Now, when I right-click on a package name, the same menu is displayed; however, if I click on to open the documentation, a warning screen is displayed that states:  "Texdoc not found".

### How to reproduce
Right-click on a package name.

[System Report.txt](https://github.com/texstudio-org/texstudio/files/3613865/System.Report.txt)

![image](https://user-images.githubusercontent.com/17906160/64923283-73de4400-d7a6-11e9-9067-6b8fa3ef8b78.png)

**Comment by muzimuzhi** [comment]
Does the `texdoc` work ok from inside `cmd.exe`? 

For example, open a `cmd.exe` window, type in `texdoc amsmath` then hit Enter. Will the doc of `amsmath` been opened?

**Comment by foreachthing** [comment]
Exact same environment but _package documentation_ works.
Tested with: `marginnote`, `wallpaper`, `lastpage`, `geometry`, `amsmath`, `amssymb`, `xcolor`, `fancyhdr`
Exception: `tikz`. `textdoc `told me there is no documentation.

**Comment by BeerStud** [comment]
> Does the `texdoc` work ok from inside `cmd.exe`?
> 
> For example, open a `cmd.exe` window, type in `texdoc amsmath` then hit Enter. Will the doc of `amsmath` been opened?

Sorry, it didn't work. This is the output:

texdoc amsmath
'texdoc' is not recognized as an internal or external command, operable program or batch file.

I did a search of the PC, and 'texdoc' was not to be found.

**Comment by muzimuzhi** [comment]
@BeerStud 
It seems that in miktex, the executable file of `texdoc` package is named `mthelp.exe`. Hence, you can try execute `mthelp amsmath` inside `cmd.exe`.

Some link:
 - `texdoc` on CTAN is contained in miktex under name `miktex-mthelp-bin-2.9`, see https://ctan.org/pkg/texdoc?lang=en
 - miktex package `miktex-mthelp-bin-2.9` (and its 64bit version) contains executable file `mthelp.exe`, see https://miktex.org/Package/Browse/miktex-mthelp-bin-2.9

**Comment by BeerStud** [comment]
> @BeerStud
> It seems that in miktex, the executable file of `texdoc` package is named `mthelp.exe`. Hence, you can try execute `mthelp amsmath` inside `cmd.exe`.
> 
> Some link:
> 
> * `texdoc` on CTAN is contained in miktex under name `miktex-mthelp-bin-2.9`, see https://ctan.org/pkg/texdoc?lang=en
> * miktex package `miktex-mthelp-bin-2.9` (and its 64bit version) contains executable file `mthelp.exe`, see https://miktex.org/Package/Browse/miktex-mthelp-bin-2.9

I have already investigated that. This is the output of just using 'mehelp.exe'

mthelp.exe amsmath
'mthelp.exe' is not recognized as an internal or external command,
operable program or batch file.

If I use the complete path, it gets slightly better.
"C:\Users\gerar\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\mthelp.exe" amsmath

That displays this page: file:///C:/Users/gerar/AppData/Local/MiKTeX/2.9/miktex/mthelp/amsmath.html

I then have to click on one of the PDF files displayed.

Something is seriously wrong here. This happened after I did a recent update of MiKTeX using the MikTeX console. I am beginning to think I will have to do a complete removal of MiKTeX and then reinstall MiKTeX to get this working again.

**Comment by foreachthing** [comment]
Go to `cmd` and type `path` [enter]. Check if the path to miktex is actually there and that it exists.
Otherwise just reinstall miktex.
![image](https://user-images.githubusercontent.com/10420187/65014147-fccbbb80-d91d-11e9-8643-df34927dd08c.png)

**Comment by BeerStud** [comment]
I finally got tired of trying to debug the problem, so I removed MiKTeX. It left files behind that I had to remove manually though. After removing all traces of MiKTeX, I rebooted and downloaded and reinstalled MiKTeX.

I don't know what caused this problem, but it is fixed now.
