### ISSUE TITLE
upon PC switch off the tex file got written as \xcd\xadL\xd4\x01 etc

### ISSUE THREAD

**Issue by IgnatRU** [texstudio-org/texstudio#726]
### Environment
- TeXstudio:  2.12.14
- Qt: 5.8.0
- OS: Win 10
- TeX distribution:  miktex

### Actual behavior
My PC unexpectedly was switched off. The TeX file I was working on was overwritten with text containing  things like 
\xcd\xadL\xd4\x01\xb0^\x10\xd0\xc7\xc4\x0c\x04@\x88\xc0\x01@!\x00\xbd${~\xd7\xbb\xacP2\xa55

Any idea what is it and how to get the normal text back?

**Comment by sunderme** [comment]
txs usually writes to a second file, and renames it. If no file filename~txs... exists, there is nothing that can be done (apart from backups in windows)
