### ISSUE TITLE
Portable version of Texstudio 2.12.8 and some problems

### ISSUE THREAD

**Issue by GyorgySZEIDL** [texstudio-org/texstudio#73]
1. Is there a way to download a portable version of Texstudio 2.12.8?
2.  If I set Hard line Wrap after 80 characters the vertical line does not appear
     in Texstudio 2.12.8 (in contrast to Texstudio 2.12.6).
3.  On the left side of the screen some items in a vertical column (Cyrillic letters, Accented letters, etc)
    do not appear in Texstudio 2.12.8 (in contrast to Texstudio 2.12.6).
4. For 2. and 3. I have uninstalled 2.12.8 and reinstalled 2.12.6 this morning.
5. No changelog information for Texstudio 2.12.8 on the homepage of texstudio.
Any information concerning the above issues is highly appreciated.
With best regards
G. Szeidl

**Comment by sunderme** [comment]
portable version is on texstudio.org (though erroneously labeled win 7/8/10 2.12.6 portable, the file name is correct)

**Comment by GyorgySZEIDL** [comment]
Dear Sunderne, Thank you very much. G. Szeidl.

**Comment by sunderme** [comment]
hard line wrap works fine on linux

**Comment by GyorgySZEIDL** [comment]
I have just installed the portable version under Windows 10. Hard line wrap does, however, not work here.

**Comment by sunderme** [comment]
3) the symbols are reordered.
The main symbol panel is "*" and there sub-panel can be selected (cyrillic,greek,etc)
Furthmore it is possible to search for symbol names.

**Comment by GyorgySZEIDL** [comment]
Dear Sunderme,
The previous symbol panel arrangements (Texstudio 2-12-6) are much better than those in the present version of the program (Texstudio 2-12-8). See the two png files.
![texstudio2-12-6](https://user-images.githubusercontent.com/37615412/37752111-7799d174-2d96-11e8-960d-a73114a231b0.png)
![texstudio2-12-8](https://user-images.githubusercontent.com/37615412/37752122-885380d2-2d96-11e8-9e63-1ad37182e7d3.png)

3. If I click on the main symbol panel in Texstudio 2-12-8  * no further sub panels are offered. See the attached Texstudio2-12-8.png file.

I was also looking for information as regards the changes in the help system but found  nothing there.

I work under Windows 10 (64 bit) and the installation of Texstudio 2-12-8 is a portable one so that I can use version 2-12-6 of the program as well.

With best regards
G. Szeidl

**Comment by sunderme** [comment]
just click on „operators“,next to the search box in the panel. There you choose other symbol panels.

**Comment by GyorgySZEIDL** [comment]
Dear Sunderme,

1. Thank you very much. It works.

In the new version I have to click four times: * , Operators, Greek, then say lambda to achieve \lambda.

In the previous version two clicks: Greek then lambda are sufficient.

Which means that a simple process has been made more complicated.

It is, of course, my mistake that I have not realized the meaning of the item Operators.

2. If I set Hard line Wrap after 80 characters the vertical line does not appear
in Texstudio 2.12.8 (in contrast to Texstudio 2.12.6). This problem still exists, compare 
the two pictures in my previous message. The settings I have selected for line wrapping 
are the same both in Texstudio 2-12-6 an in Texstudio 2-12-8.

3. In spite of all that has been said above I like this program very much, it is perhaps 
the best LaTeX editor under Windows -- I also use Winedt 10.2 but Texstudio is a bit 
better.

Sincerely yours
G. Szeidl

**Comment by timhoffm** [comment]
*Symbols*

In the new version, you have everything on one page: Favorites, Most Used and the symbol search. As soon as you start using this, Most Used fills up and you can manually add symbols to the Favorites by using the search and `right-click -> Add to favorites`. Since you'll probably use basically a handfull of symbols (or maybe all the greeks and a handful of others), you'll have all needed symbols in one place. I.e. there's just one click now and no need of switching tabs.

**Comment by fbprod** [comment]
For vertical line.

In Menu Options, command Configure TeXstudio, select Show Advanced Options.
In Adv. Editor preferences, there is a Special options named Line wrapping. Select _Soft Line Wrap after max. Characters_ or _Hard Line Wrap after max. Characters_.
The vertical line does appear.

**Comment by sunderme** [comment]
@fbprod: that seems not to be the case on windows (unlike on linux)

**Comment by fbprod** [comment]
**@sunderme**

It works fine for me.

![2018-03-22 13_23_07-sans nom - texstudio](https://user-images.githubusercontent.com/37658547/37770700-91a97558-2dd5-11e8-814c-4d3fd40a15a5.png)

OS : Windows 10 x64
TeXstudio : 2.12.8 portable

**Comment by GyorgySZEIDL** [comment]
Dear Sunderme, Fbprod and Timhoffm,

I would like to thank you for your messages. By now everything  is fine: my problems have all been solved. This could have been impossible without your help and I am very grateful for your messages.
With kind regards
G. Szeidl
