### ISSUE TITLE
libc6 dependence on xfce install

### ISSUE THREAD

**Issue by tmelorc** [texstudio-org/texstudio#733]
### Environment
- TeXstudio: 2.12.16
- Qt: QT5
- OS: Linux Mint 19.04
- TeX distribution: texlive

### Expected behavior
I'm trying to install txs from this file:

http://download.opensuse.org/repositories/home:/jsundermeyer/xUbuntu_19.04/amd64/texstudio_2.12.16-1+2.1_amd64.deb

I have a fresh Mint 19 with Xfce installed and so I suppose that xUbuntu 19.04 amd64 would be adequate to me.

But there is a dependence on libc6 which I can not solve. I tried to install it from repository and I got

libc6 is already the newest version (2.27-3ubuntu1).

but txs depends on >= 2.29

Any idea?

**Comment by sunderme** [comment]
compile txs yourself or use the appimage.
Getting debs to run which are not explicitly built for a certain OS is a waste of time.
