### ISSUE TITLE
regexp search to the first }-bracket

### ISSUE THREAD

**Issue by IgnatRU** [texstudio-org/texstudio#734]
### Environment
- TeXstudio:  2.12.16
- Qt: 5.12.1 R
- OS: Windows 10
- TeX distribution: miktex

### Expected behavior
Regexp search for, e.g. `\\tmp\{.*\}` should highlight strings up to the first`}` following `\tmp`

### Actual behavior
Regexp search  `\\tmp\{.*\}` highlights strings up to the last `}` after `\tmp` but before the end of line

### How to reproduce
Create a tex file with 
```
\tmp{bla}  blabla. In \cite{bla}
\tmp{bla}  blabla. } 

\tmp{bla}  blabla. In \cite{bla} \tmp{bla}  blabla. } 
```
try regexp searching for  `\\tmp\{.*\}`

**Comment by timhoffm** [comment]
The default behavior of the underlying `QRegExp` is greedy matching. Hence, the behavior is as designed.

I'm unclear what the general expectation should be for such a case.

**Comment by muzimuzhi** [comment]
@IgnatRU 
You can use this a-bit-more-complicated regex `\\tmp\{[^}]*\}` as a workaround.

@timhoffm 
From qt doc of `QRegExp` class, the Perl-style input for specifying single quantifier as non-greedy `<greedy-quantifier>?` is not supported. But there exists a [`QRegExp.setMinimal()` method](https://doc.qt.io/qt-5/qregexp.html#setMinimal), which can be used to globally set an regex to non-greedy. Maybe an extra config checkbox item can be added, taking the danger to make the texstudio configuration even more complicated.

**Comment by MeanSquaredError** [comment]
@muzimuzhi supporting non-greedy regexps via QRegExp::setMinimal and an extra checkbox sounds like a good idea. However IMHO the best place for the checkbox is not the TXS configuration but the search box that opens when you activate search (CTRL-F).

**Comment by benibela** [comment]
We could check for modifiers at the beginning of the regex and then set the global flags accordingly. E.g.  `(?U)` prefix  for ungreedy

**Comment by sunderme** [comment]
I would default for non-greedy behavior, unless someone comes up with a case where that gives unexpected results ...

**Comment by Timvde** [comment]
Greedy behaviour is default in all regex engines I know of. It would be a very big surprise to many if this would change. If you want an ungreedy match, use `.*?` instead.

**Comment by muzimuzhi** [comment]
> @Timvde 
> Greedy behaviour is default in all regex engines I know of.

Yes, it is.

> If you want an ungreedy match, use `.*?` instead.

But the question is that texstudio does not support `.*?`-like non-greedy notation, since the underlying Qt QRegExp class does not provide this functionality. 

> QRegExp's quantifiers are the same as Perl's greedy quantifiers (but see the note above). **Non-greedy matching cannot be applied to individual quantifiers**, but can be applied to all the quantifiers in the pattern. For example, to match the Perl regexp ro+?m requires:
> ref: https://doc.qt.io/qt-5/qregexp.html#notes-for-perl-users

**Comment by Timvde** [comment]
Oh wow, I missed that. I don't have any experience with QRegExp myself, so thanks for clarifying. In that case, a checkbox indeed seems like the best option. But please don't make non-greedy the default. That was mostly my point :)

**Comment by Timvde** [comment]
Sorry for the double post, but could you then alternatively switch to [QRegularExpression](https://doc.qt.io/qt-5/qregularexpression.html) maybe?

**Comment by MeanSquaredError** [comment]
QRegularExpression requires Qt5 and TexStudio can compile with Qt4 too.

**Comment by sunderme** [comment]
with qregularexpression you can use \\tmp\{.*?\} for lazy matching which fulfills your need
