### ISSUE TITLE
fails to compile for ARM

### ISSUE THREAD

**Issue by sunderme** [texstudio-org/texstudio#739]
### Environment
- TeXstudio: 2.12.16
- Qt: 5
- OS: Raspbian 10
- TeX distribution: N.A.

### Expected behavior
Compilation of source code for arm7.

### Actual behavior
compile error in debughelper.cpp/SimulatedCPU::set_all

### How to reproduce
see https://build.opensuse.org/package/live_build_log/home:jsundermeyer/texstudio-2.12.16/Raspbian_10/armv7l

**Comment by MeanSquaredError** [comment]
The code in debughelper.cpp on line 519 seems to be for NetBSD and the correct Linux code is commented out. I think it should be something like this:

`#elif defined(CPU_IS_ARM)`
`        #if defined(__linux__)
`                #define PC_FROM_UCONTEXT(context) (context)->uc_mcontext.arm_pc`
`                #define STACK_FROM_UCONTEXT(context) (context)->uc_mcontext.arm_sp`
`                #define FRAME_FROM_UCONTEXT(context) (context)->uc_mcontext.arm_fp`
`                #define RETURNTO_FROM_UCONTEXT(context) (context)->uc_mcontext.arm_lr`
`        #elif defined(__NetBSD__)`
`                #define PC_FROM_UCONTEXT(context) (context)->uc_mcontext.__gregs[_REG_R15]`
`                #define STACK_FROM_UCONTEXT(context) (context)->uc_mcontext.__gregs[_REG_R13]`
`                #define FRAME_FROM_UCONTEXT(context) (context)->uc_mcontext.__gregs[_REG_R11]`
`                #define RETURNTO_FROM_UCONTEXT(context) context)->uc_mcontext.__gregs[_REG_R14]`
`        #else`
`                #error Don't know how to compile`
`        #endif`
`#elif defined(CPU_IS_IA64)`

However I don't have access to NetBSD to actually test it.

**Comment by matthewberryman** [comment]
@MeanSquaredError My understanding from reading is the same, namely arm (32 bit) on Linux uses the commented-out code. I took an approach similar to yours, but sans the check for NetBSD (I assume the code that isn't commented out also works on other BSDs), and also added aarch64 (arm 64 bit) Linux support in:
https://github.com/UOW-CBB/texstudio/commit/57cc83000231bfba4e34f4aa67d86b4ee36e40e3
But note that although the offending code now compiles on aarch64 (running Ubuntu 20.04), compilation overall hasn't finished yet so I haven't had a chance to test it, but will soon and report back. I'll see if I can get BSDs going on both 32 and 64 bit arm to test those too at some point.

**Comment by MeanSquaredError** [comment]
@matthewberryman 
Just FYI, Fedora has a similar patch (pasted below) for their TeXstudio package which fixes compile for ARM. It is for TXS 2.12.16, but `src/debughelper.cpp` has not changed much between TXS 2 and 3.

```
From b0cf44fde92b66fbaefceb643b6124bc5bf0b087 Mon Sep 17 00:00:00 2001
From: hannes <hannes@fedoraproject.org>
Date: Sun, 11 Feb 2018 07:39:00 +0100
Subject: [PATCH 2/2] armfix

---
 src/debughelper.cpp | 6 +-----
 1 file changed, 1 insertion(+), 5 deletions(-)

diff --git a/src/debughelper.cpp b/src/debughelper.cpp
index 2918b43..74b94bc 100644
--- a/src/debughelper.cpp
+++ b/src/debughelper.cpp
@@ -517,16 +517,12 @@ QString print_backtrace(const QString &message)
 #define FRAME_FROM_UCONTEXT(context) (context)->uc_mcontext.gp_regs[31] //not always used
 #define RETURNTO_FROM_UCONTEXT(context) (context)->uc_mcontext.gp_regs[34]
 #elif defined(CPU_IS_ARM)
-/*
+
 #define PC_FROM_UCONTEXT(context) (context)->uc_mcontext.arm_pc
 #define STACK_FROM_UCONTEXT(context) (context)->uc_mcontext.arm_sp
 #define FRAME_FROM_UCONTEXT(context) (context)->uc_mcontext.arm_fp
 #define RETURNTO_FROM_UCONTEXT(context) (context)->uc_mcontext.arm_lr
-*/
-#define PC_FROM_UCONTEXT(context) (context)->uc_mcontext.__gregs[_REG_R15]
-#define STACK_FROM_UCONTEXT(context) (context)->uc_mcontext.__gregs[_REG_R13]
-#define FRAME_FROM_UCONTEXT(context) (context)->uc_mcontext.__gregs[_REG_R11]
-#define RETURNTO_FROM_UCONTEXT(context) (context)->uc_mcontext.__gregs[_REG_R14]
+
 #elif defined(CPU_IS_IA64)
 #define PC_FROM_UCONTEXT(context) (context)->_u._mc.sc_ip
 #define STACK_FROM_UCONTEXT(context) (context)->_u._mc.sc_gr[12] //is that register 12?
-- 
2.17.1
```

**Comment by sunderme** [comment]
if building txs is verified, please provide a PR

**Comment by sunderme** [comment]
build fails on ubuntu 16.04 arm64 (newer version are okay)

https://launchpad.net/~sunderme/+archive/ubuntu/texstudio-daily/+build/19831111/+files/buildlog_ubuntu-xenial-arm64.texstudio_3.0.0-0~202008131902~ubuntu16.04.1_BUILDING.txt.gz

**Comment by MeanSquaredError** [comment]
It seems that the gnu assembler on ubuntu 16.04 does not recognize the aliases `lr` and `fp` when building arm32 and arm64.

On arm32 `lr` is an alias for `r14` (link register)
On arm32 `fp` is an alias for `r11` (frame pointer)
On arm64 `lr is an alias `r30` (sometimes called `x30`)
On arm64 `fp is an alias `r29` (sometimes called `x29`)

So the above build error can probably be fixed by separating the assembler code into two separate ifdef branches (one for arm and another for arm64) and then using the actual register names (`rXX`) instead of their aliases (`lr` and `fp`).

However I don't have access to arm and arm64 and I am not able to test the build after making the changes, so maybe @matthewberryman can comment whether he thinks the above idea is a viable solution or whether there is a better one.

**Comment by matthewberryman** [comment]
@MeanSquaredError is correct, it seems the gnu assembler does not have those aliases built in. Just noting that `fp`, unlike the others, is only by convention `r11` (or `r7` in thumb mode but seems we don't need to worry about that per https://thinkingeek.com/2014/12/20/arm-assembler-raspberry-pi-chapter-22/ ), however that seems consistent (even on Windows per https://docs.microsoft.com/en-us/previous-versions/ms253599(v=vs.90)?redirectedfrom=MSDN ). For arm64 we want the x version (denoting 64 bit register usage). 

So I would have thought [this commit](https://github.com/UOW-CBB/texstudio/commit/4c0a47755c84276f53c4c085d65eba451d35cfda) does the trick @sunderme although I will test on arm32 and 64 bit Ubuntu 16 before submitting a PR. 

Note I have also removed the comment about it being the other way around compared to x86 (at least for gnu assembler without options), arm has the destination as the first operand.

**Comment by matthewberryman** [comment]
Built, run and tested on arm64 Ubuntu 16.04 and 20.04.
Will test arm32 on same distros tomorrow my time.
