### ISSUE TITLE
TexStudio crashed with Exeption Acces Violation

### ISSUE THREAD

**Issue by BillyV2018** [texstudio-org/texstudio#74]
### Environment
- TeXstudio: 2.12.6
- Qt: 
- OS: Windows 10
- TeX distribution: texlive

Trace log:
EXCEPTION_ACCESS_VIOLATION at 70c303 (TXS-Version 6632:7777b2b8a906 R )
[bt] 00527ea0  ??? error: 487
[bt] 0070c303  ??? error: 487

### How to reproduce

Occurs only after some three or more compile and run sessions.

**Comment by sunderme** [comment]
please try txs 2.12.8
