### ISSUE TITLE
Macros forgotten when switching profiles

### ISSUE THREAD

**Issue by dca00** [texstudio-org/texstudio#740]
### Environment
- TeXstudio: 2.12.6
- Qt: 4.8.7
- OS: Fedora Linux 4.11.8-300.fc26.x86_64
- TeX distribution: texlive 2018
### Expected behavior
Adding a macro and Okaying the dialog would persist the macros

### Actual behavior
Macros are lost when profile is switched

### How to reproduce
Create N macros
Create 2x profiles
Add more macros
Switch profile - additional macros lost

Can you please cleanup the code around macro persisting and profile switching? At the very least add a confirmation if any configuration items such as macros have been changed but profile not yet saved.

Ideally macros should not be saved in profiles, or there should be a choice into which profile to save them.

**Comment by sunderme** [comment]
1) there is no profile switching, loading "profile" is to import settings
2) the "profile" needs to be stripped down manually only to carry that information which is relevant,i.e. macros definition need to be removed
3) the macro part is not true anymore as macro storing has been changed recently. So the behavior in question is not present in 2.12.16
