### ISSUE TITLE
Aspell

### ISSUE THREAD

**Issue by johnkb123** [texstudio-org/texstudio#747]
Linux/Ubuntu/Debian

Would Tex-studio developers consider adding support for aspell in tex-studio the same way texteditor Bluefish does it? The aspell with desired dictionaries are added to ubuntu/debian by sudo apt-get install aspell en, Bluefish understand that and automatically adds support for installed aspell language.

-john

**Comment by sunderme** [comment]
no.
hunspell should offer the same or even better availability and you can use any installed dictionary, just have to point txs to it.
