### ISSUE TITLE
Sections unfold too easily

### ISSUE THREAD

**Issue by PJBoy** [texstudio-org/texstudio#75]
I frequently deal with large documents with many sections/subsections etc. and it frustrates me to no end when I begin a new environment (in the middle of the document) and it expands all of the once-folded sections written after that point.

Minimum working example:
```latex
\begin{document}
% <-- Type `$` or `\begin{align}` here, section A will be expanded

\section{A} % <-- Fold this
A
B
C
\end{document}
```

**Comment by sunderme** [comment]
your assement of the issue is not quite correct.

If you type "$", the folding will be broken up, as txs tries to find a folding region between that "$" and a following (not existing) one
If you type "\" in fromt of your commented line, the "$" becomes active and the same applies again,starting from that dollar sign.

I don't think, that the math env issue is fixable.

**Comment by sunderme** [comment]
the only other solution would be to disable folding for $$-envs. It should not be used anyway since normally the $$-regions should be quite short and should not extend over a large number of lines

**Comment by PJBoy** [comment]
I agree that $-env and $$-env needn't be folded. The ideal model behaviour would be what notepad++ has, although I'm not sure if you can get the same functionality with the frameworks that this project is using

**Comment by benibela** [comment]
This does not happen when you insert a complete environment. For example in the menu math/math mode. Or the shortcut ctrl+shift+m. Or Math/Equations/env align. Or write "align" and press ctrl+alt+space enter.



Paragraph breaks are not allowed in math mode. Are there many exceptions?  Inside nested commands?

Perhaps we could change the math mode (syntax highlighting) to end on any empty line.

**Comment by timhoffm** [comment]
I'm fine with removing $$-env folding.

> Perhaps we could change the math mode (syntax highlighting) to end on any empty line.

Ideally, that would then be a separate "invalid math mode" format.

**Comment by PJBoy** [comment]
Thanks for the tip, benibela. I'm happy this issue is being met with such consideration, the mere typing of '$' has been making me irrationally stressful lately :D

**Comment by sunderme** [comment]
Benito implemeted that $$ highlighting/folding is stopped at empty lines. I consider this issue as fixed ...

**Comment by benibela** [comment]
My change only stops it at completely empty line. We could discuss, if it should also stop at lines only containing whitespace `       `, although you can have empty lines in math envs when there is a command removing them `\newcommand{\remove}[1]{no pound sign here}`
