### ISSUE TITLE
Feature request : allow use of captured group with regex in macro

### ISSUE THREAD

**Issue by matheod** [texstudio-org/texstudio#750]
If I am not wrong, TexStudio doesn't allow to use captured group with regex in macro without using script.

It would be nice if it supported it.

Using default syntax $n might be problematic as $ is an important symbol in latex and it isn't rare to have a $ being followed by a number.

Maybe use instead `@n` ? Or `%n` ?

For exemple, a user could create a macro :
```
!!([a-z]+)!!
```
being replaced with :
```
\begin{@1}
%|
\end{@1}
```

**Comment by matheod** [comment]
Vote for notation (clic) : 

[![](https://api.gh-polls.com/poll/01DQ3QCTF8GBF89B6G4BQDQZ1C/Use%20%40n%20notation)](https://api.gh-polls.com/poll/01DQ3QCTF8GBF89B6G4BQDQZ1C/Use%20%40n%20notation/vote)
[![](https://api.gh-polls.com/poll/01DQ3QCTF8GBF89B6G4BQDQZ1C/Use%20%25n%20notation)](https://api.gh-polls.com/poll/01DQ3QCTF8GBF89B6G4BQDQZ1C/Use%20%25n%20notation/vote)

**Comment by sunderme** [comment]
hmmm, I am not sure I want to extend macro notation for a rather special case which can already be solved ...

**Comment by matheod** [comment]
What issues could bring an extension of the macro notation ?

**Comment by sunderme** [comment]
more points of failure ...
work&effort

what do you want to search and replace anyway ? A macro typically is just inserted ...

**Comment by matheod** [comment]
For exemple I would like to add :

`!!X!!` to become `\begin{X}%|\end{X}`

`!mX` to become `\begin{multicols}{X}%|\end{multicols}`

Sure, I can do that with a script, but then I need to write something to find my trigger, extract matchs, replace, and position cursor.

**Comment by sunderme** [comment]
The script looks like this:
Trigger: `!m(\S)\s`
Script:

```javascript
%SCRIPT
env = triggerMatches[1]
txt = "\\begin{multicols}{"+env+"}\n"
txt = txt+"\n" 
txt = txt+"\\end{multicols}\n" 
cursor.insertText(txt)
cursor.movePosition(2, cursorEnums.Up)
cursor.movePosition(1, cursorEnums.StartOfLine)
```

The basic point of having a scripting language is that there is more flexibility to implement special user functions. It would be kind of futile of all that functionality needs to be written again into the core program.
