### ISSUE TITLE
External open not working with custom build dir

### ISSUE THREAD

**Issue by MaxSagebaum** [texstudio-org/texstudio#754]
I have configured my environment to create everything in the 'build' directory with '-output-directory=build' for pdflatex. I also added this directory to the additional search path and there are no auxiliary or pdfs files left in the main directory. Everything works so far.

Only if I click on 'External Viewer' I get the error:

Process started: xdg-open "sample".pdf

This command misses the directory prefix. 
TexStudio displays the correct pdf file in the 'build' folder. But, the command behind the button does not use the full path.

**Comment by MaxSagebaum** [comment]
I forgot:

### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.4, compiled with Qt 5.12.1 R
- OS: Fedora 5.2.17-200.fc30.x86_64
- TeX distribution: texlive

**Comment by MeanSquaredError** [comment]
See
https://tex.stackexchange.com/questions/272151/texstudio-change-external-pdf-viewer-command-to-open-pdf-from-sub-directory

More specifically see the second reply where they set the PDF file location using "?am.pdf"

**Comment by MaxSagebaum** [comment]
Thank you for the reply. I missed this command and I could get it to work with:

```
xdg-open ?a)/build/?m.pdf > /dev/null
```

Nevertheless, I think the default behaviour of the button and the open command should be to open the pdf file found by TexStudio. It is not very user friendly to have to configure this in a manual fashion.

Maybe a new 'p' special char would help in this case. It would point to the pdf file found by TexStudio. The default command could then be:

```
xdg-open ?p > /dev/null
```

**Comment by MeanSquaredError** [comment]
OK, let me try to prepare a patch

**Comment by MeanSquaredError** [comment]
I added an implementation of this feature as a pull request here https://github.com/texstudio-org/texstudio/pull/761

However I am not sure if the suggested design (where ?p expands to the PDF pathname) is a correct one. See my thoughts on it on the page with the pull request.

**Comment by gabriele-v** [comment]
Hello @MeanSquaredError, sorry to bring up this but I've tried to make the ?p working but without success.

If I've understood correctly, i have to change from `?am.pdf` to `?p{pdf}am.pdf` correct?

Thanks

**Comment by MeanSquaredError** [comment]
@gabriele-v 

This is how I use it in the `External PDF Viewer` setting:
```
okular ?p{pdf}:ame"
```
In your setting you seem to be missing the colon symbol.
