### ISSUE TITLE
Internal PDF View opens after copy+pasting equations

### ISSUE THREAD

**Issue by herisu** [texstudio-org/texstudio#755]
### Environment
- TeXstudio 2.12.16 (git 2.12.16)
- Using Qt Version 5.12.1, compiled with Qt 5.12.1 R
- OS: Windows 10
- TeX distribution: texlive

### Expected behavior
When closed, the *Internal PDF Viewer* does not open just because math-commands were copied in the source document. 

### Actual behavior
Once the Internal PDF Viewer was opened during a run of texstudio and then closed, it will appear again immediately after copy-pasting math blocks.

Copy-pasting behaves as expected on fresh start, until the internal pdf viewer is opened for the first time and then closed.

### How to reproduce
 - open some tex document containing math 
 - (compile and) open the compiled PDF in the Internal PDF Viewer
 - close the Internal PDF Viewer
 - copy and paste some text block containing $...$ or other math commands

**Comment by sunderme** [comment]
Have you set previewing to use the embedded viewer (options/preview/diplay mode:embeded viewer) ?

**Comment by herisu** [comment]
Screenshot of my settings
![image](https://user-images.githubusercontent.com/1749293/67237575-d7196100-f44b-11e9-963e-4b787b750216.png)


And I was now observing the behavior of the preview more precisely and unfortunately, the way to reproduce the issue may not always work. For instance now I cannot reproduce it, but at the time I was posting the issue it did behave as described. I will try to figure out a more precise description.

**Comment by herisu** [comment]
Or is it just wrong settings on my side? 

I suppose it happens during the attempt to highlight the copied text passage in the internal pdf viewer, so it is not limited to math text. Sometimes, it activated only when the copied line was selected by a double-click and not by click+drag.

**Comment by MeanSquaredError** [comment]
I tried reproducing the problem but could not reproduce it on Windows or Linux.

Is the TexStudio executable one which you are building yourself or is it one of the pre-built executables available online?

Can you try changing the option in the drop-down  "Preview / Display mode" to the other possible choices and see if the preview still shows up?

**Comment by herisu** [comment]
I use the downloaded binary. 

And I thing I have an explanation for the 'issue' - it has to do with the mouse + keyboard navigation while copying. When pasting the copied snippet, I navigate the mouse to the desired position and hit Ctrl + V. So the interaction is

LeftMouse ... Ctrl ... V

And sometimes the first two are interpreted together as the 'Show line in PDF' command 'LeftM + Ctrl'

**Comment by timhoffm** [comment]
Is this timing-dependent? i.e. only happens if Leftmouse and Ctrl are very shortly (<1s) after each other?

**Comment by herisu** [comment]
Yes, exactly. When I wait a bit, the preview will not show up. 
One way to test the limit is to have the PDF View open and look whether the pasted line will be highlighted in the PDF or not.

**Comment by timhoffm** [comment]
I think it exactly happens if `Ctrl` is pressed during the mouse button is release event.
