### ISSUE TITLE
make comment or uncomment on lines in texstudio

### ISSUE THREAD

**Issue by leo0640** [texstudio-org/texstudio#756]
### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution: MikTeX 2.9
Hello,
can you give TeXstudio the ability to make comment (%) and uncomment
on activated lines by right mouse button like the MATLAB editor.
This is helpfull sometimes for example to keep programming lines
for  later applications
#

**Comment by dbitouze** [comment]
You could (should?) use the shortcut <kbd>Ctrl</kbd> + <kbd>T</kbd> for this.

**Comment by sunderme** [comment]
I don't see the need to extend the given features (see above).
Unlike program code, commenting/uncommenting is not that imperative

**Comment by timhoffm** [comment]
By "right click", do you mean an entry in the context menu?

If so, I agree @sunderme  that access via main menu (`Idefix -> Toggle Comment`)  and shortcut `Ctrl+T` are sufficient and we shouldn't overload the context menu.

**Comment by thistlillo** [comment]
In which menu can I find the "comment line" / "uncomment line" functions? I am not able to find them.

This is an important function. I am surprised it is so hard to find.
