### ISSUE TITLE
Feature request: per-file profiles

### ISSUE THREAD

**Issue by dca00** [texstudio-org/texstudio#757]
Would you please consider applying profiles to source files?
The use case would be translator work where each of the simultaneously open file being worked on requires its own set of settings and macros?

**Comment by sunderme** [comment]
This is rather difficult to implement.
Why would you need different settings/macros ?

**Comment by MeanSquaredError** [comment]
Having different macros and setting would be really confusing to the user. His .tex file compiles fine then he closes the source file, renames it, opens it again and suddenly the file stops compiling.

**Comment by timhoffm** [comment]
I agree that different macros depending on the file are rather confusing. Can't you use a joint profile containing all necessary marcros for both files?

Apart from that, a profile contains much more than macros. Would you expect to change menu items, the complete build configuration, the application color scheme, GUI scaling, ... when switching from one file to another?

IMHO profiles are are too broad concept and can't/shouldn't be tied to single files.

**Comment by timhoffm** [comment]
Going to close as non-feasible.

Note that is its possible to start multiple instances of TeXstudio with `texstudio --start-always`. These can have different different profiles.
