### ISSUE TITLE
Enhance keyboard shortcuts to line operations

### ISSUE THREAD

**Issue by oldninja** [texstudio-org/texstudio#763]
### Environment
- TeXstudio:  TeXstudio 2.12.14 (git 2.12.14)
- Qt:  TeXstudio 2.12.14 (git 2.12.14)
- OS:  Windows 10
- TeX distribution:  miktex

### Feature request
Keyboard shortcut to line operations. Particularly "duplicate line". It may be convenient for environments like enumerate, itemize, plotting in tikz, etc.

### Actual behavior
A starting point would be to at Notepad++ (https://notepad-plus-plus.org/) for their line operations. Maybe a similar implementation? Reuse of open source code?

![Git](https://user-images.githubusercontent.com/49734546/67455821-c52af000-f5fc-11e9-8f42-e1e48f9c509c.png)

**Comment by timhoffm** [comment]
The main problem is that we have too many actions and many shortcuts are already taken.

**Comment by sunderme** [comment]
duplicate line is already there, you can assign a shortcut yourself.
Most of the other stuff could be handled by macro/script. (additions to github/txs-macros are welcome)
Since I am not using things like that and it is pretty unclear anyone else would, no action will be taken...

**Comment by oldninja** [comment]
> 
> 
> duplicate line is already there, you can assign a shortcut yourself.
> Most of the other stuff could be handled by macro/script. (additions to github/txs-macros are welcome)
> Since I am not using things like that and it is pretty unclear anyone else would, no action will be taken...

Just noticed the assigning of shortcut menu. Thanks for the help guys and apologies for the "issue".
