### ISSUE TITLE
Texstudio with Texlive 2019 in Ubuntu 18.04

### ISSUE THREAD

**Issue by rcbell1** [texstudio-org/texstudio#764]
I have installed texlive 2019 and I want texstudio to use this. I installed texstudio on Ubuntu 18.04 using the PPA. 

It looks like pdflatex is pointing to the correct place

$ which pdflatex
/usr/local/texlive/2019/bin/x86_64-linux/pdflatex

and I have confirmed the acmart directory and cls file exist in the proper place

:/usr/local/texlive/2019/texmf-dist/tex/latex/acmart$ ls
acmart.cls                ACM-Reference-Format.cbx
ACM-Reference-Format.bbx  ACM-Reference-Format.dbx

but when I try to compile a document using the acmart package, it tells me the package does not exist. 

How do I configure texstudio to use texlive 2019 properly?

### Environment
- TeXstudio: TeXstudio 2.12.16 (git n/a)
- Qt: Using Qt Version 5.9.5, compiled with Qt 5.9.5 R
- OS: Ubuntu 18.04
- TeX distribution: texlive 2019

### Expected behavior
Compile a document using the acmart package

### Actual behavior
Cannot find the acmart package

### How to reproduce
Install texlive following https://www.tug.org/texlive/quickinstall.html
Install texstudio using the Ubuntu PPA: http://ubuntuhandbook.org/index.php/2018/04/install-texstudio-2-12-8-ubuntu-18-0416-04/
Compile a document with the following document class: \documentclass[sigconf]{acmart}
More acmart info here: https://www.acm.org/publications/proceedings-template

**Comment by MeanSquaredError** [comment]
Is it really a TexStudio problem? If you go into the directory that contains your .tex file (e.g. your_file.tex) and run
$ pdflatex ./your_file.tex
Does it compile the file successfully or does it give an error?

**Comment by rcbell1** [comment]
It compiles with no errors

**Comment by MeanSquaredError** [comment]
I am not a Ubuntu user so most likely my advice is too generic but:

Is TeXstudio configured to run pdflatex for the build command? 

If yes, then it seems that pdflatex run from command line and pdflatex run from TeXstudio see different search paths for .tex files (.cls files are basically treated as .tex files by TexLive search).
You can try adding "-kpathsea-debug=32" to the pdflatex command run from command line and to the pdflatex command run by TexStudio (Options / Configure TeXstudio, then check "Show Advanced Options" and then add -kpathsea-debug=32 to whichever compile command(s) you are using.

Then compare the log files generated by the two run of pdflatex (from command line and from TeXstudio). Among all the debug output in the log file there should be lines similar to this :

kdebug:kpse_find_file: searching for gmartz.cls of type tex (from texmf.cnf)
kdebug:start generic search(files=[gmartz.cls], must_exist=0, find_all=0, path=.:/root/.texlive2018/texmf-config/tex/latex//:/root/.texlive2018/texmf-var/tex/latex//:/root/texmf/tex/latex//:/usr/share/texmf/tex/latex//:!!/usr/share/texlive/texmf-local///tex/latex//:!!/usr/share/texlive/texmf-config/tex/latex//:!!/usr/share/texlive/texmf-var/tex/latex//:!!/usr/share/texlive/texmf-dist/tex/latex//:/root/.texlive2018/texmf-config/tex/generic//:/root/.texlive2018/texmf-var/tex/generic//:/root/texmf/tex/generic//:/usr/share/texmf/tex/generic//:!!/usr/share/texlive/texmf-local///tex/generic//:!!/usr/share/texlive/texmf-config/tex/generic//:!!/usr/share/texlive/texmf-var/tex/generic//:!!/usr/share/texlive/texmf-dist/tex/generic//:/root/.texlive2018/texmf-config/tex///:/root/.texlive2018/texmf-var/tex///:/root/texmf/tex///:/usr/share/texmf/tex///:!!/usr/share/texlive/texmf-local///tex///:!!/usr/share/texlive/texmf-config/tex///:!!/usr/share/texlive/texmf-var/tex///:!!/usr/share/texlive/texmf-dist/tex///)

In the above example pdflatex is run as root (risky for regular use, but it is just an example) and the compiled document tries to use a non-existent class file called gmartz.cls

If the pdflatex log which is generated from TeXstudio does not contain the pathname where your .cls file resides then you need to fix that either by adjusting the TEXINPUTS environment variable visible to TeXstudio or maybe by placing a symlink from one of the searched directories to the actual location of your acmart directory.

**Comment by rcbell1** [comment]
Thanks. I got it working, unfortunately I don't know exactly what I that made it work. One of the thinigs I did was run texhash on the texlive texmf-dist folders, perhaps that is what it took. I also restarted in between tries. Sorry I can't be more helpful, but it's working.
