### ISSUE TITLE
Wrong handling of diacritic keys

### ISSUE THREAD

**Issue by meneken17** [texstudio-org/texstudio#767]
### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.1 R
- OS: Windows 10
- Keyboard with german T1 layout (might be relevant?)

Note: '2' is used as an example for any letter that does not have a diacritic-version (e.g. not 'a')
The same issue occures with '`' and '´' instead of '^'.

### Expected behavior
Typing key '^' and key '2' should give '^2' in the editor and the curser should be behind '2'.

### Actual behavior
When typing '^' and the following letter is ignored (e.g. Typing key '^' and key '2' shows only '^' in the editor and the cursor jumps before the '^')

### How to reproduce
Typing key '^' and key '2' in the editor window.

**Comment by timhoffm** [comment]
I cannot reproduce this anymore with the released version (2.12.16, default settings).
