### ISSUE TITLE
How to handle quotation marks in another pair of quotation marks

### ISSUE THREAD

**Issue by OsbertWang** [texstudio-org/texstudio#769]
### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution: Tex Live 2019

I want to use SumatraPDF in TeXStudio, and I use the user command like:
```
"<SumatraPDFROOT>\SumatraPDF.exe" -reuse-instance -forward-search "?c:am.tex" @ -inverse-search "\"<TeXStudioROOT>\texstudio.exe\" \"%%f\" -line %%l" "?am.pdf"
```
Then, the messages show
```
Process started: "<SumatraPDFROOT>\SumatraPDF.exe" -reuse-instance -forward-search "<texfileROOT>\main.tex" 4 -inverse-search """"<TeXStudioROOT>\texstudio.exe""" """%f""" -line %l" "<pdfRfileOOT>\main.pdf"
```
i.e., there are too many quotation marks.
I don't know how to delete the additional quotation marks in the user command.
Moreover, I know the DDE command for setting forward search, but I need to set inverse search in SumatraPDF one more time if I use DDE in TeXstudio.
Would anyone here know how to handle quotation marks in another pair of quotation marks?
Thank you very much.

**Comment by timhoffm** [comment]
There seems to be an unbalanced quotation mark after `-line %%1`

**Comment by OsbertWang** [comment]
> There seems to be an unbalanced quotation mark after `-line %%1`

Hi, I think the quotation mark after `-line %%l` is not unbalanced.
Pay attention the the quotation mark before `\"<TeXStudioROOT>`.
Moreover, it is the lower case `L` not the number `1`.
Thank you.

**Comment by timhoffm** [comment]
You are right.
