### ISSUE TITLE
Make the user able to open his favorite template in one go

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#775]
Thanks to the "File → New from template..." and "File → Make Template..." (nice!) TXS' features, I guess most of the users (aware of these features), when starting a new document, most of the time start with a template ("File → New from template...") and not with an empty file ("File → New ... <kbd>Ctrl</kbd> + <kbd>N</kbd>").

Hence it would be nice for the user to be able to mark a (possibly custom) template as his favorite one and to open it in one go (e.g. "File → New ... <kbd>Ctrl</kbd> + <kbd>N</kbd>" or a new entry "File → Favorite template ... <kbd>Alt</kbd> + <kbd>N</kbd>").

**Comment by sunderme** [comment]
I am not convinced that we need optimization here. It is a singular task at the start of a document.
No need to be super-efficient.

**Comment by dbitouze** [comment]
Super-efficient, maybe not. Make simpler the life of users, why not? 

- A word processor user who wants to start to write a new document just has to:
  1. open his word processor,
  1. type. 
- A TXS's user who wants to start to write a new document has to:
  1. open TXS,
  1. go to "File → New from template..." menu entry,
  1. choose a template,
  1. click (or navigate to) several lines below,
  1. type.

**Comment by sunderme** [comment]
if you wanted to use a template in a word processor, the procedure does not look much different from txs.
I have been using txs templates for years and it is fine. 
A favourite template would be one of the functions which nobody uses or , at worst, which confuses people because the new documents are not empty and where do I change that again ...

**Comment by dbitouze** [comment]
>if you wanted to use a template in a word processor, the procedure does not look much different from txs.

Okay. So make TXS better than word processors from this point of view!

>I have been using txs templates for years and it is fine.

It _is_ fine. It could be _better_.

>A favourite template would be one of the functions which nobody uses

Not sure, especially for people aware of this feature.

> or , at worst, which confuses people because the new documents are not empty and where do I change that again ...

TXS's "File" menu could provide the following entries:

- "New (empty file) ... <kbd>Ctrl</kbd> + <kbd>N</kbd>"
- "New (favorite template) ... <kbd>Alt</kbd> + <kbd>N</kbd>"
- "New (other templates)..."

**Comment by timhoffm** [comment]
I agree with @sunderme that it's not worth adding a favourite concept. That would have to be configured somewhere explicitly again. Also, "New Favourite..." is not concept I have been seen anywhere else. Thus it appears there is little need for that and users are not accustomed to it. If anything, a "most recent templates" submenu would be more reasonable.

But more generally, overcrowding the menu makes a software less user-friendly not more. A better way might be a startup screen like QtCreator. That could have
- open last project
- a list of most recent projects
- new empty file
- new with wizard
- new from a list of most recent templates

**Comment by dbitouze** [comment]
>That would have to be configured somewhere explicitly again.

Indeed. That could be configured through radio buttons in front of each template in the "Select LaTeX Template" window when it is reached through:

- either "File → New (other templates)..." entry (currently "File → New from template..."),
- or "New (favorite template) ... <kbd>Alt</kbd> + <kbd>N</kbd>" if a favorite template has not been chosen already.

>Also, "New Favourite..." is not concept I have been seen anywhere else.

Indeed. But typesetting documents with LaTeX is something special.

>Thus it appears there is little need for that and users are not accustomed to it.

If users don't know or even imagine such a feature, definitely they don't miss it and even fewer are accustomed to it. 

The same happens with newbies in LaTeX coming from word processor world: they even couldn't imagine some of the LaTeX's killing features they are very happy to learn, and not accustomed to them.

>If anything, a "most recent templates" submenu would be more reasonable.

This would lead to an extra step. IMO, "New (favorite template) ... <kbd>Alt</kbd> + <kbd>N</kbd>" would be better.

>But more generally, overcrowding the menu makes a software less user-friendly not more.

My proposal would add just a single entry in the "File" menu. If you want to reduce the overcrowding of this menu, the very uncommon and I'm pretty sure very rarely used "Fifix" entry and all its subentries could be dropped.

>A better way might be a startup screen like QtCreator. That could have [...]
>-    new from a list of most recent templates

Okay but still an extra step compared to my proposal. I would add:

- new file from favorite template
