### ISSUE TITLE
TexStudio 2.12.16 et Linux Mint 19 : impossible à compiler

### ISSUE THREAD

**Issue by christophePoulain** [texstudio-org/texstudio#776]
Bonsoir,

j'ai essayé de compiler txs sous linux mint 19.
Avec qt4,  "poppler-qt4" n'est pas trouvé et il n'est pas disponible dans la base de l'installateur de la linux mint (je ne l'ai pas trouvé à l'aide de synaptic)
Avec qt5, "qt5 : module scripts et uitools non trouvés". Alors qu'il me semble avoir installé tout les modules qt5.
J'utilse la Tex Live 2019, installée manuellement.

J'ai effectué, en root :
./BUILD.sh ou qmake ou qtcreator : les mêmes erreurs reviennent.

**Comment by dbitouze** [comment]
Hi Christophe,

it is an English spoken repository here :)

**Comment by christophePoulain** [comment]
Hi Denis,
sorry, i believe there are some french users :)
So, I describe my problem in english (sorry for my poor english)
On Linux Mint 19, txs doesn't compile.
With qt4, the script BUILD.sh says "poppler-qt4" is absent. But, I don't find it in database with synaptic.
With qt5, the same script says "module scripts and uitools not find". Therefore, i think I installed all qt5's module.
With qmake or qtcreator, same errors.
I use TL 2019.

**Comment by MeanSquaredError** [comment]
Please paste the actual output from BUILD.sh. You can try
BUILD.sh 2>&1 | tee error.out
to capture the error output to error.out and then paste the file error.out here. We would need the errors both from build attempts with Qt4 and Qt5.

**Comment by christophePoulain** [comment]
With qt 4 :
TeXstudio compilation :
----------------------------------------
Enter SYSTEM (1: UNIX ; 2: MACOSX) (default is 1) :
Enter PREFIX (/usr , /usr/local or /opt) (default is /usr/local) :
Enter path to QT4/5 (e.g. /usr/lib/qt4, you can leave it empty if qmake is in P$
Do you want to use the internal pdf viewer (requires the Poppler library)? (yes$
Do you want to use the video player in pdf files (requires the Phonon library)?$
Do you want to build a debug or release version? (default is debug) :
Do you want to include tests in the debug build? (yes/no) (default is yes) :
Starting compilation
Project MESSAGE: Building with Qt4
Project ERROR: Package poppler-qt4 not found
make: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.
Compilation done
make: *** Aucune règle pour fabriquer la cible « install ». Arrêt.
Compilation and installation done
Icons and desktop file can be found in the /usr/local/share/texstudio directory

---------------------
with qt5 : 
TeXstudio compilation :
----------------------------------------
Enter SYSTEM (1: UNIX ; 2: MACOSX) (default is 1) :
Enter PREFIX (/usr , /usr/local or /opt) (default is /usr/local) :
Enter path to QT4/5 (e.g. /usr/lib/qt4, you can leave it empty if qmake is in P$
Do you want to use the internal pdf viewer (requires the Poppler library)? (yes$
Do you want to use the video player in pdf files (requires the Phonon library)?$
Do you want to build a debug or release version? (default is debug) :
Do you want to include tests in the debug build? (yes/no) (default is yes) :
Starting compilation
Info: creating stash file /home/christophe/Téléchargements/texstudio-2.12.16/.q$
Project MESSAGE: Building with Qt5
Project ERROR: Unknown module(s) in QT: script uitools
make: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.
Compilation done
make: *** Aucune règle pour fabriquer la cible « install ». Arrêt.
Compilation and installation done
Icons and desktop file can be found in the /usr/local/share/texstudio directory

**Comment by sunderme** [comment]
latest ubuntu, and therefore probably linux mint as well, don't offer poppler-qt4.
Hence you can't compile txs with qt4.

for qt5, you need following packages on your system:
qtbase5-dev,libqt5svg5-dev,qtscript5-dev,qttools5-dev,libpoppler-qt5-dev

**Comment by MeanSquaredError** [comment]
Actually, BUILD.sh asks you if you want to use the internal PDF viewer so if you say "no" to that question it might be able to build the source without poppler. Of course you would have to use an external viewer, which is not very convenient.

On a side note, @sunderme , I think that https://github.com/texstudio-org/texstudio/pull/761 is ready for a review and inclusion (if the code is good enough). So please take a look whenever you have the time. It still has a TODO comment, but I added it just to record an additional idea.
