### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by bijang** [texstudio-org/texstudio#777]
Please could look at the application on linux (kde in my case). Dark colour theme, the text input doesn't play well with it

**Comment by timhoffm** [comment]
Please post a screenshot to illustrate your issue.

**Comment by bijang** [comment]
![Screenshot_20191104_005609](https://user-images.githubusercontent.com/15066720/68095061-54a68d80-fe9e-11e9-80a9-0037435f9544.png)
![Screenshot_20191104_005543](https://user-images.githubusercontent.com/15066720/68095062-54a68d80-fe9e-11e9-852f-7f8f4352e3dd.png)

**Comment by foreachthing** [comment]
Change any of these colors (in _current_) to your liking:

![image](https://user-images.githubusercontent.com/10420187/68102908-082a7480-fed5-11e9-9354-a240b3b50ec4.png)
