### ISSUE TITLE
Performing copy and paste of a multi-line block loses indentation (on Mac)

### ISSUE THREAD

**Issue by cfries** [texstudio-org/texstudio#778]
### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.3
- OS: Mac
- TeX distribution: TeXLive

### Expected behavior

Copy and paste of block with indentation, say

```
    1
    2
    3
```

should result in exactly this block, i.e.,

```
    1
    2
    3
```

### Actual behavior

Copy and paste of block with indentation, say

```
    1
    2
    3
```

results in a block where indentation is lost after the second line, i.e.,

```
    1
2
3
```

### How to reproduce

Copy and paste a multi-line block with indentation (on macOS version of TeXStudio).

**Comment by sunderme** [comment]
the indentation can be controlled (somewhat) via options/editor/indentation mode

"keep indentation" is probably what you want.
