### ISSUE TITLE
Links dead

### ISSUE THREAD

**Issue by christophePoulain** [texstudio-org/texstudio#779]
Hi,

in the download page, the two links below are "dead"  : 

http://download.opensuse.org/repositories/home:/jsundermeyer/Debian_9.0/amd64/texstudio_2.12.16-1+2.1_amd64.deb

and

http://download.opensuse.org/repositories/home:/jsundermeyer/xUbuntu_19.04/amd64/texstudio_2.12.16-1+2.1_amd64.deb

**Comment by sunderme** [comment]
true, but where are the links from ?

**Comment by sunderme** [comment]
because texstudio.org seema to be fine

**Comment by christophePoulain** [comment]
I don't understand...
yesterday, links on texstudio.org were dead...
