### ISSUE TITLE
Linux Appimage : language "french" not present

### ISSUE THREAD

**Issue by christophePoulain** [texstudio-org/texstudio#780]
Hi,

when I use the appimage here :+1: 

https://github.com/texstudio-org/texstudio/releases/download/2.12.16/texstudio-2.12.16-x86_64.AppImage

in Configure -> Options -> Language, only "default" and "en" are present.

Not french language...

### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution:

**Comment by sunderme** [comment]
fixed with latest commits
spell checker dictionaries/thesaurus can be found in  [txs-app-dir]/../share/textsudio if they are not detected automatically
