### ISSUE TITLE
Feature request: Menu item to open config file

### ISSUE THREAD

**Issue by MikeTheGreat** [texstudio-org/texstudio#784]
Issue [# 1 in this other repo](https://github.com/Francis-Hsu/TeXstudio_Solarized/issues/1) is one of the top search results for finding TeXStudio's config file.

Clearly TeXStudio knows :)

**It would be great to have something like Edit->Preferences, even if the only thing it does is open the config file for you.**

### Environment
- TeXstudio 2.12.16 (git 2.12.16)
- Qt: Using Qt Version 5.12.1, compiled with Qt 5.12.1 R
- OS: Windows 10
- TeX distribution: miktex

**Comment by MikeTheGreat** [comment]
Looks like there's an Options menu already.
I'mma go refill my coffee because clearly I need it :)

**Comment by timhoffm** [comment]
I would not open the config file
