### ISSUE TITLE
Need for text function: converting individual lines to one paragraph.

### ISSUE THREAD

**Issue by YuryPakhomov** [texstudio-org/texstudio#785]
### Environment
- TeXstudio: last
- OS: Linux
- TeX distribution: texlive

### Expected behavior
I need for text function which converts individual lines to one paragraph.
I expecte to run this function when I select text block. Often copying text is formatted by individual lines ending with a newline character, i.e. they are like paragraph (one line is one paragraph).  However I want one string wrapped by texstudio editor. 
This function is available in Kile (Merge Rows or Ctrl-J hotkey).

**Comment by timhoffm** [comment]
You can use `Idefix -> Hard Line Break...`, set the line length to a very large value (e.g. 10000) and enable `Join lines before wrapping`.

**Comment by sunderme** [comment]
you can add a macro which adds this functionality via
macro/edit macro/browse/addedFeatures/joinLines ...
