### ISSUE TITLE
"full path" and "relative path" used in import.cwl are not documented

### ISSUE THREAD

**Issue by AkariAkaori** [texstudio-org/texstudio#786]
There seems to be a special argument name for cwl files "full path" and "relative path" used in [import.cwl](https://github.com/texstudio-org/texstudio/blob/master/completion/import.cwl) but these are nowhere mentioned in the cwl section of the user manual, is it possible to document these?

[Screenshot showing that the path arguments are used](https://i.imgur.com/gIqpCyK.png)

**Comment by MeanSquaredError** [comment]
"full path" and "relative path" seem to be regular argument names. 

At least there is no special handling for these names in in latexpackage.cpp in 
Token::TokenType tokenTypeFromCwlArg(QString arg, QString definition)

**Comment by AkariAkaori** [comment]
Looks like I was mistaken, it seems to be hardcoded at https://github.com/texstudio-org/texstudio/blob/6b082485518a50f5465607d3f7e39384bd87f378/src/latexdocument.cpp#L1055.
