### ISSUE TITLE
"Show Only Monospaced Fonts" choice should be persistent

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#788]
### Environment
- TeXstudio: 2.12.16 (git 2.12.16-108-g1786d152)
- Qt: 5.12.2
- OS: Linux Mageia 7
- TeX distribution: TeX Live 2019

### Expected behavior
"Show Only Monospaced Fonts" choice in menu Options → Configure TeXstudio... → Editor is persistent. Hence, the user who wants a monospaced font<sup>1</sup> but doesn't know which one to choose, doesn't have to re-enable this option at each trial.

### Actual behavior
"Show Only Monospaced Fonts" choice in menu Options → Configure TeXstudio... → Editor is not persistent.

### How to reproduce
1. Visit the menu Options → Configure TeXstudio... → Editor.
2. On this window, enable "Show Only Monospaced Fonts".
1. Click on OK.
1. Visit the menu Options → Configure TeXstudio... → Editor.
1. "Show Only Monospaced Fonts" is not enabled.

---
<sup>1</sup>IMHO, monospaced fonts should be the default at least since, with other fonts, LaTeX → Manipulate Tables → Align Columns looks to be not working.

**Comment by sunderme** [comment]
why should it be persistent ?
The main problem is, that it does not show the current selected font if it is not mono spaced and the filter is on ...
I would go for not changing current behaviour (unless there is a compelling argument)

**Comment by dbitouze** [comment]
> why should it be persistent ?

Because, as said, the user who is looking for a monospaced font but doesn't know which one to choose, currently have to re-enable this option at each trial.

> The main problem is, that it does not show the current selected font if it is not mono spaced and the filter is on ...

I don't see your point. Why would it be interesting to show the current selected font? And, in any case, the user is able to disable "Show Only Monospaced Fonts" to see the list of all fonts. Admittedly, the current selected font could be shown in addition to the monospaced ones.

**Comment by sunderme** [comment]
so, you are talking about 
activating a mono space font, selecting one font and leaving the option dialog,
then opening the option dialog again to chose a different one ?

**Comment by dbitouze** [comment]
Indeed. AFAIU, the only purpose of this "Show Only Monospaced Fonts" option is to make a choice among the many monospaced  fonts available.

**Comment by timhoffm** [comment]
One could automatically deactivate `Show Only Monospaced Fonts` if the current font is not monospaced.

Changing the font is a very rare operation so that it's hardly worth any extra effort. Then again, if one wants to find a good font, one has to cycle through them, while each time opening the dialog. There, it could be a bit annoying to activate it every time. But overall it's still quite complicated and font selection is better done in a wyswyg text processor like LibreOffice or Word on using a font table.

**Comment by dbitouze** [comment]
> One could automatically deactivate `Show Only Monospaced Fonts` if the current font is not monospaced.

Sorry, I don't understand what you mean here.

> Changing the font is a very rare operation so that it's hardly worth any extra effort.

A tiny effort for the eternity? ;)

>  Then again, if one wants to find a good font, one has to cycle through them, while each time opening the dialog.

I'm not sure to understand either. Do you mean "instead of each time opening the dialog"?

> There, it could be a bit annoying to activate it every time.

I'm not sure to understand either: it _currently_ is ~~a bit~~ quite annoying to activate it every time.

> But overall it's still quite complicated and font selection is better done in a wyswyg text processor like LibreOffice or Word on using a font table.

I disagree:

- LibreOffice (at least) doesn't let you filter monospaced fonts,
- you cannot figure out the exact result (e.g. no LaTeX syntax highlighting).

**Comment by octaeder** [comment]
> The main problem is, that it does not show the current selected font if it is not mono spaced and the filter is on ... I would go for not changing current behaviour (unless there is a compelling argument)

I think this is an impossible case because when you check the monospaced fonts only option then the combobox immediately shows (and thus selects) the first available mono spaced font (i.e. consolas). And if you now cancel the dialog both combobox and option turn back to their old values.

Should I try to do so?

**Comment by octaeder** [comment]
Note: Even if you have selected a monospaced font and option monospaced fonts only is set, end txs and then change the editor font to Arial in the ini file no problem arises. Txs starts with Arial and option monospaced fonts only set. Arial is shown in the combobox and the dropdown list shows monospaced fonts only below. When you select a font from the list then Arial is no longer available until you allow the list to show all fonts.
