### ISSUE TITLE
Running TexStudio in a docker container

### ISSUE THREAD

**Issue by sumandoc** [texstudio-org/texstudio#79]
Hi there,

Using TeXStudio for writing TeX documents is painless.

**My Wish**
If we are able to run TeXStudio in docker container that also contains TeXLive distribution and access via browser, it would be very smooth for anyone using LaTeX (including beginners). They don't need to bother about installation difficulties in any operating system.
It would be an elegant option.

For accomplishing similar job [RStudio](https://www.rstudio.com/) came up with the idea of RStudio **server** and its [docker images](https://hub.docker.com/u/rocker/) where anyone can access RStudio running in a docker container via web browser. Its very smooth running R and RStudio and can even be deployed in cloud. Instructions on running one is [provided here](https://hub.docker.com/r/rocker/rstudio/).

I was wondering if similar can be done regarding TeXStudio. Its rich set of features combined with TeXLive running in a container and using it via web browser would be super exciting.
Using it will be similarly hassle free without the need of knowing OS dependent details.
I have even built an image containing [TeXLive-2017](https://hub.docker.com/r/sumdoc/texlive-2017/).

Regards,
Suman

**Comment by benibela** [comment]
Have you looked at these projects?

https://github.com/hvarga/latex-docker

https://github.com/raabf/dockertex

https://github.com/nindanaoto/texstudio-docker

https://github.com/dit4c/dockerfile-dit4c-container-texstudio

But texstudio won't run in a webbrowser

**Comment by sumandoc** [comment]
Yes, I saw few of those. 
But I found all those cumbersome and its not as clean as **RStudio**.

**Comment by sunderme** [comment]
well, we will not provide a docker image as it has really no advantages

**Comment by sunderme** [comment]
possibly, but that is completely up to you, no support, whatsoever

**Comment by smihael** [comment]
any updates on that?

**Comment by trunc8** [comment]
I spent an evening and solved it. I have [added the instructions to my blog](https://trunc8.github.io/2021/05/22/tut-texstudio-docker), hope they can help someone.

**Comment by trunc8** [comment]
> well, we will not provide a docker image as it has really no advantages

@sunderme not the fault of TeXstudio, but I had fonts conflict between the TeXLive's extra-fonts and Font Awesome. Hope that illustrates one possible advantage.
