### ISSUE TITLE
SyncTeX jumps to pgflibraryfadings in TeXstudio with todonotes

### ISSUE THREAD

**Issue by NittanyLion** [texstudio-org/texstudio#794]
### Environment
- TeXstudio:  TeXstudio 2.12.14 (2.12.14+debian-1)
- Qt:  Qt Version 5.12.4, compiled with Qt 5.11.2 R
- OS:  Ubuntu 19.10
- TeX distribution:  texlive

### Expected behavior

If I ctrl + mouse click on the output text in TeXstudio with the code below then I would expect it to take me to the corresponding input text.   (LuaTeX engine)

\documentclass[12pt]{letter}
\usepackage{todonotes}
\usepackage{lipsum}
\begin{document}
\lipsum
\end{document}

### Actual behavior

It takes me to pgflibraryfadings.code.tex.

### How to reproduce

Build the above code.

**Comment by muzimuzhi** [comment]
Interesting. Your problem is reproducible only with `lualatex` (I am in macOS). With `xelatex` or `pdflatex`, the problem will not reproduce.

To simplify the example, I also find that
```tex
\usepackage{tikz}
```
is safe, but loading tikz libraray `fadings` like
```tex
\usepackage{tikz}
\usetikzlibrary{fadings}
```
is problematic. Other tikz libraries like `calc` or `positioning` will not cause the problem.

------
The click-and-skip function is provided by synctex program and corresponding to the `xxx.synctex.gz` auxiliary file. Hence the only difference between engines are the synctex files.

**Comment by NittanyLion** [comment]
Thank you @muzimuzhi   I'm surprised that there are differences between the synctex files, but that information is helpful.

**Comment by sunderme** [comment]
since it is rather a lualatex problem, there is nothing we can do.

**Comment by MrI2C** [comment]
I have the same issue, but not with all files. and i'm not loading any fading packets..
'''
\usepackage{circuitikz}[american]
\ctikzset{american voltages}  % Set American voltage style
\ctikzset{diodes/scale=0.8} % the standard diodes are a bit big
\ctikzset{transistors/arrow pos=end} %places the arrow more ath the end

**Comment by octaeder** [comment]
What's your environment? Can you provide a complete minimal example?
I tested the original case with Win10, txs 4.8.5beta2-4 (local msys2 build of current dev), and there's no issue. Maybe you need to upgrade?

**Comment by MrI2C** [comment]
I'm using win11 and TexStudio and LuaLaTeX . It's only a problem on the first page when going from the right pdf-part to code via GoToSource.

TeXstudio 4.8.4 (git 4.8.4)
Using Qt Version 6.7.2, compiled with Qt 6.7.2 R

Project home site: https://texstudio.org/
Latest stable version: 4.8.4
[Changelog](file:///C:/Program%20Files/texstudio/help/CHANGELOG.md)
