### ISSUE TITLE
texstudio.org - "Download"-button not working

### ISSUE THREAD

**Issue by N-Olbert** [texstudio-org/texstudio#797]
# Environment
- TeXstudio: -
- Qt: -
- OS: Windows 10 1903
- TeX distribution: -

### Expected behavior
I should be able to download the texstudio installer when visiting http://texstudio.org

### Actual behavior
The download button exists, but no href is set
![image](https://user-images.githubusercontent.com/45466413/68929591-e9f22d80-078c-11ea-8eaf-7cadd9a76884.png)

### How to reproduce
Use Edge or Firefox (havent tested it with Chrome) without any extensions -> Navigate to http://texstudio.org -> click the download button -> nothing happens.

**Comment by tusindfryd** [comment]
Fixed the issue in this pull request: https://github.com/texstudio-org/texstudio-meta/pull/3

**Comment by retifrav** [comment]
Still present, the `href=""` attribute is empty.

**Comment by timhoffm** [comment]
Fixed with the release of 2.12.18.
