### ISSUE TITLE
Feature request: Favourite header statements

### ISSUE THREAD

**Issue by PaulEJKing** [texstudio-org/texstudio#798]
Beyond the use of the wizard, there should be an entry on the wizard for additional lines of header code. I have additional lines with every document I write which imports the same packages, and have the same changes of the base font. This would be simply pasted on to the Tex source with the rest of the header.

**Comment by muzimuzhi** [comment]
Can the menu item "Macros -> Edit Macros ..." help you?

**Comment by timhoffm** [comment]
Maybe `File -> Make Template...` and `File -> New From Temaplate...` is what you are looking for.

**Comment by PaulEJKing** [comment]
Looks good. Too bad it can't target parts of the code such as the header. Still, a good workaround.

**Comment by sunderme** [comment]
I don't see any point to change something.
