### ISSUE TITLE
Random menu categories not accessible after using editor for extended period of time

### ISSUE THREAD

**Issue by amagidow** [texstudio-org/texstudio#8]
In TeXstudio 2.12.6, on Windows 10, after I have used the editor for some time, I am no longer able to access all of the menus. This appear to affect different menus at different times, so at the moment selecting the "LaTeX" menu works fine, but clicking on "Tools" or "File" does not. Other times it has been an issue with a different set of menus. I had trouble getting the spell-checking context menu to open as well. Restarting TeXStudio fixes the problem. I have not yet been able to trace this to a particular action to make it entirely reproducible, but I wanted to bring attention to the issue. I will update this issue as I find triggers for the bug.

**Comment by a-stark** [comment]
I can confirm that behaviour on Windows 7 with TeXstudio 2.12.6 (hg 6632:777b2b8a906). I mostly encounter this for the spell-checking context menu in the editor, after having the TeXstudio open for about 30min or longer, at some random time the context menu is not accessible any more (right-click on the wrongly written word will not open the context menu). Until now, I also did not find a way to reproduce deliberately this problem.

I also did not track the origin of this bug
After having open Te

**Comment by timhoffm** [comment]
I've seen the same behavior in QtCreator. Therefore, I assume it's a Qt bug.

So far I've not found a bug report in the Qt tracker. However, without reproducibility it's difficult to generate an useful upstream bug report.

**Comment by texfriend** [comment]
I'm experiencing the same issue with Texstudio 2.12.6 and Windows 8.1. The time period after which menues disappear seems to be pretty random on my system.
I understand it is hard to fix, but I think this is a very serious problem. That menus disappear randomly during work renders Texstudio virtually unusable for me and probably others too.

**Comment by genodeftest** [comment]
See also: https://sourceforge.net/p/texstudio/bugs/2321/

**Comment by Dirk7589** [comment]
I experience the same issue with Windows 10, using Texstudio 2.12.6. If there is a way to run the application with debugging/ more verbose logging/ asserts enabled, I would be happy to do so to try and catch the bug. It occurs pretty frequently for me.

**Comment by ZaydH** [comment]
I have seen this issue with MacOS X 10.13.4 (17E199) although I saw it previously with OS X 10.13.3.  I experience it on TexStudio 2.12.8 (I do not recall seeing it with 2.12.6).

For me, it primarily
<img width="180" alt="screenshot at apr 09 05-03-58" src="https://user-images.githubusercontent.com/6292018/38496745-75453be0-3bb3-11e8-804d-ea33767d32b5.png">
 affects the "TexStudio" menu.  When the issue occurs, I cannot access Preferences even by using the hotkey "Command + ,".

**Comment by sunderme** [comment]
concerns very old version
