### ISSUE TITLE
Missing section in Structure view

### ISSUE THREAD

**Issue by pjattke** [texstudio-org/texstudio#800]
### Environment
- TeXstudio: v2.12.16
- Qt: 5.12.3
- OS: macOS 10.15.1
- TeX distribution: basicTeX

### Problem description

A code snippet is added using the `listings` package. The `lstlisting` environment accepts options to define a caption. If this caption contains any command (e.g., `\texttt{main.cpp}` or `\ac{DHCP}`), then the Structure view in TexStudio breaks—any sections from there on are not listed anymore.

### Expected behavior

The section "SubsectionTwo" should appear in the Structure View of the document.

### Actual behavior

The section "SubsectionTwo" is missing.

### How to reproduce

Minimum working example:

```LaTeX
\documentclass[10pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{listings}

\begin{document}

\section{SectionOne}
\subsection{SubsectionOne}

\begin{lstlisting}[caption={Lorem ipsum {\texttt{abc}}]
	int c = 4;
\end{lstlisting}

\subsection{SubsectionTwo}  % <<< missing in Structure view

\end{document}
```

Output of the Structure view:

<img width="239" alt="CleanShot 2019-11-17 at 20 11 53@2x" src="https://user-images.githubusercontent.com/21377443/69012480-b246d980-0976-11ea-8ffc-c99b0adf48f1.png">

**Comment by mehlukas** [comment]
I don't get why this was closed since I can reproduce this bug perfectly.

It seems like using `lstlisting` breaks something.
@pjattke my workaround is to read the code from an external file using `\lstinputlisting{...}`.

**Comment by sunderme** [comment]
the example above is incorrect. (try to compile it).
If it is corrected (matching braces), structure view is fine. So there is no indication that something is amiss here.

**Comment by pjattke** [comment]
@sunderme That's true, in the MWE was a bracket missing. Thanks for pointing that out! However, it was indeed a bug and in TeXstudio 2.12.16 it leads to the described behavior (missing section in structure view).

**Comment by sunderme** [comment]
yes, it did and it is fixed in more recent versions.

**Comment by mehlukas** [comment]
Thanks for the feedback! I had another look into this and I agree, with the above example I cannot reproduce the bug.
However, it seems like when the square brackets `[..]` are not present when beginning the `lstlisting` environment, the bug still occurs.
Here is my MWE:
```
\documentclass[10pt,a4paper]{article}

\usepackage{listings}

\begin{document}
\section{SectionOne}

\subsection{SubsectionOne}

\begin{lstlisting}
test;
\end{lstlisting}

\subsection{SubsectionTwo}  % <<< missing in Structure view
\end{document}
```
Thanks in advance for your help!

**Comment by sunderme** [comment]
should be fixed now
