### ISSUE TITLE
Question about execCommand()

### ISSUE THREAD

**Issue by MeanSquaredError** [texstudio-org/texstudio#802]
@timhoffm , @sunderme , @benibela 

Hi,

This is a question for the developers of TXS. I am trying to cleanup the code in latexstyleparser.cpp which invokes external programs like pdflatex but fails to set the search path for these programs so their invocation fails on some platforms (the most recent such bug is https://github.com/texstudio-org/texstudio/issues/768 ) There are various places where QProcess is used, so I'd like to write a common wrapper for QProcess or preferably use an existing wrapper function. The wrapper would setup the search path for the executable before actually running the executable pretty much like ProcessX does.

ProcessX is too specialized, so it is not suitable for a generic QProcess wrapper. However there is one other method,
`QString execCommand(const QString &cmd,QString additionalPaths="");`
from utilsSystem.cpp

It seems to be doing almost everything that I need and it even receives an optional string argument `additionalPaths`. However this `additionalPaths` is not the path that the command is searched for, but the paths that are added to the PATH of the new process.

After some looking through the code it seems that the only caller that specifies additional paths is `KpathSeaParser::kpsewhich()` which executes kpsewhich and passes it some additional paths which are taken from `BuildManager::additionalSearchPaths`.

It really seems to me that the original intention was to specify the paths where to search for the executed command and not to augment the environment of the executed command itself. After all what would someone want to adjust the PATH variable of kpsewhich? It has its own path variables and (I think but might be wrong) that kpsewhich does not use PATH when searching.

So I am planning to modify execCommand so that `additionalPaths` would be the paths where to search for the actual executable (instead of just augmenting the environment of the executable itself).

Can anyone comment on this? Do you see any pitfalls?

**Comment by MeanSquaredError** [comment]
OK, cleaned up the program execution code and moved it to a separate class called `ExecProgram` which is similar to ProcessX but much simpler. If everything works well it will be a replacement for `execCommand`. If tests show no problem I will provide a patch which will also fix  #768

**Comment by MeanSquaredError** [comment]
OK, I built a test branch with the new ExecProgram code. It passes the tests and seems to work OK in the sense that it autogenerates .cwl and runs correctly various external commands (granted I did not do heavy testing). If it fixes #768 then I will make it into a PR.

**Comment by muzimuzhi** [comment]
@MeanSquaredError 
The extra-logging branch at commit https://github.com/MeanSquaredError/texstudio/commit/53c5f424d6d78f92200ef93398fb5b60ae745151 does not fix the problem. 

 - If opened from spotlight, apart from not auto-generating cwl files, texstudio cannot even compile tex files and returns
    ```
    Error: Could not start the command: xelatex -synctex=1 -interaction=nonstopmode "tkz-test".tex
    ```
    in (lower-left) Messages panel
    ![image](https://user-images.githubusercontent.com/6376638/69374110-55ce1c00-0ce0-11ea-9b19-1f5ed45312a7.png)

 - If opened from terminal, texstudio works alright.

logs
 - [open_from_spotlight.log](https://github.com/texstudio-org/texstudio/files/3876637/open_from_spotlight.log)
 - [open_from_terminal.log](https://github.com/texstudio-org/texstudio/files/3876639/open_from_terminal.log)

**Comment by MeanSquaredError** [comment]
I am closing this issue, but anyone can comment in the actual PR https://github.com/texstudio-org/texstudio/pull/803
