### ISSUE TITLE
Do not distinguish advanced options

### ISSUE THREAD

**Issue by timhoffm** [texstudio-org/texstudio#813]
Thinking about #811, should we remove the concept of advanced options altogether?

Advanced options were originally intended to make common options easier accessible.

- It's not unambigously clear which options should be advanced and which not.
- In particular having a separate "Advanced Editor" tab, separates logically related configs (e.g. appearance, see #811) into different parts of the config.
- Accessibility in the large set of all options increased by the search functionality.
- The extra effort of activating advanced options can perceived as bad usability (#804).
- I don't know any other software, that uses this concept on GUI level.

**Comment by sunderme** [comment]
chrome uses a menu point „extended“ for more options and spme are hidden in //config.
I think that txs‘ concept is not bad, maybe some tidying necessary...

**Comment by dbitouze** [comment]
> I don't know any other software, that uses this concept on GUI level.

What I've already seen (though I don't remember where) is a "More Options" link (on each config panel) that makes visible some more advanced options.

**Comment by MeanSquaredError** [comment]
Originally when I started using TXS it took me a while to find out that there are advanced options, so +1 to the idea of merging the two.

If not remove them then the other option would be to make the advanced options more visible.

**Comment by octaeder** [comment]
I think current state is a good solution. For a long time now the dialog also remembers the state of the checkbox _Show Advanced Options_.

![image](https://github.com/texstudio-org/texstudio/assets/102688820/4d110b19-5bba-42a6-9c80-049f744a8c87)

I would suggest closing this case.

**Comment by sunderme** [comment]
I agree, no change planned
