### ISSUE TITLE
TeXstudio GUI is very unfriendly for high resolution screen

### ISSUE THREAD

**Issue by Reformatsky** [texstudio-org/texstudio#817]
### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.1
- OS: Windows 10
- TeX distribution: MiKTeX

### Expected behavior
The icons in GUI should have proper size under high resolution environment ( > 2K screen).

### Actual behavior
However, the icons (buttons) are too small to be visible, including the icons in menu, left control bar, etc. And it seems there is no way to adjust its size in preference setting.

### How to reproduce
Every times.

**Comment by foreachthing** [comment]
I got a 4k screen and all is fine (not this one though)!
Just use the GUI-scaling...
![image](https://user-images.githubusercontent.com/10420187/69720581-3fc2c000-1113-11ea-8df1-e9df166192dc.png)

**Comment by nityesha** [comment]
On my 4K Dell laptop screen, using version 2.12.16, the scrolling of text by the mousewheel or trackpad does not work, which working fine with the previous version 2.12.14. However, scrolling works fine on a lower resolution monitor.

**Comment by sunderme** [comment]
No feedback
