### ISSUE TITLE
Go to Source/PDF does not work

### ISSUE THREAD

**Issue by wodhr1541** [texstudio-org/texstudio#818]
### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Actual behavior
When I click go to source or go to pdf it does not work.

**Comment by muzimuzhi** [comment]
To provide "go to source/pdf" function, texstudio needs three files (in the same directory)
```
main.tex
main.pdf
main.synctex.gz
```

 - Do your local files containing the "xxx.synctex.gz" one?
 - If the three-file requirement are satisfied, can you provide a three-file example so that others can test it?

**Comment by wodhr1541** [comment]
I check that my folder contains xxx.synctex.gz file.
I send you my files.

Thanks.

2019년 11월 29일 (금) 오전 11:16, muzimuzhi <notifications@github.com>님이 작성:

**Comment by muzimuzhi** [comment]
@wodhr1541 
Your files are not shown in your last comment. From this [github blog](https://github.blog/2011-03-10-reply-to-comments-from-email/), 
> Email attachments are currently ignored (when replying to comments from email). There’s no place to upload assets to issues or comments anyway.

To upload files, you may need to reply in the github's webpage.

**Comment by wodhr1541** [comment]
Is it works?

[PH612.zip](https://github.com/texstudio-org/texstudio/files/3909293/PH612.zip)

**Comment by muzimuzhi** [comment]
@wodhr1541 
> Is it works?

Yes. I will take a look at your files.

**Comment by muzimuzhi** [comment]
I tested on your uploaded three-file pairs using texstudio, vscode + latex-workshop, and overleaf.com, neither of their go-to-source/pdf function can work correctly. If I recompile the `.tex` file, then each of them works alright. I installed a texlive 2019 locally on macOS and overleaf uses texlive 2018.

I guess there is something wrong in your uploaded synctex file. What latex distribution and operation system do you use?

**Comment by wodhr1541** [comment]
I find the reason for this problem.
I think that it is due to my google drive.
I saved .tex, .pdf, .synctex.gz files in my google drive.
The files in other folder works well.
Is there any ways to solve this problem?

Thanks. Regards

2019년 12월 2일 (월) 오후 1:26, muzimuzhi <notifications@github.com>님이 작성:

**Comment by muzimuzhi** [comment]
Related: #331, #614
