### ISSUE TITLE
PDF file cannot be openned using Acrobat 

### ISSUE THREAD

**Issue by hou2** [texstudio-org/texstudio#827]
### Environment
- TeXstudio:   2.12.16
- Qt:   5.12.1
- OS:  Windows(10)
- TeX distribution:  texlive

### Actual behavior
It really weird when I choose PdfLaTex as the default compiler and select build & view option as Complie & View, then generated pdf file cannot be openned with Adobe Acrobat Pro DC. 

It works really well when I compile the tex file and the generated pdf file looks really good in the default PDF Viewer of texstudio. But the generated pdf  file can not be openned with Adobe Acrobat Pro DC. It says on the popped up windows that  An Error Exists on this Page and Acrobat may not display the page correctly. And it appears that pages are totally blank in Acrobat.

But if I choose other compiler as default compiler, like XeLaTex, or choose build & view option as DVI->PS->PDF chain, the problem will disappear.

**Comment by muzimuzhi** [comment]
If you directly compile the tex file in `cmd.exe` and using pdflatex, does the problem re-produce?

**Comment by hou2** [comment]
Yes, the problem still exists if I compile the tex file in cmd.exe with PdfLatex. So, I think the problem is not caused by TexStudio.

Thank you for your help.

**Comment by timhoffm** [comment]
Thanks for the feedback.

**Comment by dbitouze** [comment]
@hou2 Adobe Acrobat is known for preventing any change in any `.pdf` file open with. Hence, if `foo.pdf`, generated by compilation of `foo.tex`, is open with Acrobat, it is impossible to recompile the latter until the former is closed. IIRC, they are workarounds but I don't remember them.

But are you sure you need Adobe Acrobat to check the `.pdf` files you generate? Isn't the TXS' viewer enough? If not, you could have a look at [SumatraPDF](https://www.sumatrapdfreader.org/free-pdf-reader.html) which is a free, powerful, small, portable and very quickly started up PDF reader for Windows.

**Comment by BunootiAggrey** [comment]
Yes, the problem still exists if I compile the tex file in cmd.exe with PdfLatex. So, I think the problem is not caused by TexStudio.

Thank you for your help.
