### ISSUE TITLE
Failed to compile latest git version of texstudio with self comipled phonon on Debian/Ubuntu/Arch lastest versions.

### ISSUE THREAD

**Issue by hongyi-zhao** [texstudio-org/texstudio#830]
Hi,

Based on the commit here: 
```
Workaround for a qmake bug when building with phonon support #829
https://github.com/texstudio-org/texstudio/pull/829
```

I try to compile latest git version of texstudio with self comipled phonon on Debian/Ubuntu/Arch lastest versions,  but all of my tries failed.  See the following for more info:

Using the latest git version of texstudio, i.e.,

```
 git log | head -5
commit 32f0ac01d5862e696b6008da91223adfa2d7b7b1
Author: MeanSquaredError <35379301+MeanSquaredError@users.noreply.github.com>
Date:   Tue Dec 10 10:10:17 2019 +0200

    Add a workaround for a qmake bug in Qt5.12.x where "QT += phonon4qt5" does not add "-lphonon4qt5" to the linker command line (#829)
```

The steps are as follows:

1. Remove the phonon installed from the repo:
$ sudo apt-get remove libphonon4qt5-dev 

2.  Install the latest git version of phonon obtained from here:

$ git clone https://github.com/KDE/phonon.git phonon.git
  # The following is a per-requisite: 
$ git clone git://anongit.kde.org/extra-cmake-modules.git extra-cmake-modules.git

Both of them are installed with the default option and location ( i.e., install under /usr/local ) from their source directory as follows:

```
mkdir build 
cd build
cmake ..
sudo make install
```
3.  Then compile the texstudio as follows from its source directory:

```
$ qmake INCLUDEPATH=/usr/local/include/phonon4qt5/phonon/ LIBS=/usr/local/lib/x86_64-linux-gnu/ PHONON=true PREFIX=/usr/local
Project MESSAGE: Building with Qt5
Project MESSAGE: GIT
Project ERROR: Unknown module(s) in QT: phonon4qt5
```

What's wrong here?  How to solve this issue?

Regards

**Comment by MeanSquaredError** [comment]
This error
`Project ERROR: Unknown module(s) in QT: phonon4qt5`
means that phonon4qt5 is not visible from qmake. Effectively it means that qmake was unable to find the corresponding file `qt_phonon4qt5.pri` which specifies the include path, library directory and library filename.

On Fedora 30 that file is located in
/usr/lib64/qt5/mkspecs/modules/qt_phonon4qt5.pri

the contents are :
```
QT.phonon4qt5.VERSION = 4.10.2
QT.phonon4qt5.MAJOR_VERSION = 4
QT.phonon4qt5.MINOR_VERSION = 10
QT.phonon4qt5.PATCH_VERSION = 2
QT.phonon4qt5.name = phonon4qt5
QT.phonon4qt5.bins =
QT.phonon4qt5.includes = /usr/include/phonon4qt5
QT.phonon4qt5.private_includes =
QT.phonon4qt5.sources =
QT.phonon4qt5.libs = /usr/lib64
QT.phonon4qt5.plugins = /usr/lib64/qt5/plugins
QT.phonon4qt5.imports = /usr/lib64/qt5/imports
QT.phonon4qt5.depends = core widgets
```

You can try creating this file and adjust the corresponding paths to match your directory layout.
This should allow TXS (and any other Qt application that uses phonon4qt5) to build with your custom libphonon.

Or even better download your Debian package for phonon4qt5, place your custom phonon sources there and build that module, install it on your system and adjust the package manager so that it does not autoupdate that package.

**Comment by MeanSquaredError** [comment]
I guess we could add an extra build option to allow custom phonon libraries, but the cleanest solution would be to fix it at OS/package level.

**Comment by MeanSquaredError** [comment]
Actually on Debian the package that connects qmake with libphonon is libphonon4qt5-dev
You can see the list of files here
`https://packages.debian.org/jessie/amd64/libphonon4qt5-dev/filelist`
The important one in your case is 
`/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_phonon4qt5.pri`
Without it qmake will not see the phonon4qt5 module.

**Comment by MeanSquaredError** [comment]
Or if you need a quick and dirty solution, just install `libphonon4qt5-dev` and then edit
` /usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_phonon4qt5.pri`
by changing the directories there to point to your custom library directories.

**Comment by hongyi-zhao** [comment]
Still confused on this issue.  See the following:

In fact, the self compiled phonon also will install a qt_phonon4qt5.pri file, which is located here for my case:

/usr/local/mkspecs/modules/qt_phonon4qt5.pri

And it has the following content:

```
$ cat /usr/local/mkspecs/modules/qt_phonon4qt5.pri
QT.phonon4qt5.VERSION = 4.11.1
QT.phonon4qt5.MAJOR_VERSION = 4
QT.phonon4qt5.MINOR_VERSION = 11
QT.phonon4qt5.PATCH_VERSION = 1
QT.phonon4qt5.name = phonon4qt5
QT.phonon4qt5.module = phonon4qt5
QT.phonon4qt5.defines = 
QT.phonon4qt5.includes = /usr/local/include/phonon4qt5
QT.phonon4qt5.private_includes =
QT.phonon4qt5.libs = /usr/local/lib/x86_64-linux-gnu
QT.phonon4qt5.depends = core widgets
```

Why the texstudio cannot find this one?

**Comment by MeanSquaredError** [comment]
Because qmake is a part of the standard installation of Qt and it does not check
`/usr/local/mkspecs/modules/`
for module .pri files. Instead it checks 
`/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/`
(or whichever is the standard Qt directory for module files)

You can try symlinking from the standard directory to that file and chances are that it will work.
```
cd /usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/
ln -s /usr/local/mkspecs/modules/qt_phonon4qt5.pri ./qt_phonon4qt5.pri
```

**Comment by hongyi-zhao** [comment]
Thanks a lot.  It does the trick.

Some my understandings/ issues based on your instructions, please comment / review / correct me:

[1] It seems the *.pri file act as the same functionality as the common *.pc files.  The qt toolchain rely on the *.pri files to find the corresponding info to construct the compiling envirnment which can be found in the *.pc files.

[2]  If I set env vars on the qmake command line which is also set in the *.pri file, in this case, which one will take effect?  

Regards

**Comment by hongyi-zhao** [comment]
Another issue:

How to make a texstudio appimage which include this cusomized lib?

**Comment by MeanSquaredError** [comment]
.pri files are included from Qt project files (.pro), so .pri files have the same syntax as .pro files
.pc files are definition files for pkgconfig, so they have different syntax and purpose.

**Comment by MeanSquaredError** [comment]
I am not involved in the appimage creation for TeXstudio so maybe someone else can comment on that.
Generally speaking you have to create a directory with all the required files and then use `appimagetool` to create an appimage from that directory. See here for details:
https://docs.appimage.org/packaging-guide/manual.html#creating-an-appimage-from-the-appdir

But then again maybe the TXS maintainers have some scripts that create the appimages.

**Comment by MeanSquaredError** [comment]
Regarding your second question
`[2] If I set env vars on the qmake command line which is also set in the *.pri file, in this case, which one will take effect?`
I have not tried it and I am not sure that the module .pri files are visible from texstudio.pro (or any other user .pro file). I would expect qmake to process those files on the fly when you do
`QT += phonon4qt5`
so maybe there is no point in time when you could change those definitions. But then again I might be wrong so you should try it. However I would not recommend relying on these implementation details because they can easily change between different versions of qmake.

**Comment by hongyi-zhao** [comment]
Maybe the more portable way is as follows:

Use var PHONON_PRI in the texstudio.pro, and add the following codes in it:

```
!isEmpty(PHONON){
    greaterThan(QT_MAJOR_VERSION, 4) { #Qt5
        # For using the self-compiled phonon4qt5, in this case,
        # the pri file may be not in standard location, so include it here:
        !isEmpty(PHONON_PRI){ 
          exists($${PHONON_PRI}/qt_phonon4qt5.pri):include($${PHONON_PRI}/qt_phonon4qt5.pri)
         }
        QT += phonon4qt5
        LIBS += -lphonon4qt5
```

Then using the following to compile:

 qmake PHONON_PRI=/usr/local/mkspecs/modules PHONON=true PREFIX=/usr/local


See my commit here:

https://github.com/hongyi-zhao/texstudio/commit/12f1be2b47651b51785474ece22a293acd030ab5

**Comment by hongyi-zhao** [comment]
I'm not familiar with the qmake language, but only based on the similar stuff used in the texstudio.pro for doing my revision.  If I'm wrong. please correct me.

Based on  the notes here:
https://doc.qt.io/qt-5/qmake-language.html#variable-expansion

`  To obtain the contents of an environment value when qmake is run, use the $$(...) operator:`

So maybe my code should revised as follows:

```
!isEmpty(PHONON){
    greaterThan(QT_MAJOR_VERSION, 4) { #Qt5
        # For using the self-compiled phonon4qt5, in this case,
        # the pri file may be not in standard location, so include it here:
        !isEmpty(PHONON_PRI){ 
          exists($$(PHONON_PRI)/qt_phonon4qt5.pri):include($$(PHONON_PRI)/qt_phonon4qt5.pri)
         }
        QT += phonon4qt5
        LIBS += -lphonon4qt5
```

Still not so clear, for this case, does all of the following forms do the same job:

```
$$(PHONON_PRI)
or
$${PHONON_PRI}
or
$$PHONON_PRI
```

Regards

**Comment by hongyi-zhao** [comment]
Based on my tries, the following forms work:

```
$${PHONON_PRI}
or
$$PHONON_PRI
```

While the following doesn't:

`$$(PHONON_PRI)`


If so, why the official document say that:
`To obtain the contents of an environment value when qmake is run, use the $$(...) operator:`

**Comment by hongyi-zhao** [comment]
> I'm not familiar with the qmake language, but only based on the similar stuff used in the texstudio.pro for doing my revision. If I'm wrong. please correct me.
> 
> Based on the notes here:
> https://doc.qt.io/qt-5/qmake-language.html#variable-expansion
> 
> ` To obtain the contents of an environment value when qmake is run, use the $$(...) operator:`
> 
> So maybe my code should revised as follows:
> 
> ```
> !isEmpty(PHONON){
>     greaterThan(QT_MAJOR_VERSION, 4) { #Qt5
>         # For using the self-compiled phonon4qt5, in this case,
>         # the pri file may be not in standard location, so include it here:
>         !isEmpty(PHONON_PRI){ 
>           exists($$(PHONON_PRI)/qt_phonon4qt5.pri):include($$(PHONON_PRI)/qt_phonon4qt5.pri)
>          }
>         QT += phonon4qt5
>         LIBS += -lphonon4qt5
> ```
> 
> Still not so clear, for this case, does all of the following forms do the same job:
> 
> ```
> $$(PHONON_PRI)
> or
> $${PHONON_PRI}
> or
> $$PHONON_PRI
> ```
> 
> Regards

use var name: PHONON_PRI_DIR for self-compiled phonon4qt5 

See here:

https://github.com/hongyi-zhao/texstudio/commit/47f65d79c20664e89388f132b676e981dffdec6e

**Comment by MeanSquaredError** [comment]
I had the idea for a similar solution but after thinking a bit I came to the conclusion that:

1. Building and installing packages manually (and uncontrolled by a package manager) into /usr/local/ is a sure-fire way to get into trouble. Installing libraries into /usr/local/ per se is a mistake unless you have a really good reason to do that (and there is a 99.(9)% chance that what you thought is a good reason actually is not). Package managers exist for a good reason.

2. Anyone who installs libphonon into a non-standard location should know how to register it as a Qt module. libphonon per se is a Qt library, so placing it into a custom location and not registering it as a Qt module through a .pri file means that libphonon has been installed incorrectly. There is no real reason to make the TXS code more complex just to workaround the mistakes of the administrator who installed libphonon incorrectly.

**Comment by sunderme** [comment]
I think we are done here ?

**Comment by MeanSquaredError** [comment]
@sunderme 
I would say so.
