### ISSUE TITLE
Cursor placement and text insertion point differ.

### ISSUE THREAD

**Issue by ahrendsen** [texstudio-org/texstudio#832]
### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.1
- OS: Windows 10 
- TeX distribution: miktex

### Expected behavior
Text will insert at the cursor position. 

### Actual behavior
Text inserts three lines above cursor position. The syntax highlighting is consistent with the three-line-up position rather than the cursor position. 

### How to reproduce
Not sure. I have a feeling it might be related to the large number of collapsed sections in my document. I've attached the document to this issue so other can try to see if they can reproduce.[standardProcedures.txt](https://github.com/texstudio-org/texstudio/files/3947873/standardProcedures.txt)

When the issue is present, normal behavior can be restored temporarily by entering text near the top of the document where three lines above is not accessible. The old behavior return when entering text lower in the document. The issue also seemed to begin when deleting text on a line with a collapsed section heading. 

Restarting TeXStudio also fixes the problem, temporarily.

This issue has happened two or three times to me today. Sorry I can't figure out how to reproduce it. I tried "View > Collapse > Everything" and that seems to have made the issue disappear for the moment. I'll update again if I come up with a reliable method to reproduce.

**Comment by MeanSquaredError** [comment]
I tried reproducing the issue but in my case everything worked correctly with the provided sample file.

TeXstudio: 2.12.16 (downloaded from https://github.com/texstudio-org/texstudio/releases/download/2.12.16/texstudio-2.12.16-win-qt5.exe)
Qt: 5.12.1
OS: Windows 7
TeX distribution: none

**Comment by sunderme** [comment]
no feedback
