### ISSUE TITLE
Cannot import macros on Ubuntu

### ISSUE THREAD

**Issue by bonej079** [texstudio-org/texstudio#833]
### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.6
- OS: Unbuntu 19.10
- TeX distribution: texlive

### Expected behavior

In Edit Macros popup, when clicking import the txs files should be visible.

### Actual behavior

Unable to see the macros because the filter just says txs macro files (it seems it is not filtering on the extension)
### How to reproduce

Open the Edit Macros dialog

Click Import

Navigate to folder with txs files

txs Files are not visible

**Comment by MeanSquaredError** [comment]
The macro files have the extension .txsMacro
So the import dialog shows all the files with that extension.

**Comment by bonej079** [comment]
It works as specified. Would it be possible to save the files with the appropriate extension on export?

**Comment by MeanSquaredError** [comment]
Just tested the latest version of TXS on Fedora. The source code was downloaded and built from the github repository. If you don't specify an extension explicitly when exporting a macro it adds the .txsMacro extension.

**Comment by bonej079** [comment]
OK, great! Maybe it was because I was adding the extension myself.
