### ISSUE TITLE
remove QT4 support

### ISSUE THREAD

**Issue by sunderme** [texstudio-org/texstudio#835]
I would suggest to remove QT4 support.
There already a number of functions only available on Qt5 (json for language tool,e.g.).
Also poppler-qt4 does not exist on recent platforms (Ubuntu 19.10) as poppler has abandoned qt4 support.

Any objections ?

"speak now or remain silent forever" ;-)

**Comment by timhoffm** [comment]
Qt4 is officially unsupported for several years. Whoever is using such a system/configuration cannot expect to get continuing updates from other apps. It‘s fair to remove Qt4 support. That makes some things simpler.

Should we have a last Qt4-compatible release based on current master?

**Comment by sunderme** [comment]
We can release 2.12.18 and then increment to 3.0.0

**Comment by MeanSquaredError** [comment]
+1 to the removal of Qt4 support.

Might simplify the following upgrades
QtScript -> QJSEngine
Phonon -> QtMultimedia
(Phonon is not supported either)
