### ISSUE TITLE
Bookmarks' tooltip: translated as "Symbols"

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#837]
### Environment
- TeXstudio 2.12.18 (git 2.12.16-181-g17767ad6)
- Using Qt Version 5.12.6, compiled with Qt 5.12.6 D
### Expected behavior
The bookmarks' tooltip should be translated with the corresponding string in the `.ts` files.

### Actual behavior
Except with the English language, the bookmarks' tooltip is translated as the "Symbols" one.

### How to reproduce
1. Select another language than English (Options → Configure TeXstudio... → General → Language → en).
2. Close and reopen TXS.
3. Hover the mouse pointer on the "Bookmarks" icon on the left panel.

**Comment by sunderme** [comment]
okay on linux and German

**Comment by dbitouze** [comment]
>okay on linux

Sorry, I didn't specified: on Linux (Mageia 7) too.

> and German

Even with German on my Linux box: "Symbole" tooltip both for bookmarks and for symbols icons.

**Comment by sunderme** [comment]
it has been fixed...

**Comment by dbitouze** [comment]
> it has been fixed... the issue was closed with a commit.

Ah, I see. I confirm it's okay now.
