### ISSUE TITLE
New beamer slides items: untranslatable

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#838]
### Environment
- TeXstudio: 
    TeXstudio 2.12.18 (git 2.12.16-181-g17767ad6)
- Qt: Using Qt Version 5.12.6, compiled with Qt 5.12.6 D

### Expected behavior
"New beamer slides" title and items (in "Beamer Commands" tab on the left panel) should be translatable.

### Actual behavior
"New beamer slides" title and items (in "Beamer Commands" tab on the left panel) are untranslatable.

### How to reproduce

1.  Select another language than English (Options → Configure TeXstudio... → General → Language → en).
2.  Close and reopen TXS.
3. Click on the "BM" icon. Title section "New Beamer Slides" and items:

    - "slide with enumerate"
    - "slide with itemize"  
    - "slide with graphic"  

    are not translated (nor translatable).

**Comment by sunderme** [comment]
the sidebar is not translatable
This requires probably some major code change

**Comment by dbitouze** [comment]
>the sidebar is not translatable

Indeed, the same happens for:

- "Left/Right Brackets"
- "PSTricks Commands"
- "MetaPost Commands"
- "Tikz Commands" (BTW, should be "TikZ")
- "Asymptote Commands"
- "XY Commands"

but, strangely, not for Symbols tab: here, "Favorites", "Most Used", etc. are translatable.

**Comment by sunderme** [comment]
different internal mechanism ...

**Comment by dbitouze** [comment]
>different internal mechanism ...

Why not used this different internal mechanism for the currently not translatable tabs?
