### ISSUE TITLE
default dvi viewer configuration is wrong

### ISSUE THREAD

**Issue by paultjevdh** [texstudio-org/texstudio#840]
Hi,
When I open a dvi file for viewing through the `view dvi' command, the correct page is not activated when using the default command. The reason is a " in the command line
"C:\Program Files\MiKTeX 2.9\miktex\bin\x64\yap.exe" -1 -s @?"c:ame "?am.dvi"
the " in @?"c:ame confuses the parser (see behavior below).
Removing the " fixes the problem for me, but may not be sufficient when the source path contains spaces.

### Environment
- TeXstudio: 2.12.16
- Qt: 5.12.1
- OS: Windows 10 1909
- TeX distribution: Miktex

### Expected behavior
When running the view dvi command, the messages window prints:
Process started: "C:\Program Files\MiKTeX 2.9\miktex\bin\x64\yap.exe" -1 -s 18C:\Temp\Reports\BBFB.tex "C:\Temp\Reports\BBFB_analysis_no_loop_delay.dvi"
- Printed in green
- The document opens on the page corresponding to the currently active source line.

### Actual behavior
When running the view dvi command, the messages window prints:Process started: "C:\Program Files\MiKTeX 2.9\miktex\bin\x64\yap.exe" -1 -s 18c:ame "C:\Temp\Reports\BBFB_analysis_no_loop_delay.dvi"
- Printed in black
- The dvi viewer opens at first page of document. When the viewer is already open, it does not change to the location corresponding to the active source line.

### How to reproduce
Compile a tex file to dvi and open through `view dvi' command with the default setting.
Then repeat with @?"c:ame changed to @?c:ame in the command line

Best regards,
Paul

**Comment by MeanSquaredError** [comment]
The configuration of the command is OK. Effectively it means that the expanded pathname should be enclosed in double quotes. However there seems to be a small bug in the code.
I will provide a bugfix shortly.

**Comment by MeanSquaredError** [comment]
Actually you are right that the configuration is incorrect. In fact it should be 
```
"C:\Program Files\MiKTeX 2.9\miktex\bin\x64\yap.exe" -1 -s @?c:ame" "?am.dvi"
```
( the double quote should be moved after `?c:ame` )

Does that configuration work correctly by enclosing the pathname in double quotes?

**Comment by paultjevdh** [comment]
HiYes, that fixes it.
I find the opening " on the second path argument (?am.dvi) still strange though. The way I read the advanced instructions, I expect only closing quotes are required, the opening quote is generated. This true for the first argument, not for the second.
Best regards,Paul

    On Friday, December 20, 2019, 9:32:58 PM GMT+1, MeanSquaredError <notifications@github.com> wrote:  
 
 
Actually you are right that the configuration is incorrect. In fact it should be
"C:\Program Files\MiKTeX 2.9\miktex\bin\x64\yap.exe" -1 -s @?c:ame" "?am.dvi"

( the double quote should be moved after ?c:ame )

Does that configuration work correctly by enclosing the pathname in double quotes?

**Comment by MeanSquaredError** [comment]
Command-line expansions span several characters starting with ? until the so-called terminating character which can be one of

*)* Do not add characters before or after the expanded pathname parts. Used to mark the end of the expansion token.
*"* to enclose the expanded pathname parts in double quotes.</li>
*.* to add a dot after the expanded pathname parts
*(space)* to add a space after the expanded pathname parts

So in the first the expanded pathname is enclosed in double quotes because the pathname expansion has double quote as its terminating character.

In the second case the expanded pathname is not enclosed in double quotes because the pathname expansion is terminated by a dot, so the expansion is actually `?am.` and we have to add manually the extension (dvi) and enclose it in double-quotes.

If you have a recent version of the manual you can read about it in section `4.4 External Commands`

**Comment by paultjevdh** [comment]
Thanks for your explanation. I missed the importance of the `.'.

I found the manual on my hard drive as well as TeXstudio : user manual

| 
| 
|  | 
TeXstudio : user manual


 |

 |

 |

4.4 is about svn support. Is there a more recent version somewhere?
Best regards,Paul


    On Sunday, December 22, 2019, 11:53:17 PM GMT+1, MeanSquaredError <notifications@github.com> wrote:  
 
 
Command-line expansions span several characters starting with ? until the so-called terminating character which can be one of

) Do not add characters before or after the expanded pathname parts. Used to mark the end of the expansion token.
" to enclose the expanded pathname parts in double quotes.
. to add a dot after the expanded pathname parts
(space) to add a space after the expanded pathname parts

So in the first the expanded pathname is enclosed in double quotes because the pathname expansion has double quote as its terminating character.

In the second case the expanded pathname is not enclosed in double quotes because the pathname expansion is terminated by a dot, so the expansion is actually ?am. and we have to add manually the extension (dvi) and enclose it in double-quotes.

If you have a recent version of the manual you can read about it in section 4.4 External Commands

**Comment by MeanSquaredError** [comment]
Latest development builds can be downloaded from
https://bintray.com/sunderme/texstudio
I think they have the latest version of the manual too.

**Comment by MeanSquaredError** [comment]
Currently the latest Windows download is 
https://bintray.com/sunderme/texstudio/texstudio-win/2.12.18-201912221833-git_1467ea1?versionPath=%2Fsunderme%2Ftexstudio%2Ftexstudio-win%2F2.12.18-201912221833-git_1467ea1#files
