### ISSUE TITLE
"filelist" string cannot be translated

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#841]
### Environment
- TeXstudio: 2.12.18 (git 2.12.16-205-gb5a85f64)
- Qt: Version 5.12.6, compiled with Qt 5.12.6 D
- OS: Linux (Mageia 7)

The string "filelist" in LaTeX → Input/Include Files → \includeonly{filelist} cannot be translated.

**Comment by sunderme** [comment]
fixed
