### ISSUE TITLE
`TXS-program` instead of `TS-program`?

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#845]
### Environment
- TeXstudio: 3.00.00 (git 2.12.16-224-g3a8e87c3)
- Qt: Version 5.12.6, compiled with Qt 5.12.6 D
- OS: Linux (Mageia 7)

Line 1035 of `src/configdialog.ui` contains `TS-program`. Shouldn't it be `TXS-program` instead?

**Comment by sunderme** [comment]
TS-program is correct.
It is a code used in the magic comments.
