### ISSUE TITLE
Some mistranslations in the newest texstudio_hu.ts

### ISSUE THREAD

**Issue by hair-splitter** [texstudio-org/texstudio#847]
I have found some mistranslations in the newest file `texstudio_hu.ts`:

`<source>Slanted - \textsl</source>`
`<translation>Dőlt - \textsl</translation>`
correct: `<translation>Döntött - \textsl</translation>`

`<source>Place in Figure Environment</source>`
`<translation>Elhelyezés az ábra környezetben</translation>`
correct: `<translation>Elhelyezés figure környezetben</translation>`

`<source>Packages Help (Texdoc)</source>`
`<translation>Súgó csomagok (Texdoc)</translation>`
correct: `<translation>Csomagleírások (Texdoc)</translation>`

`<source>Packages Help...</source>`
`<translation>Súgó csomagok...</translation>`
correct: `<translation>Csomagleírások...</translation>`

`<source>Check Active Completion Files</source>`
`<translation>q</translation>`
correct: `<translation>Aktív kiegészítő fájlok ellenőrzése</translation>`

**Comment by sunderme** [comment]
please correct them yourself on https://www.transifex.com/texstudio/texstudio
