### ISSUE TITLE
macOS dark theme readability problems

### ISSUE THREAD

**Issue by schwedenmut** [texstudio-org/texstudio#848]
### Environment
- TeXstudio: 2.12.18
- Qt: 5.14.0
- OS: Mac
- TeX distribution: texlive

### Expected behavior
I would expect that all gui elements will be readable with dark theme enabled, or to have an option to disable dark theme in TeXstudio while the dark mode is not working as expected.

### Actual behavior
Using the macOS dark theme after the upgrade from 2.12.16 to 2.12.18 a whole bunch of gui elements are not really well readable anymore. For example the following comparison of both versions:

| 2.12.16 | 2.12.18 |
|---|---|
|<img width="1371" alt="2.12.16" src="https://user-images.githubusercontent.com/9077622/71589712-2522a300-2b26-11ea-9369-3203fdc9b5da.png">|<img width="1371" alt="2.12.18" src="https://user-images.githubusercontent.com/9077622/71589738-3966a000-2b26-11ea-8db9-11b82fc5a207.png">|
|   |<img width="1316" alt="Settings 2.12.18" src="https://user-images.githubusercontent.com/9077622/71589751-47b4bc00-2b26-11ea-9d46-6da50390fefa.png">|

Just to be sure, I am not talking about syntax highlighting which can be manually changed. I am talking about buttons, checkboxes and other labels which are not optimized for dark mode.

### How to reproduce
While having macOS dark mode enabled check TeXstudio 2.12.16 (git 2.12.16), Qt-Version 5.12.3, compiled with Qt 5.12.3 R and TeXstudio 2.12.18 (git 2.12.18), Qt-Version 5.14.0, compiled with Qt 5.14.0 R.

**Comment by schwedenmut** [comment]
probably related to #596 but on different platform and only since 2.12.17(?) 2.12.18(!).

**Comment by sunderme** [comment]
have you tried to switch color scheme and/or use own color scheme ?

**Comment by sunderme** [comment]
so another question: the main complaint is the black font in the drop down boxes ?

**Comment by schwedenmut** [comment]
@sunderme thanks for your replies, yes the main complaint is the inconsistency in the UI since darkmode is enabled automatically if macOS darkmode is used. The black font in the drop down boxes and checkboxes are just two things I noticed.

I have not tried to switch the color scheme and/or use my own since this is the "out of the box" experience without changes by myself.

**Comment by sunderme** [comment]
please try the "own colormode"

**Comment by sunderme** [comment]
I don't have access to a current osx installation.
So, I can't debug ...

**Comment by schwedenmut** [comment]
Switching to the "own colormode" gives back the normal light colorscheme. I can live with that.
<img width="1287" alt="Own Colormode" src="https://user-images.githubusercontent.com/9077622/71840524-c62cd300-30bd-11ea-8743-1ac7901c0acb.png">

**Comment by Piraty** [comment]
that's basically a QT config issue i assume? same as hypterlinks presented in dark blue

may be related: #45

**Comment by sunderme** [comment]
Yes and no.
The dark mode gives different colors for default coloring of elements. Some elements seem not to be set to sensible values (drop down text color).
For other elements,e.g. syntax highlighting, special code may be necessary to detect dark mode.

**Comment by doctorrerumnaturalium** [comment]
Where can I find `own colormode`?

**Comment by sunderme** [comment]
options/general/...

**Comment by Lyr3x** [comment]
I just updated to the latest stable version of TeXstudio. It seems that system color scheme is now supported. However when dark mode is activated the default syntax highlighting  settings makes the text hard to read.
I propose the following changes:
Basic highlighting: 
- keyword 0xB41315 -> which is a punchier red instead of a wine red
- structure 0x6FC1BF -> blue/grey tone. Black is just not readable on a dark gray backround

Line highlighting:
- current: 0x7E8080
-brace match: yellow is not a great choice here

**Comment by doctorrerumnaturalium** [comment]
### Environment
- TeXstudio: 2.12.22
- Qt: 5.14.0
- OS: macOS Catalina (10.15.29
- TeX distribution: texlive

### Expected behavior

TXS complete in dark mode when macOS switches automatically in dark mode

### Actual behavior

When macOS switches automatically into dark mode, the editor pane don't change to dark mode. All other components of TXS switches. After restart TXS, all is fine

### How to reproduce

Switch automatically or manually into dark mode on macOS Catalina when TXS is running

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/59892214/73089653-fdc9b680-3ed6-11ea-926b-3b7477a852fa.png">

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/59892214/73089766-38cbea00-3ed7-11ea-82b8-dd84215657e8.png">

**Comment by sunderme** [comment]
can someone test the latest build on osx darkmode.
The symbols in symbol widget should (hopefully) look better...

**Comment by schwedenmut** [comment]
@sunderme this screenshot is from TeXstudio 2.12.22 (git 2.12.22) or which build do you want us to test?
<img width="1287" alt="Bildschirmfoto 2020-01-26 um 19 35 24-fs8" src="https://user-images.githubusercontent.com/9077622/73139899-28e90d00-4073-11ea-9a31-e2aa3c1e0688.png">

**Comment by schwedenmut** [comment]
@sunderme the following screenshot is taken from TeXstudio 2.12.22 (git 2.12.22) and doesn't show improvements for gui elements like the dropdowns and the symbols. I am not sure if you are talking about this build or another which I didn't find.
<img width="1287" alt="Bildschirmfoto 2020-01-26 um 19 35 24-fs8" src="https://user-images.githubusercontent.com/9077622/73140006-55515900-4074-11ea-93a3-3faeab99a232.png">

**Comment by sunderme** [comment]
I was talking about this  build: https://bintray.com/sunderme/texstudio/download_file?file_path=texstudio-osx-3.00.00-202001261643-git_a398d05.dmg

**Comment by schwedenmut** [comment]
Tested with the provided dmg file. UI elements seem fixed, symbols still are with the old dark fontcolor.
![Bildschirmfoto 2020-01-27 um 08 38 31-fs8](https://user-images.githubusercontent.com/9077622/73157318-e9f1a080-40e0-11ea-9498-2f0546003fd1.png)

**Comment by sunderme** [comment]
the latest dev build on bintray.com/sunderme/texstudio has an option "dark mode" which recolors the symbols. However the syntax highlighting is not suitable for dark background.
Can someone set it up nicely and send us texstudio.ini (or the relecant part there of), so that we can make it a default. txs will have two sets of syntax highligtings, one of normal, one for dark mode.

**Comment by schwedenmut** [comment]
I can create something for the darkmode adapted from dracula theme (compare https://draculatheme.com/ or https://github.com/dracula) this weekend and upload (or create a PR).

**Comment by sunderme** [comment]
sounds good

**Comment by trg818** [comment]
On MacOS Mojave (10.14.6) I find the same problem. However, if I switch to light mode before starting TeXstudio and then switch back to dark mode after launch, I find that at least the subwindow where the actual text is written and apparently also several buttons remain bright. As I usually keep TeXstudio running except for reboots, that kind of works for me and removes most of the readability problems (but it's of course not the way it's supposed to be).

**Comment by thomas-daniels** [comment]
> I don't have access to a current osx installation.
> So, I can't debug ...

For what it's worth, at least the syntax highlighting issues can be reproduced on Linux as well, if you use a dark Qt theme, such as `kvantum-dark` (Ubuntu: install `qt5-style-kvantum` and `qt5-style-kvantum-themes` and the theme `kvantum-dark` will show up under TeXstudio's configuration options.)

**Comment by andrematzke** [comment]
the syntax highlighting is really a problem. White marked on white text.. one has customize a lot of colours or one have to reinstall an old version to work again.
![Bildschirmfoto 2020-02-26 um 18 04 08](https://user-images.githubusercontent.com/33298027/75368723-70f18e80-58c2-11ea-90bd-cf0e258e1922.png)

**Comment by sunderme** [comment]
use txs color scheme is your friend ...

**Comment by SgtSilvio** [comment]
I found another workaround:
you can exclude texstudio from the mac os dark mode with the following command:
`defaults write texstudio NSRequiresAquaSystemAppearance -bool yes`

Command to reset this setting: `defaults delete texstudio NSRequiresAquaSystemAppearance`

**Comment by sunderme** [comment]
basically done

**Comment by mhellmeier** [comment]
Why is this issue closed?

Changing the color theme to the light one as suggested by @SgtSilvio is a workaround, not a solution of the readability and highlight problems on macOS dark theme.

**Comment by AryaGuo** [comment]
> Why is this issue closed?
> 
> Changing the color theme to the light one as suggested by @SgtSilvio is a workaround, not a solution of the readability and highlight problems on macOS dark theme.

Restarting TeXstudio is helpful for me. 

So there is still something wrong if I launch in light mode and switch to dark after.
