### ISSUE TITLE
Footnote in table doesn't print at bottom of page.

### ISSUE THREAD

**Issue by sighthoundman** [texstudio-org/texstudio#849]
Footnote in table doesn't print at bottom of page.

### Environment
- TeXstudio: 
- Qt: 
- OS: 
- TeX distribution: 

### Expected behavior
Footnote in table, if legal, should print at bottom of page. (Or as endnote if that environment is set up.) If not supported, should at least give a warning.

### Actual behavior
Footnote marker appears in table. Footnote does not appear at bottom of page.

### How to reproduce
See attached file.

[bugreportfootnoteintable.pdf](https://github.com/texstudio-org/texstudio/files/4013369/bugreportfootnoteintable.pdf)

**Comment by aubreyz** [comment]
This is a Latex question not a Texstudio question. You cannot make footnotes in tables appear at the bottom of the page without special tricks. Search online. It would be inappropriate to answer here.

**Comment by sighthoundman** [comment]
Thanks. I did not realize that.
