### ISSUE TITLE
Footnote in table doesn't print at bottom of page.

### ISSUE THREAD

**Issue by sighthoundman** [texstudio-org/texstudio#850]
# Environment
- TeXstudio:  VERSION 2.12.18 
- Qt:  5.12.1 R 
- OS:  Windows10, Linux (Ubuntu 18.04.2 LTS)
- TeX distribution:  miktex 

### Expected behavior
Footnote in table, if legal, should print at bottom of page. (Or as endnote if that environment is set up.) If not supported, should at least give a warning.

### Actual behavior
Footnote marker appears in table. Footnote does not appear at bottom of page.

### How to reproduce
See attached file.

[bugreportfootnoteintable.pdf](https://github.com/texstudio-org/texstudio/files/4013369/bugreportfootnoteintable.pdf)

**Comment by aubreyz** [comment]
Duplicate issue

**Comment by sunderme** [comment]
This is a latex question. txs is only a text editor. Latex errorare not resolved here.
Please submit your question to a dedicated forum like tex.stackexchange.com (with source code).
