### ISSUE TITLE
Wired spaces near text spans with condensed font-face

### ISSUE THREAD

**Issue by levitabris** [texstudio-org/texstudio#851]
### Environment
- TeXstudio:  TeXstudio 2.12.18 (git 2.12.18)
- Qt:  Using Qt Version 5.14.0, compiled with Qt 5.14.0 R
- OS:  macOS 10.15.2 (19C57)
- TeX distribution:   TeX, Version 3.14159265, TexLive 1.35

### Expected behavior
_Syntax Highlighting_ with condensed fonts uses less horizontal space since the font-face is designed to appear narrower.

### Actual behavior
The text is visually narrower but the space taken is the same as body fonts --- non-removable extra spaces are still hanging around the text to take up the same horizontal length.

![Before Selection](https://user-images.githubusercontent.com/1910117/71641221-44414200-2c98-11ea-977a-1c80056f2e08.png)
![After Selection](https://user-images.githubusercontent.com/1910117/71641220-44414200-2c98-11ea-8ad5-06f70c6a1036.png)

### How to reproduce
1. Upgrade to TeXstudio 2.12.18
2. Install the fonts ([Oswald](https://www.fontsquirrel.com/fonts/oswald), [DIN Condensed](https://www.cufonfonts.com/font/din-condensed)) if necessary.
3. Change `extra-keyword` in _Syntax Highlighting_  to `DIN Condensed` or `Oswald Regular`

Update: The problem still exists in version 2.12.20.

**Comment by levitabris** [comment]
I'm not a native speaker of English. I'm willing to explain more. Let me know if I failed to communicate it clearly.

**Comment by sunderme** [comment]
the problem is rather that reproducing the issue is tedious, least that none of the developers uses a mac ...

**Comment by timhoffm** [comment]
You may try different rendering options:

- Uncheck automatic display options.

![grafik](https://user-images.githubusercontent.com/2836374/71846214-53762480-30ca-11ea-9860-b9fbfef85239.png).

Then try the first three "Disable" checkboxes.

You may also try out different rendering modes.

**Comment by levitabris** [comment]
> the problem is rather that reproducing the issue is tedious, least that none of the developers uses a mac ...

Well, sorry I forgot a few steps to reproduce the problem
 1. Install VirtualBox 
2. Download macOS 
3. ....

No seriously... I only think it might be unrelated to the OS. I will come back to it if I can test it with other Windows machines. Thanks for the info.

**Comment by levitabris** [comment]
> You may try different rendering options:
> 
> * Uncheck automatic display options.
> 
> ![grafik](https://user-images.githubusercontent.com/2836374/71846214-53762480-30ca-11ea-9860-b9fbfef85239.png).
> 
> Then try the first three "Disable" checkboxes.
> 
> You may also try out different rendering modes.

Thanks for the advice. 

The "Disable" options are not helpful but the rendering modes really affected the letter spaces. The **letter** option will place the same amount of space evenly between the letters, using no narrower space. The **qt** mode solves the problem well. The only issue is that it is not very compatible with the "Center Document in Editor" option. 

![Screen Shot 2020-01-07 at 22 05 56](https://user-images.githubusercontent.com/1910117/71929960-0910a880-319b-11ea-8aa1-77e6044d98e6.png)

I used different body width number. The excessive indentation appears at every line after the first with twice of the correct length.

**Comment by muzimuzhi** [comment]
I use a macOS, and I have the same macOS and texstudio version as OP. What @levitabris reported is reproducible on my side.
1. Setting a condensed font for `Preferences - Syntax Highlighting - extra-keyword` do causes the effect described in https://github.com/texstudio-org/texstudio/issues/851#issue-544351019.
1. Changing the setting `Preferences - Adv. Editor - Hacks/Workarounds - (Unchecked) Try to auto... - Render Mode` to **QT** do fixes the first problem. None of the other choices for `Render Mode` and check boxes under `Preferences - Adv. Editor - Hacks/Workarounds - (Unchecked) Try to auto...` seem to work.
1. After the second step, if choose 
    - setting `Preferences - Adv. Editor - Special options - Line Wrapping` to `Soft Line Wrap after max. Characters` and 
    - check the setting `Preferences - Adv. Editor - Special options - Center Document in Editor`,

    then for a long text line, double left skip do shows for the auto-wrapped lines.
![image](https://user-images.githubusercontent.com/6376638/72027713-fab9ae00-32ba-11ea-85a3-7ff0dc246243.png)
![image](https://user-images.githubusercontent.com/6376638/72027770-35bbe180-32bb-11ea-8a5c-6431c5443471.png)

**Comment by levitabris** [comment]
> You may try different rendering options:
> 
> * Uncheck automatic display options.
> 
> ![grafik](https://user-images.githubusercontent.com/2836374/71846214-53762480-30ca-11ea-9860-b9fbfef85239.png).
> 
> Then try the first three "Disable" checkboxes.
> 
> You may also try out different rendering modes.

This workaround fixed my problem in version 3.0
