### ISSUE TITLE
Build and view does not finish with dvi chain

### ISSUE THREAD

**Issue by paultjevdh** [texstudio-org/texstudio#852]
Hi

I use the dvi build chain (configured latex as default compiler and yap as default viewer).
When I build & view (while yap is not running yet) the command never finishes according to texstudio: There is no line saying "process exited normally" and the red "Stop compile" button remains red. 
The document in yap is ok though.
When I press the "Stop compile" button in texstudio, yap is killed.

However, when I first start yap with the "view" button and then build & view, the command is terminated ("process exited normally" is printed and the "Stop compile" button becomes grey).

### Environment
- TeXstudio: 2.12.18
- Qt: 5.12.1
- OS: WIndows 10 1909
- TeX distribution: Miktex

### Expected behavior
When yap is not running and I press build and view, I expect texstudio to finish the command the same way as when yap is started before running the build & view commands

### Actual behavior
When I build & view (while yap is not running yet) the command never finishes according to texstudio: There is no line saying "process exited normally" and the red "Stop compile" button remains red. 
When I press the "Stop compile" button, yap is killed.

### How to reproduce
See above

Best regards,
Paul

**Comment by MeanSquaredError** [comment]
Please post the configuration settings for the involved commands (build&view and each of the commands referenced in the build&view chain).

**Comment by paultjevdh** [comment]
Ahhh, good point, I did edit the build & view command to generate a nomenclature index.
I found that changing the order of commands fixes the issue, but still, that should not be the case, thus something is wrong.
My configuration (resulting in no termination): 
build&view: txs:///compile | txs:///view | txs:///user0
user0: makeindex %.nlo -s nomencl.ist -o %.nls

Change the build & view configuration to: txs:///compile | txs:///user0 | txs:///view
Then the command terminates properly.

Paul

**Comment by MeanSquaredError** [comment]
Please post the configuration definitions for `txs:///compile` and `txs:///view`

**Comment by paultjevdh** [comment]
default viewer = txs:///view-dvi
dvi viewer = "C:\Program Files\MiKTeX 2.9\miktex\bin\x64\yap.exe" -1 -s @?c:ame" "?am.dvi"
default compiler = txs:///latex
LaTeX = latex.exe -src -interaction=nonstopmode %.tex

**Comment by sunderme** [comment]
without thorough testing, but I would assume that txs wait for each command to end before passing on to the next command. And since "yap" does not finish, it is stuck at there...

**Comment by MeanSquaredError** [comment]
1. The pipe character `|` which is used to build the command chains serves as a simplified version of the unix-style pipes. So when TXS executes a command chains it does the following.
- It runs the commands in the pipe one by one from left to right. Unlike Unix the commands are not run in parallel but rather sequentially, one at a time.
- If any command in the chain fails during the sequential execution, then the whole chain fails.
- If all commands succeed then the whole chain succeeds.
- If any command in the chain runs forever and does not terminate, then the whole chain locks up and you have to terminate it through the stop button.
- If I remember correctly (must check the source) TXS does not really wait for the last command in the chain to terminate, so it always succeeds if it is started successfully.

2.The PDF viewer that you are using is
- An interactive program, so when run once it runs forever until you terminate it.
- If you start `yap` with an argument which is a PDF file and if upon startup `yap` detects that there is another copy of `yap` already running, it will instruct the already running copy to display the specified PDF file and the newly started copy of `yap` will terminate.

Having 1 and 2 in mind it is pretty easy to figure out what is happening.
When there is no running copy of `yap` your build&view chain starts yap and waits for it to terminate.
When there is already a running copy of `yap`, TXS runs `yap` from the build&view chain and the newly started copy of yap finds the old copy of yap, passes the PDF location to the old yap and terminates. So your build&view chain terminates successfully in this case.

**Comment by MeanSquaredError** [comment]
@sunderme 
I should be more concise
Did not see that you already answered the question :-)

**Comment by sunderme** [comment]
@MeanSquaredError 
your answer way clearer than mine ...

**Comment by paultjevdh** [comment]
Hi,
You describe how it is implemented, and consequently exposes the described behaviour.
I do not think that this is how it is supposed to work.
Paul

**Comment by sunderme** [comment]
that is exactly, how it is supposed to work.

**Comment by paultjevdh** [comment]
I think that for a user (non-developer) this feels inconsistent.
Since you say "TXS does not really wait for the last command in the chain to terminate,", this _is_ inconsistent.
This is _design_ rather than collateral damage?
Paul

**Comment by MeanSquaredError** [comment]
One could argue that not waiting for the last command to terminate is inconsistent (although I am not sure if it is a problem at all). However the important point is that changing TXS so that it waits for the last command to terminate would not solve the lock-up that you observed. The lockup is caused by the fact that TXS is waiting for `yap` to terminate which in turn is caused by the fact that TXS executes the programs in the chain sequentially and not in parallel. So in reality you have two choices:

1. Execute the programs in the build chain sequentially waiting for the previous one to terminate before running the next. This is the current behavior.

2. Execute the programs in the build chain in parallel not waiting for any of them to terminate and connect them through the standard input/output just like Unix does. This would not work in our case because the programs in the build chain don't communicate through the standard input/output but rely on side effects of the previous programs in the chain (in most cases it is placing output files somewhere in the filesystem).

One could argue that the current design is incorrect, but the point is that minor changes will not work and it would need a complete change in the way commands and command chains are defined.

So you are free to suggest another design, but if it is just minor changes to the current design then most likely it will be flawed too and there will be corner cases where it will break too.

**Comment by MeanSquaredError** [comment]
By the way if you want to start yap and not wait for its termination, you can create a batch file and run yap from it. Something like the workaround suggested here:
```https://stackoverflow.com/questions/2451861/how-to-not-wait-for-a-process-to-complete-in-batch-script```

**Comment by paultjevdh** [comment]
Hi
I think there is another, related inconsistency: the stop button does not activate when I just press 'view'. Following your logic, that command should exhibit the same behavior, unless the stop button is not intended to reflect viewer status, only build status.
A fix may be to restrict the stop button behavior to the 4 underlying latex build commands (and possibly user commands) instead of the aggregate build&view command. Then the stop button deactivates as soon as the build is over and before yap is started.
I guess the stop button is now handled at the interface level, that should then be changed to the command level.
Does this make sense?
Paul

**Comment by MeanSquaredError** [comment]
1. The `Stop` button is enabled only when there is an execution of a command for whose termination TXS is waiting.
2. TXS does not wait for the termination of the last command in an execution chain (there are a few exceptions, most notable is the compile of a .tex file).
3. The standalone `View` command is the only command in the command chain and therefore it is the last command in the command chain.
4. Therefore TXS does not wait for the standalone `View` command to terminate.
5. Therefore TXS does not display the stop button for the `View` command.
When you press the `view` button there.

**Comment by paultjevdh** [comment]
You describe how it is, I describe how I think it could be better.
I think you'll find that the program logic becomes simpler: no more exceptions for the last command in the chain, no more exceptions to exceptions when the last command is the compile.
Paul
