### ISSUE TITLE
Additional searchpaths not working after update to 2.12.18

### ISSUE THREAD

**Issue by Jamen1993** [texstudio-org/texstudio#855]
### Environment
- TeXstudio: 2.12.18
- Qt: 5.12.1
- OS: Windows 10 1909
- TeX distribution: texlive
- Language: German

### Expected behavior

I've set the additional searchpaths for log and pdf files and expect TS to find both files in the respective directory. This configuration worked with 2.12.16 as described in the Wiki.

![grafik](https://user-images.githubusercontent.com/17482299/71732366-58777180-2e47-11ea-8069-89fe09aee5b8.png)

### Actual behavior

I use the exact same configuration as with 2.12.16. The build process itself works fine and writes all files to the specified output directory but the pdf and log viewers ignore the additional searchpaths and aren't able to locate the files respectively.

![grafik](https://user-images.githubusercontent.com/17482299/71732456-95dbff00-2e47-11ea-90ba-4e83ce6bc6c0.png)

The correct directory would have been `D:\Dateien\Git-Repositories\masterarbeit\out\test.pdf`.

### How to reproduce

1. ![grafik](https://user-images.githubusercontent.com/17482299/71733236-64fcc980-2e49-11ea-8ec0-3e8a8ecdc4b7.png)
2. ![grafik](https://user-images.githubusercontent.com/17482299/71732366-58777180-2e47-11ea-8069-89fe09aee5b8.png)
3. Create the directory `out` in your working directory
4. Create the simplest test document
```latex
\documentclass[11pt, twoside, a4paper]{report}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}

\usepackage[british, ngerman]{babel}

\begin{document}
	Test
\end{document}
```
5. Use the internal build and view command

**Comment by sunderme** [comment]
fixed 
you can use a development build but there is little guarantee that it works fine as quite a lot has been changed recently

**Comment by Jamen1993** [comment]
I also tried that with the portable version of the development build `texstudio-win-3.00.00-202001021845-git_6b3fcae.zip` when I did as requested in #856 and it didn't work.
So you rightly gave no guarantee. :wink:

**Comment by sunderme** [comment]
the additional pdf/log path should work fine and it works on linux.

**Comment by sunderme** [comment]
taking the latest build instead of the oldest might help ...
https://bintray.com/sunderme/texstudio/download_file?file_path=texstudio-win-3.00.00-202001032141-git_fd4a0bd.zip

**Comment by Jamen1993** [comment]
Sorry, totally my fault.

It does work in ` texstudio-win-3.00.00-202001032141-git_fd4a0bd`.
