### ISSUE TITLE
Update Mac Dark Mode Readability

### ISSUE THREAD

**Issue by rjschoner** [texstudio-org/texstudio#858]
### Environment
- TeXstudio: TeXstudio 2.12.18
- Qt: Version 5.14.0, compiled with Qt 5.14.0 R
- OS:  Mac
- TeX distribution: tex live 

### Expected behavior
The update allows for dark mode in macOS. Dark background with white/light colored text. Cursor should appear in dark background and allow for typing in white text on black background

### Actual behavior
The new update using macOS dark mode makes text visible in light colors (and this I can easily change in the preferences to taste), but when I click on the white/light text, it automatically highlights the text in white making the text unreadable.
Is it possible to remove this section highlighting to make the text readable?

### How to reproduce
While having macOS dark mode download TexStudio 2.12.18 and type in text.

**Comment by sunderme** [comment]
you are talking about the line highlighting in the text ? (syntax highlighting/line highlighting/current)

**Comment by rjschoner** [comment]
> you are talking about the line highlighting in the text ? (syntax highlighting/line highlighting/current)

Yes! Thank you so much.

**Comment by ArturoRoTech** [comment]
After downloading and use for first time TeXstudio on Mac Catalina in dark mode I had exactly the same problem.
Solved!
Thank you so much!
