### ISSUE TITLE
OSX: Math symbols disappeared from left side panel

### ISSUE THREAD

**Issue by KarlMagnusLarsson** [texstudio-org/texstudio#859]
### Environment
- TeXstudio: TeXstudio 3.00.00 (git 2.12.18-66-gfd4a0bdc) 
- Qt: 14.0
- OS: 10.13.6 and 10.14.6
- TeX distribution: MacTex

The left side panel shows some symbols, but most of the area is blank. This could be due to qt5.14.0 from brew package manager. A downgrade to qt5.13.2 works for me, but qt5.14.0 does not.

### Expected behavior
Left side panel shows math symbols when * is klicked. The user can then select all, operators etc.

### Actual behavior
The left side panel shows some symbols, but most of the area is blank, with only a few symbols showing. 
![panel](https://user-images.githubusercontent.com/42386052/71768864-bb860880-2f1a-11ea-8571-33e35f8f7635.png)

### How to reproduce 
1) Build from source. Any version of source. 
2) Follow wiki build instruction for osx https://github.com/texstudio-org/texstudi /wiki/Compiling
3) brew install qt5
4) brew install poppler --with-qt5
5) git clone https://github.com/texstudio-org/texstudio.git
6) cd texstudio
7) qmake texstudio.pro
8) make
9) open texstudio.app
10) left panel math symbols does not work. The rest of Texstudio works without a problem, that is viewing and building. I have tried different computers with osx 10.13.6 and 10.14.6, same thing.

I can download any source, also from older releases of Texstudio. I get the same error.

### Alternative way to reproduce:
1) download 2.12.18 binary https://github.com/texstudio-org/texstudio/releases/download/2.12.18/texstudio-2.12.18-osx.dmg
2) start texstudio
3) left panel math symbols does not work. The rest of Texstudio works without a problem, that is viewing and building. 2.12.18 binary use Qt 5.14.0

### Workarounds 1
download 2.12.16 from https://github.com/texstudio-org/texstudio/releases/download/2.12.16/texstudio-2.12.16-osx.dmg
Texstudio 2.12.16 use Qt 5.12.3 which works for me. The 2.12.16 download works fine.

### Workarounds 2
I also managed to build latest source TeXstudio 3.00.00 (git 2.12.18-66-gfd4a0bdc) if I downgraded Qt from 5.14.0 to 5.13.2 (and downgraded/rebuilt brew poppler as well, as a side effect).

My conclusion is that Texstudio code is fine, but I suspect that brew upgrade of Qt to 5.14.0 cause the left panel math to disappear as a side effect. 

If I follow wiki build instruction for osx https://github.com/texstudio-org/texstudi /wiki/Compiling, then brew currently, 200104, gives me Qt 5.14.0 which probably breaks the left panel, regardless of Texstudio code version.

Can anyone with Texstudio OSX reproduce this observation?

**Comment by sunderme** [comment]
looks like qtsvg is not present in the qt build...

**Comment by sunderme** [comment]
works fine on linux/qt5.14

**Comment by gcaldiera** [comment]
Having exactly the same problem with TeXstudio 2.12.18 (with MacTeX 2019) on a Mac Book with Mac OS 10.15.2

https://www.reddit.com/r/LaTeX/comments/ek32kg/problem_with_texstudio_21218_side_panel/?utm_source=share&utm_medium=web2x

**Comment by KarlMagnusLarsson** [comment]
@sunderme, @gcaldiera , thank you for checking.

This could be a Homebrew Qt5.14.0 problem. For example, the formula for building qt5.14.0 does not create qtsvg or Homebrew might have omitted qtsvg in the binary package as @sunderme observed, or some other reason. I have not checked. 

Unfortunately downgrading Homebrew Qt to Qt 5.13.2 was not an easy process, at least not for me, since latest Homebrew Poppler library also depended on qt5.14.0 libs.

Qt5.13.2 formula:
brew install --force https://raw.githubusercontent.com/samford/homebrew-core/322877d333fae4ca0890aced2c411e204303f8de/Formula/qt.rb
This rebuilt Qt from source, for me.

Old Poppler formula (or perhaps any Poppler formula works as long as Homebrew rebuilds from source to pick up Qt5.13.2 libs):
brew install https://raw.githubusercontent.com/alebcay/homebrew-core/03e08b31b443e6d3aed5b09a2824ced40d01bdf8/Formula/poppler.rb

I know very little about Homebrew package management, so my downgrading procedure is not the best one.

Perhaps Homebrew track issues for Qt somewhere.

**Comment by sunderme** [comment]
no, the issue is qt5.14 itself and that a work-around suddenly stopped working.
However it seems that the work-around is not necessary any more, so I adapted the source code and the latest build works with qt 5.14 as well.

**Comment by KarlMagnusLarsson** [comment]
@sunderme: Thank you for the clarification.

@sunderme: Do you mean that Homebrew Qt5.14.0 work now, as a base for building Texstudio?

**Comment by sunderme** [comment]
yes

**Comment by KarlMagnusLarsson** [comment]
Homebrew Qt5.14.0 and Texstudio works for me. Thank you.
