### ISSUE TITLE
Defaults for search panel?

### ISSUE THREAD

**Issue by FloMiLe** [texstudio-org/texstudio#863]
### Environment
- TeXstudio: 2.12.18
- Qt: 5.14.0
- OS: Mac
- TeX distribution: MacTeX 2019

Is it possible to set defaults for the search panel, e.g. for case sensitivity and whole words?
I always have to switch those off...

**Comment by sunderme** [comment]
those settings are persistent ... and it works on linux ...

**Comment by FloMiLe** [comment]
Yes, thanks. I somehow had to trick texstudio into remembering my preferred setting by closing all files, creating a new one, setting the search options, and closing texstudio.
