### ISSUE TITLE
TeXstudio 2.12.18/Qt5.14: Many deprecated Qt functions used in the source code

### ISSUE THREAD

**Issue by jonasstein** [texstudio-org/texstudio#865]
### Environment
- TeXstudio: TeXstudio 2.12.18 (git n/a)
Using Qt Version 5.14.0, compiled with Qt 5.14.0 R
- OS: Gentoo Linux
- TeX distribution: TeXLive

The compiler can show the deprecated code if you compile with `-Wdeprecated-declarations`
or better `-Wall`

One example:

```
src/qcodeedit/lib/document/qdocument.cpp:7554:30: warning: ‘int QFontMetrics::width(QChar) const’ is deprecated: Use QFontMetrics::horizontalAdvance [-Wdeprecated-declarations]
 7554 |   m_spaceWidth = fm.width(' ');
```

**Comment by sunderme** [comment]
we are aware of it. 
The warning just comes with qt 5.14. The alternative unction however exists only since a a view qt revisions and is not accectable, so nothing to be done.

**Comment by OgreTransporter** [comment]
Vielleicht sollte man den Code aber an 5.14 anpassen und sich auch um die deprecated Funktionen kümmern. Wie auf https://www.qt.io/blog/2019/08/07/technical-vision-qt-6 zu lesen ist 5.14 eine LTS Version, aber etliche der deprecated Funktionen verschwinden mit Qt 6. D. h. wenn txs mit Qt 6 funktionieren soll müssen die deprecated Teile vermutlich ersetzt werden.

**Comment by sunderme** [comment]
As long as qt6 is not out, no need to bother. Especially as it is unclear what the new versions will be in qt6.
