### ISSUE TITLE
How to escape question mark in URL in a Script Macro?

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#868]
### Environment
  -  TeXstudio 3.00.00 (git 2.12.16-283-gf98cc2c9)
  -  Qt: 5.12.6
  -  OS: Linux Mageia 7
  -  TeX distribution: TeX Live 2019

In order to make use of Zotero's Better BibTeX's [CAYW (Cite as you Write)](http://retorque.re/zotero-better-bibtex/citing/cayw/) ([see it in action with Atom](https://atom.io/packages/zotero-picker)), I'm trying to create the following Script Macro (that I would love to be not only a Script Macro, BTW) that runs `curl` in the background but it fails because of the `?` in the URL (the URL is read until this question mark and I have been unable to escape it).

Thanks for any help.

```
%SCRIPT
var url = "http://127.0.0.1:23119/better-bibtex/cayw?format=biblatex&command=autocite&texstudio=true&minimize=true"
system("curl -v " + url)
```

**Comment by MeanSquaredError** [comment]
`system` passes the command to the corresponding shell interpreter. On Linux/bash you can wrap the URL in single quote ' and use backslash \ to escape each single quote inside the URL. So in your case it should be something like

```
%SCRIPT
var url = "http://127.0.0.1:23119/better-bibtex/cayw?format=biblatex&command=autocite&texstudio=true&minimize=true"
system("curl -v '" + url + "'")
```

**Comment by MeanSquaredError** [comment]
Actually :
1. I suspect that in your case it was the ampersand (&) that was causing the real problem. The ? is very unlikely to cause any problem, unless you have files looking like URLs in your current directory.
2. Shell-escaping anything inside a script string would really require two backslashes - one for the language string escape and the other for the actual shell escape, so if you had a URL with a single quote:

```
%SCRIPT
var url = "http://www.some.host.com/some\\'path"
system("curl -v '" + url + "'")
```
(I have not tested it, though)

**Comment by dbitouze** [comment]
> `system` passes the command to the corresponding shell interpreter. On Linux/bash you can wrap the URL in single quote ' and use backslash \ to escape each single quote inside the URL. So in your case it should be something like
> 
> ```
> %SCRIPT
> var url = "http://127.0.0.1:23119/better-bibtex/cayw?format=biblatex&command=autocite&texstudio=true&minimize=true"
> system("curl -v '" + url + "'")
> ```

Doesn't work either. I should have mentioned the error message in my OP, which is the same with you suggest here:

```
Process started: curl -v 'http://127.0.0.1:23119/better-bibtex/cayw

% Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0

* Could not resolve host: 'http * Closing connection 0 curl: (6) Could not resolve host: 'http

Process exited with error(s)
```

**Comment by dbitouze** [comment]
> Actually :
> 
>     1. I suspect that in your case it was the ampersand (&) that was causing the real problem. The ? is very unlikely to cause any problem, unless you have files looking like URLs in your current directory.

However, the error message reported in my previous comment:

```
Process started: curl -v 'http://127.0.0.1:23119/better-bibtex/cayw
[...]
```

let `?` be identified as the culprit, isn't it?

>     2. Shell-escaping anything inside a script string would really require two backslashes - one for the language string escape and the other for the actual shell escape, so if you had a URL with a single quote:
> 
> 
> ```
> %SCRIPT
> var url = "http://www.some.host.com/some\\'path"
> system("curl -v '" + url + "'")
> ```

Sorry but I don't see:

- what would be the `path` in my case,
- the connection with the single quote.

**Comment by MeanSquaredError** [comment]
I am sorry - I might be wrong about system() and it is possible that it executes programs directly without using the shell. However I will only be able to check it this evening. The error message gives the impression that curl times out because of some network error.

Can you please try the following
1. Start curl withthe ssme options from the command line and see if it will still timeout.
2. Place the curl command in a shell script file. chmod the file to make it executable, then execute it via system[] and see if it makes a diffetence

**Comment by dbitouze** [comment]
> I am sorry -

You're welcome! 

>  I might be wrong about system() and it is possible that it executes programs directly without using the shell. However I will only be able to check it this evening. The error message gives the impression that curl times out because of some network error.

Yes, I guess because it cannot read the whole URL.

> Can you please try the following
> 
>     1. Start curl withthe ssme options from the command line and see if it will still timeout.

Works as expected.

>     2. Place the curl command in a shell script file. chmod the file to make it executable, then execute it via system[] and see if it makes a diffetence

If the shell script contains just:

`curl -v 'http://127.0.0.1:23119/better-bibtex/cayw?format=biblatex&command=autocite&texstudio=true&minimize=true'
`

it works as expected. By contrast, if it contains:

`system("curl -v 'http://127.0.0.1:23119/better-bibtex/cayw?format=biblatex&command=autocite&texstudio=true&minimize=true'")
`

it fails with the error message (translated from French):

`Syntax error near the unexpected symbol « "curl -v 'http://127.0.0.1:23119/better-bibtex/cayw?format=biblatex&command=autocite&texstudio=true&minimize=true'" »`

**Comment by MeanSquaredError** [comment]
OK, I checked it and it seems that the proper way to escape the `?` symbol in TXS scripts when passing the URL to system() is to double the `?` symbol, i.e.

```
%SCRIPT
var url = "http://127.0.0.1:23119/better-bibtex/cayw??format=biblatex&command=autocite&texstudio=true&minimize=true"
system("curl -v '" + url + "'")
```

I checked the code and it seems that if the command passed to `system()` contains `txs:///` or if it contains `|` (pipe character), then it undergoes the command-line expansion pretty much like all the TXS commands.

system() does not use the shell so the OS shell expansion does not matter.

**Comment by dbitouze** [comment]
> OK, I checked it and it seems that the proper way to escape the `?` symbol in TXS scripts when passing the URL to system() is to double the `?` symbol, i.e.
> 
> ```
> %SCRIPT
> var url = "http://127.0.0.1:23119/better-bibtex/cayw??format=biblatex&command=autocite&texstudio=true&minimize=true"
> system("curl -v '" + url + "'")
> ```

Indeed:

`Process started: curl -v 'http://127.0.0.1:23119/better-bibtex/cayw?format=biblatex&command=autocite&texstudio=true&minimize=true'`

Thanks! Nevertheless, but maybe it'd worth opening another issue, the process exited with an error:

```
% Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0* Could not resolve host: 'http * Closing connection 0 curl: (6) Could not resolve host: 'http

Process exited with error(s)
```

> I checked the code and it seems that if the command passed to `system()` contains `txs:///` or if it does NOT contain `|` (pipe character), then it undergoes the command-line expansion pretty much like all the TXS commands.

Sorry but I don't understand what you mean here.

> system() does not use the shell so the OS shell expansion does not matter.

OK.

**Comment by MeanSquaredError** [comment]
> > OK, I checked it and it seems that the proper way to escape the `?` symbol in TXS scripts when passing the URL to system() is to double the `?` symbol, i.e.
> > ```
> > %SCRIPT
> > var url = "http://127.0.0.1:23119/better-bibtex/cayw??format=biblatex&command=autocite&texstudio=true&minimize=true"
> > system("curl -v '" + url + "'")
> > ```
> 
> Indeed:
> 
> `Process started: curl -v 'http://127.0.0.1:23119/better-bibtex/cayw?format=biblatex&command=autocite&texstudio=true&minimize=true'`
> 
> Thanks! Nevertheless, but maybe it'd worth opening another issue, the process exited with an error:
> 
> ```
> % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0* Could not resolve host: 'http * Closing connection 0 curl: (6) Could not resolve host: 'http
> 
> Process exited with error(s)
> ```

Try removing the single quotes around the URL.
```
 %SCRIPT
var url = "http://127.0.0.1:23119/better-bibtex/cayw??format=biblatex&command=autocite&texstudio=true&minimize=true"
system("curl -v " + url)
```
Initially I suggested them because I though it uses the system shell, but obviously this is not the case, so the single quotes are probably confusing curl.


> > I checked the code and it seems that if the command passed to `system()` contains `txs:///` or if it does NOT contain `|` (pipe character), then it undergoes the command-line expansion pretty much like all the TXS commands.
> 
> Sorry but I don't understand what you mean here.
When you pass a command to `system()`, it will 
1. Check if the command contains the string `txs:///`. If so it will do the standard command-line expansion, same as with the regular `txs:///` commands.
2. Also it will check if the passed command does not contain any pipe characters ( `|`) the command will undergo the same standard command-line expansion as in step 1.

For the command-line expansion rules, please see `4.4 External Commands`  in the updated manual (available inside TXS by choosing Help/User Manual).

**Comment by dbitouze** [comment]
> > Thanks! Nevertheless, but maybe it'd worth opening another issue, the process exited with an error:
> > ```
> > % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0* Could not resolve host: 'http * Closing connection 0 curl: (6) Could not resolve host: 'http
> > 
> > Process exited with error(s)
> > ```
> 
> Try removing the single quotes around the URL.
> 
> [...]

Bingo! 

> When you pass a command to `system()`, it will
> 
>     1. Check if the command contains the string `txs:///`. If so it will do the standard command-line expansion, same as with the regular `txs:///` commands.
> 
>     2. Also it will check if the passed command does not contain any pipe characters ( `|`) the command will undergo the same standard command-line expansion as in step 1.

OK, thanks, but what would be the benefit in my case?

**Comment by MeanSquaredError** [comment]
No specific benefit in your case. It is just the way `system()` is implemented, so when the user passes commands to `system()` he has to keep those implementation details in mind and escape the command accordingly.

This behaviour could possibly be improved, but it is probably not that much of a problem at to moment to warrant spending man-hours of work to fix that. However it is probably a good idea to document the current behaviour in the manual.
