### ISSUE TITLE
Backwards typing in TexStudio after backslash

### ISSUE THREAD

**Issue by twilsonco** [texstudio-org/texstudio#87]
This issue is partially described [here on SO](https://tex.stackexchange.com/questions/409315/backwards-typing-in-texstudio-after-backslash)

Under some circumstances, keyboard text entry is reversed after a backslash is entered. The steps to reproduce below describe the only occurrence of this behavior I've seen, but there may be more. I assume it's related to TS's autocomplete functionality since it occurs with backslash.

I think the problem is that in these circumstances, TS is keeping the cursor immediately to the right of the entered backslash, essentially turning on the old "insert" mode as if you've pressed on the "insert" key on a PC keyboard.

Please see the attached archived video demonstrating the undesired behavior, and to see how the behavior is not perfectly reproducible.

### Environment
- TeXstudio: hg 2.12.8
- Qt: 5.10.0
- OS: Mac
- TeX distribution: TeXLive

### Expected behavior
Text entry after a backslash should be in the order of keys pressed, so if I type "alpha" I should see "alpha" on the screen.

### Actual behavior
The ordering of letters is reversed, so typing "alpha" results in "ahpla" being displayed in the editor.

### How to reproduce
1. In an open TeX document in the TS editor, double click a word to select the whole word
2. Type "\alpha" and the order of the letters is reversed

[TeXStudio reversed text entry after double click select and backslash.zip](https://github.com/texstudio-org/texstudio/files/1864070/TeXStudio.reversed.text.entry.after.double.click.select.and.backslash.zip)

**Comment by sunderme** [comment]
there needs to be something else. I have never seen that behaviour on mac or linux.

**Comment by twilsonco** [comment]
I’m not the only one experiencing it (see linked SO page in OP). It’s very weird and annoying. Are there logs I can upload to help diagnose?

**Comment by benibela** [comment]
I have seen this frequently. It is very annoying indeed. But also hard to reproduce

**Comment by sunderme** [comment]
is option/advanced editor/automatically insert LRM ... activated ?

**Comment by samcarter8** [comment]
@sunderme For this problem sometimes occurs despite "automatically insert LRM characteres" **not** being activated.

**Comment by ZaydH** [comment]
I have had "automatically insert LRM" permanently disabled and I get it.

**Comment by Latin-TeX** [comment]
I got the same problem using Win 10 and MiKTeX as TeX-distribution.

**Comment by pnancke** [comment]
I have the same issue with TeXstudio 2.12.8 on Windows 10. For me it sometimes happens when I want to insert something like `\textit{...}` (I have a german keyboard layout).

**Comment by Dirk7589** [comment]
I'm experiencing this same issue 
TeXstudio 2.12.8 (hg 2.12.8-1-g68cd350)
Using Qt Version 5.8.0, compiled with Qt 5.8.0 R on Windows 10.

It was not occurring in the previous version.  Although I too do not have an exact reproduction case, it does seem to occur after typing \.. and then backspacing the \ to type normally. Restarting the application resolves the issue.

**Comment by benibela** [comment]
Likely something removes the auto update flag from the qeditor cursor

**Comment by psisquared2** [comment]
I have encountered this issue in the latest stable (2.12.10) and I have a way to realiably reproduce the issue, though I am not sure if there are still other ways to trigger it. I had been using a development version (2.12.9.something compiled after the patch commit) for a while and didn't encounter the issue, though I never tested the trigger explained below as I just found it.

**Trigger:**
1. I type a few characters (let's say "abcdef").
2. I select "abc" using the mouse.
3. Using the mouse, I drag-drop the selected text to the right of "def", such that the text now reads "defabc".
4. Now, when I type "\ghi", I end up with "\ihg" in the same manner as described in previous posts.

If it is still unclear, I can provide a screen recording of the issue.

My system: Windows 10, 64 bit, TexStudio 2.12.10, as provided on the official website. UI set to German.

For me, the issue is independent of the flag option/advanced editor/automatically insert LRM.

**Comment by ZaydH** [comment]
I duplicated @psisquared2 's description on MacOS 10.13.5 with:

TeXstudio 2.12.10 (git 2.12.10)
Using Qt Version 5.11.1, compiled with Qt 5.11.1 R

I run in English.

**Comment by ZaydH** [comment]
Clearly what @psisquared2 mentioned is a bug. However, has anyone seen the issue manifest during normal typing (i.e., without the drag/drop) in 2.12.10?  Since upgrading to 2.12.10, I have seen it while just typing.  I have not used it very heavily, but I have used it a good amount.

**Comment by pjb304** [comment]
I've just encountered this issue by accidentally performing the steps described by  psisquared2  

```
TeXstudio 2.12.10 (git 2.12.10)
Using Qt Version 5.8.0, compiled with Qt 5.8.0 R
```

I'm using windows 10 64bit, and the UI is all English.
