### ISSUE TITLE
autocomplete for \text{ substitutes \textbf{text}

### ISSUE THREAD

**Issue by zoof** [texstudio-org/texstudio#870]
When using the "\text" command with amsmath, texstudio autocompletes "\text{" with "\textbf{text}".

This worked fine in versions prior to 2.12.18.

### Environment
- TeXstudio: 2.12.18 (preferred command set to "typical" and amsmath.cwl is checked)
- Qt: 5.7.1
- OS: Debian Stretch
- TeX distribution: texlive

### Expected behavior
\text{ autocompletes with \text{text}

### Actual behavior
\text{ autocompletes with \textbf{text}

### How to reproduce
Type \text{ in document

Screencast at https://gofile.io/?c=3rxsdi

**Comment by MeanSquaredError** [comment]
I tested it with the latest development build (3.00.00-git) and autocompletion of `\text{` it seems to work correctly. Have you tried one of the development builds?

**Comment by sunderme** [comment]
and let's do the screencast again with a test document:
`\usepackage{amsmath}
\tex`

**Comment by zoof** [comment]
@MeanSquaredError No, I have not.  Is there a Debian Stretch build available or do I need to build it myself?

@sunderme https://gofile.io/?c=SVSWuW

**Comment by sunderme** [comment]
what is the content of ~/.config/textstudio/completion ? (incl. subdirs)

**Comment by zoof** [comment]
~/.config/textstudio/completion: https://pastebin.com/5W2cwtYd

and

help/active completion files: https://pastebin.com/s1UJBcJA

**Comment by sunderme** [comment]
please remove amsmath.cwl from .config/texstudio/completion/autogenerated and check the issue again (after restart of txs)

**Comment by zoof** [comment]
Perhaps that is the problem -- amsmath.cwl is active but does not exist in `.config/texstudio/completion/autogenerated` or anywhere else on my system.

    $ locate amsmath.cwl
    $

**Comment by sunderme** [comment]
amsmath.cwl is part of the binary 

have you removed the file in autogenerated ?

**Comment by zoof** [comment]
I could not delete it since it did not exist.

**Comment by sunderme** [comment]
sorry,my bad

**Comment by sunderme** [comment]
you could try https://bintray.com/sunderme/texstudio/download_file?file_path=texstudio-linux-3.00.00-202001100729-git_687fc01-x86_64.AppImage
That should work...

**Comment by zoof** [comment]
That works!  When can we expect 3.0 to be released?  I much prefer .deb packages to AppImage files.

**Comment by sunderme** [comment]
that will probably be a little while
Since you can't get along with an ubuntu ppa, the only other option which you have is building it locally.
(https://github.com/texstudio-org/texstudio/wiki/Compiling, make install is not necessary, you can run txs also in the build directory)

**Comment by zoof** [comment]
Thank you, I think I will revert to 2.12.16 and wait for the next release.

**Comment by sunderme** [comment]
this is fixed in 3.0...
