### ISSUE TITLE
Search and replace broken for some searches

### ISSUE THREAD

**Issue by zoof** [texstudio-org/texstudio#871]
I tried to replace \mathcal{H} with H.  When clicking on the single red arrow to substitute, nothing happens.  When clicking on the double red arrow, it works as expected.

### Environment
- TeXstudio: 2.12.18
- Qt: 5.7.1
- OS: Debian Stretch
- TeX distribution: texlive

### Expected behavior
Substitute one-by-one.

### Actual behavior
Advances to next search without replacing.

### How to reproduce

Do the above search and replace. Not sure if it is because of the particular string.

**Comment by sunderme** [comment]
duplicate #861 
as work-around, you can disable highlighting search results

**Comment by zoof** [comment]
Great -- that seems to work although that makes it difficult to ascertain when, on a case-by-case, basis to do the replacement.
