### ISSUE TITLE
segfault on editing spellcheck magic word

### ISSUE THREAD

**Issue by mxa** [texstudio-org/texstudio#875]
### Environment
- TeXstudio: TeXstudio 2.12.18 (git n/a)
- Qt: 5.12.4, compiled with Qt 5.12.4 R
- OS: Linux Kubuntu 19.10
- TeX distribution: texlive

### Expected behavior
changing the spellcheck magic word changes the spellcheck language

### Actual behavior
segfault

### How to reproduce
for example change `% !TeX spellcheck = en_GB` to `% !TeX spellcheck = de_DE`

**Comment by MeanSquaredError** [comment]
I can confirm the crash. Happens on Windows too.

**Comment by sunderme** [comment]
this is fixed in the current development build
