### ISSUE TITLE
Replace and Find Next find the next instance without replacing the previous one

### ISSUE THREAD

**Issue by vob2** [texstudio-org/texstudio#877]
### Environment
- TeXstudio: 2.12.18 (git 2.12.18)
- Qt: 5.12.1, compiled with Qt 5.12.1 R
- OS: Windows 10
- TeX distribution: miktex,

### Expected behavior
When text to be replaced is highlighted, pressing button Replace and Find Next should replace the highlighted text with the text in the replace field and then proceed to find the next instance of the text in the Find field.

### Actual behavior
After a few instances, pressing the button stops replacing text, but proceeds to the next instance, as if only Find functionality is working

### How to reproduce
Does not happen every time, but after a few times the button functionality worked successfully

**Comment by sunderme** [comment]
duplicate #861
