### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by sunderme** [texstudio-org/texstudio#879]
Since issue #861 comes up more than once, we should probably release a bug fix soon.
So do we release 3.0.0 or 2.12.20 (backporting the fix) ?

**Comment by MeanSquaredError** [comment]
Depends on the amount of work required to backport the fix and prepare 2.12.20. If backporting the fix and and preparing 2.12.20 is a small amount of work, then let's go for 2.12.20 (and give those stuck with Qt4 a bugfree TXS version). If backporting is too much work, then let's go for 3.0.0.

**Comment by MeanSquaredError** [comment]
I just looked at the fix - it seems to be small enough and non-intrusive so it really depends on other administrative issues. If they are negligible, then I would prefer 2.12.20 because we don't really have that many changes to warrant jump to 3.0.0 yet.

**Comment by sunderme** [comment]
effort is low, so I do that
There will be a 2.12.x branch for this purpose
