### ISSUE TITLE
Symbol rendering in sidebar not working correctly on macOS 10.14.6

### ISSUE THREAD

**Issue by niklas-uhl** [texstudio-org/texstudio#880]
From 2.12.18 onwards (I also tested 2.12.20) TXS fails to render some mathematical symbols and greek letters in the sidebar (see the attached screenshots). I managed to boil it down to 2.12.16 being the last release where it still worked. I suspect it's a Qt Problem, as 2.12.16 uses version 5.12.3, while 2.12.18 uses 5.14.0.

### Environment
- TeXstudio: 2.12.18+
- Qt: 5.14.0
- OS: macOS 10.14.6 Catalina, MacBook Pro 2019 '13 
- TeX distribution: texlive

### Expected behavior
![Bildschirmfoto 2020-01-14 um 08 42 15](https://user-images.githubusercontent.com/23433189/72324810-130b3d80-36ac-11ea-9417-38b8d505fcfd.png)
This screenshot is from 10.12.16
### Actual behavior
![Bildschirmfoto 2020-01-14 um 08 45 54](https://user-images.githubusercontent.com/23433189/72324852-26b6a400-36ac-11ea-9018-7d152925d8c1.png)
This screenshot is from 10.12.18

**Comment by sunderme** [comment]
this has been resolved.
You can use a fix via 3.0.0alpha build (https://github.com/texstudio-org/texstudio/releases/tag/3.0.0alpha1)
or 2.12.22beta1 (https://github.com/texstudio-org/texstudio/releases/tag/2.12.22beta1, still building now)
