### ISSUE TITLE
PdfLaTeX doesn't start

### ISSUE THREAD

**Issue by doctorrerumnaturalium** [texstudio-org/texstudio#881]
### Environment
- TeXstudio: 2.2.18
- Qt: 5.14.0
- OS: macOS Catalina
- TeX distribution: texlive

Hi,

installed TeXStudio 2.12.18 and want to compile my tex document. The process is starting but nothing happends (see screenshot attached). Type `pdflatex MyFile.tex` in terminal works fine. Any ideas?

Kind regards,

![Unbenannt](https://user-images.githubusercontent.com/59892214/72375998-711c3d00-370d-11ea-944f-bd3dbdc9feda.png)

**Comment by sunderme** [comment]
try to check with help/check installtion

**Comment by doctorrerumnaturalium** [comment]
This is the output

`which pdflatex: 

PDFLATEX: pdflatex -version


Environment variables:


TeXstudio:
Path        : /Applications/texstudio.app/Contents/MacOS/texstudio
Program call: /Applications/texstudio.app/Contents/MacOS/texstudio
Setting file: /Users/patrick/.config/texstudio/texstudio.ini

Command configuration in TeXstudio:
    DVI->PDF Chain (dvi-pdf-chain): txs:///latex | txs:///dvipdf | txs:///view-pdf
    Ghostscript (gs): gs "?am.ps"
    DVI Chain (dvi-chain): txs:///latex | txs:///view-dvi
    External PDF Viewer (view-pdf-external): open %.pdf > /dev/null
    Texindy (texindy): texindy %.idx
    SVNADMIN (svnadmin): 
    PDF Viewer (view-pdf): Interner PDF-Betrachter (als Fenster)
    Biber (biber): biber %
    BibTeX (bibtex): bibtex %.aux
    Makeindex (makeindex): makeindex %.idx
    Default Bibliography Tool (bibliography): BibTeX
    LaTeX (latex) (r): latex -src -interaction=nonstopmode %.tex
    Metapost (metapost): mpost -interaction=nonstopmode ?me)
    Asymptote (asy): asy ?m*.asy
    Internal Precompile (internal-pre-compile): txs:///pre-compile | txs:///conditionally-recompile-bibliography
    PDF Chain (pdf-chain): txs:///pdflatex | txs:///view-pdf
    DviPng (dvipng): dvipng -T tight -D 120 %.dvi
    Default Viewer (view): PDF Betrachter
    DVI Viewer (view-dvi): open %.dvi > /dev/null
    Default Index Tool (index): txs:///makeindex
    PS Chain (ps-chain): txs:///latex | txs:///dvips | txs:///view-ps
    Asymptote DVI Chain (asy-dvi-chain): txs:///latex | txs:///asy | txs:///latex | txs:///view-dvi
    PS Viewer (view-ps): open %.ps > /dev/null
    Latexmk (latexmk): latexmk -pdf -silent -synctex=1 %
    XeLaTeX (xelatex) (r): xelatex -synctex=1 -interaction=nonstopmode %.tex
    Makeglossaries (makeglossaries): makeglossaries %
    Build & View (quick): Erstellen & Anzeigen (mit ausgewählten Standardprogrammen)
    Default Glossary Tool (glossary): txs:///makeglossaries
    PdfLaTeX (pdflatex) (r): pdflatex -synctex=1 -interaction=nonstopmode %.tex
    SVN (svn): svn 
    Asymptote PDF Chain (asy-pdf-chain): txs:///pdflatex | txs:///asy | txs:///pdflatex | txs:///view-pdf
    DviPdf (dvipdf): dvipdfmx %.dvi
    DviPs (dvips): dvips -o %.ps %.dvi
    Precompile (pre-compile): 
    LuaLaTeX (lualatex) (r): lualatex -synctex=1 -interaction=nonstopmode %.tex
    Default Compiler (compile) (r): PdfLaTeX
    Ps2Pdf (ps2pdf): ps2pdf %.ps
    Recompile Bibliography (recompile-bibliography): txs:///compile | txs:///bibliography | txs:///compile
    BibTeX 8-Bit (bibtex8): bibtex8 %.aux
    DVI->PS->PDF Chain (dvi-ps-pdf-chain): txs:///latex | txs:///dvips | txs:///ps2pdf | txs:///view-pdf

Additional Search Paths:
    Command: /usr/local/texlive/2012/bin/x86_64-darwin
    Log: 
    Pdf: 
`

**Comment by doctorrerumnaturalium** [comment]
![image](https://user-images.githubusercontent.com/59892214/72377104-6e224c00-370f-11ea-92fb-8fedcbc3ba2a.png)

when I start `pdflatex`and then stop, the attached messages appears

**Comment by dbitouze** [comment]
> when I start `pdflatex`and then stop, the attached messages appears

Please, instead of screenshot, right click to copy the messages and just paste them here (TXS being in English could help non German speaking people to help you).

**Comment by MeanSquaredError** [comment]
It seems that TeXstudio cannot find pdflatex, that is it is not in the search path. We have already seen it in the past on macOS where programs started from shell and from launchpad have different PATH environment variables.

Can you try the following:

1. Start terminal.
2. Run `which pdflatex` from the terminal command-line. Please paste the output from `which pdflatex` here.
3. Run `texstudio` from the terminal command-line, then try to compile a document from TeXstudio.
Does it work (compile successfully when run from the command-line?

**Comment by doctorrerumnaturalium** [comment]
Ok, here's the output:
`/Library/TeX/texbin/pdflatex`

Run `texstudio`from command line takes no effect. Same result.

I've changed under Options the command `pdflatex -synctex=1 -interaction=nonstopmode %.tex` into `/Library/TeX/texbin/pdflatex -synctex=1 -interaction=nonstopmode %.tex`. PdfLaTeX doesn't start.

**Comment by sunderme** [comment]
You could try txs 3.0.0alpha1 for testing

**Comment by MeanSquaredError** [comment]
Indeed trying version 3.0.0 is a good idea.

Also try adding `/Library/TeX/texbin/` to the `Additional Search Paths / Commands ($PATH)`. You can set it from 
Options/Configure TeXstudio...
then enable "Show advanced options"
then go to Build / Additional Search Paths / Commands ($PATH)
and set it to `/Library/TeX/texbin/`

Does that make a difference

**Comment by doctorrerumnaturalium** [comment]
Ok, I've downloaded the file `https://dl.bintray.com/sunderme/texstudio/:texstudio-osx-3.00.00-202001142057-git_8190a21.dmg`. Can't start TXS. In _Additional Search Paths:_ I've changed _Commands ($PATH)_ from `/usr/local/texlive/2012/bin/x86_64-darwin` to `/Library/TeX/texbin/`. It doesn't make any difference.

The following output appears in the Messages window:
`Process started: PdfLaTeX`

`Error: Command crashed: PdfLaTeX`

`Process exited with error(s)`

`latex` or `pdflatex` works fine for me with i.e. TeXShop or from command line.

**Comment by doctorrerumnaturalium** [comment]
Ok, I've found a solution/workaround. The commands `Build & View` (`F5`), `Compile` (`F6`) and `View` (`F7`) doesn't work. So I run the commands from menu directly `Tools > Commands > PdfLaTeX`, `Tools > Commands > View PDF`. This works fine.

After that I go to `Preferences > Build` and changes the entries under `Build & View`, `Default Compiler`, `Default Viewer` and `PDF Viewer`. Now it is possible to compile and view from toolbar or press the shortcuts `F5`, `F6` and so on. No idea why the entries where changed, but now it's all fine.

![TXS_Configure](https://user-images.githubusercontent.com/59892214/72433862-91460d80-379a-11ea-8282-c7ff37fbc365.png)

**Comment by ilyamironov** [comment]
I confirm that this is still an issue on macOS X (Catalina) with TeXstudio 3.0.1. @doctorrerumnaturalium's workaround works like a charm. Thank you!
