### ISSUE TITLE
PDF additional search path

### ISSUE THREAD

**Issue by JPelda** [texstudio-org/texstudio#884]
### Environment
- TeXstudio: 2.12.20
- Qt: Qt 5.12.1
- OS: Win 10
- TeX distribution: texlive

### Expected behavior
Empedded pdf-viewer looks at additional search path './build'

### Actual behavior
Not looking at this path set relatively to the main doc. No pdf is shown. This worked before update to 2.12.18

### How to reproduce
Just compile into different folder than the doc.tex lies and try to open the pdf in the embedded pdf-viewer.

**Comment by MeanSquaredError** [comment]
Can you provide your texstudio.ini file?

**Comment by ap0305-thunder** [comment]
I have exactly the same issue. It was working in 2.12.16.

**Comment by MeanSquaredError** [comment]
@ap0305-thunder 
Can you please attach your texstudio.ini ?
On Windows it should be in AppData\Roaming\texstudio\texstudio.ini (or wherever the application data for TeXstudio is stored).

**Comment by sunderme** [comment]
can you try https://github.com/texstudio-org/texstudio/releases/download/3.0.0alpha1/texstudio-3.0.0alpha1-win-qt5.exe

**Comment by ap0305-thunder** [comment]
Here it is.
I have edited it by hand from time to time, but it is working with 2.12.16.
Even if the search path for pdf is ./build, it is looking for the pdf in .

[texstudio.ini.zip](https://github.com/texstudio-org/texstudio/files/4067459/texstudio.ini.zip)

**Comment by ap0305-thunder** [comment]
Yes I had tried.
In this case the viewer works as expected... but texstudio crashes very often...

> 
> 
> can you try https://github.com/texstudio-org/texstudio/releases/download/3.0.0alpha1/texstudio-3.0.0alpha1-win-qt5.exe

**Comment by sunderme** [comment]
What do you do when it crashes ?

I will probably publish 2.12.22beta2 tomorrow that should fix your problem...

**Comment by ap0305-thunder** [comment]
> 
> 
> What do you do when it crashes ?
> 
> I will probably publish 2.12.22beta2 tomorrow that should fix your problem...

I would say always interacting with the pdf embedded viewer window.

**Comment by MeanSquaredError** [comment]
@sunderme 
Does 2.12.20 contain your fix https://github.com/texstudio-org/texstudio/commit/6b36275e2faa1ab444d6414921296203e0bef586 and then the followup fixes from https://github.com/texstudio-org/texstudio/commit/c38b3e2d0cf2e19f852ec432d3336235ac14380b ?
If these are lacking, that would explain why additional PDF paths are not working (when they are relative paths).
I guess you are planning to backport these to 2.12.22 ?

**Comment by sunderme** [comment]
2.12.22beta2 contains the first commit,but not the second

**Comment by MeanSquaredError** [comment]
I would expect the first commit to suffice (after all it did fix the same issue https://github.com/texstudio-org/texstudio/issues/855 ).

**Comment by jjauhien** [comment]
It seems I have the same issue (using the version 2.12.0 on Ubuntu 19.10). The absolute path works fine with an embedded PDF viewer, while relative does not.

**Comment by JPelda** [comment]
> 
> 
> Can you provide your texstudio.ini file?


[texstudio.txt](https://github.com/texstudio-org/texstudio/files/4071872/texstudio.txt)

**Comment by sunderme** [comment]
2.12.22beta2 should work (https://github.com/texstudio-org/texstudio/releases/tag/2.12.22beta2)

**Comment by ap0305-thunder** [comment]
> 
> 
> What do you do when it crashes ?
> 
> I will probably publish 2.12.22beta2 tomorrow that should fix your problem...

I would say always interacting with the pdf embedded viewer window.

> 
> 
> What do you do when it crashes ?
> 
> I will probably publish 2.12.22beta2 tomorrow that should fix your problem...

In 2.12.22beta2 the problem with the pdf search patch of the embedded viewer has gone!
Many thanks!
