### ISSUE TITLE
Syntax highlight does not work

### ISSUE THREAD

**Issue by adcsilva** [texstudio-org/texstudio#885]
Syntax highlight does not work after the last update. However, I experienced this problem frequently also with the previous version. I use the default options of TeXstudio.

I am sending the files generated with the compilation; and a PDF print screen showing the text within the equation environment not highlighted.
### Environment
- TeXstudio: 2.12.18
- Qt: 5.12.1, compiled with Qt 5.12.1 R
- OS: Windows 10 Pro, version 1903.
- TeX distribution: miktex

### Expected behavior
Text with different color inside equation environment (text highlight).

### Actual behavior
No highlight.

### How to reproduce
See attached files.

[ScreenPrint.pdf](https://github.com/texstudio-org/texstudio/files/4065265/ScreenPrint.pdf)

[question.pdf](https://github.com/texstudio-org/texstudio/files/4065267/question.pdf)

[question.log](https://github.com/texstudio-org/texstudio/files/4065268/question.log)
[question.synctex.gz](https://github.com/texstudio-org/texstudio/files/4065270/question.synctex.gz)

**Comment by sunderme** [comment]
an you give the result of help/check completoon files...

**Comment by muzimuzhi** [comment]
The reported screen print:
![image](https://user-images.githubusercontent.com/6376638/72469297-19b7c300-381a-11ea-950b-e43da5b8fa6d.png)

Expected screen print:
![image](https://user-images.githubusercontent.com/6376638/72469395-44a21700-381a-11ea-9787-2eb5cbaebf0d.png)

Does clicking menu item `Idefix -> Refresh Structure` help?

**Comment by adcsilva** [comment]
Yes, clicking `Idefix -> Refresh Structure` made the highlight work. Thank you for your suggestion.

**Comment by sunderme** [comment]
never seen that issue myself
Current development state hanles math highlighting differently, so nothing left to do.
