### ISSUE TITLE
Adding a .sty file to my tex file

### ISSUE THREAD

**Issue by natashadsouza** [texstudio-org/texstudio#886]
### Environment
- TeXstudio: 
- Qt: 5.14.0
- OS: Mac
- TeX distribution: http://www.texstudio.org/www.texstudio.org

I am looking to add my own .sty file to the paper i am working on on tex studio. Is it possible to do so?

**Comment by foreachthing** [comment]
Very easy!
```
\documentclass{article}
\usepackage[yourPackageOptions]{yourPackage}
....
\end{document}
```
https://www.overleaf.com/learn/latex/Writing_your_own_package
