### ISSUE TITLE
Secondary toolbar change scale problem

### ISSUE THREAD

**Issue by jcardenast** [texstudio-org/texstudio#889]
### Environment
- TeXstudio: 2.12.20-win
- Qt:  QT5
- OS: Windows  8 and 10
- TeX distribution:  miktex 2.9

### Expected behavior
on Options -> Scale Gui -> secondary toolbar, the secondary bar size change as new configuration

### Actual behavior
on Options -> Scale Gui -> secondary toolbar, the secondary bar size change but when TexStudio restart, the bar continues with the same default size.

### How to reproduce
Change the Secondary toolbar size and apply, it works in this time, but if you close and open TexStudio this bar not apply the change. It refreshes on Entering options and click accept and it change the size.

A similar issue is on the preview document window, when all bars size looks ok, if you are watching a document and enter to Options menu and accept, in one second the icons on the preview menu resize to bigger one.

**Comment by foreachthing** [comment]
Huh?! I cannot confirm in TXS 2.12.20b1 (Win 10 x64).

**Comment by sunderme** [comment]
can't confirm either

**Comment by jcardenast** [comment]
I updated and the problem still continue. I attached this images, the first show the size of the icons (I make smaller this items before but in the start they don't change). Next I only enter to Options and click Ok without changing anything. Finally, the window update the icons to the size that I modified before. This behaviour is the same all the time that I enter to Tx.

![T1](https://user-images.githubusercontent.com/12958198/72685456-3b35da80-3ab8-11ea-9cda-124bdc23d5a5.png)
![T2](https://user-images.githubusercontent.com/12958198/72685458-3d983480-3ab8-11ea-9dda-4afd6637190b.png)
![T3](https://user-images.githubusercontent.com/12958198/72685459-40932500-3ab8-11ea-87ad-18d7c200f3a9.png)

**Comment by foreachthing** [comment]
Got two computers, same specs as you do ... cant reproduce your issue on neither machine.

Maybe completely uninstall TXS (also the config dir; where texstudio.ini is) an reinstall it. Make a backup or rename your config-dir.

**Comment by MeanSquaredError** [comment]
Does TXS preserve the other settings when you change them and then exit TXS and start it again?
For example does it keep General / Font Size if you set a non-default value and then restart it?

**Comment by sunderme** [comment]
no feedback

**Comment by jcardenast** [comment]
> Does TXS preserve the other settings when you change them and then exit TXS and start it again?
> For example does it keep General / Font Size if you set a non-default value and then restart it?

Sorry for the late response, For the question, Yes, TXS conserve the font size that I changed and the size of the others Bars except the secondary.

**Comment by jcardenast** [comment]
Can You tell me in the source code where can I find the part that load the configuration ? I will help to track the bug in the code.

**Comment by timhoffm** [comment]
search for `guiSecondaryToolbarIconSize` in `texstudio.cpp` and `configmanager.cpp`.

**Comment by MeanSquaredError** [comment]
Additionally the size of the secondary toolbar is kept in a configuration entry called `GUI\SecondaryToobarIconSize` in the configuration file `texstudio.ini`. 

You may try to 
1. Changing the secondary toolbar size from the options page
2. Exit TeXstudio
3. Check the value of the entry `GUI\SecondaryToobarIconSize` in the configuration file `texstudio.ini`

If the settings entry remains unchanged in the configuration file this means that the code that saves the configuration is broken.

If the settings entry is changed, this means that the code that reads the configuration and initializes the GUI is broken.

That would help to pinpoint the problem.

You can find the location of `texstudio.ini` by going to `Help/Check LaTeX Installation` and then once the system report is generated, searching for an entry called `Setting file:`

**Comment by jcardenast** [comment]
According to your recommendations, First, I tested the **texstudio.ini** , I changed on TeXstudio and it modifies the **GUI\SecondaryToobarIconSize** (13 is the set value), then I enter again to TXS and the problem still continue with the central bar (If you can see in the attached images before, this secondary toolbar has the problem). 

Moreover, I modified the **GUI\SecondaryToobarIconSize**  value in **texstudio.ini** directly and the problem contiues. So I checked the configmanager.cpp (I can't see nothing strange) and in texstudio.cpp I saw two lines:

line 285 ----   iconSize = qRound(qMax(16, configManager.guiSecondaryToolbarIconSize)*scale);
line 1443	---- int iconWidth=qRound(configManager.guiSecondaryToolbarIconSize*scale);

line 285 caught my attention, If the value in the **configManager.guiSecondaryToolbarIconSize** is 13, is not being bigger with that 16 value? because I made smaller the icon size. 

if I got it wrong, I will apologize for not understaning well the entire code. I will study the code in depth to help TXS.

**Comment by jcardenast** [comment]
I tested making bigger the icons for the secondary bar and the size it's keep. This 16 value I think is the problem.

**Comment by MeanSquaredError** [comment]
@jcardenast 
Thank you for checking that.

If line 285 is the problem then it means that TeXstudio will never set upon startup the icon size to be smaller than  a certain amount.

So I would expect that if you make the secondary toolbar size smaller than the default and then exit and restart TeXstudio , then the secondary toolbar size will be reset to the default size.

On the other hand if you make the secondary toolbar size bigger than the default and then exit and restart TeXstudio, then the secondary toolbar size will persist across restart and the toolbar size upon startup will be bigger than the default size.

Can you please check if that is the case indeed?

**Comment by jcardenast** [comment]
Yes, this is exactly what I tested and it works as you say. 

Well, I saw that the minimun value in the slider is 8, so I don't know if the minimun could be changed to 12 maybe, because the icons size in Windows looks bigger with the default values. I attached an image of my configuration that I resized to make the bottons looks as normal. You can compare the 12 size vs 16 size (the secondary toolbar in the middle is the only one that is not reduced at the restart, the others retained the new size )
![txs1](https://user-images.githubusercontent.com/12958198/73767340-586bd980-4745-11ea-9c17-3a95046702d9.jpg)

The second image is how it looks with the default size.

![tx2](https://user-images.githubusercontent.com/12958198/73767352-5c97f700-4745-11ea-9315-8a67dfa1a29e.jpg)

I hope I helped you with something

**Comment by MeanSquaredError** [comment]
If I prepare a binary build of TeXstudio with modified line 285 (without qMax limitation) will you be able to install it on your computer and test it whether it will work correctly?

**Comment by jcardenast** [comment]
Yes, I can do that.

**Comment by MeanSquaredError** [comment]
Hi,

I have uploaded a binary build of TXS that does not set minimum icon size for the secondary toolbar.
You can download the zipped build from https://gofile.io/?c=fxPjGj

The new build contains only texstudio.exe and the required .dll files. So you will need to unpack it on a computer that already has an installation of TeXstudio, because the new build will use the data files from the existing TeXstudio installation.
After unpacking the zip file the new files can stay in a separate directory - you don't have to overwrite your existing installation of TeXstudio.
The new build does not support the embedded PDF viewer, so only external PDF viewer is supported.

Please test it and let me know if the problem with the secondary toolbar size is still present in the new build.

**Comment by jcardenast** [comment]
I cannot run due to an error. Can I use it on a Zip version and replace .exe file with that?

![failed](https://user-images.githubusercontent.com/12958198/74264370-8ebdd180-4cce-11ea-8c72-ae5983894e5e.jpg)

**Comment by MeanSquaredError** [comment]
I am sorry, the .zip file was missing two .dll files
```
platforms\qwindows.dll
platforms/qminimal.dll
```
I created a new archive texstudio-secondary-toolbar-2.zip, please download it from
https://gofile.io/?c=lqBZtn
and try to run TXS from the unzipped file.

**Comment by jcardenast** [comment]
It works perfect. I modified making bigger and smaller the icons and it conserves it.

**Comment by MeanSquaredError** [comment]
Thank you for the information. Can you please let me know:
1. What is the screen resolution that you use?
2. What is the scaling (in percentages) applied to your screen.

You can see these settings from Start > Settings > System > Display

This article shows a the exact screen with the relevant settings  in the control panel:
https://www.pcworld.com/article/2953978/use-windows-10s-individual-display-scaling-to-perfect-your-multi-monitor-setup.html

**Comment by jcardenast** [comment]
For Windows 10
 -  screen resolution : 1920 x 1080
 - scaling : 125 (recommended by system) 

For Windows 8.1
 - screen resolution : 1920 x 1080
 - scaling :  100 (I'm not sure, its in the middle of the slider)
