### ISSUE TITLE
Additional search paths is not working with relative paths

### ISSUE THREAD

**Issue by klieret** [texstudio-org/texstudio#890]
I use a ``build`` directory together with the ``-output-directory build`` option of TeXStudio. 

However, the pdf is not found for the internal and external viewer (**but the log file seems to be found**), even though ``build`` or ``./build`` is specified in the additional search paths for both log file and pdf file. 

**It does however work when using absolute paths.**

### Environment
- TeXstudio: 2.12.20
- Qt: 5.9.5
- OS: Ubuntu 18.04 (``Linux version 5.0.0-37-generic (buildd@lcy01-amd64-023) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019
``)
- TeX distribution: texlive 2017/Debian

### Expected behavior

PDF is found by internal/external viewer when specifying ``build`` as search path

### Actual behavior

PDF is not found (``failed to find file "<path without build directory>"``)

### How to reproduce

1. Add  ``-output-directory build`` to LaTeX commands
2. Add ``build`` to log file and pdf file search paths
3. Build and view

**Comment by MeanSquaredError** [comment]
This was fixed in 2.12.22beta2
https://github.com/texstudio-org/texstudio/releases/tag/2.12.22beta2

**Comment by MeanSquaredError** [comment]
You can try the appimage from the above link.
Or you can try TXS 3.0.0
https://launchpad.net/~sunderme/+archive/ubuntu/texstudio-daily
3.0.0 has this issue fixed too, but since it is alpha, you may prefer using 2.12.22.

IIRC the the final 2.12.22 should be available within a couple of days.

**Comment by klieret** [comment]
Thanks a lot @MeanSquaredError  

I will try that!
