### ISSUE TITLE
[RFE] add \ar to tikz-cd.cwl and \tikztostart to tikz.cwl

### ISSUE THREAD

**Issue by chsk-uk** [texstudio-org/texstudio#897]
Minor request for enhancement: please

* add `\ar` to `tikz-cd.cwl` (this is an alias for `\arrow`), and
* add `\tikztostart` to `tikz.cwl` (alongside `\tikztonodes` and `\tikztotarget`).

Thank you!

**Comment by muzimuzhi** [comment]
I will add them (and maybe more) in two days. 

Currently, I am afraid that cwl files for `tikz`-related packages are more or less incomplete in both options and commands/environments.

**Comment by chsk-uk** [comment]
Excellent. Thank you for the quick fix!
