### ISSUE TITLE
Crash when opening master document

### ISSUE THREAD

**Issue by ProcyonTheEvil** [texstudio-org/texstudio#899]
### Environment
- TeXstudio: 2.12.22
- Qt: 5.12.1
- OS: Windows 8.1 Professional, all applicable Windows Updates are installed
- TeX distribution: miktex, last updated a few days ago

### Expected behavior
Texstudio should open the tex file listed as the master document under File -> Last opened files.

### Actual behavior
Texstudio crashes when clicking the "Master document: M <filepath>" menu entry.

Windows reports this information:
Problemsignatur:
  Problemereignisname:	APPCRASH
  Anwendungsname:	texstudio.exe
  Anwendungsversion:	0.0.0.0
  Anwendungszeitstempel:	5e22d191
  Fehlermodulname:	texstudio.exe
  Fehlermodulversion:	0.0.0.0
  Fehlermodulzeitstempel:	5e22d191
  Ausnahmecode:	c0000005
  Ausnahmeoffset:	014504c1
  Betriebsystemversion:	6.3.9600.2.0.0.256.48
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	5861
  Zusatzinformation 2:	5861822e1919d7c014bbb064c64908b2
  Zusatzinformation 3:	6fbe
  Zusatzinformation 4:	6fbe6bde2701766d81cbca0597a5fa35

### How to reproduce
(I do not know whether all of the first steps are needed to reproduce the issue. This is what I did.)
1. When using Texstudio, set one file as the master document.
2. Unselect the file as the master document (when you get annoyed because you are working on a completely different document, you want to compile it, hit F5, and Texstudio compiles the master document and not the one you are working on).
3. Update Texstudio to 2.12.20.
4. Open Texstudio, it loads the documents from the last session automatically.
5. Close all documents, including the master document, leave one other tex file open.
6. Select File -> Last opened files -> Master document.
7. Crash!
8. Update Texstudio to 2.12.22.
9. Repeat steps 4 to 7. It crashes again.

PS: I just "resolved" this issue by omitting step 5. Texstudio then correctly focused on the former master document.

Second, more reliable and shorter way to reproduce:
1. Open Texstudio, it automatically loads 2 files in my session: Master document 1.tex and a second one, that is included by \input{2.tex}
2. Select Options -> Master document -> Detect automatically. Master document was set to 1.tex at this point.
3. Close the master document 1.tex.
4. Select "File" -> "Last opened files" -> "Master document: M <filepath to 1.tex>"
5. Crash!

**Comment by MeanSquaredError** [comment]
I couldn't reproduce the problem on Windows 7, seems to work correctly there.

**Comment by ProcyonTheEvil** [comment]
OK, a more precise way to reproduce the crash:
1. Start Texstudio with the command
`"C:\Program Files (x86)\TeXstudio\texstudio.exe" --config %TEMP%\texstudio --start-always`
The configuration directory is empty.
2. Open the two files "document.tex" and "document2.tex" with the following content:
document.tex:
`\documentclass{article}
\input{document2.tex}
\begin{document}
	\test
\end{document}`
document2.tex:
`\newcommand{\test}{Test}`
3. Select "document.tex" as the root document by clicking on Options -> Root document -> Select current document explicitely...
4. Close the root document "document.tex"
5. Select Options -> Root document -> Detect automatically.
6. Select File -> Last opened -> Master document
7. Crash!

Texstudio does *not* crash when either the root document is not closed or the second file is closed too (i.e. no file is opened).

If you can create a debug build for me (portable version please) and tell me exactely what to do, I can try to generate some debugging output for you.

**Comment by sunderme** [comment]
please try 3.0.0 development build (bintray.com/sunderme/...)

**Comment by ProcyonTheEvil** [comment]
> please try 3.0.0 development build (bintray.com/sunderme/...)

I tested it with TeXstudio 3.00.00 (git 3.0.0alpha1-12-g508e05b) and it did not crash but opened the correct file. Thank you!

Keep up your awesome work!
