### ISSUE TITLE
Crash on opening PDF

### ISSUE THREAD

**Issue by Krzmbrzl** [texstudio-org/texstudio#9]
Im using TexStudio on Manjaro Linux and I am currently experiencing that it will crash on opening some PDFs in the internal viewer.
It will print out
```crashed with signal SIGSEGV
crashed with signal SIGSEGV
crashed with signal SIGSEGV
crashed with signal SIGSEGV
crashed with signal SIGSEGV
Forced kill after recovering failed after: SIGSEGV
```
in the console and then it's gone.

**Comment by Krzmbrzl** [comment]
This behaviour does only occur when using the internal PDF viewer

**Comment by sunderme** [comment]
how is your document compiled ? lualatex ?

**Comment by Krzmbrzl** [comment]
Yes it's compiled via `latexmk` with the `-pdflatex=lualatex` option

**Comment by sunderme** [comment]
lualatex/texlive2019 has a bug concerning synctex. We have used a newer version of synctex in our newer builds. So build txs from current git state or use build from https://build.opensuse.org/package/show/home:jsundermeyer/texstudio-2.12.8 (beta)

**Comment by Krzmbrzl** [comment]
Alright thank you very much for the support!

I am currently building from the current master-branch and I'll report back whether it worked.

As a side-note: The site you provided for downloading the beta doesn't seem to actually contain the respective file... The `texstudio-2.12.8.orig.tar.gz ` does not have a button for downloading it.

**Comment by jonasstein** [comment]
@sunderme until which version is the bug in synctex? The latest on Texlive is now synctex-45839

**Comment by sergiokapone** [comment]
If it is possible, can you please upload newer build for MS Windows?

**Comment by jonasstein** [comment]
I have prepared a new package for gentoo. If you can tag a release (2.12.7 for instance) soon, we could ship the latest fixes to our users. I think there has been a lot progress since 2.12.6 (thank you for this at this point) and it is worth to make a bump.
If it is not on schedule soon, we will have to think about a patch release 2.12.6_p2018...

**Comment by Krzmbrzl** [comment]
Okay since using the up-to-date-build no further crashes occured.
Considering that it crashed every 2-3 compilations I think it's save to say that the bug is indeed fixed with the new version.
