### ISSUE TITLE
Move option "Show messages when starting compiling" from advanced to standard options

### ISSUE THREAD

**Issue by Taneeda** [texstudio-org/texstudio#90]
TeXstudio 2.12.8 (hg 2.12.8-1-g68cd350)
Qt-Version 5.8.0, compiled with Qt 5.8.0 R

Feature Request: 
New option to show compile log after compile or show in case of active error/warning. The problem I have is that I don't get automatically informed about new warnings during work, so please show log after compile per default or make an option to allow setting this behaviour.

Greetings Taneeda

**Comment by Taneeda** [comment]
Ok, actually I found the "advanced options" with the setting "Build"-->"Show messages when starting compiling", which I can deactivate and then the view remains on log tab. This is what I want. Maybe this setting could be moved to standard options view...

**Comment by sunderme** [comment]
you have found it in the end ...
There are way too many options an someone will always argue that one particular option should be a regular one, so we don't change any.

**Comment by Taneeda** [comment]
Yap, you are right
