### ISSUE TITLE
Add TexLab support 

### ISSUE THREAD

**Issue by Krzmbrzl** [texstudio-org/texstudio#901]
I just found out that there exists a language server for LaTeX: [TexLab](https://github.com/latex-lsp/texlab) 

I think a tool like TeXStudio could hugely benefit by integrating this language server as a backend (maybe with a setting to use or not use it).

**Comment by sunderme** [comment]
unless there is a really great advantage, I don't see value.
I have tried the visual studio plug-in and I have not noted anything more elaborate (rather the opposite)

**Comment by Krzmbrzl** [comment]
Hm okay - I haven't actually tried it yet.
One advantage that comes to my mind would be that you don't need a cwl file for content assist and the like. At least if the Readme is correct...

**Comment by sunderme** [comment]
The file content assist is horrible.
It does not know anything about the command arguments (as there is no syntactical definition in tex).
It does not know whether it demands labels, colors, length ,etc.
Furthermore is does not prioritize (default, seldomly used, etc), so you get flooded with useless suggestions. This would be a huge step back ...

**Comment by Krzmbrzl** [comment]
Well I expected more of it xD

**Comment by muzimuzhi** [comment]
> One advantage that comes to my mind would be that you don't need a cwl file for content assist and the like. At least if the Readme is correct...

TexLab also uses a cwl-like file, called [language.json](https://github.com/latex-lsp/texlab/blob/995b44ff67bef49f7d391a7b1eb711b9f1877253/crates/texlab_syntax/src/language.json), to store names of commands and environments and their number of arguments respectively. And currently that `language.json` contains far fewer info than texstudio's cwl files.

Furthermore, as far as the generation of that auto-completion info (number, name, and type of arguments, available option list) need more or less human effort, files like cwl used by texstudio and json used by TexLab will continue to exist.
