### ISSUE TITLE
Adjust built filename for macOS from "texstudio.app" to "TeXstudio.app"

### ISSUE THREAD

**Issue by n1lsh** [texstudio-org/texstudio#910]
This is only a tiny annoyance, but the built ".app" file is currently named "texstudio.app". The actual name of the program is "TeXstudio". 

Could you please adjust the built name to "TeXstudio.app" such that the naming is in conformity with pretty much any other app built for macOS? 

I'm mainly asking because package managers such as Homebrew do not change the original file name.

**Comment by sunderme** [comment]
I assume that then we have to rename the binary as well.
I have no intentions to do that ...
