### ISSUE TITLE
Texstudio 2.12.22 installed but under programs&features version 2.12.18 is shown but in app itself under about it shows 2.12.22 - similar to #586

### ISSUE THREAD

**Issue by Saxomania** [texstudio-org/texstudio#913]
### Environment
- TeXstudio:    2.12.22
- Qt:  5
- OS:  Windows

### Expected behavior

under programs&features version 2.12.22 should be shown

### Actual behavior

under programs&features version 2.12.18 is shown

### How to reproduce

install Texstudio 2.12.22 on windows and check under programs&features then version 2.12.18 is shown but in app itself under about it shows 2.12.22

**Comment by sunderme** [comment]
this is fixed in source code.
The next release will not have that issue any more.

**Comment by Saxomania** [comment]
great
