### ISSUE TITLE
Can not install in macOS 10.15.2

### ISSUE THREAD

**Issue by debvrat** [texstudio-org/texstudio#915]
### Environment
- TeXstudio: 2.12.22
- OS: MacOS Catalina 10.15.2

### Expected behavior
The software should install

### Actual behavior
While trying to open the dmg, I get a message which says, "macOS cannot verify that this app is free from malware". Due to which, I cannot install the software. I do not even have the option to ignore this message. I can only move it to the bin.

### How to reproduce
 - Download the dmg file for texstudio 10.12.22 from your website
 - Double click on the dmg file
 - A window will open up with the Texstudio icon inside it (Note that this is different from the drag option we get generally, when trying to install dmgs)
![Screenshot 2020-01-31 at 1 33 52 PM](https://user-images.githubusercontent.com/11220845/73564899-90fe7100-442e-11ea-82f2-e759d49fb0f5.png)
 - Double click on this icon
 - Shows a dialogue box which says texstudio may have malware.
![Screenshot 2020-01-31 at 1 34 07 PM](https://user-images.githubusercontent.com/11220845/73564898-90fe7100-442e-11ea-8bae-8193f0754a4b.png)

**Comment by sunderme** [comment]
let's quote our website (texstudio.org):

`Please note: Because we do not have an Apple Developer Account, OS X may complain about an unidentified developer and deny opening TXS. In that case, open the context menu on the TXS icon (Ctrl + Click) and select open.`
