### ISSUE TITLE
Question about LatexDocument::checkNextLine

### ISSUE THREAD

**Issue by MeanSquaredError** [texstudio-org/texstudio#918]
Hi,

I am looking at the latest code of `SyntaxCheck` and one thing caught my attention.
It seems that in `SyntaxCheck::run` once it processes one line it optionally emits the signal `checkNextLine` which is handled by `LatexDocument`. In turn `LatexDocument::checkNextLine` processes the signal and then calls `SyntaxCheck::putLine` to queue the next line for processing.

As far as I see `LatexDocument::checkNextLine` does not really need to access the members of the `LatexDocument` object except for `LatexDocument::unclosedEnv` and the latter data member is not really dependent in any way on the `LatexDocument` class.

Is there a reason why `LatexDocument::checkNextLine` is not moved into `SyntaxCheck`? I think that this will make the code simpler and will also make it easier to clear some nasty race conditions in the tests in `SyntaxCheckTest`. Currently the tests in SyntaxCheckTest don't work very reliably especially when some other program loads the CPU during the tests. There is no easy way to fix that because due to the asyncronous nature of the `checkNextLine` event we cannot reliably catch the moment when `SyntaxCheck` has finished the processing of the queued lines.

I would expect that removing `checkNextLine` will simplify things a bit. So is there something (e.g. a design decision) that I am missing which forces the use of this separate signal?

**Comment by sunderme** [comment]
`int index = indexOf(dlh,hint);` is the function of document. 
what race condition ?

**Comment by MeanSquaredError** [comment]
`LatexDocument::indexOf` is inherited from `QDocument::indexOf`
On the other hand every `QDocumentLineHandle` object has a member `QDocument::m_doc` which points to the owner document, so we can always call `QDocument::indexOf` through the `QDocumentLineHandle` object alone.

In fact there is the convenience method `QDocumentLineHandle::line()` which delegates the call to `QDocument::indexOf`.

So I would say that we should be OK to move checkNextLine from `LatexDocument` into `SyntaxCheck` (unless I am missing something else too).

Regarding the race condition:
The code that we use to wait for the `SyntaxCheck` to finish is 
```
do{
        edView->document->SynChecker.waitForQueueProcess(); // wait for syntax checker to finish (as it runs in a parallel thread)
        QApplication::processEvents(QEventLoop::AllEvents,10); // SyntaxChecker posts events for rechecking other lines
}while(edView->document->SynChecker.queuedLines());
```
So basically we rely on `SyntaxChecker.queuedLines()` to tell us if there are no more queued lines in the `SyntaxCheck` queue. In turn `SyntaxChecker.queuedLines()` checks the semaphore via `SyntaxCheck::mLinesAvailable.available()`

However usually we just post the first line to SyntaxChecker and then once it processes a line it posts the `checkNextLine` event and then `LatexDocument::checkNextLine` queues the next line in the syntax checker. So in most cases while the syntax checker runs it either has one line in the queue or it has zero lines but it is processing the current line and shortly after that it will queue the next line.

So if the syntax checker is in `SyntaxCheck::run()`, just past `mLinesAvailable.acquire();` at the top, then `SyntaxCheck::mLinesAvailable.available()` will return 0, but shortly after that a new line will be queued and in fact the syntax checker is not over.

If we are running the tests in SyntaxCheckTest it is possible to get really unlucky and pass both tests (`waitForQueueProcess()` and `queuedLines()`) in
```
do{
        edView->document->SynChecker.waitForQueueProcess();
}while(edView->document->SynChecker.queuedLines());
```
Even though the syntax checker is not finished (in both cases there are no available lines in the semaphore but a new line is about to be queued).

The fact that `checkNextLine` is in a different thread is not the cause of the problem but it aggravates the problem because it is in a different thread and the signal is processed asynchronously so we don't really know when it exactly it will be processed and the next line will be queued (really depends on when exactly the main thread will process the events in `SyntaxCheck::waitForQueueProcess`). 

This is not really a big deal because it only affects the tests by making the `SyntaxCheckTest` and `LatexDocumentTest` fail now and then (`LatexDocument` also relies on `SyntaxCheck::waitForQueueProcess`). It really kicks in when the TXS tests are running and multiple higher priority processes kick in so the Linux scheduler begins playing with the TXS threads).

I think I can provide a fix but it would include moving `checkNextLine` entirely into `SyntaxCheck` in order to make the fix simpler. So that is why I was asking if it is OK for me to provide a fix that would also move about `checkNextLine` from `LatexDocument` to `SyntaxCheck`
