### ISSUE TITLE
Duplicate results in search

### ISSUE THREAD

**Issue by jaronowitz** [texstudio-org/texstudio#920]
### Environment
- TeXstudio:  2.12.22
- Qt:  5.12.1
- OS:  Windows(10)
- TeX distribution:  miktex

### Expected behavior
\label{unique_key} should not return a 'label defined multiple times!' error 

### Actual behavior
\label{unique_key} returns a 'label defined multiple times!' error. When searching for 'unique_key' and clicking the '+' button two search results are found pointing to the same place in the file.

### How to reproduce
Seems to be somehow associated with using the 'Root Document: Explicit' function. Also this issue is exactly the same as mine:
https://tex.stackexchange.com/questions/498076/duplicate-results-in-texstudio

![Latex_issue](https://user-images.githubusercontent.com/40301843/73775754-5735af00-473b-11ea-9a5e-6b671933475b.png)

**Comment by sunderme** [comment]
please provide a test case (text files) which we can reproduce.

why was it closed ?

**Comment by jaronowitz** [comment]
I closed it because I found a fix. In my include statement in the root document I included "Notes\Tex_files\..." instead of of the proper file location "Notes\TeX_files." It still included the correct file and compiled properly but as you can see in the included image, somehow it's causing the search to see two different documents. One at Tex_files and one at TeX_files. Not sure if it's a real bug but the problem is fixed for me.
