### ISSUE TITLE
Latex2e.html missing in 2.12.22 portable

### ISSUE THREAD

**Issue by sergiokapone** [texstudio-org/texstudio#925]
Why not available LaTeX Reference menu item? Why did the file latex2e disappear in the help\ folder?

**Comment by timhoffm** [comment]
Please state your issue more clearly; and please provide the TeXstudio version you are referring to.

**Comment by sergiokapone** [comment]
If I download the latest stable release 2.12.22 of portable .zip and look in \help\ folder I will not find there Latex2e.html

**Comment by timhoffm** [comment]
As a workaround, you can copy the file from a previous version.

**Comment by sunderme** [comment]
fixed
