### ISSUE TITLE
Feature Request: Texstudio does not parse subfiles that are \input{}

### ISSUE THREAD

**Issue by nattydread69** [texstudio-org/texstudio#927]
- TeXstudio: 2.12.14
- OS: ubuntu 19.10, kernel, 5.3.0-29

I am writing a book that is split into subdocuments that I load with \input{folder/filename}
They are blank file extensions not *.tex.
Currently texstudio does not colour highlight these files or parse them to add information about 
sections and subsections.
If I have the file named folder/filename.tex, the left panel flags file not found and the chapters appear at the bottom of the chapter list, not in the correct place, however the file is correctly parsed for highlighting.

I would really love to see this functionality added or improved.

Thanks

**Comment by sunderme** [comment]
Options/automatically load included files ?

**Comment by jrmoserbaltimore** [comment]
LaTeX automatically puts a `.tex` extension on the filename, e.g. `\input{tex_files/chapter1}` loads `tex_files/chapter1.tex`.
