### ISSUE TITLE
TXS Profile becomes corrupt - can't compile anymore

### ISSUE THREAD

**Issue by zelite** [texstudio-org/texstudio#928]
### Environment
- TeXstudio: TeXstudio 2.12.22 (git 2.12.22)
- Qt: Qt version 5.12.1, compiled with Qt 5.12.1 R
- OS: Windows 10
- TeX distribution: Texlive

### Expected behavior
I expect to be able to compile a document

### Actual behavior
When clicking compile I get an error:
(I have texstudio in portuguese)
"Erro: impossível iniciar o comando: Compilar & Ver" -> "Error: cannot start command: Build&View"

Nothing appears in the logs. Nothing starts compiling.

### How to reproduce
Thats's a bit hard to describe. Earlier it happened after changing the identation settings (Options->Editor->Identation Mode). The Build would stop working and the only way to have it working again was to reset to the default settings.  I tried to reproduce the error by changing the settings again and I could not. Everything kept working. Then just to be safe, I exported my .txsprofile.

Today, the Build stopped working again.  The last setting I changed was adding the "emphasis" button to the middle toolbar. 

Because I had saved a working .txsprofile from earlier, I made a diff between the working one and the current one and these are the main differences: 

**Not Working**

```
Tools\Commands\quick=Compilar & Ver
Tools\Commands\compile=Latexmk
Tools\Commands\view=Visualizador PDF
Tools\Commands\view-pdf=Visualizador PDF interno (embebido)
Tools\Commands\bibliography=BibTeX
```

**Working**

```
Tools\Commands\quick=txs:///compile | txs:///view
Tools\Commands\compile=txs:///latexmk
Tools\Commands\view=txs:///view-pdf
Tools\Commands\view-pdf=txs:///view-pdf-internal --embedded
Tools\Commands\bibliography=txs:///bibtex
```

In the not working version, under commands, it shows the translated strings of the commands as they appear in the ui. In the working version, it shows the "txs://" link/command.

**Comment by sunderme** [comment]
I would need a clearer way to reproduce the issue...

**Comment by sunderme** [comment]
no feedback
