### ISSUE TITLE
I can not set languagetool arguments

### ISSUE THREAD

**Issue by etienne-monier** [texstudio-org/texstudio#930]
Hi,

I want to set languagetool (LT) for TexStudio (TS), but I need to give arguments to it. The problem is that all support I found for that showed  a TS config panel with a LT arguments field but this field is absent in my installation, so that the languagetool server tells me `Error: Missing arguments for LanguageTool API. Please see https://languagetool.org/http-api/swagger-ui/#/default`.

Here is some info (French, sorry):

```
TeXstudio 2.10.8 (hg 5802:5ee1d048e556)
Utilise Qt version 5.5.1, compilé avec Qt 5.5.1 R
```

By the way, my LT version is 4.8, but that's OK with QT5.

Thanks.

**Comment by sunderme** [comment]
how about updating to a current version of txs and then we can see ?
Not really  interested in supporting obsolete versions of txs ...

**Comment by etienne-monier** [comment]
Oops ! I installed it from Ubuntu 18.04 repos, but this version is old.
I installed it from ppa and the latest version works fine.
Sorry :s And thanks !

Closed !
