### ISSUE TITLE
\multicolumn does not get parsed correctly when first/second argument are not in braces

### ISSUE THREAD

**Issue by chsk-uk** [texstudio-org/texstudio#932]
`\multicolumn` is not parsed correctly by TeXstudio when the first/second argument are not enclosed in braces, e.g. when the user writes `\multicolumn2c{...}` rather than `\multicolumn{2}{c}{...}`; see the example below. This is not merely a cosmetic issue either, as it causes the "Align Columns" functionality to insert spurious ampersands.

### Environment
- TeXstudio: 2.12.22
- Qt: 5.12.1
- OS: Windows 10, 64-bit
- TeX distribution: MiKTeX

### Example

```
\documentclass{article}
\usepackage{booktabs}
\begin{document}
\begin{tabular}{ll}
\toprule
	\multicolumn{2}{l}{This line is parsed correctly.} \\
	\multicolumn2l{This line is not parsed correctly.} \\
\bottomrule
\end{tabular}
\end{document}
```

### Expected behavior

TeXstudio recognizes that `\multicolumn2c{...}` creates a cell spanning two columns.

### Actual behavior

TeXstudio does not recognize that `\multicolumn2c{...}` creates a cell spanning two columns. In particular, clicking on "Align Columns" for this `tabular` environment inserts a spurious ampersand, as follows:

```
\documentclass{article}
\usepackage{booktabs}
\begin{document}
\begin{tabular}{ll}
\toprule
	\multicolumn{2}{l}{This line is parsed correctly.}    \\
	\multicolumn2l{This line is not parsed correctly.} &  \\
\bottomrule
\end{tabular}
\end{document}
```

**Comment by sunderme** [comment]
be reasonable.
though you can do a lot of syntactically strange stuff with latex/tex, the editor does not completely understand all aspects of tex. Especially unusual and unnecessary variants are not supported and \multicolumn2l without spaces is definitely one of those.
