### ISSUE TITLE
Current official release of TXS?

### ISSUE THREAD

**Issue by dbitouze** [texstudio-org/texstudio#936]
Which is the current official release of TXS:

- 2.12.16, as written [here](http://texstudio.sourceforge.net/#news)?
- 2.12.22, as written [here](https://github.com/texstudio-org/texstudio/releases/tag/2.12.22)?

**Comment by muzimuzhi** [comment]
2.12.22. Info on texstudio.sourceforge.net may be out-of-date.

**Comment by dbitouze** [comment]
> 2.12.22. Info on texstudio.sourceforge.net may be out-of-date.

Thanks. 

That's unfortunate since average TXS users just want to use it, not to participate to its development and would be puzzled by a GitHub repository. IMHO, the TXS "official" Web site should be up to date. But I know, you @muzimuzhi, are not responsible of this :smile:

**Comment by sunderme** [comment]
done

**Comment by muzimuzhi** [comment]
@sunderme 
The sentence `This is the last release supporting Qt4.` occurs in webpage http://texstudio.sourceforge.net/#news three times. It should only appear in the latest release note (the note for 2.12.22).

Sorry for not opening a new issue.
