### ISSUE TITLE
path:pattern Error in java-path

### ISSUE THREAD

**Issue by tsfg** [texstudio-org/texstudio#938]
### Environment
- TeXstudio: 2.12.22 as well as
                    3.00.00 (git 3.0.0alpha1-23-ge3a4e40) and 3.00.00 (git 3.0.0alpha1-52-gb124ef0)
- Qt: 5.12.1
- OS: Windows7 
- TeX distribution: miktex
### Expected behavior
LanguageTool integration. LanguageTool test result is o.k.

### Actual behavior
LT is not started with TS. 
Performing  Help> Test LT configuration shows in LT Bericht.txt (German GUI-language): 
```
where java: 

JAVA: C:\Program Files\AdoptOpenJDK\jre-11.0.6.10-hotspot\bin\java.exe -version

Echzeitprüfungen sind aktiviert.
Grammatikprüfungen sind aktiviert.

Versucht es automatisch zu starten.

Aktueller Status von LT:Fehler

LT-URL: http://localhost:8081/v2/check
```
Messages show:
```
Prozess gestartet: where C:\Program Files\AdoptOpenJDK\jre-11.0.6.10-hotspot\bin\java.exe

FEHLER: Ungltiges Schema in "path:pattern" angegeben.

Prozess endete mit Fehler(n)

```

_btw: There is  "Un**gl**tiges Schema" insted of "Un**gül**tiges" Schema but as I copy it, it is "Ungltiges Schema"_

Here a screenshot sniplet of the configuration:
![grafik](https://user-images.githubusercontent.com/16896599/74553289-5977e480-4f57-11ea-8518-7138d889f1ef.png)

**Comment by MeanSquaredError** [comment]
Does it make a difference if you specify the `Java:` setting as `java` instead of the current `C:\Program Files\AdoptOpenJDK\jre-11.0.6.10-hotspot\bin\java.exe` ?

**Comment by tsfg** [comment]
Yes, a slight difference:
I replaced `C:\Program Files\AdoptOpenJDK\jre-11.0.6.10-hotspot\bin\java.exe` with `java`
and hence, LT Bericht.txt changed to
```
where java: C:\Program Files\AdoptOpenJDK\jre-11.0.6.10-hotspot\bin\java.exe
C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot\bin\java.exe
C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
C:\ProgramData\Oracle\Java\javapath\java.exe

JAVA: java -version

Echzeitprüfungen sind aktiviert.
Grammatikprüfungen sind aktiviert.

Versucht es automatisch zu starten.

Aktueller Status von LT:Fehler

LT-URL: http://localhost:8081/v2/check
```
and the messages window show
```
Prozess gestartet: where java

C:\Program Files\AdoptOpenJDK\jre-11.0.6.10-hotspot\bin\java.exe
C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot\bin\java.exe
C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
C:\ProgramData\Oracle\Java\javapath\java.exe

Prozess endete normal
```
if I replace with `Java` (capital"J")
it looks a little different:
LT Bericht.txt:
```
where java: C:\Program Files\AdoptOpenJDK\jre-11.0.6.10-hotspot\bin\java.exe
C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot\bin\java.exe
C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
C:\ProgramData\Oracle\Java\javapath\java.exe

JAVA: Java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

Echzeitprüfungen sind aktiviert.
Grammatikprüfungen sind aktiviert.

Versucht es automatisch zu starten.

Aktueller Status von LT:Fehler

LT-URL: http://localhost:8081/v2/check
```
and messages:
```
Prozess gestartet: where Java

C:\Program Files\AdoptOpenJDK\jre-11.0.6.10-hotspot\bin\java.exe
C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot\bin\java.exe
C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
C:\ProgramData\Oracle\Java\javapath\java.exe

Prozess endete normal
```
But even with `Java` after a restart LT is not started.

**Comment by sunderme** [comment]
It seems that you have 2 java installations on your computer.
First thing to do, get LT running on the computer manually.
Try the steps described on http://wiki.languagetool.org/http-server .
If that works, we can try a bit more.

**Comment by tsfg** [comment]
You are right, I have the Oracle and moved to the AdoptOpen.

Using `java -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8081 --allow-origin "*" ` everything went right and when starting TeXStudio afterwards I gel a bunch of status lines in the command window like this : 
```
2020-02-16 14:33:01 +0100 INFO  org.languagetool.server.TextChecker Check done: 4660 chars, de-DE, #253, null, 674 matches, 9188ms, agent:-, sent, q:0, h:1, dH:1, m:all
```
Using the LT-configuration test option in TXS the L-Bericht shows:
```
where java: C:\Program Files\AdoptOpenJDK\jre-11.0.6.10-hotspot\bin\java.exe
C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot\bin\java.exe
C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
C:\ProgramData\Oracle\Java\javapath\java.exe

JAVA: Java -version

Echzeitprüfungen sind aktiviert.
Grammatikprüfungen sind aktiviert.

Versucht es automatisch zu starten.

Aktueller Status von LT:arbeitet

LT-URL: http://localhost:8081/v2/check
```
If I first start TXS  and afterwards run the cmd-command the result is the same as described yesterday.

**Comment by sunderme** [comment]
could you set LT-Path to "....\languagetool-server.jar" ?

**Comment by sunderme** [comment]
can please try out https://bintray.com/sunderme/texstudio/download_file?file_path=texstudio-win-3.00.00-202002182039-git_692a0ac.exe
It should give more error information in the LT report as well as when hovering over the LT-icon in the status bar.

**Comment by tsfg** [comment]
I tried the mentioned version (692a0ac),  is there a difference between *.zip- and the *. exe -Version. I used the zip. And to mention : In the "Über TexStudio"-Window only "TeXstudio 3.00.00 (git )" is shown.
Here the results (I see no more verbose output ?):
first with the same settings as before:
nothing changed beside, the difference between `java` and `Java` has gone and is the same as the capitalized version above.
with ...\languagetool-server.jar leaving the parameters as before.
LT-Bericht first gives : 
```
where java: C:\Program Files\AdoptOpenJDK\jre-11.0.6.10-hotspot\bin\java.exe
C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot\bin\java.exe
C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
C:\ProgramData\Oracle\Java\javapath\java.exe

JAVA: java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

Echzeitprüfungen sind aktiviert.
Grammatikprüfungen sind aktiviert.

Versucht es automatisch zu starten.

Aktueller Status von LT:Fehler


LT-URL: http://localhost:8081/v2/check
``` 
Messages
```
Prozess gestartet: where java

C:\Program Files\AdoptOpenJDK\jre-11.0.6.10-hotspot\bin\java.exe
C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot\bin\java.exe
C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
C:\ProgramData\Oracle\Java\javapath\java.exe

Prozess endete normal
```
after a short while (~15s after opening a document) the Status-Bar icon changed to the blue line and afterwards 
LT-Bericht changed to:
```
where java: C:\Program Files\AdoptOpenJDK\jre-11.0.6.10-hotspot\bin\java.exe
C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot\bin\java.exe
C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
C:\ProgramData\Oracle\Java\javapath\java.exe

JAVA: java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

Echzeitprüfungen sind aktiviert.
Grammatikprüfungen sind aktiviert.

Versucht es automatisch zu starten.

Aktueller Status von LT:arbeitet

LT-URL: http://localhost:8081/v2/check
```
As I quit TXS the corresponding java-process quits as well.

**Comment by sunderme** [comment]
Exe contains the installer, zip is the portable version.

So, in your last experiment, LT started as expected though rather slowly. Possibly because of that no error message was given.

**Comment by sunderme** [comment]
What language code does your spell-checker use ?
By any chance de_de_frami ?

**Comment by tsfg** [comment]
How / Where do I can find this information ? 
The setting in TXS is de_DE.

**Comment by sunderme** [comment]
de_DE is the setting I was looking for, so everything is fine.

**Comment by sunderme** [comment]
so, we are good now ?

**Comment by tsfg** [comment]
In the latest stable version (TeXstudio 2.12.22 (git 2.12.22) ) the modification doesn't offer the solution.

In the latest beta ``TeXstudio 3.00.00 (git )`` (from 'Über TexStudio', the git version info vanished some versions ago)  file name texstudio-win-3.00.00-202002231449-git_f2cb06a everything is working as expected. 

Any did you made relevant changes in the code beside the more verbose info telling?

By the way: Is the connection to a running LT only tested at start-up of TXS ? What about if one terminates or comes up during a running TXS-session?

**Comment by sunderme** [comment]
released versions are not modified by any changes, only newer versions of txs will have fixes.
There is a change about paths with spaces in it and one about improper language codes.
So, possibly the first one helped.

txs keeps trying to get a connection.
