### ISSUE TITLE
Width adaptation issue in the structure sidepanel

### ISSUE THREAD

**Issue by Tikrass** [texstudio-org/texstudio#94]
### Environment
- TeXstudio: 2.12.8
- Qt: 5.10.1
- OS: Linux 4.15.14-1 (Arch Linux)
- TeX distribution: texlive

### How to reproduce

1. Create a new file, including some other file with a long file-name:
![bug2](https://user-images.githubusercontent.com/641293/38354480-0cd0d64c-38ba-11e8-89dc-43732af4902c.png)
2. Change the width of the side panel.
3. Save the file.
4. Modify the file arbirarily:
5. Lose focus of the window.
![bug](https://user-images.githubusercontent.com/641293/38354471-0942f654-38ba-11e8-8a36-ca891b439f63.png)

### Expected behavior
The file names in the structure side panel should be cut off dynamically according to the width of the side panel.

### Actual behavior
After loosing focus of the Texstudio window the file names are shortened to a constant quite short number of characters.

**Comment by sunderme** [comment]
Duplitcat #43
