### ISSUE TITLE
How to record package options in cwl files?

### ISSUE THREAD

**Issue by muzimuzhi** [texstudio-org/texstudio#944]
Some options can only be used during package loading (by `\usepackage`, `\RequirePackage`, and `\PassOptionsToPackage`), but I am not sure whether texstudio supports to record package options in cwl files or not.

**Comment by sunderme** [comment]
txs does not.
the automatic package scan is meant to provide some basic syntax checking, nothing more.

**Comment by muzimuzhi** [comment]
Thanks.
