### ISSUE TITLE
Wrong version number in the system control of Windows

### ISSUE THREAD

**Issue by update-freak** [texstudio-org/texstudio#947]
- TeXstudio: 2.12.22

### Expected behavior
2.12.22 is shown in the system control of Windows

### Actual behavior
2.12.18 is shown in the system control of Windows
![sys](https://user-images.githubusercontent.com/40196995/74845548-79305380-532f-11ea-8096-b8f300d75548.png)

**Comment by sunderme** [comment]
duplicate, fixed in dev version
