### ISSUE TITLE
Could not start Build & View:PdfLaTeX

### ISSUE THREAD

**Issue by Zaki-Mao** [texstudio-org/texstudio#949]
### Environment
- TeXstudio: 2.12.14 (git 2.12.14)
- Qt: 5.11.2 
- OS: MacOS
- TeX distribution: texlive 

### Expected behavior

build &view file successfully and save as pdf file.

### Actual behavior
when I click "build&view",it gives me a frame as follows.
"Could not start Build & View:PdfLaTeX:
pdflatex -synctex=1 -interaction=nonstopmode "my pdf file ".tex."
and can not save file as pdf form on my Mac table.

I have tried to restart TXS, but it doesn't change anything. who can help me?

**Comment by muzimuzhi** [comment]
Open the Finder containing your tex file, and then open Terminal.app by service [New Terminal at Finder](https://stackoverflow.com/a/53478777/8590320). Inside that Terminal window, can you successfully compile your tex file, using the following command?
```
pdflatex -synctex=1 -interaction=nonstopmode <name of your tex file>
```

If your tex file is named "file name.tex", then each of `file\ name.tex`, `'file name.tex'` are valid `<name of your tex file>`.

**Comment by sunderme** [comment]
no feedback
