### ISSUE TITLE
Missing "file version" entry

### ISSUE THREAD

**Issue by Spiegel-Leser** [texstudio-org/texstudio#95]
### Environment
- TeXstudio: 2.12.6
- OS: Windows 7 x64
### Expected behavior
- texstudio.exe should have "file version" set to "2.12.6"
### Actual behavior
- texstudio.exe does not have "file version" set.
- No file in the TeXstudio folder has a "file version" of "2.12.6"
### Important because
- external updating tool (SUMO) relies on application having "file version" set correctly

**Comment by sunderme** [comment]
should be fixed
