### ISSUE TITLE
Missing RedeclareSectionCommand

### ISSUE THREAD

**Issue by Sam1285** [texstudio-org/texstudio#952]
### Environment
- TeXstudio: 2.12.22
- Qt: 5.12.1 R
- OS: Windows 10 Pro
- TeX distribution: Texlive 2019

### Expected behavior
Find by Intellisense and no Error marking.

### Actual behavior
I am using the Koma-Script but the \RedeclareSectionCommand is missing. There is no Error in log but it's still marked red and the parameters are underlined red aswell.

### How to reproduce
Just create a Koma Class and try to fill in the command.

**Comment by sunderme** [comment]
https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions#how-does-txs-know-about-valid-commands

You can adapt the afflicted cwl file and provide the corrected version. I am sure that there are more commands missing but not all are really used...

**Comment by muzimuzhi** [comment]
Koma-Script classes provides hundreds of new commands, and currently the corresponding [cwl file](https://github.com/texstudio-org/texstudio/blob/master/completion/class-scrartcl,scrreprt,scrbook.cwl) contains very limited lines. I am willing to provide a more comprehensive (if not complete) cwl file for koma-script classes, but since koma-script is a big package bundle and I am not familiar with it before, this may take sometime.

PS: Texstudio has a cwl-auto-generation function, but it will not run for loaded packages or classes with existing cwl files. So the cwl for koma classes is not re-generated, although I think commands like `\RedeclareSectionCommand` can be auto-recognized if the function is on.

**Comment by sunderme** [comment]
all the auto generation is really only suitable for primitive syntax checking (command is known), since the declaration don't provide any argument definitions (text, math, etc) whatsoever.

**Comment by MeanSquaredError** [comment]
Maybe it is worth implementing some kind of helper command-line option that would disable for the current run the specified builtin .cwl file, e.g. `--disable-builtin-cwl filename.ext` ?
I think it might be useful in cases like this when someone tries to work on the improvement  of builtin classes like koma-script.

**Comment by sunderme** [comment]
on first glance, I am not convinced.
In most cases, extending an existing cwl manually is easier.
But just for large dumps, (for cwl developer) using a script which directly makes use of texdef may be helpful (see latexstyleparser.cpp: QStringList LatexStyleParser::readPackageTracing(QString fn) const...)

**Comment by muzimuzhi** [comment]
> all the auto generation is really only suitable for primitive syntax checking (command is known), since the declarations in the packages don't provide any argument definitions (text, math, etc).

Yes. Actually, there could be (at least) three stages:
 - stage one, no info. Command (or environment) is highlighted as undefined.
 - stage two, limited info. Command is highlighted as normal.
 - stage three, complete info, as far as possible. Command is highlighted as normal, and auto-completer gives right indication of the number and definitions of command arguments.

Current issue complains about meeting stage one, and the auto-generator can do some work of stage two. Lastly, stage three is most satisfied and need most human work as well. The state of included cwl file for koma-script classes is between stage one and two, a somewhat embarrassing state. 

A fully review for commonly used cwl files is most welcome, but is not a short-term project.

**Comment by sunderme** [comment]
there are not too many complains of faulty cwls.
As they are easy to understand and manage, I deem them a good starting point for getting users involved into maintaining them. No need for a few to carry all the burden...
