### ISSUE TITLE
\underline considered as a math mode command

### ISSUE THREAD

**Issue by thomas-daniels** [texstudio-org/texstudio#954]
### Environment
- TeXstudio: 2.12.22
- Qt: 5.12.4
- OS: Ubuntu 19.10
- TeX distribution: texlive

### Actual behavior

`\underline` is regarded as a math mode command.

Pressing `\underl<TAB>` makes `\underline{` appear. Pressing `\underl<TAB><TAB>` makes `$\underline{text}$` appear. Removing those dollar signs makes `\underline` appear in red, with a tooltip "math command outside math env".

### Expected behavior

`\underline` should not be regarded as math mode command; `\underl<TAB>` should make `\underline{text}` appear, and `\underline` outside a math environment should not be highlighted in red.

The commit that introduced this behavior is https://github.com/texstudio-org/texstudio/commit/352377a12883c980846ff0a01973d7f29f35455f.

**Comment by sunderme** [comment]
fixed

**Comment by muzimuzhi** [comment]
Other commands, at least `\overline`, need a similar fix.

In preparing https://github.com/texstudio-org/texstudio/commit/352377a12883c980846ff0a01973d7f29f35455f, I mainly referred the book _TeX for the Impatient_, which introduces plaintex format. But the valid working situation of some commands has changed from plaintex to latex2e format. For example, `\underline` and `\overline` are math mode only in plaintex, but are both text and math mode valid in latex2e.

I will review them during this weekends. Sorry for the bug.

**Comment by sunderme** [comment]
no worries
