### ISSUE TITLE
No declaration for shape T1/pzc/mb/it.

### ISSUE THREAD

**Issue by BeerStud** [texstudio-org/texstudio#960]
### Environment
- TeXstudio: 2.12.22
- Qt: 5.12.1
- OS: Windows 10 / amd64
- TeX distribution: miktex

### Expected behavior
Until this morning, the following worked fine:
{\usefont{T1}{pzc}{m}{it} \fontsize{22pt}{20pt}\selectfont %

### Actual behavior
Now, this error message is displayed:

LaTeX Font Info:    Trying to load font information for T1+pzc on input line 137.

("C:\Users\gerar\AppData\Local\Programs\MiKTeX 2.9\tex/latex/psnfss\t1pzc.fd"
File: t1pzc.fd 2001/06/04 font definitions for T1/pzc.
)
! No declaration for shape T1/pzc/mb/it.
sub@sfcnt ...e forspace shapespace mandatory@arg }
                                                  error@fontshape else #1{Fo...
l.137 	{\usefont{T1}{pzc}{m}{it}  \fontsize{22pt}{20pt}\selectfont %
This error message was generated by an \errmessage
command, so I can't give any explicit help.
Pretend that you're Hercule Poirot: Examine all clues,
and deduce the truth by order and method.

I updated MikTex earlier this morning, and now this problem has started. I reported this to MikTex, but they seem to believe it is not their problem. Personally, I do not believe them, but what can I do?

### How to reproduce
Simply run the file with that declaration in it. By the way, this was an existing file that ran perfectly until the MikTex update, which they claim is not their fault.

**Comment by sunderme** [comment]
does the same happen when you run pdflatex from command line.
but it looks like a font set-up problem, not caused by the text editor txs ....

**Comment by muzimuzhi** [comment]
@BeerStud 
This is a known bug of latex2e kernel (see https://github.com/latex3/latex2e/issues/289), and has been fixed in latex2e-dev. If you have installed package [latex-base-dev](https://ctan.org/pkg/latex-base-dev) , you can run `pdflatex-dev main.tex` to verify it yourself (that the problem has been fixed in dev).

Anyway, this is a latex usage problem, hence has nothing to do with the editor, texstudio.

**Comment by BeerStud** [comment]
Well, it works fine from the command line. I have not been able to get it integrated into TeXstudio, however. Obviously, I am not correctly changing the settings in the <Options> <Configure Texstudio ...><Build> menu. I changes all of the "pdflatex" commands to "pdflatex-dev"; however, that does not seem to be working. I receive the following error message:

Error: One command expansion invalid
  Parent Command: compile
  Primary Command: quick

I am open to suggestions.

**Comment by muzimuzhi** [comment]
In my side, this works.
![image](https://user-images.githubusercontent.com/6376638/75462433-37527d80-59bf-11ea-9c56-326b9a94ada0.png)

**Comment by BeerStud** [comment]
Thanks. I was attempting to change all of the 'pdflatex' setting under <Build>, which obviously did not work. I appreciate your assistance.

**Comment by muzimuzhi** [comment]
@BeerStud 
Hi, the LaTeX2e 2020-02-02 Patch level 5 has been released [6 hours ago](https://github.com/latex3/latex2e/releases/tag/release-2020-02-02-PL5). This release contains the fix you need, hence you can use `pdflatex` directly and forget `pdflatex-dev` for a while. In one or two days, CTAN mirrors across the world will sync to this update and then you can use texlive (or miktex) package manager to install the release.

**Comment by BeerStud** [comment]
Thanks, I really appreciate the 'heads-up'.
