### ISSUE TITLE
Incorrect rendering of certain fonts in TeXstudio pdf viewer

### ISSUE THREAD

**Issue by fjhickernell** [texstudio-org/texstudio#97]
### Environment
- TeXstudio: 
- Qt: Version 5.10.0
- OS: Mac Version 10.13.4
- TeX distribution: MacTeX

### Expected behavior
The pdf reader in TeXstudio should render the fonts correctly.

### Actual behavior
Adobe and Preview render it fine, but TeXstudio renders certain characters wrong, e.g., the superscript in the following minimum working example.

### How to reproduce
%Example of bad pdf
\documentclass{beamer}
\usepackage{newpxtext}
\usepackage[euler-digits,euler-hat-accent]{eulervm}
\usefonttheme[onlymath]{serif}

\begin{document}

\begin{frame}
\frametitle{Error Here}
$a^T$ %the superscript T is rendered incorrectly in TeXstudio
\end{frame}

\end{document}

**Comment by sunderme** [comment]
could you try the manually build texstudio: https://bintray.com/sunderme/texstudio/download_file?file_path=texstudio.zip

**Comment by fjhickernell** [comment]
What do I need to do after I download the file?

Best regards,
Fred


Fred J. Hickernell
Director, Center for Interdisciplinary Scientific Computation (CISC)
Professor, Department of Applied Mathematics
Illinois Institute of Technology
Pritzker Science Ctr Rm 106, 3105 S Dearborn St, Chicago, IL 60616
hickernell@iit.edu <mailto:hickernell@iit.edu>, www.iit.edu/~hickernell <http://www.iit.edu/~hickernell>
Office: +1 312 567 8983   Cell: +1 630 696 8124   Skype: fjhickernell

**Comment by sunderme** [comment]
unzip the file and start texstudio from that file

**Comment by fjhickernell** [comment]
Tried that and it said that it would not open.  (I am using Mac.)  Tried control-click and then open, and it would not either.  The error message is “The application texstudio can’t be opened."

Thanks,
Fred


Fred J. Hickernell
Director, Center for Interdisciplinary Scientific Computation (CISC)
Professor, Department of Applied Mathematics
Illinois Institute of Technology
Pritzker Science Ctr Rm 106, 3105 S Dearborn St, Chicago, IL 60616
hickernell@iit.edu <mailto:hickernell@iit.edu>, www.iit.edu/~hickernell <http://www.iit.edu/~hickernell>
Office: +1 312 567 8983   Cell: +1 630 696 8124   Skype: fjhickernell

**Comment by sunderme** [comment]
I can't see a fault even in a freah install in a VM.

**Comment by fjhickernell** [comment]
I am glad that it works for you, but the issue has never been resolved for me, even though I tried what you suggested.  The fonts displayed fine in Adobe Reader or Preview, but not in TeXStudio.  This only happened after the last upgrade.

Best regards,
Fred


Fred J. Hickernell
Director, Center for Interdisciplinary Scientific Computation (CISC)
Professor, Department of Applied Mathematics
Illinois Institute of Technology
Pritzker Science Ctr Rm 106, 3105 S Dearborn St, Chicago, IL 60616
hickernell@iit.edu <mailto:hickernell@iit.edu>, www.iit.edu/~hickernell <http://www.iit.edu/~hickernell>
Office: +1 312 567 8983   Cell/WhatsApp: +1 630 696 8124   Skype/WeChat: fjhickernell

**Comment by sunderme** [comment]
I can't fix issues which are not present here.
Unless there is no further clue on what goes wrong on your system which does not on mine, I don't see a way to go on...

**Comment by sunderme** [comment]
the config sits in ~/.config/texstudio/texstudio.ini . It can be removed/renamed and txs generates a new one with default values.

**Comment by fjhickernell** [comment]
Thank you.  Will try when I return from travels.  Thanks for the suggestion.  Please elaborate on “You might provide the example pdf just to check that it contains all the fonts as it should.”  Provide to whom or how should I check whether it contains fonts?

Best regards,
Fred


Fred J. Hickernell
Director, Center for Interdisciplinary Scientific Computation (CISC)
Professor, Department of Applied Mathematics
Illinois Institute of Technology
Pritzker Science Ctr Rm 106, 3105 S Dearborn St, Chicago, IL 60616
hickernell@iit.edu <mailto:hickernell@iit.edu>, www.iit.edu/~hickernell <http://www.iit.edu/~hickernell>
Office: +1 312 567 8983   Cell/WhatsApp: +1 630 696 8124   Skype/WeChat: fjhickernell

**Comment by fjhickernell** [comment]
Thanks.

Attached is my problem file.  When viewed with Mac Preview or Acrobat, no problem.  

The windowed pdf viewer shows two fonts:

EWAYPO+TeXGyreHeros-Regular
TCSRJS+TeXGyrePagellaX-Italic

In my Preferences/Build/Meta Commands I have (same as original)

Default Viewer txs:///view-pdf
PDF Viewer txs:///view-pdf-internal —embedded

Best regards,
Fred


Fred J. Hickernell
Director, Center for Interdisciplinary Scientific Computation (CISC)
Professor, Department of Applied Mathematics
Illinois Institute of Technology
Pritzker Science Ctr Rm 106, 3105 S Dearborn St, Chicago, IL 60616
hickernell@iit.edu <mailto:hickernell@iit.edu>, www.iit.edu/~hickernell <http://www.iit.edu/~hickernell>
Office: +1 312 567 8983   Cell/WhatsApp: +1 630 696 8124   Skype/WeChat: fjhickernell

**Comment by sunderme** [comment]
the file seems not to be accessible.
But the fonts seem to be embedded, so I don't see why the pdf viewer should fail.
So, just to be on the safe side, please attach/upload the pdf **and** a screenshot what it looks like on your computer.

**Comment by sunderme** [comment]
can you try https://bintray.com/sunderme/texstudio/download_file?file_path=texstudio-osx-2.12.9-201805101303-git_cb105fb.dmg
At least here, it resolves the issue.

**Comment by fjhickernell** [comment]
YES!  You did it.  Thank you.

Is it safe to use this new version?

Best regards,
Fred


Fred J. Hickernell
Director, Center for Interdisciplinary Scientific Computation (CISC)
Professor, Department of Applied Mathematics
Illinois Institute of Technology
Pritzker Science Ctr Rm 106, 3105 S Dearborn St, Chicago, IL 60616
hickernell@iit.edu <mailto:hickernell@iit.edu>, www.iit.edu/~hickernell <http://www.iit.edu/~hickernell>
Office: +1 312 567 8983   Cell/WhatsApp: +1 630 696 8124   Skype/WeChat: fjhickernell

**Comment by sunderme** [comment]
it is the current development version, but we have only fixed bugs, hence yes, it is safe.
