### ISSUE TITLE
Texstudio crashing computer and overwriting blank text file

### ISSUE THREAD

**Issue by lifeishard** [texstudio-org/texstudio#970]
Texstudio crashing leading to computer freezing and overwriting the tex file with blank characters. I have always used the latest texstudio release and observed this bug more than 10 times.

The crashes often happen when I click the green compile icon. Out of the past 6 month, probably 7 crashes occurred on consecutive days 5 months ago, 1 crash occurred 1 month ago, and 2 crashes happened today. Every time these crashes happen the computer freezes and the .tex file I'm editing is overwritten by a file of the same size containing only the NUL character. I have not found any other patterns yet.

I don't think this bug has been reported on GitHub before but I found several mentions of this online, in addition to it happening to me 10+ times when I was writing my thesis. I think this is a very dangerous bug for many, I'm only lucky cause my tex files are auto-saved by Onedrive and I recover old versions.

https://superuser.com/questions/1263721/how-to-recover-contents-of-tex-file-from-auxiliary-files
https://tex.stackexchange.com/questions/335058/windows-crashed-tex-file-empty-but-i-can-select-empty-lines
https://tex.stackexchange.com/questions/188079/texstudio-autosave-recovery-question

### Environment
- TeXstudio: 2.12.16 - 2.12.22
- Qt:  5.12.1, compiled with Qt 5.12.1 R 
- OS:  Windows10 ... 
- TeX distribution: miktex 

### Expected behavior
Texstudio not crashing ideally.
### Actual behavior
Texstudio crashing leading to computer freezing and overwriting the tex file with blank characters.

### How to reproduce

 I'm not sure how to recreate it.

**Comment by sunderme** [comment]
are you sure that you are not having a one drive issue ?
When compiling, txs does not touch the file. miktex is doing it, using pdflatex (or whatever engine you are using)

**Comment by lifeishard** [comment]
I don't think this is a Onedrive issue since the instances of this issue reported by the links I gave online don't use Onedrive. The file that gets overwritten is full of the NUL character and the new file has the same size as the original file, this seems unlikely to be Onedrive's behaviour. If this kind of massive bug (i.e., overwriting the file with NUL characters) exist in Onedrive, it would definitely have been fixed already.

Do you think miktex is overwriting the tex file? I read somewhere about backtrace.txt for debugging texstudio, do you think it would help?

**Comment by sunderme** [comment]
possibly, but a reproducible test case would be better.

**Comment by aubreyz** [comment]
My gut feel is that this probably **is** a Onedrive issue. Onedrive (and Dropbox often do overwrite files with old versions, and there are persisting complaints about this happening. I have certainly experienced this with Dropbox, and one of your links does point to a Dropbox issue. It especially happens to locked files. A bit of googling will show that it is well known and is not "fixed already".

**Comment by sunderme** [comment]
insufficient info
