### ISSUE TITLE
Lag when saving large file

### ISSUE THREAD

**Issue by ondrejtichacek** [texstudio-org/texstudio#971]
### Issue
I work with a fairly large tex file, about 20k lines and 2.5 MB. This is the main body of a book I'm working on (about 500 pages, nothing crazy).

**When I save the file (using a shortcut or the save button), texstudio becomes unresponsive for about 2 seconds.**

I understand, it might not be possible/desirable to let the user edit the file while it's being saved, but I would like to be able to scroll, switch tabs, hit the compile button, etc.

### Proposed soluton

I assume this is not a bug, but rather due to the implementation of texstudio - let me know if I'm wrong.

Without knowing the implementation of texstudio I think there might be a rather simple fix - an assynchronous save thread. Some actions would have to wait for all save threads to be done (e.g. compiling). But then again I might be wrong, and the solution might be much more complicated. Anyway, this would be a nice feature.

### Some final notes:
 * Yes I know I could split the file into parts - but this brings other issues with texstudio (e.g. the convenience of search&replace) and other programs I use.
 * I have a fairly powerful PC with a new SSD, so the I/O speeds should not be bad.

### Environment
- TeXstudio: TeXstudio 2.12.22
- Qt: 5.14.1, compiled with Qt 5.14.0 R
- OS: Arch Linux
- TeX distribution: texlive

**Comment by sunderme** [comment]
works fine on linux (ubuntu). Well below a second saving time.
do you use a synced folder, i.e. dropbox etc ?
Apart from that, you are using arch linux. Because of a number of arch only bugs, no support for bugs on arch linux.

**Comment by sunderme** [comment]
and no, there are no plans for async write, especially as I don't see the issue.

**Comment by ondrejtichacek** [comment]
I use a synced folder (syncthing), but the save files are the same even when I use a different location. Just now, I tried saving into `/tmp` (which is in the RAM) with no improvement.

I will try if this issue can be reproduced on a Ubuntu computer I have access to.
