### ISSUE TITLE
No keyboard shortcut for "go to PDF" possible

### ISSUE THREAD

**Issue by kaymes** [texstudio-org/texstudio#973]
### Environment
- TeXstudio: 2.12.22
- Qt: 5.12.4, compiled with Qt 5.12.4 R
- OS: Ubuntu 19.10
- TeX distribution: texlive

### Expected behavior
In the editor the context menu offers a "go to PDF" command. I attempted to set a keyboard shortcut for it in configure texstudio -> shortcuts. There should be an entry "go to PDF" to set such a shortcut.

### Actual behavior
There was no option to set a shortcut for "go to PDF"

**Comment by sunderme** [comment]
The shortcut is F7/view. It automatically triggers a forward sync.
