### ISSUE TITLE
Unicode (locale) flags in regular expressions search [Feature request]

### ISSUE THREAD

**Issue by ondrejtichacek** [texstudio-org/texstudio#974]
By default, the regex expression `\w` matches the charactes in `[a-zA-Z0-9_]`. This is useful for english, not so much for other languages. Many regex engines therefore somehow implement `locale` and `unicode` flags - when used `\w` matches also non-ascii leters.

It would be great if the search & replace box in texstudio allowed to use such flags.

Unicode flag would probably be easier to implement. The locale could be read from a magic comment.

### Environment
- TeXstudio: TeXstudio 2.12.22
- Qt: 5.14.1, compiled with Qt 5.14.0 R
- OS: Arch Linux
- TeX distribution: texlive

**Comment by sunderme** [comment]
changed to match unicode

**Comment by muzimuzhi** [comment]
(related commit https://github.com/texstudio-org/texstudio/commit/f8d003f899e19be0975977e5d163c33f3e35fcfa)
