### ISSUE TITLE
FR: have text cursor jump to beginnings and ends of words (standard behaviour)

### ISSUE THREAD

**Issue by scytho** [texstudio-org/texstudio#975]
### Environment
- TeXstudio: 2.12.22
- Qt: 5.5.1
- OS: Linux
- TeX distribution: TeX Live

### Expected behavior
When pressing Ctrl+left while the text cursor is somewhere in the text/code, the cursor should jump to the next beginning of a word, i.e. be placed left of the first letter.

When pressing Ctrl+right it should be placed right to the last letter of a word.

### Actual behavior
The cursor is always being placed left to the first letter of a word, no matter if you press Ctrl+left or Ctrl+right.

### How to reproduce
In the config of TeXstudio setup the shortcuts for *move cursor to the left/right (1 word)* to be Ctrl+left/right, then write some words and press Ctrl+left/right.

### Feature request
The behaviour described above clearly isn’t a bug. I would like to have the option to have TeXstudio behave the same way as (most) text editors and as standard text fields in most GUIs (see expected behaviour).

**Comment by sunderme** [comment]
qt creator, kate behaves like txs
gedit, Visual Code Studio behave like it is described here, so no way a "standard" behaviour.
If some one wants to add that particular cursor movement, PR welcome (as non default)

**Comment by scytho** [comment]
Interessting, I didn’t know that. I thought it was more like an OS specific standard. If I knew how to add that feature, I would do it. Thanks, anyway.
