### ISSUE TITLE
Go to source not working with non-English folder name

### ISSUE THREAD

**Issue by SungwooPark1** [texstudio-org/texstudio#983]
### Environment
- TeXstudio:  2.12.22
- Qt:  5.12.1
- OS:  Win 10
- TeX distribution:  texlive

### Expected behavior
I would like to use 'Go to source' command with any folder names.
If unavailable, please introduce a proper folder naming rule.

### Actual behavior
Go to source does not work when non-English words are in folders.

### How to reproduce
Put Korean words in a folder or any subfolders.
Compile and use the 'Go to source' command.
Confirm that 'Go to source' doesn't work.

**Comment by timhoffm** [comment]
Synctex does not support Unicode. We recommend to use ASCII characters only.

See https://github.com/jlaurens/synctex/issues/31.
