### ISSUE TITLE
autoscrolling when selecting beyond viewport is broken (scrolls only on mouse move)

### ISSUE THREAD

**Issue by axkibe** [texstudio-org/texstudio#986]
### Environment
- TeXstudio: Head
- Qt: doesn't matter here
- OS: debian linux
- TeX distribution:doesn't matter here

### Expected behavior

Keep scrolling smoothing when selecting beyond the view port

### Actual behavior

Scrolls only when moving the mouse.

### How to reproduce

Select with the mouse, drag beyond the viewport

### Suggested Fix:

See Pull Request #985

It isn't perfect as I didn't want to change too much how qcodeeditor works (as scrolling speed is not determined linearly from the distance from the edge of the view, but speeds up in integer steps if it scrolls by 1,2,3 or so extra lines for which timer tick). So it's more an hack on the existing code, instead of a redesign. Otherwise it looks fine to me.

**Comment by sunderme** [comment]
you fixed it
