### ISSUE TITLE
How to tell tex studio to reload the file from disk?

### ISSUE THREAD

**Issue by nasser1** [texstudio-org/texstudio#99]
### Environment
- TeXstudio:  TeXstudio 2.12.8 (hg 2.12.8-1-g68cd350)
- Qt:  Using Qt Version 5.8.0, compiled with Qt 5.8.0 R
- OS:  windows 7, home edition
- TeX distribution:  miktex latest.

### Expected behavior

Read correct file from disk

### Actual behavior

does not read correct file from disk

### How to reproduce

I had this problem for long time. I posted question about it here 

https://tex.stackexchange.com/questions/366717/how-to-tell-texstudio-to-always-read-latest-tex-file-from-disk

I keep losing my edits because TX does NOT read the latest file from disk when I change the file from outside TX.  And I do not know how to tell TX to re-read the file from disk.
Is there a way to tell TX to re-load the latex file I have open inside it, again from disk?

This is what happens again. I use another editor to edit Latex. I use scientific word (SW). Then I save the file from SW. I  switch to TX window to compile the file so I can see the PDE. 

I only use SW to do edits. This is what happens. When I switch to TX to compile the file, I notice it is still using the old version of the latex file. Not including the edits I just made in SW and saved them. 

It did not detect the file has changed on disk and did not reload it automatically.   Sometimes it does reload the file but sometimes it does not.

Not only this. It actually overwrites the file on disk with this old copy. So when I go back to scientific word editor which is still open in another window, SW tells me the file was changed by another app (which is TX in this case) and if I want to reload it. ofcourse I say NO! This is even though I did not make any changes to the file inside TX at this time. Just switching to TX window causes this to happen.

Not only this. I close scientific word, and also close TX. Then open TX, and it is still loading an old version of the file on disk.  This is when I lose the changes I made.

I have no idea where it is loading the old file from. It must have its own cache where is keeps old copies of files??

Is there a way to tell TX to reload the file from disk? I will not use TX any more. I just lost one hr of edits I made because TX used an old cached copy of the latex file I was editing and overwrote my file with the old copy.

--Nasser

**Comment by sunderme** [comment]
file/fifix/revert to saved ...
