### ISSUE TITLE
texstudio's QFileDialog doesn't use native dialog albeit configured so

### ISSUE THREAD

**Issue by axkibe** [texstudio-org/texstudio#990]
Okay the other thing, I got one machine where TeXStudio File dialogs use Qt's fallback, instead of the native GTK ones. (The actual complaint I got is that it doesn't remember the dialog size and defaults to quite tiny, but as I figured on my machine I don't have that, since I get the gnome native dialogs)

So I'm really a bit stumped what the issue might be, it's basically the same setup.

To be honest, I wouldn't be surprised if this is way more a Qt issue than a TeXStudio, but for this I currently have no idea how to go from here. However, I checked a few applications, it's only TeXStudio where there is a difference (some use GTK natives, some use Qt's, but only TeXStudio it is different between both machines.

The only other hint I have, I get this on the stdout on the machine that comes up with Qt's Fallback dialogs: 

```
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
```
but not on my notebook, where I get the GTK native dialog.

can some other installed package cause this change in behavior? (the installed package list is not identical) Any hints/ideas what to look at are welcome.

### Environment (for both machines)
- TeXstudio: TeXstudio 3.00.00 (git 3.0.0alpha2-14-gba5d5a7f) (HEAD in time of writing)
- Qt: Using Qt Version 5.11.3, compiled with Qt 5.11.3 R
- OS: debian buster
- TeX distribution: texlive

### Expected behavior

get GTK File dialog

### Actual behavior

getting Qt's fallback file Dialog (albeit use native is configured)

### How to reproduce

I have not idea! :(  (other than starting TeXstudio on the machine it doesn't work on .../)

**Comment by benibela** [comment]
Do you have enabled "Use system file dialog" on the first config page?

**Comment by axkibe** [comment]
Yes

**Comment by axkibe** [comment]
Okay, not a TexStudio issue.Sorry for noise.

This was caused by having installing qt5ct installed, where debian auto sets the theme to qt5ct in `/etc/X11/Xsession.d/99qt5ct` and qt5ct default theme has "default" as "standard dialogs" set, which defaults to Qt's fallback, so either deinstalling qt5ct or setting it to GTK2 in qt5ct-setings fixes this.
