### ISSUE TITLE
No error when editing system files without admin rights

### ISSUE THREAD

**Issue by d-simple** [texstudio-org/texstudio#991]
### Environment
TeXstudio 2.12.22 (git 2.12.22)
Using Qt Version 5.12.1, compiled with Qt 5.12.1 R
Windows 10
TeX distribution: Miktex 2.9.7347

### Expected behavior
When saving changes to packages in Program Files/Miktex/** (most probably, any admin-protected files), without admin rights, access error dialog should display (I mean, why not?).

### Actual behavior
The studio quietly saves the file and displays it as if some changes were made, confusing the user. In actuality, the edited file is unchanged.
https://tex.stackexchange.com/questions/13178/latex-doesnt-pick-up-changes-to-style-file/13239

### How to reproduce
Building the snippet below in non-admin TexStudio
```
\documentclass{article}
\newcommand{\Bbbk}{\relax}
usepackage{amssymb}
begin{document}
end{document}
```
should raise an error
![image](https://user-images.githubusercontent.com/29694205/77244767-0549d980-6c54-11ea-9e87-b507890e7b96.png)
clicking on which, 

> amssymb.sty

file can be opened. Commenting the line

> \DeclareMathSymbol{\Bbbk} {\mathord}{AMSb}{"7C}

and saving the file should fix the issue and let the snippet compile. But it doesn't, and on consequent builds the message is shown again. 
           
If same is done in TexStudio, running with admin rights, the "fix" is done successfuly and the message doesn't appear anymore.

**Comment by muzimuzhi** [comment]
Using texstudio 2.12.22 on macOS, I get "Could not get write permission"
![image](https://user-images.githubusercontent.com/6376638/77245245-172d7b80-6c58-11ea-9b31-c7d1e9066923.png)

Not sure if this is an os specific problem.

**Comment by sunderme** [comment]
write permission detection works on linux as well

**Comment by sunderme** [comment]
not reproducible
