### ISSUE TITLE
How to add a splitindex command to TXS?

### ISSUE THREAD

**Issue by bernhard-kleine** [texstudio-org/texstudio#996]
### Environment
TeXstudio 2.12.22 (git 2.12.22)
Using Qt Version 5.12.1, compiled with Qt 5.12.1 R
Win10,
texlive
### Expected behavior
I cannot add a command to the commands which should be possible

**Comment by sunderme** [comment]
https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions#why-does-texstudio-mark-a-command-as-unrecognized

basically you need to add commands to a text file with cwl ending and put it in %APPDATA%\texstudio\completion\...
