### ISSUE TITLE
splitidx commands not supported

### ISSUE THREAD

**Issue by bernhard-kleine** [texstudio-org/texstudio#997]
### Environment
TeXstudio 2.12.22 (git 2.12.22)
Using Qt Version 5.12.1, compiled with Qt 5.12.1 R
Win10,
texlive
### Actual behavior
The splitidx.cwl is clicked, however, the command \scindex[]{} is not know and if you do not take care is replaced by \setindexpreamble which is useless.

**Comment by sunderme** [comment]
also refering to https://github.com/texstudio-org/texstudio/wiki/Frequently-Asked-Questions#why-does-texstudio-mark-a-command-as-unrecognized
